### ISSUE TITLE
browsertime forward to a error page

### ISSUE THREAD

**Issue by kakazuo** [sitespeedio/sitespeed.io#1002]
I am using sitespeed.io to test my website, it's installed on a ubuntu 14.04 LTS vm, but everytime I run test command, it always forwards to http://www.mozilla.org/en-US/firefox/new, for example, I run following command:
`sitespeed.io -u http://www.google.com -d 0 -b firefox`

**Comment by soulgalore** [comment]
Lets keep this open but track it in https://github.com/tobli/browsertime/issues/153

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
