### ISSUE TITLE
--seleniumServer doesn't work

### ISSUE THREAD

**Issue by guityd** [sitespeedio/sitespeed.io#1013]
Hello,

I try to use the lastest version of sitespeed.io with using a seleniumServer but it doesn't work:
./sitespeed.js -b firefox --seleniumServer http://127.0.0.1:4444/wd/hub --debug http://www.google.fr
[2016-06-20 23:00:00] http://www.google.fr generated the following error in Browsertime BrowserError: Timed out waiting for the WebDriver server at http://127.0.0.1:59132/hub
It doesn't take the port option. 
The port change each time

Regards,

**Comment by soulgalore** [comment]
Hi @guityd and thanks for the error report, exact which version of sitespeed.io are you using? And what OS? 

Thanks
Peter

**Comment by guityd** [comment]
Hello,
We use a clone of the git 4.0 (alpha) and Debian 8.5
Thks.

**Comment by soulgalore** [comment]
Hi @guityd 
ok, I think it could be that we still link to the old documentation. You should try:
<pre>bin/sitespeed.js --help</pre>

Then the parameter is <code>--browsertime.seleniumServer</code> but are you sure you need to use it? By default Browsertime will use the nodejs version, with no config needed.

**Comment by guityd** [comment]
Hi,
Ok thks. 
I have the same problem with or without selenium options
 ./sitespeed.js -b firefox --browsertime.seleniumServer http://127.0.0.1:4444/wd/hub --debug http://www.google.fr
[2016-06-21 10:58:01] Versions OS: linux 3.16.0-4-amd64 sitespeed.io: 4.0.0-alpha.4 browsertime: 1.0.0-alpha.20 coach: 0.23.0
[2016-06-21 10:58:01] {
  "uuid": "b1682713-df11-4596-a0f7-cc1a3945d3d5",
  "type": "url",
  "timestamp": "2016-06-21T10:58:01+02:00",
  "source": "url-reader",
  "data": "{...}",
  "url": "http://www.google.fr"
}
[2016-06-21 10:58:01] Starting firefox for analysing http://www.google.fr 3 time(s)
[2016-06-21 10:58:01] Testing url http://www.google.fr run 1
[2016-06-21 10:58:47] http://www.google.fr generated the following error in Browsertime BrowserError: Timed out waiting for the WebDriver server at http://127.0.0.1:51546/hub
    at BrowsertimeError (/root/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:10)

**Comment by soulgalore** [comment]
Ok are you using Firefox 47.0? Long story short: Firefox 47.0 broke compatibility with Selenium and hopefully will be fixed in 47.0.1. See See https://github.com/sitespeedio/sitespeed.io/issues/993

**Comment by guityd** [comment]
dpkg -l |grep firefox
ii  firefox-esr                          45.2.0esr-1~deb8u1                amd64        Mozilla Firefox web browser - Extended Support Release (ESR)
ii  firefox-esr-l10n-fr                  45.2.0esr-1~deb8u1                all          French language package for Firefox ESR

**Comment by soulgalore** [comment]
And you get the exact same error without setting <code>--browsertime.seleniumServer</code> "Timed out waiting for the WebDriver server at http://127.0.0.1XXXX" ?

**Comment by guityd** [comment]
Yes with or without i have the same error.

**Comment by guityd** [comment]
Hi,
Any idea ? Do you want some information ? 
Thks.

**Comment by soulgalore** [comment]
I think I need to spin up an instance with Debian to be able to reproduce. Have you tried the 3.x version or you can try the new version inside Docker https://hub.docker.com/r/sitespeedio/sitespeed.io/ and get the tag 4.0-alpha:
<code>docker pull sitespeedio/sitespeed.io:4.0-alpha</code>

Best
Peter

**Comment by softwareklinic** [comment]
Launches chrome on mac... but doesnt launch firefox --- i have 47.0.1

**Comment by beenanner** [comment]
I think the latest release "alpha-5" of sitespeedio with "alpha-21" of browsertime should have fixed this. I can test on my Mac tomorrow @softwareklinic

**Comment by softwareklinic** [comment]
ty, i will check it out as well...

**Comment by softwareklinic** [comment]
yes its fixed with alpha-5  - ty

**Comment by soulgalore** [comment]
@softwareklinic yes Firefoxdriver was broken in 47.0, 47.0.1 + a new Selenium fixed the issue (https://github.com/sitespeedio/sitespeed.io/issues/993).

**Comment by guityd** [comment]
Hi,
I try with alpha-5 and i always have the same problem with chrome
[2016-07-01 12:49:30] Browser failed to start in time, trying one more time. with "internal selenium" and without.

**Comment by guityd** [comment]
with firefow an external selenium server:
[2016-07-01 12:53:40] http://www.google.fr generated the following error in Browsertime BrowserError: Timed out waiting for the WebDriver server at http://127.0.0.1:32923/hub
It always change the port

**Comment by soulgalore** [comment]
Hey @guityd I have'n't had time to test on other OS than OS X & Ubuntu yet. What seems really strange is that you get different ports when you define the selenium server. To set the selenium server (if you have your own running) should be: <code>--browsertime.selenium.url</code>

Did the 3.x version work, did it work in Docker (want to see if we introduced the error or if it's always been there).

**Comment by softwareklinic** [comment]
3.x works

**Comment by softwareklinic** [comment]
so, i will need selenium server with xvfb + FF + Chrome- rght?

**Comment by soulgalore** [comment]
@softwareklinic so you have the same problem as @guityd on Debian 8.5?

**Comment by softwareklinic** [comment]
2 issues
1. When run docker on MAC --- times out while locating element --- basically invalid locator error
2. When run docker on ec2 Amazon Linux - it doesnt find the preloginscript.js via the -v mapping

**Comment by soulgalore** [comment]
yes but @softwareklinic you hijacked @guityd issue :) If it's not to much work, create one new issue with the two problems you have. For the first issue, if you could include your script that would be great so I can reproduce. Thanks!

**Comment by softwareklinic** [comment]
Both the issues are listed here with script -- https://github.com/sitespeedio/sitespeed.io/issues/1039

**Comment by guityd** [comment]
Hey, Yes it works with version 3.X and it works with docker too

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
