### ISSUE TITLE
one error with sitespeed docker container

### ISSUE THREAD

**Issue by kakazuo** [sitespeedio/sitespeed.io#1018]
I encountered following error while using sitespeed docker container, my os version is :  redhat 7, btw, for ubuntu env, it does not have any problem.
error log is:

`[root@bluemix-performance-redhat ~]# docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://dev-console.stage1.ng.bluemix.net/maintenance -d 0 -b chrome --screenshot
Wed Jun 22 02:57:29 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 49.0.2623.75
Mozilla Firefox 45.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.10.0-327.18.2.el7.x86_64', Node.js: 'v4.3.2', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'
info: Will analyze 1 page
info: Running YSlow for https://dev-console.stage1.ng.bluemix.net/maintenance [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for https://dev-console.stage1.ng.bluemix.net/maintenance chrome
info: Running browsertime for chrome https://dev-console.stage1.ng.bluemix.net/maintenance
Fetching https://dev-console.stage1.ng.bluemix.net/maintenance (1 of 3)
{ [UnknownError: chrome not reachable
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64)]
  code: 100,
  state: 'unknown error',
  message: 'chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64)',
  name: 'UnknownError',
  stack: 'UnknownError: chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64)\n    at new bot.Error (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24\n    at promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)\n    at goog.defineClass.notify (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)\n    at promise.Promise.notify_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)\n    at goog.async.run.processWorkQueue (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)\n    at process._tickCallback (node.js:364:9)\nFrom: Task: WebDriver.createSession()\n    at Function.webdriver.WebDriver.acquireSession_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)\n    at Function.webdriver.WebDriver.createSession (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)\n    at new Driver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:810:36)\n    at Builder.build (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:454:14)\n    at Object.module.exports.getDriver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:41:49)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:107:64\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:726:13\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:52:16\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:269:32\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:44:16' }
error: Error running browsertime: { [UnknownError: chrome not reachable
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64)]
  code: 100,
  state: 'unknown error',
  message: 'chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64)',
  name: 'UnknownError',
  stack: 'UnknownError: chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.18.2.el7.x86_64 x86_64)\n    at new bot.Error (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24\n    at promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)\n    at goog.defineClass.notify (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)\n    at promise.Promise.notify_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)\n    at goog.async.run.processWorkQueue (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)\n    at process._tickCallback (node.js:364:9)\nFrom: Task: WebDriver.createSession()\n    at Function.webdriver.WebDriver.acquireSession_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)\n    at Function.webdriver.WebDriver.createSession (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)\n    at new Driver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:810:36)\n    at Builder.build (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:454:14)\n    at Object.module.exports.getDriver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:41:49)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:107:64\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:726:13\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:52:16\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:269:32\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:44:16' }
Stopping proxy
info: Taking screenshot for https://dev-console.stage1.ng.bluemix.net/maintenance
error: Could not generate HAR for https://dev-console.stage1.ng.bluemix.net/maintenance { [Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-22-02-57-31/data/har/chrome/s-dev-console_stage1_ng_bluemix_net-maintenance.har']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-22-02-57-31/data/har/chrome/s-dev-console_stage1_ng_bluemix_net-maintenance.har' }
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file errors.html
info: Wrote file domains.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file screenshots.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote file s-dev-console_stage1_ng_bluemix_net-maintenance.html
info: Wrote results to /sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-22-02-57-31
info: The analyze took a minute (72 seconds)
Killed the Chromedriver instance because Chrome/driver was hanging.`

**Comment by soulgalore** [comment]
Hi @kakazuo checkout this thread https://github.com/sitespeedio/sitespeed.io-docker/issues/5#issuecomment-171543395 where @abhagupta tried out the -<code>--no-sandbox</code> hope that can help you too!

**Comment by kakazuo** [comment]
@soulgalore thanks for your response,  I will try,  BTW, want to ask you another question, how can I check if the browser is opened in container while running test using container?

**Comment by abhagupta** [comment]
@kakazuo , Since docker is running browsers in XVFB, you can only see the processes. You will need to get inside the running docker container by running command
 `docker exec <docker container pid> bash`.  This should open up the docker shell of the container. Once in there, you should be able to do a `ps aux` or `ps -a` to see the processes running. If chrome/firefox running, you should be able to see them in the list.

**Comment by kakazuo** [comment]
@abhagupta thanks, but how do you ensure the browser open a right page? for example, you want to access to page A, but the server is down for maintenance, so it redirects it to page B.

Additionally,  when I ran your docker container on Ubuntu(14.04 LTS) vm with chrome browser, it shows following error, cloud u help take a look?
`root@bluemix-ui-performance-3:~# docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://dev-console.stage1.ng.bluemix.net/maintenance -d 0 -b chrome
Wed Jun 22 14:08:43 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 49.0.2623.75
Mozilla Firefox 45.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.13.0-86-generic', Node.js: 'v4.3.2', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'
info: Will analyze 1 page
info: Running YSlow for https://dev-console.stage1.ng.bluemix.net/maintenance [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for https://dev-console.stage1.ng.bluemix.net/maintenance chrome
info: Running browsertime for chrome https://dev-console.stage1.ng.bluemix.net/maintenance
Fetching https://dev-console.stage1.ng.bluemix.net/maintenance (1 of 3)
{ [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
error: Error running browsertime: { [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
Stopping proxy
error: Could not generate HAR for https://dev-console.stage1.ng.bluemix.net/maintenance { [Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-22-14-08-45/data/har/chrome/s-dev-console_stage1_ng_bluemix_net-maintenance.har']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-22-14-08-45/data/har/chrome/s-dev-console_stage1_ng_bluemix_net-maintenance.har' }
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file domains.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote file s-dev-console_stage1_ng_bluemix_net-maintenance.html
info: Wrote results to /sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-22-14-08-45
info: The analyze took a few seconds (11 seconds)`

**Comment by abhagupta** [comment]
Looking at the logs, it sounds like tests are not running at all. It's been a while, but here is what i did for troubleshooting.

 - Went inside the docker container and made sure all the processes are running . This should include a java process for selenium, chrome for sure. If you are seeing the `chrome --sandbox`, then you need to make sure you are sending the `no-sandbox` option as Peter mentioned.
- I wrote a tiny selenium script which would just open a browser and run a simple test. 
- I tailed the webserver logs (the one which is serving the site you are running the test on) to make sure that i get some readings on access logs when selenium opens that site. If you are able to see status 200 on access logs while running the test, that means chrome is opening and its able to access the site.
- You need to make sure that the test runs perfectly with non-docker version of sitespeed. Because that is your best way to isolate the problem.
- if the tests run fine in non-docker version and only gives a problem in docker version, there could be a chance that the particular distribution of your Ubuntu and XVFB in it is having issues.. This is a very hairy troubleshooting. If you do fall into this, it might be just a better idea to try with a different distribution (which is recommended by sitespeed).    
- From your logs, it looks like somethings are written in results/pages.html file.  Check for error logs in there. (might not be that helpful since it does not give you  details, but worth trying)

Good luck!

**Comment by kakazuo** [comment]
@abhagupta thanks for you analyze!!
for firefox browser, it works well, here is the command and log:
`docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://dev-console.stage1.ng.bluemix.net/maintenance -d 0 -b firefox`

`root@bluemix-ui-performance-4:~# docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://dev-console.stage1.ng.bluemix.net/maintenance -d 0 -b firefox
Thu Jun 23 02:39:28 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 49.0.2623.75
Mozilla Firefox 45.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.13.0-88-generic', Node.js: 'v4.3.2', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'
info: Will analyze 1 page
info: Running YSlow for https://dev-console.stage1.ng.bluemix.net/maintenance [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for https://dev-console.stage1.ng.bluemix.net/maintenance firefox
info: Running browsertime for firefox https://dev-console.stage1.ng.bluemix.net/maintenance
Fetching https://dev-console.stage1.ng.bluemix.net/maintenance (1 of 3)
Fetching https://dev-console.stage1.ng.bluemix.net/maintenance (2 of 3)
Fetching https://dev-console.stage1.ng.bluemix.net/maintenance (3 of 3)
Storing /sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-23-02-39-29/data/har/firefox/s-dev-console_stage1_ng_bluemix_net-maintenance.har
Storing /sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-23-02-39-29/data/browsertime/firefox/s-dev-console_stage1_ng_bluemix_net-maintenance-browsertime.json
Stopping proxy
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file domains.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote file s-dev-console_stage1_ng_bluemix_net-maintenance.html
info: Wrote file s-dev-console_stage1_ng_bluemix_net-maintenance-0.html
info: Wrote file s-dev-console_stage1_ng_bluemix_net-maintenance-1.html
info: Wrote file s-dev-console_stage1_ng_bluemix_net-maintenance-2.html
info: Wrote results to /sitespeed.io/sitespeed-result/dev-console.stage1.ng.bluemix.net/2016-06-23-02-39-29
info: The analyze took a few seconds (37 seconds)`

**Comment by kakazuo** [comment]
this is process in container while running test
![image](https://cloud.githubusercontent.com/assets/5010445/16290407/9d7d5508-392f-11e6-9514-78edbeb2fb3a.png)

**Comment by kakazuo** [comment]
seems chrome browser is not started

**Comment by abhagupta** [comment]
Can you paste the chrome command?  Also make sure that you have a JSON file containing
  ```
{
 "noSandbox": true
}
```
 which you mount to the docker container, so sitespeed can read it with `--btconfig` option. You need to make sure that the path of the file is correctly referenced to where you have mounted the file. 

I am not sure why you are not able to see the chrome process at all. Is it just shutting down right away?

**Comment by kakazuo** [comment]
here is the command
`docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://dev-console.stage1.ng.bluemix.net/maintenance -d 0 -b chrome --btConfig nosandbox.json`

**Comment by abhagupta** [comment]
Sorry... this totally fell off my radar. Are you still experiencing the issue with chrome?

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
