### ISSUE TITLE
About Browsertime - prescript

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1025]
Any example of how to use the --browsertime.prescript ---- ?

# Issue/Request

# Issue/Bug report

### Setup
**sitespeed.io version**:
**Operating system**:
**Browser version**:

### Steps to reproduce
 1.
 2.
 3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

# Request
We love requests! Let us know what you want sitespeed.io todo. Request is a perfect way to start your PR. Write what you think is needed and we can discuss how you or we could implement it. Lets start by first proposing your idea to other contributors, that way you can get feedback on the idea before taking time to write precious code.

**Comment by soulgalore** [comment]
You can checkout the login example script in Browsertime: https://github.com/tobli/browsertime/blob/1.0/test/prepostscripts/preLoginExample.js

And we have a super simple one that runs in Travis:
https://github.com/sitespeedio/sitespeed.io/blob/master/.travis.yml#L31

Best
Peter

**Comment by softwareklinic** [comment]
Just curious the site that we have - navigates the customer thru 3 different pages

1. Collects the username
2. collects the security answer
3. collects the password

how do we instrument this kind of flow?

Selenium builder is a great tool to generate the JSON which can be passed to some generic java code perform the actions captured in selenium builder firefox plugin... do we expect something similar in pipeline.?

**Comment by soulgalore** [comment]
Hey @softwareklinic that is cool. Can you export the result to Selenium NodeJS or is there another plugin that can do it? Then it would just be to add that could in the right place everything would work fine.

**Comment by softwareklinic** [comment]
Here is the link to SE Builder - http://www.sebuilder.com/  -its an OS project -- also attaching sample JSON generated by the SE Builder...

Also, there is another open source project known as Asqatasun -- for Accessibility testing--- this project is using -- SE Builder exported JSON scripts --- for running these flows in selenium... so, practically -- i record flows using se builder --- generate JSON feed to selenium and it just works... please check it out... 

{
  "type": "script",
  "seleniumVersion": "2",
  "formatVersion": 2,
  "steps": [
    {
      "type": "get",
      "url": "https://www.microsoft.com/en-us/"
    },
    {
      "type": "clickElement",
      "locator": {
        "type": "css selector",
        "value": "h4.feature-title"
      }
    },
    {
      "type": "setElementText",
      "locator": {
        "type": "id",
        "value": "email-signup-address"
      },
      "text": "xxxxxxxxxx@gmail.com"
    },
    {
      "type": "clickElement",
      "locator": {
        "type": "id",
        "value": "email-signup-button"
      }
    }
  ],
  "data": {
    "configs": {},
    "source": "none"
  },
  "inputs": [],
  "timeoutSeconds": 60
}

**Comment by softwareklinic** [comment]
I need some help... when i ran prescript using the local code based --- it worked fine --launched the browser and ran the scripted flow...

But, i got the docker container from hub.docker.com for 4.01 alpha -- and now I'm getting below error

looks like unable to locate the element....  here is the command i ran

docker run --privileged --rm -v /Users/FamilyMac/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io:4.0-alpha sitespeed.io http://www.xxxxxxxx.com  --graphiteHost 127.0.0.1 --preScript preloginscript.js  -b firefox -n 1

[2016-06-29 19:36:44] TypeError: Invalid locator
    at Object.check [as checkedLocator] (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/by.js:267:9)
    at Driver.findElement (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver.js:857:18)
    at /sitespeed.io/preloginscript.js:33:35
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
[2016-06-29 19:36:44] Render HTML for 1 page(s) 
[2016-06-29 19:36:44] Error TypeError: /usr/lib/node_modules/sitespeed.io/lib/plugins/html/templates/index.pug:46
    44|     .row
    45|       .one-third.column
  > 46|         +boxInfo('200 responses', pagexray.summary.responseCodes['200'])
    47|       .one-third.column
    48|         +boxInfo('301 responses', pagexray.summary.responseCodes['301'])
    49|       .one-third.column

**Comment by soulgalore** [comment]
Thanks for the report, let me try that out, haven't tested it with Docker yet, can do that tomorrow.

**Comment by softwareklinic** [comment]
Also, if someone can add sample code how to make webdriver wait until the element is loaded... would be great... since... im no JS expert.... :)
 I tried adding a sleep function in Javascript -- but still could not locate the element...
