### ISSUE TITLE
PreScript - Questions & Issues

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1033]
# Issue/Request - very critical 

I tried below and it worked very well... 

bin/sitespeed.js http://www.verizonwireless.com --preScript preloginscript.js --graphite.host 127.0.0.1 --graphite.namespace VZW

as far as running the script is concerned.. in the script i recorded 3 page navigation flow... as below 

Visit home page > enter username > submit > enter security answer on next page > submit > enter password > submit --- and it showed me in browser successfully logged in for each of 3 runs using sitespeed...

But, when i visit the HTML summary page---- it just shows 1 URL i.e. of the Home page... there is no record of other 2 urls that the selenium JS script navigated thru automation...

Below is my SCRIPT

'use strict';
let webdriver = require('selenium-webdriver');
let By = require('selenium-webdriver').By;
/*
  Here's an example of how you can use a preTask to login the user
  and then measure/get metrics from pages as an authenticated user
  */

  function sleep(delay) {
        var start = new Date().getTime();
        while (new Date().getTime() < start + delay);
      }

module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      // Go to Wikipedias login URL
      return driver.get('http://www.verizonwireless.com/')
        .then(() => {
          // You need to find the form, the login input fiels and the
          // password field. Just add you name and password and submit the form
          // For more docs, checkout the NodeJS Selenium version
          // http://selenium.googlecode.com/git/docs/api/javascript/index.html

          // before you start, make your username and password
          var userName = '9999999999';
          var sq = 'xxxxxxxxxxx';
          var password = 'xxxxxxxxxxxx';
          // var loginForm = driver.findElement(webdriver.By.tagName('form'));
          sleep(3000);

          // NAVIGATING TO HOME PAGE
          var loginInput = driver.findElement(By.id('IDToken1'));
          loginInput.click();
          loginInput.clear();
          loginInput.sendKeys(userName);
          //var passwordInput = driver.findElement(webdriver.By.id('wpPassword1'));
          //passwordInput.sendKeys(password);
          //loginForm.submit();

          driver.findElement(By.xpath("(//button[@type='submit'])[4]")).click();

          // NAVIGATING TO THE SECURITY QUESTION ANSWER PAGE
          var securequestion = driver.findElement(By.id('IDToken1'));
          securequestion.click();
          securequestion.clear();
          securequestion.sendKeys(sq);
		  driver.findElement(By.css("button.o-red-button")).click();	

		  // NAVIGATING TO THE PASSWORD PAGE
          var passwordinput = driver.findElement(webdriver.By.id('IDToken2'));
          passwordinput.click();
          passwordinput.clear();
          passwordinput.sendKeys(password);
          driver.findElement(By.css("button.o-red-button")).click();
          // NAVIGATES TO THE HOME PAGE - AS SIGNED IN
        });
    })
  }
};

# Issue/Bug report

the data is being reported to graphite -- checking if all 3 pages got submitted... or just the home page metrics... this is very critical...

### Setup
**sitespeed.io version**:
**Operating system**:
**Browser version**:

### Steps to reproduce
 1.
 2.
 3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

# Request
We love requests! Let us know what you want sitespeed.io todo. Request is a perfect way to start your PR. Write what you think is needed and we can discuss how you or we could implement it. Lets start by first proposing your idea to other contributors, that way you can get feedback on the idea before taking time to write precious code.

**Comment by softwareklinic** [comment]
Just verified that in graphite as well - i see only the Home page url... i dont see the other 2 urls that my selenium script navigated to.... thoughts???

**Comment by soulgalore** [comment]
We should document this, sorry it's unclear right now. It will only pick up the URL that you do in the test, not URLs you hit in preScript/postScript. The main idea has been to fix login + making it possible to test a "warm" cache, hitting one page first and then another one (not 100% this works in FF right now, been some bugs there).

If you want to test three different pages, you need to setup three different runs as it is right now. cc @tobli to check that I remember correct. We really need some docs on this.

Best
Peter

**Comment by softwareklinic** [comment]
Sorry - maybe i didn't understand it clearly from your input above ---- can i pass e.g. 3 urls... using the -f parameter in the text file e.g.

my typical flow is
Home page > security answer > password > sign-ed in home page > my account > etc...

Can i give these 3 urls in file using -f parameter???
1. Home page (where the JS script logs into the authenticated area of the website)
2. signed-in home page
3. my account

**Comment by softwareklinic** [comment]
I was able to use prescript --- for multiple signed-in/authentication backed urls.... will publish the command and instructions shortly,

**Comment by vernontab** [comment]
It would be wonderful if you have a command here! I'm currently trying to figure out how to pass preScript multiple times. This thread seemed to get close to the answer then...

**Comment by soulgalore** [comment]
Hey @vernontab I'm not 100% follow what you mean, could you please try to explain some more? You can ad multiple preScript by passing the parameter multiple times.

Best
Peter

**Comment by vernontab** [comment]
Hi @soulgalore. What I'm trying to do is get past a login screen but it doesn't do this for each run it works for the first but not the subsequent ones). How do I use preScript multiple times? Do you have an example I could take a look at?

**Comment by soulgalore** [comment]
Hi @vernontab ok, what do you mean by not work? :)

Checkout https://www.sitespeed.io/documentation/sitespeed.io/browsers/#how-does-it-work-behind-the-scene that's the flow. The prescript runs every time. Could it be some limit setup for site?

And here's how to debug (add logging etc): https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/#debuglog-from-your-script

Best
Peter
