### ISSUE TITLE
1st Party parameter - for multiple 1st party 

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1035]
# Issue/Request

We are using multiple domains to server our resources faster - -saying that -- we have 2 or more 1st party domains,,, now do we mark more than 1 domain as 1st party and rest as 3rd party.??

# Issue/Bug report

### Setup
**sitespeed.io version**:
**Operating system**:
**Browser version**:

### Steps to reproduce
 1.
 2.
 3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

# Request
We love requests! Let us know what you want sitespeed.io todo. Request is a perfect way to start your PR. Write what you think is needed and we can discuss how you or we could implement it. Lets start by first proposing your idea to other contributors, that way you can get feedback on the idea before taking time to write precious code.

**Comment by soulgalore** [comment]
The --firstParty parameter is a regex, so you can make it match the domains you want.

**Comment by softwareklinic** [comment]
Can it.take a comma separated tregex.list.since we.have completely.different domains for resources and html content.

Sent from my iPhone

On Jun 30, 2016, at 6:39 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


The --firstParty parameter is a regex, so you can make it match the domains you want.

**Comment by beenanner** [comment]
@softwareklinic sorry no plans to support multiple regex strings. You should be able to generate a single regex that matches each of the domains + subdomains with a little extra work.
```
^(https?:\/\/)?(subdomain\d+|www)\.(domain1|domain2).*\/?$
```

**Comment by softwareklinic** [comment]
Ty.makes.sense

Sent from my iPhone

On Jun 30, 2016, at 8:40 PM, Jonathan Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> sorry no plans to support multiple regex strings. You should be able to generate a single regex that matches each of the domains + subdomains with a little extra work.

^(https?:\/\/)?(subdomain\d+|www)\.(domain1|domain2).*\/?$

**Comment by softwareklinic** [comment]
Can i call this parameter multiple times --- for different domains... somehow above regex is not working for me....

**Comment by beenanner** [comment]
@softwareklinic it only supports one currently. you could try simplifying the regex to something like .*(domain1|domain2).*

**Comment by softwareklinic** [comment]
Sure - it.worked to some.extent but am.still trying.to verify if.it.has all my.1st party covered -.will ping.my.regex.in.few

Sent from my iPhone

On Aug 12, 2016, at 10:07 PM, Jonathan Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> it only supports one currently. you could try simplifying the regex to something like .(domain1|domain2).
