### ISSUE TITLE
Visual metrics - with 4.0.0.-alpha 5

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1036]
# Issue/Request

What is the site speed syntax to generate visual metrics?

**Comment by soulgalore** [comment]
You can check browsertime here: https://github.com/tobli/browsertime/blob/1.0/lib/support/cli.js

<code>--browsertime.experimental.video</code> should do the job. but it's still experimental and its easiest used with the Docker container to get the requirements for free for VisualMetrics (like FFMPeg etc).

**Comment by softwareklinic** [comment]
Ty - when.you have a.min I need help
With.the docker issue related to pre sample.js I can get you complete.error log

Sent from my iPhone

On Jul 7, 2016, at 4:23 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


You can check browsertime here: https://github.com/tobli/browsertime/blob/1.0/lib/support/cli.js

--browsertime.experimental.video should do the job. but it's still experimental and its easiest used with the Docker container to get the requirements for free for VisualMetrics (like FFMPeg etc).

**Comment by softwareklinic** [comment]
So - do i need to pull the image of sitespeedio/VisualMetrics --- and use it with sitespeedio/sitespeed.io???

If I can get some more details...

**Comment by soulgalore** [comment]
No it's included. --browsertime.experimental.video should do the job.

**Comment by softwareklinic** [comment]
Yes.it.worked .... But the summary html doesn't have the.link.to video right?

Sent from my iPhone

On Jul 17, 2016, at 3:01 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


No it's included. --browsertime.experimental.video should do the job.

**Comment by soulgalore** [comment]
yep there a lot that can be done there, if you have time send a PR with what's missing :)
