### ISSUE TITLE
Add to documentation - for how to test multiple URLS with 4.0

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1037]
# Issue/Request

# Documentation purpose

 sitespeed.io /Users/FamilyMac/Desktop/vzw.txt  --graphite.host 127.0.0.1 --graphite.namespace VZW  

there is no more -f or -u or --sites parameter... just pass the URL or the URL list in file as above and it will run just fine.

# Issue/Bug report

### Setup
**sitespeed.io version**:
**Operating system**:
**Browser version**:

### Steps to reproduce
 1.
 2.
 3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

# Request
We love requests! Let us know what you want sitespeed.io todo. Request is a perfect way to start your PR. Write what you think is needed and we can discuss how you or we could implement it. Lets start by first proposing your idea to other contributors, that way you can get feedback on the idea before taking time to write precious code.

**Comment by soulgalore** [comment]
added
