### ISSUE TITLE
The generated report showing 0 Pages analyzed 

### ISSUE THREAD

**Issue by mail2jomy** [sitespeedio/sitespeed.io#1047]
# Issue/Request

# Issue/Bug report

### Setup
**sitespeed.io version**: "version": "3.11.5",
**Operating system**: MAC OX X El Capitan
**Browser version**:Firefox

### Steps to reproduce
 1.installed npm, git and follow the instruction 
 2. run the command "sudo sitespeed.io -u http://www.cybercom.com -b firefox"
 3. The terminal window shows sucessfull completion of the crawl of 40 pages and result write out to the folder. 
4. Open the result html page and get the message. 0 pages analyzed for http://www.cybercom.com

### Expected behaviour
 data on report

### Actual behaviour
The page opened no data. None of hte pages have data in the report. 

# Request

**Comment by soulgalore** [comment]
Hi @mail2jomy 
and thanks for the report! Could you put the log in a gist so I can have a look?

Best
Peter

**Comment by mail2jomy** [comment]
thanks @soulgalore for the quick response. did you mean the terminal logs or something else?

here is the terminal output.

--------------------------------------------------------------------------------------------------------------

jose170903:**## **node_modules jjose$ sudo sitespeed.io -u http://www.cybercom.com -b firefox -m 10 -v****
info: OS: 'darwin 15.5.0', Node.js: 'v4.4.7', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.6.0_65', browsertime: '0.12.2'
info: Will crawl from start point http://www.cybercom.com with crawl depth 1
info: Will analyze 10 pages
info: Running YSlow for http://www.cybercom.com [phantomjs]
info: Running YSlow for http://www.cybercom.com/About-Cybercom/Contact/Denmark/ [phantomjs]
info: Running YSlow for http://www.cybercom.com/About-Cybercom/Events-and-seminars/ [phantomjs]
info: Running YSlow for http://www.cybercom.com/what-we-do/digitalisation/moverex/ [phantomjs]
info: Running YSlow for http://www.cybercom.com/Cases-and-clients/automower-connect/ [phantomjs]
verbose: Done processing url in yslow: http://www.cybercom.com/About-Cybercom/Events-and-seminars/
info: Running YSlow for http://www.cybercom.com/Cases-and-clients/a-portal-for-all-government-services/ [phantomjs]
verbose: Done processing url in yslow: http://www.cybercom.com/what-we-do/digitalisation/moverex/
info: Running YSlow for http://www.cybercom.com/About-Cybercom/Press-Media/ [phantomjs]
verbose: Done processing url in yslow: http://www.cybercom.com/Cases-and-clients/automower-connect/
info: Running YSlow for http://www.cybercom.com/About-Cybercom/Events-and-seminars/bluff-contest/ [phantomjs]
verbose: Done processing url in yslow: http://www.cybercom.com/About-Cybercom/Contact/Denmark/
info: Running YSlow for http://www.cybercom.com/About-Cybercom/Corporate-governance/ [phantomjs]
verbose: Done processing url in yslow: http://www.cybercom.com
info: Running YSlow for http://www.cybercom.com/upphandlingskollen/en/ [phantomjs]
verbose: Done processing url in yslow: http://www.cybercom.com/About-Cybercom/Events-and-seminars/bluff-contest/
verbose: Done processing url in yslow: http://www.cybercom.com/Cases-and-clients/a-portal-for-all-government-services/
verbose: Done processing url in yslow: http://www.cybercom.com/About-Cybercom/Press-Media/
verbose: Done processing url in yslow: http://www.cybercom.com/About-Cybercom/Corporate-governance/
verbose: Done processing url in yslow: http://www.cybercom.com/upphandlingskollen/en/
Starting proxy on port 2001, will wait at most 15000 ms
info: Done analyzing urls
info: Wrote file domains.html
info: Wrote file assets.html
info: Wrote file pages.html
info: Wrote file errors.html
info: Wrote file rules.html
info: Wrote file hotlist.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote results to /usr/local/lib/node_modules/sitespeed-result/www.cybercom.com/2016-07-08-21-35-11
info: The analyze took 2 minutes (104 seconds)
NYjjose170903:node_modules jjose$

**Comment by mail2jomy** [comment]
Here is the report generated:

![result](https://cloud.githubusercontent.com/assets/15023885/16707541/54d83d18-45a0-11e6-94e0-3e861c920793.png)

**Comment by soulgalore** [comment]
Hey @mail2jomy 
ok it looks like all metrics is wrong and Firefox don't start (I see that you choose Firefox but don't see it in the log). What Firefox version are you using? Firefox 47 was broken (didn't worked with Selenium), fixed in 47.0.1 but then we need to update the Selenium version, we have only done that in the coming 4.x.

Best
Peter

**Comment by mail2jomy** [comment]
@soulgalore - thanks for responding to this. I'm using FF 4.7.0.1. Are you saying  next version of hte product this issue is fixed or there is something I can do in between? 

I also tried with chrome (this was my preference as my app supports chrome better), same observation. I assume I just need to start chromedriver in a parallel session. Anything else i need to do to get this working?

Chorme Version :  51.0.2704.103 (64-bit) on MAC

**Comment by mail2jomy** [comment]
This is what i did to start chrome driver.
![chromedriver](https://cloud.githubusercontent.com/assets/15023885/16710500/d5f196e8-45fe-11e6-8db5-8e7d29bee817.png)

**Comment by soulgalore** [comment]
I've done a new release, if you update it will hopefully work on Firefox 47.0.1. For Chrome you shouldn't need to start the chromderiver, just put it in your path. I have bad connectivity where I'm right now so haven't been able to test too much but can help out tonight if it doesn't work.
Best 
Peter

**Comment by soulgalore** [comment]
Hmm I see that you get the same with Chrome, can test tonight.

**Comment by soulgalore** [comment]
I did a quick test with the latest version and it works for me:
<pre>
$ sitespeed.io -u http://www.cybercom.com -b firefox -d 0 -n 1
info: OS: 'darwin 15.5.0', Node.js: 'v4.4.5', sitespeed.io: '3.11.6', PhantomJS: '2.1.1', java: '1.7.0_71', browsertime: '0.12.3'
info: Will analyze 1 page
info: Running YSlow for http://www.cybercom.com [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for http://www.cybercom.com firefox
info: Running browsertime for firefox http://www.cybercom.com
Fetching http://www.cybercom.com (1 of 1)
Storing /Users/peter/git/sitespeed.io/sitespeed-result/www.cybercom.com/2016-07-10-22-07-48/data/har/firefox/www_cybercom_com.har
Storing /Users/peter/git/sitespeed.io/sitespeed-result/www.cybercom.com/2016-07-10-22-07-48/data/browsertime/firefox/www_cybercom_com-browsertime.json
Stopping proxy
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file domains.html
info: Wrote file hotlist.html
info: Wrote file errors.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file detailed-site-summary.html
info: Wrote file index.html
info: Wrote file www_cybercom_com.html
info: Wrote file www_cybercom_com-0.html
info: Wrote results to /Users/peter/git/sitespeed.io/sitespeed-result/www.cybercom.com/2016-07-10-22-07-48
info: The analyze took a minute (58 seconds)
</pre>

In your example I could never see that the proxy nor the browser is started?

Best
Peter

**Comment by mail2jomy** [comment]
@soulgalore -The issue has been resolved. It has to do with JDK version on Mac. I updated the version and it started working. 

@soulgalore - Any issues you are aware of with Single Page Application (SPA)>

**Comment by soulgalore** [comment]
@mail2jomy you should probably change config of when to stop measuring https://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test and then I would soon start to test with 4.0, then you can test the second view (second page access) so you can keep track of cached/not cached items/score/metrics.
