### ISSUE TITLE
CSS issue with show/hide details on pages summary and individual run pages

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1049]
![css-issue-show-hide-details](https://cloud.githubusercontent.com/assets/723985/16718836/9429ec08-46f1-11e6-9301-7015e7ad776c.png)

Appears to be a padding issue with the following rule.
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/src/sass/foundations/tables.scss#L102

**Comment by soulgalore** [comment]
I can have a look tonight, probably me that broke that :)

**Comment by soulgalore** [comment]
@beenanner I did a quick fix, check that it looks ok for you :)

**Comment by beenanner** [comment]
Looks good @soulgalore!
