### ISSUE TITLE
EOFException error

### ISSUE THREAD

**Issue by njordr** [sitespeedio/sitespeed.io#1054]
Hi, I've got this error, but I cannot understand why:

14:38 [root@cwsreport:~] 22s 130 # sitespeed.io --url "https://syshell.net" --name "SYSHELL.NET"
info: OS: 'linux 3.13.0-86-generic', Node.js: 'v6.3.0', sitespeed.io: '3.11.6', PhantomJS: '2.1.1', java: '1.7.0_101', browsertime: '0.12.3'
info: Will crawl from start point https://syshell.net with crawl depth 1
error: Error from the crawl: java.io.EOFException

error: Error from the crawl: java.io.EOFException

error: Error from the crawl: java.io.EOFException

Thanks

**Comment by soulgalore** [comment]
Hey @njordr 
can verify I get the same error. I want to avoid doing so much with 3.x since 4.0 is here soon, can you try the alpha (it worked for me)?

Best
Peter

**Comment by njordr** [comment]
Hi @soulgalore 

I tried with the alpha version and it works.

Thaanks
