### ISSUE TITLE
About using sitespeed.io  + selenium docker

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1061]
I want to try out using sitespeed.js with selenium docker... so as it doesnt interfere by launching local browser.. is it possible>

**Comment by softwareklinic** [comment]
bin/sitespeed.js http://www.google.com --browsertime.seleniumServer http://127.0.0.1:32768/wd/hub -b chrome

is still launching my local mac browser... instead of the selenium running in docker

**Comment by softwareklinic** [comment]
Getting same issue of invalid locator on both MAC and AWS 

Mac docker shows firefox 47.0
AWS docker im using a separate selenium xvfb container -- using firefox 46.0

doesnt work in either case... gives INVALID LOCATOR error...

**Comment by soulgalore** [comment]
Hey @softwareklinic 
if you want to run Docker you need to do it with: docker run ...

Adding --browsertime.seleniumServer will tell browsertime to connect to another Selenium server, instead of the one comes with Browsertime.

For the locator, I think it is how you require your dependencies. I'll be offline now for a couple of days but maybe @tobli or @beenanner can help you.

Best
Peter

**Comment by softwareklinic** [comment]
What.is.the.locator? Is.it<http://is.it> unable.to find.element

Sent from my iPhone

On Jul 19, 2016, at 12:50 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic>
if you want to run Docker you need to do it with: docker run ...

Adding --browsertime.seleniumServer will tell browsertime to connect to another Selenium server, instead of the one comes with Browsertime.

For the locator, I think it is how you require your dependencies. I'll be offline now for a couple of days but maybe @tobli<https://github.com/tobli> or @beenanner<https://github.com/beenanner> can help you.

Best
Peter

**Comment by softwareklinic** [comment]
Closing this issue..... will track it in already open item
