### ISSUE TITLE
Posting data to Elasticsearch rather than graphite

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1062]
Team,

Are we planning to push the data to elasticsearch in addition to graphite.... since that can be used to further tie the data to other data sources such as dynatrace, web logs, tealeaf etc... and then do a whole 9 yards of analysis.

Just a thought... if we are planning to support it..

**Comment by beenanner** [comment]
Hey @softwareklinic,

Sounds like a great idea! For the initial release though we are looking to support only graphite and influxdb initially.

**Comment by ftore** [comment]
Hi guys, I am interested on implementing this feature. Is anybody working on it already?

**Comment by beenanner** [comment]
@store I don't believe so. That's great we have a slack channel you can join and we can help and discuss implementation!

**Comment by softwareklinic** [comment]
I would join as well


On Fri, May 26, 2017 at 9:24 PM Jonathan Lee <notifications@github.com>
wrote:

> @store I don't believe so. That's great we have a slack channel you can
> join and we can help and discuss implementation!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_1062-23issuecomment-2D304417336&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=7jKqVBOIB7DKjhkjZiYHqPQ1xUl0H4s7NKaeDod3ojI&s=hm5azvlrtLnfXd7S0-BW-PCACCr3pkMeEeyLsle5Nhg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCibVxhlqX7J6lBVc33INhmY0GiGD6ks5r93togaJpZM4JPztp&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=7jKqVBOIB7DKjhkjZiYHqPQ1xUl0H4s7NKaeDod3ojI&s=72BrZ-vaMGCrDFX2n_JZR7-VU2pzh-dyL6x7_LXXpb8&e=>
> .
>
-- 
Regards,
Keyur
Cell: 2147845203

**Comment by beenanner** [comment]
Great! :-)

**Comment by soulgalore** [comment]
Nothing happened here, I will close and if people want/needs it we should start implement it as a standalone plugin outside of sitespeed.io

**Comment by crileiton** [comment]
Hello @soulgalore, greetings, do you know any news about this? thank you
