### ISSUE TITLE
Proxy parameter for 4.0 & 3.11.x

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1066]
Im behind the proxy on my AWS VPC (intranet) --- how do i hit the urls outside...

Also, i used --proxy or -p for 3.11.x and it doesnt connect outside... using the proxy url that i provide... the same works for wget and docker pull etc... using HTTP_PROXY environment variables...

**Comment by soulgalore** [comment]
Let us surface the proxy settings from Browsertime so it is the CLI for sitespeed.io
