### ISSUE TITLE
Site comparison with 4.0

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1069]
Are we losing the functionality to compare sites --sites option - with 4.0?? or something upcoming... this is a great feature with 3.x

**Comment by soulgalore** [comment]
Hi @softwareklinic 
haven't implemented that yet and I'm not sure what it should look like. Making it easy to test multiple site is great but I'm not sure about the HTML output. Let's add issue for that #1108.

**Comment by soulgalore** [comment]
@softwareklinic you should checkout the new leaderboard https://www.sitespeed.io/documentation/sitespeed.io/leaderboard/ - that's the better solution (at least for me hehe) since it doesn't complicate the code + make things configurable for you as user.

**Comment by softwareklinic** [comment]
Awesome
