### ISSUE TITLE
Tying the grafana charts to HTML Summary Report

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1081]
Wanted to check if there is a plan to TIE the html summary reports to each data point in the grafana chart... where if there are any outliers or performance point that we want to look @ and do some analysis --- then we can just click on the chart point in grafana and goto html summary report for that date.time

**Comment by soulgalore** [comment]
Hey @softwareklinic yes it is https://github.com/sitespeedio/sitespeed.io/issues/893

I'll get back on all the other issues when I get back into town in about one week.

Best
Peter

**Comment by softwareklinic** [comment]
ty, enjoy ur vacation...
