### ISSUE TITLE
Problem while comparing sites with competitor or industry 

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1082]
I wanted to compare how are we doing compared to the industry leaders or same industry.sector....

Especially - i triggered sitespeed for microsoft.com --- which identified that the request was coming from an automated system 

"Your current user-agent string appears to be from an automated system, if this is incorrect, please click xxxxxxxxxxxxxxx......"

How can we address this....?

**Comment by tobli** [comment]
Hi!
Can't say for sure, but I assume this is from the yslow analysis which is performed from phantomjs. You can override the user agent passed to identify as Chrome, Firefox or your browser of choice. See https://www.sitespeed.io/documentation/configuration/#viewportuser-agent-and-mobile

Note that it still won't emulate a real browser, there are other runtime browser checks that'll reveal that it's not a real browser. In Sitespeed 4 real browsers (Chrome or Firefox) will be used which should eliminate this problem.

Best,
/Tobias

**Comment by soulgalore** [comment]
Hey @softwareklinic & @tobli 
I think of a couple of reasons:

* In 3.0 we actually override the user agent when you are using PhantomJS but you can still know it is PhantomJS: http://engineering.shapesecurity.com/2015/01/detecting-phantomjs-based-visitors.html

* The website has blacklisted IPs so for example if you run the tests from Amazon, they check the IP. You can try if the URL works from your local.

* You test too often. In 4.0 you can configure the time between each run: https://github.com/sitespeedio/browsertime/blob/1.0/lib/support/cli.js#L184

Best
Peter
