### ISSUE TITLE
Unable to test URLS using Docker & behind corporate firewall

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1092]
Anyone has any idea how this works... I've exhausted all options...

Sitespeed is installed as DOCKER image on AWS instance behind company firewall/proxy.... i have set all the env variables/rc/bash etc... and internet works fine from the aws ubuntu machine - but the sitespeed docker container is unable to access and test URLs... from it....

**Comment by TarunGoel** [comment]
Please refer to https://github.com/sitespeedio/sitespeed.io/issues/936
May be it will help... helped me with similar issue...

Do let us know the results...
 Thanks

**Comment by softwareklinic** [comment]
Didnt resolve the issue --- i tried all gimmicks but still unable to ping or curl or sitespeed from inside the container bash... any help would really be appreciated...

**Comment by soulgalore** [comment]
Hey @softwareklinic is there an easy way to reproduce this for me?

**Comment by softwareklinic** [comment]
I.will reply back tonight

Sent from my iPhone

On Aug 2, 2016, at 11:19 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic> is there an easy way to reproduce this for me?

**Comment by softwareklinic** [comment]
I'm not sure how to reproduce...but here is my setup

I've an amazon instance running inside my company's federation environment -- pratically a non-prod private VPC instance.... 

the only way we can go out to internet from this instance is by configuring proxy variables pointing to our internal proxy url @ port 80 e.g. http://proxy.xxx.xxxxxxx.com:80/

When i have docker sitespeed running on this aws instance... if I bash into the container - i do not see any http_proxy variables... and sitespeed.io doesnt get out to internet from the docker container...

So, I built a new image e.g. vzsitespeed using the 4.0 alpha 5 image by passing http_proxy as the ARGs/ENV variables while building image...now im able to see the variables inside the container... but still unable to CURL or Sitespeed.io from that container... is there any specific network setting required for the container to go out using proxy??? something isnt right....

**Comment by softwareklinic** [comment]
If you want - we can get on a webex --- and i can show the setup

**Comment by cgoldberg** [comment]
this is a Docker question rather than a sitespeed question.

**Comment by TarunGoel** [comment]
Try this it should work, worked for me well, 

docker run --privileged --rm \
	-e "http_proxy=http://<proxyIP or hostname>:<port>" \
	-e "https_proxy=https://<proxyIP or hostname>:<port>" \
	-v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:4.0-alpha \
	curl -I https://www.sitespeed.io

As mentioned above this is not an issue, its a docker question

**Comment by softwareklinic** [comment]
Ty - Tarun - but still the same 

sudo docker run --privileged --rm -e "http_proxy=http://proxy.xxxxx.xxxxxxxx.com:80/" -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:4.0-alpha curl -I http://www.sitespeed.io

curl: (5) Could not resolve proxy:

**Comment by softwareklinic** [comment]
THIS IS WHAT WORKED

docker run --privileged -it --dns=999.999.999.999 -e "http://proxy.xxx.xxxxx.com:80/" sitespeedio/sitespeed.io:4.0-alpha curl -I http://www.google.com

finally - was able to resolve the proxy issue using --dns=xxx.xxx.xxx.xxx + the -e "http_proxy=xxxxx" === CURL works fine now

NOW A SITESPEED CHALLENGE

but sitespeed.io still run into error... with ECONNREFUSED connect ECONNREFUSED 127.0.0.1:54675

This doesnt look like a docker issue now...

**Comment by TarunGoel** [comment]
This could be because of hostname not getting resolved to IP... try with proxy IP address and correct port.

**Comment by softwareklinic** [comment]
We are good.... i had to pass DNS IP using --dns option while launching container --- and also i had to use -e to pass http_proxy parameters..
