### ISSUE TITLE
Filename of file containing urls ends up in namespace instead of urls

### ISSUE THREAD

**Issue by OffByNone** [sitespeedio/sitespeed.io#1107]
When using a file containing urls (instead of entering a single url) one of the two graphite namespaces is incorrect.
I used a file called urls.txt - in graphite the summary namespace shows as
sitespeed_io.summary.urls_txt.chrome.native....

If I look at pageSummary urls_txt is not an option and it has the correct urls
sitespeed_io.pageSummary.www_example_com._about.chrome.native....

**Comment by soulgalore** [comment]
Hey @OffByNone yes, hmm it's by choice since you could have different domains in one file. What we maybe could do is that if one file contains the same domain, we could use that. Need to think, how to test multiple sites etc isn't ready yet.

**Comment by jessejacob** [comment]
+1. Maybe it was because I wasn't expecting it and it broke my graphs, but it seems like it would be reasonable to use the domain from the file if they're all the same. That said, I already worked around it by carefully naming the files used :)

**Comment by soulgalore** [comment]
we only use domain in name in 4.0.
