### ISSUE TITLE
TypeError when rendering GSPI results

### ISSUE THREAD

**Issue by Kataract** [sitespeedio/sitespeed.io#1110]
Perhaps I'm just doing this incorrectly.  I can see that the GSPI results are in the `/pages/$site/data` directory, so it may just be a parser error.

Command being run: `$ bin/sitespeed.js -d 0 -n 1 --gpsi.key [my key without quotation marks] [my url]`
sitespeed.io version: latest in master
OS: OSX 10.10.5
Browser: Chrome 51.0.2704.103 (64-bit)
log gist: https://gist.github.com/Kataract/cd2212276352be17a1eb913a6b72ba82

I have to remove some information but I can provide by email if it's necessary.  For what it's worth, Coach and WebPagetest will both run without error and render correctly.

**Comment by soulgalore** [comment]
Hey @Kataract 
I think it's a bug in the code for GPSI on our side, I've only tested it for a couple of sites and haven't given it so much love. Can you share the URL so I can reproduce? You can drop me an email if you wanna keep it secret: peter [AT] soulgalore [dot] com 

Best
Peter

**Comment by soulgalore** [comment]
Thanks @Kataract for the URL! It works for me with the fix. Still needs to do some fixes to output the data from GPSI better but at least it doesn't break.

**Comment by Kataract** [comment]
Working great now - thanks so much :)
