### ISSUE TITLE
Video - mpg files - playing in browser???

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1116]
How will we play mpg files in browser... once embedded as a part of the html summary report.... I've tried to create experimental video --- video gets created -- but then how do I play it in browser?

are we planning to create video in the HTML5 compatible format.?

**Comment by soulgalore** [comment]
Lets see, I've been down prioritizing the video until we can release 4.0. There's a lot of work to make the video work good.

**Comment by softwareklinic** [comment]
Ty, and yes i think it can wait :)

**Comment by soulgalore** [comment]
This is released now, it's mp4 and should work in all modern browsers :)

**Comment by softwareklinic** [comment]
Does it also show the VIDEO in the HTML Summary?

**Comment by soulgalore** [comment]
yez

**Comment by softwareklinic** [comment]
docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ -n 1  --video --speedIndex -b firefox

Are these parameters VALID --video and --speedIndex -- I found on readme/documentation page... but doesnt seem to be working - collecting visual speed index or recording video.... 

Below example from -- https://github.com/sitespeedio/sitespeed.io 

$ docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --video --speedIndex https://www.sitespeed.io/

Also, the sequence seems to be incorrect ... URL need to be 1st parameter... instead of --video --speedIndex?? -- doesnt work with the example provided..

**Comment by soulgalore** [comment]
Hey @softwareklinic are you sure you updated to 4.1.0?

<pre>
$ docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ -n 1 --video --speedIndex -b firefox
Google Chrome 54.0.2840.100 
Mozilla Firefox 50.0
[2016-12-01 15:45:53] Versions OS: linux 4.4.27-moby nodejs: v6.9.1 sitespeed.io: 4.1.0 browsertime: 1.0.0-beta.13 coach: 0.29.0
[2016-12-01 15:45:53] Starting firefox for analysing https://www.sitespeed.io/ 1 time(s)
[2016-12-01 15:45:53] Testing url https://www.sitespeed.io/ run 1
[2016-12-01 15:46:18] 8 requests, 88.29 kb, firstVisualChange: 5.93s, DOMContentLoaded: 5.74s, Load: 6.45s, speedIndex: 5937, rumSpeedIndex: 5572
[2016-12-01 15:46:18] Render HTML for 1 page(s) 
[2016-12-01 15:46:20] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2016-12-01-15-45-53
[2016-12-01 15:46:20] Finished analysing https://www.sitespeed.io/
</pre>

**Comment by softwareklinic** [comment]
Aaaahhhh -- I forgot to add the TAG... I pulled the right image ... but forgot to add the tag while running...

**Comment by softwareklinic** [comment]
Im assuming i can use --speedIndex without actually using along with --video --- it will record and delete the video... is that correct assumption?

**Comment by soulgalore** [comment]
yes, I tried to add it here: https://www.sitespeed.io/documentation/sitespeed.io/configuration/#speed-index-and-video
