### ISSUE TITLE
Maybe an enhancement - to just chart out UP TIME metrics

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1117]
Since Sitespeed.io already does a lot --- would it be a good to add 1 more metric - for monitoring uptime???

**Comment by soulgalore** [comment]
Could be that you could do something smart with graphite/grafana to get this out of the box, if you really want it!

**Comment by softwareklinic** [comment]
Will give it a shot

**Comment by softwareklinic** [comment]
I tried to explore --- but looks like might need some input later when you have time... on how do possibly do it with graphite and grafana alone... or do i use something like a node uptime type of tool to enhance to post to graphite

**Comment by soulgalore** [comment]
Let us close this, if there's something that you want @softwareklinic re-open but I think there's better tools for up time measurements out there.
