### ISSUE TITLE
Does not wait to finish loading

### ISSUE THREAD

**Issue by NoMotion** [sitespeedio/sitespeed.io#1119]
My site has a lot of javascript backend requests. Looking at the screenshots there are elements of the page still loading when sitespeed comes back with a report. sitespeed will not wait for all elements to finish loading.

This is a snapshot I get right before sitespeed stops:
![screenshot 2016-08-09 15 52 49](https://cloud.githubusercontent.com/assets/9122267/17536402/957cdaec-5e49-11e6-85be-cb66f0bb3eae.png)
Its pretty obvious these divs are still loading. Each one is sending its own request to our backend and the requests are large, we want to know how long tho for all of them

EDIT: After more investigation it seems sitspeed is ignoring the TTFB requests. I have a request waiting for 34 seconds yet get 2.5 seconds in end report

**Comment by soulgalore** [comment]
Hey @NoMotion what version are you using?

You can configure when to end your test (3.x): https://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test

You can add whatever Javascript you want that will decide when your test is finished (by returning true).

It works the same for 4.0 but the alpha version doesn't have that released yet (it's in master).

Best
Peter

**Comment by NoMotion** [comment]
Sitespeed.io version '3.11.7'

Running with that example is actually worse. I tried multiple `PerformanceTiming` methods all don't work for my use case. Any other tips? 
![grafana](https://cloud.githubusercontent.com/assets/9122267/17570696/55ba97b4-5f02-11e6-8693-563dc83f9125.png)

**Comment by soulgalore** [comment]
The example shows you how you can configure the javascript that chooses when to stop testing, so depending on how you page works, you could wait for a longer time after the loadeventEnd happens (default is 2 seconds) or tie it to an event you know happens on your page when it is finished loading, it's all up to you :)
