### ISSUE TITLE
http://dashboard.sitespeed.io/ is returning 404

### ISSUE THREAD

**Issue by gregsadetsky** [sitespeedio/sitespeed.io#1120]
The example http://dashboard.sitespeed.io/ dashboard is returning a 404.

Thanks

**Comment by soulgalore** [comment]
thanks for reporting, I need to upgrade the certificate for the site but haven't had time to do that yet.

**Comment by dj-hedgehog** [comment]
@soulgalore I suggested a reverse-proxy setup with https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion.

We're using this for everything in our company (soon also sitespeed :D )

**Comment by soulgalore** [comment]
Thanks @dj-hedgehog will try it out tomorow then, we use the standard Docker container for nginx.

**Comment by soulgalore** [comment]
finally got the time to fix this.
