### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when using gpsi

### ISSUE THREAD

**Issue by jobetdelima** [sitespeedio/sitespeed.io#1134]
Hello,

When I run => sitespeed.io -u URL_FOR_MY-SITE, things work very well and I get that report generated in the sitespeed-result folder. 

However, when I do =>  sitespeed.io -u URL_FOR_MY-SITE --gpsiKey MY_GOOGLE_KEY, I get the below error:

info: Running Google Page Speed Insights for <URL for my site>
/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/lib/util/util.js:258
      if (args.length === 1) {
              ^

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.gpsiReplacer (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/lib/util/util.js:258:15)
    at /Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/lib/util/hbHelpers.js:150:31
    at Array.forEach (native)
    at Object.<anonymous> (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/lib/util/hbHelpers.js:149:10)
    at Object.eval (eval at createFunctionContext (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:6:109)
    at prog (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at execIteration (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/node_modules/handlebars/dist/cjs/handlebars/base.js:155:19)
    at Object.<anonymous> (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/node_modules/handlebars/dist/cjs/handlebars/base.js:164:11)
    at Object.eval (eval at createFunctionContext (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:10:31)
    at prog (/Users/jdelima/.nvm/versions/node/v5.9.1/lib/node_modules/sitespeed.io/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)

Would really appreciate any lead on what could be going on.

BTW, running GPSI on the Google Page Speed Insights website by directly providing my site's URL works.

Thanks!

**Comment by soulgalore** [comment]
Hey @jobetdelima ,
you are using 3.x right? Do you have time to test with the coming 4 release (either the alpha version through npm or direct from the master branch? If it fails there too I'll try to fix it asap (trying to minimize work on 3 because we will soon(ish) release 4.

Best
Peter

**Comment by jobetdelima** [comment]
Hey @soulgalore,

I can't check the version right now but I'm running whatever version I got when I ran "npm install -g sitespeed.io" yesterday. 

Would be happy to try a different version if you could let me know how to grab it.

Thanks!

**Comment by jobetdelima** [comment]
Hi @soulgalore,

I've installed the latest alpha and tried.  It looks like the cmdline options has changed a bit so I tried this to run GPSI => sitespeed.io MY_SITE_URL --gpsi.key MY_KEY

I got a report generated - which is great! - but I can't seem to find GPSI-related score on it.  I don't see any json for gpsi under the data folder. Perhaps I'm just missing something?

Thanks!

**Comment by soulgalore** [comment]
Hey @jobetdelima 
checkout the tab on the page level (GPSI):
<img width="1020" alt="screen shot 2016-08-15 at 08 46 15" src="https://cloud.githubusercontent.com/assets/540757/17657572/cb37b808-62c4-11e6-8e91-90e9e8e2be9e.png">

If you want to have the JSON from GPSI (the full metrics):
<pre>bin/sitespeed.js https://www.sitespeed.io -n 1 --gpsi.key YYYY --plugins.load analysisStorer
</pre>
That data is stored in the data folder for that page.

Haven't added much love to display the GPSI data so that can be improved, plan to do that after we put out 4.0.
Best
Peter

**Comment by jobetdelima** [comment]
Hi @soulgalore,

I'm running 4.0.0-alpha.5, and for some reason, after trying I am getting a different looking report.
Please see screenshot.
 
![image](https://cloud.githubusercontent.com/assets/13887986/17663300/b1b1ed64-62b9-11e6-83b5-a63b35f8f039.png)

**Comment by soulgalore** [comment]
Hey @jobetdelima 
ah sorry  I wasn't clear: click in the link for the URL, in your example "https://www.sitespeed.io". We maybe should make that clearer in the UI?

Best
Peter

**Comment by jobetdelima** [comment]
Clicking on that page shows this...
![image](https://cloud.githubusercontent.com/assets/13887986/17663354/039ab412-62ba-11e6-9115-d3e2a287c934.png)

**Comment by jobetdelima** [comment]
Don't see the tabs, and checking the data folder, here's what I see:
![image](https://cloud.githubusercontent.com/assets/13887986/17663409/4f17da0a-62ba-11e6-9bbb-3a9d4b75d009.png)

Thanks!

**Comment by soulgalore** [comment]
The tabs will be there one level down. The first page you see is the summary for all runs for that page (you can choose how many runs you make per page).

The JSON is located in for the specific page, so move down to pages/XXX/data/ and it should be there.

The summary json:s are summary for all the pages, but right now we don't do any calculations for GPSI, thats why it's no data there.

**Comment by jobetdelima** [comment]
You're right!  gpsi.pageSummary.json is in the per page data (pages/XXX/data/).  Tried with "-n 1" but I still don't see  those tabs (not only for GPSI but for others as well) that you have on your first screenshot above.  

The actual command I'm running is => sitespeed.io MY_SITE -n 1 --gpsi.key MY_KEY --plugins.load analysisStorer.

I seem to be getting the exact report when not providing --plugins.load analysisStorer in the command.

**Comment by soulgalore** [comment]
Sorry, it must be bug, you should actually see it asap when you click the page link. What OS are you using?

<code>--plugins.load analysisStorer </code> store the data as JSON, if you want to use the original data or debug, the report should look the same with/or without it.

**Comment by jobetdelima** [comment]
Im running this on OSX El Capitan, v10.11.5.

**Comment by soulgalore** [comment]
Do you get any errors in the console output? I don't see the link to each run either (on yoru screenshot). Do you run from the master branch?

**Comment by jobetdelima** [comment]
Hi,

Here's a screenshot showing the version I'm running as well as what shows up on the terminal.
![image](https://cloud.githubusercontent.com/assets/13887986/17701304/5f104f36-6397-11e6-900d-6e1f61a82095.png)

**Comment by soulgalore** [comment]
This fixed for 4.0 right? Please reopen if not.
