### ISSUE TITLE
Windows Server R12 - Firefox 46.0 - Invalid Locator

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1136]
I'm trying to run sitespeed on the server --- with firefox 46.0 --- and getting invalid locator for the prelogin script... this script works just fine on mac...

**Comment by soulgalore** [comment]
Hey @softwareklinic for Firefox we now support 47+ when we did the switch to Geckodriver. Gecko only supports 47+. We maybe could change that if a lot of people stay on 46.

Fow windows, it's better to use Docker. Docker will be the mainly supported way of running sitespeed.io.

**Comment by softwareklinic** [comment]
Do we have any updated branch after 4.0 alpha 5 that we can try

**Comment by soulgalore** [comment]
You can try from master or the alpha docker container. Hopefully we can release beta later this week.

**Comment by softwareklinic** [comment]
Just want to make sure Master is 4.0 or 3.x

**Comment by soulgalore** [comment]
yes 4.0
