### ISSUE TITLE
About unused - CSS & JS --- selector / functions

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1140]
This is more of a Q -- Is there a way we can find out which CSS or JS includes are not being used or specific CSS selector not being used... or whats being used etc... and what is the size impact based on that...

I find the details provided by this pretty interesting and useful - https://unused-css.com/

**Comment by soulgalore** [comment]
I think the best way to do it is to write a plugin for sitespeed.io, you can have your own plugin that can do whatever with a URL. There's one thing missing today with the current structure and that it to output the data from the plugin in the HTML output, we need to think out a good way to solve that.

**Comment by beenanner** [comment]
Could be a plugin for the sitespeedio/coach? It does get tricky and sometimes returns false numbers if you have JS that does some ajax'ing of data and use CSS on that after it's pulled back or JS that doesn't actually execute until a user interaction. At least that's been my experience in the past with tools that report unused CSS & JS numbers.

**Comment by soulgalore** [comment]
Lets do this as separate plugins outside of sitespeed.io.
