### ISSUE TITLE
CLI options with dot in name and of boolean type not working as intended

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1150]
Was testing out various options and discovered this issue. 

`bin/sitespeed.js -b chrome https://www.sitespeed.io --html.showWaterfallSummary -n 1` is actually returning an array instead of true Ex: [ false, true ]

This appears to be caused by the . in the option removing is makes it work as expected. This could cause unforeseen side effects on our render side so need to find a fix in the CLI to parse these correctly.

**Comment by beenanner** [comment]
https://github.com/yargs/yargs#configuration dot-notation will break a lot of stuff and we lose all the object goodness of the keys. :'(

**Comment by beenanner** [comment]
Current options affected.

graphite.includeQueryParams
plugins.list
metrics.list
metrics.filterList
html.showWaterfall

budget.tap (not yet implemented)
budget.junit (not yet implemented)
html.generateHTML (not yet implemented)

**Comment by gajus** [comment]
"metrics.list" (and other dot-containing) options are not working at all, e.g.

```sh
$ sitespeed.io --version
sitespeed.io 4.0.4
$ sitespeed.io https://www.sitespeed.io --metrics.list -n 1
(node:17074) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[2016-11-11 17:20:12] Versions OS: darwin 16.1.0 nodejs: v7.0.0 sitespeed.io: 4.0.4 browsertime: 1.0.0-beta.9 coach: 0.28.4
[2016-11-11 17:20:12] Starting chrome for analysing https://www.sitespeed.io 1 time(s)
[2016-11-11 17:20:12] Testing url https://www.sitespeed.io run 1
[2016-11-11 17:20:16] 9 requests, 98.51 kb, firstPaint: 0.29s, DOMContentLoaded: 0.11s, Load: 0.33s, rumSpeedIndex: 0.29s
[2016-11-11 17:20:16] Render HTML for 1 page(s)
[2016-11-11 17:20:18] HTML stored in /test/www.sitespeed.io/2016-11-11-17-20-12
[2016-11-11 17:20:18] Finished analysing https://www.sitespeed.io
$ ls -lah
total 4.0K
drwxr-xr-x  4 gajus staff  136 Nov 11 13:16 .
drwxr-xr-x 27 gajus staff  918 Nov 11 13:14 ..
drwxr-xr-x  3 gajus staff  102 Nov 11 15:05 sitespeed-result
```

I am expecting output to produce a list of all configured plugins.

**Comment by gajus** [comment]
Furthermore, there is a discrepancy between what CLI says `--metrics.list` does and what the documentation says:

* documentation:
    
    > You can also list all possible metrics that you can send. You can do that by using --metrics.list. It will generate a text file named metrics.txt in the data folder.
    
    – https://www.sitespeed.io/documentation/sitespeed.io/metrics/

* CLI:
    
    > --plugins.list     List all configured plugins in the log.

One says it will output it to the log, the other says it will be written to `metrics.txt`.

**Comment by gajus** [comment]
Oh!, it reading the docs again:

> You can also list all possible metrics that you can send. You can do that by using --metrics.list. It will generate a text file named metrics.txt **in the data folder**.

```sh
$ ls ./sitespeed-result/www.sitespeed.io/2016-11-11-17-25-56/data/metrics.txt
./sitespeed-result/www.sitespeed.io/2016-11-11-17-25-56/data/metrics.txt
```

It does work.

However, the CLI documentation is misleading.

**Comment by soulgalore** [comment]
Better text was added to the cli a long time ago. For the dots in the params ... I don't fully follow how it isn't working or rather I think it works now.
