### ISSUE TITLE
Experimental Video --- now available in 4.0 master???

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1159]

**Comment by soulgalore** [comment]
yes it is since we merged in the 4.0 branch. it's still experimental = meaning be careful out there :)

**Comment by softwareklinic** [comment]
Sure - ty

Sent from my iPhone

On Aug 26, 2016, at 1:08 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


yes it is since we merged in the 4.0 branch. it's still experimental = meaning be careful out there :)

**Comment by softwareklinic** [comment]
Testing url http://www.verizonwireless.com run 1
Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:890:11)

**Comment by soulgalore** [comment]
Hey @softwareklinic do you use the Docker container? Else you need to install the dependencies for VisualMetrics on your server/computer on Linux. 
Best
Peter

**Comment by softwareklinic** [comment]
Yes docker container.

**Comment by softwareklinic** [comment]
how do i add dependencies for visualmetrics

**Comment by softwareklinic** [comment]
i have 4.0 master branch on local --- and getting the ENOENT error.... while calling experimental video

**Comment by softwareklinic** [comment]
Looks like there is some bug in the way speed index time is calculated it shows hours and minutes instead of ms and s
![speedindex](https://cloud.githubusercontent.com/assets/7537289/18151878/f95a4a7a-6fb7-11e6-88f3-f567138f48b6.png)

**Comment by soulgalore** [comment]
You can see the dependencies here: 
https://github.com/WPO-Foundation/visualmetrics

Yep first & last looks screwed and SpeedIndex to fast with that kind First Visual Change :) Let me look into it.

**Comment by soulgalore** [comment]
yes.
