### ISSUE TITLE
After installed. I run commad "sitespeed.io" and got an error.

### ISSUE THREAD

**Issue by MichaelMaGG** [sitespeedio/sitespeed.io#1160]

**Comment by MichaelMaGG** [comment]
thank you！
I succeed！

But i used example commad to try it. I found this. I consider it may cause by something not compatible.
Or something not install? Can you help me to solve this problem?

[root@pf-dev opt]# node -v
v6.4.0
[root@pf-dev opt]# npm -v
3.10.3
[root@pf-dev opt]# sitespeed.io -V
3.11.8

![sitespeed](https://cloud.githubusercontent.com/assets/6170926/17992000/25729f9a-6b76-11e6-9565-d55a0b48c313.png)

**Comment by beenanner** [comment]
@MichaelMaGG what does the following command give you.

`sitespeed.io -u http://www.ziroom.com -n 1 -d 0`

**Comment by MichaelMaGG** [comment]
the command gives me all in in the picture.

does it means that there is something wrong in the installing?

![site2](https://cloud.githubusercontent.com/assets/6170926/17995747/d3759578-6b96-11e6-815c-12fc06f7065c.png)

**Comment by MichaelMaGG** [comment]
Finally! My computer is centos6.5, so the default npm version is not the lasted, I only update nodejs version. So I update npm, and install sitespeed.io success!!!!
