### ISSUE TITLE
Graphite Namespace Questions

### ISSUE THREAD

**Issue by OffByNone** [sitespeedio/sitespeed.io#1163]
I have two questions regarding namespaces in graphite:

1.  In the namespace after the browser there is a .native but it is the only option.  Is there a plan to add more options, or could it be removed?  Right now it doesn't seem to be adding a lot of value, and is making the queries longer which makes them a bit harder to read.
  * ex. sitespeed_io.pageSummary.www_sitespeed_io.documentation.chrome.**_native_**.browsertime
2. Under browsertime.statistics the timings namespace is repeated.  Is this intentional?
  * ex. sitespeed_io.pageSummary.www_sitespeed_io.documentation.chrome.native.browsertime.statistics.**_timings.timings_**.frontEndTime

**Comment by softwareklinic** [comment]
You can have .cable --- if u use connection type - cable or 3g 

Also, you can i believe create custom configurations...

**Comment by soulgalore** [comment]
Hey @OffByNone 
yes as @softwareklinic the first should be for connectivity type, when we release the beta (this weekend?!?!) you can use that. 

> statistics.timings.timings.frontEndTime

Yes it's intentional but maybe not the best naming. Maybe we should just move them up one level (to be on the same as firstPaint etc. @tobli @beenanner what do you think?

Best
Peter

**Comment by soulgalore** [comment]
I think we should move them, some background:

The timings are the same as Google Analytics use (what they fetch from Navigation Timing API) or at least was what they used when I used to use it. I've had one idea that we could have a cumulative view of nav timings in the dashboards, but then they need to be reported differently.

**Comment by soulgalore** [comment]
or call them navtimings :)

**Comment by soulgalore** [comment]
this been cleaned up
