### ISSUE TITLE
Timing structure sent to Graphite

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1166]
On pageSummary level it annoys me that <code>
browsertime.statistics.timings.timings.frontEndTime</code> and <code>browsertime.statistics.timings.firstPaint</code> are on different levels, it makes templating harder. And as @OffByNone pointed out, the first has two timinings after each other in the key. That comes from the name in of the script in Browsertime, that structure is good and I'm 100% where/how we will hack it. Miniumum we should at least change the name.

Also for the summary it's a one liner change to move firstPaint and under timings to under timings, so they are all the same, but it should on the same level for both summary & pageSummary.

**Comment by beenanner** [comment]
How about renaming timings.timings to timings.nativeTimings or timings.siteTimings and moving those top level timers (firstPaint, fullyLoaded, and rumSpeedIndex) to live along with the existing timers in timing.nativeTimings? This would then allow us to have browsertime.statistics.timings.nativeTimings.firstPaint along side of browsertime.statistics.timings.nativeTimings.frontEndTime  and still keep browsertime.statistics.timings.userTimings.some_custom_site_timer. 

This way we maintain the isolation at the top level for easy templating of "native" timings vs user specific timings, and possible any other timings we may add in the future.

**Comment by beenanner** [comment]
Actually I think rumSpeedIndex is the only entry that isn't a "time" metric. we should probably move that somewhere else.

**Comment by beenanner** [comment]
Maybe pageTimings is a better name. That what I'm seeing used within browsertime.

**Comment by beenanner** [comment]
Guessing a bulk of the work would need to be in browsertime? Possible here: https://github.com/sitespeedio/browsertime/blob/master/lib/support/browserScript.js#L66

**Comment by soulgalore** [comment]
Renaming to pageTimings sounds good lets do that. Browsertime takes the name from the file so renaming https://github.com/sitespeedio/browsertime/blob/master/browserscripts/timings/timings.js will automatically fix that.

Not sure about how should move the timings. I like how Browsertime is doing this very generic, maybe to hack it in sitespeed. Or just skip it, the win would be just for templating in Grafana right? Or do we see another good thing moving?

**Comment by soulgalore** [comment]
I think it's ok for now to just rename it to pageTimings in BT. It's not perfect but I like that BT is so generic.
