### ISSUE TITLE
I have an issue.

### ISSUE THREAD

**Issue by MichaelMaGG** [sitespeedio/sitespeed.io#1173]
After intall sitespeed.io, i run it success, and i use .sh command to run, it also success.
But, i use linux timed task to run a java class, in the class to run sitespeed.io command, it show me this:

this is the command create by java class:
/usr/local/bin/sitespeed.io -u http://www.ziroom.com --memory 1024 -d 0 --storeJson -r /home/ziroom/sitespeed-result --outputFolderName www_index-2016083009

Can you tell me, what cause this problem? settings ? soft versions or anything else?

![siteissue](https://cloud.githubusercontent.com/assets/6170926/18119873/63e8ac2a-6f8f-11e6-8d23-578f52f6c9e3.png)

**Comment by MichaelMaGG** [comment]
I have try three nodejs version. 4.2.0,4.4.4 and 6.2.0 . all of them has the issue

**Comment by soulgalore** [comment]
Please retry with 4.0, if it is still an issue reopen!.
