### ISSUE TITLE
Can i export HAR from the waterfall???

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1174]
Lot of developers are probably asking if they can get the HAR file or way to export HAR file to be able to view in httpwatch or something else...?

**Comment by soulgalore** [comment]
Good idea, I've missed it lets add that.

**Comment by softwareklinic** [comment]
I would really appreciate if this is something that we can easily/quickly achieve...

**Comment by soulgalore** [comment]
You can get the HAR file now just by browsing by enable the analysis storer plugin: 
<code>--plugins.load analysisStorer</code>

But it would be nice to have a link in the HTML. I think there are a couple fixes we need to to:
* Add the link :)
* Make it possible to store only the HAR and not everything from an analys. Think it's more often we need the HAR than everything else.
* The HAR should then be saved with a .har file ending, now it's .har.json.

PRs are welcomed :)

**Comment by softwareklinic** [comment]
sorry for my ignorance - but where do i use the --plugins.load analysisStorer?? any full command example?

**Comment by soulgalore** [comment]
ah sorry, you add it in the cli.
<code>bin/sitespeed.js --plugins.load analysisStorer https://www.sitespeed.io</code>
Will store all raw data from different plugin like browsertime/wpt etc.

**Comment by softwareklinic** [comment]
awesome... so its still har.json.. just har would be awesome... for developers

**Comment by soulgalore** [comment]
yep I haven't made any changes. it works but it's not perfect.

**Comment by soulgalore** [comment]
This is nice but lets push it a couple of days

**Comment by softwareklinic** [comment]
k np

**Comment by softwareklinic** [comment]
is this available in master???

**Comment by soulgalore** [comment]
someone needs to implement it first :) we are pretty good tagging issues in our commits so when we do it, it will be here.

**Comment by softwareklinic** [comment]
:) good one
