### ISSUE TITLE
Do we send too much data per domain per pageSummary to Graphite?

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1176]
For every domain we send requests and sizes. I think we should send total amount of domains and then add docs how to configure to send per domain information. @tobli & @beenanner ?

**Comment by beenanner** [comment]
I agree I think total should be sent for the default and a config to additionally send individuals domain info along with the total if the user wants.

**Comment by soulgalore** [comment]
yes I didn't check the outcome properly when I configured the domains for a page summary. We need to add total number of domains in the Page Xray result to make it cleaner.
