### ISSUE TITLE
About experimental video --- the size on disk -- and the metrics dependency

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1178]
Here is my thought ---- speed index is absolutely a great way for us to test the performance of visible parts in view port... but for that we need to record the videos... which takes a huge size on disk... 

What if you can introduce an option to DELETE videos after the speed index is calculated --- so we get the speed index and have option to either keep the videos or not... 

One way - is i can write cron job to delete the video folders... but if sitespeed can provide an option while recording... it would be great...

**Comment by soulgalore** [comment]
Hey @softwareklinic yes I agree, we have an issue for it here: https://github.com/sitespeedio/browsertime/issues/136
