### ISSUE TITLE
60+ urls --- generate HTML stalls

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1179]
I have 69 urls in my text file --- for which after I run the sitespeed.io - it stalls @ the end of generating the HTML -- have experienced it multiple times... no error --- it just stops writing to disc in the sitespeed-result folder... for that domain/date/time -- i see most of the html/css/js/images/video -- but still it has some missing files and stalls.

**Comment by soulgalore** [comment]
And it really stalls, I mean if you let it wait, does it work? How many runs do you do? I have seen that when I've tested 100 URLs with 3 runs each I started to get out of memory (the default nodejs setting is low).

**Comment by softwareklinic** [comment]
it is 69 urls & 1 run / url...

**Comment by softwareklinic** [comment]
[2016-09-02 19:43:23] Render HTML for 112 page(s) 

<--- Last few GCs --->

 2996864 ms: Mark-sweep 1346.8 (1434.7) -> 1344.1 (1434.7) MB, 909.8 / 0 ms [allocation failure] [GC in old space requested].
 2997879 ms: Mark-sweep 1344.1 (1434.7) -> 1344.1 (1434.7) MB, 1015.4 / 0 ms [allocation failure] [GC in old space requested].
 2998824 ms: Mark-sweep 1344.1 (1434.7) -> 1344.1 (1434.7) MB, 945.4 / 0 ms [last resort gc].
 2999737 ms: Mark-sweep 1344.1 (1434.7) -> 1344.1 (1434.7) MB, 912.7 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3757a9cc9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x200c22d8d970] (this=0x3757a9c04189 <undefined>,string=0x3bc5bd8f2771 <Very long string[1135868]>,encoding=0x3757a9cd7a41 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x200c3c64e276] (this=0x3cbfd6bdd5e9 <JS Function Buffer (SharedFunctionInfo 0x3757a9ce2389)>,value=0x3bc5bd8f2771 <Very long string[1135868]>,encodingOrOffset=0x3757a9cd...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0xfb7bfc [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [node]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [node]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [node]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
13: 0x9da80b [node]
14: 0x9dadb1 [node]
15: 0x200c21b0961b

**Comment by soulgalore** [comment]
Yep for many runs/URL you will get out of memory, lets see if we can find an easy way to configure that in Docker. Stalling ... I think it will work, just take longer time?

**Comment by soulgalore** [comment]
This works better now.
