### ISSUE TITLE
Progressive JPEG - related info

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1181]
I see that the WPT provides information about missing Progressive JPEG and gives a score of 0-100 --- so maybe an additional rule...

Are we planning to incorporate in sitespeed..

**Comment by soulgalore** [comment]
Hey @softwareklinic ,
not at the moment. Right now we don't do anything special for images. To make something cool, you need to download each and every image individually and test them. I like the idea of testing compression etc, but it will make the tests slower. 

Best
Peter

**Comment by soulgalore** [comment]
Then we need to server checks I don't see that happening in the near future.
