### ISSUE TITLE
I maybe have a version issue.

### ISSUE THREAD

**Issue by MichaelMaGG** [sitespeedio/sitespeed.io#1182]
After intall sitespeed.io, i run it success, and i use .sh command to run, it also success.
But, i use linux timed task to run a java class, in the class to run sitespeed.io command, it show me this:

this is the command create by java class:
/usr/local/bin/sitespeed.io -u http://www.ziroom.com --memory 1024 -d 0 --storeJson -r /home/ziroom/sitespeed-result --outputFolderName www_index-2016083009

I have try **three nodejs version. 4.2.0,4.4.4 and 6.2.0** . all of them has the issue

**npm -v 3.10.7**

Can you tell me what may cause this issue?
![default](https://cloud.githubusercontent.com/assets/6170926/18259644/e18a53d0-7418-11e6-847a-f03a52d8c68e.png)

**Comment by soulgalore** [comment]
Hey @MichaelMaGG sorry for answering this so late, did you get this to work?

**Comment by MichaelMaGG** [comment]
actually, not.  
Very happy you can help me to solve it~
@soulgalore

**Comment by soulgalore** [comment]
Can you switch to use the beta release of sitespeed.io 4.0?

**Comment by MichaelMaGG** [comment]
first, I have try release of sitespeed.io 4.0. But also have some error.
so, i used 3.0.

Thanks All the same.
I will try until it work well.

**Comment by soulgalore** [comment]
Closing old issues. Please reopen if you this still is an issue for 4.0.
