### ISSUE TITLE
Create hotlist tab

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1183]
In 3.x we had a hotlist tab showing us pages/assets that you should look into. We should add that in 4.0, most important is:

* Top 10 largest images
* Top 10 largest assets (except images), we maybe could separate to HTML, CSS, JS and others
* Top 10 largest pages
* Top 10 pages with worst coach score
* Top 10 worst cached assets

Then if we have good way of implementing top 10 slowest assets and top 10 slowest domains that would be cool.

The largest images/assets will be perfect for the budget.

**Comment by rschoessler** [comment]
@soulgalore can you please explain what "slowest responses" is actually telling me?  Specifically, if I have a .js file that shows up as 500ms, is that telling me that the server "response" time was 500ms?  Or is it telling me that it took 500ms for that script to execute?  both? neither? ;-)  Thank you!

**Comment by soulgalore** [comment]
@rschoessler let me add some explaining text in the report, good catch. It collects the total time from the connect to when it's download. Execution time is not included only downloading.  It's a way to spot slow loading 3rd party assets. In 3.x you could send all that data to Graphite (you still can but you need to configure that) and become too heavy to have it turned on by default.

**Comment by rschoessler** [comment]
awesome, thx @soulgalore !
