### ISSUE TITLE
Make sitespeed.io less memory intensive

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1184]
A couple of ways to make sure sitespeed is less memory intensive:
 * Clear the aggregators when they are finished aggregating
 * Set a limit of top X of most used assets (or make that functionality configurable)

**Comment by moos** [comment]
Some ideas:
- enable 'longjohn' only in debug mode
- run fast-stats with [store_data=false](https://github.com/bluesmoon/node-faststats#configuring-the-stats-object) (this gives approximate percentiles, which may be good enough)
- run pug with [compileDebug=false](https://pugjs.org/api/reference.html) (seems to be on by default)

Needs to be validated to see if they offer any substantial benefit.

**Comment by beenanner** [comment]
I can try to take a stab at investigating some of @moos ideas. I'm on vacation this week, but will pick this up next week when I get back. I'm relatively new to Node @moos, so any tools or setup suggestions for profiling node apps would be greatly appreciated. I've mostly been using [node-inspector](https://github.com/node-inspector/node-inspector), but that's only been good enough for step-through debugging.

**Comment by moos** [comment]
@beenanner - see [#1219](https://github.com/sitespeedio/sitespeed.io/issues/1219#issuecomment-249407315) for what I used.   There's also [object-sizeof](https://www.npmjs.com/package/object-sizeof) to get JS object size in bytes.

**Comment by soulgalore** [comment]
This is ok for now with the fix from moos for pug.
