### ISSUE TITLE
Going beyond "Selenium scripts" and individual URLs

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1188]
Is there a way we can test FLOWS and the overall performance for flows... For eg.. lot of resources could be shared across pages... and if caching is in correct play the performance of the 1st page and the subsequent pages will be interesting to monitor... we need to be able to record a flow of pages and see how they perform...

This is important for both anonymous and signed-in customers...

**Comment by soulgalore** [comment]
It's tracked here: #693 but implemented.

For tracking what it looks like for second/third page, you can use the preScript functionality: go to one URL, then the next and then let sitespeed.o run the next URL. However, at least before Firefox had bug: https://github.com/sitespeedio/browsertime/issues/121 and I haven't tried in a while if it's fixed.

**Comment by softwareklinic** [comment]
Did u get a chance to confirm.. Since I have a prescript that logs the customer in... but if I have list of 5 urls.. in a text file... it logs in for each url separately.... that defeats the purpose right>

**Comment by softwareklinic** [comment]
probably need an option whether to use the prelogin just 1 time or each time the urls from file are run

**Comment by soulgalore** [comment]
yep that could be it. right now the prelogin is per URL, since we actively clean up everything between runs.

**Comment by soulgalore** [comment]
We other issues tracking this, lets add reference. ..
