### ISSUE TITLE
Sample user agent strings for mobile testing

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1193]
Can you share some user agent string already used to test the mobile

**Comment by soulgalore** [comment]
You mean the default one?

https://github.com/sitespeedio/sitespeed.io/blob/71c8fa839a1613615c8e9d013842e7046df12ae9/lib/plugins/browsertime/analyzer.js#L22

For Chrome it uses the what they configured for  deviceName: 'Apple iPhone 6', I need to check what it really is.

**Comment by softwareklinic** [comment]
We can close this one.... I figured out here are my samples

./bin/sitespeed.js http://www.verizonwireless.com --browsertime.userAgent "Mozilla/5.0 (iPhone; CPU iPhone OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" -n 1 --mobile --browsertime.viewPort 667x375

./bin/sitespeed.js http://www.verizonwireless.com --browsertime.userAgent "Mozilla/5.0 (Linux; Android 4.4.2; SAMSUNG-SGH-I337 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36" -n 1 --mobile --browsertime.viewPort 640x360
