### ISSUE TITLE
About - running urls from a URL on different domain

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1195]
We created an authoring tool where we are able to create a PAGE with list of urls... that we want sitespeed to run performance against...

But, since that URL is on different domain --- we are unable to run --- any thoughts...

**Comment by softwareklinic** [comment]
e.g. http://www.urlsforsitespeed.com/batch1.html

this html contains 10 urls that i want sitespeed to run against.... but those are on different domain...

e.g. http://www.verizonwireless.com

**Comment by tobli** [comment]
Hi!
Instead of creating an html page with links, just create a plain text file with one url per line. See https://www.sitespeed.io/documentation/configuration/#analyze-by-urls for more details. Hope this helps!
