### ISSUE TITLE
Missing headerSize in pagexray

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1201]
Pagexray seems to be missing headerSize for all requests when capturing first vs third party in graphite.

<img width="1106" alt="screen shot 2016-09-13 at 11 22 41 am" src="https://cloud.githubusercontent.com/assets/723985/18479825/6916fa34-79a4-11e6-86f3-4a6fd4ad33b5.png">

**Comment by soulgalore** [comment]
think it could me that missed that, I'll fix that tonight + add stats for cookies also :)

**Comment by soulgalore** [comment]
Ah I see now, sorry I wasn't reading the issue correct on the phone. We don't setup header size by default , check https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/coach/index.js#L14
