### ISSUE TITLE
Sitespeed and Graphite communication breakdown

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1203]
I have 3 docker containers - sitespeed, graphite, and grafana... For whatever reason since last night i didnt see any data coming to graphite until this morning... woke up and saw no data..

So, i restarted my selenium server thinking the test were not running or some issue.. but that was not it... so, i restarted graphite container... and everything started falling in place...

When i reviewed sitespeed logs --- it doesnt have any error about unable to send data to graphite...
no ECONNREFUSED --- or no message in logs... 

What could be the issue... how can i keep an eye on if sitespeed is unable to communicate with graphite..?

**Comment by soulgalore** [comment]
Hey @softwareklinic hmm strange, and you can see that sitespeed.io ran during that period?

Best
Peter

**Comment by softwareklinic** [comment]
Yes no errors — site speed was running like nothing has happened….

**Comment by softwareklinic** [comment]
Every 4-5 days - the graphite image/container that im using from sitespeedio --- stops capturing the metrics - -need to restart every 4-5 days... not sure if it just with the sitespeedio/graphite image... i can try other images...

**Comment by soulgalore** [comment]
could it be a memory problem? Do you see anything else? Do you just restart or do you anything else? I know to things that aren't good in the current graphite:
* we should turn off all logging inside the container
* the configuration for metrics name (downsizing etc) is for the 3.x structure, not for 4

**Comment by tobli** [comment]
I have an upcoming patch for chunking data (i.e. limiting the number of rows in each message) that's sent to Graphite. Might help as well.

**Comment by softwareklinic** [comment]
Its.a.8x32.machine.so I don't.think memory.should be an issue

Sent from my iPhone

On Sep 26, 2016, at 1:23 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


could it be a memory problem? Do you see anything else? Do you just restart or do you anything else? I know to things that aren't good in the current graphite:

 *   we should turn off all logging inside the container
 *   the configuration for metrics name (downsizing etc) is for the 3.x structure, not for 4

**Comment by soulgalore** [comment]
memory and disk inside the container. you just restart and don't do anything else to make it work again?

**Comment by softwareklinic** [comment]
right --- just restart and it start back on

**Comment by soulgalore** [comment]
lets reopen if this still happens
