### ISSUE TITLE
Waterfall chart legends

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1204]
Can we add legend for the waterfall

**Comment by soulgalore** [comment]
yep that would be cool, could you create an issue at https://github.com/micmro/PerfCascade with a suggestion of how it would be? thanks

**Comment by softwareklinic** [comment]
Done - https://github.com/micmro/PerfCascade/issues/54

**Comment by softwareklinic** [comment]
i now know that we are using perfcascade... but for whatever reason i feel web page test has some great waterfall charts and with legends -- just curious

**Comment by soulgalore** [comment]
I like also like WebPageTest waterfall graphs. I think we have more freedom with PerfCascade and fix more things (and it is Open Source). PerfCascade works and there's a lot that we all can do to make it better. @micmro is taking PRs :) 

We haven't focused on the waterfalls yet, only in the stage of making they work inside of sitespeed.io, lets see how we can make it better.

**Comment by softwareklinic** [comment]
Cool...

**Comment by soulgalore** [comment]
fixed in PerfCascade
