### ISSUE TITLE
Separation of resource count by domain

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1205]
I use --firstParty to separate out the count of overall HTTP Requests for 1st party and 3rd party... is it then possible to chart out the Resource count and size distribution by the 1st party or 3rd party?

**Comment by soulgalore** [comment]
Not by default. I think we wanna try to send a minimum amount of data to Graphite by default. However, you can configure so all domains and request/sizes is sent per domain ... let us add documentation for that. But then you need to do the distinction between first/third party in Grafana  (I've been doing that in 3.x).

**Comment by softwareklinic** [comment]
Can we do that in 4.0

**Comment by soulgalore** [comment]
Yes I meant you can do it in Grafana in 4.0 too but you need to configure the metrics to send. If you look at the Metrics in --help you can get a hunch of how to do it.

**Comment by softwareklinic** [comment]
any sample would be great... i will check out the help as welll

**Comment by soulgalore** [comment]
We need docs for this lets see https://github.com/sitespeedio/grafana-bootstrap-docker/issues/2
