### ISSUE TITLE
Figure out best practices for capturing fully loaded times for sites that have excess request counts

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1206]
We currently use the resource timing api to capture the last request time to report fully loaded. Current browser limitations stop capturing after 150 requests so for larger sites this could actually be lower than expected. There is a setter for the buffer size to increase it but it is currently only supported in firefox

https://www.w3.org/TR/resource-timing/#dom-performance-setresourcetimingbuffersize

Possible we could also look into clearing the buffer as an alternative.

https://developer.mozilla.org/en-US/docs/Web/API/Performance/clearResourceTimings

**Comment by soulgalore** [comment]
When we collect the video, we set the buffer to 600 requests for now. It's not perfect but lets keep it like that, let me know @beenanner if we should re-open.
