### ISSUE TITLE
Plugins.disable depending in order

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1210]
This doesn't seems right. This works:
`bin/sitespeed.js https://www.sitespeed.io --plugins.disable html`

This doesn't `bin/sitespeed.js --plugins.disable html https://www.sitespeed.io`

**Comment by beenanner** [comment]
This looks like an issue with yargs with parsing the options.

Strange that this works.

```
 bin/sitespeed.js --plugins.disable html --debug https://www.sitespeed.io
```
 Will continue to dig into it.

**Comment by beenanner** [comment]
Seems as though it's an issue with anything that takes a value of type array `--metrics.filter` breaks it as well.

Works if you put another option after them
```
➜  sitespeed.io git:(plugins-disable) ✗ bin/sitespeed.js --plugins.disable html --debug https://www.sitespeed.io
```

**Comment by tobli** [comment]
Having revisited this, I think we should avoid (deprecate and move away from) array type options in yargs. For plugins I propose plugins.add and plugins.remove. Either pass each option more than once if needed, or parse a comma separated list. We could translate the current options to the new during a transition period.

**Comment by soulgalore** [comment]
This has been fixed with plugins.add and plugins.remove.
