### ISSUE TITLE
Sitespeed becomes a memory hog for large # of urls

### ISSUE THREAD

**Issue by moos** [sitespeedio/sitespeed.io#1219]
Possibly cause of #1179.  Run with 5 urls (1 run each) consumes ~370MB.  With 25 urls, about 730MB.  Here's the memory allocation map for the 25-url run.  As can be seen about 700MB (between 50MB and 750MB ticks on the x-axis) is due to the HTML render section.

<img width="708" alt="screen shot 2016-09-23 at 11 58 46 pm" src="https://cloud.githubusercontent.com/assets/233047/18807021/eb25e3c8-81f1-11e6-8f15-6c41262e1fe4.png">

Memory is rarely de-allocated -- largely due to the async nature of the code.

**Comment by soulgalore** [comment]
Hey @moos, yes you are right, we have some ideas in #1184 any ideas are welcomed, haven't focused on this yet, but need to do it before final 4.0.

**Comment by moos** [comment]
I played around a bit to see what's taking up so much memory -- it's pug for sure! Here's a heap snapshot showing 32MB of strings -- most of the which are pug-related.

<img width="381" alt="screen shot 2016-09-22 at 11 14 14 pm" src="https://cloud.githubusercontent.com/assets/233047/18810143/38886446-8243-11e6-978f-7d9201d47b58.png">

Not sure if there is a way to force pug to clean up after render.

**Comment by soulgalore** [comment]
Cool! @moos can you share you have best setup node with devtools?

**Comment by moos** [comment]
I'm using this command:
```shell
$ node --inspect --debug-brk bin/sitespeed.js -m25 -n1 http://0.0.0.0:8082 
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@62cd277117e6f8ec53e31b1be58290a6f7ab42ef/inspector.html?experiments=true&v8only=true&ws=localhost:9229/node
```
Then copy&paste the URL in chrome and you're in inspect mode.  `--debug-brk` ensures a breakpoint as soon as the code is entered.  From there, you can start any of the profiles under the Profile tab. Also, I use [http-server](https://www.npmjs.com/package/http-server) to serve a local directory.

**Comment by moos** [comment]
I've de-async'd the rendering process.  This seems to make pug memory manageable without any adverse affects (most of the operations take roughly equal time).  5-url run now about 115MB.
<img width="732" alt="screen shot 2016-09-25 at 9 22 30 pm" src="https://cloud.githubusercontent.com/assets/233047/18823271/393a4be0-836d-11e6-93c8-0e554c65f460.png">

25-url run about 180MB.
<img width="749" alt="screen shot 2016-09-25 at 9 26 55 pm" src="https://cloud.githubusercontent.com/assets/233047/18823277/4b84dd88-836d-11e6-8564-39798a8e0623.png">

That seems to be about 3MB/url delta after the first one.  So a 100-url run should (theoretically) take around 115 + 3*100 = 415MB.
