### ISSUE TITLE
How to script a test with multiple steps?

### ISSUE THREAD

**Issue by usherfu** [sitespeedio/sitespeed.io#1224]
Hi,
Currently I am evaluating several performance tools to integrate with our CI pipeline. I have following questions and appreciate if anyone could give some advises:

The scenario is that end user will navigate on our web app multiple consecutive steps, e.g. navigate to the app, fill out search criteria, click "search" button, select one result from the list to navigate to the item detail, click edit button and etc. 

Questions:

- Is it possible to test above scenario with sitespeed.io?   As far as I understood, currently it can only test urls and crawl site (again with url), but not possible to script the scenario.  Is this correct? Or can sitespeed.io be used together with e.g. selenium script (selenium script drives the test while sitespeed.io take the measurement)?

Thanks!

**Comment by softwareklinic** [comment]
But, sitespeed wont measure the pages being loaded by selenium scripts right> Only the links in the TEXT file or URL provided will be measured once the selenium script is done with execution of steps...e.g. sign-into account....

**Comment by soulgalore** [comment]
yep you are right @softwareklinic . However 4.0 isn't released yet and making it possible to measure the whole trip (hitting x URLs after each other) could be doable (we need to change so we don't empty the cache for each hit in Browsertime and collect totals (like total amount of css/js etc loaded for a trip)). To measure when you run the actual Selenium, that's some extra work, I haven't thought of how that will be implemented, we need brainstorm about that.

**Comment by usherfu** [comment]
@soulgalore @softwareklinic 
Thanks for the feedback and additional question.  I think the preScript/postScript is a great way to script the scenario, unfortunately it only supports measuring URL instead of "user action" triggered by selenium script (e.g. user click).  I'd love to see that feature in 4.0.     

Just one thought. Since an user action (for example click) would basically trigger several urls, is it possible to simply list those urls in a text file and pass to sitespeed.io as a workaround?  Some caveats:  with this approach, js runtime cannot be measured in the browser, right?

**Comment by soulgalore** [comment]
I haven't seen any tool that can measure "user actions" in a good way? I mean the noise will be too high or? 

Yep, making a list of URLs will make the trick (and the noise will go away) but there's one thing missing there today and that is that we empty the cache between runs see https://github.com/sitespeedio/browsertime/issues/112 . That can be fixed though :)

**Comment by usherfu** [comment]
With [wpt scripting](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting) , it is possible to measure certain action (as written in the script) by toggling "logData". For example, 
```
logData    0

// put any urls you want to navigate
navigate    www.aol.com
navigate    news.aol.com

logData    1

// this step will get recorded
navigate    news.aol.com/world
```
Do you have any idea how they did that? or sitespeed.io might support such scenario in 4.0 or any future release?

**Comment by soulgalore** [comment]
That scenario is supported in 4.0 clicking or doing more funky stuff when you wanna catch metrics is not. To support we need to invest some time to make it as clean as possible.
