### ISSUE TITLE
Maintaining chrome login session in terminal

### ISSUE THREAD

**Issue by akashk92** [sitespeedio/sitespeed.io#1230]
Hi @soulgalore 
I logged into my web app (localhost) and I got JsissionId.
I used that session id in terminal with sitespeed.io using following command
`sitespeed.io -u http://localhost:8080/frontdesk/patients/12QLVSRS8M -d 1 --requestHeaders cookie.json`
cookie.json file:
`{
"Cookie":"978B0BEBDD24C0041F73D71665514643"
}`
but this command logs out my browser session.
So how do I maintain the same browser login session in terminal without expiring it.?

**Comment by soulgalore** [comment]
Hey @akashk92 ,
I think it's better if you can start using the beta version of 4.0 it's gonna be released this month and then you can login using a selenium script, checkout https://github.com/sitespeedio/browsertime/blob/master/test/prepostscripts/preLoginExample.js for an example.

Best
Peter

**Comment by akashk92** [comment]
@soulgalore 
so does this mean, this feature is not availablle for now?

**Comment by soulgalore** [comment]
yep you can't, you need to use a selenium script. maybe we can add support for cookies if a lot people want them (or we get a PR).

**Comment by akashk92** [comment]
@soulgalore 
if tits possible for u, can you tell me step by step procedure to the same?
>  you need to use a selenium script
FYI I don't know selenium.

**Comment by soulgalore** [comment]
You need to use Selenium as in the example.
