### ISSUE TITLE
Report cost of rendering site in reports.

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1236]
Integration with something like https://whatdoesmysitecost.com/ or similar as being able to provide $$$ in the report could be interesting to capture and surface in reports from sitespeed on a per page / per run. What do you guys think @tobli / @soulgalore? Maybe a better fit for coach or even it's own plugin? Definitely not needed for 4.0 but maybe for 4.1 or 4.2.

**Comment by soulgalore** [comment]
I like whatdoesmysitecost and the idea of making that available. One problem is that it isn't Open Source plus the data that is used to calculate the cost (not all some of them) isn't open (you need to pay for it).

**Comment by beenanner** [comment]
Boo. Yep seems like it would be interesting to try to see if you could correlate cost of a page over time using some time series DB to some other performance metrics or one of a business's main KPIs.

**Comment by soulgalore** [comment]
We have dashboard https://dashboard.sitespeed.io/dashboard/db/page-cost-estimator?orgId=1 and I think that one is enough for now. Let us re-open if we want to have something else.
