### ISSUE TITLE
Created html report using Gulp doesn't generate it's resources (img/css/fonts)

### ISSUE THREAD

**Issue by otomer** [sitespeedio/sitespeed.io#1247]
I have run $.sitespeedio (using gulp-plugins), and report is created (json for gpsi, webpagetest,yslow), and when i attempt to execute the html files (to look at it normally), but all of it's resources are missing (css, images, fonts) so the html reports (budget.html, screenshots.html,..) looks "naked" of style.
Any idea?

**Comment by beenanner** [comment]
@otomer do mind sharing a minimal setup (gulpfile.js, package.json) to reproduce? It could be generating incorrect paths or something.

**Comment by otomer** [comment]
Sure, while i tried mixing the configuration many times it still generates the same.
I get bunch of results via json files, and html (not always getting this), and when i run it it looks stripped of styles, fonts, imgs.

This is a simplified version of my code ( I just had a lot mixed around)
Btw, i also tried gulp 3.9 (latest), and the new Gulp 4 alpha 2, both generates same issue.

```
var gulp = require("gulp"),                             //The streaming build system
 $ = require("gulp-load-plugins")({ lazy: true }),


function getOptions() {
	return {
		urls: ["http://myurl.com"],
		profile: 'mobile',
		deep:0,
		skipTest: "ycdn,textcontent",
		wptKey: "..",
		wptHost: "..",
		gpsiKey: "MY_KEY",
		no: 2,
 		resultBaseDir: "./mydir",
		wptConfig: {}, //my config was set properly
		budget: {}, //my budget was set properly	
	}
}

gulp.task("sitespeedio", function(done) {
	return $.sitespeedio(getOptions())(done);
});
```

**Comment by beenanner** [comment]
@otomer try adding `html: true,` to your options object. The following works for me locally.

```
var gulp = require("gulp"),                             //The streaming build system
 $ = require("gulp-load-plugins")({ lazy: true });


function getOptions() {
    return {
        urls: ['https://www.sitespeed.io/'],
        profile: 'mobile',
        deep:0,
        skipTest: "ycdn,textcontent",
        no: 2,
        html: true,
        resultBaseDir: "./mydir",
        wptConfig: {}, //my config was set properly
        budget: {} //my budget was set properly    
    }
};

gulp.task("sitespeedio", function(done) {
    return $.sitespeedio(getOptions())(done);
});
```

**Comment by otomer** [comment]
@beenanner it worked!
I kinda missed this property, seems like it fixed everything.
I would really like to thank you, what a great help.

**Comment by beenanner** [comment]
Absolutely @otomer! Glad I could help out and everything is working. :-)
