### ISSUE TITLE
is there any way sending the json results to some service other than graphite? (windows os)

### ISSUE THREAD

**Issue by otomer** [sitespeedio/sitespeed.io#1248]
Im looking for a way to send the json results into any windows service that can be sourced with Grafana.
I previously tried graphite on my windows pc, but it was really messy using VM and vagrant (took my a lot of time!).

What im trying to achieve is viewing the results over Grafana without using Graphite.
Is there any option to send the data somewhere else? for example ElasticSearch? I tried that within Gulp but it didn't work. Can anyone suggest a working solution over windows?

**Comment by soulgalore** [comment]
Hey @otomer 
Can you try [Graphite on Docker](https://hub.docker.com/r/sitespeedio/graphite/)? That will work out of the box. Also if you are using Windows you probably should run sitespeed in Docker too, since we don't officially support Windows.

There's a PR for elasticsearch https://github.com/sitespeedio/sitespeed.io/pull/1239 and I know we wanna support InfluxDB and with the "new" plugin structure there will be possible to store data wherever.

Best
Peter

**Comment by otomer** [comment]
Thanks for your reply @soulgalore
Sitespeedio works well ony my windows, i use gulp and i did not encounter any serious issue yet. 
Main problem is movong from the html/json reports to a visual graphs, using grafana. 
Since grapgite is the middleware which is not supported on windows, it makes it really hard to progress with grafana. 
Ideally i would like graphite since it works better with sitespeedio (instead of looking other solutons like elasticsearch and such), but it purged me to install vagrant, virtual bpx and more installs im not sure what was it exactly.

Back to your suggestion using Docker image, what is it exactly? Will it install only graphite on separated os? Or it requires me to use sitespeedio task via it too?  Im kinda satisfied from the current way i use gulp and i just want it to send it to some graphite server properly. 
Also, can i keep using grafana on my windows environment? 
Sorry for the newbosh question but i never used any docker and still struggling with figuring your suggestion :)

**Comment by otomer** [comment]
It seems like "Docker for windows"  is not supported over windows 7
https://docs.docker.com/engine/installation/windows/
Did anyone tried it?
