### ISSUE TITLE
Data sent to Graphite as null

### ISSUE THREAD

**Issue by namnn96** [sitespeedio/sitespeed.io#1257]
Hi team,

I have played around with sitespeed for quite a long time now and lately there are a couple of issues.

+) I installed selenium 2.53.1 and firefox 46. It does not crash like firefox 47 but still cause some warning like Driver class not found. (it still runs fine)
+) The next strange thing is data sent to graphite, but they are all empty? I set max create per minute to inf but this still happens. (Earlier I tried on a server and it's fine, now that I install on another server.)
The sitespeed-result folder is still ok, contains all data.
+) I also test via webpagetest. The issue is when running the sitespeed command with wpt option, it stops at running webpagetest, not crash, just doing nothing and after 1 hour I had to quit it.

I hope you guys know the issue, thanks in advance.

Best regards,

**Comment by soulgalore** [comment]
Hey @namnn96 ,
which sitespeed.io version are you using? Selenium & Firefox has changed over time, dropping the built in support where you need to have the Geckodriver to work. If you run the latest beta of sitespeed it should work with Firefox 48 and later. 

> The next strange thing is data sent to graphite, but they are all empty?

You get the keyes in Graphite but no values? You can turn on verbose logging to see the exact data that is sent to try to track where the problem come from. I can point you in the right direction when I know which version.

>+) I also test via webpagetest

Do you use WebPageTest.org with a API key or do you have your own instance?

Best
Peter

**Comment by namnn96** [comment]
Hi @soulgalore,

Thanks for the reply. I am using sitespeed.io version 3.11.8.

+) I used -v and it actually says sending metrics with positive data. For example, the rulescore in verbose is 85, but when I open graphite browser and grafana, trying to display that rulescore, i got N/A

+) I have my own aws instance for Webpagetest.

In fact, I have one instance where I have all sitespeed.io, graphite, grafana and webpagetest, just different ports

Thanks in advance.

**Comment by soulgalore** [comment]
Test with 4.0, hope it will work, else please create a new issue.
