### ISSUE TITLE
Tabs not working inside of HTML Report in Jenkins

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1265]
<img width="1256" alt="screen shot 2016-10-25 at 00 02 23" src="https://cloud.githubusercontent.com/assets/540757/19665680/758605a4-9a46-11e6-968b-ab007692ce79.png">

**Comment by mglauche** [comment]
This seems to happen only if the "--outputFolder output" is specified. Without it, the reports get written correctly in the folders, but are not easily linkeable in jenkins.

**Comment by sakonachhoeurng** [comment]
Yes, we can close that issue. but this is the big thing that we need to keep track and resolve it.

**Comment by soulgalore** [comment]
When I checked my console I get:
<img width="1425" alt="screen shot 2017-03-03 at 10 54 37" src="https://cloud.githubusercontent.com/assets/540757/23546445/e097708e-ffff-11e6-959d-efd2f20cb9f7.png">

There's info [here](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy) how you can disable/change the security settings, let me know how it works out @sakonachhoeurng !

**Comment by sakonachhoeurng** [comment]
@soulgalore I try to follow your step again, and I see it error the same you. I would like to verify it on my server ci. thanks for helping along time.

**Comment by sakonachhoeurng** [comment]
@soulgalore I found the solution and it fixed on my local ci. By this line `JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox allow-scripts; style-src 'unsafe-inline' *;script-src 'unsafe-inline' *;\""` replace this with your variable `JENKINS_JAVA_OPTIONS`
or you can find [here](https://github.com/gatling/gatling/issues/2889)

**Comment by soulgalore** [comment]
Thank you @sakonachhoeurng ! I'll add it to the docs tonight.
