### ISSUE TITLE
Able to connect to graphite but dont see any results being written to /opt/data/graphite...

### ISSUE THREAD

**Issue by crkatz** [sitespeedio/sitespeed.io#1271]
Hello All,
           Instead of localhost I am using the eth0 inet address to send data to graphite on path /var/log/graphite. But no data is being written to that location.

Please advise.

-crkatz

**Comment by soulgalore** [comment]
Hey @crkatz 
sorry for taking long time answer, been busy with the new release. The IP address should work. You can debug by turning the vebose logging to see what is actually sent and in Graphite you can check the logs if you receive any data.

Best
Peter

**Comment by soulgalore** [comment]
Closing, let us know if this is still a problem.
