### ISSUE TITLE
Add info in developers section on how to use Pug

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1280]
https://www.sitespeed.io/documentation/sitespeed.io/developers/
We should write about pug and how you can run the templates against json- data files, when you wanna test your design changes.

**Comment by beenanner** [comment]
Good idea!

**Comment by soulgalore** [comment]
We should add this at the same time https://github.com/sitespeedio/sitespeed.io/issues/1287

**Comment by soulgalore** [comment]
Added a short debug info that is enough for now.
