### ISSUE TITLE
sitespeed should fetch from urls from file after preScript is finished

### ISSUE THREAD

**Issue by eplle** [sitespeedio/sitespeed.io#1291]
Hi!

I have written a small preScript that does two things:
1. Login
2. Update my url.txt that I would like sitespeed to analyze.
The reason I update the url.txt in preScript is that the page I am trying to analyze requires a token in the url. Otherwise the user will be logged out.

But I see that sitespeed fetches the url before browsertime.preScript has finished and therefore tries to analyze the url from the previous run.

Would it be possible to fetch the urls from file when the prescipt has finished?

Many thanks, Per.

**Comment by soulgalore** [comment]
Hey Per,
the thing is that the url.txt is read by the CLI in the beginning and then a URL message is sent, you can see the workflow here: https://www.sitespeed.io/documentation/sitespeed.io/developers/#analyzing-a-url-step-by-step (maybe need to make that clearer) so there's no way today to change it. Ping @tobli do you see a way to solve this?

Best
Peter

**Comment by eplle** [comment]
In 3.x it was possible to have a separate selenium script for login and determine token and then send the cookies with requestHeaders.
PreScript is a cleaner way, but I cant find a way to make it work with my token.
Is it be possible to send a URL-parameter from the prescript to sitespeed?

**Comment by tobli** [comment]
Logging in (thereby setting a cookie) is a perfect use case for pre-scripts. Adding tokens to the url has a number of downsides, and isn't a good fit for how sitespeed.io is designed.
It seems the issue for you is that the login page submit doesn't load fully before sitespeed goes on to load the page from the url list (thereby failing to set a session cookie). I'm guessing you're not returning a Promise from the pre-script. Sitespeed.io will wait for any promise returned from pre-scripts to resolve before proceeding to load the main url.

Hope this helps!

@soulgalore - we need to make sure documentation and examples reflects this pattern.

**Comment by eplle** [comment]
Hi again. Thanks for your answer.
Im not having any problems with the cookies. The problem lays with not being able to set a token as a URL parameter. The page I am trying to analyze uses the token as a protection against CSRF.

**Comment by soulgalore** [comment]
I think the best way to do this is to checkout the project and add the parameter and run your rests, don't see a use case for adding the functionality but if more people need this, let us re-open the issue!
