### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by shrynx** [sitespeedio/sitespeed.io#1297]
Is there any documentation for apis for using it via node js ?
I am planning to build a custom backend solution as a replacement Graphite

**Comment by soulgalore** [comment]
For data storage you should look how https://github.com/sitespeedio/sitespeed.io/tree/master/lib/plugins/graphite  and https://github.com/sitespeedio/sitespeed.io/tree/master/lib/plugins/influxdb plugins work (Influxdb is not fully functional yet though). All plugins listen to message, we don't have full docs yet but you can start by looking at https://www.sitespeed.io/documentation/sitespeed.io/how-it-all-works/ and https://www.sitespeed.io/documentation/sitespeed.io/how-it-all-works/ and we will add more things there the coming months.

**Comment by soulgalore** [comment]
We should add a doc section and point to https://github.com/sitespeedio/grunt-sitespeedio/blob/master/tasks/sitespeedio.js as a working example.

**Comment by soulgalore** [comment]
updated the docs
