### ISSUE TITLE
The "mobile" option can't work. 

### ISSUE THREAD

**Issue by zhangzhaoaaa** [sitespeedio/sitespeed.io#1298]
In master branch:

1. lib/support/cli.js 
The "mobile" option is the first level arg.

2. lib/plugins/browsertime/index.js
The open function:  
`this.options = merge({}, defaultConfig, options.browsertime);`  

  Here code just merges options.browsertime into defaultConfig,and put them into this.options.

3.  lib/plugins/browsertime/analyzer.js  
The analyzeUrl function:  
```

if (options.mobile) {
      btOptions.viewPort = '360x640';
      if (btOptions.browser === 'chrome') {
        btOptions.chrome = merge({}, btOptions.chrome, chromeIphoneEmulationOptions);
      } else {
        btOptions.userAgent = iphone6UserAgent;
      }
    }

```

Here options.mobile is always "undefined". 
In the 2nd step,you haven't merged "mobile" into this.options.

So,maybe you add it  in 2nd part :

```
if (options.mobile) {
      this.options.mobile = options.mobile;
}

```

Or you have a better choice.

**Comment by soulgalore** [comment]
hey @zhangzhaoaaa 
yes great it seems like bug, wanna do a PR else we can fix that tonight!
Best
Peter
