### ISSUE TITLE
Question on AWS instance user's permission

### ISSUE THREAD

**Issue by namnn96** [sitespeedio/sitespeed.io#1300]
Hi @soulgalore ,

I have a question regarding the webpagetest instance on aws. As mentioned in the link [https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance](https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance), we need to create a user with full access.

I tried with both full access and not full access users, and the full returns result while the later returns nothing (undefined). My questions are:

- Why does the user need full access? 
- Will wpt create any dummy servers for testing? 
- If not full access, what must have at least for the wpt to work?

Thanks in advance.

**Comment by soulgalore** [comment]
Hey @namnn96 ,
the user needs to have privileges to start a new Amazon instance (agents). I don't fully remember the Amazon privileges setup, but you can check my write up at https://wikitech.wikimedia.org/wiki/WebPageTest or you could ask at https://github.com/WPO-Foundation/webpagetest/issues/new so Pat can help you out!

Best
Peter
