### ISSUE TITLE
Example for --collectors option in sitespeed version 4

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#1303]
Version sitespeed@4.0.3 and  sitespeedio/sitespeed.io:4.0-beta.5  (docker).  Is there an example on how to use the collectors option?

 Also for `--postTasksDir`. I see that the way script has to be created has changed a bit.  Something like https://github.com/sitespeedio/sitespeed.io/blob/master/test/prepostscripts/postSample.js.  I saw in the index.md that options are `--postTasksDir <DIR>` | `--browsertime.postScript <DIR>, --postScript <DIR>`  . But I don't think this accepts a directory, it actually needs the path of the script file. Please correct me if I am missing anything.

Thanks

**Comment by soulgalore** [comment]
Yes, so it's maybe a little confusing.  So ooops, it was so long time I did something with 3.x. Collectors was that adding a data source, then its a plugin. 

We have skipped the old postTask. That is now a plugin. See https://www.sitespeed.io/documentation/sitespeed.io/plugins/  Everything in sitespeed.io is now a plugin. You can build your own plugin as a npm module or link them when you run, as long as they have the functions needed to be plugin. If you want to store the metrics in a database, you will build a plugin. If you want to add an analyzer (like checking used CSS) you can do that in a plugin. 

The postScript is a selenium script. With the new version you have the ability to run a Selenium script before you test a URL (preScript) so you can login a user or prewarm the cache, and you can also run a selenium script after a URL is analyzed (logout or whatever you wanna do). https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/

**Comment by abhagupta** [comment]
Thanks @soulgalore . This change unfortunately creates a lot of work for me :( .  Anyway, I tried creating a plugin to store the results in Kairos DB, but when I try to load the plugin using 
```
sitespeed.io http://www.google.com -b chrome --browsertime.chrome.args no-sandbox -n 1 --plugins.load plugin.js graphite 
```

and when I debugged it, I see that my plugin.js is executed before the performance test is executed, so my results `context.dataCollection.summaryPages`  is empty.  When I compared with `graphite` plugin, it ran after the performance test was executed.  Since I need to work with results of the test, I need my plugin to be executed after the test is executed. What am I missing? Contents of my plugin.js

```
module.exports = {
    name() {
        return path.basename(__dirname);
    },
    open(context, options){
        console.log('results', JSON.stringify(context.dataCollection.summaryPages));
    },
    processMessage(messsage){

    },
    close(options, errors) {
        // When all URLs are finished all plugins close function is called.
        // Options are the configuration options and errors a array of errors
        // from the run.
    }
}
```

**Comment by soulgalore** [comment]
yes I'm sorry :( Let us know if we can help out in any way. The thing is that the 3.x implementation was narrow and with the new structure we are totally open so we/users can add their own analyzers etc.

<code>open(context, options)</code> is called once at startup of sitespeed.io, if you wanna initialize something, try that you could connect to the db etc. 

<code>processMessage(messsage)</code> is called for every message that is sent, so you can listen to new URL, run your own analyze or collect results from other plugins. The browsertime plugin listens to messages of the type URL, so when it gets an URL, it opens the browser and collect the metrics, and then send different messages with the result (like one for the coach and so on). If you are implementing a storage you can either choose what kind of metrics you want and collect them in processMessage. Or you can use close.

<code> close(options, errors) </code> is called once when every URL and analyze is finished, so if your plugin collects data, you can store it here or user the dataCollection to take the default data.

Storing data you can either do it in a big bang in the close method or collect each message in processMessage and store it incrementally.

Sorry again that the new structure means a lot of more work for you :(

**Comment by abhagupta** [comment]
Thanks.. I just figured that the `processMessage(message)` is the method I need to use.  Sorry for alarm. I think once I get a good handle on how flow works, I should be able to convert things into plugins :)

**Comment by abhagupta** [comment]
I do strongly think, that we need more documentation around creating plugins.. may be I can send a  PR with examples for addtional docs around plugins as I go through the process.

**Comment by soulgalore** [comment]
Yep, I agree, lets create an issue for that and make it better.

**Comment by soulgalore** [comment]
@abhagupta I started updated the docs for plugins and it would be super if you can add things when you go along. https://github.com/sitespeedio/sitespeed.io/issues/1307

**Comment by tobli** [comment]
I'm closing this issue since #1307 is open for documentation improvements. Thanks!
