### ISSUE TITLE
Browser not start in time Sitespeed.io V4

### ISSUE THREAD

**Issue by namnn96** [sitespeedio/sitespeed.io#1309]
Hi @soulgalore,

I took your advice and tried sitespeed 4.0.3, node 6.9.1 and firefox 48.

I tried this simple command but it returns error that browser not start in time:
`sitespeed.io http://xxx -b firefox --graphite.host localhost --graphite.namespace test -d 0 -n 5`

Will the standalone selenium 2.53.1 work or it has to use the selenium installed via npm?

Thanks in advance.

**Comment by soulgalore** [comment]
Hey @namnn96 

> returns error that browsertime not start in time:

Do you get that all the time?

> l the standalone selenium 2.53.1 work or it has to use the selenium installed via npm?

By default Selenium is installed (the npm version) but you could use the standalone selenium jar if you want,

Best
Peter

**Comment by namnn96** [comment]
Thanks @soulgalore for the reply.

I do get that error all the time. The browsertime version is 1.0.0 beta 9

**Comment by soulgalore** [comment]
Ok, so how large server/instance do you use? Do you use xvfb?

Either I think you could just try with our Docker version:
https://www.sitespeed.io/documentation/sitespeed.io/docker/
Then you don't need to care about versions or xvfb. First install Docker and then pull the right container.

If you wanna run npm, the only thing you need should be: npm install sitespeed.io -g 
skip the rest of the steps. Make sure you use xvfb if you don't use a screen and run.

**Comment by namnn96** [comment]
Thanks, I am using aws small instance with 2GB. 

I planned to trigger sitespeed command via php request, so I am not sure if I can do that with docker.
Earlier I got it all done with sitespeed 3.11.8, just the overloaded graphite issue led me to sitespeed 4.

**Comment by namnn96** [comment]
Hey @soulgalore,

Nevermind, it was me not allowing the port 2003 in ufw and my aws. After allowing the port in both, it runs normally.

Thanks for your support.
