### ISSUE TITLE
Recover Graphite after being overloaded

### ISSUE THREAD

**Issue by namnn96** [sitespeedio/sitespeed.io#1310]
Hi @soulgalore,

I actually got the sitespeed 3.11.8 work with firefox 46 and selenium 2.53.1. However, as you said in the documentation for sitespeed v4, graphite was overloaded and crashed when I tried to run cron job for 3 urls.

Now that I delete all the folders under whisper, it again sends data to graphite as null, though the verbose says different.

Is that because my graphite is completely down and I need a new one? Or how do you overcome this issue? 

Thanks in advance.

**Comment by soulgalore** [comment]
Hey @namnn96 no it shouldn't breakdown, the "normal" behaviour is that you will miss metrics when you look in Graphite, not that it will crash. Could it be that your instance is too small?

If you could try running the Docker containers you can take it up/down as you like.

>Now that I delete all the folders under whisper, it again sends data to graphite as null, though the verbose says different.

I don't fully follow?

Best
Peter

**Comment by namnn96** [comment]
Thanks for the reply.

My aws instance is a small one with 2GB. What I did was deleting every folder in Whisper then tried to run the command again (as I hope to refresh whisper).

But the data sent to graphite are all null, while the verbose did show the value for each metric.

**Comment by soulgalore** [comment]
It depends on how much data and how complex queries you wanna do but you should probably have a bigger instance. Can you use a Graphite Docker version then it should not be an issue to reinstall?

**Comment by namnn96** [comment]
Thanks @soulgalore,

I am not quite clear about docker. I have a few questions regarding this:
- Will I still install graphite locally and use docker instance to connect to graphite host via ip?
- If I install docker, do I need to configure anything else inside docker, like firefox, selenium or geckodriver?
- Where and how the selenium will be run? In docker instance or in my aws instance?

Thanks in advance.
