### ISSUE TITLE
webpagetest (wpt) - visual complete time

### ISSUE THREAD

**Issue by jjethwa** [sitespeedio/sitespeed.io#1312]
Affects version(s) 4.0.x

It appears that visual complete time is not included in the available metric list for wpt?  (See the available metrics for wpt from the metrics.txt output)   I think it would be a valuable addition for the graphite dashboards.  Thanks so much for all the great work on sitespeed 😄 

`
webpagetest.summary.timing.firstView.TTFB.median
webpagetest.summary.timing.firstView.TTFB.mean
webpagetest.summary.timing.firstView.TTFB.min
webpagetest.summary.timing.firstView.TTFB.p90
webpagetest.summary.timing.firstView.TTFB.max
webpagetest.summary.timing.firstView.render.median
webpagetest.summary.timing.firstView.render.mean
webpagetest.summary.timing.firstView.render.min
webpagetest.summary.timing.firstView.render.p90
webpagetest.summary.timing.firstView.render.max
webpagetest.summary.timing.firstView.fullyLoaded.median
webpagetest.summary.timing.firstView.fullyLoaded.mean
webpagetest.summary.timing.firstView.fullyLoaded.min
webpagetest.summary.timing.firstView.fullyLoaded.p90
webpagetest.summary.timing.firstView.fullyLoaded.max
webpagetest.summary.timing.firstView.SpeedIndex.median
webpagetest.summary.timing.firstView.SpeedIndex.mean
webpagetest.summary.timing.firstView.SpeedIndex.min
webpagetest.summary.timing.firstView.SpeedIndex.p90
webpagetest.summary.timing.firstView.SpeedIndex.max
webpagetest.summary.asset.firstView.breakdown.html.requests.median
webpagetest.summary.asset.firstView.breakdown.html.requests.mean
webpagetest.summary.asset.firstView.breakdown.html.requests.min
webpagetest.summary.asset.firstView.breakdown.html.requests.p90
webpagetest.summary.asset.firstView.breakdown.html.requests.max
webpagetest.summary.asset.firstView.breakdown.html.bytes.median
webpagetest.summary.asset.firstView.breakdown.html.bytes.mean
webpagetest.summary.asset.firstView.breakdown.html.bytes.min
webpagetest.summary.asset.firstView.breakdown.html.bytes.p90
webpagetest.summary.asset.firstView.breakdown.html.bytes.max
webpagetest.summary.asset.firstView.breakdown.js.requests.median
webpagetest.summary.asset.firstView.breakdown.js.requests.mean
webpagetest.summary.asset.firstView.breakdown.js.requests.min
webpagetest.summary.asset.firstView.breakdown.js.requests.p90
webpagetest.summary.asset.firstView.breakdown.js.requests.max
webpagetest.summary.asset.firstView.breakdown.js.bytes.median
webpagetest.summary.asset.firstView.breakdown.js.bytes.mean
webpagetest.summary.asset.firstView.breakdown.js.bytes.min
webpagetest.summary.asset.firstView.breakdown.js.bytes.p90
webpagetest.summary.asset.firstView.breakdown.js.bytes.max
webpagetest.summary.asset.firstView.breakdown.css.requests.median
webpagetest.summary.asset.firstView.breakdown.css.requests.mean
webpagetest.summary.asset.firstView.breakdown.css.requests.min
webpagetest.summary.asset.firstView.breakdown.css.requests.p90
webpagetest.summary.asset.firstView.breakdown.css.requests.max
webpagetest.summary.asset.firstView.breakdown.css.bytes.median
webpagetest.summary.asset.firstView.breakdown.css.bytes.mean
webpagetest.summary.asset.firstView.breakdown.css.bytes.min
webpagetest.summary.asset.firstView.breakdown.css.bytes.p90
webpagetest.summary.asset.firstView.breakdown.css.bytes.max
webpagetest.summary.asset.firstView.breakdown.image.requests.median
webpagetest.summary.asset.firstView.breakdown.image.requests.mean
webpagetest.summary.asset.firstView.breakdown.image.requests.min
webpagetest.summary.asset.firstView.breakdown.image.requests.p90
webpagetest.summary.asset.firstView.breakdown.image.requests.max
webpagetest.summary.asset.firstView.breakdown.image.bytes.median
webpagetest.summary.asset.firstView.breakdown.image.bytes.mean
webpagetest.summary.asset.firstView.breakdown.image.bytes.min
webpagetest.summary.asset.firstView.breakdown.image.bytes.p90
webpagetest.summary.asset.firstView.breakdown.image.bytes.max
webpagetest.summary.asset.firstView.breakdown.flash.requests.median
webpagetest.summary.asset.firstView.breakdown.flash.requests.mean
webpagetest.summary.asset.firstView.breakdown.flash.requests.min
webpagetest.summary.asset.firstView.breakdown.flash.requests.p90
webpagetest.summary.asset.firstView.breakdown.flash.requests.max
webpagetest.summary.asset.firstView.breakdown.flash.bytes.median
webpagetest.summary.asset.firstView.breakdown.flash.bytes.mean
webpagetest.summary.asset.firstView.breakdown.flash.bytes.min
webpagetest.summary.asset.firstView.breakdown.flash.bytes.p90
webpagetest.summary.asset.firstView.breakdown.flash.bytes.max
webpagetest.summary.asset.firstView.breakdown.font.requests.median
webpagetest.summary.asset.firstView.breakdown.font.requests.mean
webpagetest.summary.asset.firstView.breakdown.font.requests.min
webpagetest.summary.asset.firstView.breakdown.font.requests.p90
webpagetest.summary.asset.firstView.breakdown.font.requests.max
webpagetest.summary.asset.firstView.breakdown.font.bytes.median
webpagetest.summary.asset.firstView.breakdown.font.bytes.mean
webpagetest.summary.asset.firstView.breakdown.font.bytes.min
webpagetest.summary.asset.firstView.breakdown.font.bytes.p90
webpagetest.summary.asset.firstView.breakdown.font.bytes.max
webpagetest.summary.asset.firstView.breakdown.other.requests.median
webpagetest.summary.asset.firstView.breakdown.other.requests.mean
webpagetest.summary.asset.firstView.breakdown.other.requests.min
webpagetest.summary.asset.firstView.breakdown.other.requests.p90
webpagetest.summary.asset.firstView.breakdown.other.requests.max
webpagetest.summary.asset.firstView.breakdown.other.bytes.median
webpagetest.summary.asset.firstView.breakdown.other.bytes.mean
webpagetest.summary.asset.firstView.breakdown.other.bytes.min
webpagetest.summary.asset.firstView.breakdown.other.bytes.p90
webpagetest.summary.asset.firstView.breakdown.other.bytes.max
`

**Comment by soulgalore** [comment]
Hey @jjethwa ,
thanks for the kind words :)

Yes so we chose a couple of ones per default but you can configure what metrics to send. We have some docs https://www.sitespeed.io/documentation/sitespeed.io/metrics/ but it could be we need more to make it understandable.  Can you try it out and I can guide you more in deep tomorrow if it's needed?

Best
Peter

**Comment by jjethwa** [comment]
Thanks for the speedy response, @soulgalore 

I totally missed the visualcomplete metric in the output until you nudged me in the right direction. 

All I had to do was add 

`
--metrics.filter webpagetest.pageSummary.data.median.firstView.visualComplete
`

Thanks again.  Really appreciate it and can't wait to see where you take us next 😄
