### ISSUE TITLE
gpsi metric ignored from the budget

### ISSUE THREAD

**Issue by krukru** [sitespeedio/sitespeed.io#1314]
When adding gpsi.pageSummary.ruleGroups.SPEED.score as a metric to the budget, it gets ignored in the budget output

Here is my budget.json

 ```json
{
   "gpsi.pageSummary":[
      {
         "metric":"ruleGroups.SPEED.score",
         "min":90
      }
   ],
   "coach.pageSummary":[
      {
         "metric":"advice.performance.score",
         "min":90
      }
   ]
}
```
Both in the budget tab and the generated junit.xml only the coach metric gets evaluated

**Comment by soulgalore** [comment]
Yep if I remember correctly we only support WebPageTest and data generated from Browsertime but it could be added.

**Comment by soulgalore** [comment]
We moved out GPSI to a own plugin in 6.0. That will happen in https://github.com/sitespeedio/sitespeed.io/issues/1825

**Comment by zunjooo** [comment]
Greetings,

I added `gpsi.pageSummary.ruleGroups.SPEED.score` metric inside my budget file but I don't see gpsi result inside report that generates when I execute sitespeed test with gpsi plugin

**Comment by soulgalore** [comment]
@zunjooo https://github.com/sitespeedio/sitespeed.io/pull/1828 needs to be merged and released first, when that is done, I'll update the plugin.
