### ISSUE TITLE
Error with Chrome browser

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1318]
[2016-11-09 12:07:44] TypeError: Cannot read property '_requestId' of undefined
    at Object.harFromEvents (/Users/xxxxxxxxx/sitespeed.io/node_modules/browsertime/lib/support/chromePerflogParser.js:234:26)

**Comment by soulgalore** [comment]
Hey @softwareklinic I think this is the same as https://github.com/sitespeedio/browsertime/issues/209 that fix is rolling out asap, probably tomorrow.

I'll close this issue when it's released.
Best
Peter

**Comment by softwareklinic** [comment]
ty

**Comment by softwareklinic** [comment]
will it be available to test today?

**Comment by soulgalore** [comment]
no sorry,we will release this weekend and bundle with SpeedIndex fixes in Browsertime.

**Comment by soulgalore** [comment]
This is release now in 4.0.5.

**Comment by softwareklinic** [comment]
Ty

Sent from my iPhone

On Nov 11, 2016, at 5:10 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


This is release now in 4.0.5.

-
