### ISSUE TITLE
Whats the reason there is no data for short time windows (e.g. last 5 minutes)?

### ISSUE THREAD

**Issue by gajus** [sitespeedio/sitespeed.io#1321]
Example, there is no data looking at:

https://dashboard.sitespeed.io/dashboard/db/page-summary?from=now-5m&to=now

I am experiencing the same behaviour on a local setup.

**Comment by soulgalore** [comment]
It depends how often we collect values, for the dashboard we run once every hour.

**Comment by gajus** [comment]
> It depends how often we collect values, for the dashboard we run once every hour.

I am running my agent every minute though, and the 5 minutes dashboard is showing as empty.

You can see the setup here, http://51.15.36.207/

```
username: test
password: test
```

**Comment by gajus** [comment]
Have you got a Slack/ IRC/ gitter channel setup?

I'd like to ask a few questions, e.g. what is the reason no information is appearing in the timings dashboard (http://51.15.36.207/dashboard/db/timings). I have confirmed that we are sending this information.

**Comment by soulgalore** [comment]
Hey @gajus check your graphite config, it depends how you aggregate your metrics. I don't have the config file name in my head. 
Best
Peter

**Comment by soulgalore** [comment]
Now I'm back on my computer. For Graphite checkout https://github.com/sitespeedio/docker-graphite-statsd/blob/master/conf/graphite/storage-schemas.conf I think the retentions need to be smaller if you wanna run each five minutes. 

About the timings, yes that's strange. None of the templates are populated so somehow the path is wrong. Check what's used for the path for the templates and what you got in Graphite.

You can reach me: peter [AT] soulgalore [DOT] com

Best
Peter

**Comment by gajus** [comment]
> I'd like to ask a few questions, e.g. what is the reason no information is appearing in the timings dashboard (http://51.15.36.207/dashboard/db/timings). I have confirmed that we are sending this information.

The reason there is no information appearing in timings dashboard is because `$path` value is hardcoded as "default" in the timings templates, e.g. see https://github.com/sitespeedio/grafana-bootstrap-docker/blob/5fcc25df9fbb273dc30e75b8aed58d43fe132efc/dashboards/timings.json#L335

**Comment by soulgalore** [comment]
cool thanks @gajus should be fixed now.

**Comment by soulgalore** [comment]
This is fixed right? Else please re-open.
