### ISSUE TITLE
generated the following error in Browsertime BrowserError: unknown error: cannot create temp dir for user data dir

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1322]
Im trying to run sitespeed on AWS linux - behind proxy.. and getting this error

generated the following error in Browsertime BrowserError: unknown error: cannot create temp dir for user data dir.

**Comment by soulgalore** [comment]
Hey @softwareklinic this looks like it comes direct from the browser. To be able to try to reproduce I need to know what browser you are using, how you run it. And does it happen all the time, once etc?

Best
Peter

**Comment by soulgalore** [comment]
Closing, let is know if it is still an issue.
