### ISSUE TITLE
How to configure custom $page?

### ISSUE THREAD

**Issue by gajus** [sitespeedio/sitespeed.io#1324]
I have two URLs that I want to test separately:

* http://www.dailymail.co.uk/home/index.html
* http://www.dailymail.co.uk/home/index.html?no-cache=true

However, sitespeed.io groups them under the same `$page` `_home_index_html`.

Is there a way to make sitespeed.io include the query string AND/OR provide an alias name for the `$page` variable for a particular test?

**Comment by soulgalore** [comment]
Hey @gajus ,
you can try out  <code>--graphite.includeQueryParams</code> hopefully that will work!

Best
Peter

**Comment by gajus** [comment]
That was obvious - Sorry, I overlooked the configuration.

Its works as expected.
