### ISSUE TITLE
High severity vulnerability affecting this repo

### ISSUE THREAD

**Issue by benmag1** [sitespeedio/sitespeed.io#1328]
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [Regular Expression Denial of Service](https://snyk.io/vuln/npm:minimatch:20160620?utm_source=gh_issue)
* Affected package: minimatch<=3.0.1

[Here is the test report for this repo](https://snyk.io/test/github/sitespeedio/sitespeed.io?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

**Comment by beenanner** [comment]
Thanks @benmag1 for the report. These vulnerabilities are hopefully report upstream (gpagespeed, and webpagetest) as we try to stay up-to-date with the latest packages. Looks like we can at least update moment to fix one of the 4.

**Comment by beenanner** [comment]
Closing as we have updated the only one we could until the upstream packages are updated.
