### ISSUE TITLE
Grafana dashboards not showing data ?

### ISSUE THREAD

**Issue by gugansankar** [sitespeedio/sitespeed.io#1333]
I just pulled sitespeed.io and graphite docker image from hub. And starting graphite image by using below command,

docker run -d   --name graphite   -p 8080:80   -p 2003:2003   sitespeedio/graphite

And Inserting data into graphite by using the below command set,

 /usr/bin/docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.google.com -d 0 -n 5 --connection cable -r /tmp/ --graphiteHost 127.0.0.1 --graphiteNamespace sitespeed.io --graphiteData summary,rules,pagemetrics,timings,requests --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

Data are inserted into graphite properly. But when I tried to use the json file that's available in git https://github.com/sitespeedio/sitespeed.io/tree/master/grafana-setup/dashboards is NOT working.

Seems, data format inserted in graphite is differ from the metrics query that written in the json files.

could you please share the data format that need to be inserted into graphite to use the dasboards json ?

**Comment by soulgalore** [comment]
Hey @gugansankar 
it seems like you are using sitespeed.io 3.x from command line when running sitespeed.io? Upgrade to 4.0 (Docker tag for the latest is 4.0.7 so docker pull sitespeedio/sitespeed.io:4.0.7 does the trick!). Then check how to run your container, it has changed between 3.x and 4: https://hub.docker.com/r/sitespeedio/sitespeed.io/ and the --help output.

Then when you inserted the data, you can use this container to get the dashboards: https://hub.docker.com/r/sitespeedio/grafana-bootstrap/

or just use the docker compose as described in the docs:
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-5-minutes

Hope that will help you!

Best
Peter

**Comment by softwareklinic** [comment]
Also, map volume for your graphite and grafana if u are using docker...
