### ISSUE TITLE
On my AWS instance - docker pull hangs/fails

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1334]
It gets stuck at this point... 

Trying to pull repository docker.io/sitespeedio/sitespeed.io ... latest: Pulling from sitespeedio/sitespeed.io
58488e45273c: Extracting [==================================================>] 49.87 MB/49.87 MB
25810b66099e: Download complete 
6571ba684f54: Download complete 
6ed49a73d8f0: Download complete 
c53777cbfc31: Download complete 
801f200083c1: Download complete 
8e363283c1ac: Download complete 
b06ad8a82df9: Download complete 
f6311292f4f5: Download complete 
b463b2fe3acc: Download complete 
19da1042ebf0: Download complete 
9fb74508f7b8: Download complete 
8778f153fe90: Download complete 
233c15313302: Download complete 
1a9b3d561280: Download complete 
028ab4283ad4: Download complete 
36cd6006cfe7: Download complete 
eaf41198b6b7: Download complete 
38d43a3daa7c: Download complete 
1d1813bc7e4b: Download complete 
7d22ee109701: Download complete 
3bf5dc895cfa: Download complete 
41f92c7f5306: Download complete 
4949cc3a2a52: Download complete 
a6d9b5cadf52: Download complete 
343f70b55c64: Download complete 
200975a7ca25: Download complete 
c30d7070d412: Download complete 
09661ca40303: Download complete 
92745e7219a1: Download complete 
ac90650c137a: Download complete

**Comment by soulgalore** [comment]
This is a docker hub or Amazon problem, can you try again?

**Comment by softwareklinic** [comment]
yes im positive its either AWS or Docker... something related to kernel probably maybe Redhat --- just wanted to post here to see if u or someone have any thoughts around it...

**Comment by beenanner** [comment]
@softwareklinic  I'll try to spin up a Redhat instance in my AWS account and see if I can reproduce. I've mostly stuck with Xenial instances and haven't had any issues.

**Comment by beenanner** [comment]
@softwareklinic are you using the latest version of docker? Closing as I don't believe this is sitespeed.io specific. Though it is interesting to know about these issues you are running into with RHEL and Docker, so feel free to add additional info to this thread as it may help others in the future. :-)
