### ISSUE TITLE
Problems with a throttled the connection

### ISSUE THREAD

**Issue by Ixl123** [sitespeedio/sitespeed.io#1339]
Hi everyone,

first of all thank you for this open source tool! :)

I have downloaded and run the docker compose file with the dashboard and all the other tools on a virtual server instance which runs ubuntu 16.04.

Everything works as expected, except when I try to throttle the connection speed. I get really unrealistic results when I do so. I use the default Tsproxy to throttle the connection. For example, when I try to throttle the connection to a 3G network my site fully loads in over 1 minute but when I run the same test on https://www.webpagetest.org/ my site needs 18 seconds to load. 

To reproduce the issue:

1. Download the docker compose file
```curl -O https://raw.githubusercontent.com/sitespeedio/sitespeed.io/master/docker/docker-compose.yml``
2. Start the service
```docker-compose up```
3. Run a test e.g. 
```docker-compose run sitespeed.io https://www.google.de  --graphite.host=graphite```
4. Run a second test with a throttled connection
```docker-compose run sitespeed.io https://www.google.de  --graphite.host=graphite -c 3g ```
5. Compare the results with  https://www.webpagetest.org/

Am I missing something? Is there something I have to consider using the throttled connection configuration option?

Best regards,
Jacob

**Comment by soulgalore** [comment]
Hey @Ixl123 thanks for the kind words :)

Yes I experience the same thing with TSProxy, I've open a issue https://github.com/WPO-Foundation/tsproxy/issues/10 in TSProxy but haven't been able add data so I can show it to Pat. If you have some examples, it would super if fill in that info.

We use the tc-engine on our Docker containers when we run dashboard.sitespeed.io, that gives more realistic values even though it is not perfect. I think we have something in the docs for recommendation using tc for now in Docker but it can be clearer.

To run tc, you just add <code>--browsertime.connectivity.engine tc</code> and it will use linux tc. However it will have the same up/download speed so it is not perfect but better than ts righ now.

**Comment by Ixl123** [comment]
Hi @soulgalore ,

thanks for your fast response. 

When I provide the ```--browsertime.connectivity.engine tc``` option I am not able to set a ```--browsertime.connectivity.profile```. When I try to i get this error message:

```TypeError: Cannot read property 'device' of undefined
    at Object.module.exports.set (/usr/src/app/node_modules/browsertime/lib/support/connectivity.js:86:42)
    at Engine.start (/usr/src/app/node_modules/browsertime/lib/core/engine.js:59:25)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:75:19)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:123:27)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by soulgalore** [comment]
can you check that you run sitespeed.io 4.0.7? we missed updating the compose file sonit runs an old beta until today when I updated.

Best
Peter

**Comment by Ixl123** [comment]
Thx Peter the update has resolved the issue.

**Comment by Palgie** [comment]
+1 on this issue.

I noticed the WPO-Foundation/tsproxy#10 wasn't resolved, any recommendations for more realistic results?

I'm also noticing a simple test of 5 or 6 URLs can take over an hour to complete with profiles set to 3g.

**Comment by soulgalore** [comment]
@Palgie yes, please use tc and our Docker containers. There's something strange going on with Selenium and TSProxy, I havenät been able figure out what yet. From 4.1 tc will be default when running Docker.

**Comment by soulgalore** [comment]
Do be clear set <code>--browsertime.connectivity.engine tc</code> and it will have more realistic result.

**Comment by Palgie** [comment]
@soulgalore Lovely thanks Peter! Alternative engine is handling this much better.

**Comment by soulgalore** [comment]
Closing this, please use https://www.sitespeed.io/documentation/sitespeed.io/browsers/#change-connectivity.
