### ISSUE TITLE
Mobile score for PageSpeed Insights

### ISSUE THREAD

**Issue by krukru** [sitespeedio/sitespeed.io#1340]
PageSpeed Insights has two types of scores, one for a desktop and one for a mobile client.

I am unable to find if sitespeed can grab the mobile score or just uses the desktop score. 
Running sitespeed with --mobile does not help, but would be great if --mobile returned mobile gpsi score and advice.

**Comment by soulgalore** [comment]
Yes lets us add it on the 2do, the GPSI integration hasn't got much love.

**Comment by beenanner** [comment]
Seemed fairly straight forward, so did a quick implementation via #1342

**Comment by beenanner** [comment]
Closing as this is in master and will be in the next release. Thanks for reporting @krukru!
