### ISSUE TITLE
Writing to multiple graphite servers??

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1343]
Is it possible to write to multiple graphite hosts -- at the same time... i want to have a backup of the data...

**Comment by softwareklinic** [comment]
i mean can i use --graphite.host multiple times for same run

**Comment by soulgalore** [comment]
no you can't but I think there's other ways of solving that on the graphite side.

**Comment by softwareklinic** [comment]
ok no worries for now :) will need sometime to dig on how to replicate graphite...

**Comment by deejay1** [comment]
@softwareklinic just put a carbon-relay in front of it and replicate the data there
