### ISSUE TITLE
What is the solution to HAR export error from firefox - timeout

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1345]
[2016-11-23 07:59:03] Couldn't generate the HAR from Firefox from the HAR Export Trigger.
[2016-11-23 07:59:03] ScriptTimeoutError: Timed out
    at WebDriverError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:27:5)
    at ScriptTimeoutError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:203:5)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/

**Comment by softwareklinic** [comment]
--browsertime.timeouts.script 80000

found it

**Comment by soulgalore** [comment]
@softwareklinic did it work for you? then we should increase the default timeout limit. I got the impression before that theres a bug in the HAR generation i Firefox so that causes a problem maybe have the timeout to low?

**Comment by softwareklinic** [comment]
running the test....

**Comment by jangrewe** [comment]
Works for me with these versions:

```
Mozilla Firefox 50.1.0
[2017-02-02 10:52:19] Versions OS: linux 4.8.0-34-generic nodejs: v6.9.1 sitespeed.io: 4.3.9 browsertime: 1.0.0-beta.23 coach: 0.30.4
```

**Comment by jangrewe** [comment]
I spoke too soon... it only works if i do 1 run.

**Comment by soulgalore** [comment]
Hey @jangrewe can you show me how you run and what kind of error you get (was it the same script timeout error?)? Think the [HAR Export Trigger](https://github.com/firebug/har-export-trigger) could have problems with some URLs?

**Comment by jangrewe** [comment]
Sure @soulgalore, here's my command line:

```
docker run --privileged --shm-size=512m --rm -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io --video --speedIndex --gpsi.key "<secret>" --graphite.host 172.17.0.1 -n 3 -b firefox --browsertime.timeouts.script 80000 --firstParty ".*quazer\.com" --outputFolder "./reports/quazer.com" https://quazer.com/
```

**Comment by soulgalore** [comment]
Had a quick look, could it be when the video is playing that the HAR export doesn't work? We use the har-api-ready event and  I think that the event isn't fired:  https://github.com/firebug/har-export-trigger/wiki/Examples#har-api-ready

I'm not familiar with the code for HAR export trigger, If you have time it would be super if you could report the bug to the project [here](https://github.com/firebug/har-export-trigger/issues/new).

Best
Peter

**Comment by jangrewe** [comment]
Yup, just opened an issue with them (see above). =)
