### ISSUE TITLE
The folder names in sitespeed-result are by domain name

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1347]
Until the alpha 4.0 --- the folder names were based on the TEXT file names... 

if all my urls are in e.g. MYURLLIST.txt --- it would create a folder called MYURLLIST_TXT in the sitespeed-result folder...

but now its just putting it all under domain name... which is very weird... i have multiple files --- for different urls alll for same domain... now i cannot distinguish the results from one file or another...

urgent help needed...

**Comment by softwareklinic** [comment]
Never mind --- i fixed it using --outputFolder --- and appending date/time stamp

**Comment by softwareklinic** [comment]
inside cron -- --outputFolder sitespeed-result/VZWTrack_Mobile_GNexus/$(date +\%Y-\%m-\%d-\%H-\%M-\%S)

**Comment by prashanth-sams** [comment]
> if all my urls are in e.g. MYURLLIST.txt --- it would create a folder called MYURLLIST_TXT in the sitespeed-result folder...

I am getting the same issue now; so, I run like this
```
docker-compose run sitespeed.io --graphite.host=graphite --budget.configPath budget.json --multi https://www.website1.com https://www.website1.com
```

But, doing this is not a good idea; is there a workaround for this? or how this was solved?

**Comment by soulgalore** [comment]
Hi @prashanth-sams he used https://github.com/sitespeedio/sitespeed.io/issues/1347#issuecomment-262646954 where he configured the result folders from the outside.

Best
Peter

**Comment by prashanth-sams** [comment]
@soulgalore it worked! Thank you :)
