### ISSUE TITLE
asp.net urls with same base url combined to a single url rather than multiple

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1352]
I am testing on a asp.net site and certain screens are facets of the same code. For example I have 3 URLs:

https://domain.com/home.asp?Category=Dinosaurs&Section=NonFiction
https://domain.com/home.asp?Category=Dinosaurs&Section=Fiction
https://domain.com/home.asp?Category=Agriculature&Section=Fiction

All three URLs end up being put in the same Page

https://domain.com/home.asp

Is there anything I can do to avoid URLS from being combined by their base URL and trend based on the provided URLs from the .txt file?

![2016-11-28_10-20-23](https://cloud.githubusercontent.com/assets/22225816/20675004/ddb2402a-b558-11e6-800f-27e4c9c81c28.png)

**Comment by tobli** [comment]
Hi @ppcuenca, use --graphite.includeQueryParams to get longer metrics keys!

**Comment by ppcuenca** [comment]
Exactly what I was looking for, thank you!
