### ISSUE TITLE
capturing single step functional performance data

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1354]
Hi,

I realize sitespeed.io does not yet have the functionality to record multi step, but is it possible to record a single step function?

For instance is it possible to use the prescript to "create a document" or "sign in" and capture the performance information for that single step and trend in grafana?

If we cannot do it through the tool automatically, is there a way to manually export the same functional step performance data after collecting the .har data (manually)to send to grafana?

Thanks,

**Comment by soulgalore** [comment]
Hey @ppcuenca ,
right now you can only measure one access out of the box, so for example if you want to test performance of a page when you are logged in, you log in the user in the preScript and then access the page that you want to measure. There's no way to measure the actual login script action, but you can hack some thing yourself in the preScript (like collect navigation timting data etc, but we probably need change the flow to make it easier to use (like collect those values and make sure you send them to your datasource).

>If we cannot do it through the tool automatically, is there a way to manually export the same functional step performance data after collecting the .har data (manually)to send to grafana?

Not sure how you mean?

Best
Peter

**Comment by ppcuenca** [comment]
Hi,

Thanks, being able to collect functional performance data would be fantastic and I think many people would find that valuable.

Regarding the manual export. My thought was using Chrome browser itself, manually to collect .har data and sending it to the same datasource to be trended on Grafana.

Do you think this would be feasible?

Thanks,
Phil

**Comment by soulgalore** [comment]
Closing and moving the discussion to https://github.com/sitespeedio/sitespeed.io/issues/1827
