### ISSUE TITLE
Custom video player design

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1356]
The current version of sitespeed.io uses the default HTML5 video player. That's ok, but it would be super cool if we could have a custom made version with:
* play button
* playbackRate
* fullScreen

And some nice skin.

**Comment by ppcuenca** [comment]
Apologies for the silly question, but which function uses this video player function?

**Comment by soulgalore** [comment]
It not a silly question, sorry for beeing unclear. Today we use standard HTML5 so each browser will define it own look and feel. So it would be nice to add some CSS our own and integrate the buttons we want (right now the playbackRate button is outside of the player).

**Comment by ppcuenca** [comment]
To be a bit more specific, what portion of the report has a video playback function? Is this related to WPT?

**Comment by soulgalore** [comment]
Use latest version, run: 
<pre>$ docker run --privileged --shm-size=1g --rm sitespeedio/sitespeed.io:4.1.0 --video --speedIndex -c cable https://www.sitespeed.io/
</pre>
And browse to the Browsertime tab for a specific page and you will see it there.

**Comment by ppcuenca** [comment]
Very cool, love the new feature!

**Comment by soulgalore** [comment]
I guess this is fixed now when we uses video.js.
