### ISSUE TITLE
how to run a sitespeed docker container with prescript files

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1357]
I am quite new to docker and I currently have a jenkins build that runs the docker sitespeed container but I have not been able to get the js script and url.txt file to be incorporated to my test run. All of this works smoothly on my local machine without using docker.

I have been trying to do some research but I am still getting the "Error: ENOENT: no such file or directory, open 'url.txt'"

I tried using the -v docker flag to specify which directory the files are in (jenkins workspace via -v "$(pwd)") Where the commands are being ran, but still not working.

Any thoughts on what I may be doing wrong?

**Comment by soulgalore** [comment]
@ppcuenca yes you need to use the flag <code>-v</code>. Doing that, you will mount a dir/file outside the container to the inside of the container.

If you use <code>-v "$(pwd)":/sitespeed.io</code> that means that your current dir will be mounted inside as /sitespeed.io. But you can use the full path to whatever directory you want. If you have a urls.txt file there, you can find that inside the container by /sitespeed.io/urls.txt.

I can add better examples here later: https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes

**Comment by ppcuenca** [comment]
This did the trick thanks!
