### ISSUE TITLE
Improve reporting and repeat testing of PWAs 

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1362]
Let's spend some time on improving the reporting on PWAs

**Comment by beenanner** [comment]
See as possible related: https://github.com/sitespeedio/browsertime/issues/121

**Comment by soulgalore** [comment]
@beenanner can you write down more what you want us todo? :)

**Comment by beenanner** [comment]
Will do. :-)

**Comment by beenanner** [comment]
Closing I think with recent additions we have a good basis. We can open new requests if when we have specifics to implement.
