### ISSUE TITLE
possible to change metrics in slack?

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1365]
Hi,

I hooked up my tests to a slack channel and it was working well! Great feature. Is it possible to change the metrics that are being reported to the channel?

![image](https://cloud.githubusercontent.com/assets/22225816/20984369/e0cfa8d8-bc8d-11e6-95a4-b04b5601bef6.png)

The above defaults are great but would love to swap some out or add "FullyLoaded"

How might I do this if it is possible?

Thanks,

**Comment by soulgalore** [comment]
Hey @ppcuenca I hardcoded the current metrics to be able to ship the functionality 😱 

I totally agree it should be configurable or at least we want to focus on some more metrics. I wanna add SpeedIndex, first/last visual change and then also wanna make it configurable to choose which metrics that makes it an success or not (now it's always coach score) but it should be configurable + the limit. I could probably do this the coming weeks.

**Comment by soulgalore** [comment]
I've added fully loaded, will come in the next release next week.
