### ISSUE TITLE
prescript does not appear to be running but sitespeed not complaining

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1368]
I am running sitespeed in docker on aws centos box and kicking off via jenkins. I am not getting any complaints from the test or jenkins but the test isn't collecting the perf metrics.

The script seems to be working it is an exact cut and paste from my local and no complaints in debug mode.

![image](https://cloud.githubusercontent.com/assets/22225816/21017851/be1bf390-bd38-11e6-8523-144cb054da2d.png)

As you can see there is a huge difference from when it was working as expected and right now. I am using the same exact jenkins commands and I copied the previous node config settings so I am led to believe there is something wrong with either docker or sitespeed...or maybe the network.

sudo docker run --rm -v /home/jenkins/workspace/sitespeed:/sitespeed sitespeedio/sitespeed.io --preScript /sitespeed/login.js /sitespeed/url.txt -b firefox --debug --graphite.host 101.253.111.147 --grahpite.port 2003 -p http://proxy-us-aws-nonprod.zyx.com:3128 --graphite.includeQueryParams

The tests are ingesting the URL file just fine according to the debug, and there are no complaints with the prescript but when I download a copy of the report the screenshot of all the pages is the landing page and never actually logs in. 

Just to further debug the issue I intentionally broke the prescript file and the test did in fact fail.

Any insights would be appreciated.

Thanks!

**Comment by tobli** [comment]
Hmm, this looks like it could be a timing issue. The first thing to check is that the prescript actually returns a Promise for the login actions. Since the selenium api is asynchronous sitespeed.io needs to know how to wait for the login to succeed before continuing. It does this by waiting for any Promise returned by a prescript to resolve. You could debug by logging in a then()-function at the end of the returned Promise chain.

If this isn't the issue I could have a look at the prescript. If you need to share it privately you could email me at tobias@lidskog.se.

**Comment by ppcuenca** [comment]
Hi Tobias,

I sent you a lengthy email  attempting to debug or isolate the issue. The problem appears to be the script is not being ran. In fact, I removed the --prescript flag and kept the "inside" urls and the report generated is exactly the same result as the issue on aws.

Not sure if this would have any effect, but I do seem to have a stale container on the aws instance. 
59e5b3e39efb        sitespeedio/sitespeed.io   "/start.sh --preScrip"   2 days ago          Up 2 days                               desperate_yalow

Report generated shows different URLs but same results as landing page.

![image](https://cloud.githubusercontent.com/assets/22225816/21027067/3e2d29e0-bd5d-11e6-8320-0bbe44054d87.png)

**Comment by cambiph** [comment]
I seem to have the same problem.
My setup is a Jenkins connected to a RHEL 7 machine running docker.
Jenkins runs the following shell-script:

```
docker run --privileged -v ${WORKSPACE}:/sitespeed.io sitespeedio/sitespeed.io --prescript /sitespeed.io/login.js --outputFolder output --budget /sitespeed.io/budget.json --budget.output junit --video <urls> -n 3 -b firefox 
```

The test runs but if I inspect closely, the preScript is never run.
Both budget.json and login.js are in my jenkins workspace.
When I resolve ${WORKSPACE}/login.js on the machine itself, it returns the correct file.
When I change the filename to something else, to force an error message stating that login.js is missing, I get nothing.
So to me it seems that the login.js is not working.
It is mounted to the volume, right? That's what -v ${WORKSPACE}:/sitespeed.io is for

**Comment by soulgalore** [comment]
@cambiph I think the problem the CLI is case sensitive and it should be <code>--preScript</code>. We run yargs without warning about parameters to be able to pass them to browsertime etc, maybe there's a better way to fix that.

**Comment by cambiph** [comment]
@soulgalore correct, I missed that.
Using --preScript instead of --prescript seems to work.
With the correct case I now get the error that I was expecting.

**Comment by soulgalore** [comment]
This seems to work.
