### ISSUE TITLE
disable html report still configurable?

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1369]
Hi,

I need to be able to disable the html report for our CI pipeline. I saw this config was available previously in https://www.sitespeed.io/3.x/configuration/

But how do I disable it in the latest version? I saw below but not sure it is referring to the html report or something else and if it is not sure what value to set.

--plugins.disable  Disable a plugin. Use it to disable generating html or screenshots.       

Thanks for the help!

**Comment by soulgalore** [comment]
Hey @ppcuenca 
yes you need to disable the html plugin, example here:
https://www.sitespeed.io/documentation/sitespeed.io/plugins/#disable-a-plugin

Best
Peter

**Comment by ppcuenca** [comment]
Thank you!
