### ISSUE TITLE
Sitespeed hangs often

### ISSUE THREAD

**Issue by deejay1** [sitespeedio/sitespeed.io#1370]
We're running sitespeed continually through cron and docker, unfortunately every now and then (usually every day) it hangs leaving lots of processes behind usually in the Zombie state

```
4365b3cc4b04        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   About an hour ago   Up About an hour                        gigantic_yalow
e257d2192e5f        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   About an hour ago   Up About an hour                        serene_panini
e437165526d9        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   4 hours ago         Up 4 hours                              berserk_mcnulty
0c4b0d5a47ff        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   4 hours ago         Up 4 hours                              reverent_brattain
136ec34baabe        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   4 hours ago         Up 4 hours                              high_leakey
930e57249e05        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   4 hours ago         Up 4 hours                              focused_ritchie
322acc345778        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   4 hours ago         Up 4 hours                              boring_roentgen
c5ff412b105d        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   7 hours ago         Up 7 hours                              compassionate_ardinghelli
34d8f30637dd        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   10 hours ago        Up 10 hours                             admiring_kare
0f179eba6681        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   10 hours ago        Up 10 hours                             distracted_albattani
f2408114cb7c        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   10 hours ago        Up 10 hours                             thirsty_jennings
3069748f0bbe        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   10 hours ago        Up 10 hours                             reverent_yalow
4452b7ed18e7        artifactory.allegrogroup.com/sitespeedio/sitespeed.io:4.0.7   "/start.sh http://all"   3 days ago          Up 3 days                               naughty_shaw
```
26315 ?        Z      0:00 [cat] <defunct>
26316 ?        Z      0:00 [cat] <defunct>
26536 ?        Z      0:00 [cat] <defunct>
26537 ?        Z      0:00 [cat] <defunct>
27048 ?        Z      0:00 [cat] <defunct>
27049 ?        Z      0:00 [cat] <defunct>
28373 ?        Z      0:00 [cat] <defunct>
28374 ?        Z      0:00 [cat] <defunct>
29318 ?        Z      0:00 [cat] <defunct>
29319 ?        Z      0:00 [cat] <defunct>
30179 ?        Z      0:00 [cat] <defunct>
30180 ?        Z      0:00 [cat] <defunct>
31239 ?        Z      0:00 [cat] <defunct>
31240 ?        Z      0:00 [cat] <defunct>
root@node-sitespeed1:~# ps ax | grep Z | grep cat | wc -l
119
```

When viewing the docker log, I see that it probably hangs on sending this information to graphite

```
[2016-12-06 09:21:17] Send data to Graphite graphite.example.com:2003
```

Any ideas?

**Comment by jpvincent** [comment]
Hi
It happens to me frequently on my dev machine (MacOS) and is typically resolved by restarting the Docker engine (1.12.3 for me). I had the idea of incriminating Docker while reading some rants on the web about it saying from time to time it would lose the network …

**Comment by soulgalore** [comment]
Hey @deejay1 
hmm, I wonder. How many URLs + runs do test per time and how frequent do you test (thinking how many metrics that graphite will send=

Best
Peter

**Comment by deejay1** [comment]
@soulgalore Well, right now we have 6 URL-s with one run per URL, spanned over 2 worker hosts which run every 3 minutes (each worker host houses 7 runners with a timeout of 10 minutes for a job). Our graphite instance can handle that easily (as right now we're getting about 6 million metrics per minute on the cluster).

One reason might be that it runs through a load balancer, maybe adding a timeout to the connection would help? AFAIK the default is no timeout (https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback) although I'll try to tweak some TCP kernel settings tomorrow as the double NAT issue might be a problem here (one SNAT on the load balancer and the other on the docker host)

@jpvincent yeah, restarting the VM helps for a while but it's a little bit hard, for the moment I'll just kill the docker containers running longer than 10 minutes (the worker timeout)

**Comment by soulgalore** [comment]
@tobli do you have any input?

**Comment by deejay1** [comment]
Also from todays batch of "hung" containers, there a lots of similar issues:
```
Google Chrome 54.0.2840.100 
Mozilla Firefox 50.0
[2016-12-12 03:36:33] Versions OS: linux 4.4.0-53-generic nodejs: v6.9.1 sitespeed.io: 4.1.2 browsertime: 1.0.0-beta.13 coach: 0.29.0
[2016-12-12 03:36:34] Starting chrome for analysing http://allegro.pl/listing/user/listing.php?us_id=1680 1 time(s)
[2016-12-12 03:36:34] Testing url http://allegro.pl/listing/user/listing.php?us_id=1680 run 1
[2016-12-12 03:40:08] Error: ENOENT: no such file or directory, rename '/sitespeed.io/ee2737c24f874f599b86f6b7ae54df8c/7844a621-446d-4f72-b662-0996c4e45b5b/video/tmp.mp4' -> '/sitespeed.io/ee2737c24f874f599b86f6b7ae54df8c/7844a621-446d-4f72-b662-0996c4e45b5b/video/0.mp4'
    at Error (native)
From previous event:
    at ffprobe.run.then.then (/usr/src/app/node_modules/browsertime/lib/support/video/scripts/finetuneVideo.js:24:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-12 03:40:08] Render HTML for 1 page(s) ```

**Comment by tobli** [comment]
Hi! What sitespeed options are you using? It seems from the log that video and/or speedIndex is turned on. Is this always the case for he hanging containers? Video is the newest big feature addition (meaning it hasn't seen as much feedback from broad usage and fine tuning) and it also spawns external processes for the video recording and processing.

**Comment by deejay1** [comment]
Options are
```yaml
command: "'{url}' --video -d 0 -n 1 --speedIndex --outputFolder /sitespeed.io/{prefix} --graphite.host {graphite_host} --graphite.namespace '{graphite_namespace}' --graphite.includeQueryParams=true --metrics.filter '*+'"
```
(things in braces are replaced with actual data)
Another case where it seems to hang on an error is:

```
Google Chrome 54.0.2840.100 
Mozilla Firefox 50.0
[2016-12-12 09:25:24] Versions OS: linux 4.4.0-53-generic nodejs: v6.9.1 sitespeed.io: 4.1.3 browsertime: 1.0.0-beta.13 coach: 0.29.0
[2016-12-12 09:25:25] Starting chrome for analysing http://allegro.pl/odziez-obuwie-dodatki 1 time(s)
[2016-12-12 09:25:25] Testing url http://allegro.pl/odziez-obuwie-dodatki run 1
[2016-12-12 09:30:30] Catched a WebDriverError [timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.062
  (Session info: chrome=54.0.2840.100)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-53-generic x86_64)]. Try one more time.TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.062
  (Session info: chrome=54.0.2840.100)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-53-generic x86_64)
```

**Comment by soulgalore** [comment]
I think there are a couple of different errors here. First using <code>--metrics.filter '*+'"</code> you will send a massive amount of metrics and if your site has adds, there will be a lot creates in Graphite, just want to double check that you are aware of that. 

As @tobli was talking, video is the latest, do you also see a lot of hanging FFMPEG processes? To debug I would start by skipping metrics.filter and/or video to see if there's any difference.

**Comment by soulgalore** [comment]
This should work now. Closing, let us know if this is still an issue.
