### ISSUE TITLE
sitespeed analysis is partial after the preScript

### ISSUE THREAD

**Issue by pixlab** [sitespeedio/sitespeed.io#1376]
Hi,

I'm not able to understand the reasons of this, but the report summary doesn't have all requests....if I navigate the website with chrome in the network panel I can see 200 and more request; but on sitespeed report there are only 17. It happens only when it runs a preScript before, it's my preScript(it's your example with some changes):

```
module.exports = {
    run(context) {
        return context.runWithDriver((driver) => {
                // Go to Wikipedias login URL
                return driver.get('urlToLogin')
                    .then(() => {
                    // You need to find the form, the login input fiels and the
                    // password field. Just add you name and password and submit the form
                    // For more docs, checkout the NodeJS Selenium version
                    // http://selenium.googlecode.com/git/docs/api/javascript/index.html

                    // we fetch the selenium webdriver from context
                    var webdriver = context.webdriver;

        // before you start, make your username and password
        var loginButton = driver.findElement(webdriver.By.className("loginButton"));
        loginButton.click();
        driver.sleep(1000);
        var userName = 'xxx';
        var password = 'xxx';
        var loginForm = driver.findElement(webdriver.By.id('loginForm'));
        var loginInput = driver.findElement(webdriver.By.id('loginUsername'));
        loginInput.sendKeys(userName);
        var passwordInput = driver.findElement(webdriver.By.id('loginPassword'));
        passwordInput.sendKeys(password);
        loginForm.submit();
        driver.sleep(30000);
    });
    })
    }
};
```

and I launch sitespeed over an internal url and the login it's ok because I see the page is loading, but only the header and then the browser is closed before the page could load completely.

thanks in advance
Roberto

**Comment by soulgalore** [comment]
Hey @pixlab 
first about the requests: wanna check so they aren't cached (loaded by the access to login page and then cached for the second page)?

So the actual page is loaded but ends to soon? Can it be that the loadEventEnd is fired and the rest of the page is loaded after? You can configure when to end a test by configuring the javascript that decides when your page is finsished: https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test

Hope that helps!
Peter

**Comment by pixlab** [comment]
@soulgalore I don't believe all requests for css or javascript files are cached....because we have some different files between login page and logged page....and the report has 0 css files requested and 0 javascript files. But what if the resources was cached?

I've tried with the example in the page you suggest me, and the page wait 10 seconds but the view is partial again...the result is the same
Could some iframe lock the process of analysis?

thanks :)

**Comment by soulgalore** [comment]
>  But what if the resources was cached?

Yes agree, that reporting isn't perfect.

I think @tobli has a better way of handling the login, lets see if we can update the example soon.

**Comment by arnaudvalle** [comment]
Hi @soulgalore - I'm facing a similar issue where my login page and page to be analysed share some JS / CSS files. The data I end up getting in my dashboard seem incomplete (because they're cached as I understand from your comments above).

Is there a way to avoid / disable that 'warm cache' at all?

**Comment by soulgalore** [comment]
Hey @arnaudvalle hmm maybe there could be away with chrome cli options or firefox preferences to totally disable the cache? not sure and need to test that out. You can see all params you can send to Browsertime here: https://github.com/sitespeedio/browsertime/blob/master/lib/support/cli.js

and then using them in sitespeed would be adding browsertime so sending Chrome cli args would be <pre>--browsertime.chrome.args</pre>

And then you need look up all CLI args for Chrome:
http://peter.sh/experiments/chromium-command-line-switches/

Please let us know if you find a solution that works!
Best
Peter

**Comment by arnaudvalle** [comment]
Great stuff, thanks for the quick answer. Seems like adding the following is already much closer (though not perfect yet) to what I was expecting:

`--browsertime.chrome.args disk-cache-dir=/dev/null`

I'll keep experimenting and will keep you posted.

**Comment by arnaudvalle** [comment]
For info, I couldn't really find the exact same numbers in the sitespeed reports and in a manual test within chrome > network tab but most of the difference seems to be because of Google Analytics calls and @font-face issues (which, looking at the repo issues, seem to be known issues).

**Comment by soulgalore** [comment]
hey @arnaudvalle there shouldn't be any request missing if you use Chrome/Firefox. If you have that then it's a bug. If you have responses arriving late (later than pageLoad + 2 sec) you can change when to end the test by https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test. Would be super if you could add an issue where you show how to reproduce so we can have a go at it.

Thanks 
Peter

**Comment by arnaudvalle** [comment]
hey @soulgalore - I did see that example in your doc and have applied it already to the command I'm launching sitespeed with. I'm setting up a test page for you and will create an issue once it's all ready. Thanks again for your help with this!

**Comment by arnaudvalle** [comment]
note: in the latest version of sitespeed (4.4.2), I had to add `--browsertime.chrome.args no-sandbox` as well (presumably because otherwise my disk-cache-dir overwrites some default chrome arg you're passing), so in the end it needs:

`--browsertime.chrome.args no-sandbox --browsertime.chrome.args disk-cache-dir=/dev/null`

**Comment by arnaudvalle** [comment]
for info, I've created an issue for my 'missing' requests here: https://github.com/sitespeedio/sitespeed.io/issues/1467

**Comment by soulgalore** [comment]
great. I'm thinking maybe the disk cache fix isn't enough because Chrome will also cache in memory?

**Comment by arnaudvalle** [comment]
Just for reference, I tried adding some extra flags but with no luck either:

`--browsertime.chrome.args disk-cache-size=1 --browsertime.chrome.args media-cache-size=1`

**Comment by soulgalore** [comment]
We should add better docs and a better example for how to wait for the login to happen (and probably a change in BT?).

**Comment by soulgalore** [comment]
This is done since ... a long time.
