### ISSUE TITLE
how to include landing page in report?

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1380]
Hi,

How do I include the homepage/landing screen in the html report? 

I can include the metrics in grafana by doing a separate run without the prescript for the home/landing screen, but obviously this would mean two separate reports.

Thanks,

**Comment by soulgalore** [comment]
Hey @ppcuenca , there's no way to do that today.

Best
Peter

**Comment by ppcuenca** [comment]
Thanks for the quick reply Peter.
