### ISSUE TITLE
Grafana dashboards not showing WPT Metrics ?

### ISSUE THREAD

**Issue by nagamallala** [sitespeedio/sitespeed.io#1383]
Hi ,
I am using latest Docker 4.0 
using the docker compose as described in the docs:
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-5-minutes
 able to get the page and site summary metrics but unable to find the WPT summery report.
the link of my dashboard is http://127.0.0.1:3000/dashboard/snapshot/r1FP6Ww5YR2dbU61v8kh1KJGscuzJgOE

running the below command 
docker run --privileged --shm-size=512m sitespeedio/sitespeed.io https://www.wyndhamhotels.com  -b chrome  --graphite.host 192.168.6.3

Thanks

**Comment by soulgalore** [comment]
Hey @nagamallala to get data from WebPageTest you need to run WebPageTest! You can read how to do that in the docs: https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/

Best
Peter

**Comment by tobli** [comment]
Closing this as it's duplicated by #1388

**Comment by nagamallala** [comment]
Hi Peter sorry for trouble you

this is the command I was running for WPT 

docker run sitespeedio/sitespeed.io --webpagetest.host https://www.webpagetest.org --webpagetest.key A.383700eab8f1fa78e881b0707949b04a https://www.wyndhamhotels.com  -b firefox --graphite.host 10.187.31.112

getting the below report but unable to see the result in grafana

docker run sitespeedio/sitespeed.io --webpagetest.host https://www.webpagetest.org --webpagetest.key A.383700eab8f1fa78e881b0707949b04a https://www.wyndhamhotels.com  -b firefox --graphite.host 10.187.36.119

<img width="926" alt="screen shot 2016-12-21 at 11 57 50 am" src="https://cloud.githubusercontent.com/assets/24470945/21379609/5c87d260-c775-11e6-8812-57b9c31b7257.png">

please correct me if I am wrong and send me the example command for WPT.

Thanks

Regards,
Naga

**Comment by soulgalore** [comment]
Cool @nagamallala then upgrade to 4.2.1, there was a bug introduced that broke WebPageTest, hopefully 4.2.1 will work better for you!
