### ISSUE TITLE
Compare URLs?

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1386]
One thing that I really miss today is the ability to compare URLs (the same URL with different runs or two or more different URLs). 

It would be something that you would run in your CI tool, making X amount of runs against two different URLs (master branch and your feature branch) and tell us if there's a regression.

* compare videos (merge the two and run them side by side)
* compare waterfalls (huu)
* compare metrics
* compare screenshots

**Comment by jpvincent** [comment]
Do you  mean have a comparison ala webpagetest, in the HTML output ?
On the grafana side, we could easily have a dashboard comparing the same metric over the pages of the same domain

**Comment by soulgalore** [comment]
Hey @jpvincent I just added that issue as reminder to myself, I should have marked it as a placeholder for more info, I'll explain later today what I'm looking for :)

**Comment by soulgalore** [comment]
I think the easiest way to do it is creating a standalone JavaScript pages that fetches multiple HAR files and compare them. We can do it something like this:

Autodeploy compare.html at the root of the domain when deploy to AWS. Add links from each run pointing to that file, so it's easy to start. When you go to the page, you need to add the path to two runs, when you submit the page, we will automatically find the HAR files, pick the run and create the compare output:
* A highlevel comparisson with number of requests, size and a couple of metrics side by side.
* Screenshot and video (add the exact URLs in th HAR so it is super easy (we alos need to add visual metrics we miss that today)
* Use PerfCascade to show the waterfall graphs, best case something like WPT do.
* Shareable URL, and links back to the result page.

What's cool with it is that we can make it generic so it will work with HARs from whatever tool and then add some extra on top for sitespeed.io.

**Comment by soulgalore** [comment]
This done in https://compare.sitespeed.io
