### ISSUE TITLE
Getting issue while installing docker on windows

### ISSUE THREAD

**Issue by nagamallala** [sitespeedio/sitespeed.io#1387]
Hi 

I have downloaded Docker new version. I was trying to install docker on windows getting below error.

 
![image](https://cloud.githubusercontent.com/assets/24470945/21255149/0dabdbd4-c390-11e6-964c-0b4957c366b3.png)

thanks in advance

**Comment by tobli** [comment]
Hi @nagamallala!
For issues with Docker itself please turn to Docker for support. Maybe the Docker Forums (https://forums.docker.com/c/docker-for-windows) can help you out.

/Tobias
