### ISSUE TITLE
Missing WPT data in graphite after successful run

### ISSUE THREAD

**Issue by julrich** [sitespeedio/sitespeed.io#1389]
When running sitespeedio in version 4.2.0, I'm currently unable to get WPT results into either the generated HTML report, nor the connected graphite database. Other data (like _gpsi_) is correctly recorded.

It outputs "Got https://ruhmesmeile.com analysed from wpt.private-instance.com" in the output, which seems to be directly followed by "Send data to Graphite graphite.host:2003". But inside Graphite there are only subdirectories _pageSummary_ and _summary_, with _pageSummary_ having entries _chrome_ and _gpsi_ for the scanned domain, but no _wpt_ anywhere.

Inside the generated result report there's an empty entry `{ "webpagetest": {} }`
 when looking at the Errors tab.

I'm running sitespeedio like this:
```
/usr/bin/docker run --rm \
  --name "sitespeedio" \
  --volume "/var/sitespeedio/data:/sitespeed.io" \
  --privileged \
  --shm-size=512m \
  sitespeedio/sitespeed.io:4.2.0 \
  https://ruhmesmeile.com \
  --browsertime.connectivity.profile "cable" \
  --browsertime.browser "chrome" \
  --browsertime.iterations 3 \
  --browsertime.speedIndex \
  --browsertime.video \
  --crawler.depth 1 \
  --graphite.host "graphite.host" \
  --graphite.port 2003 \
  --graphite.namespace "qa" \
  --gpsi.key "$GPSI_KEY" \
  --webpagetest.host "wpt.private-instance.com" \
  --webpagetest.key "$WPT_KEY" \
  --webpagetest.location "eu-central-1:Chrome" \
  --webpagetest.private "false" \
  --webpagetest.runs 1 \
  --metrics.filter "*+" \
  --outputFolder "/sitespeed.io/result" \
```

I've also attached the logfile of a number of runs, including some with more verbose output, if that helps:
[sitespeed.io.log.txt](https://github.com/sitespeedio/sitespeed.io/files/664619/sitespeed.io.log.txt)

**Comment by julrich** [comment]
Let me know, if I can be of more help to analyse this! :)

**Comment by tobli** [comment]
It'd be very helpful if you could run with `--debug -v` and share that (privately via email if needed).

**Comment by julrich** [comment]
Sure, email would be nice for the log. Would spare me the work to remove parts. Where can I mail you?

**Comment by tobli** [comment]
peter [AT] soulgalore.com and tobias [AT] lidskog.se

**Comment by julrich** [comment]
Combining `--debug` with `-v` leads to a really huge number of lines with just a single digit on them for me. Is that to be expected?

Just sent the mail with the log (8mb zipped) attached.

**Comment by tobli** [comment]
Thanks! Well… logging is an area with room for improvement. ;-)

**Comment by tobli** [comment]
btw, the single digits is probably image data being serialised. So yeah, expected but not very practical.

**Comment by tobli** [comment]
I had a look, and it looks like there's some error either parsing the initial data from WPT, or calling in the API call to WPT to get the Har file. If you could, please run with `-vvv` (no `--debug this time`) and send that log. Will probably be really large that too, but include slightly different data. Thanks!

**Comment by soulgalore** [comment]
I got a fix rolling out in a couple of minutes, will describe the problem then!

**Comment by julrich** [comment]
Okay, I've uploaded the log with only `-vvv`, too. Let me know if you still need it. But doesn't sound like it! :) Thanks!

**Comment by soulgalore** [comment]
Hey @julrich thanks for reporting 4.2.1 rolling out now, would be there in a couple of minutes. I introduced a bug when I added support for custom metrics in WebPageTest. And we just swallowed the error in the code, so the test in Travis looked ok.

**Comment by julrich** [comment]
No problem! Thanks for the more than quick fix, and the amazing work on sitespeed.io in general! Looking forward to further integrating it into our workflow.

**Comment by julrich** [comment]
Works like a charm on 4.2.1 now, thanks again!

**Comment by soulgalore** [comment]
great, sorry again and thanks for the kind words :)
