### ISSUE TITLE
Grafana setup issue using docker-compose up

### ISSUE THREAD

**Issue by narayanachilamkuri** [sitespeedio/sitespeed.io#1391]
Hi,
 
I was using sitespeed.io latest version 4.2.1.
I was trying to setup the grafana using 

https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/
Up and running in 5 minutes
but I was getting the below issue while settingup

ERROR: for graphite  Cannot start service graphite: driver failed programming external connectivity on endpoint narayanachilamkuri_graphite_1 (1e79844a643a7f7396e1f9a73353ac6b659d93bbbcb4753cd0286991dce89179): Error starting userland proxy: Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

is there any way to uninstall and reinstall again
 thanks

**Comment by soulgalore** [comment]
hey @narayanachilamkuri you shutdown docker compose with <pre>docker-compose down</pre>. There's something else running on 8080, close it or change that port in the docker compose file (check docker docs for info for ports!)
Best
Peter

**Comment by soulgalore** [comment]
Closing, let is know if this is still an issue.
