### ISSUE TITLE
Does sitespeed.io 4.0 work with IE 11?

### ISSUE THREAD

**Issue by tdmoneybanks** [sitespeedio/sitespeed.io#1392]
Hey!
I did not see anything in the docs related to IE 11 and sitespeed.io 4.0. does it still work with ie?

**Comment by soulgalore** [comment]
Hey @tdmoneybanks it would be super cool to support IE 11/Edge but to do that we need one maintainer that focus on Windows. What missing is a confiuration in Browsertime and sitespeed.io and time to test.

In the last version (3.x), I spent a lot of time just getting my Windows environment working to debug Windows issues, that I could have spent on documenting or building new features and I really wanna avoid that again.
