### ISSUE TITLE
Issue while integrating with Jenkins

### ISSUE THREAD

**Issue by dhanabalanvk** [sitespeedio/sitespeed.io#1396]
Hi Team, I am unable to intgrate sitespeed with jenkin. Its keep on running the test indefinitely.
Jenkin's shell command : 
/usr/local/bin/sitespeed.io http://www.dhanabalan.in
Started by user admin
Building in workspace /Users/Shared/Jenkins/Home/workspace/Sitespeed_Integration
Xvfb starting$ /usr/X11/bin/Xvfb :2 -fbdir /Users/Shared/Jenkins/Home/xvfb-17-7458981030807669688.fbdir
[Sitespeed_Integration] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/hudson3535840100794655923.sh
+ /usr/local/bin/sitespeed.io http://www.dhanabalan.in
[2016-12-24 20:18:04] Versions OS: darwin 16.0.0 nodejs: v7.1.0 sitespeed.io: 4.2.0 browsertime: 1.0.0-beta.18 coach: 0.30.0
[2016-12-24 20:18:04] Starting chrome for analysing http://www.dhanabalan.in 3 time(s)
[2016-12-24 20:18:04] Testing url http://www.dhanabalan.in run 1
keep on loading...!!!!!!!!!!!
Note: When I run the same command in terminal (Mac) its working fine. Attaching the screenshot for your reference
<img width="1254" alt="isssue" src="https://cloud.githubusercontent.com/assets/8679987/21486205/b71f0370-cb75-11e6-8ef6-912bb98b36cf.png">

**Comment by soulgalore** [comment]
Hey @dhanabalanvk thanks for the report! 

You probably checked this already, but just want to make sure, your Jenkins instance can reach internet so you can access the site using curl/wget? Just checking :)

There shouldn't be any magic happening. Can you try switching browsert (<code>-b firefox</code> or even better the Dockerized version (then you can skip xvfb).

Best
Peter

**Comment by dhanabalanvk** [comment]
Thanks @soulgalore !

I did the following this but no luck :(

1. Jenkins instance can reach internet so you can access the site using curl/wget -- **Reachable**
2. -b firefox -- Tried but **same issue** (keep on loading)

**One lucky thing is I tried to connect android device and triggered the build, works fine.**

Now I tried the **Dockerized** version, don't know how to specify the **budget file location** and report generation, Could you please assist me on this?

Thanks,
Dhanabalan Venkitusamy

**Comment by soulgalore** [comment]
Closing, let is know if this is still an issue.
