### ISSUE TITLE
JUnit / TAP reporting is not working

### ISSUE THREAD

**Issue by dhanabalanvk** [sitespeedio/sitespeed.io#1399]
Hi Team,

I am trying to integrate JUnit / TAP report functionality with Jenkin but report files are not generated while running the below command,

$ sitespeed.io https://www.sitespeed.io/ --budget myBudget.json --budget.output junit -b chrome -n 5

**As per the documentation it should create a junit.xml in the outputFolder.**

$ sitespeed.io https://www.sitespeed.io/ --budget myBudget.json --budget.output tap -b chrome -n 5

**As per the documentation it should create a budget.tap in the outputFolder.**

Could you please assist me whether I am missing anything to generate the reports?

Regards,
Dhanabalan Venkitusamy

**Comment by soulgalore** [comment]
Hey @dhanabalanvk thanks for reporting, this is bug (like it is now the the budget file overwrites the budget config) that I introduced a while ago, let me see if I can fix that tomorrow.

Best
Peter

**Comment by soulgalore** [comment]
I tracked it back to an upgrade of yargs. If I revert back to 5.0 it works, when we upgraded 6.x it failed.

**Comment by soulgalore** [comment]
Hey @dhanabalanvk I pushed 4.3.1 now where it works. It was a bad upgrade of yargs that caused the problem, I rolled back and will do a better fix after the holidays.

**Comment by soulgalore** [comment]
this is released and fixed.
