### ISSUE TITLE
Unable to see the metrics in grafana

### ISSUE THREAD

**Issue by narayanachilamkuri** [sitespeedio/sitespeed.io#1404]
Hi 
I was using sitespeed.io from last 3 weeks, using latest one 4.2.1
I was able to see the metrics in garafana till 3days back. But today I ran test, test ran successfully able to see HTML report but unable to see the  metrics in grafana.
I double checked running test without mistake but not getting metrics in grafana.

Please help me out

Thanks

**Comment by narayanachilamkuri** [comment]
Hi Peter,

I setup the grafana by using 
Up and running in 5 minutes
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/

I ran the below command
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:4.2.1 --webpagetest.host https://www.webpagetest.org --webpagetest.key  apikey  -n 2 --firstParty ".google.co.in" --speedIndex --video urls.txt -b firefox --graphite.host  ipaddress.
It was working when it was configured but when I check after 2 days it is not working. with same command.

Thanks

**Comment by tobli** [comment]
Hi!
The [documentation](https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-5-minutes) was missing a critical part - that's now fixed.
I've also changed the docker-compose file to revert to a non-beta version of Grafana, and the corresponding set of example dashboards. Please redownload the compose file and pull the images.
When downgrading Grafana there might be an issue with keeping the storage volume from the newer version. To be on the safe side you could delete the previous volume: docker-compose stop && docker volume rm docker_grafana.

Hope this resolves the issue!

**Comment by Geekaylee** [comment]
Hi @tobli :)

I've blatted all my containers, re-downloaded the yml file and retried but with no success.  You mention that the documentation was missing parts but the only difference I see is the additional -d param when creating the containers, which shouldn't make a difference.

**Comment by narayanachilamkuri** [comment]
Hi 
when I run the command  like 
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:4.2.1  urls.txt -b firefox --graphite.host ipaddress getting 

Google Chrome 55.0.2883.75 
Mozilla Firefox 50.0.2
[2017-01-06 14:40:11] Versions OS: linux 4.4.39-moby nodejs: v6.9.1 sitespeed.io: 4.2.1 browsertime: 1.0.0-beta.18 coach: 0.30.0

it means chrome and mozilla using to launch urls. but my system doesn't have the mozilla so 
sitespeed.io using local browsers to launch application or downloading new and launching?

Thanks

**Comment by soulgalore** [comment]
Hey @narayanachilamkuri when you use the Docker container, it is built with one specific version of Chrome and one of Firefox, so when you download the container, you download a container containing sitespeed.io, Chrome, Firefox and some other help tools (xvfb, dependencies for visualmetrics). When a new browser version is released, we release a new version of the Docker container. That way you can be sure you use the same browser version all the time, until you chose to upgrade. 

Running sitespeed.io through node (just downloading via npm) sitespeed.io will use your local installed browsers. If a browser is missing on your system, sitespeed.io will fail.

Best
Peter

**Comment by tobli** [comment]
@narayanachilamkuri - I don't fully understand your setup. You mention using the "Up and running in 5 minutes" setup. That launches multiple containers, and links them so they can be routed internally (e.g. the host name "grafana" in the sitespeed container is resolved to the grafana container). However the example command you're giving is *not* using docker-compose, but rather docker (so it's not connected to the network of containers that'd spun up if you're using the compose file). Your command specifies "--graphite.host ipaddress". I assume `ipaddress` represents a variable, however I don't understand how to interpret it.

Following the docker-compose example exactly should work. If you want to spin up graphite and grafana containers separately, and access them from a separate docker container, you need to adjust your setup. Docker containers are isolated and you can't just pass the ip of one container to another and have them connect. Please check the documentation for Docker if you'd like to run containers separately and still link them.

Best,
/Tobias

**Comment by tobli** [comment]
Hi @Geekaylee!
The `-d`does matter in that you couldn't follow the instructions literally before (you'd have to open a second shell to run the sitespeed.io container, since without the -d the shell would be held up). The changes to compose-file and instructions resolved the issue for me and at least one other =) (see #1409). So I don't know what's causing your setup to not work. Let's move this to #1407, since this issue seems to be different.

**Comment by narayanachilamkuri** [comment]
Hi Tobli,

does it mean I have to run docker-compose for send data to grafana?
I was using docker and specify ipaddress able to get the data in grafana.
could you please give me some info on exactly which I have to run 
docker-compose run sitespeed.io https://www.wyndhamhotels.com --graphite.host=graphite 
           (or)
docker run sitespeedio/sitespeed.io https://www.wyndhamhotels.com  -b firefox --graphite.host 10.187.34.123
Thanks

**Comment by soulgalore** [comment]
Hello @narayanachilamkuri 

> does it mean I have to run docker-compose for send data to grafana?

No. Both your examples are fine. If you use docker-compose you can map container with each other easy as in your example, so the sitespeed.io container knows about graphite as "graphite". If you run Docker standalone it works perfect as you did with the IP and if you run you sitespeed.io container in an own box/server that is perfectly fine so you can send the data to graphite.

**Comment by narayanachilamkuri** [comment]
Thank you so much peter your help is very appreciable

**Comment by soulgalore** [comment]
This is fixed, if not please re-open!
