### ISSUE TITLE
Grafana shows Coach's recommendations？

### ISSUE THREAD

**Issue by kikyoar** [sitespeedio/sitespeed.io#1405]
Is there any way to put recommendations and scores into one interface？
help me

thank you

**Comment by soulgalore** [comment]
Hey @kikyoar you can put the score per type and each recommendation score if that would help by configure what metrics to send https://www.sitespeed.io/documentation/sitespeed.io/metrics/ let me add a example to the docs exactly later today. 

Best
Peter

**Comment by kikyoar** [comment]
Hi，Peter，How to put the **Advice**  on top of the **Grafana**？
![11](https://cloud.githubusercontent.com/assets/3872568/21710179/02c97184-d422-11e6-9384-ebfa2aa160f3.png)

**Comment by soulgalore** [comment]
Sorry @kikyoar I missed added the example yesterday, I'll be back tomorrow and can give you an example.

Best
Peter

**Comment by kikyoar** [comment]
**thank u**

**Comment by soulgalore** [comment]
Added some info how to make sure you push all advice metrics here: https://github.com/sitespeedio/sitespeed.io/commit/af6ffe14436d9c0d21ffc1cc61f4fdd84a4c7cb0

and then you need to add it in Grafana, do you know how to do it or do you want a short guide?
Best
Peter

**Comment by kikyoar** [comment]
Hi，Peter
I just want to put **advice** into grafana，Do not need to **score**
![image](https://cloud.githubusercontent.com/assets/3872568/21838566/ab9f82c8-d80d-11e6-943c-6377bcf2da32.png)

**Comment by soulgalore** [comment]
Hey @kikyoar I'm not sure about the end purpose, like what do you want to show, how do you want to use it etc? 

Today we store the data used by Grafana in [Graphite](https://graphiteapp.org/). Graphite stores time-series data. What you can do (but it would be a lot of work) is store the score and then individually map the advice against the score in the Grafana admin, but I don't fully see the purpose? But if you explain how what you plan to do, maybe I understand :) 

Best
Peter

**Comment by kikyoar** [comment]
sorry，My English is very poor，
I would like to put the coach's Advice grafana, not just the coach's score

**Comment by soulgalore** [comment]
Ah ok I see, you wan't store the exact text for that run. There's no way to get that information in Grafana today and I'm not sure if you want that. What missing today that we want to add in the future is an easy way to go from a result in Grafana back to a sitespeed.io report page. Then you click and easily the result advice. Would do it for you (we need support in Grafana though before implementing it).

**Comment by kikyoar** [comment]
thank u ，I need that！

**Comment by lbod** [comment]
@soulgalore Great. That's what I was trying to explain in https://github.com/sitespeedio/sitespeed.io/issues/1378#issuecomment-266825609 there's String/help content as summary information that's very useful in the reports which would sit nice along side time series data.

I think either this or #1378 should be a duplicate.

**Comment by soulgalore** [comment]
I think this will never happen, you will need to go to the HTML report page to get the info.
