### ISSUE TITLE
No data on Graphana using docker-compose

### ISSUE THREAD

**Issue by misidoro** [sitespeedio/sitespeed.io#1409]
Hi,

I am trying to run sitespeed using docker-compose but I am running into problems accessing the data on Graphana dashboard.

I am downloading the docker-compose file from master 
```
curl -O https://raw.githubusercontent.com/sitespeedio/sitespeed.io/master/docker/docker-compose.yml
```

Once I have the file, I run
```
docker-compose up
```

When I go to the dashboard I don't see any data. I thought that the datasource might be empty and then I run sitespeed

```
docker-compose run sitespeed.io https://www.sitespeed.io/ --graphite.host=graphite
```

After running sitespeed, I can see data on Graphite, but Graphana still doesn't show the data. On Graphana I can see  `500 error`.

Any clues?

Thanks!

**Comment by soulgalore** [comment]
Hey @misidoro thanks for adding the issue, I wonder if there could compatible issue with Grafana 4.0 and 4.1 dashboards, I've started to prepare for 4.1 (by adding info blocks). I updated the Grafana in the docker compose file to use 4.1, if you ca try download it again and give it another go?

Best
Peter

**Comment by Geekaylee** [comment]
Is this the error you're seeing in browser for the 500 errors @misidoro?

`Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/views.py&quot;, line 122, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&quot;, line 30, in evaluateTokens
    return func(requestContext, *args)
  File &quot;/usr/lib/python2.7/site-packages/graphite/render/functions.py&quot;, line 2249, in timeShift
    series = seriesList[0] # if len(seriesList) &gt; 1, they will all have the same pathExpression, which is all we care about.
IndexError: list index out of range`

**Comment by misidoro** [comment]
@soulgalore I have tried again and still no data showing.

@Geekaylee one of the request gives error 500 saying (looks the same error):
```
Traceback (most recent call last):
  File &quot;/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py&quot;, line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 125, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 30, in evaluateTokens
    return func(requestContext, *args)
  File &quot;/opt/graphite/webapp/graphite/render/functions.py&quot;, line 2231, in timeShift
    series = seriesList[0] # if len(seriesList) &gt; 1, they will all have the same pathExpression, which is all we care about.
IndexError: list index out of range
```

**Comment by misidoro** [comment]
@tobli solved! Thanks
