### ISSUE TITLE
Memory parameter died from Sitespeed 4.x :-(

### ISSUE THREAD

**Issue by xavier-medioni** [sitespeedio/sitespeed.io#1415]
Hi Sitespeed team !

At first: Thanks and congrat's for the performance tool ! It is really amazing !
I discovered it on mid november and I am pretty addict.

I decided to build my new solution for mass page analysis on it (I share some screens below).

![01-scan-form](https://cloud.githubusercontent.com/assets/1446141/21869767/6f23ea0e-d859-11e6-9a19-3e550bc657df.png)

![02-scan-report](https://cloud.githubusercontent.com/assets/1446141/21869772/74f5d2d0-d859-11e6-8935-61658f332c06.png)

![03-page-run-report](https://cloud.githubusercontent.com/assets/1446141/21869774/766a2030-d859-11e6-9a0e-8643e0352086.png)

I am supposed to scan a wide range of urls from pre defined list, or live extracted from a sitemap, preview / organize reports and print them.
I updated to 4.3 and I meet the now famous "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory" with the following usecase: 542 urls to scan, 2 runs / url

The error occurs at about 340 urls / 2 runs (about 60%), and I planned to scan up to 1000 urls / 2 runs, approximating the necessary memory for a such scan.

I see the memory has been set to 256 mb from Sitespeed 4.0 and the --memory parameter is no more available.
You can imagine haw sad and depressive it made me before Christmas :-)

Is supposed to be back some day ?
Or is there any possible "hack" ? (oh God, I really don't like this alternative...)

Whatever, Thanks by advance !

Xavier

**Comment by soulgalore** [comment]
Hi @xavier-medioni your tool looks nice :) Wouldn't mind a small "Powered by sitespeed.io" or [the logo](https://github.com/sitespeedio/logo) somewhere :)

The memory config in 3.x was actually only for Java , we used Java in the crawler and that could eat memory, there was no way to configure the total memory for NodeJS by default.

There shouldn't not be a 256mb limit in 4, let me know if you can find that again. The limit is the default node js, something like 2 gig.

In 4.x if you use the Docker container (do you use it?) you can change the max memory: https://github.com/sitespeedio/sitespeed.io/blob/master/docker/scripts/start.sh#L23-L25
by passing a new value as a parameter MAX_OLD_SPACE_SIZE.

If you run sitespeed.io installed by npm I don't know is there a way to change the memory? I wouldn't mind a PR for that. Else you could just wrap the bin script and pass it yourself something like http://prestonparry.com/articles/IncreaseNodeJSMemorySize/ or is better ways to do that?

Best
Peter

**Comment by xavier-medioni** [comment]
Hi @soulgalore 

Thanks for your answer !

My usecase forces me to use the nodejs global sitespeed.io command line, with no docker :-(

I am now considering 3 alternatives:
- hooking the /usr/lib/node_modules/sitespeed.io/package.json and adding a flag to increase memory
- a rollback to sitespeed 3.x, and perform tests with the --memory parameter to 4096
- any other way to increase memory for a nodejs global command (parameters, environment variable, ...)

My nodejs / sitespeed 4.3 templated command line (with extra params for custom plugin + --memory uneffective param) looks like:

sitespeed.io   {{options.general.urlList}} \
        --memory 4096 \
        --scanType desktop \
        --outputFolder {{options.outputDir}} \
        --budget {{options.desktop.budget}} \
        --browsertime.viewPort {{options.desktop.viewport}} \
        --plugins.load analysisstorer \
        --plugins.load plugins/report \
        --plugins.disable html \
        -b {{options.desktop.browser}} \
        -n {{options.general.runs}} \
        --metrics.list \
        1> {{options.outputDir}}/stdout.log \
        2> {{options.outputDir}}/stderr.log

The url list file is 500+ urls

I will let you know if my memory adventure meets a happy end :-)

Xavier

**Comment by soulgalore** [comment]
Hey Xavier,
rollback to 3.x will only help for the crawler, it could be that node is less memory intensive in 3.x but you will essentially hit the limit. 

I think the easiest is just to create your own wrapper like https://github.com/sitespeedio/grunt-sitespeedio/blob/master/tasks/sitespeedio.js and then set the memory. It would not be much work. 

If you find a global way to increase memory that would be cool.

Best
Peter

**Comment by xavier-medioni** [comment]
Thanks !

It sounds good, I'll have a look at it :-)

Xavier

**Comment by beenanner** [comment]
Very cool screenshots @xavier-medioni! Keep us in the loop with your findings on the memory test.

**Comment by xavier-medioni** [comment]
Thanks @beenanner,

And I think I will post something about my memory adventure quite soon...

**Comment by xavier-medioni** [comment]
Hi dear memory followers (yes, with a "s"),

I finally found the solution I was searching for, thanks to @soulgalore for his tips about my worries.

Instead writing about the solution, let's draw

![nwjs-sitespeed](https://cloud.githubusercontent.com/assets/1446141/21956908/02c5792a-da8b-11e6-9c26-e7b90515d1e7.png)

I hope this helps.

**Comment by soulgalore** [comment]
fixed.
