### ISSUE TITLE
Add link from URL result page to Grafana

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1420]
With the new standardized dashboard for a page https://dashboard.sitespeed.io/dashboard/db/page-summary we should be able to add links on the URL result page that goes directly to the Grafana graph.

You will need add one CLI parameter with the base URL to your Grafana instance and then we can generate the rest of the parameters, so that we hit the right page.

This can be the first step to integrate so we can go back and later on forth between sitespeed.io result pages and Grafana.

**Comment by jpvincent** [comment]
Optionaly, could we use the same sort of mechanism for grafana to store the WebPageTest result ID, so that we can link to the WPT test from the WPT dashboards ?

**Comment by soulgalore** [comment]
@jpvincent I think when we got it working in both directions we could automagically add a URL to the WebPageTest result page from Grafana (if you have it configured) but lets take that in step 2.

**Comment by softwareklinic** [comment]
I thought / remember reading somewhere that now the summary is linked to the grafana charts???? === maybe im still dreaming...

**Comment by soulgalore** [comment]
No right now we only link from Grafana to the HTML result pages.

**Comment by softwareklinic** [comment]
how is it done -- which version?

On Wed, May 31, 2017 at 2:30 PM, Peter Hedenskog <notifications@github.com>
wrote:

> No right now we only link from Grafana to the HTML result pages.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_1420-23issuecomment-2D305292424&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=HohLZCoxZuWGYnLLF3O15hh4qLklybxM1tc9b_fW_kw&s=BibOXElJcAPUQYxyfHE1UY6gHpbOOktWAt46OGSARZU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCidY7zmD82AbVK2ro4q1WztHPJ03Kks5r-5Fb-5FJgaJpZM4Lms0v&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=HohLZCoxZuWGYnLLF3O15hh4qLklybxM1tc9b_fW_kw&s=xDBTdWtyKxmFS9SfTOTJqtazrQ3Vr4YRS0-p1L8YQlE&e=>
> .
>



-- 
Regards,
Keyur
Cell: 2147845203

**Comment by soulgalore** [comment]
It's done by sending annotations, check out https://dashboard.sitespeed.io/dashboard/db/page-timing-metrics?orgId=1 and check the checkbox "runs" and then click on an annotation. Checkout https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#annotations

**Comment by softwareklinic** [comment]
this is GREAT === thats all i need for now... Any example --- on how to
send the annotation (what parameters to configure) - while posting curl ---
to graphite?? especially how to send the url etc....

*resultBaseURL*

On Wed, May 31, 2017 at 2:36 PM, Peter Hedenskog <notifications@github.com>
wrote:

> It's done by sending annotations, check out https://dashboard.sitespeed.
> io/dashboard/db/page-timing-metrics?orgId=1
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__dashboard.sitespeed.io_dashboard_db_page-2Dtiming-2Dmetrics-3ForgId-3D1&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=cY2-QbiOgKND_HZhonU7Bao_xP-Cq0DQeAg5voAGFVc&s=Di6-5Gr7jgH89jSv8Zvdv-m_38PONkdpgS2Lo4RhcO4&e=>
> and check the checkbox "runs" and then click on an annotation. Checkout
> https://www.sitespeed.io/documentation/sitespeed.io/
> performance-dashboard/#annotations
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__www.sitespeed.io_documentation_sitespeed.io_performance-2Ddashboard_-23annotations&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=cY2-QbiOgKND_HZhonU7Bao_xP-Cq0DQeAg5voAGFVc&s=KGGYAMOgAoOwHRHR0sPeKiJ63SM5xQMQA7ktsxrkDMM&e=>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_1420-23issuecomment-2D305293859&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=cY2-QbiOgKND_HZhonU7Bao_xP-Cq0DQeAg5voAGFVc&s=sy7c-c_4eUHez6TFCp3hq9uQVnzyrVual-uJKk1cZ9A&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCieMsiwK7gKKhtEzPJAVkygXJlc5Aks5r-5FcEzgaJpZM4Lms0v&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=cY2-QbiOgKND_HZhonU7Bao_xP-Cq0DQeAg5voAGFVc&s=KPIjXKDdhZIw7tlyamW6uaLR9FBte90IkRgUbygU5zI&e=>
> .
>



-- 
Regards,
Keyur
Cell: 2147845203

**Comment by softwareklinic** [comment]
I think i found it in documentation

$ docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -b firefox -n 1 --graphite.host <your graphite host>  --resultBaseURL https://example.yoursite.com https://www.sitespeed.io/


Question is if my base url is http://99.99.99.99:9090 (IP and port) --- is that all I need to pass ---- since im writing results in separate folder using the namespace and then date/time stamped folders e.g. below

http://99.99.99.99:9090/VZWTrack/2017-05-31-15-45-02/

Should i just pass http://99.99.99.99:9090 as resultBaseURL??

**Comment by soulgalore** [comment]
The annotation will be sent automagically as long as you configure resultBaseURL and graphite auth, the docs I linked should do it:
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#annotations

Also check our configuration we use at dashboard.sitespeed.io https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#get-the-metrics

**Comment by soulgalore** [comment]
This was implemented a long time ago.
