### ISSUE TITLE
Possibility to also pass wpt.script to sitespeed.io through string instead of file

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#1422]
Hi all!

I'm setting up some sitespeed.io, WPT, Graphite/Grafana monitor in AWS.
Sitespeed.io will be the driver for running test (in WPT) and sending data to Graphite/Grafana setup.

I would like to create an HTTP API endpoint + lambdaFunction that starts an sitespeed.io Docker (ECS) instance so teams can easily run en schedule monitor tests.

For this they would send all config (mainly sitespeed.io config) in the body of the request. 
Because some config options (urls, budget and webpagetest script) expect a path and file this isn't really possible.

**Would it be a good idea to create an extra config where you can send a webpagetest script that is already converted to a string? For this I would use the WebPageTest API method scriptToString().
Or do you guys see other options?**

https://github.com/marcelduran/webpagetest-api/#methods

**Comment by soulgalore** [comment]
Hey @JeroenVdb let us fix so that we check if it is a file or a text, I can do that the coming days. Then you can automagically pass on a file or the script.
Best
Peter

**Comment by JeroenVdb** [comment]
Did some testing. The cli command would be something like this:

```
# via direct script string
sitespeed.io --webpagetest.script "logData\t0\nnavigate\thttp://foo.com/login\nlogData\t1\nsetValue\tname=username\tjohndoe\nsetValue\tname=password\t12345\nsubmitForm\taction=http://foo.com/main" http://sitespeed.io

# via file
sitespeed.io --webpagetest.script "./plain-wpt-script.txt" http://sitespeed.io
```

```javascript
$ node
> var fs = require('fs');
> var webpagetest = require('webpagetest');
> 
> // array to webpagetest script string
> wptScriptString = webpagetest.scriptToString([
... 	{"logData": 0},
... 	{"navigate": "http://foo.com/login"},
... 	{"logData": 1},
... 	{"setValue": ["name=username", "johndoe"]},
... 	{"setValue": ["name=password", "12345"]},
... 	{"submitForm": "action=http://foo.com/main"}
... ]);
'logData\t0\nnavigate\thttp://foo.com/login\nlogData\t1\nsetValue\tname=username\tjohndoe\nsetValue\tname=password\t12345\nsubmitForm\taction=http://foo.com/main'
> 
> /*
... 	plain-wpt-script content
... 
... 	logData	0
... 	navigate	http://foo.com/login
... 	logData	1
... 	setValue	name=username	johndoe
... 	setValue	name=password	12345
... 	submitForm	action=http://foo.com/main
... */
> 
> // webpagetest script file to webpagetest script string
> fs.readFileSync(path.resolve('./plain-wpt-script.txt'), {encoding: 'utf8'});
'logData\t0\nnavigate\thttp://foo.com/login\nlogData\t1\nsetValue\tname=username\tjohndoe\nsetValue\tname=password\t12345\nsubmitForm\taction=http://foo.com/main'
> 

```

**Comment by soulgalore** [comment]
BTW URLs don't need to be a file you can just add multiple and it will work. I think it would be cool to fix the budget and webpagetest script in a generic way. If you have time have a go (but let me know) else I'll try in a couple of days.

**Comment by JeroenVdb** [comment]
What I was thinking. Should we 
- automagically decide if the value is a path or a string;
- or make the API more verbose (but breaking) with (webpagetest.script|budget).path and (webpagetest.script|budget).string + a fallback to the automagically way.

**Comment by soulgalore** [comment]
I like the automagical (in 3.x we did nothing like that), can we come up with a good pattern?

**Comment by JeroenVdb** [comment]
- when the string/script has "navigate\t" it's probably a script string
- when the string/script has an extension  it's probably a script file

More?

**Comment by soulgalore** [comment]
fixed by @JeroenVdb
