### ISSUE TITLE
HTML reports not being written

### ISSUE THREAD

**Issue by lbod** [sitespeedio/sitespeed.io#1424]
I'm using docker compose sitespeed version v.4.3.7 and running like:

> docker-compose run -d sitespeed.io pages.txt --graphite.host=graphite --gpsi.key XXXXXXXXXXXXX --plugins.disable screenshot

There's a total of 96 urls in this file and the HTML reports aren't being written to, there's little to no errors. The step from `Render HTML for 96 page(s)` to `HTML stored in ...` never happens.  There are GPSI errors at the start for overused quota but this has been fine before and the html reports were generated.
Looking at the docker log for the container it ends like:

> /start.sh: line 30:    55 Killed                  exec node --max-old-space-size=$MAX_OLD_SPACE_SIZE /usr/src/app/bin/sitespeed.js "$@"

This was working last week, however we had seen it fail a couple of times. 

Only the `logs` and `pages` directories are written, no index.html, pages.html, css etc 

I ran the same test again against 60 urls and this worked fine.

**Can you advise where's best to debug this and/or generate more logging**? I've not tried to run with verbose logging yet, however I would like to limit hitting the same production site over and over again just for testing sitespeed.

---

edit: **This may or may not be related** but another site we run tests against with a similar number of urls occasionally doesn't write the html reports either. This happens much less but there was an extra bit of error logging:

```

Render HTML for 99 page(s) 
TypeError: Cannot read property 'data' of undefined
    at Promise.resolve.map (/usr/src/app/lib/plugins/html/htmlBuilder.js:117:24)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:110:8)
    at Object.close (/usr/src/app/lib/plugins/html/index.js:26:29)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:43:49)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:43:6)
    at runOptionalFunction.then.then.tap (/usr/src/app/lib/sitespeed.js:119:32)
From previous event:
    at loader.loadPlugins.then (/usr/src/app/lib/sitespeed.js:119:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (/usr/src/app/lib/sitespeed.js:103:12)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:100:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:29:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3


```

**Comment by soulgalore** [comment]
When I check the stacktrace it looks like we don't get data from browsertime, the check there isn't perfect let us do a fix for that (so it doesn't break). But I think there must be an error before that, when accessing a URL that didn't work? If you can share the logs to me that helps: peter [AT] soulgalore [dot] com.

Best
Peter

**Comment by soulgalore** [comment]
I would check memory usage, easiest is just to try to increase the memory for NodeJS by setting MAX_OLD_SPACE_SIZE by passing it on to Docker as an environment variable: https://github.com/sitespeedio/sitespeed.io/blob/master/docker/scripts/start.sh#L23-L25

I'll push a check for that stacktrace but it could be that we pushing the error forwards. If you get that again, can you please if you see something before that, we should have something from Browsertime.

Best
Peter

**Comment by lbod** [comment]
Much appreciated Peter.. We're a bit limited on memory at the moment but will be upping it soon (currently 2gb).

So I dropped it down to MAX_OLD_SPACE_SIZE=1024


I'll reply on the GH issue later.

Thanks


________________________________

**Comment by soulgalore** [comment]
Good. About instance size, I think 2gb in general it too low for Chrome/Firefox (but it also depends on the site).  On our instance on Digital Ocean that runs the tests for dashboard.sitespeed.io we use a 8gb instance to make sure we get as stable values as possible. That is overkill but keep an I on the performance and test how much it changes if you increase/decrease memory/CPU.

**Comment by lbod** [comment]
Thanks @soulgalore  We knew we're currently underpowered and trying to size it as we go. It makes sense how underpowered it is considering it's running a browser, as well as node, graphite and grafana containers. We still have to split that up properly.

I'd do a PR to update the website docs but there isn't a GH repo for them?

**Comment by soulgalore** [comment]
@lbod the docs are here: https://github.com/sitespeedio/sitespeed.io/tree/master/docs so you can do a PR :)

**Comment by lbod** [comment]
@soulgalore ok doing it now
