### ISSUE TITLE
couldn't be fetched, response code 500 error: Error from the crawl: 

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#1425]
Facing "couldn't be fetched, response code 500 error: Error from the crawl: "

 when i set up request Headers in sitespeed.io 

below is my command 

sitespeed.io -u http://172.17.4.67/shop/product/calvin-klein-home-bamboo-bedding-collection-100-cotton?ID=16534 -d 0 -b chrome -n 3 --budget budget.json --requestHeaders myheaders.json

myheaders.json 

{
  "X-XXX-Experiments": 
  	{
  		"EXPERIMENT":["11-21"]
  	}
}

budget.json 

{
 "timings": 
    { 
      "speedIndex": 9000 
   }
}

Attached screenshot of same.
<img width="1119" alt="screen shot 2017-01-23 at 3 32 04 pm" src="https://cloud.githubusercontent.com/assets/1479179/22227536/9a7610ee-e180-11e6-81c4-ff42e477896a.png">

**Comment by soulgalore** [comment]
Hey @badrinathvm 
so the 500 is from the page you try to test, what kind of headers are you using? Could you upgrade to latest sitespeed.io 4 we try not to spend time on the old version.

Best
Peter

**Comment by badrinathvm** [comment]
Below are headers I am using 

{
"X-XXX-Experiments":
{
"EXPERIMENT":["11-21"]
}
}

**Comment by badrinathvm** [comment]
I tried to update to  4.0 by using below command 

npm install -g sitespeed.io  - It is paicking up 3.2.5 itself every time .. Every tried deleteing old one and installing to.

**Comment by badrinathvm** [comment]
<img width="1023" alt="screen shot 2017-01-24 at 3 13 26 pm" src="https://cloud.githubusercontent.com/assets/1479179/22270987/2cb87d68-e247-11e6-8784-1511fa102324.png">

**Comment by beenanner** [comment]
@badrinathvm  are you able to upgrade to an LTS of Node(either 4 or 6)? I would recommend 6. ;-) We no longer support 0.12 in sitespeed.io as it's end of life was Dec 2016

https://github.com/nodejs/LTS#lts-schedule

**Comment by soulgalore** [comment]
Closing, let is know if you still see the issue with the latest 4.x.
