### ISSUE TITLE
cannot run tests behind proxy using docker to execute tests 

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1429]
Hi,

I am behind a corporate firewall and am having trouble running my tests on aws instance with docker.

I have configured the proxy for docker, sitespeed.io and I am still not able to get proper results.

Below is my run command in Jenkins:

sudo docker run -e  http_proxy='http://proxy-us-aws-nonprod.acme.com:3128' -e https_proxy='http://proxy-us-aws-nonprod.acme.com:3128' --privileged --shm-size=1g --rm -v /home/autocm/workspace/sitespeed:/sitespeed sitespeedio/sitespeed.io https://rqa8-cb.acme.net -b firefox --debug --graphite.host 10.IP.11.157 --grahpite.port 2003 -n 1 --graphite.includeQueryParams -p http://proxy-us-aws-nonprod.acme.com:3128

After extensive tests and support from some of the ops guys they are suggesting it will be necessary for me to configure the firefox proxy within docker to reach the internet.

Any suggestions on how to get around this? Or could our assessment be missing another factor?

I am thinking the easiest solution is to take my tests outside of docker.

**Comment by weigo** [comment]
Perhaps something along the lines outlined at the bottom of this discussion on stackoverflow:
https://stackoverflow.com/questions/843340/firefox-proxy-settings-via-command-line

**Comment by soulgalore** [comment]
Hey @ppcuenca can you check https://github.com/sitespeedio/sitespeed.io/pull/1353 I have missed merging that info, I know @softwareklinic has worked a lot to get it work with a similar problem.

And yes you configure the proxy (this is the browsertime help):
<pre>
proxy
  --browsertime.proxy.http   Http proxy (host:port)                                                                             [string]
  --browsertime.proxy.https  Https proxy (host:port)                                                                            [string]
</pre>

Best
Peter

**Comment by softwareklinic** [comment]
Will share.full working examples

Sent from my iPhone

On Jan 25, 2017, at 10:47 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @ppcuenca<https://github.com/ppcuenca> can you check #1353<https://github.com/sitespeedio/sitespeed.io/pull/1353> I have missed merging that info, I know @softwareklinic<https://github.com/softwareklinic> has worked a lot to get it work with a similar problem.

And yes you configure the proxy (this is the browsertime help):

proxy
  --browsertime.proxy.http   Http proxy (host:port)                                                                             [string]
  --browsertime.proxy.https  Https proxy (host:port)                                                                            [string]


Best
Peter

-

**Comment by ppcuenca** [comment]
Appreciate the help,

So if I understand correctly, I need to set the proxy via browsertime proxy? And if this is true do I also still need the sitespeed.io proxy?

**Comment by softwareklinic** [comment]
45 * * * * docker run --privileged -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io myurllist.txt -n 1 -b firefox --browsertime.proxy.http=proxy.domainname.com:80 --browsertime.proxy.https=proxy.domainname.com:80 --graphite.host 10.99.99.99 --graphite.namespace MyTrack  --outputFolder sitespeed-result/MyTrack/$(date +\%Y-\%m-\%d-\%H-\%M-\%S) --browsertime.timeouts.script 80000 --firstParty ".*(vzw|verizonwireless).*" >> /tmp/sitespeedvzwtrack-run.txt 2>&1

**Comment by softwareklinic** [comment]
hope this helps

**Comment by softwareklinic** [comment]
this is a 100% working example with proxy, timeouts, 1st & 3rd party, url list

**Comment by ppcuenca** [comment]
Should this work with sitespeed.io 4.1.3 or would I need the latest docker image?

**Comment by softwareklinic** [comment]
Will work

**Comment by ppcuenca** [comment]
I tried updated my command but still doesn't work. I did see something I did not see before:

`[2017-01-27 13:30:05] Catched a WebDriverError [Reached error page: about:neterror?e=connectionFailure&u=https%3A//qa-cb.acme.net/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20qa-cb.acme.net.]. Try one more time.WebDriverError: Reached error page: about:neterror?e=connectionFailure&u=https%3A//qa-cb.acme.net/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20qa-cb.acme.net.
[2017-01-27 13:30:06] WebDriverError:WebDriverError: Reached error page: about:neterror?e=connectionFailure&u=https%3A//qa-cb.acme.net/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20qa-cb.acme.net.
[2017-01-27 13:30:06] Could not load URLUrlLoadError: Failed to load https://qa-cb.acme.net, cause: Reached error page: about:neterror?e=connectionFailure&u=https%3A//qa-cb.acme.net/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20qa-cb.acme.net.
[2017-01-27 13:30:06] https://qa-cb.acme.net generated the following error in Browsertime UrlLoadError: Failed to load https://qa-cb.acme.net`

I did also try a pared down command without the docker environment variables and the "-p" sitespeed.io proxy flag but for some reason my results weren't being posted to graphite/grafana without it.

Below is my updated docker command:

`sudo docker run -e http_proxy=http://proxy-us-aws-nonprod.acme.com:3128 -e https_proxy=http://proxy-us-aws-nonprod.acme.com:3128 --privileged --shm-size=1g --rm -v /home/autocm/workspace/sitespeed:/sitespeed sitespeedio/sitespeed.io https://qa-cb.concurtech.net -b firefox --browsertime.proxy.http=http://proxy-us-aws-nonprod.acme.com:3128 --browsertime.proxy.https=http://proxy-us-aws-nonprod.acme.com:3128 --debug --graphite.host 10.xxx.xxx.157 --grahpite.port 2003 -n 1 --graphite.includeQueryParams -p http://proxy-us-aws-nonprod.acme.com:3128`

**Comment by ppcuenca** [comment]
@soulgalore @softwareklinic Any idea or suggestions I can do to modify my command that could perhaps could help.

This entire time I am unable to get a metric for First Paint when running tests from the aws server but no issues on my local machine.

Thanks,

**Comment by softwareklinic** [comment]
for chrome - u get first paint -- i dont have firstpaint- when i use firefox... hope this helps answer --- or probably more of a Q for @soulgalore  --- i think first paint is limited to chrome.

**Comment by ppcuenca** [comment]
@softwareklinic ah okay thats good to know, I did not realize that. Any thoughts how to modify my run command to avoid that error above? Do I need to set the environment variables for the docker container as well as sitespeed and browsertime?

**Comment by ppcuenca** [comment]
I believe this is related, I enabled the html report in jenkins and while I am getting some timing data the report is not complete:

![2017-01-30_12-07-15](https://cloud.githubusercontent.com/assets/22225816/22433170/717a19e6-e6e5-11e6-9442-966da29d2287.png)

**Comment by softwareklinic** [comment]
Are you using some preScripts???

**Comment by ppcuenca** [comment]
I was but I removed much of it to isolate the issue. This is just a simple single URL test.

**Comment by softwareklinic** [comment]
You should take out the -e parameter -- u dont need it i believe... just the browsertime proxy http and https proxy is good enough,

sudo docker run -e http_proxy=http://proxy-us-aws-nonprod.acme.com:3128 -e https_proxy=http://proxy-us-aws-nonprod.acme.com:3128 --privileged --shm-size=1g --rm -v /home/autocm/workspace/sitespeed:/sitespeed sitespeedio/sitespeed.io https://qa-cb.concurtech.net -b firefox --browsertime.proxy.http=http://proxy-us-aws-nonprod.acme.com:3128 --browsertime.proxy.https=http://proxy-us-aws-nonprod.acme.com:3128 --debug --graphite.host 10.xxx.xxx.157 --grahpite.port 2003 -n 1 --graphite.includeQueryParams -p http://proxy-us-aws-nonprod.acme.com:3128

**Comment by soulgalore** [comment]
hey @ppcuenca 

> firstPaint

Yes as @softwareklinic  mentioned, only Chrome supports firstPaint but if you run using Docker you should use --speedIndex then you will get firstVisualChange for both Chrome and Firefox (=analyzed using a video so for some sites it is better than firstPaint reported by Chrome).

For the proxy, let see how @softwareklinic latest example works out.

Best
Peter

**Comment by ppcuenca** [comment]
Hi,

I removed the -e flags in the run and only included the browsertime proxy info. But still not working. 

I am trying to isolate the issue by removing the preScript portion and just testing URLs that are accessible without the proxy and for some reason there is no screenshot, no har file, and no coach anlaysis.(see my above screenshot) But I am able to get some Summary information.

![2017-01-31_12-53-52](https://cloud.githubusercontent.com/assets/22225816/22477565/9f056a26-e7b4-11e6-8234-62dc90eb68b0.png)

**Comment by ppcuenca** [comment]
@soulgalore @softwareklinic 

I was told by a coworker that the problem could be that the firefox client with the docker container itself needs to be configured with the proxy.

Does this seem consistent with your experiences or unnecessary?

**Comment by softwareklinic** [comment]
Unnecessary

Sent from my iPhone

On Feb 1, 2017, at 6:33 AM, ppcuenca <notifications@github.com<mailto:notifications@github.com>> wrote:


@soulgalore<https://github.com/soulgalore> @softwareklinic<https://github.com/softwareklinic>

I was told by a coworker that the problem could be that the firefox client with the docker container itself needs to be configured with the proxy.

Does this seem consistent with your experiences or unnecessary?

-

**Comment by softwareklinic** [comment]
The.selenium sets.the.proxy.for the.browser.via.the browser time.proxy.flag.that.y.pass.fro..outside

Sent from my iPhone

On Feb 1, 2017, at 6:33 AM, ppcuenca <notifications@github.com<mailto:notifications@github.com>> wrote:


@soulgalore<https://github.com/soulgalore> @softwareklinic<https://github.com/softwareklinic>

I was told by a coworker that the problem could be that the firefox client with the docker container itself needs to be configured with the proxy.

Does this seem consistent with your experiences or unnecessary?

-

**Comment by ppcuenca** [comment]
ah okay, that makes sense... @softwareklinic is there a way I can PM you or perhaps use stackoverflow chat to work through this?

**Comment by softwareklinic** [comment]
yeah we can

**Comment by ppcuenca** [comment]
@softwareklinic  I actually have not reached the 100 reputation points required to create a chat but I did find this disposable chat. If you close the window or tab you will be logged off.

https://niltalk.com/r/satTx   the pw: sitespeed

Thanks,

**Comment by soulgalore** [comment]
Thanks @softwareklinic for helping out! Is this fixed now, else please re-open the issue.
