### ISSUE TITLE
Crash during HTML page generation

### ISSUE THREAD

**Issue by garrettwilkin** [sitespeedio/sitespeed.io#1430]
## Story

- I'm running sitespeed.io via docker.
- It fails during HTML report generation

I think this might be failing because we are not setting Expires headers properly. I know that's an issue for some of our assets (or even pages).

The part that's really confusing me is that this was running successfully just a day ago.

We've diving deeply into performance through the rest of this week and so I'm hoping to solve this soon. :anguished: 

## Commands & Evidence

Example docker command:

```
sudo docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://bdnnow.com/ -n 5
```

[Example stack trace 1](https://gist.github.com/garrettwilkin/e61f7a57d1a18ed95237a8a6698a8689)

```
sudo docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://bangordailynews.com/2017/01/25/news/bangor/body-found-under-dock-in-bucksport-that-of-missing-bangor-man/ -n 5
```

[Example stack trace 2](https://gist.github.com/garrettwilkin/c4898bb633cbb4f223dfaf0796889ca0)

Location of exception from stack trace:

https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/templates/url/pagexray/index.pug#L53

## Version

```
sudo docker pull sitespeedio/sitespeed.io
Using default tag: latest
latest: Pulling from sitespeedio/sitespeed.io
Digest: sha256:5b9c894a0940d72a439b4d7981efb5b37ce9a6dd9f2e54a61107df85315e4479
Status: Image is up to date for sitespeedio/sitespeed.io:latest
```

Here's the version I'm running

```
$ sudo docker image ls
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
sitespeedio/sitespeed.io   latest              a4b64bfc0463        6 days ago          1.47 GB

```

I can successfully run this docker image against google.com:

```
$ sudo docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://google.com -n 5                                                                                                                     
Google Chrome 55.0.2883.87 
Mozilla Firefox 50.1.0
[2017-01-25 22:08:05] Versions OS: linux 3.13.0-107-generic nodejs: v6.9.1 sitespeed.io: 4.3.8 browsertime: 1.0.0-beta.23 coach: 0.30.4
[2017-01-25 22:08:05] Starting chrome for analysing http://google.com 5 time(s)
[2017-01-25 22:08:05] Testing url http://google.com run 1
[2017-01-25 22:08:10] Testing url http://google.com run 2
[2017-01-25 22:08:14] Testing url http://google.com run 3
[2017-01-25 22:08:19] Testing url http://google.com run 4
[2017-01-25 22:08:23] Testing url http://google.com run 5
[2017-01-25 22:08:28] 13 requests, 368.19 kb, firstPaint: 516ms (±32.74ms), DOMContentLoaded: 559ms (±32.52ms), Load: 1.18s (±71.43ms), rumSpeedIndex: 517 (±32.74) (5 runs)
[2017-01-25 22:08:28] Render HTML for 1 page(s) 
[2017-01-25 22:08:30] HTML stored in /sitespeed.io/sitespeed-result/google.com/2017-01-25-22-08-05
[2017-01-25 22:08:30] Finished analysing http://google.com

```

**Comment by soulgalore** [comment]
Hey @garrettwilkin thanks for the detailed bug report! Traces and giving all extra info really helps out! I'm pushing 4.3.9 right now, it will take a couple of minutes until the tag is in the Docker hub.

I verified and it works for me but please let me know in the issue that it worked for you so we can close it.

Best
Peter

**Comment by garrettwilkin** [comment]
OMG!

I  EXUBERANTLY CONFIRM THAT IT WORKS! 

![so_much_win](https://cloud.githubusercontent.com/assets/527514/22335029/fda1a06c-e3aa-11e6-8f13-fd1d40b93cd4.jpg)
