### ISSUE TITLE
coach.pageSummary.advice.info.responsive is always true

### ISSUE THREAD

**Issue by onnimonni** [sitespeedio/sitespeed.io#1432]
Here's example site where the value of `coach.pageSummary.advice.info.responsive` is always `true`.

I think this site should be `false`: https://getbootstrap.com/examples/non-responsive/

This is the command which I tried to run:
```
$ docker run --privileged --rm sitespeedio/coach https://getbootstrap.com/examples/non-responsive/ -b chrome
```

**Versions:**
```
$ docker run --privileged --rm sitespeedio/coach --version
Google Chrome 55.0.2883.75
Mozilla Firefox 50.0.2
Starting Xvfb ...
webcoach 0.30.3
```

**Comment by soulgalore** [comment]
Hey @onnimonni thanks for reporting. The original issue is in the coach here https://github.com/sitespeedio/coach/issues/18 

If you have any input to make it work cleaner that would be super!

Thanks
Peter

**Comment by soulgalore** [comment]
Let keep the original issue open in Coach and continue there.
