### ISSUE TITLE
Sitespeed memory consuming benchmark

### ISSUE THREAD

**Issue by xavier-medioni** [sitespeedio/sitespeed.io#1435]
Hi dear followers !

Today, my post is not about requesting Sitespeed features (thanks again to all the team by the way), reporting a bug or complaining.

I made some test this week end about Sitespeed memory consuming, and I wanted to share the results with you.

The test was about scanning 542 urls (live extracted from a sitemap), and change the allocated memory for the process to run scans multiple times.

The very loyal readers have already read the https://github.com/sitespeedio/sitespeed.io/issues/1415

So the test was performed with:
- NWJS
- sitespeed.io used as nodejs library (not the command line)
- the package.json memory process parameter "js-flags": "--max_old_space_size=XXXX" to modify the allocated memory
- for sure, if the allocated memory is not enough to perform the scan, the process crashes

![memory-benchmark](https://cloud.githubusercontent.com/assets/1446141/22421629/6cfeba9a-e6e8-11e6-829d-1f8c5b56525e.png)

Note: the scan durations you can see on the screenshot are not very relevant, because I was using bandwidth to watch TV / Australian Open :-)

As results:
- 1024 MB: about 38% of 542 urls => 210 urls
- 1536 MB: about 59% / 321 urls for desktop scan and 63% / 343 urls for mobile scan
- 2048 MB: about 81% / 444 urls for desktop scan and 84% / 460 urls for mobile scan

With 4096, I can easily reach my 542 urls goal and chain desktop and mobile scans in a single process.

And for the very curious people, a full 542 urls desktop scan, on quite heavy pages (between 1 and 3 MB for page size), with analysisstorer plugin enabled and no metrics filtering, is 7.7 GB on disk :-)

I hope this help

Xavier

**Comment by beenanner** [comment]
Very cool analysis @xavier-medioni! Thanks for sharing!

**Comment by soulgalore** [comment]
There's nothing more to be done here right? Else please re-open :)
