### ISSUE TITLE
Browsertime and Flash

### ISSUE THREAD

**Issue by Geekaylee** [sitespeedio/sitespeed.io#1436]
More of a question than a bug, but is it possible to run flash on pages via the browsers included in the sitespeedio/sitespeed.io docker image?  I'd imagine I can run sitespeed locally and use my browser with Flash enabled but all my experimenting has been using the docker version so I'd prefer to stick to that.

**Comment by soulgalore** [comment]
Hey @Geekaylee sorry for not getting back, I've totally missed it. Not sure, what is the current Flash support? Best case you could turn it on with CLI parameters but it could be that the Docker container needs to have some more things installed? If that's the case you can create your own container. Let me know if you already fixed it.

Best
Peter

**Comment by Geekaylee** [comment]
No problem. I came to the same conclusion that a new container with Flash
installed would be required, however as we're actually looking to
decommission Flash on our platform this year so I didn't put to much effort
into it.

**Comment by soulgalore** [comment]
cool, thanks for getting back, closing.
