### ISSUE TITLE
Advice on how to create an alert if there third party requests have an http status error

### ISSUE THREAD

**Issue by lbod** [sitespeedio/sitespeed.io#1437]
Using docker sitespeed.io:4.3.7

This isn't a bug, sorry, just a request for advice. We have a requirement to create an alert if any third party requests have an http error status code. I thought about doing this in Grafana but I'm not exactly sure what metrics to use after looking through metrics.txt and configuredMetrics.txt. 

It'd be nice if we had something like `pagexray.pageSummary.thirdParty.status`. Another option is if I could write a plugin. Any advice is appreciated.

**Comment by soulgalore** [comment]
You could probably use https://dashboard.sitespeed.io/dashboard/db/page-summary?panelId=4&fullscreen with some tweaking for 400/500s to get alerts, but then you need to go to the result to see which request is failing. Pushing all requests isn't working right now [1412](#1412) if I remember it correctly.

**Comment by lbod** [comment]
@soulgalore ok understood, I've no idea yet how I'd query for the request domain not matching the first party domain but I should be able to figure that out, however as you say I'd need to push all the page summary xray results which I wouldn't want to do.

Would this be better as a custom plugin which does some custom reporting action (whether it's worth sharing or not I don't know)?

**Comment by soulgalore** [comment]
hey @lbod sorry for not getting back on this. Can't you use the alert features in Grafana for that? First setup a new graph that graph all response codes:
<img width="1232" alt="screen shot 2017-03-06 at 10 12 54 am" src="https://cloud.githubusercontent.com/assets/540757/23603464/a6e0b2c6-0255-11e7-8975-70fb6751b875.png">

And then make a alert that alerts on everything above 399:
<img width="648" alt="screen shot 2017-03-06 at 10 13 45 am" src="https://cloud.githubusercontent.com/assets/540757/23603483/c0006b7a-0255-11e7-8f74-17a1d2dd17b7.png">

**Comment by lbod** [comment]
hey @soulgalore and sorry I've just seen this now... That's the route we're going down and it's fine to close.
