### ISSUE TITLE
Also analyse WebPageTest HAR results with PageXray

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#1446]
If I understand correctly [PageXray](https://github.com/sitespeedio/pagexray) analyses the HAR files  provided by Browsertime to retrieve extra metrics.

**Would it be possible to also analyse the HAR files from WPT tests?**

I know some information provided by WPT and PageXray will overlap (both gather resource information per domain) but it will also add extra information about thirdparty content for example. If new metrics arise adding them to PageXray will benefit both.

This could be add to the webpagetest view namespace like: `webpagetest.pageSummary.data.median.firstView.pagexray.<metrics>`

**Comment by soulgalore** [comment]
Released in 6.3.0 but only in WebPageTest standalone mode.
