### ISSUE TITLE
WPT Test can't be made non-private

### ISSUE THREAD

**Issue by jangrewe** [sitespeedio/sitespeed.io#1448]
I'm sorry to bother you guys again, but as already mentioned in #1447, the `--webpagetest.private` parameter doesn't make tests public if set to `false`.

The `defaultConfig` hash in `lib/plugins/webpagetest/index.js` defines `private` as `true`, yet in contrast to all other options, it seems to ignore being overridden on the command line.

And yes, to not embarass myself again, i checked the "show tests from all users" box on the WPT server! ;-) 
But it only shows me the tests that were run manually, not the one from SSIO.

**Comment by soulgalore** [comment]
ok, need check then I think this is problem with the [WebPageTest API](https://github.com/marcelduran/webpagetest-api) that we use internally to talk to WebPageTest.

>And yes, to not embarass myself again, i checked the "show tests from all users" box on the WPT server! ;-)

No need to be embarassed  that this kind hard earned lesson, the GUI isn't perfect.

**Comment by jangrewe** [comment]
Thanks, it's indeed a bit outdated, compared to how nice sitespeed.io looks.

Anyways, i thought i'd do some further testing, and manually changing the `defaultConfig` hash to explicitly say `private: false` still results in the WPT test being private.

I can see it in WPT's log:
```2017-02-10 10:10:04	192.168.21.27	0	0	170210_B4_cad57c9a4630dab992a460bfda372b9c	https://quazer.com/	Windows 10 VM - <b>Chrome</b>	1			1		5c5b9e44b3eef4840c37a239efc3d1aec47043e2		1
```
The `1` in the column after the Location/Browser cloumn seems to be the `private` flag. If i change it to `0`, it shows up in the Test History page.

**Comment by soulgalore** [comment]
The problem was that the cli param was converted to a String 'false' instead of a boolean. Now it works setting <code>--webpagetest.private false</code>

**Comment by jangrewe** [comment]
Thanks, i've already left the office so i can't test it right away (though it looks like that fix solves the issue that the parameter is interpreted incorrectly), but as i already mentioned, the tests are still marked as private even if i change the `defaultConfig` Hash to set `private` to `false` by default. Would that be a bug i'd have to open at the WPT API repo, or is it possible that this Boolean is still being flipped somewhere in SSIO?

**Comment by soulgalore** [comment]
It should work, I tested it by using the API against the public WebPageTest.org and having private true made the run go away from the search, making it false made it appear. So try on Monday and I hope it will just as expected.

**Comment by jangrewe** [comment]
Will do, thanks again-again, i'll keep you posted!

**Comment by jangrewe** [comment]
Sorry for the late reply, @soulgalore, but i can confirm that it's working. Thanks! <3
