### ISSUE TITLE
use with a proxy service to check accessibility from multiple world locations?

### ISSUE THREAD

**Issue by vesper8** [sitespeedio/sitespeed.io#1449]
can I use SiteSpeed with a proxy service to check performance from multiple world locations? Is it built-in? Any recommendations on what other open-source tool I can add to achieve this

I know I'll have to use a paid proxy provider. I use Proxymesh currently

**Comment by soulgalore** [comment]
Hey @vesper8 
one way you can do it is run sitespeed.io on different servers and then push the metrics to a central Graphite server and make sure you put the data under different namespaces, then you can use just built in functionality. If you want something fancier you need to build a plugin.

What do you want to test? Performance in different datacenter och CDN provider?

**Comment by vesper8** [comment]
running it on different servers isn't going to work since I'd like to use a proxy service and test connectivity from 30+ countries

my main concern is testing to see if the site is accessible at all from those locations. I want to know if I'm being censored or blocked from certain countries basically.

It sure would be nice if you built-in a means of inserting a simple proxy between sitespeed and the site being tested.. I'm surprised such a plugin hasn't been desired before

**Comment by soulgalore** [comment]
If you wanna test accessibility I think using sitespeed.io will add a lot of overhead, since we collect a a lot measurement and run some Javascript tests to test the site. Better to just use a bash script :)

**Comment by tobli** [comment]
Agreed. Using a proxy will not give a good idea about actual performance from that location, since you'd be adding the latency from the test location to the proxy.

**Comment by softwareklinic** [comment]
If you have some latency details about the proxy... u can put it as a part of formula.. if its kind of consistent latency :) not perfect though - but something u can try

**Comment by soulgalore** [comment]
Let us know if you need anything else :)
