### ISSUE TITLE
Upload existing har

### ISSUE THREAD

**Issue by rab2215** [sitespeedio/sitespeed.io#1452]
Im looking into a historical reporting dashboard for our current UI regression which already generates har files per test. I do like the look of the graphite/grafana dashboard, so is it possible to upload existing har files to achieve the same output?

**Comment by soulgalore** [comment]
Hey @rab2215 no not out of the box, you need to build that yourself, right now we only take the current data collected from the browser and stores that in Graphite.
Best
Peter

**Comment by tobli** [comment]
See #1384 as well

**Comment by rcherny** [comment]
Has anyone looked into this? I've got some tests run previously that I'd love to import into Graphite. Both sitespeed.io test output as HTML and of course some HAR files. I realize the HTML might be a lost cause but I already tried running the HAR files through pagexray. Nice output, but at a loss what to do next.

**Comment by soulgalore** [comment]
Hi @rcherny - @tobli started before but we have some things that we think has higher prio right now (we should add prio + close tasks that we will not do the coming year).

**Comment by tobli** [comment]
Yes, I looked at it a while back. For the most part, everything worked as is, however I had to hack around a few assumptions that data originated from a url that's being crawled. To make it work proper there are a few areas of sitespeed.io that needs to be rethought, and not something I'm working on right now.

So if you're prepared to get your hands dirty you should be able to put something together by hacking together a selected few plugins, and pass some data around. The complexity would depend on how much data you're looking to push to Graphite (just pagexray data, domain data, coach analysis etc.)

**Comment by soulgalore** [comment]
I think this is something we are open to PRs but we will not work on it (if not @tobli solution is almost finished).
