### ISSUE TITLE
Feature request: include TTFB in summary output

### ISSUE THREAD

**Issue by mipearson** [sitespeedio/sitespeed.io#1455]
In the CLI output:

```
[2017-02-14 05:39:32] 50 requests, 1241.54 kb, firstPaint: 757ms (±58.17ms), DOMContentLoaded: 1.83s (±60.72ms), Load: 2.43s (±150.22ms), rumSpeedIndex: 1137 (±59.64) (20 runs)
```

it'd be very useful if we could get the TTFB (along with std dev). I know we can get this from reading the full report, but I'm running many of these in succession to test small changes.

This is useful as the TTFB in our testing changes based on server load, and if it's too high (or the std dev is high) we know that the other values are not useful.

(also, while I'm here, why no standard dev on request count or page weight?)

**Comment by soulgalore** [comment]
Hey @mipearson thanks for the input, yes lets think about that for the next release, PR:s are welcomed :) 

If I remember correctly we output different metrics depending on what we have, so for example running in Docker with video will give you SpeedIndex and firstVisualChange.

Best
Peter

**Comment by soulgalore** [comment]
in master now and coming in 5.0 next week.
