### ISSUE TITLE
Got 401 from Graphite when sending annotation

### ISSUE THREAD

**Issue by davidbonnici1984** [sitespeedio/sitespeed.io#1460]
![image](https://cloud.githubusercontent.com/assets/905774/22995936/2391a470-f3cd-11e6-8793-55cd249cb8c7.png)

**Comment by soulgalore** [comment]
Hey @davidbonnici1984 
do you run your own Graphite or https://hub.docker.com/r/sitespeedio/graphite/? If you run the one we provide it is behind basic auth (guest:guest and you should change that if it is reachable). 

When you run, add --graphite.auth USER:PASSWORD and you should get rid off the 401.

Best
Peter

**Comment by davidbonnici1984** [comment]
Thanks, it worked with my credentials!
