### ISSUE TITLE
send request with the url for testing to the sitespeed.io and get back the result in json

### ISSUE THREAD

**Issue by foxpcteam** [sitespeedio/sitespeed.io#1461]
HI,
Great project guys!
i have installed the latest Docker image and i have question.
my script is build in php.
so i want to know if there is any way to send  request with the url for testing to the server where i have sitespeed.io and get back the result in json?

i cant find any way to make this work.

Thanks

**Comment by soulgalore** [comment]
Hey @foxpcteam glad that you like what we do :)

You run sitespeed.io by the CLI as default, if you wanna have a server and get the JSON you need to that yourself. You can have a look at https://github.com/sitespeedio/grunt-sitespeedio, there we import sitespeed.io run in nodejs and then you can take the JSON and return it. It will be some work though to add a queue (you only want to run one tets at a time on the same server).

Best
Peter

**Comment by soulgalore** [comment]
Got what you need @foxpcteam ? Closing this but please re-open if you need more info.
