### ISSUE TITLE
sitespeed.io with VS?

### ISSUE THREAD

**Issue by jt4000** [sitespeedio/sitespeed.io#1462]
I'm using Visual Studio 2015 and I wonder if sitespeed provide its application for dotnet?

Thank you!

**Comment by soulgalore** [comment]
Hey @jt4000 great that you are interested in sitespeed.io. I haven't been a Windows user for the last 17 years and don't have any knowledge of Visual Studio but it would be cool if you can run/use sitespeed.io from it. Sitespeed.io is built in NodeJS but it is best to run the ready made Docker containers to get everything setup for getting video and metrics like SpeedIndex & firstVisualChange.

Best
Peter

**Comment by soulgalore** [comment]
Closing let us know how it worked out.
