### ISSUE TITLE
What browser/UI factors could cause fluctuations in results with stable BackEndTime?

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1466]
Hoping someone can shed some light,

If there have been no code changes, and the BackendTime has been relatively stable, what are some factors that could cause fluctuations in the FirstPaint, DomInteractive, and FullyLoaded times?

My guesses are if there are javascript calls to populate tables and  calls to db may be slow, but does anyone have any other thoughts that could cause this fluctuation.

![image](https://cloud.githubusercontent.com/assets/22225816/23137893/a96910f8-f772-11e6-9ac2-883304a00347.png)

Thanks,

**Comment by soulgalore** [comment]
Hey @ppcuenca can you show the URL you are testing? Do you have ads? Do you have any third party content on your site?

First it is important that you run a server that has enough CPU/memory for Chrome/Firefox to work ok. For dashboard.sitespeed.io we run a $80 and that works ok for us (Digital Ocean). You can check how the metrics changes for example the [Barack Obama page on Wikipedia](https://dashboard.sitespeed.io/dashboard/db/page-summary). If you check those first dashboards we use current, daily and weekly averages. It is pretty stable except when we have a regression in the code :).

For a site that run ads you can [checkout NYTimes](https://dashboard.sitespeed.io/dashboard/db/page-summary?var-base=sitespeed_io&var-path=desktop&var-group=www_nytimes_com&var-page=_&var-browser=chrome&var-connectivity=cable&var-function=median). The first visual change is pretty stable:
<img width="704" alt="screen shot 2017-02-20 at 19 55 02" src="https://cloud.githubusercontent.com/assets/540757/23138253/8626702a-f7a6-11e6-9cd5-c60b7345d9ae.png">

But the SpeedIndex going up and down depending on the content:
<img width="714" alt="screen shot 2017-02-20 at 19 55 08" src="https://cloud.githubusercontent.com/assets/540757/23138257/90150bf0-f7a6-11e6-864e-2982267f49ca.png">

We also test the [same page on WebPageTest](https://dashboard.sitespeed.io/dashboard/db/webpagetest-page-summary?from=now-30d&to=now):
<img width="1440" alt="screen shot 2017-02-20 at 19 56 49 1" src="https://cloud.githubusercontent.com/assets/540757/23138293/cb476da8-f7a6-11e6-854d-9ed6541fa2d0.png">

And you can see it going up and down a lot (to be fair we run on the public WebPageTest.org to get more stable values should use your instance). But it's probably ads and content that are the main problem.

We can probably help you more if it's possible to share the URL!

Best
Peter

**Comment by cgoldberg** [comment]
also consider that network transfer time also is included in those metrics.   consider network topology and network conditions between sitespeed and the website under test...   loading a web page is done by requesting assets over many TCP connections.  traversing the the big bad Internet adds some unpredictably in network latency that contributes to fluctuations in metrics.

**Comment by soulgalore** [comment]
@ppcuenca with our latest best practice of setting up connectivity https://www.sitespeed.io/documentation/sitespeed.io/browsers/#change-connectivity that can help out depending on what was your current setup.

Would be super if you could get back and comment on our questions :) That would help others in the future.

I have one more question: Any reason you don't use SpeedIndex and other video related metrics?

Best
Peter

**Comment by soulgalore** [comment]
If you need more info, please re-open.
