### ISSUE TITLE
Run script at onLoad to pause video

### ISSUE THREAD

**Issue by jangrewe** [sitespeedio/sitespeed.io#1470]
I've had a look at the documentation if there's any obvious way to do this, but either there isn't one or i'm too dumb to read the docs, sooo...

I'm testing a site that has an embedded video (the main feature of the site), and this seems to cause the `lastVisualChange` metric to go through the roof. I'd like to run a script on/after the `onLoad` event that looks for the pause button of the video and clicks it, to stop the video from playing.

Now it seems as if none of the `browsertime.[script|preScript|postScript]` options would be fitting for this (according to my understanding of the docs), even though `browsertime.script` probably would be the closest, event-timing wise?

**Comment by soulgalore** [comment]
Hey @jangrewe there no super clean way to do that, but you could probably hack that with [browsertime.pageCompleteCheck](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/cli.js#L86-L88). Yep it is ugly but maybe doable. That JS runs after onload and will check when the page is "finished". That could also look for the button, disable and then do the standard check? Ping @tobli 

Best
Peter

**Comment by jangrewe** [comment]
That is some lateral thinking right there, great idea!
I'm setting this as the script:
```
return typeof window.quazer.actions.pause() == 'undefined'
```
which returns `true` and stops the player when entered into the console on my desktop, but according to the recorded video it doesn't really fire during the actual test. Any thoughts?

**Comment by soulgalore** [comment]
Sorry for not getting, no not sure. Will introduce Visual Complete 85% the next release, maybe that will help?

**Comment by soulgalore** [comment]
ok closing this, if you found a solution let us now, maybe other people can use it :)
