### ISSUE TITLE
Keep-alive enabled - bad results

### ISSUE THREAD

**Issue by TJ71** [sitespeedio/sitespeed.io#1480]
Hi,

We've recently enabled keep-alive on a number of our sites and are actually seeing the opposite of what you'd expect. The waterfall view in Sitespeed shows things to have slowed down considerably and also some connections to now be blocked. Reviewing the sites in Chrome Dev Tools and all looks good.

Would appreciate some guidance, am able to email results to review.

Thanks

**Comment by soulgalore** [comment]
Hey @TJ71  you can email me at peter [AT] soulgalore [dot] com and I can have a look. Do you have a dashboard like dashboard.sitespeed.io so you can see before and after?

Best
Oeter

**Comment by soulgalore** [comment]
For the record: @TJ71 and me been emailing and we continue there. I'll close this issue, can't see that it is anything related to sitespeed.io/browsertime.
