### ISSUE TITLE
--requestHeaders not being picked up when run via docker command

### ISSUE THREAD

**Issue by robertgates55** [sitespeedio/sitespeed.io#1481]
Struggling to prove this either way - when running via docker and passing the --requestHeaders file.json, how can I tell whether my headers are being added to my request? I don't believe that they are, but can't find anywhere in the logs that PROVES that they're not!

Am running:
docker run --privileged --shm-size=512m --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://somesite.requiring.authcookie.com --requestHeaders file.json

And my file.json looks like:
{
  "Cookie":"PHPSESSID=489vc71ao76po6hm7h1th3qnv1"
}

and passing --requestHeaders somefilethatdoesntexist.json gives precisely the same result as --requestHeaders file.json ... leading me to wonder whether it's even being picked up?

**Comment by soulgalore** [comment]
Hey @robertgates55 
if you use 4.x it is not picked up since we don't support adding headers. In 3.x we used BrowserMobProxy to add that but we wanted to get rid of it to be able to support HTTP/2. 

For Firefox I think [there's a plugin](http://stackoverflow.com/questions/15645093/setting-request-headers-in-selenium) that we could use and then set headers, but I haven't investigated if that would work. 

Best
Peter

**Comment by robertgates55** [comment]
Thanks Peter. 

I've had a try with an older version, but am getting the following error:
docker run --privileged --shm-size=512m --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:3.11.5 http://somesite.com --requestHeaders token.json 

Wed Mar  1 18:10:42 UTC 2017
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 49.0.2623.75 
Mozilla Firefox 45.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
/home/root/scripts/start.sh: line 17: /sitespeed.io/http://somesite.com: No such file or directory

On the 3.x version, did the parameters need to be passed differently?

**Comment by tobli** [comment]
Hi @robertgates55 
You can replace all arguments (from the URL and forward) with --help, to get help (including syntax) for the specific version you're running. Work in sitespeed.io 3, 4, and most other command line tools. A good thing to try whenever you're wondering what options you can pass to your favourite tool.

**Comment by soulgalore** [comment]
We still have the docs for 3.x here: https://www.sitespeed.io/3.x/configuration/#set-request-headers

But we don't it anymore since we wanna get people to use 4 but I see your problem with the request headers, let us create a task for it so we at least have it there.

**Comment by soulgalore** [comment]
Closing this, let me know if the docs for 3.x did't help you!
