### ISSUE TITLE
sitespeed.io or equivalent tools for native mobile performance rendering

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1482]
Hi,

I had an interesting discussion with some colleagues today about measuring rendering in native mobile apps. 

I know there are some options to use emulators, but most of these measure server response time or alternatively measure the service layer. Unfortunately this is not the same as the full stack or UI rendering we're accustomed to with sitespeed. 

Does anyone have any recommendations on how we could do this for a mobile native app? Or suggest any tools that might be able to achieve this?

Thanks!

**Comment by soulgalore** [comment]
Hey @ppcuenca I think to do things for native apps you need to add measurements in the source code. But let me know if you find out something else :)

/Peter
