### ISSUE TITLE
Jenkins sitespeed.io report does not display `Page summary`

### ISSUE THREAD

**Issue by sakonachhoeurng** [sitespeedio/sitespeed.io#1490]
Hey, please help, why it does not display the page when I run with command `sitespeed.io --browsertime.selenium.url http://10.10.10.120:4444/wd/hub --outputFolder build/logs https://www.web-essentials.asia/` but when I run on my local, it displays this. I do not what is the problem and cause.

Her is the screenshot
![capture 2017-03-05 at 13 56 15](https://cloud.githubusercontent.com/assets/12217854/23541371/9b4bde2e-0019-11e7-899f-6269f382ff2d.png)

Thanks for help and your time,
Sakona

**Comment by soulgalore** [comment]
Hey @sakonachhoeurng do you run the report in an iframe (using Publish HTML Reports)? 

Can check the logs from the run, is there an error there? Else check the console in your browser, do you see any error there?

Best
Peter

**Comment by sakonachhoeurng** [comment]
Yes, I use `Publish HTML Reports` to display the report by pointing to the file, my choice I choose index.html to display the report. I do not see any error there.
And on Jenkins we use version like this `sitespeed.io: 4.3.4`

**Comment by soulgalore** [comment]
Ok, that uses an iframe, wonder if that can cause an isseue. If you use Chrome and check the console on that page:

<img width="1153" alt="screen shot 2017-03-03 at 8 54 54 am" src="https://cloud.githubusercontent.com/assets/540757/23542742/1ed49de2-ffef-11e6-9cc1-e865f97fc753.png">

Nothing there?

**Comment by sakonachhoeurng** [comment]
Yes, I use chrome, and it does not display something. But this web page is my company internal website.

**Comment by soulgalore** [comment]
Can you zip the full result folder for that run and share it so I can have a look?

**Comment by sakonachhoeurng** [comment]
[build.zip](https://github.com/sitespeedio/sitespeed.io/files/816135/build.zip)
 Please check it.

**Comment by sakonachhoeurng** [comment]
I try to check with this from download and run file index.html and see that it display report correctly, but do not why in Jenkins does not display that.

**Comment by soulgalore** [comment]
yep it worked for me when I test your zip locally so I guess it must be an issue with Jenkins and running in the iframe?
<img width="1002" alt="screen shot 2017-03-03 at 9 04 59 am" src="https://cloud.githubusercontent.com/assets/540757/23543068/b4c9daaa-fff0-11e6-85a8-0fe9c0011a2d.png">

**Comment by sakonachhoeurng** [comment]
Yes, I think it problem with Jenkins. Cause it work correctly from local.

**Comment by sakonachhoeurng** [comment]
Do you know how that we can fix this, or another that can help?

**Comment by sakonachhoeurng** [comment]
I think it similar to this issue https://github.com/sitespeedio/sitespeed.io/issues/1265

**Comment by soulgalore** [comment]
Yep it is the same, lets focus on that. Closing this, ref https://github.com/sitespeedio/sitespeed.io/issues/1265

**Comment by fayazmd** [comment]
I have similar issue, I am currently using windows OS, so using oracle VM toolbox, and trigger the sitespeed.io and wiki_barack_obama tests. Looks like I am able to run the test, but unable to view the reports.

Note: I have mounted my local drive on the virtual toolbox and copied the reports and trying to open those reports in my local machine (windows) to view reports, but not opening.

**Comment by soulgalore** [comment]
@fayazmd and the fix in https://github.com/sitespeedio/sitespeed.io/issues/1265 didn't help?

**Comment by soulgalore** [comment]
Yes please open a separate issue. It seems it cannot reach the IP you are using?

**Comment by fayazmd** [comment]
IP is reachable and I am able to login to my application manually. And yes, will open a separate ticket, as my purpose is fulfilled at this thread (i.e., viewing reports)

**Comment by soulgalore** [comment]
Yeah but you are hijacking a closed issue :) Please create a new issue where you explain your problem and verify that you had done the fix for CSP referenced in this thread.

Thanks
Peter
