### ISSUE TITLE
[Question] Use browserstack and Elasticsearch as time serie db?

### ISSUE THREAD

**Issue by naxhh** [sitespeedio/sitespeed.io#1495]
Hi everyone.

I'm just starting to look at the project and I must say I like it a lot. so congrats on that :)

We are currently researching for tools to automate our performance statistic and have a clear picture on how we are doing over time.

Sitespeed sounds like the right tool but there are a few points I would like to have more feedback on:

- Browserstack as selenium server
I've seen you can change the selenium url using `--browsertime.selenium.url` but here is no way to send user/password

Allowing to send user/password would be nice because it means we would be able to use Browserstack, for example
In our case that allows us to test using real android devices.

Is this a thing you would like to have? If the answer is yes, could I get some directions on where to start looking to implement this?

- Elasticsearch as TSDB

I don't think this is ideal but I need to ask anyway.
We currently work with EKL stack.

What are your thoughts on allowing ElasticSearch as a destination database in the same way as work in influx is being done?

EDIT: Thinking about the last. Maybe statsd makes a better point as a plugin?

Thanks a lot for your time.

**Comment by soulgalore** [comment]
Hey @naxhh 
thanks :)

I'll jump to your questions:

> Browserstack as selenium server

We don't support that in [Browsertime](https://github.com/sitespeedio/browsertime) (that we use to run the browsers) at the moment, but if you could share the setup maybe we could add it. 

I have two main concerns for Browsertstack: You cannot choose the exact device to run on right? For example if you wanna run testing on an Android device and you will test 5 URLs, they will run on different devices? And If you run it 5 minutes later, they can run on another device? If you want to have stable values I think it's best to run on the same actual physical device. However, I haven't tried Browserstack so maybe I'm wrong :)

The other concern I have is connectivity, you want to make sure that you have the same one between the test and I'm not sure you can set that on Browserstack? You can test on [Android devices with sitespeed.io](https://www.sitespeed.io/documentation/sitespeed.io/mobile-phones/) but we don't have a good example how to set the connectivity there, but I would love if we could work that out together. Else you could have [WebPageTest](https://www.webpagetest.org/) and setup your own instances with Android (or Iphones) phones.

 > Elasticsearch

That would be cool, I think we wanna keep it as a [separate plugin](https://www.sitespeed.io/documentation/sitespeed.io/plugins/) but we can help out. There's an [old PR](https://github.com/sitespeedio/sitespeed.io/pull/1239) for Elasticsearch inside of sitespeed.io, but I think having it as an own plugin is the best.  If you wanna move on with that, let us know and we can help out moving you in the right direction.

Best
Peter

**Comment by naxhh** [comment]
> You cannot choose the exact device to run on right?
Well Im not sure either about this. I should make some dig. Because right now we are only using it for integration tests but will be nice to re-use it for this kind of stuff.

Anyway. I'll investigate and when I have some time I'll move the issue to Browsertime repo :)

> That would be cool, I think we wanna keep it as a separate plugin but we can help out.

Nice! I'll also take some time to review a bit about this. Also I'm very very new to elasticsearch so it will take me some time to even start :)

But if I have any question I'll be around.

Thanks a lot.

**Comment by naxhh** [comment]
Im closing this since the questions have been answered :)

Thanks!

**Comment by 2343909** [comment]
@soulgalore  Is this still valid response above stating pretty much that we cannot use Browserstack for as a mobile solution for FrontEnd performance testing?
