### ISSUE TITLE
Sitespeed.io - questions about using --browsertime.script

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#1496]
Dears, good morning!

We are testing to see if the sitespeed.io application can be used by our project, but we are experiencing difficulties using **--browsertime.script**.  We are trying to use this option to run all the interaction that occurs in our application.
Here are the models we tried to implement and the errors that are shown in the tests:

Running my script for my url, using the **--browsertime.script**:
`
sitespeed.io --preScript prescript/loginAndProxy.js https://toBeTested.com --browsertime.script script.js --browsertime.pageCompleteCheck 'return document.getElementsByClassName("targeted-overlay-container").length > 0' -n 1
`

Implementation (script.js):
`(function() {
  run(context) {
      return context.runWithDriver(driver => {
            driver.wait(until.elementLocated(webdriver.By.className("ember-view input-  token__input input-token__input--first-segment-is-text")));
            driver.findElement(webdriver.By.className("ember-view input-token__input input-token__input--first-segment-is-text")).click();
            var projectInput = driver.findElement(webdriver.By.className('ember-view input-token__input input-token__input--first-segment-is-text'));
            var projectName = 'a'; //project name
            projectInput.sendKeys(projectName);
      });
  }
})();`

Error Displayed:
`Couldn't execute script named script error:WebDriverError: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected token {
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64)
[2017-03-08 11:06:39] WebDriverError: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected token {
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64)
    at WebDriverError (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Driver.executeScript (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:887:16)
    at Promise.try (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:171:28)
From previous event:
    at SeleniumRunner.runScript (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:165:11)
    at Promise.resolve.then (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:159:27)    ` 

Could you help us with the implementation of this command line, or send us a model or example of using --browsertime.script ? What appears in the sitespeed.io documentation is still very little and has no example of the use of this command line.

Already, grateful for availability.

Regards,

**Comment by livyson** [comment]
Hello, @soulgalore! Can you help us?

**Comment by soulgalore** [comment]
Hey @livyson 
I think there's a mixup between pre/post script and actual scripts, I think we can make the documentation cleaner.

<code>--browsertime.script</code> is a JavaScript that will run inside the browser after the page has been loaded check out https://www.sitespeed.io/documentation/sitespeed.io/browsers/#custom-metrics. You can use that to collect extra metrics that is specific for your page or something that isn't collected in sitespeed.io by default. Meaning in the script you have access to everything that you have when you run Javascript in your browser.

<code>--preScript</code> is a Selenium JavaScript that has access to the Selenium objects before the page is loaded. You can use this to navigate to another page (pre load the cache) or login the user. After the preScript the browser will navigate to the URL that you want to test.

<code>--postScript</code> is a Selenium JavaScript that has access to the Selenium objects that run after the page has been loaded and after all the metrics has been collected. Use this to logout the user or whatever post actions you want to do.

So in your implementation the _script.js_ is using Selenium, but it runs inside the browser so it needs to be pure JavaScript only.

Hope that makes things more understandable.

Best
Peter

**Comment by livyson** [comment]
Thanks, @soulgalore !
I will try to use the pure javascript. :)

**Comment by soulgalore** [comment]
@livyson closing this, please re-open if you need anything else or create a new issue :)
