### ISSUE TITLE
Memory utilization increasing rapidly

### ISSUE THREAD

**Issue by timetobehappy** [sitespeedio/sitespeed.io#1502]
I basically followed the steps mentioned under "Up and running in 5 minutes" to set up my sitespeed instance in AWS using a t2 medium. I have a single script scheduled in Cron to run every 10 minutes. The script basically runs tests against 2 different home pages. default.json has iterations set to 3. 

Memory utilization was 11% 15 hours ago and now it is at 53%.  I am using sitespeed.io:4.4.0 

Attaching dashboard showing the mem utilization change.
![memory_disk](https://cloud.githubusercontent.com/assets/13108008/23757539/bf1d2906-04ac-11e7-8757-9aa26421e77d.png)

**Comment by soulgalore** [comment]
Hey @timetobehappy do you run sitespeed.io on the server and Graphite/Grafana on another server as in https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#production ?

The memory usage the last 7 days for the worker collecting metrics for dashboard.sitespeed.io looks like this:
<img width="397" alt="screen shot 2017-03-09 at 17 04 54" src="https://cloud.githubusercontent.com/assets/540757/23758628/a3a8c250-04ea-11e7-9036-fde2a0893d1f.png">

And for the server running Graphite/Grafana:
<img width="396" alt="screen shot 2017-03-09 at 17 06 23" src="https://cloud.githubusercontent.com/assets/540757/23758683/d53232e8-04ea-11e7-84a7-0690f41ed7fe.png">

but we use Digital Ocean. @beenanner do you have any input for setup on AWS?

Best
Peter

**Comment by timetobehappy** [comment]
Hi Peter, 
I have all on a single EC2 instance now. Plan to move to a production setup later.

Earlier I was using a t2 large EC2 instance and may have seen similar issues. But then I was not monitoring memory using any dashboards.

**Comment by soulgalore** [comment]
Hi @timetobehappy 
ok, can you check which process that hogs the memory, something like <code>ps aux --sort -rss</code>?

Best
Peter

**Comment by tobli** [comment]
I'd also test a single run (with the same config) in isolation to see how long that takes, and to check that all processes exit as expected. Judging from the graph, it might be that the previous run hasn't finished when the next begins.

**Comment by timetobehappy** [comment]
Thanks, @tobli.

Peter - I had restarted my instance today morning to change the instance type. I will go back to my original configuration and then get back to you with the data in a few hours.

**Comment by soulgalore** [comment]
@timetobehappy just wanna check, did you find something?

**Comment by timetobehappy** [comment]
I did a few things. 

1. Talked to a colleague about the memory utilization pattern we see and this is what he told me... _"The thing about monitoring memory on Linux servers it is not usually reported properly.  Linux will use almost all memory available for buffers and cache.  That memory is not considered free by most monitor scripts, but the memory used by the kernel for buffers and cache is really still available if needed by an application.  To get the real free memory you need to add free + buffers + cached to get the real value._

_[jboss@host bin]$ free
             total       used       free     shared    buffers     cached
Mem:       8051364    7833916     217448          4      37300    1367176
-/+ buffers/cache:    6429440    1621924 <-- This is the real amount of free memory.
Swap:      2097148     394200    1702948_


_From your [link](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html):
Name	Description
--mem-util	Collects and sends the MemoryUtilization metrics in percentages. This option reports only memory allocated by applications and the operating system, and **excludes memory in cache and buffers**.
--mem-used	Collects and sends the MemoryUsed metrics, reported in megabytes. This option reports only memory allocated by applications and the operating system, and **excludes memory in cache and buffers.**
--mem-avail	Collects and sends the MemoryAvailable metrics, reported in megabytes. This option reports memory available for use by applications and the operating system.
"_ 
So started capturing the available memory from "free -m" and this is the pattern I see.  Available memory is slowly decreasing but not yet a big concern. See the text file attached. It was 3380 MB when I started logging this and now it is 3332 MB. Dashboard data from AWS is attached for reference. Same pattern. 
![avail_used_2017-03-10_0953](https://cloud.githubusercontent.com/assets/13108008/23802000/8e117030-0577-11e7-8946-1cb05bf7416f.png)
![memory_util_2017-03-10_0953](https://cloud.githubusercontent.com/assets/13108008/23801999/8e056c0e-0577-11e7-8c4b-de403d6797c4.png)
[AvailMemory.txt](https://github.com/sitespeedio/sitespeed.io/files/834405/AvailMemory.txt)


2. Installed another tool (trial version) on my EC2 instance to look into the process memory consumption and here are my findings.

![image](https://cloud.githubusercontent.com/assets/13108008/23802542/4fef34fc-0579-11e7-97c9-1477bb58cad3.png)

- After when the tool was installed, the host was using about 574 MB (including that is consumed by the monitoring tool) and now it is at 717 MB.

- nginx using sitespeed/graphite grew from 84 MB to 104 MB

- The agent for monitoring grew from 76.5 to 76.9 MB

- grafana-server (using "grafana/grafana") grew from 24 MB to 25.3 MB

- carbon-cache.py was 17.5 MB and is still 17.5 MB

- sitespeed.js (siteseedio/sitespeed.io) ups and downs but around 118 MB mark. Don't see this as an issue.

- Ignored others as I don't see any issues there


Summary: As per the "free -m " data, we may have lost ~48MB. Of which 20 MB seems to have been taken by Graphite. Remaining 28 MB, I am not sure how to account for.

**Comment by cgoldberg** [comment]
"unused memory is wasted memory"

**Comment by soulgalore** [comment]
great @timetobehappy , thanks for getting back. I'll close this now.
