### ISSUE TITLE
How to custom file json in performance budget

### ISSUE THREAD

**Issue by sakonachhoeurng** [sitespeedio/sitespeed.io#1511]
Hello,

I do not have any issue, but I try to follow your document [https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/](url) but I seem not understand with `myBudget.json` and 
```
{
  "browsertime.pageSummary": [{
    "metric": "statistics.timings.firstPaint.median",
    "max": 1000
    }, {
    "metric": "statistics.visualMetrics.FirstVisualChange.median",
    "max": 1000
  }],
  "coach.pageSummary": [{
    "metric": "advice.performance.score",
    "min": 75
  }, {
    "metric": "advice.info.domElements",
    "max": 200
  }, {
    "metric": "advice.info.domDepth.max",
    "max": 10
  }, {
    "metric": "advice.info.iframes",
    "max": 0
  }, {
    "metric": "advice.info.pageCookies.max",
    "max": 5
  }],
  "pagexray.pageSummary": [{
    "metric": "transferSize",
    "max": 100000
  }, {
    "metric": "requests",
    "max": 20
  }, {
    "metric": "missingCompression",
    "max": 0
  }, {
    "metric": "contentTypes.css.requests",
    "max": 1
  }, {
    "metric": "contentTypes.image.transferSize",
    "max": 100000
  },{
    "metric": "documentRedirects",
    "max":0
  }]
}
```
This is what I need to add to file, and where that file I need to replace or put in?

Please help to verify and make it clear than.
Thanks,
Sakona

**Comment by soulgalore** [comment]
Hi @sakonachhoeurng 
yes sorry the docs are a little unclear: https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/ there's a link to the internal data structure: https://www.sitespeed.io/documentation/sitespeed.io/metrics/

There you can see what the internal data structure looks like. See if we can make the docs cleaner.

Best
Peter

**Comment by sakonachhoeurng** [comment]
yes, I understand.

**Comment by sakonachhoeurng** [comment]
Hey @soulgalore,

I have something wonder with this sentence 
```
You can define your own budget file with rules on when to break your build. This budget will return an error code status after the run or you can choose to output JUnit XML and TAP.
```
What does it mean? source from [https://www.sitespeed.io/documentation/sitespeed.io/continuous-integration/#jenkins](url)

**Comment by soulgalore** [comment]
Hey @sakonachhoeurng ah good I will make cleaner.

If you run sitespeed.io and you get something that doesn't match your budget file, the sitespeed.io process will return with an error code (0 is none error) so you can act on that, like break the build. But you can also look into the JUnit XML file or TAP output and break your build depending on that. Does that make things clear?

Best
Peter

**Comment by soulgalore** [comment]
Think is solved, please re-open if you need more info!
