### ISSUE TITLE
How run all tests without closing the browser 

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#1513]
Dears, good morning!

Is it to run all tests without closing the browser and login again or perform the application? I need to perform various urls test without closing the browser and need not perform login again, running prescript once in the first run.

Already, grateful for the contribution.

**Comment by soulgalore** [comment]
Hi @livyson 
no right now we only measure one page per run, so if you have a prescript that login the user and then access a couple of URLs, we will only get measurements for the URL that we hit after the preScript. We kept it like that in 4 to not make it too complicated, if you have any input how we can make it work in the future, please let us know :)

Best
Peter

**Comment by livyson** [comment]
@soulgalore, thanks for your answer! :)
