### ISSUE TITLE
Question: Does the sitespeed app tell exactly what tests your site didn't pass

### ISSUE THREAD

**Issue by pixelprogrammer** [sitespeedio/sitespeed.io#1514]
I have been using sitespeed recently to test a site I am working on and it works fine. I see lots of 100% scores except a few. The best practices one shows that it was about 59%. When I click on it I get sent to a page that shows a list of all the best practices I should look out for but not what my site necessarily failed at.

Is there a way to display which tests actually failed to give it a low score? I feel like with so much data being analyzed I am clearly missing something here. Maybe it exists somewhere but I don't really see it.

Thanks.

**Comment by soulgalore** [comment]
Hey @pixelprogrammer for some advice we have the Show/hide details button, if we have more info for an advice we show that when you click on the button.

![show](https://cloud.githubusercontent.com/assets/540757/23871753/f5fe6a7a-082b-11e7-8de1-78b3b6c52da4.png)

But it can also be that we have advice where we miss an actionable item, if you find something that is missing it would be super if you can create issues for that over at [the Coach](https://github.com/sitespeedio/coach) and we can see if we can add it.

Best
Peter

**Comment by tobli** [comment]
I'll close this issue, please open follow-up issues if needed.

Thanks!
/Tobias
