### ISSUE TITLE
[Question] Is it possible to record a CPU profile?

### ISSUE THREAD

**Issue by Giovanini** [sitespeedio/sitespeed.io#1517]
I'm using the SiteSpeed.io to record the Timeline with Developer Tools on my projects  (it's awesome, thanks!) but I looked in the SiteSpeed.io documentation on how to record the CPU Profile and I didn't find anything.

Is it possible? If it's not possible, do you think this would be a good feature to get into future versions of SiteSpeed.io?

**Comment by soulgalore** [comment]
There's no way to do it today but I agree that would be cool! Not sure if that is supported through Chromedriver through Selenium though? If you have time to have a look that would be great :)

Best
Peter

**Comment by soulgalore** [comment]
There's no way to do this today, so lets open a new issue when there is!
