### ISSUE TITLE
Run multi step test with sitespeed

### ISSUE THREAD

**Issue by timetobehappy** [sitespeedio/sitespeed.io#1518]
Hello - 

Is there a way to do a mutli-step test (Say a ecommerce checkout) directly using sitespeeed?

I did see the article on how this can be done using WPT.

**Comment by soulgalore** [comment]
Hey @timetobehappy it depends! We haven't implemented a user journey where we measure each and every step (there's an issue for that) but as long as you measure one specific page, you can use the pre/post script (running Selenium NodeJS scripts) to login/access different pages before you git to the page you want to measure: https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/

Best
Peter

**Comment by timetobehappy** [comment]
Thanks, Peter.
