### ISSUE TITLE
Having issues outputting the test results as JSON

### ISSUE THREAD

**Issue by obihill** [sitespeedio/sitespeed.io#1526]
I'm running sitespeed.io version 4.7.0 on a Mac OSX 10.10.5. I installed it via npm.

I can't seem to figure out how to output the test results as JSON. I checked the [configuration file](https://www.sitespeed.io/documentation/sitespeed.io/configuration/), but can't seem to find anything on it.

Kindly assist.

**Comment by soulgalore** [comment]
Hey @obihill you can either use the analysis storer plugin check https://www.sitespeed.io/documentation/sitespeed.io/plugins/#add-a-plugin for how you do to configure. It will store the JSON for each plugin that collects data.  Will that do or do you need the full blob of info from all? Then you could create your own plugin or maybe create a wrapper and use sitespeed.io from NodeJS (I need to verify that we pass on the metrics though).

Best
Peter

**Comment by tobli** [comment]
Also it depends on your use case, what of all the sitespeed.io data do you need (browsertime data, HAR files, coach analysis, WebPageTest data etc.). Browsertime and Coach are available as standalone tools as well, both of which includes json output by default.

**Comment by obihill** [comment]
Hi @soulgalore. Thanks for looking into this.

I tried the analysisstorer plugin and it generated [and stored] about 7 json files. The actual data I needed was in browsertime.json, but the other files could turn out to be very handy later. However, it would be great if you could make this information more prominent, especially for others who might be focused more on the data (JSON) than on the display (HTML).

@tobli My use case is more on-demand and data-focused. Essentially, I want to create an internal API that sits in front of sitespeed.io [running on Docker in DigitalOcean] that tests a website [on-demand], and then posts JSON results to cloud storage or database. I've done this successfully with a WebPageTest Private Instance in the past [which will also queue multiple requests], but it's quite expensive running it on AWS. I'm not sure if sitespeed.io or Browsertime or Coach is built for this kind of use case?

**Comment by tobli** [comment]
For data centric use cases (e.g. storing in a database) a custom plugin will be more powerful and efficient. That'll allow you to skip html generation, and easily pick and choose from all data as needed, without having to store files on disk. Currently it's not as easy or well documented as we eventually want it to be to create a custom plugin. Any help to get us there faster is appreciated.
If you only need Browsertime data there's other options available to you. Either just run Browsertime standalone (to get json files), or use it as a library and process the results in memory. @worenga has done really interesting stuff with this approach. Hope that helps!
/Tobias

**Comment by obihill** [comment]
@tobli Thanks a lot. I'm not sure if I have the chops or chutzpah to write a custom plugin, but I'll try and see how best to hack together a solution. One major issue will be queueing tests. Is there any mechanism within sitespeed.io that lets me know when a test is complete e.g. via webhook or something?

**Comment by soulgalore** [comment]
@obihill adding for reference: I really like https://github.com/Automattic/kue for queuing since the admin is super (and it is easy to implement). 

We can add a webhook, that would be cool (we don't have that today), can you create a new separate issue? We need to specify what the hook would include.

**Comment by obihill** [comment]
@soulgalore I was thinking a little bit more about this and I think it might be better to focus more on status than queue. I'll post a new issue about it.

**Comment by soulgalore** [comment]
I don't think there's more todo in this issue else please re-open @obihill !

**Comment by obihill** [comment]
@soulgalore Sorry, forgot to close this. This issue is resolved by the sitespeed.io plugin I'm working on, so will make that available and update this thread when it's ready. Cheers.
