### ISSUE TITLE
relativeBaseDir, outputDir, Slack and S3

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1527]
@tobli: I think we should reconsider the approach with relativeBaseDir. It's not a good fit for use with outputFolder. --resultBaseURL="http://example.com/bar" --outputFolder="../../foo" will result in http://example.com/foo/...when formatted by Slack. --resultBaseURL="http://example.com/bar" --outputFolder="/var/www/foo" becomes http://example.com/bar//var/www/foo which is probably not what the user wanted.

**Comment by tobli** [comment]
I've got an idea for this. Can hopefully PR a suggestion today.

**Comment by tobli** [comment]
This is on master now (took a while longer than expected), including test cases to cover both absolute and relative outputFolders.
