### ISSUE TITLE
Graphite >0.10.0 has different tag structure

### ISSUE THREAD

**Issue by kkopachev** [sitespeedio/sitespeed.io#1539]
Graphite-web prior to 0.10.0 used to accept tags as strings. That's what currently used in [sitespeed.io](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/graphite/send-annotation.js#L19)
However, [that's changed](http://graphite.readthedocs.io/en/latest/releases/0_10_0.html#id2), and that's going to 1.0.0 release (rc1 currently released). 

I tried few months ago with latest (at the moment) graphite-web, and it didn't accept tags as string.

**Comment by soulgalore** [comment]
Hey @kkopachev thanks for informing us! If I understand the docs we could add a switch and then just make the tags an array instead of a string with commas. Just need to find a Docker container with 1.0.0-rc1 then so we can test.

Best
Peter

**Comment by soulgalore** [comment]
I've pushed a branch that could fix it, could you test it @kkopachev ? Or do you know a Docker container that contains Graphite 1.0.0 rc1?

Best
Peter

**Comment by soulgalore** [comment]
merged and will come in the next release.
