### ISSUE TITLE
Status of Tests when running sitespeed.io with multiple URLs

### ISSUE THREAD

**Issue by obihill** [sitespeedio/sitespeed.io#1543]
@soulgalore Using sitespeed.io, it's possible to submit a list of URLs to test by creating a text file containing a list of URLs. However, there doesn't appear to be any way to query for status of the operation.

For example, if I submit 1000 URLs [via the text file], how do I know where sitespeed.io is at in the sequence of tests.

Even if a query operation on sitespeed.io is not possible, a simple webhook posted to a given URL [after each URL is tested] could suffice. The webhook is merely for notification and may contain the following elements:

- the cardinality of the operation (1000 in this case)
- the current URL tested
- the position of the current URL in the list
- the elapsed time since start of operation
- the elapsed time since start of current test
- the remaining number of tests 
- the output format of the current test
- the location of the output
- and more

It would be better if the posted data in the webhook is JSON.

Is this something that could be implemented to obviate the need for a more complicated queueing setup?

**Comment by soulgalore** [comment]
@obihill how do you want to use it? Is it only for checking how things work and current status? If there's something missing in the logs we could add that and then you could use something like http://blog.getpostman.com/2015/12/23/stream-any-log-file-to-slack-using-curl/ to report the progress to Slack.

**Comment by obihill** [comment]
@soulgalore I just ran the following:

```
sitespeed.io url.txt --plugins.load analysisstorer
```

Inside the url.txt, I have 3 URLs.

Here's what is shown in the logs:

```
Versions OS: darwin 14.5.0 nodejs: v6.9.1 sitespeed.io: 4.7.0 browsertime: 1.0.0-beta.31 coach: 0.31.0
Starting chrome for analysing http://www.chevron.com 3 time(s)
Testing url http://www.chevron.com run 1
Testing url http://www.chevron.com run 2
Testing url http://www.chevron.com run 3
43 requests, 1574.30 kb, firstPaint: 7.10s (±626.54ms), DOMContentLoaded: 7.36s (±604.30ms), Load: 17.82s (±1.01s), rumSpeedIndex: 12884 (±373.95) (3 runs)
Starting chrome for analysing http://www.yahoo.com 3 time(s)
Testing url http://www.yahoo.com run 1
Testing url http://www.yahoo.com run 2
Testing url http://www.yahoo.com run 3
153 requests, 1735.68 kb, firstPaint: 4.28s (±500.09ms), DOMContentLoaded: 22.75s (±5.51s), Load: 66.28s (±760.86ms), rumSpeedIndex: 8712 (±1835.54) (3 runs)
Starting chrome for analysing http://www.sitespeed.io 3 time(s)
Testing url http://www.sitespeed.io run 1
Testing url http://www.sitespeed.io run 2
Testing url http://www.sitespeed.io run 3
10 requests, 92.93 kb, firstPaint: 1.99s (±101.11ms), DOMContentLoaded: 1.93s (±130.23ms), Load: 4.14s (±511.88ms), rumSpeedIndex: 2490 (±255.98) (3 runs)
Render HTML for 3 page(s) 
HTML stored in /Users/obihill/sitespeed-result/www.chevron.com/2017-03-23-14-38-08
```

The data is there, but it's not very machine-readable, especially when I want to parse the logs after-the-fact using regex. However, if after the test summary [or in place of it], we could have something like this:

```
{"test_result": {"test_count": "3", "url": "http://www.yahoo.com", "requests": "153", "size": "1735.68", "firstPaint": "4.28s", "firstPaintMoE": "±500.09ms", "DOMContentLoaded": "22.75", "DOMContentLoadedMoE": "±5.51s", "Load": "66.28", "LoadMoE": "±760.86ms", "rumSpeedIndex": "8712", "rumSpeedIndexMoE": "±1835.54"}}
```

I think it would make life much easier.

Of course, I would like to include some more data-points, but the point is I can very easily parse the log file using PHP, Node, etc. and extract all the results, or the specific result for a specific URL. Also, the log file would not be much larger that it is now.

Regarding the status, is it possible to add another listing in the log like this after each test result summary like so:

```
Test progress counter is 2 for http://www.yahoo.com 
```

Again, having this entry inserted in the log will let me run a substring search [via regex] at any time to get the last occurrence of the `Test progress counter` so I know how many tests have been completed.

Would this be too problematic to implement? Can this be done via plugins?

**Comment by soulgalore** [comment]
Hey @obihill the data (all the metrics) is stored in /data/ for the summaries and then for each URL in their respective data folder when you use the analysisstorer, those are JSON files so you easily can parse them. Else you can add your create your own plugin that collect messages (each tool sends a message with the data collected) and you can take the data and store it. That way you will get the data when each URL is finished. 

For slacking the log I meant more a easy way for you to keep track that it is working. We use it to keep track of errors. Regex the log seems dirty :)

I would avoid running 1000 URLs after each other because it will be memory heavy, I would split it in 100 so it's easier to handle and if something goes wrong, you only lost 100 runs :)

For logging, in 3.x we had something like where we logged each 10 or 20 URL saying "Testing URL 20 out of 100" or something like that, maybe we can do something like that.

Best
Peter

**Comment by obihill** [comment]
@soulgalore Thanks for the feedback, The reason why I prefer the summaries in the log is because the log file size post-operation is bound to be much, much smaller [and easier to deal with] than the JSON data files. It's also easier to parse because I get all the data from a single file [not seeking hundreds of files in multiple directories]. Machines are very fast at doing things like this. 

The whole log file after doing 100, or even 1000 URLs, will not be a very large file. This is not the case for the JSON data summaries. For example, in the example I did above with just 3 urls, the browsertime.json file for one of those URLs came out at 28Mb. I use the Atom text editor on a 16Gb Macbook Pro and I got a warning [the kind when you open a very large text file]. Doing this via machine will also be a significant memory issue.

So, I will take your suggestion and run 100 URLs at a time for memory-sake. However, I would like to find a way to:

1. Add the "Testing URL {current} out of {total}" notification after each URL test [just like you described was possible in 3.x. Yes, please!]
2. Update the format of the test result summary from what it is now to a more machine-friendly JSON format, and also have the ability to add more data-points [if possible]. This way, I can easily parse/query data from a single log file instead of several JSON files.

Doing this will solve all my problems and will obviate the need for a complicated queue setup.

Are these two things workable? Is it something I can do myself if your plate is full? Is it something that can be done via plugin [I'm a green-horn here though]?

Regards,

**Comment by obihill** [comment]
@soulgalore Regarding No.2 requirement above, I think it should be as easy as tracking down the code that is responsible for logging the result summary in the log file:

```
113 requests, 1534.12 kb, firstPaint: 7.03s (±1.17s), DOMContentLoaded: 21.98s (±980.96ms), Load: 68.24s (±1.10s), rumSpeedIndex: 9215 (±1078.28) (3 runs)
```

And then updating it to fit my requirements. Still trying to figure out the whole structure of sitespeed.io so I would appreciate any assistance.

**Comment by soulgalore** [comment]
I really think you should do the plugin :) We can help out get you going, checkout how we collect domain data as a simple plugin:
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/domains/index.js

We listen on messages of the type _browsertime.har_ and then collect the data we need. You could do the same, and I can help you with which messages you need if you give me the data that you wanna collect.

**Comment by obihill** [comment]
@soulgalore Thanks for the link. I'm just not familiar with the plugin architecture, but maybe with some hand-holding we can figure out a solution.

Essentially, I want all the data that you find under the "Detailed Summary" HTML page, but in JSON format, and included in the log file after each URL test [as earlier described].

So how do we get started?

**Comment by soulgalore** [comment]
So the detailed summary is for all tested URLs https://results.sitespeed.io/sitespeed-result/en.wikipedia.org/2017-03-23-23-00-03/detailed.html
 
You are interested in [this](https://results.sitespeed.io/sitespeed-result/en.wikipedia.org/2017-03-23-23-00-03/pages/en.wikipedia.org/wiki/Barack_Obama/index.html) right (min/median/max for the runs you do on one URL)?:
<img width="1002" alt="screen shot 2017-03-24 at 00 12 22" src="https://cloud.githubusercontent.com/assets/540757/24274120/a09f7404-1026-11e7-8619-72ba9a886deb.png">

A good start is to read https://www.sitespeed.io/documentation/sitespeed.io/plugins/ it's not perfect but at least a start. Then everything in sitespeed.io is a plugin so you can browse [the source code for plugin](https://github.com/sitespeedio/sitespeed.io/tree/master/lib/plugins) to find some inspiration. Would that do for a start?

**Comment by obihill** [comment]
Yes, that data is what I need.

Ok, so I've put together the boilerplate for the plugin. Essentially, I'll just be trying to replicate your default logging functionality, but with the minor enhancements I mentioned earlier.

I'll have to take a few days to get my head around the architecture and I'll get back to you.

Thanks.

**Comment by obihill** [comment]
@soulgalore So I just put this together:

```
'use strict';

const messageMaker = require('/usr/local/lib/node_modules/sitespeed.io/lib/support/messageMaker');
const path = require('path');

module.exports = {
    name() {
        return path.basename(__dirname);
    },
    open(context, options) {

    },
    processMessage(message, queue) {
         console.log(message.type);
         console.log(message);
    },
    close(options, errors) {

    }
};
```

Saved it to an `index.js` file in a path under my current working directory i.e. `sitespeed-plugin/extralog`. And then I ran it like so:

```
sitespeed.io http://www.sitespeed.io --plugins.load sitespeed-plugin/extralog
```

It worked! 

I also noticed that there were a bunch of messages output in the console.log, is this the way it works i.e. output messages as they are generated? I took notice of the message types and there were quite a number of them from `url` to `browsertime.run` to `pagexray.run` and more.

Does this mean I can just grab the data I want on-generation, generate JSON to my preference, and then use the `fs` module to output to file? 

This might turn out to be even more awesome than I initially thought. I'd love to understand how to mimic logging.

**Comment by soulgalore** [comment]
sorry I missed answering this:
> Does this mean I can just grab the data I want on-generation, generate JSON to my preference, and then use the fs module to output to file?

yep exactly.

**Comment by obihill** [comment]
Thanks. I will keep this open for now until the plugin is ready.

**Comment by soulgalore** [comment]
so @obihill can I close this or?

**Comment by soulgalore** [comment]
Closing but please re-open or send a PR if this is something you need.

**Comment by obihill** [comment]
Hi @soulgalore. Thanks. Will do.
