### ISSUE TITLE
Hash symbols in URLs not supported

### ISSUE THREAD

**Issue by danut-iosif** [sitespeedio/sitespeed.io#1548]
Hello!

This issue was closed previously, as it was before v4.0, but it's still present running from the latest docker-compose.yml.

As reported initially in #824 and #831 (a comment from a bit down), any hash symbols in the URLs will stop proper directory creation, with the outputs being overwritten for each new URL.

If you need any more info, please let me know.

Kind regards,
Dan

**Comment by soulgalore** [comment]
Hey @danut-iosif the current behavior is a feature, not a bug :) If you have links to the same page linking to different parts of the page, that is the same page.

Do your site serve different content depending on the hashbang? That's kind of an anti-pattern right, and you can fix that by changing the URL. Or what tool do you use to get those URLs=


Best
Peter

**Comment by danut-iosif** [comment]
Hello, Peter!

Hah, read more about this hashbang-in-URLs thing and managed to convince our developers to get rid of them.

Thank you for the support, nonetheless, mate!

Kind regards,
Dan
