### ISSUE TITLE
Synchronize docker machines time with host

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/sitespeed.io#1549]
Hi

the docker machines are always out of sync with the host time. It's especially visible when daylight saving time is on. It can lead to misinterpretation of the logs (I record them while running the tests).
This is a more general docker behaviour, and it looks like there is dozen of ways to do it and I dont know which one could be good.
see https://github.com/docker/docker/issues/3359#issuecomment-32150214 or https://forums.docker.com/t/time-in-container-is-out-of-sync/16566/11 for discussions.

Anyway, when running the setup of grafana, or later when machines are already running, it would be nice to be able to choose an option about time : sync with host (in my case, I know my host has the correct time) or setup a timezone and let Linux synchronize with an external server.
At least suggest a method in the documentation, for non-sysadmins like me :)

thanks

**Comment by soulgalore** [comment]
Hey @jpvincent 
I tried on my instance and there my container and the server was already in sync, so when I tried out <code>-v /etc/localtime:/etc/localtime:ro</code> I couldn't see any difference. If you could try that it would be great! 

For sitespeed.io you can use <code>--utc</code> to make the timestamps in sitespeed.io use utc but I guess that is not a issue for you.

Best
Peter

**Comment by jpvincent** [comment]
Mapping the volume from the docker machine to the host one did the trick, thank you very much.
I wrote that in a .yml file
