### ISSUE TITLE
How uninstall the sitespeed.io??

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#1565]
Guys, good morning! 

I have problems in my version and I'm trying to uninstall sitespeed.io and install it again. How do I uninstall these it? 

Thank you!

**Comment by soulgalore** [comment]
Hey @livyson if you run npm try https://docs.npmjs.com/cli/uninstall

But we prefer if you run Docker :)

Best
Peter

**Comment by livyson** [comment]
Thanks so much!
