### ISSUE TITLE
Sitespeed.io work with dynamic allocated url

### ISSUE THREAD

**Issue by linwenting** [sitespeedio/sitespeed.io#1568]
How does sitespeed.io work with dynamic allocated url? 
ex: I need to log in to a main website https://something.com first and get an encrypted id xxxx. Then I need to test the web performance of https://somehting.com/xxxx page

**Comment by soulgalore** [comment]
Hi @linwenting 
there's no way today to get sitespeed.io to work with that. You could maybe use WebPageTest (but I'm not sure), check out the documentation for scripting https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting

Best
Peter

**Comment by linwenting** [comment]
@soulgalore Thanks for the information.
