### ISSUE TITLE
Chrome timeline, dumpTraceCategoriesLog and traceCategories parameter

### ISSUE THREAD

**Issue by xavier-medioni** [sitespeedio/sitespeed.io#1569]
Hi Gentlemen !

Once again, Thanks to the whole Sitespeed team for all the work already accomplished !

And I also came today with a question.
I am focusing today about this chrome timeline extraction available from sitespeed.io v 4.5:
https://www.sitespeed.io/that-timeline-from-chrome/
with the cl parameter: --browsertime.chrome.dumpTraceCategoriesLog

I am trying to combine the timeline file / timeline message to generate automatically an analysis with the speedline tool, available as cl or nodejs library:
https://github.com/pmdartus/speedline

With a timeline file extracted manually from my chrome browser, it works fine (file: timeline-0.json in the currently attached data.zip). Every options where selected in the chrome devtools panel (i.e.: Network, JS Profile, Screenshots, Memory and Paint) and the speedline output is generated.

When using speedline (the very same way) with the trace-0.json (also available in the attached data.zip), I get
> speedline ./trace-0.json --pretty
No screenshots found in trace
[]
Error: No screenshots found in trace
    at Object.extractFramesFromTimeline (/usr/lib/node_modules/speedline/src/frame.js:94:25)
    at module.exports (/usr/lib/node_modules/speedline/src/index.js:31:15)
    at Object.<anonymous> (/usr/lib/node_modules/speedline/cli.js:94:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)

Whatever the stacktrace, I assumed there is something about the --browsertime.chrome.traceCategories, probable not including Screenshots option with its default value.

So is there away to know the default parameter value ? And, as you guessed, is there away to add the "Screenshots" option (or any other mandatory options) to make it work with speedline ?

Thanks by advance !

Xavier

[data.zip](https://github.com/sitespeedio/sitespeed.io/files/905421/data.zip)

**Comment by soulgalore** [comment]
Hi @xavier-medioni and thanks for the kind words. <code>disabled-by-default-devtools.screenshot</code> should turn on the screenshots, but not 100% user Chromedriver/Selenium will produce those, let us know how it works out.

Personally I think though it is better to use our Docker containers and get SpeedIndex and the rest analyzed from the video :)

Best
Peter

**Comment by xavier-medioni** [comment]
Hi Peter / @soulgalore,

Thanks for answering so fast !
And I can confirm: Dear readers, make your life easier, and USE THE PROVIDED DOCKER CONTAINER !!!

:-)

And for the other people working in particular contexts: Too bad, better luck next time...

In my case, the produced trace-0.json file using the cl parameter "--browsertime.chrome.traceCategories disabled-by-default-devtools.screenshot" does not contain expected screenshots / frame attribute into the json structure.

As protocol:
**- file 01**:
     source: extracted manually from chrome devtools, with "Screenshots" selected: works with speedline
**- file 02**:
     source: from sitespeed cl without parameter --browsertime.chrome.traceCategories
     result: does not work with speedline + once imported in chrome devtools: no screenshots / frames
**- file 03**:
     source: from sitespeed cl with parameter --browsertime.chrome.traceCategories disabled-by-default-devtools.screenshot
     result: does not work with speedline + once imported in chrome devtools: no screenshots / frames

As you can imagine, the last usecase made me very sad :-(

I hope this helps

Bonus: As extra doc for the current purpose:
https://github.com/axemclion/browser-perf/issues/36
https://github.com/GoogleChrome/lighthouse/issues/420



[new-data.zip](https://github.com/sitespeedio/sitespeed.io/files/905864/new-data.zip)

**Comment by xavier-medioni** [comment]
New bonus reference:
https://github.com/paulirish/automated-chrome-profiling/blob/master/get-timeline-trace.js

**Comment by soulgalore** [comment]
yes, been looking for adding one of Pauls libraries to the result pages when we collect the trace log to make something sane out of it, but haven't had the time yet. Not 100% sure which views that we should use

**Comment by xavier-medioni** [comment]
Another very helpful Paul's lib is [pwmetrics](https://github.com/paulirish/pwmetrics).
And my Paul's top charted is [speedline](https://github.com/paulirish/speedline), cause it processes the whole "paint and detect changes" timeline !

So thanks by advance to @soulgalore to integrate @paulirish 's work into Sitespeed ! :-D

**Comment by soulgalore** [comment]
I think the video we record and using VisualMetrics as we do right now so we can use it for Firefox too is pretty good. For FirstMeaningFullPaint I suggest that you verify those values using for example WebPageTest before you actually use them. When I tried it I could see that values could be 500 ms off (happening before firstPaint) for Wikipedia, so I think you should treat it as experimental (that's why we haven't pushed it Browsertime).

**Comment by xavier-medioni** [comment]
Extra info / Update:

Using Sitespeed 5.2.1 nodejs lib:

According the brand new reference: (https://github.com/paulirish/automated-chrome-profiling/blob/master/get-timeline-trace.js)

I tried to set browsertime.chrome.traceCategories to the following value:

-*,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,toplevel,blink.console,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot,disabled-by-default-v8.cpu_profile,disabled-by-default-v8.cpu_profiler,disabled-by-default-v8.cpu_profiler.hires

and the generated trace-0.json generated file still does not contain frame information :-(

**Comment by soulgalore** [comment]
I think that then it is a bug in Chromedriver.

**Comment by siteriaitaliana** [comment]
hit by the same issue atm, anybody managed to get this? I'm trying to have the LH reports from the trace logs generated by browsertime but without screenshot there isn't much interesting being generated

**Comment by soulgalore** [comment]
Ah thanks for that link.

**Comment by xavier-medioni** [comment]
Hi Al,

A few additional documentation (even if then code is 2 years old):
[axemclion/chrome-selenium-timeline.js](https://gist.github.com/axemclion/38265a963f5a863f7a53)

**Comment by soulgalore** [comment]
I'm not seeing how we will use this in sitespeed.io, instead I think it's better to help @siteriaitaliana with his Lighthouse plugin.

**Comment by xavier-medioni** [comment]
Hi all,

The main point is to be able to map the network information (from the HAR file) to the visual progress and the execution information (from the trace file). Those data make sense only if extracted from the same page load in order to model the page lifecycle.
According what I have read from the lighthouse plugin from @siteriaitaliana, a second lighthouse page load is performed.

Today, I only can retrieve the visual progress data with Sitespeed under the following conditions:
- using docker: see #1634 for further details
- with a Linux distribution
- and because a video is recorded, via xvfb, then processed

And there is so many other correlations to automate (as Sitespeed plugin) with the screenshot and browsertime combined data, and I really prefer Sitespeed to lighthouse (really guys, and once again, great job !) !

Sorry for "spamming", but I try to provide as many information as it gets and I really hope this helps !

Xavier

----------

**Additional information:**
After further testing, lighthouse has the following default traceCategories enabled:

`-*,toplevel,v8.execute,blink.console,blink.user_timing,benchmark,loading,latencyInfo,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot`

We can see it when running:
`lighthouse --list-trace-categories`

With those default options, a *-output-0.trace.json file is generated, and can be dragged into Chrome devTools Performance panel, including the screenshot options.

When running sitespeed with the very same traceCategories enabled, as:

`sitespeed.io -b chrome -n 1 https://www.wesplay.com --plugins.remove html --plugins.add analysisstorer --plugins.list --browsertime.chrome.collectTracingEvents --browsertime.chrome.collectNetLog --browsertime.chrome.collectPerfLog --browsertime.chrome.traceCategories="-*,toplevel,v8.execute,blink.console,blink.user_timing,benchmark,loading,latencyInfo,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot"`

The trace-0.json file generated this way, once dropped in Chrome devTools, does not contain the screenshot information.

**Comment by soulgalore** [comment]
@xavier-medioni I personally think @siteriaitaliana approach is fine. What makes lighthouse good is the rules it has, and to be ables to run those is kind a nice feature. 

The VisualMetrics though from Lighthouse can be wrong for slow sites since there's a limit on how many screenshots that can be made (450 frames see https://bugs.chromium.org/p/chromium/issues/detail?id=739759).  If that's fixed in the future, Speedline could be something to implement. Right now the only way to get correct SpeedIndex is running through Browsertime or use WebPageTest.
