### ISSUE TITLE
Optimize screenshot in results

### ISSUE THREAD

**Issue by pborreli** [sitespeedio/sitespeed.io#1570]
My docker instance of grafana/sitespeed is running out of space because of the size taken by the screenshot in results page.

```bash
ls sitespeed-result/website.com/2017-04-10-10-04-06/pages/website.com/data/screenshots/

2.6M 0.png
3.0M 1.png
3.0M 2.png
```

Not sure is png is a good format for storing screenshots. 
What about optimising those files and maybe add an option to disable screenshots in results ?

**Comment by lbod** [comment]
You can disable screenshots using `--plugins.disable screenshot`

**Comment by pborreli** [comment]
@lbod thanks, indeed it doesn't generate the screenshot anymore but it generates 404 in results
![image](https://cloud.githubusercontent.com/assets/77759/24858690/455be74a-1de5-11e7-83b5-00eba7fdd9bf.png)

**Comment by soulgalore** [comment]
In 3.x we used pngcrush if it was installed on the server to compress the image, lets do something like that again. Taking a PR for the broken image if you disable screenshots :)

**Comment by soulgalore** [comment]
We should be able to do this with a plugin. We should make sure the plugin that stores the screenshots sends a message to the queue when the file is stored, and then this plugin will optimize the image.

**Comment by pborreli** [comment]
shouldn't JPG a better format to store those captures ?

**Comment by soulgalore** [comment]
yeah but then you need to have imagemagick or graphicmagick installed to convert it or is there another way?

**Comment by Algram** [comment]
We could use something like Sharp https://github.com/lovell/sharp. It would still need compiling but has very good cross platform support and is fast. I like the idea of keeping this a plugin.

**Comment by soulgalore** [comment]
@Algram yes good idea, that would be great to convert to jpeg + change the size. Let me give it a try.

**Comment by soulgalore** [comment]
Did a quick try, this will work great. Think we should include it in the screenshot plugin by default and then make it configurable.

**Comment by soulgalore** [comment]
Started in https://github.com/sitespeedio/sitespeed.io/tree/sharp

**Comment by soulgalore** [comment]
This was released a couple of releases ago. You can now switch to jpg and set compression level.
