### ISSUE TITLE
Crawler seems to stop after 200 urls

### ISSUE THREAD

**Issue by kj-brown** [sitespeedio/sitespeed.io#1572]
I'm having issues trying to use the crawler on our domain. I'm using the sitemap on our website with `-d 2 -m 40000`, but unfortunately the crawler seems to stop after testing the original URL plus 200 more. 

Is there a time limit on the crawler, or something I'm missing for the number of URLs it can click?

**Comment by soulgalore** [comment]
Hey @kj-brown what version of sitespeed.io are you using? There should not be a limit if I remember correctly in 4.x, and no difference if you increase -d to say 3? Or do you have more than 200 links on the first page? From the help:
<pre>
Crawler
  --crawler.depth, -d     How deep to crawl (1=only one page, 2=include links
                          from first page, etc.)
  --crawler.maxPages, -m  The max number of pages to test. Default is no limit.
</pre>

Best
Peter

**Comment by kj-brown** [comment]
I'm currently using 4.7.0? There's more than 200 urls on the first page - I did try increasing the depth and the max pages to see if there were any changes but it still seems to max out.

**Comment by soulgalore** [comment]
The exact 200 numbers make me think that there's a bug somewhere, can you share the URL so I can test? I think we had that 200 hardcoded number in 3.x that's why I asked about version :)

**Comment by kj-brown** [comment]
No problem - it's http://www.which.co.uk/sitemap/ 👍  thanks for all your help!

**Comment by soulgalore** [comment]
I run a test and I think there's something one of the pages that breaks the crawler :| Tried on other domains/URLs and there it works.

**Comment by soulgalore** [comment]
Next step is to try it out with [simplecrawler](https://github.com/cgiffard/node-simplecrawler) standalone to see if it works. Any change you have time to help with that @kj-brown ?

**Comment by kj-brown** [comment]
Sorry, I was ill yesterday @soulgalore!

I'm on it now 👍

**Comment by kj-brown** [comment]
Yeah, looks like we're getting a fetch error which is coincidentally 199 urls in. it loads up the 200 and ends for some reason.

**Comment by soulgalore** [comment]
ok, let us check then what error we get, the crawler should still continue with the rest, so I think we need to do some modification on our side.

**Comment by beenanner** [comment]
I ran this through simplecrawler and it didn't seem to crash for me and made it through almost 5k of URLs.

```
fetchstart http://www.which.co.uk/reviews/%5C&quot;/reviews/toasters/article/how-to-buy-the-best-toaster%5C&quot;
fetched 4741 of 4743 — 2 open requests, 0 open listeners
fetchheaders http://www.which.co.uk/reviews/toasters/compare
fetched 4742 of 4743 — 2 open requests, 0 open listeners
fetcherror http://www.which.co.uk/reviews/toasters/compare
fetched 4742 of 4743 — 1 open requests, 0 open listeners
fetchheaders http://www.which.co.uk/reviews/%5C&quot;/reviews/toasters/article/how-to-buy-the-best-toaster%5C&quot;
fetched 4743 of 4743 — 1 open requests, 0 open listeners
fetcherror http://www.which.co.uk/reviews/%5C&quot;/reviews/toasters/article/how-to-buy-the-best-toaster%5C&quot;
fetched 4743 of 4743 — 0 open requests, 0 open listeners
complete null
```

**Comment by beenanner** [comment]
oops just saw @kj-brown comment so it is giving fetch errors. :-)

**Comment by beenanner** [comment]
I ran this against a large sites and the fetch errors didn't seem to occur there around the 200 URL mark. I think this is specific to the www.which.co.uk domain.

**Comment by beenanner** [comment]
Here is the js file I threw together.

https://gist.github.com/beenanner/310812658c74f90af3c390809aab393f

**Comment by soulgalore** [comment]
Nothing to do with sitespeed.io, closing.
