### ISSUE TITLE
help.html - information

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#1582]
I was looking at the structure on the page 'help.html'. Does not all the subheadings (Example... 'Do not load specific print stylesheets', 'Avoid slowing down the critical rendering path', etc...) have static information... are generated dynamically? If so, how are they loaded and where? Can you load them statically?

**Comment by soulgalore** [comment]
Hey @amic81 ,
the advice from the Coach are collected from the coach [here](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/htmlBuilder.js#L104-L109) the other content are static in the pug file: https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/templates/help.pug

What do you want to do?
Best
Peter

**Comment by amic81** [comment]
Hi Peter,  thanks for the answer, but in 

'https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/templates/help.pug' 

I can not find ('Do not load specific print stylesheets', 'Avoid slowing down the critical rendering path', etc...), these parts are loaded dynamically? Where and how? I wish I could translate it.

Bye
amic81

**Comment by soulgalore** [comment]
Hi again @amic81 yes they are loaded dynamically from the coach [here](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/htmlBuilder.js#L104-L109). The text lives in https://github.com/sitespeedio/coach/tree/master/lib DOM and HAR, each advice has there own snippet.

Best
Peter

**Comment by quartex** [comment]
Hi Peter, thanks for the all,
I work with amic81 and we try to translate all html site output from english to a different language.
Could we suggest for newer version to use a better separation from code to string value used in the output (in a json files with a index for the messages ??) because now is almost impossible to do this work without touch more files (also with code inside) finding it using debug trace. Now is a almost impossible work to do.

**Comment by soulgalore** [comment]
Hi @quartex yes we have no support for different languages right now and I'm not sure about the best way to fix that, but we are open for discussion. Let us now if you got an idea how we can make it better for the next release :)

Best
Peter

**Comment by amic81** [comment]
Hi Peter, always about the translation of the **help.html** page. ;-)
Some descriptive parts are found under the **node_modules/webcoach** directory (Rif. coach).
With the docker, the **node_modules** directory is not present in the image, it is recreated every time and as a result the webcoach directory (with any translations) is reset, losing any translation. 
I thought I would exclude the option **!node_modules/webcoach** in the file _.dockerignore_ and in the file _package.json_ to avoid downloading **"webcoach": "0.34.0"**. 
How could the solution be fine or can you give me a better solution? Thank you

**Comment by soulgalore** [comment]
Hi @amic81 ,
I think hacking it isn't a solution that will work in the long term. Better to use https://github.com/mashpie/i18n-node or something like that both in the coach and in sitespeed.io, so that we have a clean separation.

Best
Peter

**Comment by quartex** [comment]
Hi soulgalore,
Mashpie seems great with webtranslateit.com tool ... now is a very long and hardly task translate and mantain it
+1 for me ;-)

**Comment by soulgalore** [comment]
I think this will not happen, sorry. I want to focus on other things.
