### ISSUE TITLE
Prescript syntax

### ISSUE THREAD

**Issue by cambiph** [sitespeedio/sitespeed.io#1586]
Hey,

I was wondering if the syntax of the prescript in the [documentation](https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/) is still correct.
When I follow the guidelines at [seleniumhq](http://seleniumhq.github.io/selenium/docs/api/javascript/index.html) it looks very different.

I am using the following code:

```javascript
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
        return driver.get('https://********')
                .then(() => {
                        var webdriver = context.webdriver,
                        By = webdriver.By,
                        until = webdriver.until;
                        
                        var driver = new webdriver.Builder()
                            .forBrowser('chrome')
                            .build();

                        var form = driver.findElement(By.name('******'));
                        driver.findElement(By.id('username')).sendKeys('*****');
                        driver.findElement(By.id('password')).sendKeys('*****');
                        form.submit();
                        driver.wait(until.elementIsVisible(driver.findElement(By.name('**********'))), 5000);
                        
                        var iklForm = driver.findElement(By.name('*********'));
                        driver.findElement(By.name('**********')).sendKeys('11269483');
                        iklForm.submit();

                        driver.wait(until.elementIsVisible(driver.findElement(By.id('************'))));
                        driver.findElement(By.linkText('**********')).click();
                        return true;
                        })
                })
        }
}
```

I am constantly getting:

> TypeError: Cannot read property 'elementIsVisible' of undefined
    at driver.get.then (/sitespeed.io/prescript.js:15:30)

But as I can see, webdriver should be defined...

**Comment by soulgalore** [comment]
Hey @cambiph ,
yep are using the NodeJS flavour of Selenium but it could be some objects isn't clear, see if make the docs better.

```
var driver = new webdriver.Builder()
                            .forBrowser('chrome')
                            .build();
```
isn't needed, you have the driver already supplied to you in **return context.runWithDriver((driver)** so use that if you that one. We handle that in Browsertime and pass it on so we in the pre and post scripts can use the same instance. 

If you remove that, I hope it just works :)

Best
Peter

**Comment by cambiph** [comment]
Changed it to code below but still same result:

```javascript

module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
        return driver.get('https://dm-cvs-mlb1ldv.ops.vdab.be')
                .then(() => {
                        var webdriver = context.webdriver,
                        By = webdriver.By,
                        until = webdriver.until;

                        var form = webdriver.findElement(By.name('ldap_login_form'));
                        webdriver.findElement(By.id('username')).sendKeys('vdabcor1');
                        webdriver.findElement(By.id('password')).sendKeys('ldv');
                        form.submit();
                        webdriver.wait(until.elementIsVisible(webdriver.findElement(By.name('ikl_num_seq'))), 5000);

                        var iklForm = webdriver.findElement(By.name('opzoeken_via_ikl'));
                        webdriver.findElement(By.name('ikl_num_seq')).sendKeys('11269483');
                        iklForm.submit();

                        webdriver.wait(until.elementIsVisible(driver.findElement(By.id('wijzigWerksituatie'))));
                        webdriver.findElement(By.linkText('Leerweg')).click();
                        return true;
                        })
                })
        }
}
```

**Comment by soulgalore** [comment]
Hey @cambiph ,
the *driver* already supplied to your function, is the driver that do the connection the the page *return driver.get('**********')* so when you wanna run something on that page you should use that:
webdriver.findElement(By.name('*****')); ---> driver.findElement(By.name('*****'));

The driver object is the one that is connected to the page.

> var webdriver = context.webdriver,
Is the static instance, that you can use to get hold of all the types as you do in the example with By and until.

It's a little confusing since almost have the same name :)

Best
Peter

**Comment by soulgalore** [comment]
Let me spend some time tonight and make the documentation easier to understand and add more examples.

**Comment by cambiph** [comment]
Thank you for the fast and clear response.
The script is working now.
