### ISSUE TITLE
Cant pull sitespeed io for windows docker

### ISSUE THREAD

**Issue by dddeeennn** [sitespeedio/sitespeed.io#1588]
I installed Window Server 2016 on Virtual Machine and installed the docker

PS C:\Users\Administrator> Get-Package -Name docker

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
docker                         17.03.0-ee-1     DockerDefault                    DockerMsftProvider

and  tried to pull sitespeed io as follow:

PS C:\Users\Administrator> docker pull sitespeedio/sitespeed.io
There was an error:

Using default tag: latest
latest: Pulling from sitespeedio/sitespeed.io
image operating system "linux" cannot be used on this platform

How to solve this issue?

**Comment by soulgalore** [comment]
There's some info [here](https://github.com/moby/moby/issues/27668) hope that can help you!
Best
Peter

**Comment by dddeeennn** [comment]
Thanks! It explains the problem but I have decided to use the Unix based OS for hosting sitespeedio

**Comment by beenanner** [comment]
@dddeeennn sounds good we currently only support the linux based images. Closing this out.
