### ISSUE TITLE
Clear docker graphite data

### ISSUE THREAD

**Issue by radum** [sitespeedio/sitespeed.io#1589]
Hello,

Maybe this is not the best env to ask for this but couldn't find an answer anywhere.

I've setup my performance-dashboard via

```bash
curl -O https://raw.githubusercontent.com/sitespeedio/sitespeed.io/master/docker/docker-compose.yml
docker-compose up -d
```

And all works ok. But how do I clear the graphite data?

I tried to `docker-compose stop && docker-compose rm` and even deleted the entire images and restarted from scratch.

I still get the old data. How do I clear it?

**Comment by soulgalore** [comment]
Hi @radum I think you need make sure all containers are removed and then remove the volume check: https://github.com/docker/compose/issues/1227

I thought I documented that in https://github.com/sitespeedio/sitespeed.io/blob/master/development/index.md but I missed it. If you get it to work, can you reply to the issue and I can update the docs (or if you have time to send PR that would be great!).

Best
Peter

**Comment by soulgalore** [comment]
And if it don't work for you, let me know and I can check it tonight, it was while I did it and forget exact how :)

**Comment by radum** [comment]
@soulgalore Reading the dockerfile a bit better I realized that the volumes are persistent. Removing the volumes solves the problem. The -v param doesn't solve it because ... how docker works :) it is well explained in the link you gave me. I will raise a PR with the docs updates.
