### ISSUE TITLE
error when testing pdf page

### ISSUE THREAD

**Issue by Gilumaro** [sitespeedio/sitespeed.io#1591]
Whenever I test a set of urls that contains 1 pdf page, I get several errors in the log (only for that page, all others have no errorrs) and the html report is all messed up (missing css). The detailed page for that specific pdf page is missing.

The results seem to be there (info like Total Size (kb), Total Requests, First Visual Change, Speed Index, Last Visual Change, Performance score), screenshots are taken (of the correct page). Even all the data is sent to Grafana
I'm thinking it might have something to do with the fact that it's a PDF instead of a normal HTML page. Or maybe it has something to do with the URL itself? (https://mysite.acc-company-name.nl/MyCompanyOrderSetPDFDisplayCmd?pathName=%2Fwcsstore%2FMyCompanyStorefrontAssetStore%2F&hostName=https%3A%2F%2Fmysite.acc-company-name.nl&catalogId=10101&parentOrgId=7000000000000014319&orderId=&langId=-31&storeId=10151)

I'm using Sitespeed.io v5.0.0 with Docker Compose

![image](https://cloud.githubusercontent.com/assets/27728684/25433178/cbb4c9e8-2a87-11e7-819c-fff9ea0f8bbf.png)
![image](https://cloud.githubusercontent.com/assets/27728684/25433243/f83dec60-2a87-11e7-87b7-41e21c505201.png)
![image](https://cloud.githubusercontent.com/assets/27728684/25433293/2bee023e-2a88-11e7-8d0f-204c24c395f8.png)

Logfile: https://gist.github.com/Gilumaro/b063a9b98c0d9b7249fda3e625f0b426

**Comment by soulgalore** [comment]
Hey @Gilumaro 
thanks for reporting.

So is it that the crawler pick a URL that actually is a PDF instead of a HTML-page and then everything breaks?

The gist isn't working anymore, could you include the part where the generation of the HTML breaks (you should see an error in the log) so we can catch that? 

Best
Peter

**Comment by Gilumaro** [comment]
Hey Peter, I  have a .txt file with about 23 urls, the last one being a url that gives back a pdf. I've updated the logfile: https://gist.github.com/Gilumaro/b063a9b98c0d9b7249fda3e625f0b426. It shows only the part of the error. If you need more, let me know! 

Ivo

**Comment by cgoldberg** [comment]
fwiw, selenium can't interact with pdf files

**Comment by beenanner** [comment]
Probably best if we just skip analyzing URLs that are not content-type text/html?

**Comment by Gilumaro** [comment]
I get what you're saying and I've thought about just leaving it out too (to be honest I wasn't expecting it to work at all, at first). But the sitespeed part does work, you can see it in the screenshot (the last page in the table is the PDF page). Also the screenshots are correct. All data is sent correctly to grafite/grafana as well. So sitespeed does provide me what I need, unfortunately the results page looks messed up.

when I look at the log, it looks like the ' Coach'  tool gives the exception. Maybe the exception can be caught, so that an error message is provided in the results page and allowing the rest of the tool to finish?

**Comment by soulgalore** [comment]
yep I agree but it shouldn't break the generation of HTML, so thanks for reporting, we should fix that!

**Comment by Gilumaro** [comment]
I tried your solution, it works great for me:

![image](https://cloud.githubusercontent.com/assets/27728684/25580978/07c82208-2e85-11e7-880f-20ff5a7233ad.png)

thanks! :)

**Comment by beenanner** [comment]
Closing since this is released an in master.
