### ISSUE TITLE
Data retention for built-in graphite

### ISSUE THREAD

**Issue by cambiph** [sitespeedio/sitespeed.io#1592]
Hello,

I have a question regarding the Graphite instance that is included in the docker version of sitespeed.
I am having trouble feeding the data to that instance. The sitespeed docker instance runs on server x. When I add --graphite.host x to my docker command as seen below I do not get any data in Grafana:

> docker run --privileged -v ${WORKSPACE}:/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://xxxxxxx -n 1 -b chrome --speedIndex -d 2 --graphite.host xxxx -vvv

When I go to x:3000 I can see the Grafana instance by there is no data in it.
Sitespeed reports the following, which seems to be correct:

> [2017-04-27 06:32:15] INFO: [sitespeedio.plugin.graphite] Send data to Graphite xxx:2003
[2017-04-27 06:32:15] DEBUG: [sitespeedio.plugin.graphite] Sending sitespeed_io.default.summary.www-xxxxchrome.native.pagexray.contentTypes.html.transferSize.median 13119 1493274653 ........

**Comment by soulgalore** [comment]
Hey @cambiph 
when you run things inside the container, localhost is the container and not the server, so if you change to the IP instead of your machine, it should work.

Best
Peter

**Comment by cambiph** [comment]
Hey @soulgalore 
I am not using localhost, I am using the DNS-name of the machine on which it is running.
Lets say the docker image is on test.google.com, my --graphite.host is set to test.google.com.
That seems to be right, no?

**Comment by soulgalore** [comment]
Hehe you edited the issue :)

Yep that should work as long as the port is shared from Docker as in https://github.com/sitespeedio/sitespeed.io/blob/master/docker/docker-compose.yml#L27-L31

Do you use the dashboards or do you create them yourself, I mean do you see that no keys are in there?

Best
Peter

**Comment by cambiph** [comment]
Sorry, saw that I made a type.

Not sure what you mean with "as long as the port is shared from Docker as in ". I am using the docker image as provided by you guys, did not make any alterations (yet).

When I go to the Grafana instance from the docker image metioned above, I can see the domain etc in the filter but there is no data displayed. In the 'Page cost estimator' however, I see errors like this one:

> &#10;<center>&#10;<h2>&#10;<p>Graphite encountered an unexpected error while handling your request.</p>&#10;<p>Please contact your site administrator if the problem persists.</p>&#10;</h2>&#10;<br>&#10;<div>&#10;&#10;</div>&#10;&#10;<div>&#10;<pre>Traceback (most recent call last):&#10;  File &#34;/usr/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 112, in get_response&#10;    response = wrapped_callback(request, *callback_args, **callback_kwargs)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/views.py&#34;, line 122, in renderView&#10;    seriesList = evaluateTarget(requestContext, target)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&#34;, line 10, in evaluateTarget&#10;    result = evaluateTokens(requestContext, tokens)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&#34;, line 21, in evaluateTokens&#10;    return evaluateTokens(requestContext, tokens.expression)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&#34;, line 28, in evaluateTokens&#10;    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&#34;, line 21, in evaluateTokens&#10;    return evaluateTokens(requestContext, tokens.expression)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/evaluator.py&#34;, line 30, in evaluateTokens&#10;    return func(requestContext, *args)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite/render/functions.py&#34;, line 642, in scale&#10;    series.name = &#34;scale(%s,%g)&#34; % (series.name,float(factor))&#10;TypeError: float() argument must be a string or a number&#10;&#10;</pre>&#10;</div>&#10;&#10;</center>&#10;

**Comment by soulgalore** [comment]
How do you start Graphite do you use the compose file (then everything should be ok)?

Sometimes it could be hard to see the metrics if you just fired away one run, but you can see that the keys are there. Do you have any data in the dropddowns in https://dashboard.sitespeed.io/dashboard/db/page-summary?orgId=1

<img width="1432" alt="screen shot 2017-04-27 at 09 05 10" src="https://cloud.githubusercontent.com/assets/540757/25471735/b4eeed1e-2b28-11e7-83bd-23b9b7bbc4c7.png">

Or is that empty (=no data has reached Graphite).

Best
Peter

**Comment by cambiph** [comment]
I don't have anything special setup for Graphite, I use the one built in in the sitespeedio/sitespeed.io docker image.
When I open https://dashboard.sitespeed.io/dashboard/db/page-summary?orgId=1 I can see data.

**Comment by cambiph** [comment]
Ok duh, I needed to pull the other images too.
I feel dumb.

**Comment by soulgalore** [comment]
no worries happens to me often. Great that it works now!
