### ISSUE TITLE
Updating to the version 5.0

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#1593]
Everyone, good morning!

I updated the sitespeed.io to version 5.0 and that was apparently successfully updated, but when I type the -version terminal command continues showing me that I'm using the version 4.6.1.

When I updated the sitespeed.io:
![image](https://cloud.githubusercontent.com/assets/26279007/25498590/f30896dc-2b5e-11e7-8a3d-848f60f6e2f8.png)

When I search the version:
![image](https://cloud.githubusercontent.com/assets/26279007/25498611/068bbb44-2b5f-11e7-894d-edd1f91a6cf8.png)

Can you help me?

Thanks!

**Comment by soulgalore** [comment]
Hey @livyson 
I think you are seeing the npm version, not sitespeed.io version.

Test `sitespeed.io --version` to see the installed version.

Best
Peter

**Comment by livyson** [comment]
Thanks!
