### ISSUE TITLE
Include backendtime (TTFB) in Timings summary

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1595]
<img width="990" alt="screen shot 2017-04-28 at 10 01 37 am" src="https://cloud.githubusercontent.com/assets/540757/25519863/d04d0eb6-2bf9-11e7-98f5-3d38f2b5e2d9.png">

It will make it easier to find runs with the same ttfb.

**Comment by KimberlyGT** [comment]
Where is the TTFB metric?

**Comment by soulgalore** [comment]
It's called backEndTime but maybe we should make it easier to understand.

**Comment by KimberlyGT** [comment]
Ok Thanks!!! :)
