### ISSUE TITLE
Is it possible to run load test with sitespeed.io?

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#1596]
Guys,

Is it possible to run the same test simulating access for several users (load test)?

I have progressed a lot with this tool, fantastic.

Thanks!

**Comment by soulgalore** [comment]
Hi @livyson 
great :)

I would use other tools for that, maybe https://github.com/loadimpact/k6 or even something simpler, depending on what you need.

Best
Peter
