### ISSUE TITLE
What are the index.html thresholds?

### ISSUE THREAD

**Issue by rschoessler** [sitespeedio/sitespeed.io#1598]
Hi...what are the thresholds for the red-yellow-green on the index.html page?  For example, I want to get my JS in the green, what should I be aiming/budgetting for?  Is there a list in the code somewhere that I can take a look at for each of those squares?  Thank you.

**Comment by soulgalore** [comment]
Hi @rschoessler if I remember correctly they are all based on the coach advice score. It's not super easy to see in the code, but the limits is implemented in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/helpers/scoreLabel.js and the mapping (what is what) is done in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/setup/summaryBoxes.js and the original comes from the coach advice https://github.com/sitespeedio/coach/tree/master/lib
Best
Peter

**Comment by rschoessler** [comment]
Thanks...I will poke around at this and see what I can see!
