### ISSUE TITLE
Want failed on Jenkins when score is below 90%

### ISSUE THREAD

**Issue by sakonachhoeurng** [sitespeedio/sitespeed.io#1599]
I do not have any issues. I would ask question because I try to research, but seem not found.

Currently when `sitespeed.io` run on `Jenkins` there is not way to know the build failed when it is low score.
Any solution for this. Please advice and share.

Thanks,
Sakona

**Comment by soulgalore** [comment]
Hi @sakonachhoeurng 
you should be able to do it with a budget configuration: https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/ and then either output junit.xml and use that in Jenkins to pass/fail or just use sitespeed.io exit status, all exits with zero will be a budget fail.

The configuration isn't super clear in the docs, let us know if you need help and exactly when you want to fail, and we can update the docs.

Best
Peter

**Comment by sakonachhoeurng** [comment]
Hi @soulgalore 
thanks for sharing. I used to try on with `performance-budget`.
I am not so clear your fresh `and use that in Jenkins to pass/fail or just use sitespeed.io exit status`
Could you give me some example with this?
I will try to do it again with `budget`

**Comment by sakonachhoeurng** [comment]
@soulgalore, I try to and see how it works with `budget` now. I feel do not understand some field of test report of budget. I also do not know what is the different between `Failing budgets` and `Working budgets` report
![screenshot from 2017-05-05 14-35-34](https://cloud.githubusercontent.com/assets/12217854/25737111/2d852702-31a0-11e7-8cac-94537203ddf0.png)

Could you help with this, and for document seem most not understand.

Best,
Sakona

**Comment by soulgalore** [comment]
Hi again @sakonachhoeurng 

ok, let see if I can explain it better:
> and use that in Jenkins to pass/fail or just use sitespeed.io exit status

When you run sitespeed.io and everything and all budgets are passed (=are ok), sitespeed.io will exit with a 0 exit code (you can read [this](http://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/) for more info about exit codes). If a budget fails, it will exit with an error code. Jenkins will automatically pickup the error and fail the build if I remember correctly. If you output the result as JUnitXML or TAP, you need to activate a plugin for Jenkins that reads the JUnitXML or TAP file and if fails the build if you have budget that fails (checkout https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin).

A budget is when you setup a goal for the page. It could be a maximum size of page or a time metric that you want to be under. Failing budget is when the metrics for that test doesn't pass. Working (maybe we should rename that) is when the numbers are within the budget. 

Best
Peter

**Comment by sakonachhoeurng** [comment]
Thanks Peter for this explanation.

**Comment by beenanner** [comment]
Let us know if you need anything else @sakonachhoeurng. Going ahead and closing this ticket out.
