### ISSUE TITLE
sitespeed 5.0 - Webpagetest metrics not all metrics being written to influxdb

### ISSUE THREAD

**Issue by lfventura** [sitespeedio/sitespeed.io#1604]
We are running sitespeed with webpagetest and writing data to influxdb.
Some metrics are not being written on influxdb (or it is not easy to find :D). One of the main metrics we need and that is not being shown there is WebPageTest Loadtime.  When we go to the LoadTime table there is no webpagetest metrics inside, just browsertime.

Command that is being run:
`sitespeed.io https://xxx -n 5 -b "chrome" -c "cable" --influxdb.host xxx --influxdb.username "xxx" --influxdb.password "xxx" --influxdb.database "xxx" --firstParty ".xxx" --gpsi.key xxxxxx --webpagetest.host xxxxx --webpagetest.key xxxxx --webpagetest.location sa-east-1`
Output on InfluxDB:
`SELECT * FROM pageLoadTime;
----
pageLoadTime
time	browser	category	connectivity	group	max	mdev	mean	median	min	origin	p10	p90	p99	page	pageTimings	statistics	summaryType	timings

2017-05-05T23:30:11.069804408Z	"chrome"	"default"	"cable"	"xxx"	6071	351.91470557508677	5046	4640	4343	"browsertime"	4343	6071	6071	"_"	"pageLoadTime"	"timings"	"pageSummary"	

2017-05-05T23:31:25.690146606Z	"chrome"	"default"	"cable"	"xxx"	6071		5046	4640	4343	"browsertime"		6071					"summary"	"pageTimings"`

<img width="1680" alt="captura de tela 2017-05-05 as 20 44 29" src="https://cloud.githubusercontent.com/assets/17435512/25767930/4d68cf2c-31d4-11e7-895b-8459377c7c1c.png">

**Comment by soulgalore** [comment]
Hi @lfventura we only send a curated list of metrics (same as to Graphite) by default https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/webpagetest/index.js#L19-L40 but you can override it. 

Have a look at https://www.sitespeed.io/documentation/sitespeed.io/metrics/ how you can override or add your own list, hope that helps!

Best
Peter

**Comment by beenanner** [comment]
Closing feel free to reopen @lfventura if @soulgalore solution does not work for you, but it should. :-)
