### ISSUE TITLE
Search functionality for site documenation

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1611]
Would be cool if we could figure out a simple search feature for the site to help people that are quickly looking for a specific topic.

Maybe investigate some static site generator search plugins for jekyll?

https://blog.algolia.com/instant-search-blog-documentation-jekyll-plugin/

**Comment by soulgalore** [comment]
@beenanner yes that would great! I want us to focus on plugins that are hosted on the site and don't use an external search engine. Probably a little less functionality but more freedom :)

**Comment by soulgalore** [comment]
It's there now!
