### ISSUE TITLE
New plugin - top list per page summary for 3rd party audit / tracking

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1613]
Gather the following from a composite listing of all requests from every run for a particular page. 

- A list of the top 10 heaviest requests in reverse order.
- A list of the top 10 slowest requests in reverse order. 
- A list of the top 10 least performant requests in reverse order. This could be determined by Content Download (ms) / Bytes Downloaded = milliseconds per byte downloaded. 

Possible start with a tabbed HTML report for the pge summary report like we do for webpagetest and then allow sending of metrics to a TSDB for long term analysis. The TSDB will be tricky since for graphite it will eat up disk space for sites that have changing 3rd party resources. i.e. https://www.cnet.com/ We could document best practice for managing that data separately from the core site data. e.x. store for a significantly short time frame.

**Comment by soulgalore** [comment]
The lists are almost the same as we have on the "toplist page", maybe we could add those lists to the current assets plugin, if you just configure <code>--firstParty</code>? That would work out fine I think. Sending to Graphite/InfluxDB, let us work on that. 

If you agree @beenanner let us setup another issue for what is needed for plugins to work as we want (add HTML/send to TSDB etc).

**Comment by beenanner** [comment]
That sounds good to me @soulgalore. :-)

**Comment by beenanner** [comment]
https://github.com/sitespeedio/sitespeed.io/issues/1141 for reference to plugin improvements. :-)

**Comment by soulgalore** [comment]
We should re-factor assets a little, I think there are room for improvements and make it a little cleaner than today, I can start with that later this week.

**Comment by soulgalore** [comment]
@beenanner made a shot at the first two lists, check if it is the way you want.

**Comment by beenanner** [comment]
@soulgalore Nice! I'll check it out and see. Thanks!

**Comment by soulgalore** [comment]
I think the mosquitoes important ones work, let us create.a new issue if we need more.
