### ISSUE TITLE
Running multiple carbon-cache.py

### ISSUE THREAD

**Issue by jffz** [sitespeedio/sitespeed.io#1615]
I'm currently looking to implement graphite + grafana in my env but i'm actualyl facing a resources consumption issue.

As i gather informations from ~400 hosts, carbon-cache.py tends to eat all memory (16GB), i could add more memory to this host but from graphite documentation, we need to [run multiple carbon-cache.py](http://graphite.readthedocs.io/en/latest/carbon-daemons.html#carbon-cache-py). 

Is there an easy way to do it using your docker image ?

**Comment by beenanner** [comment]
@jffz I have not, but this sounds super cool! Please share with us if you learn anything interesting! :-)

**Comment by soulgalore** [comment]
Nothing here 2do.
