### ISSUE TITLE
--mobile option not being passed through to the WPT options during run

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1617]
Was testing various options and it appears that `--mobile` is no longer being proxied to the WPT instances when including it in a run. I'll take a look at this later tonight if someone else doesn't grab it before me. :-)

`docker run --privileged --shm-size=1024m --rm -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io:5.1.0  https://www.cnet.com/ --mobile --webpagetest.key xxxxxxxx --webpagetest.location Dulles:Chrome --webpagetest.runs 1 --webpagetest.connectivity 3G -n 1`

**Comment by soulgalore** [comment]
Are you sure it ever has? :) I think (but not 100%) that you even in 3.x needed to set the config for WebPageTest, but maybe we could add it.

**Comment by beenanner** [comment]
Ah that would make sense. Looking at the code it seems you are right. I think we can convert this into a feature request then. ;-)

**Comment by beenanner** [comment]
Not needed right now since we have other more pressing things to work on. :-)

**Comment by soulgalore** [comment]
I think we can close this, please re-open if you think it's something we need.
