### ISSUE TITLE
Also get WebPageTest HAR result analyzed by the Coach

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#1618]
When you run browsertime the HAR result gets analyzed by the coach plugin (and others?).

Because I mainly use WebPageTest (which also provides a HAR file) it would be awesome to also have that HAR analyzed.

This doesn't look very hard when I just listen to the `'webpagetest.har'` message in the coach. All data is analyzed and stored correctly at first sight.

What can be a problem is when you would use both browsertime and webpagetest as an input for your run. Both would generate coach results with the same namespace: `pagexray.pageSummary` (and `pagexray.summary` but maybe you want to keep this summary over the different inputs types).

Is this a concern?

Possible solution? Start the namespace with the input type? Maybe we should always namespace the metrics with the input plugin? Like: `webpagetest.coach.pageSummary` or `browsertime.coach.pageSummary`.

My branch: https://github.com/JeroenVdb/sitespeed.io/commit/cb0748ecb788810f91770596ed6ea0b3f7423171

**Comment by soulgalore** [comment]
I'm not so into changing the namespace. Since browsertime is default, what about just adding an extra for webpagetest <code>webpagetest.coach.pageSummary</code>?

**Comment by soulgalore** [comment]
I personally think WebPageTest needs the JavaScript part of the coach too, to give better advice. I want to close this but it depends on what you want @JeroenVdb

**Comment by soulgalore** [comment]
Released this in 6.3.0, but only if you run WebPageTest in standalone mode.

**Comment by soulgalore** [comment]
Ohh, we only implemented PageXray, I closed the wrong issue :|

**Comment by soulgalore** [comment]
This is done for PageXray but I think for implementing this for the coach we should also implement getting the doc tests. However I personally don't feel the need to do this in WPT since we have this in BT.
