### ISSUE TITLE
performance overhead running sitespeed from docker container?

### ISSUE THREAD

**Issue by rschoessler** [sitespeedio/sitespeed.io#1629]
@soulgalore 
So we are testing out running sitespeed from our build system using the docker container running on a Linux VM.  Initially the VM had 1 cpu and 1GB RAM.  I saw some really slow times when compared to just running sitespeed on my local machine (4cpu and 16GB RAM).  So, we upped the resources to 2 cpu and 8GB ram.  This took my times for firstPaint from 2110ms down to 240ms on my desktop (removed --speedIndex --video) ...with video I am still seeing some very wide differences from what I see on the webpage load in dev tools vs. what I see on the video...sometimes as big a difference as 10 seconds!

Are there any limits set on the container for resource usage?  Docker website says:
`By default, a container has no resource constraints and can use as much of a given resource as the host’s kernel scheduler will allow.`

What am I missing?

**Comment by soulgalore** [comment]
Hi @rschoessler 
normally I wouldn't worry too much of different timings on different machines but 10s is a looong time. You setup Docker networks and limit the connectivity on both machines (as in https://www.sitespeed.io/documentation/sitespeed.io/browsers/#change-connectivity)?

Do you watch the CPU? We run our instances on Digital Ocean (blog post coming up) on a 4gb memory, 2 CPUs, the CPU usage is 60-70%. Testing a newspaper site (with more requests) is around 90% usage. We use video, SpeedIndex and collect the trace log from Chrome. Before we used a 8gb memory/4 CPUs but that is overkill for many websites.

Best
Peter

**Comment by rschoessler** [comment]
Thanks @soulgalore. We are not using Docker networks.  We monitored cpu and memory during the tests and they would get to 90% at times for cpu.  ...we'll continue to do some testing here.
