### ISSUE TITLE
Not able to add Graphite datasource in Grafana

### ISSUE THREAD

**Issue by mananpreetsingh** [sitespeedio/sitespeed.io#1638]
I am running graphite and grafana on docker. For grafana I am using the latest image from grafana official docker image and for graphite I am using the image from sitespeedio.

so graphite is basic Auth protected "guest/guest" as per sitespeedio container. When I try to create datasource in grafana using basic auth it does not work gives Unknown error in Grafana but seems some issue with 'Access-Control-Allow-Origin'  in graphite config.

Attached the image with error and issue. Can you please advise what needs to be done in the graphite config in order to make it work ?
Added screenshot of graphite config as well.

thanks,
Manan
![screen shot 2017-06-12 at 5 01 09 pm](https://user-images.githubusercontent.com/27379172/27054993-f19c86c2-4f90-11e7-9230-9eb4103e4dd6.png)
![screen shot 2017-06-12 at 5 02 49 pm](https://user-images.githubusercontent.com/27379172/27055012-fbc98d34-4f90-11e7-9be1-e0ddd142bd32.png)

**Comment by soulgalore** [comment]
Hi @mananpreetsingh 
how did you start the containers? Usually, localhost inside a container is just inside that container = cannot reach the other containers.

We have a compose file ready with all the relations that you can use: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-5-minutes 

Hope it helps!
Best
Peter

**Comment by mananpreetsingh** [comment]
I wrote a compose file to start the containers, Both containers are on same network, Also they are linked to each other, So one containers can talk / ping to each other.

Only reason I put http://localhost:80 in grafana because it's the interface from where grafana is pulling the metrics data and its accessible, If I don't use basic auth in graphite container it is working fine with all the same settings. But with basic auth it's giving me above error.

Here is the copy of compose file that I am using:

https://github.com/mananpreetsingh/projects/blob/master/monitoring/docker-compose.yml

thanks much,
Manan

**Comment by mananpreetsingh** [comment]
Found an error log on nginx server Even though username and pass is specified:


2017/06/13 16:19:57 [error] 185#0: *4 no user/password was provided for basic authentication, client: 172.18.0.1, server: , request: "OPTIONS /metrics/find/?query=* HTTP/1.1", host: "localhost", referrer: "http://localhost:3000/datasources/edit/1"


Below attachment gives you grafana config and error (on the left side), nginx config (top right) and error (bottom right) on graphite server:


<img width="1410" alt="screen shot 2017-06-13 at 12 22 52 pm" src="https://user-images.githubusercontent.com/27379172/27093037-4b081012-5033-11e7-8b59-071439ebbd0d.png">

thanks,
Manan

**Comment by mananpreetsingh** [comment]
If I access via browser its working fine, First two are the logs if I access via browser and last two if I access via grafana.

<img width="693" alt="screen shot 2017-06-13 at 1 04 21 pm" src="https://user-images.githubusercontent.com/27379172/27094686-f7d2238c-5038-11e7-87d5-eb0fec01da15.png">

**Comment by soulgalore** [comment]
Hey @mananpreetsingh  if you use our Docker compose file the data sources are setup automatically with the bootstrap container, you can check out how it works: https://github.com/sitespeedio/grafana-bootstrap-docker

Best
Peter

**Comment by mananpreetsingh** [comment]
Ahhhh! compose file acts weirdly, If I use http://graphite:80 Its working but I use http://localhost:80 it does not in case of Auth.

If I don't use Auth it works with http://localhost:80 as well.


But thanks @soulgalore for your support.

Just wondering how regularly this docker image is maintained, I see the original image (hopsoft) is getting update every month but this is like once 6 months ?

**Comment by soulgalore** [comment]
We do changes if needed, but I would like to rollover and use Graphite 1.X in Docker if someone else could maintain it, let me know if you find a good image!

**Comment by mananpreetsingh** [comment]
Thanks, Will do that, Also I tried to create auto custom dashboard using your GitHub bootstrap container. You can see all the config here:

https://github.com/mananpreetsingh/monitoring

But auto dashboard and datasource is not get created, Did I do something wrong ?

**Comment by mananpreetsingh** [comment]
I think I am able to make it work, Now I believe the issue is what you mention about BUG in dashboard import, I did not get much information about that bug, Can you please provide me any link where I can read about it if I have to change value how should I and which ones ?

I created a templated dashboard.

**Comment by soulgalore** [comment]
Hey @mananpreetsingh what bug are you talking about? If you use our docker compose file and the instructions at https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-5-minutes it should just work. If it doesn't, there's bug, but I need more detailed info then to help. At least what doesn't work :) 

If you run own compose files/setup, then look at our files as inspiration if you runs into problems. 

Best
Peter

**Comment by mananpreetsingh** [comment]
@soulgalore  Your compose file works absolutely fine, I am trying to make my own dashboard, So I exported Json file from Grafana Dashboard and put it under dashboards folder as per the instructions mentioned.

You mentioned about that BUG at the very end of page over here: https://github.com/sitespeedio/grafana-bootstrap-docker


This is the my exported json  file from Grafana for the custom dashboard:
https://github.com/mananpreetsingh/monitoring/blob/master/dashboards/grafana-graphite-collectd-auto.json

When I put it under dashboards folder it does not import properly and end up getting errors while bringing up the containers, I think it may be because of Grafana bug that you mentioned over there.

**Comment by mananpreetsingh** [comment]
Actually I make it worked everything, sorry to bother you with extra issues. Everything is working and good! thanks for writing the code :)

**Comment by soulgalore** [comment]
Great, closing this then :)
