### ISSUE TITLE
Is it possible to integrate result data with Kibana instead of Grafana

### ISSUE THREAD

**Issue by weliame** [sitespeedio/sitespeed.io#1640]
Hi SiteSpeed team

First, I want to say that SiteSpeed is really cool, It helps me a lot. Thank you guys.
My question is, is it possible to integrate result data with Kibana instead of Grafana? If possible, how can I do that? Due to my work, I'd like to make Kibana as the UI monitor.

**Comment by soulgalore** [comment]
Hey @weliame great that you like sitespeed.io :) 

Kibana only supports ElasticSearch right? We don't have support that yet, there's been some discussion here: https://github.com/sitespeedio/sitespeed.io/issues/1062

Best
Peter

**Comment by weliame** [comment]
Thank you very much @soulgalore. I went through #1062, at least there're some useful messages for me. BTW, another small question, can I customize metrics? I want calculate `p95` besides of `p90`.

**Comment by soulgalore** [comment]
ok, we use fast-stats to get the stats, but I don't remember if also configured 95/99. But how many runs do you plan todo per URL? Will p95 give you any better values than p90? For synthetic testing I found it more valuable to be able to switch between median and min (to get more stable values etc). 
Best
Peter

**Comment by weliame** [comment]
Maybe 10 runs per URL. We already have some other monitors with p95 metric, and I'd like to keep in line with those monitors. That's my reason :). Yes, median and min metrics are important, too.

**Comment by tobli** [comment]
The percentile calculation is customisable, we just haven't hooked it up to the cli yet. Could you please open a new issue for it, so we don't forget.

Thanks,
/Tobias

**Comment by tobli** [comment]
The percentile calculation is customisable, we just haven't hooked it up to the cli yet. Could you please open a new issue for it, so we don't forget.

Thanks,
/Tobias

**Comment by ftore** [comment]
Hi @weliame, I created [this pull request](https://github.com/sitespeedio/sitespeed.io/pull/1644) for Elasticsearch plugin. I am willing to maintain it as a standalone plugin. I need help with creating a dashboard in Kibana. If you can help me, please, let me know..

**Comment by weliame** [comment]
Thank you @tobli, I created a new issue #1645.

**Comment by weliame** [comment]
Hi @ftore, nice to see such a plugin. I'm not sure what I can help. But if you have any question, leave message to me, I will try for that. We may keep in touch offline.

**Comment by weliame** [comment]
Thank you guys, I think the ticker could be closed.
