### ISSUE TITLE
Question: plotting speed metrics by web site build number

### ISSUE THREAD

**Issue by leeMoonpig** [sitespeedio/sitespeed.io#1641]
In Grafana, we'd like to see our changing metrics plotted by build number rather than by time.

Is there anyway we can call sitespeed.io and pass in our build number so that it ends up in Grafana?

**Comment by tobli** [comment]
Hi!
Could you embed the build number in the page, e.g. in a js variable or hidden node? If so you can add a custom browsertime script to read that. That would then be included in the 'browsertime.pageSummary' message that the graphite picks up. You should then be able to add that information to graphite using the --metrics.filter option. By default most data from browsertime is filtered out and not sent to Graphite.

**Comment by soulgalore** [comment]
I really like @tobli approach, it's nice to get the value directly from the HTML of the pages, that will make easy in the future. Let us know @leeMoonpig if you need more help.

**Comment by soulgalore** [comment]
Closing, @tobli idea should solve it.
