### ISSUE TITLE
Question: params to WPT

### ISSUE THREAD

**Issue by kchoi01** [sitespeedio/sitespeed.io#1642]
Hi, I am wondering how to pass more options to WPT than the ones specified in the help screen? Issue #1617 mentions that the mobile flag is not passed. How do I make WPT run with mobile emulation?

Thanks.

**Comment by soulgalore** [comment]
Hey @kchoi01 everything that you pre-pend with *webpagetest.* will be passed to the [Webpagetest API](https://github.com/marcelduran/webpagetest-api#test-works-for-test-command-only) as documented in https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#configuration (maybe we can make that cleaner for people to understand).
Best
Peter

**Comment by kchoi01** [comment]
Hi Peter, thanks for the clarification. For the WPT "runs" param, is it per sitespeed.io iteration? So for example, if sitespeed.io iteration is 3 and WPT runs is 3, is it going to run WPT 9 times?

**Comment by soulgalore** [comment]
No. It is totally separeted. 3 wpt runs will be 3 runs, you can think of them as two different tools that you need to configure one by one.
Best
Peter

**Comment by kchoi01** [comment]
Great thanks!
