### ISSUE TITLE
The InfluxDB annotation shows 3,3 runs instead of 3.

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1646]
<img width="301" alt="screen shot 2017-06-20 at 4 39 23 pm" src="https://user-images.githubusercontent.com/540757/27339115-2f26dcee-55d7-11e7-9057-cd07a7a023ba.png">

**Comment by soulgalore** [comment]
Ok, this is wrong in the configuration on dashboard.sitespeed.io. @beenanner do you have time later this week and login to the server and change from 3,3 to 3? I don't have access the coming days. It is both for ryanair and the nytimes tests.

**Comment by beenanner** [comment]
Sure I'll take a look tonight.

**Comment by beenanner** [comment]
Fixed. Closing.

**Comment by soulgalore** [comment]
thanks @beenanner for fixing my mistake :)
