### ISSUE TITLE
Feature: Capture page weight info till User defined mark name

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#1656]
Wondering if sitespeed.io can Capture page weight info till User defined mark name rather than page fully loaded. 
Page weights matters much mainly due to different network speed nowadays, the engineering team should keep a close eye on the page weights , and pay more attention to the page size until most critical stage (Engineer need to define this mark on his pages), the page size after this mark, we can consider as a second priority for the end users. Let me know what your thoughts on this.
Thanks!

**Comment by soulgalore** [comment]
I don't see how this would work? Is it the fully loaded or? I think this can be a nice plugin for someone outside the team to implement :) Closing for now, but please let us know if there's a plugin out there.
