### ISSUE TITLE
Testing url with more parameters in query string

### ISSUE THREAD

**Issue by pixlab** [sitespeedio/sitespeed.io#1657]
Hi,

I'm trying to test a page that it needs some parameters in query string like this:
https://www.mysite.com/hompage?parameter1=value1&parameter2=value2&parameter3=value3

I write this instruction:
docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.mysite.com/hompage?parameter1=value1&parameter2=value2&parameter3=value3

but sitespeed goes to test this url:
https://www.mysite.com/hompage?parameter1=value1

It leaves only one parameter and it produces a 404 error page.

thanks for help
Roberto

**Comment by tobli** [comment]
Hi!
The & has a special meaning to your unix shell, so you need to put quotes around the url for them to be passed to sitespeed.io

/Tobias

**Comment by pixlab** [comment]
Hello Tobias,

yes it works....thanks for you suggestion :)

Roberto

**Comment by tobli** [comment]
My pleasure!
