### ISSUE TITLE
Run sitespeed.io for user actions

### ISSUE THREAD

**Issue by vijaycs** [sitespeedio/sitespeed.io#1661]
Would it be possible to measure the performance of web page for some user actions like clicks on login button or submit button using sitespeed.io. 

Note: I tried with --PreScript which runs the selenium script before reaches the target URL. But actually i need to measure the perform of the page when click on login button.

**Comment by soulgalore** [comment]
Hi @vijaycs no it is not. We got that query sometimes and [I haven't seen a tool that can do that](https://github.com/sitespeedio/sitespeed.io/issues/1224#issuecomment-250416797), where it actually works and not too much noise. If you have an example for a tool where it works, would be cool! Measuring more than one page is hard, interactions even harder I think.

Best
Peter

**Comment by vijaycs** [comment]
Thank you Peter.
