### ISSUE TITLE
Url list file vs standalone url testing feature parity(alias and preScript)

### ISSUE THREAD

**Issue by UltraNemesis** [sitespeedio/sitespeed.io#1663]
I have a scenario where I need to test a bunch of url's some of which require a preScript and others don't. Based on the documentation, I don't see any way to pass preScript inside URL list file for selective URLs. On the other hand if I run the test for individual URLs, I don't seem to have a way to pass an alias name for the URL which is available with the URL list.

Shouldn't there be feature parity which ever way we run the test?

**Comment by soulgalore** [comment]
Hi @UltraNemesis I separate them by making different runs, invoking sitespeed for each use case. One without prescript(s) and one with, that is the only way to do it at the moment. I usually keep a default.json config file with my standard settings, that I always load, then the cli-options override the json config file, so in the second runs with preScripts I only override that one.

> Shouldn't there be feature parity which ever way we run the test?

Yep I think you are right, setting alias is only supported if you supply a list of URLs from file. PRs are open to adding support for it :)


Best
Peter

**Comment by soulgalore** [comment]
PRs are open for this, but nothing we will active work on.
