### ISSUE TITLE
[Feature]: Leverage Performance Paint Timing API to get visual metrics from Chrome

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#1667]
may consider to leverage Performance Paint Timing API to get the 'first-paint' and 'first-contentful-paint' metrics too from Chrome Browser:

performance.getEntriesByType('paint');

API intro URL:
https://github.com/WICG/paint-timing

**Comment by soulgalore** [comment]
Hi @joychester ,
it is there already when you use Chrome 60, added it a couple of releases ago :) However ALWAYS verify the metric that it works, I've had a bad experience with it see https://twitter.com/soulislove/status/878191034789838849

Best
Peter

**Comment by joychester** [comment]
@soulgalore , peter, i missed your twitter ,lol thanks for the info 👍
