### ISSUE TITLE
EACCES error using node 8 (npm 5)

### ISSUE THREAD

**Issue by DanielRuf** [sitespeedio/sitespeed.io#1668]
I get the following error during install which stops the install process.

`Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/sitespeed.io/node_modules/webcoach/node_modules/soprano-saxophone/vendor'`

**Comment by soulgalore** [comment]
Hey @DanielRuf 
I think this could be a problem with the [Download package](https://github.com/tobli/soprano-saxophone/blob/master/install.js#L3) or with npm5? I know @tobli is using 5, can you try when you got the time? I personally have had such a bad experience with npm 5 so far so I rolled back a couple of weeks ago, but I can try again when I get back to a good internet connection.

Best
Peter

**Comment by DanielRuf** [comment]
Do you mean that I shall test if a newer version of the module fixes this?

https://github.com/tobli/soprano-saxophone/blob/master/package.json
https://github.com/kevva/download/releases

What is the best approch or way to test it locally?

**Comment by DanielRuf** [comment]
Some additional information: this only happens on a Debian 8.4 server. On Windows there was no problem with npm 5. I'm not yet sure if it is a problem with an installed system package, npm or the package. I have to recheck if the latest npm version was the culprit.

**Comment by beenanner** [comment]
@DanielRuf can you attach the node version and npm version to this ticket with commands you executed? I'll try to reproduce.

**Comment by tobli** [comment]
For permission issues with npm (specifically EACCES) I'd suggest looking at the npm docs on the subject: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by DanielRuf** [comment]
It just happens with node 8, in node 6 this error is not thrown.

> @DanielRuf can you attach the node version and npm version to this ticket with commands you executed? I'll try to reproduce.

The latest node 8 and npm 5.2 versions were used. I've switched to node 6 shortly after this.

**Comment by soulgalore** [comment]
We build everything now with node 8 and hopefully it "just works". Please re-open if you still got the problem.
