### ISSUE TITLE
Content metrics from pagexray does not appear when tests run on mobile

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#1669]
Hello @soulgalore 
I am running sitespeed.io on mobile device (locally connected). I get all metrics except the content size, javascript size etc.  I believe this metric is produced by pagexray.  When I looked into pagexray, nothing stood out to me which would cause issue. But can you think of any reason why pagexray would not be able to grab content asset data in mobile browser?
Thanks

**Comment by soulgalore** [comment]
Hey @abhagupta ok hmm, I don't have my Android phone with me so I can reproduce, but it works like this: We use Chome trace log to produce the HAR using https://github.com/sitespeedio/chrome-har then PageXray parse the HAR and get the size etc. 

Is it both content and transfer size that doesn't work? Can you check if you see the size in the HAR file? Else if you could add --browsertime.chrome.collectNetLog to your run so and then attach the trace to the issue so we can have a look.

Thanks
Peter

**Comment by abhagupta** [comment]
Hi @soulgalore  sorry for delay on this.  Thanks for the explanation. I do not see either content or transfer size. The only metric I see is `"name":"rapido.cloud.https_www_walmart_com.root.asset_data" `  . In desktop environment, I can see data  as follows
```
rapido.r_discovery_collections.http_dev_walmart_com_3000.collection_47206334.asset_data.base_domain
rapido.r_discovery_collections.http_dev_walmart_com_3000.collection_47206334.asset_data.base_domain
rapido.r_discovery_collections.http_dev_walmart_com_3000.collection_47206334.asset_data.total_domains
... and so on 
```

**Comment by soulgalore** [comment]
@abhagupta ok. Can you send me one HAR file from the run (located in the data folder for that page): peter [at]soulgalore[.]com - then I can see where the problem is. 
Best 
Peter

**Comment by soulgalore** [comment]
Thanks @abhagupta the size is in the HAR file so the Chrome trace is working (you can check by dropping it into https://micmro.github.io/PerfCascade/ (check the response). 

Then it is something how the metrics are picked up and sent to your data storage?

**Comment by abhagupta** [comment]
I am investigating that as well. I woudn't really think so because I am not filtering any metrics between desktop runs vs mobile runs, but I am looking into that as well. Will keep you updated

**Comment by soulgalore** [comment]
I'll have a look also when I'm back have my android phone.

**Comment by abhagupta** [comment]
You were right. This turned out to be an issue on how I am saving data. Everything looks good in mobile tests now.
