### ISSUE TITLE
Visual complete and blinking caret/cursor

### ISSUE THREAD

**Issue by Gilumaro** [sitespeedio/sitespeed.io#1670]
I've noticed in my the results of some of the pages I test, that sometimes they had very long last visual change times. When I looked into the reason for this, it seems this is caused by a blinking caret/cursor.

it happens also on google.com, where the search input field is focussed on page load (same happens on the site I test).

short fully loaded time (median 906 ms), but last visual change of 3083ms!
![image](https://user-images.githubusercontent.com/27728684/28207098-b4695f58-6888-11e7-9aea-ec8161213750.png)

when looking at browser time metrics, I can see this:

![image](https://user-images.githubusercontent.com/27728684/28207157-e3b35c32-6888-11e7-87ee-a131dd59bf54.png)

visual progress goes to 100%, back to 99%, back to 100%, back to 99%, back to 100%. 
This is caused by the blinking caret on the page. 

the measurement is wrong because of this. Is it possible to have sitespeed report on the first time the visual progress is at 100%? 
webpagetest does not seems to have this issue, so I assume there the tool uses the first time 100% is hit.

I'm open to other suggestions as well. So far I have investigated adding css/js to hide the caret, but I have come up empty.

**Comment by soulgalore** [comment]
Hi @Gilumaro 
ok, I haven't seen it myself yet. Do you run our Docker container? The way to fix it would be to disable the cursor/pointer, I think we could do it in XVFB? Do you have time to check if you can find a solution? You should be able to test it out in https://github.com/sitespeedio/browsertime - I can help out pointing you in the right direction if you need!

Best
Peter

**Comment by soulgalore** [comment]
Ah sorry you mean the cursor and not the pointer, I see. I guess the best way is to just disable the cursor or set it to solid. Not sure though the best solution fo it.

**Comment by Gilumaro** [comment]
Hey Peter!

yes I use the docker container, sitespeed 5.4.1.

Definitely have time to see if I can find a solution. I think the best way would be to hide the caret with css. (by setting the color of the input fields to transparent)

I see that there is a userChrome.css that hides the statusbar in FF to get valid speedIndex. Something similar could be done for this?

not sure how I can test this in my environment though, so definitely would need some pointers ;-)

**Comment by Gilumaro** [comment]
Best CSS solution I've found:
https://stackoverflow.com/questions/3671141/hide-textfield-blinking-cursor#answer-23472096
https://jsfiddle.net/jx6q1peo/

but how do I add this css to my docker image, and how will the tool pick this up?

**Comment by soulgalore** [comment]
Hi @Gilumaro cool!

I need to check how we can add it. If you clone git@github.com:sitespeedio/browsertime.git and then you can build the docker container and run it locally (and get the video and verify that it works):

```
docker build -t sitespeedio/browsertime .
docker run --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime -n 1 --video --speedIndex https://www.sitespeed.io/
```

Best
Peter

**Comment by soulgalore** [comment]
I think one way to do it is to add it in our Chrome/Firefox plugin: https://github.com/sitespeedio/browsertime-extension

It is used when we run the browser, right now only for Chrome but it is prepared for Firefox when the next Selenium version gets out. It's only triggered for some use cases at the moment though.

**Comment by Gilumaro** [comment]
Hi Peter, 

I was on holiday the last week, so didn't have time to look into this until today :-)
I have no experience with nodejs but I managed to add some code that appends style tags to the head of the page I am testing and it works (more or less). 
`driver.executeScript("var css = 'input[type=\"tel\"] { color: transparent; text-shadow: 0 0 0 #000; }'," +`
`"head = document.head || document.getElementsByTagName('head')[0]," +`
`"style = document.createElement('style'); " +`
`"style.type = 'text/css'; " +`
`"style.appendChild(document.createTextNode(css));" +`
`"head.appendChild(style);");`

The issue is where to place the script and the impact this has on the timing when the script is executed and the css is added. The script has to run as soon as possible so that the cursor is hidden before the page is actually visually complete. 
The cursor is now hidden but only halfway during page load (which is fine for my use case, other elements are still changing while the cursor is hidden). Ideally it would be hidden at the start of rendering. I have no idea what the best place would be to run this script.

other thoughts:
- I use docker-compose. how can I use this local docker container? Just point to this local container in the yml file? (I will try this out after writing this comment ;-))
- the script will have some impact on fully loaded time I guess, albeit very little? any idea on how to make this impact as small as possible or eliminate it all together?
- If this solution/feature is added to sitespeed.io would it possible to add this as an cli argument to the tool? my application has `input type='tel'`, other applications might use `input type='text'` or something else. So if the element could  A cli argument could look like `--hideCursor 'input type='text'` 
- maybe the above feature is too specific and a broader feature could be to run a script during/before pageload (current options --script --preScript --postScript are of no use because they run either too early or too late)
- I am now using a script to append the css. I don't know how to add just custom css to every page in chrome, although I found this https://developer.chrome.com/extensions/tabs#method-insertCSS. The restricition here is that !important is ignored I believe and all other css will trump this injected css, making this solution unreliable.

**Comment by Gilumaro** [comment]
Hey Peter!

Another way this issue pops up, is with flashing banners on a webpage. I was wondering how the tool handles these, so I tested it out on a dutch news website where I know there will be flashing banners: www.nu.nl. 

basically the same happens here. visual progress goes from 99 to 100 to 99 to 100 to 99 to 100. 
![image](https://user-images.githubusercontent.com/27728684/28955771-07097516-78e9-11e7-8b9e-cc3d25346425.png)

when I look at the video the first time the visual progress is at 100%, is actually the time when the page is visually complete, after that it's just flashing banners. 

You can find the results here:

https://www.dropbox.com/s/ixu53or9jjm0sya/www.nu.nl.tar.gz?dl=0

so instead of doing a lot of difficult stuff with css or javascript, why not just report on the first time the visual progress is at 100%? Would that be possible? Are there scenarios where this wouldn't be useful?

Regards,

Ivo

**Comment by soulgalore** [comment]
Hi Ivo,
I think the long term solution would be to add the functionality to blank out parts of the video as Sergey Chernyshev talks about here: https://www.youtube.com/watch?v=t6l9U5bC8jA since it will be different for different sites. There's sites out there that go up and down in progress and I think we need to be able to define which elements that not will be included. 

Best
Peter

**Comment by Gilumaro** [comment]
Hey Peter,

really interesting stuff! Having a metric like time to primary content or something like that would be really useful to business. 
for the issue of blinking/flashing banners/cursors/etc being able to blank out certain parts would certainly be the most elegant solution as it would (I hope) tell when that certain element shows on the page, and whatever fancy blinking and flashing that occurs is just ignored. Cool!

Is there anything I can do short term to hide blinking cursors on the site I test? I'm pretty much stuck right now and the best thing I have is a javascript that runs halfway through pageload that hides the cursor. This solution is good enough but I only have this working in a local browsertime container like you mentioned before, and I have no idea how to incorporate this into the setup I have with docker-compose with sitespeed/grafana/graphite/webserver. 

Thanks!

Ivo

**Comment by soulgalore** [comment]
ping @tobli do you have a best way how we can help @Gilumaro with the blinking cursor problem?

**Comment by soulgalore** [comment]
Nothing we can do here on our side right? Else please re-open the issue.

**Comment by romanresh** [comment]
Hi, we use the following workaround to prevent the cursor issues:

```json
{
    "browsertime": {
        "iterations": 5,
        "browser": "chrome",
	"injectJs": "addEventListener('load',()=>{var s = document.createElement('style');s.type='text/css';s.appendChild(document.createTextNode('input{caret-color:transparent!important; }'));document.head.appendChild(s);})"
    }
}
```
