### ISSUE TITLE
HTTP 500 returned on a POST to /api/datasources/proxy/1/render

### ISSUE THREAD

**Issue by stephendonner** [sitespeedio/sitespeed.io#1683]
Steps to Reproduce:

1. Load https://dashboard.sitespeed.io/dashboard/db/webpagetest-page-summary?orgId=1, as an example
2. Look in the Network Console

Actual Results:

See http://www.webpagetest.org/result/170728_F5_MEC/1/details/#step1_request29 - there's an HTTP 500 returned, on a POST to /api/datasources/proxy/1/render

**Comment by soulgalore** [comment]
So I guess it is one query we do that doesn't get a result back from Graphite, I'll put this on low prio for now.

**Comment by stephendonner** [comment]
Yeah, looks like it.

**Comment by soulgalore** [comment]
Seems to be fixed now :)
