### ISSUE TITLE
Prevent Sitespeed.io from refreshing page, if endpoint already accessed via pre-script

### ISSUE THREAD

**Issue by johnathan-wells** [sitespeedio/sitespeed.io#1686]
Hi guys.

We have an operation we'd like to benchmark: generating a PDF from a page. This means we need to make a pre-script that clicks a button on the page, and start benchmarking from that point. Unfortunately, when Browsertime finishes its prescripts it loads the URL fresh, even if it's on that page already.

I understand that Browsertime is made for testing endpoints and static pages, but it seems like such a shame that, from my point of view, all that would be required is to make Browsertime skip loading the page and begin benchmarking.

That is, of course, from my point of view!

**Comment by UltraNemesis** [comment]
I too have a very similar requirement and facing problems accomplishing it. I have a page where clicking a button opens a overlay in which a form is loaded. I need to capture the time taken from clicking of button to loading complete. 

I can do it using a very simple Webpagetest script, but could not find any way to do it with just sitespeed. Of course I can write selenium script preScript to click the button, but after that it has to launch whatever URL I pass.

**Comment by soulgalore** [comment]
thanks @UltraNemesis ! I'm not 100% sure how we should implement it, we had some ideas in the past but haven't find the time yet to do it. I'll create an issue later with the main task and ping this issue.

**Comment by johnathan-wells** [comment]
Thanks @soulgalore, that's really great news.

**Comment by soulgalore** [comment]
I created a discussion issue for this and closing all other issues: #1827 Let us do all the talking there :)
