### ISSUE TITLE
Sitespeed.io on Google cloud

### ISSUE THREAD

**Issue by taurusismysign** [sitespeedio/sitespeed.io#1688]
Hi Peter,

I deployed sitespeed.io docker in Google cloud (Docker image + Kube). I want to integrate invoking the docker container running on a cluster via a say .. rails application.

Do you have any example/ documentation on how to go about it? 

Thanks

**Comment by beenanner** [comment]
@taurusismysign that sounds really cool, but I don't think we have any setups that advance!  ;-) 

When you say 
> I deployed sitespeed.io docker in Google cloud (Docker image + Kube).

Do you mean GKE or your own Kubernetes cluster running on compute instances? I know Kubernetes has the concept of jobs, so maybe that is a way to integrate sitespeed runs with it. If you wan to fire off a sitespeed run from another language I think interfacing with the Kubernetes API would be your best bet.

**Comment by beenanner** [comment]
@taurusismysign did you get this working with k8 would be pretty cool if so and would a great blog post or addition to the documentation. If not I hope to spend some time in the coming months to investigate things like this. :-)

**Comment by Algram** [comment]
The basic setup with Grafana, Graphite and the Sitespeed Runners is working in our Kubernetes Cluster here via CronJobs. We ran into issues with network throttling though: https://github.com/sitespeedio/sitespeed.io/issues/1819
