### ISSUE TITLE
S3 upload with SigV4 broken

### ISSUE THREAD

**Issue by fbusse** [sitespeedio/sitespeed.io#1689]
Uploading to S3 in newer regions[1] that need v4 authentication is not possible.
This happens when with sitespeed 5.4.4:

ERROR: Could not upload to S3 Error: Non-file stream objects are not supported with SigV4 in AWS.S3
    at Request.computeSha256 (/usr/src/app/node_modules/aws-sdk/lib/services/s3.js:200:18)

[1] http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by beenanner** [comment]
@fbusse thanks for reporting will take a look soon.

**Comment by soulgalore** [comment]
so if I wanna try this, do we know which region? maybe we just need to upgrade the s3 plugin?

**Comment by fbusse** [comment]
@soulgalore Sorry if you were waiting for a response from me: My test was with eu-central-1.
All new regions use SigV4.

**Comment by soulgalore** [comment]
@beenanner started to look at this but not sure why it's not working (removed my branch since it uses v4 per default). let me know if you have any idea.

**Comment by soulgalore** [comment]
Seems to be that the s3 module we use hasn't been updated with the latest aws-sdk https://github.com/andrewrk/node-s3-client/issues/175

**Comment by soulgalore** [comment]
This was released a couple of releases ago (by using the aws code directly).
