### ISSUE TITLE
Feature: Import legacy Webpagetest results into Sitespeed.io and/or Graphite for migration

### ISSUE THREAD

**Issue by rcherny** [sitespeedio/sitespeed.io#1694]
Similar to what's noted in #1452 and #1384 — I'd like to be able to migrate to Sitespeed.io from using WebpageTest directly — particularly for the charting in the Graphite UI as the notion is to use this over time. But, the catch is I don't want to lose legacy test results.

[This is follow up to the discussion on twitter](https://twitter.com/SiteSpeedio/status/901871760890634242).

I could be mistaken, but this seems like a job for a plugin, that given a command line or API flag Sitespeed could be pointed to a file, skip initial test execution, ingest it, analyze and format the messages data necessary to push that data into Graphite the way typical results are.

I'd settle for one at a time, but being able to point to a folder or something would be ideal.

So, given a CSV from Webpagetest.org results, or better yet a HAR and/or JSON file fetched by the Webpagetest-api — we'd need to trigger the import.

> Disclaimer: I haven't hacked anything on Sitespeed.io, and am barely familiar with the code base — but I am willing to learn and am curious where one would even start. I also _can't necessarily commit_ to being able to deliver a PR (personal time constraints unless I can pull off getting approval do so during the work day -- this is for a work project) any time soon, but I'd love to try to start with a fork and get the ball rolling here.

So, for me at least, the logical entry points are:

1. _Where in the pipeline of data flow_ is the WPT data currently "ingested" by Sitespeed?
2. And, _where in the codebase_ is that data translated into whatever format Sitespeed and/or Graphana uses?
3. Finally, _where in the codebase_ does Sitespeed then trigger the import?

On (1) I don't even know if Sitespeed is able to be _run_ in a different "mode" per se, skipping test execution. 

Assuming (1) can be done and a suitable import mechanism be created (seems trivial, a simple read from files to start) I'd almost assume (2) and possible (3) might "just work" even.

I'll start to dig myself as I have time (today is even TBD), but any pointers would be a leap forwards for me. Several personal challenges including just getting Sitespeed and Graphite running locally outside of Docker, which is all I've done to date — but that's clearly a separate discussion so that's just an FYI.

**Comment by rcherny** [comment]
An alternative might be to simply be able to extend Sitespeed's use of the Webpagetest-API wrapper, which itself is able to fetch results using the ID of a test result -- currently this doesn't seem to work.

The more I think about it, this may even be a better starting point.

**Comment by soulgalore** [comment]
Hey @rcherny thanks for adding the issue. I know @tobli started before on generating results from a HAR but I think he stopped with other things with higher prio. @tobli do you have any input?

Best
Peter

**Comment by soulgalore** [comment]
I think this is nothing we will actively work on, but we are open for PRs.
