### ISSUE TITLE
Should the NPM `sitespeed` package carry a deprecation warning?

### ISSUE THREAD

**Issue by kohlmannj** [sitespeedio/sitespeed.io#1696]
A moment ago, I realized I was having issues with Sitespeed.io because I had (globally and locally) installed the `sitespeed` package from the NPM registry, rather than `sitespeed.io`.

Specifically, I encountered this issue thread (https://github.com/sitespeedio/sitespeed.io/issues/1665#issuecomment-315326329), ran `yarn info sitespeed`, and thought, "wait, I don't see any v5.4.x releases listed!"

I suppose I'm really wondering why there's both a `sitespeed` and `sitespeed.io` package on the NPM registry, but if that has to remain the case, I'd appreciate **some kind of message when installing `sitespeed`**. That way, new users will at least have _some_ hint that they may have wanted to install `sitespeed.io` instead.

**Comment by soulgalore** [comment]
Hey @kohlmannj thanks for filing the issue. We (=the team) don't own *sitespeed* on npm, there's someone else that published that :(
Best
Peter

**Comment by soulgalore** [comment]
I think it is ok as long as we link to the right one.
