### ISSUE TITLE
Not able use sitespeed to run just WPT test 

### ISSUE THREAD

**Issue by UltraNemesis** [sitespeedio/sitespeed.io#1700]
It looks like it is not possible to use sitespeed to just run a test on Webpagetest. The URL field is mandatory making it impossible to pass a WebPageTest script and record result of the same. 

I have situations where I need to be able to run a test on just WPT private instance,

**Comment by soulgalore** [comment]
I've made a fix now so it at least work for me, can you try from master?

`bin/sitespeed.js --plugins.disable browsertime --webpagetest.key SECRET https://www.sitespeed.io
`

**Comment by UltraNemesis** [comment]
Thanks, This works for me now.

One issue that I noticed is that if I pass the --plugins.disable in command line, the order of args matters for some reason. Initially I tried putting it at the other of other command line args just before the URL, but it didn't work for me and I was getting the noURL/file error. Then when I tried moving it to the first command line arg, it worked then.

**Comment by soulgalore** [comment]
@UltraNemesis yep, that is kind of an old bug, how we handle "arrays", but we haven't fixed it, we have an issue somewhere (I'm travelling at the moment). Lets see if we can fix it to 6.0, it is annoying.

**Comment by soulgalore** [comment]
I've released this yesterday. Let us fix the array problem for 6.0.
