### ISSUE TITLE
Sitespeed.io + docker generate diff directory

### ISSUE THREAD

**Issue by p3dro114** [sitespeedio/sitespeed.io#1702]
Hi,

I solved a problem with sitespeed.io + docker.

When you launch "docker run ...", it create diff file on this path /var/lib/docker/aufs/diff/

Some files can be delete, but not all !

rm -rf /var/lib/docker/aufs/diff/*-removing

Regards,

**Comment by soulgalore** [comment]
Hi @p3dro114 
I think this is a Docker issue and not sitespeed.io related, so closing this. Have a look in the [Docker forums](https://forums.docker.com/) if you can find help. If you still find it sitespeed.io related, feel free to re-open the issue.

Best
Peter
