### ISSUE TITLE
chrome fail to start when args provided

### ISSUE THREAD

**Issue by tglanz** [sitespeedio/sitespeed.io#1707]
Hi, thank you for the great tool!

I am trying to apply the following options to chrome, running sitespeed through docker container
```
--disk-cache-size=1
--media-cache=1
```

using the configuration file, the browsertime section looks something like
```
"browsertime": {
        "iterations": 1,
        "browser": "chrome",
        "chrome": {
            "args": [
                "--disk-cache-size=1",
                "--media-cache=1"
            ]
        }
    }
```
when applying those configurations, the browser fail to start with the error
```Browser failed to start, trying one more time. TimeoutError: Failed to start browser in 60 seconds.```

I believe the issue is probably how i format configurations, tried other formats as well for those args and cannot get this to work, any advice?

Thanks!

**Comment by soulgalore** [comment]
Hi @tglanz thanks for the kind words. I think we need to add more documentation for this. One thing is that you don't need the "--" for the args (but that isn't obvious). I'll try tonight with a JSON to see how it works. Paremeters using the cli like *--browsertime.chrome.args "disk-cache-size=1"* works for me.

Best
Peter

**Comment by talgsoluto** [comment]
Hi @soulgalore as i can tell it still seems to crash the browser after removing the "--"
Thanks

**Comment by tglanz** [comment]
Hi @soulgalore as i can tell it still seems to crash the browser after removing the "--"
Thanks

**Comment by soulgalore** [comment]
Hi @tglanz what OS and Chrome version are you using? I tested with Chrome 61 on my Mac and this works for me (tried to make a really simple test case):
```
{
  "browsertime": {
    "iterations": 2,
    "browser": "chrome",
    "chrome": {
            "args": [
                "--disk-cache-size=1",
                "--media-cache=1"
            ]
        }
  }
}
```
And then run it:
`sitespeed.io --config config.json https://www.sitespeed.io`

**Comment by tglanz** [comment]
Running on osx, using latest docker image. With standalone chrome, v60 i believe.
I will check again tommorow, reducing all other configurations and will try to add additional logs

**Comment by soulgalore** [comment]
Aha ok! Sorry I missed that and we need to add it to the documentation. Checkout the docker file:
https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L4

In our Dockerfile we automatically set the no-sandbox argument to Chrome, when you add your chrome arguments on the same path, that one will be overridden. If you add no-sandbox to your JSON, I'm pretty sure it will work.

Best
Peter

**Comment by soulgalore** [comment]
Let me know if that was the case (when you have time to test)!

**Comment by tglanz** [comment]
@soulgalore it works! indeed adding no-sandbox fixed the issue.
Thank you!

**Comment by soulgalore** [comment]
Great, I'll update the docs for that.

**Comment by mani619cash** [comment]
I tried the above mentioned config but it didnt work.

```
sitespeed.io --config config.json https://www.sitespeed.io
[2018-09-01 15:40:21] INFO: Versions OS: linux 4.9.0-6-amd64 nodejs: v10.9.0 sitespeed.io: 7.3.6 browsertime: 3.3.1 coach: 2.0.6
[2018-09-01 15:40:21] INFO: Starting chrome for analysing https://www.sitespeed.io 2 time(s)
[2018-09-01 15:40:21] INFO: Testing url https://www.sitespeed.io iteration 1
[2018-09-01 15:41:21] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
```
`which google-chrome`
`/usr/bin/google-chrome`

**Comment by soulgalore** [comment]
@mani619cash did you try adding `--chrome.args no-sandbox`  ?

Best
Peter
