### ISSUE TITLE
How to use the number of third-party requests in the performance budget file

### ISSUE THREAD

**Issue by Algram** [sitespeedio/sitespeed.io#1709]
Hello,
I want to configure a budget for the number of third-party requests. I generated the `metrics.txt` file and searched for it there, but it does not seem to be included. What would the correct string be that I need to add to the budget file so that it works for the third-party requests?

Thank you!

**Comment by soulgalore** [comment]
Hi @Algram yep that isn't perfectly clear. I would start with listing all the metrics to a file, checkout https://www.sitespeed.io/documentation/sitespeed.io/metrics/#list-metrics and then take it from there, I can help out this weekend. I'll update the issue when I have had time to check.

Best
Peter

**Comment by Algram** [comment]
@soulgalore Thank you. That's what I did. In the documentation you mention 
> You can also list all possible metrics that you can send.

The command you provide below that statement does in fact **not** list **all** possible metrics. To list all the possible ones you also need to specify the `--firstParty` parameter.

After doing that, I am getting more metrics in the `metrics.txt`, but it seems the one that I need is still missing. There is `pagexray.pageSummary.firstParty.requests` for all the firstParty requests, but the same thing is missing for the thirdParty (e.g `pagexray.pageSummary.thirdParty.requests`). Instead I only have the requests for specific content types like CSS, JS, etc.

If I understand correctly, this makes it impossible to set a budget based on the **total** number of thirdParty requests.
It would be great if you could confirm that :)

**Comment by soulgalore** [comment]
Ah sorry I see now. 

Ok, could it be that if you don't have any third parties PageXray doesn't add it?

When I test `sitespeed.io  --metrics.list --firstParty .*cnet.* -n 1 https://www.cnet.com` I get pagexray.pageSummary.thirdParty.requests and pagexray.pageSummary.firstParty.requests

Best
Peter

**Comment by Algram** [comment]
Yeah that is a good guess. I tested it with sitespeed.io, which does not have any third parties. I will configure the budget with `pagexray.pageSummary.thirdParty.requests` and see if it works.

Thanks for your help!
