### ISSUE TITLE
[Question] Get raw metrics of each measurement

### ISSUE THREAD

**Issue by moehlone** [sitespeedio/sitespeed.io#1710]
Hi,

sorry if I missed that in your great docs, but: 

Is it possible to get a raw CSV, JSON or other format of all measurements for each page/iteration?

Thank you in advance.

Best regards
Philipp

**Comment by soulgalore** [comment]
Hi @moehlone I think we miss documentation about that, let me go through it this weekend. You can write all raw data (as JSON) to disk so get the data from each plugin (Browsertime, Coach WebPageTest etc). There's some info here: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#add-a-plugin

We have a plugin (named analysisstorer (not the best name)) that you need to turn on:
`$ docker run -shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io --plugins.load analysisstorer `

should do the trick.

Best
Peter

**Comment by tufandevrim** [comment]
This is very nice. I have tried following command:
```
sitespeed.io https://www.yahoo.com/ --plugins.load analysisstorer
```
it produces 7 json results, among one of them always has invalid json format: `largestassets.summary.json`

**Comment by soulgalore** [comment]
thanks @tufandevrim I created a new issue for that, I'm closing this one.
