### ISSUE TITLE
Information from Plugin (S3) in Postscript

### ISSUE THREAD

**Issue by taurusismysign** [sitespeedio/sitespeed.io#1714]
Can a plugin - say s3 - which is uploading the files to S3 bucket make the s3 path available in postscript (context.results)?

Or screenshot path be available in postscript?

Basically, postscript gives results but outputs/ results of these independent plugins is not available there to read. How can this be made possible?

**Comment by tobli** [comment]
Hi @taurusismysign!
Could you please describe your use case, what you'd like to achieve? Pre- and post scripts run before or after every url is loaded in your local browser (Browsertime running as one of the sitespeed.io plugins). The S3 plugin to sitespeed.io does its' work at the last stage of the plugin lifecycle, when all plugins have completed. Therefor there's no direct relationship between postscripts and the s3 plugin.

**Comment by taurusismysign** [comment]
Thanks for the quick response @tobli 

So here's what I am trying to do. I want ONE json output of all plugins - browsertime, s3 etc - so that I can take that information and process it. 

I was hoping that postscript is that place - but looks like postscript is post browsertime (plugin) and doesn't have any relation with s3 or other plugins. 

Is there any hook/ place which runs at the very end where I can get results from all the plugins?

**Comment by tobli** [comment]
There's no canonical JSON representation of plugin results. Some plugins (such as the s3 plugin) just logs some information as it runs. Others, such as the browsertime plugin, can store megabytes of data to disk for each url (including HAR files, screenshots etc.).

Not knowing what type of processing you're thinking of, it sounds like you might want to make a plugin of your own. Most plugins listens to messages, sent either by other plugins or by sitespeed.io itself. Some also sends messages, e.g. the domains plugin listens for 'browsertime.har' messages, analyses what domains are used, and sends a 'domains.summary' message that's picked up by the html plugin and the graphite plugin. If you write your own plugin, you can take part in this exchange of messages.

To see the flow of messages just add ```--debug``` when running sitespeed.io (add an extra -v for more in-depth messages). You can read a bit more here: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#add-a-plugin.

**Comment by taurusismysign** [comment]
This sounds great @tobli. Thanks for such a detailed answer.
