### ISSUE TITLE
IE 11 Setup Details or Step 

### ISSUE THREAD

**Issue by SourabhKotnala** [sitespeedio/sitespeed.io#1715]
Hi,

I am performance engineer and  trying to setup sitespeed for IE11, but not sure about the configuration steps for it. Is there a documentation around it which can be shared.
Thanks

**Comment by soulgalore** [comment]
Hi @SourabhKotnala we don't support Windows at the moment. With some changes it could work but we are too few people to keep a Windows version working. You can use a WebPageTest agent and pull the data from that or just run WebPageTest standalone if IE 11 metrics is the one you need

Best
Peter

**Comment by SourabhKotnala** [comment]
Hi @soulgalore, thanks for quick response. I did try that but having issues for IE11 with uwebsockets.

Regards
Sourabh
