### ISSUE TITLE
404 when trying to download Grafana dashboards package

### ISSUE THREAD

**Issue by kamilkrzeminski** [sitespeedio/sitespeed.io#1720]
Downloading dashboards package from https://www.sitespeed.io/documentation/performance-dashboard/dashboards.zip results in 404.

**Comment by soulgalore** [comment]
Hey @kamilkrzeminski thanks for reporting! We need to change the link. The correct way is to either use the docker image: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#pre-made-dashboards or download them from that repo: https://github.com/sitespeedio/grafana-bootstrap-docker

Best
Peter

**Comment by soulgalore** [comment]
By the way, do you remember where you got to that link?

**Comment by kamilkrzeminski** [comment]
Actually - somewhere here in issues. But there's another 404 on this page: https://www.sitespeed.io/3.x/performance-dashboard/ (search "To get up and running fast we have a zip file") - URL targeting  https://www.sitespeed.io/dashboards.zip

**Comment by soulgalore** [comment]
Thanks that's the old (really old) version, I'll remove old that when we push 6.0. No one should run 3.x.

**Comment by kamilkrzeminski** [comment]
Thanks for the answer, I got that working.

**Comment by soulgalore** [comment]
Old docs removed.
