### ISSUE TITLE
Allow plugins to depend on other plugins

### ISSUE THREAD

**Issue by Mr0grog** [sitespeedio/sitespeed.io#1724]
Is there any way to specify that one plugin requires another to be loaded? For example, if I’ve written a plugin that processes messages from gpsi in order to do something special, I’d like to ideally ensure that gpsi gets loaded without having to tell a user to make sure they’ve set `--plugins.load gpsi my-plugin`.

Barring that, it would at least be nice to have a final list of loaded plugins so I could throw an error or log a message noting that gpsi (or whatever other plugin I depend on) isn’t loaded.

Similarly, it would be helpful to be able to supply additional options to the plugin I depend on. For example, I am working on a plugin that requires a special post-script be used for Browsertime. It would be nice to somehow explicitly declare that I depend on Browsertime and provide the path to the post-script to load from my plugin instead of telling users to make sure they set that Browsertime option appropriately on the CLI.

**Comment by soulgalore** [comment]
Hi @Mr0grog thanks for sharing, sorry that it took a couple of days to get back.

I'm gonna put in some work for the plugin structure for 6.0 sometimes in October or early November, but my main focus will be to add support for HTML (so you, when you do a plugin, can add your result to the HTML pages), for me that is the feature I miss the most.

Plugin dependency will make things more complicated so I'm scared of that.  One way to fix the problem for users is to supply [an example config.json](https://www.sitespeed.io/documentation/sitespeed.io/configuration/#configuration-as-json) where you can put all the config with the plugins that need to run. Maybe we could make the list of configured plugins available in the context, else I would add a check in close for my plugin and then log/throw if I didn't got any messages. Not perfect but it could be away to show it for the user.

> supply additional options to the plugin I depend on

Yep, we started this a year ago or something, like your plugin can say what parameters that they support so when you run --help the user sees those extra params? We should look at that again. I agree we should have something like that.

Best
Peter

**Comment by Mr0grog** [comment]
> Plugin dependency will make things more complicated

Yeah, I can’t disagree with that! Even if explicit dependencies aren’t possible, it would be helpful if the the plugin `open` method received a list of all the loaded plugins so I could log a meaningful error telling the user exactly what they need to set for their `plugins.load` argument if the plugin I depend on isn’t present.

> like your plugin can say what parameters that they support so when you run --help the user sees those extra params?

That would be nice, too, but not quite what I was getting at. In my current case, I have a plugin called `image-detector`, which finds detailed information about the images used on the page. To do so, it has to run a browser script. That means the user has to specify the following options:

`--plugins.load plugins/image-detector --postScript plugins/image-detector/browsertime-post-script.js`

That second argument seems kind of ridiculous to have to tell the user to add (and error-prone). It would be much nicer if someone could just specify:

`--plugins.load plugins/image-detector`

…and the plugin code itself could be given the opportunity to update the `browsertime.postScript` option.

**Comment by soulgalore** [comment]
Yep, lets aim for making the plugin list public. I can fix that for 6.0.

> --plugins.load plugins/image-detector

I understand. That would mean that your plugin would send a message that browsertime would pick up. I need to talk with @tobli about it, I like the idea but not sure how we would implement it.

Best
Peter

**Comment by soulgalore** [comment]
@tobli I think a plugin could pass on a message in postOpen that Browsertime would pickup and then add it to the array of JavaScript that it runs with just open up https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/browsertime/analyzer.js#L49 ? That would make plugins really powerful and still easy to use for users.

**Comment by soulgalore** [comment]
@Mr0grog we done some fixes here in the latest release see: https://www.sitespeed.io/documentation/sitespeed.io/plugins/

There's a setup phase now when plugin can talk to each others. Plugins can send JavaScript to browsertime and catch the result. 

They will depend on each other but hopefully you can do the most of what you need. Else please re-open or create a new issue.

**Comment by Mr0grog** [comment]
This is a huge improvement, thanks!

However, it seems like I need to use the `browsertime.config` message to set up pre/post scripts, and when doing that I run the risk of clobbering ones specified by other plugins or via CLI (because [it just uses `lodash.merge()` on the options](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/browsertime/index.js#L153-L156), which replaces/merges array elements instead of appending). So I have some imperfect boilerplate now:

```js
function processMessage (message, queue) {
  if (message.type === 'sitespeedio.setup') {
    // This message-based config mechanism is a public API, but unfortunately
    // you can’t specify new post-scripts to *add*, so we have to reach around
    // and try and figure out what’s already configured to be safe.
    const browsertime = this._options.browsertime;
    const existingPostScripts = browsertime && browsertime.postScripts || [];

    queue.postMessage(make('browsertime.config', {
      postScript: existingPostScripts.concat([postScriptPath])
    }));
  }
}
```

It would be great if that treated pre/post scripts specially or if there was special message for them. Should I file a separate issue for that?

It also looks like, based on the docs, normal [scripts are no longer required to return numeric, aggregatable values](https://github.com/sitespeedio/sitespeed.io/blob/master/docs/documentation/sitespeed.io/plugins/index.md#let-your-plugin-collect-metrics-using-browsertime). Is that right? If there were a way to add async scripts, I could use that instead.

**Comment by soulgalore** [comment]
Hey @Mr0grog there's no way right now to add pre/post scripts from a plugin to Browsertime can you give me an example when you need it so I understand? They are usually site specific?

> It also looks like, based on the docs, normal scripts are no longer required to return numeric, aggregatable values. Is that right?

They have actually never needed to. Browsertime collect for example all the data for the coach: https://github.com/sitespeedio/coach/tree/master/lib/dom/info

> If there were a way to add async scripts, I could use that instead.

Browsertime supports async scripts but we don't have a way to add it right now from sitespeed.io. PRs are welcome :)

Best
Peter

**Comment by Mr0grog** [comment]
> there's no way right now to add pre/post scripts from a plugin to Browsertime can you give me an example when you need it so I understand? They are usually site specific?

For one, it’s the only way to provide an asynchronous script right now without skipping Sitespeed.io and using the Browsertime library directly (so far as I can tell). So I don’t have any other options, even though it is completely generic.

My current use case is the one explained earlier in this issue: https://github.com/sitespeedio/sitespeed.io/issues/1724#issuecomment-333162819 — the script finds all the images and their rendered sizes in the page. It’s async because it has to make sure every image is loaded in order to determine rendered size (since aspect ratio is often maintained).

> They have actually never needed to. Browsertime collect for example all the data for the coach

Hmmm, looking through the 5.x source now, I’m struggling to remember what exactly I was trying to do that was causing problems. I think maybe I had been trying to get a single value out from all the runs, but it still seems like should have been able to do that without causing it to go through the aggregator. Nevermind on that, I guess.

> PRs are welcome :)

If only I had the time aside from other projects I am maintaining! But I certainly hear you here.

**Comment by soulgalore** [comment]
Lets create an issue the coming days then the coming days to open the Browsertime from sitespeed.io to async a JavaScript, it's a nice feature but no one has focused on opening it up from the outside.

**Comment by soulgalore** [comment]
https://github.com/sitespeedio/sitespeed.io/issues/1837
