### ISSUE TITLE
No page reload when accessing landing page

### ISSUE THREAD

**Issue by JoaoGFarias** [sitespeedio/sitespeed.io#1734]
Given that:
- Selenium is a great tool for performing complex interactions on web pages;
- Many interesting performance issues happen after AJAX requests (click on a button that loads a huge load of data);

One can use the _--preScript_'s to not only log in applications, but also to perform interactions on them. The problem lies on the fact the landing page is obligatorily accessed, reloading the page. This reloading can invalidated the operations performed _--preScript_'s.

It would be great if we could have one of the following options:
- Skip the landing page step;
- Have a _--innerScript_, which would allow to use Selenium to interact with the page before _--browsertime.pageCompleteCheck_ loop starts running.

**Comment by soulgalore** [comment]
Hey @JoaoGFarias yes, I actually started on something like that in https://github.com/sitespeedio/browsertime/tree/selenium-script today but I need to find the time to discuss and sync with @tobli and @beenanner . I hope we can have something like that in 6.0 late November.

Best
Peter

**Comment by soulgalore** [comment]
I created a discussion issue for this and closing all other issues: #1827 Let us do all the talking there :)
