### ISSUE TITLE
docker-compose and urls.txt

### ISSUE THREAD

**Issue by pixlab** [sitespeedio/sitespeed.io#1736]
Hello,

I'm trying to test some urls using urls.txt file and send it to grafana...but it doesn't work, this is the response in my terminal:

`$ docker-compose run sitespeed.io "$(pwd)"/urls.txt --graphite.host=graphite`
`Google Chrome 60.0.3112.78`
`Mozilla Firefox 54.0`

`/usr/src/app/lib/support/cliUtil.js:32`
`            throw new Error(`Couldn't find url file at ${filePath}`);`
                  ^
`Error: Couldn't find url file at <pwd_path>/urls.txt`
`    at Object.getURLs (/usr/src/app/lib/support/cliUtil.js:32:19)`
`    at Object.parseCommandLine (/usr/src/app/lib/support/cli.js:683:19)`
`    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:22:18)`
`    at Module._compile (module.js:570:32)`
`    at Object.Module._extensions..js (module.js:579:10)`
`    at Module.load (module.js:487:32)`
`    at tryModuleLoad (module.js:446:12)`
`    at Function.Module._load (module.js:438:3)`
`    at Module.runMain (module.js:604:10)`
`    at run (bootstrap_node.js:389:7)`
`    at startup (bootstrap_node.js:149:9)`
`    at bootstrap_node.js:504:3`

thanks for your help :)
Roberto

**Comment by soulgalore** [comment]
Hi @pixlab you need to map your file/map into the container, checkout https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes

Best
Peter

**Comment by soulgalore** [comment]
I think you missed **-v** before your mapping.

Best
Peter

**Comment by soulgalore** [comment]
ah sorry you are running compose, need to google then how to map your dir correctly :)

**Comment by soulgalore** [comment]
Ok, the correct way is to add it to your docker-compose file:
```
...
     volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - ./urls.txt:/sitespeed.io/urls.txt
...
```

and then `docker-compose run sitespeed.io urls.txt  ...`

Best
Peter

**Comment by hunt3r** [comment]
👍 Thanks!
