### ISSUE TITLE
Question - custom plugin dependencies

### ISSUE THREAD

**Issue by tglanz** [sitespeedio/sitespeed.io#1743]
Hi,

I have a custom plugin which has some npm dependencies (axios for example) not included in the sitespeed's main package.json.

My approach of enabling it in the plugin's code is by having a package.json inside the plugin's directory which contains those dependencies. When the container will run, it'll have the plugin with the required node_modules to include so everything works as expected.

With this approach, ill have to npm install before the first execution on the **host machine**, which might not have node installation or a correct node version.

So my question is,
Is there any other way of including dependencies without having to install them from the host?
Maybe a pre-load script / commands that runs inside the container?

Thanks!

**Comment by soulgalore** [comment]
Hi @tglanz 
no I don't have a better way to do it (except of copying node_modules from another machine if installing npm is the issue) @beenanner @tobli do you have any input?

Best
Peter

**Comment by beenanner** [comment]
@tglanz / @soulgalore  I think grafana does something similar with their plugin infrastructure. I'll take a peek this week and report back. If you are using docker containers for now would it be easier to just create an custom image with your plugin and dependencies already installed using a Dockerfile?

**Comment by tglanz** [comment]
@beenanner creating a custom image is a great idea, thank you

**Comment by soulgalore** [comment]
Fixed by Jonathans comments.
