### ISSUE TITLE
Update log info - HTML stored

### ISSUE THREAD

**Issue by lucaspouzac** [sitespeedio/sitespeed.io#1744]
Is it possible to update this log info (or add new log) when we run sitespeed ?

Actually log
> [2017-10-16 16:03:31] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.example.com/2017-10-16-15-59-01

Run sitespeed 
> docker run --privileged --shm-size=1g --rm -v /sitespeed.io/config.json:/sitespeed.io/config.json  sitespeedio/sitespeed.io:5.6.2 --config config.json -b chrome

config.json
> {
...
  "resultBaseURL": "http://webperf.example.fr/"
}

Expected log
> [2017-10-16 16:03:31] INFO: HTML stored in http://webperf.example.fr/www.example.com/2017-10-16-15-59-01

**Comment by soulgalore** [comment]
Hi @lucaspouzac thanks for the issue, yes that is a good idea, let us add that.

Peter

**Comment by soulgalore** [comment]
Pushed this to master (coming 6.0), if we do fix release of 5.x I'll make sure we include it. Trying to focus only on 6.0 now :)
