### ISSUE TITLE
minimum required Node.js version

### ISSUE THREAD

**Issue by DanielRuf** [sitespeedio/sitespeed.io#1751]
The docs say 4.3.0 is required but there is a spread operator and 6 is required as a minimum.

https://www.sitespeed.io/documentation/coach/how-to/

**Comment by soulgalore** [comment]
Hi @DanielRuf thanks for your finding. We use [LTS](https://github.com/nodejs/Release#release-schedule1) so current stable you should use latest 6.x and soon we will switch to 8.

Best
Peter

**Comment by soulgalore** [comment]
We released a new version yesterday and now everything needs 8.9 and docs are updated.
