### ISSUE TITLE
Running headless?

### ISSUE THREAD

**Issue by krukru** [sitespeedio/sitespeed.io#1753]
Is there an option to run chrome or firefox browsers in headless mode? I tried passing `--browsertime.chrome.args "headless" --browsertime.chrome.args "disable-gpu"` for chrome, but this just generated a bunch of errors.

**Comment by soulgalore** [comment]
Hi @krukru if you run from sitespeed.io `--browsertime.headless` it should work.

`sitespeed.io --browsertime.headless -n 1 https://www.sitespeed.io`

However some functionality will not work since headless in Chrome doesn't support WebExtensions.

Best
Peter

**Comment by krukru** [comment]
Thanks again Peter for the quick answer. I double checked the documentation and couldn't find any word about this option. It certainly has it's use case, maybe it would be a good idea to include it

**Comment by soulgalore** [comment]
Maybe. We don't expose every configuration from Browsertime to try to limit the chock when you run --help. To see them (the latest version) you can run `$ browsertime --help.`

We preparing everything for 6.0 that will be released sometime after FF 57.
