### ISSUE TITLE
separate Sitespeed executions using docker

### ISSUE THREAD

**Issue by mvillarejo** [sitespeedio/sitespeed.io#1768]
Hello,

first of all, congratulation for the tool, it's really great,

do you think is there any way I could run several checks using the same docker container but report them separatelly rather than all into the same report? i.e.
```
sitesepeed.io --separate http://www.google.com http://www.google.es
```
will create two separate reports rather than only one. The idea behind this is to reuse the actual dependencies: selenium, Xvfb, etc. so we can run checks sequentially and avoid duplicating the same processes within different containers...

I hope that makes sense

thanks!

**Comment by soulgalore** [comment]
Hi @mvillarejo thanks for the kind words.

I'm not sure I understand exactly how you wanna do it?

So you can test multiple URLs and they will be reported separately to Graphite/InfluxDB and each page to HTML, but the summaries will be for both URLs. 

You can either use add the URLs `sitesepeed.io  http://www.google.com http://www.google.es` or the path to a file with each URL on one line. Then the URLs will be tested after each other.

But you need to different reports?

Best
Peter

**Comment by mvillarejo** [comment]
thanks for the quick response! yes, it'll be great if the reports are generated separately.

feature request maybe? 🙈

**Comment by soulgalore** [comment]
I didn't fully get why it's important to reuse the same depennies as you say?

**Comment by mvillarejo** [comment]
well, it'll be great if we could have those reports individually as the pages do not have relation between them.

**Comment by soulgalore** [comment]
yes but I'm from Sweden: I must have a reason/a use case where it will help to be able to implement :) Like will it make it easier/save money etc?

**Comment by mvillarejo** [comment]
it's ok, I believe we will work out another implementation,

thanks anyway.
