### ISSUE TITLE
Is it possible to measure interactions within an already loaded page?

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#1771]
Guys, good morning!

I wonder if it is already possible to perform the following interactions on a loaded page:

1. Clicking on any page element (page can't be reloaded)?
2. Fill in some inputToken and only go to measure the performance from the interaction of the click;
3. Click to open some interaction modal and only start to measure the performance from the moment of the click and finish this measurement after the appearance of the modal.

Currently I have felt many needs to test the performance of elements of a page, not just page loading. And since I have used sitespeed.io to do load performance tests, maybe these possibilities can add a lot more value to our tool.

I'm waiting for feedback.

Thank you so much for your availability.

**Comment by soulgalore** [comment]
Hi @livyson I think starting by adding  [user timings](https://www.w3.org/TR/user-timing/) on your page could be the first thing, so whatever tool can pickup those metrics (RUM, sitespeed.io). Right now you can do that on a preTask but you need to do something smart to propagate it to the last page, not sure how I would do it with the current solution.

Best
Peter

**Comment by livyson** [comment]
Thanks, @soulgalore! I am starting this job.
