### ISSUE TITLE
FTP uploader plugin

### ISSUE THREAD

**Issue by moix** [sitespeedio/sitespeed.io#1778]
Hi!
I wanted to contribute with a simple ftp uploader plugin to publish the output of the executions into an ftp, I find it useful, so I send a pr some minutes ago, #1777, however the build failed. I'd be happy to fix it if is related, anyone can help here?

Thanks!

**Comment by soulgalore** [comment]
Let us create a new issue when this is needed. I think now when we both support s3 and the google version have what we need.
