### ISSUE TITLE
Sitespeed vs WPT numbers... 

### ISSUE THREAD

**Issue by raptor235** [sitespeedio/sitespeed.io#1788]
Hey there,

We're pulling our hair our trying to figure out why sitespeed numbers are so different from WPT... 

If you take a look at these numbers 

http://www.flowpress.com/screenshots/Screen%20Shot%202017-11-09%20at%2012.08.24.png 

WPT SpeedIndex and Fully Loaded numbers are like 300% higher then what sitespeed is reporting.

Any help shining some light here would be amazing... thank you!

**Comment by tobli** [comment]
Hi!
Hard to say without more context, but one thing to start looking at are latency and bandwidth differences. Are you running the tests much “closer” to the site you’re accessing, compared to the where the WPT node is? If you’re running a private WPT instance, not having enough memory and cpu for that can have a huge impact on timings.
Use the HAR files (waterfalls in the sitespeed.io report) to see how download times compare between local browser and WPT.
Hope this can be of some help!
/Tobias

**Comment by raptor235** [comment]
Thanks @tobli 

That's actually one thing that we're going to test now... we were using sitespeed without any connection speed limits. The WPT test was run againts the public version and I just noticed they limit the speed to cable... so this would be the only explanation as to why there is such a massive difference in performance.

**Comment by soulgalore** [comment]
I can add a couple of things to the list (I'll update the docs in coming 6.0):

There's a couple of things to know that differs between WebPageTest and Browsertime/sitespeed.io but first I wanna say that it is wrong to compare between tools, it is right to continuously compare within the same tool to find regressions :)

WPT and sitespeed.io differs by default when they end the tests. WPT ends when there hasn't been any networks traffic for 2 seconds (if I remember correctly). sitespeed.io ends 2 s after loadEventEnd. Both tools are configurable.

WebPageTest on Windows (old version) records the video with 10 fps. 5.x of sitespeed.io uses 60 fps, coming sitespeed.io 6.0 will have 30 fps per default. New WebPageTest on Linux will have 30 fps per default. Running 60 fps will give you more correct numbers but then you need to have a server that can record a video of that pace. 

And a couple of generic testing things:

Connectivity matters: You need to set the connectivity.

CPU matters: Running the same tests with the same tool on different machines will give different results.

The page your testing matters. It could happen that your page has different sweat spots on connectivity (that makes the page render faster) so even a small change, will make the page much slower (we have that scenario on Wikipedia).

**Comment by abhagupta** [comment]
We had a similar discussion in the beginning when we started testing our front end apps. After multiple runs with both WPT and sitespeed.io, we saw different results and we didn't know which ones to trust.  As Peter mentioned, yes, these are 2 different tools whose results should not compared with each other.   We finally ended up creating a laboratory setup in which we run sitespeed.io in an isolated docker containers inside a VM which is very tightly controlled from resources standpoint.  We monitor the resources continuously using `sysbench`.   This gave us a standard benchmarks to start with.  Now we run the tests continuously to find any regressions.  Also, how we addressed the noise of connectivity ?  We mocked all the third party calls to ads services, and anything we could not control in production environment. 

As far as picking between 2 tools, (WPT or Sitespeed.io), both are reliable as long as you follow one. Good thing is sitespeed.io can give you both.

**Comment by soulgalore** [comment]
@abhagupta thanks for sharing! You don't use any replays like mahimahi or WebPageReplay? We've been testing out Browsertime with WebPageReplay at work with good results but we are still struggling on where we should deploy it. So far we get best stable metrics on a c4.large on AWS but would like to move the tests inhouse, but we haven't tried what you described, interesting!

**Comment by beenanner** [comment]
I'm also very interested in how you all approached the mocking of ads services @abhagupta. If you have the time I'd love to touch base privately as we are looking to do something similar at my work!

**Comment by abhagupta** [comment]
Sure. You can email me at abha.agupta@gmail.com. We essentially mock the
responses of third party calls with a mocking server. We have in-house
built mocking service but it is similar to products like Wiremock,
MockServer etc . If you are in node world, you can make use of Smocks, nock
etc.

**Comment by soulgalore** [comment]
I've added a part in the docs about the difference, please send PRs if I missed anything: https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#difference-in-metrics-between-webpagetest-and-sitespeedio

Closing, let me know if you need more info!
