### ISSUE TITLE
Is there any way to specify where tests start?

### ISSUE THREAD

**Issue by skeenerok** [sitespeedio/sitespeed.io#1796]
Hi sitespeed.io team,
I'm looking for tools to measure the performance of Single Page Application written on Angular2 and sitespeed.io looks very interesting. To log in the application I use selenium in --preScript,  to define whether the application is loaded I use  --browsertime.pageCompleteCheck. However, I did not find the way to specify where tests start since the page is always reloaded after executing --preScript. I try to measure how much time is required for one user interaction(for example open user list) without the time of loading whole application. Can you give me some advice?
I'm looking forward to hearing from you.

**Comment by soulgalore** [comment]
Hi @skeenerok sorry for the late reply. Yep this is something I also think is important, it doesn't work in the current version. @tobli and me try to find some time to discuss it but has failed so far, hope to do it early next week.

Best
Peter

**Comment by soulgalore** [comment]
I created a discussion issue for this and closing all other issues: #1827 Let us do all the talking there :)
