### ISSUE TITLE
Use ISO 8601 timestamps in browsertime plugin.

### ISSUE THREAD

**Issue by tobli** [sitespeedio/sitespeed.io#1806]
Currently timestamps in browsertime.pageSummary and browsertime.run message data are changed from ISO 8601 (in the Browsertime source data) to a "yyyy-MM-dd HH:mm:ss" format. This is so we can print a human friendly timestamp in the generated html.
However this is a backwards dependency. We should publish data in a standard format, and reformat it for humans only when we actually need to.

**Comment by soulgalore** [comment]
Closing since we haven't implemented this in two years.
