### ISSUE TITLE
Running of Performance evaluation on iPhone/iPad Air2

### ISSUE THREAD

**Issue by rachitktesting** [sitespeedio/sitespeed.io#1814]
Environment:
iPhone 6, iPhone 8 Plus, iPhone X
iPad Air2, iPad Pro

Expected: 
Should be able to plugin iPhone in USB mode and run the performance test on iOS / Safari.

Actual:
Execution is not happening on iOS devices.

**Comment by soulgalore** [comment]
Hey @rachitktesting we don't support iOS devices, when webdriver can, we can do it too. Checkout https://www.webpagetest.org/ that got nice support for iOS.

Best
Peter

**Comment by rachitktesting** [comment]
Hey Peter,

First of all Sitespeed.io is awesome, I just configured docker and running the test generating dashboards hardly in <10 mins.

We are using several platforms like SauceLabs (Emulators), TestObject (Real devices), Local Selenium Grids etc. 

Could there be a way somehow to run the performance test on these devices in SauceLabs, TestObject public clouds and getting the results pushed to any repository may be S3 (?).

What do you think?

Thanks for making wonderful product,
Rachit

**Comment by soulgalore** [comment]
Thanks @rachitktesting  :)

There are people that has done some  hacking and using SauceLabs (I think you can find some clues in issues in Browsertime and here), but there's nothing we officially support. I've seen that they are satisfied with the metrics they get, I'm personally a little skeptical until someone can show me some raw numbers. Another (better) way would be to build a plugin for SauceLabs plugin for sitespeed.io, that should be doable and we can surely help guide you. We will soon (days/week(s)) release 6.0 that make the plugins easier. 

Best
Peter
