### ISSUE TITLE
HELP.md is missing

### ISSUE THREAD

**Issue by sergeychernyshev** [sitespeedio/sitespeed.io#1815]
Looks like HELP.md file was deleted a few days ago
https://github.com/sitespeedio/sitespeed.io/commit/698438863ced48fd04a195e35f3b1a47d7cbbfad

breaking some links
https://github.com/sitespeedio/sitespeed.io/search?q=%22HELP.md%22&type=Code

**Comment by soulgalore** [comment]
Thanks @sergeychernyshev I think (I hope) I hade some idea ... but I don't remember what so added it back :)
