### ISSUE TITLE
Grafana dashboard - Templating init failed [object Object]

### ISSUE THREAD

**Issue by khalmur** [sitespeedio/sitespeed.io#1817]
Using latest (https://raw.githubusercontent.com/sitespeedio/sitespeed.io/master/docker/docker-compose.yml), with grafana:4.6.2 , I get "Templating init failed [object Object]" when I open dashboard.

<img width="1439" alt="templating_init_failed" src="https://user-images.githubusercontent.com/33911616/33148921-ae1326aa-cf9b-11e7-9353-366b50faa8cd.png">

**Comment by beenanner** [comment]
Hi @khalmur could you share what OS and version of Docker and Docker Compose are you running? I just tested on Ubuntu 16.04 with Docker 17.11 CE and Docker Compose 1.17 and everything is working as expected.

```
beenanner@ubuntu:~/test$ docker-compose -v
docker-compose version 1.17.0, build ac53b73
beenanner@ubuntu:~/test$ docker -v
Docker version 17.11.0-ce, build 1caf76c
beenanner@ubuntu:~/test$ uname -a
Linux ubuntu 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by khalmur** [comment]
@beenanner my docker-compose wasn't running latest, sorry about that. Closing issue.
