### ISSUE TITLE
ENV set in Dockerfile is Strings but we treat them as booleans

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1822]
This is generic problem we have in both Browsertime and sitespeed.io. We get "false" but treat want to treat it as a boolean.

**Comment by beenanner** [comment]
Look like we may need to handle this in the wrapper script to convert from a string to a boolean?

**Comment by beenanner** [comment]
It appears process.env stores everything as a string. I think it's also being parsed by yargs in browsertime and converted to a boolean or at least should be?
 https://github.com/sitespeedio/browsertime/blob/master/lib/support/cli.js#L54

https://github.com/sitespeedio/browsertime/blob/master/lib/support/cli.js#L432

**Comment by soulgalore** [comment]
yes but I think it's not. I logged the options object and it had 'false'/'true' for the env. Had a problem with turning on/off XVFB fo android.

**Comment by soulgalore** [comment]
We are moving away from them so I think we can close this issue.
