### ISSUE TITLE
Repeating `--plugins.add` or `--plugins.remove` throws exceptions

### ISSUE THREAD

**Issue by Mr0grog** [sitespeedio/sitespeed.io#1831]
I’ve just upgraded to v6 and the configuration documentation says “specify multiple plugin names separated by comma, or repeat the --plugins.add option” for both `--plugins.add` and `--plugins.remove`. However, repeating them doesn’t actually work and in fact throws an exception:

```sh
$ bin/sitespeed.js http://www.sitespeed.io --plugins.add plugin-1 --plugins.add plugin-2
> plugins.add.split is not a function
```

It looks like the problem is that the [`coerce` function for plugins doesn’t check the type for the `add`/`remove` properties](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli/cli.js#L641-L649). It should probably also make sure to split each item in the array (if the properties are arrays) and flatten them, since it could be repeated with comma-delimited lists, too:

```sh
$ bin/sitespeed.js http://www.sitespeed.io --plugins.add plugin-1 --plugins.add plugin-2,plugin-3
```

**Comment by soulgalore** [comment]
Thanks @Mr0grog for reporting, let us fix this ASAP.

**Comment by soulgalore** [comment]
thanks again @Mr0grog for reporting, pushed 6.0.1 a couple if minutes ago with the fix.
