### ISSUE TITLE
Passing configuration parameters to sitespeed.io running on AWS ECS

### ISSUE THREAD

**Issue by Dolphsps** [sitespeedio/sitespeed.io#1836]
Has anyone tried to run sitespeed on AWS ECS and passed configuration parameters through config.json?

I have bundled up my configuration in to a config.json file and have my URL list in urls.txt.  Both files are passed to /sitespeed.io.

My ECS task command [urls.txt] works fine but I am seemingly unable to find a way of combining the urls.txt with the additional configuration file [--config config.json].

I have tried various incantations of [urls.txt, --config config.json], [urls.txt, config=config.json].

Any help would be much appreciated.

**Comment by soulgalore** [comment]
Hi @Dolphsps no I haven't tried ECS. @beenanner have you tried?

Running on standard Docker you need to make sure that you mount both urls.txt and config.json and that you inside the container references to where the file actually is (inside the container). If that helps you somehow :)

Best
Peter

**Comment by Dolphsps** [comment]
Hi @soulgalore thanks for quick reply.  Both files are in the same volume and I can see the file from the container.  Just can't get the container to launch with the configuration parameters defined within.

**Comment by beenanner** [comment]
@Dolphsps do you have the exact run command? I haven't dabbled in ECS much but it should be `--config config.json` then `url.txt`. If you are passing an array maybe try ['--config', 'config.json', 'url.txt']?

Here is the docker run command I use to verify locally though that probably isn't much help.

`docker run -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io --config config.json url.txt`

and overriding the config is done before the file path of the urls as well.

`docker run -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io --config config.json -n 1 url.txt`

**Comment by beenanner** [comment]
@Dolphsps ECS Tasks try to use the CMD syntax from the dockerfile instead of supporting individual ARGs like docker run. See: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html 

After running the task can you run `docker inspect` on one of the containers and see if the args are showing up in the json output as an array?

**Comment by beenanner** [comment]
```
4211990feaf   sitespeedio/sitespeed.io   "/start.sh -n 10 https://www.sitespeed.io"                          25 seconds ago      Up 24 seconds                           inspiring_wing
```
overriding the CMD make it run like so which breaks sitespeed

```

**Comment by Dolphsps** [comment]
Hi @beenanner and @soulgalore .

I have got this working now and we are building up a nice little setup based on AWS ECS services.  
Thanks for your help.

**Comment by beenanner** [comment]
That's great news @Dolphsps! Let us know if you run into any other issues. It would be great if you have any generic steps or tips and tricks to show others how to run a similar setup in AWS ECS. I'm sure others would love it. Selfishly if I ever get some time I wouldn't mind trying to set things up myself. ;-) I'll close this issue.

**Comment by Dolphsps** [comment]
Yeah will do.  In the light of the AWS announcements last week on ECS and their new Fargate offering, it could look very different when these features are made generally available.
