### ISSUE TITLE
Docker Image for Sitespeed goes missing!!

### ISSUE THREAD

**Issue by ganeshmuralidhar** [sitespeedio/sitespeed.io#1843]
Hi,

I started using the docker version on sitespeed and is able to run tests followed by proper reporting. 
I started facing a weird issue where on one particular machine, I pull the docker image using 

docker pull sitespeedio/sitespeed.io

and i execute a test. So far so good, after few minutes when I execute another test, i get an error saying 'Unable to find image 'sitespeedio/sitespeed.io:latest' locally' and the image gets downloaded again. 

When i re-checked the same by looking at docker images on my host, i see that the sitespeed image went missing. I tried multiple ways to restore it by composing a tar file one a different host and extracting it here. But after few mins the image just goes missing and i couldn't find it any where. 

I have to do a docker pull everytime i need to use sitespeed. Any pointers here please?

**Comment by soulgalore** [comment]
Hi @ganeshmuralidhar 
no you need only to pull it once. But when you do, please use the tags so you use one exact version:
`docker pull sitespeedio/sitespeed.io:6.0.3`
That way you can make sure you are in control when you upgrade to a new version.

There's something on your machine that removes containers, do you run docker prune somewhere? :)

**Comment by ganeshmuralidhar** [comment]
Hi Pete,
I did use the version as well when tried for various options. And dont see any docker prune running ever. When all my other images on this host stay, dont know why only sitespeed goes missing !

**Comment by soulgalore** [comment]
Hmm strange, please let me know if you find the reason. I have a hard time to see this is something todo with our image.

**Comment by ganeshmuralidhar** [comment]
I too think the same. Will raise it with docker and see if there is a solution.

**Comment by ganeshmuralidhar** [comment]
Hi Pete,

Now that we are not able to find a solution for this, is there a chance you can give me the actual DockerFile and the related files repo so that I can try to build the image by myself on my host and see if that can solve the issue?

Thanks!

**Comment by soulgalore** [comment]
I don't think it will help, but the Dockerfile is here: https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile

**Comment by ganeshmuralidhar** [comment]
True. This didn't help either :(

**Comment by ganeshmuralidhar** [comment]
But, one thing that I observed is that the image stays back of I pull any version 5.2.0 and below. And not beyond that. This is really weird.

**Comment by ganeshmuralidhar** [comment]
Now - I am quite surprised to see this but I found a work around for it. 

I pulled the latest version of sitespeed and created an additional tag for it, like : 

docker tag sitespeedio/sitespeed.io <temp_tag>

Since I did this, i can see the image intact and I am able to use it for multiple tests. I have no idea how it worked, but IT WORKED, is all I can say as of now!

**Comment by beenanner** [comment]
@ganeshmuralidhar what's your OS and docker version could you attach the output of the following just out of curiosity? 

`uname -a`
`docker -v`
`docker system info`

**Comment by ganeshmuralidhar** [comment]
hello @beenanner ,

If that helps in anyway to get rid of this work around i mentioned above, here it is:

[root@xxxxxxxxx ~]# uname -a
Linux xxxxxxxx.xxxxxxxx.com 3.10.0-327.36.2.el7.x86_64 #1 SMP Mon Oct 10 23:08:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@xxxxxxxxx ~]# docker -v
Docker version 1.12.0, build 8eab29e

[root@xxxxxxxxx~]# docker system info
docker: 'system' is not a docker command.
See 'docker --help'

**Comment by beenanner** [comment]
Cool thanks @ganeshmuralidhar. Do you have the ability to upgrade Docker? Docker 1.12 is fairly old  which is why that 3rd command does not work. ;-) Alternatively for the 3rd command for 1.12 you can run `docker info` instead.

**Comment by soulgalore** [comment]
Closing this since I think upgrade Docker is fixing the issue.
