### ISSUE TITLE
Feature request - CLI - load file over http for urls

### ISSUE THREAD

**Issue by lbod** [sitespeedio/sitespeed.io#1844]
I'd tried/hacked this a couple of weeks ago and it seemed straightforward but is it worth allowing loading a file of urls over http (as compared to currently only node.Path filesystem)? 

I don't actually need this feature now but it seemed useful at the time.
Discussion might be needed on the current command lines options e.g. https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli/util.js#L12

Just an example but where the discussion would be re cli options.

    sitespeed.js remotefile=http://www.sitespeed.io/urls.txt

If it's something useful I'll submit a PR

**Comment by lbod** [comment]
@beenanner I don't think there's much support for this so I'm fine if it's closed unless you think otherwise. We ended up syncing the files from S3 which probably makes more sense.

**Comment by beenanner** [comment]
Yep @lbod we do the same at my work and have just started working on using something like Ansible with Jenkins to deploy new changes out to the boxes when needed. I'll close for now. Thanks for reaching out.
