### ISSUE TITLE
Metrics listing doesn't work in 6.0.0 - 6.0.3

### ISSUE THREAD

**Issue by suratovvlad** [sitespeedio/sitespeed.io#1850]
Hi,

I've found that "--metrics.list" parameter doesn't work in new release 6.0.x., last working version is 5.6.5.
I'm expecting "data" folder with file metrics.txt in "./sitespeed-result/www.sitespeed.io/*/data/metrics.txt",
however, there is no "data" folder in output. Also `find ./ -iname metrics.txt` diplays nothing.

The command that I'm using to reproduce the bug:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.0.3 http://www.sitespeed.io -n 1 --metrics.list`

Please, could you check it and fix the documentation or the issue?

**Comment by soulgalore** [comment]
Hi @suratovvlad thanks for reporting, it's a bug, us fix that and roll it out tomorrow.

Best
Peter

**Comment by suratovvlad** [comment]
Hi @soulgalore! Wow, I'm glad to see how fast you fix the bugs! You are amazing, thank you!

**Comment by soulgalore** [comment]
Thanks, well it was me that caused the bug, so I should fix it :) Let me roll it out tomorrow, got one PR that I think we should include.

**Comment by soulgalore** [comment]
released in 6.1
