### ISSUE TITLE
Metrics list command doesn't work

### ISSUE THREAD

**Issue by wcarle** [sitespeedio/sitespeed.io#1852]
The metrics list commands don't seem to work:
--metrics.list
--metrics.filterList
It says a metrics.txt file will be put in the data directory of the results but nothing is there.

I've tried both docker and locally installed instances on the latest version:
<img width="1036" alt="screen shot 2017-12-11 at 2 52 28 pm" src="https://user-images.githubusercontent.com/2293692/33858000-f95b9480-de82-11e7-8d62-45583e8f4b68.png">

**Comment by wcarle** [comment]
Interestingly when I pulled the the git project directly it seems to work so I'm guessing the fix just hasn't made it to the official release yet

**Comment by soulgalore** [comment]
@wcarle yes I just pushed the fix, it was reported earlier today: https://github.com/sitespeedio/sitespeed.io/issues/1850 - I'll release it during the day tomorrow.

**Comment by wcarle** [comment]
Ah perfect thanks!
