### ISSUE TITLE
Add webpagetest port argument for docker run command

### ISSUE THREAD

**Issue by serputko** [sitespeedio/sitespeed.io#1855]
Hi guys,
i'll try to describe my case and maybe you can help me with some advice.
I have few containers (all of them are in one docker network):
- jenkins
- webpagetest server
- graphite

I run sitespeed.io container from jenkins with: 
`docker run --network=graphite ... sitespeedio/sitespeed.io --graphite.host graphite--graphite.port 2003 --graphite.httpPort 80  --webpagetest.host wptserver --webpagetest.location Test --webpagetest.runs 1 --browsertime.iterations $run_number $URL`

I use --network=graphite to have access to my containers network. Test is run successfully but link to  WebPageTest report looks like http://wptserver/results.php?test=test_id and my host's browser can't get access to wptserver.
I thought it could be possible to view report if i would run sitespeed container with:
`docker run --network=host ... sitespeedio/sitespeed.io --graphite.host localhost --graphite.port 2003 --graphite.httpPort 8080 --webpagetest.host localhost --webpagetest.location Test --webpagetest.runs 1 $URL`
Sitespeed.io would use host network and could get access to all docker containers via exposed ports, but in webpagetest case sitespeed io has no webpagetest port argument and 80 host port would be used. I don't want to use default http port for this.
Could you suggest me how to deal with this or maybe it is possible to add parameter like --webpagetest.host for docker run command?
Many thanks!

**Comment by soulgalore** [comment]
Hi @serputko  hmm yes the current version just treat the host as URL. Do I understand correctly that everything works (WebPageTest runs the tests, you get the data to Graphite) except that the URLs in the sitespeed.io report is wrong?

I think we actually get that link from the WebPageTest JSON (we don't create it on our side), so I think it is something that needs to be fixed there, but I need to have a look.

Best
Peter

**Comment by soulgalore** [comment]
Closing this since we never heard back, but please ping the issue again if you still have the issue so we can help you!
