### ISSUE TITLE
404 when running "npm install"

### ISSUE THREAD

**Issue by chipitsine** [sitespeedio/sitespeed.io#1866]
I cloned the repo, after "npm install" ...

```
npm ERR! code E404
npm ERR! 404 Not Found: read-all-stream@https://registry.npmjs.org/read-all-stream/-/read-all-stream-3.1.0.tgz
```

**Comment by soulgalore** [comment]
Hi @chipitsine could it be a temporary npm glitch? I tried on a fresh checkout on my Mac and it worked for me.

```
$ npm --version
5.4.2
```

Best
Peter

**Comment by chipitsine** [comment]
it was something with my local npm.

I could get it working later
