### ISSUE TITLE
aliased binaries do not work

### ISSUE THREAD

**Issue by DanielRuf** [sitespeedio/sitespeed.io#1882]
With

```
"scripts": {
    "sitespeed.io": "sitespeed.io",
    "browsertime": "browsertime",
    "pagexray ": "pagexray",
    "webcoach ": "webcoach"
  },
```

`npm run browsertime -- --help` works

`npm run webcoach -- --help` does not work

Windos 10, Node.js 8 with npm 5

**Comment by soulgalore** [comment]
Hey @DanielRuf yes, maybe you can help us out, we [recommend](https://www.sitespeed.io/documentation/sitespeed.io/installation/#windows-1) using Docker on Windows but if you could find/know what's wrong and fix it, it would be nice.

Thanks 
Peter

**Comment by DanielRuf** [comment]
I might take a closer look this week or at the weekend.

**Comment by soulgalore** [comment]
Closing since there hasn't been any activity for so long time.
