### ISSUE TITLE
sitespeed-result(s)

### ISSUE THREAD

**Issue by DanielRuf** [sitespeedio/sitespeed.io#1883]
Shouldn't it be `sitespeed-results` instead of `sitespeed-result`?

**Comment by soulgalore** [comment]
Yeah, if you run more than once :) Let us keep it like it is and maybe maybe change it in the future.

**Comment by DanielRuf** [comment]
Mh, even after running the same command multiple times the directory is still called `sitespeed-result`. So actually this is not how you describe it. Is it in an upcoming release?

**Comment by soulgalore** [comment]
@DanielRuf ah sorry, I tried to be ironic that running it once, the name is probably ok. I think we need to keep it **sitespeed-result** for compatibility reasons.

**Comment by DanielRuf** [comment]
Right. Because the sitespeed plugins use the plural form `results`.

Ok. Thanks for taking the time.
