### ISSUE TITLE
Using sitespeed.io on Raspbian

### ISSUE THREAD

**Issue by LorisWouep** [sitespeedio/sitespeed.io#1886]
Hi ! I am trying to use sitespeed.io on a Raspberry Pi 2 with the Raspbian disto. Is there a solution for running sitespeed.io with an ARM architecture ?

Thanks !

**Comment by soulgalore** [comment]
Hi @LorisWouep I the Raspberry Pi will be have too many restrictions (CPU/Memory) for Chrome/FF to work, but I think you could use the Raspberry Pi to drive Android instances? So like you have NodeJS and adbkit on your device with sitespeed.io and collect the metrics using your phone. 
Let me know if you try it out :)

Best
Peter

**Comment by LorisWouep** [comment]
Thank you so much @soulgalore for your reply !
Your solution with the phone looks great but before I really like to try with a Raspberry alone (I'm stubborn ...).
I think the problem is just the Chrome driver does not exist under ARM

```
pi@wouab-cli:~/sitespeed $ git clone https://github.com/sitespeedio/sitespeed.io.git
Clonage dans 'sitespeed.io'...
remote: Counting objects: 27117, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 27117 (delta 48), reused 60 (delta 26), pack-reused 27015
Réception d'objets: 100% (27117/27117), 267.75 MiB | 999.00 KiB/s, fait.
Résolution des deltas: 100% (17546/17546), fait.
pi@wouab-cli:~/sitespeed $ cd sitespeed.io
pi@wouab-cli:~/sitespeed/sitespeed.io $ npm install

> sleep@3.0.1 install /home/pi/sitespeed/sitespeed.io/node_modules/sleep
> node-gyp rebuild

make : on entre dans le répertoire « /home/pi/sitespeed/sitespeed.io/node_modules/sleep/build »
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make : on quitte le répertoire « /home/pi/sitespeed/sitespeed.io/node_modules/sleep/build »

> alto-saxophone@2.34.0 install /home/pi/sitespeed/sitespeed.io/node_modules/alto-saxophone
> node install.js


/home/pi/sitespeed/sitespeed.io/node_modules/alto-saxophone/install.js:33
        throw err;
        ^
HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/pi/sitespeed/sitespeed.io/node_modules/got/index.js:197:24)
    at EventEmitter.emit (events.js:160:13)
    at Immediate.<anonymous> (/home/pi/sitespeed/sitespeed.io/node_modules/got/index.js:63:8)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alto-saxophone@2.34.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alto-saxophone@2.34.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-01-19T09_27_16_187Z-debug.log
 ```

I also tried with npm and yarn ... i get the same error.

Best
Loris

**Comment by soulgalore** [comment]
Ah I see, ok, there's no way to run the official build then except to hack it, but it will be the same way for Geckodriver I guess? Or is the download picking the wrong one? If you have time you can checkout the implementation here https://github.com/tobli/alto-saxophone and help us if you have ideas how to fix it.

Best
Peter

**Comment by soulgalore** [comment]
I've spent a lot of time trying to get Browsertime to work on Raspberry PI in Docker but at the moment the miss match in ADB/ Chromedriver/Chrome on ARM was really annoying. When Chrome starts to ship again on ARM, we can create a new issue.
