### ISSUE TITLE
Process Data from Previous Run

### ISSUE THREAD

**Issue by enummela** [sitespeedio/sitespeed.io#1887]
Is it possible to process data after a run has already been completed? I ask because sometimes a test will end prematurely and no HTML report will have been generated in that case. For tests that take a long time to run this can result in a significant setback.

I noticed that test data for each page is stored on disk during the run. These include `browsertime.har`, `screenshots/` and `videos/`. I'm curious if there's a simple way to generate HTML reports from this data? It would be much faster than rerunning all of the tests.

**Comment by soulgalore** [comment]
Hi @enummela I think we should try to fix the original issues. If you could create new issues with trace logs when it happens (the test ends prematurely and you don't get the result) that would be super! 

We've been trying to make sure we catch most cases so only that URL would be affected but apparently we have some cases we missed.

Thanks
Peter

**Comment by enummela** [comment]
Thankfully none of my runs have been disrupted since I pulled the latest Docker image. I was curious about this because I have data from runs using an older image that ended prematurely, but I will just run the tests again.

Thanks for the reply Peter
