### ISSUE TITLE
is XVFB mandatory?

### ISSUE THREAD

**Issue by anandsourabh** [sitespeedio/sitespeed.io#1888]
Hi, This is more of a question that an issue.
I have set up sitespeed using npm module in RHEL 7.
However when I execute test on one of the servers, I get the following error:

2018-01-18-12-55-13]$ [2018-01-18 12:57:14] ERROR: https://www.americanexpress.com generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch.e (/home/user/.npm-global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:93:15)
From previous event:
    at SeleniumRunner.start (/home/user/.npm-global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:92:13)
From previous event:
    at runIteration (/home/user/.npm-global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:229:10)
    at Promise.reduce (/home/user/.npm-global/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/cor

While I am going to try various recommendations such as running selenium server externally, add no-sandbox arguments etc. I wanted to confirm if XVFB configuration is mandatory when chrome is running in a headless mode?

Docker is not an option as of now for us.

**Comment by soulgalore** [comment]
Hi @anandsourabh 
so do you run in Chrome headless (—browsertime.headless) or you mean headless with xvfb? I you run Chrome headless you can do it without xvfb but you will miss some functionality as video, speedIndex and running Browser extensions (that enables basic auth, extra request headers etc).

Can you share how you run (the exact parameters)?

Best
Peter

**Comment by anandsourabh** [comment]
This is the command:

sitespeed.io $URL --influxdb.host $INFLUX_HOST --influxdb.port $INFLUX_PORT --influxdb.database INFLUX_DB --browsertime.chrome.args headless --browsertime.chrome.args  no-sandbox --connectivity 3g  -n 5

I do not have xvfb server running as of now.

**Comment by soulgalore** [comment]
Headless in Browsertime is not only Chrome so you can use the generic version (check the options: https://www.sitespeed.io/documentation/browsertime/configuration/#the-options), then Browsertime will add the extra parameters needed for turning on headless. So change `--browsertime.chrome.args headless 
` to `--browsertime.headless ` and I hope it will work.

**Comment by anandsourabh** [comment]
Thanks a lot @soulgalore. The browsertime.headless option worked for me. Working for all except visual metrics etc.

Getting xvfb enabled on enterprise grade servers is a bit tough at my end. Trying my best to get this enabled soon.

Thanks again!
