### ISSUE TITLE
Testing local site with docker

### ISSUE THREAD

**Issue by ti2m** [sitespeedio/sitespeed.io#1889]
Hi,

thanks for the great work! I'm using sitespeed for some time now and it is a great help! I'm having an issue though with testing my local site that I can't resolve on my own.
The documentation states to use 192.168.65.1 to test local sites. As I'm testing a local site (OSX Sierra) with a vhost I used to run docker with `--add-host=mysite.local:192.168.65.1` which worked great in the past. This stopped working with one of the last docker updates as the fixed IP is not available anymore as also stated here https://github.com/docker/for-mac/issues/2373#issuecomment-356014608

If I resolve `docker.for.mac.localhost` within the docker container I get 192.168.65.2. I could automated the resolving later on but wanted to test first with this IP. Using `--add-host` with this IP doesn't seem to work for the browsers though. It does get added correctly to `/etc/hosts` and I can run `curl` against my local site and get the HTML back, but neither chrome nor firefox are able to reach the site. I always get:

```
Google Chrome 63.0.3239.84 
Mozilla Firefox 54.0.1
[2018-01-19 15:11:24] INFO: Versions OS: linux 4.9.60-linuxkit-aufs nodejs: v8.9.1 sitespeed.io: 6.2.3 browsertime: 2.1.2 coach: 1.1.2
[2018-01-19 15:11:25] INFO: Starting chrome for analysing http://mysite.local/ 1 time(s)
[2018-01-19 15:11:25] INFO: Testing url http://mysite.local/ run 1
[2018-01-19 15:11:27] ERROR: Could not load URLUrlLoadError: Failed to load http://mysite.local/
[2018-01-19 15:11:28] ERROR: http://mysite.local/ generated the following error in Browsertime UrlLoadError: Failed to load http://mysite.local/
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:176:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:174:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:250:27)
............        
```
Any clue why this is happening? Are chrome and firefox both ignore `/etc/hosts` in the latest version? Don't really think that is the case, but not sure why else the browsers aren't picking up on it. Running sitespeed against remote sites work fine. 

I would appreciate any hints.

**Comment by soulgalore** [comment]
Thanks @ti2m for making the issue, I've seen that they have changed it in Docker but I didn't know that the old solution stopped working, let see if I or @beenanner can have a go this weekend and see if we understand how it can be done.

Best
Peter

**Comment by soulgalore** [comment]
Hi @ti2m had a quick test and using http://docker.for.mac.localhost:4000 isn't working for me but if I get the IP with: 
```
docker run -it alpine nslookup docker.for.mac.localhost
nslookup: can't resolve '(null)': Name does not resolve
Name:      docker.for.mac.localhost
Address 1: 192.168.65.2
```
and then test against the ip (without doing any change and my test site is on port 4000):
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 1 http://192.168.65.2:4000`

it worked for me. Does that work for you? @beenanner do you know a way of not doing the lookup first?

Best
Peter

**Comment by soulgalore** [comment]
And I'm running: _Version 17.12.0-ce-mac49 (21995)_

**Comment by ti2m** [comment]
Hi @soulgalore, thanks for your quick reply!

While looking at it this morning I saw that I was being stupid. I had to change my local setup to move from .dev to another domain to allow http connections in chrome and something went wrong their. Sorry about that, but maybe we can solve the IP issue anyway as it might help others. 

Good news is that 192.168.65.2 now works for me as 192.168.65.1 did before. From my point of view the command to figure out the IP could just be added to the docs. 
An option for automatically resolving it would be to add e.g. `sitespeed-host.local` at startup to `/etc/hosts`, then everyone could use `sitespeed-host.local:4000` when starting the container to reach the host. As sitespeed always uses the same container one way of resolving `docker.for.mac.localhost` is fine as it doesn't have to respect all different kind of containers as mentioned here https://unix.stackexchange.com/questions/392992/universal-way-to-check-if-docker-for-mac-localhost-dns-name-is-resolvable

As said, providing a command in the docs for people to find out the correct IP would also be enough and it might even be more helpful for people with a vhost setup like me as they understand how to adjust the setup. I now run the command in the container and then add the IP/domain mapping via the `--add-host` argument.

**Comment by beenanner** [comment]
@ti2m sorry for being late to the party you could run sitespeed.io using the `--net=host` option if you are running some other site not in docker. It should then just you your mac's /etc/hosts file.

`docker run --net=host --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 1 http://mysite.local:4000`

**Comment by soulgalore** [comment]
@beenanner I don't get the net-host to work for me. I always get a couple of `sudo: unable to resolve host linuxkit-025000000001` errors.

**Comment by ti2m** [comment]
@beenanner Also tried the net-host option, but I don't get it to work either.

**Comment by ti2m** [comment]
@soulgalore Docs update looks good to me and solves this issue from my point of view. Thanks!

**Comment by beenanner** [comment]
Are you guys on High Sierra? I tested it over the weekend and it seemed to work for me, but I wasn't using a .local domain. I'll test some more but glad there is a workaround for now.

**Comment by soulgalore** [comment]
Could be that I missed to name it .local, let me try that.

**Comment by beenanner** [comment]
I'm on High Sierra and using Docker for Mac Edge (18.01) too.

**Comment by soulgalore** [comment]
Yep also on High Sierra, ah I see now, yep also used a .local :)

**Comment by SoreGums** [comment]
this looks like my issue - however following along I can't figure out how to apply it.

I'm combined the https://github.com/wodby/docker4wordpress & sitespeed docker-compose.yml files to have one stack. 

So if I want to run the test, I need the host header to be set to wp.docker.localhost and for it to go connect to the traefik container on port 8000. the site is at http://wp.docker.localhost:8000 from the host machine.

Maybe this not an ideal way to do it and should run two stacks - still then I'd need http://wp.docker.localhost:8000 to hit the host and from above I don't follow how to get the correct IP to sitespeed container  :/

**Comment by soulgalore** [comment]
Following https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost should just work.
