### ISSUE TITLE
The test URL with '&' char will be removed from query parameters

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#1890]
Hi, Peter et al,
we are testing the page URL with serveral query parameters, for example in following:

Test Sample to reproduce the issue: 
$ sudo docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.2.3 -b chrome -n 2 **https://donate.wikimedia.org/w/index.php?title=Special:LandingPage&country=CN&uselang=en**

The final result for the test url will be https://donate.wikimedia.org/w/index.php?title=Special:LandingPage , which is not the right page we are testing with the other query parameters removed.

Meanwhile, seems the sitespeed docker instance does not exit properly, have to 'Ctrl-C' to exit the process. If there is no query parameter or just one param, it will be exited correctly..

Please advice! Thanks very much!

**Comment by soulgalore** [comment]
Hi @joychester running Linux you need to make sure that & is part of the URL, meaning give it as a String:

`sudo docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.2.3 -b chrome -n 2 "https://donate.wikimedia.org/w/index.php?title=Special:LandingPage&country=CN&uselang=en"`

Else it will start a new process.

Best
Peter

**Comment by joychester** [comment]
That works!! Thanks Peter for the advice!
