### ISSUE TITLE
Update Ubuntu 17.04 docker image 

### ISSUE THREAD

**Issue by suratovvlad** [sitespeedio/sitespeed.io#1891]
Hi!

I've faced with problems, using your image sitespeedio/sitespeed.io:6.2.3 as the base for my image.
I'm using the 'apt update' command and several days ago it fails due to end of limetime ([Re: apt-get update failing on 17.04](https://ubuntuforums.org/showthread.php?t=2382832&p=13731536#post13731536))

Could you change in the next iteration the base image to 17.10 or to the current LTS release

**Comment by soulgalore** [comment]
thanks @suratovvlad let us fix that for the next release.

**Comment by suratovvlad** [comment]
@soulgalore Thanks a lot!

**Comment by soulgalore** [comment]
Pushed in 6.3.0
