### ISSUE TITLE
Run Webpagetest basic auth using dockerized sitespeed

### ISSUE THREAD

**Issue by bharat129** [sitespeedio/sitespeed.io#1892]
Hi @soulgalore ,

I am running Webpagetest using sitespeed, I am able to do it on a website with no basic auth. But when I am trying to run WPT on site with basic auth, it does not work since I could not find any config how to run webpagetest with basic auth.

**command to run:**

docker-compose -f /www/sitespeed/docker-compose.yml run -v /www/sitespeed:/sitespeed.io sitespeed.io https://xxx.xxx.com/ --webpagetest.key=<WPT_key> --webpagetest.runs=1 --webpagetest.location=Toronto:Chrome --graphite.host=graphite

Can you please let me know how to modify this command for basic auth?

**Comment by soulgalore** [comment]
Hi @bharat129 we use the WebPageTest API (read more on how we use it here https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#configuration) and pass on all configuration. If you check https://github.com/marcelduran/webpagetest-api#test-works-for-test-command-only it looks like _--webpagetest.login_ and _--webpagetest.password_ should do the trick!

All the best 
Peter

**Comment by bharat129** [comment]
Thanks @soulgalore , WPT is running now after adding your suggested options.

But the command also trigger sitespeed run. Do we have any configuration available which can disable sitespeed run during webpagetest run?

I have separate command to run sitespeed, don't want extra overhead on the server.

**Comment by soulgalore** [comment]
Do you mean to disable getting metrics using Browsertime? https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#run-webpagetest-without-browsertime

**Comment by bharat129** [comment]
Thanks again @soulgalore , But **--plugins.remove=browsertime** only did not work, I also had to put **--speedIndex=false** in my WPT command

**Comment by soulgalore** [comment]
Hm what version of sitespeed.io do you use, are you on 6.x? That's how you should do to disable plugins.

**Comment by soulgalore** [comment]
Didn't get any feedback in this, disabling browsretime should work. Please show exactly how you run so we can reproduce.
