### ISSUE TITLE
WPT plugin to support the medianMetric param

### ISSUE THREAD

**Issue by siteriaitaliana** [sitespeedio/sitespeed.io#1894]
As from https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis the default metric to use when calculating the median run is the loadTime, which is not very accurate for modern PWA... the SpeedIndex would be much more meaningful there.

We should fetch median run results based on that, possibly by letting users specify the medianMetric strategy.

**Comment by soulgalore** [comment]
Hi @siteriaitaliana yes we support all setting the [WebPageTest API](https://github.com/marcelduran/webpagetest-api), it's more up to the user to use it by setting **--webpagetest.median** and **--webpagetest.medianrun**.

Best
Peter

**Comment by soulgalore** [comment]
Also see https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#configuration

**Comment by soulgalore** [comment]
Already supported through the WPT API.
