### ISSUE TITLE
Running sitespeed on Heroku (using a Docker container)

### ISSUE THREAD

**Issue by shrej** [sitespeedio/sitespeed.io#1895]
Hello,

I am trying to run sitespeed.io using docker on Heroku. I have a heroku.yml file which looks like this:
`build:
   docker:
    worker: Dockerfile
`
I modified the Docker file to include the following line at the end:
`CMD docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.2.3 https://www.google.com`

I however see the following user permission issue:

**State changed from starting to crashed 
State changed from crashed to starting 
Google Chrome 63.0.3239.132  
Process exited with status 1 
Mozilla Firefox 54.0.1 
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set**

 It is not possible to run as root user on Heroku. Is it possible to use the existing Dockerfile on Heroku ?

**Comment by soulgalore** [comment]
Hi @shrej what kind of instance do you run on Heroku? Could it be memory issues? I've never tried on Heroku, think others work can disturb the instance, but I can be wrong. If you got it working, please let us know!

Best
Peter

**Comment by shrej** [comment]
Hi @soulgalore ! You are right. It is indeed a memory issue. I am currently using a dyno with only 512 MB RAM. 

![image](https://user-images.githubusercontent.com/12212922/35572831-82d9bab0-05a3-11e8-964f-5b82cc88a059.png)

Do you have any suggestions to make the process use less memory ? 
I will let you know if I can make it to work. 

Thanks!

**Comment by soulgalore** [comment]
@shrej Chrome and Firefox eats memory. When we run on AWS we use a c4.large instance (3.75GB memory).

Best
Peter

**Comment by shrej** [comment]
Thanks @soulgalore ! Closing this issue as it is related to memory usage. I will keep you updated if we still decide to use Heroku.

Best,
Shrey
