### ISSUE TITLE
--browsertime.requestheader (-r) option does not work correctly using Docker cmd

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#1896]
Hi, Peter
I am trying to add custom request headers to my page tests:

> docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.2.3 https://www.sitespeed.io/ -n 1 -b chrome --gzipHAR true --browsertime.requestheader testheader=123

I did not find my custom header in Har file. Please advice if I am using it correctly, or it is an issue here. 

Thanks!

**Comment by soulgalore** [comment]
Hi @joychester sorry I think we are missing docs (and the CLI is missing it too). Separate the key/value by a : 
`--requestheader hepp:hepp`

Best
Peter

**Comment by joychester** [comment]
Thank you @soulgalore for the tip!! it works well 👍 
seems you mentioned here on how to use the -r option : https://github.com/sitespeedio/sitespeed.io/blob/698438863ced48fd04a195e35f3b1a47d7cbbfad/docs/_posts/2017-04-24-sitespeed.io-5.0.md

Hope you can add this to the configuration list as an example for people reference!

**Comment by soulgalore** [comment]
Yep, I've added it to the CLI so it will go out in the next release, sorry that we missed that!

**Comment by Sudeep05** [comment]
@soulgalore , I'm unable to do the same thing as above to add custom headers during browsetime with my js file, when i add -r in my command it throws null and unable to add text where I'm trying to add some data to Textbox but whereas when i remove my Header , it works.

I'm using below command.
docker run --cap-add=NET_ADMIN --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.1.0-plus1 Test.js --multi -c lte --browsertime.connectivity.engine=throttle  -n 1 --graphite.host=x.x.x.x  --graphite.port=2001 --requestheader ByPassReCaptcha:1677590802609 --slug Test_Demo --graphite.addSlugToKey true
