### ISSUE TITLE
Does the upgrade to 6.x from 5.x double run times?

### ISSUE THREAD

**Issue by lbod** [sitespeedio/sitespeed.io#1901]
We're in process of moving from a single VM on one cloud platform to using AWS ECS, we also upgraded from 5.x to 6.3.1. What we're seeing is the same jobs we run on the current VM we use take twice as long to run on ECS. Video, html and screenshots are removed/disabled.  Being new to ECS I've tried to alter container memory and cpu settings and it hasn't made much difference. 

I downgraded back to 5.x on ECS and the runs were twice as fast. I understand that video is on by default now, so I tried enabling it to make sure there wasn't something wrong with my config, as expected it took slightly longer.

I need to enable verbose logging again and have a look though but was there expected longer runtimes of sitespeed (we're not crawling, feeding it a list of urls)?

**Comment by soulgalore** [comment]
Hi @lbod and you run our default Docker containers? Yep only change I can think of is that video is running by default but you can see that in the default log _...speedIndex: 471 (±94.76), visualComplete85: 489ms (±98.40ms), lastVisualChange: 489ms (±98.40ms) ..._ ?

Best
Peter

**Comment by lbod** [comment]
@soulgalore , yes only the default containers. I need to 100% check the logs again and verbose them but don't have access atm. Would you expect that to double the time? 
I had run with and without the `--video,false` args and for the same 10 pages it was a couple of minutes faster when video was removed. I've been taking notes of run times for different configs.
Thanks

**Comment by soulgalore** [comment]
Yep, the video is post processed after each run and that takes extra time, I don't know how much but it is slower.

**Comment by lbod** [comment]
I eventually saw the documentation re setting **both video and speedIndex to false**, once I did that the timings were more or less the same. We're obviously missing out on visual metrics but I was just concerned I was missing something in comparison, which I was

**Comment by lbod** [comment]
Sorry I need to reopen again. We've been doing quite a bit of testing on ECS now and trying to size according to needs. 
Our longest run is 96 pages but the difference in runtimes between 6.1.3 and 5.4.3 is massive and it appears it's somewhere around the html plugin from the logs I see. 
The actual crawl time seems to take the same time now but the time spent between `Render HTML for %s page(s)` and `HTML stored in %s` is where that extra time is coming from.

e.g. on 5.4.3

```
11:17:33 - 11:54:24 (36:57 mins) Total runtime
11:53:09 - 11:54:04 HTML storage time
```

on 6.1.3 (with video and speedindex disabled)


```
16:00:37 - 17:18:34 (1hr:17:57) Total runtime
16:36:25 - 17:18:20 HTML storage time
```

or another run today with 6.1.3:

```
[2018-02-07 13:15:12] DEBUG: [sitespeedio.plugin.html] Render HTML for 94 page(s)
[2018-02-07 13:51:38] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-results
```

The html plugin time is doubling the time for this run.

I did a diff between 6.x and 5.x what the changes were to the HTML plugin but there's too many to see anything obvious, big changes since 5.x. I also pumped up logging but there's nothing logged in between.
Is there an obvious reason why the html plugin would take so much longer now?

**Comment by soulgalore** [comment]
I wonder if we can have lost rendering the pages in parallel? Need to look into to know more.

**Comment by soulgalore** [comment]
By the why how much memory do you have on that instance @lbod ?

**Comment by soulgalore** [comment]
And how many runs do you do per URL?

**Comment by lbod** [comment]
@soulgalore it's 94 pages * 4 runs and we've something like 3.8gb assigned to the ECS container.

We've been watching cpu/memory/throughput etc and we don't think there's anything crazy happening, though we could be wrong

**Comment by soulgalore** [comment]
Thanks, we'll look into it the coming days.

**Comment by soulgalore** [comment]
Hi @lbod can you build from master (clone the repo, build the docker container, checkout how we do in release.sh) ? I did to things this morning, first I added debug logging so each HTML step is logged (enable by add -v to your run) and then I reduced the number of merges (that was introduced in 6) at least when I tried on pages with a lot of data that reduced the time to generate the HTML. We can do more things, but if you can try this first that would be great.

**Comment by lbod** [comment]
Thanks @soulgalore I'll give it a try but at work and have to run over very slow wifi. I might have to leave it till later when I'm at home.

**Comment by soulgalore** [comment]
Let us merge https://github.com/sitespeedio/sitespeed.io/pull/1910 first, I'm pretty sure it will solve most of the problems.

**Comment by soulgalore** [comment]
@lbod pushed 6.3.3 with more fixes, best case it will be faster than 5.x, please let us know when you had time to test it. thanks!

**Comment by lbod** [comment]
@soulgalore thanks so much, we're testing it now

**Comment by lbod** [comment]
Massive thanks @soulgalore and the turnaround impressive. 

```
[2018-02-08 16:10:52] DEBUG: [sitespeedio.plugin.html] Render HTML for 94 page(s)
[2018-02-08 16:11:02] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-results

```

Obviously I've left out all the html rendering logs but html rendering is down to seconds now!

**Comment by soulgalore** [comment]
Good! When we introduced tabs for plugins (you can let your own plugin have your own tab) we accidentally made it slower without noticing by copying a lot of data.

**Comment by lbod** [comment]
Working as expected now so closing
