### ISSUE TITLE
Webpagetest runs using sitespeed throwing timeout errors

### ISSUE THREAD

**Issue by bharat129** [sitespeedio/sitespeed.io#1902]
Hello @soulgalore ,

I am getting below time out error while running WPT using sitespeed. 

`[2018-02-03 17:27:17] ERROR: Error creating WebPageTest result  {"error":{"code":"TIMEOUT","testId":"<testID>","message":"timeout"}}`

Docker-compose command to run sitespeed:
`/usr/local/bin/docker-compose -f /www/sitespeed/docker-compose.yml run -v /www/sitespeed:/sitespeed.io sitespeed.io URLs.txt  --webpagetest.key=<WPT-key> --webpagetest.runs=3 --webpagetest.location=Toronto:Chrome --plugins.remove=browsertime --speedIndex=false  --graphite.host=graphite`

out of 14 URLs, I get response for 6 but other 8 gets timeout.

Do we have any config from which I can stop these runs to getting timed out?

**Comment by soulgalore** [comment]
The default timeout is 600 seconds, you can change it with --webpagetest.timeout , if you are using WebPageTest.org you should probably setup your own instance.

Best
Peter

**Comment by soulgalore** [comment]
You can read more about the configuration for WebPageTest at https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#configuration
