### ISSUE TITLE
preURL option seems broken in 6.3.1

### ISSUE THREAD

**Issue by aerwin** [sitespeedio/sitespeed.io#1904]
I've noticed that the preURL option seems broken in 6.3.1. Previously, when I was running with 5.4.0 there was a clear difference running with preURL than without. However, with 6.3.1, the results look the same regardless of the preURL value. This will prevent me from being able to use version 6.3.1 in my production tests. Any help would be greatly appreciated!

## With preURL
<img width="1359" alt="screen shot 2018-02-04 at 9 42 19 pm" src="https://user-images.githubusercontent.com/1258743/35787521-6051aa48-09f4-11e8-94cb-b0fb7896080e.png">

Produced with:

```
docker run --privileged --shm-size=512m  --rm -v ~/.nvm/versions/node/v6.9.4/lib/node_modules/@console/bluemix-sitespeed-driver:/sitespeed.io sitespeedio/sitespeed.io:6.3.1 https://console.bluemix.net/catalog/  --preURL https://console.bluemix.net/catalog/ --outputFolder ./sitespeed-result/console.bluemix.net/catalog_NOLOGIN_repeatView
```

## Without preURL
<img width="1373" alt="screen shot 2018-02-04 at 9 44 22 pm" src="https://user-images.githubusercontent.com/1258743/35787548-a5f8e912-09f4-11e8-8ba6-c1071dae3b1f.png">

Produced with:

```
docker run --privileged --shm-size=512m  --rm -v ~/.nvm/versions/node/v6.9.4/lib/node_modules/@console/bluemix-sitespeed-driver:/sitespeed.io sitespeedio/sitespeed.io:6.3.1 https://console.bluemix.net/catalog/ --outputFolder ./sitespeed-result/console.bluemix.net/catalog_NOLOGIN
```

## Using preURL with 5.4.0
Below are the expected results with 5.4.0:

<img width="1027" alt="screen shot 2018-02-04 at 9 52 28 pm" src="https://user-images.githubusercontent.com/1258743/35787716-cd3bdd12-09f5-11e8-9158-b33a65109827.png">

Produced with:

```
docker run --privileged --shm-size=512m  --rm -v ~/.nvm/versions/node/v6.9.4/lib/node_modules/@console/bluemix-sitespeed-driver:/sitespeed.io sitespeedio/sitespeed.io:5.4.0 https://console.bluemix.net/catalog/  --preURL https://console.bluemix.net/catalog/ --outputFolder ./sitespeed-result/console.bluemix.net/catalog_NOLOGIN_repeatView2
```

**Comment by soulgalore** [comment]
Hi @aerwin ah thanks for reporting, the shortcut in the cli seems to have been mystically removed sometimes ago (the base --browsertime.preURL was still working). I didnt have time now to look why, but I added it back and will release it the coming hour.

Best
Peter

**Comment by soulgalore** [comment]
6.3.2 is pushed, the Docker container will be there in -1 minute, thanks again for reporting.

One other thing: I think you don't need to run with --privileged anymore. You needed that before to run Chrome but we now default to use --no-sandbox when you run with Docker, so it should just work with lower privs.
Best
Peter

**Comment by soulgalore** [comment]
great, closing then.
