### ISSUE TITLE
Setting graphite namespace not getting all values

### ISSUE THREAD

**Issue by senthilr2k** [sitespeedio/sitespeed.io#1905]
Hi i am using latest docker version of sitespeed. When i gave a namespace while running i am not getting all values in graphite. But getting all values when i am not giving any namespace. Please advise

**Comment by soulgalore** [comment]
Hi @senthilr2k what Graphite version are you using? By default there's a really low limit of creating new metrics (MAX_CREATES_PER_MINUTE) see point number 6: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#setup-important

If it is that that's the problem, you will see that you will get more metrics the next run.

Best
Peter

**Comment by senthilr2k** [comment]
hi thanks.  i am getting all values when using default  .

**Comment by senthilr2k** [comment]
hi peter,

   i am using a standalone graphite.  not the one inside docker

thanks
senthil r

On 06-Feb-2018 6:41 PM, "Senthil Retnaswamy" <senthil.retnaswamy@gmail.com>
wrote:

hi thanks.  i am getting all values when using default  .

**Comment by senthilr2k** [comment]
Hi Peter,
  I pulled latest version of sitespeed using docker. I have configure graphite outside of docker.  When i used --graphite.namespace to provide a namespace, i am getting very few property values in graphite. But when i removed --graphite.namespace, I was seeing all the values under sitespeed.io/default in graphite.
  I also tried to pull the metrics list using --metrics.list and added those values in --metrics.filter values but still i am not getting all the values. I also tried *+ option inside metrics filter but still no luck. Could you please help here. Got stuck.

**Comment by soulgalore** [comment]
Hi @senthilr2k have you changed the MAX_CREATES_PER_MINUTE on your Graphite instance or is it default (like 50 creates per minutes)? 50 creates means that if we send min/max/median/avg you will get 10 metrics or something like that per run. 

Also you have the storage schema for graphite (dependent on key names) checkout https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#configure-graphite and also read Etsys great docs about configuring Graphite: https://github.com/etsy/statsd/blob/master/docs/graphite.md

Best
Peter

**Comment by senthilr2k** [comment]
Thanks Peter. Worked like charm
