### ISSUE TITLE
Combining prescript and crawl

### ISSUE THREAD

**Issue by sergitorralba** [sitespeedio/sitespeed.io#1920]
I was trying to combine prescript and crawl. But it seems that it tries to crawl before running the prescript.
So if the prescript is to login, when it does the crawl is crawling the login form not the actual page under test.

**Comment by soulgalore** [comment]
Hi @sergitorralba the crawl happens before with a standalone tool (simplecrawler). Right now our impl only supports basic auth but simplecrawler has support for adding cookies see https://github.com/simplecrawler/simplecrawler#cookies and adding request headers (**crawler.customHeaders**) so if you have time to do a PR for adding the headers (we have support for request headers in Browsertime) and you can supply your login status with a header, that would probably work. But we need a PR for that.

Best
Peter

**Comment by sergitorralba** [comment]
Let see if I have time, but thanks anyway!

**Comment by soulgalore** [comment]
Closing this, lets add a new issue for adding a cookie to the crawl if there are someone that needs it :)
