### ISSUE TITLE
Core.xxxxx files are getting generated will running sitespeed.io

### ISSUE THREAD

**Issue by senthilr2k** [sitespeedio/sitespeed.io#1921]
Hi ,
Core.xxxxx files are getting generated will running sitespeed.io in docker. These files are of huge size.

Thanks,
Senthil R

**Comment by soulgalore** [comment]
Hi @senthilr2k thanks for reporting, can you help me out some more, how do you get them and where and what are those? What OS are you using etc. How do I do to reproduce the issue?

Thanks!
Peter

**Comment by soulgalore** [comment]
Closing this since we didn't get any feedback.
