### ISSUE TITLE
setup compare 

### ISSUE THREAD

**Issue by spham** [sitespeedio/sitespeed.io#1930]
Hi
just need help documentation for setup compare view
example : 
https://dashboard.sitespeed.io/d/000000049/compare-performance?orgId=1

**Comment by soulgalore** [comment]
Hi @spham ,
I think this is the one: https://github.com/sitespeedio/grafana-bootstrap-docker/blob/master/dashboards/graphite/CompareBetweenPages.json

Check out if that will help you.
Best
Peter

**Comment by spham** [comment]
i dont get where to setup this file ?

**Comment by soulgalore** [comment]
You can checkout the Grafana docs on how to import dashboards: http://docs.grafana.org/reference/export_import/

**Comment by soulgalore** [comment]
If you use our Docker compose file you can find the info here: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes

**Comment by spham** [comment]
It’s little confusing

**Comment by soulgalore** [comment]
Ok. How do you setup Grafana? Do you use it standalone (then check with Grafana.org for default password), else if you start Grafana using our Docker compose file, the password is in the docker compose file: https://raw.githubusercontent.com/sitespeedio/sitespeed.io/master/docker/docker-compose.yml

**Comment by soulgalore** [comment]
Yep there are fields in that template that is hardcoded:"To make this dashboard work for you, you need to reconfigure the constants (template) sitespeed_io and desktop."

**Comment by spham** [comment]
I see , but i must replace with ?

**Comment by soulgalore** [comment]
Hi @spham so it depends on the configuration when you run? You can configure what Graphite namespace to use with:

`--graphite.namespace           The namespace key added to all captured metrics.                           [default: "sitespeed_io.default"]`

But if you use Grafana and the query editor, you can see what data you have in Graphite and then choose which one you wanna use. You can checkout the docs at Grafana: http://docs.grafana.org/guides/basic_concepts/

**Comment by spham** [comment]
hum, i use default docker + grafana.
but it's not clear.
have you an example with screenshot ?

**Comment by spham** [comment]
how to  reconfigure the constants (template) sitespeed_io and desktop when use default docker and graphite

**Comment by soulgalore** [comment]
This is Grafana issues, I think you best find them at Grafana. This is how you use templates etc: http://docs.grafana.org/reference/templating/

**Comment by spham** [comment]
i dont think is grafana issue, but it's how to use with sitespeed

**Comment by spham** [comment]
ok dont matter :-(
