### ISSUE TITLE
How to complete a test without waiting load event

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/sitespeed.io#1939]
Is there a way to start computing values without waiting load event which might be stuck downloading an asset it beacon. I am looking at a timeout value if load event doesn't fire for example 10 sec

**Comment by soulgalore** [comment]
Hi @tufandevrim at the moment we use the default pageLoadStrategies for Selenium/WebDriver meaning that we get back in control after the loadEventEnd has fired. We have an old issue to change that see https://github.com/sitespeedio/browsertime/issues/186 but when I looked at it a year ago (or two) Firefox/Chrome didn't support it.

But now it seems like Geckodriver (for Firefox) has implemented it: https://github.com/mozilla/geckodriver#webdriver-capabilities

And I think maybe also Chromedriver implements it so let me have a look next week and implement it in the coming 3.0 of Browsertime. It will work like this: You will set the load time strategy and then you need to supply the pageCompleteCheck that will run in the browser and choose when to end the test.

Best
Peter

**Comment by soulgalore** [comment]
It turns out both Chrome and Firefox supports it now! I've made a PR to Browsertime https://github.com/sitespeedio/browsertime/pull/501 but that is for next major version coming later this year (a couple of months maybe).

**Comment by tufandevrim** [comment]
Thanks @soulgalore. This is great since I get too many timeouts recently due to some assets stuck and  doesn't load for 2 mins and my tests timeouts. I see following error:

![screen shot 2018-03-16 at 10 34 14 am](https://user-images.githubusercontent.com/1676189/37611415-7efa26be-2b5f-11e8-8624-230ecd883415.png)

So I am assuming this is happening because the onload event didn't fire in 60 sec, right? If it is, is there any config to increase it?

**Comment by soulgalore** [comment]
@tufandevrim no that is another error: it is (usually) Chrome that don't start. @vgoncharenko has a fix for that (Chrome leaves some processed behind), I was thinking to push that to Browsertime 3.0 but can add it to the current version (https://github.com/sitespeedio/sitespeed.io/pull/1924/files)

**Comment by tufandevrim** [comment]
Yes please add this current version and so I can use the docker version right away to fix the problem we're experiencing

**Comment by tufandevrim** [comment]
> @tufandevrim no that is another error: it is (usually) Chrome that don't start. @vgoncharenko has a fix for that (Chrome leaves some processed behind), I was thinking to push that to Browsertime 3.0 but can add it to the current version (https://github.com/sitespeedio/sitespeed.io/pull/1924/files)

What version of sitespeed.io has this fix right now?

**Comment by soulgalore** [comment]
@tufandevrim haven't pushed this to sitespeed.io yet, it only exists in coming Browsertime 3.0. The fix is easy but it has been so much other things going on with the problems with the HAR for Firefox and the broken Chrome https://github.com/sitespeedio/browsertime/issues/489

**Comment by soulgalore** [comment]
In 7.0.0 we (right now) run with pageLoadStrategy none = you can end the test whenever you want (you don't need to wait on onLoad). We maybe will change that, but we will always keep --browsertime.pageLoadStrategy to choose between none and normal.

**Comment by soulgalore** [comment]
ping @tufandevrim

**Comment by tufandevrim** [comment]
thank you @soulgalore

**Comment by soulgalore** [comment]
FYI @tufandevrim we rollbacked the change since it caused problems for people using preScripts (#2062). But you can still set it yourself, so `--browsertime.pageLoadStratege none` will do the trick!

**Comment by soulgalore** [comment]
See https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test
