### ISSUE TITLE
How do i send data between servers?

### ISSUE THREAD

**Issue by martijnvanloon** [sitespeedio/sitespeed.io#1954]
I have setup two servers for sitespeed on digitalocean, one for grafana and one to run tests with. I have no idea how to get the resultas from the first server into the other one. I don't see this mentioned anywhere in the docs except for recomendations to run seperate servers. Maybe its best to run both on one server since that works out of the box?

**Comment by soulgalore** [comment]
Hey @martijnvanloon let us make cleaner in the docs: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#configuration-setup

You should set `--graphite.host` to the ip (or hostname) of the server that where you run graphite. Add that extra parameter to sitespeed.io and you should be ready to go.

Best
Peter

**Comment by martijnvanloon** [comment]
And it works immediately! Thank you for the help and great project, documentation is a bit hard to understand for a front end developer but I normally don't mess around with servers.

**Comment by knaos** [comment]
I have issue with sending data to graphite when using config.json file. If I pass the params with --graphite.host=my.ip everything works fine.

This is the config.json

```
{
    "browsertime": {
        "iterations": 5,
        "browser": "chrome",
        "video": true,
        "preScript": "scripts/login.js",
        "pageCompleteCheck": "return (function() {try { return (window.document.querySelector('.map-container') !== null);} catch(e) {} return true;})()",
        "chrome": {
            "args": ["disk-cache-dir=/dev/null", "disk-cache-size=1", "media-cache-size=1"]
        }
    },
    "graphite": {
        "host": "my.ip"
    },
    "webpagetest": {
        "host": "my.ip"
    },
    "plugins": {
    },
    "utc": true
}
```
