### ISSUE TITLE
Add second score + combined score

### ISSUE THREAD

**Issue by kab12** [sitespeedio/sitespeed.io#196]
The idea is to have a second grade just based on performance metrics, the current score is primarily used to grade to what extend performance best practices have been applied which doesn't necessarily mean that performance really is fine (just that in theory it should be…). You already do something like this with the colour coding on the summary page but not on the Pages page.

The idea would be to have two scores (best practice score and performance score) and then to create an overall score that is the average of these two. This would then be the one to sort the Pages table on. Of course, adding a column with the ranking based on this combined score would also be appreciated. You can then sort the table in any direction but still have the original ranking.

For example 25 points for Load Time (25 for 0 seconds, 0 for everything above 6 seconds). 25 points for cacheable items. (100% is 25, below 50 is 0), 20 points for Page Size (below 500k is 20, above 2mb is 0). 20 points for Total Requests (below 40 is 20, over 100 is 0). 10 points for TTFB (10 for 0 sec, 0 for 1+ sec).

**Comment by soulgalore** [comment]
ping #687

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
