### ISSUE TITLE
Deploying my dashboard to Heroku

### ISSUE THREAD

**Issue by ammar88** [sitespeedio/sitespeed.io#1964]
Hi,

I'm currently trying to setup a hosted version of the local dashboard I've created using the steps in the performance dashboard docs. Everything works perfectly locally. I'm trying to deploy to Heroku using docker but I'm having trouble understanding how to get docker compose to do it's thing on Heroku.

Any guidance on how to setup the performance dashboard on Heroku?

Thanks,
Ammar

**Comment by soulgalore** [comment]
Hi @ammar88 sorry I never tried. I'm not familiar with running Docker on Heroku, can you run a standalone container? Only find [this](https://medium.com/travis-on-docker/how-to-run-dockerized-apps-on-heroku-and-its-pretty-great-76e07e610e22) but maybe it's other examples out there. One of the reasons I haven't invested time in trying to run on Heruko is that I'm not sure about the performance (but that is for the sitespeed.io container).
 
Do you specifically need Heruko or can you run on AWS standalone?

Best
Peter

**Comment by ammar88** [comment]
Thanks for the prompt reply Peter. I went with Heroku because I thought, along with docker, it would be the easiest solution to implement. We use AWS also, so I could give that a try.

Ammar
