### ISSUE TITLE
InfluxDB event annotations overwrite within test session

### ISSUE THREAD

**Issue by mitchtech** [sitespeedio/sitespeed.io#1966]
When running sitespeed to test multiple URLs with `influxdb` plugin enabled and `resultBaseURL` set,
event annotation are uploaded for each URL tested, but continuously overwrite with the most recently tested URL. 

The result is that only the event annotation from the last tested URL per run will persist.

**Comment by mitchtech** [comment]
The issue appears to be re-use of the InfluxDB event annotation timestamp. The event annotations are sent to InfluxDB correctly with each tested URL within a test run, but they all reuse the same test session timestamp. This causes InfluxDB to treat each subsequent annotation upload as an update to the previous rather than as new data.

**Comment by mitchtech** [comment]
A simple solution is to generate a unique timestamp for each event annotation upload. I submitted a pull request with this fix: https://github.com/sitespeedio/sitespeed.io/pull/1967

**Comment by petemyron** [comment]
This can be closed now.

**Comment by amitmalhotra-cell** [comment]
hi @mitchtech ,
i am facing same issue of same timestamp getting inserted in influxdb for annotations . Can you tell me how to fix this. I am using latest sitespeed docker image.
