### ISSUE TITLE
User timing measures are not sent to Graphite

### ISSUE THREAD

**Issue by knaos** [sitespeedio/sitespeed.io#1968]
Hello! I think that user timing measures are not sent to Graphite.
I have sitespeed:5.6.1 container sending data to the docker-compose variant of Graphite and Grafana. I am able to see all kind of data except for user timing **measurements**. I can see user timing marks, but when I edit the query like that:
![image](https://user-images.githubusercontent.com/7912102/38353079-067c5506-38be-11e8-9617-e5928c52e09a.png)
I confirm that only user marks are sent. And I am sure I have performance measures on my site (measured right after the mark_end in the code).

![image](https://user-images.githubusercontent.com/7912102/38353315-bb6b080e-38be-11e8-90aa-8f751672dcee.png)

**Comment by knaos** [comment]
Turns out I was making a wrong query in Grafana. All the data is trully in Graphite. 
I will post the query after I figure it out. Issue can be closed

**Comment by knaos** [comment]
Ok I found how to query them. The problem is that they are not sent with their names. Eveyrthing insude the measures folder is folders named with digits:
![image](https://user-images.githubusercontent.com/7912102/38354652-0587c432-38c3-11e8-93e7-5f18d8b12612.png)

When I move into a folder, all the data that is kept per measurement is startTime and duration. The name is missing.

Am I doing something wrong?

**Comment by knaos** [comment]
It is given a number for name, as if the key was given from array position. And the only values stored per measurement entry are startTime and duration.

**Comment by soulgalore** [comment]
yeah but what's the name of the measurement in the User Timing API? :)

**Comment by knaos** [comment]
They are all named. Here is one of them:
![image](https://user-images.githubusercontent.com/7912102/38355681-52dad3a2-38c6-11e8-818c-51f61ca837b5.png)
I have about 30 well named measurements.

**Comment by knaos** [comment]
Could it be in this file: https://github.com/sitespeedio/browsertime/blob/c4440fd93c50288eab0c386c3cd05b89d0299a6a/lib/core/engine/collector.js

In the perIterations script I think you have a typo in the last but one if: userTiming.measure instead of userTiming.measure**s** ?

**Comment by soulgalore** [comment]
yes. I can fix it to tonight or can you do a PR to the 2.x branch (that is the current one released)?

**Comment by knaos** [comment]
I can try

**Comment by soulgalore** [comment]
@knaos I've pushed it now, thanks for finding the exact problem.

**Comment by knaos** [comment]
What kind of test could be added for this one? And when will it get
released?

**Comment by soulgalore** [comment]
hmm tomorrow is better, last time we had some problem with Chrome, something made metrics higher, so need to test that first.

**Comment by knaos** [comment]
Sorry for asking, but I could not find it - Is this fixed and released now?

**Comment by soulgalore** [comment]
Ah sorry I forgot to ping the thread. Upgrade to 6.5.3 
 and the fix should be there. https://github.com/sitespeedio/sitespeed.io/blob/master/CHANGELOG.md#653-2018-04-07
