### ISSUE TITLE
sitespeedio.ERROR: {"cause":{"errno":-13,"code":"EACCES","syscall":"mkdir","path":"/sitespeed.io/sitespeed-result"},"isOperational":true,"errno":-13,"code":"EACCES","syscall":"mkdir","path":"/sitespeed.io/sitespeed-result"}

### ISSUE THREAD

**Issue by Tangyiming** [sitespeedio/sitespeed.io#1975]
![default](https://user-images.githubusercontent.com/18328731/38654672-246f8102-3e43-11e8-969e-65af718cd548.png)

i use root role to do this
please help me ,thank you

**Comment by soulgalore** [comment]
Hi @Tangyiming thanks for the report. Can you create a dir and set open privileges for it, and then run inside that dir? Also what host OS are you running?

Best
Peter

**Comment by Tangyiming** [comment]
@soulgalore 
first ,thank you for your reply.

my OS is CentOS7 
i make a dir,and chmod 777,then run the command inside that directory
but the problem still exists
![default](https://user-images.githubusercontent.com/18328731/38655569-0c214fa4-3e48-11e8-9b4c-67e0432f33ca.png)

**Comment by soulgalore** [comment]
Maybe this can help you: https://github.com/moby/moby/issues/22348

**Comment by Tangyiming** [comment]
@soulgalore thank you !!!!!
