### ISSUE TITLE
Influxdb configuration - docker-compose

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#1977]
Hi, I tried to configure grafana with influxdb via docker-compose.

I have taken as reference the docker-compose part (under the **tools/influxdb** directory) to replace graphite in the docker-compose (under the **docker** directory)

**influxdb:
        image: tutum/influxdb
        environment:
            - PRE_CREATE_DB="sitespeed"
            - ADMIN_USER="root"
            - INFLUXDB_INIT_PWD="root"
            - GRAPHITE_DB=sitespeed
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
            - "8099:8099"**

I started **docker-compose up** under the 'docker' directory, then I tried to contact via API (simulated metric request)

**_curl sitespeedio:"user password"@''my ip":3000/api/datasources/proxy/1/metrics/find_**

response 'grafana':
 
**_'http: proxy error: dial tcp: lookup graphite on 127.0.0.11:53: no such host'
'lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=sitespeedio method=GET path=/api/datasources/proxy/1/metrics/find status=502 remote_addr=172.18.0.1 time_ms=830 size=0 referer='_**

am I missing some other configuration in the docker-compose? Is there a more detailed documentation regarding sitespeed-grafana-influxdb?

Thanks so much

**Comment by soulgalore** [comment]
Hi @amic81 on dashboard.sitespeed.io we run influxdb with the setup:

```
influxdb:
     image: influxdb:1.2.2
     ports: 
        - "8086:8086"
     volumes:
        - /my/path/influxdb:/var/lib/influxdb
```

And we create the database:
```
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE sitespeedio"
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE USER our_user WITH PASSWORD 'our_password'"
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=GRANT all ON sitespeedio TO our_user"
```

**Comment by amic81** [comment]
Hi @soulgalore, 

thank you for your answer.
