### ISSUE TITLE
proposal for 7+: puppeteer for headless Chrome out of the box

### ISSUE THREAD

**Issue by DanielRuf** [sitespeedio/sitespeed.io#1978]
We could use puppeteer in upcoming versions or are there reasons why this does not make much sense to implement?

**Comment by soulgalore** [comment]
Hi @DanielRuf yes I like the Puppeteer API, it's simple and easy for people to use. Or do you see also other use cases to use Puppeteer?

Today we use Selenium/WebDriver to drive the browser and what's good with that is that we can reuse the same code to both drive FF and Chrome (with some different configurations) and maybe in the future also use it for Safari and best case Safari on iOS. That helps us to support multiple browsers, so I kind of like that idea of a common way to use different browsers.

Best
Peter

**Comment by soulgalore** [comment]
Closing but let me know @DanielRuf if you have other use cases that you think would benefit from Puppeteer.

**Comment by DanielRuf** [comment]
> Closing but let me know @DanielRuf if you have other use cases that you think would benefit from Puppeteer.

What a coincidence. Finished a blog article (currently draft) with some Puppeteer examples beyond my projects which already use Puppeteer.

I also saw that Firefox also has a headless flag on the terminal and already has some headless functions.

Hopefully the others and the webdriver implementation(s) get(s) widely adopted.
