### ISSUE TITLE
S3 endpoint URL support

### ISSUE THREAD

**Issue by abhinavn** [sitespeedio/sitespeed.io#1987]
I am using S3 compliant storage and need to pass endpoint param when pushing reports to S3 because its not default AWS S3, does sitespeed support passing s3 endpoint? I didnt find any such setting in documentation

**Comment by abhinavn** [comment]
@soulgalore - happy to help with testing.

**Comment by abhinavn** [comment]
@soulgalore I am doing some major code enhancements and was wondering if you are able to get the merge in.

Also thanks for all the OSS work you are doing, appreciate it

**Comment by soulgalore** [comment]
thanks for the kind words @abhinavn !

Yes of course, what do you aim for? I think the cleanest way would be to get rid of s3 and instead only use aws-sdk directly? Or what do you want to enhance? :)

**Comment by abhinavn** [comment]
@soulgalore i see the issue linked to this is closed, is there documentation i can refer to for passing s3 URL in 7.0?

**Comment by soulgalore** [comment]
@abhinavn yes sorry: https://www.sitespeed.io/documentation/sitespeed.io/configuration/#the-options scroll to the s3 params:

Checkout --s3.params (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) and --s3.options (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) I hope they will help?

Best
Peter

**Comment by abhinavn** [comment]
@soulgalore yes, got it by looking as S3 documentation. what i did was use --s3.options.endpoint <custom s3 endpoint>

Closing this as fixed! Thank you!

**Comment by soulgalore** [comment]
thanks @abhinavn for adding how you did it!
