### ISSUE TITLE
Difference Transfer vs content size

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#1989]
Hi,I tried to do a scan (docker run ... -n 1) and I noticed that the transfer size and content size are different.

Example javascript part

- **Transfer size** : 784.5 Kb
- **Content size** : 1032.7 Kb

How are these 2 values calculated?

Thank you

**Comment by tobli** [comment]
🎉 This is awesome, compression is great for web performance! 🎉 

Transfer size is the number of bytes sent "over the wire", content size is the size on disk (of the raw js files in this case). If you have compression turned on, the web server will zip the text content before it's sent, and the browser will decompress it.
