### ISSUE TITLE
InfluxDB data and annotations timestamp differs by 15-20 sec

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#1995]
Hello,

I'm using InfluxDB as statistics data storage.
Looks like timestamp of data bunches and annotations differs by 15-20 sec leading to confusing moments like at picture below. 

![image](https://user-images.githubusercontent.com/10085700/39201485-deab93c2-47f7-11e8-8eb7-a1a9247eb59e.png)

I'm pretty sure that annotation timestamps are set correctly especially after #1967 but other data gets timestamp of appearing in InfluxDB (according to InfluxDB logs). I see that timestamp is set for data bunch in data-generator.js as time: time.valueOf()

I'm not really good in nodejs and InfluxDB but I consider that timestamp should be provided as single value rather than key:value.

Could you please look into and fix this issue?
Thank you in advance.

**Comment by soulgalore** [comment]
Hi @Icecold777 thanks for reporting the issue!

Can you show me how you run? You test the same URL once but every X minutes? Just so I understand the use cases. 

Best
Peter

**Comment by Icecold777** [comment]
Hi @soulgalore, 

Right, the use case is to touch the same URL in loop just one by one without pause.

Best Regards.

**Comment by soulgalore** [comment]
So how often do you do releases :) 

I'm not using influxdb so would love a PR for this but else let us add it to the list and look into it later.

**Comment by Icecold777** [comment]
That's funny but the easiest way to synchronize annotations and data buckets time is just to remove timestamp field from annotation sender js file.
Works perfect
![image](https://user-images.githubusercontent.com/10085700/39322720-71d57cb6-4993-11e8-8448-55f0be4033fe.png)

but I'm not sure that it will be OK in case of bad network connection between sitespeed and remote influxDB (just as example). That will lead to the same desynchronization.

btw,
is it possible to catch the bodies of POST request to influxDB sent be sitespeed?

**Comment by soulgalore** [comment]
sorry for the late response.

> is it possible to catch the body of POST requests to influxDB sent be sitespeed?

How do you mean?

**Comment by soulgalore** [comment]
Closing this since we never heard back, but please ping the issue again if you still have the issue so we can help you!
