### ISSUE TITLE
Visual metrics not being generated

### ISSUE THREAD

**Issue by abhinavn** [sitespeedio/sitespeed.io#1996]
I am on sitespeed.io 6.5.4 version and i see that visual metrics are not being generated for my video files. I ran the videos through visualmetrics.py and i dont metrics available either. I am looking for some help on how to debug this issue

https://www.dropbox.com/s/i7q64nvsfg0rvhc/2.mp4?dl=0

Any idea on what could be happening here? Attached is originalVideo file

**Comment by soulgalore** [comment]
Hi @abhinavn thanks for reporting. It seems it picks up something at the beginning of the video, but for me to know what I need to have the original video (not processed), you can get that with **--browsertime.videoParams.keepOriginalVideo**. One of the most common problem is that you run without setting any connectivity and depending on where you test, the orange frame in the beginning is too short.

1. Try to set connectivity (if you don't today).
2. I'll think we added a longer wait time in the coming Browsertime 3.0 so hopefully it will work when we release that.

Best
Peter

**Comment by abhinavn** [comment]
@soulgalore thanks, that was it. I was working fine in the past without connectivity, as in working with "native". I just setup cable connectivity and dont see to have any issues now. I do see visualMetrics being generated

**Comment by abhinavn** [comment]
Closing the issues as resolved
