### ISSUE TITLE
coach-results and browsertime-results in json format

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2000]
Hi,

Is it possible to extract the **coach** and **browsertime** data in **json** format through sitespeed? (Without going to the coach or browsertime)

There are some options to add to the command:

**docker run --shm - size = 1g --rm - v "$ (pwd)": / sitespeed.io sitespeedio / sitespeed.io: 6.5.4 https://www.sitespeed.io/**

Thanks so much

**Comment by soulgalore** [comment]
Hi @amic81 you can run the plugin analysisstorer that will store it to disk. Here's an example: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#add-a-plugin

Best
Peter

**Comment by soulgalore** [comment]
Yep you are right, that's the summary of the metrics for all the runs. I don't think there's a way today to store the raw data. So you mean you want the texts, and not the actual metrics? Tell us our use case  so we know why it's important :)

Best
Peter

**Comment by amic81** [comment]
Hi,
in reality I would have used both the texts and the numerical values in order to have all the information as the coach's launch. :)

Bye
amic81

**Comment by soulgalore** [comment]
Hepp, I've missed that the data is already stored in the data folder for each individual page. Let us add some documentation for that in the coming release. Go to the data folder for each page and you will find what you need @amic81 !

Best
Peter

**Comment by amic81** [comment]
Hi @soulgalore,

I tried to do a scan:

**docker run --shm-size=1g --rm -v "$ (pwd)"/sitespeed.io sitespeedio/sitespeed.io http://www.sitespeed.it -n 1**

but I did not find the data stored in json format in the directory:

**\sitespeed-result\www.sitespeed.it\2018-04-30-09-24-49\pages\www.sitespeed.it\data**

is the path wrong? Are the data not saved in json format? Or am I wrong with the generation command?

best
amic81
