### ISSUE TITLE
Additional metrics on summary tab

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2001]
Can I customize with sitespeed commandline on what parameters i can have on pages tab - forexample i want to add perceptual speed index here...

![image](https://user-images.githubusercontent.com/7537289/39325923-17dee6c8-4959-11e8-9a8c-8a3f649f8913.png)

**Comment by soulgalore** [comment]
Maybe. It will not happen before 7.0 though, at least from me. To make it work, it needs to be refactored, but right now I need focus on Browsertime 3.0 so we can release sitespeed.io 7.0 sometimes after Firefox 61 goes to beta (and broken things in Firefox is fixed), that's the prio the coming months.

**Comment by softwareklinic** [comment]
thank you - whenever we can --- if we can...

On Thu, Apr 26, 2018 at 2:06 PM, Peter Hedenskog <notifications@github.com>
wrote:

> Maybe. It will not happen before 7.0 though, at least from me. To make it
> work, it needs to be refactored, but right now I need focus on Browsertime
> 3.0 so we can release sitespeed.io 7.0 sometimes after Firefox 61 goes to
> beta (and broken things in Firefox is fixed), that's the prio the coming
> months.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2001-23issuecomment-2D384756354&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=ILVcDL7mMKNwsgYeZFJ6v8_8KsgRI4mIZh91onmOBtc&s=ECJ_Bjz4G_7EDwRIo-dIvTn6Yr3wL5vMcMXPburMqlU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCiZU8nzt999jPCDuaFTyhqaN7D7Lnks5tshqwgaJpZM4Tm2Ry&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=ILVcDL7mMKNwsgYeZFJ6v8_8KsgRI4mIZh91onmOBtc&s=U5YWqL_i-dVYi-gckN1225_Rp3FSUU70MScTzI5gW5U&e=>
> .
>



-- 
Regards,
Keyur
Cell: 2147845203

**Comment by soulgalore** [comment]
yep lets see I'll have a look when I find the time, it shouldn't be too complicated but want to make it cleaner that it is today.

**Comment by soulgalore** [comment]
This is also on my top want at the moment, let me see how we can fix this the coming weeks.

**Comment by softwareklinic** [comment]
Awesome


Regards
Keyur

On Apr 8, 2019, at 10:42 PM, Peter Hedenskog <notifications@github.com>
wrote:

This is also on my top want at the moment, let me see how we can fix this
the coming weeks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2001-23issuecomment-2D481110031&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=48Qodx9PYNEsE4aEItrsrT305JtDPq0BIxjnT-CKSxg&s=ivyM6tF3Ns2z6O8wZSupj0AIrHki2e27Ypx5xb47VT8&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCidLYjft20xvQvLZuq3MFbqAmtUfDks5vfCgygaJpZM4Tm2Ry&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=48Qodx9PYNEsE4aEItrsrT305JtDPq0BIxjnT-CKSxg&s=fnin1qsWfq_O56PCLWn_2L-QwI_iaoN1Ctzh1src3go&e=>
.

**Comment by soulgalore** [comment]
I didn't get around to fix this but I now have an idea on how to do it:

We should move https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/budget/friendlynames.js outside of the budget and make it generic. Then we could use the short names to choose what columns to show. We could add a cli parameter that default has the one we have today, an array with a couple if strings. And then the user can choose change that, but only with the ones we have in friendly names.

**Comment by soulgalore** [comment]
This was released in 11.0!

**Comment by softwareklinic** [comment]
Super


Regards
Keyur

On Nov 18, 2019, at 7:39 PM, Peter Hedenskog <notifications@github.com>
wrote:

﻿

This was released in 11.0!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2001-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABZQFCNIGWCJQKXRZSXSKETQUM7V5A5CNFSM4E43MRZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEMRIUI-23issuecomment-2D555291729&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=tH5QBkpJSjFEwlPQKoOBuo4uVrXubE_VjG-JGQcFUZM&s=-Q4uZpOzt9e_JX_XdIftOE5W4CHSj0LN8x6n-7O0f8M&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABZQFCKMM7XT3LROWRTZ3FDQUM7V5ANCNFSM4E43MRZA&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=tH5QBkpJSjFEwlPQKoOBuo4uVrXubE_VjG-JGQcFUZM&s=cDNNEVSmepFuVtWKPG6oQJALN4x9rdTMbqWfQoqOWgw&e=>
.

**Comment by jmrane** [comment]
is this resolved or any workaround for this?

**Comment by soulgalore** [comment]
I think you can use `--html.pageSummaryMetrics ` to change them, the documentation: https://www.sitespeed.io/documentation/sitespeed.io/configure-html/#configure-page-metrics
