### ISSUE TITLE
influxdb : discriminate data score

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2003]
Hi,

launching 2 scans of sitespeed

the first with the parameter 
--metrics.filter *- coach.pageSummary.advice.performance.adviceList.cacheHeaders.score
and the second with the parameter 
--metrics.filter *- coach.pageSummary.advice.performance.adviceList.avoidScalingImages.score

and saving the data on influxdb, I noticed that the 2 measurements are both finished on score.
By making a select on influxdb (select * from score), there is no discriminating in understanding which one refers to cacheHeaders and which to avoidScalingImages.

Can an identification tag be used to discriminate the 2 types of score?

Best
amic81

**Comment by soulgalore** [comment]
Ah so it's an miss then that we are missing a tag? It should be a tag for **advice** that in your case should be cacheHeaders or avoidScalingImages.

Best 
Peter

**Comment by amic81** [comment]
Yes, I suppose there should be a tag advice to differentiate the cacheHeaders or avoidScalingImages records (or another record ...) otherwise there are two or more identical records as a score.

Can you add this tag to discriminate? What do you think about it?

Thanks
amic81

**Comment by soulgalore** [comment]
Did you check if the tag was there? It is in the code, but I don't have an instance running that pushed metrics at the moment. The one we have is too small on Digital Ocean and cannot handle the metrics, I'll try to upgrade when I find the time.

**Comment by amic81** [comment]
Hi @soulgalore 

The tag on influxdb is not present, surely it's in the code but it's probably not saved.

Can you offer an instance in our DataCenter to continue more quickly the debug of sitespeed code for 4 months free? 
If you are interested plis contact email alessandro.fustini@host.it

Thanks
amic81

**Comment by soulgalore** [comment]
Hmm are you sure, I wonder if it can be some configuration issue?  It's there by default:
<img width="1099" alt="screen shot 2018-04-30 at 11 27 43" src="https://user-images.githubusercontent.com/540757/39421502-a40be05c-4c69-11e8-9557-ab19a4d2245d.png">

**Comment by amic81** [comment]
Hi @soulgalore,

at the command

docker run --shm-size=1g --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io http://www.sitespeed.io -n 1 --video --influxdb.host=x.x.x.x -metrics.filter *- coach.pageSummary.advice.performance.adviceList.cssPrint.score coach.pageSummary.advice.performance.adviceList.cssSize.score

on influx for the metric score the tag $group is present and is enhanced with "www_sitespeed_io" (about this, is there a reason why you put _ instead of the . ?),
the tag I do not see is a tag that identifies the value (I think of type) that in this case should be "cssPrint" or "cssSize".
Instead of seeing 2 "cssPrint" or "cssSize" records, I see only one record without the tag that identifies them.

I hope I was able to explain well. ;-)

**Comment by soulgalore** [comment]
Ah I see now how you mean, ok we miss one level then. Yep we don't have that today.

**Comment by soulgalore** [comment]
@amic81 I've pushed a branch than adds a tag adviceName to each score, let me know if you have time to test it out!

**Comment by soulgalore** [comment]
This was fixed some time ago.
