### ISSUE TITLE
Special characters need to be escaped for ffprobe to work

### ISSUE THREAD

**Issue by aerwin** [sitespeedio/sitespeed.io#2016]
I believe I have a case similar to https://github.com/sitespeedio/sitespeed.io/issues/1797 where a URL containing `=` was causing `ffprobe` to die. However, in my case, I'm suspecting `:`'s and `/`'s.

The URL I'm testing contains a CRN and looks like the following when encoded:

`https://console.bluemix.net/services/appid/crn%3Av1%3Abluemix%3Apublic%3Aappid%3Aus-south%3Aa%2F2bcf38bc5bb11ca5e41e3fda204a5147%3A2c392070-bac9-4745-b33a-879163f84315%3A%3A/?paneId=manage`

When the CRN part of the path (see `crn%3Av1%3Abluemix%3Apublic%3Aappid%3Aus-south%3Aa%2F2bcf38bc5bb11ca5e41e3fda204a5147%3A2c392070-bac9-4745-b33a-879163f84315%3A%3A`) is decoded, it looks like

`crn:v1:bluemix:public:appid:us-south:a/2bcf38bc5bb11ca5e41e3fda204a5147:2c392070-bac9-4745-b33a-879163f84315::`

With video capture enabled, Sitespeed fails with the following `ffprobe` error (which contains the decoded string in the file name):

```
[2018-05-04 14:18:20.821] [ERROR] bluemix-sitespeed-driver - [2018-05-04 19:19:04] ERROR: Error: Command failed: ffprobe -f lavfi -i movie='/SitespeedDriverResults/sitespeed-result/console.bluemix.net/2018-05-04/19_17_49.754Z_services_appid_crn_3Av1_3Abluemix_3Apublic_3Aappi_AUTHENTICATED/pages/console.bluemix.net/services/appid/crn:v1:bluemix:public:appid:us-south:a/2bcf38bc5bb11ca5e41e3fda204a5147:2c392070-bac9-4745-b33a-879163f84315::/query-4352e841/data/video/0.mp4',signalstats -show_entries frame_tags=lavfi.signalstats.SATAVG -v quiet -print_format json
```

If I use a URL with the encoded `:`'s and `/`'s replaced with `_`'s (like below), then video records successfully (though it's just a 500 error page because it's no longer a valid CRN):

`https://console.bluemix.net/services/appid/crn_v1_bluemix_public_appid_us-south_a/2bcf38bc5bb11ca5e41e3fda204a5147_2c392070-bac9-4745-b33a-879163f84315__/?paneId=manage`

Any help would be appreciated. Thanks!

**Comment by soulgalore** [comment]
Hi @aerwin can you help me how I can reproduce it? Tried with `"https://www.sitespeed.io/?test=crn:v1:bluemix:public:appid:us-south:a/2bcf38bc5bb11ca5e41e3fda204a5147:2c392070-bac9-4745-b33a-879163f84315::"` but that works for me.

Do you pick up any more error messages? FFProbe is used to pickup when the orange color switched to white and a common bug sometimes is that the the sites load too fast if you don't set any connectivity? Are you using any connectivity settings?

Best
Peter

**Comment by aerwin** [comment]
@soulgalore Thanks for the response... many apologies in my delay. Somehow I missed the @-mention from you back in May.

Anyway, I was able to reproduce with the following where I put the CRN in the URL path, rather than in the args:

`docker run --rm -v /Users/aerwin/git-ACE_MICRO/bluemix-sitespeed-driver:/sitespeed.io sitespeedio/sitespeed.io:6.5.1 https://example.com/services/crn:v1:bluemix:public:appid:us-south:a/2bcf38bc5bb11ca5e41e3fda204a5147:2c392070-bac9-4745-b33a-879163f84315:: --browsertime.iterations 1`

**Comment by soulgalore** [comment]
Thanks @aerwin , I could reproduce with 6.5.1. With 7.1.2 it works :)

Best
Peter

**Comment by aerwin** [comment]
thanks, @soulgalore -- I've confirmed the fix.

I opened this long enough ago, I should have tried the latest version myself in the first place. :)
