### ISSUE TITLE
Pre/post scripts - external parameters

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2020]
Hi,

In a preScript / postScript would it be possible to pass external parameters?

For example would it be possible to externally pass the **paramValue** parameter value?

```
var request = require('sync-request');

module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
		
		var options = {
		 headers: {
		   'Content-Type': 'application/json'
		 },
		 qs: {'param': 'paramValue'}
	   };
		
		var res = request('GET', 'http://XX.XX.XX.XX:8080/api/yyyy', options);
		
		var jsonString = res.body.toString('utf-8');
		console.log(jsonString);

      });
  }
};
```

Thanks
amic81

**Comment by soulgalore** [comment]
Hi @amic81 
yes I thinks so but I haven't tested it. The context that is passed into the pre/post script holds the options object, that is the parsed version of what you add in the CLI. We don't verify the parameters so you could (probably) add your own. Like `--browsertime.myplugin.hepp paramValue` would then be available as **context.options.browsertime.myplugin.hepp** in your plugin. At least I think, and if it doesn't work and it would help you, I can try to fix it. 

Best
Peter

**Comment by soulgalore** [comment]
Closing but let me know if my example didn't work out.
