### ISSUE TITLE
Post script

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2021]
Hi,

could you add the possibility to run a script at the end of the whole analysis?

Virtually after

Example
**Finished analysing http://www.sitespeed.io**

a type parameter

**- postScript**

(and maybe even a generic **--preScript** ...)

Best
amic81

**Comment by amic81** [comment]
Hi,

I would need to be able to run my own script at the end to perform various final operations (for example save me only the browsertime, call my API for data processing, etc ...)

In the sitepeed project I could not find the file context.index, where is it?

Buy and thank you for the support.

amic81

**Comment by soulgalore** [comment]
Checkout https://github.com/sitespeedio/sitespeed.io/blob/master/test/prepostscripts/postSample.js#L2 that's the context object where we pass on data to pre/post taska. So try it out, write a simple post task and log the index (the iteration, we should rename that so it is clear):

```
module.exports = {
  run(context) {
    context.log.info('Index:' + context.index);
  }
};
```

Best
Peter

**Comment by amic81** [comment]
Ok, 

but (for example) I would need browsertime.har and this file is not present on the container at the time of the postscript launch... I think it would serve a command like --finalScript launched after (at the end of the analysis ... - Finished analysing http://www.sitespeed.io -)
Do you think it's a good idea?

Thanks
amic81

**Comment by soulgalore** [comment]
I see, then you can build a plugin: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin - then you can pickup the metrics you want and do whatever you need. All functionality in sitespeed is built upon plugins, so you can find inspiration there.

Best
Peter

**Comment by amic81** [comment]
Thank you,

I'll try the way of the plugin. In this regard, is it possible to pass external parameters to the plugin?

Example
--plugins.add /myplugin **param1**

Thank you
amic81

**Comment by soulgalore** [comment]
Hi @amic81 
pass them like `--myplugin.param1`, the options object is passed to the plugin. Check the plugins folder for inspiration: https://github.com/sitespeedio/sitespeed.io/tree/master/lib/plugins

Best
Peter

**Comment by soulgalore** [comment]
Closing this, let me know @amic81 if it didn't work out for you.
