### ISSUE TITLE
Browserify - conflict of interests

### ISSUE THREAD

**Issue by TJ71** [sitespeedio/sitespeed.io#2023]
So I have a small challenge... A developer has recently added [Browserify](http://browserify.org/) to a few of the sites that we monitor with Sitespeed. 

The outcome of using it is I'm getting very little sight of whats actually loading on the page. The HARs show 5-6 items when I know the pages contain far more. 

My 'toplist' and 'assets' show plenty, so I'm maybe being overly concerned when there isn't any real issue.

Keen to hear if anyone else monitors pages that use Browserify or similar and/or if there is a workaround - including the obvious one of 'you need to remove Browserify.' 

thanks

**Comment by soulgalore** [comment]
Closing since it seems there's no one there that could help, sorry.
