### ISSUE TITLE
How to get WebPageTest Script data in grafana ?

### ISSUE THREAD

**Issue by aprak7** [sitespeedio/sitespeed.io#2025]
Hi - 
I have done the setup for WebPageTest + Sitespeed + Graphite + Grafana.

Issue -->  I am not able to see metrics for URLs passed in WPT Script in grafana. Metrics are visible only for the URL that is passed with sitespeed. WPT Script has a user journey in continuation with the URL being passed in Sitespeed {{URL}}. Below is the configuration and the command which are being used to trigger the test -

linux 4.4.0-1055-aws nodejs: v8.11.1 sitespeed.io: 6.5.4 browsertime: 2.5.0 coach: 1.3.0

/usr/lib/node_modules/sitespeed.io/bin$ sudo ./sitespeed.js {{URL}}--browsertime.chrome.args no-sandbox --xvfb --browsertime.xvfb --speedIndex -n 1 --graphite.host xx.xx.xx.xx  --webpagetest.host http://x.x.x.x --webpagetest.location Local-WPTDriver --webpagetest.includeRepeatView true --webpagetest.file WPTScript.txt --webpagetest.private false

**Comment by soulgalore** [comment]
Hi @aprak7 
by default we only send a couple of cherry picked metrics to Graphite to not overload it, but you can choose what metrics to send, here's the documentation: https://www.sitespeed.io/documentation/sitespeed.io/metrics/

It's a little bit tricky so let me know how it works out, but now when I think about it I wonder if we don't send user defined metrics by default? If you open Grafana and go into one of your WebPageTest dashboards and drill down the WebPageTest metrics, can you find a path named *custom* ? I think all custom metrics should be there.

Best
Peter

**Comment by soulgalore** [comment]
You can choose what to send, please let us know if it didn't work out for you.
