### ISSUE TITLE
[Feature Request] Ability to view browser console log errors in HTML report and Grafana

### ISSUE THREAD

**Issue by abhinavn** [sitespeedio/sitespeed.io#2029]
Currently sitespeed.io doesn't have ability to show errors from browser console log. However browsertime does have ability to capture this data(using --chrome.ConsoleLog flag). Request is to parse this data from browsertime and add the details to 1)HTML report 2) Graphite. One can build Grafana page to show errors and link reports to the HTML report over period of time.

I would visualize being able to see JS errors from console log in Grafana something like what is available in NewRelic - https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/javascript-errors-page-examine-errors-over-time 

cc : @soulgalore

**Comment by soulgalore** [comment]
This was released in 7.0 but I need to verify that errors in Graphite work as it should. I think we maybe don't send any metrics if it is 0, but let me have a look at that later.

**Comment by abhinavn** [comment]
@soulgalore let me try this and update you

**Comment by soulgalore** [comment]
Fixed in 7.x
