### ISSUE TITLE
Display har - PerfCascade

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2043]
Hi,

I saw that to display the har used perf-cascade.

But on various browsers (Edge 41.x, chrome 66.x) I detected various anomalies ... is there a reason why you chose this library?

thanks
amic81

**Comment by soulgalore** [comment]
Hi @amic81 ,
PerfCascade is the only modern open source HAR viewer I know about that displays the HAR waterfall using SVG, I think it's pretty awesome!

I haven't seen any bugs with Chrome 66. Could you please create one individual issue for each browser in https://github.com/micmro/PerfCascade/issues/new

Please provide a screenshot if that will help, describe the error and check if you see an error in the console (include that too). And also include the HAR so we can reproduce it.

Best
Peter

**Comment by amic81** [comment]
Ok,

I proceed to open a issue.

Thanks Peter
amic81
