### ISSUE TITLE
Sitespeed, Graphite and Grafana in Windows

### ISSUE THREAD

**Issue by PerfRobo** [sitespeedio/sitespeed.io#2054]
Can some one provide us with a quick link to the steps to configure and run the Sitespeed along with the performance dashboard in a windows environment?

Thanks.

**Comment by soulgalore** [comment]
Hi @PerfRobo best is to use Docker containers. I think Docker on windows handles paths a little different so you need to read up on https://docs.docker.com/docker-for-windows/

Best
Peter

**Comment by PerfRobo** [comment]
Hello Peter, docker is not allowed yet in my workplace environment. Is there any other alternative?

**Comment by soulgalore** [comment]
Docker as is or ready made Docker containers? I guess it''s hard to not use the first layer with the OS. 

Installing npm works but there's a lot of decencies to keep track of, you can see them if you start in the https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile and walk upwards in the FROM section.

**Comment by Icecold777** [comment]
I've installed sitespeed.io using npm to Win7 without any problem. 
1. download latest LTS .msi (https://nodejs.org/en/download/) and install nodejs
2. npm install --global --production windows-build-tools
3. npm install -g sitespeed.io
4. c:\Users\${USER_NAME}\AppData\Roaming\npm\sitespeed.io.cmd -help

Chrome and Firefox were preinstalled preliminary. Basic functionality works the same way but video recording and all metrics connected to video analysis, network throttling are not available out of the box. I have not spent a lot of time to resolve this issue but expect that integration with FFmpeg will be a tricky task. 
And important to note that sitespeed works in GUI mode without XVFB but you may use _--browsertime.headless true_ to use headless Chrome instead. 

@soulgalore, is there a way to add memory to headless chrome like --shm-size=1g in docker? I see some page load time overhead running headless against GUI mode. Even backend SSL connection takes more time. 
![image](https://user-images.githubusercontent.com/10085700/40786549-f3d8fae6-64f3-11e8-9365-b08e13127118.png)

**Comment by PerfRobo** [comment]
Hello Icecold..

Are you running graphite and grafana on win7 as well?

Regards, PK

**Comment by Icecold777** [comment]
Hi PerfRobo. I use influxDB + Grafana installed from some random web guide

**Comment by soulgalore** [comment]
Closing this since we officially only support Linux.

**Comment by shrutiseth** [comment]
@Icecold777 - Do you have any documentation or reference for this setup on Windows?
