### ISSUE TITLE
[QUESTION] Is it possible to do interactions?

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#2057]
Guys,

Is it possible to do interactions after loading a page?

I have a scenario where I need to load a page and measure the loading time to appear a popover after the click on a button. It is possible? 

Thank you!

**Comment by soulgalore** [comment]
Hi @livyson no, try with WebPageTest.org and https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting maybe it can work. 

Best
Peter
