### ISSUE TITLE
[QUESTION] Network time influences the test time?

### ISSUE THREAD

**Issue by livyson** [sitespeedio/sitespeed.io#2058]
Guys,

Does sitespeed.io add network time at test times? It is bad because the application may be good in the times, but the bad network ends up influencing the execution time of the application.
If so, how can I separate these times?

**Comment by soulgalore** [comment]
Hi @livyson what do you want to measure? :) 

Either you set connectivity (try to emulate a specific network time) https://www.sitespeed.io/documentation/sitespeed.io/connectivity/ or if you want to make sure to eliminate network/backend problems as much as possible, try out WebPageReplay - https://www.sitespeed.io/documentation/sitespeed.io/webpagereplay/

Best
Peter

**Comment by soulgalore** [comment]
Closing, let me know if you need more info than the docs.
