### ISSUE TITLE
ERROR: Cannot read property 'pushStart' of undefined

### ISSUE THREAD

**Issue by calebcassel** [sitespeedio/sitespeed.io#2068]
I'm running with these versions:
 Versions OS: linux 4.15.0-22-generic nodejs: v8.11.1 sitespeed.io: 7.0.2 browsertime: 3.0.16 coach: 2.0.2

Yet for certain pages I'll get the following error:
```
[2018-06-01 16:32:48] INFO: Testing url **** iteration 1
[2018-06-01 16:32:56] ERROR: TypeError: Cannot read property 'pushStart' of undefined
    at populateEntryFromResponse (/usr/src/app/node_modules/chrome-har/index.js:72:27)
    at Object.harFromMessages (/usr/src/app/node_modules/chrome-har/index.js:424:15)
    at ChromeDelegate.onStopIteration (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:73:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is on Chrome. If I disable HAR then it goes away. I wasn't having this issue on the latest 6.x version.

**Comment by soulgalore** [comment]
Hi @calebcassel thanks for reporting the issue. We did [one fix](https://github.com/sitespeedio/chrome-har/pull/21/files) in the Chrome HAR that converts the Chrome trace log to a HAR file that have introduced it. I can make a quick fix now but it would be super if you could provide the URL/or a trace log so we could add a test case. I'll ping the thread when we released a fix.

Thanks again for reporting!
Peter

**Comment by soulgalore** [comment]
Lets wait with closing until it's in sitespeed.io

**Comment by soulgalore** [comment]
The fix is pushed in master now. We also upgraded Chrome 67 but I could see now that metrics increased on one of our instances, so I reverted that change and will wait for that [everything looks ok](https://www.sitespeed.io/releasing-with-confidence/) then I'll push a new release and have a look at the 67 problem later.

**Comment by calebcassel** [comment]
Thanks for the quick response!
I'm able to see these errors on this URL: https://www.hudl.com/video/59e9139c02b1c80a5034323e

**Comment by soulgalore** [comment]
Ah thanks. I wanna make sure that the metrics goes down so I can see that it is Chrome 67 and not the new version of the Chromedriver, I'll know for sure tomorrow will do the release sometimes this weekend.

**Comment by soulgalore** [comment]
Pushed 7.0.3 just now so it should be in the Docker hub in a couple of minutes.

**Comment by soulgalore** [comment]
Released and should work now.
