### ISSUE TITLE
Test out s3 plugin compatibility with DO Spaces

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#2072]
It looks like we could possible add documentation around the use of DO spaces since they are compatible with the S3 API. This would be good to get our users another option for html storage.

https://www.digitalocean.com/products/spaces/

**Comment by soulgalore** [comment]
Ping @beenanner :)

**Comment by beenanner** [comment]
Let me test this out next week and get the docs updated if everything works. :-)
