### ISSUE TITLE
Performance budget analysis

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2075]
Hi there,

I've configured small budget file 
`{
	"browsertime.pageSummary": [{
		"metric": "statistics.timings.firstPaint.mean",
		"max": 500
	},
	{
		"metric": "statistics.visualMetrics.FirstVisualChange.mean",
		"max": 1000
	},
	{
		"metric": "statistics.timings.pageTimings.backEndTime.mean",
		"max": 10
	}]
}`

There are the first two metrics in configuredMetrics but FirstVisualChange rule is not applied.  I see 0 working and 2 failing rules.
Please explain the behavior.

Another question, if there is  browsertime.pageSummary.statistics.timings.pageTimings in configuredMetrics does it mean that all metrics under this alias are available (e.g. .backEndTime.mean). I considered that it should look like browsertime.pageSummary.statistics.timings.pageTimings.*

Best Regards.

**Comment by soulgalore** [comment]
Hi @Icecold777 
can you show me how you run? Do you collect visual metrics (either by running in Docker where it is turned on by default or by adding --visualMetrics)? 

I tried with `docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ --budget.configPath budget.json` (with your budget file as budget.json) and then I get all three rules. What's the problem I think is that it isn't clear that the default behavior if you miss a metric, the budget pass?

> Another question, if there is browsertime.pageSummary.statistics.timings.pageTimings in configuredMetrics does it mean that all metrics under this alias are available (e.g. .backEndTime.mean). I considered that it should look like browsertime.pageSummary.statistics.timings.pageTimings.*

Yeah that doesn't seem completely right, I agree.

Best
Peter

**Comment by Icecold777** [comment]
oh, shame on me(
I'm validating this budget file on Windows machine out of Docker. And it's pretty obvious that visualMetrics are not available.

Thank you, Peter

**Comment by Icecold777** [comment]
Another question)

I'm running following command in Jenkins
docker run --shm-size=1g --rm -v $sitespeed_home:/sitespeed.io sitespeedio/sitespeed.io:7.0.2 https://sitespeed.io --config /sitespeed.io/configs/conf.json  --budget.configPath /sitespeed.io/budget/budget.json

One of the rules is failing but Jenkins job is finished with SUCCESS status. --budget.suppressExitCode is not used in config file

Google Chrome 66.0.3359.181 
Mozilla Firefox 61.0
[2018-06-12 14:32:15] INFO: Versions OS: linux 4.4.0-1060-aws nodejs: v8.11.1 sitespeed.io: 7.0.2 browsertime: 3.0.16 coach: 2.0.2
[2018-06-12 14:32:15] INFO: Starting chrome for analysing https://sitespeed.io 1 time(s)
[2018-06-12 14:32:15] INFO: Testing url https://sitespeed.io iteration 1
[2018-06-12 14:32:29] INFO: 10 requests, 129.34 kb, backEndTime: 552ms, firstPaint: 620ms, firstVisualChange: 633ms, DOMContentLoaded: 565ms, Load: 603ms, speedIndex: 633, visualComplete85: 633ms, lastVisualChange: 633ms, rumSpeedIndex: 620
[2018-06-12 14:32:29] ERROR: Failing budget browsertime.pageSummary.statistics.timings.pageTimings.backEndTime.mean for https://sitespeed.io with value 552 ms max limit 100 ms
[2018-06-12 14:32:29] INFO: Budget: 8 working and 1 failing tests
[2018-06-12 14:32:31] INFO: HTML stored in /sitespeed.io/sitespeed-result/sitespeed.io/2018-06-12-14-32-15
[2018-06-12 14:32:31] INFO: Finished analysing https://sitespeed.io

Finished: SUCCESS

**Comment by Icecold777** [comment]
I've found the reason. docker run should be the latest action in Jenkins build. 
As I understand that means if I execute two docker run commands and the first one has failed budget and the second one not the build won't be FAILED status. 
My use case:
I run the same pages with different connectivity profile

**Comment by soulgalore** [comment]
Hi @Icecold777 you can collect the result code from each run and then exit on the sum. If everything is ok it will be 0 = pass. Something like:

```
#!/bin/bash
declare -i RESULT=0
docker run ....
RESULT+=$?
docker run ....
RESULT+=$?
docker run ....
RESULT+=$?
exit $RESULT
```
Is that what you need?

Best
Peter

**Comment by Icecold777** [comment]
That's exactly what I need. Thank you!
