### ISSUE TITLE
Taking a long time to perform tests on Android

### ISSUE THREAD

**Issue by Adesh** [sitespeedio/sitespeed.io#2080]
Setup:
Host - Ubuntu 18.04
Sitespeed - docker version 7.1.2

When running sitespeed on Android, the process takes around 10 minutes on an average.
Most of the time is taken by analysing the web and converting videos on 30 fps format.

The average page load times are in minutes, which otherwise opening on the android chrome browser does not take so long to be loaded.

Can anyone provide a solution to speed up the process? And also highlight why testing sitespeed on an Android makes chrome opening a webpage very slow.

**Comment by soulgalore** [comment]
Hey @Adesh what kind of hardware are you using and what URL are you using?

Best
Peter

**Comment by Adesh** [comment]
@soulgalore i am using Samsung galaxy note 4 and using https://www.wikipedia.com/ page for testing

**Comment by soulgalore** [comment]
Hi again,
can you show me how you run? I tested now on Ubuntu 16 running in Parallels on my Mac, so it isn't super fast:

```
docker run --privileged -v /dev/bus/usb:/dev/bus/usb -e START_ADB_SERVER=true --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.1.2  -n 1 --browsertime.chrome.android.package com.android.chrome --browsertime.xvfb false --chrome.timeline https://www.wikipedia.com/
Google Chrome 67.0.3396.79 
Mozilla Firefox 61.0
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
ZY3222N2CZ	device

[2018-06-15 05:51:14] INFO: Versions OS: linux 4.13.0-45-generic nodejs: v8.11.1 sitespeed.io: 7.1.2 browsertime: 3.1.2 coach: 2.0.2
[2018-06-15 05:51:15] INFO: Starting chrome for analysing https://www.wikipedia.com/ 1 time(s)
[2018-06-15 05:51:15] INFO: Testing url https://www.wikipedia.com/ iteration 1
[2018-06-15 05:51:33] INFO: Converting video to 30 fps
[2018-06-15 05:52:11] INFO: 9 requests, 88.61 kb, backEndTime: 384ms, firstPaint: 972ms, firstVisualChange: 867ms, DOMContentLoaded: 1.10s, Load: 1.19s, speedIndex: 1019, visualComplete85: 1.17s, lastVisualChange: 2.80s, rumSpeedIndex: 972
[2018-06-15 05:52:13] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.wikipedia.com/2018-06-15-05-51-14
[2018-06-15 05:52:13] INFO: Finished analysing https://www.wikipedia.com/
```
Converting the video happens on your machine not the phone so it depends on the host you use.

Best
Peter

**Comment by Adesh** [comment]
Hi @soulgalore,

I
I think the problem is with my setup it Ubuntu is running with in the Windows through virtual box because of organizational restriction. And in virtual box 3d acceleration is off for our setup, which causes the video conversion a lengthy process.

Apart from that the loading time of a web page using chrome driver is also slow.

I am running the following command in a cron job.

**Comment by soulgalore** [comment]
Ok so is there anything we can do for you in this issue @Adesh ?

**Comment by Adesh** [comment]
Hi @soulgalore,

I will later post the output logs here (i don't have the access to the system for now).
We can close this issue for now.

Kind regards,
Adesh
