### ISSUE TITLE
Response times for individual Resource URLs e.g. images, css, js

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2083]
Is there a sample chart/table showing how to present the response times for images, css, js etc...

**Comment by soulgalore** [comment]
No you can only see that in the HAR/waterfall today, not one by one in a table. Maybe it would add value? Right now you can only see the slowest one in https://examples.sitespeed.io/6.0/2017-11-23-23-43-35/toplist.html

**Comment by softwareklinic** [comment]
I think it will certainly add value to see how the size is impacting the response times... and also, just the slowest # of resources is not per URL... Usually we run a test for a LIST of URLS... so the slowest will be across all ursl... we run about 190 or 200 urls per run... (from a text file) --- so that will defeat the slowest purpose

Example below

![image](https://user-images.githubusercontent.com/7537289/41664936-69c84eb4-746c-11e8-8198-e7f16c05466d.png)

**Comment by softwareklinic** [comment]
@soulgalore I will try this out and let you know how it works

https://github.com/gvalkov/harstats-graphite

**Comment by soulgalore** [comment]
I'm closing this because I don't think it will be implemented the coming year(s).
