### ISSUE TITLE
About Proxy adding latency to tests

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2085]
Hello Peter,

Is there a way Sitespeed can be enhanced to exclude the latency added by proxy.... we are running sitespeed from non-prod AWS servers to hit our production site and have to go via proxy....

**Comment by softwareklinic** [comment]
Yes, we have RUM and synthetic... but i see a huge difference in response
times when I compare a Sitespeed run directly from Azure/AWS (hosted
sitespeed) - vs.. the same hosted behind proxy... here are examples

Considering below to are far apart - thought of sharing this with you and
getting your inputs...

FROM AZURE HOSTED SITESPEED




FROM INTERNAL AWS HOSTED (BEHIND PROXY)






On Mon, Jun 25, 2018 at 2:33 PM, Peter Hedenskog <notifications@github.com>
wrote:

> Hey @softwareklinic
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_softwareklinic&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=9ZHWqDRSf2NuBcnV2OdvTLoEgyFMSIARfeNRMulpmbs&s=RneiGsUzKIt3ptgd4EVbFZmpuzzswgxA_NHGCJNC0UY&e=>
> so you mean you will remove some time fro, each metric? No, we don't have
> that. But does it matter? Thinking you will collect "correct" user times
> with RUM and then with the synthetic metrics you can spot regressions etc?
>
> Best
> Peter
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2085-23issuecomment-2D400067249&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=9ZHWqDRSf2NuBcnV2OdvTLoEgyFMSIARfeNRMulpmbs&s=WWzEVNRRK6F3ewb-rmhIYI9KY9XC7mySGTo_U1xPWyQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCifLpLSKH7Ix5XQdW-2DJoTrxu4SBaEks5uATrsgaJpZM4U2lWJ&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=9ZHWqDRSf2NuBcnV2OdvTLoEgyFMSIARfeNRMulpmbs&s=QBNHHWoQurbnEFwORMbvRuc_Jhu5PUO73KpciNsMPwU&e=>
> .
>



-- 
Regards,
Keyur
Cell: 2147845203

**Comment by soulgalore** [comment]
@softwareklinic so what diff do you see for backend time etc?

**Comment by softwareklinic** [comment]
Will share in few


Regards
Keyur

On Jun 26, 2018, at 7:42 AM, Peter Hedenskog <notifications@github.com>
wrote:

@softwareklinic
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_softwareklinic&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=XhYWHsMLosmXIieH34z6l5CXZ6PlaGb9gSp6e9dR7u4&s=sK0rqpqhWZhpDU4ZzNRpNDA3mk8HSekI3WebIVuTYTI&e=>
so what diff do you see for backend time etc?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2085-23issuecomment-2D400293515&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=XhYWHsMLosmXIieH34z6l5CXZ6PlaGb9gSp6e9dR7u4&s=D1YGmpZ20HhNMTSoT9vNlQEbHauvMfLxUJV_WjaPsl0&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCiTslXqllDbmxzBdYRLdG-5FJrndb43ks5uAiwfgaJpZM4U2lWJ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=XhYWHsMLosmXIieH34z6l5CXZ6PlaGb9gSp6e9dR7u4&s=M4Q2AkH4XZ2P6X7vKIi4A_o08ERRjJ2FzSFBis-2lp4&e=>
.

**Comment by softwareklinic** [comment]
Here is how it looks in AZURE - no proxy

![image](https://user-images.githubusercontent.com/7537289/41924790-8ae38050-7930-11e8-8c23-cd6d27655b98.png)

And below is with PROXY

![image](https://user-images.githubusercontent.com/7537289/41924833-9fe1b968-7930-11e8-95f4-d2199d774908.png)

**Comment by soulgalore** [comment]
Yeah but as long as you get reasonable stable metrics and the proxy doesn't do anything with the traffic, that's ok I think? Or how do you feel @softwareklinic ?

**Comment by softwareklinic** [comment]
I agree it atleast gives us comparable metrics before and after scenario.. but would definitely want to see if you can replicate this at your end.. and see whats adding the delay....

**Comment by soulgalore** [comment]
nothing more here to do.
