### ISSUE TITLE
--add-host not working

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2086]
Hi guys,

Apologies if this has been answered before.
I've noticed that using the docker flag --add-host does not seem to be working.  Is this due to the way sitespeed.io launches and does not take into account /etc/hosts?

This would be great to have the ability to tests to different CDN's.

Thanks,
scabs

**Comment by soulgalore** [comment]
Hey @scabenga I haven't tried, can you add an example so we can try? What host OS are you using?

Best
Peter

**Comment by scabenga** [comment]
HI @soulgalore 

I using the following to launch:
docker run -it --add-host news.sky.com:98.54.85.5 --shm-size=2g --rm -v "$(pwd)":/sitespeed.io

When i open a shell to the running container i can see the host has been added, but it seems the test ignores this.

*Domain and IP above are an example.

**Comment by scabenga** [comment]
@soulgalore , it seems an intermediate proxy was interfering here.  Thanks for checking it out, it's working after bypassing the proxy...
