### ISSUE TITLE
 [sitespeedio.queuehandler] TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by VarunRaje** [sitespeedio/sitespeed.io#2087]
Hi Team,

Hello Team,
I am facing below error while running sitespeed.io docker.

I am running below command

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.1.3 --preScript preScript.js --video --speedIndex --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 10000;} catch(e) {} return true;})()' --influxdb.host=${HOST} --influxdb.port=${PORT} --influxdb.database="sitespeed" -b chrome ${TEST} -n 1
`

```

[2018-06-28 12:44:17] ERROR: [sitespeedio.queuehandler] TypeError: Cannot read property 'id' of undefined
    at Object.getResultLogLine (/usr/src/app/node_modules/browsertime/lib/support/util.js:41:44)
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:114:19)
    at <anonymous>
From previous event:
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:17)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

```

**Comment by soulgalore** [comment]
Hey @VarunRaje it looks like we somehow doesn't create the HAR file correct for Chrome, is it possible to share some code or at least some pseudo code for what you do in the prescript, that would make it easier to find the bug?

Best
Peter

**Comment by VarunRaje** [comment]
@soulgalore in pre-script we simply login to our testing website with username and password. This script written in selenium and java script. elements are located by xpath. I am sure that xpaths are valid. because same is working in other scripts as well

**Comment by soulgalore** [comment]
Hmm could this be the same as #2091 ? @VarunRaje do you have a couple of URLs so I can test to reproduce?

**Comment by soulgalore** [comment]
I tried and I can reproduce this when using hash-URLs, so I think one of the problems is that we then create one HAR file with page (and maybe that is right?). Need to sync this with @tobli.

**Comment by soulgalore** [comment]
Using the new `--spa` should make this works out of the box.

**Comment by parag85** [comment]
Hello @soulgalore ,

I am facing issues with pre-defined script.
Latest docker installed before running the script, device already attached and all pre mentioned steps performed successfully.

 On your phone #

    Install Chrome
    Enable developer USB access to your phone: Go to About device (or About phone) in your settings, tap it, scroll down to the Build number, tap it seven (7) times.
    Disable screen lock on your device.
    Enable Stay awake in Developer options.
    Enable USB debugging in the device system settings, under Developer options.
    Install the Stay Alive app and start it.
    Plug in your phone using the USB port on your desktop computer.
    When you plugin your phone, click OK on the “Allow USB debugging?” popup.

Docker command:

docker run --privileged -v /dev/bus/usb:/dev/bus/usb -e START_ADB_SERVER=true --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.6.0  -n 1 --browsertime.chrome.android.package com.android.chrome --browsertime.xvfb false https://www.sitespeed.io
--------------------------------------------------

Error screenshot:
/home/qualitrix/Pictures/Screenshot from 2019-07-29 15-50-43.png

**Comment by soulgalore** [comment]
Hi @parag85 what OS are you using? Only Docker on Linux support mounting phones to Docker. 

Best
Peter

**Comment by parag85** [comment]
My host machine OS: Linux 18 and latest docker installed on the host machine and following same steps as mentioned above to connect the actual device but didn't get attached device details while running below command:

docker run --privileged -v /dev/bus/usb:/dev/bus/usb -e START_ADB_SERVER=true --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.6.0 -n 1 --browsertime.chrome.android.package com.android.chrome --browsertime.xvfb false https://www.sitespeed.io

**Comment by soulgalore** [comment]
Ok, hmm. Somehow the mount between your USB port and the Docker container doesn't work (can see on your output that where it would log the phone info it's just empty). Can you stop the adb-server on your host, so that that one doesn't take your connection to the phone?

You can also try by mounting per device (see https://www.sitespeed.io/documentation/sitespeed.io/mobile-phones/#driving-multiple-phones-from-the-same-computer) or try run without Docker.

**Comment by parag85** [comment]
![connect_issue](https://user-images.githubusercontent.com/8840359/62200329-ca342680-b3a2-11e9-878b-94e74440fd70.png)

/sys/bus/usb/devices/usb3/3-1/dev

Above is my connected device details, getting same issue

**Comment by soulgalore** [comment]
Did you stop adb on your host before starting the container?

**Comment by parag85** [comment]
Yes executed adb kill-server command and tried but same issue

**Comment by parag85** [comment]
Thanks dear, you are a gem:)
