### ISSUE TITLE
Yellow highlighted ROW - in waterfall

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2089]
Whats the significance of the yellow highlighted rows in waterfall

![image](https://user-images.githubusercontent.com/7537289/42098909-cfb0be48-7b81-11e8-88cd-9cb5f80e8ecd.png)

**Comment by soulgalore** [comment]
Hey @softwareklinic sorry, maybe that isn't clear. The yellow and the little round arrow means a redirect. If you click on the row you should see the response code.

Best
Peter

**Comment by softwareklinic** [comment]
Thank you  - closing
