### ISSUE TITLE
FullyLoaded Issue

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2092]
Hi Guys,

I'm using a --browsertime.pageCompleteCheck to say when the test should stop, however i've noticed that the fully loaded metric is sometimes a few seconds after the point at which i have requested the test to stop.  Is fullyLoaded not the point the actual test completes.

I've also noticed that the time on the video does not match the output metrics.
E.G: i'ved noticed that the test completes at say 20:00 however the lastVisualChange is sometimes after this 

![image](https://user-images.githubusercontent.com/8235483/42376239-a5fd401a-811e-11e8-8589-79d94b116c6e.png)

Thanks,
scabs

**Comment by soulgalore** [comment]
Hi @scabenga 
at the moment fullyLoaded uses the resource timing API (I think we set max value to 600 requests), so it isn't perfect. Been thinking about moving the fully loaded to check the HAR (we got that implemented in PageXray but we haven't moved that on yet to sitespeed.io, I guess that could be something for sitespeed.io 8).

> E.G: i'ved noticed that the test completes at say 20:00 however the lastVisualChange is sometimes after this

ok, can you provide an example so we can reproduce, it will make it easier to find the bug, thanks!

Best
Peter

**Comment by scabenga** [comment]
Thanks @soulgalore, i'll see if i can get an example together.
With regards to the --browsertime.pageCompleteCheck, does this stat get recorded, so when we can see exactly when we stopped the test?

**Comment by soulgalore** [comment]
> --browsertime.pageCompleteCheck, does this stat get recorded,

no.

**Comment by soulgalore** [comment]
In 8.0 this is fixed and we always use fully loaded from the HAR.
