### ISSUE TITLE
ERROR: EISDIR: illegal operation on a directory for images in page data

### ISSUE THREAD

**Issue by ant71** [sitespeedio/sitespeed.io#2093]
Using the latest version (7.2.0) via docker-compose on MacOS 10.12.6, and for every version tested that is newer than 6.5.3, the following error is returned for each iteration run;

ERROR: Error: EISDIR: illegal operation on a directory, unlink '/[PATH]/[TO]/[TEST]/[RESULTS]/[TEST DATETIME]/pages/[HOST]/data/video/images''

(yes, there is an extra trailing ' - it is not a typo).

I tested working backwards against various earlier releases. Versions 7.2.0, 7.1.3, 7.1.0 and 7.0.0 (all on Node 8.11.1) returned the same error on each run. Version 6.5.3 (Node 8.9.4) ran without this error.

Example command used to run tests;
docker-compose run --rm sitespeed.io --browsertime.browser chrome --browsertime.connectivity.profile native --browsertime.connectivity.engine tc --graphite.host=graphite --graphite.auth=[user]:[pass] /sitespeed.io/sitespeed-runs/urls.txt

**Comment by soulgalore** [comment]
Hi @ant71 thanks for the report.

Could it be that the URLs you are testing are the same except that they have different hashes at the end? The name of the dirs are generated from the file name but the hashes are skipped. I don't remember though that that should have been changed between 6 and 7 (do you @tobli?).

If that's the case you should try to give each URL a alias, checkout the alias section: https://www.sitespeed.io/documentation/sitespeed.io/configuration/#analyse-by-urls

If that doesn't work, please provide the URLs that you are testing so I can try to reproduce.

A couple of other things I noticed:
* tc as connectivity engine was removed in 6 (https://www.sitespeed.io/sitespeed.io-6.0/) so you need to either use Docker networks or throttle to set the connectivity. We have a guide [here](https://www.sitespeed.io/documentation/sitespeed.io/connectivity/).
* using docker-compose isn't always the best, checkout https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#production-guidelines

Hope it helps!

Best
Peter

**Comment by ant71** [comment]
Thanks for the quick reply @soulgalore .

I am only running it locally at the moment, so docker-compose is a great, simple way to spin it up in that scenario.

URLs that were tested were;
https://iview.abc.net.au/
https://iview.abc.net.au/channel/abc1
https://iview.abc.net.au/channel/abc2
https://iview.abc.net.au/shows
https://iview.abc.net.au/shows/cc
https://iview.abc.net.au/show/peppa-pig

None of the URLs contain hashes, and all URLs are throwing the error on each iteration.

I did try adding aliases as per the documentation, but got the same error.

Thanks for the tip about connectivity, it was a hang over from when I was using older versions. I removed that before re-running - just in case - but still got the same result.

**Comment by ant71** [comment]
Further info, and apologies, but I omitted that I was using a config.json and did not include the information from that. I have been able to identify the change to a config that causes the error.

By simplifying the config, I can regularly have the error occur by the following changes.

This config throws the error on each iteration;

`{
  "browsertime": {
    "visualMetrics": true,
    "video": false
  }
}`

This one doesn't;

`{
  "browsertime": {
    "visualMetrics": true,
    "video": true
  }
}`

Neither does this one;

`{
  "browsertime": {
    "visualMetrics": true
  }
}`

So, it looks to be a combination of having visualMetrics being captured and trying to remove the video that causes the error.

**Comment by soulgalore** [comment]
Hi @ant71 thanks for sharing the URLs. Ah I see now, sorry I didn't follow the path structure that you should with the error. It comes from when Visual Metrics creates the filmstrip from the video (we produce the strip but do not use them). As a quick fix, could you try to disable the filmstrip by adding `--browsertime.videoParams.createFilmstrip false`?

I tried to reproduce on my Mac:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io urls.txt -n 1` (using the same URLs) and even with docker-compose but I didn't get the error. I wonder do you set  `--outputFolder`? sitespeed.io should support it, but could be that we have missed checking the image dir before we create that? Usually when I use outputFolder, I use it in Jenkins and then remove/move the result. 

Best
Peter

**Comment by ant71** [comment]
I just tried running with `--browsertime.videoParams.createFilmstrip false` and can confirm I am not setting `--outputFolder` at all. The error still occurred.

I did try simplifying things as much as possible, by removing config json and running directly with the docker command you used.

I can reproduce the error in this way;

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 1 --browsertime.visualMetrics true --browsertime.video false https://iview.abc.net.au`

This returns the error;

`ERROR: Error: EISDIR: illegal operation on a directory, unlink '/sitespeed.io/sitespeed-result/iview.abc.net.au/2018-07-12-00-33-14/pages/iview.abc.net.au/data/video/images''`

The error does not appear if I change the `--browsertime.video` value to true (or removing it entirely) i.e.

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 1 --browsertime.visualMetrics true --browsertime.video true https://iview.abc.net.au`

It would be interesting to see if that can be replicated at your end.

By the way, none of this is presenting a particular problem for me as I can work around it.

**Comment by soulgalore** [comment]
Ok. @ant71 can you share exactly how you run with full config?

@tobli @beenanner do you have a quick look and check if I have missed something?

**Comment by Sly777** [comment]
hey @soulgalore. I'm also getting the same error on the latest version of Sitespeed on docker-compose (with graphite). You can find the full config below.

`
{
    "browsertime": {
        "connectivity": {
            "profile": "3gfast"
        },
        "video": false,
        "visualMetrics": true,
        "iterations": 5,
        "chrome": {
            "timeline": true
        }
    },
    "chrome": {
        "timeline": true
    },
    "crawler": {
        "depth": 1
    },
    "plugins": {
        "remove": ["screenshot"]
    },
    "graphite": {
        "host": "graphite"
    },
    "utc": true,
    "mobile": true,
    "video": false,
    "firstParty": ".helloworld.com"
}
`

**Comment by soulgalore** [comment]
Hi @Sly777 and @ant71 seems there's some mismatch when turning off the video but keeping visual metrics, I could reproduce it now and could best case roll out a fix tonight.

Best
Peter

**Comment by soulgalore** [comment]
I've pushed a new version of Browsertime with a fix, it work on my local but I'm having very limited internet connectivity so I couldn't run too many test.

Do you have the time to verify that it works for you before I release a new version of sitespeed.io? You can either build the docker container from your checkout (master): `docker build -t sitespeedio/sitespeed.io .`

Or you can use our auto-build that will be up in 10-15 min: `docker run sitespeedio/sitespeed.io-autobuild:latest ...`

Best
Peter

**Comment by soulgalore** [comment]
Released 7.2.2, please have a go when you have time.

**Comment by ant71** [comment]
Sorry I have only just got back now, I've been out of action.

I have just tried 7.2.2 and can report that the error is no longer appearing.

Thanks for all your great work on this project!
