### ISSUE TITLE
NEW Plugin with Docker not able to create

### ISSUE THREAD

**Issue by BPrathap** [sitespeedio/sitespeed.io#2095]
In Dockerfile

FROM sitespeedio/sitespeed.io:latest

# TODO <CUSTOMIZED PLUGIN>
COPY ./plugin/sample test

VOLUME /test.ui

WORKDIR /test.ui

/*sample/index.js*/

const path = require('path');

module.exports = {
  name() {
    // This is ... shocking news: the name of the plugin
    return path.basename(__dirname);
  },

  open(context, options) {
    // when sitespeed.io start it calls the open function once for all plugins
    // the context holds information for this specific run that
    // generated at runtime, for example you can get hold of the storageManager
    // that stores files to disk.
    // The options is the configuration supplied for the run.
  },
  processMessage(message, queue) {
    // The plugin will get all messages sent through the queue
    // and can act on specific messages by type:
    // message.type
  },
  close(options, errors) {
    // When all URLs are finished all plugins close function is called once.
    // Options are the configuration options and errors a array of errors
    // from the run.
  }
};

then

docker build -t test .

docker run --shm-size=1g --rm -v "$(pwd)":/test test https://www.google.com --plugins.list -n 1 --plugins.add test

ERROR

ouldn't load plugin /test.: Error: Cannot find module '/usr/src/app/lib/plugins/test.'
[2018-07-10 12:12:24] ERROR: Error: Cannot find module '/test.'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Promise.resolve.map.name (/usr/src/app/lib/core/pluginLoader.js:61:18)
From previous event:
 

or you try to  bake this plugin (https://github.com/sitespeedio/plugin-gpsi) as part of docker

**Comment by soulgalore** [comment]
Hi @BPrathap thanks for creating the issue. It works like this (I'll update the docs to makes it easier to understand later on): if the path to the plugin is without any path at all, sitespeed.io will look for the plugin in the plugin folder (that what happens now). If you change the path to be absolute, it will find the plugin wherever you put it inside of the container.

Best
Peter

**Comment by BPrathap** [comment]
Thanks @soulgalore.   I just copied ,ENV PLUGINDIR=/usr/src/app/lib/plugins

COPY ./plugin/test $PLUGINDIR/test and start using  without path.
