### ISSUE TITLE
Ignore SSL certificate 

### ISSUE THREAD

**Issue by sureshkrishnaselvam** [sitespeedio/sitespeed.io#2098]
Hi Peter,

I want to ignore ssl certificate using docker command, Tried few things but dosen't worked out. Please see the docker command and error log,

Docker Command:
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.2.0 --browsertime.chrome.args ignore-certificate-errors https://www.xxxx.com

Error Log:
ERROR: UrlLoadError: Failed to load/verify https:xxxx.com uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:194:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by soulgalore** [comment]
Hi @sureshkrishnaselvam thanks for reporting the issue! Is your URL internal or can you share it? Tried with `docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.2.0 --browsertime.chrome.args ignore-certificate-errors https://www.sitespeed.io` and it worked. 

Also just want to verify that the URL works if you skip the ignore parameter?

Best
Peter

**Comment by sureshkrishnaselvam** [comment]
Thanks for looking into this issue, Its internal url.

**Comment by soulgalore** [comment]
Ok, and it works without the ignore param? Can you also try with Firefox? `-b firefox --browsertime.firefox.acceptInsecureCerts`

**Comment by sureshkrishnaselvam** [comment]
Yes tried without ignore param also in chrome and getting same, now with the firefox browser getting below error,

ERROR: Could not load URLBrowserError: Running page complete check 
return (function() {
    try { 
        var end = window.performance.timing.loadEventEnd;
        return (end > 0) && (Date.now() > end + 2000);
    } catch(e) {
        return true;
    }
})();
 took too long for https://www.xxx.com
[2018-07-13 12:05:26] ERROR: UrlLoadError: Failed to load https://www.xxx.com
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:185:13)
    at <anonymous>

**Comment by soulgalore** [comment]
Ok, then I think the problem is that the URL isn't reachable from within your Docker container. Do you have host file on your computer with the domain, can you reach the server by IP?

**Comment by sureshkrishnaselvam** [comment]
Hi Peter, 
Thanks for your comments, I got the IP address and checked it, its not reachable but I am able to hit the url in browser and the page is loading fine. Any idea on this.

**Comment by soulgalore** [comment]
Hi @sureshkrishnaselvam do you have anything special in your host file? Maybe try add `--net=host` to Docker when you run (docker run --net=host ...).

Best 
Peter

**Comment by sureshkrishnaselvam** [comment]
Hi @soulgalore Docker is not recognising any url when I connect to VPN network, is there any possible options to resolve this issue.

**Error Log:**
ERROR: UrlLoadError: Failed to load/verify https:xxxx.com uri:chrome-error://chromewebdata/
at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:194:15)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by soulgalore** [comment]
Hi @sureshkrishnaselvam maybe something like this https://stackoverflow.com/questions/33904647/docker-container-and-host-network-vpn#36185896 else had over to the [Docker forums](https://forums.docker.com/) and check there.

Best
Peter

**Comment by quartex** [comment]
Hi,
use NODE_TLS_REJECT_UNAUTHORIZED=0 in docker enviroment ?

**Comment by sureshkrishnaselvam** [comment]
Hi @soulgalore Thanks for the update, I have tried restarting docker after connecting to VPN but that doesn't worked getting the same error.

Hi @quartex Thanks for ur suggestion, could you help me how to use NODE_TLS_REJECT_UNAUTHORIZED=0

docker run -e http_proxy='http://xxxx.com:8080' -e https_proxy='http://xxxx:8080' node_tls_reject_unauthorized=0 --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.2.0 -n 1 https://xxxx.com/

**Comment by jdunc** [comment]
just wondering what was the solution to this? @sureshkrishnaselvam

**Comment by hash0307** [comment]
I was sort of facing similar issue, where I am unable to access https URL from within the Docker container. 
Could you please share/update if we found any solution for this ? @soulgalore @sureshkrishnaselvam
