### ISSUE TITLE
Adding Multiple Cookies

### ISSUE THREAD

**Issue by roymartinezblanco** [sitespeedio/sitespeed.io#2099]
Hi, 

I need to add multiple cookies to the test that I want to do but I can't seem to find a way.
I've tried to use the following:
`--browsertime --cookie`
`--browsertime.cookie`
`-r` 

But I can't seem find a way to add more than one cookie without getting the error "ERROR: TypeError: options.cookie.substring is not a function"
`docker run --shm-size=2g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io  -r "GeoZipCode=33120" -r "ZipCode=33120" 'https://www.example.com/'`

**Comment by soulgalore** [comment]
Hi @roymartinezblanco yep at the moment we only support one cookie. I pushed the change on my way to the vacation and did not have the time to fix multiple support. Feel free to do a PR in https://github.com/sitespeedio/browsertime-extension (that what's we use to set the cookie). Else I will have a look asap when I have the time.

Best
Peter

**Comment by soulgalore** [comment]
Btw I could probably fix it the coming days, it's a little hacky to jump into the extensions ... I'll keep you posted when I start.

**Comment by roymartinezblanco** [comment]
Thanks, that confirms that am not doing something wrong 👍. For the sake of speed I'll just use a local webproxy to do all the header handling. thanks

**Comment by soulgalore** [comment]
FYI @roymartinezblanco I pushed a updated version of Browsertime (3.2.1) today and will let it run on our test server tonight and then push a new version tomorrow of sitespeed.io with multiple cookies support.

**Comment by soulgalore** [comment]
@roymartinezblanco we released 7.2.1 yesterday that fixes the multiple cookie issue, tanks for filing the task!
