### ISSUE TITLE
Unrecognized option 'draw_mouse' error

### ISSUE THREAD

**Issue by sureshkrishnaselvam** [sitespeedio/sitespeed.io#2100]
I am getting the following error while running the site speed to capture visual metrics.

bin/sitespeed.js --visualMetrics https://www.sitespeed.io/

**_Error_** 
Unrecognized option 'draw_mouse'.
Error splitting the argument list: Option not found

ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /var/folders/th/v6v16nh55tg2s39b6_clv4ph0000gq/T/browsertime-kxCNuc/x11.mp4

I am using latest version ffmpeg in Mac.
Also I used visual metrics check and it passed. python visualmetrics.py --check

ffmpeg:   OK
convert:  OK
compare:  OK
Pillow:   OK
SSIM:     OK

Please help to resolve this issue..

**Comment by soulgalore** [comment]
Hi @sureshkrishnaselvam at the moment you need to run on Linux to get video to work. We used to kind of had support a version or two ago but I think that ever actually worked 100%. 

Best
Peter

**Comment by sureshkrishnaselvam** [comment]
Thank You will do it in Linux..Will it work in Windows?

**Comment by soulgalore** [comment]
Hey @sureshkrishnaselvam sorry no Windows, only Windows through Docker. Keeping a Windows version up to date is to much work for our small team, we need to have one that is Windows dedicated to make that happen. For Mac, I would like to make that work again (it's good for testing) but I'm not sure when.

Best
Peter

**Comment by sureshkrishnaselvam** [comment]
Thanks Peter
