### ISSUE TITLE
Annotation/event/tag graphite question 

### ISSUE THREAD

**Issue by Svampen** [sitespeedio/sitespeed.io#2102]
Hi 
Is it possible to add custom annotation/event/tag during runs to the wards graphite, to build dashboard on grafana? 
Our scenario is that we want to track site speed changes on different development branches. Where we would run builds every x hour from different branches and the same url. 
Right now I have build id and url on grafana with the help of graphite.namespace but it's not enough... Is it possible to extend this with sitespeed.io or do I need to add this annotation/event/tag afterwards with a script?
Thanks for any help and for an awesome product!

**Comment by soulgalore** [comment]
Hi @Svampen thanks for the kind words :) 

There's no way to add extra things than to change the namespace (we haven't added support for tags yet) but it would be great to add. Let us iterate together how we can solve this. Right now most of us are [on vacation](https://github.com/sitespeedio/sitespeed.io#vacation-july---august) but maybe we can do a PR together if we can finalize exactly how it would work.

Best
Peter

**Comment by Svampen** [comment]
Hi

Sure, sounds great.
In the mean time I will look into adding extra tags to existing events in graphite so that we can start using sitespeed :)

**Comment by soulgalore** [comment]
So do you mean that adding tags to the current annotation would help (the annotation with the link to the HTML result)? Or do you need tag support for Graphite? The first one would be easy (I can guide you to do a PR for that if you need), the other one needs more work (I think).

**Comment by Svampen** [comment]
Hi

I worked out a solution that works for us and I will try to explain it.

We want to see the trend of our feature branches, to keep track of any degradation or improvements that happens during development. We run this through Jenkins every 3h towards the same AWS instance (by just changing the build). At the moment we have 4 branches but new ones are created as we go a long in our development cycle, mostly for every new feature.

I changed so that the namespace is now the branch name that the build on our AWS instance is running, which makes it easier to specify in grafana, but we are still missing the info of which build/commit has been tested.
What I did to fix that is to add event to graphite after sitespeed has run with the buildId, commit, link to S3... I do this by curling graphites http api for the latest event in order to use the same 'when' (timestamp). This is the part that would be great to have in sitespeed.

Does that make sense? Maybe there is a more obvious way of doing this that I've not thought of as I've only worked with sitepseed, grafana and graphite for a week now :)

**Comment by soulgalore** [comment]
Ok cool. Two things:
* If it's possible to add tags to the current annotation that we send, would that help you so you could skip your event? 
<img width="487" alt="screen shot 2018-07-23 at 18 52 16" src="https://user-images.githubusercontent.com/540757/43091119-98210bb4-8ea9-11e8-9552-a6463c1892a7.png">
* Another solution that I know people use is to put the build number in the HTML, so it' reachable from JavaScript and then use `--script`  and feed your JavaScript and pickup the metrics (it will automatically be sent to Graphite if I remember correctly, you just need to find it). But it need to be a number then to be handled correctly.

**Comment by Svampen** [comment]
Yes and also if it would be possible to extend/customize the data field in the event. For our example to have links directly to to GitHub commit and/or branch

Thanks for the info about the build number in the HTML, I will investigate that a bit too

**Comment by soulgalore** [comment]
Ah I see! That is a really good idea, I've pushed a branch just now where you can append HTML to the annotation message (the link that today show Result X run(s)). I'll merge that ASAP, could you try it out before I release it? 

You can test it with using our auto build container **sitespeedio/sitespeed.io-autobuild:latest**   with `--graphite.annotationMessage` - the message can be HTML so you could create your link directly to your branch. The build will be ready in 15 min when I merged. 

I also prepared a branch where you can attach more tags, but I'm thinking append a message (where you could put whatever) is more useful?

**Comment by soulgalore** [comment]
Released both of those in 7.3.0 just now.

**Comment by Svampen** [comment]
Nice. I will try to give it a try later today if I get the chance.

**Comment by soulgalore** [comment]
Cool, wait for 7.3.1 because of a bug ...

**Comment by Svampen** [comment]
I've pulled in the 7.3.4 docker now and updated my script to use it, so I will try it out tomorrow with the new flags

**Comment by soulgalore** [comment]
Hi @Svampen let me update the docs. The easiest way (always) to get parameters with " or ' is to start with a " (that starts the String as the parameter in) and then inside the HTML always use '. That way the CLI tool we use now that it's one String that comes and will pass that into sitespeed.io.

So for example:
`--graphite.annotationMessage "Mobile_1022  <a href='https://github.com/***' target='blank'>commitsha</a>"`

I'll update the docs and tag the issue.

**Comment by soulgalore** [comment]
https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#how-do-you-pass-html-as-a-cli-parameter

**Comment by soulgalore** [comment]
This should work now.
