### ISSUE TITLE
Total requests - (XHR)

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2103]
Hi,

I noticed a difference in the number of requests passing from sitespeed instead of making them directly to the browser (chrome).
Are the ajax requests (XHR) not counted (if any) in sitespeed?

Docker: sitespeedio / sitespeed.io: 7.2.1
OS: Windows 10

I remain available if you need more information.

Thanks

**Comment by soulgalore** [comment]
Hi @amic81 you can check the HAR file and see if the request is included (we take the total from the HAR if I remember it correctly). Use pageCompleteCheck to choose when to end the test.
Best
Peter

**Comment by soulgalore** [comment]
You can also use the new --spa that should fix most problems since it waits on responses in the resource timing api.
