### ISSUE TITLE
confuse about getting summary scores from influxdb

### ISSUE THREAD

**Issue by Tangyiming** [sitespeedio/sitespeed.io#2111]
![_20180724104435](https://user-images.githubusercontent.com/18328731/43113961-2312690e-8f2f-11e8-9b2a-a74564a496f5.png)
i want to get the four scores show in summary page from influxdb ,so i query with this:
`select * from score where category='Test_180724100930' and summaryType='summary'`

but there are two group of scores as below:

![_20180724104603](https://user-images.githubusercontent.com/18328731/43113974-35c878b8-8f2f-11e8-822f-ada2ba9069d3.png)

i'm confused , why the scores in summary page is only one group's score? 
maybe i can use just another group's scores to show in  summary page ?

maybe it's not correct to test multiple domain's url,i think when i test more than one domain's urls，the scores will grouped into different domains scores,but the summary page only show one group's score,right?

**Comment by soulgalore** [comment]
Hi @Tangyiming sorry for the confusion. If I remember correctly we only send per domain/group to influxdb/graphite.  In the HTML I need to check, either we cheat and only show one of them (we don't have "multiple" domains level at the moment) or we have a total. 

The idea we had from the beginning was that if you need stats from multiple domains in Graphite/InfluxDB you could calculate them yourself. They will not be 100% correct though I guess.

Best
Peter

**Comment by Tangyiming** [comment]
@soulgalore thank you for the explaination!
i will run test one domain one time 😄
