### ISSUE TITLE
Error when trying to disable multiple plugins

### ISSUE THREAD

**Issue by obihill** [sitespeedio/sitespeed.io#2122]
Hi,

I'm using the docker version of sitespeed, version 7.2.0 [running on my Mac OS], and it's working quite well.

However, I have an issue when trying to remove multiple plugins [following the instructions in the documentation]. When I run the code below:

```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io -v "/path/to/my/custom/volume:/custom_vol" sitespeedio/sitespeed.io:7.2.0 http://www.anydomain.com --plugins.add /custom_vol/my_custom_plugin --plugins.remove html harstorer --plugins.list -b chrome -n 2
```

I get the following error:

```
throw new Error(`Couldn't find url file at ${filePath}`);
```

The reason I'm trying to disable these plugins is because I have a custom plugin that generates the exact data that I need, so I want to disable what sitespeed generates by default.

**Comment by soulgalore** [comment]
Hey @obihill ah sorry I think the documentation page is wrong, the --help option is right though:

```
--plugins.remove  Extra plugins that you want to run. Relative or absolute path to the plugin. Specify multiple plugin names separated by comma, or repeat the --plugins.remove option
```
This should work:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io -v "/path/to/my/custom/volume:/custom_vol" sitespeedio/sitespeed.io:7.2.0 http://www.anydomain.com --plugins.add /custom_vol/my_custom_plugin --plugins.remove html --plugins.remove harstorer --plugins.list -b chrome -n 2`

I'll update the doc asap.

Best
Peter

**Comment by soulgalore** [comment]
Docs updated.
