### ISSUE TITLE
Running tests with a connectivity profile "3g" and "cable" gives the same result

### ISSUE THREAD

**Issue by Vickgrego** [sitespeedio/sitespeed.io#2125]
Hi!
I run sitespeed.io tests with config.json
`{"browsertime":{"browser":"chrome","iterations":1,"connectivity":{"profile": "cable" }}`
and another test with config.json
`{"browsertime":{"browser":"chrome","iterations":1,"connectivity":{"profile": "3g" }}`

The command is the basic one
` docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --config config.json url.txt `
I run Linux Ubuntu 16.04 kernel 4.4.0-130-generic

It seems to me, that "profile":"3g" and "profile" "cable" gives the same metrics
Here are the results https://prnt.sc/kf9mlf and https://prnt.sc/kf9mdu
In the same case, WPT gives a different result for 3g and cable (you can see it from the screenshots).

I do read https://www.sitespeed.io/documentation/sitespeed.io/connectivity and when following this documentation I managed to get slightly slower results for 3G (however, it was very tiny margin, less than 0.5 second for 3g, what makes me wonder).

Please, advise me what `connectivity":{"profile": "3g" }` is for in first place? Does it suppose to affect test result? Does it require additional configuration to be provided?
Thank you for the wonderfull tool!

**Comment by Vickgrego** [comment]
Full config.js file
`{"browsertime":{"browser":"chrome","iterations":1,"connectivity":{"profile": "cable" },"viewPort":"1920x1080","delay":"3000"},"crawler":{"depth":1}, "outputFolder":"output/1","utc":true,"webpagetest":{"key":"A.11111111111111111","connectivity": "Cable", "location": "Dulles"}}`

**Comment by soulgalore** [comment]
Hi @Vickgrego 
the connectivity is only affecting if you run your test with Browsertime (the tool provided by sitespeed.io), for WebPageTest you need to configure it in the wpt config (I can show that later when I’m back on my computer).

For setting connectivity you need to either setup different docker networks or use throttle, I didn’t see anything of that in your config. The docs at https://www.sitespeed.io/documentation/sitespeed.io/connectivity/ should explain how you should do it, else let us know how we can do it better!

Best
Peter

**Comment by Vickgrego** [comment]
I run 
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --config config.json url.txt`
Where config.json provided above.
And Browsertime metrics were the same for 3g and cable profile.

After implementing https://www.sitespeed.io/documentation/sitespeed.io/connectivity/  the metrics became different for 3g and cable.

I just don't get why I need provide `"connectivity":{"profile": "cable" }` if all job is made by docker:
`docker network create --driver bridge --subnet=192.168.33.0/24 --gateway=192.168.33.10 --opt "com.docker.network.bridge.name"="docker1" 3g
tc qdisc add dev docker1 root handle 1: htb default 12
tc class add dev docker1 parent 1:1 classid 1:12 htb rate 1.6mbit ceil 1.6mbit
tc qdisc add dev docker1 parent 1:12 netem delay 150ms`

Did I miss something here?

**Comment by soulgalore** [comment]
Ah I see. `"profile": "cable" ` is just the name, so we internally can use it for keys in graphite or friendly name when we display the connectivity setting. It isn't needed for actually setting the connection, you are right.  In older versions of sitespeed.io we changed the connectivity inside the container with tools like TSProxy or tc but they wasn't working correctly for us (so the naming is kind of legacy).In Docker there's no way today (that we know of) where you completely can change up/download speed just inside the container, you need to do it with network or give the container the right to change the network and use **modprobe** (on Linux).

**Comment by soulgalore** [comment]
I've updated the docs and the cli-help, the cli help and config section (auto-generated) will pop up at next release.
