### ISSUE TITLE
TypeError: preScript.run is not a function

### ISSUE THREAD

**Issue by magimenon** [sitespeedio/sitespeed.io#2126]
I'm getting a typeError while running the below command.
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:latest  --config config.json https://www.diverchev.com --preScript test.js

ERROR: TypeError: preScript.run is not a function
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:105:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

OS - MacOs

**Comment by soulgalore** [comment]
HI @magimenon without your preScript it is super hard to know what's wrong, is it possible for you to include it? Have you followed the examples at https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/#debuglog-from-your-script ?

Best
Peter

**Comment by soulgalore** [comment]
Missing info. And for 8.0 there's a new structure for preScript to follow the new scripting structure.

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore ,
i followed prescript given on :  https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/#debuglog-from-your-script 

It works fine for most of the login sites. But Our site Login Page url redirects with tokens and session id. So i tried using selenium as prescript.
Below is code 

module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      // Go to Wikipedias login URL
      return driver.get('https://mysite/login')
        .then(() => {
          
          // we fetch the selenium webdriver from context
          const webdriver = context.webdriver;
          // and get hold of some goodies we want to use
          const until = webdriver.until;
          const By = webdriver.By;

          // before you start, make your username and password
          const userName = 'harrypotter@yopmail.com';
          const password = 'password1234';

          driver.findElement(By.id('home__formMemberEmail_username_username')).sendKeys(userName);
          driver.findElement(By.id('home__formMemberEmail_pass1_password')).sendKeys(password);
          driver.findElement(By.className('btn btn-block baseButton btn-primary activated')).click();
          // we wait for something on the page that verifies that we are logged in
          return driver.wait(until.elementLocated(By.className('user-id')), 10000);
        });
    })
  }
};

On running using docker command on windows -
docker run --rm -v %cd%:/sitespeed.io sitespeedio/sitespeed.io:12.3.1 --preScript /sitespeed.io/script4.js https://mysite/dashboard

i get error as : TypeError : Prescript is not a function.

Please help.

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell I think you use an old structure of the preScript, could it be have an old non updated documentation somewhere? 

The template should look like this (no run etc):
```
module.exports = async function(context, commands) {

};
```

**Comment by amitmalhotra-cell** [comment]
Thanks for reply.
Initially i used it as below -

module.exports = async function(context, commands) {
  await commands.navigate('https://mysite/login');
try {
  await commands.addText.byId('harrypotter@yopmail.com', 'home__formMemberEmail_username_username');
  await commands.addText.byId('password1234', 'home__formMemberEmail_pass1_password');
  // find the submit button and click it
  await commands.click.byclassNameAndWait('btn btn-block baseButton btn-primary activated');
   // we wait for something on the page that verifies that we are logged in
    return commands.wait.byclassName('user-id',20000);
   
} catch (e) {
  commands.error('User login failed');
  }

};

But as i said , this code works for normal login sites , my site login page flow redirects to another url with tokens and sessionid so this code fails to authenticate user.
like
"https://mysite/login"  url redirects to below

//account-mysite.com/?SAMLRequest=fZLBbsIwDIZfpcq9bQgUaERBaAgNiU0Tgx12i1ID0ZqkxCkFnn5dGRM7bNfE9uf&#x2f;S0aTky6CIzhU1mSkE1ESgJE2V2aXkc16Hg7JZDxCoQtW8mnl92YFhwrQB1NEcL5pe7AGKw3uFdxRSdislhnZe18ij2Oha3GW1hiQPhSlkA524UFE9sOL0sFRQR1Jq2NEG7eQmFqhsai0uaweTTHcr&#x2b;l&#x2b;QIK5dRJafEa2okAgwWKWEZUPKaMJ7Sa0n9A0HfQZZYz20m7abyoQK1gY9ML4jDQ3NKQsZIM1HXJGeY9FaZK8k&#x2b;DtFp99xW&#x2b;EGOTXxBmpnOFWoEJuhAbkXvLX6dOSN6W8dNZbaQvyLYi3QHc&#x2f;4f8B4qaQjG&#x2f;C6rpu5VyttEbw6jVscEeVg4uxvFzO&#x2b;uK126nKC3dyLh&#x2f;F9yv8vNhzw1zMXmyh5PlLohb&#x2b;75U6Uac9UXm4bUt5ZbAEqbYKchKPvxm&#x2f;&#x2f;8H4Ew&#x3d;&#x3d;&RelayState=&#x25;2Foauth2&#x25;2Fv1&#x25;2Fauthorize&#x25;2Fredirect&#x25;3Fokta_key&#x25;3DvFgzbxnAzWM3uqO1rTln1od5lXjSnRrETYC2c4gXG4M

Above url contains username, password and Login submit button . 

i also tried below below SELENIUM code :
module.exports = async function(context, commands) {
  // we fetch the selenium webdriver from context
    const webdriver = context.webdriver;
    const driver = context.driver;

     context.log.info('Prescript Started');
     await driver.get('https://mysite/login');

     try {
driver.sleep(10000);
    await driver.findElement(webdriver.By.id('home__formMemberEmail_username_username')).sendKeys('harrypotter@yopmail.com');
    await driver.findElement(webdriver.By.id('home__formMemberEmail_pass1_password')).sendKeys('password1234');
    // find the sumbit button and click it
    await driver.findElement(webdriver.By.className('btn btn-block baseButton btn-primary activated')).click();

     } catch (e) {
    context.log.info('User login failed');

    }
context.log.info('Prescript ended');

};

But it gives me error :  TypeError: Cannot read property 'get' of undefined

**Comment by soulgalore** [comment]
So many things has changed since 2018, closing but let me know if this is still an issue.
