### ISSUE TITLE
Getting error while sending metrics to graphite

### ISSUE THREAD

**Issue by magimenon** [sitespeedio/sitespeed.io#2130]
I'm trying to send the metrics to graphite. I followed the below documentation: https://www.sitespeed.io/documentation/browsertime/graphite/

I can the below command - docker run --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime:3.3.0 --video --visualMetrics  --resultDir ~/tmpDir  https://www.sitespeed.io/ -n 5

After running 5 interations I get a message in my console Wrote data to ../Users/xxx/tmpDir

And now when I run the below command: echo "browsertime.your.key.SpeedIndex.median" $(cat ~/tmpDir/browsertime.json | jq .statistics.visualMetrics.SpeedIndex.median) "`date +%s`" | nc -q0 my.graphite.com 2003

I get the below error:
nc: invalid option -- q
Try `nc --help' for more information.
cat: /Users/xxx/tmpDir/browsertime.json: No such file or directory
-bash: echo: write error: Broken pipe

Where does the file gets created?

- OS - MACOS

**Comment by magimenon** [comment]
I'm trying to send the metrics to graphite. I followed the below documentation: https://www.sitespeed.io/documentation/browsertime/graphite/

I can the below command - docker run --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime:3.3.0 --video --visualMetrics  --resultDir ~/tmpDir  https://www.sitespeed.io/ -n 5

After running 5 interations I get a message in my console Wrote data to ../Users/xxx/tmpDir

And now when I run the below command: echo "browsertime.your.key.SpeedIndex.median" $(cat ~/tmpDir/browsertime.json | jq .statistics.visualMetrics.SpeedIndex.median) "`date +%s`" | nc -q0 my.graphite.com 2003

I get the below error:
nc: invalid option -- q
Try `nc --help' for more information.
cat: /Users/xxx/tmpDir/browsertime.json: No such file or directory
-bash: echo: write error: Broken pipe

Where does the file gets created?

- OS - MACOS

**Comment by soulgalore** [comment]
Hi @magimenon 
when you run Docker all files are created within the Docker container. To get the files out of Docker, you can then mount volumes from your host OS to the Docker container. That is what you do with `-v "$(pwd)":/browsertime-results ` - It means that you map your current dir (pwd) to the /browsertime-results folder inside of the container. So everything inside the container inside of /browsertime-result will be available outside of the container in your current dir (pwd).

With `--resultDir ~/tmpDir` you are setting the tmpDir of the home directory of the user inside of the Docker container, and that dir is mounted = available outside the container.

If you instead set it to just tmp  `--resultDir tmp` there should be a tmp directory inside of your current dir after you run, does that work for you?

Best
Peter

**Comment by magimenon** [comment]
Thanks for the explanation. I tried creating the resultDir tmp but still not luck when I run the below command:
echo "browsertime.your.key.SpeedIndex.median" $(cat /tmpDir/browsertime.json | jq .statistics.visualMetrics.SpeedIndex.median) "date +%s" | nc -q0 my.graphite.com 2003

I still see the same error:
cat: /tmpDir/browsertime.json: No such file or directory
nc: invalid option -- q
Try `nc --help' for more information.
-bash: echo: write error: Broken pipe

**Comment by soulgalore** [comment]
Hey @magimenon yes I think the default netcat (nc) on Mac miss -q feature (how long time to wait for stdin before quitting). You can just try without it. I think the example is from Ubuntu. If you want to run Browsertime continuously you probably wanna set it up on a standalone Linux machine.

Best
Peter

**Comment by soulgalore** [comment]
I think my last comment was the solution, please let me know if its still an issue.
