### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'SpeedIndex' of undefined

### ISSUE THREAD

**Issue by jtcosta** [sitespeedio/sitespeed.io#2132]
Hello,

Trying to put the logs and the line of execution from my jenkins instance...

docker run --rm --shm-size=1g -v /sitespeedio:/sitespeed.io sitespeedio/sitespeed.io URL --speedIndex --graphite.host=graphiteHost --outputFolder output/ -n 3 -d 2 -m50 --basicAuth x@x
Google Chrome 68.0.3440.75 
Mozilla Firefox 61.0
[2018-08-08 10:06:54] INFO: Versions OS: linux 4.15.0-29-generic nodejs: v8.11.1 sitespeed.io: 7.3.5 browsertime: 3.2.3 coach: 2.0.6

Ir runs using Docker-ce 18.06.

Unhandled rejection TypeError: Cannot read property 'SpeedIndex' of undefined
    at Object.pickMedianRun (/usr/src/app/lib/plugins/html/metricHelper.js:20:71)
    at Promise.resolve.map.url (/usr/src/app/lib/plugins/html/htmlBuilder.js:175:38)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:172:69)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:199:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-08-08 11:00:44] ERROR: TypeError: Cannot read property 'SpeedIndex' of undefined
    at Object.pickMedianRun (/usr/src/app/lib/plugins/html/metricHelper.js:20:71)
    at Promise.resolve.map.url (/usr/src/app/lib/plugins/html/htmlBuilder.js:175:38)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:172:69)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:199:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

Sometimes this works with no errors, but occasionally it throws an error.
Hoping someone can help me with this.

**Comment by soulgalore** [comment]
Hi @jtcosta thanks for submitting the issue!

Hm I wonder, it looks like the Visual Metrics isn't created for one URL, can you see if that happens for one specific URL (if you check earlier in the log)? That should also be other errors in that case. We can make sure we catch the error better but I want to fix the original issue.

Best
Peter

**Comment by jtcosta** [comment]
Hello again,

ERROR: Error: Command failed: /usr/src/app/node_modules/browsertime/vendor/visualmetrics.py --dir /sitespeed.io/output/pages/baseurl/category/page/data/video/images/3 --video /sitespeed.io/output/pages/baseurl/category/page/data/video/3.mp4 --orange --perceptual --force --startwhite --renderignore 5 --json --viewport -q 75

ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/output/pages/baseurl/category/page/data/video/3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:05.43, start: 0.000000, bitrate: 100 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 96 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/output/pages/baseurl/category/page/data/video/images/3/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.78x    
video:4kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:13:26.095 - No video frames found in /sitespeed.io/output/pagesbaseurl/category/page/data/video/images/3
mogrify-im6.q16: unable to open image `/sitespeed.io/output/pages/baseurl/category/page/data/video/images/3/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/output/pages/baseurl/category/page/data/video/3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:05.43, start: 0.000000, bitrate: 100 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 96 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/output/pages/baseurl/category/page/data/video/images/3/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.78x    
video:4kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:13:26.095 - No video frames found in /sitespeed.io/output/pages/baseurl/category/page/data/video/images/3
mogrify-im6.q16: unable to open image `/sitespeed.io/output/pages/baseurl/category/page/data/video/images/3/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


    at makeError (/usr/src/app/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Hope this helps.

**Comment by soulgalore** [comment]
Yeah, it seems like Visual Metrics fails, but I need the original video to be able to recreate the problem. Usually, this happens when you run without setting any connectivity https://www.sitespeed.io/documentation/sitespeed.io/connectivity/ ... somehow the site loads too fast or we do something stupid with the video, however we should fix that but if you don't use any connectivity setting I recommend you should see https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#throttle-or-not-throttle-your-connection

When we are back from vacations we can see if we can fix the original problem.

Best
Peter

**Comment by jtcosta** [comment]
Ok will set the connectivity - thank you for the fastest reply ever! 👍

**Comment by marty90** [comment]
I'm having the same issue on browsertime, with Android test agents :(

**Comment by soulgalore** [comment]
Hi @marty90 could you please open a new issue, add as much info as possible so we can recreate and have a look! 
Thanks
Peter

**Comment by marty90** [comment]
Sure
