### ISSUE TITLE
Wait for background requests 

### ISSUE THREAD

**Issue by primehaxor** [sitespeedio/sitespeed.io#2136]
Hello,

  We are trying to collect metrics in one specific application, the page receive some inputs and move to a next screen with a message "We are processing your request", but the test ends in this screen, it wasn't able to recognize that has more things happening in the background before consider the test as a finished. Just to make sure I was testing with our previous tool and this behavior was able to be handled.

**Testing command Chrome**
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.2.1 'https://www.mysite.com/search\?out0_dep_all\=false\&out0_dep\=AMS\&out0_arr_all\=false\&out0_arr\=GRU\&in0_date\=2018-09-29\&out0_date\=2018-09-27\&adt\=1\&chd\=0\&inf\=0\&cls\=Y' --cookie Banner=accept --video -n1 --graphite.host=10.176.59.102 -b chrome
`
**Testing command Firefox**
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.2.1 'https://www.mysite.com/search\?out0_dep_all\=false\&out0_dep\=AMS\&out0_arr_all\=false\&out0_arr\=GRU\&in0_date\=2018-09-29\&out0_date\=2018-09-27\&adt\=1\&chd\=0\&inf\=0\&cls\=Y' --cookie Banner=accept --video -n1 --graphite.host=10.176.59.102 -b firefox
`

**Comment by soulgalore** [comment]
Hi @primehaxor thanks for creating the issue! You can choose when to end your test with `--pageCompleteCheck` see https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test

By default the tests ends 2s after the onload has happens, but we also have another prepared config that you turn on with `--pageCompleteCheckInactivity` - then we wait for 5 s of no request ending up in the Resource Timing API.

I would first test with `--pageCompleteCheckInactivity` and if that doesn't work, try to write your own JavaScript that chooses to end your test (as in  https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test).

Hope that helps!
Best
Peter

**Comment by primehaxor** [comment]
Just a heads up, I was able to collect the metrics in our search page, the solution was the use of `--browsertime.pageCompleteCheck` with a custom javascript to monitor for an element.
