### ISSUE TITLE
Missing other url's Detail Page Summary

### ISSUE THREAD

**Issue by Tangyiming** [sitespeedio/sitespeed.io#2138]
Hi,Dear @soulgalore 
![image](https://user-images.githubusercontent.com/18328731/44022655-ca079716-9f1a-11e8-911a-1c21448d114a.png)
As you can see, i tested 3 urls. 
So when i check out each url's Page Summary,the report always shows THE LAST URL‘S Page summary Report , is this a bug?
and i also checkout the html report folder  xx/pages/seal.uat1.rs.com/data/video/
![image](https://user-images.githubusercontent.com/18328731/44022860-76eff28e-9f1b-11e8-9e4f-c1a61ecd6ef3.png)
this 3 video is also the same (recorded the last url)

my sitespeed.io version is 6.5.4

i think this problem is caused by the hash routes #1548

**Comment by Tangyiming** [comment]
today i updated to the version 7.3.6 and test again. but got the error the same as #2087 

`18:39:26 + docker run --shm-size=1g --rm -v /home/workspace:/sitespeed.io sitespeedio/sitespeed.io:7.3.6 --preScript preScript.js --config config.json --influxdb.tags category=seal-h5_20180814183036 --mobile false --browser chrome -n 3 --connectivity native --viewPort 1366x708 --video true --outputFolder ./tempresult urls.txt
18:39:27 Google Chrome 68.0.3440.75 
18:39:27 Mozilla Firefox 61.0
18:39:28 [2018-08-14 10:39:28] INFO: Versions OS: linux 3.10.0-693.el7.x86_64 nodejs: v8.11.1 sitespeed.io: 7.3.6 browsertime: 3.3.1 coach: 2.0.6
18:39:29 [2018-08-14 10:39:29] INFO: Starting chrome for analysing http://seal.uat1.rs.com/#/ 3 time(s)
18:39:29 [2018-08-14 10:39:29] INFO: Testing url http://seal.uat1.rs.com/#/ iteration 1
18:39:38 [2018-08-14 10:39:38] INFO: BackEndTime: 93 DomInteractiveTime: 551 DomContentLoadedTime: 551 FirstPaint: 180 PageLoadTime: 587
18:39:38 [2018-08-14 10:39:38] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 LastVisualChange: 0
18:39:39 [2018-08-14 10:39:39] INFO: Testing url http://seal.uat1.rs.com/#/ iteration 2
18:39:46 [2018-08-14 10:39:46] INFO: BackEndTime: 86 DomInteractiveTime: 573 DomContentLoadedTime: 573 FirstPaint: 174 PageLoadTime: 621
18:39:46 [2018-08-14 10:39:46] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 LastVisualChange: 0
18:39:46 [2018-08-14 10:39:46] INFO: Testing url http://seal.uat1.rs.com/#/ iteration 3
18:39:54 [2018-08-14 10:39:54] INFO: BackEndTime: 106 DomInteractiveTime: 581 DomContentLoadedTime: 581 FirstPaint: 191 PageLoadTime: 628
18:39:54 [2018-08-14 10:39:54] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 LastVisualChange: 0
18:39:54 [2018-08-14 10:39:54] ERROR: TypeError: Cannot read property 'id' of undefined
18:39:54     at Object.getResultLogLine (/usr/src/app/node_modules/browsertime/lib/support/util.js:41:44)
18:39:54     at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:114:19)
18:39:54     at <anonymous>
18:39:54 From previous event:
18:39:54     at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:17)
18:39:54     at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
18:39:54     at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
18:39:54     at runCallback (timers.js:794:20)
18:39:54     at tryOnImmediate (timers.js:752:5)
18:39:54     at processImmediate [as _immediateCallback] (timers.js:729:5)`

urls:
http://seal.uat1.rs.com/#/ Index
http://seal.uat1.rs.com/#/todo Todo
http://seal.uat1.rs.com/#/sealDetail?sealId=114 Seal_Detail

preScript.js:
`module.exports = {
  run(context) {
    return context.runWithDriver(driver => {
      return driver
        .get(
          //登录页网址
          'http://xxxxxx.com/home/index?appcode=2021&returnurl=http://seal.uat1.rs.com/seal-web/common/login?currentUrl=http://seal.uat1.rs.com/#/'
        )
        .then(() => {
                      const webdriver = context.webdriver;
                      const until = webdriver.until;
                      const By = webdriver.By;
                      //登陆账号密码
                      const userName = "xxxxxx";
                      const password = "xxxxxx";
                      driver.findElement(By.xpath('//*[@id="loginName"]')).sendKeys(userName);
                      driver.findElement(By.xpath('//*[@id="loginPassword"]')).sendKeys(password);
                      var loginButton = driver.findElement(webdriver.By.xpath('//*[@id="btn-login"]'));
                      loginButton.click();
                      return driver.wait(until.elementLocated(By.xpath('/html/body/div[1]/div[2]/div/div[1]/div[1]/span')), 3000);
                    });
    });
  }
};`

**Comment by Tangyiming** [comment]
hope sitespeed can support hash routes soon,thank you @soulgalore

**Comment by soulgalore** [comment]
@Tangyiming thanks for sharing exactly how you run, that helps a lot! I was of the impression that it would work as long as you set a name/alias per URL but then I understand that we still link to the same page then? I'll test this again ASAP (after the weekend). 

Best
Peter

**Comment by Tangyiming** [comment]
update to the new version,and it's solved
