### ISSUE TITLE
Specific method of calculating the score

### ISSUE THREAD

**Issue by Tangyiming** [sitespeedio/sitespeed.io#2143]
hi @soulgalore , 
could you tell me where i can find the specific method of calculating the score?
Thanks 👍

**Comment by soulgalore** [comment]
Hi @Tangyiming that happens in the Coach: https://github.com/sitespeedio/coach/tree/master/lib/dom and https://github.com/sitespeedio/coach/tree/master/lib/har/performance (parts are calculated running JS, the other from evaluating the HAR file). Let me know if you cannot find what you are looking for.

Best
Peter

**Comment by Tangyiming** [comment]
@soulgalore  that's what i want, thank you for your  answering 🥇 👍
