### ISSUE TITLE
browsertime basic authentication not working through Apache 2.4

### ISSUE THREAD

**Issue by capearlman** [sitespeedio/sitespeed.io#2151]
Hello!

I am having trouble getting basic auth to work with our setup. We have a couple applications sitting behind HTTPD (Apache 2.4) that we are tying to run sitespeed against. Here is the command I am running:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0  --basicAuth XXX@XXX https://mytestingurl`

The result of running this is always sitespeed being pushed back to the login page. I can confirm basic auth works with our site by using curl:

`curl -vv -u XXX:XXX https://mytestingurl`

I also tried using a selenium prescript to do a login. That seemed to work, but would just hang/timeout after the prescript was done and would not transition to the actual sitespeed browsertime test. The prescript login I'm using is the exact script fogin example from this tutorial:

https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/#login-example

Please let me know any additional information you may need.

Thanks!

**Comment by soulgalore** [comment]
Hey @capearlman if you check the video/sceenshot what do you see (do you get a video)? 

I've tested basic auth at httpbin and that seems to work for me:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 --basicAuth user@passwd https://httpbin.org/basic-auth/user/passwd`

I can see in the screenshot that I get to the final page.

Best
Peter

**Comment by capearlman** [comment]
Hi @soulgalore, thanks for the quick response!

The video shows our login page. I should justify that the URL I am testing against goes deeper than https://mytestingurl and we should never see that login page. Please let me know what other info might help. 

--Chris

**Comment by capearlman** [comment]
I should also add that it doesn't seem that sitespeed/browsertime is passing up an authorization header. Doing a tcpdump over port 80 and comparing the curl call with the sitespeed call; the curl call includes an authorization header and sitespeed does not.

**Comment by soulgalore** [comment]
Hmm could it be the username/pw that causes some problems? If you try the same I showed you, does that work for you:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 --basicAuth user@passwd https://httpbin.org/basic-auth/user/passwd` ?

https://httpbin.org/basic-auth is behind basic auth and you choose the user/password yourself.

Is this the exact parameters that you pass (except the secret URL and password of course)? 
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 --basicAuth XXX@XXX https://mytestingurl`

Best
Peter

**Comment by capearlman** [comment]
Yes, that works for me. I obviously think it's an issue with how our environment is set up (Apache and the application). I just assumed if I can use curl successfully with basic auth, then sending basic auth up with sitespeed should work as well. The authorization header seems like the only outlier here. Is there a reason sitespeed does not send up this header when using basic auth?

**Comment by capearlman** [comment]
I can confirm that if I put the basic auth header into the sitespeed run it works:

-r "Authorization:Basic xxxxxxxxxxxxxxxxxxxxxx"

I just assumed that a basic auth header should be passed when sending basic auth (I could be wrong through).

**Comment by capearlman** [comment]
Interesting. Yes, this might be the case. Referring to their [documentation](https://developer.chrome.com/extensions/webRequest#implementation) they provided from their code, and this section with inside that:

"The following headers are currently not provided to the onBeforeSendHeaders event"

The authorization header is part of that group (that is not sent up).

**Comment by soulgalore** [comment]
I wonder if it works with Firefox then maybe (if you can just switch with `-b firefox`). Any change you could share the URL with me (peter [at] soulgalore [dot] com) then I can have try at my end over the weekend.

Best
Peter

**Comment by soulgalore** [comment]
@capearlman I've changed so we send a basic auth request header instead of using the extension built in. It works for me (tm) and it would be great if you could test it before I merge it. Right now we set the basic auth for just that URL and I'm not 100% sure that's the best. 

In a couple of minutes there will be a new Docker container ready for test:

`$ docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime-autobuild:updated-extension-with-basic-auth-rh ...`

When I'm sure this work, I can release a new version of Browsertime and then update sitespeed.io

Best
Peter

**Comment by capearlman** [comment]
Hi @soulgalore,

I just tested this and it is working correctly and as I would expect it to.

Thanks!!

**Comment by soulgalore** [comment]
Perfect, thank you @capearlman for taking the time to test! It's merged in master of sitespeed.io and will be released in a couple of days.

Best
Peter

**Comment by soulgalore** [comment]
This is released in 7.5.
