### ISSUE TITLE
saving --preURL test metrics

### ISSUE THREAD

**Issue by tomthedude** [sitespeedio/sitespeed.io#2153]
Hello,
I was wondering why when i use --preURL, the results that are exported to json files are only for the second address, after the cache was filled. but from what i see it does make test and take metrics on the preURL as well, so why not save them anywhere? could be useful .
because now if i want to know the difference between cache and no cache i have to run a test with --preURL and then a test without --preURL, and then compare them two instead of the results for this wll come out at the first test i do with --preURL, to different json files in the "data" folder.

thank you.

**Comment by soulgalore** [comment]
Hey @tomthedude with 8.0 you can use https://www.sitespeed.io/documentation/sitespeed.io/scripting/ to collect metrics from multiple URLs in one run/step.

Best
Peter
