### ISSUE TITLE
multiple paths in the grafana query

### ISSUE THREAD

**Issue by primehaxor** [sitespeedio/sitespeed.io#2154]
Hello,

  I have more than one path/uri to check on the same page, during the tests locally I can see both being populated in the path menu, now I can't see in the production data, i'm unable to see multiple paths in the grafana dashboard, but i can see it in the graphite as well, maybe it can take some time to scrape this new data?

**Comment by primehaxor** [comment]
nvm, it was a misunderstanding on my part, it took 1 hour to see this new data.

**Comment by soulgalore** [comment]
so does it work for you, can close the issue, I didn't fully understand :)
