### ISSUE TITLE
Can't retrieve/find/enable browsertime.json raw metric results for loading into TSDB

### ISSUE THREAD

**Issue by sdjayna** [sitespeedio/sitespeed.io#2157]
Running the following on macOS High Sierra (Docker 18.06.1)

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 https://www.sitespeed.io/`
`find . | grep json`

I would expect the raw .json from Browsertime to be available somewhere amongst the results. I can't find an option for the life of me to retrieve them (I want to feed the raw data into another TSDB).

Also tried:

`docker run --shm-size=1g -v "$(pwd)":/browsertime-results sitespeedio/browsertime:latest --video --visualMetrics  --resultDir sitespeed-result  https://www.sitespeed.io/ -n 1`

..but I suspect that wrote browsertime.json within the container and it was never exposed externally.

Am I just doing it wrong or would this be a feature request?

**Comment by soulgalore** [comment]
Hi @sdjayna 
if you just run Browsertime and map your current dir (`-v "$(pwd)":/browsertime-results`) you don't need to change the resultdir, just do:

`docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:3.5.0 https://www.sitespeed.io/` then your file will end up in **$(pwd)/browsertime/www.sitespeed.io/**.


If you want to skip the folder creation you can choose to write the file to the dir we map in Docker:
`docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:3.5.0 --resultDir . -n 1  https://www.sitespeed.io/` then your file will be in your current dir.

For sitespeed.io you can enable can enable a plugin that store all json files to disk (by default we only keep them in memory):
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 --plugins.add analysisstorer https://www.sitespeed.io `

Hope that helps
Peter

**Comment by sdjayna** [comment]
Thank you -- really appreciate it -- and thanks for a great project.
