### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by donwalling** [sitespeedio/sitespeed.io#2164]
Per https://www.sitespeed.io/documentation/sitespeed.io/installation/#npm  I'm trying to install sitespeed globally using npm but its failing with the error below. Is this error expected? Docker works ok so far. Full log attached
[2018-10-03T19_41_50_031Z-debug.log](https://github.com/sitespeedio/sitespeed.io/files/2443566/2018-10-03T19_41_50_031Z-debug.log)

macOs High Sierra 10.13.6 (17G65)

dwalling-osx:~ dwalling$ npm -version
6.4.1
dwalling-osx:~ dwalling$ node --version
v8.12.0
dwalling-osx:~ dwalling$ sudo npm install -g sitespeed.io
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
/usr/local/bin/sitespeed.io -> /usr/local/lib/node_modules/sitespeed.io/bin/sitespeed.js

> sleep@3.0.1 install /usr/local/lib/node_modules/sitespeed.io/node_modules/sleep
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sitespeed.io/node_modules/sleep/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sitespeed.io/node_modules/sleep
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> sharp@0.20.2 install /usr/local/lib/node_modules/sitespeed.io/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-darwin-x64.tar.gz
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/sitespeed.io/node_modules/sharp/10517-libvips-8.6.1-darwin-x64.tar.gz'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sitespeed.io/node_modules/sharp/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sitespeed.io/node_modules/sharp
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 (node_modules/sitespeed.io/node_modules/sleep):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dwalling/.npm/_logs/2018-10-03T19_41_50_031Z-debug.log

**Comment by soulgalore** [comment]
Hi @donwalling does it work if you install something else from npm? It looks like permission issues on your machine (`gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sitespeed.io/node_modules/sleep/build'`)?

Best
Peter

**Comment by soulgalore** [comment]
Can you try to fix so you don't need to use sudo when installing with npm? There's a fix [here](https://stackoverflow.com/questions/16724259/npm-command-sudo-or-not) you can try. 

Best
Peter

**Comment by donwalling** [comment]
@soulgalore  I can install sitespeed using the prefix approach (using the second answer in the stackoverflow thread, since I don't agree with the first answer on shared machines). Closing this issue.
