### ISSUE TITLE
Volume mount issue

### ISSUE THREAD

**Issue by clsahu25** [sitespeedio/sitespeed.io#2170]
Hi Team,

Just started using site speed and facing an issue while using it. When I run site speed on my local its mounting the volume and I am able to see the reports. 

However, when I run the same command through Jenkins slave, I am not able to archive the folder because of volume, not mount issue.

Below is the command which I am running on Jenkins slave

```
docker run --shm-size=1g --rm -v "$(pwd)"/reports/sitespeed:/sitespeed.io sitespeedio/sitespeed.io:7.4.0 --video false --visualMetrics false --outputFolder output https://xyz.com

archiveArtifacts 'reports/sitespeed/output/**'
```
**"$(pwd)"/reports/sitespeed** do exist in docker image but no **output** folder inside it. Can you please help me to which I am missing?

Thanks,

**Comment by soulgalore** [comment]
Hi @clsahu25 
ok can you try to make the output folder absolute? Try 
`--outputFolder /sitespeed.io/output` (since you are inside the container).

Best
Peter

**Comment by soulgalore** [comment]
Have you checked the Jenkins docs? I'm no Jenkins user but I remember that you have env variables that point out different dirs. In your example you use pwd (current dir) but that can be anywhere right? In our example https://www.sitespeed.io/documentation/sitespeed.io/continuous-integration/#setup we use $WORKSPACE but maybe it's better variables to use on the slave.

Best
Peter

**Comment by clsahu25** [comment]
Hi Peter,

I checked every possible thing and I know where it should mount the volume. I put sleep time on my slave and tried with the find command to search reports and directories and there is no luck. I am using docker version 17 and I hope this is fine.

Any help is appreciated :)

Thanks,

**Comment by soulgalore** [comment]
Hi @clsahu25 are your agent also a Docker container? Have you tried something like this:

**Comment by clsahu25** [comment]
Hi Peter,

It's working now. My jenkins slave is a docker container and inside that, site speed again a docker container. But now it's working through below steps

```
                    docker run --name sitespeed sitespeedio/sitespeed.io:7.4.0 https://xyz.com
                    docker start sitespeed
                    docker cp sitespeed:/sitespeed.io reports/sitespeed/
                    docker stop sitespeed
```
It's working for me now, and I am getting reports from Jenkins.

Thanks,
Chhannu
