### ISSUE TITLE
How to get the advice.json from sitespeed.io run 

### ISSUE THREAD

**Issue by idristarwala** [sitespeedio/sitespeed.io#2171]
Hi , 

is it possible to obtain the advice.json file from a regular sitespeed.io run instead of doing the sitespeed.io/coach run ?

**Comment by soulgalore** [comment]
Hi @idristarwala either you can enable to store all individual data from sitespeed.io with the analysisstorer plugin:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 https://www.sitespeed.io --plugins.add analysisstorer` (i'll update the FAQ later today) or you can run the coach standalone https://github.com/sitespeedio/coach

Best
Peter

**Comment by idristarwala** [comment]
Thanks Peter , I found that in the docs right after I posted here.. I think whats missing in the docs is where all the data goes. For example part of the /data is in the data directory and other other half is in the /pages/data directory..
