### ISSUE TITLE
passing proxy to coach 

### ISSUE THREAD

**Issue by idristarwala** [sitespeedio/sitespeed.io#2172]
Hi ,
I am currently behind a company firewall and trying to make site-speed work in our environment. Although I was able to make sitespeed to work using the following command 

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.4.0 https://www.yahoo.com -n 1 --plugins.add analysisstorer --browsertime.proxy.http=xxx.xxx:yyyy --browsertime.proxy.https=xxx.xxx.com:yyyy`

In the above use case , when I check data in the /data folder under sitespeed-result/<timestamp>/ , browsertime.summary-total.json file has the right data , but the coach.summary-total.json file has some kind of standard scores and recommendations which dont change for different websites.

So my thought here is that the coach run doesnt go through the proxy , I also tried it with the npm global install of webcoach and the same result. Could you tell me how I can pass the proxy to webcoach as well ?

**Comment by soulgalore** [comment]
Hi @idristarwala I've just updated the documentation, the data for each page is stored in `$RESULT/data/pages/$PAGE/data` see https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#i-want-a-json-from-browsertimecoach-other-tools-how-do-i-get-that 

There you should have one coach file per run, and one coach.pageSummary.json file that is the summary for all run.

Best way to verify that the proxy works is to look at the screenshot, video and waterfall and check that everything looks ok.

Best
Peter

**Comment by idristarwala** [comment]
so you are saying that if browsertime data is correct with the proxy , then the coach data also has to be correct ?

**Comment by soulgalore** [comment]
yep

**Comment by soulgalore** [comment]
Let us know if this is still a problem and we can re-open.
