### ISSUE TITLE
Page not created from Chrome on navigation with pre script

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2181]
See https://github.com/sitespeedio/sitespeed.io/issues/2091#issuecomment-430141618

**Comment by HackXiong** [comment]
Hi soulgalore,

Thank you for your quick reply. I add the new --useHash to my cli param and Alias is OK. But I got a error: TypeError: Cannot read property '_meta' of undefined in one of the test url(total 4 url), strange, you can see from the logs.
Here is the detail:
CLI: 
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.6.2 DxPress_stage_urls.txt --preScript ./login.js --browsertime.videoParams.combine  -b chrome --pageCompleteCheckInactivity --useHash`

DxPress_stage_urls.txt(The website is internal use only, not for public):
https://vdc-stg-repo-vip.vmware.com/contribution/#/add-api AddAPI
https://vdc-stg-repo-vip.vmware.com/contribution/#/edit-api EditAPI
https://vdc-stg-repo-vip.vmware.com/contribution/#/add-sdk AddSDK
https://vdc-stg-repo-vip.vmware.com/contribution/#/edit-sdk EditSDK

preScript:
`module.exports = {
	run(context) {
		return context.runWithDriver((driver) => {
			// Go to Wikipedias login URL
			context.log.info('go to test url');
			return driver.get('https://vdc-stg-repo-vip.vmware.com/contribution/#/')
			.then(() => {
				// we fetch the selenium webdriver from context
				const webdriver = context.webdriver;
				// and get hold of some goodies we want to use
				const until = webdriver.until;
				const By = webdriver.By;

				// You need to find the form, the login input fields and the
				// password field. Just add you name and password and submit the form
				// For more docs, checkout the NodeJS Selenium version
				// http://seleniumhq.github.io/selenium/docs/api/javascript/index.html
				driver.sleep(2000);
				const signInLocator = 'Sign In';
				driver.findElements(By.partialLinkText(signInLocator))
				.then(found => context.log.info('found sign in : ' + found.length));
				driver.findElements(By.partialLinkText(signInLocator))
				.then(elements => {
					if (elements.length == 1) {
						context.log.info('go to test url after');

						driver.getCurrentUrl().then(url => context.log.info('current url: ' + url));

						const signInBtn = driver.findElement(By.partialLinkText(signInLocator));
						signInBtn.click();
						// before you start, make your username and password
						const loginType = 'My VMware';
						const userName = 'ee_dp_qe_gurus1@vmware.com';
						const password = 'Abcd1234';
						driver.wait(until.elementLocated(By.id('login-auth-source')), 20000)
						const loginForm = driver.findElement(By.css('form'));
						const loginTypeBtn = driver.findElement(By.id('login-auth-source'));
						loginTypeBtn.sendKeys(loginType);

						driver.findElement(By.name('email')).sendKeys(userName);
						driver.findElement(By.name('password')).sendKeys(password);
						const loginButton = driver.findElement(By.className('btn btn-primary'));
						loginButton.click();
						// we wait for something on the page that verifies that we are logged in
						driver.sleep(3000);
						const loggedInInfo = 'nav-text dropdown-toggle';
						//return driver.wait(until.elementLocated(By.className(loggedInInfo)), 5000);
                        driver.findElements(By.className(loggedInInfo))
						.then(found2 => context.log.info('found logged info : ' + found2.length));
					}
				});

			});

		})
	}
};
`

results:
[https://onevmw-my.sharepoint.com/:u:/g/personal/qinh_vmware_com/ERX-iJviQStFqBO8C743vegBYkUut3kccrDGFOMOl3ZEGQ?e=hA31ml](url)


Another question:
Sitespeed.io can provide an option for prescript to run only once during testing? For example, I am just trying to log in in prescript, so I don't need to log in when testing other urls later.


thanks.

**Comment by soulgalore** [comment]
Hi @HackXiong thanks for sharing!

> TypeError: Cannot read property '_meta' of undefined 

Yes that is a bug: I'll take care of the error better but the problem is that we don't take care of the navigation from Chrome and a page isn't created in the HAR (so there must be another case that we missed).

> Sitespeed.io can provide an option for prescript to run only once during testing? For example, I am just trying to log in in prescript, so I don't need to log in when testing other u

No, not at the moment. Here's docs that explains the flow: https://www.sitespeed.io/documentation/sitespeed.io/browsers/#how-does-it-work-behind-the-scene

Best
Peter

**Comment by soulgalore** [comment]
This has been changed now with scripting in 8.0, let us know if you still has issues.
