### ISSUE TITLE
Chrome HAR - Bodies

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2184]
Hi Guys,

Please confirm if it is possible to get the request and response bodies in the HAR file when using Chrome?

I see that Firefox has the following flag --firefox.includeResponseBodies

Thanks!

**Comment by soulgalore** [comment]
Yep not at the moment, see https://github.com/sitespeedio/chrome-har/issues/8#issuecomment-430381519

Best
Peter

**Comment by scabenga** [comment]
Perfect, thanks @soulgalore

**Comment by soulgalore** [comment]
Closing this and will create a new one when Selenium 4 is released (and works).
