### ISSUE TITLE
Annotations issue [InfluxDB]

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2190]
Hi there, 

Sitespeed 7.7.1
Grafana 5.3.0

Please shed some light on annotation mechanism of sitespeed 7.7.1
As I understand if I set --grafana.host it will send data to Grafana and I should use built-it annotations either if -grafana.host is not set old annotations way will be used (Influxdb events table).
but it seems that events table is not created no more even when -grafana.host is not set.
Please check this.

Another one question :)
I've stuck with new Grafana annotations. 
I've set grafana host, port and auth + baseURL and it seems to be sent successfully but I can't see it on the dashboard. 
Please help me how it should be configured.

Best Regards.

**Comment by soulgalore** [comment]
Hi @Icecold777 
I think it's a bug then. InfluxDB should work as before. I did some refactoring and it must have gone wrong for Influx, let me have a look in a couple of hours.

For Grafana, it should work if you just change to Grafana as Data source. Have you looked at what it looks like for Grafana?
<img width="1078" alt="screenshot 2018-10-24 at 18 37 43" src="https://user-images.githubusercontent.com/540757/47446668-04411e00-d7bc-11e8-9960-154885ba46c4.png">

Best
Peter

**Comment by soulgalore** [comment]
@Icecold777 I've fixed two issues now. I wanna wait until I can verify that it looks ok on dashboard.sitespeed.io and then I'll push a release.

**Comment by soulgalore** [comment]
I've just released 7.7.2. It works there for me but please confirm that works for you too @Icecold777 and we can close this issue. 

Best
Peter

**Comment by Icecold777** [comment]
Hi @soulgalore. Thank you for such quick response! It works now as before)

Best Regards.

**Comment by soulgalore** [comment]
Great!
