### ISSUE TITLE
Is it possible to see details of 404 pages inside Detailed Summary section of HTML report

### ISSUE THREAD

**Issue by zunjooo** [sitespeedio/sitespeed.io#2201]
I think it would be a great thing to see details about 404 pages inside HTML report for URLs + inlinks and outlinks maybe also. 
Is that an option in the moment right now? All I see for now is "404 responses" under Detailed Summary section in HTML report.

Here is a screenshot:

<img width="1196" alt="sitespeed" src="https://user-images.githubusercontent.com/22975725/48063414-3c395f80-e1c5-11e8-81bb-cbd03974e8de.png">

All the best!

**Comment by soulgalore** [comment]
Hi @zunjooo the 404 is responses for requests so it could be a missing image, font etc. The only way to see them today is to go to the HAR file and check it out in the waterfall. So you need to do an extra step. One way to do it could be to have a "error" summary for each run ... but there no easy way to link to it directly. 

Best
Peter

**Comment by zunjooo** [comment]
Greetings,

I downloaded HAR file from one result of sitespeed.io test, and tried it on "G Suite Toolbox HAR Analyzer" and "Compare.sitespeed.io", but it seems it's not working right, the errors I get are:
On Compare site - "Cannot read property 'id' of undefined";
On G Suite Toolbox HAR Analyzer site - "Errors found when processing the HAR file: No log entries found in the file."

Best
Vanja

**Comment by soulgalore** [comment]
Hi @zunjooo 
can you share the HAR file and how you run so I can try to reproduce?

Best
Peter

**Comment by zunjooo** [comment]
Hi @soulgalore 
yea sure, I had this same error messages for all HAR files that I got from sitespeed.io HTML results.
Particular one for this commend above is this one:
[sitespeed.har.zip](https://github.com/sitespeedio/sitespeed.io/files/2561407/sitespeed.har.zip)

I got this HAR file with this instructions:
1. Open Google Chrome and go to the page - HTML result from sitespeed.io scan.
2. From the Chrome menu bar select View > Developer > Developer Tools.
3. From the panel opened at the bottom of your screen, select the Network tab.
4. Look for a round Record button in the upper left corner of the Network tab, and make sure it is red. If it is grey, click it once to start recording.
5. Check the box next to Preserve log .
6. Click the Clear button to clear out any existing logs from the Network tab.
7. Now try to reload page, while the network requests are being recorded.
8.. Once this is done, right click anywhere on the grid of network requests, select Save as HAR with Content , and save the file to your computer.

I got this error messages:
https://toolbox.googleapps.com/apps/har_analyzer/ - I just added this HAR file

https://compare.sitespeed.io/ - same case here, but I added 2 HAR files just to be sure

**Comment by soulgalore** [comment]
Ah I see @zunjooo , You need to download the actual HAR from the sitespeed.io run (you try to get the HAR from accessing the HTML page and get it from devtools). 

1. Go to your result page, to the URL you tested.
2. Scroll down and click the "Download HAR" button.
![download](https://user-images.githubusercontent.com/540757/48196299-8439bd00-e352-11e8-9cc8-87e3118a1fe2.png)

Then you will get the HAR from the sitespeed.io run.

Best
Peter

**Comment by zunjooo** [comment]
Oh sorry, thank you, yes I see now, I didn't know that I can do it in that way.

Thank you so much for quick responses!

Cheers and all the best,
Vanja
