### ISSUE TITLE
Optimisation recommendations for URL list

### ISSUE THREAD

**Issue by kab12** [sitespeedio/sitespeed.io#221]
Hi Peter,

When processing a url list we get the optimisation recommendations per page showing us the score per rule. I think that it would be great to have a dedicated tab (+csv output) showing (over all pages) the rules that had the greatest negatives impact. The list would show : Yslow rule, number of pages impacted, Total number of Score points missed, Average number of Score points missed because of this rule. 

This list is great to use as an action list for a site optimisation plan.

Cheers,
Peter

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
