### ISSUE TITLE
Docker Mac Error

### ISSUE THREAD

**Issue by rohitsethitcs** [sitespeedio/sitespeed.io#2211]
Hi , 

I am having the below error , when i run sitespeed using docker via this command 

/usr/local/bin/docker-compose run sitespeed.io https://www.xxxxxx.com/ --graphite.host=graphite

Error

Error response from daemon: Mounts denied: { errno = [EACCES]; call = getattrlist; label = /private/var/root/sitespeed-result }

Can anyone tell me , how to get rid of this ?

**Comment by soulgalore** [comment]
Hi @rohitsethitcs sorry I missed this issue, have you found the solution? It looks like a Docker mount issue.

Best
Peter

**Comment by soulgalore** [comment]
Closing this since we never heard back, but please ping the issue again if you still have the issue so we can help you!
