### ISSUE TITLE
Where are the values of metrics stored?

### ISSUE THREAD

**Issue by qqdqy** [sitespeedio/sitespeed.io#2214]
Where are the values of metrics stored? I only see them in the html file, but I want to save them to database, what should I do？

**Comment by soulgalore** [comment]
Hi @qqdqy you can default choose to store metrics in Graphite or InfluxDB (read through https://www.sitespeed.io/documentation/sitespeed.io/graphite/). 

If you want store it in a database. you need create your own plugin: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin

Best
Peter

**Comment by qqdqy** [comment]
@soulgalore Thanks for your reply! I will try it according to your suggestion.
