### ISSUE TITLE
Include in the documentation on how to integrate with Gitlab CI

### ISSUE THREAD

**Issue by lucasafranio77** [sitespeedio/sitespeed.io#2218]
In the gitlab site there is a material talking about how to work Gitlab CI with sitespeed.io. It would be good to include this on the project site as well. Follow the link:

https://docs.gitlab.com/ee/ci/examples/browser_performance.html

Congratulations to the work.

**Comment by soulgalore** [comment]
Hi @lucasafranio77 good idea, let me fix that tonight! 

Best
Peter

**Comment by soulgalore** [comment]
Added the links to the docs. Thanks again @lucasafranio77 !
