### ISSUE TITLE
Need help with querying metrics in Influx

### ISSUE THREAD

**Issue by ckhampus** [sitespeedio/sitespeed.io#2222]
Hi! This might just be inexperience with Influx on my part but I'm having a hard time querying certain metrics.

For example I'm trying to get CPU metrics but I have no clue how the query should look like? 🤔 

Another example would be Lighthouse scores. 

With the following query I manage to get a value:

```
SELECT mean("value") FROM "score" WHERE ("origin" = 'lighthouse') AND $timeFilter GROUP BY time($__interval) fill(null)
```
But what does that value mean? Is it the perfomance score, the PWA score, ore something else?

Thanks for the awesome work you do!

**Comment by soulgalore** [comment]
Hi @ckhampus thank you for the kind words :)

I'm no InfluxDb user either (we use Graphite). If everything is right in the code, most key paths in Graphite should be converted to tags when using InfluxDB. Let me turn on CPU for our tests that stores the data to Influx and have a look (I looked now and it seems the tests are down, so I will fix that first).

For Lighthouse they should also have tags per type but let me have a look, maybe the structure there isn't correct.

Best
Peter

**Comment by soulgalore** [comment]
Did a quick check for CPU. At the moment we don't tag per type (which makes it harder). I will create a follow up issue for that. Right now they are all at the same level (see "Scripting"):
<img width="1446" alt="screen shot 2018-11-27 at 21 23 45" src="https://user-images.githubusercontent.com/540757/49109417-ea976880-f28a-11e8-9724-7f9f872af5ad.png">

That works to make a graph for the high level of time spent (scripting, rendering, painting etc) but if you wanna graph per event type in the trace log ... it's a lot of work. Let me fix that for at least the next major (before Christmas).

For Lighthouse, we also need a fix for Influx. The structure is like this: https://github.com/sitespeedio/plugin-lighthouse/blob/master/index.js#L8-L13

And we need to catch the Lighthouse data in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/influxdb/data-generator.js#L89 and then add a tag per type (SEO etc) and also a generic Lighthouse tag. If you have time I can guide you (if you want it ASAP).

Best
Peter

**Comment by ckhampus** [comment]
Hi @soulgalore! 

Thanks for your answer and the example. This will get me started, but I just realized that I may not have activated the CPU timings correctly and that's why I don't see the data 😛 What's the correct way of enabling the CPU timings?

I don't need the data right now so don't stress it 👍 Was just playing around in Grafana and needed a little help.

-Cristian

**Comment by soulgalore** [comment]
Let me fix that for the next major then, it's kind of annoying the way it is now.

Adding `--chrome.timeline` will pickup the metrics.

**Comment by soulgalore** [comment]
And yes it only works in Chrome at the moment, Firefox doesn't expose that kind of metrics at the moment (there are some upstream tasks for it though).

**Comment by ckhampus** [comment]
Thanks! Got it working now 👍 I'll close this now as I got the help I needed 😄

**Comment by soulgalore** [comment]
Cool! I've merged the fixes in master, so next release it will be easier to pickup the CPU metrics + you can actually use the Lighthouse ones.
