### ISSUE TITLE
Can I test a website with multiple connectivities at the same time? (using Docker)

### ISSUE THREAD

**Issue by mporras17** [sitespeedio/sitespeed.io#2223]

**Comment by soulgalore** [comment]
Hi @mporras17 I think it would be possible to setup multiple docker networks and then use them for different containers. However I never run more than one test at a time, since I want to avoid disturbance and unstable metrics.

Best
Peter

**Comment by mporras17** [comment]
The idea is testing a webpage using sitespeed docker container but I would like to know if I have the possibility to add different networks (2g, 3g, cable...) in the config.json 
![config](https://user-images.githubusercontent.com/45072185/49108004-b56c2580-f24c-11e8-9bc6-5047787bb007.PNG)

**Comment by soulgalore** [comment]
That is just the name. All setup of connectivity happens on the outside of the container, check the docs here: https://www.sitespeed.io/documentation/sitespeed.io/connectivity/

Hope that makes it more easier to understand!
Best
Peter
