### ISSUE TITLE
Is it possible to analyse not signed SSL certificate?

### ISSUE THREAD

**Issue by jchatard** [sitespeedio/sitespeed.io#223]
I need to analyse a client site which is under development, but for now, the certificate isn't valid. And it seems that sitespeed.io can't get the content of pages.

Which make sense, because all regenerated xml files are empty...

Thanks so much :-)

Jérémy

**Comment by mackelito** [comment]
Hey!.. I'm kind of struggling to get this working.. is there any docs about how to ignore the ssl??

**Comment by jchatard** [comment]
Hmm, https://github.com/sitespeedio/sitespeed.io/issues/223#issuecomment-20657507 should do the trick.

Well for me it did, a long time ago...

**Comment by mackelito** [comment]
I'm using the dockers so I guess I need to to something in the sitespeed docker

**Comment by soulgalore** [comment]
Hey @mackelito , I wonder if it could be the crawler part that's failing (we still use an Java crawler) and it could be that causes the problem. You can sidestep it by not crawling, try it by create a text file with the URL on one line and feed it with the -f parameter. If you can test that, then we know if it's the cralwer that is the problem (remember that the file needs to be availible inside of the Docker container, menaing map it with -v, let me know if you need help).

Best
Peter

**Comment by mackelito** [comment]
Sure I can test that :)
Where do I place the txt file?

**Comment by mackelito** [comment]
Have tried to get this working but no luck..
This is what I'm running now.. so I assume that I need to replace the url with eg. "urls.txt".. but before that use the -v option some how..
```
docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u https://localhost:9002/sv/login#/ -b chrome --basicAuth test:test --connection cable -r /tmp/ --graphiteHost 192.168.99.100 --seleniumServer http://127.0.0.1:4444/wd/hub -d 0
```
Any help is most welcome :)

**Comment by soulgalore** [comment]
ok so is  https://localhost:9002/sv/login#/ an example URL? When you are inside the container, the localhost will be inside the container, so if you run your site outside locally, you need to use the ip of your local machine (or the ip of the other container where you have your site). 

The *-v* maps a folder/map from your phusical server inside your container. In your example, do you have a folder in root like this */sitespeed.io* then change the url to be *-f /sitespeed.io/urls.txt* and locally on your server, place the file in /sitespeed.io.

Hope that helps :)

**Comment by mackelito** [comment]
Yes it was an example.. I'm using the IP when I run :)

The file is placed in /sitespeed.io/urls.txt
And I run 
```
docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -f /sitespeed.io/urls.txt -r /tmp/ --graphiteHost 192.168.99.100 --seleniumServer http://127.0.0.1:4444/wd/hub -d 0 -n 1
````
but I get --file: '/sitespeed.io/urls.txt' can't be found

**Comment by soulgalore** [comment]
ok, what OS are you using? On Mac OS X & Windows, you are only able to map volumes inside the user home dir, could it be that? https://www.sitespeed.io/documentation/docker/#setup-the-volume

Best
Peter

**Comment by mackelito** [comment]
Running OSX so that migth be it then :) I'll give it a try..
Is it possible to add the file based on where I stand when running the command?

eg. in the terminal I'm in /Users/myUser/sitespeed/ and there is where my urls.txt file is

**Comment by soulgalore** [comment]
ah cool :) Yes use the “$(pwd)”, check the example in the doc.

**Comment by mackelito** [comment]
So something like this?
```
docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -f $(pwd)/urls.txt -r /tmp/ --graphiteHost 192.168.99.100 --seleniumServer http://127.0.0.1:4444/wd/hub -d 0 -n 1
```
The path is changed but file still not found... The file is there and I even chmod 777 the little bastard ;)

**Comment by soulgalore** [comment]
ah sorry I wasn't clear how I meant:

First we need to make sure that we inside the container can reach the file we want to use, so we map it (or a directory) as volume. Lets say I'm in my home dir on my Mac and created a folder called urls with a file called firstrun.txt (~/urls/firstrun.txt) then to Docker I add (if I run from my homedir): *-v “$(pwd)”:/test*

Then when I run sitespeed.io inside the container, we will have the file in /test/urls/firstrun.txt so we use it like *-f /test/urls/firstrun.txt*

I wrote this without testing (bad practice) so I hope it is right :)

**Comment by mackelito** [comment]
Hmmm.. still not getting it to work...
```
docker run --privileged --rm -v $(pwd):/test sitespeedio/sitespeed.io sitespeed.io -f /test/urls.txt -r /tmp/ --graphiteHost 192.168.99.100 --seleniumServer http://127.0.0.1:4444/wd/hub -d 0 -n 2
```
And now I'm getting "--file: '/test/urls.txt' can't be found"?

**Comment by soulgalore** [comment]
and you are in your home dir? 

I've tested now on my computer running Docker quickstat terminal. In my home dir I created urls.txt and then run it like this (tried to make it as simple as possible):
<pre>
cd ~
echo 'http://www.sitespeed.io' > urls.txt
docker run --privileged --rm -v $(pwd):/test sitespeedio/sitespeed.io sitespeed.io -f /test/urls.txt -d 0 -n 1 -b chrome
</pre>

And it works. Can you try exactly as I did and check?

Best
Peter

**Comment by mackelito** [comment]
Aaaah.. now I see the problem.. I used the "-v $(pwd):/test" incorrect... all is working fine now! :)
Big thx!
