### ISSUE TITLE
Webpage test response issue

### ISSUE THREAD

**Issue by prashan9775** [sitespeedio/sitespeed.io#2230]
Hi,

I ran below sitespeed command with following parameters to generate webpage test summary

`docker-compose run sitespeed.io site_urls.txt --graphite.host=graphite --mobile --firstParty .fabhotels.com --network=3gslow -c 3gslow --webpagetest.key=<Webpagetest API Key> --webpagetest.runs=1 --webpagetest.useragent="Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Mobile Safari/537.36" --webpagetest.location=ap-south-1:Chrome.3GSlow`

In output i am getting this error 

```
Unhandled rejection TypeError: Cannot read property 'browser_name' of undefined on line 48
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:159:71)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1767:3)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at Promise.resolve.map.url (/usr/src/app/lib/plugins/html/htmlBuilder.js:248:37)
```

After little debugging i found that the api response has missing values.I am pasting my api response may be it can help you to understand the exact problem we are facing.

```
{
  "log": {
    "version": "1.1",
    "creator": {
      "name": "WebPagetest",
      "version": "18.10"
    },
    "browser": {
      "name": null,
      "version": null
    },
    "pages": [
      {
        "startedDateTime": "1970-01-01T00:00:00.000+00:00",
        "title": "Run , First View for ",
        "id": "page___",
        "pageTimings": {
          "onLoad": null,
          "onContentLoad": -1,
          "_startRender": null
        }
      }
    ],
    "entries": []
  }
}
```

Thanks
Prashant singh

**Comment by soulgalore** [comment]
Yeah it seems like the WebPageTest response is broken and we don't handle that. We check for an ok status code https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/webpagetest/analyzer.js#L42-L51 but I guess the API returns 200 then? If you check at the WebPageTest server, can find your run, what does it look like? I think you should file an upstream issue to check what's wrong.

Best
Peter

**Comment by prashan9775** [comment]
Hi @soulgalore thanks for the reply.

I found the problem, it is in the params that we are sending in request.The requirement we are having is that location server should be mumbai and n/w connection value to be slow3G so we assigned 
--webpagetest.location=ap-south-1:Chrome.3GSlow which is not the correct way to do.

**Comment by soulgalore** [comment]
Ok, so I guess we don't need to do anything, closing.
