### ISSUE TITLE
Use alias or hash of url to store page data

### ISSUE THREAD

**Issue by djusv** [sitespeedio/sitespeed.io#2238]
Hello,

first I would like to say sitespeed.io is a wonderful collection of tools.
I have been trying to setup some tests for our own SPA and so far I got it all up and running.
But I would like to suggest an enhancement for the storage of the data per page.

I use the urls textfile and also defined an alias for these urls and also they have a '**#**' inside of them.
I already use the **--useHash** feature.

```
https://SERVER/webapp/#/page1 page_1
https://SERVER/webapp/#/page2 page_2
https://SERVER/webapp/#/page3?param1=val1&param2=val2&param3=val3&param4=val4 page_2
```

What I noticed is that under Windows the names of the output can be too long when using a lot of query parameters. Also in the generated report the links to page3 don't work.

My suggestion is instead of replacing the all invalid characters with a '**-**' 
is to use the alias if given or calculate a SHA for the url and use that as a name for storing it in folder.
 
I am using the docker-compose setup (sitespeed.io:7.7.3) under windows 10.

**Comment by soulgalore** [comment]
I've checked the implementation and when not using hash it works as it should: it creates a short path using a SHA. Let me fix so it works the same with #-urls before the first alpha.

**Comment by soulgalore** [comment]
This is fixed in 8.
