### ISSUE TITLE
Unable to connect to Xvfb

### ISSUE THREAD

**Issue by balajir2016** [sitespeedio/sitespeed.io#2250]
Hi Peter,

I have followed the steps mentioned https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes and tried to connect to VNC via using 0.0.0.0:7600, I get "connection closed unexpectedly" error when I try to connect from realvnc client. 

Please help.

Thanks,
Balaji R

Please see stack trace:

**Docker command**
cd; docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io -**p 7600:5900** sitespeedio/sitespeed.io https://www.mysite.com -n 50 --graphite.host=172.16.100.177

**Docker ps**
CHMB105416:~ balaji_rama$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                                                                       NAMES
88e97086ef39        sitespeedio/sitespeed.io         "/start.sh https://w…"   5 seconds ago       Up 4 seconds        **0.0.0.0:7600->5900/tcp**                                                                      elastic_galileo
c9021259f262        grafana/grafana:5.4.0            "/run.sh"                5 weeks ago         Up 5 days           0.0.0.0:3000->3000/tcp                                                                      balaji_rama_grafana_1_d24118a38ae8
04dbf634f793        sitespeedio/graphite:1.0.2-2-b   "/sbin/my_init"          5 weeks ago         Up 5 days           2004/tcp, 2023-2024/tcp, 0.0.0.0:2003->2003/tcp, 8126/tcp, 8125/udp, 0.0.0.0:8080->80/tcp   balaji_rama_graphite_1_1edc5a638fbd
CHMB105416:~ balaji_rama$ 

**Addtional Logs:**
root@bbae666c834f:/sitespeed.io# x11vnc -display :99 -storepasswd
Enter VNC password: 
Verify password:    
Write password to /root/.vnc/passwd?  [y]/n y
Password written to: /root/.vnc/passwd
root@bbae666c834f:/sitespeed.io# ps -ef | grep Xvfb
root        69    59  2 10:03 ?        00:00:10 Xvfb :99 -ac -nolisten tcp -screen 0 1366x708x24
root     10348  1397  0 10:10 pts/0    00:00:00 grep --color=auto Xvfb
root@bbae666c834f:/sitespeed.io# ps -ef | grep x11 
root@bbae666c834f:/sitespeed.io# ps -ef           
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 10:03 ?        00:00:00 /bin/bash /start.sh https://www.mysite.com -n 50 --graphite.host=172.16.100.177
message+    48     1  0 10:03 ?        00:00:00 /usr/bin/dbus-daemon --system
root        58     1  0 10:03 ?        00:00:00 /usr/bin/dbus-daemon --syslog --fork --print-pid 4 --print-address 6 --session
root        59     1  4 10:03 ?        00:00:20 node --max-old-space-size=2048 /usr/src/app/bin/sitespeed.js https://www.mysite.com -n 50 --graphite.hos
root        69    59  2 10:03 ?        00:00:10 Xvfb :99 -ac -nolisten tcp -screen 0 1366x708x24
root        76    59  1 10:03 ?        00:00:08 /usr/src/app/node_modules/alto-saxophone/vendor/chromedriver --port=55996
root      1397     0  0 10:04 pts/0    00:00:00 bash
root     10562    76 36 10:11 ?        00:00:00 /opt/google/chrome/chrome --allow-running-insecure-content --disable-add-to-shelf --disable-background-down
root     10567 10562  0 10:11 ?        00:00:00 cat
root     10568 10562  0 10:11 ?        00:00:00 cat
root     10570 10562  1 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=zygote --no-sandbox --enable-logging --log-level=0 --user-data-dir=/tmp/.o
root     10571 10570  0 10:11 ?        00:00:00 /opt/google/chrome/nacl_helper --no-sandbox
root     10595 10562  5 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=17204570419235345004,1367920287878146723,
root     10792 10570 11 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=renderer --no-sandbox --enable-automation --enable-logging --log-level=0 -
root     10815 10570  9 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=renderer --no-sandbox --enable-automation --enable-logging --log-level=0 -
root     10818 10570  7 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=renderer --no-sandbox --enable-automation --enable-logging --log-level=0 -
root     11021 10570  3 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=renderer --no-sandbox --enable-automation --enable-logging --log-level=0 -
root     11032    59 16 10:11 ?        00:00:00 ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0
root     11039 10570  0 10:11 ?        00:00:00 /opt/google/chrome/chrome --type=renderer --no-sandbox --enable-automation --enable-logging --log-level=0 -
root     11049  1397  0 10:11 pts/0    00:00:00 ps -ef
root@bbae666c834f:/sitespeed.io# CHMB105416:~ balaji_rama$

**Comment by balajir2016** [comment]
After I do the configurations mentioned in documentation and I connect to 0.0.0.0:7600 from real VNC client, I get "connection closed unexpectedly".

I followed documentation from https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes

**Comment by soulgalore** [comment]
So anyone wants to try this and see what's wrong? Maybe the documentation is outdated.

**Comment by abecker4** [comment]
@balajir2016 I was able to get this to work by following the documentation and leaving off the -storepasswd argument from the 'Visualize your test in XVFB' section in the link above.

**Comment by soulgalore** [comment]
Closing as it seems to work now.
