### ISSUE TITLE
Strange results while using the mobile testing tool

### ISSUE THREAD

**Issue by marimeireles** [sitespeedio/sitespeed.io#2256]
I'm using sitespeed.io to test https://staging.webcompat.com
The tests run fine and make sense if I'm running on docker. When I try to use the tool to run tests using mobile I get some strange results. I'm using Chrome v 71.0, sitespeed 7.7.3, a Nexus five mobile and a MacBook Mojave to run the tests. Here are some examples of measurements I made:

Time to first paint on docker using chrome: 2372
Time to first paint on mobile: 1655

Time to be interactive on docker: 5615
TTI on mobile: 1416

When I run the tests using other tools like Chrome DevTools I get a very different result, the time to load on mobile is much bigger, practically 2x the desktop time. I thought it might be something related to cache, I believe it's disabled by default, but I didn't find anything in the docs about it.
The page is loading normally, just super fast, as if it had info cached.

The command I'm using is:
`sitespeed.io --browsertime.chrome.android.package com.android.chrome --preScript login_mobile.js --config config.json https://staging.webcompat.com`

My config.json contains simple instructions:
```
{
  "browsertime": {
    "iterations": 3,
    "browser": "chrome"
  },
  "utc": true,
  "outputFolder": "name"
}
```

And the prescript is used only to login:
```
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('url')
        .then(() => {
          const webdriver = context.webdriver;
          const until = webdriver.until;
          const By = webdriver.By;

          const userName = 'user';
          const password = 'pass';
          driver.findElement(By.name('login')).sendKeys(userName);
          driver.findElement(By.name('password')).sendKeys(password);
          const loginButton = driver.findElement(By.className('btn-block'));
          loginButton.click();
          return driver.wait(until.elementLocated(By.id('body-webcompat')), 3000);
        });
    })
  }
};
```

Thanks for the help!

**Comment by soulgalore** [comment]
Hi @marimeireles thanks for the report. So in your login script, do that page also load the same assets (css/js/images) etc that you test and they populate the browser cache before you do the tes? Are you testing the exact same way when you run on desktop?

Best
Peter

**Comment by marimeireles** [comment]
Ooohhh, you're right.
That's where the cache comes from. It loads the front page once it finishes loading my script. The. it starts loading the page I'm interested in, but it already have a lot of stuff cached.

Do you know how can I fix it? I didn't find anything to control cache. 

Thanks a lot for your answer & sorry for the silly issue 🙈

**Comment by soulgalore** [comment]
@marimeireles glad I could help! There are no silly issues they will help others that gets here :)

Best
Peter
