### ISSUE TITLE
--chrome.timeline should provide more insightful information

### ISSUE THREAD

**Issue by kazazor** [sitespeedio/sitespeed.io#2264]
I'm not sure if it's a feature or a bug.

When testing using Chrome, I also use the option `--chrome.timeline` to [add more information](https://www.sitespeed.io/documentation/sitespeed.io/spa/#cpu-metrics).

The places I saw it make a difference in the report are:

Coach
<img width="1149" alt="screen shot 2019-01-23 at 1 21 08" src="https://user-images.githubusercontent.com/1577655/51572160-317d9500-1ead-11e9-8b71-ab54128c697a.png">

Metrics
<img width="1218" alt="screen shot 2019-01-23 at 1 18 22" src="https://user-images.githubusercontent.com/1577655/51572167-39d5d000-1ead-11e9-83ec-a9e68689dc31.png">

I run the command:
```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.0.2-plus1 --browser chrome --chrome.timeline <any_url>
```
The problem I see here is mainly that this information does not provide me with too many insights. I would expect that I could dive into the `EvaluateScript` part to see which functions are taking the most time to run.
Something like what's written [here](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/#tools).
The docs here says:
>where Chrome spends it times rendering and executing JavaScript.

I'm afraid that currently either I'm missing something, or I cannot really see where it sent its time on.

## More info
Version: 8.0.2

**Comment by soulgalore** [comment]
Hi @kazazor I think you should think about it like this:

Use the categories and events to draw graphs like in https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?panelId=6&fullscreen&orgId=1 - that way you can keep track of changes and find regressions. You keep track of the performance on a high level.

When you have a regression you need to use the the collected trace log and drag and drop it into chrome devtools and investigate it there. 

You can change what kind events you collect with the trace log using `--chrome.traceCategories  ` but the more information you collect, the more it will affect the performance.

Best
Peter

**Comment by kazazor** [comment]
> You can change what kind events you collect with the trace log using --chrome.traceCategories but the more information you collect, the more it will affect the performance.

Thanks @soulgalore , good point there. Sounds good to me as I forgot this data could be used in chrome dev tools.

I'll close the issue now.
