### ISSUE TITLE
Lighthouse plugin in scripted flows

### ISSUE THREAD

**Issue by idristarwala** [sitespeedio/sitespeed.io#2283]
While trying to run a scripted flow the lighthouse plugin enabled, I came across the console error which said not supported yet in scripted flows.
do you have an ETA on this feature or when this will be supported ?

**Comment by soulgalore** [comment]
Hi @idristarwala 

> do you have an ETA on this feature or when this will be supported ?

Ask the Lighthouse team :)

I don't know when they will support it. WebPageTest has [there own scripting](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting) and you need to run it separately so I guess it will be the same with Lighthouse.

Best
Peter
