### ISSUE TITLE
When running Sitespeed script or WPT script scandir fails

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2293]
I am running with the 8.2.3 version of the Docker image on MacOS Mojave.

When running a multi-step test with either sitespeed scripting or wpt scripting, I always run into the same error when the results are being processed:

`ERROR: Error: ENOENT: no such file or directory, scandir '/sitespeed.io/sitespeed-result/rc.rc.nextiva.xyz/<date>/pages/rc.rc.nextiva.xyz/data/video/images/1'`

I believe this has to do with the fact that the images are actually located at:

`/sitespeed.io/sitespeed-result⁩/rc.rc.nextiva.xyz⁩/2019-02-06-23-09-30⁩/pages⁩/⁨rc.rc.nextiva.xyz⁩ /Platform⁩/login⁩/data⁩/video⁩/images/1`

**Comment by leathej1** [comment]
When running --debug, this is the last message before the failure:

```[2019-02-06 23:33:06] INFO: {
  "uuid": "1eeb713b-0cfb-48db-8f53-870375309e56",
  "type": "sitespeedio.render",
  "timestamp": "2019-02-06T23:33:06+00:00",
  "source": "queueHandler"```

**Comment by soulgalore** [comment]
Hi @leathej1 can you show me how you run so [I can reproduce](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue)? 

Best
Peter

**Comment by leathej1** [comment]
Unfortunately, you would have to be inside our firewall. Are there any other debug logs that I can produce?

**Comment by soulgalore** [comment]
If you don't show me how you run it super hard to guess what's wrong :)

**Comment by leathej1** [comment]
I can show you the structure of the scripts, but you won't be able to run it. Is there something else that might help, like the .har?

**Comment by soulgalore** [comment]
Does it produce the HAR? If you can show me exact how you run from the command line and blanking out if you have any sensitive information, that would be great!

**Comment by leathej1** [comment]
This is the wpt script:

```
logData	0
setActivityTimeout	60000
setEventName	OpenBaseURL
navigate	https://rc.rc.nextiva.xyz/
setValue	name=loginUserName	***
setValue	name=loginPassword	***
sendClick	class=check
setEventName	Login
clickAndWait	type=submit
setEventName	SelectProfile
execAndWait	document.querySelector("body > div.profiles-panel > div:nth-child(2) > div.rounded-badge").click();
setEventName	OpenCRM
logData	1
navigate	https://rc.rc.nextiva.xyz/apps/agent
```

And this is how it runs on my local wpt: https://www.webpagetest.org/results.php?test=190207_PN_862daa34381f27bb3c889b39d14d69ab

But the issue is that the directory that is being referenced in this error does not exist:

```
[2019-02-07 16:22:20] ERROR: Error: ENOENT: no such file or directory, scandir '/sitespeed.io/sitespeed-result/rc.rc.nextiva.xyz/2019-02-07-16-18-47/pages/rc.rc.nextiva.xyz/data/video/images/1'
```

![image](https://user-images.githubusercontent.com/24658347/52426126-9db9e480-2aba-11e9-9026-b1183c80934f.png)

But it *does* exist here:

![image](https://user-images.githubusercontent.com/24658347/52426328-00ab7b80-2abb-11e9-8ce6-664bfd1df1fa.png)

**Comment by soulgalore** [comment]
I wonder if it gets confused with https://rc.rc.nextiva.xyz vs https://rc.rc.nextiva.xyz/apps/agent so that if you change how you run:

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.2.3 --graphite.host 10.11.161.113 --webpagetest.file login-crm.txt --webpagetest.host 10.11.161.113:4000 --webpagetest.location Test --webpagetest.runs 1  https://rc.rc.nextiva.xyz/apps/agent -n 1`

maybe that works?

Also if you run WebPageTest scripts I think it's best to [disable Browsertime](https://www.sitespeed.io/documentation/sitespeed.io/webpagetest/#run-webpagetest-without-browsertime) since it will not test the same thing (Browsertime doesn't use WebPageTest scripts and WebPageTest doesn't work with Browsertime scripting). 

Best
Peter

**Comment by leathej1** [comment]
Yes, adding the /apps/agent did the trick - thanks!

**Comment by soulgalore** [comment]
Great!
