### ISSUE TITLE
URL / Alias Suggestion

### ISSUE THREAD

**Issue by banuady** [sitespeedio/sitespeed.io#2296]
This is a suggestion, not necessarily an issue:

Inside the report, the full URLs are provided in sections like Pages (table) or Page Summary. In case of a very large URL, it will look better to have the "Alias" provided in the script instead of the full URL.
Another advantage would be to easily match the generated report with Grafana Dashboard.

**Comment by soulgalore** [comment]
Yeah I totally agree, I didn't had the time to add it before the first release but I totally agree, let me fix that for the next release.

**Comment by soulgalore** [comment]
I've fixed it for the page summary and individual page, need to do it for the "Pages" table before releasing it.

**Comment by soulgalore** [comment]
Merged and will release in 8.3.0.

**Comment by banuady** [comment]
Thanks, Peter. This looks fine in 8.3.0

**Comment by soulgalore** [comment]
Great, I will update the docs later today.
