### ISSUE TITLE
Store html result/report assets separate from reports

### ISSUE THREAD

**Issue by fholzer** [sitespeedio/sitespeed.io#2320]
Hi,

first off, thank you for this great project!

We store a large number of html reports in our setup (tens of thousands, planning to increase that soon) and are thinking about ways to reduce storage requirements. One approach is to store all html report assets in a shared location. So instead of writing all js, css, image files to each report directory, we store them centrally (e.g. under "example.com/assets/8.1.1/...", while reports are at "example.com/report/..."). So for each new version of sitespeed we use, we only have one copy of the assets that are used by all of our html reports. With each new version, we export the assets once.

I already have a working implementation that we're planning to use internally: https://github.com/sitespeedio/sitespeed.io/compare/master...fholzer:separate-assets
If you're interested, I can create a PR.

Cheers,
Ferdinand

**Comment by soulgalore** [comment]
Hi @fholzer ! First thank you for the PRs :)

Yes, please do a PR, I think we had that functionality a long time ago, maybe v3 or something like that, but then skipped it (don't remember the reason, but I remember implementing it). Could be we focused on compressing the HARs and now lately trying to make the video as small as possible (but I guess you run without keeping the video?).

Best
Peter

**Comment by fholzer** [comment]
closing, as PR has been merged.
cheers,f
