### ISSUE TITLE
Using pageCompleteCheck for a single page inside the script

### ISSUE THREAD

**Issue by banuady** [sitespeedio/sitespeed.io#2323]
Using the docker image 8.6.0, I tried to apply the --browsertime.pageCompleteCheck for a script. Here is my command:

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.6.0 --multi script.js --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 20000;} catch(e) {} return true;})()'

The script will contain multiple pages, some pages using long polling. There is only 1 page for which I would like to manually apply the above script, however, using --browsertime.pageCompleteCheck seems to be applied to all pages with long polling, which is not intended. Without --browsertime.pageCompleteCheck all long polling pages are measured ok.

It would be nice to be able to use js.runAndWait() inside the script.js for that particular page and remove --browsertime.pageCompleteCheck from the command line. I tried something like this, but it didn't seem to work:

```
module.exports = async function(context, commands) {
    // measuring other pages including long polling
  
    // this page requires longer wait time
    await commands.js.runAndWait('return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 20000;} catch(e) {} return true;})()');
    await commands.measure.start('https://<my_web_page>', "My Web Page");
}
```
This might be already implemented, but I was not able to implement it based on the documentation and the above script is not working as intended.

Thanks,
Adrian

**Comment by soulgalore** [comment]
Hi @banuady ! Ah see. I think I have a way of doing it, let me know it works out for you and then we can add a section in the docs:

```
module.exports = async function(context, commands) {
  // First test a couple pages with default page complete test...
   await commands.measure.start('https://<page1>');
   await commands.measure.start('https://<page2>');
   await commands.measure.start('https://<page3>');

  // Then we have a page that we know need another setting 
  await command.measure.start('MySpecialPage');
  await commands.navigate('https://<myspecialpage>'); 
  // Maybe we are missing something to wait on let me know
  // Or run your custom JS that returns when something special happens
  await commands.wait.byId(id, 20000);
  // And then when you know that page had loaded stop the measurement
  // = stop the video, collect metrics etc
  return commands.measure.stop();
}

```

Best
Peter

**Comment by banuady** [comment]
Thanks Peter,

This is quite a nice solution. It works for me.

Best regards,
Adrian

**Comment by soulgalore** [comment]
Perfect, I've updated the documentation with that example.
