### ISSUE TITLE
Waterfall labels not shown completely

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2324]
Sitespeed 8.6.0 (and prior versions)

I was not able to determine how this style flowed from the css, but I noticed that I can fix this if I set svg:not(:root) overflow to 'visible'.

![image](https://user-images.githubusercontent.com/24658347/53036830-e1570b80-3435-11e9-88a9-f17a12aca34d.png)

**Comment by soulgalore** [comment]
Hi @leathej1 ah thanks for reporting!

Best
Peter

**Comment by soulgalore** [comment]
I think should be fixed in https://github.com/micmro/PerfCascade
