### ISSUE TITLE
Google Cloud storage bucket

### ISSUE THREAD

**Issue by mliljedahl** [sitespeedio/sitespeed.io#2329]
I just wrote a plugin for storing the results in a Google Cloud storage bucket. But before I make a pull request of it I would like to align it to the S3 plugin that already exists. Then I came across a few questions. 

When trying to implement the `path` option that exists in S3 and also sending annotations to Graphite the resultUrls is completely ignoring the `path` option giving me:

```INFO: [sitespeedio] Find the result at https://storage.googleapis.com/bucketname/www.my-domain.com/2019-02-21-10-49-01```

Instead of (setting path to `my-sub-folder/test1`):

```INFO: [sitespeedio] Find the result at https://storage.googleapis.com/bucketname/my-sub-folder/test1```

This gives wrong urls in the annotations.
 
I do not have the possibility to test the S3 storage plugin but to me it looks like the same problem exists there? I have also inspected the `message` in the Graphite plugin and cant find any info about the path in there and also the Graphite plugin looks like it is run before storing the results in S3?

As a bonus it would be nice to not having to specify a `--resultBaseURL` when using S3 (or any other storage) where it would be possible to default to an url connected to the storage provider; `https://storage.googleapis.com` in the GCS case if it is not set.

Tested using the master branch pulled a few minutes ago.

**Comment by soulgalore** [comment]
Hi @mliljedahl aha cool!

> I do not have the possibility to test the S3 storage plugin but to me it looks like the same problem exists there? I have also inspected the `message` in the Graphite plugin and cant find any info about the path in there and also the Graphite plugin looks like it is run before storing the results in S3?

Hmm yeah that sounds like a bug and something we missed then. I haven't used that part for a long time and I'm not 100% sure how it would work, need to look into it.

Best
Peter

**Comment by soulgalore** [comment]
> As a bonus it would be nice to not having to specify a `--resultBaseURL` when using S3 (or any other storage) where it would be possible to default to an url connected to the storage provider; `https://storage.googleapis.com` in the GCS case if it is not set.

Yes that would be cool, good idea, let us add that as separate issue!

**Comment by soulgalore** [comment]
Ping @beenanner since I guess you are also interested in this :)

**Comment by beenanner** [comment]
Very much so let me take a look at this!

**Comment by soulgalore** [comment]
@beenanner cool! Do you mean you help @mliljedahl if he needs any help or do you mean you fix the bug #2330 he found? Or implement #2331? :)

**Comment by beenanner** [comment]
@mliljedahl feel free to take a stab at the fixes if you have time. Lots of stuff going on at my day job for the next few months, but I will try to help when I find time here and there.

**Comment by soulgalore** [comment]
Released earlier this year, thank you @mliljedahl !
