### ISSUE TITLE
frontend_report issue

### ISSUE THREAD

**Issue by KimberlyGT** [sitespeedio/sitespeed.io#2337]
Hi i have this problem...i don't know the reason , please help me 

cp: 'frontend_report/assets.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/assets.html' are the same file
cp: 'frontend_report/css' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/css' are the same file
cp: 'frontend_report/detailed.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/detailed.html' are the same file
cp: 'frontend_report/domains.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/domains.html' are the same file
cp: 'frontend_report/errors.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/errors.html' are the same file
cp: 'frontend_report/font' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/font' are the same file
cp: 'frontend_report/help.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/help.html' are the same file
cp: 'frontend_report/img' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/img' are the same file
cp: 'frontend_report/index.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/index.html' are the same file
cp: 'frontend_report/js' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/js' are the same file
cp: 'frontend_report/logs' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/logs' are the same file
cp: 'frontend_report/pages' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/pages' are the same file
cp: 'frontend_report/pages.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/pages.html' are the same file
cp: 'frontend_report/toplist.html' and '/var/jenkins_home/workspace/FrontendJob/frontend_report/toplist.html' are the same file
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/jenkins_home/workspace/FrontendJob/frontend_report to /var/jenkins_home/jobs/FrontendJob/builds/2338/htmlreports/frontend_5freport
Finished: FAILURE

**Comment by soulgalore** [comment]
Hi @KimberlyGT it looks like a problem in Jenkins when trying to move the report? Are you using the latest version of sitespeed.io and can you help us by describing how you run? See
https://www.sitespeed.io/documentation/sitespeed.io/bug-report/

Thanks
Peter

**Comment by soulgalore** [comment]
Closing this since we didn't get more, but please let us know if you still need help!
