### ISSUE TITLE
Budget files with scripting does not work

### ISSUE THREAD

**Issue by lukaszmorawski** [sitespeedio/sitespeed.io#2338]
Hi,
It seems that when using scripting, the budget files does not work. junit.xml file is generated and produce output like this:
`advice.performance.score is undefined and limit min undefined`

Budget file:
`{
  "browsertime.pageSummary": [{
    "metric": "statistics.timings.pageTimings.pageLoadTime.mean",
    "max": 5000
    }],
	"coach.pageSummary": [{
    "metric": "advice.performance.score",
    "min": 50
  }]
}`

Script looks like this (it contains multiple measurement actions and goes through multiple pages):

`await commands.measure.start('proceed-to-step-2-action');
	await commands.click.byXpathAndWait('somepath');
	//Wait for Email field to be visible
	await commands.wait.byXpath('somepath', 10000);
	await commands.measure.stop();`

and commandline (node.js version but the same on docker):
`sitespeed.io --influxdb.host myhost --influxdb.username user --influxdb.password mypass --influxdb.database sitespeed --config config.json --outputFolder output myscript.js --multi --budget.configPath budget.json --budget.output junit`

**Comment by soulgalore** [comment]
Hi @lukaszmorawski thanks for your report. Which sitespeed.io version are you using? 8.5.0 fixed a bug introduced in 8.3.0 for JUnit budget output. Latest version is 8.6.3. We also introduced a simpler budget format in 8.0 if you haven't seen it https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/#the-budget-file

Internally it "should" not be any difference how you run. Budget plugin act on page summary messages that sent in the internal queue after a page has been tested. I say "should" if there's s bug there :)

Best
Peter

**Comment by lukaszmorawski** [comment]
Hi @soulgalore,

I use: `nodejs: v10.15.1 sitespeed.io: 8.6.3 browsertime: 4.4.7 coach: 3.2.1`. 
Using new budget:
`{
 "budget": {
    "timings": {
      "SpeedIndex":1000
    }
 }
}`

I get an empty.junit.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<testsuites/>`

And budget.html  says:
`The result of the performance budget. We got 0 failing and 0 working`

best regards,
Łukasz Morawski

**Comment by soulgalore** [comment]
Ok and you run with Docker with video/visual metrics turned on (default if you use Docker)? Just want to be 100% sure :) If you run with NodeJs as in your first example you need to turn on video recording (and installing FFMPEG/Imagemagick etc).

If you don't use Docker change the SpeedIndex to firstPaint instead (that is always collected direct from the browser):
`{ "budget": { "timings": { "firstPaint":1000 } } }`


Best
Peter

**Comment by lukaszmorawski** [comment]
On node.js when switched to `{ "budget": { "timings": { "firstPaint":1000 } } }` it works fine.

On docker I run:
`docker run --rm -v ${WORKSPACE}:/sitespeed.io sitespeedio/sitespeed.io:8.6.2 --influxdb.host myhost --influxdb.username myuser --influxdb.password mypass --influxdb.database sitespeed --config config.json --outputFolder output script.js --multi --budget.configPath budget.json --budget.output junit`

but during the tests I get:
`[2019-02-21 10:41:37] ERROR: The video recording start is zero, either no orange is there in the video or VisualMetrics failed.
[2019-02-21 10:41:47] ERROR: Visual Metrics failed to analyse the video Error: Command failed: /usr/src/app/node_modules/browsertime/vendor/visualmetrics.py --dir somepathhere/query-033c2401/data/video/images/1 --video somepathhere/query-033c2401/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport -q 75
10:41:42.622 - Input video file somepathhere/query-033c2401/data/video/1.mp4 does not exist


10:41:42.622 - Input video file somepathhere/enrollment/query-033c2401/data/video/1.mp4 does not exist


    at makeError (/usr/src/app/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

and then junit.xml is:
`advice.performance.score is undefined and limit min undefined`

Metrics are set to Influx with success (if this matter, anyways).

best regards,
Łukasz Morawski

**Comment by soulgalore** [comment]
Ok, for the visual metrics failure: 

1. Can you try setting some connectivity when you test (https://www.sitespeed.io/documentation/sitespeed.io/connectivity/) if you haven't already.
2. To debug what's going I need to have the exact URL and script, any chance you can email me:? peter [AT] soulgalore [dot] com and I will have a look tonight.

Best
Peter

**Comment by lukaszmorawski** [comment]
So, it seems that it helped. Despite the error, metrics are sent to Influx and new budget works. Last thing for me hard to figure out is how to refer PageLoadTime in budget file.
Something like this:
`{
"budget": {
    "timings": {
      "Load": 5000,
      "PageLoadTime": 5000
    },    
    "score": {      
      "performance": 50
    }
  }
}`

seems not working (only "Score" is evaluated).

best,
Łukasz Morawski

**Comment by soulgalore** [comment]
Hi,  pageLoadTime hasn’t been added yet, check here which one you can use at the moment:
https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/#full-example

We can add more timings like pageLoadTime later on.
Best
Peter

**Comment by lukaszmorawski** [comment]
Hi,

That would be great to have that, since the old way gave a lot of freedom and flexibility in term of budgets.
Thanks, I guess we can close this one.

best regards,
Łukasz Morawski

**Comment by soulgalore** [comment]
I added pageLoadTime that I'll merge when we release next minor release, maybe the coming weekend.

Best
Peter
