### ISSUE TITLE
Spurious pages are listed in Grafana

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2341]
All 8.x versions of Sitespeed.io thus far have been experiencing this issue.

For some reason, I am seeing extra pages listed in Grafana.

Script:
```module.exports = async function (context, commands) {
    await commands.measure.start('https://<myapp>/Platform/login', 'Launch Platform');
    try {
        await commands.js.runAndWait('document.querySelector(\'#formNew > p:nth-child(3) > input\').value = \'<name>'');
        await commands.js.runAndWait('document.querySelector(\'#formNew > p:nth-child(5) > div > input\').value = \'<password>\'');
        await commands.js.runAndWait('document.querySelector(\'#formNew > label > span\').click();');
        await commands.measure.start('Login');
        await commands.js.runAndWait('document.querySelector(\'#formNew > p.submit > input[type="submit"]\').click();');
        await commands.measure.stop();
        await commands.measure.start('https://<myapp>/apps/agent/#/', 'Open CRM');
        } catch (e) {
    }
};
```

And I am calling it by `docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io login-voice-rc.js --config config-rc.json`

What I see in Grafana is that 'Open CRM' is listed, but also '_apps_agent_', which is reflective of '/apps/agent'

![image](https://user-images.githubusercontent.com/24658347/53267686-33e83000-36a1-11e9-8e34-a6a1cad82150.png)

**Comment by soulgalore** [comment]
Hi @leathej1 thanks for creating the issue. I've seen part of this too but I haven't been able to recreate on my local machine. I think it's a bug in how we convert the Chrome trace log to a HAR but I will look into it this weekend and hopefully fix it.

Best
Peter

**Comment by soulgalore** [comment]
Hi @leathej1 one thing that seems to be unclear in the documentation, the difference between `commands.js.runAndWait`  and `commands.js.run`. I'll try to explain it better in the documentation but will start here first: All commands that ends with ...andWait means that it will wait for page to finish loading using the pageCompleteCheck see https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test.

The await that is before all commands means in JavaScript that you should wait until the command has finished until moving on to the next commands. So in your script, I think you can simplify (and make it run faster) if you don't wait on pages to finish loading when you don't navigate to a new page. I'll add some comments yo your code:

```
// Here we measure navigating to the start page where you login
await commands.measure.start('https://<myapp>/Platform/login', 'Launch Platform');
    try {
        // Then we wanna add texts, fill in fields etc, then we do not need to wait on page complete check
        await commands.js.run('document.querySelector(\'#formNew > p:nth-child(3) > input\').value = \'<name>'');,
        await commands.js.run('document.querySelector(\'#formNew > p:nth-child(5) > div > input\').value = \'<password>\'');
        await commands.js.run('document.querySelector(\'#formNew > label > span\').click();');
        await commands.measure.start('Login');
        // Here we click on the link tio login the user, that  will generate a new page view so we 
        // need to wait for that to finish
        await commands.js.runAndWait('document.querySelector(\'#formNew > p.submit > input[type="submit"]\').click();');
        await commands.measure.stop();
        await commands.measure.start('https://<myapp>/apps/agent/#/', 'Open CRM');
        } catch (e) {
    }
```

Best
Peter

**Comment by soulgalore** [comment]
@leathej1 You got mail :) If you could try to remove the faulty ones so we are sure that they are recreated and wasn't created with a run without the alias, that would be great :)

**Comment by leathej1** [comment]
I'd like to, but I am having a really hard time following the instructions
for moving grafana.db to a host directory, and keep docker-compose.yml in
sync.

**Comment by soulgalore** [comment]
Ok, the Grafana db is only for annotations. Have you mounted the whisper file for Graphite (as in the running Graphite in prod instructions) or do you run everything in the container? I’m on vacation this week but can help out later this week with better instructions when I’m back online.
Best
Peter

**Comment by leathej1** [comment]
Oh! Don't worry - I'll try some things and follow up next week if I get
stuck again.

Have a great holiday!

**Comment by leathej1** [comment]
I added a new test and experienced the same behavior, if that helps. I'm
still struggling to manage the mounting of graphite.db, so I haven't
checked to see if I can clear those columns out and try again.

James

**Comment by soulgalore** [comment]
Ok, I couldn't reproduce locally it when I tried last week but let me set up the use case on another server where more logs to collect so I can see what happens.

**Comment by soulgalore** [comment]
Adding some extra info here: I got reproducible test case from @leathej1 and it helps so much to get reproducible test case. The problem was that alias of the URL is sent on the queue, but in some cases the alias was sent after other messages with metrics, so those metrics used the URL instead of the alias. Fix coming up soon.

**Comment by leathej1** [comment]
👍
