### ISSUE TITLE
Update Jenkins documentation

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2346]
We need to document how you run Docker from your Jenkins instances (that runs Docker). When we started that was not a thing but I think now there's a best practice.

We also should add examples of how to run Jenkins agents running sitespeed.io

**Comment by leathej1** [comment]
Yes, please.

**Comment by soulgalore** [comment]
Hoping for a PR for that, since I'm no Jenkins user.

**Comment by patoperpe** [comment]
Hi! I modified the entry point of the image **sitespeedio/sitespeed.io** to be able to use it as a docker agent for a stage.
`docker
FROM sitespeedio/sitespeed.io
ENTRYPOINT [ "/bin/sh", "-c" ]
`
My jenkinsfile is the following, it generates the report and the save it as an artifact for that stage.
`pipeline {
  agent {
    docker {
      image 'registry.gitlab.com/singletonsd/docker/sitespeed.io'
    }
  }
  stages {
    stage('git') {
      steps {
        git(url: 'GIT_URL', branch: 'master', credentialsId: 'CREDENTIALS_ID')
      }
    }
        stage('test') {
          steps {
            dir(path: 'audit-runtime') {
              sh '/start.sh --config config.json urls.txt'
            }
          }
        }
      }
  post {
    always {
      archiveArtifacts artifacts: 'audit-runtime/sitespeed-result/**', fingerprint: true
    }
  }
}
`
Now I'm trying to connect the output report to Graphite. Is there any way to send the report manually after the report is generated?

**Comment by soulgalore** [comment]
Hi @patoperpe aha cool.

One thing, I wonder if it Is possible to use `--entrypoint` for Docker run to override the default one instead of needing to create your own image? I'm not familiar with the Jenkins syntax for running Docker.

> Now I'm trying to connect the output report to Graphite. Is there any way to send the report manually after the report is generated?

There's no way for you do do it with just configuring Graphite (`--graphite.host` etc) when you run? If you don't do it like that, its a lot of extra work. You can store the raw data as JSON (use the analysis storer plugin) and then cherry pick the metrics you wanna send.

Best
Peter

**Comment by patoperpe** [comment]
I tried several times to change the entry point inside jenkina agent without success. So my only way to make it work was modifying the entry point to default so that it can be used for an stage.

The problem of configuring the graphite's host is that when you run Jenkins inside a jekins container, each stage of pipeline is ran inside a container isolated for everything but the Jenkins container (they are connected by a network). If you set up an infrastructure with graphite (as you provide in your web site, which it is very helpful by the way 😊), the container running sitespeed can't connect to the one with graphite because of the isolation.

So, one way to tackle this problem is to generate the reports in one stage and then send it from Jenkins container to graphite.

Sorry if my explanation is not so clear, I tried to be the more simple as I can.

Thanks anyone to answer so quickly and congratulations for your tool. It's really usable!

**Comment by soulgalore** [comment]
Thanks @patoperpe for the explanation. I see. Let me think a while if that's fixable in an easy way. 

In. what stage would it be possible for you to send the metrics?

Best
Peter

**Comment by patoperpetua** [comment]
Hi! At the end of the pipeline, I have a task which runs always when the test finishes as you see here:
bash```post { 
always { archiveArtifacts artifacts: 'audit-runtime/sitespeed-result/**', fingerprint: true 
SEND_REPORTS_HERE
} 
} 
} ` 

Best
Pato

**Comment by soulgalore** [comment]
Hi @patoperpetua ok thanks. I will try to setup Jenkins with an agent when I get some time (probably in September), maybe we could simplify parts on our side so its easier to just use in Jenkins. I'll ask you for help when I get there if thats ok :)

Best
Peter

**Comment by patoperpetua** [comment]
Cool! Yes, of course. Whatever you need send me a message.

Thanks!

**Comment by patoperpetua** [comment]
Hello! I had an idea and I got sitespeed working along with grafana and jenkins. The trick is to connect to graphite throw container gateway.
The following script gets the gateway of the running container:
`def target_host = '''$(printf "%d.%d.%d.%d" $(awk '$2 == 00000000 && $7 == 00000000 { for (i = 8; i >= 2; i=i-2) { print "0x" substr($3, i-1, 2) } }' /proc/net/route))'''`

And then you pass that address to graphite.host variable:
`sh """/start.sh --config config.json urls.txt --outputFolder=reports --graphite.host=${target_host}"""`

Also, here there is my jenkinsfile:
`
pipeline {
  agent {
      docker {
          image 'egl_sitespeed-io'
      }
  }
  stages {
    stage('git') {
      steps {
        git(url: 'git@gitlab.com:.git', branch: 'master', credentialsId: 'jenkins-deploy_key')
      }
    }
    stage('test') {
          steps {
                script {
                        def target_host = '''$(printf "%d.%d.%d.%d" $(awk '$2 == 00000000 && $7 == 00000000 { for (i = 8; i >= 2; i=i-2) { print "0x" substr($3, i-1, 2) } }' /proc/net/route))'''
                        sh """/start.sh --config config.json urls.txt --outputFolder=reports --graphite.host=${target_host}"""
                }
          }
    }
}
`

The docker image is the same image as **sitespeedio/sitespeed.io** but without the entrypoint.

I hope this could help.

**Comment by soulgalore** [comment]
Hi @patoperpetua ah cool! I've haven't had time yet to try out anything on Jenkins. If you feel like it, it would be great if you could do a PR for the docs to share your findings.

Best
Peter

**Comment by patoperpetua** [comment]
Yes, sure. Where do you want to put in?

**Comment by soulgalore** [comment]
Great! Somewhere in the Jenkins settings where you think ut works: https://github.com/sitespeedio/sitespeed.io/blob/master/docs/documentation/sitespeed.io/continuous-integration/index.md

**Comment by patoperpetua** [comment]
Done! [PR 2601](https://github.com/sitespeedio/sitespeed.io/pull/2601)

**Comment by soulgalore** [comment]
Oops, that PR never got merged, let me fix that tomorrow.
