### ISSUE TITLE
Frequency of tests

### ISSUE THREAD

**Issue by gety9** [sitespeedio/sitespeed.io#2347]
Guys hi,

Not an issue, but more of a question

What is recommended frequency of tests?
 
If we'd like to test only 3 times a day should it be during peak load (when most visitors visit the website) or or least load periods?

**Comment by beenanner** [comment]
Depends on your visitors traffic patterns, caching, and how much your budget is willing to afford. I would try to have more than 1 run say 3 to 5 runs to get an avg for any single test and at a minimum you probably want 3 to 5  tests a day to get an idea of site impact throughout any one day. Remember the more you can the test the more you can potentially learn about your user's experience and improve it!

**Comment by soulgalore** [comment]
@beenanner I think in general we are missing out on documentation on a high level, I've started "performance testing in practice" docs that aims to be tool independent, I'll share the branch in a couple of weeks when I had time to get further. @gety9 question is perfect for that.

I also would like to start to try out organising parts of the documentation as run books https://en.wikipedia.org/wiki/Runbook - Timo at work has started doing it for our performance related stuff and I think we could do the same.

**Comment by gety9** [comment]
@beenanner 

thanks for reply, for now i made 3 tests a day 5 runs each.
The reason i asked the question cause when looking at dashboard.sitespeed.io
i see that wikipidia.com stats vary greatly by time of the day so for this kind of site hourly might be needed, but for ryanair it's pretty stable.

@soulgalore 
it would be great!

One more question not related to this one.
What is the difference between transfer size and content size, and why are they so different for js here
https://puu.sh/CRtgf/dbf952dacd.png
?

**Comment by beenanner** [comment]
Transfer would take in account gzipping

**Comment by soulgalore** [comment]
The variation usually depends on either the server you use to run the test and the content that is served. For most sites First Visual Change is a ok metric to focus on since best case ads etc will not change that metrics (if it do you need to check your inplementetion). 

Best
Peter

**Comment by gety9** [comment]
@beenanner @soulgalore 

> Transfer would take in account gzipping

got it

> For most sites First Visual Change is a ok metric to focus

got it

When recording site speed it must be exactly same website that users see (including all tags - like GTM, Google Analytic, FB pixel, Mouseflow, etc) - correct?

We have interal cookie that disables all tags, and that's what we were planning to use not to litter analytics/stats with sitespeed tester visits, but this way i guess results will not be 100% accurate.

So i as i understand we must enable all tags, and than filter this traffic inside the tools (GA, FB pixel, etc) .
Did i understand this right?

**Comment by soulgalore** [comment]
Aha, I think you should test both then, because then you can more easily keep track of how much the tags impact performance. It's easier then to see if some of your own code changes impact the performance vs the tags.

Best
Peter

**Comment by gety9** [comment]
@soulgalore 

1
>I think you should test both then

looked more into it, and tools (GA, FB pixel, etc) do not have option to exclude by cookie, so the only way is to attach static IP to testing instances and exclude by IP. But than you have to pay for unused IPs when instances are stopped. i guess we will just test with tags disabled for now (will disable all tags in GTM which has option to filter by cookie).

2
Also in your experience do slower speeds result in lesser location specific site speed difference?
For example first visual change on our desktop site with cable connection throttling is about ~50% faster for ohio (US) vs london(UK).
But for mobile site with 3g throttling there is no difference for first visual change between locations, which is a little strange to me.  
https://puu.sh/CTuBM/3e9886f7d7.png

Is it expected behavior?

**Comment by soulgalore** [comment]
> 2
Yeah that seems strange, look into the HAR/waterfall and verify that everything looks right (look at the ttfb/download times to see that the throttling/connectivity really works). Adding latency should make things slower so the longer from the source, the slower load.

**Comment by gety9** [comment]
@soulgalore 

> look into the HAR/waterfall and verify that everything looks right (look at the ttfb/download times to see that the throttling/connectivity really works)

Do you mean to look at "receive"? For page itself and first css file london's receive is much much faster than for ohio https://puu.sh/CTwCr/554f40b012.png

> Adding latency should make things slower so the longer from the source, the slower load.

that's what i expect too

**Comment by soulgalore** [comment]
Sorry I missed how did you setup https://www.sitespeed.io/documentation/sitespeed.io/connectivity/ ?

**Comment by gety9** [comment]
@soulgalore 

Seems like problem was with how docker resolves DNS on different Ubuntu versions.
https://github.com/docker/libnetwork/issues/2187

After Ubuntu update on london instance results look more trustworthy:
https://puu.sh/CUJHT/97e0b119eb.png
Could you please confirm that now everything looks right?

Also do i understand it correctly that when comparing 3g ohio and 3g london that "receive" should be about the same, and difference will be in "connect" and "wait" ?

**Comment by soulgalore** [comment]
So what kind of connectivity are you using, you didn't answer that? If you don't set a connectivity it will run on the current internet connection on the host.

**Comment by gety9** [comment]
@soulgalore 

we are using docker network
https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#docker-networks

**Comment by soulgalore** [comment]
Anything more needed from us here?

**Comment by gety9** [comment]
@soulgalore

we've managed to solve it,
problem was OS version on instance server
