### ISSUE TITLE
[Info needed] CPU Metrics support in Firefox browser

### ISSUE THREAD

**Issue by rockmax-rajat** [sitespeedio/sitespeed.io#2349]
As far as I can make out, we are supporting CPU metrics like scripting, painting, rendering etc only in Chrome.
Are we supporting these in Firefox as well?

If not, are there any plans to add this in future sitespeed releases?

**Comment by soulgalore** [comment]
Yes when Firefox add supports for it. There's an upstream tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1250290

Best
Peter

**Comment by soulgalore** [comment]
Closing until FF supports it.
