### ISSUE TITLE
Error trying to install using npm on Windows 10

### ISSUE THREAD

**Issue by dhAlcojor** [sitespeedio/sitespeed.io#2350]
Hi, I was trying to install sitespeed.io using npm on Windows 10 with the following command:

`npm install -g sitespeed.io`

After installing python (first error I got) I'm getting this one:
![image](https://user-images.githubusercontent.com/567687/53421059-3f0ec900-39dd-11e9-8e0c-ddc462445de4.png)

**Comment by soulgalore** [comment]
Hi @dhAlcojor 
we only support Docker on Windows see https://www.sitespeed.io/documentation/sitespeed.io/installation/#windows-1

Best
Peter

**Comment by dhAlcojor** [comment]
I see. Thank you!
