### ISSUE TITLE
Annotations help

### ISSUE THREAD

**Issue by luisxiaomai** [sitespeedio/sitespeed.io#2356]
I followed annotation section from https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/.

When I run command with `--graphite.host=127.0.0.1 --graphite.auth guest:guest --resultBaseURL=http://127.0.0.1:9900 --graphite.annotationScreenshot` parameters, I got bellow error:
```
ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

What's wrong here? Tanks for any help...

**Comment by soulgalore** [comment]
Hi @luisxiaomai The error is that it cannot send the metrics to Graphite, how do you run sitespeed.io? If you run inside of a Docker container it will map 127.0.0.1 to that container not localhost on your server.

Best
Peter

**Comment by luisxiaomai** [comment]
@soulgalore , I run graphite , grafana, sitespeed.io in one server. Run sitespeed.ios like  `docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.6.4 -n 1 script.js --multi --graphite.host=127.0.0.1 --graphite.auth guest:guest --resultBaseURL=http://127.0.0.1:9900 --graphite.annotationScreenshot`. Run graphite, grafana use docker-compose followed https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/.

**Comment by luisxiaomai** [comment]
@soulgalore , I solved annotation based on your comments and enabled it in grafana. Thanks again.

**Comment by soulgalore** [comment]
Ah great, I've missed getting back, sorry.
