### ISSUE TITLE
Unable to run few containers of sitespeed.io

### ISSUE THREAD

**Issue by MaximSergeichik** [sitespeedio/sitespeed.io#2364]
Hi,

I faced an issue with the run of the sitespeed.io through docker containers.
When I try to run test while previous one is not finished I receive following error:
`[2019-03-06 14:53:17] ERROR: [sitespeedio.queuehandler] Error: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 

    at ChildProcess.self._process.on (/usr/src/app/node_modules/@cypress/xvfb/index.js:189:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)`

Run command
`sudo -S docker run --net=host --shm-size=1g --rm -v "$(pwd)":/sitespeed.io -v "/disk2/server/result/":/sitespeed.io/sitespeed-result \
	sitespeedio/sitespeed.io:8.6.5-plus1 -n 3 -b chrome --chrome.timeline -vvv --debug \
	--graphite.host=$host --graphite.port=2003 --graphite.httpPort=80 --graphite.namespace "sitespeed_desktop_test."$2 --graphite.auth $user:$pass \
	--graphite.annotationScreenshot --graphite.annotationTag "desktop" \
	--browsertime.viewPort 1920x1080 --browsertime.pageCompleteCheckInactivity=true --browsertime.chrome.args ignore-certificate-errors \
	--resultBaseURL http://$host:81/result/desktop_$2 --outputFolder /sitespeed.io/sitespeed-result/desktop_$2/$dt  $1 \
	--lighthouse.settings.emulatedFormFactor desktop --lighthouse.settings.throttlingMethod devtools --lighthouse.settings.disableDeviceEmulation \
	--lighthouse.settings.throttling.rttMs 0 --lighthouse.settings.throttling.throughputKbps 1000000 --lighthouse.settings.throttling.requestLatencyMs 0 --lighthouse.settings.throttling.downloadThroughputKbps 1000000 --lighthouse.settings.throttling.uploadThroughputKbps 1000000 --lighthouse.settings.throttling.cpuSlowdownMultiplier 1 \
	--metrics.filter lighthouse.pageSummary.audits.first-contentful-paint.rawValue lighthouse.pageSummary.audits.first-meaningful-paint.rawValue lighthouse.pageSummary.audits.first-cpu-idle.rawValue lighthouse.pageSummary.audits.interactive.rawValue lighthouse.pageSummary.audits.speed-index.rawValue \
	--plugins.add /lighthouse`

Sitespeed version: 8.6.5-plus1
OS: Centos7 64bit

Best Regards,
Maksim

**Comment by soulgalore** [comment]
Hi @MaximSergeichik  I never tried running multiple containers since the metrics probably will be affected. Checking duckduckgo it seems to be CentOs? What you can do is run headless. (--headless) but then you also need to disable xvfb (--browsertime.xvfb false) and disable video (--browsertime.video false and --browsertime.visualMetrics false). I think thats's the right parameters.

Best
Peter

**Comment by MaximSergeichik** [comment]
Hi @soulgalore,

Yes, I use Centos.
As far as I know there shouldn't be any affect on the metrics if there is enough hardware resources on the machine. Maybe you can look for some solution for this situation since run headless is not suitable for my purpose.

Best Regards,
Maksim

**Comment by soulgalore** [comment]
Try it first on Ubuntu/Debian and see if it is an CentOS issue. Also if you haven't read checkout the Lighthouse docs for throttling https://github.com/GoogleChrome/lighthouse/blob/9ba7199409c6142b9e64892eb4f33d446e7072a5/docs/throttling.md to get stable metrics.

Best
Peter

**Comment by soulgalore** [comment]
Hi @PedroMSantosD I think you need to specify browsertime for the xvfb parameters, something like ` --browsertime.xvfbParams.display`? I could add an alias in coming releases maybe.

Best
Peter

**Comment by soulgalore** [comment]
Ah good. Let me know if you remember if you saw the faulty ones in the documentation somewhere (so I can change that), could be that we missed it somewhere.

Best
Peter
