### ISSUE TITLE
Day.js official UTC plugin

### ISSUE THREAD

**Issue by xxyuk** [sitespeedio/sitespeed.io#2365]
In dayjs v1.8.9 there is a packed UTC plugin, you could simply `import UTC from 'dayjs/plugin/utc'`, to set Day.js in UTC mode.

We might could give it a try, to keep update with the original package.

This is also referenced in #2233 

>use extended dayjs until dayjs supports utc

**Comment by soulgalore** [comment]
Hi @xxyuk aha cool, yes let us try that.

Best
Peter

**Comment by iamkun** [comment]
Great, I'm glad to help if needed. 😁 

Cheers!

**Comment by soulgalore** [comment]
@iamkun great, if you have time please do a PR :)

Thanks 
Peter

**Comment by soulgalore** [comment]
Fixed, going out in the next release.

**Comment by xxyuk** [comment]
Cool
