### ISSUE TITLE
lib/plugins/html/assets not present in npm package

### ISSUE THREAD

**Issue by conraid** [sitespeedio/sitespeed.io#2366]
There isn't _lib/plugins/html/assets_ directory in the _https://registry.npmjs.org/sitespeed.io/-/sitespeed.io-8.7.1.tgz_ and 8.7.0 packages.
And the command ends with...
`[2019-03-07 15:06:12] ERROR: Error: ENOENT: no such file or directory, stat '/usr/lib64/node_modules/sitespeed.io/lib/plugins/html/assets'`

**Comment by soulgalore** [comment]
Hi @conraid can you show me how you run?
Best
Peter

**Comment by conraid** [comment]
`$ sitespeed.io -b firefox https://conraid.net`

If you look in package on registry.npmjs.org see that the dir is missing, which instead is presented in the repository and in the tar.gz file downloadable from github.

I'm sorry for my bad english.

**Comment by soulgalore** [comment]
Thanks, I made a mistake in the .gitignore file. It should work now when npm updates to 8.7.2. Thanks for reporting the issue!

**Comment by soulgalore** [comment]
And running the Docker container it worked, however Travis should (or we should make sure) Travis fails if this happens again.
