### ISSUE TITLE
How to set cookies for preURL

### ISSUE THREAD

**Issue by aravindhan87** [sitespeedio/sitespeed.io#2369]
Hi ,

I am trying to warmup the static assets for the page which are yet to be live in production.

To do so I am setting up the preURL and corresponding cookie followed by the real page. 

Looks like preScript is not honoring the cookie and taking me to the old page.

Can you please help me here.

Command I am using.

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --preURL "https://www.bergdorfgoodman.com/search.jsp?from=rfkSearch&l=Christian%20Louboutin&q=Christian%20Louboutin&N=0&Ntt=Christian%20Louboutin" --cookie name=value --urlAlias searchPage2 "https://www.bergdorfgoodman.com/search.jsp?from=rfkSearch&l=satchel&N=0&Ntt=satchel&q=satchel"  --cookie name=value

Thanks
Aravindhan
-->

**Comment by soulgalore** [comment]
Hi @aravindhan87 
hmm that part is poorly documented. When I look in the code, the preURL happens before we set any cookies. That should probably change.

For you to get it to work, you can try out doing [a script](https://www.sitespeed.io/documentation/sitespeed.io/scripting/): Set the cookie, navigate to the first URL and then measure the second. If you use the navigate command, the cookie will be set before that URL.

Let me know if you need help!

Best
Peter

**Comment by soulgalore** [comment]
You can also set cookies with scripting nowadays. Closing.
