### ISSUE TITLE
Add favicon transferSize to budget file

### ISSUE THREAD

**Issue by PedroMSantosD** [sitespeedio/sitespeed.io#2371]
Hi, current Budget suport ignores favicon tranfer size;

this is my budget file
```
{
"budget": {
    "transferSize": {
      "html": 100000,
      "favicon" : 1000,
      "css": 50000
    }
  }
}
```
This is my test report:
```
[2019-03-11 11:55:22] INFO: Budget: 2 working and 0 failing tests
```

Could you kindly have it addded to validation list on budget processing ?
it is not on this request:
https://github.com/sitespeedio/sitespeed.io/pull/2253/files

![Screen Shot 2019-03-11 at 11 59 46](https://user-images.githubusercontent.com/17711131/54119418-90fc1980-43f5-11e9-9ab1-f8edd984915b.png)

Thanks in advance.

**Comment by PedroMSantosD** [comment]
Btw: old format works like a swarm.
config:
```
{
    "pagexray.pageSummary": [
    {
      "max": 100000,
      "metric": "contentTypes.html.transferSize"
    },
    {
      "max": 1000,
      "metric": "contentTypes.favicon.transferSize"
    },
    {
      "max": 50000,
      "metric": "contentTypes.css.transferSize"
    }
  ]
}
```

outcome:
```
[2019-03-11 12:30:42] INFO: Budget: 3 working and 0 failing tests
```

**Comment by soulgalore** [comment]
Yep you are right, currently we only have support for these ones in the new budget format: https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/#full-example

Any chance you can do a PR for adding it? I'm pretty busy this week but can do it the next week.

Best
Peter

**Comment by PedroMSantosD** [comment]
Hi, I have added this pull request:
https://github.com/sitespeedio/sitespeed.io/pull/2374

Best Regards,

**Comment by PedroMSantosD** [comment]
closing as PR has been merged
