### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by georgsh** [sitespeedio/sitespeed.io#2372]
Hello. I also faced this unclear error message, like many others, spent alot of time with it.
[2289](https://github.com/sitespeedio/sitespeed.io/issues/2287)
[2287](https://github.com/sitespeedio/sitespeed.io/issues/2289)

Is it possible to check all measure.stop() is called for every measure.start() explicitly and display error message like "You should call measure.stop(), check this docs -> ...."?
Thanks.

**Comment by soulgalore** [comment]
Yeah it isn't optimal the way it is now. I've been thinking of adding an automatically stop after a navigation (and keep it backward compatible) but I'm not 100% sure.

I'll look into how to add it lo the log, but sure need to look. The things is that you need top read the docs on how to implement the scripting and somehow it's super hard to read the stop() stuff :) But its seems to be a use case that should have been done in another way.

Best
Peter

**Comment by soulgalore** [comment]
Hi @georgsh I've just pushed 8.7.5 that catches if you miss calling stop and also log it, so hopefully (if it works 100%) it will make it a lot easier to run scripts.

Thanks for creating the issue!

Best
Peter

**Comment by georgsh** [comment]
@soulgalore awesome!
