### ISSUE TITLE
ERROR: Could not upload to Google Cloud Storage 

### ISSUE THREAD

**Issue by primehaxor** [sitespeedio/sitespeed.io#2381]
Hello!

During the page tests, I had some problems during the GCS upload part, I've got two different problems ( I've suppressed the message since it prints my SA key... )

1 - 
```
ERROR: Could not upload to Google Cloud Storage {"message":"request to https://www.googleapis.com/oauth2/v4/token failed, reason: getaddrinfo EAI_AGAIN www.googleapis.com www.googleapis.com:443","type":"system","errno":"EAI_AGAIN","code":"EAI_AGAIN","config
```

2 - 
```
 ERROR: Could not upload to Google Cloud Storage {"message":"request to https://www.googleapis.com/oauth2/v4/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443","type":"system","errno":"ENOTFOUND","code":"ENOTFOUND","config":{"method":"POST","url":"https://www.googleapis.com/oauth2/v4/token"
``` 
Every 4 to 6 request I get into this error...

**docker command:**
```
docker run --rm --network=$net -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.7.5 -c $net $url --graphite.host 10.132.0.43 -n 2 \
	       --browsertime.video --gcs.projectId=my-project --gcs.key=sa.json --gcs.bucketname=my-bucket-sitespeed-io --gcs.removeLocalResult=true
```

Isn't it possible to retry or add some option to set the number of retries?

**Comment by soulgalore** [comment]
Hi @primehaxor it looks like a DNS problem when I looked for the error. Maybe you can try setting up multiple DNS servers as in https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/. 

I remember in the early days of Docker it sometimes helped to restart the Docker daemon.

Best
Peter

**Comment by primehaxor** [comment]
Hello @soulgalore you were right, looks better now!

thx for you help!

**Comment by soulgalore** [comment]
Great!
