### ISSUE TITLE
downloaded graphite.db missing Tag tables

### ISSUE THREAD

**Issue by jasondewitt** [sitespeedio/sitespeed.io#2383]
I'm working on getting the sitespeed.io performance dashboard set up for a production deployment, I am working with the provided docker-compose file (converting it to an ansible playbook) on a server running Centos 7.

 I have noticed a problem with the blank graphite.db I download from the github repo at https://github.com/sitespeedio/sitespeed.io/blob/master/docker/graphite/graphite.db 
This downloaded database seems to be missing the tables for the graphite tagging feautre, which causes those requests to the graphite http tags api to throw a 500 error:

```
19/03/2019 15:39:19 :: [tagdb] Error tagging stats.timers.view.graphite.tags.views.POST.upper: Error response 500 from http://127.0.0.1:80/tags/tagMultiSeries
```

When I try to post to the api from within the container, I get a "no such table" error

```
/ # curl -X POST "http://127.0.0.1/tags/tagMultiSeries" \
>   --data-urlencode 'path=disk.used;rack=a1;datacenter=dc1;server=web01'
{"error": "no such table: tags_series"}
```

When I check the tables in this downloaded database file I see:

```
/opt/graphite/storage # sqlite3 graphite.db
SQLite version 3.24.0 2018-06-04 19:24:41
Enter ".help" for usage hints.
sqlite> .tables
account_mygraph             dashboard_dashboard_owners
account_profile             dashboard_template        
account_variable            dashboard_template_owners 
account_view                django_admin_log          
account_window              django_content_type       
auth_group                  django_migrations         
auth_group_permissions      django_session            
auth_permission             events_event              
auth_user                   tagging_tag               
auth_user_groups            tagging_taggeditem        
auth_user_user_permissions  url_shortener_link        
dashboard_dashboard       
```

When starting up the graphite container with docker-compose, and no volume, the entrypoint script runs all the database migrations and creates the database, which contains more tagging related tables:

```
/ # cd /opt/graphite/storage
/opt/graphite/storage # sqlite3 graphite.db 
SQLite version 3.24.0 2018-06-04 19:24:41
Enter ".help" for usage hints.
sqlite> .tables
account_mygraph             dashboard_template_owners 
account_profile             django_admin_log          
account_variable            django_content_type       
account_view                django_migrations         
account_window              django_session            
auth_group                  events_event              
auth_group_permissions      tagging_tag               
auth_permission             tagging_taggeditem        
auth_user                   tags_series               
auth_user_groups            tags_seriestag            
auth_user_user_permissions  tags_tag                  
dashboard_dashboard         tags_tagvalue             
dashboard_dashboard_owners  url_shortener_link        
dashboard_template        
```

Does the template database need to be updated or am I missing something here?

**Comment by soulgalore** [comment]
Hi @jasondewitt thanks for creating the issue! I think you are right, it needs to be updated. I think I created it before tags was introduced in Graphite (tags for metrics). Tags for annotations should work out of the box. Any change you can contribute a clean updated version? 

Best
Peter

**Comment by jasondewitt** [comment]
@soulgalore yeah, that is possible. I just spun up a fresh copy of the graphite container and copied graphite.db out of there. Im looking it over to make sure it is actually blank. If it looks good I will submit a PR
