### ISSUE TITLE
Missing 8.8.0-plus1

### ISSUE THREAD

**Issue by richardmcsong** [sitespeedio/sitespeed.io#2389]
Hi! I tried pulling 8.8.0-plus1 from docker, but the manifest didn't exist: 
```Error response from daemon: manifest for sitespeedio/sitespeed.io:8.8.0-plus1 not found```
Tried looking on dockerhub itself, and it doesn't seem to be there either.

**Comment by soulgalore** [comment]
Thanks @richardmcsong for creating the issue. Something went wrong with the built and I pushed the version to the Docker hub now: https://cloud.docker.com/u/sitespeedio/repository/docker/sitespeedio/sitespeed.io

Best
Peter

**Comment by richardmcsong** [comment]
Looks like you pushed 8.0.0 instead of 8.8.0.
![Screen Shot 2019-03-21 at 4 21 28 PM](https://user-images.githubusercontent.com/9144514/54782495-6da34c80-4bf5-11e9-9a44-92f154378196.png)

**Comment by soulgalore** [comment]
Ooops, you are right. 8.8.0 is there now.

**Comment by richardmcsong** [comment]
Verified. Closing.
