### ISSUE TITLE
Waterfall - Request Details - Tab buttons not aligned with button text

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2395]
Sitespeed 8.8.3

<img width="646" alt="Screen Shot 2019-03-27 at 9 41 53 AM" src="https://user-images.githubusercontent.com/24658347/55095164-e7fc2280-5074-11e9-8991-ab509ecf6b5c.png">

**Comment by soulgalore** [comment]
Hi @leathej1 
can you give the exact browser version? This is should probably be an upstream issue in https://github.com/micmro/PerfCascade 

If you have time and can try the HAR file in https://micmro.github.io/PerfCascade/ then we know if it's the sitespeed.io version or upstream,

Thanks!
Peter

**Comment by leathej1** [comment]
Sorry - Chrome 73.0.3683.86.

It does align correctly in Firefox.

**Comment by soulgalore** [comment]
Ok thanks @leathej1 ! Are you on Windows? Tried 73 on Mac on https://s3.amazonaws.com/results.sitespeed.io/en.wikipedia.org/2019-03-27-18-59-04/pages/en.wikipedia.org/wiki/Barack_Obama/index.html#waterfall and there it works (at least for me) or could it be depending on content?

**Comment by leathej1** [comment]
Oh, weird. The results you provided do not show the issue. Let me find some
local results to send you.

**Comment by leathej1** [comment]
New detail: Local results will not display this problem. Only results uploaded to S3 will show this behavior.

**Comment by soulgalore** [comment]
Aha, then I would guess it could be that all requests aren't coming through. If you check the network tab of your browser, do you get any 404?

Best
Peter

**Comment by leathej1** [comment]
I thought of that, and no. Everything is there.

**Comment by soulgalore** [comment]
This was so long time ago, hopefully this works now :)
