### ISSUE TITLE
multiple request headers in config file

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2396]
Hello, is it possible to provide multiple request headers in config json file? Or command line parameter -r is the only option?

**Comment by soulgalore** [comment]
Hi @Icecold777 yes it should be, we need to find a better to document that. You can use an array in your configuration: `['key:value', 'key2:value2']` should work.

Best
Peter

**Comment by Icecold777** [comment]
@soulgalore, thank you, will try this)
