### ISSUE TITLE
Issue with daylight saving time

### ISSUE THREAD

**Issue by morty29** [sitespeedio/sitespeed.io#2399]
Hi, I have an issue with daylight saving time, which I believe is either a dayjs issue or of the usage of dayjs.format in sitespeed.
The issue that despite its EDT in new york now - sitespeed is still using EST.
In time in container is working properly, to test that i used `$ docker run --rm -v /usr/share/zoneinfo/America/New_York:/etc/localtime busybox date`

> - Exact how you run

`docker run --shm-size=1g --network=3g --rm -v /usr/share/zoneinfo/America/New_York:/etc/localtime:ro -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.8.3-plus1 --browsertime.iterations 2 https://en.wikipedia.org/wiki/Barack_Obama`

> - OS (if you use Docker, report the base OS)

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Docker version 18.09.3, build 774a1f4

Its an issue mostly coz reports are generated with wrong datetime string, so it sometimes hard to comprehend which one is for which check. Maybe you can confirm if its sitespeed or dayjs issue, or maybe I'm doing something wrong?
Exect results are in screenshot below. Thanks.

![image](https://user-images.githubusercontent.com/9250945/55199169-c8264500-51c1-11e9-8c07-2506ab052acd.png)

**Comment by xxyuk** [comment]
According to their change-log, Day.js supports DST since v1.7.7. What's your version, please?

**Comment by soulgalore** [comment]
Hi @morty29 and @xxyuk 

We [use](https://github.com/sitespeedio/sitespeed.io/blob/master/package.json#L77) DayJs 1.8.9

The log timestamp is from https://www.npmjs.com/package/intel but the file dir (that last dir) should be generated using dayjs. Maybe we create the dayjs object the wrong way?

Best
Peter

**Comment by xxyuk** [comment]
I'd like to check if it's a Day.js problem. 
And is there a simple code that could reproduce this issue?

**Comment by soulgalore** [comment]
Thanks @xxyuk .

This is how we dayjs is used: https://github.com/sitespeedio/sitespeed.io/blob/8bd8c670336888b797fc3b95aa27c95d4ec928e4/lib/sitespeed.js#L49

**Comment by xxyuk** [comment]
That's the exact correct usage. However it can't explain the bug in this issue. 😢

**Comment by soulgalore** [comment]
@morty29 does it work if you pass on `-e TZ= America/New_York ` to the container?

`docker run  -e TZ=America/New_York --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 1 https://www.sitespeed.io `

Best
Peter

**Comment by morty29** [comment]
Yes, it helped, thank you. Closing.
