### ISSUE TITLE
Annotation URLs missing hash for SPA pages

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2400]
8.8.3, Dockerized

Grafana with InfluxDB

When I run a multi step script with several pages in my SPA, the annotations that are created during the run do not have the correct urls for the report pages. This seems to be an issue with only the URLs with hash marks.

For example, the annotation has a URL of:
`http://sitespeed.blahblah.io.s3-website-us-west-2.amazonaws.com/prod-crm_js/2019-03-29-20-00-02/pages/performance2.blahblah.com/apps/home/index.html`

But it should be:
`http://sitespeed.blahblah.io.s3-website-us-west-2.amazonaws.com/prod-crm_js/2019-03-29-20-00-02/pages/performance2.blahblah.com/apps/home/hash-ca2daf9b/index.html`

**Comment by soulgalore** [comment]
Thanks @leathej1 for the report, let me try to fix that before the release that goes out tomorrow. 
Best 
Peter

**Comment by soulgalore** [comment]
I made a PR and will merge ASAP. I think I missed implementing using the hash-configuration in one place. Release going today or tomorrow, need to do a blog post first :)

Best
Peter

**Comment by leathej1** [comment]
I am still not seeing the hash values reflected in the annotation URL.

**Comment by soulgalore** [comment]
Let me have a look tonight.

**Comment by leathej1** [comment]
Hmm. It started magically working in the same version.
"Aliens"
