### ISSUE TITLE
How to get metrics from console.log messages?

### ISSUE THREAD

**Issue by hubchau** [sitespeedio/sitespeed.io#2406]
Hi, 

Not exactly an issue, I just need some help...

I'm trying to gather values that are displayed in `console.log` messages and (hopefully) have them shown in the Sitespeed metrics (back-end rendering time in ms).

Do you think it's doable? Do I have to create my own plugin? Or parse them afterward using a Shell script?

A huge thanks for any tip!

Regards

**Comment by soulgalore** [comment]
Hi @hubchau not out of the box. You could [build a plugin](https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin) that catches the **browsertime.console** message type (if you use Chrome and collect the console log that's the message that is passed in the queue), and then get the actual metrics, but it would be some work to do it.

Best
Peter

Best
Peter

**Comment by soulgalore** [comment]
Closing, let me know if you need more help!
