### ISSUE TITLE
performance.measure() duration

### ISSUE THREAD

**Issue by prsriniv** [sitespeedio/sitespeed.io#2407]
Firstly,
Thanks so much for such an awesome program. I am using sitespeed.io to actually see if I can get some userTimings off of the site I am testing. I am using sitespeed 8.10.0 (the Npm package) as I am testing a local debug build of mine. I am able to see the performance mark and measure time stamp. Is it possible to get the duration of the performance measure? 

As in:
`performance.getEntriesByName("difference")[0].duration`? I can get this from the console.log, but does sitespeed support getting the duration? This is more of a help wanted issue, to see if something like this is supported

**Comment by soulgalore** [comment]
Hi @prsriniv thanks for the kind words. Sorry I missed your question. 

We get the data in Browsertime https://github.com/sitespeedio/browsertime/blob/master/browserscripts/timings/userTimings.js#L21-L27 but I guess then we don't use it/show it in sitespeed.io? Yep that's it, let me fix that.

Best
Peter

**Comment by soulgalore** [comment]
I made a PR that shows the duration, this will come in the next release.

**Comment by prsriniv** [comment]
@soulgalore Thanks a lot for the PR, You are awesome!
