### ISSUE TITLE
Chrome generates broken HAR [was Waterfall is not loading in sitespeed report]

### ISSUE THREAD

**Issue by kabilan-ravi** [sitespeedio/sitespeed.io#2408]
I updated sitespeed to 8.9.0 docker image. Our setup has been connected with graphite db as illustrated in the documentation. Before upgrade the waterfall reports was working good. After upgrade its not displaying properly. The timelines are missing.

Old version: 7.7.2
New version: 8.9.0

Docker image is running in cent os 7
<img width="541" alt="Screenshot 2019-04-04 at 11 26 50 AM" src="https://user-images.githubusercontent.com/8100164/55535090-b9fd8a80-56d3-11e9-884c-ac18eecb4b0d.png">

**Comment by soulgalore** [comment]
Hi @kabilan-ravi thanks for creating the issue. Only thing I know about is that we changed the font size but it shouldn't be that.  If you check you console when you visit the waterfall page, do you see any error there? 

Best
Peter

**Comment by kabilan-ravi** [comment]
Hi @soulgalore, yes there are errors in console. Please refer the screenshot. Errors are from perf.cascade.min.js

<img width="1436" alt="Screenshot 2019-04-04 at 12 25 06 PM" src="https://user-images.githubusercontent.com/8100164/55535425-d1894300-56d4-11e9-85bc-75b283138489.png">

**Comment by kabilan-ravi** [comment]
I think it happens when one of the timeline data has "NaN ms".

**Comment by soulgalore** [comment]
Ok thanks @kabilan-ravi, looks like an upstream issue, if you have time can you create a issue in https://github.com/micmro/PerfCascade/issues (I cannot transfer issues there) and then also include the HAR file is a gist so that it is reproducible.

Thanks!
Peter

**Comment by soulgalore** [comment]
Hmm I wonder if the HAR is broken too? Do you use Chrome or Firefox @kabilan-ravi ? Thinking it could be multiple issues, if its something wrong with the HAR for Chrome it something we should try fix on our side.

**Comment by kabilan-ravi** [comment]
I am using chrome. I checked the har using har viewer. Seems like its not broken. Please find the har below. 
[AllTickets-chrome-2019-04-03075521.har.gz](https://github.com/sitespeedio/sitespeed.io/files/3042232/AllTickets-chrome-2019-04-03075521.har.gz)

**Comment by kabilan-ravi** [comment]
@soulgalore Please confirm once you reviewed the HAR. If the issue is with perfcascade i will raise the issue there

**Comment by soulgalore** [comment]
Hi @kabilan-ravi yep got It thanks, there are couple of fields that are broken, I use http://www.softwareishard.com/har/viewer/ to verify, so let us keep this task for fixing that and then also if you can create issue in PerfCascade maybe we can catch the errors better there.

**Comment by kabilan-ravi** [comment]
@soulgalore Sure. i will add a bug in perfcascade. Any timeline for the fix?

**Comment by soulgalore** [comment]
Hi @kabilan-ravi can you share exactly how you run so I can reproduce? Tried hitting that URL in the HAR but didn't get the same error.

Best
Peter

**Comment by kabilan-ravi** [comment]
@soulgalore We have 6 urls configured in text file and 4 networks (native, 3g, 3gfast and cable). sitespeed runs infinitely in a loop. 3 iterations for each url. Prescript for login into our portal. Also we set the disk cache and media cache to 1 bytes and the firstparty set as --firstParty ".*(support|fassetsblue|fassetsgreen|fassets).freshdesk.com.*"

**Comment by kabilan-ravi** [comment]
@soulgalore Issue fixed.
