### ISSUE TITLE
Wrong request count when using Firefox browser

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2409]
Sitespeed.io 8.10.0 (Docker container)

The requests count on the Summary results page is inaccurate when a test is run in Firefox. The same test in Chrome logs the correct requests count.

Firefox (incorrect):
Run 1: 308
Run 2: 1
Run 3: 1

Firefox (actual):
Run 1: 39
Run 2: 41
Run 3: 39

Chrome (correct): 
Run 1: 49
Run 2: 47
Run 3: 43

**Comment by soulgalore** [comment]
Hi @leathej1 this thanks for the report and the mail of how you run. Can you share the HAR from the failing run too? I did a quick test on my machine and there it looked ok, so wanna see if I can understand better what happened on the failing run. The number of request should come from the HAR originally (and then it's counted in PageXray), so either something is wrong in the HAR or we count it wrong. If I have the HAR file I could reproduce and hopefully fix it!

Best
Peter

**Comment by soulgalore** [comment]
Ah @leathej1 forget what I said. I could reproduce! Turning on the video recording also gives me the same error. Let me check ...

Best
Peter

**Comment by soulgalore** [comment]
The problem is that we In PageXray thought that all requests in the HAR would be in a specific order, but they are not. I'll have a fix but need to test it some more, will do a fix release tonight.

**Comment by soulgalore** [comment]
Pushed 8.10.1 that should fix the problem.

**Comment by leathej1** [comment]
Cool - thanks!

**Comment by soulgalore** [comment]
I verified and it worked for me. Please re-open if you still get this error.

**Comment by leathej1** [comment]
Looks good - sorry for the delay.
