### ISSUE TITLE
Sitespeed - Issue with script , need help:- "commands.addText.byId"

### ISSUE THREAD

**Issue by jyoprakashJP** [sitespeedio/sitespeed.io#2414]
Hi, 
I am running following scripts and getting error for "commands.addText.byId", need help if I am doing anything wrong.

**This is the whole script:**

 module.exports = async function(context, commands)
   {
  await commands.measure.start('loginPage');
   await commands.navigate('https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page');
  await commands.measure.stop();
   try {
         await commands.addText.byId('xyz@xyz.com','wpName1');
         await commands.addText.byId('testpassword$$','wpPassword1');
         await commands.measure.start('login');
         await commands.click.byIdAndWait('wpLoginAttempt');
         await commands.measure.stop();
       }
       catch (e)
       {
       }
    };

**Error log:**
[2019-04-08 14:38:27] INFO: Running tests using Chrome - 1 iteration(s)
[2019-04-08 14:38:29] INFO: Start to measure loginPage
[2019-04-08 14:38:29] INFO: Navigating to url https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page iteration 1
**[2019-04-08 14:38:39] ERROR: Could not add text xyz@xyz.com to id wpName1**

**- Exact how you run -** sudo docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.9.0 test.js --multi --debug -n 1

**- Which version you are using -** Versions OS: linux 4.14.94+ nodejs: v10.13.0 sitespeed.io: 8.9.0 browsertime: 4.5.3 coach: 3.3.0

**- OS (if you use Docker, report the base OS)-**
sudo docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        774a1f4
 Built:             Fri Mar 29 06:40:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       774a1f4
  Built:            Fri Mar 29 06:39:27 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**- Browser version (if you don't run Docker)**
Google Chrome 73.0.3683.75 
Mozilla Firefox 66.0

-->

**Comment by soulgalore** [comment]
Hi @jyoprakashJP thanks for the report.

 If you add` --verbose` to your run you will see the error you get. If I run your script naming it test.js: `--multi -n 1 test.js ` it works for me.

Best
Peter

**Comment by jyoprakashJP** [comment]
Thanks,
Its working now. Seems I was using 8.9, with 8.10 I did not see any issue

**Comment by soulgalore** [comment]
There was no related change between those release though. I'll close but let us know if it happens again.

**Comment by Irshad021** [comment]
Hi @soulgalore 
I have a simple doubt I am using docker so where should I save the scripting files to execute when I run from the command line
