### ISSUE TITLE
How to View the result htmls when we have multiple execution

### ISSUE THREAD

**Issue by jyoprakashJP** [sitespeedio/sitespeed.io#2420]
How do you setup GCS to view multiple results.
Currently my test is storing them as with given Path- scriptname/timestamp.
How can I atleast have page when I can see the all the runs and link to individual index.html rather than manually find the timestamp values and constructing my complete URL.

http://www.sendmyresult.com/**testcopy_js/2019-04-12-15-24-55**/index.html
http://www.sendmyresult.com/**testcopy_js/2019-04-12-18-20-04**/index.html

even I can achieve directory listing, then it would be great.(Something like below screen for each execution)
![image](https://user-images.githubusercontent.com/49405846/56063556-9ecaf480-5d3d-11e9-9ca6-d7c3d09f3ff7.png)

FYI- if you run http://www.sendmyresult.com, it will give you complete bucket list for all the objects .

**Comment by soulgalore** [comment]
I use the annotations https://www.sitespeed.io/documentation/sitespeed.io/graphite/#annotations in Grafana for finding the right run.

I'm no GSC user but maybe someone has a solution?

**Comment by jyoprakashJP** [comment]
I was able to use annotation, only problem was that it works for single URL. In case of multi step test , it would appear when you select the last step(page). however I was able to open the result HTML.

**Comment by soulgalore** [comment]
Ah I see. Can you share an example where it don't work for you? We have a couple of multi steps running on dashboard.sitespeed.io and the annotations looks ok there?

**Comment by jyoprakashJP** [comment]
eg- I have 2 Steps in the script, 1-LoginPage, 2-Login.
Scenario1- I run both transaction, and when I apply annotation, I see that it works for 1st step. when I select the 2nd Step from page drop down, annotation goes away.

Scenario2- I comment out 2nd step, and run again. I see that annotation is working for 1st step.

**Comment by soulgalore** [comment]
Ok then I think there's a bug or some kind of scenario that I missed.

If everything works, the dropdown for the page, matches the tags in the annotation:
<img width="515" alt="Screen Shot 2019-04-17 at 20 06 47" src="https://user-images.githubusercontent.com/540757/56310530-6caa0000-614c-11e9-9400-646efca2080c.png">

Any change you can share your exact example so I can try to reproduce? You can email me: peter [at] soulgalore [dot] com. I can have a look early next week (I'm away the coming days).

Best
Peter

**Comment by soulgalore** [comment]
I don't think we got any feedback here so closing.
