### ISSUE TITLE
test localhost on linux

### ISSUE THREAD

**Issue by OlgaMiniukovich** [sitespeedio/sitespeed.io#2423]
Hello. I have issue testing app (which is deployed locally). My app is inside another docker container and it is accessible in browser (localhost:8080). I work on Linux (ubuntu). I know the solution for MAC (http://host.docker.internal) but it doesn't help me. 
I try sudo docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.12.0 http://host.docker.internal:8080. 
The error is { "browsertime": "UrlLoadError" }.
Would very appreciate your help.

**Comment by soulgalore** [comment]
Hi @OlgaMiniukovich it looks like `--network="host"` should work according to https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach - please let us know if it worked for you so I can update the documentation.

Best
Peter

**Comment by OlgaMiniukovich** [comment]
Hello @soulgalore 
The solution helped. The command that worked for me is  sudo docker run --rm --network=host -v "$(pwd)":/sitespeed. sitespeedio/sitespeed.io:8.12.0 http://localhost:8080/
Thanks a lot for your help!!!
