### ISSUE TITLE
Question about setup

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2430]
We got this question on our Slack channel:

I would like a recommendation from you. I have read the following documentation (https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#setup-important), It mentions to use sitespeed stand-alone (we understand as one container) . However, given our scenario, we don't know if the architecture, we decided matchs the recommendation.

Our scenario: We we like to test the main user journey (https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#i-want-to-test-a-user-journey-multiple-pages-how-do-i-do-that)  for different markets and different set of types of products in parallel as we would like to run these scenarios every 5 min. They maybe a large set of scenarios (labelled accordingly the mentioned characteristic ). We have a virtual server with docker compose running push gateway and sitespeed , for each config set (pre/pos script, browser, etc) we run a container, so at the end we have multiple sitespeed on the same server.

We want to know if it is possible to have better performance and stability using a stand-alone sitespeed and still configure por these multiple scenarios in parallel .
Is it the only possibility to use scripting (https://www.sitespeed.io/documentation/sitespeed.io/scripting/)?

Can we use one config file with multiple test cases, specify a url alias or multiple url alias for each test case?

We want to allow our devs to config sitespeed, so we thought the config file would be great or multiple config files as we use the PageCompleteCheck one for each page.
Option Multi allows to run in parallel? Can we share the same plugin with different argument for each URL or test case?

**Comment by soulgalore** [comment]
Getting stable metrics can be hard. We've been testing different cloud providers at work and with sitespeed.io  running different setups, and we have always got the most stable metrics with AWS. However one AWS instance (for example c5.large) cab differ from another instance of the same type. So if you run the same test on the same type of instance on two different instances, you can get different values and different stabilities. When we did this we wanted to have super stable metrics so I think this is a little edge case. I think the best way for you is to try it out, because it both depends on the server (how you set it up) and the pages that you test. If you test user scenarios (multiple pages after each other) there will be more variance, so the server may have less role to play. I would say just try try out :)
 
> run these scenarios every 5 min.

I think every 5 min is too often in most scenarios. Or how often do you deploy changes?  For example at work we have a train once a week and then we do multiple changes each day, but we almost never push multiple changes every hour, so we have different tests running, where we test once an hour or once every three hours. That pace still helps us find the regressions we want.

However if you really need every 5 minutes there are some configurations that you need to change. If you store the data in Graphite we have a default retention on 10 min (see https://www.sitespeed.io/documentation/sitespeed.io/graphite/#configure-graphite). That means if you do two runs within 10 minutes only one will be stored, so you need to change that configuration to be 5 min.

About containers: I usually have one setup that runs Graphite/Grafana etc using docker-compose and then multiple servers/instances running sitespeed.io using `docker run`.

Yes you are right: To run user scenarios, you need to use the [scripting](https://www.sitespeed.io/documentation/sitespeed.io/scripting/).

> Can we use one config file with multiple test cases, specify a url alias or multiple url alias for each test case?

I'm not 100% sure I fully understand. I use the config file (like the config.json) that contains the info about the setup like this: I setup a config file that have everything I need about the setup and then for different runs, I feed the config.json to sitespeed.io and then add extra parameters with the cli, all cli params will override what you have configured in the JSON config. For example: say that you mostly test with Chrome so in your config.json file you configured chrome, then for one test you wanna run Firefox, you can then just feed the same config to your run and add `-b firefox` and all configuration will be used from the config file and just override the browser.

If you mean config file the script file with the user scenario, yes they can have the same alias. The important thing is that you store the data in different name spaces. If you use Graphite, you do that with `--graphite.namespace`. Say that you test the same scenario from two different locations, then you just add `--graphite.namespace sitespeed_io.norway` and `--graphite.namespace sitespeed_io.irland` to your runs and the data will end up in two different name spaces.

> We want to allow our devs to config sitespeed, so we thought the config file would be great or multiple config files as we use the PageCompleteCheck one for each page.

Do you need different pageCompleteChecks for different pages/scenarios? I think there could be a way to find one that maybe use for most. For example if you use --spa it will wait for 5 s silence in the Resource Timing API (meaning no new responses will come in for 5 seconds). If one response comes, it will wait for 5 seconds more.

> Option Multi allows to run in parallel? 

No multi is what you need to add to run a script instead of testing a URL.

> Can we share the same plugin with different argument for each URL or test case?

Not sure I get that, can you please try to explain it some more :)

Best
Peter

**Comment by vivitc** [comment]
Thanks Peter, 
We will make more test with scripting feature.
As well, we would like to give you more context: We are trying to use sitespeed as frontend monitoring tool using lab data (https://developers.google.com/web/fundamentals/performance/speed-tools/), there are service, infra changes that affect the normal behaviour. We are trying to get some basic metrics: availability(we created using the pageCompleteCheck), latency(timing metrics), errors(sitespeed_console), similar to the 4 golden signal (https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/). That's why we try to get frequent escenarios, we might not need the other metrics as frequent as the mentioned three ones. 

Today, our setup, multiple sitespeed, one push gateway in one server and prometheus and granafa in their own servers. We created a plugin to map metrics from sitespeed to prometheus format using pushgateway. Today we spin up a new sitespeed container for each scenario, but it seems we are not fully using the container properly, as the scenarios we would like to run are about 120. We read that one container would run several scenarios or user journeys, in this post mentions 100+ (https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#memory--cpu). So we are trying to understand how setup sitespeed to run several scenarios in parallel but at the same time have different pageCompleteCheck for each user journey, using the same plugin (it seems we coud use the same config.json file for this).  How can we run scenarios in parallel?

"Can we share the same plugin with different argument for each URL or test case?"
When, i asked if we could send arguments to the plugin, was because we are trying to classify our scenarios( for example device, type of customer, etc )that later will be mapped as custom label for prometheus.

**Comment by soulgalore** [comment]
> We read that one container would run several scenarios or user journeys, in this post mentions 100+ 

Ah I see. What I meant there where not running different scenarios, more that if you test many pages after each other (either with a long URL list or crawling) you will hit the default NodeJS default memory limit. So you need to increase it, else you will run out or memory, 

> How can we run scenarios in parallel?

Either multiple containers on the same (big) server with correct config (you need to setup xvfb to use different ports if you run on the same machine) or have smaller instances with one container each (I use the latter). 

You need to start each scenario after each other. If you only test URLs you can feed sitespeed.io with a config/text file with multiple URL. If you wanna run different scenarios you need to start the sitespeed.io per scenario. I haven't run a super complicated setup so I usually just have a bash script with X different runs. But maybe you need something more sophisticated.

> Can we share the same plugin 

Do you mean your own implemented plugin? 


> availability(we created using the pageCompleteCheck),

I wonder if there could be a way we could support it out of the box, any idea? In master (not yet released) we push errors from Browsertime to Graphite/InfluxDB meaning for example if the web site is unreachable, you will get the error sent to your data source. That would probably fix it for you right? I also pushed a new thing in Browsertime that will come in the next release so that you can define your own errors in your scripts. Like for example you can check if something is missing on a page and then `command.error(text)` in your script, and that error will end up in your datasource or rather the amount of errors.

**Comment by naomijub** [comment]
@shakey2k2 I believe we could run frequently browsertime with less metrics. So instead of running all sitespeed metrics, we could run just a couple metrics we consider best. Is that possible? Also, could we integrate with a separated selenium machine for performance gain?

**Comment by soulgalore** [comment]
Yep you could use Browsertime. We do it at work and then cherry pick some metrics from the result json file (using the official Docker container).

You mean using a Selenium grid or? To be able to get Visual Metrics you need to run on the local machine.

**Comment by soulgalore** [comment]
Think the question was answered :)
