### ISSUE TITLE
storageManager.writeData in custom plugin does nothing? 

### ISSUE THREAD

**Issue by bkarlson** [sitespeedio/sitespeed.io#2431]
Hello,
I'm trying to make https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js work, and while everything looks fine (i.e. plugin loads, starts, collects data etc -- I checked everything via logging), the final step `storageManager.writeData` does nothing: no files are written and no errors are returned. I played with permissions, tried to point it to another dir:

```js
this.storageManager.createDirectory('dATA').then(dir =>
      this.storageManager.write(dir, 'performance.json', 'perform.json', 'perf.json')
    );
```

nothing is happening (it creates `dATA`, but it still ends up empty).

I'm really puzzled here, this plugin is supposed to work out of the box, but i've been debugging for 2 hours now and nope.

Running on Amazon Linux,
nodejs: v10.15.3 sitespeed.io: 8.13.0 browsertime: 4.6.4 coach: 3.3.0

Thanks for your time!

**Comment by bkarlson** [comment]
I ended up using default `fs.writeFileSync`. No idea why async write does no work in such case. 

To whoever stumbles here via google:

```js
    fs.writeFileSync('performance.json', JSON.stringify(this.results), function(err, result) {
     if(err) console.log('error', err);
   });
```

**Comment by soulgalore** [comment]
Hi @bkarlson just want to check that you returned the promise or awaited it when you tried storageManager.writeData? Any chance you could share your example? 

Best
Peter

**Comment by bkarlson** [comment]
Yes, the `close()` function returns promise in the original script:

```js
  close(options, errors) {
    return this.storageManager.writeData(JSON.stringify(this.results), 'performance.json');
  }
```

I realise it's got smth to do with async-nature of `writeData`, but i'm not strong enough in JS to make it work in original https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js. What puzzles me that it does not work out of the box, yet the plugin is supplied and extensively documented on GItLab website. I'd assume they tested it and it had worked, yet something has changed in sitespeed / storageManager arch maybe?

**Comment by soulgalore** [comment]
There was a bug in 8.x that didn't make sure we waited on all promises from close methods until it moved on. It's fixed in https://github.com/sitespeedio/sitespeed.io/commit/6b954528e3c36ce825e97672ef2ab83e4ccd52d9 and I plan to release it later today.

**Comment by soulgalore** [comment]
This was released a couple of months ago, please let me know if it is still a problem and we can re-open.
