### ISSUE TITLE
command.addText.byXpath not working for me

### ISSUE THREAD

**Issue by jyoprakashJP** [sitespeedio/sitespeed.io#2435]
Am I doing any thing wrong?
Script runs good until 2nd Try block and when I try to key word search using Xpath, it fails, I dont see any error thrown, but I see that catch block is executed.
**await command.addText.byXpath('gloves','//*[@id="searchBarForm"]/div/div/input');**

1. Please note that I don't have id in search field so have to use xpath or css selector to add text.
2. Addtext.byId worked for login credential.

**Complete Script:**
module.exports = async function(context, commands)
   {
   try {
        await commands.measure.start('01_LoginPage');
        await commands.navigate('https://xyz.com');
        await commands.measure.stop();
       }
   catch (e)
       {
        return commands.measure.stop();
        throw e;
       }
   try {
         await commands.addText.byId('testname','USER');
         await commands.addText.byId('testpwd','PASSWORD');
         await commands.measure.start('02_LoginPage');
         await commands.click.byClassNameAndWait('btn btn-primary submit-btn');
         await commands.wait.byId('change-account-link',20000);
         await commands.measure.stop();
       }
   catch (e)
       {
       return commands.measure.stop();
       throw e;
       }
   try {
         **await command.addText.byXpath('gloves','//*[@id="searchBarForm"]/div/div/input');**
         **await commands.measure.start('03_search');**
         await commands.click.byClassNameAndWait('search-button');
         await commands.wait.byId('pageResults',20000);
         await commands.measure.stop();
       }
   catch (e)
       {
       return commands.measure.stop();
       throw e;
       }
   };

**Comment by jyoprakashJP** [comment]
I tried wiki login script with xpath, did not work for me, and no error thrown as well.

 module.exports = async function(context, commands)
   {
  await commands.measure.start('loginPage');
  await commands.navigate('https://en.wikipedia.org/w/index.php?title=Special:UserLogin');
  await commands.measure.stop();
   try {
  //       await commands.addText.byId('myusername','wpName1');
  //       await commands.addText.byId('mypassword','wpPassword1');
          **await command.addText.byXpath('myusername','//*[@id="wpName1"]');
         await command.addText.byXpath('mypassword','//*[@id="wpPassword1"]');**
        await commands.measure.start('login');
         await commands.click.byIdAndWait('wpLoginAttempt');
         await commands.wait.byId('1pt-userpage',2000);
         await commands.measure.stop();
       }
       catch (e)
       {
       }

   };

**Comment by soulgalore** [comment]
Hi @jyoprakashJP are you sure your xpath expression is correct? When I add scripts I usually do it without Docker just so I can see the browser window and visually verify what happens. If you upgrade to 8.14.0 the error you get will have a better error message (before we just wrapped the Chromedriver error and that rarely said something interesting), hopefully that can help you.

Best
Peter

**Comment by jyoprakashJP** [comment]
I believe so, I tried the wiki login example, and just replaced addtext with xpath version. I will try to run local with 8.14.

module.exports = async function(context, commands)
{
await commands.measure.start('loginPage');
await commands.navigate('https://en.wikipedia.org/w/index.php?title=Special:UserLogin');
await commands.measure.stop();
try {
// await commands.addText.byId('myusername','wpName1');
// await commands.addText.byId('mypassword','wpPassword1');
await command.addText.byXpath('myusername','//[@id="wpName1"]');
await command.addText.byXpath('mypassword','//[@id="wpPassword1"]');
await commands.measure.start('login');
await commands.click.byIdAndWait('wpLoginAttempt');
await commands.wait.byId('pt-userpage',2000);
await commands.measure.stop();
}
catch (e)
{
}

};

**Comment by jyoprakashJP** [comment]
Xpath is not working for me even with latest 8.14, I don't see any error message thrown but I do see that catch block is executed.


await command.addText.byXpath('myusername','//[@id="wpName1"]');
await command.addText.byXpath('mypassword','//[@id="wpPassword1"]');

**Comment by soulgalore** [comment]
But do you log the error so you can see what happens?

```
catch (e) { 
  console.log(e);
}
```

**Comment by jyoprakashJP** [comment]
Seems some syntax error. Its working now. Other issue while running with 8.14 is that I am getting "Could not Parse trace log from Chrome Error: No ThreadId found for ThreadID ...."

**Comment by soulgalore** [comment]
Ok! 

> "Could not Parse trace log from Chrome Error: No ThreadId found for ThreadID ....

That is Chrome issue, the implementations have changed over time. This started to happen on some URLs two versions ago but I haven't been able to nail it. If you can share the URL so I can reproduce that would be great, or if you could the chrome trace log (is it produced?) from the failing run, that would also help!

Best
Peter

**Comment by soulgalore** [comment]
In 9.0 we changed tools to get the trace log and hopefully this works better for you know. If not, please let us know.
