### ISSUE TITLE
Unable to find identical content

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2437]
Does sitespeed support identifying duplicate content served from different urls on the same page - e.g. on gtmetrix

![image](https://user-images.githubusercontent.com/7537289/56743219-cbb6d880-673b-11e9-9be4-291b9ea40a2d.png)

**Comment by soulgalore** [comment]
No it does not. Its a use case I haven't thought of. 

The coach checks for multiple JQuerys but nothing more than that.

**Comment by soulgalore** [comment]
Closing because I don't see this is gonna be implemented.
