### ISSUE TITLE
Fetch URL/scrips from ... a URL :)

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2439]
One thing that we are missing today is a way to feed sitespeed.io with an endpoint where it can fetch which URLs/scripts to run. We have a user that wanted to build that on the side but I think we could do it with some small changes.

It would work something like this: You add a parameter with a URL where we will find the job/URLS/scripts is needed. 

I think we could just squeeze it in the current solution without much overhead, but we need to specify how it would work.

**Comment by daviddarke** [comment]
Hi @soulgalore . Thanks for looking into this. After a quick bit of thinking, two ways of handling this came to mind.

## Option 1
Sitespeed.io define the required format of how a custom API should present a list of urls to test.

So running something like:

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.15.0 https://randomsite.com/queue --api`

… you would expect `https://randomsite.com/queue`  to return something like:

```
{
	"urls": [{
		"alias": "url"
	}]
}
```

An actual example would look like:

```
{
	"urls": [{
		"Google": "https://google.com",
		"Bing": "https://bing.com",
	}]
}
```

So something very similar to the multiline file format, the format is very fixed and defined. These urls could even be processed in the way method the current multi url options use.

One other thing to consider about this approach is that basic auth options (of some variety) will need to be added at the same time.

## Options 2
Update the url detection options found [sitespeed.io/cli.js at master · sitespeedio/sitespeed.io · GitHub](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli/cli.js#L49) to skip file detection if a command like this is run:

```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.15.0 --urlScript /sitespeed.io/script.js
```

This would then use the same concept as the pre script inclusion. The content of `/sitespeed.io/script.js` could then be something super basic like:

```
module.exports = async function(context, commands) {

    // GO TO API, AUTHENTICATE, GRAB FEED IN WHATEVER FORMAT

    // Some sort of loop to parse custom feed of urls and start processing urls
    for (j = 0; j < jsonContent.length; j++) {
        await commands.measure.start( jsonContent[i].url );
    }
}
```

I think with this options it allows far more customisation on the part of the end user AND lets them worry about authentication methods with their system.

@soulgalore let me know your thoughts.

**Comment by soulgalore** [comment]
Hi @daviddarke thanks for taking the time to think about! If it's possible I wanna use the same structure/functionality as we have already today, just to minimising different ways of input and making it easier to test.

I'm not sure yet but I'm thinking something like this. We could change so that `--config` also reads a config file from a URL.

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.15.0 --config https://www.sitespeed.io/config.json`

Then we also need to do a couple of change in the cli handling, so if you supply a config, you don't need to add a URL/path when you start sitespeed.io. The config json file can hold the URLs in an array. Best case it can also have scripts.  

The config.json works like this today: If you supply a config,json file, all parameters that you supply through command line will override the config file.

I need to think about for a couple of more days though. What's you thoughts?

Best
Peter

**Comment by daviddarke** [comment]
Hi there again, yes that does sound great. Everything is on the part of the "external API" to then produce the config AND the required URLs for testing. That could be really powerful because you can also manipulate the rest of the config options at the same time via the external API.

Also from an auth point of view, the scheduler that spins up the sitespeed container can pass an API key at the same time.

```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.15.0 --config https://www.sitespeed.io/config.json?key=xxxxxxxxxxxxxxxxxx
```

... to then secure the rendering of the `config.json` (essentially what should be next in the queue).

Sounds perfect!

**Comment by soulgalore** [comment]
Great! To do it we need to upgrade yargs that we use for the CLI handling, we missed out doing for years and we should make sure we use the latest and then extend it to get the config. The last time I tried it was breaking change that broke how we instantiate plugins ... it was something like the reset() function was deprecated ... or it is deprecated now but I think also included some change, because it broke it for us (but could not see anything in the changelog at that time).

**Comment by daviddarke** [comment]
Interesting, let me know if you need anything from me.

**Comment by soulgalore** [comment]
@daviddarke if you are a NodeJs user, feel free to try to upgrade yargs to the latest version and checkout what happens and see if you can make it run.  I can do that but busy until the 9th of May, after that I can do the fixes needed, but if you have time to try to fix that upgrade that would help a lot :)

**Comment by daviddarke** [comment]
Great, I'll try and have a go in the next couple of days.

**Comment by soulgalore** [comment]
Cool, no pressure though :) If I remember correctly we run 6.x version of yargs and we use the reset method get the explicit parameters in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli/cli.js#L1119 but that somehow changed. 

Later on in the code, we use those params to know which plugins to start. For example, say that you want to use Graphite and you add --graphite.host ... then we know that we should include the Graphite plugin in the start-up. But later version of yargs we get all parameters (not only the ones that you gave to the cli) and makes the code start EVERY plugin.

**Comment by daviddarke** [comment]
@soulgalore Yeah, with Yargs `13.2.2` I'm getting this on initial run:

```
YError: Invalid first argument. Expected boolean or string but received function.
```

Full output:

```
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/Users/daviddarke/Sites/sitespeed.io/node_modules/yargs/lib/argsert.js:67:9)
    at parsed.optional.forEach (/Users/daviddarke/Sites/sitespeed.io/node_modules/yargs/lib/argsert.js:49:39)
    at Array.forEach (<anonymous>)
    at argsert (/Users/daviddarke/Sites/sitespeed.io/node_modules/yargs/lib/argsert.js:44:21)
    at Object.version (/Users/daviddarke/Sites/sitespeed.io/node_modules/yargs/yargs.js:790:5)
    at Object.parseCommandLine (/Users/daviddarke/Sites/sitespeed.io/lib/cli/cli.js:74:6)
    at Object.<anonymous> (/Users/daviddarke/Sites/sitespeed.io/bin/sitespeed.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Line 74 of `lib/cli/cli.js` does seem to be causing issues. https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli/cli.js#L74

I switched this to `.version( packageInfo.version )` but it all starts unravelling there lol.

This is at the limit of my experience with node, so I may have to leave it in your capable hands but only when you have the time. Thanks again :)

**Comment by soulgalore** [comment]
Np @daviddarke ... if I don't find the time to do the update, I can just add the functionality for getting the config file, I think the current version will support it. I'll get back on Friday when I have had some time to try it out.

**Comment by soulgalore** [comment]
Added #2445 for the upgrade, but wanna wait on the Firefox extensions issues.

**Comment by soulgalore** [comment]
@daviddarke one question: who needs to add new tests in your case, is it developers (that can use git) or is it users? Is it one off runs or do you wanna continuously measure each URL? For the use case where the user can use git and you continuously wanna measure a URL I have better solution :)

**Comment by daviddarke** [comment]
Hi @soulgalore it will be users.

> who needs to add new tests in your case, is it developers (that can use git) or is it users?

Users, I'm building the interface for it now

> Is it one off runs or do you wanna continuously measure each URL? 

continuously, nightly runs. 

Many thanks.

**Comment by soulgalore** [comment]
Ok! I'll implement a simple way to add URLs using Git, hopefully I can start this weekend and use dashboard.sitespeed.io as an example. Thinking maybe tweaking your code could use that solution too.

It will work something like this: You need to create a git repo (I'm gonna use Github so everything is open), that repo will have a structure like this:

```
/servername/desktop/urls.txt
/servername/desktop/script1.js
/servername/desktop/script2.js
/servername/mobile/script1.js
```

Then on the server that runs the tests, you need to install Git and Docker and add a bash script. The script will run in a infinite loop, each iteration getting a updated version if the git repo. In the urls.txt file you can just add a new URL at the end of the file and it will be picked up the next iteration. 

Then all files in the server folder matching your server will be run. 

Whats needed on the server is a default config.json (or rather multiple) that holds the variables that you wanna keep secret (key/grafana passwords etc).

In your case you need to implement that when a user adds a script/URL, you write that to the repo. Would that work fo you? What I like a bout this approach is that we can do a version that is easy to demo and replicate for users and we are using Git to keep track and have the history of what we are running.

**Comment by daviddarke** [comment]
Hi there @soulgalore yeah that all makes sense. It's kind of away from what I was originally talking about because there will never be a test server, it will all be running in k8s and you get into the docker in docker problem.

I could do this now already (with no changes and not on K8) with a bash script that talks to the queue API and then literally runs the docker command and passes the url at that point.

I was more looking for the queue accessing to happen inside the container on boot.

Make sense? Obviously, don't worry if it's not possible.

**Comment by soulgalore** [comment]
I see, let me add the functionality to read the config json from HTTP the weekend (that will solve the problem for you right?).

**Comment by daviddarke** [comment]
Sounds amazing, thank you.

**Comment by soulgalore** [comment]
When we released 9.0 we updated yargs but I haven't implemented the fix to get the config. Before I do I just wanted verify (again) that you need it @daviddarke  :)

**Comment by daviddarke** [comment]
Hi there @soulgalore I will 100% use this feature, but please don't think you have to do this on just my behalf.

If you feel it's outside of the feature set you currently want to supply, or the docker inside docker aspect is an edge case then I'll find another workaround some other way, no problem 👍

**Comment by soulgalore** [comment]
I was thinking there is a workaround :) Sorry I'm lazy, I think maybe there are some functionality that we can use already, but I'm 100% since I'm no Kubernetes user.

There's way today to add your own bash script that runs before sitespeed.io starts:
https://www.sitespeed.io/documentation/sitespeed.io/docker/#extra-start-script

Is that possible to use Kubernetes? That could be a one liner using curl/wget that get the config file and stores it at the right place inside the container? From my side I need changed so we keep curl in the container (we use it to install but removes it).

**Comment by daviddarke** [comment]
I did look at that, but there were issues about where the script actually existed before booting the sitespeed instance. No worries, it's sounding like you are going to need quite a few changes from your side so don't worry, I'll find a workaround from this side 👍 thanks for your time!

**Comment by soulgalore** [comment]
Yeah there where no easy way to fix this and not sure how much value it would add so closing.
