### ISSUE TITLE
Accent on Dashboard documentation [proposal]

### ISSUE THREAD

**Issue by ceckoslab** [sitespeedio/sitespeed.io#2443]
I decided to try sitespeed.io about 2 days ago. I wanted to run some smoke tests and as a new comer I wanted to have dashboard like: https://dashboard.sitespeed.io/

And to make my suggestion valid: Is there a Google Analytics data how often visitors go to Dashboard documentation page?

I come with the mindset as somebody who wants to give a try of sitespeed.io and avoid digging too early in to the details all the amazing setting and metics sitespeed.io has.

Best option for me could be to find very easy the dashboard setup documentation but I needed about half an hour to find it.

Best option for me could be to have link to Dashboard documentation in main documentation dropdown or above the fold of this page: https://www.sitespeed.io/documentation/sitespeed.io/

This is what I mean with:

**Link in main dropdown**
<img width="1140" alt="Screenshot 2019-05-04 at 13 40 56" src="https://user-images.githubusercontent.com/1024001/57178616-96189a80-6e73-11e9-9d82-a1c4b5863c4d.png">

**Above the fold of: https://www.sitespeed.io/documentation/sitespeed.io/**
<img width="1157" alt="Screenshot 2019-05-04 at 13 46 15" src="https://user-images.githubusercontent.com/1024001/57178620-b0527880-6e73-11e9-99d9-b8fc38b5f8f8.png">

**Comment by soulgalore** [comment]
Hi @ceckoslab yeah I agree we should make it easier to find. Easiest to move it up to the "Start" but I think it should be more advanced. Let me think how we can best do it.

>  Is there a Google Analytics data how often visitors go to Dashboard documentation page?

No we don't use GA since we believe in [privacy for our users](https://www.sitespeed.io/privacy-policy/).

Best
Peter

**Comment by soulgalore** [comment]
I've moved the links to the start section and added a new section on the first page, thanks for your input!
