### ISSUE TITLE
Grafana IP for Mac - proposal [documentation]

### ISSUE THREAD

**Issue by ceckoslab** [sitespeedio/sitespeed.io#2444]
looks like minor but and person that does not has experience with Docker on Mac may run it to this problem but I would like to mention it.

I tested the Dashboard on my Mac machine and followed the documentation from this page: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/

At point 4 it says: "Access the dashboard: http://127.0.0.1:3000" but we for Mac we need to use Docker Machine ip, which usually is 192.168.99.100. It may vary and the command `docker-machine ip` provides the real Docker Machine ip.

<img width="1103" alt="Screenshot 2019-05-04 at 13 57 11" src="https://user-images.githubusercontent.com/1024001/57178790-31ab0a80-6e76-11e9-9830-2e18dbd20f04.png">

Do you think that it makes sense to add small notice that for Mac the ip should be different?

**Comment by soulgalore** [comment]
Hi @ceckoslab ah ok, hmm it works for me on my Mac. What version are you using?

```
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01
```

Best
Peter

**Comment by ceckoslab** [comment]
Hi @soulgalore 

That is interesting:

```
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
```

Obviously I am behind you ... do you use Docker Machine on Mac?

Looks like minor problem but I will try to find you what could be different in my setup and I will upgrade docker and docker compose.

**Comment by ceckoslab** [comment]
Hello @soulgalore 

I did a research and I believe that you are using Docker for Mac but not Docker Machine because I've never seen Docker Machine to run on 127.0.0.1

I never used Docker for Mac but I refer to this link that provides me with some cues: https://stackoverflow.com/a/50356519

**Comment by soulgalore** [comment]
Aha thanks @ceckoslab I'll update the docs then!

Best
Peter

**Comment by soulgalore** [comment]
Updated the docs, thanks @ceckoslab !
