### ISSUE TITLE
Find the conditional formatting for index.html numbers

### ISSUE THREAD

**Issue by xanderstephens125** [sitespeedio/sitespeed.io#2447]
I am looking for the conditional formatting for the summaryBox colors on the index.html page. 

I have looked through: https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/helpers/scoreLabel.js

I was not able to find it here. Is there any straight forward conditionals, or are they all derived from elsewhere?

Thank you!

**Comment by soulgalore** [comment]
Hi @xanderstephens125 when it is a score (not a metric), the score is calculated in the coach, and then the file you showed is the one that sets the limits. They are straight forward (hard coded :)).

Best
Peter

**Comment by soulgalore** [comment]
Closing but let me know if you need more help.
