### ISSUE TITLE
BrowserTime pageCompleteCheck

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2448]
Hi Guys,

Just a quick query, i could not find the answer.

What is the interval on the pageCompleteCheck and is there a delay in loading this?
The question stems from the fact that i have some JS which is looking for an element being removed to stop the test, however the test is only stopping some time (4 seconds or so) after said element is removed (i'm also using the flag --browsertime.pageCompleteWaitTime 1000).

Thanks,
Scabs

**Comment by soulgalore** [comment]
Hi @scabenga I don't have it in my head, we use the driver.wait method in Selenium and need to check the source code there (https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebDriver.html) to see how often it runs. Any chance you can check?

Best
Peter

**Comment by soulgalore** [comment]
Closing but please let me know if you need to know exact how it works!
