### ISSUE TITLE
EGL driver error ;if no GPU;can sitespeed run?

### ISSUE THREAD

**Issue by fakerName** [sitespeedio/sitespeed.io#2451]
![309FA592-8C2F-469e-917C-95144396BC4D](https://user-images.githubusercontent.com/17928352/57610870-31142180-75a4-11e9-91e8-a35ed764bc76.png)
Chrome in  74.0;In windows;

**Comment by soulgalore** [comment]
Hi @fakerName officially we don't support Windows through NodeJS, you need to use Docker.

Best
Peter

**Comment by fakerName** [comment]
> Hi @fakerName officially we don't support Windows through NodeJS, you need to use Docker.
> 
> Best
> Peter

OK,thank you

**Comment by fakerName** [comment]
I turn to use Docker, but there is the same error. any reason on gpu?

**Comment by fakerName** [comment]
![image](https://user-images.githubusercontent.com/17928352/57757202-862c7080-7727-11e9-9907-82a608981685.png)

**Comment by soulgalore** [comment]
Seems like people had that error with Chrome/Chromedriver. Any chance you could try something else than Windows 7?

**Comment by fakerName** [comment]
> Seems like people had that error with Chrome/Chromedriver. Any chance you could try something else than Windows 7?

I made it on mac already.win7 chrome may have some error.
