### ISSUE TITLE
How to hide/delete domain's data

### ISSUE THREAD

**Issue by jomyjo** [sitespeedio/sitespeed.io#2458]
Hi, quick question. Is there a way to hide or delete domains that were added? 

For example, I've added http://abc.com, http://xyz.com and http://foobar.com. Now on the dashboard, I only want to show dropdown for domain abc.com and xyz.com hence, only the data of both the mentioned domains should be available.

Another case would be deleting domains that I permanently don't need already.

Are there ways (maybe I'm not aware of) to accomplish this?

**Comment by soulgalore** [comment]
HI @jomyjo there's two ways of doing it:
* You remove the raw data. If you are using Graphite, the data is file based so each domain will be a folder on disk. Depending on you setup (you can mount volumes) you need to find it and then you can just go through it (folder/files follow  the same structure as the key in Graphite. When you find the right place you can just `rm -fR xyz_com`.
* Or you can change the query variable in Grafana that gets the domain and add a regex that removes the domains that you don't want.

<img width="1271" alt="Screen Shot 2019-05-14 at 12 27 05" src="https://user-images.githubusercontent.com/540757/57691173-bf8bb000-7643-11e9-8950-144c4a062784.png">

Hope that helps!
Best
Peter

**Comment by jomyjo** [comment]
Thanks for the quick reply @soulgalore !

Can option 2 be achieved by using the pre made dashboard from sitespeed.io or do I have to create an account in Grafana for that - I was thinking how will I able to access the page as the screenshot above? 

Seems like both options are for **delete** - How about if I just want to hide some domains from showing in the dashboard but I still want it to remain available so I could get the data next time?

**Comment by soulgalore** [comment]
Hi @jomyjo the second option is hiding, not deleting. How do you run Grafana? If you host your own instance (using our docker-compose file) or your own setup, you can just login to Grafana and change the template. If you use a hosted Grafana version you can change that there too. The default dashboard that we shipped are made to be an example that you can change whatever way you need. If you are new to Grafana, you need a little time to try it out and learn, but it is worth it.

> How about if I just want to hide some domains from showing in the dashboard but I still want it to remain available so I could get the data next time?

It depends. At work where we use Grafana and I just want to show some parts of the data, I click on that metric/domain or whatever the graph shows. You can also show multiple ones, check out the screenshot:
<img width="862" alt="Screen Shot 2019-05-15 at 20 30 24" src="https://user-images.githubusercontent.com/540757/57799887-5fcefb00-7750-11e9-85cd-98b4f965c046.png">

Does that help?
Best
Peter

**Comment by soulgalore** [comment]
Let me know if you need more help!
