### ISSUE TITLE
About Duplicate items in 1 category of coach

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2461]
How do we differentiate which resources are violating which recommendation from coach... check below screenshot

EG... below recommendation has everything in one row... and shows multiple resources multiple times...

There are 32 response(s) that sets a p3p header. There are 66 response(s) that sets both a max-age and expires header. There are 20 response(s) that sets a pragma no-cache header (that is a request header). There are 72 response(s) that sets a server header.

![image](https://user-images.githubusercontent.com/7537289/57932021-77f16800-787f-11e9-88ce-0991b456991b.png)

**Comment by soulgalore** [comment]
Hi @softwareklinic at the moment you need to check the HAR for each individual request.

Best
Peter

**Comment by softwareklinic** [comment]
Ty


Regards
Keyur

On May 18, 2019, at 12:24 PM, Peter Hedenskog <notifications@github.com>
wrote:

Hi @softwareklinic
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_softwareklinic&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=E2vJwm5VZm8Zb1tmfL3FQekMyMkXWEPPVzmW1ETzxS4&s=Vl9Fwj7IFdI1j0JJWKmEpBv6kZcHrXxjW9JON6vCPtY&e=>
at the moment you need to check the HAR for each individual request.

Best
Peter

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2461-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABZQFCO2SLZDEG5VFGVTJKDPWA3TZA5CNFSM4HNVMIA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWSRZY-23issuecomment-2D493693159&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=E2vJwm5VZm8Zb1tmfL3FQekMyMkXWEPPVzmW1ETzxS4&s=EG_4ZErbQ8AsF0Hs6iS1RTWIuqoOU42xE_3k5AG5B6U&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABZQFCKUNAVU7FWZN4CTC7TPWA3TZANCNFSM4HNVMIAQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=E2vJwm5VZm8Zb1tmfL3FQekMyMkXWEPPVzmW1ETzxS4&s=pEbN7eLA6R4k_m4Tf82tXu55tAbAmrulK_yzcVyBvKo&e=>
.
