### ISSUE TITLE
ERROR: UrlLoadError: Failed to load/verify

### ISSUE THREAD

**Issue by Uporaba1** [sitespeedio/sitespeed.io#2466]
Hi,I run the container with command:
`docker run --name speedtest --rm -v /home/speedtest/urls.txt:/sitespeed.io/urls.txt sitespeedio/sitespeed.io:8.15.2 urls.txt --graphite.host=host.of.graphite -n 1 --speedIndex false --video false -c 3g --graphite.namespace sitespeed_io.xxx`
And when i look in the logs i see it:
`[2019-05-21 12:48:21] INFO: Running tests using Chrome - 1 iteration(s)
[2019-05-21 12:48:22] INFO: Testing url https://aliexpress.com iteration 1
[2019-05-21 12:48:28] ERROR: UrlLoadError: Failed to load/verify https://aliexpress.com uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:232:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-21 12:48:28] INFO: https://aliexpress.com 0 requests, 0 bytes
[2019-05-21 12:48:28] INFO: Running tests using Chrome - 1 iteration(s)
`
And it doesn't display metrics in grafana. How i can fix it?

**Comment by soulgalore** [comment]
Hi @Uporaba1 when I tried the URL it seems lika a lot of redirects is going on, I wonder if thats the problem? Can you test the final URL and see if it works for you?

Best
Peter

**Comment by Uporaba1** [comment]
@soulgalore This problem is not due to redirection. On some sites that are not in my company's network, the exact same problem occurs.

**Comment by Uporaba1** [comment]
@soulgalore I cited this site only as an example.

**Comment by Uporaba1** [comment]
@soulgalore I also noticed that metrics are coming, but randomly. I have a server on my server, a cron task that runs the container every hour. But metrics for some reason come randomly. 
![image](https://user-images.githubusercontent.com/32709525/58251753-d8037500-7d7d-11e9-9fef-4065f7a2a004.png)
![image](https://user-images.githubusercontent.com/32709525/58251772-e5206400-7d7d-11e9-8e33-468ec1627ff5.png)
![image](https://user-images.githubusercontent.com/32709525/58251785-eea9cc00-7d7d-11e9-9b6b-36a73ea0853a.png)

**Comment by Uporaba1** [comment]
@soulgalore What information do you need to help solve my problem?

**Comment by soulgalore** [comment]
Hi @Uporaba1 here's the docs on how you can help us: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/

For your sites not working, do you run inside of your network at work or a machine somewhere outside?

>  I also noticed that metrics are coming, but randomly
Is it your Graphite or? By default Graphite have a low limit of new metrics that can be created per minute, could it be that? Or do you mean random as it doesn't match your cron?

Best
Peter

**Comment by Uporaba1** [comment]
@soulgalore at work

**Comment by soulgalore** [comment]
And still looks the same? For missing metrics they appear when you been running for a while. For the failing runs I think there's something in your network at work that makes fail, please try on a cloud provider or a server outside of your work.

**Comment by soulgalore** [comment]
Didn't got more info about it, so closing.
