### ISSUE TITLE
Instructions on how to fail a deployment in CI if performance budget fails(preferably after retrying)

### ISSUE THREAD

**Issue by jbrawley** [sitespeedio/sitespeed.io#2467]
This is less of a bug, and more of a question on how to use the tool.  I asked on Twitter, and it was suggested to open up an issue to discuss there.

"Are there any instructions for how to fail a deployment in CI if a performance budget fails, or any best practice around this?  Maybe a way to repeat the test if it fails x times, before failing the deployment?"

Our config is a work in progress, we have not added performance budget's yet and we are testing against a staging environment closed off.  We have someone currently working on a script, because this is a B2B e-commerce website(Magento 2 platform) we are testing, requiring to login, add products to cart, checkout, etc.

**Comment by jbrawley** [comment]
{
  "browsertime": {
    "iterations": 5,
    "browser": "chrome",
    "headless": true,
    "outputFolder": "output",
    "cacheClearRaw": true
  },
  "chrome": {
    "timeline": true,
    "args": "no-sandbox"
  },
  "graphite": {
    "host": "redacted",
    "port": "redacted",
    "includeQueryParams": true
  },
  "metrics": {
    "filter": [
      "coach.pageSummary.advice.performance.adviceList.*.score",
      "coach.pageSummary.advice.bestpractice.adviceList.*.score",
      "coach.pageSummary.advice.accessibility.adviceList.*.score"
    ]
  }
}

**Comment by soulgalore** [comment]
Hi @jbrawley thanks for creating the issue. We try to answer as much as possible in issues (or the docs) so it searchable. The docs is missing this part so let me answer it here first and then update the docs.

If you run using a budget file, the exit code will be an error if the budget fails. So run sitespeed.io and then check `$?` . If it's a 0 the budget was ok, if it's a 1 it failed. 

There's no implementation of retrying. Instead increase the number of runs. For example run 5 runs per URL. All timing metrics use the median value. So the more number of runs, the more stable metric (hopefully).

For me it has been quite hard to get stable timing metrics in CI (that you can alert on). You need to make sure the server is stable etc. Usually it also differs a lot depending on production where you have real content. We use Grafana alerts at work that works fine for us, to test against production data.

Best
Peter

**Comment by soulgalore** [comment]
Closing but please let me know if you need more help!
