### ISSUE TITLE
Bad HTML on Waterfall page

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2473]
Docker image - 9.0.0

Looks something like this:

Waterfall
Run 1 

\n \n \n\n\n\n\n\n\n \n \n \n \n\n\n
\n\n
\n\n
\n
\n \n  \"\"\n \n

\n 
\n\n
\n \n \n \n \n \n \n \n \n
\n\n
\n

You can contact me for the full repro script and report.

**Comment by leathej1** [comment]
<img width="1280" alt="Screen Shot 2019-05-24 at 9 48 58 AM" src="https://user-images.githubusercontent.com/24658347/58344146-c798dc00-7e09-11e9-9d25-7533cacd598a.png">

**Comment by soulgalore** [comment]
Hi @leathej1 wow :) And you don't get any errors in the log? If you could share the HAR file that would be great!

Best
Peter

**Comment by soulgalore** [comment]
There's a couple of bugs here, hopefully I can include a fix for the release coming on Thursday!

**Comment by soulgalore** [comment]
The fix was released in 9.1 earlier today, I could verify the issue and see that it works for me, but please let me know if it still fails for you. The issue was originally for pages that has inline JavaScript in the HTML and that broke the rendering on our side.

**Comment by leathej1** [comment]
Looks great - thank you!
