### ISSUE TITLE
--multi flag cannot be used with urls.txt

### ISSUE THREAD

**Issue by Xebi4i** [sitespeedio/sitespeed.io#2484]
Hello. I am trying to verify static pages and scripted scenarios in one test:
`docker-compose run sitespeed.io --config config.json urls.txt auth.js --multi`
But if I use --multi flag, my command is falling down with error. 
Without this flag, my script is not executed.

All files are mapped in compose file.
I am using the latest version of sitespeed: 9.0.0
MacOS machine
Chrome browser

Can someone please please check this combination on the personal machine: default docker compose with mapped files (urls.txt, config.json and .js script) and --multi flag?

docker-compose.yml

> version: '3'
> services:
>     sitespeed.io:
>       image: sitespeedio/sitespeed.io:9.0.0
>       command: -V
>       shm_size: 1g
>       volumes:
>             - ./sitespeed-result/:/sitespeed.io/sitespeed-result
>             - ./scripts/urls.txt:/sitespeed.io/urls.txt
>             - ./scripts/config.json:/sitespeed.io/config.json
>             - ./scripts/auth.js:/sitespeed.io/auth.js
>             - ./scripts/addtocart.js:/sitespeed.io/addtocart.js
>             - ./scripts/checkout.js:/sitespeed.io/checkout.js
>     grafana:
>       image: grafana/grafana:6.2.0
>       depends_on:
>         - graphite
>       links:
>         - graphite
>       ports:
>         - "3000:3000"
>       environment:
>         - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
>         - GF_SECURITY_ADMIN_USER=sitespeedio
>         - GF_AUTH_ANONYMOUS_ENABLED=true
>         - GF_USERS_ALLOW_SIGN_UP=false
>         - GF_USERS_ALLOW_ORG_CREATE=false
>       volumes:
>         - grafana:/var/lib/grafana
>       restart: always
>     graphite:
>       image: sitespeedio/graphite:1.1.5-3
>       ports:
>         - "2003:2003"
>         - "8080:80"
>       restart: always
>       volumes:
>         - whisper:/opt/graphite/storage/whisper
>         - ./graphite/graphite.db:/opt/graphite/storage/graphite.db
>         - ./graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
>         - ./graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
>         - ./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
>     grafana-setup:
>       image: sitespeedio/grafana-bootstrap:9.0.1
>       links:
>         - grafana
>       environment:
>         - GF_PASSWORD=hdeAga76VG6ga7plZ1
>         - GF_USER=sitespeedio
> volumes:
>     grafana:
>     whisper:

config.json file

> {
>    "browsertime":{
>       "iterations":1,
>       "browser":"chrome",
>       "visualMetrics":false,
>       "screenshot":false,
>       "videoParams":{
>          "createFilmstrip":false
>       },
>       "video":false
>    },
>    "plugins":{
>       "remove":["html","harstorer"]
>    },
>    "graphite":{
>       "host":"graphite"
>    }
> }

Thanks

**Comment by soulgalore** [comment]
Hi @Xebi4i the multi flag is used signal that all files that you feed is a script file, testing "multiple" pages within the same browser session. If you have a text file with URLs, each URL is in a new browser session.

Is your use case like this: auth.js logs in the user and then you want to teat one URL as a logged in the user? Then you can use `--preScript auth.js urls.txt` then for each URL a new browser will be opened, first running auth.js and then accessing the URL.

Best
Peter

**Comment by Xebi4i** [comment]
That makes sense. Thank you for explaining. Indeed I tried to use multi as preScript flag.
Close the ticket.
