### ISSUE TITLE
headless, visualMetrics and video parameters in config file are ignored. 

### ISSUE THREAD

**Issue by Xebi4i** [sitespeedio/sitespeed.io#2485]
Hello. 
_headless=true_ parameter in config.json file raises error, that make me include 2 other parameters (_visualMetrics=false_ and _video=false_) into the same config. But it does not help. 
I see the same error.
`docker-compose run sitespeed.io --config config.json https://google.com/`
> You cannot combine headless with video/visualMetrics because they need a screen to work.

But if I use _visualMetrics_ and _video_ parameters explicitly in command line, this error does not happen. 
`docker-compose run sitespeed.io --config config.json --visualMetrics false --video false https://google.com/`

Sitespeed version: 9.0.0

config.json file

> {
>    "browsertime":{
>       "iterations": 3,
>       "browser": "chrome",
>       "visualMetrics": false,
>       "video": false,
>       "headless": true,
>       "screenshot": false,
>       "outputFolder": "output"
>    },
>    "chrome": {
>       "timeline": true,
>       "args": "no-sandbox"
>    },
>    "plugins":{
>       "remove":["html","harstorer"]
>    },
>    "graphite":{
>       "host": "graphite",
>       "includeQueryParams": true
>    }
> }

Thanks

**Comment by soulgalore** [comment]
Hi @Xebi4i yeah that isn't optimal. I haven't verified but I think the reason that in our Docker file we automatically [turn on video and visual metrics by default](https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L3-L6) and I think they override what you configured in your configuration file. So it looks something like this:

`config.json -> docker config -> cli config`

We could move the docker config inside of sitespeed.io instead I guess and that would make it possible to fix the problem.

Best
Peter

**Comment by Xebi4i** [comment]
sounds good

**Comment by soulgalore** [comment]
This was fixed in 11.0.
