### ISSUE TITLE
Lighthouse perf budget 

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2496]
Is it possible to extend basic Lighthouse performance budget with more in-depth metrics?
I mean this budget which may be applied to different URLs in one test run.
{
"budget": {
  "lighthouse": {
      "performance": 90,
      "accessibility": 90,
      "best-practices": 90,
      "seo": 90,
      "pwa": 90
    }
  }
}

It would be great to see Time to Interactive, FirstCPUIdle and FirstContentfulPaint then.

Best Regards.

**Comment by soulgalore** [comment]
No not at the moment without any code changes. These are the ones available at the moment: https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/#all-possible-metrics-you-can-configure
