### ISSUE TITLE
Unable to test multiple urls in sitespeed through .txt file

### ISSUE THREAD

**Issue by prashanth-sams** [sitespeedio/sitespeed.io#2500]
### `budget.json`
```
{
  "budget": {
      "timings": {
        "firstPaint": 1000,
        "pageLoadTime": 2000,
        "fullyLoaded": 2000,
        "FirstVisualChange": 1000,
        "LastVisualChange": 1200,
        "SpeedIndex": 1200,
        "PerceptualSpeedIndex":1200,
        "VisualReadiness": 200,
        "VisualComplete95": 1190
      },
      "requests": {
        "total": 89,
        "html": 1,
        "javascript": 0,
        "css": 1,
        "image": 50,
        "font": 0
      },
      "transferSize": {
        "total": 400000,
        "html": 20000,
        "javascript": 0,
        "css": 10000,
        "image": 200000,
        "font": 0
      },
      "thirdParty": {
        "transferSize": 0,
        "requests": 0
      },
      "score": {
        "accessibility": 100,
        "bestpractice": 100,
        "privacy": 100,
        "performance": 100
      }
    }
  }
```
### `txt`
```
https://www.website1.com/
https://www.website2.com/
https://www.website3.com/
```
### `cmd`
```
docker-compose run sitespeed.io --graphite.host=graphite --budget.configPath budget.json --sites urls.txt
```
### `Output error`
```
One or multiple URLs or scripts
```

Note: The txt file is mounted inside containers as shown in this image
![image](https://user-images.githubusercontent.com/2948696/59158443-36915880-8acb-11e9-9bc5-ea3d75a5e9a1.png)

**Comment by soulgalore** [comment]
Hi @prashanth-sams thank for the report. I think the problem is that `--sites` is a non valid option, so since it isn't configured, the cli will take the next param after --sites.  If you skip --sites it should work. Could it be that we have some old docs somewhere that we need to change, do you know where you got that parameter?

Best
Peter

**Comment by prashanth-sams** [comment]
@soulgalore thanks for the prompt reply; I did removed the --sites option and it works. I believe I saw this somewhere in one of the existing github issues when I searched for it.
