### ISSUE TITLE
Need Help -- Request Header to pass LINK PREFETCH

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2508]
Before I make a change to the page to add prefetch/preload etc... i wanted to test using sitespeed by injecting or altering the header to add the LINK e.g. below for http header

HTTP Header: Link: </uploads/images/pic.png>; rel=prefetch

I looked at the sitespeed documentation --- how do I specify or use the --requestheader where it says key=value

would it look something like

**_--requestheader Link="</uploads/images/pic.png>;rel=prefetch"_**

**Comment by soulgalore** [comment]
Hi @softwareklinic the request header is the header you can configure that sitespeed.io will add to Chrome/Firefox when it access your site. 

If you wanna add a **response** header, I guess you can do that with a proxy. 

If you need to manipulate a page you can use `--browsertime.injectJs` - Inject JavaScript into the current page (only Firefox at the moment) at document_start. More info: https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts

Or if you use Chrome you can do that using Scripting see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#cdpsendcommand-args (I haven't unified that yet between Chrome/Firefox). 

But manipulating maybe doesn't help you.

Best
Peter

**Comment by soulgalore** [comment]
Closing let me know if there was something else you needed!
