### ISSUE TITLE
docker --shm-size=1g start parameter question

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2509]
Hello,
Recently I've found that --shm-size=1g docker parameter disappeared from all sitespeed.io documentation. Is it not useful anymore?

**Comment by soulgalore** [comment]
Hi @Icecold777 early 2019 https://github.com/sitespeedio/browsertime/blob/master/CHANGELOG.md#400---2019-01-21 we disabled the use of dev-shm in Chrome by default, so that config doesn't add any value (for Chrome). For Firefox I'm not sure.

Best
Peter

**Comment by Icecold777** [comment]
Cool, is --disable-dev-shm-usage flag already  applied in sitespeed.io code? or I should add it manually
?

**Comment by soulgalore** [comment]
Aha ok, its already there so you do not need to add it.

**Comment by soulgalore** [comment]
Closing. You don't need it for Chrome but it is still valuable for Firefox. Docs is updated.
