### ISSUE TITLE
[Feature request] Add tags to InfluxDB upload dynamically

### ISSUE THREAD

**Issue by petemyron** [sitespeedio/sitespeed.io#2512]
I'd like to be able to add tags to the influxdb results at runtime, not in `config.json`. Is this possible already? 

Essentially, using `--multi`, I check for certain html resources on some page, but the page can can fail. I want to add a tag to that test run that specifies that it failed.

I've tried creating some new fake measurement if/when it fails to find an element and it does work, but it creates a separate measurement, obviously, and that's not ideal. It does let me alert on too many failures in some time period through Grafana, though.

`example.js`:
```javascript
module.exports = async function(context, commands) {
    context.log.info('start script');
    await commands.navigate(
        'https://google.com'
    );

    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');

    try {
        console.log("try");
        // Measure login performance
        await commands.measure.start('test');
        await commands.click.bySelector('input.gNO89b');
        await commands.wait.byXpath('//*[@id="barf"]', 500);

        // if it fails, this never happens vvv
        // await commands.measure.stop();
        await commands.measure.start('test_good_results');
        await commands.wait.byTime(500);

    } catch(e) {
        console.log("didn't find the stupid thing: \n   " + e);
        // await commands.measure.stop();
        await commands.js.run('performance.mark("barfed");')
        await commands.measure.start('test_bad_results');
        await commands.wait.byTime(500);

    } finally {
        console.log("finally");

        return commands.measure.stop();
    }
}
```

Any other suggestions are welcome, too. I also intend to use this for some pass/fail scenarios rather than relying on missing data when it times out. I see there's a 'timings' tag/field. What's that for and can I use it?

**Comment by soulgalore** [comment]
Hi @petemyron aha I see. Today you can only add tags when you start the test with `--influxdb.tags`.

Let me think for a while of how we could implement something like that.

I wonder if it could be possible by adding your own JS metrics? `--script` - _"Add custom Javascript that collect metrics and run after the page has  finished loading. Note that --script  can be passed multiple times if you want to collect multiple metrics.The metrics will automatically be pushed to the summary/detailed summary and each individual page sent to Graphite/InfluxDB"._ 

Best
Peter

**Comment by petemyron** [comment]
Thanks @soulgalore! I'm having a hard time finding any examples of this switch actually being used. Are there any that you know of? What objects are available?

**Comment by petemyron** [comment]
I finally found https://www.sitespeed.io/documentation/sitespeed.io/scripting/, which I've seen a bunch before, but I think I'm in the same position. I think my only option is to do as above (which creates a separate measurement in influx--not ideal), or possibly directly write to influx explicitly from javascript, which also smells bad. I'll keep poking.

Just for people searching later, the template currently looks like this in a pre-, post- or multipage/selenium script:

```javascript
module.exports = async function(context, commands) {
  // add your own code here
}
```

**Comment by petemyron** [comment]
is there a way to access the raw results/objects from the test script? That'd be pretty easy to just inject it in there.

The best way I've come up with getting pass/fail results is to use a custom userTiming metric (shows on Page Summary):
![image](https://user-images.githubusercontent.com/627937/60626837-ea22fb00-9da0-11e9-880b-7420829cc102.png)

I've also tried creating a plugin, but I either can't access any objects from my test script in the plugin or I can't access any objects in the plugin (like `message` or `context`) in my test script. I run into other issues when doing this, but will create another issue for that.

Here's an example test script that will create a userTiming performance mark as seen above.

"passes":
```javascript
module.exports = async function(context, commands) {
  try {
    await commands.navigate('https://google.com');

    // search that should work correctly
    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');
    await commands.measure.start('google_search_1');
    await commands.click.bySelector('input.gNO89b');

    // pass/fail test
    await commands.wait.byXpath('//*[@id="resultStats"]', 3000); // passes

    // if it can't be found, this is never set to true
    await commands.js.run('performance.mark("test_pass");');

  } catch(error) {
    await commands.js.run('performance.mark("test_fail");');

  } finally {
    await commands.measure.stop();
  }

  return;
}
```

"fails":
```javascript
module.exports = async function(context, commands) {
  try {
    await commands.navigate('https://google.com');

    // search that will fail
    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');
    await commands.measure.start('google_search_2');
    await commands.click.bySelector('input.gNO89b');

    // pass/fail test
    await commands.wait.byXpath('//*[@id="resultStatsbarf]', 3000); // fails

    // if it can't be found, this is never set to true
    await commands.js.run('performance.mark("test_pass");');

  } catch(error) {
    await commands.js.run('performance.mark("test_fail");');

  } finally {
    await commands.measure.stop();
  }

  return;
}
```

This basically gives you the ability to add a graph/alert with pass/fail in something like Grafana, though they are separate queries, which is too bad, but at least it's actionable.

![image](https://user-images.githubusercontent.com/627937/60627919-85699f80-9da4-11e9-9cbe-5015a875e472.png)

**Comment by soulgalore** [comment]
Hi @petemyron sorry I totally missed this. If this still is an issue let me know. You can pass on options through the cli and you will get the in your plugin +  you can get whatever data other plugins produce by [listening on message](https://www.sitespeed.io/documentation/sitespeed.io/plugins/#processmessagemessage-queue).

Best
Peter

P.S Sorry again that I missed the issue.

**Comment by petemyron** [comment]
Hi @soulgalore. Yep, it's still something we should be able to do. The above is a hack.

**Comment by amitmalhotra-cell** [comment]
hi @petemyron , @soulgalore ,

_Just to share , i am sending pass,fail status using below:_

extraMetrics = { Pass: 1,Fail: 0}; // for Pass
extraMetrics = { Pass: 0,Fail: 1}; // for Fail
return commands.measure.addObject(extraMetrics);

This way i send it to HTML and influxdb and Grafana displays Pass Fail status based on count stored in influxdb.
HTML 
![image](https://user-images.githubusercontent.com/63041681/85919768-10805700-b88c-11ea-9fbf-054bbf1029bb.png)

**Comment by soulgalore** [comment]
I think that work around is great.
