### ISSUE TITLE
Local Test Location missing after error (TIMEOUT) encountered

### ISSUE THREAD

**Issue by aceey** [sitespeedio/sitespeed.io#2515]
Hi guys. I'm having this kind of issues lately and I have no idea what's going on.

I am regularly running my sitespeed runs daily. Well maintained and checked everyday. Since last week, I got this issue:

![image](https://user-images.githubusercontent.com/42996872/60064367-c1f92380-9732-11e9-88c9-8e881d6c61e9.png)

Everytime I encounter that issue, my WebPageTest Local Test Location is always missing after that error. And whenever I restarted all of my containers, everything will get back to normal. And when I run it again and same error is encountered. My WebPageTest Local Test Location is gone again. So I do the restart thing just to get that Local Test Location back and disregard that specific link on my scheduled runs.

Thanks guys.

**Comment by soulgalore** [comment]
Hi @aceey I think you should create an issue upstream in https://github.com/WPO-Foundation/wptagent/ . We run a WPT agent at work and I have't got any problem like that there. Make sure your instance is large enough (we use c5.large on AWS).

Best
Peter
