### ISSUE TITLE
Can we display the average page loading time in the pages.html table ?

### ISSUE THREAD

**Issue by Nanthakumar-Gunasekaran** [sitespeedio/sitespeed.io#2519]
In the pages.html, we display a table with page URL,Total size, Total requests, etc.

It would be helpful if we display the average Page loading time as well.

**Comment by soulgalore** [comment]
That will be fixed with https://github.com/sitespeedio/sitespeed.io/issues/2001 ... but i haven't started yet. FYI all metrics we show is the median not average!

**Comment by Nanthakumar-Gunasekaran** [comment]
Awesome.! Thanks

**Comment by soulgalore** [comment]
Tracked in #2001
