### ISSUE TITLE
Leaderboard Dashboard Failing - HTTP 500

### ISSUE THREAD

**Issue by gregorywolf** [sitespeedio/sitespeed.io#2521]
Hello -
I am unable to use the Leaderboard dashboard successfully. I am using 2 separate runs of sitespeed using a different set of URLs, each using a unique namespace. I know that the data exists in Graphite when I manually access the metrics. However, as soon as I open the Leaderboard dashboard I get an HTTP internal server error (500). I have attached all of the files that i am using to stand up my environment. Please note that i change the $namespace variable to one of my 2 namespaces that I use din the sitespeed run.

Couple of questions to be answered:

1. Should I be using specific versions of docker images for the various docker images?
Comment: When I use graphite v1.1.5-3 I continually see python errors in the log which is why I am using a later version.

2. It seems the only way i can get data to appear on the grafana dashboards is to use HTTP_PROXY. Not sure if this is the best approach....?

3. Not sure if all of the docker switches and options are the most appropriate. Need a confirmation.

Let me know if additional information is required.

[Files.zip](https://github.com/sitespeedio/sitespeed.io/files/3340069/Files.zip)

**Comment by soulgalore** [comment]
Hi @gregorywolf 

> 1

The latest tag in Docker is three years old so that is probably the problem that Graphite at that point didn't support the sortBy question specific for that dashboard. 

<img width="631" alt="Screen Shot 2019-06-28 at 21 54 56" src="https://user-images.githubusercontent.com/540757/60367968-efbec080-99ef-11e9-84a7-f554ae87e521.png">


If our container isn't working, you could use the official one, use the latest tagged version: https://hub.docker.com/r/graphiteapp/graphite-statsd/tags

Our version is just a thin wrapper that adds some extra config. I haven't upgraded it in a while, let me add that in the 2do list. I haven't seen the errors that you get for Graphite so not 100% sure.

I would start by updating the container, I think that could be the reason, the latest tag is just too old. I will also update the docs to be better about using tagged versions.


Best
Peter

**Comment by gregorywolf** [comment]
Peter - Thank you for the guidance. I used the new graphite repository and things are looking much better. The Leaderboard dashboard finally was successful. I was also able to switch back and forth between 2 different namespaces.

I would like to bring something up. Not sure if this is the right place or whether I should open up another Github issue. On the default dashboards (page summary, site summary, page timing metrics, and leaderboard) any panel that uses the sortby by function does not show any data. When drilling into the query using grafana query editor it shows that the first part of the metric is sitespeed_io even after I changed the variable name. I know the changed variable name is used since the other panels show data correctly. You mentioned that another user encountered a similar issue. Do you know if he ever was able to resolve? Is this issue unrelated to the other person? 

Let me now if I should open up a new issue.

Thank you.

**Comment by soulgalore** [comment]
Hi @gregorywolf ah ok, great!

About the other namespace. How do you add your dashboards? Do you inject them using https://github.com/sitespeedio/grafana-bootstrap-docker ? If so, I think that's something that we haven't thought of, that way it will always be inserted with sitespeed_io as the base. We haven't moved to the "new" way of provisioning dashboards as in https://grafana.com/docs/administration/provisioning/ maybe we should do that.

If you import the dashboard one by one, then you should get a question about what the constant should be.

**Comment by gregorywolf** [comment]
Hi @soulgalore -
Since I do not use grafana bootstrap, I am forced to import my dashboards individually. Not a problem. As you pointed out when I do the import the last input box allows me the alter the namespace from the default of sitespeed_io to whatever I used to collect data. The following is a screen shot of what I am referring to just to make sure we are on the same page.

![image](https://user-images.githubusercontent.com/8494683/60454885-0721c780-9c03-11e9-903b-0d78c8d2268e.png)

I also want to confirm that when I run sitespeed I use the following switch to generate my unique namespace:
--graphite.namespace=bbby.default
I can see the data successfully written to whisper database. Is the syntax of the switch correct?

After collecting data I open up some dashboards and I am still seeing sitespeed_io as the first par tof the metric, which causes no data to show up. So unfortunately changing the namespace name to bbby doe snot work as you suggested. So the question is am i doing something wrong or does something have to be done on your side? Also just to let you know I am using sitespeed 9.4.0, graphite 1.1.5-12, and grafana 6.2.2. Also I am no longer using the HTTP_PROXY.

Your continued help is much appreciated.

**Comment by soulgalore** [comment]
Ok, I wonder if there's bug in the dashboards or how I export them to not make them work when you change the namespace. Everything you do looks correct. Let me setup a different namespace tomorrow and reproduce.

**Comment by gregorywolf** [comment]
Hi @soulgalore - Let me provide some more details and screen shots. I want to make sure you have all of data I am using.
I am using the dashboards from https://github.com/sitespeedio/grafana-bootstrap-docker/tree/master/dashboards/graphite

The following screen shot displays the result of an imported dashboard that does not yield any panel data even after the dashboard is imported using the unique namespace. As you can see the underlying query still uses the sitespeed_io namespace in the metric space:

![image](https://user-images.githubusercontent.com/8494683/60463907-2e848e80-9c1b-11e9-8404-3a0dc8f60757.png)

This is a common result across a number of dashboards. 

Here is the Leaderboard. As you can see the left panel looks fine yet the right panel. However the underlying query is a little different. The comp namespace is populating the query but no data appears on the panel.

![image](https://user-images.githubusercontent.com/8494683/60464158-bec2d380-9c1b-11e9-9b74-c1b2b038c87c.png)

![image](https://user-images.githubusercontent.com/8494683/60464217-ee71db80-9c1b-11e9-8213-9f165aa78193.png)

**Comment by soulgalore** [comment]
Hi @gregorywolf to collect data when Largest Images and other visual elements appear you need to turn it on with `--visualElements `. It's not on by default because it will add some extra video/image work. For the other, let me have a look.

Best
Peter

**Comment by soulgalore** [comment]
The problem with the site summary was my fault, somehow there where hardcoded names instead of the constant. I've updated it now. Let me know if there are other dashboards that doesn't work!

**Comment by gregorywolf** [comment]
Thank you for all the help!! I will implement everything once I get into the office. I have a question in regards to dashboards and multiple namespaces. Your suggestion is that when a dashboard is imported use the namespace of interest in the import process. This will result in multiple dashboards, each configured with its own namespace. My goal is to import a dashboard once and then modify either the $base or $namespace variable changing it from constant to query and allowing multi selection. Do you see an issue with this approach? The problem is that I have not been able to identify the correct metric to query on in order to return the namespaces. Do you know the metric name or the correct approach to achieve my goal?

**Comment by soulgalore** [comment]
Hi @gregorywolf I usually use the same $base for all my tests. So for example if I use a Graphite instance that collects data from multiple data sources (where sitespeed.io is one of them) I just use sitespeed_io as the first and the change the next part. I use namespaces like `sitespeed_io.desktop` and `sitespeed_io.emulatedMobile` or `sitespeed_io.desktopUS`. Then all dashboards work. Ideally you would wanted to have more parts in the namespace but its been like this since version 4 I think and I don't want to change since it will break peoples dashboards.

**Comment by soulgalore** [comment]
And doing that way, the second part of the namespace is always in the dropdown and you can choose whatever data you need.

**Comment by gregorywolf** [comment]
@soulgalore Peter - Your approach is much better. Thank you. Have a great holiday!!!

**Comment by soulgalore** [comment]
I'll update the docs tomorrow so this approach is included.
