### ISSUE TITLE
using script through docker-compose, it can't find my script file 

### ISSUE THREAD

**Issue by hassankaz** [sitespeedio/sitespeed.io#2522]
Hi,

This is very similar to #2304 but since it's closed, I am creating a new issue.

I'm trying to run script through docker-compose (as I want to use the quick feature for building dashboard), but it keeps telling me it can't find the file. So after that I ran this command below, but it still doesn't work. It tells me "Run a one-off command on a service."  login.js file is located at the current directory.

docker-compose run -v $(pwd):/sitespeed.io --rm sitespeed.io /sitespeed.io/login.js --multi

It tells me 
Thank you!
Kazue

**Comment by soulgalore** [comment]
Hi @hassankaz 
I think if you use docker-compose you need to do the mapping in the docker compose file, something like:

```
volumes:
      - ${pwd}:/sitespeed.io
```

Best
Peter

**Comment by hassankaz** [comment]
I updated the compose file with

 volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - ./login.js/:/sitespeed.io/login.js

and it worked!  Thank you! 
Kazue
