### ISSUE TITLE
Is it possible to have addText.byName, or addText.byClassName?

### ISSUE THREAD

**Issue by hassankaz** [sitespeedio/sitespeed.io#2523]
Due to the limitation of our site, I can't use byId, nor bySelector, byXPath, is it possible to add
addText.byClassName? 

Thank you!
Kazue

**Comment by soulgalore** [comment]
Hi @hassankaz we need to some code to add that shortcut, we can do that. But it will take some time, so in the mean time you could do it by running your own JavaScript, checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#jsrunjavascript (not a perfect example but I think you get the idea).

Best
Peter

**Comment by soulgalore** [comment]
Hi @hassankaz try out 9.5.0:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#addtextbynametext-name
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#addtextbyclassnametext-classname

Best
Peter

**Comment by hassankaz** [comment]
Thank you so much @soulgalore !! This saves my life!

**Comment by soulgalore** [comment]
Great!
