### ISSUE TITLE
Is there any way to receive response directly into script, instead of going to readpage manually ?

### ISSUE THREAD

**Issue by Deep-Xbyte** [sitespeedio/sitespeed.io#2526]
Hello, 
I would like to use the site speed service with my scrapy script, for the testing purpose.

Is that anything by which I can send a request to the docker, and it directly response back, instead of writing a page.

Currently, I am doing it manually and have to wait until the page process finished and then Have to read the page manually, which is becoming the very time-consuming process.

**Comment by soulgalore** [comment]
Hi @Deep-Xbyte not 100% sure I follow. You can  either [create your own plugin](https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin) that has full access to  and get the result or you could use JSON output (use the analysisstorer plugin https://www.sitespeed.io/documentation/sitespeed.io/plugins/#add-a-plugin) to get the result as JSON.

Best
Peter

**Comment by soulgalore** [comment]
Closing since we didn't hear anything back.
