### ISSUE TITLE
VirtualBox/Ubuntu VM/Docker/Client Certificate

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2535]
I am using Sitespeedio using Docker for Ubuntu (VirtualBox). I am trying to prepare a test script for single-signon page. It uses SSL certificate and gets authenticated using Azure AD. I need your help to pass my client certificate inside the test script. I could not find any relevant documentation in website.

**Comment by soulgalore** [comment]
Hi @nevesing I think you should dig into to configuring Chrome/Firefox. For Chrome https://peter.sh/experiments/chromium-command-line-switches/ is a good page for checking different switches (use them with `--chrome.args` 

Best
Peter

**Comment by hellosirandy** [comment]
Hi @nevesing, I'm having the same problem here, are you able to insert client certificate to Sitespeed io command?

**Comment by nevesing** [comment]
Yes. You can either build a custom sitespeed image (or) use something like this in your extra start script:

`docker run -e EXTRA_START_SCRIPT=/sitespeed.io/test.sh --rm -v "$(pwd)":/sitespeed.io ...`.


```
#!/bin/bash
if  [ -f "/sitespeed.io/cert.pfx" ]
then
  echo "Importing client certificate"
  certutil -d sql:$HOME/.pki/nssdb -L
  pk12util -d sql:$HOME/.pki/nssdb -i /sitespeed.io/cert.pfx -W "" 
fi
```

**Comment by hellosirandy** [comment]
Well for me I'm working on inserting mTLS key/cert/ca on the request, how can I bind those within the Extra Start Script?
