### ISSUE TITLE
Provide a reference to the valid Selenium JS documentation.

### ISSUE THREAD

**Issue by vhryhorchuk-amplify** [sitespeedio/sitespeed.io#2536]
Hello.
It seems to me, that provided link to the Selenium JS documentation is not valid:
From https://www.sitespeed.io/documentation/sitespeed.io/scripting/#use-selenium-directly
```
You get a hold of the Selenium objects through the context. The selenium.webdriver that is the Selenium WebDriver public API object. And selenium.driver that’s the instantiated version of the WebDriver driving the current version of the browser.
```
I.e.:
Documentation refer to the `this.getRect()` method of `WebElement` to find a location.
But when we print `await context.log.info(context.webdriver.WebElement);` we find the `getLocation()` as a proper method.
There are a few more examples of mismatch.

Would suggest to provide a link to the proper documentation, where the Sitespeed.io gets this Selenium code, either notify users in the documentation about Selenium JS version.
Best regards,

**Comment by soulgalore** [comment]
Hi @vhryhorchuk-amplify which version of sitespeed.io are you using? In 9.5.0 we updated to latest Selenium and that should match the documentation (I hope, I'm not sure how they release updated versions of the docs).

Best
Peter

**Comment by vhryhorchuk-amplify** [comment]
My bad, I was using version 9.3.5.
Thanks for a quick response

**Comment by soulgalore** [comment]
Cool ok I think the docs been wrong then for almost a year (since we just upgraded to the alpha of Selenium 4). Versioning docs are hard :(
