### ISSUE TITLE
[Feature request] Performance Leaderboard for InfluxDB as datasource

### ISSUE THREAD

**Issue by ogarling** [sitespeedio/sitespeed.io#2538]
A brilliant Performance Leaderboard has been created as a Grafana dashboard which uses Graphite as datasource.
Would be very nice to be able to use InfluxDB as datasource which requires rewriting panel queries though.
Personally just migrated from Graphite to InfluxDB as TSDB like many in the community I presume.

**Comment by soulgalore** [comment]
Hi @ogarling yes I agree. I'm no InfluxDB user, so if someone one could help out and donate that dashboard, that would be great!

Best
Peter

**Comment by soulgalore** [comment]
We never got a contribution for this so closing. I think keeping Graphite dashboards is ok, and then it will be up to the user to create for influx/prometheus.
