### ISSUE TITLE
Unable to send annotations to Graphite

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2539]
Dockerized Sitespeed 9.5.0 on .213
Dockerized Sitespeedio/graphite 1.1.5-12 on .231

Command: ```docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io navigate-admin.js --config config-prod.json --preScript login-platform.js --browsertime.tenant "performance2.myco.com" -b chrome -n 1```

Everything works and logs to InfluxDB (on .213) But when we get to Graphite, I get:

```[2019-07-09 23:07:10] WARN: Got 500 from Graphite when sending annotation
[2019-07-09 23:07:10] ERROR: Error: Got 500 from Graphite when sending annotation
    at ClientRequest.lib.request.res (/usr/src/app/lib/plugins/graphite/send-annotation.js:91:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:441:20)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Graphite config in config-prod.json:

``` "graphite": {
    "host": "10.80.250.231",
    "httpPort": "8080",
    "port": "2003",
    "auth": "guest:guest",
    "annotationScreenshot": "true"
  },
```

**Comment by leathej1** [comment]
Graphite container on .231 is started with:
```
sudo docker run -d \
  --name graphite \
  -p 8080:80 \
  -p 2003:2003 \
  -v /opt/graphite/storage/whisper:/opt/graphite/storage/whisper \
  sitespeedio/graphite
```

**Comment by soulgalore** [comment]
Hi @leathej1 if you check on the Graphite side what do you see there? Check what for your instance name `docker ps` and then `docker logs INSTANCENAME`.

Try to [send annotations manually using curl](https://www.hostedgraphite.com/docs/api/annotations-and-events.html#creating-an-annotation-for-the-impatient) and check the log, to see if you get some hint of whats wrong.

Best
Peter

**Comment by leathej1** [comment]
Hmm. These instructions are for Hosted Graphite. When I try to send it with my IP and a --user, I get a 401.

In any case, the logs are like this:
```
[james.leatherman@graphitedb ~]$ docker logs graphite
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
[Tue Jul  9 22:50:42 UTC 2019]  building index...
[Tue Jul  9 22:50:44 UTC 2019]  complete, switching to new index file
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
No handlers could be found for logger "cache"
```

**Comment by soulgalore** [comment]
Ooops, sorry I'm on a very slow connection and that was the first thing I found on how to send an annotation using curl.

Was the configuration for how you start Graphite the one you use `sitespeedio/graphite`?  Then you use the dreadful **latest** Docker tag. Checkout https://www.sitespeed.io/documentation/sitespeed.io/docker/#tags-and-version 

Try start it with `sitespeedio/graphite:1.1.5-12`.

Best
Peter

**Comment by leathej1** [comment]
Well, I tend to `docker system prune -a` so that I can control my versions and save space. So the string I use do start sitespeedio/graphite shouldn't need a version, since I have only one.

**Comment by soulgalore** [comment]
Hi @leathej1 the Docker tag is usually the tag of the software in the container. The **latest** tag of sitespeedio/graphite was created 3 years ago see:
<img width="332" alt="Screen Shot 2019-07-10 at 21 24 02" src="https://user-images.githubusercontent.com/540757/60998389-21714900-a359-11e9-90e2-1457354aa8d6.png">

Meaning that container hasn't been updated since then and it runs an old version of Graphite. I'm not 100% sure that container supports tags. 

If you use the **1.1.5-12** tag, it was created 11 days ago (with at that time the latest version of Graphite meaning Graphite version 1.1.5-12.

I didn't get it how you control your versions using prune? If you use latest of any container, you are never safe of which version you are using. That's why you should always [use a specific tag](https://www.sitespeed.io/documentation/sitespeed.io/docker/#tags-and-version). 

Best
Peter

**Comment by leathej1** [comment]
Ah yes, you are right. I was depending on the `docker pull sitespeedio/graphite:1.1.5-12` to limit the `docker run` to that version, but it still fetches latest.

With the 1.1.5-12 version, everything works now! Thanks for your patience while I learn stuff.
