### ISSUE TITLE
Need integration with protractor

### ISSUE THREAD

**Issue by abhinaba1080** [sitespeedio/sitespeed.io#2542]
Hi Team,

first of all a big thumbs up for the work you are delivering to us.

1. Just wanted to check if we have sitespeed integration with protractor.  Any example/guide/documentation will be highly appreciated. 

2. On the same context, if i need to run sitespeed with selenium/protractor without cli, what needs to be done.  I want to start protractor tests in same way i use to run by invoking "protractor protractor.conf.js". I want sitespeed will trigger in runtime and measure the performance on the go. let me know if this is possible.

**Comment by soulgalore** [comment]
Hi @abhinaba1080 sorry for the really late answer, I missed this when I was on vacation.

> Just wanted to check if we have sitespeed integration with protractor. 

No, not that I know of.

> On the same context, if i need to run sitespeed with selenium/protractor without cli, 

Yes you can require sitespeed and use it from your script.

**Comment by soulgalore** [comment]
Closing, let me know if your questions didn't get answered.
