### ISSUE TITLE
[Feature request] Show resources loaded by service worker

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2543]
Currently, it is difficult to visualize why certain resources are being blocked because the prefetches being instantiated by the service worker are not visualized. It would be nice to have a parameter that would enable plotting service worker requests in the waterfall.

<img width="1493" alt="Screen Shot 2019-07-12 at 10 09 09 AM" src="https://user-images.githubusercontent.com/24658347/61146779-b0807d00-a48f-11e9-8026-1aaae9114cbb.png">

**Comment by soulgalore** [comment]
Hi @leathej1 I wonder if we pick up that info already doesn't show It? If you use Chrome and check a resource that you know is loaded by a service worker, do you see that as "initiated by"? Or do you have a URL that I can test and use so we can add that?

Best
Peter

**Comment by leathej1** [comment]
Sure - let me send you the creds.

**Comment by soulgalore** [comment]
I'm pretty sure "initiated by" will show it. Please re-open if not the case.
