### ISSUE TITLE
Performance drop when upgrading from sitespeed 8.15 to 9.6

### ISSUE THREAD

**Issue by naomijub** [sitespeedio/sitespeed.io#2546]
Hi Team
My team and I use sitespeed regularly to measure our frontends and determine Golden Signals. When we were using version 8.15 we ran 32 scenarios paralleled in ~360 seconds. When we upgrade to version 9.6 the time to run all 32 scenarios increase to ~1800 seconds. Same configuration and same scenarios. Our config file is:
```json
{
  "browsertime": {
    "iterations": 3,
    "browser": "chrome",
    "chrome": {
      "timeline": true,
      "collectConsoleLog": true
    },
    "visualMetrics": false,
    "headless": true
  },
  "utc": true
}
```

Also we observed that no metrics were caught when log `INFO` with text `Browser failed to start` was logged. Could it be changes to a log level `ERROR`? This affects our metrics also.

**Comment by soulgalore** [comment]
Hi @naomijub ,
do you use Docker? I’ve checked the changelog and there’s two things that I noticed: We upgraded from Chrome 74 to 75 and we changed lib for parsing Chromes tracelog from our own to Tracium. 

I think you can see where the time is spent by adding 
```—verbose
``` to your runs and then look at the timestamps in the log to understand where the time is spent. 

Best 
Peter

**Comment by soulgalore** [comment]
Easiest for you is to either on verbose and dig into the log. 

Or guess that I’m right and turn off the timeline log (checking again I could see that we added a couple of trace categories for Chrome = could mean slower performance) and check the time. And also build your own container roll back to Chrome 74.

Best
Peter

**Comment by naomijub** [comment]
Yes, we use docker.
We rolled back to 8.15 and everything went back to normal. Don't you think it is weird the whole process going from 360 s to 1800 s? Also, other people in slack reported seeing this effect also, but I guess they don't run as much scenarios at the same time as us.

**Comment by soulgalore** [comment]
If you check the logs I think you can see what takes more time. The upgraded I could see was new Chrome version (but in that case you should see that change in the metriics too) or the switch to Tracium (but please check the changelog to see if you can find something else).

On Slack people said WebPageTest took longer + other things. Easiest way for me or someone else is to try to create reproducable test cases and report more test data!

Best 
Peter

**Comment by soulgalore** [comment]
Ping @naomijub did you find any more info from the logs?

**Comment by naomijub** [comment]
Hi @soulgalore 
We stopped having problems by fixing our version to 8.x.x. We will only be able to evaluate migration to further versions in November.

Our logs just showed that multiple containers were concurrently accessing all our instance and due to this they were queued.
Sorry
