### ISSUE TITLE
Graphite Not Recording All Requested Data from SITESPEEDIO

### ISSUE THREAD

**Issue by gregorywolf** [sitespeedio/sitespeed.io#2547]
Hello - 

I am running  Sitespeed in a Docker image and sending data to a Graphite database. I have created TWO Graphite databases, one using Docker and one using a native installation. My intention is to use the native installation once I get past my current issue. I am testing the sitespeed run using the following settings and it is working great when directing the data to Graphite on Docker. However, when I run the SAME exact settings and direct the data to the Graphite server running the native installation I do not get all of the metrics. Specifically I am missing all of the FirstVisualChange metrics and many other categories. This in turn BREAKS all of the default Sitespeed dashboards.

As you can see by the two screen shots the resulting directories are VERY different.

I am suspecting that this is a Graphite installation issue but I thought I would start here first.

Any help or guidance would be much appreciated.

Thank you.

`docker run \
--rm \
--name=sitespeed-bbby \
-v "$(pwd)":/sitespeed.io \
sitespeedio/sitespeed.io:9.6.0 \
--cookie emailsignupapifeo=10 \
--firstParty ".bedbathandbeyond.com" \
--chrome.timeline \
--chrome.collectLongTasks \
--visualMetrics \
--visualElements \
--cpu \
--speedIndex \
--thirdParty.cpu \
-n 1 bbby-urls.txt \
--graphite.host=x.x.x.x \
--graphite.namespace=sitespeed_io.BBBY`

![Graphite Native](https://user-images.githubusercontent.com/8494683/61496389-11c1b800-a98a-11e9-93bb-72977a29a04f.png)
![Graphite Docker](https://user-images.githubusercontent.com/8494683/61496391-138b7b80-a98a-11e9-8b15-bd143706ea13.png)

**Comment by soulgalore** [comment]
Hi @gregorywolf 
checkout number 3: https://www.sitespeed.io/documentation/sitespeed.io/graphite/#graphite-for-production-important

The max create is low on default Graphite (to make sure it isnt overloaded). That means you can either increase it or just wait until metrics are cteated.

Best
Peter

**Comment by gregorywolf** [comment]
@soulgalore Peter - Thank so much!!! I changed the default value from 50 to inf and it works like a charm. When i move to production I will have to make sure my server is robust enough to handle the increased I/O.

Again thank so much!!
