### ISSUE TITLE
[FEATURE] Docker Swarm Rocks integration

### ISSUE THREAD

**Issue by maikschneider** [sitespeedio/sitespeed.io#2548]
It would be nice to be able to deploy sitespeed.io to a docker swarm. [Swarmprom](https://dockerswarm.rocks/swarmprom/) from the project [Docker Swarm Rocks](https://dockerswarm.rocks) is a very nice way to bootstrap a cluster with monitoring system.

Swarmprom already comes with grafana and traefik as reverse proxy. I wrote a docker compose file that integrates sitespeed.io into Swarmproms grafana with its existing configuration.

Steps to add sitespeed.io to your cluster:

```
$ export SITESPEED_COMMAND="-n 5 http://example.org/"
$ docker stack deploy -c sitespeed.io/docker/docker-compose.traefik.yml sitespeed"
$ docker run -it --network swarmprom_net -e GF_PASSWORD=${ADMIN_PASSWORD} -e GF_USER=${ADMIN_USER} sitespeedio/grafana-bootstrap:9.1.1
```

I'm aware that this would make more sense in the swarmprom project, however I think it's still a nice template for a fast deployment to a swarm. 

[feat: add compose file for swarm mode with traefik](https://github.com/maikschneider/sitespeed.io/commit/89de012846c06ed10d0f05a5b9138f495f02f1b6)

**Comment by soulgalore** [comment]
Hi, sorry I missed replying. I think since nothing happened for two years, I'll just close this.
