### ISSUE TITLE
Dashboards NOT Working When Pointing to Graphite Native Installation

### ISSUE THREAD

**Issue by gregorywolf** [sitespeedio/sitespeed.io#2550]
Hello - 
I currently have 3 VM instances, each running a Docker image with graphite, grafana, and sitespeed respectively. This configuration works great. I can create custom namespaces and all of the default dashboards works very nicely.

However, my goal is set up grafana and graphite using native installations. I have set them up and they work fine. My plan is to continue running sitespeed in a docker image and direct the data to my graphite server. I can successfully write all my data to either graphite server, either Docker or native installation. I can see the file tree structure and all of the related directories and files. However, when i use grafana (v6.2.2 or v6.2.5) I get different results depending on which graphite server I use as a source. When pointing to Docker everything works great. However, when pointing to graphite using native the dashboards yield no data. I know data exists because I can create a query and pull up data.

The following is a query that yields different results depending on which source is used.

`aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 'average'),3, 4)`

The query works on the Docker installation and yields no data on the native installation.

The following Docker command is used for BOTH graphite servers, albeit in separate runs; I simply change the IP address for the graphite server.

`docker run \
--rm \
--name=sitespeed-bbby \
-v "$(pwd)":/sitespeed.io \
sitespeedio/sitespeed.io:9.6.0 \
--cookie emailsignupapifeo=10 \
--firstParty ".bedbathandbeyond.com" \
--chrome.timeline \
--chrome.collectLongTasks \
--visualMetrics \
--visualElements \
--cpu \
--speedIndex \
--thirdParty.cpu \
-n 1 bbby-urls.txt \
--graphite.host=x.x.x.x \
--graphite.namespace=sitespeed_io.BBBY`

My suspicion was that the folder structure was different which was causing the problem, however, it appears that the folder structure is the SAME of both the Docker and native installations. The following 2 files are displays of the folder structure on each from the point of whisper downwards.

Any help would be much appreciated.

Thank you.

[graphite-native.txt](https://github.com/sitespeedio/sitespeed.io/files/3412843/graphite-native.txt)

[graphite-docker.txt](https://github.com/sitespeedio/sitespeed.io/files/3412849/graphite-docker.txt)

**Comment by soulgalore** [comment]
Hi @gregorywolf - I think your problem could be that your native Graphite version is old, do you know which version you are using? Did you install it from source? 

The Docker version is the latest (or almost latest version) released a couple of weeks ago. I doesn’t need to be so new but at I think version 1 something should do.

Best
Peter

**Comment by gregorywolf** [comment]
Hi @soulgalore - I was thinking the same thing. When I run Docker I am using graphite 1.1.5-12. However installing from source (https://launchpad.net/graphite/0.9/0.9.10/+download/graphite-web-0.9.10.tar.gz) appears to be a very old version.....like REALLY old. I have been digging around and cannot seem to locate the latest code for a native install. Could you point me to the latest release for a source install? I looked at github but I am not familiar enough with what to grab.....

Thank you for the help.

**Comment by soulgalore** [comment]
Great, please let me know if it works for you.

**Comment by gregorywolf** [comment]
Hi @soulgalore - UGH. I have been going round and round for days and am still no where!! I realize that this community is focused on sitespeed.io but you are incredibly knowledgeable and helpful So I am hoping you could lend me a hand once again.

My goal is to run graphite natively, not using Docker. The problem is that I have not been able to download the correct installation files. I have tried using yum and pip and git clone from the source directly. Can you point me to the correct method to download the most current installation. I am trying to install graphite-web, whisper and carbon.

Please take a look at another ticket I opened - https://github.com/graphite-project/graphite-web/issues/2469

It seems I am close but carbon will not install.
Any help would be much appreciated.

**Comment by soulgalore** [comment]
Hi @gregorywolf I never installed Graphite from scratch. that's the beauty of using Docker. 

I'm thinking maybe there are some help out there: If you follow the [official Docker container setup ](https://github.com/graphite-project/docker-graphite-statsd/blob/master/Dockerfile) with how they do with the installation of carbon (and all the other req). Following those exact step "should" work for you to.

Best
Peter

**Comment by gregorywolf** [comment]
Thanks @soulgalore I am making good progress now using github code.
