### ISSUE TITLE
[Feature] Add the FMP (first meaningful paint) metrics from CDP performance metrics

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#2552]
Currently, sitespeed.io has first-contentful-paint and first-paint reported in "Browser Metrics", shall we add **first-meaningful-paint** metric too from CDP performance metrics? 
https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics#user-centric_performance_metrics

**Comment by soulgalore** [comment]
Hi @joychester I think itsn't included in the CDP performance metrics yet? I did a quick check and couldn't see it. I know there are trace events like FMP candidates but then you need to choose.

Best
Peter

**Comment by joychester** [comment]
HI, @soulgalore , 

The FMP(FirstMeaningfulPaint) has been exposed by puppeteer, i am using the puppeteer to grab FMP metrics from my synthetic page tests,  the following detail metrics can be returned from CDP client: 

```
[
  { name: 'Timestamp', value: 35037.202627 },
  { name: 'AudioHandlers', value: 0 },
  { name: 'Documents', value: 3 },
  { name: 'Frames', value: 2 },
  { name: 'JSEventListeners', value: 63 },
  { name: 'LayoutObjects', value: 435 },
  { name: 'MediaKeySessions', value: 0 },
  { name: 'MediaKeys', value: 0 },
  { name: 'Nodes', value: 506 },
  { name: 'Resources', value: 11 },
  { name: 'ScriptPromises', value: 0 },
  { name: 'PausableObjects', value: 39 },
  { name: 'V8PerContextDatas', value: 1 },
  { name: 'WorkerGlobalScopes', value: 1 },
  { name: 'UACSSResources', value: 0 },
  { name: 'LayoutCount', value: 2 },
  { name: 'RecalcStyleCount', value: 5 },
  { name: 'LayoutDuration', value: 0.0860430000029737 },
  { name: 'RecalcStyleDuration', value: 0.00374899999587797 },
  { name: 'ScriptDuration', value: 0.0770069999925909 },
  { name: 'TaskDuration', value: 0.297364000020025 },
  { name: 'JSHeapUsedSize', value: 6295344 },
  { name: 'JSHeapTotalSize', value: 10891264 },
  { name: 'FirstMeaningfulPaint', value: 35036.03356 },
  { name: 'DomContentLoaded', value: 35036.122972 },
  { name: 'NavigationStart', value: 35035.833805 },
]
```
Following is some code sample i took from one of blog post, For the reference:
https://michaljanaszek.com/blog/test-website-performance-with-puppeteer#firstMeaningfulPaint
hope it helps!

Thanks!
Cheng

**Comment by soulgalore** [comment]
Hi @joychester you are right! We actually strip it out today as in https://github.com/sitespeedio/browsertime/blob/master/lib/chrome/webdriver/chromeDelegate.js#L302-L309 let me try to fix that when I'm back from vacation.

Best
Peter

**Comment by joychester** [comment]
Sure, Have a great vacation @soulgalore !!

**Comment by soulgalore** [comment]
Coming in next major!
