### ISSUE TITLE
how to get leaderboard working

### ISSUE THREAD

**Issue by hassankaz** [sitespeedio/sitespeed.io#2556]
Hi,
I'm trying to get leaderboard working without success.
I put the urls I want to test in a .txt file as in the following, but all I get is just a separate page result for each URL. Could you please let me know what I'm missing, and if I need to update anything on grafana. 

docker-compose run sitespeed.io competitors.txt --browsertime.cacheClearRaw --slack.hookUrl https://hooks.slack.com/services/T025MKY6A/BGLED0ZRN/yXXXXXXXX --graphite.host=graphite --graphite.namespace

Thank you!
Kazue

**Comment by soulgalore** [comment]
Hi @hassankaz you need to have the leaderboard dashboard and view that. You can get the dashboard https://github.com/sitespeedio/grafana-bootstrap-docker/blob/master/dashboards/graphite/Leaderboard.json.

And then make sure you choose the leaderboard dashboard in the dropdown in Grafana:
![AwesomeScreenshot-Leaderboard-Grafana-2019-07-27-09-07-34](https://user-images.githubusercontent.com/540757/61991446-71862600-b050-11e9-9c6d-6f6639c004a4.png)


Hope that helps!
Best
Peter

**Comment by hassankaz** [comment]
Thank you Peter,

I imported the leaderboard.json to grafana, then ran the job, I see the pages under domains, but no data show up:

![image](https://user-images.githubusercontent.com/1616330/62084569-7abcf180-b20e-11e9-8fe5-ff5eb1d088db.png)

Is there any other hookup I need to do for the UI to show up on the dashboard?

Thank you again,
Kazue

**Comment by hassankaz** [comment]
My grafana is 5.4.3(default installed by docker-compose). does it require newer version of grafana?

**Comment by soulgalore** [comment]
Hi @hassankaz yes you are right, it needs Grafana 6.2 or later (https://www.sitespeed.io/documentation/sitespeed.io/leaderboard/). 6.2 added that new look and feel. We constantly update the docker compose file with newer versions.

Best
Peter

**Comment by hassankaz** [comment]
Thanks. I updated docker-compose.yml to the latest. However, when i run `docker-compose up -d`, i get this error

![image](https://user-images.githubusercontent.com/1616330/62156799-8f59c200-b2c0-11e9-9d87-b1d6ce5b5f74.png)

I made sure to run `docker-compose down` so no other container running on the port.. 
What should I do to fix the error above?

Thank you again!
Kazue

**Comment by soulgalore** [comment]
It looks like you have something running on port 8080. Maybe something like https://github.com/docker/for-win/issues/573#issuecomment-301513210 ?

**Comment by hassankaz** [comment]
I just had to disable  - "8080:80" for ports in docker-compose.yml file.  The dashboard looks so nice! thank you so much!! 

Kazue
