### ISSUE TITLE
Unexpected results when reloading page

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2557]
Dockerized sitespeed.io:9.6.0

I am attempting to test an uncached SPA and then the cached version in the next step. However, the results of the hit to the cached page do not show API endpoints, and the timings are too quick.

```
module.exports = async function (context, commands) {
    tenant = context.options.tenant;
    console.log(context.options.tenant);
    commands.meta.setTitle('Navigate CRM');
    commands.meta.setDescription('https://' + tenant);
    try {
        await commands.measure.start('https://' + tenant + '/apps/agent/#', 'Open CRM');
        await commands.wait.byTime(1000);
        await commands.measure.start('https://' + tenant + '/apps/agent/#', 'Open CRM (cached)');
    } catch (e) {
        context.log.error(e);
        commands.error(e);
    }
};
```
I have tried a few versions of this script, but the results are the same. I can supply the scripts and config separately if you need them.

**Comment by soulgalore** [comment]
Hi @leathej1 I think that is a little bit too simple? What kind of cache do you have on your app and how does your app work? Like what is cached.

I would measure it in two different scripts. When you access URLs after each other with a wait, it depends on how long time the browser keeps the HTTP connection open to the server. So if the connection is still open, the second hit will be much faster.

Best
Peter

**Comment by leathej1** [comment]
OK, I see. I can work around this by navigating away from this page and then hitting it again in the same session.
