### ISSUE TITLE
[Enhancement] Add Transferred size to the Largest javascript files report

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#2558]
In toplist.html report --> "Largest JavaScript files" table, it shows the original size without compression, instead of real the transfer size on the network, shall we add one column => "Transfered size" to indicate how much size we transferred through network with compression enabled?

**Comment by soulgalore** [comment]
Hi @joychester good idea, I did a PR but need to test it out some more.

**Comment by joychester** [comment]
Thanks peter :)

**Comment by soulgalore** [comment]
Coming in next major!
