### ISSUE TITLE
Sending metrics to influxdb

### ISSUE THREAD

**Issue by Uladik** [sitespeedio/sitespeed.io#2567]
I am new to sitespeed, but it will definitely be very useful for my project. And I have a couple of questions to which I could not find answers, could you please help me?
1) Is it possible to send metrics to influx in real time, for example, my script consists of opening 3 pages, is it possible to send metrics for each page immediately after it loads? Now it sends metrics of all pages after the last one has loaded
2) Is it possible to send the error text to the influx? I have seen that the errors statistics data sent to the influx under the key browsertime.statistics.errors. But I wonder if the text of the error itself can be sent?
Thank you in advance!

**Comment by soulgalore** [comment]
Hi @Uladik I mostly use Graphite but I think I can answer your questions:
'
> 1 Is it possible to send metrics to influx in real time

The metrics are sent after all runs are done. For example if you have a script that test three pages, and you test them three times, the metrics are sent when all the runs have finished.

> Is it possible to send the error text to the influx

Nothing we have implemented but maybe something that is possible, I haven't tested. What kind of error messages are you thinking about?

Best
Peter

**Comment by Uladik** [comment]
@soulgalore For example:
[2019-08-04 20:40:37] ERROR: Could not find element by xpath //*[@id="passwordNext"]/spanspan
[2019-08-04 20:40:37] ERROR: Error: Could not find element by xpath //*[@id="passwordNext"]/spanspan

**Comment by soulgalore** [comment]
For that I would create my own error https://www.sitespeed.io/documentation/sitespeed.io/scripting/#error and then when I see the error in Grafana, click on annotation and see the error. One more step, but that's work today.

**Comment by soulgalore** [comment]
Let me know if you have any more questions.
