### ISSUE TITLE
ERROR: Error: Tracing is not started issue

### ISSUE THREAD

**Issue by manojs1978** [sitespeedio/sitespeed.io#2568]
Hi All,
getting below error while creating user journey ie end to end flow.

[2019-08-09 12:42:17] INFO: http://**********:40102/**/****** has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2019-08-09 12:42:18] INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.
[2019-08-09 12:42:19] ERROR: Error: Tracing is not started
    at _enqueueCommand (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\chrome-remote-interface\lib\chrome.js:90:34)
    at Chrome._handleMessage (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\chrome-remote-interface\lib\chrome.js:252:17)
    at WebSocket._ws.on (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\chrome-remote-interface\lib\chrome.js:230:22)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\ws\lib\receiver.js:422:14)
    at perMessageDeflate.decompress (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\ws\lib\receiver.js:379:23)
    at _decompress (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\ws\lib\permessage-deflate.js:298:9)
    at _inflate.flush (C:\Users\****\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\ws\lib\permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)

steps :
1) create user journey using commands.measure.start /commands.measure.stop.
2) in last step of user journey  we are facing above issue.
and we are not gettign page wise result. we are getting only one page ie last page results.

**Comment by soulgalore** [comment]
Hi @manojs1978 thanks for creating the issue! Please have a look at https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ to make a reproducable bug, it makes it so much easier for us to fix things! 

Best
Peter

**Comment by manojs1978** [comment]
steps :

create user journey using commands.measure.start /commands.measure.stop.
create multiple user journey steps more than 10.
in last step of user journey we are facing above issue.
and we are not getting page wise result. we are getting only one page ie last page results.
command:
sitespeed.io -n 1 http://**/**/ --preScript **.js  --chrome.timeline

OS/sitespeed/browsertime  version
Versions OS: win32 10.0.16299 nodejs: v10.16.0 sitespeed.io: 9.8.1 browsertime: 5.7.3 coach: 3.6.0

browser version: 75.0.3770.142

**Comment by manojs1978** [comment]
require('events').EventEmitter.prototype._maxListeners = 15;
module.exports = async function(context, commands) {
  context.log.info('Info logging from your script');
  context.log.error('Error logging from your script');

var rn = require('random-number');

var gen = rn.generator({
  min:  1
, max:  10000000
, integer: true
})

var rnumber = require('random-number');
var gen1 = rnumber.generator({
  min:  1
, max:  10000000
, integer: true
})

  const webdriver = context.selenium.webdriver;

  const driver = context.selenium.driver;

  await commands.measure.start('http://inde5539.eaas.amdocs.com:40102/content/digitalexp/flow/login-menu.html');

await commands.measure.start('shop Anonymous');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[3]/div/form/button')
await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[2]/section/div/div/div/div/a[1]', 5000)
await commands.wait.byTime(5000)
await commands.measure.stop();



  await commands.measure.start('devicelist');

  await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[2]/section/div/div/div/div/a[1]')
  await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[4]/div/div/section/div[2]/div/div/ul/li[2]/div/div[1]/figure/div/img', 15000)
  await commands.wait.byTime(8000)
  await commands.measure.stop();

  await commands.measure.start('devicedetails');
  await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/div/section/div[2]/div/div/ul/li[3]/div/div[1]/figure/div/img')

  await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[4]/div/section/div[2]/button', 5000)


await commands.measure.stop();

await commands.wait.byTime(5000)


await commands.measure.start('choosePlan');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/section/div[2]/button')
//await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/section/div[1]/section/button')
await commands.wait.byTime(8000)

await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/section/div[1]/div/div[3]/div/div/section/section/button/span')

await commands.wait.byTime(8000)
await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[4]/div/div/div/div[2]/section/div[2]/div/div/ul/li[6]/div/div[4]/button', 15000)

await commands.wait.byTime(5000)
await commands.measure.stop();


await commands.measure.start('productconf');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/div/div/div[2]/section/div[2]/div/div/ul/li[7]/div/div[4]/button/span')
await commands.wait.byXpath('/html/body/section/div[1]/div[2]/div/div/button', 15000)
await commands.wait.byTime(5000)
await commands.measure.stop();



await commands.measure.start('BringMyNumber');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[2]/div/div/button')
await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[5]/div[1]/div[1]/div/div/div/div/ul/li[2]/label/span[2]/span', 5000)
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[5]/div[1]/div[1]/div/div/div/div/ul/li[2]/label/span[2]/span')

await commands.wait.byXpath('/html/body/section/div[1]/div[2]/div/div/button', 7000)
await commands.wait.byTime(5000)
await commands.measure.stop();

await commands.measure.start('cart');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[2]/div/div/button')
await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[4]/div/div[2]/div[1]/footer/button[1]/span', 5000)
await commands.wait.byTime(5000)
await commands.measure.stop();



await commands.measure.start('createCustomer');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/div[2]/div[1]/footer/button[1]/span')
await commands.wait.byXpath('/html/body/section/div[1]/div[2]/div/div[2]/button/span', 15000)
await commands.wait.byTime(5000)
await commands.measure.stop();




await commands.measure.start('deliveryOption');

driver.findElement(webdriver.By.xpath("//input[@name='owningIndividual.firstName']")).sendKeys("manoja"+gen()+gen1());
driver.findElement(webdriver.By.xpath("//input[@name='owningIndividual.lastName']")).sendKeys("manoja"+gen()+gen1());
driver.findElement(webdriver.By.xpath(".//span[.='Date of birth']/..//input[@name='date']")).sendKeys("21");
driver.findElement(webdriver.By.xpath(".//span[.='Date of birth']/..//input[@name='months']")).sendKeys("02");
driver.findElement(webdriver.By.xpath("//span[.='Date of birth']/..//input[@name='years']")).sendKeys("1980");
driver.findElement(webdriver.By.xpath("(.//input[@type='tel'])")).sendKeys("032323232323");
driver.findElement(webdriver.By.xpath("(.//input[@type='email'])")).sendKeys("manoj"+gen()+"su"+gen1()+"@amdocs.com");

driver.findElement(webdriver.By.xpath("(.//span[@class='ds-form__text'][text()='Email'])")).click();


selectElem = driver.findElement(webdriver.By.xpath("/html/body/section/div[1]/div[1]/div[5]/div[1]/div/section/div/div/section[2]/fieldset/div/div[1]/div/select"));
selectElem.findElement(webdriver.By.xpath("/html/body/section/div[1]/div[1]/div[5]/div[1]/div/section/div/div/section[2]/fieldset/div/div[1]/div/select/option[3]")).click();



driver.findElement(webdriver.By.name("owningIndividual.identification.identificationNumber")).sendKeys(gen()+gen1());

driver.findElement(webdriver.By.name("owningIndividual.identification.issuerName")).sendKeys("amdocsd");

driver.findElement(webdriver.By.xpath("(//span[.='Expiration Date']/..//input[@name='date'])")).sendKeys("21");
driver.findElement(webdriver.By.xpath("(//span[.='Expiration Date']/..//input[@name='months'])")).sendKeys("02");
driver.findElement(webdriver.By.xpath("(//span[.='Expiration Date']/..//input[@name='years'])")).sendKeys("2020");

driver.findElement(webdriver.By.xpath("(.//span[contains(., 'Issued')]/..//input[@name='date'])")).sendKeys("21");
driver.findElement(webdriver.By.xpath("(.//span[contains(., 'Issued')]/..//input[@name='months'])")).sendKeys("02");
driver.findElement(webdriver.By.xpath("(.//span[contains(., 'Issued')]/..//input[@name='years'])")).sendKeys("2018");


var fileInput = driver.findElement(webdriver.By.xpath('/html/body/section/div[1]/div[1]/div[5]/div[1]/div/section/div/div/section[2]/fieldset/div/div[6]/div/div[2]/div[4]/label/input'));
var path = process.cwd()+'/attch.png';
fileInput.sendKeys(path);

driver.findElement(webdriver.By.name("address.addressLine1")).sendKeys("pune");
await commands.wait.byTime(5000)
driver.findElement(webdriver.By.xpath("/html/body/section/div[1]/div[1]/div[5]/div[1]/div/section/div/div/fieldset/div/div/section/div[2]/fieldset/div/div[1]/div/div[2]/ul/li/div")).click();

driver.findElement(webdriver.By.xpath("//button[@class='ds-btn ds-btn--primary']/span")).click();


await commands.wait.byTime(12000)
await commands.wait.byXpath('/html/body/section/div[1]/div[2]/div/div[2]/button/span', 10000);

await commands.measure.stop();
await commands.measure.start('ordersummary');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[2]/div/div[2]/button/span')
//await commands.wait.byXpath('/html/body/section/div[1]/div[1]/div[4]/div/div/footer/button/span', 12000)

await commands.measure.stop();



await commands.measure.start('orderConfirmation');
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/div/div[2]/div[1]/div[3]/form/fieldset/div/div/div[1]/label/div/span[1]')
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/div/div[2]/div[1]/div[4]/form/fieldset/div/div/div[1]/label/div/span[2]')
await commands.wait.byTime(3000)
await commands.click.byXpathAndWait('/html/body/section/div[1]/div[1]/div[4]/div/div/div[2]/footer/button/span')

await commands.measure.stop();


await commands.measure.stop();

return commands.measure.stop();
};



above is the file which i am running using --preScript option
command :
sitespeed.io -n 1 http://**/***/**/login-menu.html/ --preScript Anonymous**.js  --chrome.timeline

**Comment by manojs1978** [comment]
i beg you pardon closing this issue , i was facing this issue due to extra line "await commands.measure.stop();" in my code.
now its working fine,

**Comment by manojs1978** [comment]
i beg you pardon closing this issue , i was facing this issue due to extra line "await commands.measure.stop();" in my code.
now its working fine,

**Comment by manojs1978** [comment]
i beg you pardon closing this issue , i was facing this issue due to extra line "await commands.measure.stop();" in my code.
now its working fine,
