### ISSUE TITLE
There is no data in the table

### ISSUE THREAD

**Issue by Uporaba1** [sitespeedio/sitespeed.io#2573]
![image](https://user-images.githubusercontent.com/32709525/63079959-40b35580-bf59-11e9-9624-b7f429051f2a.png)
Hello. Why some data is not displayed? How can I can debug this?

**Comment by soulgalore** [comment]
HI @Uporaba1 can you please share a little more about your setup? That helps us a lot to track down the problem! See https://www.sitespeed.io/documentation/sitespeed.io/bug-report/

Best
Peter

**Comment by Uporaba1** [comment]
Everything is configured through the docker. On 1st server, grafana + graphite is deployed, on 2nd, container sitespeed with this settings: `docker run --name speedtest --rm -v /home/speedtest/urls.txt:/sitespeed.io/urls.txt sitespeedio/sitespeed.io:9.8.1 urls.txt --graphite.host=IP -n 1 --speedIndex false --video false -c 3g --graphite.namespace sitespeed_io.test` which start on cron. In urls.txt list of sites surveyed.

**Comment by soulgalore** [comment]
Is it default Graphite or our version with pre-made config? Checkout point number 3 in https://www.sitespeed.io/documentation/sitespeed.io/graphite/#graphite-for-production-important 

Best
Peter

**Comment by soulgalore** [comment]
Closing since no response.
