### ISSUE TITLE
data on time boundaries

### ISSUE THREAD

**Issue by srijondas** [sitespeedio/sitespeed.io#2582]
how is the data so precisely aligned to the time boundaries on grafana ... 10:10 AM, followed by 10.20 AM... 10.30.. 10.40 and so on, while my test has been running all the time.

Also is there a configuration that can be changed to report the actual time when the transaction happened rather than report all the results on 10 minute intervals.

**Comment by soulgalore** [comment]
It is reported when its finished. You can configure Graphite how to store values, checkout Etsys write down how storage/retention in Graphite works: https://github.com/statsd/statsd/blob/master/docs/graphite.md

**Comment by soulgalore** [comment]
Let me update our docs too so it clearer to see why and how!
