### ISSUE TITLE
Not using visual metrics

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2585]
Hi Guys,

Not an issue, just a question :)

Are we able to not use visual metrics and just record the time in which you requested the test to stop when using --browsertime.pageCompleteCheck ??

Regards,
scabenga

**Comment by soulgalore** [comment]
Hi @scabenga yeah it should work. If you use Docker you need to disable both video and visual metrics (they are turned on by default in Docker). If you add `--visualMetrics false --video false` I think it would work. 

Just to be clear, the tests always stops with ` --browsertime.pageCompleteCheck` but running Visual Metrics there are some extra work done, analysing the video etc.

Best
Peter

**Comment by scabenga** [comment]
Thanks @soulgalore !  All sorted.
