### ISSUE TITLE
Grafana-PageTimingMetrics (domain/page dropdown menu)

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2586]
Environment - VIrtualBox-Ubuntu/Docker-Compose (sitespeedio version)

I am trying to execute below sample script using docker-compose and send the metrics to localhost graphite. Note that the list of domains are different but the grafana dashboard (page summary for example) shows all page names (page dropdown-domain1,2,3) for any domain name (domain dropdown) i select which is very confusing. Expectation is that it should list only relevant page names depends on domain selection. Please correct me if I am wrong.

```
module.exports = async function(context, commands) {
  await commands.measure.start('Domain1');
  await commands.navigate('https://domain1.com/home');
  await commands.measure.stop();
  await commands.wait.byTime(1000);
  await commands.measure.start('https://domain2.com','Domain2');
  await commands.wait.byTime(1000);
  return await commands.measure.start('https://domain3.com','Domain3');
};
```

**Comment by soulgalore** [comment]
Hi @nevesing I've checked the dashboard and it looks like the page section (that dropdown) is populated depending on the domain you are using. 

Could it be dirty data? You can check that in Grapite or Grafana if you edit the query. 

Best
Peter

**Comment by nevesing** [comment]
Thanks for your reply. It is not dirty data. I double checked again using below script and docker command.

**Docker command:**

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.8.1 interneturls.js --multi -n 1 graphite.host=mygraphitehostname`

**Script:**

```
(module.exports = async function(context, commands) {
  await commands.measure.start('https://google.com','Google');
  await commands.wait.byTime(1000);
  await commands.measure.start('https://youtube.com','Youtube');
  await commands.wait.byTime(1000);
  return await commands.measure.start('https://yahoo.com','Yahoo');
};)
```
**Grafana screenshot:** Selecting 'google' still shows all page names

![Grafana](https://user-images.githubusercontent.com/50423486/63466156-a9ef0900-c430-11e9-8f5f-190186b4d42c.JPG)

**Comment by soulgalore** [comment]
Hi @nevesing yeah that looks strange, let me have a look tomorrow and check if I understand why.

Best
Peter

**Comment by nevesing** [comment]
Thanks. Below is the output for docker command in case you need it.

```
Google Chrome 76.0.3809.87 
Mozilla Firefox 68.0
[2019-08-21 20:37:13] INFO: Versions OS: linux 5.0.0-25-generic nodejs: v10.13.0 sitespeed.io: 9.8.1 browsertime: 5.7.3 coach: 3.6.0
[2019-08-21 20:37:13] INFO: Running tests using Chrome - 1 iteration(s)
[2019-08-21 20:37:14] INFO: Start to measure Google
[2019-08-21 20:37:15] INFO: Navigating to url https://google.com iteration 1
[2019-08-21 20:37:25] INFO: Start to measure Youtube
[2019-08-21 20:37:25] INFO: Navigating to url https://youtube.com iteration 1
[2019-08-21 20:37:48] INFO: https://www.google.com/ 38 requests, 647.81 kb, backEndTime: 232ms, firstPaint: 454ms, firstVisualChange: 507ms, DOMContentLoaded: 627ms, Load: 1.19s, speedIndex: 867, visualComplete85: 1.59s, lastVisualChange: 6.15s, rumSpeedIndex: 455
[2019-08-21 20:37:48] INFO: https://www.youtube.com/ 75 requests, 2699.27 kb, backEndTime: 178ms, firstPaint: 1.30s, firstVisualChange: 134ms, DOMContentLoaded: 2.59s, Load: 2.83s, speedIndex: 1649, visualComplete85: 2.63s, lastVisualChange: 4.20s, rumSpeedIndex: 1628
[2019-08-21 20:37:52] INFO: HTML stored in /sitespeed.io/sitespeed-result/interneturls_js/2019-08-21-20-37-13
```

**Comment by soulgalore** [comment]
Thanks. Thinking about yesterday I understood what's going. The current versions map the alias against the page part of the URL (not the domain) so for example if you test multiple pages at / with different aliases, / is assigned all of those.

Let me think if there's an easy solution.

**Comment by soulgalore** [comment]
Had a quick look and I was wrong. I could see that PageXray and the third party plugin send message with wrong group/domain and that messages thing up. I'll try to fix it this weekend.

**Comment by soulgalore** [comment]
I've just merged https://github.com/sitespeedio/sitespeed.io/pull/2592 that is going out in the next alpha release. If you need to use stable, you need to skip aliases for different domains for now. The new stable is going out in the middle of September.

Best
Peter

**Comment by nevesing** [comment]
Thanks Peter. I will wait for the next stable version.

**Comment by soulgalore** [comment]
This is fixed and released.
