### ISSUE TITLE
same url on page with multiple transactions

### ISSUE THREAD

**Issue by srijondas** [sitespeedio/sitespeed.io#2590]
The below transactions in the code snippet happen in one single page - view the pdp page, click on buy, click on buy confirm. All of the transactions occur on the same pdp url with ajax calls to the backend. 

Does the numbers appearing on Grafana represent the sum of all transactions, or just one of these transactions.

If I add additional command.measure.start commands to the snippet, then the script fails. I tried these steps but it fails - https://www.sitespeed.io/documentation/sitespeed.io/spa/  

  await commands.measure.start('measure_pdppage')
  await webdriver.get('https://somepdppage.com/details/pdp_item1')
  await webdriver.findElement(By.css('[data-elm-id=\"buy_button\"]')).click()
  await webdriver.findElement(By.css('[data-elm-id=\"buy_confirm\"]')).click() 
  await commands.measure.stop()

**Comment by soulgalore** [comment]
Hi @srijondas it depends on the metrics. The visual metrics like first visual change, last visual change will represent the full flow. So in your example, last visual change would be a metric that would work. For the performance metrics in JS are mostly for first view. If you add [user timings](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) and measure each step, they will then be collected when you do measure.stop.

Best
Peter

**Comment by soulgalore** [comment]
Closing, let me know if you need more info.
