### ISSUE TITLE
Retina support?

### ISSUE THREAD

**Issue by chregu** [sitespeedio/sitespeed.io#2596]
Would it be possible to add support for retina screens, resp. screens with a higher device-to-pixel ratio? Since most screens are like this nowadays, it would be useful to have that. Especially for image sizes as lots of pages use `srcset` to load different images depending on the dpr of the screen.

There's an old report for that already at #317, but maybe lots has changed in the meantime.

**Comment by soulgalore** [comment]
Hi @chregu if you use Chrome you can set the pixel ratio when you emulate a device, would that do?

`--browsrertime.chrome.mobileEmulation.pixelRatio` -  Pixel ratio of emulated mobile screen (e.g. 2.0)

I haven't tested it myself, I usually just set the deviceName when emulating so not 100% sure how/if it works.

Best
Peter

**Comment by chregu** [comment]
Thanks for your help.

That doesn't seem to have any effect. Even if setting `--browsertime.chrome.mobileEmulation.pixelRatio` to 1.0, it still downloads images in retina quality (set by srcset) in the mobile profile (or if set to 2.0, it downloads them in not-retina quality for non mobile profile)

**Comment by soulgalore** [comment]
Hi @chregu ok, hmm, could you see that mobile emulation really was kicked in for Chrome? Another way could be to test one of the Chrome pre made profiles `--chrome.mobileEmulation.deviceName`

See https://github.com/sitespeedio/browsertime/blob/5769b5ebfed219987f9d48f4e13b4e8c047447e6/lib/support/getViewPort.js#L11-L25

`--chrome.mobileEmulation.deviceName "iPhone X"` should fix that I hope.

Best
Peter

**Comment by soulgalore** [comment]
Closing since no feedback. Please get back and we can re-open.
