### ISSUE TITLE
Unable to send influxdb tags

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2604]
Dockerized Sitespeed 9.8.1

Using something like `--influxdb.tags "build=1.0"` in your docker run command will prevent sending annotations to InfluxDB.

**Comment by soulgalore** [comment]
I wonder if it could be fixed in master with https://github.com/sitespeedio/sitespeed.io/pull/2587 ? I did a quick try and it looked ok for me. Did you get any error message?

**Comment by leathej1** [comment]
No error that I noticed.

**Comment by leathej1** [comment]
I'm curious how anyone is using this in a CI pipeline, since tagging a build number is pretty important. Maybe this is only affecting InfluxDB.

**Comment by leathej1** [comment]
I have tags again - thank you!!

**Comment by soulgalore** [comment]
great
