### ISSUE TITLE
Incomplete first view data for WPT test with webpagetest multi steps script

### ISSUE THREAD

**Issue by fxbtr** [sitespeedio/sitespeed.io#2617]
_INFO: Versions OS: linux 4.9.184-linuxkit nodejs: v10.13.0 sitespeed.io: 9.8.1 browsertime: 5.7.3 coach: 3.6.0_

Hello, 

I have an issue that already popped up a few times [here and there](https://github.com/sitespeedio/sitespeed.io/issues/1897) but I could not find help in the comments.

I am running a 3 steps script on webpagetest and getting the following error: 

> [2019-09-04 12:34:03] INFO: Sending url https://www.cdiscount.com/informatique/tablettes-tactiles-ebooks/samsung-2-en-1-galaxy-book-12-pouces-fhd-ram/f-1079801-smw720nzkbxef.html to test on xxx
[2019-09-04 12:41:47] INFO: Got https://www.cdiscount.com/informatique/tablettes-tactiles-ebooks/samsung-2-en-1-galaxy-book-12-pouces-fhd-ram/f-1079801-smw720nzkbxef.html analysed with id 190904_a01wptui001iA9_184 from xxx
[2019-09-04 12:41:47] INFO: WebPageTest result at: http://xxx/results.php?test=190904_a01wptui001iA9_184
[2019-09-04 12:41:49] ERROR: Incomplete first view data for WPT test 190904_a01wptui001iA9_184, run 1
[2019-09-04 12:41:49] ERROR: Metricsfilter: The breakdown is missing from the metrics breakdown.*.requests
[2019-09-04 12:41:49] ERROR: Metricsfilter: The breakdown is missing from the metrics breakdown.*.bytes
[2019-09-04 12:41:51] ERROR: TypeError: Cannot read property 'details' of undefined on line 24
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:84:99)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1767:3)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:352:35)

I am using docker with the following parameters: 
`docker run --rm -v C:\Git\Budgets-Batch:/sitespeed.io sitespeedio/sitespeed.io:9.8.1 --config ./config/desktop.json --budget.configPath ./budgets/FP/myBudget.json https://www.cdiscount.com/informatique/tablettes-tactiles-ebooks/samsung-2-en-1-galaxy-book-12-pouces-fhd-ram/f-1079801-smw720nzkbxef.html --graphite.namespace sitespeed_io.desktopFirstView_NoConsent    --webpagetest.file ./scripts/WPT_ATB_NoConsent.txt`

The config works as intended with a script that doesn't involve multiple steps but let me know if you do need it. 

The script itself: 

> setActivityTimeout	250
> setEventName	FP:::fp
> navigate	https://www.cdiscount.com/informatique/tablettes-tactiles-ebooks/samsung-2-en-1-galaxy-book-12-pouces-fhd-ram/f-1079801-smw720nzkbxef.html
> setEventName	RA:::ra
> execAndWait document.getElementById('fpAddBsk').click()
> setEventName	BASKET:::basket
> navigate	https://www.cdiscount.com/Basket.html

And obtaining this JSON from WPT: https://gist.github.com/fxbtr/949c75a2226e574e0b4b40d8365ac29c

Despite a JSON that looks okay, the data are not sent to Graphite and some information are missing on WPT (first screenshot showing the issue, second from a different but working test)
<img width="482" alt="ko atb" src="https://user-images.githubusercontent.com/41640867/64261203-716d2600-cf2c-11e9-9b7b-c510283838a9.PNG">
<img width="482" alt="ok atb" src="https://user-images.githubusercontent.com/41640867/64261209-74681680-cf2c-11e9-97f3-0cb354c1d4fa.PNG">

What I am looking for: being able to send to Graphite the following metrics SI, TTFB, # of css requests (breakdown.css.requests), JS transfersize (breakdown.js.bytes) for each step, similar to your implemetation with browsertime :) 

Thank you for your time

**Comment by soulgalore** [comment]
Hi @fxbtr I think either our implementation is broken or the WebPageTest API. Let me have a look the coming the days and try to understand what's going wrong. We are pushing a new release next week and it would be great to fix it before that.

Thanks for sharing the script, that makes it so much easier for me to reproduce.

Best
Peter

**Comment by soulgalore** [comment]
Had a quick look and you are right, it doesn't work. We haven't prepared our code for it + I didn't understand the JSON the API returns for multi step. I need to have some time to implement it or if someone else can ship in.  Let us track that work in https://github.com/sitespeedio/sitespeed.io/issues/2620

**Comment by fxbtr** [comment]
Sorry, it took me time to reply but I noticed your swift replies, thank you.

**Comment by soulgalore** [comment]
Closing this in favour of #2620
