### ISSUE TITLE
Proxy configuration does not work through corporate proxy

### ISSUE THREAD

**Issue by Zujiry** [sitespeedio/sitespeed.io#2618]
I am trying to get sitespeed.io running in a docker container running through a corporate proxy. The docker container is started with docker-compose.

**Using:** Docker via docker-compose
**Sitespeed-version:** 9.8.1
**Base OS:** Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux 

**Command:**
docker-compose run sitespeed.io https://sitespeed.io --graphite.host=graphite -v

**Output:**
Google Chrome 76.0.3809.87
Mozilla Firefox 68.0
[2019-09-05 11:39:35] INFO: [sitespeedio] Versions OS: linux 4.9.0-9-amd64 nodejs: v10.13.0 sitespeed.io: 9.8.1 browsertime: 5.7.3 coach: 3.6.0
[2019-09-05 11:39:36] DEBUG: [sitespeedio.plugin.graphite] Setting up Graphite graphite:2003 for namespace sitespeed_io.default
[2019-09-05 11:39:36] DEBUG: [browsertime] Running with options: {
 "scripts": [],
 "iterations": 3,
 "delay": 0,
 "videoParams": {
   "addTimer": true,
   "filmstripFullSize": false,
   "createFilmstrip": true,
   "framerate": 30,
   "crf": 23,
   "filmstripQuality": 75
 },
 "statistics": true,
 "browser": "chrome",
 "connectivity": {
   "profile": "native",
   "engine": "external"
 },
 "screenshot": true,
 "screenshotParams": {
   "type": "png",
   "png": {
     "compressionLevel": 6
   },
   "jpg": {
     "quality": 80
   },
   "maxSize": 2000
 },
 "viewPort": "1366x708",
 "xvfbParams": {
   "display": 99
 },
 "spa": false,
 "pageCompleteCheckInactivity": false,
 "page-complete-check-inactivity": false,
 "video-params": {
   "add-timer": true,
   "filmstrip-full-size": false,
   "create-filmstrip": true,
   "framerate": 30,
   "crf": 23,
   "filmstrip-quality": 75
 },
 "android": false,
 "chrome": {
   "cdp": {
     "performance": true
   },
   "includeResponseBodies": "none",
   "include-response-bodies": "none"
 },
 "headless": false,
 "visualMetrics": true,
 "visual-metrics": true,
 "video": true,
 "docker": "true",
 "xvfb": "true",
 "pageCompleteWaitTime": 5000,
 "page-complete-wait-time": 5000,
 "view-port": "1366x708",
 "pageLoadStrategy": "normal",
 "page-load-strategy": "normal",
 "scriptInput": {
   "longTask": 50
 },
 "script-input": {
   "long-task": 50
 },
 "firefox": {
   "includeResponseBodies": "none",
   "include-response-bodies": "none"
 },
 "screenshot-params": {
   "type": "png",
   "png": {
     "compression-level": 6
   },
   "jpg": {
     "quality": 80
   },
   "max-size": 2000
 },
 "verbose": 1,
 "mobile": false,
 "screenshotType": "png",
 "coach": true,
 "resultDir": "/sitespeed.io/sitespeed-result/sitespeed.io/2019-09-05-11-39-35"
}
[2019-09-05 11:39:36] INFO: [browsertime] Running tests using Chrome - 3 iteration(s)
[2019-09-05 11:39:36] INFO: [browsertime.command.measure] Testing url https://sitespeed.io iteration 1
[2019-09-05 11:39:36] DEBUG: [browsertime.video] Add orange color
[2019-09-05 11:39:36] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 10M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/browsertime-SSBWtt/x11.mp4

**Hanging here a long time and finally exiting with:**

[2019-09-05 11:55:06] ERROR: [browsertime] Could not load URLTimeoutError: timeout
 (Session info: chrome=76.0.3809.87)
[2019-09-05 11:55:06] ERROR: [browsertime] UrlLoadError: Failed to load https://sitespeed.io
   at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:229:13)
   at process._tickCallback (internal/process/next_tick.js:68:7)

**Tried with:**
--proxy.https <host>:<port>
With the correct syntax this does lead to the same result as the command above in Chrome.

Using **firefox** via " -b firefox" with **--proxy.https xxx:XXXX** leads to the following:

Error: [2019-09-05 11:50:10] INFO: Browser failed to start, trying one more time: Cannot read property 'split' of undefined

with **firefox** and **--proxy.http** + **--proxy.https**:
[2019-09-05 11:51:12] INFO: Browser failed to start, trying one more time: Invalid proxy configuration entry: httpProxyPort

Thank you :)

**Comment by soulgalore** [comment]
HI @Zujiry sorry for the late answer, I missed your issue. For Firefox it looks like bug in the code let me have a look. For Chrome ... need to look more.

Best
Peter

**Comment by soulgalore** [comment]
I've fixed it in Browsertime and I can roll out a release on Sunday (I wanna squeeze in.a couple of more bug fixes during the weekend).

Best 
Peter

P.S Sorry again that I missed your issue!

**Comment by soulgalore** [comment]
This was pushed this weekend in a new release, let me know @Zujiry if you have time to test again.

Best
Peter

**Comment by Zujiry** [comment]
Hey, sorry for the late answer and thank you :)!
We just tried it out and it asks for a user and password but we are not sure how to give said things in the proxy.http syntax?

**Comment by soulgalore** [comment]
Aha, I wonder if that's doable with Selenium (that we use), I tried to search but couldn't find anything. I usually recommend running without a proxy (since the proxy could mess with the performance). Any chance you could run your tests outside of the office?

Best
Peter

**Comment by soulgalore** [comment]
The original issue is fixed but I don't think there's support for password etc in Selenium. Please have a look at https://peter.sh/experiments/chromium-command-line-switches/ for Chrome, maybe it's something there that you can use!
