### ISSUE TITLE
Cannot set cookie when using a .js script 

### ISSUE THREAD

**Issue by banuady** [sitespeedio/sitespeed.io#2624]
Hi guys,

I have an issue setting up a new cookie when I use **--cookie** parameter and a .js script. For simplicity here is an example:

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.8.1 test.js --multi --cookie name=value  -n 1 `

My test.js scripts is provided below:

`module.exports = async function(context, commands) {
    await commands.measure.start("SiteSpeed.io");
    await commands.navigate('https://www.sitespeed.io/');
    return commands.measure.stop();
}`

As a result, I am getting the following error: **Could not set cookie because the URL is unknown.** 
If I provide the full URL in the docker command, **--cookie** parameter works fine.

Regards,
Adrian

**Comment by fxbtr** [comment]
Hello, I do have the same message but the cookie is in fact correctly set.

I use a config.json file instead of the parameter, it also works in your script.js with context.options.cookie = "name=value", despite the error message in both case.

**Comment by banuady** [comment]
Hi @fxbtr ,

Thanks for your suggestions. I tried both ones but unfortunately, none of them worked for me.

Regards,
Adrian

**Comment by soulgalore** [comment]
Hi, if you use Chrome you can use CDP to set the cookie in your script. Checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#chrome-devtools-protocol and https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setCookie

Best
Peter

**Comment by banuady** [comment]
Hi Peter,

Thanks for this. I tried this and it worked:

`await commands.cdp.send('Network.setCookie',{name:'cookie_name', value:'cookie_value',domain:'my_domain'});`

regards,
Adrian
