### ISSUE TITLE
Failed to wait WebDriverError: Failed to decode response from marionette

### ISSUE THREAD

**Issue by vitorarins** [sitespeedio/sitespeed.io#2627]
Hi,

I am trying to run the example with a website and I am getting an error about webdriver.
Here is the command I am using:
```
docker run --cap-add=NET_ADMIN --rm -v "$(pwd)":/sitespeed.io -e REPLAY=true -e LATENCY=100 sitespeedio/sitespeed.io --debug -vvv -n 1 -b firefox https://www.edreams.com
```

Unfortunately I think it didn't pickup the `--debug` flag, but the log I got was this:
```
Google Chrome 76.0.3809.87 
Mozilla Firefox 68.0
Start WebPageReplay Record
[2019-09-09 14:27:35] INFO: Running tests using Firefox - 1 iteration(s)
[2019-09-09 14:27:37] INFO: Testing url https://www.edreams.com iteration 1
[2019-09-09 14:27:40] ERROR: Failed to wait WebDriverError: Failed to decode response from marionette
[2019-09-09 14:27:40] ERROR: Could not load URLUrlLoadError: Failed to wait 
[2019-09-09 14:27:40] ERROR: UrlLoadError: Failed to load https://www.edreams.com
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:229:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-09-09 14:27:40] INFO: https://www.edreams.com 0 requests, 0 bytes
Recording or accessing the URL failed, will not replay
Stopped WebPageReplay record
ERROR: exit status 1
``` 

This happened to me in other occasions as well, but intermittently (sometimes would work, sometimes not), so I think this could be a generic error, but I don't know how can I debug things like the webdriver itself.
On this website I found that it actually never works, so I believe you should be able to reproduce. 

Thank you

**Comment by soulgalore** [comment]
Hi @vitorarins ok, this looks like an upstream issue then, but I wonder if it should be reported in Geckodriver/Marionette or Selenium?

About --debug, yeah in the current released version that means "debugging the queue", not super easy to understand :) I've fixed it to the next major though. You can use `--verbose` but at the moment we don't add any logging from Geckodriver (at least before there was no way to add that).

Best
Peter

**Comment by vitorarins** [comment]
Hey @soulgalore , thank you for the quick response.
I am trying to dig deeper and find any errors on the driver itself. I already found some similar issues https://stackoverflow.com/questions/49734915/failed-to-decode-response-from-marionette-message-in-python-firefox-headless-s

If you have any tips on how to isolate the error I would appreciate.
Thanks

**Comment by soulgalore** [comment]
Hi @vitorarins sorry I don't know. What I think is needed, is Geckodriver to fix so you through Selenium could turn on Gecko/Marionett log (I don't that's doable today or at least it wasn't before).

Best
Peter

**Comment by soulgalore** [comment]
The last weeks I've seen this on our test server to, it happens but very rarely but I haven't been able to pint point what kind of content that triggers it.

**Comment by soulgalore** [comment]
There's a new Geckodriver (0.25) so I'll upgrade to that tomorrow.

**Comment by vitorarins** [comment]
Thanks for the update @soulgalore , any luck so far with the upgrade?

**Comment by soulgalore** [comment]
I've upgraded to 0.26.0 but hasn't released it yet. I'll push it today but then I wanna run it on our test server for a day or so.

**Comment by soulgalore** [comment]
I've got this every time on Travis now for one of the test. Looking for similar things, it looks like we are running out of memory see https://bugzilla.mozilla.org/show_bug.cgi?id=1245239

@vitorarins I think adding `--shm-size 2g` could fix this for you?

**Comment by vitorarins** [comment]
hey @soulgalore , sorry for the delay. 
Indeed increasing the amount of shared memory for the container helped and it works fine now. Thank you!
