### ISSUE TITLE
FFMPEG recording page indefinitely

### ISSUE THREAD

**Issue by obihill** [sitespeedio/sitespeed.io#2628]
Hey, how is it going?

I'm on Mac OS X 10.13.4. Chrome version is 76.0.3809.87. Docker version is 18.03.1-ce.

I have a problem with a sitespeed test not terminating i.e. running endlessly. I have a specific local site I'm testing that has no timed carousels or anything like that. It's just a simple webapp with a loader that waits until the content is retrieved from a remote data store before posting it to the page. There is nothing that happens on the page afterwards.

From the verbose logs it appears that FFMpeg is continuously recording the page and does not stop. Here is the last record before I terminated the test after 4 minutes [the page fully visually loads in like 15 seconds]:

```
[2019-09-10 11:16:51] TRACE: [browsertime.video] frame= 7963 fps= 29 q=0.0 size=   32256kB time=00:04:36.80 bitrate= 954.6kbits/s dup=36 drop=381 speed=   1x
    at Socket.readableStream.on.data (/usr/src/app/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:45:13)
    at Socket.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
``` 

This is the command I'm running:

```
docker run --rm -v "$(pwd)/_temp":/sitespeed.io -v "$(pwd)/_staging/_plugin/sitespeed":/sitespeed_plugins sitespeedio/sitespeed.io:9.8.1 --plugins.remove html --plugins.remove text --plugins.remove harstorer --plugins.remove tracestorer --plugins.list --plugins.add /sitespeed_plugins/resultmanager -b chrome -n 1 --test_id my_test_id --chrome.timeline -vvv http://my-app-url
```

Is there some way I can get it stop recording [perhaps after a given interval] without completely disabling visualMetrics [which I need]?

Thanks.

**Comment by soulgalore** [comment]
Hi @obihill by default the test ends + 2 after the load event end. Checkout https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test

You can choose when you want to end your test by adding the JavaScript that will decide when to end. Its all there in the link to the docs, please let me know something is unclear.

There's a bug in the current version when you run Docker that you cannot disable the video. Tomorrow I'll release a new stable version if everything works out with the test and there it is fixed. You can then disable with `--video false` and if you don't want visual metrics you can add `--visualMetrics false`

Best
Peter

**Comment by obihill** [comment]
Hi Peter,

Thanks for the response.

I tried the following:

```
docker run --rm -v "$(pwd)/_temp":/sitespeed.io -v "$(pwd)/_staging/_plugin/sitespeed":/sitespeed_plugins sitespeedio/sitespeed.io:9.8.1 --plugins.remove html --plugins.remove text --plugins.remove harstorer --plugins.remove tracestorer --plugins.list --plugins.add /sitespeed_plugins/resultmanager -b chrome -n 1 --test_id my_test_id --chrome.timeline --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.navigationStart) > 20000;} catch(e) {} return true;})()' -vvv http://my-app-url
```

However, the video recording kept running. I have to `Ctrl+C` to terminate. I'm not sure why it's not triggering to end the test. Any ideas what else I could try?

**Comment by soulgalore** [comment]
Hi @obihill hmm ok. And your test just waits then I guess? Could it be that the loadEventEnd is never fired on that page? By default the Webdriver waits until the event is fired and then gives back control (=we run the JavaScript). But you can change that with `--pageLoadStrategy none`                 

```
The Page Load Strategy decides when you have control of the page load. Default is normal meaning you will have control after onload. You can change that to none to get control direct after navigation. [choices: "normal", "none"] [default: "normal"]
```

Can you try that?

Best 
Peter

**Comment by obihill** [comment]
Hi Peter,

Sorry for the delayed response.

I created a test page with the following HTML:

```
<!DOCTYPE html>
<html>
    <head>
        <title>Main Page</title>
    </head>
    <body>
        <h1>This is a Web page!</h1>
    </body>
</html>
```

then I run the following command:

```
docker run --rm -v "$(pwd)/_temp":/sitespeed.io -v "$(pwd)/_staging/_plugin/sitespeed":/sitespeed_plugins sitespeedio/sitespeed.io:9.8.1 --plugins.remove html --plugins.remove text --plugins.remove harstorer --plugins.remove tracestorer --plugins.list --plugins.add /sitespeed_plugins/resultmanager -b chrome -n 1 --test_id my_test_id --chrome.timeline --pageLoadStrategy none --videoParams.debug  -vvv http://my-app-url/index-test.html
```

The test ends after a few seconds, but no results are generated, and no video is created.

I then run it without `--pageLoadStrategy none` and the earlier problem with the video recording not terminating persists.

When you say I should try running it without Docker, do you mean with npm?

**Comment by soulgalore** [comment]
Hi @obihill sorry for the late answer. Thanks for the example. So the HTML is deployed on a server not locally on your machine?

> When you say I should try running it without Docker, do you mean with npm?

Yes. Doing it that way it's sometimes easier to see what's going on.

Best
Peter

**Comment by soulgalore** [comment]
Did this work out for you @obihill ?

**Comment by soulgalore** [comment]
Closing since no new feedback.
