### ISSUE TITLE
sitespeed graphite disc issue

### ISSUE THREAD

**Issue by srijondas** [sitespeedio/sitespeed.io#2635]
I have stated using dockerized sitespeed/graphite extensively (more than 10 use cases automated using selenium) on Redhat linux boxes but its running out of 10G disc space quickly. I have a backup storage but I cannot use that for storage gives "could not use snapshotter btrfs " error.

Can someone outline the steps to increase disc size. If there are instructions to install graphite on Redhat that would help as well.

**Comment by soulgalore** [comment]
Hi @srijondas not exactly sure what you mean with the 10G disc?

Usually its so much easier to run Graphite in a container and mount a volume from the outside, then you get rid of all the hassle of installing Graphite.

Best
Peter

**Comment by soulgalore** [comment]
Closing since we didn't get any response.
