### ISSUE TITLE
Feature request - Kerberos Authetication

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2637]
We have few applications which uses Kerberos/sigle sign on authetication for which we need to install "Kerberos Linux Client" inside the docker container (sitespeed.io)

Package to be installed - sudo apt install krb5-user libpam-krb5 libpam-ccreds auth-client-config

Refer this link - https://help.ubuntu.com/lts/serverguide/kerberos.html

We tested in our local by passing the EXTRA_START_SCRIPT as env variable and it is working as epxected. 

Problem - We need to install this package for every docker run command and it is taking extra minutes. 

Ask - Is there a way you include those package in next release (or) any other work around?

**Comment by soulgalore** [comment]
Hi @nevesing I think easiest way for you is to wrap our container, create your own that extends our official and then installs that package. At least for now and then we can look into adding the package.

Best
Peter

**Comment by nevesing** [comment]
I am new to building own containers. Should I use the dockerfile in below link and append it with 
`RUN sudo apt install krb5-user libpam-krb5 libpam-ccreds auth-client-config`

[https://github.com/sitespeedio/sitespeed.io/blob/master/docker/Dockerfile-plus1](url)

**Comment by soulgalore** [comment]
You could do something like this: Create a new Dockerfile

```
FROM sitespeedio/sitespeed.io:10.0.0-plus1
RUN sudo apt install krb5-user libpam-krb5 libpam-ccreds auth-client-config -y
```

`docker build -t your/name .`

I think :)

**Comment by nevesing** [comment]
Thanks. I have to execute a shell script while building the image so I copied sitespeeed start.sh and appended extra lines of code in first few lines. Please see if it is okay (or) is there a way to run extra shell scripts during the build?

```
FROM sitespeedio/sitespeed.io:10.0.0
COPY start.sh /start.sh
RUN chmod +x /start.sh
RUN  apt-get install -y krb5-user
ENTRYPOINT ["/start.sh"]
VOLUME /sitespeed.io
WORKDIR /sitespeed.io
```

**Comment by soulgalore** [comment]
At build time, you need to extend the start script. If you want to add a extra script at start-up you can do it with https://www.sitespeed.io/documentation/sitespeed.io/docker/#extra-start-script

Best
Peter

**Comment by nevesing** [comment]
Yes "extra-start-script" works fine (thanks for that). I thought to move the code to my custom image build itself.

**Comment by soulgalore** [comment]
Wanna avoid making the container larger, so if this worked for you, I think we can close the issue.
