### ISSUE TITLE
Graphite: How to send 'average' time only for some metrics

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2646]
We usually execute 1 iteration only for most of the URLs that we test. So there is no need to send min, max, avg, etc.. for each metric to graphite; instead we would like to restrict only the 'average' time. Is there any configuration parameter available in the current version?

**Comment by nevesing** [comment]
I saw this option under browsertime configuration (--userTimingWhitelist) but it does not have an example so I am not sure how to use it. Is this relevant to the question I asked above?

**Comment by nevesing** [comment]
Also graphite has something called blacklist.conf which can solve this problem

**Comment by soulgalore** [comment]
Hi @nevesing sorry for the late answer. `userTimingWhitelist` is for data from the User Timing API. I think one way to solve it could be https://github.com/sitespeedio/sitespeed.io/pull/1925 or make a new PR. This isn't super high prior's for me, but if you can explain/show me more of what you will gain without, I can have a look :)

Best
Peter

**Comment by soulgalore** [comment]
Closing but please get back with a use case showing the gain and we can probably re-open.
