### ISSUE TITLE
help needed on running sitespeed on kubernetes PODs

### ISSUE THREAD

**Issue by jyoprakashJP** [sitespeedio/sitespeed.io#2647]
I am trying to run sitespeed on kubernetes, it works well with single url testing,however I am not able to pass the script to the POD at run time, any idea as how I can pass/copy the script to the POD right after container starts ?

apiVersion: v1
kind: Pod
metadata:
  name: sitespeed-pods
  labels:
    app: sitespeed
spec:
      restartPolicy: Never
      containers:
        - name: sitespeed-demo
          image: 'sitespeedio/sitespeed.io'
          args:
            - 'market.js'
            - '--multi'
            - '--v'
            - '--chrome.timeline'
            - '--visualElements'
            - '-n'
            - '1'
            - '--rm'

**Comment by soulgalore** [comment]
Checkout https://github.com/prashanth-sams/kube-sitespeedio

Best
Peter

**Comment by soulgalore** [comment]
Did that help you @jyoprakashJP ?

Best
Peter

**Comment by jyoprakashJP** [comment]
I had tried that deployment approach and that works. I was thinking like, using the Yml. Say I have 10 scripts to run every 15 min on 10 PODs, I can configures the Yml for each script, create POD, run the test, kill the POD.after 15 min repeat. Need to think how to queue the script on PODs. Not sure which approach would be better.

**Comment by soulgalore** [comment]
Ok, closing this since the original issue is fixed.
