### ISSUE TITLE
How to get full information about testing page not only index

### ISSUE THREAD

**Issue by aurelijusjaneliunas** [sitespeedio/sitespeed.io#2652]
Hello, team,

In previous versions (up to 7.7.2) of the sitespeed application was not an issue get the URL of the running test, by calling context.url or get the alias - context.alias, but from the 8.0.0+ version is not possible anymore. According documentation you only could get context.index which is not sufficient if you want to test multiple sites in the same run and you need to apply different logins to the applications. To run multiple probes is not efficient either. Please, help us to resolve this issue.

https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/

**Comment by soulgalore** [comment]
Hi @aurelijusjaneliunas when we released scripting we removed the URL from the context since now you aren't sure what the URL is until you have reached that page (clicking on a submit button etc). But you should be able to get the URL anyway can you show me a little more indeed example so I can check how it can be done?

Best
Peter

**Comment by aurelijusjaneliunas** [comment]
`module.exports = async function(context, commands) {

   const actionCenterLogin = async function(loginContext){

        const loginUrl = loginContext.loginUrl;
        const loginUser = loginContext.loginUser;
        const loginPwd = loginContext.loginPassword;
        const commands = loginContext.commands;

        await commands.navigate(
            loginUrl
        );
        // Add text into an input field y finding the field by id
        await commands.addText.byName(loginUser, 'username');
        await commands.addText.byName(loginPwd, 'password');

        // find the sumbit button and click it
        await commands.click.byIdAndWait('login-submit');

        // we wait for something on the page that verifies that we are logged in
        return commands.wait.byId('crow-avatar-caret', 20000);

    };

    const jiraLogin  = async function(loginContext){
        const driver = loginContext.driver;

        const loginUrl = loginContext.loginUrl;
        const loginUser = loginContext.loginUser;
        const loginPwd = loginContext.loginPassword;
        const commands = loginContext.commands;

        await commands.navigate(
            loginUrl
        );
        // Add text into an input field y finding the field by id
        await commands.addText.byId(loginUser, 'login-form-username');
        await commands.addText.byId(loginPwd, 'login-form-password');

        // find the sumbit button and click it
        await commands.click.byIdAndWait('login-form-submit');

        // we wait for something on the page that verifies that we are logged in
        return commands.wait.byId('header-details-user-fullname', 20000);

    };

    const confluenceLogin = async function(loginContext){

        const loginUrl = loginContext.loginUrl;
        const loginUser = loginContext.loginUser;
        const loginPwd = loginContext.loginPassword;
        const commands = loginContext.commands;

        await commands.navigate(
            loginUrl
        );
        // Add text into an input field y finding the field by id
        await commands.addText.byId(loginUser, 'os_username');
        await commands.addText.byId(loginPwd, 'os_password');

        // find the sumbit button and click it
        await commands.click.byIdAndWait('loginButton');

        // we wait for something on the page that verifies that we are logged in
        return commands.wait.byId('rw_global_menu', 20000);
    };

    const executeLogin = async function(authModule, context, commands){
        const loginUrl = authModule.login.url;
        const userName = authModule.login.user;
        const userPwd = authModule.login.password;

        const authContext = {
            "commands": commands,
            "context": context,

            "loginUrl": loginUrl,
            "loginUser": userName,
            "loginPassword": userPwd
        };

        let authResult = null;
        if (authModule.type === "jira"){
            authResult = await jiraLogin(authContext);
        } else if (authModule.type === "confluence"){
            authResult = await confluenceLogin(authContext);
        } else if (authModule.type === "actionCenter"){
            authResult = await actionCenterLogin(authContext);
        }

        return authResult;
    };

    let authModules = context.options.auth;
	
	//no more context.url
	let authModule = authApplicationToLogin(ccontext.url, context.options.auth)
	
	await executeLogin(authModule, context, commands);
	

}`

Something similar.

**Comment by soulgalore** [comment]
Hi @aurelijusjaneliunas thanks, I didn't fully get the flow :) So you run this as preScript and then to be able to know how to fix the auth, you need to know the URL that you gonna test in the next step,  does I understand the problem correct then?

Best
Peter

**Comment by aurelijusjaneliunas** [comment]
Yes, you do understand correct @soulgalore. The URL is helping what type of the auth method should be used.

**Comment by soulgalore** [comment]
Ok, is that per domain or per URL? Do you test multiple domains per setup, or do you do multiple runs (there are different solutions I think)?

**Comment by aurelijusjaneliunas** [comment]
We are testing multiple pages per domain and we have several domains in the url list we are passing to the sitespeed docker image. We would love to have single probe setup to test all the endpoints in the url list.

**Comment by aurelijusjaneliunas** [comment]
`
https://support.xxx.xxx.com/browse/PQA-3458 Issue_View
https://support.xxx.xxx.com/servicedesk/customer/portal/19 Portal
https://support.xxx.xxx.com/servicedesk/customer/portal/19/create/263 Portal_Create_Customer_Request
https://info.xxx.xxx.com Landing_Page
https://info.xxx.xxx.com/display/ANON/Secure+Development+Guidelines Secure_Development_Guidelines
https://info.xxx.xxx.com/display/ANON/GIS+Software+catalog GIS_Software_catalog
https://info.xxx.xxx.com/display/PQA/Leaving+instructions Leaving_instructions
https://info.xxx.xxx.com/display/PQA/How+to+request+access+to+eazyBI+dashboards How_to_request_access_to_eazyBI_dashboards
https://crow.xxx.xxx.com/portal/onc/non-compliant-machines Non_compliant_machines
https://crow.xxx.xxx.com/portal/onc/non-compliant-machines/61364 Machine_INSVWDLOFEST01
`

**Comment by aurelijusjaneliunas** [comment]
Pre/Post scripts are executing before running the target page to test. I would love to get that target page information (URL, alias, index) in the pre/post script.

**Comment by soulgalore** [comment]
I think this could be solved by using scripting.

**Comment by CheRuisiBesares** [comment]
I would also like to have one prescript that works for all the domains i supply in the url file. ATM I have a bash loop that pairs the url in the file list to the extra param i pass in. I would love to do something like in a prescript

```
module.exports = async function(context, commands) {
        command.navigate(context.targetURL);
        // do things with the url im about to test
};
```

**Comment by soulgalore** [comment]
@CheRuisiBesares can you share a little bit more on how you run, I didn't fully understood? Maybe there's a workaround or maybe we need to add something.

**Comment by CheRuisiBesares** [comment]
hey @soulgalore thanks for the response. I have three files in my setup. Here are some to the point versions for context:

`sites.txt` - This is just a list of URLs I want to test that look like this
```
https://a.example.com
https://b.example.com
...
```
`entrypoint.sh` - basically just for each of the sites on the list run the test and also set `--browsertime.url` to the test url.
```bash
#!/bin/bash
while read site ; do
        /start.sh \
        --browsertime.iterations 3 \
        --preScript /scripts/pre.js \
        --browsertime.url $site \
        $site
done < sites.txt
```

`pre.js` - this prescript does something for each site before the test.

```js
module.exports = async function(context, commands) {
   context.log.info("about to run test for " + context.options.url )
   doSomething(context.options.url);
};
```
I would like to lose the bash script and just pass the sites.txt file directly to the sitespeed.io endpoint. When I did that though I wasn't able to determine the url of the test that would follow the prescript invocation. To get around it I basically had to add some bash and pass a browsertime option that i could grab out of the context for each test. I would love to lose the bash if there is a way to determine the url about to be tested from the context. Let me know if that helps at all. Thanks again!

**Comment by soulgalore** [comment]
@CheRuisiBesares you can pass on your own options to your script see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#pass-your-own-options-to-your-script

So I would do like this (testMultipleUrls.js):
```js
module.exports = async function (context, commands) {
  const urls = context.options.urls;
  for (let url of urls) {
   // Do the stuff for each url that you need to do
   // Then test the URL
   await commands.measure.start(url);
   // When the test is finished, clear the browser cache
   await commands.cache.clear();
   // Navigate to a blank page so you kind of start from scratch for the next URL
   await commands.navigate('about:blank');
  }
};
```

Then you can run it with:
`sitespeed.io testMultipleUrls.js --multi --browsertime.urls https://www.sitespeed.io --browsertime.urls https://www.sitespeed.io/documentation -n 1`

If you can have your configuration as JSON it becomes cleaner:
```json
{ 
  "browsertime": {
    "urls": ["url1", "url2", "url3"]
  }
}
```

**Comment by CheRuisiBesares** [comment]
OK this works well enough for what I need. Thanks again!
