### ISSUE TITLE
Unable to run the script - No page that could be associated with the error

### ISSUE THREAD

**Issue by prateeksingh** [sitespeedio/sitespeed.io#2657]
Dear Sitespeed.io,

Greetings!

I am trying to develop script for performance testing purpose. I could write the script using sitespeed.io "commands" option. But Selenium script would be more appropriate for us. Using documentation I had just followed and written the script. It throws me this error - 
-------------------- Error -----------------
[2019-09-25 11:18:14] INFO: [browsertime] Running tests using Chrome - 1 iteration(s)
[2019-09-25 11:18:15] ERROR: [browsertime.command.measure] No page that could be associated with the error:urlOrAlias.startsWith is not a function
[2019-09-25 11:18:15] ERROR: [browsertime] TypeError: urlOrAlias.startsWith is not a function
    at Measure.start (/Users/philips/.config/yarn/global/node_modules/browsertime/lib/core/engine/command/measure.js:125:19)
    at /Users/philips/.config/yarn/global/node_modules/browsertime/lib/core/engine/run.js:9:32
    at Iteration.run (/Users/philips/.config/yarn/global/node_modules/browsertime/lib/core/engine/iteration.js:165:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Engine.runByScript (/Users/philips/.config/yarn/global/node_modules/browsertime/lib/core/engine/index.js:123:20)
    at async Object.analyzeUrl (/Users/philips/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:115:21)
    at async Object.processMessage (/Users/philips/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:127:24)
[2019-09-25 11:18:15] DEBUG: [browsertime] Closed the browser.
[2019-09-25 11:18:15] ERROR: [browsertime] No data to collect
-------------------- Error -----------------

Command to run script -  sitespeed.io  --multi --spa -n 1 -v pages/therapyReportWebDriver.js 

script - 
module.exports = {
    run(context) {
        return context.runWithDriver((driver) => {
            return driver.get("http://abc.com/#/login")
                .then(() => {

                    const webdriver = context.webdriver;
                    const until = webdriver.until;
                    const By = webdriver.By;

                    const userName = 'username';
                    const password = 'password';
                    const loginForm = webdriver.findElement(By.xpath("//button[@title=\'Login\']"));
                    webdriver.findElement(By.id('username')).sendKeys(userName);
                    webdriver.findElement(By.id('password')).sendKeys(password);
                    loginForm.click();

                    return webdriver.wait(until.elementLocated(By.id('pt-userpage')), 3000);
                });
        })
    }
};

Working on sitespeed.io version - 10.0.2

Kindly assist, where I am going wrong.

Regards,
Prateek

**Comment by soulgalore** [comment]
Hi @prateeksingh 
yes you can use Selenium script as you do but you need to add command.measure to actually measure the speed of the page (so you get some metrics). 

In your example you just use Selenium without measuring anything. See https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestart

Best
Peter

**Comment by prateeksingh** [comment]
Hi Peter, 
Thank you for quick reply. I added them, still same error. Here is the modified script - 
module.exports = {
    run(context) {
        return context.runWithDriver((driver) => {
            return driver.get('https://abc.com/')
                .then(() => {


                    const webdriver = context.webdriver;
                    const until = webdriver.until;
                    const By = webdriver.By;

                    **commands.measure.start("login time");**
                    const userName = 'username';
                    const password = 'Password';
                    const loginForm = webdriver.findElement(By.xpath("//button[@title='Login']"));
                    webdriver.findElement(By.id('username')).sendKeys(userName);
                    webdriver.findElement(By.id('password')).sendKeys(password);
                    loginForm.click();
                    **commands.measure.stop();**

                    return webdriver.wait(until.elementLocated(By.id('pt-userpage')), 3000);
                });
        })
    }
};

**Comment by soulgalore** [comment]
Hi again,
the stop command (and most commands) are async, so you need to wait for them to finish.
`await commands.measure.stop();`

There are a couple of examples of different user flows here:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#examples

Best
Peter

**Comment by prateeksingh** [comment]
Here we use js code which is developed using webdriver.js library, that would work right? like 80-90% of it.
Because I see, some things works at webdriver.js and some thing doesn't work. 

Second question - do we have log available? I couldn't find why it can not click there, or some element exections are not coming.

**Comment by soulgalore** [comment]
We use latest version of https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

Logging: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#log-from-your-script

**Comment by prateeksingh** [comment]
Hi Peter,

Thank you for your quick responses. I went through them, understanding is better. Could run the selenium code in different way. I think learning will keep happening on the way.

I am one question - Can we use multiple commands.measure.start() and stop() in single script? Because I have observed the selenium operation fails if I do multiple measures.

Script - 
_await commands.measure.start("Login time");_

        await commands.addText.byId('username','username');
        await commands.addText.byId('Password2','password');

        await commands.click.byXpathAndWait("//span[contains(text(),\"Login\")]");
        await commands.wait.byTime(2000);

        await commands.click.byXpath("//ul/li/a[contains(text(),\"Patient\")]");
        await commands.wait.byTime(2000);
        _await commands.measure.stop();_

        await commands.measure.start("Time for Search Patient");
        await commands.addText.byXpath("firstname lastname","//input[@name=\"search-term\"]");
        await commands.wait.byTime(2000);
        await commands.click.byXpath("//button[@name='search']");
        await commands.wait.byTime(2000);
        await commands.click.byXpath("//li[1]//button[1]");
        await commands.wait.byTime(2000);
        await commands.measure.stop();


In the above script, If I remove the first measure, it works fine, Ans if I add it fails in selenium operation.

**Comment by soulgalore** [comment]
>  Can we use multiple commands.measure.start() and stop() in single script? 

Yes you can as long as you navigate to a new URL or at least makes one request between them (and run with `--spa`).

I usually try these steps  https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug when I try debug a script.

Best
Peter

**Comment by prateeksingh** [comment]
Hi Peter,

I understand the reason for failure now.
In our website, the url changes in some steps and in others it doesn't. What would be best approach here?   any suggestion would be helpful.

Regards,
Prateek

**Comment by soulgalore** [comment]
Hi @prateeksingh sorry I missed to answer your question. Can you show me a use case, like step by step when it change or not on a high level, then it's easier for me to understand!

Thanks
Peter

**Comment by soulgalore** [comment]
Closing, but if you get back with a use case I can re-open!

Best
Peter
