### ISSUE TITLE
Multiple Request Parameters - Unclear Documentation, Possible Bug

### ISSUE THREAD

**Issue by juca2** [sitespeedio/sitespeed.io#2658]
The test case is the following: adding multiple request headers to a sitespeed run.

First of all, documentation around `--browsertime.requestheader, -r, --requestheader` is unclear:

> ...Add multiple instances to add multiple request headers. Use the following format key:value....

Multiple instances of what? is it `-r key1:value1 -r key2:value2` or `-r ''key1:value1, key2:value2"` or is it something else altogether?
There should be a concrete example showing how multiple key:value pairs are to be provided to the CLI.

Secondly, none of the following combinations worked for me, the results were a mix of a single misformed request header like `key:value1, value2` or the error message:
`ERROR: Request headers need to be of the format key:value not key1:value1,key2:value2`

Attempting to use the attached config file containing `"requestheader": 
 ["key1:value1","key2:value2"]` also produced the same results, i.e. only the first header included and misformed

Version info for all test cases
**OS:** Docker 2.1.03(38240) running on Windows 10 v1903
**Sitespeed Version:** latest (10.0.3) and 10.0.2
**Browsertime Version:** 6.0.4

**Cases and Reproduction steps:** 

**Case 1 (Multiple Headers)** **FAIL**
1. Open PowerShell
2. Run `docker run --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io -r key1:value1 -r key2:value2 https://sitespeed.io`
**Expected:** Both request headers added to the requests sent by sitespeed, no errors reported.
**Actual:** `ERROR: Request headers need to be of the format key:value not key1:value1,key2:value2` and none of the request headers added to the requests. See attached [case1-browsertime.har.txt](https://github.com/sitespeedio/sitespeed.io/files/3651074/case1-browsertime.har.txt).

**Case 2 (Multiple Headers)** **FAIL**
1. Open PowerShell
2. Run `docker run --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io  --config config.json https://sitespeed.io`
using the config file here 
[config.json.txt](https://github.com/sitespeedio/sitespeed.io/files/3651120/config.json.txt)
**Expected:** Both request headers added to the requests sent by sitespeed, no errors reported.
**Actual:** `ERROR: Request headers need to be of the format key:value not key1:value1,key2:value2` and none of the request headers added to the requests. See attached 
[case2-browsertime.har.txt](https://github.com/sitespeedio/sitespeed.io/files/3651108/case2-browsertime.har.txt)

**Case 3 (Multiple Headers)** **FAIL**
1. Open PowerShell
2. Run `docker run --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io  -r key1:value1,key2:value2 https://sitespeed.io`
**Expected:** Both request headers added to the requests sent by sitespeed.
**Actual:** Only one header added to the requests sent by sitespeed, as `key1:value1,key2`
See attached 
[case3-browsertime.har.txt](https://github.com/sitespeedio/sitespeed.io/files/3651177/case3-browsertime.har.txt)

**Case 4 (Single Header)** **PASS**
1. Open PowerShell
2. Run `docker run --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io -r key1:value1 https://sitespeed.io`
Result is as expected, the header is included in the requests
[case4-browsertime.har.txt](https://github.com/sitespeedio/sitespeed.io/files/3651154/case4-browsertime.har.txt)

**Note:** In my troubleshooting I ran a multitude of other combinations like `key1:value1::key2:value2`,`-r 'key1':'value1' -r 'key2':'value2'` etc. None of the combinations seem to work or even accepted, which leads me to believe there is a defect in Browsertime or Sitespeed

**Comment by soulgalore** [comment]
This looks like a bug, you should be able to just add multiple headers with **-r** , let me see if I can fix it.

Best
Peter

**Comment by soulgalore** [comment]
FYI it works in Firefox ... I'll do the release later today with the fix! I will also add one extra example in the documentation.

**Comment by juca2** [comment]
Wow thanks for the very quick turnaround!

**Comment by soulgalore** [comment]
I've pushed 10.1.0 just now, please let me know how it works out for you.

**Comment by juca2** [comment]
Multiple request headers working fine in 10.1.0 with chrome browser, both via CLI and config file. Thanks a lot once again!
