### ISSUE TITLE
BasicAuth settings for graphite not respected

### ISSUE THREAD

**Issue by stawek** [sitespeedio/sitespeed.io#2662]
Documentation here https://hub.docker.com/r/sitespeedio/graphite and here https://github.com/sitespeedio/dashboard.sitespeed.io/tree/master/config suggests that Graphite can be secured by basic auth

However I noticed that it doesn't work properly, despite providing .htpasswd file 

For example it is possible to send arbitrary data to your graphite instance: 

https://dashboard.sitespeed.io/d/000000043/page-summary?orgId=1&var-base=sitespeed_io&var-path=basicAuthTest&var-group=hub_docker_com&var-page=_r_graphiteapp_graphite-statsd_&var-browser=chrome&var-connectivity=native&var-function=median&from=now-6h&to=now

https://i.imgur.com/5eLT1F7.png

In other part of documentation you are mentioning UFW  - however simply setting ufw and then using docker can be misleading - see https://blog.viktorpetersson.com/2014/11/03/the-dangers-of-ufw-docker.html

**Comment by soulgalore** [comment]
Yeah thanks for reminding me. The basic was for the HTTP admin for Graphite, but I guess maybe that stopped working when we switched container.

If you wanna limit traffic you need to use firewall or if you run AWS you can use security groups. I'm gonna write some examples when I write the docs for setting up Graphite on AWS.

**Comment by soulgalore** [comment]
I added a how to section in the docs: https://www.sitespeed.io/documentation/sitespeed.io/graphite/#secure-your-instance

Best
Peter
