### ISSUE TITLE
Cannot specify "resultBaseURL" as an environment variable

### ISSUE THREAD

**Issue by MasonM** [sitespeedio/sitespeed.io#2663]
It's impossible to specify the `--resultBaseURL` option as an environment variable because yargs always camel-cases env variables, turning it into `resultBaseUrl`. This behavior isn't documented AFAIK, but here's the code: https://github.com/yargs/yargs-parser/blob/051601951c458e1294270c6baca79b4aff32f8b6/index.js#L583-L588

Reproduction code:
```
SITESPEED_IO_resultBaseURL='http://localhost' ./bin/sitespeed.js -n1 https://example.com 2>&1 | grep -i 'Find the result at'
```

Expected output:
```
[2019-09-30 09:51:56] INFO: [sitespeedio] Find the result at http://localhost/example.com/2019-09-30-09-51-47
```

Actual output: nothing

**Comment by soulgalore** [comment]
Hi @MasonM aha ok. Is it possible for you to do a PR? One hack to test is to add another alias for that cli param as _resultBaseUrl_?

Best
Peter

**Comment by soulgalore** [comment]
Had some time tonight so I made the PR. I'm gonna make a new fix release tomorrow.

**Comment by soulgalore** [comment]
Released a fix earlier today, let me know if it works for you @MasonM

**Comment by MasonM** [comment]
It works! Thank you!
