### ISSUE TITLE
Influx Template(s)

### ISSUE THREAD

**Issue by jholsgrove** [sitespeedio/sitespeed.io#2672]
Hi, 

I recently posed a query to @soulgalore about whether there were plans to create some more [Influx templates](https://github.com/sitespeedio/grafana-bootstrap-docker/tree/master/dashboards/influxdb) for Grafana, much like the Graphite ones listed [here](https://github.com/sitespeedio/grafana-bootstrap-docker/tree/master/dashboards/graphite).

It was mentioned that the current Influx one perhaps required some updating. So this issue is to discuss that.

I currently send metrics to Influx to graph using the Influx template linked above. Details of what I'm doing to achieve that are as follows:

- `docker run --shm-size=1g --network=cable --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io login.js --multi -d 3 -b chrome https://urlToTest.com --influxdb.host xxx.xxx.xxx.xxx --influxdb.port 8086 --expose 8086 -c cable --budget.configPath myBudget.json --budget.output json --slack.hookUrl https://hooks.slack.com/services/blablabla --axe.enable`
- Sitespeed version `10.1.0`
- Running on Windows Server 2019 using Docker.

Happy to be a guinea pig for any amendments, adjustments or ideas people might have.

**Comment by soulgalore** [comment]
HI @jholsgrove yeah it's time to give InfluxDB some love. I'm in the making of redoing the main dashboard for Graphite for 10.2 and let me redo the InfluxDB one too, following the same structure/pattern. It will also be good for me so I can keep track if there are metrics missing. I'll ping this issue in a couple of days when I have something for you to try out.

Best
Peter

**Comment by soulgalore** [comment]
Hi @jholsgrove you can try out https://github.com/sitespeedio/grafana-bootstrap-docker/blob/10.2.0/dashboards/influxdb/pageSummary.json  ... it isn't finished but at least better than before. Need to publish a new release though to get the Long Tasks to work (we where missing a tag).

**Comment by soulgalore** [comment]
Hi @jholsgrove 

> What is the difference between the two DOM elements panels? I h

Think this was a miss by me.

> User Timings is empty.

I've removed them for now, the current structure for user timings is not the best for Influx, you need to create it yourself.

I've updated the default ones now with the new 10.2.0 release.

Best
Peter

**Comment by jholsgrove** [comment]
Awesome, many thanks for your efforts as always @soulgalore.
