### ISSUE TITLE
Metrics on per-iteration basis

### ISSUE THREAD

**Issue by kevinlacotaco** [sitespeedio/sitespeed.io#2673]
We are using the sitespeed + statsd interface with multiple iterations. This provides us aggregated metrics. When piping this to datadog this means every aggregate is its own metric. Datadog then also provides aggregates based on the metrics provided. 

Is it possible to get the metrics fired to graphite/statsd interface on a per-iteration basis without the aggregates. I was looking at how all the messages were passed and was wondering if it existed.

- Using docker-compose (no additional plugins besides the ones provided) with 4 URLs under test and 10 iterations per. We also upload to S3 the html reports (which the aggregates are necessary for). 
- Version: 10.0.1 (I see 10.1.1 is out)
- OS: Docker provided image, Base OS is MacOS (locally)

It looks like there is a method to the iteration messages because I turned on the 'analysisstorer' plugin to checkout the provided JSONs results and found one for each iteration. 

Example metrics:

```
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.mean:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.mdev:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.stddev:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.min:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.p10:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.p90:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.p99:<number>|ms|
<namespace>.pageSummary.<page-alias>.chrome.native.browsertime.statistics.timings.loadEventEnd.max:<number>|ms|
```

Each one goes to DataDog and then provides a `max`, `min`, `median`. So you will have a 

```
<namespace>.pageSummary.<page-alias>.<metric>.max.max
<namespace>.pageSummary.<page-alias>.<metric>.max.95percentile
<namespace>.pageSummary.<page-alias>.<metric>.max.median
<namespace>.pageSummary.<page-alias>.<metric>.max.avg
```

**Comment by soulgalore** [comment]
Sorry I missed the issue. Thanks for the PR it look cool, lets just add some extra documentation for it and we can push it in the next release.

**Comment by kevinlacotaco** [comment]
@soulgalore Do we want to close this now? I have a couple questions and can file additional issues if you want. 

The iterations are working but I noticed the userTimings marks and measures are just numbers instead of names. Are those only mapped during summaries?

**Comment by soulgalore** [comment]
Yes let us close this and make follow up issues.

If I remember correctly the user timing API use key/value as field, so we need to massage the data to get a better structure for Graphite and I guess then that is only done for summaries. Best way to check that is to look at the browsertime.json (if you run Browsertime standalone) where each iteration is stored. But I could be wrong so need to have a look.

**Comment by kevinlacotaco** [comment]
I will take a look at that!
