### ISSUE TITLE
statsHelpers are not handling floating point stats correctly

### ISSUE THREAD

**Issue by tengremlin** [sitespeedio/sitespeed.io#2674]
Hi,
`summarizeStats` in [statsHelpers](https://github.com/sitespeedio/sitespeed.io/blob/3a956e2368d6eb95ee74ef03ffe12170a8a5a0e6/lib/support/statsHelpers.js#L46) are accepting `options` where you can define `decimals` for your stats, but then whole result is parsed to Int making it redundant.

Moreover if anybody would like to use it to summarise any float values, it will be rounded to nearest integer. It is especially a problem in such metrics as Lighthouse category scores, where all values are in range from `0.00` to `1.00`.

**Comment by soulgalore** [comment]
Thank you for the PR, this was just released in 10.2.0

**Comment by soulgalore** [comment]
Release your PR, thanks!
