### ISSUE TITLE
disk cache hit is not recorded but omitted in the HAR file

### ISSUE THREAD

**Issue by gogo9th** [sitespeedio/sitespeed.io#2683]
Hi,

I asked this question int the browsertime Github but got no answers, so I am asking here in case somebody could give me a good hint... 

I am building an efficient web proxy and I need to record how many URLs are hit from the disk or memory cache from inside the browser. However, browsertime seems to omit those URLs that are disk/memory-hit. I wonder if you could change the HAR file format to include the disk/memory hit URLs as well...

Thanks a lot for your help.

**Comment by soulgalore** [comment]
Hi @gogo9th sorry I missed your question before, I've updated that now so closing this and we can keep the discussion in the original issue: https://github.com/sitespeedio/browsertime/issues/947

Best
Peter

Sorry again that I missed  your question!
