### ISSUE TITLE
TSProxy Not Working Since 10.0.2

### ISSUE THREAD

**Issue by gfoxCartrawler** [sitespeedio/sitespeed.io#2686]
Test freezes on video recording when using TSProxy after version 10.0.2. Before tests worked fine with TSProxy running

- Exact how you run (the exact parameters)
`docker run --rm -v "$(pwd)":/sitespeed.io  sitespeedio/sitespeed.io:10.1.1 --outputFolder odigeo_run_default  flash/selenium/edreams-steps/scenario.js --config flash/config.json --multi --debug`

config.json
```
{
  
  "utc": true,
  "gzipHAR": true,
  "html": {
    "fetchHARFiles": true,
    "showScript": true
  },
  "screenshot": {
    "type": "jpg"
  },
  "browsertime": {
    "iterations": 3,
    "browser": "chrome",
    "pageCompleteWaitTime": 15000,
    "connectivity": {
      "engine": "tsproxy",
      "profile": "custom",
      "alias": "15mbps_throttle",
      "downstreamKbps": 15000,
      "upstreamKbps": 400,
      "latency": 4
    },
    "chrome": {
      "args": ["--proxy-server=\"socks://localhost:1080\""]
    }
  }
}
```

- Which version you are using
**10.0.3 -> 10.1.1** 

- OS (if you use Docker, report the base OS)
**Mac OS and also Linux in Kubernetes Cluster**

When enabling debug I noticed in the logs that there was a slightly different configuration set between the version **10.0.2** which worked and **10.0.3** and above

10.0.2 has the following setting added to the options

```
connectivity": [
    "custom",
    {
      "engine": "external"
    }
  ]
```

10.0.3 has the following setting added

```
"connectivity": {
    "engine": "tsproxy"
  },
```
There was a commit added to 10.0.3 around connectivity which I'm not sure if it has something to do with the issue we are facing
https://github.com/sitespeedio/sitespeed.io/commit/78e28df70a54255f98352d9b2cc571e23a0b93f7

Any help would be greatly appreciated.

**Comment by soulgalore** [comment]
Hi @gfoxCartrawler thanks for the report, we have updated TSProxy versions [between the releases](https://github.com/sitespeedio/sitespeed.io/blob/master/CHANGELOG.md#fixed-2) and when I try to rollback to the version before, it works for me. I can push that version but then we will miss out on the fix https://github.com/WPO-Foundation/tsproxy/issues/20. Let me have a closer look later today and see if I understands what is going on.

Best
Peter

**Comment by soulgalore** [comment]
I've just released 10.2.0 where I stepped back on commit in TSProxy. Please verify that it works for you, I'll create an upstream issue.

**Comment by gfoxCartrawler** [comment]
Hi Peter,

Thank you for the quick responses.
Can confirm that 10.2.0 works for me on both Mac and Linux in a Kubernetes cluster.

Thanks,
Gary

**Comment by soulgalore** [comment]
Great!
