### ISSUE TITLE
Per Iteration User Measures and Mark Names instead of numbers

### ISSUE THREAD

**Issue by kevinlacotaco** [sitespeedio/sitespeed.io#2693]
Using the experimental per iteration flag with the statsd interface the user measures and marks, long task names they remain indexed numbers example: `chrome.native.browsertime.pageinfo.longTask.10.startTime`, `browsertime.coach.coachAdvice.advice.timings.userTimings.measures.27.duration`. In the summary and pageSummary views they get named to their user defined named. 

To reproduce, running a url with the experimental per iteration flag on a site that has user timings. 

1. Using docker-compose (no additional plugins besides the ones provided) with 4 URLs under test and 10 iterations per. We also upload to S3 the html reports (which the aggregates are necessary for).
1. Version: 10.2.0
1. Docker - on MacOS
1. Docker container version (Chrome 77.0.3865.75)

Related to issue https://github.com/sitespeedio/sitespeed.io/issues/2673

**Comment by kevinlacotaco** [comment]
Looked into a little bit of the massaging for the names for measures/marks. How early do we want to potentially massage it for the run message?

**Comment by soulgalore** [comment]
Today we do it in Browsertime for the pageSummary metrics here: https://github.com/sitespeedio/browsertime/blob/master/lib/core/engine/collector.js#L129-L138

But I think avoiding changing the format in Browsertime is good, so it should be done somewhere in sitespeed.io, preferable late :) But not sure where right now.

**Comment by kevinlacotaco** [comment]
Sounds great, I will keep thinking where would have the lowest impact on anything using the data as is.

**Comment by kevinlacotaco** [comment]
I did notice in the graphite index there are some manipulation of the data for webpagetest (https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/graphite/index.js#L96). Would this be a decent location to manipulate the marks, measures, long tasks, etc? Or does that not make sense.
