### ISSUE TITLE
While running multiple scripts I use the following command - sitespeed.io script1 script2 script3 --multi    The scripts run as expected however, the report shows result for the last script (script3) only whereas I have used the measure commands in both script 2 and script 3. How can I see results for all scripts for which I have configured measure commands ? 

### ISSUE THREAD

**Issue by Subihit** [sitespeedio/sitespeed.io#2699]

**Comment by soulgalore** [comment]
Hi @Subihit sorry I missed this.

I didn't fully understand, let me check: you run three files, each of them are using measure. But in the HTML you can only see the result of the last file and not from the two other files, is that correct?

Best
Peter

**Comment by soulgalore** [comment]
Closing since we didn't got more info. Please let me know if we should re-open.
