### ISSUE TITLE
Slack site summary urls with s3 not directing to index.html

### ISSUE THREAD

**Issue by kevinlacotaco** [sitespeedio/sitespeed.io#2705]
- Using docker-compose
- Version: 10.2.0 (looking to update soon)
- OS: docker container, base OS: OSX (locally)
- Browser version: included from docker container

Slack configuration: `summary`

Using the slack configuration to get stats on our runs with s3 hooked up at a base url for summary does not include index.html. Adding `/index.html` properly loads the page.

Also, visible in the sitespeed.io slack channel: `Site summary (result)` -> points to an s3 bucket without `/index.html`

Page results do not have this issue.

**Comment by kevinlacotaco** [comment]
Could be right here: https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/slack/summary.js#L72

**Comment by soulgalore** [comment]
This was fixed and released some time ago!
