### ISSUE TITLE
axe-core version???

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2717]
Which one is sitespeed.io using

![image](https://user-images.githubusercontent.com/7537289/67426205-99c9e600-f5a7-11e9-8e21-d64ae841f29c.png)

**Comment by soulgalore** [comment]
You can see that in the package.json file:
https://github.com/sitespeedio/sitespeed.io/blob/master/package.json#L76

3.3.1

**Comment by softwareklinic** [comment]
Any plans to upgrade to 3.4.0

<http://www.verizon.com>

Keyur Shah

Associate Fellow - Sys Engrg
2147845203

"Defects & waste slow down the progress" - Identify, measure and eliminate.

**Comment by soulgalore** [comment]
released in 11.0.0
