### ISSUE TITLE
Add display name to friendly names

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2722]
In the budget and the pages page where we use https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/friendlynames.js we could be nicer to the user and display a better name for the metric that is used. I think we could add an extra field to each entry that will be displayed.

**Comment by thapasya-m** [comment]
> we could be nicer to the user and display a better name for the metric

@soulgalore  from our earlier discussion around the same, do mean we can have 
`pagexray: {
    requests: {
      total: 'requests',`
to 
`pagexray: {
    requests: {
      total: { key: 'requests', friendlyName: 'Requests'},`
?

**Comment by soulgalore** [comment]
yeah something like that I @thapasya-m or is there a better way, haven't thought so much about it.

**Comment by soulgalore** [comment]
This was released in 11.0.0
