### ISSUE TITLE
Configuration setting for html results namespace/directory

### ISSUE THREAD

**Issue by stawip** [sitespeedio/sitespeed.io#2732]
Hello, 

I noticed that sometimes test results are placed within namespace/directory which isn't related to domain which was used for actual performance test run.

What is logic behind this behavior? How to configure it or be able to predict where test results will be placed?

Here is an example to illustrate my question:

https://dashboard.sitespeed.io/d/000000059/page-timing-metrics?orgId=1&var-base=sitespeed_io&var-path=alexaDesktop&var-group=en_wikipedia_org&var-page=_wiki_Barack_Obama&var-browser=chrome&var-connectivity=cable&var-function=median&from=1572078924937&to=1572256100389

![image](https://user-images.githubusercontent.com/173826/67765516-9ec9e200-fa4c-11e9-9da1-8403f1f2b460.png)

And then results url looks like this:
![image](https://user-images.githubusercontent.com/173826/67765581-c91b9f80-fa4c-11e9-862a-59ab4d6ec2e4.png)

https://s3.amazonaws.com/results.sitespeed.io/www.google.com/2019-10-28-04-11-33/pages/en.wikipedia.org/wiki/Barack_Obama/index.html

Why wikipedia test run is placed under google.com namespace?

**Comment by soulgalore** [comment]
Hi @stawek the first URL that you test is used by default as the path to the tests. So if you run multiple domains within one test as in https://github.com/sitespeedio/dashboard.sitespeed.io/blob/master/tests/nyc3-1/desktop/urls/alexaDesktop.txt they will live in the HTML under that URL. In Graphite/Grafana they will be under the right domain.

Best
Peter

**Comment by stawek** [comment]
@soulgalore 
Thank you for explanation

> the first URL that you test is used **by default** as the path to the test
Since you not mentioned it in your response I suppose that at this moment it isn't possible to change this default behavior?

**Comment by softwareklinic** [comment]
In the CRON i've configured something like below - to get a different name based on date/time stamp --- not sure if this is what u are  looking for --- but i do need a different folder name than the FILE name of the domain name... and this is how its achieved in my case

 --outputFolder sitespeed-result/Comparison/$(date +\%Y-\%m-\%d-\%H-\%M-\%S)

**Comment by soulgalore** [comment]
@stawek did you got the help you needed?

**Comment by soulgalore** [comment]
Closing since no more feedback.
