### ISSUE TITLE
Chrome Details vs Sitespeed details for AXECORE

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2734]
Sitespeed just shows that we have certain violations/warnings/errors etc... (count)

AXECORE output in GOOGLE CHROME plugin

![image](https://user-images.githubusercontent.com/7537289/67798889-bc05ad00-fa5a-11e9-8834-e36f01bfc4bb.png)

SITESPEED OUTPUT

![image](https://user-images.githubusercontent.com/7537289/67798983-ebb4b500-fa5a-11e9-8642-7ac9514e8cb8.png)

**Comment by soulgalore** [comment]
Hi @softwareklinic if you check axe for a specific run (not the summary page) you will see all the violations and recommendations. Is that what you are looking for?

Best
Peter

**Comment by softwareklinic** [comment]
Yes which I did

But what I’m seeing is that the axe core chrome plugin reports way more
violations compared to sitespeed for same page


Regards
Keyur

On Oct 29, 2019, at 4:07 PM, Peter Hedenskog <notifications@github.com>
wrote:

﻿

Hi @softwareklinic
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_softwareklinic&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=8vgMkZhf7zd0iYIcLNw5PUTQPZ9MrJLmtwdjqzfKtbQ&s=Ebt4SrzGELMVyLOu_EPskZ_uG4bUhSE5Q2j94BqeTRQ&e=>
if you check axe for a specific run (not the summary page) you will see all
the violations and recommendations. Is that what you are looking for?

Best
Peter

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2734-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABZQFCIPUHM4AHGJLOAO463QRCQ2TA5CNFSM4JGNXIY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECSCW3A-23issuecomment-2D547629932&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=8vgMkZhf7zd0iYIcLNw5PUTQPZ9MrJLmtwdjqzfKtbQ&s=0dUZ0ybLXvgQrl3jEhDpYjmoGqNUIY37D7Sc_um09vE&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABZQFCNU4PUCVPAZDDCNAG3QRCQ2TANCNFSM4JGNXIYQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=8vgMkZhf7zd0iYIcLNw5PUTQPZ9MrJLmtwdjqzfKtbQ&s=c7Oc-McCpDaSf6b2cDYN6jpMGDdqgEki6vTW_R1ySf4&e=>
.

**Comment by soulgalore** [comment]
We run default settings, but you can change that through the command line. I haven't checked what the Chrome plugin uses as default.

**Comment by softwareklinic** [comment]
I dont see in documentation on how to change the settings... Any suggestions on how do I specify axe-core settings from command line?

**Comment by soulgalore** [comment]
Yeah it isn't super clear we should work on that docs: 
https://www.sitespeed.io/documentation/sitespeed.io/axe/#configure-axe and then https://github.com/dequelabs/axe-core/blob/master/doc/API.md#api-name-axeconfigure

If you come out with an working example that would be great!

Best
Peter

**Comment by softwareklinic** [comment]
Thank you - working on the example(S)

**Comment by softwareklinic** [comment]
Peter - I take it back --- I was able to compare the axe-core chrome extension results with what sitespeed is reporting --- its exactly the same... just a different style of presentation.

One particular thing I would probably still call out is chrome extension also reports a section called "needs review" --- which are ideally not violations but something it reports --- which has a bigger count of it... is this something we can probably return in sitespeed using the CONFIG/axe.check... I will try it out and let u know or if u have a mean let me know.
