### ISSUE TITLE
Not sending WPT Lighthouse metrics to Graphite

### ISSUE THREAD

**Issue by delambo** [sitespeedio/sitespeed.io#2737]
Hi! I'm not sure if this is a bug or if I'm not configuring ssio correctly, but here it goes:

I'm running ssio against a private WPT instance and sending the results to a graphite instance. My problem is that the WPT lighthouse metrics are not getting sent to graphite. I configured ssio with the `lighthouse` parameter and I have verified that WPT is running the lighthouse tests and that WPT is returning the lighthouse results to ssio. However, there are no lighthouse metrics in the data that gets sent to Graphite.

- OS: `Debian GNU/Linux 9 (stretch)`
- Docker image: `sitespeedio/sitespeed.io:10.3.2`
- Command: `docker run --add-host=blah.net:blah --shm-size=1g --rm -i -w /sitespeed.io -v /tmp/tmp.Gc3dXayJ1U:/sitespeed.io -v /ssio-runs/:/ssio-runs sitespeedio/sitespeed.io:10.3.2 /ssio-runs/budget/nytimes-story.urls.txt --config /ssio-runs/budget/nytimes-story.config.json --webpagetest.file /ssio-runs/budget/nytimes-story.wpt.txt --webpagetest.key BLAHBLAHBLAHBLAH --webpagetest.label budget.nytimes-story -vvv --graphite.namespace sitespeed_io.budget.nytimes-story`

Contents of `/ssio-runs/budget/nytimes-story.config.json`:
```
{
  "graphite": {
    "host": "...",
    "arrayTags": true
  },
  "webpagetest": {
    "host": "...",
    "location": "us-east-1-linux",
    "runs": 1,
    "connectivity": "custom",
    "bwdown": 29000,
    "bwup": 10000,
    "latency": 4,
    "private": false,
    "timeline": true,
    "keepua": true,
    "includeRepeatView": true,
    "lighthouse": true
  },
  "plugins": {
    "list": true,
    "remove": ["browsertime", "html"]
  },
  "utc": true
}
```

If needed, I can share the verbose output - it's 10,000+ lines of code 😬. Is there some configuration that I'm missing or is it even possible to send the WPT lighthouse results to graphite?

**Comment by soulgalore** [comment]
Hi @delambo thanks for creating the issue. We have a couple of metrics that we cherry picked that are sent to Graphite, that's because the size on disk can heavily increase per metrics (you can configure how often you collect the metric and how long time you will store it and then than amount will be added per metric). So that's why we only send some metrics by default.

But you can configure which metrics to send to Graphite using a filter. It isn't super clean but I think could use it with the Lighthouse data, checkout https://www.sitespeed.io/documentation/sitespeed.io/metrics/#configurefilter-metrics

Hope that helps!
Best
Peter

**Comment by delambo** [comment]
Hi, Peter!

Thanks for the help, and a very warm thank you for the library. We've been using it at the New York Times for a couple of years 💖

I followed your advice and configured a filter, and it's working!

For anyone that stumbles onto this issue, I added the following json configuration (note, there are a lot more lighthouse metrics that you could filter):

```
  "metrics": {
    "filter": [
      "webpagetest.pageSummary.data.lighthouse.categories.performance.score",
      "webpagetest.pageSummary.data.lighthouse.categories.accessibility.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-allowed-attr.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-required-attr.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-required-children.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-required-parent.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-roles.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-valid-attr-value.score",
      "webpagetest.pageSummary.data.lighthouse.audits.aria-valid-attr.score",
      "webpagetest.pageSummary.data.lighthouse.audits.errors-in-console.score",
      "webpagetest.pageSummary.data.lighthouse.audits.errors-in-console.numericValue"
    ]
  }
```
