### ISSUE TITLE
Feature request - AXE

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2738]
Can we add the AXE violation count in this table for all URL runs, and also are these violation counts reported to graphite??

![image](https://user-images.githubusercontent.com/7537289/67981847-e17bed80-fbf7-11e9-8ea1-03b8846ac4ef.png)

**Comment by soulgalore** [comment]
Hi @softwareklinic the metrics are sent to Graphite and from the latest release you can choose to have violations in table, checkout https://www.sitespeed.io/documentation/sitespeed.io/configure-html/#configure-page-metrics

Best
Peter

**Comment by soulgalore** [comment]
Closing. Let me know if you need anything else!

**Comment by softwareklinic** [comment]
Ty that’s awesome


Regards
Keyur

On Nov 9, 2019, at 3:22 PM, Peter Hedenskog <notifications@github.com>
wrote:

﻿

Hi @softwareklinic
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_softwareklinic&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=ikXs51awJWPqAbtkMKUCGJ07YEbxTILgaySZTJjDR9U&s=wdhW-2_baBRyx14N_xklqzlLN0KNTqZePVxDBndZs08&e=>
the metrics are sent to Graphite and from the latest release you can choose
to have violations in table, checkout
https://www.sitespeed.io/documentation/sitespeed.io/configure-html/#configure-page-metrics
<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.sitespeed.io_documentation_sitespeed.io_configure-2Dhtml_-23configure-2Dpage-2Dmetrics&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=ikXs51awJWPqAbtkMKUCGJ07YEbxTILgaySZTJjDR9U&s=fpQJk53U-3p36ePG8HVDwgAcvW-PfLn30_EhO7Okt8g&e=>

Best
Peter

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sitespeedio_sitespeed.io_issues_2738-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABZQFCOHAAIKB2RIX6YQLKTQS4SZRA5CNFSM4JHRXG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDUPR2Y-23issuecomment-2D552138987&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=ikXs51awJWPqAbtkMKUCGJ07YEbxTILgaySZTJjDR9U&s=uQVNpmqk3hQ_f4wqmPSxFaMHTt3pi14shdjfgNGZcrE&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABZQFCKIXYQB27MCBB7BC7LQS4SZRANCNFSM4JHRXG3Q&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=ikXs51awJWPqAbtkMKUCGJ07YEbxTILgaySZTJjDR9U&s=WRq4nyG7eOWymnIK6_il0TRhWjEK9C5YJXngf_XwMaw&e=>
.
