### ISSUE TITLE
crawler include

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2748]
currently crawler has `--crawler.exclude`, it would be handy to crawl URL that contain something, eg `--crawler.include`

**Comment by soulgalore** [comment]
Hi @Matti yeah that should be doable, any chance you have time to do a PR? I can help guide you  through it.

Best
Peter

**Comment by matti** [comment]
Sure, can you give me a pointer where of the line/file where it should be done (lazy hehe)

**Comment by soulgalore** [comment]
This is the exclude:
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/crawler/index.js#L46-L57

I think adding it easy, testing it is more work :)

**Comment by soulgalore** [comment]
For CLI parameters, everything is automatically pushed on to the plugin. So for example the plugin name is crawler. `--crawler.test` `--crawler.test2`  `--crawler.test3` will then automatically be in the options object (without adding anything). But then if you want any verification or the option to be seen in the help, you need add the option in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli/cli.js

I should add this in the docs.
