### ISSUE TITLE
grafana annotations do not appear

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2750]
I have configured
```
--grafana.host
--grafana.port
--grafana.auth
```
and according to `-vvvv` logs grafana annotations are being sent, but not visible in grafana. how could I debug further?

Found #1826 but that didn't help.

**Comment by soulgalore** [comment]
Hi @matti have you set the resultBaseURL? It's maybe not obvious in the docs, but the annotations are only sent if you setup a result URL (that is used for the screenshot and the link to the result).

Best
Peter

**Comment by matti** [comment]
Yes I have that set and in the verbose logs I can see that the annotations are being sent.

**Comment by soulgalore** [comment]
@Matti  if you test sending an annotation using curl using the same auth, does that work? https://frederic-hemberger.de/articles/annotate-grafana-dashboards-with-deployments/

**Comment by matti** [comment]
good tip, I'll try that - however, if that works then it means that sitespeed has a bug since output says it's succesful

**Comment by matti** [comment]
so first a dummy test with wrong grafana api key:
```
WARN: No valid authentication. Got 401 from Grafana when sending annotation
ERROR: Error: Got 401 from Grafana when sending annotation
at ClientRequest.lib.request.res (/usr/src/app/lib/plugins/grafana/send-annotation.js:100:21)
```
then I create grafana admin api key and test it with:
```
$ curl -H "Authorization: Bearer eyJrIjoidzNoSUZxeGQwSGZFNTEzcFhaajRDa09pam5IcUNtVlkiLCJuIjoiYWFhIiwiaWQiOjF9" http://localhost:3000/api/dashboards/home
{"meta":{"isHome":true,"canSave":false,"canEdit":true,"canAdmin":false,"canStar":false,"slug":"","url":"","expires":"0001-01-01T00:00:00Z","created":"0001-01-01T00:00:00Z","updated":"0001-01-01T00:00:00Z","updatedBy":"","createdBy":"","version":0,"hasAcl":false,"isFolder":false,"folderId":0,"folderTitle":"General","folderUrl":"","provisioned":false,"provisionedExternalId":""},"dashboard":{"annotations":{"list":[]},"editable":true,"folderId":null,"gnetId":null,"graphTooltip":0,"hideControls":true,"id":null,"links":[],"panels":[{"content":"\u003cdiv class=\"text-center dashboard-header\"\u003e\n  \u003cspan\u003eHome Dashboard\u003c/span\u003e\n\u003c/div\u003e","editable":true,"gridPos":{"h":3,"w":24,"x":0,"y":0},"id":1,"links":[],"mode":"html","style":{},"title":"","transparent":true,"type":"text"},{"folderId":0,"gridPos":{"h":17,"w":12,"x":0,"y":6},"headings":true,"id":3,"limit":30,"links":[],"query":"","recent":true,"search":false,"starred":true,"tags":[],"title":"","transparent":false,"type":"dashlist"},{"editable":true,"error":false,"gridPos":{"h":17,"w":12,"x":12,"y":6},"id":4,"links":[],"title":"","transparent":false,"type":"pluginlist"},{"gridPos":{"h":4,"w":24,"x":0,"y":3},"id":123123,"type":"gettingstarted"}],"rows":[],"schemaVersion":17,"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"now-6h","to":"now"},"timepicker":{"hidden":true,"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"],"type":"timepicker"},"timezone":"browser","title":"Home","version":0}}%
```

then I test annotations manually:
```
curl -XPOST 127.0.0.1:3000/api/annotations \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer eyJrIjoidzNoSUZxeGQwSGZFNTEzcFhaajRDa09pam5IcUNtVlkiLCJuIjoiYWFhIiwiaWQiOjF9" \
  --data @- << EOF
  {
    "text": "Deployed service 'backend-service'\n\n
      <a href=\"https://github.com/org/backend-service/commit/8ba7fb80\">GitHub (8ba7fb80)</a>\n
      <a href=\"http://ci.example.com/jenkins/job/backend-service/32/\">Jenkins (#32)</a>",
    "tags": [
      "deployment",
      "env:production",
      "tier:backend"
    ]
  }
EOF
```

then I open the pre-made "page timing metrics" dashboard and configure dashboard built-in annotations:
```
filter by: tags
tags: deployment
```

and I see my manual annotation in the graph.

I can see these in the logs:
```
[2019-11-06 13:05:03] DEBUG: [sitespeedio.plugin.grafana] Sent annotation to Grafana
[2019-11-06 13:05:03] INFO: [sitespeedio.plugin.messagelogger] {
  "uuid": "04e976d4-2d6e-491d-814c-863e4095c19a",
  "type": "sitespeedio.summarize",
  "timestamp": "2019-11-06T13:05:03+00:00",
  "source": "queueHandler"
}
```
but I just don't see anything in the grafana dashboard.

**Comment by matti** [comment]
```
/start.sh
--graphite.host=graphite 
--browsertime.browser=chrome
--browsertime.spa
--browsertime.iterations=1
--html.fetchHARFiles=true
--gcs.projectId=lol-engineering
--gcs.bucketname=lol.cat.engineering
--gcs.key=gcs-key.json
--gcs.public=true
--gcs.removeLocalResult=true
--grafana.host=grafana
--grafana.port=3000
--grafana.auth=eyJrIjoidzNoSUZxeGQwSGZFNTEzcFhaajRDa09pam5IcUNtVlkiLCJuIjoiYWFhIiwiaWQiOjF9
--resultBaseURL=http://lol.cat.engineering
-vvv
--debugMessages 
https://www.hemnet.se
```

^-- starting options

**Comment by soulgalore** [comment]
Ok let me have a look then. We don't use the Grafana ones on dashboard.sitespeed.io, only Graphite ones but we should have a test case for that.

**Comment by matti** [comment]
yeah, I don't really care if it's built-in grafana or graphite, but I just followed sitespeed docs and I got the impression that those would work

**Comment by soulgalore** [comment]
It works for me when I match the tags. Let me update the section in the docs tonight. If you look at the "run" annotation using Graphite we match some template variables for tags (the dropdown). You need to add those template variable too in the new Grafana annotation.

<img width="873" alt="Screenshot 2019-11-06 at 14 39 18" src="https://user-images.githubusercontent.com/540757/68302999-4d9c9c80-00a3-11ea-93b6-43dd420cded5.png">

If you do that, the correct annotation will be shown when you change the dropdowns.

**Comment by matti** [comment]
yeah okay, so to close this issue the default dashboard jsons should be updated so that user doesn't have to edit anything..?

**Comment by soulgalore** [comment]
No, I think its better to just stick to Graphite annotations in Grafana for a while, then you don't need to do anything at all. For Grafana you need to set up the API key. I was thinking about changing to Grafana when they implement configurable removal of old annotations.

**Comment by matti** [comment]
fair enough, so just doc update and close?

**Comment by matti** [comment]
I switched to graphite annotations now, it is sooo much easier and works OOTB.

**Comment by soulgalore** [comment]
Closing this, updated the docs.
