### ISSUE TITLE
not measuring the last step in script even after using measure start()-stop()

### ISSUE THREAD

**Issue by shubh1212** [sitespeedio/sitespeed.io#2751]
module.exports = async function(context, commands) {
    context.log.info('##### START#####');
	await commands.navigate('URL');
	try{
	   await commands.addText.byXpath('username');
	   await commands.addText.byXpath('password');

	// find the sumbit button and click it

	   await commands.click.byXpathAndWait("//button[@type='button' and contains(.,'login')]");
	   context.log.info('Info logging from your script');

	   await commands.click.byXpathAndWait("//div[@data-qa='expand-right']")
	   await commands.click.byXpathAndWait("//div[contains(text(),'Activities')]")

	   await commands.measure.start('Inbox');
	   await commands.click.byXpathAndWait("//div[contains(text(),'Promote Knowledge')]")
	   await commands.measure.stop();

	   await commands.measure.start('Draft');
       await commands.click.byXpathAndWait("//span[contains(text(),'Draft')]")
       await commands.measure.stop();

       await commands.click,byXpathAndWait("//a[@data-qa='bricks-IconButton']/span/*[local-name() = 'svg' and @data-qa='bricks-icons-ArrowBack']")

       await commands.measure.start('Published');
       await commands.click.byXpathAndWait("//span[contains(text(),'Published')]")
 	   return commands.measure.stop();

	}catch(e){

	}

};

I am getting the metrics for first two measures but not for the last one, even after using the stop().
this happens only with the last measure.

**Comment by soulgalore** [comment]
Hi @shubh1212 do you get any errors in that catch?  I usually follow these steps when I try to debug what goes wrong: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

Best
Peter

**Comment by shubh1212** [comment]
resolved after debugging
