### ISSUE TITLE
gcs.path does not use the full path provided, only last folder

### ISSUE THREAD

**Issue by Krattan** [sitespeedio/sitespeed.io#2753]
Using version: 10.3.2-plus1

When using --outputFolder only the last folder of the provided path is used.
I tried setting the --gcs.path directly but encountered the same issue.

Example:
config="desktop.json"
output_dir="results/desktop/siteurl/11-06-2019_13-48"
url="siteurl"
/start.sh --config $config --outputFolder $output_dir $url --plugins.add analysisstorer --plugins.add /lighthouse

Outcome:
[2019-11-06 13:49:13] INFO: Uploading /codefresh/volume/project/results/desktop/siteurl/11-06-2019_13-48 to Google Cloud Storage bucket gcloud-bucket, this can take a while ...                      
[2019-11-06 13:49:14] INFO: Finished upload to Google Cloud Storage

The root of the bucket I uploaded to only contains the last folder in the provided path:
![image](https://user-images.githubusercontent.com/17826669/68306777-770cf680-00aa-11ea-8c30-d60a0851b6cc.png)

It would be great if the whole path could be persisted to help with structuring of the artifacts

**Comment by Krattan** [comment]
This issue seems to have been resolved in the 11.0.0-plus1 release.
Closing this issue.

**Comment by soulgalore** [comment]
Hmm @Krattan this is kind of worrying because there hasn't been a change there I think between these releases.
