### ISSUE TITLE
Axe plugin only runs after last URL in JS file

### ISSUE THREAD

**Issue by abecker4** [sitespeedio/sitespeed.io#2754]
When running the --multi CLI parameter and a list of URLs in a JS file Axe will only execute after the final URL in the list and use the results for all URLs. 

**Version:**
10.3.2

**OS:**
Windows using Docker image

**CLI:**
docker run --rm -v c:/Workspace/Test:/sitespeed.io -p 5900:5900 sitespeedio/sitespeed.io:10.3.2 --axe.enable multi.js --multi -b chrome -n 1

**Example multi.js contents:**
module.exports = async function(context, commands) {
  await commands.measure.start('https://www.wikipedia.org/');
  await commands.measure.start('https://www.yahoo.com/');
  return commands.measure.start('https://www.google.com/');
};

**Steps to reproduce:**

1. Execute a solo run against https://www.wikipedia.org
2. Execute a run using --multi and the multi.js file above
3. Execute a solo run against https://www.google.com/
4. Compare the Axe results for the wikipedia page from the solo run to the multi run and observe they are different
5. Compare the Axe results for the wikipedia page from the multi run to the google solo run and observe they are the same. Implying Axe only runs on the last URL in multi.js and uses the results for all prior URL's.

**Comment by soulgalore** [comment]
We need the fix in sittespeed.io too.

**Comment by soulgalore** [comment]
Thank you @abecker4 for writing such a good bug report, that helped me a lot! This is fixed now and will roll out in the next release, hopefully tomorrow night.

**Comment by abecker4** [comment]
Of course @soulgalore. Thank you so much for the quick turnaround!
