### ISSUE TITLE
keep selected tab open accros runs

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2758]
currently changing the run resets the active tab:

![Screen Recording 2019-11-07 at 13 57 54](https://user-images.githubusercontent.com/3893/68387478-155e9200-0167-11ea-8ea7-e6e05f1d7d13.gif)

**Comment by soulgalore** [comment]
Yeah that is annoying! Hope someone with some front end skills can help us with that!

**Comment by AndresContreras96** [comment]
Hello,
I would like to work on this issue, is it still available?

**Comment by matti** [comment]
yes go ahead

**Comment by Aadi-27** [comment]
I would like to take this issue if no one is working on it ?

**Comment by matti** [comment]
go ahead

**Comment by Aadi-27** [comment]
sorry, picked other open source and got hands full. Don't mind

**Comment by matti** [comment]
never minded. for all future askers, just do the damn PR.

**Comment by JoseNavy** [comment]
Hello! Is this issue still happening? If so, I want to help! I'm new to Open Source and would be glad to help.

**Comment by soulgalore** [comment]
Hi @JoseNavy yes that would be great, I can guide you if you need help. Either you can ask here or join the Slack channel: sitespeedio.herokuapp.com

**Comment by JoseNavy** [comment]
Thank you @soulgalore! I'll install the project and If I have any questions, I'll drop them here.

**Comment by amtanq** [comment]
Please take a look at my pull request for the issue.
Thank you

**Comment by soulgalore** [comment]
This has been fixed.
