### ISSUE TITLE
crawler and gcs uploads

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2760]
With `--browsertime.iterations=10` I get grafana annotations and annotation links for GCS report.

If I enable:

```
  --crawler.depth=2 \
  --crawler.maxPages=10 \
```
the annotations are generated with links, but no files are uploaded anymore --> clicking annotation links point to a folder in a bucket that has not been generated.

Additional question: Can iterations and crawler be used together?

**Comment by soulgalore** [comment]
>  but no files are uploaded anymore

Do you see anything in the log?

The flow is like this: first the web site is crawled, then each URL are passed in in the queue that all plugins listens to,. Then each URL is tested the number of iterations.

**Comment by matti** [comment]
can't reproduce anymore, thanks for the flow explanation.
