### ISSUE TITLE
html report visualmetrics times overlap

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2761]
<img width="800" alt="adf" src="https://user-images.githubusercontent.com/3893/68390531-28c12b80-016e-11ea-86b9-69fbbcbb3e44.png">

**Comment by matti** [comment]
@samulir will prob submit a PR soon

**Comment by Aadi-27** [comment]
Hi, 
I would like to take this issue if it isn't fixed yet or noone is still working on it ?

**Comment by matti** [comment]
no, go ahead

**Comment by Aadi-27** [comment]
sorry, picked other open source and got hands full. Don't mind.

**Comment by matti** [comment]
never minded

**Comment by Bhuvnesh875** [comment]
i would like to work on it ,if its available.

**Comment by matti** [comment]
https://github.com/sitespeedio/sitespeed.io/issues/2761#issuecomment-702661407

**Comment by SD007CSE** [comment]
is this issue available?

**Comment by matti** [comment]
@SD007CSE most definitely! and based on the history it will be available until 2029!

**Comment by shaikhazrath** [comment]
i want to fix this can i know how to reproduce the same issue

**Comment by soulgalore** [comment]
@shaikhazrath I think it happens if you test a really slow web site. You can slowdown the connectivity to use 3g and then run your test, maybe that can reproduce it.

**Comment by matti** [comment]
is there some reward on sitespeed issue fixing somewhere? just looking at the history of this issue and it seems so

**Comment by shaikhazrath** [comment]
i may not fix it but i want to fix some bugs in sitespeed can anyone guide me

**Comment by 4nshuman** [comment]
Hello there @matti,
I am next in line to try and slay this dragon that has claimed so many of our great warriors.
I have analyzed the issue and have determined that this dragon named pug is plotting a chart named of destruction with huge numbers.
Allow me to tame this pug and have it plot the numbers at a 45° angle.

**Comment by matti** [comment]
@4nshuman godspeed

**Comment by 4nshuman** [comment]
Hello @matti, @soulgalore 
I think I was able to solve this issue:

Before :
![image](https://github.com/user-attachments/assets/c2a5b6aa-6e6a-4b80-b3a2-4fb218417f04)

After :
![image](https://github.com/user-attachments/assets/72395b0a-3e2e-4835-9514-2cdbff9462fc)

would love to hear your reviews on the PR please.
PR : https://github.com/sitespeedio/sitespeed.io/pull/4269

**Comment by soulgalore** [comment]
Releasing this later today.
