### ISSUE TITLE
--postScript has no selenium session identifier

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2762]
with:
```
  --postScript=postscript.js
  --multi
  http://www.example.com
  http://www.example.net
```

postscript.js:
```
module.exports = async function (context, commands) {
  context.log.info('LOLBUG');
  context.log.info(context.selenium.driver);

  let src = `1+1`
  let ret;
  try {
    res = await context.selenium.driver.execute(src);
  } catch (err) {
    context.log.info("LOLBUG ERR");
    context.log.info(err);
  }

  context.log.info('LOLBUG ret');
  context.log.info(ret);
};
```

error:
```
INFO: [browsertime] LOLBUG
INFO: [browsertime] { "session_": { }, "executor_": { "w3c": true, "customCommands_": { }, "log_": { "name_": "webdriver.http.Executor", "level_": null, "parent_": { "name_": "webdriver.http", "level_": null, "parent_": { "name_": "webdriver", "level_": null, "parent_": { "name_": "", "level_": { "name_": "OFF", "value_": null }, "parent_": null, "handlers_": null }, "handlers_": null }, "handlers_": null }, "handlers_": null } }, "fileDetector_": null }
INFO: [browsertime] LOLBUG ERR
INFO: [browsertime] TypeError: command.setParameter is not a function
at Driver.execute(/usr/src / app / node_modules / selenium - webdriver / lib / webdriver.js: 696: 13)
at module.exports(/app/postscript.js: 8: 41)
at Iteration.run(/usr/src / app / node_modules / browsertime / lib / core / engine / iteration.js: 180: 15)
at process._tickCallback(internal / process / next_tick.js: 68: 7)
INFO: [browsertime] LOLBUG ret
INFO: [browsertime] undefined
```

**Comment by matti** [comment]
I'd like to run my script similarly to https://github.com/sitespeedio/browsertime/pull/985/files - not sure if this is related?

**Comment by soulgalore** [comment]
What do you want to do, what's the use case? I think maybe the docs are missing something. ´--multi´ is the switch to use when you are testing multiple pages in a script:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/

Also I think the documentation for postScript maybe is wrong let me look into it, I haven't used it since we introduced scripting.

**Comment by matti** [comment]
I want to analyze the page contents after the page has loaded.

`--multi` is also used without scripts for testing multiple urls so that the cache is not destroyed after the first one, so for example:

```
--multi http://www.example.com http://www.example.com/second
```

without `--multi` the `/second` page is loaded with empty caches?

**Comment by soulgalore** [comment]
Yeah you are right I was wrong!

In your example you are calling the wrong method (that one takes a command), check the webdriver API: https://selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebDriver.html

**Comment by matti** [comment]
thanks again, postscript works - I was debugging too many things at the same time, for example the: #2765
