### ISSUE TITLE
--crawler and --multi

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2765]
when both `--crawler` and `--multi` are set, the crawling is silently ignored.

`--crawler` is useful for giving just one page, like http://www.example.com and then discovering automatically some urls. `--multi` is useful for make those subsequent urls to use caches.

Currently these switches can not be combined, how to enable crawling with caches?

**Comment by soulgalore** [comment]
Yeah I think that's something I've missed, let me check how much work that is to fix it.

**Comment by soulgalore** [comment]
I think the fix I added before is enough.
