### ISSUE TITLE
pending request causes load to hang/timeout

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2770]
In https://www.nenapaiva.fi/ there is one request that is pending and causes the load to take 60s (?)

I don't think it should be the responsibility of sitespeed user to write custom script that handles this case.

**Comment by matti** [comment]
see here: https://www.youtube.com/watch?v=lyt_zcRhg4E&feature=youtu.be

**Comment by matti** [comment]
the site is kinda hanging because 1 font loading request is pending, but it doesn't *really* mean that the page is still loading - I think this could be improved without manual "when to stop loading" js?

**Comment by soulgalore** [comment]
I think this is the same as I've seen in https://github.com/sitespeedio/browsertime/issues/984. Are you using Chrome? When I looked upstream Chromedriver 78 hade a change that looked suspicious where they change how timeouts are handled. I've had time yet to check if someone else reported this in Chromedriver or created an upstream issue.

**Comment by soulgalore** [comment]
Ok I saw now that its not the same, it times out after 60s for you right? That’s the browser timing out the request I guess, but need to check the limit.

**Comment by matti** [comment]
The nenapaiva.fi site still hangs, so you could try that now with sitespeed? I *think* it times out at 60s, but cureently metric sending is broken for some reason so I can't be sure.

**Comment by soulgalore** [comment]
Yep, it times out after 60s with Chrome. Firefox gets a 404 instead. This is a great opportunity to fix https://github.com/sitespeedio/chrome-har/issues/26 (we don't get the correct end time for that request), I've collected the log so I can fix that next week.

I think this correct behaviour and the only way to find SPOF?

**Comment by matti** [comment]
![image](https://user-images.githubusercontent.com/3893/68526150-74e0ad00-02e1-11ea-9609-2db8434f98cc.png)

Are you sure about 404s? Because now when I look at the HAR those requests are eventually completed (also see the youtube link above)

**Comment by matti** [comment]
So currently I'm confused about what should be the correct behavior... Because the page is significantly changing at ~59s mark.  Maybe the current behavior is okay after all?

**Comment by matti** [comment]
Although, could it be that timeout causes somehow the pending request to complete? (see video how suddenly the page is fully loaded) ?

**Comment by soulgalore** [comment]
Yes, the browser has timeout for how long time it waits for a request to finish.

I think this is the correct behavior since it's the only way to find SPOF. I'm closing, but please let me know if you disagree.
