### ISSUE TITLE
Application page shows error at last step

### ISSUE THREAD

**Issue by shubh1212** [sitespeedio/sitespeed.io#2771]
below is the snapshot of the code.
console shows no error, but if i see the recording and screenshots, last step throws an error on the application after click operation.

module.exports = async function(context, commands) {
    context.log.info('##### START - Execute ABC.js #####');
	await commands.navigate('URL');
	try{
	
	   await commands.addText.byXpath('username', "//input[@name='username']");
	   await commands.addText.byXpath('pass', "//input[@name='password']");

	// find the sumbit button and click it

	   await commands.click.byXpathAndWait("//button[@type='button' and contains(.,'login')]");
	   context.log.info('Info logging from your script');
      
	   await commands.measure.start('Step1');
	   await commands.click.byXpathAndWait("//div[contains(text(),'sample')]");
	   await commands.measure.stop();
	   
	   await commands.wait.byXpath("//span[contains(text(),'sample2')]/preceding::div[1]", 10000);

	   await commands.measure.start('step2');
       await commands.click.byXpathAndWait("//span[contains(text(),'sample2')]/preceding::div[1]");
      await commands.wait.byTime(5000);
       
       await commands.wait.byXpath("some locator", 10000);
        
      await commands.click.byXpath("some locator");
      
       await commands.measure.stop();
      
       await commands.wait.byTime(5000);
        
        await commands.wait.byXpath("some locator", 10000);

       await commands.measure.start('step3');

       **await commands.click.byXpathAndWait("some locator");**
 
       await commands.wait.byTime(5000);
}catch (e){}

return commands.measure.stop();

};

looks like right after performing last step, application error page appears according to video.

![image](https://user-images.githubusercontent.com/55746507/68528370-cb68de00-0317-11ea-81fb-4f19cda3cb7e.png)

**Comment by soulgalore** [comment]
Hi @shubh1212 I don't follow. What's the error or what do you mean goes wrong on the sitespeed.io side?

Best
Peter

**Comment by soulgalore** [comment]
Closing since lack of feedback.
