### ISSUE TITLE
Verify error handling in Slack

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2773]
When I had a quick look at the Slack plugin I think the plugin doesn't handle errors the correct way, at least it looks different that we do in the HTML plugin.

**Comment by erickwilder** [comment]
Would you elaborate a bit on this issue? I've spent some time with the Slack plugin already and if you could point me in the right direction I might get this to take a look.

Just trying to keep the momentum 💪 😄

**Comment by soulgalore** [comment]
Ha that description wasn't very helpful, let me have look tomorrow and see if I remember :) Thanks @erickwilder

**Comment by soulgalore** [comment]
I didn't get time to check this today, I wanted to merge your PR first @erickwilder . Gonna try to find time tomorrow.

**Comment by erickwilder** [comment]
Don't worry. Take your time! In the meantime, I will skim thru other issues to see where/if I can help.

**Comment by soulgalore** [comment]
Lets close this and focus on making Slack work exactly as Matrix.
