### ISSUE TITLE
grafana link points to last page

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2775]
```
--multi
http://www.example.com/first
http://www.example.com/second
```

--> grafana link points to `/second`, but it would make more sense if it opened `/first` - now I need to manually click "Pages" and then select the first one.

**Comment by soulgalore** [comment]
This looks like a bug, there should be one annotation per URL.

**Comment by soulgalore** [comment]
Can you show me more how it doesn't work for you? I tried with: ` --graphite.host 127.0.0.1 https://www.sitespeed.io https://www.sitespeed.io/documentation/ --multi -n 1 --headless --resultBaseURL https://result.sitespeed.io/` and looking at the annotation there are one per URL and they point to each start test page for that URL?

I'm using Graphite, the default annotations. Check the tags, there should be a tag for the path of the URL.

<img width="282" alt="Screenshot 2019-11-12 at 20 55 24" src="https://user-images.githubusercontent.com/540757/68705668-c5c8fd80-058e-11ea-9cee-acb60020ac0c.png">
<img width="300" alt="Screenshot 2019-11-12 at 20 55 13" src="https://user-images.githubusercontent.com/540757/68705669-c5c8fd80-058e-11ea-9b23-3e5e3e474416.png">

**Comment by matti** [comment]
so when I run
```
--multi 
https://icebreaker.vc/
https://icebreaker.vc/
```

and when I click the result link in grafana annotation, then it throws me to:

![image](https://user-images.githubusercontent.com/3893/69742070-d360b480-1144-11ea-85bd-878efbee5224.png)

so I'm on the second run (browsertime_run=2) and I need to click "Pages" so that I can get to the first run:

![image](https://user-images.githubusercontent.com/3893/69742209-0e62e800-1145-11ea-80b1-253062170bb5.png)

**Comment by soulgalore** [comment]
That was not the example you showed in the issue :)  Yes looks that that could be fixed.

**Comment by tshrsrvstv** [comment]
@soulgalore Can you assign this issue to me ?

**Comment by matti** [comment]
@tshrsrvstv you are now soft-assigned. just do it.

narrator: he did not

**Comment by tshrsrvstv** [comment]
@soulgalore looks like this is fixed already as when I open results I am getting a summary page and on that I have to go to Pages to navigate through different pages

**Comment by soulgalore** [comment]
There's more important things to spend time on to fix so lets close this one.
