### ISSUE TITLE
conditional annotation sending

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2776]
I want to send annotation/upload to bucket only if some condition, like response code is not 200 or page load time is over 5 - is this possible now?

**Comment by soulgalore** [comment]
No it isn't. Right now we only send annotations for linking to the result. The I've been using errors is that I create an alert that fires if we have errors.

It would be cool to have a concept of using more annotation but sure when/how etc.

**Comment by soulgalore** [comment]
I think these kind of things are better implemented as alerts directly in Grafana.
