### ISSUE TITLE
Error : Chrome failed to start: exited abnormally  while executing test from docker

### ISSUE THREAD

**Issue by koulvivek** [sitespeedio/sitespeed.io#2780]
I am unable to run basic sitespeed intro test on RHEL using docker container 

**Command and Params :**
docker run --rm -v "$(pwd)":/Sitespeed sitespeedio/sitespeed.io:11.0.0 -b chrome https://www.sitespeed.io/

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Google Chrome 78.0.3904.87 
Mozilla Firefox 70.0

**Version Info** 
[2019-11-12 15:06:10] INFO: Versions OS: linux 4.18.0-80.4.2.el8_0.x86_64 nodejs: v12.13.0 sitespeed.io: 11.0.0 browsertime: 7.0.1 coach: 4.2.0

**Error** 

[2019-11-12 15:06:11] INFO: Running tests using Chrome - 3 iteration(s)
[2019-11-12 15:06:13] INFO: Browser failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-11-12 15:06:15] INFO: Browser failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)

**Comment by koulvivek** [comment]
**Additional logging** 

  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-11-12 15:06:30] INFO: Browser failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-11-12 15:06:30] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2019-11-12 15:06:30] ERROR: No data to collect
[2019-11-12 15:06:31] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2019-11-12-15-06-10

**Comment by koulvivek** [comment]
The setup works fine with Firefox

**Comment by soulgalore** [comment]
Hi @koulvivek thank you for creating the issue! Seen this in a couple of issues before, then it was that Chrome was missing the `--no-sandbox` flag but we add that automatically now if the [Docker env flag is set](https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L4). How do Podman work, can it have messed up that somehow? Can you try adding it manually: 
`--browsertime.chrome.args no-sandbox` 

to really make sure it is there?

Another trick is to turn on the Chromedriver log and see if the log can give us more info. Add `--verbose`to your run and a chromedriver.log file should be created, maybe that can help us.

Best
Peter

**Comment by koulvivek** [comment]
Hi Peter ,

Thanks for your reply !! I added _--browsertime.chrome.args no-sandbox arguments but it did not help. I also installed google chrome separately with the same version as in docker container ,however it did not help. Finally i tried the same setup on Centos and it worked like a charm.I do feel that Podman might have different settings which may impact launch of chrome(however i am not certain with concrete proof).

**Comment by soulgalore** [comment]
Ok cool!

**Comment by keshavmesta** [comment]
> Hi @koulvivek thank you for creating the issue! Seen this in a couple of issues before, then it was that Chrome was missing the `--no-sandbox` flag but we add that automatically now if the [Docker env flag is set](https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L4). How do Podman work, can it have messed up that somehow? Can you try adding it manually: `--browsertime.chrome.args no-sandbox`
> 
> to really make sure it is there?
> 
> Another trick is to turn on the Chromedriver log and see if the log can give us more info. Add `--verbose`to your run and a chromedriver.log file should be created, maybe that can help us.
> 
> Best Peter

hey @soulgalore don't mean to reopen this issue but I was just wondering where chromedriver.log would be created. I am running into a similar issue and trying to find this chromedriver.log
