### ISSUE TITLE
Sitespeed.io click by hardware button

### ISSUE THREAD

**Issue by ialeshina** [sitespeedio/sitespeed.io#2784]
Hi dears!
Please advice if it is possible to call hardware button click via sitespeed.io.

Use case: navigate to web url that requires authentication before user can proceed.
In order to proceed with browsing, user has to enter pincode and press Enter key hardware button.

**Comment by soulgalore** [comment]
Hi @ialeshina no not that I know of. I think the way people usually handles it is to setup ways to bypass these kind security things.

Best
Peter

**Comment by soulgalore** [comment]
Closing this since the question is answered, sorry!
