### ISSUE TITLE
"await commands.measure.start()" leads to page cannot be found 

### ISSUE THREAD

**Issue by ialeshina** [sitespeedio/sitespeed.io#2794]
Hi dears!
I got some strange behavior when running my script.
Trying to measure page: https://integration.alloffice.se/papper

No errors in logs, but when I look at resulted video, I can see, that page cannot be found
![1](https://user-images.githubusercontent.com/54897268/69238887-4a240d80-0b99-11ea-95a3-8aedf7baf5a2.png)

However if I enter the exact link directly into browser,  page is opened, no issues.

My script
```

  try {
                context.log.info("script to measure start, category, and product pages");
                await commands.measure.start('https://integration.alloffice.se/?auth_code=1978','start_page');
                 //Click on Private user to get rid of customer divider
                await commands.click.byXpath('//*[@id="container"]/div/div[9]/div/div[2]/button[2]');
                context.log.info("closed customer divider window");
                await commands.wait.byTime(5000);

               

                await commands.measure.start('https://integration.alloffice.se/papper','category_page');
                await commands.wait.byTime(5000);

               
                await commands.measure.start('https://integration.alloffice.se/alloffice/product197667','product_page');
                await commands.wait.byTime(10000);

                return
  } catch (e) {
                context.log.info('in catch',e);
  }
}

```
Command used to run:
`sudo docker-compose -f /home/qa-sitespeed/sitespeed/docker-compose.yml run sitespeed.io --multi  --pageCompleteWaitTime 10000 AOsmoke_test_3.js -n 3 
`
 INFO: Versions OS: linux 5.0.0-1016-azure nodejs: v10.13.0 sitespeed.io: 9.3.2 browsertime: 5.2.5 coach: 3.6.0

No such problems if I try any other site.

Can you please advice where could be the problem?

**Comment by soulgalore** [comment]
Hi @ialeshina how is the auth_code propagated from one page to another? When I tested I either get the "code" page (and I guess that should the auth code or?) or missing page. I don't think this is a problem of sitespeed.io if you check of hit works behind the scenes maybe there's a way to fix it.

Best
Peter

**Comment by ialeshina** [comment]
You are asked for auth code only once at a start page and we can workaround it by feeding it into link itself.

So if you put links directly into browser:
https://integration.alloffice.se/?auth_code=1978 - auth code is fed and page can be opened and measured without issues

Then you can open next page, cache and cookies are saved:
https://integration.alloffice.se/papper  - user is not asked for code

**Comment by soulgalore** [comment]
Yeah in theory :) That doesn't work for me when I tried in Safari I think there's some bug in that sites functionality and that also makes the tests fail. Also you can verify that the cookie is set if you look at the requests/responses in the waterfall.

**Comment by ialeshina** [comment]
Thanks a lot for quick responce. Will keep digging with dev team ))
Feel free to close it
