### ISSUE TITLE
Extract values e.g. via regex from a response

### ISSUE THREAD

**Issue by rnemeth1980** [sitespeedio/sitespeed.io#2796]
Hi, 
is it possible to extract values e.g. via regex from a response, like session codes and use for login? 

I see 
there https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure-the-actual-login-step 
entering credentials, but keycloak login requires some session parameters which need to be extracted from the reponse of the (previous) GET request, then used in following POST request. 

How do I do this with sitespeed scripting?

Also is it somehow possible to read e.g. csv files, use data like credentials and enter them into input fields?

Thank you,
Roland

**Comment by soulgalore** [comment]
Hi @rnemeth1980 you can't get hold of the response directly (only after in the HAR file) if you do  the normal flow navigation but you could do a GET request with NodeJS something like https://nodejs.dev/making-http-requests-with-nodejs - then you will have access directly to the response.

>Also is it somehow possible to read e.g. csv files, use data like credentials and enter them into input fields? 

You could use NodeJS own file handling to read it if its a file. If there's just credentials, you can pass on those from the cli, checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#pass-your-own-options-to-your-script

Hope that helps!
Best
Peter

**Comment by rnemeth1980** [comment]
Thank you @soulgalore , that helped.
