### ISSUE TITLE
Irregular performance test results using throttle with Sitespeed

### ISSUE THREAD

**Issue by obihill** [sitespeedio/sitespeed.io#2803]
I'm running Sitespeed (10.3.2) with Docker on a Google Cloud VM (n1-standard-1).

I installed throttle:
```
sudo npm install @sitespeed.io/throttle -g
```

And then I ran the following command:
```
sudo modprobe ifb numifbs=1
```

Then I started running my sitespeed tests. First via cable connectivity:

```
docker run --cap-add=NET_ADMIN --shm-size=1g --rm sitespeedio/sitespeed.io:10.3.2 --browsertime.connectivity.engine=throttle -c cable -n 1 -b chrome --chrome.timeline https://www.oxo.com
```

Here are the results for cable:

```
[2019-11-27 14:42:42] INFO: https://www.oxo.com 412 requests, backEndTime: 953ms, firstPaint: 3.27s, firstVisualChange: 3.27s, DOMContentLoaded: 10.80s, Load: 22.56s, speedIndex: 17554, visualComplete85: 32.33s, lastVisualChange: 32.33s, rumSpeedIndex: 13987
```

I then switch to 3G running the following command:

```
docker run --cap-add=NET_ADMIN --shm-size=1g --rm sitespeedio/sitespeed.io:10.3.2 --browsertime.connectivity.engine=throttle -c 3g -n 1 -b chrome --chrome.timeline https://www.oxo.com
```

Here are the results for 3g connectivity:
```
[2019-11-27 14:47:36] INFO: https://www.oxo.com 417 requests, backEndTime: 1.96s, firstPaint: 6.37s, firstVisualChange: 6.47s, DOMContentLoaded: 7.38s, Load: 40.15s, speedIndex: 16519, visualComplete85: 51.40s, lastVisualChange: 51.40s, rumSpeedIndex: 32547
```

The Speed Index values are 17554 [cable] and 16519 [3g]. How is this possible, given that cable is a much faster connection than 3g? 

I also ran a similar test via WebPageTest.org [the website itself] and I got 6298 [cable] and 17903 [3g], which seems more realistic.

Is there something I'm doing wrong?

**Comment by soulgalore** [comment]
Hi @obihill to verify that Throttle works I would look at server timings and things like first paint. 

See https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#difference-in-metrics-between-webpagetest-and-sitespeedio for comparing tools. 

Speed Index depends on screen size so if that is different, they will have different values. To check what happens I would look at the video or the filmstrip. Your first paint values look ok.

**Comment by obihill** [comment]
Sorry for the late response.

Thanks for the link on the comparison between webpagetest and sitespeed.

I believe throttle is working based on the first paint and loaded times, but the speed index values are off. What should I be looking for in the videos?

**Comment by soulgalore** [comment]
My guess is that you get different content different times, so if you check the videos, can you spot any difference?

**Comment by soulgalore** [comment]
Closing because of lack of feedback.
