### ISSUE TITLE
crawling does not start

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2804]
tried different combos including maxPages and crawler.include, no luck. with v11.4.0.

```
/start.sh
  --graphite.host=graphite
  --browsertime.browser=chrome
  --browsertime.spa
  --html.fetchHARFiles=true
  --gcs.projectId=lol   --gcs.bucketname=lol.cat   --gcs.key=gcs-key.json   --gcs.public=true   --gcs.removeLocalResult=true
  --graphite.annotationScreenshot
  --resultBaseURL=http://lolcat.com
  -vv
  --graphite.annotationTag=myannotation
  --browsertime.iterations=1
  --crawler.depth=1
  https://www.wikipedia.org
```

**Comment by soulgalore** [comment]
The depth needs to be 2 see:
`--crawler.depth, -d     How deep to crawl (1=only one page, 2=include links from first page, etc.)`

Its old historical reasons. We should change that in a future major.

**Comment by matti** [comment]
I have this _feeling_ that there is something fundamentally wrong with the way sitespeed handles options. see #2765 for example. silent failures are not good.

**Comment by soulgalore** [comment]
Yes so its feature that we you can pass on anything but if you miss-spell its a bug. It's good that you don't need to define parameters, that means we can pass on new parameters to plugins. There's a issue #1065 to implement so plugins can validate themselves, but it isn't super trivial to implement. A simpler way could be to just output unmatched parameters, that could maybe be possible.

I think for #2765 that wouldn't help, that's more of how the feature is built, it has nothing to do with the parameter. Right now you kind of switch mode with --multi so it disables crawling. That needs to be fixed.

**Comment by matti** [comment]
I can see from the logs that crawler finds urls, but it only visits the root.

**Comment by matti** [comment]
Okay, something was off. I think it's that the cli option parsing is "broken" - I think sitespeed should error out when not enough options are given for something.

**Comment by matti** [comment]
I'll just close this issue, there should be a new one about this bigger "usability" problem.

**Comment by soulgalore** [comment]
Yep I think that's miss in the crawler plugin.
