### ISSUE TITLE
safer option parsing

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2806]
sitespeed should exit with error when for example `--crawler.maxPages` is given, but not `--crawler.depth` because it's confusing that "something" starts to happen, but not the desired thing.

**Comment by soulgalore** [comment]
Yes it's kind of broken. Some plugins have a guard that checks the essential configurations first before starting the plugin. Another way could be to automatically run the plugin and and log that we use a default depth.

**Comment by soulgalore** [comment]
Released in 11.5.0
