### ISSUE TITLE
Collect number of processes running on the machine

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2808]
One thing that we are missing is collecting number of processes running on the machine, that will help us know if something is going on on that machine. That's something the Chrome performance team is using see https://www.youtube.com/watch?v=ctavZT87syI

I think we could do something simple like
`ps aux | wc -l` and just send that metric to Graphite/InfluxDB.

But since we use Docker, we should do it directly on the server. Maybe we can just add a example on how to implement it or we could use something like https://github.com/shawn-sterling/graphios

**Comment by matti** [comment]
>But since we use Docker, we should do it directly on the server

what do you mean by this?

**Comment by soulgalore** [comment]
If we check number of processes inside the container it doesn't matter, they will be the same mostly but if have server and keep it running, you need keep track of processes there so they do not interfere with our testing.

**Comment by matti** [comment]
fyi: you can attach to the host pid namespace from a docker container - not sure if this helps

**Comment by soulgalore** [comment]
Aha cool, let me try that after Christmas.

**Comment by soulgalore** [comment]
I think this is easy to do on the outside of sitespeed.io.
