### ISSUE TITLE
Video creation fails as of Sitespeed.io 11.3.0 (Browsertime 7.2.2)_

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2815]
Sitespeed.io 11.3.0 (dockerized)
Browsertime 7.2.2

As of this version, when attempting to play back video, I receive "The media could not be loaded, either because the server or network failed or because the format is not supported.".

```
{
  "cpu": "true",
  "multi": "true",
  "network": "cable",
  "name": "Platform - Dev",
  "resultBaseURL": "http://sitespeed.myco.io.s3-website-us-west-2.amazonaws.com",
  "browsertime": {
    "iterations": 2,
    "block": "bam.nr-data.net",
    "browser": "chrome",
    "pageCompleteCheckInactivity": "true",
    "spa": "true",
    "video": "true",
    "visualElements": "false",
    "visualMetrics": "true"
  },
```

**Comment by soulgalore** [comment]
Hi @leathej1 we haven't changed anything of the video format, could it be that the file is corrupt (not recorded ok)?
Do this video work for you? https://s3.amazonaws.com/results.sitespeed.io/www.google.com/2019-12-06-08-42-52/pages/en.wikipedia.org/wiki/Barack_Obama/index.html#video

**Comment by leathej1** [comment]
Yes, that works. Let me send you the script. I literally walked through every version, one by one, until it failed at 11.3.0.

**Comment by soulgalore** [comment]
I checked the [changelog](https://github.com/sitespeedio/sitespeed.io/blob/master/CHANGELOG.md#1130---2019-11-22) and what changed was when we end recording the video. 

It used to work like this:
- start the video
- navigate to the page
- pageCompleteCheck says the page is finished
- we collect all JavaScript metric
- video stops
- the video is cut so we remove everything after last visual change

new:
- start the video
- navigate to the page
- pageCompleteCheck says the page is finished
- video stops
- we collect all JavaScript metric
- the video is cut so we remove everything after last visual change

Try to add some extra wait before you stop your measurement. My guess is that it worked before just because we collected the JS and that made the video longer.

**Comment by leathej1** [comment]
Sorry - won't an added wait before stopping the measurement affect page metrics?

**Comment by soulgalore** [comment]
Hopefully not? Checked your example, I think when you click the submit button, try use the ...andWait command as in https://www.sitespeed.io/documentation/sitespeed.io/scripting/#jsrunandwaitjavascript 

That will give the browser time for to load the new page.

**Comment by leathej1** [comment]
Hmm... that doesn't seem to help. I wonder if the new order of events is getting tripped up by this error: `INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.`

**Comment by leathej1** [comment]
And then `ERROR: Could not read filmstrip dir Error: ENOENT: no such file or directory, scandir '/sitespeed.io/sitespeed-result/navigate-crm_js/2019-12-10-16-20-23/pages/performance2.myco.com/apps/agent/hash-96f6a71c/data/filmstrip/1''`

**Comment by soulgalore** [comment]
If you look at the video or run it with a screen what do you see? Most cases you can see what's goes wrong.

> INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.

That's comes from a trace bug in Chrome. Sometimes (it's non deterministic at least those cases I've seen) when we navigate to a page, the trace log doesn't generate the navigation event, so we just inject one ourselves. 

> ENOENT: no such file or directory, scandir 

Yeah I think that's a follow up because there's no video.

**Comment by leathej1** [comment]
```
{ Error: Command failed with exit code 1 (EPERM): ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 10M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /Github/performance-sitespeed/sitespeed-result/navigate-crm_js/2019-12-10-11-15-46/x11-tmp.mp4
    at makeError (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  command:
   'ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 10M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /Github/performance-sitespeed/sitespeed-result/navigate-crm_js/2019-12-10-11-15-46/x11-tmp.mp4',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr:
   "Unrecognized option 'draw_mouse'.\nError splitting the argument list: Option not found",
  all:
   "Unrecognized option 'draw_mouse'.\nError splitting the argument list: Option not found",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }
```

**Comment by soulgalore** [comment]
Are you running directly on OS X with ffmpeg? The current version doesn't support that.

If you look at the video or run it with a screen what do you see? Most cases you can see what's goes wrong?

**Comment by leathej1** [comment]
Sorry - I must be missing something. How can I run interactively without running directly on the OS?

**Comment by leathej1** [comment]
OK - I have this figured out, I believe. It has to do with the number of redirects seen at this uri: 
`await commands.measure.start('https://' + tenant + '/apps/agent/#', 'Open CRM');`

The redirect behavior that existed previously was changed. This led to the same page being loaded multiple times. When I went to /apps/agent (the new preferred path), the redirects were handled better, and video creation started and ended successfully.

**Comment by soulgalore** [comment]
Ah ok good. Sorry I was unclear. When I debug I run the NodeJS version but without the video and just watch the browser window on my local machine.That together with logging usually solves most issues for me.

**Comment by leathej1** [comment]
Ah, unfortunately this did not turn out to be the fix for this issue after all.

The only remedy I have is to set `"visualMetrics": "false"`, which is not great.

**Comment by soulgalore** [comment]
So what happens if you look at the browser when you run the tests, can you see what goes wrong? 

Also added a new method in scripting that will store a screenshot to disk that maybe can help you debug: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#screenshottakename
