### ISSUE TITLE
Friendly name in budget output

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#2817]
Instead of the full URL, can we have the friendly name in the budget output?   Similar to how its displayed in the page summary. 

![image](https://user-images.githubusercontent.com/1022410/70498333-05c6c600-1ae4-11ea-9788-bc69bef17693.png)

**Comment by soulgalore** [comment]
I think this has been fixed when I fixed so we can configure a alias for a budget.
