### ISSUE TITLE
Budget file is not being read properly.

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#2818]
Below is my budget file but the output passes because it reads the "transfersize" section as 0 b instead of the values I added. 

{
 "budget": {
   "timings": {
         "firstPaint": 433,
         "fullyLoaded": 15000,
         "FirstVisualChange": 401,
         "VisualReadiness": 5000
    },
   "cpu": {
         "totalBlockingTime": 1000,
         "maxPotentialFid": 200,
         "longTasksTotalDuration": 1000
    },
   "requests": {
         "total": 230,
         "html": 1,
         "javascript": 24,
         "css": 2,
         "image": 40,
         "font": 4,
         "httpErrors": 0
    },
   "transferSize": {
         "total": 250000,
         "html": 16500,
         "javascript": 150000,
         "css": 120000,
         "image": 500000,
         "font": 50000,
         "json": 230000
    },
   "contentSize": {
         "total": 750000
    },
   "thirdParty": {
         "transferSize": 500000,
         "requests": 25
    },
   "webpagetest": {
         "TTFB": 400,
         "fullyLoaded": 10000
    }
 }
}
~

Output (omiting URLs) (also requested on another enhancement request to replace URLs with friendly names)
![image](https://user-images.githubusercontent.com/1022410/70498562-cd73b780-1ae4-11ea-8de3-88df505934dc.png)

**Comment by soulgalore** [comment]
Hi @kmaqsudi thanks for reporting let me have a look asap.

**Comment by soulgalore** [comment]
This was introduced a while ago when adding support in budget for HTTP errors. This is fixed in 11.7.1, please let me know that it works for you!
