### ISSUE TITLE
Multiple set of iteration in single config.json

### ISSUE THREAD

**Issue by sureshkrishnaselvam** [sitespeedio/sitespeed.io#2822]
Hi guys, It would be a great help if anyone suggest me some solutions to run multiple set of iterations like 5, 10, 15 in a single config json file. Below is my config.json file in which I have configured test to run 5 iterations. 

**Config.json :**

{
    "browsertime": {
	  "iterations": 5,
	  "browser": "chrome",
	  "visualMetrics" : true
	},
	"xvfb": true,
	"chrome": {
		"args": [
			"no-sandbox"
		]
	},
	"html": {
		"showAllWaterfallSummary": true
	},
	"outputFolder": "test/performance/reports/google",
	"mobile": false,
	"budget": {
		"configPath": "test/performance/google/budget.json",
		"output": "tap"
	},
	"utc":true
}

**Comment by sureshkrishnaselvam** [comment]
@soulgalore can you please help me on this request.

**Comment by soulgalore** [comment]
Hi @sureshkrishnaselvam sorry I missed this. CLI parameters overrides config, so I usually have on config that I use and then have different iterations in the cli:
```
--config config.json -n 11
--config config.json -n 5
```

Best
Peter

**Comment by sureshkrishnaselvam** [comment]
Hi @soulgalore thanks for your suggestions, so I can have one config.json and then we can mention the number of iterations to run in the CLI 

**Say like this,**
/usr/src/app/bin/sitespeed.js --preScript=test/performance/login.js --config=test/performance/config.json -n 10 --config=test/performance/config.json -n 15 test/performance/url.txt

I am running the test in Jenkins.

**Comment by soulgalore** [comment]
Like this:
`/usr/src/app/bin/sitespeed.js --preScript=test/performance/login.js --config=test/performance/config.json -n 10 test/performance/url.txt`

`/usr/src/app/bin/sitespeed.js --preScript=test/performance/login.js --config=test/performance/config.json -n 15 test/performance/url.txt`

**Comment by sureshkrishnaselvam** [comment]
Thank you @soulgalore is there any other way to execute the test in a single CLI with multiple set of iterations by passing the iteration value to config file like parametrisation.

**Comment by soulgalore** [comment]
No. Can you explain a little about your use case?

**Comment by sureshkrishnaselvam** [comment]
Since we execute the test in jenkins every-time we need to change the number of iterations to execute. So, instead of changing can we pass iteration number as data parameter to config file. 
In that case we can select any one set of iteration either 5 or 10 or 15 to execution with one config file, one CLI execution command.

**Comment by soulgalore** [comment]
I didn't fully understand. You test the same URLs/pages with same configs but sometimes you wanna do different iterations?

**Comment by sureshkrishnaselvam** [comment]
Yes @soulgalore thats correct.

**Comment by soulgalore** [comment]
Yes but why can't you have multiple lines and call it multiple times?

**Comment by soulgalore** [comment]
We don't support multiple runs in one config.
