### ISSUE TITLE
ERROR: Could not add meta data to the HAR, miss page 0

### ISSUE THREAD

**Issue by yangying05** [sitespeedio/sitespeed.io#2828]
hi，

I want to record different operation in the same page(the url is not changed) and generate a report for each operation. For example, navigation to http://sitespeed.io/video/, then play the video. I want to record the info after click the play button. 

**[Command]:**
`docker run --rm -v /d/dev/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io:11.9.2 --plugins.list --browsertime.chrome.collectPerfLog  --multi test_sitespeed.js -n 1`

**[test_sitespeed.js]:**
```
module.exports = async function (context, commands) {
    // First test a couple pages with default page complete check
    await commands.navigate('https://www.sitespeed.io/video/');
    try {
        await commands.measure.start('PlayVideo');
        //click play btn
        await commands.click.byXpathAndWait('//*[@data-id=\'eJ9apclVo7Q\']');

        return commands.measure.stop();
    } catch (e) {
        throw e;
    }
};

```

**[log]:**
```
Google Chrome 79.0.3945.79
Mozilla Firefox 71.0
[2019-12-25 03:57:40] INFO: Versions OS: linux 4.9.184-linuxkit nodejs: v12.13.0 sitespeed.io: 11.9.2 browsertime: 7.8.1 coach: 4.3.0
[2019-12-25 03:57:40] INFO: The following plugins are enabled: assets, browsertime, budget, coach, domains, harstorer, html, metrics, pagexray, text, thirdparty, tracestorer
[2019-12-25 03:57:40] INFO: Running tests using Chrome - 1 iteration(s)
[2019-12-25 03:57:45] INFO: Navigating to url https://www.sitespeed.io/video/ iteration 1
[2019-12-25 03:57:54] INFO: Start to measure PlayVideo
[2019-12-25 03:58:00] ERROR: Could not add meta data to the HAR, miss page 0
[2019-12-25 03:58:00] INFO: https://www.sitespeed.io/video/ backEndTime: 1.32s, firstPaint: 1.98s, firstVisualChange: 0ms, DOMContentLoaded: 1.98s, Load: 3.46s, speedIndex: 0, visualComplete85: 0ms, lastVisualChange: 0ms, rumSpeedIndex: 2902
[2019-12-25 03:58:00] ERROR: Could not find the right index 0 for har for url https://www.sitespeed.io/video/
[2019-12-25 03:58:00] ERROR: Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/webcoach/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/webcoach/lib/index.js:130:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:229:29)
[2019-12-25 03:58:01] INFO: HTML stored in /sitespeed.io/sitespeed-result/test_sitespeed_js/2019-12-25-03-57-40
```

**Comment by soulgalore** [comment]
Hi @yangying05 at the moment you can only measure navigations. What you can do is wrap everything in a start/stop and then add your own User Timing for the thing you want measured, that will be picked up.

Best
Peter

**Comment by serputko** [comment]
Hi @soulgalore, I have a similar problem like described here. Could you give some example of how to provide custom user timing in script to be picked up by sitespeed?
Many thanks :)

**Comment by serputko** [comment]
@soulgalore Well I was finally able to make it working but still have a question. 
In my scenario, I want to open a page, measure its timings then put search query in the field and measure how long it takes to get search suggestions(ajax call without navigation). As you suggested I've tried User Timings and here is the code I've used

 ```
    //open web page and get all timing metrics
    await commands.measure.start('https://example.com');
    
    await commands.measure.start('search');
    await commands.navigate('https://example.com');
    //set start point for custom measurement
    await commands.js.run('performance.mark("start")');
    await commands.click.bySelector('.rd-navbar-search-toggle');
    await commands.addText.byId('trim', 'search');
    await commands.wait.byXpath('//*[@id="search_autocomplete"]//*[@class="amsearch-item product-item"]', 5000);
    //set end point for custom measurement
    await commands.js.run('performance.mark("end")');
    await commands.js.run('performance.measure("search_completed", "start", "end")');
    return commands.measure.stop();
```
Search measurement is not working if remove `await commands.navigate('https://example.com');` it throws `ERROR: Could not find the right index 2 for har for url`. You may say that i can just remove first call for URL(await commands.measure.start('https://example.com');) and leave this structure:
```
start()
navigate()
performance.mark("start")
...
performance.mark("end")
stop();
```
But i want to see user actions list on 'Pages' page in report and to do this i need to create separate measure.start('user action name'). Is it possible to avoid this extra usage of navigate() command while calculating custom user action timings if assuming that user is not changing the page?

Thanks

**Comment by serputko** [comment]
@soulgalore One more observation, video could not be added to second page if the same url is used in navigate() step, for example
```
//open web page and get all timing metrics
   await commands.measure.start('https://example.com');
   
   await commands.measure.start('search');
   await commands.navigate('https://example.com');
```
Getting next error:
`ERROR: [browsertime.video] The video recording start is zero, either no orange is there in the video or VisualMetrics failed: {"visualMetrics":{"SpeedIndex":7584,"FirstVisualChange":1097,"LastVisualChange":14742,"ContentfulSpeedIndex":-1,"videoRecordingStart":0,"PerceptualSpeedIndex":5838,"VisualProgress":"0=0%, 1097=53%, 1130=85%, 1355=57%, 1613=56%, 1646=57%, 2065=53%, 2097=52%, 2710=53%, 3162=54%, 3226=54%, 3936=54%, 4452=54%, 4839=53%, 6388=53%, 8065=52%, 8807=50%, 14742=100%","VisualReadiness":13645,"VisualComplete85":14742,"VisualComplete95":14742,"VisualComplete99":14742}}`
But if change `await commands.navigate('https://example.com');` to await `commands.navigate('https://example.com?dummy');` video is saved fine

**Comment by soulgalore** [comment]
Hi @serputko can you please create a new bug for the problem with the same URL? We have a fix for that but it seems that there's bug or use cases that I missed. 

> . Is it possible to avoid this extra usage of navigate() command while calculating custom user action timings if assuming that user is not changing the page?

No sorry, at the moment all metrics are tied to a page. Depending on what metrics that you focus on you could potentially skip that first measurement? But the last visual change and other metrics would be affected.

**Comment by voboshi** [comment]
@serputko thank you, your snippet helped me get over the same hurdle. :)

**Comment by Myvryn** [comment]
Are there plans to implement measuring things such as forms submission in the near future?

**Comment by soulgalore** [comment]
@Myvryn what would you measure/how would it work? You can measure submitting a form with scripting but Im thinking that's not the same of what you mean?

**Comment by Myvryn** [comment]
Well, currently, using selenium, we measure using c#'s stopwatch. So going from the time that we click the submit button to the time we see a response on the web page.

In the case of sitespeed.io, I was hoping there might eventually be a mechanism for timing the start of network traffic (clicking the submit button) and the time the server responds back with a message stating the form was submitted correctly. 

I haven't delved into the browsertime code, so it's kinda black box to me at the moment, and probably just a bunch of wishful thinking on my part.

**Comment by soulgalore** [comment]
@Myvryn no there's nothing low level going on. If there's a post and a new page, you will get the visual metrics (when things is painted on screen).

**Comment by Myvryn** [comment]
Yeah... unfortunately on this one, there is no new page. Just the closing of a modal dialog and a "toast" that pops up saying the form was submitted successfully.
Oh well..

**Comment by soulgalore** [comment]
Do you own the page so you can create your own [User Timing](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) on the page?

**Comment by Myvryn** [comment]
We do... and that looks like it might be an option. Thanks.

**Comment by Myvryn** [comment]
You can close this issue.
