### ISSUE TITLE
Broken documentation link for configure-metrics.

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#2837]
The following link is broken and responds with 404. 

**https://www.sitespeed.io/documentation/sitespeed.io/configure-metrics/**

Can be found in the more detail section of the documentation under configure metrics. 

https://www.sitespeed.io/documentation/sitespeed.io/

**Comment by soulgalore** [comment]
Hi @kmaqsudi that pages mysterious dissapeared  with a refactor, I pushed it now so it should work.
