### ISSUE TITLE
Sitespeed - Issue with script , need help:- Is there an alternative to "commands.click.byIdAndWait" with element Value instead of ID? 

### ISSUE THREAD

**Issue by HNarek** [sitespeedio/sitespeed.io#2840]
Is there an alternative to "commands.click.byIdAndWait" with element Value instead of ID? 
The log in button in the page doesn't have an ID, instead it has a value which is "Log in".
I tried "commands.click.byValueAndWait"
but got this error 
"ERROR: TypeError: commands.click.byValueAndWait is not a function"

**Comment by soulgalore** [comment]
Hi @HNarek you have couple of different ways checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#click

And then you can checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#finding-the-right-element 

Hope that helps!

**Comment by HNarek** [comment]
Great Thanks @soulgalore !
