### ISSUE TITLE
Video record could not be added to second page if the same url is used in navigate() step

### ISSUE THREAD

**Issue by serputko** [sitespeedio/sitespeed.io#2842]
One more observation, video could not be added to second page if the same url is used in navigate() step, for example
```
//open web page and get all timing metrics
   await commands.measure.start('https://example.com');
   
   await commands.measure.start('search');
   await commands.navigate('https://example.com');
```
Getting next error:
```
ERROR: [browsertime.video] The video recording start is zero, either no orange is there in the video or VisualMetrics failed: {"visualMetrics":{"SpeedIndex":7584,"FirstVisualChange":1097,"LastVisualChange":14742,"ContentfulSpeedIndex":-1,"videoRecordingStart":0,"PerceptualSpeedIndex":5838,"VisualProgress":"0=0%, 1097=53%, 1130=85%, 1355=57%, 1613=56%, 1646=57%, 2065=53%, 2097=52%, 2710=53%, 3162=54%, 3226=54%, 3936=54%, 4452=54%, 4839=53%, 6388=53%, 8065=52%, 8807=50%, 14742=100%","VisualReadiness":13645,"VisualComplete85":14742,"VisualComplete95":14742,"VisualComplete99":14742}}
```
But if change 
`await commands.navigate('https://example.com');` 
to 
`await commands.navigate('https://example.com?dummy');` 
video is saved fine

**Comment by soulgalore** [comment]
Thank you @serputko for creating the issue, I'll have a look tonight or early tomorrow.

**Comment by serputko** [comment]
@soulgalore Hi, any news about this?

**Comment by soulgalore** [comment]
BTW maybe I misunderstood, the problem is the error message? That message has been removed in the next coming stable version. It reported that it wasn't anything to remove from the start of the video but it should actually only report if Visual Metrics couldn't get any metrics. Yeah, that error message is confusing.

**Comment by serputko** [comment]
Thank you @soulgalore 
Could you also clarify me next behavior. I have the steps to open cart and change product quantity in script:

```
//Open cart
//click.bySelectorAndWait('a.showcart'); opens page with domain/checkout/cart/ url
        await commands.click.bySelectorAndWait('a.showcart');
        await commands.wait.byXpath("//*[contains(@class,'viewcart')]", 5000);
	await commands.measure.start('Open cart');
	await commands.click.bySelectorAndWait('a.viewcart');
	await commands.measure.stop();

//Update quantity
// Here i change quantity and click Update button which triggers /update_quantity request with 302 Found response
// Redirect is to the same url, but quantity is updated
    await commands.wait.byXpath("//*[contains(@class,'input-text qty')]", 5000);
    await commands.wait.byXpath("//*[contains(@class,'action update')]", 5000);
    await commands.measure.start('Update cart');
    await commands.addText.bySelector('2', 'input.qty');
    await commands.click.bySelectorAndWait('button.update');
    await commands.measure.stop(); 

```

What i have in logs:

[2020-01-24 15:41:11] INFO: Start to measure Open cart
[2020-01-24 15:41:30] INFO: Start to measure Update cart
[2020-01-24 15:41:49] INFO: https://domain/checkout/cart/ has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs


Looks like everything works fine here
but at the end i see

[2020-01-24 15:43:57] ERROR: Could not read filmstrip dir Error: ENOENT: no such file or directory, scandir '/sitespeed.io/output/pages/domain/checkout/cart/query-6bc054f4/data/filmstrip/1''
[2020-01-24 15:43:57] ERROR: Could not read filmstrip dir Error: ENOENT: no such file or directory, scandir '/sitespeed.io/output/pages/domain/checkout/cart/query-6bc054f4/data/filmstrip/1''

and there is no video and filmstrip available. At the same time metrics and waterfall are available.
If i understand correctly this case should be handled by sitespeed itself

**Comment by soulgalore** [comment]
Yeah it seems something isn't right. Can you see something in the video or screenshot? The filmstrip is generated from Visual Metrics when it uses the video to get SpeedIndex and other metrics. Either that fails, or could it be it uses the wrong URL in our code. If you check the result folder, do you have the data for two pages?

**Comment by serputko** [comment]
Hello @soulgalore , thanks for your help. 
No, i do not have video folder for both pages: _/checkout/cart_ and _/checkout/cart/?browsertime_run=2_
At the same time i'm able to see all metrics for that pages, except video and filmstrip
![image](https://user-images.githubusercontent.com/16308826/73128424-d4448400-3fd7-11ea-9bd6-57ca9d9b7507.png)
![image](https://user-images.githubusercontent.com/16308826/73128427-de668280-3fd7-11ea-89cc-97fc81b84532.png)
![image](https://user-images.githubusercontent.com/16308826/73128446-38ffde80-3fd8-11ea-9bf9-3776bd7f1d91.png)
![image](https://user-images.githubusercontent.com/16308826/73128449-4917be00-3fd8-11ea-8c77-dc76ffe1931e.png)
![image](https://user-images.githubusercontent.com/16308826/73128455-58970700-3fd8-11ea-9cab-86b84a327418.png)
![image](https://user-images.githubusercontent.com/16308826/73128462-77959900-3fd8-11ea-915e-6c10115eaa44.png)

**Comment by soulgalore** [comment]
Ok, I wonder if there's a bug where we use the wrong path. Let me try to reproduce.

**Comment by soulgalore** [comment]
Yep I could reproduce running my example in https://github.com/sitespeedio/sitespeed.io/issues/2842#issuecomment-577706048 (sorry I did it without the video turned on the last time). 

Let me try to fix it the coming days.

**Comment by soulgalore** [comment]
This is fixed in https://github.com/sitespeedio/browsertime/pull/1161

There was bug that made us use wrong URL for the video. The next release going out when Chrome 80 is released in a couple of days.

**Comment by soulgalore** [comment]
This works now in 12.0.0 in the tests I've done, can you please check @serputko if it works for you? My test case was quite simple so want to be sure.

**Comment by serputko** [comment]
@soulgalore works for me too. many thanks
