### ISSUE TITLE
Setting --browsertime.requestheader host:... does not work anymore

### ISSUE THREAD

**Issue by eserte** [sitespeedio/sitespeed.io#2845]
It was possible to set the HTTP Host header until sitespeed 9.7.0. For example:
```
$ docker run --rm -v $(pwd)/sitespeed:/sitespeed.io sitespeedio/sitespeed.io:9.7.0 --browsertime.iterations 1 -b chrome --browsertime.requestheader host:www.sitespeed.io https://www.sitespeed.io/
```
Starting with sitespeed 9.8.0 this uses to hang for five minutes and fails eventually, and this is still the case with recent sitespeed:
```
$ docker run --rm -v $(pwd)/sitespeed:/sitespeed.io sitespeedio/sitespeed.io:11.9.3 --browsertime.iterations 1 -b chrome --browsertime.requestheader host:www.sitespeed.io https://www.sitespeed.io/
Google Chrome 79.0.3945.79 
Mozilla Firefox 71.0
[2020-01-15 13:19:19] INFO: Versions OS: linux 4.4.0-21-generic nodejs: v12.13.0 sitespeed.io: 11.9.3 browsertime: 7.8.3 coach: 4.3.0
[2020-01-15 13:19:19] INFO: Running tests using Chrome - 1 iteration(s)
[2020-01-15 13:19:20] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2020-01-15 13:24:24] ERROR: Failed to wait BrowserError: Running page complete check 
return (function(waitTime) {
    try { 
        const end = window.performance.timing.loadEventEnd;
        return (end > 0) && (Date.now() > end + waitTime);
    } catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long 
[2020-01-15 13:24:24] ERROR: Could not load URLUrlLoadError: Failed to wait 
[2020-01-15 13:24:24] ERROR: UrlLoadError: Failed to load https://www.sitespeed.io/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:226:13)
[2020-01-15 13:24:24] INFO: https://www.sitespeed.io/ 
[2020-01-15 13:24:25] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2020-01-15-13-19-19
```
Looking at the gi logs it seems that the change between 9.7.0 and 9.8.0 was the update to Chrome 76.

Maybe this is difficult or even impossible to fix, and `Host` is a rather special HTTP header, so if this is not fixable, then maybe browsertime may croak if the user tries to set this header.

**Comment by soulgalore** [comment]
Hi @eserte thanks for reporting! I've tested on the master branch of Browsertime and I could see that there the header is set but there are some error logs. I'm in the middle of preparing a new major release of Browsertime (with a lot of new stuff for Firefox), I hope I can release the stable version next week but I can release a alpha/beta with sitespeed.io late this week ... but let me fix the problem first. I'll look into tonight or early tomorrow. 

Best
Peter

**Comment by emalihin** [comment]
hey, this still doesn't work for me?

**Comment by soulgalore** [comment]
Setting headers work I verified that but there's something special with how the host header is handled right?

**Comment by emalihin** [comment]
@soulgalore it works well with `-b firefox`, but chrome throws the same error as for OP

**Comment by soulgalore** [comment]
You can verify that it works with:
`sitespeed.io  https://httpbin.org/headers --browsertime.requestheader "test:test" -n 1`

For the host header, I would try CDP in scripting and see if that works.
