### ISSUE TITLE
Sitespeed - Issue with script , need help:- Wanted to know if there's a sample script for login with 2-factor Authentication.

### ISSUE THREAD

**Issue by HNarek** [sitespeedio/sitespeed.io#2848]
Hi,

Wanted to know if the prescript can only be a .js file (I must only use NodeJS) or
I can write a python script instead (.py) ? 
If it's only .js, by any chance do you have a sample script for login with 2-factor Authentication?
To be exact, After inputing login and pass I receive an email with an auth code which I have to input to log in. 

P.S. Thanks for the quick reply to my previous question.

**Comment by soulgalore** [comment]
Hi @HNarek it needs to be a NodeJS script.

Best
Peter
