### ISSUE TITLE
setting user agent doesn't seem to be working 

### ISSUE THREAD

**Issue by monalisatripathhy** [sitespeedio/sitespeed.io#2850]
Running on Mac through docker and trying to set the user agent through --browsertime.userAgent, --userAgent, but not getting set with the new one. Could you please let me know if anything is missing from my end ?

**Comment by soulgalore** [comment]
Hi @monalisatripathhy no I think that is the right way. Can you check against  https://httpbin.org/headers and verify? That page prints out the request headers with the agent so it's easy to see if it works or not.

**Comment by monalisatripathhy** [comment]
The page (https://httpbin.org/headers)seems to be displaying an user agent which is really specific to app, but when I set that in my docker command it doesn't take the same. Though it takes the mweb one. Any idea why ? e.g. the site prints : Mozilla/5.0 (Linux; Android 6.0; Google Nexus 6 - 6.0.0 - API 23 - 1440x2560 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36; MyntraRetailAndroid/4.1912.5 (Phone, 560dpi); MyntraAndroid/4.1912.5 (Phone, 560dpi)
But it takes : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

**Comment by soulgalore** [comment]
Hi again, httpbin display the actual agent used that is picked up by the server. If you check in the HAR I'm not 100% it pick the right one. So if you run against httpbin and check the screenshot, you can see the user agent that is used.

**Comment by monalisatripathhy** [comment]
when I override the useragent with **Mozilla/5.0 (Linux; Android 6.0; Google Nexus 6 - 6.0.0 - API 23 - 1440x2560 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36; MyntraRetailAndroid/4.1912.5 (Phone, 560dpi); MyntraAndroid/4.1912.5 (Phone, 560dpi)** in my docker command and execute it I don't get the expected snapshot also in browsertime.har file I could see a different user agent. There is a mismatch which is causing the issue. So could you please let me know why the newly set user agent is not being picked up ?

**Comment by monalisatripathhy** [comment]
Hi @soulgalore Could you please update if we have any progress on this ? Is it working fine at your end if you set a new user agent in chrome ? It's mandatory for our website as need to verify few stuff using a specific user agent.

**Comment by soulgalore** [comment]
Can you show me how it doesn't work, follow the instructions in https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ ? That helps a lot so I can reproduce the issue on my side.

**Comment by monalisatripathhy** [comment]
This is how I am running my test
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:11.9.3 https://www.myntra.com/checkout/cart --browsertime.userAgent "Mozilla/5.0 (Linux; Android 6.0; Google Nexus 6 - 6.0.0 - API 23 - 1440x2560 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36; MyntraRetailAndroid/4.1912.5 (Phone, 560dpi); MyntraAndroid/4.1912.5 (Phone, 560dpi)" --mobile true -n 1 -c 3gfast --cookie at=zz

As I mentioned above I am using docker on mac (10.13.6)

So basically I am trying to run sitespeed on one of the webview with Android(native) user agent , but after execution it still shows me the mweb view instead of native app view. Ideally if you look into both the attached screenshots the header shouldn't be displayed after setting the useragent, but I am getting it as it still points to the mweb user agent. so in this case setting user agent doen't seem to create any difference.
<img width="1440" alt="Actual_Snapshot" src="https://user-images.githubusercontent.com/33315994/72816070-a4227b80-3c8d-11ea-9213-c7f1d6662049.png">
<img width="1440" alt="Expected_Snapshot" src="https://user-images.githubusercontent.com/33315994/72816095-ac7ab680-3c8d-11ea-8308-604c61d06721.png">

**Comment by monalisatripathhy** [comment]
@soulgalore Please let me know if you need more details to debug the issue

**Comment by monalisatripathhy** [comment]
@soulgalore Closing this as got the issue. Actually in my docker command I was providing --mobile so it was not taking the android app UA. After removing that it works as expected. Thanks for the support
