### ISSUE TITLE
Axe.Checks Not Filtering

### ISSUE THREAD

**Issue by gfoxCartrawler** [sitespeedio/sitespeed.io#2854]
Using Axe.checks does not filter axe for accessibility testing. I am unsure how the checks object should look. 

I have tried an array of objects and just an object with no luck. Any help would be appreciated.

- Exact how you run (the exact parameters)
`docker run --rm -v "$(pwd)":/sitespeed.io  sitespeedio/sitespeed.io:11.2.0 flash/selenium/accessibility-smartblock/scenario.js --multi --debug --browsertime.scenarioName accessibility-smartblock -n 1 --config flash/config-accessibility.json`

```
Config:
{
  "gzipHAR": true,
  "useHash": true,
  "verbose": true,
  "multi": true,
  "axe": {
    "enable": true,
    "checks": {
      "id": "area-alt"
    }
  },
  "html": {
    "fetchHARFiles": true,
    "showScript": true
  },
  "screenshot": {
    "type": "jpg"
  },
  "filmstrip": {
    "showAll": true
  },
  "browsertime": {
    "iterations": 1,
    "browser": "chrome",
    "pageCompleteWaitTime": 15000,
    "visualMetrics": false,
    "video": false
  },
  "metrics": {
    "filter": [
      "*-",
      "browsertime.pageSummary.statistics.timings.pageTimings.*",
      "browsertime.pageSummary.statistics.coach.*",
      "browsertime.summary.pageTimings.*"
    ]
  }
}
```
- Which version you are using
11.20 -> 11.9.3
- OS (if you use Docker, report the base OS)
Docker, Mac OS
- Browser version (if you don't run Docker)

**Comment by soulgalore** [comment]
Hi @gfoxCartrawler thank for including so much in the issue!

Sorry had a rough couple of days so I'm a little slow: You mean you wanna run just one type of AXE tests but it doesn't work?

**Comment by gfoxCartrawler** [comment]
No worries at all, sorry for the confusion. The example above is just trying to filter by 1 rule but I probably need to filter by 6 or 7 rules.Either way the axe tests will still run against all rules set in the axe-core library.

I was just going off the documentation here https://www.sitespeed.io/documentation/sitespeed.io/axe/#configure-axe
Not sure if I am setting the configuration incorrectly or its an actual issue in the sitespeed library.

**Comment by gfoxCartrawler** [comment]
@soulgalore Is there any update to this?

**Comment by soulgalore** [comment]
No I haven't had a look. Did you follow the AXE configuration at https://github.com/dequelabs/axe-core/blob/master/doc/API.md#api-name-axeconfigure ?

**Comment by gfoxCartrawler** [comment]
Hi @soulgalore  I had a look but still the same result.

I have ran a test directly through the axe-core library and this works when passing rules to`axe.configure`. example axe.configure( {
    "rules": [{
      "id":"accesskeys",
      "enabled": false
    },
    {
      "id":"aria-allowed-role",
      "enabled": false
    }]})

It seems when I run the sitespeed tests `context.options` does have not the axe object set (returning undefined) and as a result the line here https://github.com/sitespeedio/sitespeed.io/blob/v12.0.0/lib/plugins/axe/axePostScript.js#L8 does not resolve to true.

**Comment by gfoxCartrawler** [comment]
Hi @soulgalore I have opened a small P.R to fix the axe filtering.
