### ISSUE TITLE
Provision for setting the Cookie for domain explicitly instead of taking the domain that we test

### ISSUE THREAD

**Issue by MonalisaT** [sitespeedio/sitespeed.io#2856]
For setting cookie we just use --cookie name=value and the cookie will be set on the domain that you test(here it's www.myntra.com). By any chance if we can reset the domain to .myntra.com instead of the default www.myntra.com while setting the cookie in docker command of sitespeed then that will be useful for us to handle few specific cases . Please help me in adding this functionality as well.

**Comment by soulgalore** [comment]
There's a branch where I tried to fix this: https://github.com/sitespeedio/browsertime/tree/cookies-part-2

However this should be fixable by running scripting and using CDP.

**Comment by soulgalore** [comment]
Today you can only do that with scripting and CDP.
