### ISSUE TITLE
Add more runtime info (Feature request)

### ISSUE THREAD

**Issue by AAZANOVICH** [sitespeedio/sitespeed.io#2860]
Would be great to have 4g connectivity preset (it is 2020 btw ;). Something similar to Lighthouse 4g Slow.

**Comment by soulgalore** [comment]
Hi @AAZANOVICH I've added it to the coming release (released later this week). You can also always set your own custom profile if you use Throttle or if you use Docker networks you can just create your own network.

Best
Peter

**Comment by AAZANOVICH** [comment]
@soulgalore I know, but this tool already have preset which is convenient, so good to have presents which actually used in real life. I thing 4g is more relevant today. Also if it matches to presets of Lighthouse then it makes life easier. Anyway thanks !

**Comment by soulgalore** [comment]
Released of 12.0.0. I would take the connectivity with a pinch of salt. Comparing a connectivity setting with the real world is hard. I'm more thinking of the connectivity of a way to make sure that the tests have the same setup all the time and by slowing down the connectivity its easier to see some problems.

**Comment by AAZANOVICH** [comment]
You are right, there are way more variables when you run tests in real world and results might differ significantly from test to test. However you need a way to test your changes and see whether they improve performance or not and overall track the progress. So, throttling speed is a useful option in that case and it good to keep it as close as possible to real world. Overall even metrics calculations have its own issues and flaws ..

**Comment by AAZANOVICH** [comment]
@soulgalore I think would be great to print Runtime Settings on report, because it is not clear which settings were used, even if a pass parameter  --network=5g it will not give any error and will generate report. I ran with --network=3g then --network=4g, I can't even tell whether 4g was working or not, or it was 3g in both cases, and I can't see Runtime Settings I can't compare with other tools ...

Would be great to add Runtime Settings in report, like Lighthouse does:

Runtime Settings
URL
https://www.apple.com/
Fetch time
Feb 18, 2020, 7:19 PM PST
Device
Emulated Nexus 5X
Network throttling
150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling
4x slowdown (Simulated)
User agent (host)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
User agent (network)
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse
CPU/Memory Power
1604

**Comment by soulgalore** [comment]
I've added some of this in the latest release (released this morning):
<img width="1203" alt="Screenshot 2021-04-27 at 15 59 45" src="https://user-images.githubusercontent.com/540757/116254433-a10c1a00-a771-11eb-9c3a-735d7910c277.png">

I'm gonna add some docs next week :)
