### ISSUE TITLE
Unable to locate li elements within the HTML code

### ISSUE THREAD

**Issue by shawneenc** [sitespeedio/sitespeed.io#2870]
sitespeed version - 11.0.0
Running code locally from command line (norm use chrome)

I am trying to locate an element contained within a list on my website.  I have tried using switchToFrame by using the ID of the frame - this was unsuccessful.  I have also tried directly locating the element within the list by its xpath, etc.  All with no success.

I have spent a long time on this and have been unable to find anything within the sitespeed docs, or online to help.

can someone please advise?

HTML CODE SNIPPET (attached below):
<img width="1029" alt="Screenshot 2020-02-13 at 13 56 37" src="https://user-images.githubusercontent.com/55998417/74442235-0e7fa380-4e69-11ea-8695-7c2f634db5e6.png">

COPY OF MY .JS CODE:
`module.exports = async function(context, commands) {

const BASE_URL = context.options.url
const LOGIN_NAME = context.options.login
const PASSWORD = 'Test1234'

  // We start by navigating to the login page.
  await commands.measure.start('Access login page')
  await commands.navigate(BASE_URL)
  await commands.measure.stop()

  try {
    await commands.addText.byId(LOGIN_NAME, 'loginName');
    /* Two Step Authentication Check 
      Currently wrapping in a try catch until all environments
      have the feature enabled.
    */
   try {
    context.log.info('Checking for Two Step Authentication');
    const nextButton = '//div/button[.="Next"]';
    await commands.wait.byXpath(nextButton,10000);
    await commands.click.byXpath(nextButton);
    await commands.wait.byId('password',10000);
  } 
    catch (e) {
      context.log.info(`Two Step Authentication Flow - Not Found. Ignore if TwoStepLogin is not enabled. Actual Error: ${e}`);
  }
    await commands.addText.byId(PASSWORD, 'password');

    await commands.measure.start('login');
    await commands.click.byXpathAndWait('//button');
    await commands.wait.byXpath('//a[@class="NavBar---tabItem---180LI"]')
    await commands.measure.stop();

    await commands.measure.start('navigate to user listing report')
    await commands.click.byXpath('//a[@class="NavBar---tabItem---180LI"]')
    await commands.wait.byTime(10000)
    await commands.switch.toFrame('navbar-menu-Reports-menu')
    await commands.click.byXpathAndWait('//a[@href="/admin/report/learner-activity"]')
    return commands.measure.stop()
    
  } catch (e) {
    context.log.error(e);
    return commands.measure.stop();
    // We try/catch so we will catch if the the input fields can't be found
    // The error is automatically logged in Browsertime and re-thrown here
  }
};
`

**Comment by soulgalore** [comment]
Hi @shawneenc I usually use JS directly so using devtools I try until I get the correct JS to work and then I use js.run or js.runAndWait (if I click on something in the JS that will navigate to a new page): https://www.sitespeed.io/documentation/sitespeed.io/scripting/#jsrunjavascript

Hope that helps!

**Comment by shawneenc** [comment]
Hi @soulgalore, thanks for your response - So are you saying that you use javascript in the browser to pinpoint a locator to use within the .js sitespeed test file?  I had a look at the sistespeed docs for doing this, but it was very vague..  Where do you enter the javascript, i.e. within the console in devtools?

**Comment by shawneenc** [comment]
Hi @soulgalore - just wondering if you have any update on this?  Thanks

**Comment by soulgalore** [comment]
Hi @shawneenc if you use Chrome you can write your JavaScript in the console in Devtools:
<img width="1595" alt="Screenshot 2020-02-17 at 10 46 51" src="https://user-images.githubusercontent.com/540757/74642205-da5ef800-5172-11ea-9957-861d5e817832.png">

And to run it in the browser through sitespeed.io: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#run-javascript

**Comment by shawneenc** [comment]
Hi @soulgalore - have tried this suggestion, as well as many others and there is no way i can obtain, or reach these elements..  Do I need to open a bug with sitespeed?  There is a page that we cannot performance test, due to this

**Comment by shawneenc** [comment]
Hi @soulgalore - Just wondering if you can offer any other help here?  I have spent a long time on this and have not been able to come up with anything that works.  Elements can not be interacted with.  We have a full site that is made up with this type of code and all the dropdowns are written with this code structure.  We are unable to performance test any of it using sitespeed.  Maybe we should consider another tool ?

**Comment by soulgalore** [comment]
Hi @shawneenc can you do what you need through Selenium? So there's nothing magic in sitespeed.io either you use Selenium or our help classes or you use JS directly. If you could share the URLs and follow https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ to make a reproducible its much easier for me to understand what doesn't work and maybe possible to help out.

**Comment by soulgalore** [comment]
Don't see this as a sitespeed.io issue.
