### ISSUE TITLE
Allow first party ONLY resources in budget file

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#2871]
Currently we are only able to add 3rd party resources or All resource types (first and third) in the budget file.  I would like to be able to track 1st party resources types only.   This is currently captured in sitespeed but not available to budget on.  This limitation currently exists in most tools (lighthouse, WPT+grunt, etc).

**Comment by soulgalore** [comment]
Hi @kmaqsudi ok, so you need a budget like with a limit of for example 5 JavaScript 3rd parties script? Thinking do you really need by type, can you give me an example?

**Comment by kmaqsudi** [comment]
I would like to budget on my base HTML size and main CSS file.  Here is what I see in sitespeed.  see images.  
What I see when defining budgets today:
<img width="1397" alt="currently" src="https://user-images.githubusercontent.com/1022410/74482020-bdc87480-4e81-11ea-9b42-87af5991eadb.png">



What I would like to budget on:
<img width="1392" alt="budget" src="https://user-images.githubusercontent.com/1022410/74482060-d0db4480-4e81-11ea-9382-27746ff8775e.png">

**Comment by soulgalore** [comment]
Ok just so I understand correctly, you need to have like a budget for HTML/JS/CSS that's only includes the first party size, right? That makes sense let me check how hard it is to add,

**Comment by soulgalore** [comment]
Adding requests/transfer/content size is easy, added that in a PR. Adding it per content type needs some refactor, we don't have that today for either first/third party in the budget.

**Comment by kmaqsudi** [comment]
Yes.  Thanks again Peter.

**Comment by kmaqsudi** [comment]
I see third party size per resource type in the example budget file you
already have on the site.  Just not first party only.  Hope that helps.

**Comment by soulgalore** [comment]
Where? :) No I think with the old setup you can do that (its super generic) but the new easier budget format, that metric needs to be defined.

**Comment by kmaqsudi** [comment]
Just checked and it's third party but only requests and transfer size.   My
mistake.

**Comment by soulgalore** [comment]
I think it work ok now, closing.
