### ISSUE TITLE
[Help] Get page performance metrics in a state of cache filled

### ISSUE THREAD

**Issue by luisxiaomai** [sitespeedio/sitespeed.io#2877]
Hello,

I want to get multiple pages performance metrics in a state of cache filled, and also these pages need login firstly using scripts. Currently I can only get the first load performance metrics of these pages? Can I get these metrics in cache filled state?

Thank you.

**Comment by soulgalore** [comment]
Hi @luisxiaomai you can do that with scripting: https://www.sitespeed.io/documentation/sitespeed.io/scripting/ - then the browser is kept open between different pages and the cache is used in the browser.

**Comment by luisxiaomai** [comment]
@soulgalore yes, I used scripting. I need test one page twice, one for no cached resources and one for cached resources. For example, I used bellow codes to test https://www.sitespeed.io/ twice. But the second performance result is not correc,  almost every metric is 0. Is it possible to get correct metrics like what we see in browser devtools, these cached resources are marked from disk or memory. 

```
module.exports = async function(context, commands) {  
    await commands.measure.start('https://www.sitespeed.io/', 'HomePage');
    return commands.measure.start('https://www.sitespeed.io/?dummy', 'BackToHomepage');
}
```
<img width="1078" alt="result" src="https://user-images.githubusercontent.com/6835229/74619004-f19be680-516e-11ea-98b2-0408fa270feb.png">

**Comment by soulgalore** [comment]
Hi @luisxiaomai the waterfall shows the requests sent over the wire. If you are looking for more devtools info, you can catch that on Chrome with `--cpu` (and drag and drop the trace file into your performance tab of devtools)  and on Firefox with  `--firefox.geckoProfiler ` and drag/drop the file into https://profiler.firefox.com

**Comment by soulgalore** [comment]
Closing let me know if you needed more info.
