### ISSUE TITLE
Cannot execute JS that works in Google Chrome Dev Tools console

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2891]
Sitespeed Docker 12.0.1

Given: This command will correctly execute in Chrome console
`$x('.//div[contains(text(),"performance3")]/following-sibling::div')[0].click()`
`div.display-name`

However, the following commands will fail in Sitespeed:
` await commands.measure.start('Select Profile');
 await commands.js.run("($x('.//div[contains(text(),\"performance3\")]/following-sibling::div')[0]).click();");`

With the following error:
`[2020-02-24 17:28:05] INFO: Start to measure Select Profile
[2020-02-24 17:28:06] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: $x is not defined
  (Session info: chrome=80.0.3987.87)
[2020-02-24 17:28:06] ERROR: Could not run JavaScript ($x('.//div[contains(text(),"performance3")]/following-sibling::div')[0]).click(); 
Failed to select profile: Error: Could not run JavaScript ($x('.//div[contains(text(),"performance3")]/following-sibling::div')[0]).click();`

**Comment by soulgalore** [comment]
**$x** is a specific devtools console utility, so you need need to use another to run get elements by xpath, the JS from sitespeed.io doesn't run in the devtolols console context.

**Comment by leathej1** [comment]
OK, understood.
