### ISSUE TITLE
HTML Report permission issue

### ISSUE THREAD

**Issue by lochy89** [sitespeedio/sitespeed.io#2898]
Hi Sitespeed Team.
My problem is: even if i run docker with a specified Linux OS User, the generated reports are always made by the root user. Although the working directory belongs to not root user. The generated user becomes the 0 uid/gid IDs. 

I checked the start script on the line 31-34:

# Create user with the same UID and GID as the owner of the working directory, which will be used
# to execute node. This is partly for security and partly so output files won't be owned by root.
groupadd --non-unique --gid $WORKDIR_GID sitespeedio
useradd --non-unique --uid $WORKDIR_UID --gid $WORKDIR_GID --home-dir /tmp sitespeedio

Do i need to run the container another way?
docker run --rm -v /home/sitespeed/sitespeed/sitespeed-result/:/sitespeed.io/sitespeed-result sitespeedio/sitespeed.io https://www.some-url.com

I'm using the latest version, my OS is Oracle Linux.
Thank you in advance!

**Comment by soulgalore** [comment]
Hi @lochy89 thanks for the report. I'm wondering what's the easiest way for me to try to reproduce?

@MasonM do you know what can be the problem?

**Comment by MasonM** [comment]
This can happen when using [userns-remap](https://docs.docker.com/engine/security/userns-remap/), but I'd need to see the permissions inside the container to be sure.

@lochy89 Can you please run the following command and copy-and-paste the output?
```
docker run --rm -v /home/sitespeed/sitespeed/sitespeed-result/:/sitespeed.io/sitespeed-result --entrypoint="/usr/bin/stat" sitespeedio/sitespeed.io .
```

**Comment by MasonM** [comment]
Oh, and the bind mount in the command you gave looks off:
`-v /home/sitespeed/sitespeed/sitespeed-result/:/sitespeed.io/sitespeed-result`

That should be `-v /home/sitespeed/sitespeed/sitespeed-result/:/sitespeed.io`

**Comment by lochy89** [comment]
Hi @MasonM 

it seems the problem was the wrong bind mount.
It is working with: /home/sitespeed/sitespeed/sitespeed-result/:/sitespeed.io
Thank you!!! : )
