### ISSUE TITLE
VideoJS Fonts output even if video is disabled

### ISSUE THREAD

**Issue by mountainash** [sitespeedio/sitespeed.io#2910]
~45KB of unnecessary fonts are added to the reports outputFolder even when `headless` is true or `video` is false (meaning that no video tests are created - and therefor the fonts are not used).

```
VideoJS.eot
VideoJS.svg
VideoJS.ttf
VideoJS.woff
```

Outputting these fonts can add up "quickly" for storage costs on automated reporting.

I suggest they don't be outputted if they aren't needed.

Test run from "sitespeedio/sitespeed.io:12.1.0".

**Comment by soulgalore** [comment]
Hi @mountainash ok feel free to make a PR. If you wanna minimise the size of the output, have a look at `--html.assetsBaseURL`.

**Comment by mountainash** [comment]
> have a look at `--html.assetsBaseURL`

Thanks for the tip - that could be handy. Are there any (public) CDN's hosting the assets that I could point to simplify this (and save some data for all users)?

**Comment by mountainash** [comment]
Found something:
```sh
--html.assetsBaseURL https://cdn.jsdelivr.net/npm/sitespeed.io@12.1.0/lib/plugins/html/assets/
```
OR
```json
  "html": {
    "assetsBaseURL": "https://cdn.jsdelivr.net/npm/sitespeed.io@12.1.0/lib/plugins/html/assets//"
  }
```
For best results update the version number in the URL to match the version of Sitespeed.io used to generate the results.

**Comment by soulgalore** [comment]
I think I will prio to fix this, so closing but feel free to do a PR if someone needs it.
