### ISSUE TITLE
Create minimal slim container

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2913]
We have the large container that can do everything and it would be nice to try create a slim one with only one browser (Firefox) and see how small we can make it.

**Comment by mrchrisadams** [comment]
LOL, I was about to ask about this yesterday, and wanted to have a go at this, so I'm glad you beat me to it.

I've asked in the mozilla dev-tools slack channel to see if there's any prior work we might build off, as I reckon they'd have a bunch of prior experience doing something along these lines already.

**Comment by soulgalore** [comment]
@mrchrisadams I pushed a branch with an example, but at the moment the sustainable-plugin doesn't work, its not installed because it misses python/make, we could add it in the build step and remove but I'm thinking we make co2.js lean and clean first, we don't need to do that.

**Comment by soulgalore** [comment]
This is pushed as `sitspeedio/sitespeed.io:12.2.2-slim`
