### ISSUE TITLE
Switch to iFrame with INDEX e.g. 0 - doesnt work

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2916]
I see that sitespeed has methods to swith.toFrame(id), toWindow(name), and toParentFrame(name) --- but in some cases iframe doesnt have any name as in our case..

So, selenium recording shows below code

    driver.switchTo().frame(0);

How do I address this in sitespeed scripting --

**Comment by soulgalore** [comment]
If the normal commands doesn't work, you can try the raw Selenium commands: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#use-selenium-directly

**Comment by softwareklinic** [comment]
I'm good -- Instead of using the container holding iframe - i used the
iframe url to load and continue.

<http://www.verizon.com>

Keyur Shah

Associate Fellow - Enterprise Architecture
2147845203

"Defects & waste slow down the progress" - Identify, measure and eliminate.

**Comment by soulgalore** [comment]
Ok!
