### ISSUE TITLE
Getting Invalid JSON config file: config.json when running with docker-compose

### ISSUE THREAD

**Issue by testautonation** [sitespeedio/sitespeed.io#2924]
I am trying to run the following command: 

docker-compose run --rm sitespeed.io --config config.json https://google.com

using the following docker-compose.yml file: 

`version: '3'
services:
    sitespeed.io:
      image: sitespeedio/sitespeed.io
      command: -V
      shm_size: 1g
      volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
    grafana:
      image: grafana/grafana:6.6.2
      depends_on:
        - graphite
      links:
        - graphite
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_SECURITY_ADMIN_USER=sitespeedio
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
      volumes:
        - grafana:/var/lib/grafana
      restart: always
    graphite:
      image: sitespeedio/graphite:1.1.5-12
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        # In production you should configure/map these to your container
        # Make sure whisper and graphite.db/grafana.db lives outside your containerr
        # https://www.sitespeed.io/documentation/sitespeed.io/graphite/#graphite-for-production-important
        - whisper:/opt/graphite/storage/whisper
        # Download an empty graphite.db from https://github.com/sitespeedio/sitespeed.io/tree/master/docker/graphite
        # - /absolute/path/to/graphite/graphite.db:/opt/graphite/storage/graphite.db
        # 
        # And put the configuration files on your server, configure them as you need
        # Download from https://github.com/sitespeedio/docker-graphite-statsd/tree/master/conf/graphite
        # - /absolute/path/to/graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        # - /absolute/path/to/graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        # - /absolute/path/to/graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
    grafana-setup:
      image: sitespeedio/grafana-bootstrap:12.1.0
      links:
        - grafana
      environment:
        - GF_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_USER=sitespeedio
volumes:
    grafana:
    whisper:`

The config.json file is as follows: 

{
  "browsertime": {
    "iterations": 1,
    "browser": "chrome",
    "connectivity": {
     "profile": "3g"
    }
  },
  "webpagetest": {
   "key":"<API Key>",
"runs": 1 },
 "plugins": {
  "add": "/sitespeed.io/plugin-gpsi"
}, "gpsi": {
  "key": "<API Key>"
 },
 "graphite": {
  "host": "graphite"
 },
  "mobile": true
}

I am using Mac OS, docker version: 
Docker version 19.03.8
docker-compose version 1.25.4, build 8d51620a

**Comment by soulgalore** [comment]
Hi @testautonation  if you use `--config config.json` you need to map that directory where you run into the container, else the container can't find the file. Checkout https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes

Best
Peter

**Comment by borgandrea** [comment]
ah it worked, Thanks @soulgalore ! :D

**Comment by testautonation** [comment]
It worked! Thank you so much @soulgalore :D
