### ISSUE TITLE
How do I Write a particular COOKIE Value in the RESULTS Summary Page

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#2934]
Is it possible using the sitespeed or selenium script to write a cookie value in the results summary page... e.g. session id --- it would be helpful if I can write this value on dashboard or push it as a metric to graphite/grafana from where I can link it to the dashboard... where I can debug the session id...

**Comment by soulgalore** [comment]
If you use scripting you can create your own metric like this: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#add-your-own-metrics

**Comment by softwareklinic** [comment]
Yes, I figured out from your pointer... below is sample

        const ig_session = driver.manage().getCookie('digital_ig_session') 
        const am_id = driver.manage().getCookie('amID')
        Promise.all([ig_session, am_id]).then(function(values) {
            console.log(values);
            var fs = require("fs");
            var stream;
            stream = fs.createWriteStream("cookies.json");
            var jsonString = JSON.stringify(values,null, 2);

        commands.measure.add('session_id', values[0].value);
        commands.measure.add('am_id', values[1].value);

Now - im trying to insert it as an HREF -- so from here I can open another grafana dashboard which can take this session id -- and open dashboard with details about that session from elasticsearch logs...

I tried this --         commands.measure.add('Detailed_View', finalUrl);

Where finalUrl -- is the HREF for grafana dashboard with parameters...

Do you have a way I can insert the metric as clickable link or how do I make the session_id cookie value clickable in HTML SUMMARY METRICS

**Comment by soulgalore** [comment]
No there's no way at the moment.
