### ISSUE TITLE
Metrics sent to graphite have the same timestamp

### ISSUE THREAD

**Issue by tsmith8** [sitespeedio/sitespeed.io#2945]
```
// first metric received
graphite-converter    | time="2020-03-26T17:48:01Z" level=debug msg="Incoming line : sitespeed_io.desktop.pageSummary.www_website_com.homepage.chrome.native.browsertime.statistics.timings.pageTimings.backEndTime.median 338 1585244855" source="main.go:119"
graphite-converter    | time="2020-03-26T17:48:01Z" level=debug msg="Sample: {OriginalName:sitespeed_io.desktop.pageSummary.www_website_com.homepage.chrome.native.browsertime.statistics.timings.pageTimings.backEndTime.median Name:sitespeed_io_page_statistics_timings_pageTimings Labels:map[base:sitespeed_io browser:chrome connectivity:native function:median group:www_website_com metric:backEndTime page:homepage path:desktop] Help:Graphite metric sitespeed_io_page_statistics_timings_pageTimings Value:338 Type:2 Timestamp:2020-03-26 17:47:35 +0000 UTC}" source="main.go:158"

// last metric received
graphite-converter    | time="2020-03-26T17:48:28Z" level=debug msg="Incoming line : sitespeed_io.desktop.pageSummary.www_website_com.plp.chrome.native.pagexray.contentTypes.html.headerSize 0 1585244855" source="main.go:119"
graphite-converter    | time="2020-03-26T17:48:28Z" level=debug msg="Sample: {OriginalName:sitespeed_io.desktop.pageSummary.www_website_com.plp.chrome.native.pagexray.contentTypes.html.headerSize Name:sitespeed_io_page_contentTypes Labels:map[base:sitespeed_io browser:chrome connectivity:native group:www_website_com metric:headerSize metricType:html page:plp path:desktop] Help:Graphite metric sitespeed_io_page_contentTypes Value:0 Type:2 Timestamp:2020-03-26 17:47:35 +0000 UTC}" source="main.go:158"
```
See above graphite-converter (https://github.com/prometheus/graphite_exporter) debug output. The timestamp is the same against every metric the converter receives. It appears to correlate with the timestamp of the start of iteration 1 of the first test url.

```
174 func (c *graphiteCollector) processSamples() {
175 	ticker := time.NewTicker(time.Minute).C
176
177 	for {
178 		select {
179 		case sample, ok := <-c.sampleCh:
180 			if sample == nil || !ok {
181 				return
182  			}
183  			c.mu.Lock()
184 			c.samples[sample.OriginalName] = sample
185 			c.mu.Unlock()
186 		case <-ticker:
187 			// Garbage collect expired samples.
188 			ageLimit := time.Now().Add(-*sampleExpiry)
189 			c.mu.Lock()
190 			for k, sample := range c.samples {
191	 				if ageLimit.After(sample.Timestamp) {
192 					delete(c.samples, k)
193 				}
194 			}
195 			c.mu.Unlock()
196 		}
197 	}
198 }
```
https://github.com/prometheus/graphite_exporter/blob/b5150e26bacde4dee36a09f8a5fa0ead2b61852d/main.go

Prometheus graphite_exporter uses the timestamp to calculate when a sample of metrics has expired, with the default sampleExpiry duration set to 5 minutes. As the timestamp is set to the start of the test against all metrics, the exporter stops processing any metrics sent after the duration of the sampleExpiry has expired.

Is it possible for the timestamps to reflect the actual time that each metric was recorded, or to reflect the start of each iteration? We're currently working around the issue by overriding the default sampleExpiry duration.

Thanks.

**Comment by soulgalore** [comment]
Hi @tsmith8 not by configuration but I think we should be able to fix it. Easiest is to at least have the start of each tested URL, then maybe per run. At least for the metrics that comes from Browsertime. I need to think a little how it can be fixed. Let me know if you would have time to do a PR and I can help out, else I probably at least can think about a solution early next week.

**Comment by tsmith8** [comment]
Hi @soulgalore, thanks for the quick reply. Agree that updating the timestamp at the start of each tested URL should be sufficient. There's no immediate urgency on the fix as we have a workaround in place by increasing the sampleExpiry duration of the exporter.

**Comment by soulgalore** [comment]
I think this has changed over time but let me check the code.

**Comment by soulgalore** [comment]
No this is still an issue.

**Comment by soulgalore** [comment]
I think this was fixed sometime ago with https://github.com/sitespeedio/sitespeed.io/blob/main/lib/plugins/graphite/index.js#L157
