### ISSUE TITLE
sitespeed.io fails to start when 9.x version is updated to the latest one

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2948]
Hi there,

I have AWS instance with sitespeed.io 9.8.1 as the latest version. I've pulled the latest for this moment 12.3.1 and look like sitespeed.io failes to start. Please see screen below.
The issue is in mounted volume -v /home/centos/sitespeed:/sitespeed.io. 
As soon as I change it to /home/centos/sitespeed2 everything works as expected.
I'm just interested why it happens such way? -vvv or --debug do not show any info at all.
I know my colleagues faced it since 10 or 11 version.

![image](https://user-images.githubusercontent.com/10085700/78007044-6a818700-7346-11ea-8106-c693195b9d18.png)

**Comment by soulgalore** [comment]
Hi @Icecold777 it then looks like it fails before starting sitespeed.io, meaning there's something in the [start script](https://github.com/sitespeedio/sitespeed.io/blob/master/docker/scripts/start.sh) that caused it to fail.  There was a fix a couple of versions ago that makes sure you can run sitespeed.io and the output files doesn't need to be owned by root, I'm thinking maybe that could be the issue? That fix was https://github.com/sitespeedio/sitespeed.io/pull/2710. 

Can you help me debug it? First try run without sudo and check that the user you use can create files in the current folder.

Then check the fix: https://github.com/sitespeedio/sitespeed.io/pull/2710 - I wonder if there could be something there that doesn't  work on CentOS?
