### ISSUE TITLE
User actions getting failed

### ISSUE THREAD

**Issue by nagarajulrpt** [sitespeedio/sitespeed.io#2949]
Hello team,

Few of my user actions are getting failed when wrapped between commands.measure.start and commands.measure.stop commands. In below script, EnterWorkspace, NavToTab and Logout actions are getting failed but when I place the same user actions commands under Login action it is executing without any issues.

not sure what could be the issue here.

script.js:

module.exports = async function(context, commands) {
 
const webdriver = context.selenium.webdriver;
const driver = context.selenium.driver;    

await commands.measure.start('LaunchURL', 'Launch');
await commands.wait.byId('btnLogin', 100000);
await commands.wait.byTime(30000);  

driver.findElement(webdriver.By.id('inputEmail')).sendKeys('testuser email');
driver.findElement(webdriver.By.id('inputPassword')).sendKeys('password');

await commands.measure.start('Login');
await driver.findElement(webdriver.By.id("btnLogin")).click();
await commands.wait.byId('messageCancelBtn', 300000);
await driver.findElement(webdriver.By.id("messageCancelBtn")).click();
await commands.measure.stop();

await commands.wait.byId('wrapperjqxWorkspaceList',10000);

await commands.measure.start('EnterWorkspace');
const actions = driver.actions();
const exchange = await driver.findElement(webdriver.By.xpath("//div[@id='row0jqxWorkspaceList']/div[1]/div/span[2]/a"));
await actions.doubleClick(exchange).perform();
await commands.wait.byId('documentContent', 180000);
await commands.measure.stop();

await commands.measure.start('NavToTab');
await driver.findElement(webdriver.By.xpath('//li[@id="permissionsModuleTab"]/a')).click();
await commands.wait.byId('contentpermOverviewTreeGrid', 180000);
await commands.measure.stop();

await commands.measure.start('Logout');
await driver.findElement(webdriver.By.xpath("//li[@id='user-menu']/a/span[2]")).click();
await commands.wait.byTime(6000);
await driver.findElement(webdriver.By.xpath("//li[@id='account-logout-option']/a[contains(text(),'Logout')]")).click();
await commands.wait.byTime(5000);
return commands.measure.stop();

};

RunCMD: docker run  --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.3.0 script.js -b chrome -n 1 --multi --spa --html.showScript

**Comment by soulgalore** [comment]
Hi @nagarajulrpt I'm not sure, but I think in your example you should make sure that pages has finished loading.

For example, if you use the scripting pre-made clicks, you should use the ...Wait methods like https://www.sitespeed.io/documentation/sitespeed.io/scripting/#clickbyclassnameclassname . That way, the normal [pageCompleteCheck](https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test) runs to make sure the page has loaded. 

If you don't use it, you can add 
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#waitbypagetocomplete before you run stop, that way you can make sure that the page has finished loading before you stop your test.

**Comment by nagarajulrpt** [comment]
Hi @soulgalore even after using "await commands.wait.byPageToComplete();" also commands are not executing as expected, as I said the script executing commands when I place all commands under login action like below and facing issues when I have additional user actions after login.

module.exports = async function(context, commands) {

const webdriver = context.selenium.webdriver;
const driver = context.selenium.driver;

await commands.measure.start('LaunchURL', 'Launch');
await commands.wait.byId('btnLogin', 100000);
await commands.wait.byTime(30000);

driver.findElement(webdriver.By.id('inputEmail')).sendKeys('testuser email');
driver.findElement(webdriver.By.id('inputPassword')).sendKeys('password');

await commands.measure.start('Login');
await driver.findElement(webdriver.By.id("btnLogin")).click();
await commands.wait.byId('messageCancelBtn', 300000);
await driver.findElement(webdriver.By.id("messageCancelBtn")).click();
//await commands.measure.stop();

await commands.wait.byId('wrapperjqxWorkspaceList',10000);

//await commands.measure.start('EnterWorkspace');
const actions = driver.actions();
const exchange = await driver.findElement(webdriver.By.xpath("//div[@id='row0jqxWorkspaceList']/div[1]/div/span[2]/a"));
await actions.doubleClick(exchange).perform();
await commands.wait.byId('documentContent', 180000);
//await commands.measure.stop();

//await commands.measure.start('NavToTab');
await driver.findElement(webdriver.By.xpath('//li[@id="permissionsModuleTab"]/a')).click();
await commands.wait.byId('contentpermOverviewTreeGrid', 180000);
//await commands.measure.stop();

//await commands.measure.start('Logout');
await driver.findElement(webdriver.By.xpath("//li[@id='user-menu']/a/span[2]")).click();
await commands.wait.byTime(6000);
await driver.findElement(webdriver.By.xpath("//li[@id='account-logout-option']/a[contains(text(),'Logout')]")).click();
await commands.wait.byTime(5000);
return commands.measure.stop();

};

**Comment by soulgalore** [comment]
What kind of errors do you get? Easiest to debug run on your local machine without Docker, or record a video for the full run or take screenshots through out the script to see what's going on see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

**Comment by nagarajulrpt** [comment]
Hi @soulgalore ,

Thanks for the response !!!
"documentContent" object not found with in the provided time as previous doubleClick command not performed as expected.

But, same doubleClick operation performing successfully if i place those commands under login action.

**Comment by soulgalore** [comment]
I think follow the debug steps: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug is a good a way of finding if anything is broken.
