### ISSUE TITLE
[feature request] Upload URL to influx when using aliases

### ISSUE THREAD

**Issue by petemyron** [sitespeedio/sitespeed.io#2950]
If I use aliases with urls, I can't see the actual URL in the results uploaded to influx. The report contains this, but not where the data are aggregated. It's possible I'm just missing it. "Page" contains the alias. 

It would probably be best to upload both separately and _null_ if alias isn't used. So, 

- "alias" should contain, um, the alias
- "url" should contain the URL (I'm not sure if it should be the final, redirected URL, though, or the initial value, and
- "page" should be alias if used, otherwise URL

Thoughts?

**Comment by soulgalore** [comment]
Yes I think this is something I missed, coming from Graphite and not using tags.

**Comment by soulgalore** [comment]
Lets fix this in the generic metric/tag plugin and then implement it in influx/prometheus.
