### ISSUE TITLE
Graphite Annotation message - update

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2959]
From the graphite annotation message, clicking on the 'Result' link opens in 'same tab' whereas clicking on the 'screenshot' opens in 'new tab'. Is it possible to update the message for 'Result' link to include this attribute "target='_blank'"

![image](https://user-images.githubusercontent.com/50423486/79487963-04a02b00-7fe7-11ea-84f8-b2d705d81368.png)

![image](https://user-images.githubusercontent.com/50423486/79487464-467ca180-7fe6-11ea-8719-4c1d2bdc904b.png)

**Comment by nevesing** [comment]
Also, how do I make this change to my current version 12.x using --graphite.annotationMessage

**Comment by soulgalore** [comment]
That is inconsistent. You need to change the source code to fix that.

**Comment by soulgalore** [comment]
This is annoying but we also want to avoid storing to much data in the annotations so I think we will keep it as is.
