### ISSUE TITLE
TSProxy is not working with Sitespeedio 12.7.1

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/sitespeed.io#2978]
Hi there,

We've just upgraded Sitespeedio from 12.5.1 to 12.7.1 and our runs are no longer being executed. It bombs out with no errors when we get to the point where Sitespeedio initiates TSProxy.

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.7.1  https://www.sitespeed.io/ --browsertime.connectivity.engine tsproxy --browsertime.connectivity.profile cable

- Which version you are using - 12.7.1
- OS (if you use Docker, report the base OS) - Ubuntu 18.04

**Comment by soulgalore** [comment]
My guess is that this was introduced when we switched from Python 2.7 -> 3 in the Docker container. I'm pretty sure I tried it on my Mac but probably not in the container. Let me have a go tonight and fix it.

**Comment by soulgalore** [comment]
No the TSProxy script needs to be updated to 3.0, I guess I've missed it and only focused on VisualMetrics when I did the upgrade.

**Comment by soulgalore** [comment]
Yes the problem is Python 3. I created an upstream issue and had a quick go at it myself, but I couldn't get it to work. Lets wait a couple of days and see if we can get help to get it fixed, else I guess we need to install old Python in the container.

**Comment by shaqb** [comment]
Thanks very much @soulgalore!

**Comment by soulgalore** [comment]
Sorry this took a while. I've pushed 12.8.1 where the container use Python 2 instead. Could you please verify that it works for you now @shaqb ?

**Comment by shaqb** [comment]
Hey @soulgalore - looks good now. I've run 12.8.1 with a few urls and TSProxy is back in business. Thanks for quick turnaround!!!
