### ISSUE TITLE
Document how to use client certificate in browser

### ISSUE THREAD

**Issue by znerd** [sitespeedio/sitespeed.io#2979]
I'd like to use a client certificate with sitespeed.io (with the Chrome backend). I've searched the documentation, but I could not find any explanation on how to do this.

Note that the Chrome browser does support the use the certificates installed in the host operating system (e.g. Windows or macOS).

Request: Please document how to use client certificates (e.g. P12) in the any browser (or at least Chrome) used by sitespeed.io.

**Comment by soulgalore** [comment]
Hi @znerd maybe you can help me out if you have some certificates. I think there's a couple of ways to do it:
* For Firefox you can setup your own profile with `--firefox.profileTemplate`, I guess the best is to setup Firefox and then copy that dir and use it. 
* For Chrome my guess is to either create your own Docker file where you add the certificates or ignore them with `--ignore-certificate-errors-spki-list` see https://peter.sh/experiments/chromium-command-line-switches/

I've been lucky that I haven't needed to add extra certificates so far.

**Comment by hellosirandy** [comment]
> I'd like to use a client certificate with sitespeed.io (with the Chrome backend). I've searched the documentation, but I could not find any explanation on how to do this.
> 
> Note that the Chrome browser does support the use the certificates installed in the host operating system (e.g. Windows or macOS).
> 
> Request: Please document how to use client certificates (e.g. P12) in the any browser (or at least Chrome) used by sitespeed.io.

@znerd Have you found any way to insert client key/cert with sitespeed.io? For me I'm trying to test mtls endpoints with sitespeed.io so I think I'm looking for the same thing as you do.
Thanks!

**Comment by hellosirandy** [comment]
Hi @soulgalore, in our case we are trying to run tests on internal mTLS url with sitespeed.io, in which ```ignore-certificate-errors``` won't work. Do you have any suggestion to inserting the key/cert in the request?
Thanks!

**Comment by soulgalore** [comment]
There's no magic in Browsertime/sitespeed.io so if you can do it with your browser you can do it with Browsertime/sitespeed.io. If you run Docker you can add your own extra start script: https://www.sitespeed.io/documentation/sitespeed.io/docker/#extra-start-script - I think you could use that to install extra certificates? 

In our Docker container we install certificates for WebPageReplay, so I think if you can get the mounting right (mounting your certificate into the container you could use the same functionality): https://github.com/sitespeedio/sitespeed.io/blob/main/Dockerfile#L22 (but do it in your start script if you want to avoid creating your own container).

**Comment by soulgalore** [comment]
It seems no-one could help with this so closing.
