### ISSUE TITLE
SiteSpeed domain change not working on Firefox

### ISSUE THREAD

**Issue by vishallanke** [sitespeedio/sitespeed.io#2988]
Below script is working on Chrome but not on Firefox. User gets navigated to Organizational Entitlement Service web page (domain change from mywebsite.cloud) might be the root cause. I am not sure. Following code is working on Chrome but not on Firefox.

```
    module.exports = async function(context, commands) {
  // Navigate to a URL, but do not measure the URL
    await commands.measure.start('Home Page Responsiveness')
    await commands.navigate('https://mywebsitecloud/#/login');
    await commands.measure.stop();
    try {
    await commands.wait.byTime(5000);
    await commands.click.byXpathAndWait('//*[contains(text()," Log in / Sign up ")]'); // It will change domain and navigate user to Organizational Entitlement Service web page
    await commands.wait.byTime(25000);
    await commands.addText.byId('myemail@gmail.com','1-email');                      
    await commands.addText.byXpath('mypass@' , '//*[contains(@type,"password")]');
    await commands.measure.start('Overview Page Responsiveness')
    await commands.click.byXpathAndWait('//button[@name="submit"]');
    await commands.wait.byTime(12000)
    return commands.measure.stop();
    } catch  (e) {
      throw e ;
    }
};
```
Error is as below -

`[2020-05-11 14:09:53] ERROR: Error: Could not add text myemail@gmail.com to id 1-email
`
In captured video, I can see white screen.

Note - Entitlement service works well on Firefox.

**Comment by soulgalore** [comment]
Hi @vishallanke here's the steps I use when I try to debug scripts:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

Easiest is almost always if you can run it on your local machine, without Docker and just look at the browser window and see what happens.

**Comment by vishallanke** [comment]
Its not working on local machine, only on Firefox. 
Organizational Service Entitlement Page does not get opened. Email id and Password fields are white out.
Note - If I trigger the page manually on Firefox , it works. Entitlement Service has full support on Firefox.
![image](https://user-images.githubusercontent.com/46259109/82879727-fedd2400-9f5a-11ea-9aae-c0f14c86e4df.png)

**Comment by soulgalore** [comment]
Does it generate a HAR file, so you can what response that isn't loaded (my guess is that some request/responses is blocked). Also if get in that state in your browser, check the network tab and see if you can see something there (if you're scripting, you can just add a looooong wait so you have time to check the network tabs what's going on.

**Comment by soulgalore** [comment]
Think this has nothing to do with browsertime/sitespeed.io, more a Firefox issue.

**Comment by vishallanke** [comment]
It seems not a Sitespeeed issue.
More to do with behaviors of Corporate Entitlement Service with Firefox when triggered from any automation script
