### ISSUE TITLE
Default annotations not sent to Influxdb events table in case of --multi scripts.js

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#2998]
AIM : To run multiple scripts.js using --multi flag and save result in influxdb and display on Grafana where we can show runs link to Html reports (in S3 bucket)

Docker command used : docker-compose run sitespeed.io /sitespeed.io/login.js /sitespeed.io/cart.js --multi --config /sitespeed.io/influxConfig_file.json

where script1 : login.js measures login journey only
and scripts2 : cart.js measures loading of cart page 
Also , Config file is as below 
{
  "browsertime": {
    "iterations": 1,
    "browser": "chrome"
      },
  "influxdb": {
    "host": "influxdb",
    "port": "8086",
    "database": "data",
    "annotationScreenshot": true
  },
 "resultBaseURL": "url mentioned here",
 "mobile": false,
"s3": {
     "bucketname": "Bucketnamehere",
     "removeLocalResult": false
  }
}

Result Outcome: 
Data stored in influxdb successfully
Graph displayed on Grafana successfully 
But ..

Problem/Bug : By default , in influxdb events table , only 1 result run gets store for cart page.
There should be 2 records for 2 pages in events table in influx db . Due to this issue ,Grafana is displaying only cart page results link and not other page.

**Comment by amitmalhotra-cell** [comment]
To summarize above issue : In documentation where mentioned below -
Run your script by passing it to sitespeed.io and adding the parameter --multi. If you have multiple scripts, you can just pass them in as well.

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.10.2 script.js script2.js script3.js --multi

will result in only script.js to store in influxdb ->events table to store link to results.

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell thanks for creating the issue. I wonder if the annotation is sent or if its sent with wrong tags (so that it will not show up). If you set the log level to debug `-v`  you will get a log message (or multiple) that looks like:
`Send annotation to Influx ...` 

Can you turn on the logs and share the annotation debug messages, then hopefully we can understand if the messages isn't or if the tags are wrong.

Thanks!
Peter

**Comment by amitmalhotra-cell** [comment]
Hi @soulgalore , Thanks for your quick response. I am attaching verbose logs . You can search with "Send annotation to Influx"

Also i am attaching detailed steps performed so that everything is clear. Please check
[verboselog_SendannotationtoInflux.docx](https://github.com/sitespeedio/sitespeed.io/files/4639750/verboselog_SendannotationtoInflux.docx)
[StepsPerformed.docx](https://github.com/sitespeedio/sitespeed.io/files/4639751/StepsPerformed.docx)

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore, 
It seems same timestamp is sent to influxdb for annotations as per logs and it must be getting overwritten while inserting in influxdb. 
If you agree , please let me know how can we avoid this and help resolve this issue .

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore : Any Update on this issue ?

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell I couldn't fully follow the logs. So you are saying they annotation has different tags but use the same timestamp so its overwritten or can do they have the same tags too? I looked at the code and the timestamp is generated when the annotation is sent (if I understand correctly) but then we set `precision=s` when sending it to InfluxDB.

**Comment by amitmalhotra-cell** [comment]
Sorry, can you please tell how to add precision=s in below command when sending to InfluxDB please? 

docker-compose run sitespeed.io /sitespeed.io/login.js /sitespeed.io/cart.js --multi --config /sitespeed.io/influxConfig_file.json 

Config.json file as below  {
  "browsertime": {
    "iterations": 1,
    "browser": "chrome"
      },
  "influxdb": {
    "host": "influxdb",
    "port": "8086",
    "database": "data",
    "annotationScreenshot": true
  },
 "preScript": "/sitespeed.io/PHL_Prescript.js",
 "resultBaseURL": "Urlhere",
 "mobile": false,
"s3": {
     "bucketname": "Bucketnamehere",
     "removeLocalResult": false
  }
}

**Comment by soulgalore** [comment]
I mean the precision is used when you send the annotation by default. Checkout https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/influxdb/send-annotation.js#L63-L74

So are the annotations is your case sent the same second?

**Comment by amitmalhotra-cell** [comment]
So are the annotations is your case sent the same second? - YES (see below)

Timestamp in logs:
![image](https://user-images.githubusercontent.com/63041681/82649694-3d12d480-9c37-11ea-8f0a-8ba436e5f5f7.png)


Timestamp inserted in Influxdb Events Table:
![image](https://user-images.githubusercontent.com/63041681/82649632-22d8f680-9c37-11ea-84ea-65e8a148c124.png)


This happens ALWAYS when i use multiple scripts to execute using --multi flag as below :
docker-compose run sitespeed.io /sitespeed.io/login.js /sitespeed.io/cart.js --multi --config /sitespeed.io/influxConfig_file.json

I checked send-annotation.js , Can changing to below fix this? 
 path: '/write?db=' + options.influxdb.database + '&precision=s',

change to nanoseconds:

path: '/write?db=' + options.influxdb.database + '&precision=rfc3339',

**Comment by soulgalore** [comment]
No the precision is only for how InfluxDB stores the annotation. The fix is in the sitespeed.io code that it should use the timestamp from when the page was tested.

**Comment by soulgalore** [comment]
To fix this we need to do some code change. At the moment the plugins that get the summaries don't know when the data was collected (only when sitespeed.io was started). Browsertime have that information per run, but I don't think we pass that on in the summary (or maybe we do?). At least we need to store the timestamp in the InfluxDB plugin and use it when the annotation is sent.

**Comment by soulgalore** [comment]
I probably need a couple of days to come up with a good fix for this. We pass on the timestamp from browsertime, but we wanna have the same timestamp for other metrics collected at the same time (and that's missing). We have a generic timestamp that is generated when the message is sent (=all data Is collected), that would fix it but it would not be the exact timestamp of when the test was run.

**Comment by amitmalhotra-cell** [comment]
Thanks @soulgalore for looking into this issue on priority. I really appreciate if you are able to provide fix in next release.

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore , Any update on fix ? 
i intend to use --multi flag to run multiple scripts one by one. i can only achieve this is this bug gets fixed. Else i will have to run docker run command 30 times for 30 test scenario for example.

**Comment by soulgalore** [comment]
No updates, I'll update the issue when I have time to do a fix.

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell try 13.3.1 , I hope the fix there work for you.

**Comment by amitmalhotra-cell** [comment]
thanks @soulgalore . I will check it and let you know in case of any issue
