### ISSUE TITLE
Error: PageIndex out of range

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#3007]
Error: PageIndex out of range

I saw your comment in #2425 : At the moment you need to either navigate or make one request between start/stop for it to work.

Do you have any solution to it now or this behavior remains same today as well ?

**Comment by soulgalore** [comment]
What are you trying to do @amitmalhotra-cell ? Checkout https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ - that helps us to understand and reproduce. 

Thanks!

**Comment by amitmalhotra-cell** [comment]
@soulgalore : **Adding more details to issue** 

Issue Description : Getting error "PageIndex out of range" when no navigation or request is included between commands.measure.start/stop.

OS : Windows
**Steps Performed :** 
**1)Docker command used :**
docker run --rm -v %cd%:/sitespeed.io sitespeedio/sitespeed.io:12.3.1 -n 1 /sitespeed.io/AddToCart.js --multi

**2) Error encountered below :** 
![image](https://user-images.githubusercontent.com/63041681/82667613-d5b84d00-9c55-11ea-94fc-035854156177.png)

**3) AddToCart.js  code used as below :** 

await commands.measure.start('AddToCart');

//No request or navigation included between Start and Stop

await driver.findElement(webdriver.By.id('addToCartButton')).click(); // This results in AJAX call
await new Promise(resolve => setTimeout(resolve, 5000));
context.log.info('Item1 Added to Cart');

return commands.measure.stop();

**Self Analysis** : I saw your comment in #2425 as below : 
_soulgalore commented on Jun 28, 2019
At the moment you need to either navigate or make one request between start/stop for it to work.

Best
Peter_

Problem statement : Can we measure only AJAX call time : like add to cart which do not involves any request or navigation to new page ?

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell yes I think you can measure that by adding a user timing using the User Timing API (start before you do the call, end it after) and then add it to the result with https://www.sitespeed.io/documentation/sitespeed.io/scripting/#add-your-own-metrics

**Comment by amitmalhotra-cell** [comment]
@soulgalore : Thanks for your reply. I will try to do this and hope it records video automatically for custom metric. If i found any issue , i will let you know.

**Comment by amitmalhotra-cell** [comment]
Thanks @soulgalore . It worked for me. We can close this issue . Thanks for your help!

**Comment by AnilkishoreReddy** [comment]
@amitmalhotra-cell  Can you share the final script, please?

**Comment by spencerkingman-niche** [comment]
You can also get this error if you use `measure.start()` with the 2nd paramater `alias`. If the alias is identical to one you have already used in the same test run, you may see this error.

**Comment by soulgalore** [comment]
Hi @spencerkingman-niche thanks for sharing, I think that could have been something I missed, let me have a look this weekend (we could have better error handling for that case).
