### ISSUE TITLE
addObject(extraMetrics) String value not inserted in influxdb

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#3014]
hi @soulgalore ,

Version info :
Versions OS: linux 4.19.76-linuxkit nodejs: v12.13.0 sitespeed.io: 12.3.1 browsertime: 8.3.1 coach: 5.0.1

Issue detail: 
1) screenshot.take(name) is not working. I wish to capture error snapshot and send to grafana but see error.
2) How can i mark test run as Fail and send fail status in Grafana.

Steps (Below are steps i intend to do)
1) Run below to test login functionality
docker run --rm -v %cd%:/sitespeed.io sitespeedio/sitespeed.io:12.3.1 -n 1 /sitespeed.io/login.js --multi
2) in script i am trying to catch snapshot as below in case of element not found.
try {
    await driver.findElement(webdriver.By.id('home__formMemberEmail_pass1_passwor')).sendKeys('xxxx');
  } catch (e) {
  context.log.info(e);
  screenshot.take('LoginFailedError')
  }

Expected result :  In case of error capture snapshot and send to Grafana.

Problem statement : i get error as below: screenshot is not defined
![image](https://user-images.githubusercontent.com/63041681/82986354-5343da80-a013-11ea-9659-e6fa0dcd8b11.png)

**Comment by amitmalhotra-cell** [comment]
I mean can you tell me how to use screenshot.take(name) correct way with example ?

**Comment by soulgalore** [comment]
If you follow the script syntax with:
```
module.exports = async function(context, commands) {
}
```

all commands live in the commands name space so:
```
module.exports = async function(context, commands) {
commands.screenshot.take('my-new-screenshot');
}
```

For errors you can use https://www.sitespeed.io/documentation/sitespeed.io/scripting/#error

**Comment by amitmalhotra-cell** [comment]
Thanks @soulgalore for reply . I have few questions here: 

1) commands.screenshot.take('my-new-screenshot')-->Works fine but save snaphot only in folder . Does is show snapshot in html report as well which we can directly open from grafana ?

2) For errors , i followed  https://www.sitespeed.io/documentation/sitespeed.io/scripting/#error
Error can be seen in HTML report -->This is working fine as below but
![image](https://user-images.githubusercontent.com/63041681/82996973-5fd02f00-a023-11ea-9c41-b3d31ee681e8.png)

But can we see error : Submit button not found on grafana itself somehow ?

3) In case of error , i don't want to capture any performance metrics so how can i avoid this but i want to have some data like 'Fail' to show on grafana so that i know it was error and view error message in html report ?

**Comment by soulgalore** [comment]
> 1 

No, that isn't implemented yet in the HTML. 

> 2

All errors are reported to Graphite/InfluxDB. If you checkout https://dashboard.sitespeed.io/d/000000043/page-summary?orgId=1 and scroll down to "Errors" that is the one that is reported to the data source. So it keep track of number of errors.

> 3

That isn't perfect today. Maybe you ca throw an error from the script.

**Comment by amitmalhotra-cell** [comment]
@soulgalore : For point 3 : To send Status as Pass or Fail , i tried to use first commands.measure.addObject(extraMetrics) as below : 

1) **use commands.measure.addObject(extraMetrics) between start and stop**
module.exports = async function(context, commands) {
    const webdriver = context.selenium.webdriver;
    const driver = context.selenium.driver;
    const extraMetrics = { a: 1, b: 2, c: 3};

await commands.measure.start('LoginProcess');
.....//do login
commands.measure.addObject(extraMetrics);
return commands.measure.stop();

**This shows error as below:**
![image](https://user-images.githubusercontent.com/63041681/83020362-ff9eb480-a045-11ea-89ab-d3aa88a69376.png)

2) **if i use commands.measure.addObject(extraMetrics) after stop** , then extrametrics are not displayed in HTML report.

Can you check if this is bug or i am doing anything wrong here ?

**Comment by soulgalore** [comment]
Hi, the metrics needs to be attached to a page at the moment so add them after your test:

```
await commands.measure.start('LoginProcess');
.....//do login
await commands.measure.stop();
return commands.measure.addObject(extraMetrics);
```

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore ,
Below is **working fine**
await commands.measure.start('LoginProcess');
.....//do login
extraMetrics = { Status: 'Failed'};
await commands.measure.stop();
return commands.measure.addObject(extraMetrics);

and i see in HTML report **but i dont see in Influxdb. i dont see any measurement with name extrametrics or status in influxdb. Can you help** ?
![image](https://user-images.githubusercontent.com/63041681/83148319-72776080-a116-11ea-8185-8c66108e3160.png)

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore , Did you get time to check above issue ?

**Comment by soulgalore** [comment]
I think they should be sent automatically, do you send them as numbers? I don't we send true/false metrics.

**Comment by soulgalore** [comment]
It could be that we miss adding a specific tag for it in Influx so its hard to find? In Graphite we the key structure with _statistics.extras.*_

**Comment by amitmalhotra-cell** [comment]
i see extrametrics in HTML report sent value as Failed below , but since it is not sent to Influxdb , i cannot send 'Failed' status to grafana. Can you fix check if this needs a fix for influxdb. **This part is very important to me.**
![image](https://user-images.githubusercontent.com/63041681/83249454-37cc0180-a1c4-11ea-837c-d3fd3ee63810.png)

**Although , below method sends custom metric to Influxdb but for timing. Not sure if i can use it to send Pass or Fail.**

await commands.js.run('performance.mark("start")');
...somework
await commands.js.run('performance.mark("end")');
await commands.js.run('performance.measure("Loadingtime", "start", "end")');

**Comment by amitmalhotra-cell** [comment]
So what i conclude is Current bug is **custom metrics not sent to **_influxdb_** by both below commands :** 
_1)commands.measure.add('TestResult', 'Pass'); OR
2)commands.measure.addObject(extraMetrics);_

Please @soulgalore , any scope you can fix this **urgent request**.

**Comment by soulgalore** [comment]
I can accept a PR for that :) I think its a lot of work to add support for strings. Change and send a Integer instead. Then we can see if it gets tagged right or need an extra tag.

**Comment by amitmalhotra-cell** [comment]
Sending **Integer value works fine** and sent to influxdb successfully and i can see in Grafana as well. This solves my purpose. Thanks @soulgalore . I have changed title of issue for future reference to all. Closing issue.
![image](https://user-images.githubusercontent.com/63041681/83320120-f68a2f00-a261-11ea-927d-079ac48c775b.png)
