### ISSUE TITLE
Questions or Sitespeed Limitations

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#3030]
hi @soulgalore ,
**Why i ask below questions:** 
_I find Sitespeed as amazing tool not only to do performance testing but also i intend to do Functional testing as well. Despite reading documentation few things are unclear though._

### 1) Does Meta works only before start/stop ?
I intend to capture actual result and compare with expected result and display in meta data
_Example : Below code meta data not displayed_
commands.meta.setTitle('Expected Result : Username should be XYZ');
await commands.measure.start('Login');
//do login
//var username= stores username...XYZ
await commands.measure.stop();
commands.meta.setDescription("ActualResult : Username is "& username);

### 2) Error handling only works if try/catch included inside start/stop
Consider a scenario where i want to measure logout time. But if login fails due to some element not found then error is not sent to HTML report because i didcnot started measure yet. So how to capture error ?
_Example :_ 
try{
//do login [suppose login fails here]
}catch(e){commands.error(e);}
await commands.measure.start('Logout');
//do logout
await commands.measure.stop();

### 3) How can i exclude performance metrics like only capture video and extrametrics ?
_Example : how to use below command  to send only video and extrametrics in HTML report_
docker run --net host --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.3.0 --metrics.list https://www.sitespeed.io -n 1 --metrics.filter *- coach.pageSummary.advice.performance.adviceList.*.score --graphite.host 127.0.0.1 --graphite.port 52860

Reference : https://www.sitespeed.io/documentation/sitespeed.io/configure-metrics/#configurefilter-metrics

4) ### await commands.wait.byPageToComplete()-to Wait for the page to finish loading does not work

_Example:_
module.exports = async function(context, commands) {
  // we fetch the selenium webdriver from context
    const webdriver = context.selenium.webdriver;
    const driver = context.selenium.driver;
await driver.findElement(webdriver.By.className('login')).click();
await new Promise(resolve => setTimeout(resolve, 10000));//wait for 10 sec [i know this is not correct way]
await commands.wait.byPageToComplete() // **but this does not work**

**Comment by soulgalore** [comment]
> 1) Does Meta works only before start/stop ?

No I think you can use it whenever or do it not work for you?

> 2) Error handling only works if try/catch included inside start/stop

There's no good way to do that today since the error you create today will be added to a specific page. You can throw the error and just let the run fail I guess.

> 3) How can i exclude performance metrics like only capture video and extrametrics ?

I don't think there's a way to disable that today. You can disable the full Browsertime plugin but then you will not get any metrics at all.

> await commands.wait.byPageToComplete()-to Wait for the page to finish loading does not work

Do the login load a new page? Can you share the code, it should work so maybe there's a bug? I use it some tests today where it work so it maybe a case that isn't covered.

**Comment by amitmalhotra-cell** [comment]
Thanks @soulgalore for your quick response :)
I think i will leave point 2 and 3 as it is for now.

For points 1 and 4 , i will share you my code by tomorrow . I think something i may be doing wrong there or it is a miss :)

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore ,

i retested Points 1 and 4 and below are results :

1) _Does Meta works only before start/stop ?_ 
This is working fine now. I was doing some silly mistake in my code. 👍 

4) _await commands.wait.byPageToComplete()_ - **NOT WORKING** 
Do the login load a new page? -->_YES to homepage ._
Please see below code i used :
```

`module.exports = async function(context, commands) {
  // we fetch the selenium webdriver from context
    const webdriver = context.selenium.webdriver;
    const driver = context.selenium.driver;
    var x;

    await commands.measure.start('LoginProcess');
try{
     await commands.navigate('https://xyz/login');
    
     await driver.findElement(webdriver.By.id('username')).sendKeys('573801');
     await driver.findElement(webdriver.By.id('password')).sendKeys('1234');

await driver.findElement(webdriver.By.className('login')).click();
 //await new Promise(resolve => setTimeout(resolve, 100000));
 await commands.wait.byPageToComplete();

 var existed = await driver.findElement(webdriver.By.className('homepageWebelement')).then(function() {
    x= 'Login Successful';
    context.log.info(x);
    //commands.screenshot.take(x);
    extraMetrics = { Pass: 1,Fail: 0};
    return true;//it existed
  }, async function(err) {
      if (err instanceof webdriver.error.NoSuchElementError) {
        x= 'Login Failed';
        context.log.info(x);
        //commands.screenshot.take(x);
        extraMetrics = { Pass: 0,Fail: 1};
        return false;//it was not found
      } else {
            webdriver.promise.rejected(err);
      }
  });
     } catch (e) {
      commands.screenshot.take('Error'); // capturing screenshot of error
      context.log.info(e);// printing error on console
      commands.error(e);//automatic error sending to HTML report
      extraMetrics = { Pass: 0,Fail: 1};// sending status as Fail to HTML and influxdb
    }
commands.meta.setTitle('Test Case 1');
    commands.meta.setDescription('<b>Result: </b>'+ x );
    
    // Stop and collect the metrics
     await commands.measure.stop();
    commands.measure.add('Expected Result', 'Login should be successful');
    commands.measure.add('Actual Result', x);
     return commands.measure.addObject(extraMetrics);
};

`

```
### ERROR : 
![image](https://user-images.githubusercontent.com/63041681/83843282-4ebda700-a722-11ea-81b9-09fdf5a0dc2f.png)

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore  , Any update on this issue ?

**Comment by soulgalore** [comment]
If you check the browser window, what happens? That is usually the easiest way to see what's going on and trying to understand why things isn't working.

**Comment by soulgalore** [comment]
Didn't get any response so closing.
