### ISSUE TITLE
Unable to find Custom Metrics in Graphite

### ISSUE THREAD

**Issue by girishv01** [sitespeedio/sitespeed.io#3031]
Hi, 

I am following https://www.sitespeed.io/documentation/sitespeed.io/scripting/#add-your-own-metrics
and using -   commands.measure.add('batteryTemperature', temperature/10);

I am able to find this metric on HTML report. As the documentation mentions that the custom metric is automatically sent to Graphite - where do I find this in Graphite (for further dashboarding in Grafana)
I am able to see other metric collected using - commands.measure.start('Launch App');

Thanks,

Girish

**Comment by soulgalore** [comment]
Hi @girishv01 sorry I missed to answer this.  Let ,me update the docs. The metrics are under the key **...statistics.extras.YOUR_METRIC**

**Comment by girishv01** [comment]
Thanks @soulgalore , able to track the metrics.
