### ISSUE TITLE
Unexpected File type output

### ISSUE THREAD

**Issue by corbett3289** [sitespeedio/sitespeed.io#3032]
Running the example command from the documentation produces an error:

C:\Users\andrew.corbett>sitespeed.io https://www.sitespeed.io/

C:\Users\andrew.corbett>

This file doesn't have an app associated with it. Its a .io file format and when I open it it looks like the below code:

 ```
this. #!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/sitespeed.io/bin/sitespeed.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/sitespeed.io/bin/sitespeed.js" "$@"
  ret=$?
fi
exit $ret
```

Is this a bug or a lack of documentation on how to handle file expected file outputs?

**Comment by soulgalore** [comment]
Hi @corbett3289 not sure how that works on Windows? Would be cool to make it work out of the box on Windows too, do you know how? I think most works nowadays on Windows and maybe that's the last thing to fix.

**Comment by bonesoul** [comment]
same here

**Comment by soulgalore** [comment]
This works if you run in bash, checkout https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/windowsFull.yml
