### ISSUE TITLE
[Question][Documentation] Is there a way to get the runs in the Grafana dashboard from the local file system, or server that I host?

### ISSUE THREAD

**Issue by katanaBoy** [sitespeedio/sitespeed.io#3034]
Hi guys,
First of all thank you for this amazing peace of software! 

I'm trying to set up your dashboard and I use the following resources
https://github.com/sitespeedio/dashboard.sitespeed.io https://www.sitespeed.io/documentation/sitespeed.io/continuously-run-your-tests/

I got stuck on the documentation here ...

"resultBaseURL": "https://s3.amazonaws.com/results.sitespeed.io",
  "s3": {
    "key": "S3_KEY",
    "secret": "S3_SECRET",
    "bucketname": "BUCKET_NAME",
    "removeLocalResult": true
  },
...
Can I use my local file system or vm with file server hosted by me to get those run results showing in the dashboard? 
Like in your case ...
![2020-06-11 18_23_15-dash](https://user-images.githubusercontent.com/16033169/84405555-f6e6da80-ac10-11ea-88d7-ab6bbd5364d3.jpg)

**Comment by soulgalore** [comment]
Short answer: yes. 

It depends on where/how you wanna do it. Either you mount a dir for a web server that you run locally (then it will probably just work out of the box) or you need to build a plugin that copy the files where you wanna move them. Let me know what you wanna do and I can help out on a high level.

**Comment by katanaBoy** [comment]
Hi Peter, 
Thank you for the replay. 
Let's try first with mounting the directory to the webserver.  
What do I was planning to try is to create another container whit some web server in it and share the folder with the results.   
If I do this how do I need to change the config in order to make this to work? 
Thank you!

**Comment by soulgalore** [comment]
Ok. I think the key issue is mounting the directory where you write the result files. If you use Docker the default looks something like `-v "$(pwd)":/sitespeed.io` where pwd is the current dir. Change that to a specific directory on the server, and then make sure that one is also mounted for the container that have the web server. One thing that you will miss is deleting old output (like X days or months or whatever) so you need to add that yourself.

**Comment by soulgalore** [comment]
Closing think its solved.
