### ISSUE TITLE
Unable to point to custom chrome driver path

### ISSUE THREAD

**Issue by Prakhar36** [sitespeedio/sitespeed.io#3041]
Hello,
   I had a query. I was trying to use my custom chrome driver and then call this driver while running my selenium script to navigate to a webpage. My intent is to make my javascript file more customizable in terms of web navigation and then using sitespeed extensively for measuring the performance of the webpage. Can anybody give me an example to illustrate this issue. I tried downloading chromedriver.exe that is compatible with my chrome browser and i had kept it inside my folder directory and then pointing the chromedriver.exe using the argument---browsertime.chrome.chromedriverPath, --chrome.chromedriverPath. But when i run the docker command it throws me an exception stating-throw er; // Unhandled 'error' event
   ^
Error: spawn chromedriver ENOENT
  at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
  at onErrorNT (internal/child_process.js:469:16)
  at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
  at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
  at onErrorNT (internal/child_process.js:469:16)
  at processTicksAndRejections (internal/process/task_queues.js:84:21) {
 errno: 'ENOENT',
 code: 'ENOENT',
 syscall: 'spawn chromedriver',
 path: 'chromedriver',
 spawnargs: [ '--port=55995' ]
It would be really gratifying if somebody can give me a code snippet to illustrate this. I am trying out something new and it would be of great help.
Thanks in advance!

**Comment by soulgalore** [comment]
Hi @Prakhar36 can you show me your command? If you run in Docker, then you both need to include the new Chrome and the Chromedriver version in Docker? The Docker container comes with latest Chrome and the matching driver. If you need to update one of them, for example Chromedriver to use it with an older Chrome on Android, you can do that by mounting a volume into the container. If you can show me your full command I think I can help you.

**Comment by soulgalore** [comment]
Closing since we didn't get any feedback.
