### ISSUE TITLE
Running sitespeed script by taking multiple urls from a text file

### ISSUE THREAD

**Issue by sowmyasurampalli** [sitespeedio/sitespeed.io#3047]
I have a requirement to run Sitespeed script by including text checks and custom conditions. I have to read all the urls from a text file.

I tried the following code but it didn't work:
`const cb = (context, commands) =>
  async function (err, data) {
    if (err) throw err;
    console.log(data.toString().split(',\n'));
    url_arr = data.toString().split(",\n");
    for (url of url_arr) {
      console.log("url is",url);
      var failed = 0;
      try {
        await commands.measure.start(url);
      } catch (e) {
        failed = 1;
      }
      if (failed == 1) {
        try {
          await commands.measure.start(url);
        } catch (e) {
          context.log.info(e);
        }
      }
      await commands.js.run(
        'document.body.innerHTML = ""; document.body.style.backgroundColor = "white";'
      );
    }
    return commands.js.run(
      'document.body.innerHTML = ""; document.body.style.backgroundColor = "white";'
    );
  };
module.exports = async function (context, commands) {
  const fs = require("fs");
  fs.readFile("urls.txt", cb(context, commands));
};`

Question on stackoverflow:
[https://stackoverflow.com/questions/62423635/running-sitespeed-script-by-taking-multiple-urls-from-a-text-file](url)

**Comment by soulgalore** [comment]
Hi @sowmyasurampalli what do you want to do? You want to test multiple URLs? If you just want to test the URLs one by one (using a new browser session) you can do that with https://www.sitespeed.io/documentation/sitespeed.io/configuration/#analyse-by-urls

Or do you want to test the URLs with the same browser session, so that you first hit one page, then another etc? Then you can just add `--multi` to your run. Check the same documentation link and look for "If you want to test multiple URLs in a sequence (where the browser cache is not cleared) use –multi:"

Best
Peter

**Comment by sowmyasurampalli** [comment]
> Hi @sowmyasurampalli what do you want to do? You want to test multiple URLs? If you just want to test the URLs one by one (using a new browser session) you can do that with https://www.sitespeed.io/documentation/sitespeed.io/configuration/#analyse-by-urls
> 
> Or do you want to test the URLs with the same browser session, so that you first hit one page, then another etc? Then you can just add `--multi` to your run. Check the same documentation link and look for "If you want to test multiple URLs in a sequence (where the browser cache is not cleared) use –multi:"
> 
> Best
> Peter

Hi Peter,
The requirement is to ensure a particular text is loaded while testing each URL. Please suggest the better approach if not scripting.

**Comment by amitmalhotra-cell** [comment]
@sowmyasurampalli , i am using sitespeed from past couple of months. I achieved this using selenium scripting and verifying text by fetching using getText (). Link for reference :
https://www.sitespeed.io/documentation/sitespeed.io/scripting/

**Comment by soulgalore** [comment]
Scripting is best for that.
