### ISSUE TITLE
Threshold for Metrics Guide

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#3056]
hi @soulgalore ,

### Can you tell me what are the threshold values we can set for all performance metrics or can you share any link which shares ideal metrics values ? 

_example Threshold for Performance score and all other scores ?
example Threshold for Last visual change etc ?
example Threshold for image size, Css transfer size etc ?_

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell thresholds depends on what connectivity and what computer you use when you run your tests. You can configure the summary boxes thresholds with https://www.sitespeed.io/documentation/sitespeed.io/configure-html/#configure-the-thresholds-for-redyellowgreen-summary-boxes.

**Comment by amitmalhotra-cell** [comment]
Thanks @soulgalore for sharing link. i will use it.

### Also , i have 2 questions regarding connectivity and Browser which i was unable to resolve from documentation.

1. **Regarding Browser** : i am running simple docker run command as below and wanted to test on **safari browser** .
GOT BELOW ERROR : 
![image](https://user-images.githubusercontent.com/63041681/85580356-48ec1f00-b659-11ea-9f83-07ba71e5863f.png)


2. **Talking about connectivity** ,  i am running my production tests on AWS EC2 Linux instance using docker run command with default connectivity **native**.
I have NOT setup up Docker network bridges on a server for now. Now by the term **native** , does it mean it is using my C4.large instance type network speed currently ?

**Comment by soulgalore** [comment]
Safari only work on OS X/iOS: https://www.sitespeed.io/documentation/sitespeed.io/browsers/#safari

> C4.large instance type network speed currently 

Yes.

**Comment by amitmalhotra-cell** [comment]
Thanks @soulgalore . We can close this Ticket.
