### ISSUE TITLE
Error while using multiple comma seperated tags --influxdb.tags

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#3060]
### Issue : Error while using multiple comma seperated tags --influxdb.tags

**Steps :** 
 1) using latest sitespeed image on docker hub.
Command run : 
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io /sitespeed.io/Login.js --multi --config /sitespeed.io/Config.json **--influxdb.tags market=xyz,dateTime=2020-06-27-10-15-47** --browsertime.my.env PROD --browsertime.my.usrNm xyz@gmail.com --browsertime.my.pswd xyz

### Error:
![image](https://user-images.githubusercontent.com/63041681/85920156-fbf18e00-b88e-11ea-968b-bcbddcf2b21a.png)

@soulgalore  : Can you check if you are able to reproduce this issue . Please use multiple tags comma seperated as above.
Note : if i send only 1 tag then it is working fine.

**Comment by amitmalhotra-cell** [comment]
Hi @soulgalore  , Did you get time to check this ?

**Comment by soulgalore** [comment]
Can you try with "market=xyz,dateTime=2020-06-27-10-15-47" instead? Maybe yargs (that we use the parse the cli) split the string automatically.

**Comment by amitmalhotra-cell** [comment]
Yes , its works fine now. Thanks.
Closing issue.
