### ISSUE TITLE
localStorage & cookies

### ISSUE THREAD

**Issue by IMT-happy** [sitespeedio/sitespeed.io#3076]
hi, when i use sitespeed to collect the data from video page, i need do some things. such as : write something which we want into local Storage and cookies ,so i hope you can tell me how to run browser with this ;
 and thank you  very much

**Comment by soulgalore** [comment]
Hi @chenghuangu I think its easiest if you use Chrome and the Chrome Devtools Protocol. Checkout the sitespeed.io documentation on how to use CDP https://www.sitespeed.io/documentation/sitespeed.io/scripting/#chrome-devtools-protocol and checkout the devtools docs: https://chromedevtools.github.io/devtools-protocol/
