### ISSUE TITLE
Graphite annotations do not appear

### ISSUE THREAD

**Issue by mploquin** [sitespeedio/sitespeed.io#3096]
Hi,

I don't see Graphite annotation in Grafana panel when I run my docker image of sitespeed.

I defined the `resultBaseURL` and `graphite.auth` options but nothing is displayed in Grafana and nothing in the logs about sending annotations in Graphite..

But when I manually add an event annotation in Graphite, it works good and I see it in Grafana.

There is something special to do ?

**Comment by soulgalore** [comment]
Hi @mploquin no I think that should be enough. Can you try adding a annotation using curl (https://graphite.readthedocs.io/en/latest/events.html#adding-events) from the server (or did you already do that or added an annotation through the GUI in Grafana?).

**Comment by mploquin** [comment]
Yes it works using curl and with the gui in Grafana..
I think it's a problem with my corporate proxy not at all with sitespeed.
Sorry
