### ISSUE TITLE
No unit for the slack summary

### ISSUE THREAD

**Issue by lbilhaut** [sitespeedio/sitespeed.io#3099]
This is not a bug, but as a physicist at heart, it makes me sad that the Slack report doesn't have any unit in it. I've made the change to the file on my personal repo, [here is the commit](https://github.com/lbilhaut/sitespeed.io/commit/c3fc35d1b492ecd3a687ea5c83ce329419d23161). Is it ok if I open a PR with it? (I've never made a contribution to an open source project before so I'm walking on eggshells here!)

**Comment by soulgalore** [comment]
Hi @lbilhaut looks good! After we added support for Slack we also introduced a way to format metrics in ms see https://github.com/sitespeedio/sitespeed.io/blob/main/lib/support/helpers/time.js#L36-L43 I think we also could use that there, so each metric just have a format function?

But you could do a PR first with what you done (just move the space from " ms" and have that once where you combine the metric with the unit. 

In the long run I wanna start to use https://github.com/sitespeedio/sitespeed.io/blob/main/lib/support/friendlynames.js in Slack (where each metric and formatter is already defined). I'm gonna do a rewrite of the Slack plugin when I add Matrix support in a couple of weeks.

**Comment by lbilhaut** [comment]
@soulgalore  Great, thanks! The latest option sounds definitively the best path!
I've pushed my changes but I'm still having an issue with the build for Linux browsers. This is not my OS so I'm not familiar with it. I'm wondering if it's because the API key is not valid for CruX (in that case, how to fix it?) or if it's because now, it expects a space between the number and the unit.

**Comment by soulgalore** [comment]
This is fixed.
