### ISSUE TITLE
S3 NetworkingError: self signed certificate

### ISSUE THREAD

**Issue by georgejeffery** [sitespeedio/sitespeed.io#3100]
Hi!

So, I'm trying to run sitespeed.io on Azure.

Everything's going great so far, apart from one thing:

I've got an s3 proxy running so I can send the data to an azure blob rather than S3, The proxy routes through https, but without TLS and with a self-signed certificate. The proxy is working great through S3 explorer (meaning I can access the blob as if it's s3), but when I try to send data through sitespeed I get the following:

`ERROR: Could not upload to S3 NetworkingError: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)`

I've set s3:options:sslEnabled to false (to get round the TLS), but it seems like it's a node issue?

**Comment by soulgalore** [comment]
Did you get it to work?

**Comment by georgejeffery** [comment]
Yeah - I managed to get it working with an `env` flag. But then I ran into issues with the `region` which the S3 proxy didn't have. Managed to fix that though!

I had to do the following, for reference 

Added to `docker run`

`-e "NODE_TLS_REJECT_UNAUTHORIZED=0"` **< disables Certificate checking in Node**

In `config.json`

"s3": {
        "endpoint": "[ip]",
        "key": "[key]",
        "bucketname":"[two part bucket name, separated by . ]",  (for example **`sitespeed.results`**) **<this bit is vital!**
        "secret": "[secret]",
        "removeLocalResult": true,
        "options":{
            "sslEnabled": false, **< disables TLS in aws-sdk**
            "s3ForcePathStyle":true
        }
     },
That way you're basically convincing aws-sdk/node that the first half of the bucket name is the region, and the second half the bucket.

I used the CE edition of Flexify.IO (on docker as `flexifyio/ce`) running on the same VM as Grafana and Graphite, connected to a separate Azure storage blob. With flexify you can do "virtual buckets" which allowed me to do the above.

Happy to do a complete write up / overview of the steps necessary if that would help! Not sure how many Azure users you have!
