### ISSUE TITLE
Ajax requests measuring

### ISSUE THREAD

**Issue by nadiabodnarchuk** [sitespeedio/sitespeed.io#3104]
Hi @soulgalore,
can you please assist me with the following question? 

In my scenario I need to click a link on the page and this click triggers ajax requests sending and as a result pop up appears. 
What confuses me is that I don't see opened pop up on the video: script just navigates to Page 1, not openes pop up, and then navigates to Page 2.

Here is my script:
```
await commands.measure.start('Open Page 1"');
await commands.navigate(
    'https://sample.org/page1'
	);
await commands.wait.byTime(10000);
await commands.measure.stop();

await commands.measure.start('Open Page 2"');
	await commands.click.byClassNameAndWait( // after click ajax requests are sending and I expect to see opened pop up
	'edit-row__edit js-edit-row ajax-link'
	);
	await commands.wait.byTime(10000);
	await commands.navigate(
            ''https://sample.org/page2'
	         );
        await commands.wait.byTime(10000);
    
return commands.measure.stop();
```

Here is how I start sitespeed.io run:
`docker run --network=host --privileged=true --shm-size=1g -e MAX_OLD_SPACE_SIZE=4096 --rm -v /c/Users/user/Documents/sitespeedio/:/sitespeed.io sitespeedio/sitespeed.io:14.0.0 --graphite.host localhost --graphite.auth root:root --grafana.host 127.0.0.1 --grafana.port 3000 prod_script_1.js --multi -n 1 --pageCompleteWaitTime 20000` 

How should I handle this situation?

Thanks in advance!

**Comment by soulgalore** [comment]
Hi @nadiabodnarchuk hard to say, with a quick look I think your code look ok, can you share the URLs so I can test? That makes it easier to understand what's going on.

**Comment by nadiabodnarchuk** [comment]
@soulgalore thanks for the answer!
Unfortunately script requires authentication to navigate to tested URLs :( Is there any other way I can help you to understand what's going on?

I thought the problem was that Sitespeed does not measure ajax requests, only navigations. This is very my situation: after click on link to open pop up actual navigation is not happening.

But I thought at least I would be able to see opened pop up on the video. So I suspect click itself is not triggering by some reason.

To demonstrate my scenario more clearly. Here are a number of "Edit" links. I need to click the first one:
![2020-07-26_11-50-10](https://user-images.githubusercontent.com/47209933/88475211-854fbb00-cf36-11ea-9333-af23e767d603.jpg)
HTML code of this link:
```
<span class="edit-row__edit js-edit-row ajax-link" data-sub-procedure-id="2138">Edit</span>
```
So I wrote XPath for this element:
```
//span[@data-sub-procedure-id="2138" and contains(text(), "Edit")]
```
And step in my scenario became as this:
```
await commands.measure.start('Open Pop up"');
await commands.click.byXpathAndWait(
'//span[@data-sub-procedure-id="2138" and contains(text(), "Edit")]' // after click ajax requests are sending and I expect to see opened pop up
);
await commands.wait.byTime(20000);
await commands.navigate(
'https://sample.org/page2'
);
```
But video does not show that pop up has been opened. I think by some reason click has not been happened...

**Comment by nadiabodnarchuk** [comment]
The second problem I have faced within this script is that after log in gray page is viewed instead of navigation to the needed page:
![2020-07-26_15-34-31](https://user-images.githubusercontent.com/47209933/88479209-1bdfa480-cf56-11ea-9304-2d1d2fb9ec57.jpg)

To log in I use separate file as preScript:
```
module.exports = async function(context, commands) {
  await commands.navigate(
    'https://sample.org'
  );
  await commands.wait.byTime(10000);
  
  await commands.addText.byId('login', 'txtLoginEmail');
  await commands.addText.byId('password', 'txtLoginPassword');
  await commands.click.byClassNameAndWait('btn btn-success btn-block');
  
  return commands.wait.byPageToComplete();
}
After click on Log In button, two ajax requests executes:

- auth;
- setSession

``` 
Then main script run:
```
module.exports = async function(context, commands) {
  context.log.info('Script is running');

try {
	await commands.measure.start('Open Page that should not be gray"');
	await commands.navigate(
    'https://sample.org/notgraypage'
	);
	await commands.wait.byTime(20000);
	await commands.measure.stop();
```

Really don't know where the problem can lie :(

**Comment by nadiabodnarchuk** [comment]
Okay, I solved first problem by using Selenium. This works properly for me:
```
await commands.measure.start('Open Page')
await driver.get("https://sample.org")
await driver.sleep(40000) 

await driver.findElement(webdriver.By.css(".js-sub-procedure-id-2138 .edit-row__edit")).click() // this opens pop up with no problem and I can see it on video 
await driver.sleep(5000)
```

**Comment by nadiabodnarchuk** [comment]
@soulgalore  After more deep investigation of second issue (gray page is viewed after log in), 
I figured out that this connected with necessity to set up local timezone (Europe/Minsk on Sitespeed docker container (we have already faced with this issue when run autotests through Jenkins and bash script with timezone setup helped).

I also figured out that Sitespeed docker container has UTC timezone by default.

What I've tried to change container's time zone to Europe/Minsk:
- /etc/localtime:/etc/localtime:ro - does not work as I have Windows host
-  -e TZ=Europe/Minsk as an argument when run docker - has no effect

Cay you please suggest what should I do to set up needed timezone in Sitespeed docker container Or sync it with Windows host machine?

**Comment by soulgalore** [comment]
Hi @nadiabodnarchuk sorry I don't have Windows, have searched at the forums at Docker? https://forums.docker.com

**Comment by soulgalore** [comment]
For measuring Ajax request the new stop watch command will work great: https://github.com/sitespeedio/sitespeed.io/pull/3338., coming in the 17.0 release in two days.
