### ISSUE TITLE
CrUX plugin doesn't send metric name for origin 

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3106]
Hello,
sitespeed.io version 14.1.0
influxdb 1.7.7

I use InfluxDB as data storage.
As I see CrUX plugin doesn't send metric name tag while fetching data for domain origin.
![image](https://user-images.githubusercontent.com/10085700/88544586-4c8d1000-d022-11ea-9c75-ee9a0b7bec8e.png)

url data seems valid
![image](https://user-images.githubusercontent.com/10085700/88545002-08e6d600-d023-11ea-95cb-ed92ec7f49be.png)

Best Regards.

**Comment by Icecold777** [comment]
Also fetching only ORIGIN has an issue.
![image](https://user-images.githubusercontent.com/10085700/88779625-a3b1f280-d192-11ea-85a7-9004b0014353.png)

**Comment by soulgalore** [comment]
Hi @Icecold777 sorry missed to answer this. InfluxDB only takes care of pageSummary messages at the moment (= data for a specific URL and not for a origin). To get this to work on InfluxDb we need to fix/change that.

**Comment by Icecold777** [comment]
As workaround it's possible to use InfluxDB built-in Graphite Protocol support. https://docs.influxdata.com/influxdb/v1.8/supported_protocols/graphite/

The only thing you need is to enable it in influxdb configs, bind address and define parsing template.

[[graphite]]
   enabled = true
   database = "sitespeedCrUX"
   retention-policy = ""
   bind-address = ":2003"
   protocol = "tcp"
   batch-size = 5000
   batch-pending = 10
   batch-timeout = "1s"
   consistency-level = "one"
   separator = "."
      templates = [
	 "sitespeedCrUX.summary.* .summaryType.group.origin.experience.formFactor.metric.measurement",
	 "sitespeedCrUX.pageSummary.* .summaryType.group.page.origin.experience.formFactor.metric.measurement"
   ]

**Comment by soulgalore** [comment]
Lets make a generic metric/tag plugin that handles this for Prometheus/Influx.
