### ISSUE TITLE
blockDomainsExcept doesn't appear to apply correctly

### ISSUE THREAD

**Issue by bobstrecansky** [sitespeedio/sitespeed.io#3107]
I've attempted to apply the `blockDomainsExcept` flag in my sitespeed executions.  I'm trying to get the result of just loading all the base domain.   I still see all of the other 3rd party results being loaded.

- Exact how you run (the exact parameters)

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:14.1.0 https://homedepot.com '--blockDomainsExcept homedepot.com'`

- Which version you are using

Latest (14.1.0)

- OS (if you use Docker, report the base OS)

Docker, have tried on MacOS 10.15.5 and linux (Centos 7.6)

- Browser version (if you don't run Docker)
N/A

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:14.1.0 https://homedepot.com '--blockDomainsExcept homedepot.com'`

**Comment by soulgalore** [comment]
Hi @bobstrecansky thanks for creating the issue. I had a go and got the same, I wonder if the flag we are using in Chrome changed or if there's a bug in how we set it up ("it used to work"). I have a look tonight.

**Comment by soulgalore** [comment]
Hi @bobstrecansky I think the cli conversion to Browsertime doesn't work correctly. If I run like this:

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:14.1.0 https://www.homedepot.com --browsertime.chrome.blockDomainsExcept "*.homedepot.com"
-n 1` (see the extra _browsertime.chrome._ it works for me).

I'll check what's going on.

**Comment by bobstrecansky** [comment]
@soulgalore - sounds good.  Your fix will work fine for my use case in the interim I think!

**Comment by soulgalore** [comment]
Ah I checked the docs (https://www.sitespeed.io/documentation/sitespeed.io/thirdparty/#block-all-3rd-parties and tested) the correct way is `--chrome.blockDomainsExcept`. Could it be that there's somewhere else in the documentation that miss out on specifying Chrome?

**Comment by bobstrecansky** [comment]
I definitely copied that from somewhere in the documentation, but I can't remember exactly where.  This issue should suffice if someone comes along the same problem.  I think we can close this?
