### ISSUE TITLE
Configure number of retries in case of failing to load

### ISSUE THREAD

**Issue by rashnakumar96** [sitespeedio/sitespeed.io#3114]
There are some urls/resources in my test data that just download a file. When I test those urls with site speed.io, it gives the error: 
"failed to load, the browser are still on data:text/html;charset=utf-8,<html><body></body></html> , trying 5 more time(s) but first wait for 10000 ms.
failed to load, the browser are still on data:text/html;charset=utf-8,<html><body></body></html> , trying 4 more time(s) but first wait for 20000 ms."
It does a couple of more retries, after which it exits While the result is expected, but is there a way to configure the number of retries and the above wait time (so that time is not wasted on trying to load urls that will not load)?

**Comment by soulgalore** [comment]
Yes you can use  `--browsertime.retries`  to set the number of retries  and `--browsertime.retryWaitTime ` to set the wait time between retries.
