### ISSUE TITLE
[feature request] append User-Agent string, not just replace

### ISSUE THREAD

**Issue by petemyron** [sitespeedio/sitespeed.io#3118]
I would like to be able to append a string to the UA string without having to stay in sync with browser versions. 

I get that `--browsertime.userAgent`, `--userAgent` allow this to be overridden, but I have site owners that are wanting to ignore my generated traffic from their reporting/metrics (a reasonable request). This would allow them to easily filter my traffic.

I would suggest, `--browsertime.userAgentSuffix` or `userAgentAppendage` (or something better) and it should append whatever that string is to the end of the UA string.

Example:
`... -b chrome --browsertime.userAgentSuffix "my group name"` and it should produce something like:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 (my group name)
```

Maybe later, [Client Hints](https://wicg.github.io/ua-client-hints/) can be used instead or as an additional option.

**Comment by soulgalore** [comment]
I think its doable but we need to change a couple things: We need to start the browser, get the current user agent and then add the extra info. I see the use case but have hard time to estimate how much work it is.

**Comment by shaqb** [comment]
+1 on this feature request! We have a number of sites that sit behind a bot protection manager, and our security team would like us to use add a token to our user agent so that they can whitelist. Currently we can use a hardcoded user agent with the token, but every time we upgrade the version of sitespeed.io (and subsequent browser) we have to change the user agent in our config. Being able to append our token would be a big help!

**Comment by soulgalore** [comment]
Let me have a look later this week see if there's an easy way to implement it.

**Comment by soulgalore** [comment]
I released a fix for this in 21.3.0 that works for Chrome and Edge. Use `--chrome.appendToUserAgent` to add extra string to the user agent.

**Comment by soulgalore** [comment]
For Firefox I haven't found an easy way to do this. I'll ask Mozilla but the only way I see it right now is to start the browser, get the user agent, stop the browser and start a new browser with the new user agent.

**Comment by shaqb** [comment]
This is awesome - thanks so much @soulgalore !

**Comment by soulgalore** [comment]
This is done for Firefox / Chrome and Edge.
