### ISSUE TITLE
Ways to run test using NodeJS

### ISSUE THREAD

**Issue by poornachandraFeb** [sitespeedio/sitespeed.io#3119]
Hi Team,

Can you assist in the different ways to run the test webpage using sitespeed.io NodeJS  package.
When we install the package using packge.json file we are unable to find the option to run the test.

But when we install through - npm install sitespeed.io we can run through

..sitespeedio\node_modules\sitespeed.io\bin>node sitespeed.js www.google.com

The above option will not be available when we install it from package.json in the Azure Pipeline. Please assist with the different options to run the test.

**Comment by poornachandraFeb** [comment]
[package.txt](https://github.com/sitespeedio/sitespeed.io/files/5061596/package.txt)

This was the package.json used to install the sitespeed.io

**Comment by soulgalore** [comment]
Sorry I missed this. Can you install it globally? I haven't used Azure Pipeline, but I guess they should have some documentation on how to run NodeJS applications?

**Comment by soulgalore** [comment]
Did you get it to work?
