### ISSUE TITLE
Chrome Emulated Mobile : issues with screenshots, filmstrip visible in the html report

### ISSUE THREAD

**Issue by fxbtr** [sitespeedio/sitespeed.io#3122]
Hi,

When running the following command : 

```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:14.2.3-plus1 -n 1 --mobile -c 3gslow --cpu --video false https://www.recette-cdiscount.com/telephonie/telephone-mobile/samsung-galaxy-s10-128-go-noir-double-sim/f-14404-samgalaxs10p128n.html --plugins.add /lighthouse --lighthouse.iterations 1
```
It's pretty vanilla, I am not setting a specific aspect ratio or anything.
I get the following output in my html folder : scrollbars in screenshots, and a weird viewport, the website appears to be cropped.

![image](https://user-images.githubusercontent.com/41640867/90004811-93237100-dc96-11ea-82e4-e755cd203ea9.png)
![image](https://user-images.githubusercontent.com/41640867/90004823-99b1e880-dc96-11ea-9e21-11f698594766.png)
![image](https://user-images.githubusercontent.com/41640867/90004831-9cacd900-dc96-11ea-8f46-2bcf808e4ba0.png)

I don't have this issue with the version 13.2.0 : 

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.2.0-plus1 -n 1 --mobile -c 3gslow --cpu --video false https://www.recette-cdiscount.com/telephonie/telephone-mobile/samsung-galaxy-s10-128-go-noir-double-sim/f-14404-samgalaxs10p128n.html --plugins.add /lighthouse --lighthouse.iterations 1`

![image](https://user-images.githubusercontent.com/41640867/90005717-e34f0300-dc97-11ea-8fcf-26cb7b3c2858.png)
![image](https://user-images.githubusercontent.com/41640867/90005721-e518c680-dc97-11ea-98cd-8d9497621b50.png)
![image](https://user-images.githubusercontent.com/41640867/90005726-e6e28a00-dc97-11ea-8dc9-f9b65fc977b8.png)

Am I the only one? 

Thanks

**Comment by soulgalore** [comment]
Hi @fxbtr thanks for creating the issue. My guess is that something changed in Chrome between 83 and 84 that I've missed, it looks like emulation fails (with the scroll bars), let me have a look the coming days.

**Comment by soulgalore** [comment]
I need to try it out tio see the config needed. I use https://www.sitespeed.io/documentation/sitespeed.io/configure-metrics/#list-configured-metrics to do that.

I try to avoid sending data per asset to Graphite since it will take a lot of disk space if the URLs change see https://www.sitespeed.io/documentation/sitespeed.io/graphite/#configure-graphite. Away to "fix" that is to setup rules to keep that data only for a couple of days.

**Comment by soulgalore** [comment]
It seems like it works on OS X but Chrome 84 in Docker gets the scroll list. I tried with 83 in Docker and could see that it works. I briefly looked in the Chromedriver/Chrome bug tracker but couldn't find anything. I'll create an upstream bug when I looked some more, hopefully early next week.

**Comment by fxbtr** [comment]
Hi @soulgalore as always thanks for taking the time.

**Comment by soulgalore** [comment]
Made a quick check for the coming Chrome 85 and its the same problem there. Let me dig deeper.

**Comment by soulgalore** [comment]
I created an issue for Chromedriver, lets see if they can help out: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3576

**Comment by soulgalore** [comment]
This is fixed in Browsertime and I'm releasing it later today. The problem was not upstream, it was a miss on how we set emulation, however it seems to be ok until a Chrome release ago.
