### ISSUE TITLE
JavaScript heap out of memory during script execution

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3123]
Hello, 
I'm trying to run script with the following command.

docker run --name script --network $net  --rm -v "$(pwd)":/sitespeed.io -p 8980:5900 sitespeedio/sitespeed.io:12.4.0 /sitespeed.io/scripts/$script --multi --resultBaseURL  http://127.0.0.1:8180/ -c $net --html.showAllWaterfallSummary true -n 10 --cpu true --spa true

but execution fails somewhere in the middle of scenario. 
Please advise how to set nodejs memory limits. 

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200813.110356.32.0.001.json
<--- Last few GCs --->

[32:0x3e73f00]   170543 ms: Mark-sweep 2061.4 (2096.8) -> 2061.4 (2065.8) MB, 839.7 / 0.0 ms  (average mu = 0.153, current mu = 0.000) last resort GC in old space requested
[32:0x3e73f00]   171262 ms: Mark-sweep 2061.4 (2065.8) -> 2061.4 (2065.8) MB, 718.7 / 0.0 ms  (average mu = 0.088, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13725d9]
    1: StubFrame [pc: 0x1317f84]
Security context: 0x0d46895008a1 <JSObject>
    2: from [0xd4689510d69](this=0x0d4689510b89 <JSFunction Array (sfi = 0x1f84273c8e11)>,0x10e1181ebea1 <JSArray[20155392]>)
    3: _computeRecursiveAttributableURLs [0x2f78bb8294f9] [/usr/src/app/node_modules/@sitespeed.io/tracium/lib/main-thread-tasks.js:~184] [pc=0x3b97d4a4f8ca](this=0x2f78bb829b61 <JSFunction MainThreadTasks ...

Node.js report completed
 1: 0x9d8da0 node::Abort() [node]
 2: 0x9d9f56 node::OnFatalError(char const*, char const*) [node]
 3: 0xb37dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb38139 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xce34f5  [node]
 6: 0xcf33bd v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
 7: 0xcb9c67 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [node]
 8: 0xfefb9b v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x13725d9  [node]`

**Comment by soulgalore** [comment]
Hi @Icecold777 checkout https://www.sitespeed.io/documentation/sitespeed.io/docker/#increase-memory

**Comment by Icecold777** [comment]
Thank you, @soulgalore
