### ISSUE TITLE
Run sitespeed.io from a go application running on a docker

### ISSUE THREAD

**Issue by rashnakumar96** [sitespeedio/sitespeed.io#3129]
I have been trying to use docker command for sitespeed.io inside a golang
application which I build and run through a dockerfile. The command is : "cmd := exec.Command("docker","run", "--rm", "-v", "$(pwd):/sitespeed.io", "sitespeedio/sitespeed.io", url)" and the dockerfile looks like this:

FROM golang:1.15
ENV PORT=9000
RUN mkdir -p /app
WORKDIR /app
ADD . /app
ENV GOPATH=/app 
RUN go generate
CMD ["./bin/application"]

The application runs successfully but gives this error with the docker command for sitespeed.io: 
Error: running sitespeed.io                   error="exec: \"docker\": executable file not found in $PATH. When I build the application without the dockerfile everything works fine. So is there a way to run sitespeed.io from within a go application which is built and run through a docker?

**Comment by soulgalore** [comment]
Hi @rashnakumar96 I think that means that your go application can't find the docker command in the path, checkout out the docs for go how to do that.
