### ISSUE TITLE
How to include the "_error" in the HAR file?

### ISSUE THREAD

**Issue by flyisland** [sitespeedio/sitespeed.io#3132]
Hi, my targeted website includes some pictures that are blocked by the firewall, so that there some errors like `"_error": "net::ERR_TIMED_OUT"` or `"_error": "net::ERR_CONNECTION_RESET"` in the HAR file generated by the Chrome DevTools.

But I can not find any such errors in the HAR file generated by the sitespeed.io on the same website pages while there is this error: 
> ERROR: Failed waiting on page to finished loading, timed out after 300000 ms BrowserError: Running page complete check

Is it possible to ask the sitespeed.io tool to include the "_error" in the HAR file?

**Comment by flyisland** [comment]
Hi @soulgalore, I've created an issue on [chrome-har](https://github.com/sitespeedio/chrome-har/issues/74), please check it, thanks!

**Comment by soulgalore** [comment]
Thanks for creating it on the right place, closing this for now.
