### ISSUE TITLE
no video recorded during scripted user journey

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3136]
Hello,

docker command
sudo docker run --network $net  --rm -v "$(pwd)":/sitespeed.io -p 8980:5900  sitespeedio/sitespeed.io:12.3.1 /sitespeed.io/scripts/$script --multi -c $net --html.showAllWaterfallSummary true -n 1--cpu true --video true

Script has 8 steps. One of them doesn't have recorded video neither in html report nor in results folder. 
But all visual metrics are collected.

Debug logs says
"files": {
      "video": [
        "pages/checkout/payment/index.jsp/query-7070dddc/data/video/1.mp4"
      ],
      "screenshot": [
        "pages/checkout/payment/index.jsp/query-7070dddc/data/screenshots/1.png"
      ],
      "timeline": [
        "pages/checkout/payment/index.jsp/query-7070dddc/data/trace-1.json.gz"
      ],

And there is trace and screenshot in place.

I don't see orange screen at measure.start while exploring process via VNC but see in logs
[2020-08-27 13:41:17] INFO: [browsertime.command.measure] Start to measure OrderPaymentPage
[2020-08-27 13:41:17] DEBUG: [browsertime.video] Add orange color

I don't see errors in 1.visualmetrics.log.  According to log file filmstrip is generated from video successfully but in HTML report it's corrupted 

Script part doesn't contain any unusual actions
		await commands.measure.start('OrderPaymentPage');
		await commands.click.bySelector(selectorOrderPaymentPage);
		await commands.wait.byPageToComplete();
		return commands.measure.stop();

What may be the reason of missing video?  I'll be happy to provide more details

**Comment by soulgalore** [comment]
Hi @Icecold777 I don't know, I need to be able to reproduce to try to understand.
