### ISSUE TITLE
Har with Content

### ISSUE THREAD

**Issue by umeshPathak** [sitespeedio/sitespeed.io#3137]
How to create the HAR with Contents ?

**Comment by soulgalore** [comment]
For Firefox use `--browsertime.firefox.includeResponseBodies all `and for Chrome `--browsertime.chrome.includeResponseBodies all` see https://www.sitespeed.io/documentation/sitespeed.io/configuration/#the-options

**Comment by umeshPathak** [comment]
I tried this for chrome, but response -> content -> text is missing. see the attached screenshot

![btime](https://user-images.githubusercontent.com/17564142/91693365-8ce32f00-eb88-11ea-8eb1-a0437bc09f77.JPG)

**Comment by umeshPathak** [comment]
I tried with below command
browsertime --browsertime.chrome.includeResponseBodies choices:all https://www.infosys.com

**Comment by umeshPathak** [comment]
It worked :) I tried with browsertime https://www.infosys.com --chrome.includeResponseBodies all
