### ISSUE TITLE
Run 2 pages but only get 1 page browertime.har result for the report

### ISSUE THREAD

**Issue by zoujuanstefjay** [sitespeedio/sitespeed.io#3140]
INFO: Versions OS: darwin 17.7.0 nodejs: v12.18.3 sitespeed.io: 14.4.0 browsertime: 9.4.0 coach: 5.1.1
using chrome version: 85.0.4183.83
postscript as below:
![image](https://user-images.githubusercontent.com/41933556/91981422-69bca900-ed5b-11ea-9c93-2e81517ba1f5.png)

result is good as below:
![image](https://user-images.githubusercontent.com/41933556/91981610-adafae00-ed5b-11ea-89d6-a714163e320e.png)

but in the output report there is only 1 page data:
![image](https://user-images.githubusercontent.com/41933556/91981752-de8fe300-ed5b-11ea-8104-505cf8e0c1f1.png)

**Comment by zoujuanstefjay** [comment]
![image](https://user-images.githubusercontent.com/41933556/92308415-f53e7000-efcf-11ea-8c1a-80635551df03.png)
missing 1 har file in one of the 2 pages

**Comment by deena9291** [comment]
I am facing the same issue as well, I get the page level metrics for only the last page in the flow.

**Comment by soulgalore** [comment]
Hi @zoujuanstefjay sorry I missed this issue. Do not use post script to collect metrics, its not designed for that. Instead  you can use multiple scripting files (maybe we miss that in the documentation)? You can add them like `--multi script1.js script2.js script3.js` and then they will run after each other (if you wanna re-use functionality between different use cases). The postScript was actually created before we added scripting support and should be used for things you need to so after your tests (log off the user, cleanup etc). I'll try to add more examples in the docs the coming week.
