### ISSUE TITLE
npm installation error in Linux

### ISSUE THREAD

**Issue by umeshPathak** [sitespeedio/sitespeed.io#3141]
I  have got attached error on the Linux box after I execute npm install browsertime -g command 
![npm](https://user-images.githubusercontent.com/17564142/92115639-5e778500-ee10-11ea-9ef1-1ce4ece48f69.JPG)

**Comment by soulgalore** [comment]
This looks like a dir owner issue on your machine. Check if your user (that runs the install command) has correct permissions where your global NodeJs code is installed.

**Comment by umeshPathak** [comment]
Ok. I overcome this issue. But a new one popped up.   when I executed  **browsertime https://www.infosys.com  --iterations 1 --headless --browser firefox  --firefox.includeResponseBodies all**

 _The specified executable path does not exist: /usr/local/lib/node_modules/browsertime/node_modules/@sitespeed.io/geckodriver/vendor/geckodriver_

How to manually install geckodriver ?

**Comment by soulgalore** [comment]
Use https://github.com/sitespeedio/geckodriver or download it from https://github.com/mozilla/geckodriver/releases. It should be installed automatically though?

**Comment by soulgalore** [comment]
Did you get this to work?
