### ISSUE TITLE
How to access and change storage-schemas.conf & storage-aggregation.conf

### ISSUE THREAD

**Issue by TheDreaMzZ77** [sitespeedio/sitespeed.io#3143]
Hello everyone !

I would like to know how to access and change the settings for storage-schemas.conf and storage-aggregation.conf.

I'm trying to change the settings to be able to keep the data for 1 year but I don't know how to change them.

**Comment by soulgalore** [comment]
Hi @TheDreaMzZ77 do you run the sitespeedio/graphite Docker container? Then you can checkout https://github.com/sitespeedio/sitespeed.io/blob/main/docker/docker-compose.yml#L30-L41 and the docs https://www.sitespeed.io/documentation/sitespeed.io/graphite/#configure-graphite

Also these docs are good: https://github.com/statsd/statsd/blob/master/docs/graphite.md

**Comment by TheDreaMzZ77** [comment]
I didn't see that there were some changes to be made in docker-compose.yml... (https://github.com/sitespeedio/sitespeed.io/blob/main/docker/docker-compose.yml#L30-L41)

Thank you I think my problem is solved!
