### ISSUE TITLE
How to change the metrics ?

### ISSUE THREAD

**Issue by TheDreaMzZ77** [sitespeedio/sitespeed.io#3145]
Hi !

I would like to change the metrics that are displayed in localhost in grafana do I need the dashboard.sitespeed.io folder?
I don't know which command to make or where the document is located and what to put in this document ...
Then I would like to display it in the leaderboard of grafana

**Comment by TheDreaMzZ77** [comment]
For exemple i would like to add the "Cumulative Layout Shift"
https://web.dev/optimize-cls/

**Comment by soulgalore** [comment]
Hi @TheDreaMzZ77 https://grafana.com/tutorials/ have tutorials on how to create graphs. If sitespeed.io collects metric but don't send them to Graphite, you can configure it: https://www.sitespeed.io/documentation/sitespeed.io/configure-metrics/

For CLS you can see that in the dashboard https://dashboard.sitespeed.io/d/000000043/page-summary?orgId=1 (for browsers that supports it), scroll down to "Page"

<img width="1499" alt="Screenshot 2020-09-09 at 19 57 04" src="https://user-images.githubusercontent.com/540757/92635771-ac8bfd00-f2d6-11ea-93f3-f30323874e3b.png">

**Comment by TheDreaMzZ77** [comment]
How do I know which line corresponds to which metrics?
Let's take my example, I want to add the "Cumulative Layout Shift", let's imagine that I have to add the metrics as said here (https://www.sitespeed.io/documentation/sitespeed.io/configure-metrics/#add-a-metric)
what are the lines to import and paste in the config.json? 
And how do I know this for the next data I want to add?

**Comment by soulgalore** [comment]
"Cumulative Layout Shift" is sent by default. Can you give me a concrete example I can guide you. I think the easiest way is to look at the remade dashboards and look there how the queries is created and then redo them on your own dashboard.

**Comment by soulgalore** [comment]
In the new dashboards CLS and other Google Web Vitals are presented by default (when you use Chrome for testing).
