### ISSUE TITLE
What is the metric of Total Blocking Time (TBT)

### ISSUE THREAD

**Issue by Namac0** [sitespeedio/sitespeed.io#3147]
I have a question:
Here as you can see graphite send the TBT but how can i acces it in a grafana query ?
I would like to make a dashboard with this metrics.

![Capture](https://user-images.githubusercontent.com/71318226/93226967-2f4c0680-f774-11ea-894f-933f8b0443e0.PNG)

ConfiguredMetrics.txt : 
`largestassets.summary.image.0.transferSize
browsertime.pageSummary.statistics.timings.pageTimings
browsertime.pageSummary.statistics.timings.rumSpeedIndex
browsertime.pageSummary.statistics.timings.fullyLoaded
browsertime.pageSummary.statistics.timings.firstPaint
browsertime.pageSummary.statistics.timings.timeToDomContentFlushed
browsertime.pageSummary.statistics.timings.timeToContentfulPaint
browsertime.pageSummary.statistics.timings.timeToFirstInteractive
browsertime.pageSummary.statistics.timings.loadEventEnd
browsertime.pageSummary.statistics.timings.userTimings
browsertime.pageSummary.statistics.timings.paintTiming
browsertime.pageSummary.statistics.timings.largestContentfulPaint.renderTime
browsertime.pageSummary.statistics.timings.largestContentfulPaint.loadTime
browsertime.pageSummary.statistics.timings.elementTimings.*
browsertime.pageSummary.statistics.timings.firstInput.delay
browsertime.pageSummary.statistics.timings.firstInput.duration
browsertime.pageSummary.statistics.visualMetrics.*
browsertime.pageSummary.statistics.custom.*
browsertime.pageSummary.statistics.console.error
browsertime.pageSummary.statistics.console.warning
browsertime.pageSummary.statistics.cpu.categories.*
browsertime.pageSummary.statistics.cpu.events.*
browsertime.pageSummary.statistics.cpu.longTasks.*
browsertime.pageSummary.statistics.cdp.performance.RecalcStyleCount
browsertime.pageSummary.statistics.cdp.performance.JSHeapUsedSize
browsertime.pageSummary.statistics.cdp.performance.JSHeapTotalSize
browsertime.pageSummary.statistics.cdp.performance.FirstMeaningfulPaint
browsertime.pageSummary.statistics.errors
browsertime.pageSummary.statistics.axe.violations.*
browsertime.pageSummary.statistics.pageinfo.layoutShift
browsertime.pageSummary.statistics.pageinfo.domElements
browsertime.pageSummary.statistics.extras.*
browsertime.pageSummary.statistics.android.batteryTemperature.*
browsertime.summary.firstPaint
browsertime.summary.rumSpeedIndex
browsertime.summary.timeToDomContentFlushed
browsertime.summary.fullyLoaded
browsertime.summary.pageTimings
browsertime.summary.userTimings.marks
browsertime.summary.userTimings.measures
browsertime.summary.visualMetrics.*
browsertime.summary.custom.*
browsertime.summary.cpu.categories.*
browsertime.summary.cpu.longTasks.*
browsertime.run.firstPaint
browsertime.run.rumSpeedIndex
browsertime.run.timeToDomContentFlushed
browsertime.run.fullyLoaded
browsertime.run.pageTimings
browsertime.run.userTimings.marks
browsertime.run.userTimings.measures
browsertime.run.visualMetrics.*
browsertime.run.custom.*
browsertime.run.cpu.categories.*
browsertime.run.cpu.longTasks.*
coach.summary.score.*
coach.summary.performance.score.*
coach.summary.privacy.score.*
coach.summary.bestpractice.score.*
coach.summary.accessibility.score.*
coach.run.score.*
coach.run.performance.score.*
coach.run.privacy.score.*
coach.run.bestpractice.score.*
coach.run.accessibility.score.*
coach.pageSummary.advice.score
coach.pageSummary.advice.performance.score
coach.pageSummary.advice.privacy.score
coach.pageSummary.advice.bestpractice.score
coach.pageSummary.advice.accessibility.score
coach.pageSummary.advice.info.documentHeight
coach.pageSummary.advice.info.domElements
coach.pageSummary.advice.info.domDepth
coach.pageSummary.advice.info.iframes
coach.pageSummary.advice.info.scripts
coach.pageSummary.advice.info.localStorageSize
pagexray.pageSummary.contentTypes
pagexray.pageSummary.transferSize
pagexray.pageSummary.contentSize
pagexray.pageSummary.requests
pagexray.pageSummary.firstParty
pagexray.pageSummary.thirdParty
pagexray.pageSummary.responseCodes
pagexray.pageSummary.expireStats
pagexray.pageSummary.totalDomains
pagexray.pageSummary.lastModifiedStats
pagexray.pageSummary.cookieStats
pagexray.summary.contentTypes
pagexray.summary.transferSize
pagexray.summary.contentSize
pagexray.summary.requests
pagexray.summary.firstParty
pagexray.summary.thirdParty
pagexray.summary.responseCodes
pagexray.summary.expireStats
pagexray.summary.domains
pagexray.summary.lastModifiedStats
pagexray.summary.cookieStats
pagexray.run.contentTypes
pagexray.run.transferSize
pagexray.run.contentSize
pagexray.run.requests
pagexray.run.firstParty
pagexray.run.thirdParty
pagexray.run.responseCodes
pagexray.run.expireStats
pagexray.run.domains
pagexray.run.lastModifiedStats
pagexray.run.cookieStats
thirdparty.pageSummary.category.*.requests.*
thirdparty.pageSummary.category.*.tools.*
thirdparty.pageSummary.requests.*
thirdparty.run.category.*.requests.*
thirdparty.run.category.*.tools.*
thirdparty.run.requests.*
`

**Comment by soulgalore** [comment]
Hi @Namac0 you have the metric in the https://dashboard.sitespeed.io/d/000000043/page-summary?editPanel=121&orgId=1 

<img width="813" alt="Screen Shot 2020-09-15 at 7 16 39 PM" src="https://user-images.githubusercontent.com/540757/93243137-0f264280-f788-11ea-9af4-99725232251c.png">

**Comment by Namac0** [comment]
@soulgalore Here's what worked :

`aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalBlockingTime.$function, 'average'),3, 4)`

Have you a solution for : Max Potential FID ?

**Comment by Namac0** [comment]
I searched for "totalBlockingTime" in configuredmetrics.txt and metrics.txt and I couldn't find it. Why @soulgalore

**Comment by soulgalore** [comment]
configuredmetrics.txt and metrics.txt are generated depending on the CLI input, so for example you need to turn on collect CPU data to get that into the metrics. MAX Potential Fid: In your Grafana instance, follow the same pattern as for total blocking and go key by after the cpu key and have a look.

**Comment by soulgalore** [comment]
This should automatically be sent when you enable `--cpu`
