### ISSUE TITLE
No impact on data collected with CPU throttling --chrome.CPUThrottlingRate

### ISSUE THREAD

**Issue by fxbtr** [sitespeedio/sitespeed.io#3148]
Hi,
I am running the following command: 
`docker run --rm -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io:13.2.0 --outputFolder ss7J20R189K -n 30 https://www.cdiscount.com --graphite.namespace PerformanceTest.ss7J20R189K --config ./config_base.json  --mobile -c 3gslow`

where config_base.json is: 
`{
  "browsertime": {
    "cpu": true,
    "video": false
  },
  "chrome": {
   "CPUThrottlingRate": 20
  },
  "plugins": {
    "list": true
  },
  "graphite": {
    "host": "XXXXXX",
    "experimental.perIteration": false
  },
  "metrics.filter": [
    "*-",
    "browsertime.pageSummary.statistics.cpu.longTasks.maxPotentialFid.stddev",
    "browsertime.pageSummary.statistics.cpu.longTasks.maxPotentialFid.median",
    "browsertime.pageSummary.statistics.cpu.longTasks.maxPotentialFid.mean",
    "browsertime.pageSummary.statistics.cpu.longTasks.totalBlockingTime.stddev",
    "browsertime.pageSummary.statistics.cpu.longTasks.totalBlockingTime.median",
    "browsertime.pageSummary.statistics.cpu.longTasks.totalBlockingTime.mean",
  ]
}`

The config is correctly picked up:
![image](https://user-images.githubusercontent.com/41640867/93584527-b6cc8c00-f9a5-11ea-983d-2ecca98f42c2.png)

I don't notice any difference if I use a rate of 2, 3, 4, 5, 10, 20 or 1 on cpu metrics, which is unexpected to me.
Am I missing a --cap-add maybe for this to work? The test are launched on Debian GNU/Linux 10 (buster).

Thank you
Best regards
FX

**Comment by soulgalore** [comment]
Hi @fxbtr I think this is the same as https://github.com/sitespeedio/browsertime/issues/1380 , I've pushed a fix for that earlier today, hopefully I will release it Sunday night or at least on Monday.

**Comment by fxbtr** [comment]
Ho indeed, sorry for the duplicate, thanks for getting back to me.
