### ISSUE TITLE
Video Record don't stop even using --video=false during preScript, video recording causes problem running on kubernetes pods

### ISSUE THREAD

**Issue by roshan02** [sitespeedio/sitespeed.io#3156]
Hi  @soulgalore, I am trying to run sitespeed in a Kubernetes pod there I am facing issues with video conversion. So i stopped recording video and conversion as well using `--video false  --videoParams.convert false` So it works fine for any normal site where you don't require login. But I am trying to test one site where it requires login, so I am using preScript, so the issue is even when the video is set false it records video during preScript. So what I think there's small bug that those video flags or params only comes into action after this preScript execution is over.
This is the video file that generates even when video is turned off: `x11-tmp.mp4` which cause my setup to fail. So is there any other way to stop this video recording?

One other thing why it fails for video on kubernetes pods whereas my same code works perfectly fine if I run it on any VM or my physical machine? So what I could gather, its having problem with those videos in pods.

**Comment by roshan02** [comment]
This is the error I get on running on a pod without turning off the video (There's no preScript here). Because of which I am trying to skip the video recording part.

`root@sitespeed-io-644c878d94-khkbs:/# ./start.sh https://www.sitespeed.io/ -n 1
Google Chrome 85.0.4183.121 
Mozilla Firefox 81.0
groupadd: group 'sitespeedio' already exists
useradd: user 'sitespeedio' already exists
[2020-10-01 05:29:43] INFO: Versions OS: linux 4.19.43-coreos nodejs: v12.16.2 sitespeed.io: 15.2.0 browsertime: 10.1.0 coach: 5.1.1
[2020-10-01 05:29:43] INFO: Running tests using Chrome - 1 iteration(s)
[2020-10-01 05:29:46] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2020-10-01 05:30:04] ERROR: Converting the video failed. Converting from /sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/x11-tmp.mp4 to /sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/pages/www.sitespeed.io/data/video/1.mp4
[2020-10-01 05:30:04] ERROR: Error: Command was killed with SIGKILL (Forced termination): ffmpeg -nostdin -i /sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/x11-tmp.mp4 -c:v libx264 -crf 23 -preset fast -vf format=yuv420p /sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/pages/www.sitespeed.io/data/video/1.mp4
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/x11-tmp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:08.27, start: 0.000000, bitrate: 2220 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), gbrp(tv, gbr/unknown/unknown), 1366x642, 2218 kb/s, 52 fps, 52 tbr, 13312 tbn, 104 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
[libx264 @ 0x739ec00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x739ec00] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0x739ec00] 264 - core 159 r2991 1771b55 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=20 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/pages/www.sitespeed.io/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1366x642, q=-1--1, 52 fps, 13312 tbn, 52 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   44 fps= 20 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/x11-tmp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:08.27, start: 0.000000, bitrate: 2220 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), gbrp(tv, gbr/unknown/unknown), 1366x642, 2218 kb/s, 52 fps, 52 tbr, 13312 tbn, 104 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
[libx264 @ 0x739ec00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x739ec00] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0x739ec00] 264 - core 159 r2991 1771b55 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=20 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43/pages/www.sitespeed.io/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1366x642, q=-1--1, 52 fps, 13312 tbn, 52 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   44 fps= 20 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
    at makeError (/usr/src/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/src/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DesktopRecorder.stop (/usr/src/app/node_modules/browsertime/lib/video/screenRecording/desktop/desktopRecorder.js:76:9)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:205:11)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:194:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-10-01 05:30:04] ERROR: TypeError: Cannot read property 'length' of undefined
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:116:31)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:198:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-10-01 05:30:08] INFO: HTML stored in /sitespeed-result/www.sitespeed.io/2020-10-01-05-29-43
`

**Comment by roshan02** [comment]
Hi @soulgalore, can you please take some time to look into this.

**Comment by soulgalore** [comment]
Hi @roshan02 sorry I've missed the issue. If you run using Docker both video and visual metrics is turned by default. The name of the video parameter isn't perfect: in this case it means keep the video (if you have visualMetrics turned on). Can you try with `--video false --visualMetrics false` ?

But then as you say it seems like there's more problems: video shouldn't be turned on when using preScript, I wonder if we can a simpler use case to reproduce that.

The error you get seems not to be related with the recording of the screen, it looks like when the video is converted. Are you able to grab a video from a run so we can look what it looks like?

**Comment by roshan02** [comment]
@soulgalore, so I tried these things (lets first resolve this and we will move to preScript issue, because if this gets resolved might it work for preScript also):
1.) ```root@sitespeed-io-644c878d94-m7wds:/# ./start.sh https://www.sitespeed.io/ -n 1 --video false --videoParams.convert false```
 works perfectly fine without any issue. I didn't find any video getting generated when I grabbed results so that's why maybe this works fine.

2.) ```root@sitespeed-io-644c878d94-m7wds:/# ./start.sh https://www.sitespeed.io/ -n 1 --video false --visualMetrics false```
This also works perfectly without any issue but this won't give me the visual metrics which I want so not of much use.

3.) ```root@sitespeed-io-644c878d94-m7wds:/# ./start.sh https://www.sitespeed.io/ -n 1```
This is what I want should work but this one fails at video conversion with the same error as above I am pasting again below. Also, this is the link to video file (this video won't play but, don't know what's issue with this file) https://we.tl/t-yp47FinoG5.


```root@sitespeed-io-644c878d94-m7wds:/# ./start.sh https://www.sitespeed.io/ -n 1                                    
Google Chrome 85.0.4183.121 
Mozilla Firefox 81.0
groupadd: group 'sitespeedio' already exists
useradd: user 'sitespeedio' already exists
[2020-10-14 06:47:15] INFO: Versions OS: linux 4.19.43-coreos nodejs: v12.16.2 sitespeed.io: 15.2.0 browsertime: 10.1.0 coach: 5.1.1
[2020-10-14 06:47:16] INFO: Running tests using Chrome - 1 iteration(s)
[2020-10-14 06:47:19] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2020-10-14 06:47:37] ERROR: Converting the video failed. Converting from /sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/x11-tmp.mp4 to /sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/pages/www.sitespeed.io/data/video/1.mp4
[2020-10-14 06:47:37] ERROR: Error: Command was killed with SIGKILL (Forced termination): ffmpeg -nostdin -i /sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/x11-tmp.mp4 -c:v libx264 -crf 23 -preset fast -vf format=yuv420p /sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/pages/www.sitespeed.io/data/video/1.mp4
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/x11-tmp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:08.06, start: 0.000000, bitrate: 2198 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), gbrp(tv, gbr/unknown/unknown), 1366x642, 2195 kb/s, 51 fps, 51 tbr, 13056 tbn, 102 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
[libx264 @ 0x6f71c00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x6f71c00] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0x6f71c00] 264 - core 159 r2991 1771b55 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=20 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/pages/www.sitespeed.io/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1366x642, q=-1--1, 51 fps, 13056 tbn, 51 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   37 fps= 24 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/x11-tmp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:08.06, start: 0.000000, bitrate: 2198 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), gbrp(tv, gbr/unknown/unknown), 1366x642, 2195 kb/s, 51 fps, 51 tbr, 13056 tbn, 102 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
[libx264 @ 0x6f71c00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x6f71c00] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0x6f71c00] 264 - core 159 r2991 1771b55 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=20 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15/pages/www.sitespeed.io/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1366x642, q=-1--1, 51 fps, 13056 tbn, 51 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   37 fps= 24 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
    at makeError (/usr/src/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/src/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DesktopRecorder.stop (/usr/src/app/node_modules/browsertime/lib/video/screenRecording/desktop/desktopRecorder.js:76:9)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:205:11)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:194:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-10-14 06:47:37] ERROR: TypeError: Cannot read property 'length' of undefined
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:116:31)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:198:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-10-14 06:47:41] INFO: HTML stored in /sitespeed-result/www.sitespeed.io/2020-10-14-06-47-15

```

**Comment by soulgalore** [comment]
The video works when I tried with VLC. When I checked it starts orange (as it should when we calculate visual metrics) but then its white and nothing is generated on the screen. That is strange. Do you get a screenshot and it looks ok?

**Comment by roshan02** [comment]
No actually I didn't find any screenshot in results folder and there's no report as well as run has failed. You can try running this  with my below deployment.yaml file.

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sitespeed-io
  labels:
    run: sitespeed-io
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sitespeed-io
  template:
    metadata:
      labels:
        run: sitespeed-io
    spec:
      containers:
      - name: sitespeed-io
        image: sitespeedio/sitespeed.io
        securityContext:
          privileged: true
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        volumeMounts:
          - mountPath: /sitespeed.io
            name: sitespeed-volume
      restartPolicy: Always
      volumes:
        - name: sitespeed-volume
          hostPath:
            path: '/tmp/'
        - name: dshm
          emptyDir:
            medium: 'Memory'
            sizeLimit: '2800Mi'
```

**Comment by roshan02** [comment]
Hi @soulgalore, can you please try with this above deployment.yaml file, I think this will help you in reproducing the error which I have got. Just try deploying using this deployment.yaml and run this below command.
```root@sitespeed-io-644c878d94-m7wds:/# ./start.sh https://www.sitespeed.io/ -n 1```

**Comment by soulgalore** [comment]
@roshan02 I didn't get it to work on my local machine with Kubernetes, can you guide me (I'm using OS X) in a couple of steps? Or what's the easiest way to reproduce, use. a new linux box with your deploy file? I haven't used Kubernetes.

**Comment by roshan02** [comment]
@soulgalore Hi, so do you have kubernetes installed on your mac, with kubect commad working? So if that is working. You need to follow the following commands.
First lets check if kubectl is installed: ```kubectl version --client ````

If this works we are good to go ahead. Now just copy above deployment.yaml file to your local system and then just use this command:
```kubectl apply -f deployment.yaml```

WIth this we should be able to successfully deploy sitespeed on kubernetes. This is how you can check the status.
```kubectl get pods -w```
You should wait till sitespeed pod goes into running state.
Now we will go inside our kubernetes pod and try running sitespeed test manuallly. So for that just use following command.
```kubectl exec -it sitespeed-io-644c878d94-zj2pb bash```
So you will have some name of sitespeed pod just similar to above with some new random string attached at end like sitespeed-io-xxxxxxxxxx-xxxxx

Now you will we inside sitespeed pod here if we can run following command to run our test.

```
root@sitespeed-io-644c878d94-zj2pb:/# cd ..
root@sitespeed-io-644c878d94-zj2pb:/# ./start.sh https://www.sitespeed.io/ -n 1

```
With this your sitespeed test should start running.

![image](https://user-images.githubusercontent.com/22377561/98202824-dc632400-1f58-11eb-838e-346008bc4be8.png)

**Comment by soulgalore** [comment]
I would avoid running tests on Kubernetes since you cannot set the throttling.
