### ISSUE TITLE
Sitespeed hits session in Google Analytics

### ISSUE THREAD

**Issue by marithpl** [sitespeedio/sitespeed.io#3158]
We have a problem with sitespeed.io which make hit sessions to our GA.
The server IP is excluded on GA filters despite this we see pageviews on tested sites.

Do you have any recommendation? Maybe we made a mistake in installation?

**Comment by soulgalore** [comment]
Hi @marithpl I don't use Google Analytics. Can you filter in any other way, like add a specific string to the User Agent and remove that traffic?

**Comment by marithpl** [comment]
We will try

**Comment by Icecold777** [comment]
Hi @marithpl, if you use sitespeed.io docker version it's possible to block host by mapping it to localhost. just add docker flag to stary command --add-host="your_hostname:127.0.0.1". Sitespeed won't send any call to GA.

**Comment by soulgalore** [comment]
Closing since I think its ways to get around this.
