### ISSUE TITLE
On PowerShell console, doesn't work

### ISSUE THREAD

**Issue by AdrianoCahete** [sitespeedio/sitespeed.io#3159]
PC Info:
Microsoft Windows 10 Pro 64 bits (10.0.19041)
Shell: PowerShell 5.1.19041.1

With npm package, when you call the package with `sitespeed.io https://www.google.com/`, the popup to "Open with" appears to open the `.io` filetype. If you open in notepad, this will open the node package or sh file, I think?

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/sitespeed.io/bin/sitespeed.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/sitespeed.io/bin/sitespeed.js" "$@"
  ret=$?
fi
exit $ret

```

**Comment by tpynak** [comment]
Use sitespeed.io.cmd, rather than sitespeed.io
i.e. sitespeed.io.cmd https://www.google.com
