### ISSUE TITLE
Reports are owned by root

### ISSUE THREAD

**Issue by prudloff-insite** [sitespeedio/sitespeed.io#3177]
I see that since https://github.com/sitespeedio/sitespeed.io/pull/2710, sitespeed.io should not create reports owned by root.
However, on our CI reports are still owned by root, which causes various problems. (Other non-root CI tasks can't delete them.)

Here is what I am running to reproduce locally:
```bash
docker run  --rm --shm-size 1g --volume '/mnt/89001ee4-8dbb-4cb0-a7a4-bb066e75a834/workspace/drupal_d9/robo/../tests/:/cnf/' -i sitespeedio/sitespeed.io:15.6.4 --config /cnf/sitespeed.io/config.json --budget.configPath /cnf/sitespeed.io/budget.json --budget.output junit --browsertime.connectivity.profile cable --browsertime.video false --browsertime.visualMetrics false http://example.com/ --outputFolder /cnf/reports/sitespeed/desktop/
```

I am using Docker 19.03.13 on  Linux Mint 20. `docker` is called by my normal non-root user.

Our budget and config files are pretty basic:
```json
{
  "browsertime": {
    "headless": true
  },
  "summary-detail": true,
  "plugins": {
    "remove": [
      "assets",
      "coach",
      "domains",
      "harstorer",
      "html",
      "pagexray",
      "screenshot",
      "tracestorer",
      "crawler",
      "metrics"
    ]
  }
}
```

```json
{
  "browsertime.pageSummary": [
    {
      "metric": "statistics.timings.rumSpeedIndex.median",
      "max": 1000
    }
  ]
}
```

**Comment by soulgalore** [comment]
Hi @prudloff-insite thanks for creating the issue. @MasonM it should pickup so the files are owned by the owner directory right? @prudloff-insite who owns the dir you mount?

**Comment by prudloff-insite** [comment]
The directory I am mounting as a volume is owned by my own user.

**Comment by soulgalore** [comment]
I wonder then if something has changes along the line then, I think we upgraded Ubuntu since that fix. i can have a try to reproduce it tomorrow.

**Comment by soulgalore** [comment]
I tried on Ubuntu 20 and there it worked (I created a new user, that user run Docker and the files was owned by that user). @prudloff-insite is there a easy way for me to try on Linux Mint 20?

**Comment by MasonM** [comment]
This appears to be a repeat of https://github.com/sitespeedio/sitespeed.io/issues/2898. The working directory for the Docker image is `/sitespeed.io`, not `/cnf`. Try this command:
```
docker run  --rm --shm-size 1g --volume '/mnt/89001ee4-8dbb-4cb0-a7a4-bb066e75a834/workspace/drupal_d9/robo/../tests/:/sitespeed.io/' -i sitespeedio/sitespeed.io:15.6.4 --config /cnf/sitespeed.io/config.json --budget.configPath /sitespeed.io/sitespeed.io/budget.json --budget.output junit --browsertime.connectivity.profile cable --browsertime.video false --browsertime.visualMetrics false http://example.com/ --outputFolder /sitespeed.io/reports/sitespeed/desktop/
```

**Comment by prudloff-insite** [comment]
Oh right, this makes sense. Mounting `/sitespeed.io/` does indeed work.
Thanks for the help!
