### ISSUE TITLE
Use AWS Timestream serverless time series database instead of Influxdb database

### ISSUE THREAD

**Issue by amitmalhotra-cell** [sitespeedio/sitespeed.io#3187]
Problem statement : 
Is it possible to **Use AWS Timestream serverless time series database instead of Influxdb database**

_Example :_ 
I am using influxdb as below : 

_docker run --rm -v %cd%:/sitespeed.io sitespeedio/sitespeed.io:14.0.0 -n 1 /sitespeed.io/UrlPath.txt -–influxdb.host XXX.XXX.X.XX -–influxdb.port 8086 -–influxdb.database DBNAME  --resultBaseURL S3bucketurl_

**I need to know if there is support/any documentation for using AWS Timestream serverless time series database instead of Influxdb database?**

**Comment by soulgalore** [comment]
Hi @amitmalhotra-cell you need to build a [plugin](https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin) to handle a new database.
