### ISSUE TITLE
Cannot extends properties with another configuration file

### ISSUE THREAD

**Issue by mploquin** [sitespeedio/sitespeed.io#3190]
Hi @soulgalore,

I have a problem with the `extends` properties of a configuration file.

I have two configuration files `desktop.json` and `secrets.json` in a directory `testsitespeedio`

**desktop.json**
```
{
  "extends": "./secrets.json",  
  "graphite": {
    "annotationScreenshot": true
  } 
}
```
**secrets.json**
```
{  
  "graphite": {
    "host": "graphite.host",
    "httpPort": 80,
    "auth": "guest:guest"
  } 
}
```

and when i run sitespeed with the command line in the same directory `testsitespeedio`, i have the following error :

```
sitespeed.io --config=desktop.json  https://www.google.fr

[2020-11-07 10:22:12] INFO: Versions OS: linux 5.8.0-26-generic nodejs: v12.14.1 sitespeed.io: 15.7.2 browsertime: 10.6.4 coach: 5.1.1
[2020-11-07 10:22:12] ERROR: Error: Required option(s) [ '"host"' ] need to be specified in namespace "graphite"

```

It's the same thing with the docker image.

There is something particular to do ?

Thank's

**Comment by soulgalore** [comment]
Hi @mploquin hmm we use https://github.com/yargs/yargs for the configurations. At work I use absolute paths for finding extended configs to get it to work (but there we have the configs at different locations). I need to try to have them on the same location, it should work, but could it be that extends is relative to where you run sitespeed.io?

**Comment by soulgalore** [comment]
Also let me test it more tomorrow, I wonder if something can have changed upstream, I also got some error when I tried.

**Comment by mploquin** [comment]
I wanted to create a kubernetes cronjob. But in the jobs, the sitespeed.io configuration files are mounted in a volume with an absolute path and i have the same error...

**Comment by soulgalore** [comment]
I tested now and it works for me with your example I created the two JSON files and run:
```
❯ sitespeed.io --config desktop.json https://www.sitespeed.io -n 1
[2020-11-09 09:47:57] INFO: Versions OS: darwin 19.6.0 nodejs: v10.15.3 sitespeed.io: 15.7.2 browsertime: 10.6.4 coach: 5.1.1
[2020-11-09 09:47:58] INFO: Running tests using Chrome - 1 iteration(s)
[2020-11-09 09:48:00] INFO: Testing url https://www.sitespeed.io iteration 1
[2020-11-09 09:48:09] INFO: https://www.sitespeed.io 12 requests, TTFB: 184ms, firstPaint: 425ms, FCP: 425ms, DOMContentLoaded: 379ms, LCP: 845ms, CLS: 0, TBT: 0ms, Load: 816ms
[2020-11-09 09:48:09] ERROR: Error: getaddrinfo ENOTFOUND graphite.host graphite.host:2003
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
```

The problem I've been seeing at work was my fault, the JSON wasn't correct structured. 

The example you added, do that not work for you or is it a simplified example?

**Comment by mploquin** [comment]
Hi Peter,

It's a simplified example and I know where the error came from.... :upside_down_face: 
I was using a wrong parameter assignment for config, with an equal :  

`> sitespeed.io --config=desktop.json https://www.sitespeed.io -n 1`

But actually there isn't, my bad :see_no_evil: 

However I find an error that I have already encountered, if you can look at [it](https://github.com/sitespeedio/sitespeed.io/issues/2918#issuecomment-698216770)
And thank you very much for your work on sitespeed.io.

**Comment by soulgalore** [comment]
Closing since extending works.
