### ISSUE TITLE
Can't get browsertime.chrome.args to work when defined using JSON config

### ISSUE THREAD

**Issue by fabis94** [sitespeedio/sitespeed.io#3192]
Tried to disable Chrome cache using the solution outlined in this issue: https://github.com/sitespeedio/chrome-har/issues/1#issuecomment-367370561

But I can't get it to work when using the JSON config. This is how I defined the chrome args there:

```
{
  "browsertime": {
    "chrome": {
      "args": [
        "disk-cache-dir=/dev/null",
        "disk-cache-size=1",
        "media-cache-size=1"
      ]
    }
  }
}
```

There's not much documentation around this so I'm wondering if I'm passing in the args the correct way. Is there any way to verify that these args actually are passed to Chrome?

**Comment by soulgalore** [comment]
Hi @fabis94 that looks right. Let me add a verbose log for all arguments so its easier to verify.

**Comment by soulgalore** [comment]
@fabis94 the configuration is logged now. I created a config file as you described and named it *config.json* and then I run: `sitespeed.io --config config.json https://www.sitespeed.io -n 1 --verbose`

`[2021-04-15 21:01:43] DEBUG: [browsertime.chrome] Setting the following Selenium options: {"map_":{},"options_":{"prefs":{"profile.password_manager_enable":false,"profile.default_content_setting_values.notifications":2,"credentials_enable_service":false},"args":["--window-position=0,0","--window-size=1366,708","--ignore-certificate-errors","--disable-background-networking","--no-default-browser-check","--no-first-run","--new-window","--allow-running-insecure-content","--disable-client-side-phishing-detection","--disable-component-update","--disable-default-apps","--disable-device-discovery-notifications","--disable-domain-reliability","--disable-background-timer-throttling","--load-media-router-component-extension=0","--mute-audio","--disable-hang-monitor","--password-store=basic","--disable-breakpad","--dont-require-litepage-redirect-infobar","--override-https-image-compression-infobar","--disable-fetching-hints-at-navigation-start","--remote-debugging-port=9222","disk-cache-dir=/dev/null","disk-cache-size=1","media-cache-size=1"],"perfLoggingPrefs":{"enableNetwork":true,"enablePage":true},"excludeSwitches":["enable-automation"]}}`

so ... the setting is missing `--`. Changing to:

```
{
  "browsertime": {
    "chrome": {
      "args": [
        "--disk-cache-dir=/dev/null",
        "--disk-cache-size=1",
        "--media-cache-size=1"
      ]
    }
  }
}
```
So the cli HELP is wrong when you use it in a configuration file. I'm gonna change that now, sorry!

**Comment by soulgalore** [comment]
Will come in next fix release, probably tomorrow.
