### ISSUE TITLE
Can't see LCP and CLS in InfluxDB backend

### ISSUE THREAD

**Issue by egouraud-claranet** [sitespeedio/sitespeed.io#3193]
Hi there

it seems that LCP and CLS are measured but not written into influxdb backend, is it possible to add them ?

```
[2020-11-12 15:01:16] INFO: mysite 127 requests, TTFB: 36ms (±5.21ms), firstPaint: 1.25s (±19.14ms), firstVisualChange: 1.38s (±23.57ms), FCP: 1.25s (±19.14ms), DOMContentLoaded: 1.72s (±23.58ms), LCP: 1.65s (±33.18ms), CLS: 0.0963 (±0.01), TBT: 360ms (±12.91ms), Load: 2.37s (±79.30ms), speedIndex: 1.69s (±23.21ms), visualComplete85: 1.78s (±20.14ms), lastVisualChange: 2.84s (±9.54ms) (3 runs)
```
**How to reproduce?**

use latest version of sitespeed docker container and configure an InfluxDB backend
no measurement with those particular names

thx

**Comment by scrobertson** [comment]
Same issue here

**Comment by soulgalore** [comment]
Hi @egouraud-claranet yes it is, they should be added by default, let me have a look.

**Comment by soulgalore** [comment]
If you check for the tags { statistics: 'timings', largestContentfulPaint: 'renderTime' } that is LCP. For CLS I think it should be visible with statistics: 'pageinfo', let me know if it works.

**Comment by scrobertson** [comment]
Hi yeah my bad. 
renderTime = LCP
layoutShift = CLS

Those who use FID 
measurement - duration
Tag - firstInput

**Comment by soulgalore** [comment]
Yeah, sorry. Internally in Chrome LCP has many fields https://wicg.github.io/largest-contentful-paint/#largestcontentfulpaint. For CLS ity has changed name in Chrome and maybe we should double that metric so its named also after their new standard.

**Comment by soulgalore** [comment]
With the new release 17.0.0  you can find all Google Web Vitals with the tag "statistics" set to "googleWebVitals".
