### ISSUE TITLE
Sending data to Graphite  not working

### ISSUE THREAD

**Issue by deena9291** [sitespeedio/sitespeed.io#3195]
sitespeed image: sitespeedio/sitespeed.io:15.8.0
graphite image:  sitespeedio/graphite:1.1.5-12
grafana image :  grafana/grafana:7.3.1

I am running all 3 images as diff pods in the same node on a K8 cluster. When trying to send the metrics to graphite, I see only respective folders being created but metrics are not updated in graphite. PFB screen shot;
![image](https://user-images.githubusercontent.com/62435018/99476559-c6713e00-291e-11eb-9f2a-fd90346b0c83.png)

When I use the graphite-statsd image (graphiteapp/graphite-statsd:1.1.7-7), I see partial metrics being sent to graphite. hence the connection seems to be working fine, I am not sure what could be the issue here. I tried to use the sitespeed provided conf files on the graphite-statsd image as well, no luck :(

Please help me to resolve this issue, I am stuck here for last 3 days, your help will be much appreciated !!

**Comment by soulgalore** [comment]
Hi @deena9291 can you explain a little bit more what you mean by "I see partial metrics being sent to graphite.", I didn't fully get that? 

By default the Graphite have a very conservative limit of creating new metrics (checkout MAX_CREATES_PER_MINUTE in carbon.conf). I think default is 50, so it will be overloaded. If you use the sitespeedio/graphite from the beginning it should help (there its set to inf). Easiest is if you remove all folders, restart Graphite and send metrics again (using the sitespeed.io version). If you use the official Graphite image you need to configure schema https://github.com/sitespeedio/docker-graphite-statsd/blob/main/conf/graphite/storage-schemas.conf and aggregation https://github.com/sitespeedio/docker-graphite-statsd/blob/main/conf/graphite/storage-aggregation.conf and change MAX_CREATES_PER_MINUTE.

Best
Peter

**Comment by deena9291** [comment]
Hi Peter,

Thanks a lot for the quick response, I tried again with the below;
graphite image: sitespeedio/graphite:1.1.5-12 (recreated the graphite container)

carbon.conf: I used the all the 3 recommended .conf files from here (https://github.com/sitespeedio/docker-graphite-statsd/tree/main/conf/graphite)
![image](https://user-images.githubusercontent.com/62435018/99542911-935f9680-2980-11eb-979c-937f86d184dd.png)

Graphite Image:
![image](https://user-images.githubusercontent.com/62435018/99543288-0537e000-2981-11eb-975a-185b4e5a6b0a.png)

Whisper folders inside the graphite pod before test:
![image](https://user-images.githubusercontent.com/62435018/99543117-cd309d00-2980-11eb-9c82-68c96a49a784.png)

Test Logs: this confirms the data being sent
![image](https://user-images.githubusercontent.com/62435018/99543370-18e34680-2981-11eb-8e9d-7c37894402db.png)

Still no luck, I see empty folders in graphite;
![image](https://user-images.githubusercontent.com/62435018/99544014-d5d5a300-2981-11eb-9a3c-7ace495db956.png)

When I used the graphiteapp/graphite-statsd:1.1.7-7 image, I saw some of the data like # of reqs per page, total transfer size and few other metrics being written to graphite with the same script.

Please let me know if you need further information.

**Comment by deena9291** [comment]
Worked for me after below fixes in K8's;
1. Create the graphite container with - graphiteapp/graphite-statsd:1.1.7-7
2. Update the conf files from here - https://github.com/sitespeedio/docker-graphite-statsd/tree/main/conf/graphite
3. Add the environment variable to fix the tagging errors in graphite logs - kubectl set env deployment/graphite REDIS_TAGDB=1 -n graphite. This variable has to be added to the manifest.
4. Use the latest site speed image - sitespeedio/sitespeed.io:15.9.0-plus1

Finally !!
![image](https://user-images.githubusercontent.com/62435018/99600168-e100f100-29ca-11eb-8982-f1dfde7ed399.png)

Open Issues:
1. sitespeedio graphite image is not working in K8's (sitespeedio/graphite:1.1.5-12), I was getting "builtins.OSError: [Errno 95] fallocate" from graphite container even after setting "WHISPER_FALLOCATE_CREATE = False" in carbon.conf. I tried to use couple of different images, same issue in everything.

2. Even if you use "graphiteapp/graphite-statsd:1.1.7-7", respective metrics folder are not created automatically, we have to execute a test with sitespeedio/graphite:1.1.5-12, even though this run will not send any data to graphite, it will create required folder structure. We have to switch back to "graphiteapp/graphite-statsd:1.1.7-7" to push the metrics to get it working.

I am still working on few more upgrades to my framework (which will execute the test using Jenkins for every meaningful code change and push results to grafana)  where I foresee some challenges, I will keep you posted !

Thanks,
Deena

**Comment by soulgalore** [comment]
Thanks for getting back @deena9291   

>1.  sitespeedio graphite image I

That's is just a wrapper around the graphiteapp/graphite-statsd but the versions differ so my guess is that we should update it to contain the latest version graphiteapp/graphite-statsd. I'll fix that later this week.


> Even if you use "graphiteapp/graphite-statsd:1.1.7-7", respective metrics folder are not created automatically, 

Like the base folder? I didn't fully understand that. You mount where you want to store the data on disk, and then when you run the first sitespeed.io test and send the data, the folders structure will be created.

**Comment by deena9291** [comment]
Closing this issue as the set up is working fine.
