### ISSUE TITLE
could not add meta data to the HAR, miss page "X" again

### ISSUE THREAD

**Issue by whichfinder** [sitespeedio/sitespeed.io#3196]
Hello
At first - thank you for such a good tool.

I am running the latest version : Versions OS: linux 5.4.0-53-generic nodejs: v12.16.2 sitespeed.io: 15.9.0 browsertime: 10.9.0 coach: 5.1.1

My test script is something like:

```
module.exports = async function (context, commands) {
	try {

		const maxTime = 60000;
		const webdriver = context.selenium.webdriver;
		const driver = context.selenium.driver;
		const actions = driver.actions();
		const email = process.env.EMAIL;
		const password = process.env.PASSWORD;
		const host = process.env.HOST;

		await commands.measure.start('Open home page');
                await commands.navigate(<my_host_name>);
                await commands.wait.bySelector('#username');
                await commands.measure.stop();

                await commands.addText.bySelector(username, '#username');
                await commands.addText.bySelector(password, 'input#password');

                await commands.measure.start('Do login');
                await commands.click.bySelectorAndWait('button[type="submit"]');
                await commands.wait.bySelector('.btn.btn--primary.btn--medium', this.maxTime);
		await commands.click.bySelector('.btn.btn--primary.btn--medium');
                await commands.measure.stop();

		let oppUrl = await this.getUrl();   // getting current url here 

		await commands.measure.start('Submit');
		await commands.navigate(oppUrl, 'Submit');
		await commands.wait.byXpath("//a[contains(@href, '/command/')]", this.maxTime);
		await commands.measure.stop();

	} catch (e) {
		throw e;
	}
}

```

I run it inside docker with a command:
`docker run --rm --env EMAIL=my_mail --env PASSWORD=my_password --env HOST=my_host -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest script.js --multi --config config.json --spa`

my config:
`{
    "browsertime": {
      "browser": "chrome",
      "viewPort": "1920x1080",
      "iterations": 1,
      "spa": true,
      "video": true,
      "visualElements": true,
      "visualMetric": true,
      "pageCompleteWaitTime": 10000
    },
    "chrome": {
        "collectLongTasks": true
    },
    "screenshot": {
      "type": "jpg"
    },
    "multi": true
  }`

Result:
I get a correct report with all metrics and measurement except for the last action.

There is an error in my log: [2020-11-18 22:16:08] ERROR: Could not add meta data to the HAR, miss page "X"

And my report page shows me the last URL on "Pages" section without alias (please check  [screenshot](https://imgur.com/CZMlCHI) PS: hostname and some query params were changed on screenshot but it shows the issue)

Note: getting current url was some sort of workaround, but even without that extra navigation I see the same report

Can you please point me what is wrong?
I've checked other reported issues : #2941 , #2918, #958, #2828, #1872, #1548, #2953 and proposed solutions don't work for me.

**Comment by soulgalore** [comment]
Hi @whichfinder `miss page "X"` almost always comes from that the script never navigated to a new page (but the script try to measure one).  Let me make that error messages better in the coming release. When I get a error like that I run the script on my local machine (using NodeJS) and look at the browser to see what's going on. https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

**Comment by whichfinder** [comment]
Hi, @soulgalore, yes I am aware of this. I checked this locally and it works. Also, recorded video shows that navigation happens and even there are metrics present on video for that page [screenshot from video](https://imgur.com/BqkJDAa)

**Comment by whichfinder** [comment]
Hi, @soulgalore 
I have managed to resolve this issue. Some details: during steps of my tests I was trying to measure actions that were within the same browser URL. Navigate didn't help in this case so I've made a dirty hack that replace url parts during measurement.
So, issue can be closed.

PS: if you want I can show you workaround that I did

**Comment by Icecold777** [comment]
@whichfinder please show how did you manage to solve the issue

**Comment by whichfinder** [comment]
@Icecold777 

I am not sure that this is a best way, but for our purposes this works pretty well:

I have this function:

async hackMeasurement(currentUrl) {
        let ts = Date.now()
        let subString = currentUrl.split('#')[0].split('documents')[1]   # here you need to split by needed url part
        let jsString = "history.pushState('','','" + subString + "&ts=" + ts +"')" 
        return jsString
    }

it generates url with custom params. Then, call this function inside your measurement. For example, you have action:

async someAction() {
    let currentUrl = await getUrl(); # get current browser url
    let neededSubstring = await hackMeasurement(currentUrl);

    await this.commands.measure.start('measure some action);
    await this.commands.js.run(neededSubstring) # here you replace your current url without navigating to it
    <do actions you want to measure>
    await this.commands.measure.stop();
  }

If it is not clear - ping me on linkedin (link is in my profile)
