### ISSUE TITLE
Influx Cloud (v2) support

### ISSUE THREAD

**Issue by danielloader** [sitespeedio/sitespeed.io#3197]
I've read the documentation and other issues on here, and I've noticed in this [reply](https://github.com/sitespeedio/sitespeed.io/issues/3015#issuecomment-635153227) that sitespeed leverages the [node-influx ](https://github.com/node-influx/node-influx/) package for connectivity with influxDB.

However node-influx aren't advertising compatibility with InfluxDB 2, suggesting to use the official [influxdb-client-js](https://github.com/influxdata/influxdb-client-js/) package instead. (https://github.com/node-influx/node-influx/issues/483#issuecomment-597657588) 

Is this on the roadmap to support the new influxdb client library?
Thanks

**Comment by soulgalore** [comment]
Hi @danielloader ah cool, I'm no InfluxDB user so I haven't noticed there's a new version. I'm busy with work for the rest of the year that has higher prio for me, but I can help out if someone wanna make a PR.

Best
Peter

**Comment by ahoiroman** [comment]
+1 for this. Unfortunately I cannot help with code but I would love to help by testing etc.

**Comment by ahoiroman** [comment]
As far as I know it's not - the read-API kinda is, but the write is not. But maybe a switch could be added (`--influx-version`)?
