### ISSUE TITLE
Support helm chart for Dashboard

### ISSUE THREAD

**Issue by thanhtoan1196** [sitespeedio/sitespeed.io#3198]
Please support helm chart for easier installation.
https://helm.sh/

**Comment by soulgalore** [comment]
Hi @thanhtoan1196 that would be cool. I'm not sure though, I usually avoid recommend people running on Kubernetes since there's no good way to throttle the network connection on Kubernetes, I know people been using TSProxy but I'm not 100% sure though how good it works.

**Comment by thanhtoan1196** [comment]
@soulgalore I think supporting Kubernetes for Dashboard is enough
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#production-guidelines

**Comment by soulgalore** [comment]
Yeah I see. I wonder if someone could contribute an example, I'm have a full list of things I need to do first before Christmas.

**Comment by soulgalore** [comment]
Kubernetes make me shiver. I agree setting up the dashboard could be ok, but I don't actually see why ut need be in Kubernetes. Closing and will keep it close until someone can convince me.
