### ISSUE TITLE
Support LocalStorage

### ISSUE THREAD

**Issue by IngCesarPerf** [sitespeedio/sitespeed.io#3200]
Hi, 

I am using the latest version 15.9.0 at the time of the Issue.
When executing through the terminal I am using the parameter --cookie cookieName = cookieValue and it works very well with the analyzes I carry out, however, in addition to the use of the cookie I need to send the name of a localStore and value string, since within navigating the page I'm testing, a flow creates that localstorage and stores information that I need to continue with the next flow. I hope you can help me how to use localstorage from the terminal (I'm using docker).

Thank you 
regards.

**Comment by soulgalore** [comment]
Hi @IngCesarPerf I think you should look at https://chromedevtools.github.io/devtools-protocol/ and use https://www.sitespeed.io/documentation/sitespeed.io/scripting/#chrome-devtools-protocol
