### ISSUE TITLE
Total transfer size in reports not matching with manual data collected for same action using chrome inspect elemment

### ISSUE THREAD

**Issue by roshan02** [sitespeedio/sitespeed.io#3232]
Hi, @soulgalore I was doing one test using scripts but the Total transfer size data which I was getting in HTML report was not matching with the manual data collected. So I have created this below reproducible issue on a public website.
I am getting the total transfer size value as 74KB in HTML report whereas the actual data transfer size when I tried manually is 645KB. Make sure you disable cache while testing manually.

Here I have created a reproducible issue for this. You can save this file as script.js and run using the below command:
```docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:15.9.0 script.js -n 2 --spa true --browsertime.cacheClearRaw --multi --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 10000;} catch(e) {} return true;})()'```

script.js

```
module.exports = async function(context, commands) {
  // We start by navigating to the login page.
  await commands.navigate('http://testyou.in/Login.aspx');
  context.log.info('##### waiting for page to load ######');
  try {
    await commands.wait.byTime(3000);
    // Add text into an input field, finding the field by id
    await commands.addText.byId('johndoe0204', 'ctl00_CPHContainer_txtUserLogin');
    await commands.addText.byId('Test@123', 'ctl00_CPHContainer_txtPassword');
    await commands.measure.start('Login_Page');
    await commands.click.byIdAndWait('ctl00_CPHContainer_btnLoginn');
    await commands.wait.byTime(2000);
    return commands.measure.stop();
  }
  catch (e) {
    // We try/catch so we will catch if the the input fields can't be found
    // The error is automatically logged in Browsertime an rethrown here
    // We could have an alternative flow ...
    // else we can just let it cascade since it caught later on and reported in
    // the HTML
    throw e;
    context.log.info('#######-----$$$$$error occurred!!$$$$$-------########3');
  }
};
```

**Comment by soulgalore** [comment]
Hi @roshan02 thanks for creating the issue. Do you see the same number of requests in both use cases?

**Comment by roshan02** [comment]
Hi, @soulgalore No total number of requests also different in both cases. Manually I can see 55 requests whereas using sitespeed scripts I can see 23 requests. But in the video returned in sitespeed results I can see everything is going as expected.

**Comment by soulgalore** [comment]
I haven't seen that we loose requests before so I think somehow how you are measuring. To debug it I would try different browsers Chrome vs Firefox to see if you see the same in both browsers. And then check in details look at the request and compare what's the different then I hope you can see what's going on.

**Comment by roshan02** [comment]
Hi @soulgalore I tried with firefox and chrome getting requests count and total transfer size in a similar range but not exactly the same, but they are much different than what sitespeed is returning. Are you getting some different results?

**Comment by roshan02** [comment]
@soulgalore can you please confirm your observation if it was different than mine.

**Comment by soulgalore** [comment]
Sorry I haven't had time to look, hopefully I can have a go tomorrow.

**Comment by soulgalore** [comment]
Hi @roshan02 so the HAR file only shows file that are made on the wire, in devtools you see also the ones servers from cache:
<img width="1068" alt="Screenshot 2021-01-26 at 03 37 38" src="https://user-images.githubusercontent.com/540757/105792569-f32d7b80-5f87-11eb-8fc6-29b3b1a1e209.png">

Could that be the thing?
