### ISSUE TITLE
Create example on how to run on the free Grafana Cloud setup

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#3250]
Lets create documentation on how to setup the free instance of Grafana Cloud:
https://grafana.com/blog/2021/01/12/the-new-grafana-cloud-the-only-composable-observability-stack-for-metrics-logs-and-traces-now-with-free-and-paid-plans-to-suit-every-use-case/

**Comment by SoNiC-HeRE** [comment]
I'm interested on working on this issue

**Comment by soulgalore** [comment]
@SoNiC-HeRE great, let me know if you need any help!

**Comment by soulgalore** [comment]
This never happen so closing.
