### ISSUE TITLE
sitespeed doesn't work when I use score in budget

### ISSUE THREAD

**Issue by akinv** [sitespeedio/sitespeed.io#3256]
I'm running this command line

`
docker run --rm \
    -v "${PWD}:/sitespeed.io" \
    sitespeedio/sitespeed.io:16.2.1-plus1 \
    urls.txt \
    -n 1 \
    --outputFolder performance-reports-output \
    --budget.configPath budget.json \
    --budget.output junit \
    --plugins.remove /lighthouse,/gpsi
`
budget.json
`{
  "budget": {
    "score": {
      "accessibility": 100,
      "performance": 100
    }
  }
}
`

This gives me this error
"ERROR: TypeError: Cannot read property 'path' of undefined
    at verify (/usr/src/app/lib/plugins/budget/verify.js:44:68)
    at Object.processMessage (/usr/src/app/lib/plugins/budget/index.js:39:9)
    at /usr/src/app/lib/core/queueHandler.js:214:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (internal/timers.js:456:21)"

if I remove score and add "timings" then i don't get any error and budget works fine.
Am I missing something?

I know there is a similar issue in 2019, I see the score was used, but doesn't work in my local. 
https://github.com/sitespeedio/sitespeed.io/issues/2307

**Comment by soulgalore** [comment]
Hi @akinv thank you for filing the issue! Either there's a bug or something is wrong in the documentation, let me try to fix it the coming days.

**Comment by soulgalore** [comment]
Ah I see now. "accessibility" was [removed from the Coach in 16.0](https://www.sitespeed.io/sitespeed.io-16.0-browsertime-11.0-coach/), its better to use AXE. I'll fix that error message, its really hard to understand.
