### ISSUE TITLE
Unable to execute sitespeed using docker in git repository.

### ISSUE THREAD

**Issue by TusAuto** [sitespeedio/sitespeed.io#3261]
I am unable to execute sitespeed in git pipeline using docker image. Issue is in git $(pwd) is not mounting to local script to docker container. Hence Unable to find overview.js file error message in pipeline.

1. I have added our project hierarchy image. [ Folder structure ].
2.  I have also added .yml file from git.
3.  Also attached Pipeline error message.

Please let me know why $(pwd) in git is not finding local script files.
![git_project_hierarchy](https://user-images.githubusercontent.com/47890381/104998704-ad395a80-5a51-11eb-93bc-44159c6b6cb2.PNG)
![git-lab yml](https://user-images.githubusercontent.com/47890381/104998709-ae6a8780-5a51-11eb-9430-14849e5bca76.PNG)
![Error in pipeline](https://user-images.githubusercontent.com/47890381/104998711-af031e00-5a51-11eb-9445-d198d55bd96e.PNG)

**Comment by soulgalore** [comment]
Hi @TusAuto do not GitLab have any documentation of mount directories, I'm thinking they maybe have a standard way of handling?

**Comment by soulgalore** [comment]
There has been multiple issues for GitLab users, mounting when using Docker in Docker seems to be a problem. Please check with GitLab how they solve it.
