### ISSUE TITLE
Add  meta data or tags dynamically to each tested URL

### ISSUE THREAD

**Issue by ahoiroman** [sitespeedio/sitespeed.io#3263]
Hello,

I would like to solve the following problem:

Sitespeed is reporting data to influxdb, which is just working fine.

Now I got a lot of tested websites and Grafana is supposed to display all those results, but I would like to filter access to specific websites by using some kind of website-to-organization-relation.

To archive this, I thought about adding a user-id or organization name as a tag. 

My question: If I provide a list of domains to sitespeed's docker-container, is it possible to add a specific tag for each URL?

Example:

```
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.5.0 -b chrome https://www.sitespeed.io/ --tag "oganization1" https://example.org --tag "oganization2" ...
```

**Comment by soulgalore** [comment]
Hi @ahoiroman not at the moment. But if you run multiple tests (one per domain/organisation) you could do that with `--grafana.annotationTag`(if you use Grafana tags) or `--graphite.annotationTag` if you use Graphite.

Then it would be like:
`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.5.0 -b chrome https://www.sitespeed.io/ https://www.sitespeed.io/documentation/ --grafana.annotationTag "oganization1"`

`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.5.0 -b chrome https://www.aftonbladet.se/ https://www.aftonbladet.se/someURL --grafana.annotationTag "oganization2"`

Would that work for you?

**Comment by ahoiroman** [comment]
Thank you for your response.

This will work, although it's causing to start the container over and over again. But as there are not hundreds of websites (at the moment) it should be a valid workaround for now.

Thanks :-)
