### ISSUE TITLE
Is it possible to use JS6 features like import? 

### ISSUE THREAD

**Issue by olemal-wh** [sitespeedio/sitespeed.io#3270]
Hi! 

I want to write performance tests for our product, which is written using JS6 features. I want to re-use some of the staff from the project in the test. And while I can use "require" import in the tests I obviously cannot rewrite our whole UI project using "require". So the test throws me an error "SyntaxError: Cannot use import statement outside a module" for other files I imported into tests. Is it possible to somehow enable support for this or SitespeedIO uses native node features to not affect performance so it's not possible? 

Thanks for any answer. 

Regards.

**Comment by soulgalore** [comment]
No I don't think so, sorry!
