### ISSUE TITLE
Duplicated tags by default in Graphite annotations

### ISSUE THREAD

**Issue by SkynetKoks** [sitespeedio/sitespeed.io#3277]
**Steps to reproduce:**
1. Use docker-compose for sitespeed.io that you provided for localhost testing
2. Run command `docker run --shm-size=1g --rm -v "C:/Users/mykola.panasiuk/myDockerVolumes/sitespeed:/sitespeed.io" sitespeedio/sitespeed.io:16.8.0 -n 1 --graphite.host=host.docker.internal --resultBaseUrl http://localhost:8081 https://www.sitespeed.io/`
3. Check event that has been created in Graphite on `http://localhost:8080/events` -> check for duplicates by domain
4. Go to Grafana on localhost -> open console in chrome browser 
5. Hover over an annotation

**Actual result:**
The event in Graphite has duplicated tags (by domain) and that cause an issue in showing tags in the annotation in Grafana

**Expected result:**
No duplicates in tags and annotation is able to show tags 
![2021-02-11_10-50-45](https://user-images.githubusercontent.com/53987913/107616855-7ffa5980-6c57-11eb-97ae-f08f6621f798.png)

**Comment by soulgalore** [comment]
Hi @SkynetKoks thanks for adding the issue! Ah I see, this is in main but I haven't advertised the new feature yet, I was planning to do that for 17.0 that will be released soonish. The problem right now is that the domain and the slug/test name collide. You can overcome that by give the test a name, do that by use `--slug your-testname`. But the default behaviour where the same names collide isn't good, let me think if I can come up with a fix for that.

Thanks again for filing the issue, I hadn't noticed the problem.

**Comment by SkynetKoks** [comment]
Thanks for your quick answer and a workaround! Also thank you and your teammates for the amazing job you've done and continue to do. I have been playing with your solution for almost two weeks and I'm impressed

**Comment by soulgalore** [comment]
Thanks :) I'm rolling out 16.8.1 with a fix .. now. If you have time verify that it works for you that would be great.

**Comment by SkynetKoks** [comment]
I've just checked with 16.8.1-plus1 and it works perfectly, thank you)
