### ISSUE TITLE
How to properly setup tsproxy in K8?

### ISSUE THREAD

**Issue by deena9291** [sitespeedio/sitespeed.io#3278]
Hi @soulgalore @pmeenan

Thankyou for this amazing tool !!!

I am trying to run a sitespeed test with network throttling and using tsproxy to do so on a K8 cluster, I get different response time with different connectivity profiles (which is great !!);

Testing with this config "--browsertime.connectivity.engine tsproxy --rtt 10 --inkbps 25000 --outkbps 10000 -c **4g** --verbose" since the profile is "4g", it automatically overwrites my tsproxy preference in cmd line and it starts the tsproxy with the predefined config "--rtt 85 --inkbps 9000 --outkbps 9000 -p 1080"

log msg:
INFO: [browsertime.connectivity.tsproxy] Start TSProxy:/usr/src/app/node_modules/browsertime/vendor/tsproxy.py --rtt 85 --inkbps 9000 --outkbps 9000 -p 1080
DEBUG: [browsertime.connectivity.tsproxy] Started TSproxy

When I run the test with this config "--browsertime.connectivity.engine tsproxy --rtt 10 --inkbps 25000 --outkbps 10000 -c **native** -verbose" there is no output in the log file which states that it started the tsproxy with a specific network config (apart from the config json displayed before the run), but seems like the network is throttled based on the RT seen in the HTML report.

--browsertime.connectivity.engine tsproxy --rtt 10  --inkbps 25000 --outkbps 10000 -c native --verbose[RT - 4.8 secs]
--browsertime.connectivity.engine tsproxy --rtt 28  --inkbps 5000 --outkbps 1000 -c native --verbose [RT - 6.4 secs]

Can you please confirm if the connectivity profile is "native", it will automatically run the test with the specified tsproxy setting "--rtt 10  --inkbps 25000 --outkbps 1000"?

I doubt if the profile is native , it will not take tsproxy into consideration and the RT difference I see is because of the flaky tests, please clarify.

Thanks,
Deena.

**Comment by soulgalore** [comment]
Hi @deena9291 I think you need to set the connectivity profile to _custom_ for in/out to work. If you check `--help` you can see _This option requires --connectivity be set to "custom"._ but we should also have a warning.

Please let me know how it works out. I usually [don't recommend using TSProxy](https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#tsproxy) but it would be interesting to see how it works in k8.

Best
Peter

**Comment by deena9291** [comment]
Hi @soulgalore ,

Thanks for the info, I started using custom connectivity profiles along with tsproxy and getting proper results based on the respective network configuration;
![image](https://user-images.githubusercontent.com/62435018/107794805-e77eda80-6d25-11eb-9096-38d9c918d1d7.png)


Here we can see that the response time (page load time) differs for the same use case according to the settings :)

Learning: We should **not** use  tsproxy provided command line options in sitespeed like this one -  "tsproxy --rtt 10 --inkbps 25000 --outkbps 10000", we should always use connectivity profile to control the bandwidth even if you are using tsproxy in K8 like below;

option:
 --browsertime.connectivity.engine tsproxy  -c custom  --latency 10 --downstreamKbps 25000 --upstreamKbps 10000 --debug
logs:
[2021-02-12 14:35:34] INFO: [browsertime.connectivity.tsproxy] Start TSProxy:/usr/src/app/node_modules/browsertime/vendor/tsproxy.py --rtt 10 --inkbps 25000 --outkbps 10000 -p 1080
[2021-02-12 14:35:34] DEBUG: [browsertime.connectivity.tsproxy] Started Tsproxy

**Question/Improvement??:** Can we create a custom variable param (to save as a new profile) while we are setting this bandwidth and running from containers? Its very hard to figure out the bandwidth from grafana as all these change we make in custom profile (thru cmd line) will be stored as a single connectivity option "custom", it is impossible to segregate and analyze regressions when we run with different custom settings. I believe we cannot create/add profiles in the "trafficShapeParser.js" insid the container and we are downloading the image on the CICD pipeline.

Grafana Screenshot:
![image](https://user-images.githubusercontent.com/62435018/107795951-4c870000-6d27-11eb-98b2-fb5d392cb4d1.png)

Always appreciate your support !!

Thanks,
Deena.

**Comment by soulgalore** [comment]
Sorry, I missed this one. Yes you can set a name for your profile by setting an alias ` --connectivity.alias`
