### ISSUE TITLE
[help required] How to handle opening of new tab after clicking

### ISSUE THREAD

**Issue by vishallanke** [sitespeedio/sitespeed.io#3280]
Click on 'https://twitter.com/Wikipedia
Click on Wiki hyper link
It opens new tab

```
module.exports = async function(context, commands) {
  try {
	await commands.measure.start('Twitter Wikipedia');
	await commands.navigate('https://twitter.com/Wikipedia');
	await commands.measure.stop();
	await commands.measure.start('Home  Wikipedia');
	await commands.click.byXpathAndWait('//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div[1]/div/div[2]/div/div/div[1]/div/div[4]/div/a');
	return commands.measure.stop();
	 } catch (e)  {
	  throw e;
  }
};
```

ERROR
[2021-02-14 18:48:52] ERROR: Caught error from Browsertime Error: PageIndex out of range

**Comment by soulgalore** [comment]
Hi @vishallanke I don't think there's a workaround to fix this, right now everything is focused on one tab.

**Comment by Icecold777** [comment]
@vishallanke, I pretty sure that it's possible to use selenium in this case

Something like this code should work
```
const driver = context.selenium.driver;
let tabs = await driver.getAllWindowHandles();
driver.switchTo().window(tabs[1])
```

**Comment by soulgalore** [comment]
Right now we do not support measuring in other tabs. The Mozilla team maybe will implement it see https://github.com/sitespeedio/browsertime/issues/958
