### ISSUE TITLE
Budget-File not found when ran in Gitlab CI

### ISSUE THREAD

**Issue by benboit** [sitespeedio/sitespeed.io#3285]
Hello,

im trying to use the browser performance-testing according to https://docs.gitlab.com/ee/user/project/merge_requests/browser_performance_testing.html

Gitlab CI is using this configuration to run a docker-based sitespeed.io instance: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Verify/Browser-Performance.gitlab-ci.yml

When changing the SITESPEED_OPTIONS to **--budget.configPath /sitespeed.io/budget.json -b chrome -n 3** that file is not found

`ENOENT: no such file or directory, open '/sitespeed.io/budget.json'`

My budget.json is in the current folder and when doing the exact same locally the budget test is running. I also tried to check in the pipeline, if the budget.json is really in place and it is.

I also tried using just budget.json as the configPath, but this also doesnt work.

I thought that might be a problem with DIND, but inside the host docker-container the file is also available. Also using the gitlab env var for the current project directory instead of the PWD aint working.

I dont know if this is a sitespeed specific problem or something with gitlab. Is there a proposed way to run sitespeed.io inside of a gitlab pipeline? I also tried running sitespeed image directly (no DIND), but then passing configuration doesnt work as expected.

From what i can read from the Dockerfiles /sitespeed.io should be the right target volume, isnt it?

**Comment by soulgalore** [comment]
Hi @benboit I haven't used GitLab but lets see if I can help. 

You are right, inside the container /sitespeed.io is used so mapping that directory is the right way to go (and have your budget file their) so if you run the Docker container standalone you should be able to follow the old docs for GitLab: https://docs.gitlab.com/ee/user/project/merge_requests/browser_performance_testing.html#gitlab-versions-123-and-older.  The essential is the mapping of the current directory and /sitespeed.io `-v "$(pwd)":/sitespeed.io`. /sitespeed.io is the working dir inside the container so then you can use  `--budget.configPath budget.json ` directly

Can you see in the GitLab documentation what directory is mapped (I can't find it).? If you cannot find it I think you should ask GitLab and when you know I can help out!

Best
Peter

**Comment by benboit** [comment]
Hello, thanks for your comment, this ist related to volumes in docker-in-docker context in gitlab. So not your fault.

For everyone interested: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227

You need to configure your runner.toml, to mount the build directory (see: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_292893514)
