### ISSUE TITLE
Screenshots are missing in HTML report

### ISSUE THREAD

**Issue by SkynetKoks** [sitespeedio/sitespeed.io#3286]
**Steps to reproduce:**
1. Run test with: `docker run --shm-size=1g --rm -v "C:/Users/mykola.panasiuk/myDockerVolumes/sitespeed:/sitespeed.io" sitespeedio/sitespeed.io:16.8.1-plus1 --plugins.remove /gpsi --plugins.remove /lighthouse -n 1 --html.showScript myscript.js --multi`
2. Once it's finished go to HMTL report -> then to Screenshots tab 

**Actual result:**
Screenshots are missing in HTML report. They are present in the directory
No errors in logs

**Expected result:**
Screenshots are shown in HTML report

It should be somewhere here - https://github.com/sitespeedio/sitespeed.io/blob/70656055f176df8fdfe22cf5a92a904dbd6dd0d5/lib/plugins/html/templates/url/screenshots/index.pug
Please fix this issue once you have time as it's quite noisy while debugging scripts. Thank you in advance. 
![2021-02-23_18-28-06](https://user-images.githubusercontent.com/53987913/108878400-e6dd2280-7608-11eb-92c7-02fd2728faa9.png)

**Comment by soulgalore** [comment]
Hi @SkynetKoks thanks for the bug report. I fixed it in a PR and it will go out in the next release.

**Comment by SkynetKoks** [comment]
Thank you! Works for me now in sitespeedio/sitespeed.io:16.9.0-plus1
