### ISSUE TITLE
Partially rebuilded image for Mac M1 (firefox only)

### ISSUE THREAD

**Issue by whichfinder** [sitespeedio/sitespeed.io#3291]
Hello guys,

I've tried to build docker image for sitespeed.io for Mac m1 (arm64).

Steps that were performed:
1. build new ubuntu node image (like [this](https://hub.docker.com/layers/sitespeedio/node/ubuntu-20.04-nodejs-14.15.0/images/sha256-492e41e03493a91ae3b57a5298d40e499b91cd505300a0a81a0638f5037e9b1d?context=explore))
but, unfortunately, this didn't work. So I build it from scratch with replacing all amd64 packages with arm64 analogs.
2. Based on step 1 I build another image (like [this](https://hub.docker.com/layers/sitespeedio/visualmetrics-deps/ffmpeg-4.2.2-imagemagick-6.9.10-23-p2-b/images/sha256-82da3105b5b9c2579dd2403bdf7c161ece4d0991d07aa6ceaab28b05bf2c22bc?context=explore)) with replacing 
` python3 -m pip install pyssim Pillow image && \`
3. Based on step 2 I build another image (like [this](https://hub.docker.com/layers/sitespeedio/webbrowsers/chrome-88.0-firefox-84.0-edge-89.0-dev/images/sha256-e8d4a9620a28adedf2f8ba9636dfb1f2f8c60791bef5b213c23eca16dc632096?context=explore)). Majority of code was removed and commented (Chrome is not available as arm64 package, but possibly it could be replaced with chromium), and installation of firefox arm64 was added.
4. Based on step 3 I build last image (like [this](https://hub.docker.com/layers/sitespeedio/sitespeed.io/16.9.2/images/sha256-d0db18095e98cd5612187ce364abc520a4da4cb70f328158347783c48d65e93e?context=explore))

As a result I have at least working image that could produce at least some report (you can found it [here](https://hub.docker.com/layers/docdsd/ssio/partially-working-image-mac-m1-firefox/images/sha256-8e6b963dbfc2857252e6268b5f3fed4fc7a0f3295cda0e1ef9d91521b8b1e88e?context=repo))

Here is a [Dockerfile](https://pastebin.com/Hz3hPkJ3)

But I run into a problem that I have exceptions during the test (and part of the report is missing). Video is being generated.

Command to run:
`
docker run -v "$(pwd)":/sitespeed.io docdsd/ssio:partially-working-image-mac-m1-firefox test.js --multi --config config --spa -b firefox
`

Here is a log:
```
[2021-02-24 17:01:10] ERROR: VisualMetrics failed to run Error: Command failed with ENOENT: python /usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py --dir /sitespeed.io/sitespeed-result/test_js/2021-02-24-17-00-51/pages/site_com/action/data/filmstrip/1 --video /sitespeed.io/sitespeed-result/test_js/2021-02-24-17-00-51/pages/site_com/action/data/video/1.mp4 --orange --force --renderignore 5 --json --viewport -q 75 --logfile /sitespeed.io/sitespeed-result/test_js/2021-02-24-17-00-51/pages/site_com/action/data/video/1.visualmetrics.log -vvv
spawn python ENOENT
spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2021-02-24 17:01:10] ERROR: Could not run Visual Metrics Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/test_js/2021-02-24-17-00-51/pages/site_com/action/data/video/1.visualmetrics.log''
[2021-02-24 17:01:10] ERROR: Visual Metrics failed to analyse the video Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/test_js/2021-02-24-17-00-51/pages/site_com/action/data/video/1.visualmetrics.log''
```
And some weird exception:
```
[2021-02-24 17:01:10] ERROR: TypeError: Cannot read property 'push' of undefined
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:255:31)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:258:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:117:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
```

Example of report (as you can see some columns are shifted and some data is missing from first 3 columns)
![image](https://user-images.githubusercontent.com/8527453/109045594-74d60d80-76dc-11eb-9279-bb539ab462ac.png)

Any ideas on this exception?

PS: Huge thank for @binary-zero-one

**Comment by soulgalore** [comment]
Hi @whichfinder thanks for creating the issue. I've briefly created ARM-builds (see https://github.com/sitespeedio/docker-browsers/issues/2) but never got around to get it to work. Best case I wanna find a way to use the same Docker files for both builds but not sure if its possible. Looks like you got further than me, great!

I think the error means that python is not found, checkout the Visual Metrics script: https://github.com/sitespeedio/browsertime/blob/main/browsertime/visualmetrics.py#L1

My guess is that it can be solved with adding python-is-python3 to your install, can you try that? 

In the original container we still use Python 2, the reason is that Kubernetes users may want use TSProxy for network throttling and it only works with 2 at the moment https://github.com/WPO-Foundation/tsproxy/issues/23. But I guess its better to fix that with a special build for Kubernetes users.

Let me know how it works out, would love to get this to work (and add Chromium too).

**Comment by soulgalore** [comment]
Had a quick try and I guess the best way is to add a arg `--build-arg PLATFORM=arm64` or do you see a better way of doing it @whichfinder ?

**Comment by whichfinder** [comment]
Hello @soulgalore 
I will check python today, thank you for hint.
PS: +1 to `--build-arg PLATFORM=arm64`

**Comment by soulgalore** [comment]
I did quick test and visual metrics works, but got another problem, it seems like the [HAR export trigger](https://github.com/firefox-devtools/har-export-trigger) do not work:

```
[2021-02-25 08:39:18] INFO: https://www.sitespeed.io/ TTFB: 415ms DOMContentLoaded: 757ms firstPaint: 749ms FCP: 748ms Load: 882ms 
[2021-02-25 08:39:18] INFO: VisualMetrics: FirstVisualChange: 768ms SpeedIndex: 780ms VisualComplete85: 801ms LastVisualChange: 868ms
[2021-02-25 08:39:21] INFO: Testing url https://www.sitespeed.io/ iteration 2
[2021-02-25 08:39:30] INFO: Waiting on har-export-trigger to collect the HAR
[2021-02-25 08:39:30] ERROR: Got an error from HAR Export Trigger {}
[2021-02-25 08:39:30] ERROR: TypeError: Cannot read property 'log' of undefined
    at Firefox.afterPageCompleteCheck (/usr/src/app/node_modules/browsertime/lib/firefox/webdriver/firefox.js:114:15)
```

That empty object as and error doesn't help so much :)

**Comment by soulgalore** [comment]
@whichfinder FYI I tried some more with buildx and got the repo https://github.com/sitespeedio/docker-node built for different platforms, checkout https://github.com/sitespeedio/docker-node/blob/main/Dockerfile#L3 and the build instructions in the README. I'll try to fix a couple of the other containers to follow the same pattern tonight or the coming weekend.

**Comment by soulgalore** [comment]
I made branch for the container with the browsers: https://github.com/sitespeedio/docker-browsers/blob/multi-platform-support/Dockerfile

One thing that we need to look into is matching Chromedriver/Chrome version for arm.

**Comment by soulgalore** [comment]
@whichfinder @alextiley1 I pushed a version sitespeedio/webbrowsers:chrome-88.0-firefox-84.0-edge-89.0-dev-multi (from the branch https://github.com/sitespeedio/docker-browsers/tree/multi-platform-support) and then Firefox works and I need help with Chromium (the current install do not work).

To try it, change the Dockerfile to depend on sitespeedio/webbrowsers:chrome-88.0-firefox-84.0-edge-89.0-dev-multi  and rebuild (and fix the start.sh script).

I'll be offline next week ( I'll can answer question but probably no coding.), if you have time to try it out it would be great.

**Comment by whichfinder** [comment]
ff works perfectly, thank you @soulgalore 
I am trying to build using chromium and current idea is to make link chromium -> chrome so we don't need to change start.sh, what do you think? 
AFAIK chrome and chromium commands are the same..

**Comment by soulgalore** [comment]
Yes sounds good. When I tried I sometimes get that HAR error from Firefox but not all the time. Do you get that error too?

**Comment by whichfinder** [comment]
no error at all on my end

**Comment by whichfinder** [comment]
Hi, @soulgalore 
I've tried several ways of installing chromium on ubuntu arm image. One worked for me and I successfully installed chromium:
`apt-get install -y software-properties-common && \`
`apt-get install libgcc1 gcc-8-base && \`
`apt-key adv --fetch-keys "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xea6e302dc78cc4b087cfc3570ebea9b02842f111" && echo 'deb http://ppa.launchpad.net/chromium-team/beta/ubuntu bionic main ' >> /etc/apt/sources.list.d/chromium-team-beta.list && apt update && \`
`apt-get install -y chromium-browser chromium-chromedriver && \`
`apt-get install -y snap snapd && \`
`ln -s /usr/bin/chromium-browser /usr/bin/google-chrome && \`
`ls -la /usr/bin && \`
`chmod 777 /usr/bin/google-chrome`

Taken from [here](https://ahelpme.com/linux/ubuntu/chromium-browser-in-ubuntu-20-04-lts-without-snap-to-use-in-docker-container/)

After that I've added link to chromedriver to sitespeedio module as it was not created during install:
`RUN mkdir -p /usr/src/app/node_modules/@sitespeed.io/chromedriver/vendor/`
`RUN ln -s /usr/bin/chromedriver /usr/src/app/node_modules/@sitespeed.io/chromedriver/vendor/chromedriver`

I tried to start chrome in container but received error:
```
Command '/usr/bin/google-chrome' requires the chromium snap to be installed.
Please install it with:

snap install chromium
```
According to [this](https://snapcraft.io/blog/chromium-in-ubuntu-deb-to-snap-transition) seems it's impossible to run chromium without snap, and snap doesn't work in docker.

Any thought on this? As for me - ff is the only option for now

**Comment by soulgalore** [comment]
Hi @whichfinder aha thanks for looking into it. Let me add then so at least we release the Firefox version next time + logs errors for Chrome until there's a way to fix it.

**Comment by soulgalore** [comment]
So I've prepared everything except Browsertime/sitespeed.io containers, let me have another go and at least fix Firefox.

**Comment by soulgalore** [comment]
I've prepared every step but is still missing a way for installing Chromeium.

**Comment by radum** [comment]
Ins't `apt install chromium-browser` pulling the right version for ARM?

**Comment by soulgalore** [comment]
Yep want chromium but get the same as https://github.com/sitespeedio/sitespeed.io/issues/3291#issuecomment-789751656 that `requires the chromium snap to be installed.`

**Comment by radum** [comment]
ppa:saiarcot895 Doesn't need snap and its quite popular. I don't know any other official ppa that has it.

https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev
https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta

And its kept up to date.

**Comment by soulgalore** [comment]
Ah thank you @radum !
