### ISSUE TITLE
Getting error " TypeError: Cannot read property 'addDeep' of undefined" 

### ISSUE THREAD

**Issue by rockstar690** [sitespeedio/sitespeed.io#3292]
Hi Team,

We are creating scripts for single page application on latest version of sitespeed 16.8 and getting "addDeep" issue frequently.  

![image](https://user-images.githubusercontent.com/79684446/109262447-9263be00-7827-11eb-80d3-d51d086c5439.png)

After completing of all the transactions, this error "addDeep" is generating at last.
Due to security reason, I can't share URL and login creds.

version used for script creation:
Versions OS: win32 10.0.19041 
nodejs: v14.15.0 
sitespeed.io: 16.8.0 
browsertime: 11.4.0 coach: 6.0.1

**Comment by soulgalore** [comment]
Hi @rockstar690 it's [super hard to reproduce without any more info](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue). Do you get it frequently or all the time? My guess is that the page/transaction isn't generating a request for each step. I can try to add some better error checks/usefuful error messages in the next release.

**Comment by rockstar690** [comment]
Hi @soulgalore ,

Can you pls share your personal email id so that I can share my script for debugging the issue.

Thanks in advance.

**Comment by rockstar690** [comment]
Hi @soulgalore,

Still I am waiting for your response, pls ack

**Comment by rockstar690** [comment]
hi @soulgalore 

can you please respond to our query.

thanks

**Comment by soulgalore** [comment]
Hi @rockstar690 I've been offline for a couple of days. You can reach me at: peter [AT] souldgalore |DOT] com.

**Comment by rockstar690** [comment]
Hi @soulgalore ,

Thanks for your response. I am trying to send you mail at "peter@souldgalore.com" but it is not working.

**Comment by soulgalore** [comment]
Ooops, sorry the email adress was not correct, sorry: peter [AT] soulgalore |DOT] com.

**Comment by rockstar690** [comment]
Hi @soulgalore,

Thanks for your reply. 

Currently, the project is on hold and we have lost all access. So we can't proceed further.

Will intimate you, if we face this issue again in the future.
