### ISSUE TITLE
InfluxDB seriesname data set as last metric field

### ISSUE THREAD

**Issue by pintiyas** [sitespeedio/sitespeed.io#3295]
Hi all!

Using sitespeed.io:16.9.2-plus1 I get metric using config.json from GPSI such as:

```
"gpsi.pageSummary.data.lighthouseResult.audits.total-blocking-time.numericValue",
"gpsi.pageSummary.data.lighthouseResult.audits.total-blocking-time.score",
"gpsi.pageSummary.data.lighthouseResult.audits.total-byte-weight.numericValue",
"gpsi.pageSummary.data.lighthouseResult.audits.total-byte-weight.score",
```

When I see log by -v option it sends metrics to Influx and send something as follows, so there's no way to know which metric is send:

```
{
    "tags": {
      "origin": "gpsi",
      "summaryType": "pageSummary",
      "strategy": "desktop",
      "page": "---",
      "group": "---"
    },
    "seriesName": "numericValue",
    "point": {
      "time": 1614770826991,
      "value": 1050317
    }
  },
  {
    "tags": {
      "origin": "gpsi",
      "summaryType": "pageSummary",
      "strategy": "desktop",
      "page": "---",
      "group": "---
    },
    "seriesName": "score",
    "point": {
      "time": 1614770826991,
      "value": 1
    }
```

Is there any way for matching which data is send and metric belongs to?

Thanks!

**Comment by SkynetKoks** [comment]
Hi, u can use -vvv (more detailed debug output, but even it will not show you all metrics to send, at least I see only browsertime metrics to send to Graphite)

**Comment by soulgalore** [comment]
Hi @PIntiyas I think the conversion of the Lighthouse data to InfluxDB (and Graphite) is very limited today. The "magic" converting the data happens in https://github.com/sitespeedio/sitespeed.io/blob/main/lib/plugins/influxdb/data-generator.js#L197-L205 - if you could add a PR that take the metric name and add it as a tag I think that should work.

**Comment by PIntiyas** [comment]
Hi @soulgalore !

I made the "magic" but with a hotfix in this file. I put key value instead of splitted last part when end of metric is not contained in conts list. It's working fine for me, but I think that it's no a real good job with setting parameters and those kind of things.
I will try to do something more elegant and pull it.

Thanks!

**Comment by soulgalore** [comment]
Cool, yeah so if I remember correctly the JSON result from Lighthouse is kind of bloated and we probably wanna avoid having direct conversions, more generic one that handles most of the cases so we don't need to change it so often. Haven't had a try though since I'm no Lighthouse user :)

**Comment by soulgalore** [comment]
I think it's better to spend time on doing a generic metric/tag converter that can be used in both Prometheus and InfluxDB instead of fixing this in Influx.
