### ISSUE TITLE
Unable to see metrics in graphana dashboard , could see those in graphite 

### ISSUE THREAD

**Issue by Binayjojo** [sitespeedio/sitespeed.io#3303]
Have a separate server for graphana and graphite.

https://raw.githubusercontent.com/sitespeedio/sitespeed.io/main/docker/docker-compose.yml used this  
Base OS Amazon linux

While i can see  metrics in graphite, not seen in graphana.
![graphite_data](https://user-images.githubusercontent.com/48512071/110257151-806de200-7fc2-11eb-96f9-c8c8ecd0a71e.png)
![graphana](https://user-images.githubusercontent.com/48512071/110257178-8bc10d80-7fc2-11eb-98c0-e346a71e769e.png)

**Comment by Binayjojo** [comment]
Is this something to do with the variables defined for dashboard , as i see the same issue  in https://dashboard.sitespeed.io/d/000000043/page-summary?orgId=1 .

**Comment by soulgalore** [comment]
Hi @Binayjojo what dashboards did you use from the beginning? Did you download them from dashboard.sitesped.io or? And what config do you use?

So we are in the middle of releasing the next major version, where the dashboard will need to have the slug (see https://dashboard.sitespeed.io/d/000000064/page-metrics-mobile?orgId=1&var-base=sitespeed_io&var-path=emulatedMobileFirstView&var-testname=alexa&var-group=en_m_wikipedia_org&var-page=_wiki_Barack_Obama&var-browser=chrome&var-connectivity=3g&var-function=median&var-resulturl=https:%2F%2Fs3.amazonaws.com%2Fresults.sitespeed.io&var-screenshottype=jpg=). The docs for that coming latest next week.

**Comment by Binayjojo** [comment]
Hi @soulgalore  , Thanks for the reply ,

I am using Default sitespeed.io dashboards for Graphite . Got the answer. Will wait for the next version.
