### ISSUE TITLE
Unable to connect android device

### ISSUE THREAD

**Issue by parag85** [sitespeedio/sitespeed.io#3304]
Hello Team,

Unable to connect my android device.

Ubuntu - 18.04.5 LTS
sitespeed.io: 16.9.2 
browsertime: 11.5.0

Command to run: 

docker run --privileged -v /dev/bus/usb:/dev/bus/usb -e START_ADB_SERVER=true --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.9.2  -n 1 --android --browsertime.xvfb false https://www.sitespeed.io

Error:

ERROR: Caught error from Browsertime Error: No Android phone was found
    at Android._init (/usr/src/app/node_modules/browsertime/lib/android/index.js:45:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Engine.start (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:81:7)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:115:7)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
![Screenshot from 2021-03-08 18-27-17](https://user-images.githubusercontent.com/8840359/110324443-f6faf600-803b-11eb-8242-4346beca7658.png)

**Comment by soulgalore** [comment]
Hi @parag85 thanks for creating the issue. If you run ADB without Docker, is the device listed then? Thinking there's something going with the mapping of the USB port. I don't have access to Linux at the moment but if you cannot get it to work I can see if I can have a go the coming week or so.

**Comment by parag85** [comment]
Hi @soulgalore , Yes device is listing without running docker. I am able to install apk and other commands via adb command.

**Comment by soulgalore** [comment]
Hi @parag85 I think I may know what's happened. Some time ago I've updated to https://www.npmjs.com/package/@devicefarmer/adbkit and I wonder if this new:

> For Linux users, adb need plugdev group acess, So you may need to add your current user to plugdev group. sudo usermod -a -G plugdev $USER

I know I haven't done that in the Docker container, I wonder if that could be the problem?  There's a hack you could try to help me test. You can run a extra shell script before sitespeed.io starts:
https://www.sitespeed.io/documentation/sitespeed.io/docker/#extra-start-script

Could you try to run a script that add the user to the plugdev group?

**Comment by soulgalore** [comment]
No that shouldn't be it. Let me install Linux, I can do that early next week, I'll ping the issue ASAP when I tried it out.

**Comment by soulgalore** [comment]
@parag85 Let me update the docs: You can only have the phone attached to one adb server at a time, so you need to make sure adb is not running on your host machine (`adb kill-server`).

**Comment by parag85** [comment]
New changes worked, thanks @soulgalore
