### ISSUE TITLE
Graphite Metrics - ERROR: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by LuisBatistaEscobedo** [sitespeedio/sitespeed.io#3310]
I'm currently using Docker on Windows to make some tests with Sitespeed, Grafana and Graphite. I used the docker-compse.yml file attached for the configuration on the containers and everything seem to be working well; I modify the storage-schemas.conf and the storage-aggregation.conf files. I successfully ran the test using the lates Sitespeed distribution(16.10.0), but it seems that once I try to upload the data to graphite I got a timeout on the graphite host.

This are the configurations from my hosts and my containers:

![02](https://user-images.githubusercontent.com/32347105/111025766-23e03d80-839b-11eb-9a85-bdb35faa81cd.jpg)

And this is the error I'm getting:

![01](https://user-images.githubusercontent.com/32347105/111025778-39edfe00-839b-11eb-9864-876260b7db0d.jpg)

[yml.txt](https://github.com/sitespeedio/sitespeed.io/files/6136026/yml.txt)

**Comment by soulgalore** [comment]
Hi @LuisBatistaEscobedo I think that IP is not reachable from within the container. I've not used Graphite with Windows, but I think could get help at the Docker web site.

**Comment by soulgalore** [comment]
I usually test with curl just to see that the other server that runs Graphite is reachable by that IP etc, can you test that @LuisBatistaEscobedo

**Comment by LuisBatistaEscobedo** [comment]
After revisiting the documentation, I saw the section of "Up and running in (almost) 5 minutes" and check the step three, where it specifies to set de graphite host to "graphite.host=host.docker.internal" when you are using a localhost.

That finally worked and now I'm seeing my data on Grafana, thanks for the help.

https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes
