### ISSUE TITLE
Best plugin for CrUX data and Lighthouse scores

### ISSUE THREAD

**Issue by mploquin** [sitespeedio/sitespeed.io#3312]
Hi @soulgalore ,

What is the best way to get the crux data : with the crux plugin or the gpsi plugin? What is the differences between this two plugins ? Is there one more precise or more suitable in a particular situation ?

Same for lighthouse scores, what is the best use : the gpsi plugin or the standalone lighouse plugin ?

Thank you for your answers and your work !

**Comment by soulgalore** [comment]
Hi @mploquin for crux it seems to be better to use the CrUX API see https://groups.google.com/a/chromium.org/g/chrome-ux-report/c/TTL4HR8pCcE 

For Lighthouse: If you use the Lighthouse plugin you can update Lighthouse versions if you want, GSPI you want to wait until they do. But on the other side: gpsi runs Lighthouse on someone else computer, the Lighthouse plugin on your own so it depends.
