### ISSUE TITLE
Cookie parameter doesn't work anymore

### ISSUE THREAD

**Issue by Ludovic33Fr** [sitespeedio/sitespeed.io#3314]
Hello, 

It seems there is a regression on the cookie parameter. 

**how to reproduce your issue** 

1. I have upgraded sitespeed to latest v 16.10.0
2. I switch on fiddler to catch the request
3. I run a test with the following command : node  bin/sitespeed.js https://www.sitespeed.io/ -n 1 --cpu --cookie TEST_PRIVACY=123456 -vvv
4. I  am looking for cookie into HTTP Header : TEST_PRIVACY into fiddler and it fails whereas i can see the cookie parameter into log sitespeedio : 

![2021-03-16_17h41_22](https://user-images.githubusercontent.com/39523675/111346838-e6bbca00-867e-11eb-8d41-2cd0ceede6d8.png)

Please find in attchment the Fiddler session exported
[Sitespeedio-cookie.zip](https://github.com/sitespeedio/sitespeed.io/files/6150597/Sitespeedio-cookie.zip)

This parameter --cookie is required to monitor the third party and simulate the consent cookie (GRPD issue)

**Comment by Ludovic33Fr** [comment]
![image](https://user-images.githubusercontent.com/39523675/111347027-19fe5900-867f-11eb-8b46-91b5b669130b.png)

**Comment by soulgalore** [comment]
Hi @Ludovic33Fr I usually [use httpbin to verify](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue). They have different URL that just echo back the values. https://httpbin.org/cookies will print all cookies on the screen:

` bin/sitespeed.js https://httpbin.org/cookies  -n 1 --cpu --cookie TEST_PRIVACY=123456`
<img width="358" alt="Screenshot 2021-03-16 at 18 55 27" src="https://user-images.githubusercontent.com/540757/111357114-4ae38b80-8689-11eb-9334-90d127062b38.png">

Can you try if it works for you?

**Comment by Ludovic33Fr** [comment]
Hi @soulgalore ,

Thank you for your response. I try with httpbin and i think that the issue coming from the execution context.

In deed with your command : **node  bin/sitespeed.js https://httpbin.org/cookies -n 1 --cpu --cookie TEST-PRIVACY=123456**

- It works if i call it from Terminal powershell of visual studio code
- However : it fails and i reproduce everytime, if i call the command line into a windows prompt
![image](https://user-images.githubusercontent.com/39523675/111384214-89893e00-86a9-11eb-9c66-a40b3f468761.png)

Maybe it is coming from node version : for me v.14.15.4

**Comment by Ludovic33Fr** [comment]
To add more informations on this issue : 

- We reproduce the same issue by calling httpbin in linux command line context
- We change the version of sitespeed io recently from 13.2.0 to 16.8.0. With this old version it works

**Comment by soulgalore** [comment]
Ok, can you help me how to reproduce it on Linux? Is it that example you showed or another that do not work?

When I tried the dockerized version it also works for me: `docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://httpbin.org/cookies -n 1 --cpu --cookie TEST-PRIVACY=123456 -n 1`

Setting a cookie for Chrome uses the CDP protocol. this is the magic: https://github.com/sitespeedio/browsertime/blob/main/lib/chrome/chromeDevtoolsProtocol.js#L131-L141

**Comment by mploquin** [comment]
Hi, 

This works for me on Linux, but I also ran into some issues with cookies, especially when I am using `requestheader` option. 
For example, httpbin shows cookies but they are not really in the broswer : 
<img src="https://user-images.githubusercontent.com/19324133/111960333-e6448880-8aef-11eb-9aac-8f6d5213bdc1.png" width="480">

Overall I have encountered several issues with special characters especially (`=` and `:`) 
Ex: `TEST_COOKIE=a=b` OR `TEST_COOKIE=2020-10-12T08:24:23` 

Moreover we cannot define a custom domain nor a path with the cookie option. So the solution for me was to use scripts and the Chrome DevTools Protocol.

**Comment by soulgalore** [comment]
Hi @mploquin yep its a limit today that you cannot set domain/path. If you have time I PR I can rewove it. In CDP it would be pretty straightforward, but for Firefox we still use https://github.com/sitespeedio/browsertime-extension to set cookies, that is little bit harder to test.

**Comment by Ludovic33Fr** [comment]
Thank you @soulgalore  for your advice. It helps me to troubleshoot.

Best,
