### ISSUE TITLE
<Query >How does Budget pass/fail works in case of  Iteration run= 3.

### ISSUE THREAD

**Issue by TusAuto** [sitespeedio/sitespeed.io#3318]
We are executing each url for iteration count=3. Also we have Page load Time as budget configured metrics.  I want to know how page load time will be taken for 3 iteration ? Is it average time that calculated for 3 iterations or how does it calculate final page load time or other Coach metrics. ??

**Comment by soulgalore** [comment]
Hi @TusAuto it should be the median.
