### ISSUE TITLE
<Query> Does "await commands.wait.byTime(25000)" included in the Page load time if used in-between  measure.start() and measure.stop()

### ISSUE THREAD

**Issue by TusAuto** [sitespeedio/sitespeed.io#3319]
Our Application is taking more time for loading , hence we have added await commands.wait.byTime(25000) in between measure.start() and measure.stop(). So does it add 25sec in page load Time matrix ?

We have used different page load strategies  like --browsertime.pageCompleteCheckInactivity ,--pageCompleteWaitTime but we finalized to use  await commands.wait.byTime(25000) as our application is to slow. 

Hence please guide if it add additional time in Page Load time / Total Blocking Time ?

Code we used :

await commands.wait.byXpath(ASM_SIGN_IN_LOCATOR,20000)
	await commands.click.byXpathAndWait(ASM_SIGN_IN_LOCATOR); 	 
	await commands.wait.byId(EMAIL_LOCATOR,15000)
	await commands.addText.byId(process.env.EMAIL, EMAIL_LOCATOR);  					 
	await commands.addText.byXpath(process.env.PASSWORD , PASSWORD_LOCATOR);  
	await commands.measure.start();
	await commands.click.byXpathAndWait(SUBMIT_LOCATOR);
	//await commands.wait.byTime(15000);
	context.log.info('Overview page opened..');					
	**await commands.wait.byTime(25000);**
	await commands.measure.stop();
	await commands.cache.clear();
	 } catch (e)  {
	  throw e;
  }

**Comment by soulgalore** [comment]
Hi @TusAuto the extra wait time will just wait, so after the extra wait time is finished all metrics are collected. If more JavaScript run under that time than it normally would and it will be long tasks you can see that in total blocking. But the actual wait will not add anything extra to any metric. That only happens if the page do something during that time.

**Comment by TusAuto** [comment]
Thank you @soulgalore :)  But if we remove that extra time , We can see in html report -->Page tab screenshot  , our page is not loaded and readings are captured for incomplete page.  Do we any other option that we can add instead of hard wait time ??. Because it will slow down our execution for all scripts.  I tried  --browsertime.pageCompleteCheckInactivity ,--pageCompleteWaitTime but not useful in our context.

**Comment by soulgalore** [comment]
Hi @TusAuto when is your page finished loading? :) You can define your own page load complete check https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test `--browsertime.pageCompleteCheck`.

**Comment by TusAuto** [comment]
Hi @soulgalore , Problem with pageCompleteCheck is it wait on all the pages ( for 10 sec if mentioned) like after login page then specific tab navigation. Its causing unnecessary slow execution.  I need to use  pageCompleteCheck  only for specific page or navigation.

**Comment by soulgalore** [comment]
Yes but you can use click on links etc without the wait? https://www.sitespeed.io/documentation/sitespeed.io/scripting/#click
