### ISSUE TITLE
Grafana Annotation timestamp is set to test start time

### ISSUE THREAD

**Issue by eQza** [sitespeedio/sitespeed.io#3320]
Annotation is logged at the beginning instead of at the time the page is loaded. The gap between the metrics and the annotation in the dashboard can be confusing to readers.
![image](https://user-images.githubusercontent.com/21050380/112316643-344dbd80-8ca3-11eb-8548-2205b5f5ab86.png)

Annotation
![image](https://user-images.githubusercontent.com/21050380/112315997-9823b680-8ca2-11eb-929f-a0b5c34fdb62.png)

Request Sent
![image](https://user-images.githubusercontent.com/21050380/112316127-b984a280-8ca2-11eb-99f0-bceceb697c66.png)

Tested using:
sitespeedio/sitespeed.io:16.10.3 &
sitespeedio/sitespeed.io

Grafana v7.3.7
Influx 1.8

**Comment by soulgalore** [comment]
This has been changed in Graphite and I think it also was changed in Influx. Please let me know if that was not the case.
