### ISSUE TITLE
Not able to see the videos when using NodeJS

### ISSUE THREAD

**Issue by LuisOsv** [sitespeedio/sitespeed.io#3336]
I cannot see the video, when running on NodeJS+Windows with the following command:
`node sitespeed.js https://en.wikipedia.org/wiki/Barack_Obama -b firefox --video --visualMetrics -n 1`
![image](https://user-images.githubusercontent.com/1733890/113984370-04f98d80-9819-11eb-8881-72edae740b8f.png)

**Comment by soulgalore** [comment]
Hi @LuisOsv thanks for filing the issue. Do the file exist and do you get any errors in the log?

**Comment by LuisOsv** [comment]
Hi @soulgalore, nope the video does not exist, and the logs folder is empty

**Comment by soulgalore** [comment]
It doesn't log to file by default (to make sure you don't accidentally leak information if you run on a server etc). It should output the log when you run the command, can you check? Almost always you get a error log message if something is wrong.

**Comment by soulgalore** [comment]
The good news is that the video works since you get first visual change and speed index :) I wonder if the link somehow is wrong on Windows? Could you please check if the /data/video/ directory is empty?

**Comment by LuisOsv** [comment]
Yes the folder is empty. How can I check if the link is wrong?

**Comment by LuisOsv** [comment]
[2021-04-08-09-57-57.zip](https://github.com/sitespeedio/sitespeed.io/files/6288873/2021-04-08-09-57-57.zip)
I'm adding the report

**Comment by soulgalore** [comment]
Hi @LuisOsv thanks for adding that. Hmm really strange. You are right there's nothing there, but you got the actual metrics. You can remove the video by setting `--video false `. Let me see if I can get Windows to work on Parallels and see if I get the same.

**Comment by soulgalore** [comment]
Hmm this works on our Windows GitHub Action and for Mozillas Windows tests. Closing but please let me know if this is still an issue.
