### ISSUE TITLE
Filmstrip for desktop (all browser) not perfect.

### ISSUE THREAD

**Issue by svkrclg** [sitespeedio/sitespeed.io#3337]
Hello Team,
We tried running a few sitespeed processes with visual metrics on desktop OSX, but there are the following issues regarding filmstrip, 
- Orange screen being shown in filmstrips.
- TimeStamps are considering from the beginning (i.e from orange screen load)
- Overall the event and filmstrip are not matching.

Sitespeed version used: 16.3.2
node version: 12.19
browser: Chrome 88.0, 89.0
OS: OS X Mojave
Some sample are attached for reference. 
![Screenshot 2021-04-08 at 5 20 28 PM](https://user-images.githubusercontent.com/30564616/114143923-5ea1ab00-9932-11eb-9a44-e4c936db18d5.png)
![Screenshot 2021-04-08 at 2 14 16 PM](https://user-images.githubusercontent.com/30564616/114144044-84c74b00-9932-11eb-87e2-a639a96d6f64.png)

Steps to reproduce:
- CMD to execute:
   `node <sitespeed.io_path>/sitespeed.js -b <browser_name> --chrome.binaryPath <chrome_path> --chrome.chromedriverPath <chrome_driverpath> --outputFolder <output_folder> -n 1 --cpu --plugins.remove coach --plugins.add analysisstorer --visualMetrics true https://flipkart.com`

**Comment by soulgalore** [comment]
Hi @svkrclg thanks for creating the issue. Can you show me how you run your tests so I can reproduce it? There are an example of what I need here: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue

**Comment by svkrclg** [comment]
Added the steps to reproduce

**Comment by soulgalore** [comment]
For the second filmstrip, what URL do you test? Can you verify that all dependencies are OK (what needs to be installed here https://www.sitespeed.io/documentation/sitespeed.io/installation/#mac). I tested https://flipkart.com and I didn't get the same (using Big Sur)

There's a way to keep the original video `--browsertime.videoParams.keepOriginalVideo`, can you do a run with that and share the video (its named something with original) , then I can run VisualMetrics locally and see what happens?

**Comment by soulgalore** [comment]
You can also try that everything is installed ok for FFMPEG. Easiest is if you clone the sitespeed.io repo and run:
```
❯ ./node_modules/browsertime/browsertime/visualmetrics.py --check
('ffmpeg:  ',)
OK
('convert: ',)
OK
('compare: ',)
OK
('Pillow:  ',)
OK
('SSIM:    ',)
OK
```

**Comment by svkrclg** [comment]
> For the second filmstrip, what URL do you test?
https://www.android.com
I have verified the dependencies, and it is showing OK for every package.

> There's a way to keep the original video --browsertime.videoParams.keepOriginalVideo
I tried using this flag, but I can't see any video generated, also this flag is not mentioned in sitespeed configuration [page](https://www.sitespeed.io/documentation/sitespeed.io/configuration/).
Instead I tried with flag `--video true --videoParams.addTimer false`. Attached video below

https://user-images.githubusercontent.com/30564616/114358082-24354980-9b90-11eb-80c2-bfffefa31b3d.mp4

**Comment by svkrclg** [comment]
IMO, the issue is around cropping the orange part of the video. This orange part is getting considered in extracting the filmstrip.

**Comment by soulgalore** [comment]
I's strange. I tried that video and it looked ok, but can you do one more try so I get the original video:

If I run like this:
`bin/sitespeed.js --browsertime.videoParams.keepOriginalVideo true https://www.sitespeed.io -n 1 --video --visualMetrics`

You will get the video in:
<img width="463" alt="Screenshot 2021-04-13 at 02 57 16" src="https://user-images.githubusercontent.com/540757/114481089-26d18680-9c04-11eb-8aa6-36c9c3a932e2.png">
