### ISSUE TITLE
Problem with --browsertime.chrome.includeResponseBodies all

### ISSUE THREAD

**Issue by pan-alexey** [sitespeedio/sitespeed.io#3342]
For example comand
`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.10.3 --browsertime.chrome.includeResponseBodies all --logToFile --cpu https://en.wikipedia.org/wiki/Barack_Obama`

In report file dont work waterfall.
<img width="1490" alt="Снимок экрана 2021-04-13 в 09 29 12" src="https://user-images.githubusercontent.com/17202913/114506612-b8f48180-9c3a-11eb-878d-98d8ed331ac1.png">

**Comment by soulgalore** [comment]
Hi @pan-alexey what browser do you use when viewing the result? I tried with latest Chrome, Firefox and Safari and there it seems to be displayed correctly. 
<img width="1396" alt="Screenshot 2021-04-13 at 08 34 19" src="https://user-images.githubusercontent.com/540757/114507185-0ec52b80-9c33-11eb-9969-52a899ab3cfb.png">

**Comment by Bobrovskih** [comment]
the same issue

**Comment by pan-alexey** [comment]
Problem with params --browsertime.chrome.includeResponseBodies all

**Comment by soulgalore** [comment]
I haven't been able to reproduce this.
