### ISSUE TITLE
urls alias  + urls with amp

### ISSUE THREAD

**Issue by inti-tui** [sitespeedio/sitespeed.io#3345]
Hi,

We have some urls with "&" and other reserved signs. When we trying to test them together with alias in script, always fail.

ex.
#! /bin/bash
.....
/usr/bin/docker run --rm -v /var/data/sitespeed:/sitespeed.io --sitespeedio/sitespeed.io:16.10.3-plus1 --config ./config-mobile-test.json --urlAlias search_result "https://www.mydomain.se/suchen/hotels/Mallorca/1197/list?searchScope=HOTEL&departureAirports=BRN;DUS;BRU&startDate=2022-04-01&endDate=2022-04-05&showTotalPrice=0&useExtendedFilterDefaultValues=1"
.......

Couldn't find url file at /sitespeed.io/"https:/www.mydomain.se/suchen..."

How should I do?

Very grateful if you could help me. I have test a lot with different approach but can't get it work.

Thanks!

**Comment by soulgalore** [comment]
Hi @inti-tui is that the exact example? The two dashes before _sitespeedio/sitespeed.io:16.10.3-plus1_ seems wrong.

I did a quick test and this works:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:16.10.3-plus1  --urlAlias search_result --n 1 --gpsi.key XXXX "https://www.sitespeed.io/?searchScope=HOTEL&departureAirports=BRN;DUS;BRU&startDate=2022-04-01&endDate=2022-04-05&showTotalPrice=0&useExtendedFilterDefaultValues=1"`

**Comment by inti-tui** [comment]
Hi, thank you for a quick feedback.

The extra dashes was a copy/paste typo.

No, It was not a exact example. 

I have tested your example and it work if you run it "manually" at the command line but not in bash script with loop for urls.

The urls with quotas will expand to something like '"url"' and sitespeed lighthouse don't like it.   

Do you have some example with multiple urls and alias?

**Comment by inti-tui** [comment]
test log from your example with a real url.
[test.log](https://github.com/sitespeedio/sitespeed.io/files/6311234/test.log)

**Comment by soulgalore** [comment]
Sorry for not getting back. This is the PROTOCOL_TIMEOUT error you get in Lighthouse, please checkout the Lighthouse issues if they could help: https://github.com/GoogleChrome/lighthouse/issues/6512
