### ISSUE TITLE
TypeError: result[resultIndex].files.screenshot[runIndex] is not iterable

### ISSUE THREAD

**Issue by sujin-sam** [sitespeedio/sitespeed.io#3346]
I have the following selenium script

```
module.exports = async function(context, commands) {
   
  const webdriver = context.selenium.webdriver;
  const driver = context.selenium.driver;
  const until = webdriver.until;
  const By = webdriver.By;
  const Key = webdriver.Key;

  await commands.measure.start('Home');
  await driver.get("https://www.johnlewis.com");
  await driver.wait(until.elementLocated(By.xpath("//*[text()='Allow all']")),15000);
  await commands.measure.stop();

  await driver.findElement(By.xpath("//*[text()='Allow all']")).click();   
  await commands.wait.byTime(5000);

  await driver.findElement(By.name('search-term')).sendKeys('shirts'); 
      
  await commands.measure.start('Search');
  await driver.findElement(By.xpath("//button[@type='submit']")).click();
  await driver.wait(until.elementLocated(By.xpath("//a[starts-with(@class, 'product-card')]")),10000);
  //await commands.wait.byTime(10000);
  await commands.measure.stop();

  return commands.wait.byTime(10000);

}
```

when I run this, I'm getting the error at the `Search` page, while stopping the measure
The console log file with the error is in the attached doc
[Iterable_error_sitespeed.txt](https://github.com/sitespeedio/sitespeed.io/files/6310437/Iterable_error_sitespeed.txt)

If I comment this line ` await driver.wait(until.elementLocated(By.xpath("//a[starts-with(@class, 'product-card')]")),10000);` and use `await commands.wait.byTime(10000);` , the script runs fine

**versions**
Sitespeed - `16.10.3`
BrowserTime - `11.6.3`
Coach - `6.1.0`
Node - `14.16.1`
Firefox - `87.0`

**Comment by soulgalore** [comment]
Hi @sujin-sam thanks for the detailed bug report let me have a look.

**Comment by soulgalore** [comment]
Thanks again @sujin-sam for the bug report. It's super helpful when you write exactly how you run so we can recreate the issue. It seems that sometime the HAR exporter that we use for Firefox takes some extra time after the page has been loaded to be accessed. I fixed that now so that if it fails (like it did for you) it will wait some extra time until tries again.

I'm in the middle of doing a new release, but I don't think it will be ready today so hopefully early (CET) tomorrow you can try it out.

**Comment by sujin-sam** [comment]
Thanks @soulgalore for the quickfix and the tip, I'll keep in mind when I write

**Comment by soulgalore** [comment]
@sujin-sam I meant your bug repot where perfect since I could recreate the issue with it :)

**Comment by sujin-sam** [comment]
Ah ok, I misunderstood the line :)

**Comment by soulgalore** [comment]
@sujin-sam I've just pushed 17.0.0 where the issue should be fixed (at least it works then for me when I tried).

**Comment by sujin-sam** [comment]
@soulgalore its working fine from my end as well
btw, I'm new to node how to upgrade sitespeed.io using npm command? I had to re-install

**Comment by soulgalore** [comment]
Yes you need to re-install!
