### ISSUE TITLE
No "standard" video/screenshot produced

### ISSUE THREAD

**Issue by kissifrot** [sitespeedio/sitespeed.io#3350]
Hello,

I'm trying to run the docker container (17.0.0 version)  with the following config:
```json
{
  "extends": "/config/secrets.json",
  "browsertime": {
    "connectivity": {
      "engine": "throttle",
      "profile": "cable"
    },
    "visualElements": true,
    "iterations": 3,
    "browser": "chrome",
    "video": true,
    "visualMetric": true,
    "chrome": {
      "collectConsoleLog": true,
      "enableTraceScreenshots": true
    },
    "firefox": {
      "includeResponseBodies": "all",
      "disableBrowsertimeExtension": true,
      "windowRecorder": true,
      "geckoProfiler": true
    }
  },
  "cpu": true,
  "gzipHAR": true,
  "outputFolder": "desktop",
  "html": {
    "fetchHARFiles": true,
    "showScript": true,
    "compareURL": "https://compare.mysite.io/"
  },
  "screenshot": {
    "type": "jpg"
  },
  "slug": "firstView",
  "graphite": {
    "namespace": "sitespeed_io.desktop",
    "addSlugToKey": true
  }
}
```

Againts an URL list (in the same format as https://github.com/sitespeedio/dashboard.sitespeed.io/blob/main/tests/desktop/desktop.txt for example), however when I try to feed the results to the same dashboard as the one on https://dashboard.sitespeed.io/d/9NDMzFfMk/page-metrics-desktop?orgId=1 (Graphite data source), there is neither a jpg screenshot nor a video in the results folder.

Did I miss something in the config?

**Comment by soulgalore** [comment]
Hi @kissifrot let me update the documentation how to debug and make it easier to understand how it work. Have you added the result base URL? 

The path to the image is created using the following config in the panel:
<img width="907" alt="Screenshot 2021-04-15 at 20 37 30" src="https://user-images.githubusercontent.com/540757/114921129-7f826880-9e2a-11eb-86c4-9540f2b146b6.png">

To debug it, you can either inspect the HTML in Grafana, check the network log in devtools (to see if the full URL is correct) or add `<div>$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype</div>` to the panel so you can see it.

**Comment by soulgalore** [comment]
@kissifrot I updated the docs: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#how-to-get-the-latest-videoscreenshot-visible-in-grafana - please let me know how it work out for you and I can have another go in making the docs better tomorrow.

**Comment by kissifrot** [comment]
@soulgalore Thanks for the insight, I fiddled a bit with the settings and along my tests I set `--outputFolder` which prevented the use of  `--copyLatestFilesToBase`.

However, as I used s3 I also had to set `--s3.path` for the screenshot to appear (as otherwise it would have been stored by default to a new timestamped-folder.

So what I would suggest is add this indication about the need to set `--s3.path` (or `--gcs.path` I guess) when using S3 or GCS as output destination for the screenshot to be displayed correctly with this setup

Good job otherwise 👍

**Comment by soulgalore** [comment]
So how do you set it @kissifrot :) I didn't fully follow. I use s3 and the configuration I use is:

```
 "s3": {
    "key": "XXXXX",
    "secret": "YYYYYY",
    "bucketname": "results.sitespeed.io",
    "removeLocalResult": true
  },
```

**Comment by kissifrot** [comment]
EDIT: However when using S3 with the `--path`, slug isn't taken into account, so data is uploaded directly in the specified path and not in the path/`slug` subfolder

**Comment by kissifrot** [comment]
@soulgalore 
I used
```json
  "s3": {
    "key": "XXXXXXX",
    "secret": "YYYYYY",
    "bucketname": "sitespeed-bucket",
    "removeLocalResult": true,
    "path": "sitespeed"
  }
```

**Comment by soulgalore** [comment]
Thanks @kissifrot , any reason you use the path? I think I missed testing with that.

**Comment by kissifrot** [comment]
@soulgalore Well after cleaninp up all my previous (failed) tests from S3 the base S3 config works correctly, so path isn't needed at all, sorry for the noise 😞 

All works well (except for the vitals and such but I guess I will have to wait for a few runs before having results to display within a long timeframe)

**Comment by kissifrot** [comment]
Since my original question was answered, I'm closing this issue, thanks a lot! 👍 

BTW: How on  the [leaderboard ](https://dashboard.sitespeed.io/d/000000060/leaderboard?orgId=1&var-namespace=sitespeed_io&var-path=desktop&var-testname=firstView&var-domains=All&var-pages=All&var-browser=chrome&var-function=median&var-connectivity=cable) can you still have data with a 7 days timespan? 

I only have values in the leaderboard when I select an interval less than last 6 hours, even if collected data is older 😭
