### ISSUE TITLE
The test result is slower than real experience

### ISSUE THREAD

**Issue by jamee-wang** [sitespeedio/sitespeed.io#3353]
I use docker to test my site, I always got slower metrics, say: Last Visual Change about 6s, I saw the vedio it's also 6s arond, however, I checked my stopwatch，the time should be 4s around.

My startup command
`
docker run -d  sitespeedio/sitespeed.io:17.0.1 https://xxx.com -b chrome --visualMetrics --spa --browsertime.chrome.CPUThrottlingRate=1
`

And even I set higher cpu and memory for docker container, the metrics got slower.

**Comment by soulgalore** [comment]
Hi @jamee-wang can you share the video? It could be that Visual Metrics (that analyse the video) pick up some artefacts maybe?

**Comment by jamee-wang** [comment]
Sorry, I can't upload file, maybe I found the reason, When I clear all cache of chrome, I browser the web page, the time is close to 6s, I think the sitespeed run the chrome in a clean environment, and when I add --preURL, the time is close to 4s.

Am I right?

**Comment by soulgalore** [comment]
Yes it starts as a new "clean" user.
