### ISSUE TITLE
Trying for the first time, no data showing in grafana

### ISSUE THREAD

**Issue by outdooricon** [sitespeedio/sitespeed.io#3356]
Hello, I just ran through the install instructions on https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes up to step 4. However, when I navigate to localhost grafana, all of the boards are showing no data.

If I navigate around in graphite on :8080, it does look like there is data stored in there currently. Also, if I test the Graphite Datasource in grafana, it says "DataSource is working".

I'm on macOS Mojave.

Am I missing a step? Loving this project already and can't wait to get even deeper into it!

**Comment by soulgalore** [comment]
Hi @outdooricon oops, I think I've missed update the 5 minutes run example: In 17.0.0 we introduced seeing the name of your test to Graphite and that needs to be included for the dashboards to work:  `--slug yourTestName --graphite.addSlugToKey true`, please try with that and let me know if it works. I'm gonna update the example now.

**Comment by outdooricon** [comment]
That did it, thanks @soulgalore!
