### ISSUE TITLE
Example Dashboard - Page Summary Dashboard not found(Grafana+Graphite)

### ISSUE THREAD

**Issue by IngCesarPerf** [sitespeedio/sitespeed.io#3363]
Hi everyone,

I'm looking at the page http://www.sitespeed.soulislove.com/examples/  some examples about to use performance dashboard with sitespeed and grafana, these dashboards are amazing, but in the web site i click on "Chechout our example dashboard" and i can't load the page
![image](https://user-images.githubusercontent.com/75047962/116278109-c8e88700-a74b-11eb-8794-145d71469a17.png)

in this case i need to use this dashboard (PageSummary) with "Avg Last 24 Hour", "Relative to Yesterday", "Relative to last week", "Relative last month". attached image of the dashboard and the gauges framed in red, 
I hope you can help me.

![image](https://user-images.githubusercontent.com/75047962/116277539-32b46100-a74b-11eb-9700-dc70d6a41df6.png)

Regards.

**Comment by soulgalore** [comment]
Hi @IngCesarPerf so I removed that part when I updated some versions ago, I wasn't using it, but let me add again. I can do it later this week and I will ping the issue when it's done.

**Comment by IngCesarPerf** [comment]
Thank you very much @soulgalore  I'll be attentive
