### ISSUE TITLE
Error: The coach got the following errors: {"info":{"sessionStorageSize":"Cannot read property 'length' of null"}} (browsertime)

### ISSUE THREAD

**Issue by jpalmer-miovision** [sitespeedio/sitespeed.io#3365]
I am getting this error when loading pages on my application:

`The coach got the following errors: {"info":{"sessionStorageSize":"Cannot read property 'length' of null"}} (browsertime)`

Unfortunately I haven't been able to reproduce on other sites, and I can't share this URL.  Talking to Peter on Slack, he says:

"I checked the code and it looks like "window" is not defined on that page. If you can create an issue I can add a guard for that in future releases."

Here is my script I'm running:

```
module.exports = async function(context, commands) {
   await commands.navigate(

'<website url>'
   )
try {
   await commands.addText.byName('<my login>', 'email');
   await commands.addText.byName('<my password>', 'password');
   await commands.click.byClassName('auth0-label-submit');
   await commands.wait.byId('divMainContentFullScreen', 10000); 
   await commands.measure.start('https://<my-web-application>/listview/listviewpage.aspx');
   await commands.measure.start('https://<my-web-application>/requeststudy/requeststudypage.aspx');

 } catch (e) {
   throw e;
 }
};
```

**Comment by soulgalore** [comment]
Hi @jpalmer-miovision can you try add one line so it looks like this:

```
...
await commands.click.byClassName('auth0-label-submit');
await commands.wait.byPageToComplete() 
await commands.wait.byId('divMainContentFullScreen', 10000); 
...
```

That way, it will use the [regular check](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#waitbypagetocomplete) to see that the page has finished loading before continue to the next step.

I think that `await commands.wait.byId('divMainContentFullScreen', 10000);` could return before everything on the page is finished so it can mess up things. I'm not 100% sure though that it will fix the error.

Best
Peter
