### ISSUE TITLE
Grafana Container unable to reach Graphite, gives 404

### ISSUE THREAD

**Issue by cutebadmash** [sitespeedio/sitespeed.io#3372]
Hi,

**SETUP**

1. I have installed sitespeed using the docker compose file as outlined in this [link](https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes).
2. This is on a single AL2 ec2 instance. 
3. ALL TCP Ports are open on the security group for the instance.
4. Both the containers are present on the ec2-user-default network.
5. Public IP:  18.234.193.241

**ISSUE:**

1. Checking the grafana logs I found the following error code
`2021-05-04T14:09:30+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
 t=
2021-05-04T14:09:31+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=sitespeedio method=GET path=/api/datasources/id/graphite **status=404** remote_addr=172.18.0.4 time_ms=21 size=35 referer=`

2. Neither grafana not Graphite are accessible using the public IP of the ec2 instance. I get an ERR_EMPTY_RESPONSE
![image](https://user-images.githubusercontent.com/8313019/117175284-aafad200-ad9c-11eb-8205-c4c497a27c98.png)

3. running a cURL on http://localhost:3000 results in the below response.
![image](https://user-images.githubusercontent.com/8313019/117175851-4429e880-ad9d-11eb-84c4-5b7ee14c13b2.png)

Any help is appreciated

**Comment by cutebadmash** [comment]
still the same. @soulgalore 
Though the instance details are different.
public ip: 3.128.172.52

**Comment by soulgalore** [comment]
Does it work when you try the same locally on your machine? This looks like a server issue?

**Comment by cutebadmash** [comment]
having issues running Docker locally. Hence using this aws instance.
