### ISSUE TITLE
Unable to run docker image (sitespeedio/sitespeed.io:17.3.1) on Centos 7

### ISSUE THREAD

**Issue by ganeshcpote** [sitespeedio/sitespeed.io#3378]
I am having Centos 7 version with docker enabled and docker image sitespeedio/sitespeed.io:17.3.1 unable to execute the test. It exit the execution without any error message.

**OS version which I am using for the test :** 
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Docker command which I am executing to run the basic test :**
docker run --rm -v /var/lib/jenkins/workspace/sitespeedtest:/sitespeed.io 	 https://www.google.com  --slug test14 -b chrome -d 1 -m 1 --outputFolder output

**Output I am getting after execution :** 
Google Chrome 90.0.4430.85
Mozilla Firefox 88.0
Microsoft Edge 89.0.774.14 dev

**Comment by soulgalore** [comment]
Hi @ganeshcpote the output you get is from the start script (before sitespeed.io has started). After that there's a trick that try to fix so the output files are written for the user that you use https://github.com/sitespeedio/sitespeed.io/blob/main/docker/scripts/start.sh#L29-L43 , I'm thinking that goes wrong somehow? Can you check the owner and right privileges to the directory where you to run (var/lib/jenkins/workspace/sitespeedtest) and see that those are correct for the user that runs sitespeed.io?

**Comment by ganeshcpote** [comment]
Hi @soulgalore - It was permission issue on folder and this issue fixed. Thanks for your help
