### ISSUE TITLE
How to disable the HTML output

### ISSUE THREAD

**Issue by ganeshcpote** [sitespeedio/sitespeed.io#3379]
I am using InfluxDB as my data source and want to disable the default output (HTML/JSON) on storage/local. Is there any way to only push output to InfluxDB?

**Comment by ganeshcpote** [comment]
Is there any way to push HAR file content as well to influxdb or graphite like other metrics? This will add additional value to the users who just want to use database driven approach and build their own dashboards.

**Comment by soulgalore** [comment]
The HAR data is summarised in PageXray. If you need the timing metrics for each requests, you could either configre sitespeed.io to send that but it will generate so much data, I thunk a better approach is to build your own plugin.
