### ISSUE TITLE
Connection issue by AWS S3 upload

### ISSUE THREAD

**Issue by lochy89** [sitespeedio/sitespeed.io#3382]
Hi.

I have an issue.
We run the test from kubernetes cluster and everything works fine except one thing.
Uploading to S3. I tried many-many things out.

I am running the test internally, behind a corporate proxy and sitespeed can not upload the generated results to S3.
I tested everything out.

It is possible to upload files from the same sitespeed container with aws-cli. So there is no problem with credentials.
But the aws-sdk seems not to working.

What the output said:

> INFO: Uploading /sitespeed-result/test/2021-05-14-09-32-00 to S3 bucket XXXXXXXXXXXXX, this can take a while ...

> ERROR: Could not upload to S3 NetworkingError: connect ECONNREFUSED 52.219.74.177:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

For the sitespeed container i have created the following proxy env vars.

        - name: HTTP_PROXY
          value: "http://xxxxxxxxxxxxxx:80"
        - name: HTTPS_PROXY
          value: "http://xxxxxxxxxxxxxx:80"
        - name: NO_PROXY
          value: "graphite,prometheus,localhost,*.xxxxxxx"

Do i need somewhere else change the proxy for nodejs aws-sdk?
If it is so, where?

Thank you in advance!
Regards, Balint

**Comment by soulgalore** [comment]
Hi @lochy89 I think you need set specific AWS properties to use the proxy.

Checkout how in https://www.sitespeed.io/documentation/sitespeed.io/s3/#extra-configuration and then you have the documentation of the AWS properties: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

Best
Peter

**Comment by lochy89** [comment]
Hi @soulgalore.

Thank you for the quick reply. Ok, i'm not a developer. :)
Should i give the script the following part?

--s3.params.httpOptions.proxy=http://proxy.xxxxx.de:80

Regards

**Comment by lochy89** [comment]
Ok, i solved it with --s3.options.httpOptions.proxy
Thank you and habe a nice day!

**Comment by soulgalore** [comment]
Great!
