### ISSUE TITLE
Lighthouse metrics in performance budget

### ISSUE THREAD

**Issue by Andrei-Rudenka-bos** [sitespeedio/sitespeed.io#3384]
Please add lighthouse metrics to performance budget, such as :
First Contentful Paint
Speed Index
Largest Contentful Paint 
Time to Interactive 
Total Blocking Time
Cumulative Layout Shift

**Comment by soulgalore** [comment]
No. The reason is that those metrics are so unstable for Lighthouse so I think no one should use them.
