### ISSUE TITLE
Need some information

### ISSUE THREAD

**Issue by Resolution-of** [sitespeedio/sitespeed.io#3391]
Hello, I've been working with your application for about a month on my current project and have several questions. It won't be a trouble if you don't answer them, nevertheless I can say that your application is pretty good. Particularly HTML report. So my questions:
1. Can run selenium python scripts in it (coded js selenium, but for some reasons need python)?
2. Grafana dashboard is cool too, but there is a way to make dashboard not for summary of iterations, but for each of them? From my point of you static dashboard need to have such feature, when you need only one iteration from all (nowadays I need to show in my report iteration with max time, when there are 60 of them). Or maybe I am not enough attentive and you have this? :)
3. Is there any way to put test user info from csv file to script, such as login and password, running not locally with NodeJS, but with docker?
I hope for an answer. Have a productive day!

**Comment by soulgalore** [comment]
Hi @Resolution-of 

> Can run selenium python scripts in it (coded js selenium, but for some reasons need python)?

No.

> Grafana dashboard is cool too, but there is a way to make dashboard not for summary of iterations, but for each of them?

Yes there are but I. didn't fully understood. the use case? If you need every run in Graphite/Grafana you can add `--graphite.perIteration` then all the data per run is sent. Next step is to configure Graphite so.they are stored. Read https://www.sitespeed.io/documentation/sitespeed.io/graphite/#configure-graphite to get a feeling for what's needed. 

> Is there any way to put test user info from csv file to script, 

Either you can pass on parameters like https://www.sitespeed.io/documentation/sitespeed.io/scripting/#pass-your-own-options-to-your-script or you can just read the CSV file in your script and use the data.

**Comment by Resolution-of** [comment]
Thanks a lot for an answer. I will try.
One more time, your application is awesome
