### ISSUE TITLE
Selenium multiple click during journey needs wait.byTime

### ISSUE THREAD

**Issue by bodtx** [sitespeedio/sitespeed.io#3395]
Hi, I'm running sitespeedio/sitespeed.io:17.5.0

When I use directly the selenium driver, I often need to place a commands.wait.byTime to wait the real page load (dom + js)

if I don't, I have a problem with components rendered with javascript : bootstrap and other jquery select box....

My test is like this
 
    await commands.wait.byTime(2000);
    await driver.findElement(webdriver.By.css(".even:nth-child(4) > .select-checkbox")).click()
    await driver.findElement(webdriver.By.id("nbRelance")).click()
    await driver.findElement(webdriver.By.css(".odd:nth-child(1) .ouvreConfirmation > .rouge")).click()
    await commands.wait.byTime(2000);
    await driver.findElement(webdriver.By.css(".even:nth-child(4) > .select-checkbox")).click()
    await driver.findElement(webdriver.By.id("commentaire")).click()

I've tried to use every tricks told by this page: https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test

but it seems to work only for the global test and not for each pages inside the journey.
Is there a way to really wait the final render (as the selenium ide would do)?

**Comment by soulgalore** [comment]
Hi @bodtx I see. The default click commands has a clickAndWait alternative (see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#click) that means that when you click a link etc the default  page complete check will run (waiting on load etc). If you do not use them, you can  use the waitByPageToComplete https://www.sitespeed.io/documentation/sitespeed.io/scripting/#waitbypagetocomplete

So for every time when you want navigate to a new page, click a link you can do something like this:
```
await driver.findElement(webdriver.By.css(".odd:nth-child(1) .ouvreConfirmation > .rouge")).click();
await commands.wait.byPageToComplete();
```

Could that do the trick?

**Comment by bodtx** [comment]
indeed great.

I need to launch the docker with the parameter  

`--browsertime.pageLoadStrategy="normal"`

then I've replaced my 

 await commands.wait.byTime(2000);

with

 await commands.wait.byPageToComplete();
 
this is great as it has shrunk the execution time of my tests to its minimum. 


thx ❤️️

**Comment by Icecold777** [comment]
Hello, @soulgalore please give a piece of advice. I faced pretty the same issue but using SPA app which sometimes doesn't return pageComplete event.
As workaround I wait for an element with wait.bySelector. Is it possible to use smth more universal as I have to update element selectors from tome to time?

**Comment by soulgalore** [comment]
Hi @Icecold777 no there's no perfect way I think. One thing you could do is to increase the wait time for the page complete check,but that will make the test take longer time to run.
