### ISSUE TITLE
Webpagetest plugin runs but throws error in summary page

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#3401]
Hi Peter,

The webpagetest plugin runs with no issues but in the sitespeed.io summary page, it doesn't show up and throws an error.  

![image](https://user-images.githubusercontent.com/1022410/120267314-b8a75880-c271-11eb-8344-d38b3f5e3e63.png)

TypeError: Cannot read property 'replace' of undefined (webpagetest)

**Comment by soulgalore** [comment]
Hi @kmaqsudi looking at the code it looks like the data from WebPageTest misses out on a location in the JSON back from WebPageTest? https://github.com/sitespeedio/plugin-webpagetest/blob/main/index.js#L247

If you have the test id of the test., you could go to the WebPageTest server and look at the JSON that is returned (I don't have the exact URL in my head but I think the WebPageTest team has it documented somewhere).

**Comment by kmaqsudi** [comment]
Hi @soulgalore  Thanks for that info.   Thats exactly what my problem was.   Issue resolved now.  Thanks
