### ISSUE TITLE
Lighthouse, GPSI export to Influxdb 

### ISSUE THREAD

**Issue by ganeshcpote** [sitespeedio/sitespeed.io#3415]
Hello team,

I am using sitespeed.io and want to check if we have Lighthouse and GPSI metrics export to Influxdb. If yes, what are those measurements.

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @ganeshcpote for Lighthouse look for the tag **audit** , for gpsi you should be able to see the ones with the tag **strategy**. We should probably add a tag per tool to make it easier to see where the metric origin.

**Comment by ganeshcpote** [comment]
> Hi @ganeshcpote for Lighthouse look for the tag **audit** , for gpsi you should be able to see the ones with the tag **strategy**. We should probably add a tag per tool to make it easier to see where the metric origin.

Thanks @soulgalore. I can find the records under **score** with score.origin = "lighthouse" for lighthouse and for **gpsi** under accessibility, best-practices, seo, performance, pwa metrics. 

We can arrange these scores under **score" measurement at consolidated place with CUxR score as well.

**Comment by joshuagibeonm** [comment]
I tried to find web vitals field data distribution from GPSI in InfluxDB. But it's missing.

The only measurement that sent to InfluxDB is LCP distribution from all pages served from particular origin. Under fast, moderate, and slow metric.

Do you have any idea where I could find the rest of them?

**Comment by soulgalore** [comment]
Hi @joshuagibeonm I think we do not add them to influx by default, so we need to add that then in https://github.com/sitespeedio/sitespeed.io/blob/main/lib/plugins/influxdb/data-generator.js. Collecting them directly through the Crux plugin I think we add them but need to check.

**Comment by joshuagibeonm** [comment]
Hi @soulgalore. If sitespeed don't add them to influx by default, then I think readme file in plugin-gpsi needs some rewording.

>By default the plugin sends the GSPI score for the tested page for the five categories: accessibility, seo, pwa, best-practices and performance.

>It also sends the loadingExperience for the page. That includes the actual percentile for First Contentful Paint and First Input Delay and the percentage of fast/moderate/slow users.

At least for me, It implies that the plugin sends the loadingExperience by default.

**Comment by soulgalore** [comment]
I see, I think it does for Graphite but not for InfluxDB then. Let me fix that when I'm back from vacation in a couple of weeks.

**Comment by soulgalore** [comment]
Or even earlier, let me have a look tonight.

**Comment by soulgalore** [comment]
Hi @joshuagibeonm sorry I didn't fully understood what you meant. Had some time now and added a PR for fixing the problem with GPSI. The current released version do not add any good tags so you can separate the metrics. 

Do you have time to check the PR and see if those new tags works fine for you?

**Comment by joshuagibeonm** [comment]
Hi @soulgalore. I checked the PR and It works very well. Except somehow I have to remove all metric that related to first input delay first because the result from PGSI didn't have first input delay.

Thank you for your time and the PR! I really appreciate it.

**Comment by soulgalore** [comment]
Thanks @joshuagibeonm for checking the out. I've merged the PR and hope to release it tomorrow. It seems like GPSI plugin is over optimistic that the data is always there (I did get the same when I tried www.sitespeed.io), let me fix that too.

**Comment by soulgalore** [comment]
@joshuagibeonm I've just released the fix, hope it works out fine for you!

**Comment by joshuagibeonm** [comment]
@soulgalore Thanks a lot!
