### ISSUE TITLE
Accept chromedriver port or port range as cli param

### ISSUE THREAD

**Issue by svkrclg** [sitespeedio/sitespeed.io#3427]
This is not a bug, but rather a **feature**. A feature to specify the Chromedriver **port** or port range through our **CLI** param. 
This will eventually act as `--port ` for our Chromedriver process. 

Use case: 
- This can be used to identify and kill  (externally) the stray Chromedriver process in the situation when Sitespeed gets crashed for an unknown reason.
- Can be helpful in the automation of sitespeed.

I have figured out few changes that need to be done in the sitespeed.io and browsertime repo.
Let me know your thoughts on this idea. @soulgalore 
Thanks

**Comment by soulgalore** [comment]
Hi @svkrclg yes sounds like a good idea!

**Comment by svkrclg** [comment]
Cool, so I will start with the dev of this.
