### ISSUE TITLE
HTML reports not being written to Jenkins artificacts

### ISSUE THREAD

**Issue by jsbalasu** [sitespeedio/sitespeed.io#3431]
We are trying to run sitespeed via docker [latest image] via Jenkins and noticed its not writing HTML reports if I exceeds the url count 6 or 7.

Versions OS: linux 4.15.0-147-generic nodejs: v14.17.1 sitespeed.io: 18.0.0 browsertime: 13.1.2 coach: 6.4.3 
Google Chrome 92.0.4515.107 

**Error:**

**/start.sh: line 41:    41 Killed                  chroot --skip-chdir --userspec='sitespeedio:sitespeedio' / node "$@"**

I am seeing this discussion thread [1424](https://github.com/sitespeedio/sitespeed.io/issues/1424)

Could you please help me to fix the issue?Thanks.

Pleas note I run the command as below

```dir ('jenkins/jobs/sitespeed') {
                    sh '''#!/bin/bash
                       sitespeed=$(docker run -d -v /sitespeed.io -e MAX_OLD_SPACE_SIZE=8192 sitespeedio/sitespeed.io init.js --multi -n 1  --browsertime.email "${EMAIL}" --browsertime.password "${PASSWORD}" --outputFolder results --resultBaseURL /sitespeed.io/results)
                       docker cp init.js ${sitespeed}:/sitespeed.io/init.js
                       docker start ${sitespeed}
                       docker logs --follow ${sitespeed}
                       docker cp ${sitespeed}:/sitespeed.io/results results
                       docker rm ${sitespeed}
                    '''
                    archiveArtifacts (artifacts: 'results/**', fingerprint: true)
   ```
                    
**Script [init js]**

```async function setUp(context, commands) {
    // Navigate to a URL, but do not measure the URL
    await commands.navigate(
      'https://xx/xx/login/landing'
    );
  
    try {
      // Add text into an input field, finding the field by id
      await commands.addText.byXpath(context.options.email, '//*[@id="email"]');
      await commands.wait.byTime(1000);
      await commands.click.bySelector('#next-button');
      await commands.wait.byTime(5000);
      await commands.addText.bySelector(context.options.password, '#password');
      await commands.wait.byTime(5000);
      await commands.click.bySelector('#signinbutton');
      await commands.wait.byTime(5000);
    } catch (e) {
      throw e;
    }
};

async function perfTest(context, commands) {
  await commands.measure.start('https://xxx/xx/xx/xx');
  await commands.measure.start('https://xxx/xx/xx/xx');
  await commands.measure.start('https://xxx/xx/xx/xx');
  await commands.measure.start('https://xxx/xx/xx/xx');
  return commands.measure.start('https://xxx/xx/xx/xx');
};

module.exports = {
  setUp: setUp,
  test: perfTest
};
```

**Comment by jsbalasu** [comment]
@soulgalore it would be great if we get guidance asap for this thanks

**Comment by soulgalore** [comment]
Hi @jsbalasu do I understand correctly that if you test more than X(6-7) URLs in your script, you get the error:
> /start.sh: line 41: 41 Killed chroot --skip-chdir --userspec='sitespeedio:sitespeedio' / node "$@"

Is that correct? If you run outside of Jenkins do it work there? Or is this only when you kick off the jobs from Jenkins?

**Comment by jsbalasu** [comment]
Hello @soulgalore,
Its working fine when I run locally in my machine [outof Jenkins].Issue is only when running via Jenkins.you can see I am using MAX_OLD_SPACE_SIZE=8192 while running Jenkins Pipeline.

Let me know how we can fix this.Thanks

**Comment by jsbalasu** [comment]
@soulgalore Could you please assist?Thanks

**Comment by soulgalore** [comment]
Is Jenkins using Docker so you run Docker in Docker?

**Comment by jsbalasu** [comment]
Yeah that's right @soulgalore

**Comment by jsbalasu** [comment]
We have fixed the issue the other way.thanks
