### ISSUE TITLE
Make tests in a website with a lot of simultaneous connections

### ISSUE THREAD

**Issue by albertvilabsc** [sitespeedio/sitespeed.io#3436]
Hi all,
I have a question regarding sitespeed.io. 
Can you test how a website behaves with many simultaneous connections? sitespeed.io, can do this? Simulate many simultaneous connections and make the tests?
I use sitespeed.io with docker in Ubuntu 20.04 LTS.
Many thanks in advance,
Albert

**Comment by soulgalore** [comment]
Hi @albertvilabsc you mean like test for many users? I think its better to use a load test tool like K6 or something else and then at the same time run sitespeed.io with one instance to get a feeling of what it would look like for one user.

Best
Peter

**Comment by albertvilabsc** [comment]
Hi @soulgalore, yes test the page with a lot of load.
You know some free tool to make load tests in a webapge?
You mean that I need to use a tool to make a lot of connections in my website and at the same time use sitespeed.io?
Apache JMeter is a solution?
Thanks,
Albert

**Comment by soulgalore** [comment]
Yes you should try some of those other tools.
