### ISSUE TITLE
Sitespeed.io report showing only few metrics after testing on safari

### ISSUE THREAD

**Issue by imakhnyboroda** [sitespeedio/sitespeed.io#3438]
Hi! I am doing a safari test and I am wondering if it is expected that I do not have as many metrics as in Chrome
![image](https://user-images.githubusercontent.com/89066077/130090214-bea85177-20a9-44b7-8402-a3e3730edc16.png)

I used for running test this command:
sitespeed.io --name "Desktop TU safari" -b safari -n 20 https://[my url]/

**Comment by soulgalore** [comment]
Hi @imakhnyboroda yes it is. We lack many metrics from Safari:
* Safari lack implementation of a lot of performance metrics direct in the browser
* We also miss out on getting a HAR file from Safari (I have an open feedback assistant number for that)
* On desktop you can get visual metrics if you follow the instructions on https://www.sitespeed.io/documentation/sitespeed.io/installation/#mac to get the extra things you need.
* For Safari on iOS there's an open issue for a fixing the video and visual metrics see https://github.com/sitespeedio/browsertime/issues/1598

**Comment by imakhnyboroda** [comment]
Thank you so much for detailed information!
