### ISSUE TITLE
Missing most active frame. Number of threads 0, Number of TraceEvents X and Threads []

### ISSUE THREAD

**Issue by MichaelDally** [sitespeedio/sitespeed.io#3444]
Hello,

I have a website which opens a new tab. I press a button and I want to wait for the task to process before asserting that the screen is loaded. Using the Firefox browser, I have been able to get metrics; however, with Chrome, I see the following error:

`Missing most active frame. Number of threads 0, Number of TraceEvents X and Threads []
`

Here is some sample code - for security reasons I cannot provide real URLs or passwords, but I hope this is enough to help debug

```
module.exports = async function(context, commands) {
    // Navigate to a URL, but do not measure the URL
    await commands.navigate(
      'https://stg-accounts.gomolearning.com'
    );

  const webdriver = context.selenium.webdriver;
  const driver = context.selenium.driver;

    try {
      // Add text into an input field, finding the field by id
      await commands.addText.byId('email@address.com, 'username');
      await commands.addText.bySelector('PASSWORD', '.passwordField');
 
      await commands.click.bySelectorAndWait('.btn-primary');

      console.log("OPENING PORTAL")
      await commands.switch.toNewTab('https://my.desired.url');

      console.log('ATTEMPTING CLICK ON COURSE CREATION BUTTON');
      await commands.click.bySelectorAndWait('.btn.purple-cta-button');

      await commands.addText.byId('Perf Test:', 'project_name');
      await commands.click.byLinkText('Next');
      await commands.click.byLinkText('Next');
      await commands.click.byLinkText('Create');

      await commands.measure.start('Some alias');
      await commands.wait.bySelector('.some-item',30000);
      return commands.measure.stop();
    } catch (e) {
      throw e;
    }
  };
```

I am running this command with

`docker run --privileged --shm-size=512m --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest ~/Documents/SitespeedTests/script.js -b chrome -n 1 --multi
`

OS: Mac Big Sur 11.1

**Comment by soulgalore** [comment]
Thank you @MichaelDally for the report! 

What is suppose to happen when you run:
` await commands.wait.bySelector('.some-item',30000);`

Are you loading a new page with the click? Sometimes the select can be there but the page hasn't finished loading, can you try and change:
```
await commands.wait.bySelector('.some-item',30000);
```
to 
```
await commands.wait.bySelectorAndWait('.some-item');
```
That will make sure that the default check for waiting for the page to load is used see https://www.sitespeed.io/documentation/sitespeed.io/scripting/#clickbyselectorandwaitselector

**Comment by MichaelDally** [comment]
My original intent was to wait for that page to load - the previous step clicks a Create button, which waits for some background processing before redirecting to a new page. I've since modified the wait code to

`await commands.measure.start('Project Creation');

      await commands.click.byLinkTextAndWait('Create');  // My assumption here is that it will wait for the redirect

      return commands.measure.stop();
`

I'm now getting this error:

`
[2021-08-25 13:32:14] INFO: Start to measure Project Creation
[2021-08-25 13:32:24] INFO: No element attached to the entry in largest-contentful-paint
[2021-08-25 13:32:26] ERROR: Missing most active frame. Number of threads 0, Number of TraceEvents 1615 and Threads []
[2021-08-25 13:32:26] ERROR: TypeError: Cannot read property 'frame' of undefined

**Comment by soulgalore** [comment]
I see. Can you check if the _trace-1.json.gz_ file is saved in the data folder for the URL that you test? Then if you can please share that file (that's Chrome log) with me on Slack I can check if I understand what's going on. Thanks!

**Comment by MichaelDally** [comment]
@soulgalore the issue I was facing was due to the fact that my workflow was opening multiple tabs, so it was unable to collate all of the performance logs. To workaround this, I injected JS into elements which would open a new tab and force them to open in the same window:

`      await commands.js.run("$('.button-which-opens-new-tab').attr('target', '_self');");
`

This resolved my problem! Thanks for your assistance
