### ISSUE TITLE
[help required] Modify JUnit test suite name or test case class name

### ISSUE THREAD

**Issue by vishallanke** [sitespeedio/sitespeed.io#3447]
Sitespeed generate below junit test cases after test execution - 

```
<testsuites>
<testsuite name="sitespeed.io.account_apps_._" tests="6" failures="0" errors="0" skipped="0">
<testcase classname="account_apps._" name="timings.Page Load Time">
<system-out>
<![CDATA[ Page Load Time is 1.662 s ]]>
</system-out>
</testcase>
</testsuites>
```

```
testsuite name = sitespeed.io.account_apps_._
testcase classname="account_apps._" 
```

Due to this after importing this test cases, I can see test case name ```sitespeed.io.account_apps_._```
Here, I want name of my script  file. Is there a way where I can replace these names with some user friendly tests case name.

![image](https://user-images.githubusercontent.com/46259109/131091340-afc1b549-7641-4fbf-aa83-d35941841f9e.png)

**Comment by vishallanke** [comment]
@soulgalore  Yes, its working ! :) Thanks

**Comment by vishallanke** [comment]
I can see some error like below-
ERROR: It seems like you configure a metric accessibility that we do not have a friendly name. Please check the docs if it is right.

Is this related to budget friendly name property ?

**Comment by soulgalore** [comment]
@vishallanke yes, can you check if there is a metric configured in your budget file that do not exist in https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/#all-possible-metrics-you-can-configure ?
