### ISSUE TITLE
Unable to see all test result data on grafana

### ISSUE THREAD

**Issue by iamlohith** [sitespeedio/sitespeed.io#3451]
Hi , i did a setup of sitespeed.io ,webpagetest and graphite and grafana(i installed sitespeed using npm install -g and  i installed , 
wpt graphite and grafana using docker )

But the problem is when i run this command 
`sitespeed.io --wpthost localhost --graphite.host localhost --graphite.port 2003  --graphite.httpPort 8080 -- graphite.namespace testing.wpt.v1 -n 1 -b chrome https://www.sitespeed.io/`

I am able to see graph on grafana but after few 3-4 tests some data will disappear or gets average of 2 tests not sure why and how to run multiple url  using file?

**Comment by soulgalore** [comment]
Hi @iamlohith Graphite is a little special in how it stores the data: to make sure it not exceeds it limits you need to decide before you start how often you will store the data.  Start by reading https://www.sitespeed.io/documentation/sitespeed.io/graphite/#configure-graphite and https://github.com/statsd/statsd/blob/master/docs/graphite.md to get a feeling for how it works.
