### ISSUE TITLE
Security warnings when running npm install

### ISSUE THREAD

**Issue by barryperez** [sitespeedio/sitespeed.io#3455]
Good evening!

I'm trying to build a Docker image for SiteSpeed.io to be internally hosted (client security requirement). In doing so, I've run into some issues during security scans on the resultant container.

There are a number of HIGH severity issues which impact downstream tar dependency required by SiteSpeed (dependency browsertime > @sitespeed.io/geckodriver > tar) version being used. Please find attached.

[tar-issues.txt](https://github.com/sitespeedio/sitespeed.io/files/7112069/tar-issues.txt)

I was able to reproduce locally by cloning the repo on a fresh Ubuntu 20.0.4 installation and then running "npm install" / "npm audit"

To fix, the version of tar dependency needs upgrading to at least 6.1.9.

Hope this helps - I have very limited knowledge of the project and nodejs in general, so I'm not able to contribute at this time.

**Comment by soulgalore** [comment]
Hi @barryperez you can try the new 19.4.1 where it should be fixed.

**Comment by barryperez** [comment]
Hello @soulgalore - thank you so much for this! I can see now that the tar issue has been fixed.

There's something else flagged subsequently, which is more to do with some Ubuntu 20.0.4 libraries, but I'll raise a separate issue for that with the full details.
