### ISSUE TITLE
This is not an issue but an approach for running sitespeed.io using  k8s and Helm

### ISSUE THREAD

**Issue by SriramIyengar2012** [sitespeedio/sitespeed.io#3458]
Hi All,

Sitespeed.io has been a great project that I have been using for web performance monitoring, it runs outbox in docker as per the documentation. but places, where application access is only restricted to k8s namespaces, below approach, might help us run the same module in k8s:

**(for Testing Url)**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitespeed-io-deployment
  labels:
    app: sitespeed-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitespeed-io
  template:
    metadata:
      labels:
        app: sitespeed-io
    spec:
      containers:
      - name: sitespeed-io
        image: gcr.io/scenic-lane-325608/sitespeed.io/sitespeed.io:latest
        command: ["/bin/sh"]
        args: ["-c", "/usr/src/app/bin/sitespeed.js -b chrome {url}"]
        ports:
        - containerPort: 80 (this is not required, just had it)

**(for Testing user Journey using scripts)**
Build a docker file with with below contents
 **From sitespeed.io:latest
Copy / /**

refer the above docker file in k8s deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitespeed-io-deployment
  labels:
    app: sitespeed-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitespeed-io
  template:
    metadata:
      labels:
        app: sitespeed-io
    spec:
      containers:
      - name: sitespeed-io
        image: sitespeed.io/sitespeed.io:latest
        command: ["/bin/sh"]
        args: ["-c", "/usr/src/app/bin/sitespeed.js -b chrome /tests/test.js --multi"]
        ports:
        - containerPort: 80 (optional)

Scripts names and URLs used can also be parameterized and tests using Helm charts
Reports can be viewed in Jenkins using publish Html Report plugin

I did not know how to share so sharing this as an issue here

Hope this helps people who are trying out something similar

:-)

**Comment by soulgalore** [comment]
Hi @SriramIyengar2012 thanks for sharing, if you have time, could you do a PR to the docs, add a new section under https://github.com/sitespeedio/sitespeed.io/edit/main/docs/documentation/sitespeed.io/docker/index.md 

Thanks again!
Peter

**Comment by SriramIyengar2012** [comment]
sure @soulgalore will raise a PR request this week for the same, thank you
