### ISSUE TITLE
Map the configured metrics to the measurement on InfluxDB

### ISSUE THREAD

**Issue by zzhao2010** [sitespeedio/sitespeed.io#3459]
Hi,
I was testing to feed specific sitespeed.io metrics to InfluxDB. Could anyone help me understand how do I map the configured metrics to the measurement on InfluxDB?  
For example, I was using the default metric filter, and attached is the list of configured metrics [FilterMetricList.txt](https://github.com/sitespeedio/sitespeed.io/files/7155797/FilterMetricList.txt). 
And on InfluxDB side, I see there were bunch of measurements created based on the configured metrics. I wanted to understand which specific metric created the corresponding measurement so that I can figure out what metrics I can filter out further instead of sending them all to InfluxDB.. Like the last measurement below "first-contenful-paint", I thought it came from browsertime.pageSummary.statistics.timings.timeToContentfulPaint, but it was not... Because I tested to send this metric ONLY to influxdb and there was no measurement created.

name: measurements
name
----
FirstMeaningfulPaint
FirstVisualChange
JSHeapTotalSize
JSHeapUsedSize
LastVisualChange
Layout
O7jPNb
ParseHTML
RecalcStyleCount
RunTask
SpeedIndex
UpdateLayoutTree
V8_Execute
V8_HandleInterrupts
V8_RunMicrotasks
VisualComplete85
VisualComplete95
VisualComplete99
VisualReadiness
backEndTime
connectStart
cpuBenchmark
cumulativeLayoutShift
domComplete
domContentLoadedEventEnd
domContentLoadedEventStart
domContentLoadedTime
domElements
domInteractive
domInteractiveTime
domainLookupEnd
domainLookupStart
domainLookupTime
duration
durations
errors
fetchStart
**first-contentful-paint**
...

**Comment by soulgalore** [comment]
Ah sorry we do not have any docs for that today, I mainly focus on the Graphite metrics. Here's description of the main metrics we collect https://www.sitespeed.io/documentation/sitespeed.io/metrics/
