### ISSUE TITLE
json config - multiple headers in config not being respected

### ISSUE THREAD

**Issue by barryperez** [sitespeedio/sitespeed.io#3460]
Hi,

I noticed some unexpected behaviour (to me!) when attempting to add more than one header in a json config:

Firstly, I added multiple headers in a json config for a site, as follows:

```
 "browsertime": {
    "requestheader": "a:1",
    "requestheader": "b:2",
    "requestheader": "c:3"
  },
```

I saw some unexpected result, so I ran Sitespeed with -vvv and looked at the chromedriver.log which was generated. I could see that only the last header was being added to the request:

```
   "request": { "headers": {
         "c": "3",
      },
```

It appears that when the config is parsed, if there are multiple elements with the same name, only the last one ends up getting processed.

The same test works fine if I add multiple --header options from the command line, however I'm trying to drive all my tests via json file, as opposed to having to pass a lot of additional command line parameters.

**Comment by soulgalore** [comment]
Hi @barryperez sorry I think I've missed that part in the docs. I added it now (scroll down): https://www.sitespeed.io/documentation/sitespeed.io/configuration/#configuration-as-json

We use yargs as a cli/json parser and when you have multiple values, it need to be an array. So your example should be:
```
 "browsertime": {
    "requestheader": ["a:1", "b:2", "c:3"]
  },
```

**Comment by barryperez** [comment]
Hi @soulgalore - thanks for this. I did wonder if it might be covered already!

Also, really graet work updating the doc so quickly - I'm sure it'll help others too!
