### ISSUE TITLE
Catchpoint blog migration

### ISSUE THREAD

**Issue by doffymingozzz** [sitespeedio/sitespeed.io#3461]
Hi!

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following pages: 
https://www.sitespeed.io/documentation/sitespeed.io/mobile-phones/
I wonder if you’d be able to replace it with the new one:
https://www.catchpoint.com/blog/m1-mac-mini-mobile-device-testing
Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up!

Best, 
Gleb

**Comment by soulgalore** [comment]
Hi Gleb, 
thanks, I fixed it with #3461.

Best
Peter
