### ISSUE TITLE
Possibility of updating Grafana Dashboard variables via source control

### ISSUE THREAD

**Issue by jsbalasu** [sitespeedio/sitespeed.io#3463]
Hi @soulgalore ,
We have Grafana Dashboards up and running and we used default docker images [used from https://github.com/sitespeedio/grafana-bootstrap-docker] to get remade custom dashboards.

**Major Requirement:**
We have requirement to add `All` option in Grafana LeaderBoard under testname and we are looking for possibility to add it via source code directly.Please let us know if this is feasible by passing values for `multi-value` and `include All option` in `testname` variable via some methods using source code. thanks.

On the other hand we tried the below options

**Working as expected:**
We aware manual updating the settings `multi-value` and `include All option` in `testname` variable and create a new dashboard copy works as expected.We ensure the respective values are getting updated to json model.

<img width="285" alt="Screenshot 2021-09-21 at 2 15 29 PM" src="https://user-images.githubusercontent.com/28977436/134183822-a66efb0b-f6d8-4e62-8b48-71da64b01062.png">

<img width="365" alt="Screenshot 2021-09-20 at 6 20 05 PM" src="https://user-images.githubusercontent.com/28977436/134183968-8433f086-a90c-412e-8712-2948cb5b9e08.png">

**Not working as expected:**
When we update the variable with above settings and save dashboard, it shows the option for sometime but gets reverted to earlier stage in dashboard or works abnormally for some reasons though it got saved in json model. Can you confirm Why?

**Comment by soulgalore** [comment]
Hi @jsbalasu 

> When we update the variable with above settings and save dashboard, 

How do you add the dashboards, do you have the Docker container in a Docker compose file? If that's the case, then I think the dashboards are inserted again when you restart compose (=your change is over written).

**Comment by jsbalasu** [comment]
Hi @soulgalore ,
yes we have docker container created out of yaml file [we segregated and running it in Openshift].
Is there a hack around apart from altering the values and save it as New Dashboard copy [which works as expected]?

**Comment by jsbalasu** [comment]
To be precise is it ok to enable these values as true for `testname` by default bu you on https://github.com/sitespeedio/grafana-bootstrap-docker/blob/44c3bb4659be3951aca4fe54dd24f38421c50c82/dashboards/graphite/Leaderboard.json#L3023 and https://github.com/sitespeedio/grafana-bootstrap-docker/blob/44c3bb4659be3951aca4fe54dd24f38421c50c82/dashboards/graphite/Leaderboard.json#L3025 so it will have All options with multi select as default as like `domains` and `pages`.

Let me know how I can set this values by default for my project [which uses the docker image grafana/grafana:8.0.3] if not can be done in the production image.

**Comment by soulgalore** [comment]
Hi @jsbalasu sorry for not responding earlier. I think the best way for you (and others) is not to run the Docker image with the dashboards in production because that way you cannot add your own changes (as you seen) and I think the real beauty with Grafana and the pre made dashboards is that they are just examples, so you can use them as a base and then remove/add/change what you need so it fits your organisation/company.

First make sure that you store the Grafana dashboards outside of the container (or somewhere so you can backup them). They are stored in the Grafana database. Then make your change, save. Then restart the services again and verify that it works. If you have a larger setup checkout https://grafana.com/docs/grafana/latest/best-practices/dashboard-management-maturity-levels/.

**Comment by jsbalasu** [comment]
Hello @soulgalore thanks for the update.Yeah we planned to store the dashboards [which required changes] outside of container to achieve and injecting to container using configmap [as we are running in Openshift].I will revert if we come across any further issues.Thanks again.

**Comment by soulgalore** [comment]
@jsbalasu log into Grafana and edit the dashboards: https://grafana.com/docs/grafana/latest/dashboards/ and https://grafana.com/docs/grafana/latest/panels/panel-editor/

**Comment by soulgalore** [comment]
@jsbalasu that is coming form the internal datastructure of metrics in sitespeed.io. You can use https://www.sitespeed.io/documentation/sitespeed.io/configure-metrics/#list-metrics to see all the metrics and structure used by a specific test.
