### ISSUE TITLE
How to log in before crawling

### ISSUE THREAD

**Issue by siriak** [sitespeedio/sitespeed.io#3464]
I'm testing an app that requires logging in through an SSO. I made it work by logging in with login/password in preStart script and it works. It doesn't see other pages though. From what I've read, crawling is done before the preStart script is run, so it just can't log in to crawl. What can I do? I can log in as in preStart script with login/password or I also can put a pre-baked JWT in local storage directly (theoretically, yes, but I haven't figured out how to do that with Selenium because chrome devtools protocol complains about missing frame or something like that). Please advise, thanks!

**Comment by soulgalore** [comment]
Hi @siriak there's no ready made solution for that right now, only workarounds that maybe will work, not sure.  It works like this: the crawling uses https://www.npmjs.com/package/simplecrawler to crawl, so it doesn't use a browser or the same session as the actual test. The simplecrawl supports cookies/adding request headers, so maybe we could add that to the cli so you can set that (if that would help you get through the SSO). 

Else I would use another crawler (if there's any) to crawl and just store the URLs to a text file as a first step and then feed them and use a prescript. Would that work for you?

**Comment by siriak** [comment]
Cookies and request headers won't help because we have a single-page app and it looks for a JWT stored in local storage. If it's missing, the user isn't authenticated. Could you recommend a crawler that I can use to scrape only URLs? I'd like to do that automatically in the Jenkins pipeline before running sitespeedio. If that doesn't work, I guess, my best option is just to use a maintained by hand text file.

**Comment by siriak** [comment]
Gotta go now, will get back and read your reply in ~9 hours, thanks :)

**Comment by siriak** [comment]
Thanks for your help, I'll stick to using a hand-made list of URLs. This should serve the purpose for now.
