### ISSUE TITLE
Not able to generate report with multiple tab

### ISSUE THREAD

**Issue by KesavanGurusamy** [sitespeedio/sitespeed.io#3465]
On clicking a button is opening a new tab in the browser. While generating report, we are getting error as 
Could not generate url/summary/index

![image](https://user-images.githubusercontent.com/91149850/134218224-2e738ab9-3ee7-4b5f-8504-b99d3078e812.png)

**Comment by soulgalore** [comment]
Hi @KesavanGurusamy I think one of the limits today is that we can only measure things in one tab, but I'm not exactly sure what happens, can you share the use case so I can try? 

Best
Peter

**Comment by KesavanGurusamy** [comment]
> Hi @KesavanGurusamy I think one of the limits today is that we can only measure things in one tab, but I'm not exactly sure what happens, can you share the use case so I can try?
> 
> Best
> Peter

Hi @Peter,
We have a scenario like , clicking a button or link in current screen will open new tab in browser and in the new tab we have additional steps to continue.

We are able to execute script successfully by using the below code snipped, but while generating report we are getting the error message as mentioned above.

await command.click.byXpathAndWait("//*[@id='XXXXX']");
		await command.switch.toWindow(parentHandle);
		context.log.info('Switched to parentHandle');
		const winHandles = await driver.getAllWindowHandles();
		await command.switch.toWindow(winHandles[1]);
                context.log.info(winHandles.toString());

Thanks & Regards
Kesavan

**Comment by KesavanGurusamy** [comment]
> > Hi @KesavanGurusamy I think one of the limits today is that we can only measure things in one tab, but I'm not exactly sure what happens, can you share the use case so I can try?
> > Best
> > Peter
> 
> Hi @peter,
> We have a scenario like , clicking a button or link in current screen will open new tab in browser and in the new tab we have additional steps to continue.
> 
> We are able to execute script successfully by using the below code snipped, but while generating report we are getting the error message as mentioned above.
> 
> await command.click.byXpathAndWait("//*[@id='XXXXX']");
> await command.switch.toWindow(parentHandle);
> context.log.info('Switched to parentHandle');
> const winHandles = await driver.getAllWindowHandles();
> await command.switch.toWindow(winHandles[1]);
> context.log.info(winHandles.toString());
> 
> Thanks & Regards
> Kesavan

Hi @soulgalore ,
Kindly let me know do we have any workaround for this issue to proceed.

Thanks & Regards
G.Kesavan

**Comment by soulgalore** [comment]
As I said most things work in one tab for Chrome. If you try Firefox does it work there? Also if you could share a [reproducible test case](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue) that is super helpful, then I can have a look. Thanks!

**Comment by moulaligithub** [comment]
Is there any new workaround to handle multiple windows/tabs for report generation.
