### ISSUE TITLE
Not able to get Sitespeed.io not loading pages correctly 

### ISSUE THREAD

**Issue by kaurav1108** [sitespeedio/sitespeed.io#3469]
Hi Team,
sitespeed.io docker container is not able to load the endpoint URL properly, as every page getting this error.

so is there any change into image version.

please find the below details for more information

 docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://flow.telefonica.de/login.jsp?nosso --preScript /sitespeed.io/loginProd.js --browsertime.iterations=1 --graphite.host 10..X.X.X--graphite.port 2005 --graphite.namespace sitespeed.baseline.systemdashboard --net=host
Google Chrome 70.0.3538.67
Mozilla Firefox 63.0
[2021-09-30 09:32:32] INFO: Versions OS: linux 3.10.0-862.14.4.el7.x86_64 nodejs: v8.12.0 sitespeed.io: 7.7.2 browsertime: 3.11.1 coach: 2.4.0
[2021-09-30 09:32:32] INFO: Starting chrome for analysing https://flow.telefonica.de/login.jsp?nosso 1 time(s)
[2021-09-30 09:32:32] INFO: Testing url https://flow.telefonica.de/login.jsp?nosso iteration 1
**[2021-09-30 09:34:41] ERROR: NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="login-form-username"]"}**
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 3.10.0-862.14.4.el7.x86_64 x86_64)
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 3.10.0-862.14.4.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:546:15)

**Comment by soulgalore** [comment]
Hi @kaurav1108 that means that your script `loginProd.js ` tries to find an element by id with id `login-form-username`.  You can follow our guide https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug to debug your scripting.
