### ISSUE TITLE
Execution support to Elasticsearch OR flat JSON file

### ISSUE THREAD

**Issue by ganeshcpote** [sitespeedio/sitespeed.io#3481]
Hello Team,

Is there any support for Elasticsearch or flat JSON as datastore as an alternate to InfluxDB or Graphite DB. 

Thanks,
Ganesh Pote

**Comment by soulgalore** [comment]
Hi @ganeshcpote there's no pre built plugin for Elastic. All data collected is passed in queue that plugins use to get the data see https://www.sitespeed.io/documentation/sitespeed.io/plugins/ so it would be possible to build a plugin for that. I can guide  you if you need help.

Best
Peter
