### ISSUE TITLE
visualElements in scripts for different pages

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3489]
Hello, 

Please shed some light on if this parameter --browsertime.scriptInput.visualElements works with a scripted scenario approach.
I mean is it possible to specify selectors of different pages' elements at the start command.

**Comment by soulgalore** [comment]
Hi @Icecold777 I think the best way is to annotate your elements with elementtiming instead if they change between different pages checkout https://www.sitespeed.io/documentation/sitespeed.io/video/#collect-visual-elements-metrics. Having different/multiple querySelectors per page seems complicated.

**Comment by Icecold777** [comment]
got it. thanks @soulgalore
