### ISSUE TITLE
Open test result page after test run

### ISSUE THREAD

**Issue by zhouhana** [sitespeedio/sitespeed.io#3492]
Another thing that would make it easier for newbies to understand where to see the test result would be if after the test is run the result opened in the browser. At least on macOS, the terminal command `open <path to HTML file>` would open the page in the default browser.

**Comment by soulgalore** [comment]
This was release some time ago, thanks for sharing the idea, I use it all the time now :)

**Comment by zhouhana** [comment]
Awesome! 🙂  Thanks for the update!
