### ISSUE TITLE
graphite cannot receive sitespeed data

### ISSUE THREAD

**Issue by heavenmyth** [sitespeedio/sitespeed.io#3504]
graphite cannot receive sitespeed data

There is no error in the sitespeed execution log
![image](https://user-images.githubusercontent.com/26155539/140316790-3a707da7-57e9-48a2-855a-33d1b410322c.png)

Carbon did not receive performance indicator data
![image](https://user-images.githubusercontent.com/26155539/140317222-52e93bf7-1679-4370-84ae-c681f8eb4229.png)

I don't know where the problem is。

**Comment by soulgalore** [comment]
Hi @heavenmyth I need to add FAQ on how to debug, let me do that the coming days. For now checkout https://github.com/sitespeedio/sitespeed.io/issues/3094#issuecomment-662106784

**Comment by soulgalore** [comment]
Hope you got this working, please re-open if this is still an issue.
