### ISSUE TITLE
Unable to install plugin at runtime

### ISSUE THREAD

**Issue by barryperez** [sitespeedio/sitespeed.io#3509]
Hi!

I'm trying to load the WPT plugin at runtime, following the instructions on the site.

- I've cloned the WPT plugin repo into /sitespeedio/plugins/wpt

- I then try to run as follows (mapping the /sitespeedio folder in):

**docker run --rm -v /sitespeedio:/sitespeed.io:Z sitespeedio/sitespeedio:19.4.1 --plugins.add /sitespeed.io/plugins/wpt**

The following error occurs. Note that the error suggests that we're trying to look in /usr/src/app/lib/plugins/{plugin path}.

Couldn't load plugin /sitespeed.io/plugins/wpt: Error: Cannot find module '/usr/src/app/lib/plugins/sitespeed.io/plugins/wpt'
Require stack:
- /usr/src/app/lib/core/pluginLoader.js
- /usr/src/app/lib/sitespeed.js
- /usr/src/app/bin/sitespeed.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.loadPlugins (/usr/src/app/lib/core/pluginLoader.js:53:24)
    at Object.run (/usr/src/app/lib/sitespeed.js:116:41)
    at async run (/usr/src/app/bin/sitespeed.js:14:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [Array]

I tried changing the plugins.add parameter to "../../../../../sitespeed.io/plugins/wpt", and then got a slightly different error "Couldn't load plugin ../../../../../sitespeed.io/plugins/wpt: Error: Cannot find module 'lodash.clonedeep'"

Appreciate any assistance on this! I'm pretty sure I've followed the documentation related to installing a plugin.

Thanks in advance!
Barry

**Comment by soulgalore** [comment]
Hi @barryperez thanks for filing the issue, yep the docs (https://www.sitespeed.io/documentation/sitespeed.io/plugins/#mount-your-plugin-in-docker)  looks wrong or its a bug, let me have a go tonight and see what's wrong.

**Comment by soulgalore** [comment]
Are you sure you got everything right in your mapping for Docker and the names etc, the example doesn't look copy/pasted?
When I tried it works for me, I did it like this (trying to mimic your example):

```
$ cd
$ mkdir test
$ cd test
$ git clone git@github.com:sitespeedio/plugin-webpagetest.git
$ cd plugin-webpagetest
$ npm install
$ pwd
$ /Users/peter/test/plugin-webpagetest
$ docker run --rm -v /Users/peter/:/sitespeed.io sitespeedio/sitespeed.io --plugins.add /sitespeed.io/test/plugin-webpagetest/ https://www.sitespeed.io
```

**Comment by barryperez** [comment]
Hello @soulgalore - apologies, it was my incorrect usage here - I hadn't run "npm install" - although it wasn't clear that was the problem from the error.

**Comment by soulgalore** [comment]
Np, glad that it works!
