### ISSUE TITLE
Graphite does not work when env variable set

### ISSUE THREAD

**Issue by Behoston** [sitespeedio/sitespeed.io#3511]
```yaml

  sitespeed:
    image: sitespeedio/sitespeed.io:20.6.0
#    environment:
#      - SITESPEED_IO_graphite.host=graphite
    networks:
      - default
    depends_on:
      - graphite

```

When `SITESPEED_IO_graphite.host` set, sitespeed saves only html reports. I thought it will be sending data to graphite when variable is set, but it's not a main problem.

When CLI argument  --graphite.host=graphite, it will try to connect to graphite, but it tries to connect to 127.0.0.1 (but debug message says that data will be sent to graphite host, but error tells that connection is refused by 127.0.0.1)

log:

```
[2021-11-19 12:22:49] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite <***internal docker IP***>,graphite:2003
[2021-11-19 12:22:49] ERROR: [sitespeedio.queuehandler] Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

**Comment by soulgalore** [comment]
Hi @Behoston thanks for filing the issue.
When the plugin starts, there should be a debug message like 
`Setting up Graphite %s:%s for namespace %s`. what values do you get in that case?

When you use _- SITESPEED_IO_graphite.host=graphite_ I wonder if that is the correct path? If it would I think you should get send messages. For the cli, if I look at the code it looks like your parameter graphite is evaluated to `<***internal docker IP***>,graphite` is that how it works in Docker compose when you setup dependencies, I haven't used that so much.
