### ISSUE TITLE
Execute sitespeed in gitlab, the -d parameter is invalid

### ISSUE THREAD

**Issue by heavenmyth** [sitespeedio/sitespeed.io#3521]

**Comment by heavenmyth** [comment]
![image](https://user-images.githubusercontent.com/26155539/145149436-dd08d4e3-5e0c-450f-b998-90882aa2bcd8.png)

**Comment by soulgalore** [comment]
Hi @heavenmyth I don't follow, could you please help me by following https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ 

Thanks!

**Comment by soulgalore** [comment]
Also please report GitLab issues to. ... GitLab :)
