### ISSUE TITLE
[HELP] multi browser support and ramps users

### ISSUE THREAD

**Issue by RollerIn** [sitespeedio/sitespeed.io#3524]
Hello,
can you please let me know ,will this framework supports

scope : desktop ? or includes mobile browsers?

scenarios: login to application—> traverse to multi pages like searching page, order page, …can we implement these kind of scenarios 

Thanks

**Comment by soulgalore** [comment]
Hi @RollerIn 
for scenarions its easiest if you use https://www.sitespeed.io/documentation/sitespeed.io/scripting/ and then if you need you can combine that with Selenium NodeJS browser. That will work for all browsers that sitespeed.io supports. Safari on iOS do not support video at the moment, for the rest of the browsers everything should work.

**Comment by RollerIn** [comment]
Thank you @soulgalore ,I will try and let you know

**Comment by soulgalore** [comment]
Think this works now so closing, please let me know if that's not the issue.
