### ISSUE TITLE
Select value from a html <option> dropdown list

### ISSUE THREAD

**Issue by shawneenc** [sitespeedio/sitespeed.io#3533]
Hi,

How can i select an option from a dropdown list.  Have tried many things with regards, it is not possible using sitespeed.io commands directly (i.e. .click() on the options locator) and I cannot find a way to import the 'Select' library from selenium to use that code directly.

Have followed the guidelines on using selenium-webdriver with sitespeed.io, but it looks like the 'Select' command is not available for use : https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Capabilities.html.  I obtained this information from this issue : https://github.com/sitespeedio/sitespeed.io/issues/2119

Have tried using javascript directly by using var document = webdriver.document; and this does not work

(Just to note that the select works directly from selenium using  'Select', like so: 
wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//select[@id='value']"))).click();
Select value = new Select (driver.findElement(By.id("value")));
value.selectByIndex(11);)

HTML Code snippet:
![image](https://user-images.githubusercontent.com/55998417/150115466-3a57f606-9264-4136-84b5-17b3bd8b0640.png)

Dropdown list, as displayed within the app:
![image](https://user-images.githubusercontent.com/55998417/150115737-e8a1bb95-b4ed-4220-aee3-eb3485a4dad7.png)

I have been stuck on this issue at work for quite sometime, please help and advise?

**Comment by soulgalore** [comment]
Hi @shawneenc I usually follow https://www.sitespeed.io/documentation/sitespeed.io/scripting/#finding-the-right-element to find the elect and then click by xpath. In one of our current tests we do that with our Grafana instance checkout https://github.com/sitespeedio/dashboard.sitespeed.io/blob/main/tests/desktop/spa.js

**Comment by shawneenc** [comment]
Hi soulgalore,

I have tried every locator possible with .click(), full xpath, rel xpath, id, selector, etc.  None are recognised and that specific command is ignored.  I also tried all the locators with the code from here : https://github.com/sitespeedio/dashboard.sitespeed.io/blob/main/tests/desktop/spa.js: 
 
```
await commands.measure.start('pageTimingMetrics30Days');
  try {
    await commands.click.byXpathAndWait(
      '/html/body/div/div/main/div[3]/header/div/div[4]/div/div[1]/section/div/div[1]/div[1]/div[2]/div[1]/ul/li[11]/label'
    );
    await commands.wait.byTime(5000);
  } catch (e) {
    context.log.error('Could not find Grafanas 30 days dropdown');
    throw e;
  }  
```

No joy

I can select the parent field for the dropdown and expand it, but am not able to select any of the options in the list :-( 

Is there any way that we can use the 'Select' command from selenium-webdriver in sitespeed.io?  This is a very basic function/command

**Comment by soulgalore** [comment]
Can try with just running JavaScript directly (https://www.sitespeed.io/documentation/sitespeed.io/scripting/#jsrunjavascript)?

For example if I go to:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select - the id of the select is _cars_.

I can change/choose the dropdown with `document.getElementById("cars").value = "saab";`

**Comment by shawneenc** [comment]
I have tried using javascript directly with document.  - I had many errors on trying to set this up to run properly.

Can you let me know the code to insert to run this within my script?  I.e. the command that will actually allow me to use and import document. ?

**Comment by soulgalore** [comment]
If you run `commands.js.run('window,document.getElementById("cars").value = "saab"'); ` that will run directly in the browser, so that document should be defined.

**Comment by shawneenc** [comment]
Thanks @soulgalore, I can see that this is navigated to, but not actually selected the option I require.  When I perform the next action, it switches back to the default selection.  How can I actually select this option when I have navigated to it?

**Comment by shawneenc** [comment]
Hi @soulgalore,

Do you have any other suggestions?  Is there any way to import the library and use the 'Select' command from selenium-webdriver

**Comment by soulgalore** [comment]
Hi @shawneenc you can use https://www.sitespeed.io/documentation/sitespeed.io/scripting/#use-selenium-directly. I haven't used "Select"-command can you share a link to it in the docs, I cannot find it in https://www.selenium.dev/selenium/docs/api/javascript/ ?

**Comment by shawneenc** [comment]
Hi @soulgalore,

I have gone through those links last week, not useful, or helpful.  From here (https://www.selenium.dev/selenium/docs/api/javascript/) there is no command available to use 'Select' from the selenium-webdriver libraries.  Just to confirm from sitespeed's point of view, there is no way to complete what I am trying to do?

**Comment by soulgalore** [comment]
Hi @shawneenc that second link I shared is from Selenium, that's why I asked you to show me the 'Select' command so I can help you how to use it? If you can do that please, I can show you how to import/use it.

> Just to confirm from sitespeed's point of view, there is no way to complete what I am trying to do?

Most is doable with straight JavaScript or Selenium, but its hard to help you if I don't have a full working example following https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue if you can share that so I can run the code locally, then I can have a look.

**Comment by shawneenc** [comment]
Apologies @soulgalore ,

The following is the selenium-webdriver code that works (I have run this code):

	  ```
      wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//select[@id='val']"))).click();
      Select value = new Select (driver.findElement(By.id("val")));
      value.selectByIndex(11);
```
This is the library used to import 'Select' for selenium-webdriver: import org.openqa.selenium.support.ui.Select;

I have shared the code i am running in a previous comment.  Here it is again, please note that I cannot provide details from my company's system, i.e. login details, or actual locator Id's.  This example is using javascript to try and select from the dropdown :
```

```
 //const LOGIN_NAME = context.options.login
 const PASSWORD = 'val'
 const webdriver = context.selenium.webdriver;
 const driver = context.selenium.driver;
 await commands.navigate('url');
  
 try {

   // Login to Homepage
   await commands.addText.byId('val2', 'loginName');
   const nextButton = '//div/button[.="Next"]';
   await commands.wait.byXpath(nextButton,10000);
   await commands.click.byXpath(nextButton);
   await commands.wait.byId('password',10000);
   await commands.addText.byId(PASSWORD, 'password');

   await commands.measure.start('login');
   await commands.click.byXpathAndWait('//button');
   await commands.measure.stop();
            
             // TEST
             await commands.click.byXpathAndWait('LINK', 20000); 
             await commands.measure.start("TEST 1");
             await commands.click.byXpathAndWait('xpath');

             const filter = await driver.findElement(webdriver.By.xpath('//select[@id="filt xpath"]'));
             await filter.click();
             
             commands.js.run('window,document.getElementById("filt xpath").value = "value"');

  } catch (e) {
    context.log.error(e);
    return commands.measure.stop();
    // We try/catch so we will catch if the the input fields can't be found
    // The error is automatically logged in Browsertime and re-thrown here
  }
};
```

**Comment by soulgalore** [comment]
Ah I see, it's implemented in the Java flavour but not for JavaScript/NodeJs version of Selenium.

I think in pure JavaScript this would work:
```
await commands.js.run("const el = document.getElementById('YOUR_SELECT_ID'); el.value = 'YOUR_VALUE'; el.dispatchEvent(new Event('change'));");
```

**Comment by soulgalore** [comment]
If this works I can add a command for it in sitespeed.io to make it easier to use.

**Comment by shawneenc** [comment]
Hi @soulgalore ,

Unfortunately that doesn't work :-(.  It does not make the selection on the value I have asked for.  

I will go away and try to figure out another work around

**Comment by soulgalore** [comment]
@shawneenc can you share a simplified HTML page of your use case that fail when you test? When I tested the code on my tests it worked, so it's  something that differs.

**Comment by shawneenc** [comment]
Hi @soulgalore,

Here is the HTML code:
![image](https://user-images.githubusercontent.com/55998417/150545646-3628b247-0283-4d7f-8dc3-baae3f2175b5.png)

**Comment by shawneenc** [comment]
Hi @soulgalore ,

Here is the HTML code:
![image](https://user-images.githubusercontent.com/55998417/150545824-7cacf9d9-7da9-4618-be92-aab397505c72.png)

**Comment by shawneenc** [comment]
When a user navigates to the page I am testing, the dropdown has a default value set within it, a user has to manually expand the dropdown and select another value to change it.

When I run the code and watch it, I can see that it hovers over the selection I want, **but it doesn't actually select, or click on it.**  When the next action is performed within the code, i.e. clicking on a different field, the dropdown value returns to its default value

**Comment by soulgalore** [comment]
Hmm, I did a simple test and it work for me. I have a select that looks like this:

```
<form>
<select id="testType" name="testType">
<option value="desktop">desktop</option>
<option value="emulated mobile">emulated mobile</option>
<option value="android">android</option>
<option value="ios">ios</option>
</select>
</form>
```

I serve the page locally and run a script like this (just to see that the values changes):

```
module.exports = async function (context, commands) {
  await commands.navigate('http://127.0.0.1:3000');
  await commands.js.run(
    `const select = window.document.querySelector("select[name='testType']"); select.selectedIndex=3;select.dispatchEvent(new Event('change'));`
  );
  // extra wait to see that it kicks in
  await commands.wait.byTime(1000);
  await commands.js.run(
    `const select = document.getElementById('testType'); select.value = 'android'; select.dispatchEvent(new Event('change'));`
  );
  await commands.wait.byTime(1000);
};

```

**Comment by shawneenc** [comment]
Hi @soulgalore ,

Are you performing another action after the select?  Also does the dropdown you are working with have a default value?  

You need to run your code against a dropdown list that has a default value in place, then you need to select a different value.  You then need to perform another action on the page, i.e. by select another element on the page.  Then verify that the default value has not been returned to - which is happening with me

**Comment by soulgalore** [comment]
Yes it all works for me. Maybe you have some JavaScript that runs on the site that changes it back? If you could share a full example that I can run locally where it do not work, then I can help you fix it.

**Comment by shawneenc** [comment]
Hi @soulgalore ,

I have found a method that works, it is navigating to each report, setting the values at the end of the URL, like : 
'https://my-url-dev.com/val/rep/report-type?start=2021-05-03&end=2021-08-05&preset=presetCustom'.  I have done this once with 1 report, setting the full url once at the start of the script.  The problem is that there are 19 reports.
 
Would need to iterate through each of the reports within 1 script.  Is there any way that I can get the current url on each report and append/add the value to the url as I hit each report within the script and navigate to that?  For example:

```
const url = 'https://my-url-dev.com';  // set url to open application at login page
await commands.navigate(url);    // runs at the start of the script to navigate to the url
code inserted here to login to the application and navigate to report section;

code required to get current url for each report opened
const repVals = '?start=2021-05-03&end=2021-08-05&preset=presetCustom'; // when each report has been open, how do I append this value to the url grabbed from previous step ???
```
