### ISSUE TITLE
The ChromeDriver could not be found

### ISSUE THREAD

**Issue by YuriyGuminskiy** [sitespeedio/sitespeed.io#3534]
Hello everyone!
I ran into the situation when after start of tests from console with node I see the next message "The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH". I downloaded  chromedriver.exe for my version of Chrome (Version 97.0.4692.71 (Official Build) (64-bit)) and replace old file, but the problem doesn't solve.
I'm using a separated version 21.5.0 of sitespeed (not from docker). Under there are screens.
![1](https://user-images.githubusercontent.com/79785579/150120213-f60670d9-fc2c-4358-8161-915f31efa478.jpg)
![2](https://user-images.githubusercontent.com/79785579/150119796-d97846e6-a4ea-462a-b7e2-d02856d3c8b5.jpg)
<img width="370" alt="image" src="https://user-images.githubusercontent.com/79785579/150119724-c3832f97-a1c2-4979-886b-080f1a5134a0.png">

**Comment by soulgalore** [comment]
Hi @YuriyGuminskiy hmm Chromedriver should be downloaded automatically when you run `npm install`, did you see anything in the install log?

You can try to point out the Chromedriver directly using: `--browsertime.chrome.chromedriverPath` and then add the exact path to your downloaded version, hope that helps!

**Comment by YuriyGuminskiy** [comment]
> 

Hi @soulgalore! Your solving with directly exact path of chromedriver.exe is working. Thanks for the help!)))

But when I installed with "npm install" I don't remember something wrong in install logs. Maybe reinstalling will help me?

**Comment by soulgalore** [comment]
@YuriyGuminskiy if you have time and could try to reinstall and check the logs it would be great. Maybe there's a bug that needs to be fixed :)
