### ISSUE TITLE
The Cumulative Layout Shift doesn't follow Web Vitals limits. What limits does it use?

### ISSUE THREAD

**Issue by alexvolk001** [sitespeedio/sitespeed.io#3542]
Hi, 
I compared the Web Vitals limits and the results I'm getting in reports. I noticed that the Cumulative Layout Shift doesn't follow Web Vitals limits. What limits does it use? 
The google document says the way to calculate CLS was updated. 
It would be great to add more information on how the metrics are calculated to the metrics section on the website.

Thank you.

**Comment by soulgalore** [comment]
Hi @alexvolk001 I think I missed update the documentation the code was changed with the 5s limit in 17.8 https://github.com/sitespeedio/sitespeed.io/blob/main/CHANGELOG.md#1780---2021-06-04. Let me update the docs this weekend and thanks for the ping.
