### ISSUE TITLE
[Help Required] Is there a way to import Selenium Library in Sitespeed

### ISSUE THREAD

**Issue by vishallanke** [sitespeedio/sitespeed.io#3548]
### Your question

Is there a way to import Selenium Library in Sitespeed ?
Automation code working inside Selenium does not directly work in Sitespeed

**Comment by soulgalore** [comment]
Hi @vishallanke sitespeed.io needs to be in control of starting the browser, control the settings etc so using a pre-made Selenium script that runs directly with only Selenium will not work. 

Checkout the documentation https://www.sitespeed.io/documentation/sitespeed.io/scripting/#use-selenium-directly where we provide the driver and selenium driver object. Is that enough for you or do you need something else? Let me know if there's something else that it's needed and I can try to help out!
