### ISSUE TITLE
Integration with Grafana tempo via opentelemetry

### ISSUE THREAD

**Issue by Zapfmeister** [sitespeedio/sitespeed.io#3566]
### Your question

Hi,

i would love to get the waterfall charts shown here: [Compare](https://www.sitespeed.io/examples/#compare)
into Grafana, as shown on the bottom of the page here: https://grafana.com/blog/2021/04/13/how-to-send-traces-to-grafana-clouds-tempo-service-with-opentelemetry-collector/

This would allow to combine all the logs from the infrastructure hosting the page with the actual testing of the page from the web browser.

My understanding is that the data collected by sidespeed.io would need to be transformed into a format accepted by Grafana Tempo, like the opentelemetry one:
https://opentelemetry.io/docs/concepts/data-sources/

Do you think it is possible convert the data?
Im more than open to help with this as well. If you could give me some hints on where the tracing data is currently stored.

**Comment by soulgalore** [comment]
Closing but please let me know if you need any help with the plugin.
