### ISSUE TITLE
Kubernetes runAsNonRoot

### ISSUE THREAD

**Issue by ZazaKumar** [sitespeedio/sitespeed.io#3567]
### Your question

Is there a way to run sitespeed.io as non root user in k8s? I got a lot of problems with chroot in start.sh script

**Comment by soulgalore** [comment]
Hi @ZazaKumar no I think we need to do some refactoring of the setup for that to work. I haven't focus on getting it to work on k8 since there's no way to set connectivity speed.

**Comment by soulgalore** [comment]
I think using Kubernetes for performance tests is an anti-pattern so I will not spend any time right now fixing it.
