### ISSUE TITLE
junit stdOut undefined error

### ISSUE THREAD

**Issue by rghetu** [sitespeedio/sitespeed.io#3568]
### Feature/improvement

node_modules\sitespeed.io\lib\plugins\budget\junit.js

We get undefined in the junit xml reports in the standardOutput() section of the results.working / results.failing.

There is a "," that should be deleted

.failure(
              result.metric + ' is ' + result.friendlyValue || result.value,
              +' and limit ' + result.limitType + ' ' + result.friendlyLimit ||
              result.limit + ' ' + url

should be 

.failure(
              result.metric + ' is ' + result.friendlyValue || result.value
              +' and limit ' + result.limitType + ' ' + result.friendlyLimit ||
              result.limit + ' ' + url

Also we can add here the time here is my improved method : 

    if (results.working[url]) {
      for (const result of results.working[url]) {
        var timeValue = String(result.value);
        console.log(result.value);
        var timeParsed = timeValue.replace(" ms","");
        suite
          .testCase()
          .className(fineUrl)
          .name(url + '_' + result.type + '.' + result.metric)
            .time(parseInt(timeParsed)/1000)
          .standardOutput(
            result.metric + ' is ' + result.value
            +' and limit ' + result.limitType + ' ' + result.limit + ' ' + url
          );
      }
    }

**Comment by rghetu** [comment]
Cool , thanks a lot, the .time thing is a separate improvement and not a real problem , but if you use the generated xml in other places like datadog, jenkins publish junit etc you won't have the duration of the metric - of course in the metrics we can have milliseconds for pageLoadTime for example which need to be converted to seconds (junit has seconds) , but we also may have scores (integers) which make no sense as a time value - I will maybe add another improvement ticket with those if it is ok.

**Comment by soulgalore** [comment]
@rghetu I fixed the wrong  ",", if you can send PRs for your improvements that would be great!

**Comment by rghetu** [comment]
Sure will send them.
