### ISSUE TITLE
urlAlias in budget page in sitespeed.io report

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/sitespeed.io#3571]
### Feature/improvement

Currently in the Pages section of the HTML report the table has the URL as the urlAlias if a urlAlias was sent.

However in the Budget section of the HTML report the table has the actual URL instead of the urlAlias, regardless of whether one was provided. 

Can the Budget HTML report be updated to use the same format as the Pages HTML?

Thanks,

Shaq

**Comment by soulgalore** [comment]
Aha I though I fixed that but clearly not then. Let me fix that at the same time as #3570

**Comment by soulgalore** [comment]
Ooops this has been released but I missed adding it to the CHANGELOG.

**Comment by shaqb** [comment]
Nice one @soulgalore !
