### ISSUE TITLE
What is document complete equivalent in sitespeed?

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#3576]
### Your question

What is document complete equivalent in sitespeed

**Comment by soulgalore** [comment]
Hi @softwareklinic do you mean https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event ? https://www.sitespeed.io/documentation/sitespeed.io/metrics/#domcontentloadedtime
