### ISSUE TITLE
click.byXpathAndWait does not take to next page

### ISSUE THREAD

**Issue by myanees284** [sitespeedio/sitespeed.io#3588]
### Your question

Hello -
I am completely new to SiteSpeed scripting. My script does below steps:
1) Navigate to URL
2) Search for flight
3) Select the flights
4) Proceed to Passenger page

The first 3 steps works well. And the 4th step - I tried with -
a) click.bySelectorAndWait
b) click.byIdAndWait
c) click.byXpathAndWait

From the result I could see, the expected passenger page does not load; Rather the sitespeed script execution stop while moving to passenger page.
I even added wait for some element to appear in passenger page to verify the page is loaded. But the script throws error stating:  the element was not located
await commands.wait.byXpath('//*[@id="ctl00_c_ctPax1_txtFirstName"]',20000);
![Capture](https://user-images.githubusercontent.com/44027805/156362668-cd85f9f1-6b88-45bf-8f72-8d60c89711da.JPG)

[ss_flightsearch.txt](https://github.com/sitespeedio/sitespeed.io/files/8169587/ss_flightsearch.txt)

**Comment by soulgalore** [comment]
Hi @myanees284 here's a couple if things I try when I debug a script: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug

I try to run without Docker on my local computer and then I run JavaScript to validate that the element is really there. Also a trick that isn't in the debug docs is to run the tests locally on machine, add a long wait before the error happens, open devtools in the browser and run my JS to try to understand what's going on.

**Comment by myanees284** [comment]
Hello @soulgalore - Thanks for your input.
I tried both the options:

1) Running the script on my local laptop using sitespeed.io command and monitor the network tab from dev tools ---> I could see from browser that the expected link is getting clicked, however there are no post requests being sent. But when I do the same operation manually - I could see those post requests from network tab.

2) Using docker command appended with --browsertime.videoParams.debug 

In both cases - I see "**Almost there.."** spinning page stays upto the maxtime specified as below and finally the script stops -
_await commands.wait.byId('ctl00_c_ctPax1_txtFirstName',100000)_

I have attached the js and video from data/video

https://user-images.githubusercontent.com/44027805/156445880-db0941df-77ad-4b1d-a1e8-d024470105fd.mp4

[script.txt](https://github.com/sitespeedio/sitespeed.io/files/8172785/script.txt)

**Comment by soulgalore** [comment]
And if you try to Run JavaScript to click on the link, what happens then? Like if you manually do the steps in your browser, then as the last step open devtools and run JS to click on the link? And then if that works, use that JavaScript in the script for sitespeed.io?

**Comment by myanees284** [comment]
@soulgalore - Manually, I am able to execute the javaScript from devtools console which does the click on that link and could see the expected page
`document.getElementById('ctl00_c_lnkContinue').click();`

When I add this line as below in the sitespeed script - same old behaviour
`await commands.click.byJsAndWait('document.getElementById(\'ctl00_c_lnkContinue\');')`

**Comment by myanees284** [comment]
> @soulgalore - Manually, I am able to execute the javaScript from devtools console which does the click on that link and could see the expected page `document.getElementById('ctl00_c_lnkContinue').click();`
> 
> When I add this line as below in the sitespeed script - same old behaviour `await commands.click.byJsAndWait('document.getElementById(\'ctl00_c_lnkContinue\');')`

@soulgalore -  1 more thing which I found was- When I run the script using sitespeed.io locally and have added longer wait time before clicking the link.Now from the chrome browser(initiated by sitespeed.io)- when I run the JS command manually - same behaviour appears along with error in console:
`VM2275:1 Uncaught ReferenceError: __doPostBack is not defined
    at <anonymous>:1:1`

**Comment by soulgalore** [comment]
Could it be that some JavaScript file isn't loaded?

**Comment by soulgalore** [comment]
Didn't get any response so closing.
