### ISSUE TITLE
SitespeedIO Issue - Getting "ERROR: Caught error from Browsertime error: Page Index out of range” 

### ISSUE THREAD

**Issue by rohitputhanveetil** [sitespeedio/sitespeed.io#3601]
I have created a Client side script in Site speed IO  for one of our applications. Reports are getting generated correctly when I run for 1 iteration, but facing the following error during report generation when running for multiple iterations - “ERROR: Caught error from Browsertime error: Page Index out of range” but navigation is happening fine for all the iterations in the UI.

Any pointers/suggestions on this issue? Please let me know. Thanks in Advance!!

**Comment by soulgalore** [comment]
Hi @rohitputhanveetil the “Page index out of range” usually means that a navigation didn’t happen. Do your URLs differ between runs? If the URLs change, you can try giving them an alias (=telling
sitespeed.io they are the same).  There’s been bugs and fixes for that but maybe there’s a case that do not work. If you help me reproduce it I can have a look: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue

Best
Peter

**Comment by soulgalore** [comment]
Didn't get any response so closing.
