### ISSUE TITLE
Different lighthouse performance score executing with browser chrome or node in the same machine

### ISSUE THREAD

**Issue by pedrolgon** [sitespeedio/sitespeed.io#3612]
### Your question

I Alll

I put this question in the plugin-litgthouse section

https://github.com/sitespeedio/plugin-lighthouse/issues/102#issue-1181038853

anyone can help me?

Regards,

**Comment by soulgalore** [comment]
I added a comment in the original issue. For others please see the Lighthouse docs https://github.com/GoogleChrome/lighthouse/issues/10657

**Comment by pedrolgon** [comment]
Hi,
Thanks so much
I read the issue but my problem is not the same
The score between different executions in node or docker is the same
but when I execute the lighthouse in the browser the score is always higher and this is a problem for us.
is this an usual behavior?
Regards,
Pedro

**Comment by soulgalore** [comment]
Hi Pedro I think you should ask in https://github.com/GoogleChrome/lighthouse - I think they know better what's the difference between running directly in Chrome vs from NodeJS
