### ISSUE TITLE
Block specific url

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/sitespeed.io#3614]
### Feature/improvement

Hi @soulgalore - in WebPageTest there is the ability to block a url (or any url containing a specific substring). 
Sitespeedio currently allows blocking by domain which is great, but would it be possible to also add blocking by url (or url containing substring)?

**Comment by soulgalore** [comment]
Hi @shaqb the good news is that the functionality is already there for Chrome/Edge but I think the documentation could be better.

This example block the two JavaScript files that sitespeed.io uses:
`sitespeed.io https://www.sitespeed.io -n 1 -o --browsertime.block "https://www.sitespeed.io/js/clipboard-2.0.4.min.js" --browsertime.block "https://www.sitespeed.io/js/prism-1.15.js"`

**Comment by shaqb** [comment]
Ah nice one @soulgalore !

**Comment by soulgalore** [comment]
@shaqb have you been able to test? Wanna make sure it works for you before I close it :)

**Comment by shaqb** [comment]
Hi @soulgalore - I just took your comment as confirmation that it all works! Let me test it now though :)

**Comment by shaqb** [comment]
Works a treat @soulgalore - I was able to block an individual js from our site and use wildcard to block all js. It's amazing how fast it loads without any js 😂
Feel free to close!
