### ISSUE TITLE
I can't close file explorer window when I try to upload a file with sitespeed io docker image 16.8.0

### ISSUE THREAD

**Issue by LAlejandro8** [sitespeedio/sitespeed.io#3622]
### Your question

Hey guys, I'm using the following line to upload a file:

'''await commonUtils.driver.findElement(commonUtils.webdriver.By.xpath(xpath)).sendKeys(file_path);'''

This actually works but when I run it, the file explorer window shows up and doesn't close. :(

![image](https://user-images.githubusercontent.com/10155073/162051416-dfe38724-f8ae-4800-89df-62d7fddb896b.png)

Help!!!

**Comment by soulgalore** [comment]
Hi @LAlejandro8 I haven't had a use case where I upload a file. Have you searched how people usually do it in Selenium? Maybe send the escape key?

**Comment by LAlejandro8** [comment]
Hi @soulgalore, the escape key didn't work, I tried with other keys like ALT + F4 but no results. I'm searching with the Selenium community. Thanks for your reply.

**Comment by soulgalore** [comment]
I think this is an Selenium issue so closing.
