### ISSUE TITLE
Allow to define sendAnnotation from options

### ISSUE THREAD

**Issue by i-marchenko** [sitespeedio/sitespeed.io#3624]
### Feature/improvement

We use graphite-exporter for prometheus instead of graphite itself.
In case when resultBaseURL is defined there is an error due to exporter does not support graphite api:
` ERROR: Got error from Graphite when sending annotation Error: connect ETIMEDOUT <host>:8080
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
ERROR: Error: connect ETIMEDOUT <host>:8080`

We'd like to be able to disable sendAnnotation from options like --graphite.sendAnnotation false

**Comment by soulgalore** [comment]
Thank you @i-marchenko for the report, I see, that's something I've missed, let me add a fix for that in the next release.

**Comment by soulgalore** [comment]
This was pushed in a couple of releases ago.
