### ISSUE TITLE
Change Grafana auth. settings to allow using of a Basic auth. header

### ISSUE THREAD

**Issue by vs-odessa** [sitespeedio/sitespeed.io#3626]
### Feature/improvement

 Existing configuration of grafana authentication restricts for using API key only, because "Bearer" auth type is hardcoded:  
  
```
if (options.grafana.auth) {
      log.debug('Using auth for Grafana');
      postOptions.headers.Authorization = 'Bearer ' + options.grafana.auth;
    }
```

I propose 2 options to resolve the issue:
1. Preferrable (but breaks compatibility):
To remove Bearer type and set 
      `postOptions.headers.Authorization = options.grafana.auth;`
It will allow using both auth: types by setting grafana.auth parameter with specifying type:
`Bearer {API_KEY}`
or
`Basic {USER_PASSWORD_HASH}`

2. Without breaking backward compatibility:
To add another parameter for specifying basic auth.:

```
if (options.grafana.auth) {
      log.debug('Using auth for Grafana');
      postOptions.headers.Authorization = 'Bearer ' + options.grafana.auth;
    }
else if (options.grafana.basic_auth) {
      log.debug('Using basic auth for Grafana');
      postOptions.headers.Authorization = 'Basic ' + options.grafana.basic_auth;
    }
```

**Comment by vs-odessa** [comment]
PR for the first option:
https://github.com/sitespeedio/sitespeed.io/pull/3627

**Comment by soulgalore** [comment]
Hi again @vs-odessa thanks for creating the issue (and the PR)! I added a comment in the PR, maybe there's a way to do your fix and make it backward compatible.

Best
Peter

**Comment by vs-odessa** [comment]
https://github.com/sitespeedio/sitespeed.io/pull/3627 is updated according to @soulgalore 's comment.

**Comment by vs-odessa** [comment]
Merged
