### ISSUE TITLE
First vs Third Party is Missing

### ISSUE THREAD

**Issue by gregorywolf** [sitespeedio/sitespeed.io#3642]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.att.com

### What are you trying to accomplish

I have been running sitespeed v 24.0.0 for quite some time now without any issues. When I upgraded to v 24.1.0 and 24.3.0 I noticed that First vs Third Party section was missing in the HTML-based results. This is usually found in Pages -> Third Party.

When working:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/8494683/165937733-ec7dceb9-ec50-48d5-ab5d-4892802eae05.png">

<img width="867" alt="image" src="https://user-images.githubusercontent.com/8494683/165937765-1dc50c55-f19e-482f-8c82-b8d43479346b.png">

When using 24.1.0 or 24.3.0 it "breaks:

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/8494683/165937880-3216cb29-4303-4d09-a6f3-e7be6638abab.png">

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/8494683/165937891-87ebbf0e-3f10-406e-ae31-3b65cf7f509d.png">

### What browser did you use?

Chrome

### How to reproduce

```shell
Simply run sitespeed version 24.1.0
```

**Comment by soulgalore** [comment]
Hi @gregorywolf thanks for creating the issue! Can you show me exact what value you use for the firstParty switch _(\.(coachoutlet)|.)_ seems to be for another site?) When I run:

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:24.3.0 https://www.att.com -n 1` 

I get the first party data:
<img width="1223" alt="Screenshot 2022-04-29 at 14 04 59" src="https://user-images.githubusercontent.com/540757/165941184-e26bdd29-fed1-45ab-8b1b-11d6fac565c6.png">

Thanks!
Peter

**Comment by soulgalore** [comment]
Hmm strange if I run with: 
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:24.3.0 https://www.att.com -n 1 --firstParty "\.(att)\.(com)"`

I get that data:
<img width="1257" alt="Screenshot 2022-04-30 at 09 25 47" src="https://user-images.githubusercontent.com/540757/166096287-2021526a-9d42-47e8-8712-f790efe4d3a0.png">

By default if you do not set a firstParty reg it uses the domain as in  _.*att.*_ is there something there that make it so it do not work of you? That should work if you run multiple domains to for example:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:24.3.0 https://www.att.com https://www.sitespeed.io -n 1`

**Comment by gregorywolf** [comment]
@soulgalore I seem to have hit an issue that I cannot figure out. I have read your comments and can see clearly that you are successfully using the `firstParty` . Unfortunately I am not having the same success. On my system (CentOS 7) regardless of the syntax the First Party information is being ignored. I have now confirmed this is happening on any version of Sitespeed being executed. I have just run sitespeed v24.3.0 with `-vvv` and have attached the resulting capture. I have looked at it carefully but nothing is catching my eye. When you have a moment could you take a look and see if anything jumps out? It would be much appreciated. Thank you. 







[debugmsgs.txt](https://github.com/sitespeedio/sitespeed.io/files/8598831/debugmsgs.txt)

**Comment by soulgalore** [comment]
I think the reason is that the regex you are using isn't matching any requests? Have you tried it with for example https://regexr.com to verify? I checked the sitespeed.io code and if there's no matching requests, that's the current behaviour. I will change so if there's no matching requests we will see that in the HTML.

**Comment by gregorywolf** [comment]
@soulgalore I have had a chance to do some extensive testing. I am successfully able to use `--firstParty` but there seems to be some nuances that perhaps you can comment on. The way I got it to work was to use a single `--firstParty` line such as the following:
![Screen Shot 2022-05-03 at 6 05 30 PM](https://user-images.githubusercontent.com/8494683/166576396-ee3b5f12-7ee6-4400-8789-a031d0eeee31.jpg)
The results are fine when I want to test a single TLD such as www.amazon.com. However, I notice that when I cluster multiple domains together using a RegEx capture group the results are spotty, meaning that some domains are not getting picked up. This a very central use case since I do a lot of competitive studies with multiple domains. If you look at the next example you can see the httparchive.org is being completely ignored even though it is clearly in the list:
![Screen Shot 2022-05-03 at 6 08 45 PM](https://user-images.githubusercontent.com/8494683/166577856-75d5998f-f455-4395-9c53-e9314d1116df.jpg)

I also tried using a capture group following the domain name and that did not help either:
![Screen Shot 2022-05-03 at 6 14 14 PM](https://user-images.githubusercontent.com/8494683/166578653-fe49b905-dffd-4820-b05b-e4bdf980355f.jpg)

My question for you is what syntax should I use if I have multiple domains in a single test run? Does sitespeed have any limitations on what RegEx it will support? I have been using RegEx for years and realize that there are many different flavors.

I also tried using multiple `--firstParty` lines each with its own unique TLD, but that did not work at all. 

Thank you for the help.

**Comment by soulgalore** [comment]
Hi @gregorywolf there's two different technologies used here and I think that is confusing and maybe we could change that but I need to look into the code how it works. However I don't think that is the reason for the first issue?

First there's the regular expression that defines the firstParty. That is used to categorise each request as first/third party. If you test multiple URLs it will automatically pickup the domain as in https://github.com/sitespeedio/sitespeed.io/issues/3642#issuecomment-1113237785.
<img width="1207" alt="Screenshot 2022-05-04 at 15 56 27" src="https://user-images.githubusercontent.com/540757/166696634-2eac1157-8696-4b88-9a5f-1c05febea92c.png">


We then use the [Third party web](https://github.com/patrickhulce/third-party-web) to categorise what kind of tools that is used. 
<img width="1241" alt="Screenshot 2022-05-04 at 15 58 01" src="https://user-images.githubusercontent.com/540757/166696992-bbedbd36-f34f-44ee-93be-07ad6411def6.png">

What's maybe confusing is the text (I'll change that in the next release): 
<img width="1228" alt="Screenshot 2022-05-04 at 15 58 45" src="https://user-images.githubusercontent.com/540757/166697235-6751789b-73a5-45bc-ad31-e5bc30b0c210.png">

What its suppose to say is that if you have unmatched domains, you need to contribute that domain to the third party web project. The --firstParty switch will only affect when we categorise metrics as first/third in the first case.


>  It seems that if I have two URLs, https://www.att.com and https://www.httparchive.org, sitespeed is only taking into account att.com and ignoring httparchive.org

No I don't think so? If you do not pass on any args as firstParty it will use that domain as regular express using _.*DOMAIN.*_ -  however if you pass on your own regular expression that need to match all the URLs that you test to make sure it matches correctly. I think in your case that comes from the Third party web right? 

What I think we can do is list all responses (or make it configurable) where we can see exact if it is a match or not, to make it easier to see.

**Comment by gregorywolf** [comment]
@soulgalore Wow Not sure what happened but something just clicked. I now realize that the easiest thing to do is DO NOT use `--firstParty` at all. I just tested not using it with a list of URLs with diverse and different TLDs and everything was match correctly. I think any additional wording to help clarify things would be helpful. 

The one thing that is still not totally clear is this what is the best way to handle one additional "firstParty" domain that is associated with one of my tested URLs? I can either use a very long and convoluted RegEx on firstParty switch (and potentially get it wrong) OR .... enter a new entry into the Third Party code? That's the part I am unclear on. Please elaborate. Thanks.

**Comment by soulgalore** [comment]
Great, I added that do the `--help` just now so you can actually understand what's used if you do not set --firstParty.

> The one thing that is still not totally clear is this what is the best way to handle one additional "firstParty" domain that is associated with one of my tested URLs? 

Today you can only do that by a big regular expression. I understand the need but right now I don't have a good pattern for the implementation, but if you could create a separate issue for that, that's a good start and I think how we could do it!

**Comment by gregorywolf** [comment]
Hi @soulgalore. I have just created a new issue for a feature request that extends this conversation for first parties.

https://github.com/sitespeedio/sitespeed.io/issues/3651

**Comment by soulgalore** [comment]
Closing in the favour of #3651
