### ISSUE TITLE
Error: "One or multiple URLs or scripts" when using config.json

### ISSUE THREAD

**Issue by ceddlyburge** [sitespeedio/sitespeed.io#3653]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.peter-emery.com/

### What are you trying to accomplish

I am trying to run sitespeed.io with a config file.

I have installed it with `npm i -g sitespeed.io`

When I run it, it logs the command line parameters, and then "One or multiple URLs or scripts" at the end

### What browser did you use?

Chrome

### How to reproduce

```shell
When I run `sitespeed.io --config config.json` the following error is returned:

| One or multiple URLs or scripts

When I run `sitespeed.io --config config.json script.js --multi` everything works ok.

I think the first command is correct according to the docs, but I can't make it work.
```

### Relevant log output

```shell
This is the config.json that I am using

{
  "browsertime": {
    "urls":[
        "https://www.peter-emery.com/",
        "https://www.peter-emery.com/work"
        ],
    "iterations": 1,
    "browser": "chrome",
    "visualMetrics": false,
    "screenshot": true,
    "screenshotLCP": false,
    "screenshotLS": false,
    "video": false,
    "visualMetricsPortable": false,
    "chrome": {
      "enableTraceScreenshots": false
    },
    "headless": true
  },
  "html" : {
    "summaryBoxes": ["transferSize.total","transferSize.html","transferSize.javascript","contentSize.javascript","transferSize.css","transferSize.image","thirdParty.transferSize","thirdParty.requests","webpagetest.TTFB","cpu.longTasksTotalDuration","cpu.longTasks","cpu.totalBlockingTime","cpu.maxPotentialFid"]
  },
  "sustainable": {
      "enable": false
  },
  "axe": {
      "enable": false
  },
  "plugins" : {
      "add": ["analysisstorer"],
      "remove": ["axe", "sustainable"]
  }
}
```

**Comment by shaqb** [comment]
Hi @ceddlyburge - you will need to pass your urls in a different file and add that to the command line.

For example you could have a urls.txt that looks like this:

```
https://www.peter-emery.com/ Homepage
https://www.peter-emery.com/work Work
```
Note, I have added a page label ('Homepage', 'Work') to your urls so they're easier to see in the report, but these can be omitted.

Then to call this on the command line you can run `sitespeed.io --config config.json urls.txt`

**Comment by ceddlyburge** [comment]
Thanks Shaqb :)

**Comment by soulgalore** [comment]
Thank you @shaqb !
 
Today we do not support having the URLs in the config, I think it's a use case that I missed.
