### ISSUE TITLE
getaddrinfo ETIMEDOUT locahost

### ISSUE THREAD

**Issue by prashantgautam96** [sitespeedio/sitespeed.io#3671]
### Your question

i am getting the error--
 getaddrinfo ETIMEDOUT locahost
while doing a post request can anybody help me here is the data
`router.put("/:id", async (req, res) => {
  if (req.body.userId === req.params.id) {
    if (req.body.password) {
      const salt = await bcrypt.genSalt(10);
      req.body.password = await bcrypt.hash(req.body.password, salt);
    }
    try {
      const updatedUser = await User.findByIdAndUpdate(
        req.params.id,
        {
          $set: req.body,
        },
        { new: true }
      );
      res.status(200).json(updatedUser);
    } catch (err) {
      res.status(500).json(err);
    }
  } else {
    res.status(401).json("You can update only your account!");
  }
});`

`put request ___ locahost:5000/api/users/:629ae48f5baff41b57b9eba4
{
    "userId":"629ae48f5baff41b57b9eba4",
    "username":"aaraqv",
    "password":"aarav@123"
    
}
`

**Comment by soulgalore** [comment]
Closing, I don't see how this has anything to do with sitespeed.io.
