### ISSUE TITLE
Wait one of selectors ready to stop measure

### ISSUE THREAD

**Issue by lgxFree** [sitespeedio/sitespeed.io#3681]
### Your question

Hello, Dear author.
I want to measure a scene that is a list or table. 
it maybe has two final states.
state 1:  Existing data
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/90895136/176127300-e8972705-9027-4462-98a5-3a40f0b7f5b5.png">
state 2: No data
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/90895136/176128117-d7ad7f11-dbca-4f35-a8e2-433ad9188767.png">

so I write a function convenient for measuring that. The function like:
![image](https://user-images.githubusercontent.com/90895136/176128753-fbdc8d74-3e4f-446c-a57c-4ec1a0d2230a.png)
And the usage of function:
![image](https://user-images.githubusercontent.com/90895136/176129802-2b6167d6-7ce8-4e81-bcbf-68d6d9d21d8c.png)

When I measure multiple scenarios together, There will be an error.
![image](https://user-images.githubusercontent.com/90895136/176130242-8b77fd04-3df4-4089-bffb-6c4abd8c4b99.png)

As mentioned above, I just want to wait for one element to come out not all of them to stop measure. 
we will measure different accounts, account configuration is different, I want to make my script more compatible. 
I guess the `commands.wait.bySelector` and `Promise.race`  caused the problem.

How can i solve the problem?
Looking forward to your reply, thanks!

**Comment by soulgalore** [comment]
Hi @lgxFree hmm it looks like stop is never called, could you share the full script or is that the full script?

One thing I've seen that you can change is:
`return await Promise.race(...` you don't need to wait on the race when you return it so you can change to `return Promise.race(...`

**Comment by lgxFree** [comment]
My scenario is to perform two page measurements at once.
I further found the problem was WebSocket closed before `await commands.measure.stop()`. I don't understand why when i measure the second page webSocket Early exit with error.  
I try to add some debug script.
![image](https://user-images.githubusercontent.com/90895136/176401716-24e32d8e-1ede-429c-8899-1f922a51816d.png)
![image](https://user-images.githubusercontent.com/90895136/176401265-587a12e4-1ef8-409d-8fd8-8a90e0a683cc.png)
ErrorInfo:
![image](https://user-images.githubusercontent.com/90895136/176402086-539ffb47-ee6e-4f5d-b4e8-6acbf53f7234.png)

**Comment by soulgalore** [comment]
Hi @lgxFree sorry I don't follow, any change you could share the full scripts so I could try?

**Comment by soulgalore** [comment]
Didn't get any response so closing.
