### ISSUE TITLE
--multi params ,  Redirection problem start measure  throw error

### ISSUE THREAD

**Issue by linqunhe** [sitespeedio/sitespeed.io#3684]
### environment
docker: sitespeed v25.3.0
site router mode : hash 
site runtime : spa

config.json
```json
{
  "browsertime": {
    "iterations": 3,
    "browser": "chrome",
    "viewPort": "1920x1080",
    "cpu": true,
    "timeouts": {
      "pageCompleteWaitTime": 8000
    },
    "spa": true,
    "prettyPrint": true
  },
  "utc": true,
  "summaryDetail": true,
  "html": {
    "showAllWaterfallSummary": true,
    "topListSize": 20,
    "logDownloadLink": true,
    "showScript": true
  },
  "filmstrip": {
    "showAll": true
  },
  "metrics": {
    "list": true
  },
  "useHash": true,
  "logToFile": true
}

```

### Your question

The problem is roughly as follows：

If several files are run together, it will be reported that the element can not be found, and they will all be redirected to the starting bit, and then query the element and simulate the click.
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/80025623/176812007-1ff00b06-0545-4253-8a9c-e46471f7e48c.png">

but , only run error file will be success ;
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/80025623/176812154-4bd87d64-ea2a-4d94-84bb-cc88e3b1ae2c.png">

What I have in common is that I redirect each file to the same link（same origin） and start other actions I need to do, such as finding elements, moving the cursor, and simulating clicks.

For this problem, I have tried the following behavior:
1. Reload after navigate
2. navigate + commands.wait.byTime
3. navigate + commands.wait.byCondition (find elm)
4. navigate +  commands.wait.bySelector

rather than throw same error

**Comment by soulgalore** [comment]
Hi @linqunhe 
I didn't fully get:

> If several files are run together

Can you please share a little more on how you run? 

For debugging you can try the `--debug` switch, checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug
