### ISSUE TITLE
performance budget expect file url  or preview

### ISSUE THREAD

**Issue by linqunhe** [sitespeedio/sitespeed.io#3685]
### Your question

<img width="1318" alt="wecom-temp-205480-9d7d6474e13ccca324d17ab02f47d7fa" src="https://user-images.githubusercontent.com/80025623/176869466-7819d318-5b79-4e2e-a3b2-09c71c1c6d6b.png">

There is no corresponding warning resource for toplist version.
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/80025623/176869624-76ed4bc6-cddc-44dd-bd98-1001743ac361.png">

expect  toplist  and budget  include  file  url or  preview【example:svg,jpg,png,js,css】
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/80025623/176870018-73848009-3082-4348-8087-cc9ebd241495.png">

**Comment by soulgalore** [comment]
Hi @linqunhe the warning in the budget is for the total page, so if you add all JavaScript files together.

**Comment by linqunhe** [comment]
@soulgalore 
I'm sorry, maybe I didn't make myself clear. I hope I can perceive this traditional file list for further analysis, such as

<img width="1872" alt="image" src="https://user-images.githubusercontent.com/80025623/177076000-23959468-4f2d-4143-8267-8c7fb4661542.png">


There is another problem, that is, budget will output duplicate text information, which in theory should not be collected.
![wecom-temp-175924-c70e2307c858d535a87e985954bc06c1](https://user-images.githubusercontent.com/80025623/177075282-b97d2360-605a-4079-ba92-d9ddc9ade1bc.png)

![wecom-temp-156812-a3f86d9e2acbe7dcaee0a1aa398932b5](https://user-images.githubusercontent.com/80025623/177075543-79ac085b-9c88-44ee-8ac1-8fda2fde4c54.png)


Thanks

**Comment by soulgalore** [comment]
Ah I see.

> There is another problem, that is, budget will output duplicate text information, which in theory should not be collected.

Yes that looks weird, is there a way for me to reproduce that? Do you test the same page multiple times or how do you get that output?

> I'm sorry, maybe I didn't make myself clear. I hope I can perceive this traditional file list for further analysis, such as

Good idea! At the moment the budget plugin do not know about the different requests but let me think a while about it, maybe there's a way to fix that.
