### ISSUE TITLE
--block is blocking all the requests in that domain and not just the targeted request

### ISSUE THREAD

**Issue by dev9492** [sitespeedio/sitespeed.io#3688]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.t-mobile.com/

### What are you trying to accomplish

My requirement is to block a certain js request (_https://tags.tiqcdn.com/utag/tmobile/rainier/prod/utag.js_) from the page under test (_https://www.t-mobile.com/_). I have done so by using the below command - 

`sudo docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:24.7.0 --shm-size=1g --axe.enable -n 1 visibletestnojs.js --multi --outputFolder Results/SP/TEST/$(date +%Y-%m-%d)/$(date +%Y-%m-%d-%H-%M-%S) --spa --block "https://tags.tiqcdn.com/utag/tmobile/rainier/prod/utag.js"
`
When I run the command without the `--block`, we can see all the requests from the `utag `domain but when I execute the same command with `--block` to just block one specific js request, all the requests under that domain `utag `are getting blocked including the target request.

### What browser did you use?

Chrome

### How to reproduce

```shell
Test the target URL with and without the --block so observe the difference

Target URL - https://www.t-mobile.com/
URL to block - https://tags.tiqcdn.com/utag/tmobile/rainier/prod/utag.js
```

**Comment by soulgalore** [comment]
Hi @dev9492 the JavaScript in https://tags.tiqcdn.com/utag/tmobile/rainier/prod/utag.js is the one that initiate the load of the rest, so if you block that all will be blocked. You can see that in the waterfall (_Initiator loaded by_):

<img width="1238" alt="Screenshot 2022-07-04 at 09 58 13" src="https://user-images.githubusercontent.com/540757/177109434-824828d3-cf3f-4321-b4a7-5743bd6df026.png">
