### ISSUE TITLE
ERROR: TypeError: commands.select.selectByIdValue is not a function

### ISSUE THREAD

**Issue by prithivi96** [sitespeedio/sitespeed.io#3689]
Hi, 
We were trying to select option from dropdown using Select command in SiteSpeed tool but received error like **"ERROR: TypeError: commands.select.selectByIdValue is not a function"** at that particular step during execution. Kindly someone help us to resolve this issue.
Thanks in advance.

**Comment by soulgalore** [comment]
Hi @prithivi96 I think that is type in the documentation, let me have a look later today. The correct is: `selectByIdAndValue`

**Comment by prithivi96** [comment]
@soulgalore  Thank You. It is working now after replacing with correct method name (selectByIdAndValue).

**Comment by prithivi96** [comment]
@soulgalore  Thank You. It is working now after replacing with correct method name (selectByIdAndValue).
