### ISSUE TITLE
How to use Selenium Explicit Wait Condition in Sitespeed.io ?

### ISSUE THREAD

**Issue by prithivi96** [sitespeedio/sitespeed.io#3690]
### Your question

Dear Author,
I have been trying to use some of the selenium wait and expected conditions in Sitespeed script using context. But I am facing issues in using Explicit wait methods of selenium eg. driver.wait(ExpectedConditions.invisibilityOfElementLocated(locator)) in sitespeed script. I looking through the methods of the driver instance and found wait is one of the method. When I tried to use it using selenium.driver instance with help context variable, I received the below error.

**_ReferenceError: until is not defined_** 

**selenium.driver Doc:** [https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebDriver.html](url)

Below is the sitespeed script:

`module.exports = async function(context, commands) {
   // We fetch the selenium webdriver from context
  // The selenium-webdriver 
  // https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index.html
  const seleniumWebdriver = context.selenium.webdriver;
  const seleniumDriver = context.selenium.driver;
  const By = seleniumWebdriver.By;
  try {
	 
	const seleniumWebdriver = context.selenium.webdriver;
   await commands.measure.start('BPF1_Application_T010_Homepage'); //Start of transaction
   await commands.navigate('appUrl');   //Navigate to Application URL
   await seleniumDriver.wait(until.visibilityOfElementLocated(By.xpath('//*[text()="E-mail Address"]')), 60000);
   await commands.measure.stop();	//End of transaction
   context.log.info('1 - Home Page'); // Log the message
   
   await commands.wait.byTime(5000);
} catch (e) {
    throw e;
  }
};`

**Comment by soulgalore** [comment]
Hi @prithivi96 in your example you haven't defined until, I think that is exposed by the webdriver (you can check https://www.selenium.dev/selenium/docs/api/javascript/index.html and search) 

I think it would work like this:
```
const seleniumWebdriver = context.selenium.webdriver;
const until =  seleniumWebdriver.until;
```

**Comment by prithivi96** [comment]
As mentioned, I have defined until method from selenium webdriver package and now explicit wait is working fine. Hence closing this issue. Thanks for the support!
