### ISSUE TITLE
Fails to use bundled ChromeDriver with Windows/npm install

### ISSUE THREAD

**Issue by Rarst** [sitespeedio/sitespeed.io#3695]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

localhost

### What are you trying to accomplish

Use sitespeed, installed with npm in Windows (e.g. `npm install -g sitespeed.io`).

Some last several versions it started to fail, unable to find ChromeDriver.

ChromeDriver does seem to be present and installed in dependencies, it works if I configure the precise path to it in the command line.

### What browser did you use?

Chrome

### How to reproduce

```shell
sitespeed.io.cmd http://localhost:3000

sitespeed.io.cmd --chrome.chromedriverPath="c:\Users\Rarst\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\@sitespeed.io\chromedriver\vendor\chromedriver.exe" http://localhost:3000
```

### Relevant log output

```shell
[2022-07-13 15:09:04] INFO: Versions OS: win32 10.0.19043 nodejs: v18.3.0 sitespeed.io: 25.4.0 browsertime: 16.11.2 coach: 7.1.2
[2022-07-13 15:09:04] INFO: Running tests using Chrome - 3 iteration(s)
[2022-07-13 15:09:04] INFO: chrome failed to start, trying 2 more time(s): The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
```

**Comment by Rarst** [comment]
> When you run install, can you see if you get any errors or something reported about Chromedriver?

Doesn't look like it, here is a complete log from a clean install:
<details>
<pre>
>npm install -g sitespeed.io
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity
ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity
ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should
use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 527 packages, and audited 528 packages in 15s

72 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (1 low, 3 moderate, 6 high)

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
</pre>
</details>

**Comment by Rarst** [comment]
> If you check in your npm install for sitespeed.io do you see node_modules/@sitespeed.io/chromedriver/vendor/chromedriver.exe ?

Yes, as above, it works if I provide explicit `--chrome.chromedriverPath` to it in there. :) Just not finding it out of the box.

**Comment by Rarst** [comment]
I looked through the code, starting at `at SeleniumRunner.start(C:\Users\Rarst\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\seleniumRunner.js:91:13)` that it reports as where error happens and it seems to happen around here where path is generated _but not returned_ in Windows case https://github.com/sitespeedio/chromedriver/blob/df3c01d9c90ce1b31d35740c0155c96cee07365b/index.js#L13

Does seem to have been broken with Raspberry Pi changes, as you guessed above, because return at the end of function got moved into `else` that never runs for Windows case https://github.com/sitespeedio/chromedriver/commit/0367730d75ead32bff90d2e18890690925d24a62

**Comment by soulgalore** [comment]
Thanks @Rarst for the investigation, I'll fix that tonight then and do a new release.

**Comment by soulgalore** [comment]
That was my fault. In 25.5.0 (just released) it should be fixed. Sorry!
