### ISSUE TITLE
no docker image for latest 25.5.0

### ISSUE THREAD

**Issue by mfontani** [sitespeedio/sitespeed.io#3698]
### Your question

Hi,

There doesn't seem to be a docker image available for the latest tag, `25.5.0`. It gets usually automatically generated and pushed. Something went wrong?

```
# docker pull sitespeedio/sitespeed.io:25.5.0
Error response from daemon: manifest for sitespeedio/sitespeed.io:25.5.0 not found: manifest unknown: manifest unknown
```

**Comment by mfontani** [comment]
The "build container on new tag" step indeed seems to have failed: https://github.com/sitespeedio/sitespeed.io/runs/7340970831?check_suite_focus=true

**Comment by soulgalore** [comment]
Hi @mfontani thanks for reporting, it looks like Docker got a 503 error. I'll push a new release in a couple of minutes.

**Comment by soulgalore** [comment]
The 25.5.1 is there now. Thanks again for reporting!

**Comment by mfontani** [comment]
Thanks, closing!
