### ISSUE TITLE
ERROR: Could not generate crux, Cannot convert undefined or null to object on line 21

### ISSUE THREAD

**Issue by frank-embleton** [sitespeedio/sitespeed.io#3708]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [ ] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://glitch.com/

### What are you trying to accomplish

When trying to collect the CrUX report with sitespeed I get an error: `Could not generate crux, Cannot convert undefined or null to object on line 21`

If I query the google endpoint directly using the same API key like so:

```
url = "https://chromeuxreport.googleapis.com/v1/records:queryRecord?key=**API KEY**"
r = requests.post(url, json={
  "origin": "https://glitch.com/",
  "formFactor": "PHONE",})
print(r.json())
```

Then it returns a valid response:

```
{'record': {'key': {'formFactor': 'TABLET', 'origin': 'https://glitch.com'},
  'metrics': {'experimental_interaction_to_next_paint': {'histogram': [{'start': 0,
      'end': 200,
      'density': 0.2671755725190843},
...
```

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --cap-add=NET_ADMIN --shm-size=1g --rm -v /root/sitespeed:/sitespeed.io -v /root/sitespeed-result:/result -v /etc/localtime:/etc/localtime:ro --name sitespeed --network=host sitespeedio/sitespeed.io:25.7.1 --crux.key **API KEY** --plugins.remove browsertime --crux.formFactor PHONE --graphite.host localhost --slug device --crux.collect ORIGIN --graphite.namespace glitch.crux https://glitch.com/
```

### Relevant log output

```shell
Google Chrome 104.0.5112.79 
Mozilla Firefox 103.0
Microsoft Edge 104.0.1293.47 
https://glitch.com/[2022-08-14 10:25:16] INFO: Versions OS: linux 5.15.0-46-generic nodejs: v16.16.0 sitespeed.io: 25.7.1 browsertime: 16.13.1 coach: 7.1.2
[2022-08-14 10:25:17] INFO: Get CrUx data for domain glitch.com
[2022-08-14 10:25:17] ERROR: Could not generate crux, Cannot convert undefined or null to object on line 21
[2022-08-14 10:25:18] INFO: HTML stored in /sitespeed.io/sitespeed-result/device/2022-08-14-10-25-16
```

**Comment by soulgalore** [comment]
Hi @frank-embleton thanks for reporting the bug! There was a bug in the frontend that didn't handle if you only get origin data. Pushed a PR and hope to release that tomorrow.

**Comment by frank-embleton** [comment]
@soulgalore thanks!
