### ISSUE TITLE
excute error collect extra metrics

### ISSUE THREAD

**Issue by linqunhe** [sitespeedio/sitespeed.io#3710]
### Feature/improvement

- now [error]

<img width="914" alt="image" src="https://user-images.githubusercontent.com/80025623/184591349-b8635b66-9a28-4fa2-9e1e-c0bc2430b519.png">
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/80025623/184591366-fdf0e85d-7eb7-49ca-abdf-ccb770a83bce.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/80025623/184591405-2bf5d494-991c-4904-8e0c-562cfeb14bef.png">

- normal 【measure no error】
<img width="882" alt="image" src="https://user-images.githubusercontent.com/80025623/184591488-3d97a2cd-fa28-4738-b88d-e52b7b039e26.png">

How to ensure that some of the collected indicators can be injected in the event of an exception in process execution?

**Comment by linqunhe** [comment]
Transition posture, first finish the measurement, and then return, but at this time the error can no longer be captured from the outside, thus output to html

<img width="748" alt="image" src="https://user-images.githubusercontent.com/80025623/184593396-6ae8ca25-a0dd-4dfb-859b-ad0a5f7370a0.png">

**Comment by soulgalore** [comment]
Hi @linqunhe I didn't fully understand, what do you want me to do? :)
