### ISSUE TITLE
Chrome is not able to start

### ISSUE THREAD

**Issue by Vaibhavi-jasolia** [sitespeedio/sitespeed.io#3722]
### Your question

<img width="765" alt="Screenshot 2022-09-10 at 16 31 37" src="https://user-images.githubusercontent.com/113252013/189490436-b5511b03-df46-4563-a9b7-9a78e19af86e.png">
I am using latest sitespeed image then also chrome is not able ton start.

<img width="647" alt="Screenshot 2022-09-10 at 16 33 16" src="https://user-images.githubusercontent.com/113252013/189490565-0150312c-b819-458e-a10c-c703d4484b38.png">

**Comment by soulgalore** [comment]
Hi @patel20162009 if you run without modifying the container do that work?

`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:25.11.0 https://www.sitespeed.io/`

A way to see what's going on is enabling the Chromedriver log (the Chromdriver is the code that drives Chrome). You can enable that logs by adding `--browsertime.chrome.enableChromeDriverLog true` then in your result folder you should see   a log file named someting like _chromedriver-1.log.gz_ , unpack that file and check the log if you see any errors etc, hopefully that can tell us what's going on.

**Comment by patel20162009** [comment]
Thanks for the reply.
If I use this docker file then it will work
https://github.com/sitespeedio/sitespeed.io/blob/main/docker/Dockerfile-plus1
?
..
