### ISSUE TITLE
Grafana Dashboard Alert Query

### ISSUE THREAD

**Issue by Vaibhavi-jasolia** [sitespeedio/sitespeed.io#3728]
### Your question

Using sitespeed.io I am collecting the metrics for webpage. I have Grafite as a datasource. Grafana as visualisation tool. I have build the dashboard using variable.
While alerting I have different url but same query.. E.G. I want to setup alerting on pageLoadTime, TBT,TTFB FOR all the urls..
How I can do that?
Do I have to setup alerting for each url and each panel?
New Upcoming urls how i can do alerting before hand..E.G. url coming first time to the dashboard and pageLoadTime is high we need alerting .. How I can do this?

**Comment by soulgalore** [comment]
Hi @patel20162009 if you use Grafana for alerting you should checkout https://grafana.com/docs/grafana/latest/alerting/ and ask in https://community.grafana.com, I think they can help you better there.
