### ISSUE TITLE
Bug? Vedio read LastVisualChange 0 !!

### ISSUE THREAD

**Issue by linqunhe** [sitespeedio/sitespeed.io#3732]
### Your question

video total time 1s!
https://user-images.githubusercontent.com/80025623/191918832-e5fa035c-2184-4d0c-b0af-cdb64b2fe724.mp4

store data read zero !
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/80025623/191919223-ee258c15-705c-4cbe-8816-6b7dde1304c8.png">
<img width="889" alt="image" src="https://user-images.githubusercontent.com/80025623/191918762-2f64e907-fdff-4db4-bdb1-4d01e39b5edf.png">

sitespeed(docker run) : [v25.11.0](https://github.com/sitespeedio/sitespeed.io/releases/tag/v25.11.0)

**Comment by soulgalore** [comment]
Closing since I didn't get any response.
