### ISSUE TITLE
Render blocking says blocking but in fact not

### ISSUE THREAD

**Issue by ettenjerome** [sitespeedio/sitespeed.io#3733]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

internal-url

### What are you trying to accomplish

Hi, when I see the waterfall I have two resources display with "_renderBlocking": "blocking" but in fact there are not blocking.

I verified in the google chrome console, this resources are not blocking.

![2022-09-23_09h51_03](https://user-images.githubusercontent.com/71869605/191920111-e6a97ad5-cb70-40f8-b079-145439ff66b2.png)
![2022-09-23_09h49_55](https://user-images.githubusercontent.com/71869605/191920118-8cf08da8-3b75-4eb3-9268-f812d25f912b.png)
![2022-09-23_10h21_36](https://user-images.githubusercontent.com/71869605/191920120-5b0879b7-313a-4404-a132-20000a6ca332.png)

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --network=4g --rm -v /home/src/Budgets-Batch:/sitespeed.io -v /etc/localtime:/etc/localtime:ro sitespeedio/sitespeed.io:25.11.0 --graphite.addSlugToKey false --config config_base.json  -c 4g urls/PA.txt --plugins.remove html --plugins.remove assets --plugins.remove harstorer --plugins.remove domains --plugins.remove lateststorer --plugins.remove budget --plugins.remove text --plugins.remove tracestorer --graphite.namespace sitespeed_io.desktopFirstView_WithConsent --cookie tarteaucitron=tarteaucitron=!analytics=true!hotjar=true!bingads=true!criteo=true!facebookpixel=true!googleadwordsconversion=true!googleadwordsremarketing=true
```

### Relevant log output

```shell
Google Chrome 105.0.5195.52
Mozilla Firefox 104.0
Microsoft Edge 104.0.1293.70
[2022-09-23 08:02:45] INFO: Versions OS: linux 4.19.0-21-amd64 nodejs: v16.16.0 sitespeed.io: 25.11.0 browsertime: 16.15.1 coach: 7.1.2
[2022-09-23 08:02:45] INFO: The following plugins are enabled: browsertime, coach, graphite, metrics, pagexray, remove, thirdparty
```

**Comment by soulgalore** [comment]
Hi @ettenjerome that info comes directly from Chrome, so it should be the same in devtools. Can you show me how you see that in Chrome devtools, I haven't used that in a while.

**Comment by ettenjerome** [comment]
You case use Performance insights in chrome devtools.

I just double-checked with chrome devtools the resources are effectively  blocking rendering.

There are no problem, @soulgalore thank you for your response.
