### ISSUE TITLE
Consume an updated model for the sustainable web design features in sitespeed 

### ISSUE THREAD

**Issue by mrchrisadams** [sitespeedio/sitespeed.io#3735]
### Feature/improvement

Hi folks. 

The org I work for, the Green Web Foundation did some work a while back with some of the sitespeed team, to add Sustainable Web Calculations into sitespeed. You can read about it below here:

https://www.thegreenwebfoundation.org/news/how-to-build-a-more-sustainable-web-with-a-little-help-from-sitespeed-io/

We have a new version of the underlying library, CO2.js, out, which provides much more data about the carbon intensity of electricity, as well as using revised model for converting usage into energy and carbon emissions figures.

It's outlined at the link below, as opposed to the existing variant of the 1byte model:

https://sustainablewebdesign.org/calculating-digital-emissions

We've put a short blog post explaining the differences between the models, and what to take into account when upgrading from previous versions, and I wanted to create the issue to make sure us switching didn't accidentally impact anyone using it in sitespeed. It's available below:

https://www.thegreenwebfoundation.org/news/release-guide-co2-js-v0-11/

It looks like the [master branch is pinned to using version 0.8.0 of CO2.js](https://github.com/sitespeedio/sitespeed.io/blob/main/package.json#L80), so I think us switching to the new Sustainable Web Design model won't affect anyone who hasn't explicitly made the decision to use a newer version of the library, but I wanted to open this issue if anyone was considering updating for a future release and would like any help doing so.

**Comment by soulgalore** [comment]
Hey @mrchrisadams I can start with the update next week, thanks for reaching out. I've been following the project but haven't fully understood when there was good time to upgrade but I guess then that the time is now. I'll ping you in the PR so I can get your input if something is missing.

**Comment by soulgalore** [comment]
HI @mrchrisadams I tried this morning upgrading to 0.11.1 (from 0.10.4) and it seems that something changed I couldn't find in the changelog, I get that loadJSON function is removed? `TypeError: tgwf.hosting.loadJSON is not a function` and when I checked I could only see the hosting.check method? What do I need to change on my side?

I also wanted to update the url2green.json file, but I don't remember how to generate it? Is there docs somewhere? I could only find the db files in https://admin.thegreenwebfoundation.org/admin/green-urls

**Comment by soulgalore** [comment]
Hi @mrchrisadams I don't think at the moment hosting-node.js isn't exported, so you cannot get gold of it outside the project? I can make PR for the change you proposed.

**Comment by mrchrisadams** [comment]
Ah, nuts, I think you're right Peter. thanks for checking.

I'd really appreciate the PR, thanks 👍

**Comment by soulgalore** [comment]
This been fixed after the PR.
