### ISSUE TITLE
Grafana : Error: getaddrinfo ENOTFOUND host.docker.internal

### ISSUE THREAD

**Issue by lilei1122** [sitespeedio/sitespeed.io#3738]
### Your question

Follow document to install docker grafana and sitespeed.io.  Executed the docker commond of below:

-bash-4.2$ docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:26.0.1 --graphite.host=host.docker.internal https://www.sitespeed.io/ --slug yourTestName --graphite.addSlugToKey true

I got error message when commond executed finished.
[2022-10-09 03:50:59] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

Search the error in google,  local IP(127.0.0.1) and localhost need to config in hosts file. but error still popup when executed. and there is no any data in Grafana GUI.
Could you please support on this error, how to collect the sitespeed.io test result in Grafana.

![image](https://user-images.githubusercontent.com/39395526/194737206-1a8dd1d6-0bbb-4344-b1b8-1f924c2bb3a1.png)

**Comment by soulgalore** [comment]
Hi @lilei1122 what's localhost inside the container depends on your OS, it seems that is handled differently on different platforms. Here's some tips: https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost
