### ISSUE TITLE
Using FID metric in the budget

### ISSUE THREAD

**Issue by inderpartap** [sitespeedio/sitespeed.io#3742]
### Your question

We tested the FID using scripts for our URLs, and the metric is visible under the page summary in the metrics section. So far so good.

My question is if this can be used in the budget configuration. We do calculate and store it in [webdriver/chromium.js](https://github.com/sitespeedio/browsertime/blob/main/lib/chrome/webdriver/chromium.js#L377). Can we make it so that if this metric is calculated, the budget would work, or else it'll be ignored? Or am I missing something?

**Comment by soulgalore** [comment]
Hi @inderpartap no I haven't added FID to the list of metrics available for the budget. The reason is that I think it's hard to get right and it easier to keep track of total blocking time. Do you get a FID metric that you feel is correct and the same over time? Then I can make sure its there for the next release!

**Comment by inderpartap** [comment]
Ah yes, it varies, but the variance wasn't too much for the script I was running. I agree that we should estimate FID issues using TBT, but our TBT values are all over the place for some reason.  

The way we run SiteSpeed is one URL per test and is run 15 times. However, when multiple tests (multiple containers) run on the same EC2 instance, the std dev is quite high. We do this because we built a custom wrapper around SiteSpeed, which manages the tests to run, and blocks PRs from being merged in case of performance regressions.

Do you think the high std dev is because of the multiple containers on a single machine?

**Comment by inderpartap** [comment]
Though I think you answered my question in #2430. We have used an ECS cluster of c5.2xlarge instances but ran ~6-7 containers on each instance. Each container had a config of 1 URL and 15 runs.
I'll try setting up 1 container per instance and check if that resolves the variance issues

**Comment by soulgalore** [comment]
@inderpartap I think the problem is not variance from multiple containers, I think the FID depends very much on when Selenium do things compared to when the browser is handling it's JavaScript. That's why I was thinking using total blocking time would be easier to use if you need a budget.

**Comment by inderpartap** [comment]
I meant the FID was fairly consistent for us, but TBT had a huge std dev (of about 800ms). I tested with one container per instance, bringing down the std dev to ~70ms.

**Comment by soulgalore** [comment]
Yeah but how do you know that you are measuring FID the way users get it?  I think we are depending on when Selenium runs the commands at the exact same time the browser do JavaScript. What I like about TBT or using long tasks, then at least in theory it should me more constant as long as you deliver the same JS.

**Comment by inderpartap** [comment]
Oh yes, totally agreed. I know what we were measuring was only one case of interaction. Many variables depend on the user - where they click, and when they click, which cannot be accurately reproduced in the lab. I only tried looking at FID because TBT had a high std dev for our tests. But running a single container per instance has solved that problem to a large extent.

I'll be closing this issue as a resolution was achieved. Thanks for your time :)
