### ISSUE TITLE
Running sitespeed.io https://www.sitespeed.io/ opens a bashfile?

### ISSUE THREAD

**Issue by jzatarain** [sitespeedio/sitespeed.io#3746]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io/

### What are you trying to accomplish

Test sitespeed.io and got this: 
![image](https://user-images.githubusercontent.com/20093580/198088702-663e4d4b-cfbf-461e-b46a-78931c7fb125.png)

### What browser did you use?

Edge

### How to reproduce

```shell
I ran "sitespeed.io https://www.sitespeed.io/" from powershell as admin

I have node 14.16.1
```

**Comment by amtest1** [comment]
I have the same problem. Did you figure out how to bypass this?
