### ISSUE TITLE
Filmstrip images are shrunk/displayed as tiny images - reproducible

### ISSUE THREAD

**Issue by manjunathpremkumar** [sitespeedio/sitespeed.io#3753]
Hi,
We have noticed this issue for couple of scripted journeys and reproducible, where the filmstrip images are shrunk/displayed as tiny images. 

Have tried with below settings along Broswertime but results were still same. Attached the HAR file and config file and screenshot

     "videoParams.filmstripFullSize": true,
    "videoParams.filmstripQuality": 100,

Thanks,
Manju

[MYB_Lounge_URP_Page_Load_confirmation-chrome-2022-11-24045342.har.gz
![FilmStrip_Issue](https://user-images.githubusercontent.com/43643055/203947152-aeb110ef-bd0a-4faf-8416-579fa5de21da.JPG)
](https://github.com/sitespeedio/sitespeed.io/files/10090340/MYB_Lounge_URP_Page_Load_confirmation-chrome-2022-11-24045342.har.gz)
[default_config.txt](https://github.com/sitespeedio/sitespeed.io/files/10090352/default_config.txt)

**Comment by manjunathpremkumar** [comment]
@soulgalore - your help and feedback please

**Comment by soulgalore** [comment]
Hi @manjunathpremkumar thanks for creating the issue, I will have a look this weekend and see if I can understand what's going on.

**Comment by soulgalore** [comment]
@manjunathpremkumar I need a way to reproduce it, can you share the user journey? Or how I can reproduce it? Adding the same config for video and kiosk mode just accessing one URL works for me. What do the video look like, is it correct or also tiny?

**Comment by manjunathpremkumar** [comment]
@soulgalore - it says video is not available to download kind of corrupted. I will check with my team if I can get the user journey script

**Comment by soulgalore** [comment]
Do you keep the logs, I wonder if there's error log somewhere?

**Comment by manjunathpremkumar** [comment]
@soulgalore - I am sorry for late reply, I was down with flu. Attached the user journey script and error log. 
[ErrorLog_3753.txt](https://github.com/sitespeedio/sitespeed.io/files/10119567/ErrorLog_3753.txt)
[user_journey_script_3753.txt](https://github.com/sitespeedio/sitespeed.io/files/10119568/user_journey_script_3753.txt)

**Comment by soulgalore** [comment]
The only way for me to fix these kind of things is to show how to reproduce it.
