### ISSUE TITLE
Has anyone set up alerting? 

### ISSUE THREAD

**Issue by tprocter1984** [sitespeedio/sitespeed.io#3754]
### Your question

I'm trying to configure alerting so that I push to the likes of Slack. When I go to create an Alert rule, I am unable to: 
![image](https://user-images.githubusercontent.com/6536117/204766987-6ceda21b-7c7f-4367-bd55-80df77c88b1e.png)

This is the button that is not available:
![image](https://user-images.githubusercontent.com/6536117/204767795-1f556d06-0541-41b6-9856-0abac442b3d5.png)

Has anyone done this yet? From what I can see, we would need to add some additional docker containers, however, I am not 100% confident this is correct. 

Any help or info would be appreciated and you'll get all my love :heart:

**Comment by soulgalore** [comment]
Hi @tprocter1984 sorry I missed your questions. Yes I have. Grafana has changed art GUI on functionality between releases, what Grafana version are you using?

**Comment by soulgalore** [comment]
No feedback so closing.
