### ISSUE TITLE
Get the page Cookies

### ISSUE THREAD

**Issue by pedrolgon** [sitespeedio/sitespeed.io#3756]
### Your question

Hi All,

I need get the page cookies and save them for a new execution
how can I do it?

Regards,

Pedro

**Comment by soulgalore** [comment]
Hi @pedrolgon either if you use [scripting](https://www.sitespeed.io/documentation/sitespeed.io/scripting/) you navigate to a page, get the cookie (per automatic), start a measurement and go to the next page.

Else use dev tools, copy/paste the cookie/value and use `--browsertime.cookie`  with those copied values for your run.

Best
Peter

**Comment by soulgalore** [comment]
Didn't get any response so closing.
