### ISSUE TITLE
measure area has blink , last visual change result error

### ISSUE THREAD

**Issue by linqunhe** [sitespeedio/sitespeed.io#3760]
#### env
- node 16
- macos
- docker
- sitespeed 26.1.0

#### question
It only takes about three seconds to enter this page by artificial perception, but the measured last visual change is more than ten seconds. I tried to click on other areas to make the cursor disappear, but how to write the click logic, I still need to wait for more than ten seconds to continue other logic. , tried injecting commands.js.run and await command.wait.bySelector + click

https://user-images.githubusercontent.com/80025623/207768127-54597608-ee2a-494d-93ee-61605189bc73.mp4

code 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/80025623/207768366-f8bb66fc-7a93-4ee3-82a6-fe3a9a94969d.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/80025623/207768401-b7039456-7d5f-4432-a390-2f423803cce4.png">

It can’t be implemented according to my expectation. I don’t know if it’s a bug. In theory, it should be implemented as expected. The last visual change of this page should be within 4s

tks

**Comment by soulgalore** [comment]
There are some hacks here: https://stackoverflow.com/questions/9333044/how-to-hide-blinking-cursor-in-input-text
