### ISSUE TITLE
Extra metrics collected using scripting in graphite

### ISSUE THREAD

**Issue by bastihav** [sitespeedio/sitespeed.io#3765]
I would like to be able to track extra metrics which I collect using scripting in graphite.
Currently, they do not show up and I can also not find them when running "--metrics.list". 
The metrics do, however, show up on the html report.

Is there some way to configure this, which I overlooked?

**Comment by soulgalore** [comment]
Hi @bastihav it depends, how do you collect the metrics, can you share an example? For some cases there should be there automatically but it could be that its a bug.

**Comment by bastihav** [comment]
Sure, thanks :)
Maybe I'll give some context; I need the extra metric as our SPA performs regular health-checks to the backend. This happens every 30 seconds and as the page is very slow, this can make the full load time bounce between 30 and 60 seconds. Hence, my target metric is time from beginning of the document to the end time of the last completed response.

script.js:
```js 
module.exports = async function(context, commands) {
    await commands.navigate('myUrl')
    await commands.addText.byId(username, 'username');
    await commands.addText.byId(password, 'password');
    await commands.click.byId('login-button');

    const start =  await commands.js.run("return window.performance.now()");
    await commands.wait.byPageToComplete();
    
    let resourceTimings = await commands.js.run("return window.performance.getEntriesByType('resource')");
    resourceTimings = resourceTimings.filter(entry => !entry.name.includes("api/health-check"))
    // sort by end date: last element should be the latest completed request
    resourceTimings = resourceTimings.sort((a,b) => a.responseEnd - b.responseEnd)
    const end = resourceTimings.pop().responseEnd
    const time =  end - start
    
    await commands.measure.stop();
    await commands.measure.add('my.metric', time + "ms");
};
```

Similarly, my pageCompleteCheck looks a bit different, too:
```js
module.exports = function(waitTime) {
    const defaultPageCompleteCheck = function(waitTime) {
        try {
            let end = window.performance.timing.loadEventEnd;
            let start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
        }
        catch(e) {
            return true;
        }
    };

    const p = window.performance;

    if (window.location.href.includes('login.html')) {
        return defaultPageCompleteCheck(500);
    }

    let resourceTimings = p.getEntriesByType('resource');
    resourceTimings = resourceTimings.filter(entry => !entry.name.includes("api/health-check"))
    // sort by end date: last element should be the latest completed request
    resourceTimings = resourceTimings.sort((a,b) => a.responseEnd - b.responseEnd)
    if (resourceTimings.length > 0) {
        const lastEntry = resourceTimings.pop();
        const stop = p.now() - lastEntry.responseEnd > waitTime;
        if (stop) {
            return true;
        }
    } else {
        return false;
    }
}
```
It tries to combine both the default and SPA check of you. The login is very quick so I have a different timeout set, for the other page (again, loads roughly 30s) I take a look at the last completed request (filtering all health checks out). We sometimes have requests which were started very early, but take a long time. Hence, I sort by endTime (might be something you want to consider for the SPA check!)

I then start sitespeedio with 
```json
{
  "browsertime": {
    "iterations": 1,
    "browser": "chrome",
    "pageCompleteWaitTime": 28000,
    "pageCompleteCheck": "pageCompleteCheck.js"
  },
  "graphite" : {
    "host": "localhost",
    "port": 2003,
    "namespace": "sitespeed"
  },
  "plugins": {
    "remove": ["html"]
  }
}
```
and 
`sitespeed.io --config sitespeed-config.json --multi script.js`

The metric then shows up as "Extra metrics collected using scripting" in the report, but is not sent to graphite, nor does it appear in the metrics.list output.

If I can record this metric in some other way and it works, that would be fine for me too. But as it is timing related, I don't think I can add the metric using the standalone metric script thing.

**Comment by soulgalore** [comment]
Hi @bastihav I think the problem is:

` await commands.measure.add('my.metric', time + "ms");` so Graphite do not handle strings, try with:

` await commands.measure.add('my.metric', time);`

then I think it will automatically pushed to Graphite

Best
Peter

**Comment by bastihav** [comment]
Thanks for the quick help! :)
I thought I already tested it before I added the ms, but oh well, works now.
For anyone finding this thread:
it would show up under `metrics.sitespeed.*.pageSummary.*.*.chrome.native.browsertime.statistics.extras.my_metric` in my case.
