### ISSUE TITLE
Unable to push data to Graphite hosted in a separate machine

### ISSUE THREAD

**Issue by prabinkumar677** [sitespeedio/sitespeed.io#3766]
Trying to push data to graphite which is hosted on different machine . Unable to see the data getting appeared in Graphite UI . Also don't see any error in console as well. Any help on this would be appreciated !

**Comment by soulgalore** [comment]
Hi @prabinkumar677 one thing to try first could be to see if you can send a test metric using curl from that machine to Graphite, to verify that the issue is in sitespeed.io (checkout step 3):

https://graphite-web.readthedocs.io/en/latest/feeding-carbon.html

**Comment by soulgalore** [comment]
Didn't get any response so closing.
