### ISSUE TITLE
Get custom metric from javascript variable

### ISSUE THREAD

**Issue by pedrolgon** [sitespeedio/sitespeed.io#3768]
### Your question

Hi All,

We need to get a custom metric from javascript variable, but this is only possible executing a script.

is it possible get a custom metric executing sitespeed.io without a script?

Regards,

Pedro

**Comment by soulgalore** [comment]
Hi @pedrolgon it should work with:

 `--browsertime.script`           Add custom Javascript that collect metrics and run after the page has finished loading. Note that --script can be passed multiple times if you want to collect multiple metrics. The metrics will automatically be pushed to the summary/detailed summary and each individual page + sent to Graphite/InfluxDB.

You can test it by create a file (the name will be used as the metric name): myCustomMetric.js and then add the JavaScript in that file:
```
(function () {
  return 1;
})();
```

Then run with `--browsertime.script myCustomMetric.js ` then you will see the metric in the Metrics tab and check for "Custom metrics collected through JavaScript".

Best
Peter

**Comment by pedrolgon** [comment]
Hi Peter,

Thanks so much

The solution is working for me

Regards,

Pedro
