### ISSUE TITLE
support for Azure storage

### ISSUE THREAD

**Issue by mdvaliyullah** [sitespeedio/sitespeed.io#3784]
### Feature/improvement

support for Azure storage to store the result HTML/images and videos

**Comment by soulgalore** [comment]
Hi @mdvaliyullah I haven't used Azure, is that the blob storage? https://www.npmjs.com/package/@azure/storage-blob 

I wonder if there's a dummy version so we could add tests for it, I want to avoid having a subscription.

**Comment by mdvaliyullah** [comment]
yes its blob storage

**Comment by AlanCodega** [comment]
I think you can "manually" reach the same result by modifying your yml file with something like (This in my case it's to publish as an artifact the sitespeed.io report result):
- task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/sitespeed-result-${{ parameters.networkVelocity }}-$(TIMESTAMP)'
        artifact: 'sitespeed-result-${{ parameters.networkVelocity }}-$(TIMESTAMP)'
      displayName: 'Publish Sitespeed.io results'

**Comment by soulgalore** [comment]
At the moment I think we will not support Azure storage, it will be to much burden to keep all the different versions up and running.
