### ISSUE TITLE
How to add custom timer 

### ISSUE THREAD

**Issue by jmrane** [sitespeedio/sitespeed.io#3786]
### Your question

Hello,

I am trying to get custom timer but cant see it in the report.

using below code:-

Hi,
I am unable to add the timer in a page. Using below code.

 const stopWatch = commands.stopWatch.get('search');
	await commands.addText.byXpath('7307586','/html/');
	await commands.wait.byPageToComplete()	
stopWatch.stopAndAdd()

Cant see the "search" in the Pages section of the result.

Thanks

**Comment by soulgalore** [comment]
Hi @jmrane not 100% sure, what do you want to measure and what happens on the page when you add that text by xpath?

**Comment by jmrane** [comment]
it is basically a adding a text in to a search box and get the output

**Comment by soulgalore** [comment]
Sorry I didn't understand what you want to measure? Can elaborate your full use case/how it will work?

**Comment by soulgalore** [comment]
Ah I see thank you.

In your code you need to find a way to know that the search has finished, in your code you wait for page to finish to load:
```
const stopWatch = commands.stopWatch.get('search');
await commands.addText.byXpath('7307586','/html/body/div[1]/div[2]/div/div[2]/main/div[2]/div/div[2]/');
await commands.wait.byPageToComplete() <---- waits for page to finish loading
const time = stopWatch.stop();
console.log(stopWatch.getName()); 	
commands.measure.add(stopWatch.getName(), time);
```

There's a couple of different things you can do: either you can use scripting/Selenium to check when the search content is in the DOM. The problem with this is that it's not exactly the same as the content is visible for the user but maybe it can be enough.

If you use Chrome(ium) browsers you can use the [Element Timing API](https://wicg.github.io/element-timing/) if you can change the search result and add an elementtiming attribute, you can get when the result was painted.

**Comment by jmrane** [comment]
Thanks I will check this. But my question is why the stopwatch command is not working. I should see the 'search' name in to the page list. But I can't see it

**Comment by soulgalore** [comment]
In the HTML your timers will be in the "metrics" section for the page where you attached that metrics. 
![metrics](https://user-images.githubusercontent.com/540757/226542553-442cc1da-9f59-41c6-aa83-f84dbdaa1165.jpg)

Then you can scroll down and look for "Extra metrics collected using scripting":
<img width="1255" alt="Screenshot 2023-03-21 at 08 33 07" src="https://user-images.githubusercontent.com/540757/226542616-c40a4c3f-bfa5-4e33-948e-704b766f557d.png">

Do you get it there?

**Comment by jmrane** [comment]
Is it necessary to have the stopwatch inside the main page? Because then to measure the search time inside the page is a problem

**Comment by soulgalore** [comment]
The measurement you do needs to be attached to a measurement of a page. I updated the documentation some time ago: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure
