### ISSUE TITLE
Can I connect the result page to https?

### ISSUE THREAD

**Issue by itsssyou** [sitespeedio/sitespeed.io#3795]
### Your question

The result page communicates with HTTP.
I connect this to nginx.
Can I communicate with HTTPS with a certificate file?

**Comment by soulgalore** [comment]
Yes you can setup HTTPS on nginx: https://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by itsssyou** [comment]
많은 도움이 되었습니다! 감사합니다.
