### ISSUE TITLE
Can I change the graphite index query?

### ISSUE THREAD

**Issue by itsssyou** [sitespeedio/sitespeed.io#3796]
### Your question

It is indicated as an index when checking the page in grafana.

For example, like "_pages_check_index.aspx"

Can you change this name like "check"?

**Comment by soulgalore** [comment]
Hi @itsssyou don't follow exactly what you want to do, can you please try to explain a little more?

**Comment by itsssyou** [comment]
I am collecting data using Graphite.

Graphite's whisper is stored as a domain index.

For example, in the following folder name.

ex)
_test_inC_desktop_deafult_aspx
_test_inc_mobile_deafult_aspx
_Desktop_deafult_aspx
_Mobile_deafult_aspx

The data stored in this way in Grafana's dashboard
It is displayed in the same name as above.

But I think this is not readable.

This

_test_inc_desktop_deafult_aspx => test_desktop
_test_inc_mobile_deafult_aspx => test_mobile
_Desktop_deafult_aspx => Desktop
_Mobile_deafult_aspx => Mobile

I want to change it like this.

But I confirmed that even if I changed the name of the folder in whisper, it was not applied.

  What you want to summarize is that you can check the collected page stored in whisper on the grafana or dashboard with the name I changed?

**Comment by soulgalore** [comment]
If you give your URL an alias, that alias will be used in Grafana (and in Graphite). I think that will fix the problem for you? Please let me know if it didn't.
