### ISSUE TITLE
When a null value occurs for the reposition alert

### ISSUE THREAD

**Issue by itsssyou** [sitespeedio/sitespeed.io#3798]
### Your question

I am receiving alert as a slack when a "Repense error code" occurs.
For example, like a 4xx error or a 5xx error.

There is no error code collected when the error is solved.
When the error is solved, the alarm of "nodata labels = {} value = null" is generated.

I set "Notification Settings" to "Disable Resolved Message" in Grafana's "Update Contact Point".
And I set the "OK" option to "Alert State if No Data or All Values are null" options.
Nevertheless, a null error occurs.

-Collect 4xx and 5xx errors from Response Code data.
-If the error is solved, there is no more data collected.
-There is a NULL alarm due to this problem
-In order to solve, when the null value occurs without receiving the alarm when the grafana is reslovered, the alarm is not generated, but the null alarm continues to occur.

How can I solve the above problem?

**Comment by soulgalore** [comment]
Hi @itsssyou this seems like Grafana issue, please ask in https://github.com/grafana/grafana/issues
