### ISSUE TITLE
Passing multiple test data in sitespeed.io

### ISSUE THREAD

**Issue by QTSankarRajan** [sitespeedio/sitespeed.io#3800]
### Your question

I am trying to test a user journey where each page use different test data for each iteration its being tested. Is it possible to supply it as external parameter using a file? If so, please help me with how to do the same, else any documents on the same would be helpful.

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @QTSankarRajan I think this is what you can use: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#pass-your-own-options-to-your-script

Best
Peter

**Comment by soulgalore** [comment]
It's an example on how to pass on data. You can pass on path to a file you can read, or an array with data for each iteration or whatever.

**Comment by QTSankarRajan** [comment]
Thanks for responding. I will try this for what I am looking for.
