### ISSUE TITLE
Adding custom headers to the js file in docker command with -r not working

### ISSUE THREAD

**Issue by Sudeep05** [sitespeedio/sitespeed.io#3801]
@soulgalore , I'm unable to do the same thing as above to add custom headers during browsetime with my js file, when i add -r in my command it throws null and unable to add text where I'm trying to add some data to Textbox but whereas when i remove my Header , it works.

I'm using below command.
docker run --cap-add=NET_ADMIN --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.1.0-plus1 Test.js --multi -c lte --browsertime.connectivity.engine=throttle  -n 1 --graphite.host=x.x.x.x  --graphite.port=2001 --requestheader ByPassReCaptcha:1677590802609 --slug Test_Demo --graphite.addSlugToKey true

_Originally posted by @Sudeep05 in https://github.com/sitespeedio/sitespeed.io/issues/1896#issuecomment-1485270329_

**Comment by soulgalore** [comment]
Hi @Sudeep05 I cannot reproduce it? 

I created a script that navigates to httpbin headers page that just echo:s the headers:
```
module.exports = async function (context, commands) {
  return commands.measure.start('http://httpbin.org/headers');
};
```

And then I run it like this:
`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:26.1.0 test.cjs --multi -n 1 --requestheader test:test`

Then I can see in the screenshot that the header exists:
![afterPageCompleteCheck](https://user-images.githubusercontent.com/540757/228010944-4b261493-25ea-418e-be1f-18c22d83a12d.png)

Best
Peter
