### ISSUE TITLE
Slack Links on sitespeed.io appear to be broken

### ISSUE THREAD

**Issue by jelias2** [sitespeedio/sitespeed.io#3802]
### Your question

Hello,
I'm greatly enjoying this project and all the resources that sitespeed.io provides for free! I was looking to dicuss some of my experiences with other users however the slack links from the sitespeed.io website appear to be broken. All of the slack links appear to redirect to https://sitespeedio.herokuapp.com/ which gives an error for me.

I'm just looking for the best place to discuss with other users, if that slack would some one please be able to post the invite link or update the sitespeed.io slack links. If its some other forum please let me know! 

Cheers, ty

**Comment by soulgalore** [comment]
Hi @jelias2 can you try: 
https://join.slack.com/t/sitespeedio/shared_invite/zt-1rwonkwzr-~xnGFm8_x3dJzpt3kvUGAg

That will work for 30 days, I'll try to fix the other link later.

Best
Peter

**Comment by OphyBoamah** [comment]
Hi @soulgalore. Can you kindly share a new invite link?
