### ISSUE TITLE
How to get aggregateassets/slowestassets/largestassets metrics

### ISSUE THREAD

**Issue by ushklianik** [sitespeedio/sitespeed.io#3815]
### Your question

Hi! 
I am trying to filter the metrics and send them to influxdb. But for some reason, no metrics are sent. 
Could you please share how to turn them on?

I use such rows in config:
```
"metrics": {
    "filter": [
       "*-",
       "aggregateassets.summary.*",
       "slowestassets.summary.*",
       "largestassets.summary.*"
    ]
  }
```

Using the following versions: 
nodejs: v18.14.2 
sitespeed.io: 27.3.0 
browsertime: 17.8.0 
coach: 7.1.3

Thanks!

**Comment by ushklianik** [comment]
Looks like it is disabled right now, could you please enable the sending of this metrics?
![image](https://user-images.githubusercontent.com/76432241/233021802-f7a348ba-cfc6-4e6e-b4b7-30b13f0af579.png)

**Comment by soulgalore** [comment]
I think its disabled for Graphite too, if you test on a web page that have ads, it will store too much data because those assets will change all the time.

**Comment by ushklianik** [comment]
> I think its disabled for Graphite too, if you test on a web page that have ads, it will store too much data because those assets will change all the time.

Thank you for answering! I got it. And is it possible, for example, to track the response time of assets for each category? Now I see possibility to track transferSize, contentSize, requests. but what about response time?

**Comment by soulgalore** [comment]
You can see the response time in the HAR/waterfall.
