### ISSUE TITLE
Getting  connect ETIMEDOUT 192.168.48.1:2003 error while running sitespeed.io

### ISSUE THREAD

**Issue by rahulanwekar23** [sitespeedio/sitespeed.io#3824]
I have configured sitespeed.io in my local as per steps mentioned in documentation. While running below command, I am getting below error:
Command:  docker run --rm -v "%cd%:/sitespeed.io" sitespeedio/sitespeed.io:27.3.1 --graphite.host=host.docker.internal https://www.telstra.com.au// --slug myFirstTest --graphite.addSlugToKey
P.S.: I have replaced $(pwd) with %cd% as I am running from windows

ERROR: Error: connect ETIMEDOUT 192.168.48.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

INFO: HTML stored in /sitespeed.io/sitespeed-result/myFirstTest/2023-05-03-01-29-04
Error: Errors while running:
Rejected {
  "uuid": "8b836b02-5210-4c0b-86b7-34e606285ca4",
  "type": "coach.pageSummary",
  "timestamp": "2023-05-03T01:30:06+00:00",
  "source": "coach",
  "data": "{...}",
  "url": "https://www.telstra.com.au//",
  "group": "www.telstra.com.au"
} for plugin: graphite, url: https://www.telstra.com.au//
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "9c7d0c7d-3a19-4097-abaf-b78fb83c76bb",
  "type": "pagexray.pageSummary",
  "timestamp": "2023-05-03T01:30:07+00:00",
  "source": "pagexray",
  "data": "{...}",
  "url": "https://www.telstra.com.au//",
  "group": "www.telstra.com.au"
} for plugin: graphite, url: https://www.telstra.com.au//
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "343d4ff6-5caf-4e32-b82e-20b9ba957bc8",
  "type": "browsertime.pageSummary",
  "timestamp": "2023-05-03T01:30:07+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://www.telstra.com.au//",
  "group": "www.telstra.com.au",
  "runTime": "2023-05-03 01:29:05"
} for plugin: graphite, url: https://www.telstra.com.au//
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "3b9414ec-4e99-4812-b21e-e6c3ce0655d1",
  "type": "thirdparty.pageSummary",
  "timestamp": "2023-05-03T01:32:18+00:00",
  "source": "thirdparty",
  "data": "{...}",
  "url": "https://www.telstra.com.au//",
  "group": "www.telstra.com.au"
} for plugin: graphite, url: https://www.telstra.com.au//
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "81d8e0b3-a304-42b4-8e0a-7003ebf85b2f",
  "type": "pagexray.summary",
  "timestamp": "2023-05-03T01:32:18+00:00",
  "source": "pagexray",
  "data": "{...}",
  "group": "www.telstra.com.au"
} for plugin: graphite
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "ba45fc8b-9662-4819-83c7-f3e35a94c899",
  "type": "coach.summary",
  "timestamp": "2023-05-03T01:32:18+00:00",
  "source": "coach",
  "data": "{...}",
  "group": "www.telstra.com.au"
} for plugin: graphite
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "0d32d629-deda-404d-985e-79ad00fcd034",
  "type": "browsertime.summary",
  "timestamp": "2023-05-03T01:32:18+00:00",
  "source": "browsertime",
  "data": "{...}",
  "group": "www.telstra.com.au"
} for plugin: graphite
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
Rejected {
  "uuid": "10f64f06-ad40-4d1f-8e42-23aed3e20489",
  "type": "largestassets.summary",
  "timestamp": "2023-05-03T01:32:18+00:00",
  "source": "assets",
  "data": "{...}",
  "group": "www.telstra.com.au"
} for plugin: graphite
{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"192.168.48.1","port":2003}
    at start (file:///usr/src/app/bin/sitespeed.js:31:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:62:1

**Comment by soulgalore** [comment]
Hi @rahulanwekar23 how's your Graphite setup? `--graphite.host=host.docker.internal` means that sitespeed.io will try to access Graphite on the same localhost? Do they share the same network? One way for you to debug is to go into the sitespeed.io container using https://www.sitespeed.io/documentation/sitespeed.io/docker/#inspect-the-container and then try to reach Graphite.

**Comment by rahulanwekar23** [comment]
Hi @soulgalore , yes graphite is in same localhost and I can access Grafana dashboard using http://127.0.0.1:3000/?orgId=1 but  my sitesepeed results are not getting populated in this dashboard

**Comment by soulgalore** [comment]
Yes,  but I'm not sure localhost inside the sitespeed.io container will point to Graphites it depends if you setup the Docker networks? The easiest thing is first to jump into the sitespeed.io container `docker run -it --entrypoint bash sitespeedio/sitespeed.io:27.3.1` then you can try `curl 127.0.0.1:2003`, if curl can't connect, sitespeed.io can't connect. Then try your servers ip instead and see if that works.

**Comment by rahulanwekar23** [comment]
Thanks @soulgalore , I tried to connect Graphites from container using curl but it is not accessible. So in that case how I can push my sitespeed result to Grafana dashboard. Is there any document which I can follow? 
As of now I am following below documents to setup Sitespeed in my local:
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/

**Comment by soulgalore** [comment]
I think the problem is that is that you use localhost inside the container. Either use the IP of your server or try add `--network=host`?

**Comment by rahulanwekar23** [comment]
I checked sample docker-compose file and it looks Graphite is mapped but don't know how to access:
Here is the content of docker-compose
version: '3'
services:
    grafana:
      image: grafana/grafana:9.4.7
      hostname: grafana
      depends_on:
        - graphite
      links:
        - graphite
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_SECURITY_ADMIN_USER=sitespeedio
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
        - GF_INSTALL_PLUGINS=grafana-piechart-panel
      volumes:
        - grafana:/var/lib/grafana
      restart: always
    graphite:
      image: sitespeedio/graphite:1.1.10-3
      hostname: graphite
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        # In production you should configure/map these to your container
        # Make sure whisper and graphite.db/grafana.db lives outside your containerr
        # https://www.sitespeed.io/documentation/sitespeed.io/graphite/#graphite-for-production-important
        - whisper:/opt/graphite/storage/whisper
        # Download an empty graphite.db from https://github.com/sitespeedio/sitespeed.io/tree/main/docker/graphite
        # - /absolute/path/to/graphite/graphite.db:/opt/graphite/storage/graphite.db
        # 
        # And put the configuration files on your server, configure them as you need
        # Download from https://github.com/sitespeedio/docker-graphite-statsd/tree/main/conf/graphite
        # - /absolute/path/to/graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        # - /absolute/path/to/graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        # - /absolute/path/to/graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
    grafana-setup:
      image: sitespeedio/grafana-bootstrap:24.5.0
      links:
        - grafana
      environment:
        - GF_PASSWORD=hdeAga76VG6ga7plZ1
        - GF_USER=sitespeedio
volumes:
    grafana:
    whisper:

**Comment by rahulanwekar23** [comment]
Hi @soulgalore 
Now I am getting another issue while runnint sitespeed.io:
PFA the screenshot
![image](https://user-images.githubusercontent.com/40842275/236962188-1b5b241a-2a48-4c40-befa-71462fd93fa0.png)

**Comment by rahulanwekar23** [comment]
Hi @soulgalore , I tried but nothing is working. Is it possible fro you to connect so that I can show you my setup. I have also referred your you tube video and did as per that but no luck.
