### ISSUE TITLE
Does sitespeed add user to host.

### ISSUE THREAD

**Issue by rsrahulsingh** [sitespeedio/sitespeed.io#3831]
### Your question

Hello Team,

The security team has flagged that a user named **sitespeedio** was added to one of our host. Can you confirm that sitespeed add this user or if it uses it?

**We had executed this command on the host:**

docker run --rm -v "$(pwd):/[sitespeed.io](http://sitespeed.io/)" sitespeedio/sitespeed.io:26.1.0  urls.txt --slug desktop_chrome_test --graphite.addSlugToKey true -n 5 --graphite.host==${ipaddress} --grphite.port 80 -b chrome

docker run --rm -v "$(pwd):/[sitespeed.io](http://sitespeed.io/)" sitespeedio/sitespeed.io:26.1.0  urls.txt --slug mobile_chrome_test --graphite.addSlugToKey true -n 5 --graphite.host=${ipaddress} --grphite.port 80  --browsertime.userAgent "Mozilla/5.0 (Linux; Android 10.0; S21+Ultra Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36" -b chrome

**Logs in question by security team:**

·  /usr/bin/containerd-shim-runc-v2 -namespace moby -address /run/containerd/containerd.sock -publish-binary /usr/bin/containerd -id ed9004ead2377ba50509062908f00408851d520a7852a91854caed0 start

·  /usr/bin/containerd-shim-runc-v2 -namespace moby -id ed9004ead2377ba5050733e8206290408851d520a7852a91854caed0 -address /run/containerd/containerd.sock

·  runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/ed9004ead2377ba5050933e820f00408851d520a7852a91854caed0/log.json --log-format json --systemd-cgroup create --bundle /run/containerd/io.containerd.runtime.v2.task/moby/ed9004ead2377ba505097203e82062908f00851d520a7852a91854caed0 --pid-file /run/containerd/io.containerd.runtime.v2.task/moby/ed9004ead2377ba50509720333e862908f008851d520a7852a91854caed0/init.pid ed9004ead2377ba50509720333e82062901d520a7852a91854caed0

·  /bin/bash /start.sh urls.txt --slug desktop_chrome_test --graphite.addSlugToKey true --graphite.host=${Hostip} --grphite.port 80 -b chrome

·  useradd --non-unique --uid 0 --gid 0 --home-dir /tmp sitespeedio

**·  New user 'sitespeedio' added**

Can you please confirm if this user is a service user of sitespped or something else?

Thanks,
Rahul.

**Comment by soulgalore** [comment]
Hi @rsrahulsingh there's a sitespeed-user inside the Docker container, checkout https://github.com/sitespeedio/sitespeed.io/blob/main/docker/scripts/start.sh#L43-L46
