### ISSUE TITLE
How to analysis different scenarios on same page (single page/same url)

### ISSUE THREAD

**Issue by hsuraweera** [sitespeedio/sitespeed.io#3848]
### Your question

I have to test a web application. 

- The first navigation is the login which is not needed to be analyzed.
- The second one is launching the application. Which is needed to be tested as flow 01.
- The third navigation is happening when I clicked on a dropdown item after launching the application. It is needed to be analyzed as flow 02.

The issue is that the URL is not getting while it is clicking on a discipline. The URL will be same for the flow 01 and flow 02. Because of that, I get the report for only flow 01.

Is there any way to handle this kind of scenario with sitespeed.io, please?

**Comment by soulgalore** [comment]
Hi @hsuraweera as long as it is navigations you can use alias for an URLs checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestarturl-alias and https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestartalias - would that work in your use case?

**Comment by hsuraweera** [comment]
Hi, @soulgalore thanks for the reply!
I tried them but in my case, the application is not navigating. Even when we select the dropdown item, it is only changing the components in the application. So all the time, the URL is the same.

**Comment by dxrobinson** [comment]
I have the same situation you met and tried this way, if the flow02 can be measured after flow01, I mean you don't care measure start from blank, you can just measure.stop and measure.start(new_alias) and stop after flow finish.

**Comment by soulgalore** [comment]
There's not any super solution for this at the moment, but I think following what @dxrobinson is good. Early next year I will start to implement soft navigations for Chrome and maybe that will make things better.
