### ISSUE TITLE
Error: Require summary page metrics to be from given array

### ISSUE THREAD

**Issue by Awradz** [sitespeedio/sitespeed.io#3849]
Hello dear, 

I'm trying to configure summary page metrics in a json file and it's not working with me, this is my json file looks like: 

{

    "html": 
      { "pageSummaryMetrics":[    
        "timings.pageLoadTime",
        "webpagetest.TTFB",
        "requests.total",
        "transferSize.total",
        "googleWebVitals.interactionToNextPaint",
        "googleWebVitals.totalBlockingTime",
        "timings.serverResponseTime",
        "requests.httpErrors",
        "thirdParty.requests",
        "score.performance",
        "googleWebVitals.timeToFirstByte"
    ] }

}

and this is my command:

docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:27.6.2 MazadLogin.js --multi --browsertime.urls https://xxx/home/auctions --browsertime.urls https://xxx/home/groups --browsertime.urls https://xxx/home/faq --browsertime.urls https://xxx/home/contactus **--html.pageSummaryMetrics pageSummaryMetrics.json --html.showScript** -n 1 

Please advise me on the above.

Regards,

**Comment by soulgalore** [comment]
Hi @Awradz can you share a little bit how you see that it do not work our do you get an error?

I did try with this:
test.json
```
{
    "html": {
        "pageSummaryMetrics": [
            "timings.pageLoadTime",
            "webpagetest.TTFB",
            "requests.total",
            "transferSize.total",
            "googleWebVitals.interactionToNextPaint",
            "googleWebVitals.totalBlockingTime",
            "timings.serverResponseTime",
            "requests.httpErrors",
            "thirdParty.requests",
            "score.performance",
            "googleWebVitals.timeToFirstByte"
            ]
    }
}
```
 Then the page looks like this for me:
<img width="1534" alt="Screenshot 2023-05-18 at 13 48 37" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/4c90ed2f-1808-4eac-b214-f73137b42a25">

**Comment by dxrobinson** [comment]
did this problem solved? I also want to custom the page summary metrics, but got the same error "Error: Require summary page metrics to be from given array".
It seems only can choose some of them instead of add new ones. @soulgalore how did you use it to generate the screenshot like you replied?

thanks for replying, I really need this function.

**Comment by dxrobinson** [comment]
> Hi @Awradz can you share a little bit how you see that it do not work our do you get an error?
> 
> I did try with this: test.json
> 
> ```
> {
>     "html": {
>         "pageSummaryMetrics": [
>             "timings.pageLoadTime",
>             "webpagetest.TTFB",
>             "requests.total",
>             "transferSize.total",
>             "googleWebVitals.interactionToNextPaint",
>             "googleWebVitals.totalBlockingTime",
>             "timings.serverResponseTime",
>             "requests.httpErrors",
>             "thirdParty.requests",
>             "score.performance",
>             "googleWebVitals.timeToFirstByte"
>             ]
>     }
> }
> ```
> 
> Then the page looks like this for me: <img alt="Screenshot 2023-05-18 at 13 48 37" width="1534" src="https://user-images.githubusercontent.com/540757/239226020-4c90ed2f-1808-4eac-b214-f73137b42a25.png">

what's the command and version you used? why I only got error"Error: Require summary page metrics to be from given array"

**Comment by dxrobinson** [comment]
problem solved using config.json file, or just use multiple times of passing arguments
