### ISSUE TITLE
Couldn't load plugin /lighthouse: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/src/app/lib/plugins/lighthouse/index.js' imported from /usr/src/app/lib/core/pluginLoader.js

### ISSUE THREAD

**Issue by Awradz** [sitespeedio/sitespeed.io#3854]
### Your question

Hello dear, 

I'm trying to add lighthouse plugin but there is an error occurred while typing this command: 

docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:27.6.2 MazadLogin.js --multi --browsertime.urls https://xxx/home/auctions --browsertime.urls https://xxx/home/groups --browsertime.urls https://xxx/home/faq --browsertime.urls https://xxx/home/contactus --html.pageSummaryMetrics timings.pageLoadTime --html.pageSummaryMetrics webpagetest.TTFB --html.pageSummaryMetrics webpagetest.TTFB --html.pageSummaryMetrics requests.total --html.pageSummaryMetrics transferSize.total --html.pageSummaryMetrics googleWebVitals.interactionToNextPaint --html.pageSummaryMetrics googleWebVitals.totalBlockingTime --html.pageSummaryMetrics timings.serverResponseTime --html.pageSummaryMetrics requests.httpErrors --html.pageSummaryMetrics thirdParty.requests --html.pageSummaryMetrics score.performance --html.pageSummaryMetrics googleWebVitals.timeToFirstByte --html.showScript --plugins.add analysisstorer --plugins.add /lighthouse -n 1

and the error as shown below: 

Couldn't load plugin /lighthouse: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/src/app/lib/plugins/lighthouse/index.js' imported from /usr/src/app/lib/core/pluginLoader.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/lighthouse' imported from /usr/src/app/lib/core/pluginLoader.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at loadPlugins (file:///usr/src/app/lib/core/pluginLoader.js:76:37)
    at async run (file:///usr/src/app/lib/sitespeed.js:129:26)
    at async start (file:///usr/src/app/bin/sitespeed.js:131:22)
    at async file:///usr/src/app/bin/sitespeed.js:177:1 {
  code: 'ERR_MODULE_NOT_FOUND'
}

Could you please advise?

**Comment by soulgalore** [comment]
Hi @Awradz you need to run the Lighthouse container (if you don't install the Lighthouse plugin yourself in the container) that is named ` sitespeedio/sitespeed.io:27.6.4-plus1 ` and then the correct path to the plugin ins /lighthouse/index.js - I've seen that one page in the documentation was pointing to the wrong path, I'll fix that now.

`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:27.6.4-plus1 https://www.sitespeed.i --plugins.add /lighthouse/index.js`

Best
Peter

**Comment by Awradz** [comment]
Hello Peter,

Appreciate you time and efforts. I tried the command above and the error disappeared, how ever, I can't see lighthouse tab in the page summary. 

<img width="919" alt="page summary" src="https://github.com/sitespeedio/sitespeed.io/assets/60400619/aa7dc119-f90d-4e4b-b15e-3923b293aff2">

One more questions, can I get benefit of one of the reads provided by lighthouse such as "Time to interactive" which they are not provided by sitespeed.io and customize it in the "pages" page ?

<img width="912" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/60400619/7b61967a-4502-420b-990b-e5e57df2ae75">

As shown in the picture above why "WebPageTest TTFB" is always giving zero value? I tried to do multiple iterations but same result occurred overtime however, the reads is appearing in the powershell during the execution for each iteration.

<img width="955" alt="powershell" src="https://github.com/sitespeedio/sitespeed.io/assets/60400619/aa666929-38b6-4b92-85e8-2e023be04900">

**Comment by soulgalore** [comment]
Hi @Awradz Lighthouse only runs when you do a first view test, not for a user journey.

For WebPageTest TTFB you need to run your test with WebPageTest. To get TTFB from Browsertime you can use `timings.backEndTime` (I'll fix add an alias for TTFB to that metric in next release so it's easier to understand).

> "Time to interactive" 

I don't use that metrics see https://github.com/sitespeedio/sitespeed.io/issues/3024#issuecomment-638795828. (you can get it from sitespeed.io if you use Firefox though since they have a native implementation). For other Lighthouse metrics, no they are not available as summaries.

Best
Peter
