### ISSUE TITLE
Threshold range in Summary Limits 

### ISSUE THREAD

**Issue by Awradz** [sitespeedio/sitespeed.io#3856]
### Your question

Hello @soulgalore,

I'm obsessed with sitespeed.io and I'm in the phase of discovering it right now, I wanna know if it's possible to apply a range for my threshold instead of static value? 

for example: 

[
    {
        "transferSize": {
            "total": { 
                "green": "Between 1-2 MB", 
                "yellow": 3,
                "red" : "More than 3MB"
            }
        }
    }
    
]

**Comment by Awradz** [comment]
Dear @soulgalore, 

Could you please advise? 

Regards,
Awrad

**Comment by soulgalore** [comment]
Hi @Awradz sorry I missed this issue. Check out the documentation here: https://www.sitespeed.io/documentation/sitespeed.io/configure-html/#configure-the-thresholds-for-redyellowgreen-summary-boxes

In your case, if I remember correctly the size is in bytes.

Best
Peter

**Comment by Awradz** [comment]
Hi @soulgalore, 

It's ok no worries.

Thanks for your reply, I've seen the documentation mentioned above however, I would like to know if I can apply this logic to my configuration file same as this example below?

[
{
"transferSize": {
"total": {
"green": **1000000<totalTransferSize<2000000**,
"yellow": **3000000<totalTransferSize<4000000**,
"red" : **totalTransferSize>4000000**
}
}
}

]


Thanks!
Awrad

**Comment by soulgalore** [comment]
Hi again, you only configure the limits for green and yellow and the red in your case will be everything above the yellow limit.

```json
{
    "transferSize": {
        "total": { 
            "green": 2000000, 
            "yellow": 4000000 
        }
    }
}
```

Best
Peter

**Comment by soulgalore** [comment]
Hope that configuration helped you out!
