### ISSUE TITLE
pulling sitespeed image (27.6.4) from Quay.io is failing

### ISSUE THREAD

**Issue by manjunathpremkumar** [sitespeedio/sitespeed.io#3862]
Below are steps to reproduce
Step1) Creating Image and pushing it to Quay.io
Docker file,
FROM sitespeedio/sitespeed.io:27.6.4

RUN apt-get update

RUN rm -rf /usr/local/bin/wpr; rm -rf /usr/src/app/docker/webpagereplay/wpr; rm -rf /usr/src/app/docker/webpagereplay/linux/amd64/wpr; rm -rf /usr/src/app/docker/webpagereplay/linux/arm64/wpr

Step2) create a AMI in AWS , while trying to pull the image from Quay.io

- name: Quay.io login
  command: docker login -u={{ quay_username }} -p={{ quay_password }} quay.io
  register: result
  failed_when: '"Login Succeeded" not in result.stdout'

- name: Pull image
  command: docker pull {{ quay_sitespeedio_image }}
  vars:
    ansible_command_timeout: 600
  register: result
  failed_when:
    - "'Status: Downloaded' not in result.stdout"
    - "'Image is up to date' not in result.stdout"
  changed_when:
    - "'Status: Downloaded' in result.stdout"

Step3) Getting error

amazon-ebs-sitespeed.amazon-ebs.this: fatal: [default]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "quay.io/domain/sitespeedio:27.6.4-Habac091"], "delta": "0:00:04.078315", "end": "2023-05-26 11:32:21.231523", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2023-05-26 11:32:17.153208", "stderr": "Could not reach any registry endpoint", "stderr_lines": ["Could not reach any registry endpoint"], "stdout": "Trying to pull repository quay.io/domain/sitespeedio ... \nPulling repository quay.io/domain/sitespeedio", "stdout_lines": ["Trying to pull repository quay.io/domain/sitespeedio ... ", "Pulling repository quay.io/domain/sitespeedio"]}

Note - Found that manifest file was not available for this image in Quay.io repo

Troubleshooting
Trial1 - Checked the docker version, had latest version installed, still same error
Tiral2 - Increased the EBS root volume space if that is problem why this is erroring out, still same error
Trial3- Did same exercise with 26.1.0 version perfectly worked. Able to create AMI

OS used - RHEL7.9

Any help will be much appreciated

**Comment by manjunathpremkumar** [comment]
@soulgalore

**Comment by soulgalore** [comment]
Hi @manjunathpremkumar I haven't used Quay.io, there's no documentation on how to do it on their side?

**Comment by manjunathpremkumar** [comment]
Hi @soulgalore - looks like manifest file missing is the issue here...when we try  using the Jenkin CI/CD pipeline to create and push the image to quay (manifest file was not created, this happened only for 27.6.4 version whereas when we tried for 26.1.0 older version it was successfully creating the image with manifest file in quay.io)  .. As a work around we  manually pulled the sitespeed images from quay( for 27.6.4 version where manifest files were missing)  to local Rhel instance and re-tag it and push it to Quay repo (manifest files got generated)... then we were able to  proceed with next steps that is to pull the image in jenkin CI/CD pipeline to build AMI in AWS.

**Comment by soulgalore** [comment]
Hi @manjunathpremkumar ah thanks for sharing. We build the container with a GitHub action that pushes it to the Docker hub but then something is broken there, let me have a look this weekend and try to fix it for the next release.

**Comment by manjunathpremkumar** [comment]
Thank you

**Comment by soulgalore** [comment]
Hi @manjunathpremkumar thanks, you can try with 27.6.5 that was newly released, I tried it and I could the manifest. There was a couple of things: I hade not updated the Docker build actions in half a year and it seems like that broke it + for some users the new SLSA Provenanc fixed in https://github.com/docker/build-push-action/releases/tag/v4.0.0 seems to been a problem (I've turned that off now).

> Buildx v0.10 enables support for a minimal [SLSA Provenance](https://slsa.dev/provenance/) attestation, which requires support for [OCI-compliant](https://github.com/opencontainers/image-spec) multi-platform images. This may introduce issues with registry and runtime support (e.g. https://github.com/docker/buildx/issues/1533). You can optionally disable the default provenance attestation functionality using provenance: false.

**Comment by manjunathpremkumar** [comment]
Thanks a lot, will try on 27.6.5

**Comment by manjunathpremkumar** [comment]
@soulgalore  - 27.6.5 worked well with pull request from Quay and even manifest file got generated. Thanks. 
We found issues to trigger the test in pipeline and on instance as well, below is command manually executed on the instance

Command executed - sudo docker run --rm quay.io/dummy/sitespeedio:27.6.5 -b chrome https://www.sitespeed.io/ 
or
sudo docker run --shm-size=2g --rm -v /sitespeed.io:/sitespeed.io:Z quay.io/dummy/sitespeedio:27.6.5 -b chrome https://www.sitespeed.io/

Error
node[28]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7a940 node::Abort() [node]
 2: 0xb7a9be  [node]
 3: 0xbe98be  [node]
 4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb395ab node::Start(int, char**) [node]
 7: 0x7fb099ff5d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fb099ff5e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xabbdee _start [node]
/start.sh: line 52:    28 Aborted                 (core dumped) chroot --skip-chdir --userspec='sitespeedio:sitespeedio' / node "$@"

**Comment by manjunathpremkumar** [comment]
Thanks, currently we are not able to upgrade from Docker 1.18 version..in next month will try on them RHELOS 8.7 and podman CE..

**Comment by soulgalore** [comment]
I think the rest of the issues was not related to sitespeed.io so closing.
