### ISSUE TITLE
How we can ingest existing chrome HAR to sitepeed.io

### ISSUE THREAD

**Issue by rahulanwekar23** [sitespeedio/sitespeed.io#3866]
### Your question

Hi Team,
Do we have any approach using we can import existing Chrome HAR file Sitespeed.io?

**Comment by soulgalore** [comment]
Hi @rahulanwekar23 I created https://bugs.chromium.org/p/chromium/issues/detail?id=1276896 a couple of years ago hoping that the Chrome team could implement a way to get a HAR file from Chrome.
