### ISSUE TITLE
Just a question ... 

### ISSUE THREAD

**Issue by MartinWolfert** [sitespeedio/sitespeed.io#3870]
Hi,
just to get it right :)

the "co2PerPageView" output from sitespeedio returns the unit "CO2e"?
This is at least my conclusion after studying the contents of the following pages:

1. https://developers.thegreenwebfoundation.org/co2js/explainer/methodologies-for-calculating-website-carbon/
2. https://sustainablewebdesign.org/calculating-digital-emissions/

right?
Or have I misunderstood something?

Best,
Martin

**Comment by soulgalore** [comment]
Hi @MartinWolfert sorry for not getting back earlier, yes CO2E =  CO2 emissions, that is correct.

Best 
Peter

**Comment by MartinWolfert** [comment]
Thy!  :)
