### ISSUE TITLE
Cant't get custom data in grafana

### ISSUE THREAD

**Issue by FrankWang117** [sitespeedio/sitespeed.io#3877]
### Your question

I create a custom data in some preScripts like this:
```js
module.exports = async function (context, commands) {
    const fileCount = 297;

    context.log.info('file count', fileCount)
    commands.measure.add('testFileCount', fileCount);
};

```
I see this log in terminal: 
![image](https://github.com/sitespeedio/sitespeed.io/assets/21688648/87844826-b647-4ac5-b6db-2f67fa4bb911)
and I see this data in html file:
![image](https://github.com/sitespeedio/sitespeed.io/assets/21688648/9c0b2e10-6fae-4eba-b159-09bed2248cf2)

but I want use it in grafana (data source is graphite), and I cound't find it in new panel's Query:
![image](https://github.com/sitespeedio/sitespeed.io/assets/21688648/a47d3834-d943-47f0-bfc4-9b1cd38f0b5e)

How do I pass this data to graphite?

**Comment by soulgalore** [comment]
Hi @FrankWang117 it should be passed on automatically under` ...statistics.custom.testFileCount`. If you use one of the default dashboards it should be `$base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.custom.testFileCount`

Can you find it there?

Best
Peter

**Comment by FrankWang117** [comment]
@soulgalore Yes! I found it.Thank you very much. 👍🏼  by the way, `custom` Now it should be `extras` 
![image](https://github.com/sitespeedio/sitespeed.io/assets/21688648/afb713d2-c2b3-42bc-809d-c9c214a2f7b1)

**Comment by soulgalore** [comment]
Ah thanks I'll go through the documentation and update it.
