### ISSUE TITLE
got error when use config.json file

### ISSUE THREAD

**Issue by dxrobinson** [sitespeedio/sitespeed.io#3881]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io

### What are you trying to accomplish

$ sitespeed.io https://www.sitespeed.io --config ./config.json 
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at open (node:internal/fs/promises:538:10)
    at readFile (node:internal/fs/promises:909:20)
    at parseCommandLine (file:///C:/Users/zhaoyang18/AppData/Roaming/npm/node_modules/sitespeed.io/lib/cli/cli.js:2060:13)
    at start (file:///C:/Users/zhaoyang18/AppData/Roaming/npm/node_modules/sitespeed.io/bin/sitespeed.js:119:22)
    at file:///C:/Users/zhaoyang18/AppData/Roaming/npm/node_modules/sitespeed.io/bin/sitespeed.js:178:7 {
  code: 'ERR_INVALID_URL_SCHEME'
}

Node.js v18.16.0

### What browser did you use?

Chrome

### How to reproduce

```shell
just run it in windows platfrom
```

**Comment by dxrobinson** [comment]
Take a quick look of the source code, I just change the readfile of config file to readfileSync, and it works well.
I did not look into it why, please help me out later, otherwise I need maintain a version by myself, that really not what a want. thanks a lot.

**Comment by soulgalore** [comment]
Hi @dxrobinson yeah that looks like bug, hmm, we have some tests for that but it seems broken, let me have a look.

**Comment by dxrobinson** [comment]
> Hi @dxrobinson yeah that looks like bug, hmm, we have some tests for that but it seems broken, let me have a look.

Hi Peter,

My job is a tester, so really great to find a bug for you  :  )
