### ISSUE TITLE
[Scripting] Can't run js script

### ISSUE THREAD

**Issue by Amerousful** [sitespeedio/sitespeed.io#3885]
**How to resolve issue with `export`?**

Hello! 

I have some issue with run js script. Version: 27.9.0
I wrote script by your [examples](https://www.sitespeed.io/documentation/sitespeed.io/scripting/).
`script.mjs`:
```js
export default async function (context, commands) {
    await commands.navigate(
        'https://www.sitespeed.io/documentation/'
    );

    context.log.info('Info logging from your script');
}
```
Command for run:
```bash
sitespeed.io https://www.sitespeed.io/ --script script.mjs -n 1 
```
Error:
```
ERROR: Couldn't execute script named script.mjs error:JavascriptError: javascript error: Unexpected token 'export'
  (Session info: chrome=114.0.5735.106)
ERROR: Failed to execute user script: JavascriptError: javascript error: Unexpected token 'export'
  (Session info: chrome=114.0.5735.106)
ERROR: Unhandled value type undefined found when adding data for custom 
```

**Comment by soulgalore** [comment]
Hi @Amerousful what NodeJS version are you using? We support latest LTS: https://nodejs.org/

Best
Peter

**Comment by Amerousful** [comment]
@soulgalore Thank you for your prompt response!
```
node -v 
v19.5.0
```

Okay, I'm updating to the latest version.

**Comment by Amerousful** [comment]
Hm, I checked docker image `27.9.1` and here `nodejs: v18.16.0`
Command:
```bash
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:27.9.1 https://www.sitespeed.io/ --script script.mjs -n 1
```
Output:
```bash
INFO: Versions OS: linux 5.15.49-linuxkit-pr nodejs: v18.16.0 sitespeed.io: 27.9.1 browsertime: 17.11.1 coach: 7.2.0

```

**Comment by Amerousful** [comment]
I found several different behaviours when it **works** 
1) `.mjs` + `export default` + `multi`
cmd: ```docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io test.mjs --multi -n 1```
script: ```export default async function...```

2) `.js` + `module.exports` + `multi`
cmd: ```docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io test.js --multi -n 1```
script: ```module.exports = async function...```

**Remark**: I have no clue why we should use `--multi` for these cases above...

***
In this case `--multi` it makes sense to use
3) `.js` + `module.exports` + `multi` + url 
cmd: `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io test.js --multi -n 1`

**Comment by soulgalore** [comment]
Hi, 16 and 18 is LTS https://github.com/nodejs/release#release-schedule but I wonder if there's something else because we have tests for 20 that passes.

I wonder if someone another version is picked up? I'll check tonight. Versions before v14.13.0 should gives that error.

**Comment by Amerousful** [comment]
Thanks!

Here you are commands for fast reproduce:
```bash
echo "module.exports = async function (context, commands) {context.log.info('Info logging from your script');}" | tee module_export.{js,mjs}
echo "export default async function (context, commands) {context.log.info('Info logging from your script');}" | tee export_default.{js,mjs}

sitespeed.io https://www.sitespeed.io --script export_default.js -n 1
sitespeed.io https://www.sitespeed.io --script export_default.mjs -n 1
sitespeed.io https://www.sitespeed.io --script export_default.js -n 1
sitespeed.io https://www.sitespeed.io --script module_export.mjs -n 1


docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io --script export_default.js -n 1
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io --script export_default.mjs -n 1
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io --script export_default.js -n 1
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io --script export_default.mjs -n 1
```

**Comment by soulgalore** [comment]
Ah I see now, thanks for sharing the examples!

The `--script `flag is the flag to point out a JavaScript to collect a custom metric. If you check --help you will see: `Add custom Javascript to run after the page has finished loading to collect metrics. If a single js file is specified, it will be included in the category named "custom" in the output json. Pass a folder to include all .js scripts in the folder, and have the folder name be the category. Note that --script can be passed multiple times.`. That JacaScript will run inside the browser, accessing the page that you test and need to return something (that will be the custom metric).

https://www.sitespeed.io/documentation/sitespeed.io/scripting/ is the way to navigate a page and do user journeys. The names (script/scripting) is almost the same so its confusing.

**Comment by Amerousful** [comment]
Oops, just made incorrect assumptions about all of these options. 
Now I understand, `--script` it's only about running inside a browser and now it's clear why there were errors about `module.exports` / `export default`
Honestly, you've written amazing documentation. Sorry that I waste your time
Peter, thanks for your patience and help!
