### ISSUE TITLE
How to delete test data in graphite?

### ISSUE THREAD

**Issue by FrankWang117** [sitespeedio/sitespeed.io#3887]
### Your question

I'm using Graphite and Grafana.
and I have some test data in grafana panel,like this:
![image](https://github.com/sitespeedio/sitespeed.io/assets/21688648/a8bb0e3e-2fc9-433d-bc98-9c07d9b0c144)
How can I delete these data?

**Comment by soulgalore** [comment]
Hi @FrankWang117 sorry I missed this issue. Graphite store metrics on file, so each part of the key is a folder, so you need to login to the Graphite server and manually delete the metrics (folders and files).
