### ISSUE TITLE
Graphite deployment in production for performance dashboard

### ISSUE THREAD

**Issue by Msarma93** [sitespeedio/sitespeed.io#3889]
### Your question

I have deployed grafana and graphite instances in a kubernetes namespace and hosted respective urls.
However, now while pushing metrics to graphite from sitespeed using the graphite url,  I see error [2023-06-22 06:35:28] ERROR: Error: connect ECONNREFUSED <ip>:<port>.
I have passed --graphite.host as the graphite ingress url.
Please help me with a solution here.

Thanks!

**Comment by soulgalore** [comment]
Hi @Msarma93 I guess maybe the port isn't open on the server for that port 2003? You can try that without sitespeed.io just sending a dummy metric to Graphite.

There's documentation here: https://graphite.readthedocs.io/en/latest/feeding-carbon.html
`echo "test.bash.stats 42 `date +%s`" | nc graphite.example.com 2003`

**Comment by Msarma93** [comment]
Hi @soulgalore , Thank you for your input. I have resolved the above issue . I have graphite and grafana both up and running in two different pods and able to successfully push data to graphite from sitespeed. 
However, now I do not see the default dashboards in grafana production as I had seen in local. I believe the grfana/bootstrap image is to be executed. I am a bit confused about the value "GF_API - path to the Grafana API (default: ["http://grafana:3000/api"]". For Example,if my grafana ingress url is <example.com>. What would be the GF_API  value.

**Comment by Msarma93** [comment]
Hi @soulgalore , The setup is completed and is successfully live on  the kubernetes namespace. Thank You for your help again.
