### ISSUE TITLE
[Plugins] S3: how to provide aws_session_token

### ISSUE THREAD

**Issue by Amerousful** [sitespeedio/sitespeed.io#3891]
Hey there! 

I have problem with uploading results to AWS S3.
Is there any way to provide `AWS_SESSION_TOKEN` ?https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

**Comment by soulgalore** [comment]
Hi @Amerousful it looks like it should be picked up automatically if you export it https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html - can you try and see if that works?

**Comment by Amerousful** [comment]
@soulgalore
I tried to use exported credentials, but it didn't work. However, I was able to identify the issue - the **same** credentials which were defined in a [config](https://www.sitespeed.io/documentation/sitespeed.io/s3/#json-configuration-file) are causing some sort of disruption.
If remove the username and the secret from the config, it will work.

**Comment by soulgalore** [comment]
Great that you found it.
