### ISSUE TITLE
Sitespeed Unable to capture exact page load time

### ISSUE THREAD

**Issue by mahesharravally** [sitespeedio/sitespeed.io#3904]
While I'm using Selenium integrated nodejs sitespeed application
For our project in which.                          manual time is 15 to 18 seconds  
rom Dev tools like network calls lighthouse  time is  14 to 18 seconds
  But from sitespeed application it's giving time is 9 to 13 seconds by which I'm saying that sitespeed unable capture exact load time of a page  if any solution please let us know
Presently I'm using sitespeed application with selenium integrated nodejs with script.js file
And command as below
C:\\Users\\INARMAH2\\Downloads\\ARM_61_Mahesh_By_Locators1.js
![Screenshot (292)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/c7dba7c5-7b37-4491-8d33-138ff4009031)
![Screenshot (293)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/510ed0a1-1a78-4b90-b8c2-ad08593f59ca)
![Screenshot (291)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/3a174292-6e15-496c-947c-916d3fa93d4f)
![tmp_c2c9f849-bf4b-42d4-8671-6de6729c4ce4](https://github.com/sitespeedio/sitespeed.io/assets/134609751/0d91a179-6185-43ae-9ef6-2e62b38f8040)
![tmp_d89b7764-13b9-4153-baf4-f85bef67fd9e](https://github.com/sitespeedio/sitespeed.io/assets/134609751/e3687a57-7273-4c22-a2c9-855d98d8af16)
![tmp_61f3b81f-ea78-4f08-82e3-3a4ccecfaa10](https://github.com/sitespeedio/sitespeed.io/assets/134609751/994bc1ed-8b1c-4cde-93be-601b6f9ca8e6)

**Comment by mahesharravally** [comment]
Please give solution have another issue with double click is not working fine

**Comment by soulgalore** [comment]
Hi @mahesharravally thanks for creating the issue. 

I don't follow/understand what you show with the screenshots, can you please elaborate why you think Lighthouse show the right numbers and sitespeed.io wrong numbers? Do you run the tests with the same setup or how do you compare?

**Comment by soulgalore** [comment]
Never got anything back so closing.
