### ISSUE TITLE
Annotation timestamps

### ISSUE THREAD

**Issue by lrojash** [sitespeedio/sitespeed.io#3905]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [x] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://metricfire.com https://hostedgraphite.com https://ringcaptcha.com

### What are you trying to accomplish

I am using npm to run sitespeed locally with 3 urls:
https://metricfire.com https://hostedgraphite.com https://ringcaptcha.com

The timestamp issues was address through these PR's:
[https://github.com/sitespeedio/sitespeed.io/pull/3901](url)
[https://github.com/sitespeedio/sitespeed.io/pull/3900](url)

This fix the issue for the most part but it comes back after a few runs. Please refer the the example below:
![New dashboard - Grafana 2023-07-14 at 10 09 00 AM](https://github.com/sitespeedio/sitespeed.io/assets/67330937/f3829c57-a508-4a27-b13c-1e5fe260ee8e)
 
I didn't mark it but it also happened between the time 09:25-09:30 where only 1 and then only 2 came through.

Is there a downtime, or another param we need to add to avoid this from happening, or is there still bug around causing the inconsistency?

(Thanks for the help you guys have provided to the Metricfire team, we appreciate it!)

### What browser did you use?

Chrome

### How to reproduce

```shell
bin/sitespeed.js https://metricfire.com https://hostedgraphite.com https://ringcaptcha.com \
  --graphite.host carbon.hostedgraphite.com
  --graphite.port 2003
  --graphite.namespace <api-key>.sitespeed_io.default
  --graphite.webHost www.hostedgraphite.com
  --graphite.proxyPath /api/v1/graphite/events/
  --graphite.httpPort 443
  --graphite.auth '<api-key>:'
  --graphite.sendAnnotation true
  --slug hg
  --graphite.addSlugToKey true
  --resultBaseURL https://fake.usagibox.com -n 1 -vvv
```

### Relevant log output

```shell
case when only one annotation came through:

[2023-07-14 09:24:06] DEBUG: [sitespeedio.plugin.graphite] Using auth for Graphite
[2023-07-14 09:24:06] VERBOSE: [sitespeedio.plugin.graphite] Send annotation to Graphite: "{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"53b25d29-acf4-407e-8c35-33fc265654b1\",\"sitespeed_io\",\"metricfire_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-09-23-44/pages/metricfire_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689348224}"

[2023-07-14 09:24:22] DEBUG: [sitespeedio.plugin.graphite] Using auth for Graphite
[2023-07-14 09:24:22] VERBOSE: [sitespeedio.plugin.graphite] Send annotation to Graphite: "{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"53b25d29-acf4-407e-8c35-33fc265654b1\",\"sitespeed_io\",\"hostedgraphite_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-09-23-44/pages/hostedgraphite_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689348224}"

[2023-07-14 09:24:39] DEBUG: [sitespeedio.plugin.graphite] Using auth for Graphite
[2023-07-14 09:24:39] VERBOSE: [sitespeedio.plugin.graphite] Send annotation to Graphite: "{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"53b25d29-acf4-407e-8c35-33fc265654b1\",\"sitespeed_io\",\"ringcaptcha_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-09-23-44/pages/ringcaptcha_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689348224}"

case where two annotations came through:

23-07-14 10:15:19] DEBUG: [sitespeedio.plugin.graphite] Using auth for Graphite
[2023-07-14 10:15:19] VERBOSE: [sitespeedio.plugin.graphite] Send annotation to Graphite: "{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"53b25d29-acf4-407e-8c35-33fc265654b1\",\"sitespeed_io\",\"metricfire_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-10-15-01/pages/metricfire_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689351304}"

[2023-07-14 10:15:34] DEBUG: [sitespeedio.plugin.graphite] Using auth for Graphite
[2023-07-14 10:15:34] VERBOSE: [sitespeedio.plugin.graphite] Send annotation to Graphite: "{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"53b25d29-acf4-407e-8c35-33fc265654b1\",\"sitespeed_io\",\"hostedgraphite_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-10-15-01/pages/hostedgraphite_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689351301}"

[2023-07-14 10:15:53] DEBUG: [sitespeedio.plugin.graphite] Using auth for Graphite
[2023-07-14 10:15:53] VERBOSE: [sitespeedio.plugin.graphite] Send annotation to Graphite: "{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"53b25d29-acf4-407e-8c35-33fc265654b1\",\"sitespeed_io\",\"ringcaptcha_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-10-15-01/pages/ringcaptcha_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689351301}"
```

**Comment by soulgalore** [comment]
Hi @lrojash hmm ok, I can not reproduce it, can you verify that you run the latest version in the main branch?

If I run like this:
```bin/sitespeed.js --resultBaseURL https://www.example.com --graphite.host 127.0.0.1 https://metricfire.com https://hostedgraphite.com https://ringcaptcha.com -n 1 --graphite.port 62522  --slug hg --graphite.sendAnnotation true ```

I can see that I get three different timestamps for the annotations:

```
{"what": "28.2.0 - 114.0.5735.198", "tags": ["native","chrome","sitespeed_io","default","metricfire_com","_","hg"], "data": "<a href='https://www.example.com/hg/2023-07-14-23-14-08/pages/metricfire_com/index.html' target='_blank'>Result 1 run</a>", "when": 1689369250}
{"what": "28.2.0 - 114.0.5735.198", "tags": ["native","chrome","sitespeed_io","default","hostedgraphite_com","_","hg"], "data": "<a href='https://www.example.com/hg/2023-07-14-23-14-08/pages/hostedgraphite_com/index.html' target='_blank'>Result 1 run</a>", "when": 1689369279}
{"what": "28.2.0 - 114.0.5735.198", "tags": ["native","chrome","sitespeed_io","default","ringcaptcha_com","_","hg"], "data": "<a href='https://www.example.com/hg/2023-07-14-23-14-08/pages/ringcaptcha_com/index.html' target='_blank'>Result 1 run</a>", "when": 1689369296}
```
Best
Peter

**Comment by lrojash** [comment]
Hi Peter,

Yes I am running from the latest version in the main branch.

Did another git pull just in case and ran the tests again and got the same result two have the same timestamps resulting in only two of the annotations getting sent:
![New dashboard - Grafana 2023-07-14 at 5 10 51 PM](https://github.com/sitespeedio/sitespeed.io/assets/67330937/6f7a592d-92bf-4af2-b737-5f90444f384a)

`"{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"33fc265654b1\",\"sitespeed_io\",\"hostedgraphite_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-17-05-55/pages/hostedgraphite_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689375955}"`

`{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"33fc265654b1\",\"sitespeed_io\",\"ringcaptcha_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-17-05-55/pages/ringcaptcha_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689375955}`

`{\"what\": \"28.2.0 - 114.0.5735.198\", \"tags\": [\"native\",\"chrome\",\"33fc265654b1\",\"sitespeed_io\",\"metricfire_com\",\"_\",\"hg\"], \"data\": \"<a href='https://fake.usagibox.com/hg/2023-07-14-17-05-55/pages/metricfire_com/index.html' target='_blank'>Result 1 run</a>\", \"when\": 1689375957}`

**Comment by soulgalore** [comment]
Ok. It looks strange since you get two different timestamp, the old implementation used one and the same for all the runs for different URLs within one test. 

Just to be 100% sure, if you check the result page for each URL, you have different timestamps for each URL right?
<img width="638" alt="time" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/8698f0b8-2437-456e-91e3-26826633cb76">

Also wanted to clarify _"only two of the annotations getting sent:"_ do you mean that sitespeed.io do not send them? Or when you receive them, they aren't handled because they have the same timestamp?

**Comment by lrojash** [comment]
Sorry about not clarifying, the annotations I believe are getting sent, or at least attempted. In our end we reject them because they have the same time stamps. 

So I suppose in general is there a case where the annotations  would have the same timestamp for multiple urls?

In this run:
![Summary for 1 run hostedgraphite com at 2023-07-17 090819 2023-07-17 at 9 12 52 AM](https://github.com/sitespeedio/sitespeed.io/assets/67330937/91af079b-f341-4204-bedd-b6e0ed40689e)

The timestamps in the logs for each annotation is: 1689606479

That's the time that's here: 
![Overview of 3 pages for metricfire com at 2023-07-17 090759 2023-07-17 at 9 18 43 AM](https://github.com/sitespeedio/sitespeed.io/assets/67330937/7ecd0a70-68ae-41b8-8ab3-38e54182316f)

**Comment by soulgalore** [comment]
It's strange I cannot reproduce it. Can you just double check that the parameters you use in the first comment is the exact ones you use? Just to be 100% sure. I also made a npm release _29.0.0-alpha.1_ to try it out on a test server and I get the same there. I wonder how/what I should do to reproduce it, not sure.

**Comment by lrojash** [comment]
Thanks for taking a look, and yes those are the params I am using. 
I also tested with the alpha npm release and same strange behavior. 
I would say that out of 10 runs, 7-9 times the urls have different timestamps. 

The only thing I could think of is maybe the rounding in the timestamp that is done in 'send-annotations.js'. Only think this because the closer I make the runs (within 1-5mins) the more likely the annotations have the same timestamps. 

Just to clarify a run is each time I run the full command I have provided in the first comment.

**Comment by soulgalore** [comment]
I think as long as you don't run with `--graphite.annotationRetentionMinutes` the rounding will only remove ms. 

Do you see the same thing if you run with more iterations per URL?

**Comment by lrojash** [comment]
Ah got it

But yes, I tried 2, 3, 5 iterations and the same behavior is present it becomes more constant with more iterations.

I also ran with 1, 2, 3 different urls and same thing.

**Comment by soulgalore** [comment]
Ok, is it possible to create a cloud instance on a server where you get the problem and give me access so I can have a look, since I can't reproduce it? That would be super helpful. 

Thanks.

**Comment by lrojash** [comment]
I think the root of the issue is the message.type and this part of the code in the index.js of the graphite plugin:

`const timestamp =
  message.type === 'browsertime.pageSummary'
   ? dayjs(message.runTime)
   : this.timestamp;`
              
whenever we have a timestamp issue the message type comes back as 'coach.pageSummary'

made that a ternary for testing locally and the issue stopped

My questions then, what causes the message.type from being browser or coach?


Thanks!

**Comment by soulgalore** [comment]
Ok, thanks for that info! There are some info about the messages [here](https://www.sitespeed.io/documentation/sitespeed.io/plugins/#important-messages). The coach messages are messages with [Coach](https://www.sitespeed.io/documentation/coach/) metrics and Browserime are more timing related metrics. 

If the Coach messages triggers the annotation messages, it makes sense that the time is incorrect because then it only uses the start time of the time you start the test, the strange thing is that we should only send annotations on browsertime.pageSummary messages, so it must be a bug somewhere that I can't locate. So you can see that the coach messages are triggering the annotation to be sent, correct?

**Comment by lrojash** [comment]
Thanks for the links with the info on the coach messages!

That is correct I am logging the message type right before 
(in the lib/plugins/graphite/index.js line 185)
`          const timestamp =
            message.type === 'browsertime.pageSummary'
              ? dayjs(message.runTime)
              : this.timestamp;`

and when there are timestamp issues it logs coach.pageSummary

If the annotations is only supposed to fire on browsertime.pageSummary could it be because the initial check only checks:

```
        if (
          this.receivedTypesThatFireAnnotations[message.url] ===
            this.messageTypesToFireAnnotations.length &&
          this.resultUrls.hasBaseUrl() &&
          this.sendAnnotation
        )
```
and somehow the data for coach messages is getting sent prior to browsertime so all of those conditions are true.

**Comment by soulgalore** [comment]
Yeah, that looks suspicious, thanks. Let me do a quick fix for that now and then I can clean up the code when I remove the WebPageTest support.

**Comment by soulgalore** [comment]
@lrojash can you verify when you have time that it works in 29.2.0?

**Comment by lrojash** [comment]
I tested both through docker and npm and looks good, not experiencing anymore issues.

Thank you, for the assistance!
