### ISSUE TITLE
Error 'No data to collect' in Sitespeed.io

### ISSUE THREAD

**Issue by pam2502** [sitespeedio/sitespeed.io#3911]
### Your question

Issue description:
When running Sitespeed.io with a JavaScript script, the process terminates without collecting any data and displays the error message "No data to collect."

Steps to reproduce the issue:
1. Execute the following command in CMD windows: docker run --rm -v "%cd%":/sitespeed.io sitespeedio/sitespeed.io ejemplo.js --multi -n1
2. The process starts and navigates to the URL provided in the script.
3. However, after completing the navigation and the script, Sitespeed.io does not collect any data and shows the "No data to collect" error message.
4. I have tried multiple times with different scripts and URLs, but the issue persists.

Additional information:
- Sitespeed.io version used: 29.0.0-alpha.1
- Operating system: Windows 10
- Tested URL: https://www.sitespeed.io
- Script used: ejemplo.js

module.exports = async function(context, commands) {
  try {
    await commands.navigate('https://www.sitespeed.io');
    await commands.wait.byTime(5000);
  } catch (error) {
    console.error('Error:', error);
  }
};

Screenshot of the error message: 
![image](https://github.com/sitespeedio/sitespeed.io/assets/140012063/2cba2482-1e04-48f2-ba19-baf0e6f69854)

I send the response of the execution in the txt:
[response.txt](https://github.com/sitespeedio/sitespeed.io/files/12099349/response.txt)

**Comment by soulgalore** [comment]
Hi @pam2502 checkout the measure command: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure

**Comment by pam2502** [comment]
Thank you very much for the answer, I'm exploring this wonderful tool and sometimes I omit simple things
