### ISSUE TITLE
[Documentation/Jenkins] CSP values don't allow fetch resources

### ISSUE THREAD

**Issue by Amerousful** [sitespeedio/sitespeed.io#3915]
### Your question

Hi! Maybe I should create it as a bug report, but I'm not sure. My problem related to integration with Jenkins. There are some options to allow Jenkins to run js scripts, fetch resources, etc. - https://www.sitespeed.io/documentation/sitespeed.io/continuous-integration/#setup, and it didn't work for me. 
```sandbox allow-scripts; style-src 'unsafe-inline' *;script-src 'unsafe-inline' *;```

**I found which works**: ```default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' 'unsafe-inline' data:;```

Command: ```docker run -v ${WORKSPACE}:/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://www.sitespeed.io/ -n 1```
<img width="1506" alt="image 2426" src="https://github.com/sitespeedio/sitespeed.io/assets/22199881/c46da86b-4772-4c38-8a89-c70c64dd78ab">

**Comment by soulgalore** [comment]
Hi @Amerousful thanks, I'll update the documentation.
