### ISSUE TITLE
Dashboard for version 29.0.0 adds unknown database

### ISSUE THREAD

**Issue by kissifrot** [sitespeedio/sitespeed.io#3919]
Ah I see, no sorry I should have explained that better: where do you push the result (the HTML/video/screenshots) from the sitespeed.io test? Do you push it to S3, or a server? If you just test it out locally you can just add a dummy URL as endpoint for the JSON plugin.

_Originally posted by @soulgalore in https://github.com/sitespeedio/grafana-bootstrap-docker/issues/48#issuecomment-1650345172_

(sorry for the "new" issue)

Results are pushed to s3

**Comment by soulgalore** [comment]
Ah thank you for creating the issue, I missed to link the old issue here when I archived the old.

So then you can:
1. Install the JSON Datasource (either through your docker compose, or install it manually. In Grafana admin you can add a datasource.
2. Add the base URL from S3 as your URL for the JSON datasource.

I'm gonna write some more detailed instructions and will link them from this issue.

**Comment by soulgalore** [comment]
I updated the documentation at https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/ to better match how it works.

**Comment by kissifrot** [comment]
> I updated the documentation at https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/ to better match how it works.

Thanks! 👍 

S3 does not like being used as a JSON datasource though, even if using public bucket's URL 🙂

**Comment by soulgalore** [comment]
Could it be that your bucket hasn't enabled CORS? https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html - if you check the log in devtools in your browser when you access the Grafana dashboard, you will see the error there.

**Comment by soulgalore** [comment]
I don't have access from my current computer so I can give you an working example, can do that I think this weekend.

**Comment by soulgalore** [comment]
Sorry this took a really long time. I've updated the documentation to include a CORS setting.
