### ISSUE TITLE
Running config.json on sitespeed (via node CLI)

### ISSUE THREAD

**Issue by Edson1337** [sitespeedio/sitespeed.io#3920]
### Your question

Dear developers of sitespeed.io, I come to ask about the use of config.json for the command that runs through the node, locally on my machine. I have tried several ways to put the configuration I created, but the evaluation starts with the default configuration and ignores the json, or in other attempts I put the flag --config, is not considered correct, appears "TypeError [ERR_INVALID_URL_SCHEME]".

**Comment by soulgalore** [comment]
Hi @Edson1337 can you share an exact example of how you run?

This works for me:
`sitespeed.io --config config.json https://www.sitespeed.io`

And the config.json looks like this:
```
{
    "browsertime": {
        "iterations": 1
    }
}
```

Here's the documentation: https://www.sitespeed.io/documentation/sitespeed.io/configuration/#configuration-as-json

**Comment by Edson1337** [comment]
Hi @soulgalore, here is the configuration I am using for the test:

![Captura de Tela (18)](https://github.com/sitespeedio/sitespeed.io/assets/63821150/50bb8ffb-3256-46ac-9623-8beb96dbf8e7)

Also, I use the same command line for execution and I get this error:

![Captura de Tela (19)](https://github.com/sitespeedio/sitespeed.io/assets/63821150/57058475-597d-4b83-b63a-d2898814328a)

One detail I did not mention in my question is that I am running on Windows.
If you can give me some insight on how to solve this, I would be grateful.

**Comment by soulgalore** [comment]
Ah thank you @Edson1337 I wonder then if there's a bug in how we read the file on Windows, I added a test and will have a look.

**Comment by Edson1337** [comment]
Thanks for adding the test, sougalore. I saw here that you mentioned this issue in the test you performed and that it generated the same error. So if there is a resolution to this issue, please let me know if possible.

I look forward to hearing from you and have a nice weekend.

**Comment by soulgalore** [comment]
Hi @Edson1337 the error was introduced when I moved the code to ESM and I fixed it in https://github.com/sitespeedio/sitespeed.io/pull/3921. I didn't had test for that on all platforms, but I added it now.

I'll release the fix later today (Sunday).

**Comment by soulgalore** [comment]
@Edson1337 please try with 29.1.1 when you have time, I think it will work in that version.

**Comment by Edson1337** [comment]
Hi @soulgalore , sorry I didn't reply sooner, but thank you very much for your help. I have already downloaded the new version and tested it with the settings I had made in the json file, I confirm the correct operation now.
