### ISSUE TITLE
Custom metric is not getting pushed in influx DB.

### ISSUE THREAD

**Issue by ParagGade94** [sitespeedio/sitespeed.io#3933]
### Your question

hi @soulgalore I am trying to get the error message into influx db. I tried using the below code in the catch block to export the custom metrics. This custom metric is available in the HTML report but I am not able to find it anywhere in the influxdb measurements. Can you please help me out regarding this ?

                  await commands.error(e);
		 await commands.measure.add('ErrorMessage',e);
		  await context.log.info("Custom metric sent");
                 return await commands.measure.stop();

**Comment by soulgalore** [comment]
Hi @ParagGade94 thanks for creating the issue, I don't think that it is implemented yet to send custom metrics to influx db with a tag that says it's custom. I would guess the metric would be sent to InfluxDB without a nice tag though, but I need to verify that.

**Comment by ParagGade94** [comment]
Thanks for the quick response @soulgalore much appreciated. Please if you can let me know that the custom metric is going to influx or not and is there any other way to access it in influx then it will be much helpful.  I need to print the error message in grafana. Thanks

**Comment by soulgalore** [comment]
I tested and it seems to work for me. In my script file I add a custom metric like this:

` await commands.measure.add('MyCustomMetric', 22);`

And then the statistics tag has the value of _extra_ and there's a metric named _MyCustomMetric_.
```
{
    "tags": {
      "statistics": "extras",
      "category": "default",
      "origin": "browsertime",
      "summaryType": "pageSummary",
      "connectivity": "native",
      "browser": "chrome",
      "page": "myTest",
      "group": "www_sitespeed_io"
    },
    "seriesName": "MyCustomMetric",
    "point": {
      "time": 1691661611000,
      "median": 22
    }
  },
```

**Comment by soulgalore** [comment]
I didn't get any response so closing.
