### ISSUE TITLE
Javascript Error - Executing using npm modules

### ISSUE THREAD

**Issue by QTSankarRajan** [sitespeedio/sitespeed.io#3934]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [x] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

www.sitespeed.io

### What are you trying to accomplish

I am trying the execute a hello world test after installing Sitespeed as npm package from windows. I am getting Windows error when I trying to executed below cmd command from the path where sitepeed.js file is located.

node_modules\sitespeed.io\bin>sitespeed.js https://www.sitespeed.io

Below is the error message I am getting when we have invoked above command

![image](https://github.com/sitespeedio/sitespeed.io/assets/100260268/0613d62f-bd19-4b86-89a5-39f38a735ae3)

### What browser did you use?

Chrome

### How to reproduce

```shell
Invoke the Windows command mentioned above.
```

**Comment by soulgalore** [comment]
Hi @QTSankarRajan here's some examples how we run sitespeed.io on Windows on our Github action tests:
https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/windows.yml
