### ISSUE TITLE
Help with Documentation

### ISSUE THREAD

**Issue by OphyBoamah** [sitespeedio/sitespeed.io#3941]
### Your question

Hi @soulgalore, I reached out on Slack over a month ago about wanting to help restructure the sitespeed.io documentation but I'm yet to hear back. Just checking if you've had the chance to look at my message, please.

**Comment by soulgalore** [comment]
Hi @OphyBoamah sorry, let me get back this weekend when I've had a look. 

Thanks
Peter

**Comment by OphyBoamah** [comment]
Alright, thanks.

**Comment by soulgalore** [comment]
I got back. In general:
1. If you want to help out making the documentation better, perfect!! Making tutorials, restructuring the current content to make it easier to understand/read, that is great.
2. If you want to change the framework and add tons of JavaScript to the documentation I'm always against that :)

**Comment by soulgalore** [comment]
Closing this and then lets add specific issues for specific changes in the documentation.
