### ISSUE TITLE
Cannot find user script

### ISSUE THREAD

**Issue by dooglewoogle** [sitespeedio/sitespeed.io#3943]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

localhost

### What are you trying to accomplish

Hi, I'm trying to just run a user script, nothing unusual. However when I run sitespeed, I get: 
myTestScript.mjs does not exist, is the path to the file correct?

I have tried:

- putting in the absolute and relative paths
- checking that the file exists
- checking it exists where I expect it to be (tab complete in shell)
- that permissions are ok, I believe they started at 750, I increased it slowly up to 777 where it is now
- that the file is owned by the current user.

The command: 
~$> sudo docker run --rm -v "$(pwd):/ssio" sitespeedio/sitespeed.io:29.1.3 myTestScript.mjs --multi

Taking away the script argument, it works perfectly. It's just with this it's not. 

Extra environment: 
Distro: CentOS 7
uname -r:  3.10.0-1160.95.1.el7.x86_64
Docker version 24.0.5, build ced0996

Any thoughts on other things I could try?
Thanks. 

### What browser did you use?

Chrome

### How to reproduce

```shell
sudo docker run --rm -v "$(pwd):/ssio" sitespeedio/sitespeed.io:29.1.3 myTestScript.mjs --multi
```

### Log output

```shell
Google Chrome 115.0.5790.102
Mozilla Firefox 115.0
Microsoft Edge 115.0.1901.183
sitespeed.js [options] <url>/<file>

Browser
  -b, --browsertime.browser, --browser                                                              Choose which Browser to use when you test. Safari only works on Mac OS X and iOS 13 (or later). Chrome needs to be the same version as the current installed  ChromeDriver (check the changelog for what version that is currently used). Use --chrome.chromedriverPath to use another ChromeDriver version.  [choices: "chrome", "firefox", "safari", "edge"] [default: "chrome"]
  -n, --browsertime.iterations                                                                      How many times you want to test each page  [default: 3]
      --browsertime.spa, --spa                                                                      Convenient parameter to use if you test a SPA application: will automatically wait for X seconds after last network activity and use hash in file names. Read https://www.sitespeed.io/documentation/sitespeed.io/spa/  [boolean] [default: false]

........
........

      --config                                                Path to JSON config file
      --version                                               Show version number  [boolean]
  -h, --help                                                  Show help  [boolean]

Read the docs at https://www.sitespeed.io/documentation/sitespeed.io/

Error: myTestScript.mjs does not exist, is the path to the file correct?
```

**Comment by soulgalore** [comment]
Hi @dooglewoogle when you mount `"$(pwd):/ssio"` that means that the current directory (pwd) is mounted as /ssio inside the container, but the default working directory inside docker is `/sitespeed.io` so in your example, sitespeed.io will look for the script `/sitespeed.io/myTestScript.mjs`. Try either mount as in the documentation `-v "$(pwd)":/sitespeed.io` or in your example give the full path to the script like  `/ssio/myTestScript.mjs`

**Comment by dooglewoogle** [comment]
Ah, I see it was a misunderstanding of docker. Thank you, that appears to be working.
