### ISSUE TITLE
Have a CO2.js and/or Axe Toplist

### ISSUE THREAD

**Issue by mgifford** [sitespeedio/sitespeed.io#3946]
### Feature/improvement

It would be nice to see which URLs are the worst  (and maybe the best too) for the optional elements like axe & CO2.js

If you want to know which are the most bloated pages, would be great to have a list of pages to tackle first.

Also would be useful to see where the largest page and slowest pages overlap with CO2.js.

**Comment by soulgalore** [comment]
Hi @mgifford one way to get the list right now would be to use https://www.sitespeed.io/documentation/sitespeed.io/configure-html/#configure-page-metrics - that way you can add columns with co2 and axe and different speed metrics and then you can sort them by clicking on the table heading.

**Comment by soulgalore** [comment]
I would use https://github.com/sitespeedio/sitespeed.io/issues/3947#issuecomment-1871295017 to get those toplists. The toplists today shows assets and not pages, so I think building that would mean a lot of work, its better to use the pages page.
