### ISSUE TITLE
If you've enabled CO2.js or axe it in the 50 pages analysed for https://example.com table

### ISSUE THREAD

**Issue by mgifford** [sitespeedio/sitespeed.io#3947]
### Feature/improvement

If you're loading Sitespeed.io for the first time or first time in a while, it can be possible to forget where the CO2.js or axe results should be.  I'd like to see them highlighted in the Pages page so that it is easy to scroll down and also sort based on the CO2 of the pages that have been scanned for accessibility & CO2.

**Comment by soulgalore** [comment]
Isn't this doable with --html.pageSummaryMetrics?  

I config file like:
```
{
    "sustainable":  {
        "enable": true
    }, 
    "axe": {
        "enable": true
    },
    "html": {
        "pageSummaryMetrics" : ["axe.serious","sustainable.totalCO2"]
    }
}
```

should do it but I think there's a bug when displaying co2, I only see zeroes and I think it could be a bug that we do not show metrics smaller than 1. I'll look into it.

**Comment by soulgalore** [comment]
This should work when https://github.com/sitespeedio/sitespeed.io/pull/4042 goes live.

**Comment by soulgalore** [comment]
If you upgrade 31.0.1 you can use a config file like:

```
{
    "sustainable":  {
        "enable": true
    }, 
    "axe": {
        "enable": true
    },
    "html": {
        "pageSummaryMetrics" : ["axe.serious","sustainable.totalCO2"]
    }
}
```
 to get those metrics in the pages page.
