### ISSUE TITLE
It is important to identify versions of 3rd party tools when describing them.

### ISSUE THREAD

**Issue by mgifford** [sitespeedio/sitespeed.io#3949]
### Feature/improvement

Axe is described as:

> ## Axe
> 
> Axe is an accessibility testing engine for websites and other HTML-based user interfaces. Read more about [axe-core](https://github.com/dequelabs/axe-core).

What version of axe? Latest is 4.7.2

Same with the sniffing tools.

> ## Technologies used to build the page.
> 
> Data collected using [Wappalyzer.](https://github.com/AliasIO/wappalyzer) Use --browsertime.firefox.includeResponseBodies htmlor --browsertime.chrome.includeResponseBodies htmlto help Wappalyser find more information about technologies used.
> 
> Data collected using [Third Party Web.](https://github.com/patrickhulce/third-party-web)

Is Third Party Web version 0.24? and what version of Wappalyzer are you running now that the original repo seems to no longer be visible [https://github.com/AliasIO/wappalyzer](https://github.com/AliasIO/wappalyzer)  
  
Also, that link to Wappalyzer will need to be updated.

**Comment by soulgalore** [comment]
Hi @mgifford , let's add it so we pickup the versions from the package.json file, that should be easy for Axe. For the others coach core needs to expose them, but it should be doable. Do you have time to have a go and make a PR?

Best
Peter

**Comment by soulgalore** [comment]
Hmm, I checked the code and we actually show the version number for axe on each individual run page:
<img width="1168" alt="Screenshot 2023-08-29 at 21 40 34" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/145a7426-d8b8-428f-92c6-533f90f44f25">

Let me check if we can add the version number then on the summary page too since it seems to be hard to find.

**Comment by soulgalore** [comment]
Fot wappalyzer we use https://www.npmjs.com/package/wappalyzer-core and I do not plan to switch to the API in the near future, I haven't looked into how that work. 

https://github.com/sitespeedio/coach-core/pull/111 should make it easy to get the versions in the HTML.

**Comment by soulgalore** [comment]
For upcoming wappalyzer I guess the best way would to go with the fork in https://github.com/HTTPArchive/wappalyzer that way we are inline with HTTPArchive and that seems like a good idea.

**Comment by soulgalore** [comment]
Versions have been implemented. I'm adding a new issue to switch to https://github.com/HTTPArchive/wappalyzer
