### ISSUE TITLE
Minimize size of the dataset

### ISSUE THREAD

**Issue by mgifford** [sitespeedio/sitespeed.io#3951]
### Feature/improvement

The data collected from sitespeed.io is pretty extensive. Videos, images, HTML, the whole lot.

If I just want to run a scan and then collect the results, I should be able to easily delete the videos or other elements that take up a lot of space.

In the best practice documentation:
https://www.sitespeed.io/documentation/sitespeed.io/best-practice/

I can see how to minimize the video size, but not eliminate it:

```
## Video
You can change the [Constant rate factor](https://trac.ffmpeg.org/wiki/Encode/H.264#crf). Default is 23. If you change that you can have videos with lower quality but it will take less space. Use --browsertime.videoParams.crf.

You can also change the quality of the video filmstrip screenshots. Default it is set to 75 but you can set a value between 0 - 100. Use --browsertime.videoParams.filmstripQuality.

If you dont use the filmstrip (at the moment the filmstrip screenshots isn’t used within the sitespeed.io result pages) you can disable it. --browsertime.videoParams.createFilmstrip false will disable the filmstrip.
```

How do I remove the weighty videos & images?

**Comment by soulgalore** [comment]
Hi @mgifford to remove the video you can set video to false `--video false`. As long as you have `--visualMetrics true` the video will still be recorded so that the visual metrics can be collected and then the video will be removed.

```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ --video false --visualMetrics true -n 1 --browsertime.videoParams.createFilmstrip false
```

For the screenshots for page complete and LCP/CLS, I need to look into how it works, not sure if all those can be removed.

**Comment by soulgalore** [comment]
You can disable screenshots with:
`--browsertime.screenshotLCP false --browsertime.screenshotLS  false --browsertime.screenshot false`.

I hope that makes the trick.
