### ISSUE TITLE
[Bug] Versions 29.3.0 and 29.4.0 (--platform linux/arm64) still use Chromium 107 instead of Chromium 116

### ISSUE THREAD

**Issue by polarnik** [sitespeedio/sitespeed.io#3959]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://miro.com

### What are you trying to accomplish

--platform linux/amd64 images use chrome-116.0, but --platform linux/arm64 images use chromium 107

1) Check out the base image for versions 29.3.0 and 29.4.0:

- https://github.com/sitespeedio/sitespeed.io/blob/v29.3.0/Dockerfile#L1
- https://github.com/sitespeedio/sitespeed.io/blob/v29.4.0/Dockerfile#L1

`FROM sitespeedio/webbrowsers:chrome-116.0-firefox-116.0-edge-115.0`

2) Try to start a test with

docker pull sitespeedio/sitespeed.io:29.4.0 (--platform linux/arm64)
and
docker pull sitespeedio/sitespeed.io:29.4.0-plus1 (--platform linux/arm64)

Results:

1. sitespeedio/sitespeed.io:29.4.0 - works fine, but uses Chromium **107.0.5304.62** Ubuntu 22.04
3. sitespeedio/sitespeed.io:29.4.0-plus1 - works fine, but uses Chromium **107.0.5304.62** Ubuntu 22.04

### What browser did you use?

Chrome, Other

### How to reproduce

```shell
docker run --shm-size=1g --rm \
  -v "$(pwd)/sitespeed.io:/sitespeed.io" \
  --platform linux/arm64 \
  sitespeedio/sitespeed.io:29.4.0 \
  "https://miro.com"

# and

docker run --shm-size=1g --rm \
  -v "$(pwd)/sitespeed.io:/sitespeed.io" \
  --platform linux/arm64 \
  sitespeedio/sitespeed.io:29.4.0-plus1 \
  "https://miro.com"
```

### Log output

```shell
Log for sitespeedio/sitespeed.io:29.4.0  --platform linux/arm64 :

Digest: sha256:6fcc1062523e35bcb6d626cd5bb706cf0a4a9531794cc439b2b5993d22260263
Status: Downloaded newer image for sitespeedio/sitespeed.io:29.4.0
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 116.0.3
[2023-09-02 12:39:40] INFO: Versions OS: linux 5.15.49-linuxkit-pr nodejs: v18.16.0 sitespeed.io: 29.4.0 browsertime: 17.15.0 coach: 8.0.2
[2023-09-02 12:39:40] INFO: Running tests using Chrome - 3 iteration(s)

---------------------------

Log for sitespeedio/sitespeed.io:29.4.0-plus1 --platform linux/arm64 :

Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 116.0.3
[2023-09-02 12:40:19] INFO: Versions OS: linux 5.15.49-linuxkit-pr nodejs: v18.16.0 sitespeed.io: 29.4.0 browsertime: 17.15.0 coach: 8.0.2
[2023-09-02 12:40:20] INFO: Using default Lighthouse configuration for desktop 
[2023-09-02 12:40:20] INFO: Will run Lighthouse tests after Browsertime has finished 
[2023-09-02 12:40:20] INFO: Sending url https://miro.com to test on Page Speed Insights
[2023-09-02 12:40:21] INFO: Running tests using Chrome - 3 iteration(s)

**Comment by polarnik** [comment]
Sorry! I have a trouble with the Rosetta tool for x86/amd64 emulation on Apple Silicon. 
A Docker Desktop unsets the "Use Rosetta for x86/amd64 emulation on Apple Silicon" option after each MacOS restart. And I need to instal the Rosetta tool again.

Maybe the test results about --platform linux/amd64 was incorrect. I need to recheck them:

```sh
docker run --shm-size=1g --rm \
  -v "$(pwd)/sitespeed.io:/sitespeed.io" \
  --platform linux/amd64 \
  sitespeedio/sitespeed.io:29.4.0 \
  "https://miro.com"
```
and
```sh
docker run --shm-size=1g --rm \
  -v "$(pwd)/sitespeed.io:/sitespeed.io" \
  --platform linux/amd64 \
  sitespeedio/sitespeed.io:29.4.0-plus1 \
  "https://miro.com"
```

But test results about --platform linux/arm64 are correct. linux/arm64 images still use Chromium 107 instead of Chromium 116

**Comment by soulgalore** [comment]
Hi @polarnik sorry that wasn't understandable in the documentation, so I just updated the documentation. The problem is that Google do not provide any binaries for Chrome/Chromium on ARM Linux, so we use the latest release in the *ppa:saiarcot895/chromium-beta* and that ppa been lagging for a while. That will not change until anyone else provide a working ppa and keep updated.

Best
Peter
