### ISSUE TITLE
Chrome mobile emulation doesn't set the right useragent

### ISSUE THREAD

**Issue by srvraja** [sitespeedio/sitespeed.io#3960]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://demoqa.com/

### What are you trying to accomplish

Trying to test the URL with Chrome mobile emulation. UserAgent is expected to be set related to mobile but desktop user agent been set. 

Sitespeed version details

 INFO: Versions OS: win32 10.0.14393 nodejs: v18.17.1 sitespeed.io: 29.2.1 browsertime: 17.14.3 coach: 7.2.1
[2023-09-06 17:35:12] INFO: Running tests using Chrome - 1 iteration(s)
<img width="1107" alt="Report_run_time_settings" src="https://github.com/sitespeedio/sitespeed.io/assets/133784721/fa279d8f-71e9-4181-ae0c-5dad17ac8893">
[mobile_config.txt](https://github.com/sitespeedio/sitespeed.io/files/12541071/mobile_config.txt)

### What browser did you use?

Chrome

### How to reproduce

```shell
Run sitespeed.io test for the above URL with config set as in attachment(mobile_config.txt). Check UserAgent value in the runtime settings of the generated report. Mobile useragent expected but the actual is the desktop useragent
```

**Comment by srvraja** [comment]
@soulgalore , Need your help.

**Comment by soulgalore** [comment]
Hi @srvraja I don't think emulation in Chrome sets the user agent automatically, you need to do that yourself. 

`--browsertime.userAgent "MyNewAgent"` should do the trick.

**Comment by srvraja** [comment]
@soulgalore , Let me try this option 

I just gone through a issue which was fixed mid 2020, is that similar to what i reported?
https://github.com/sitespeedio/sitespeed.io/issues/3042

Thanks for your time

**Comment by soulgalore** [comment]
I think this has been changed in Chrome. To be safe, always set the user agent yourself.
