### ISSUE TITLE
Selenium behaviour is different with sitespeed

### ISSUE THREAD

**Issue by trooperjey01** [sitespeedio/sitespeed.io#3969]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [x] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

http://www.duckduckgo.com/

### What are you trying to accomplish

Hello, 

I'm trying to use selenium scripts to measure an user journey on our webapplication.

When I try to use the selenium wait funtion like just below, I have and error:  "ERROR: TypeError: Wait condition must be a promise-like object, function, or a Condition object"

 await driver.wait(until.elementLocated(By.id('XX')), 50000); 

When I execute a script file directly with node it works .

I'm new with sitespeed and selenium . May I miss something ?

### What browser did you use?

Chrome

### How to reproduce

```shell
selenium_example.js:
 
const { Builder, By, Key, until } = require('selenium-webdriver');

async function example() {
  let driver = await new Builder().forBrowser("chrome").build();
  try {
    await driver.get('http://www.duckduckgo.com/');
    await driver.findElement(By.id('searchbox_input')).sendKeys('Hello world', Key.RETURN);
    const firstArticle = await driver.wait(until.elementLocated(By.id('r1-0')), 20000);
    await driver.wait(until.elementIsVisible(firstArticle), 10000);
    await firstArticle.click();
  } finally {
    await driver.quit();
  }
};
// Run the example
example().catch(console.error);

command line:
node ./selenium_example.js

output: 
Test ok


sitespeed_example.js:

const { By, Key, until } = require('selenium-webdriver');

module.exports = async function(context, commands) {
  const driver = context.selenium.driver;
  try {
    await commands.navigate('http://www.duckduckgo.com/');
    await driver.findElement(By.id('searchbox_input')).sendKeys('Hello world', Key.RETURN);
    const firstArticle = await driver.wait(until.elementLocated(By.id('r1-0')), 20000);
    await driver.wait(until.elementIsVisible(firstArticle), 10000);
    await firstArticle.click();
  } catch (e) {
    throw e;
  }
};

command line:
docker run --rm -v "${pwd}:/sitespeed.io" sitespeedio/sitespeed.io ./sitespeed_example.js --multi -n 1
```

### Log output

```shell
ERROR: TypeError: Wait condition must be a promise-like object, function, or a Condition object
    at Driver.wait (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:901:13)
    at module.exports (/sitespeed.io/tests/sitespeed_tests.js:8:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///usr/src/app/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:240:9)
    at async Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:190:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:173:26)
```

**Comment by soulgalore** [comment]
Hi @trooperjey01 there's some documentation on how to get hold of the same Selenium version that sitespeed.io uses here: 
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#use-selenium-directly

You need to do that to be able to use the rest of the commands (like measure etc).

Let me know how it works out for you!

**Comment by trooperjey01** [comment]
Hi @soulgalore , ok I see I had forgotten to declare and use  seleniumWebdriver.By and seleniumWebdriver.until . Thanks a lot for your help :-)
