### ISSUE TITLE
sitepeed on Plain windows installtions

### ISSUE THREAD

**Issue by rajesh3349** [sitespeedio/sitespeed.io#3971]
Hi, I am trying to install sitespeed on windows machine. 
I have NPM  (8.15.0) & Pip 3.11
tried npm install sitespeed.io without any success.

Downloaded latest zip and placed it under npm. when I run npm install or bin/browserXX.js it is complaining various packages are missing. 
Lodash merge needs salty-0.2.4 looks like .... this is not available in npmjs site itself. 

anyone faced this issue please help asap. 

email:v.rajesh3349@gmail.com

**Comment by soulgalore** [comment]
Hi @rajesh3349 in the sister-project Browsretime we have Github action that sets up everything needed to run on Windows, please have a look: https://github.com/sitespeedio/browsertime/blob/main/.github/workflows/windows.yml hopefully that can help.

**Comment by rajesh3349** [comment]
Hi Soulgalore, Thanks for quick reply.
do we need this Chocolatey ? our org is so security intensive. it is not easy to install every software. 
currently installed Node and PIP not sure if that helps?

**Comment by soulgalore** [comment]
No you can install those dependencies however you can, I just use that on the GitHub action because it is simple.

**Comment by rajesh3349** [comment]
yeah, folllowd the steps as needed for windows. infact downloaded the sitepeed-29.05.0.zip
placed this in NPM folder...trying to launch the sitespeed.io withno luck. 
it is kept compalining about dependencies. currently stuck at salty-0.2.4 which is not available on npmjs.org itself. 
not sure how to proceed further.

**Comment by soulgalore** [comment]
Follow the installation in the GitHub action. Please use `npm install` instead of downloading a zip file.
