### ISSUE TITLE
Group of measurements success/fail indication

### ISSUE THREAD

**Issue by dooglewoogle** [sitespeedio/sitespeed.io#3973]
### Your question

Hi, I've got a user flow of about three steps, in a larger script that I'm measuring. Is there something I can add or do, from within the user journey script, to add something that indicates that those three steps have run successfully? For this particular thing I'm not super concerned about timings, just whether it's errored or not. 

I could do this on the retrieval side, in something like fluxQL, but I'm hoping there is something a bit cleaner then that. 

Thanks.

**Comment by soulgalore** [comment]
Hi @dooglewoogle 
in your script you can create errors that ends up in the time series databases at least Graphite. The docs says influxdb too, but I don't remember if that is correct.

Checkout the dashboard https://dashboard.sitespeed.io/d/9NDMzFfMk/page-metrics and then scroll down to the errors row. To the right are errors from running the tests:

<img width="1413" alt="Screenshot 2023-10-09 at 09 47 14" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/c8bc7e64-45e3-4d26-83d7-ba9ee79cf450">

If your script throws an error, it will automatically end up there. You can also create the error yourself https://www.sitespeed.io/documentation/sitespeed.io/scripting/#error-handling

`commands.error('The link named Checkout do not exist on the page');`

**Comment by amitdisha** [comment]
Hi @dooglewoogle , 
You can send extrametrics for pass and fail to html report and influxdb and plot on grafana. 
Example -
extraMetrics = { Pass: 0,Fail: 1};// sending status as Fail to HTML and db

**Comment by soulgalore** [comment]
I hope these answers helps, please let me know if something is missing.
