### ISSUE TITLE
Excessive time to finish sitespeed.io execution using directly from NodeJS

### ISSUE THREAD

**Issue by lucasvieira123** [sitespeedio/sitespeed.io#3983]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io/documentation/sitespeed.io/developers/#use-sitespeedio-from-nodejs

### What are you trying to accomplish

I'm running sitespeed.io directly in a nodejs project. In a simple example of execution according to the documentation. It warns me that it has finished generating the HTML results:

`[2023-10-17 16:55:28] INFO: HTML stored in C:\Users\lucas\Workspace\performance-evaluation-tool\temp-sitespeed-controller\sitespeed-result\www.sitespeed.io\2023-10-17-16-55-14 `

but it keeps running without generating any logs or artifacts for another 1 minute until it finally finishes the process.
I tested it on two different machines, but the same problem persisted.

### What browser did you use?

Chrome

### How to reproduce

```shell
1- Create a project node locally. (npm init)
2- Install sitespeed.io module (npm install sitespeed.io)
3- Create a file "test.js"
4- Past this code inside test.js (based on sitespeed.io documentation: https://www.sitespeed.io/documentation/sitespeed.io/developers/#use-sitespeedio-from-nodejs):
---
import * as sitespeed from 'sitespeed.io';
const urls = ['https://www.sitespeed.io/'];

 function run() {
  try {
    const result = sitespeed.run({
      urls,
      browsertime: {
        iterations: 1,
        browser: 'chrome'
      }
    });
    console.log(result);
  } catch (e) {
    console.error(e);
  }
}

run();
---
4- Add attribute and value "type": "module" in package.json from your created project node
5- Execute node test.js on terminal
```

### Log output

```shell
$ node test.js
[2023-10-17 17:14:00] INFO: Versions OS: win32 10.0.22621 nodejs: v18.18.2 sitespeed.io:
 29.8.0 browsertime: 17.17.0 coach: 8.0.2
[2023-10-17 17:14:01] INFO: Running tests using Chrome - 1 iteration(s)

DevTools listening on ws://127.0.0.1:9222/devtools/browser/6cd67c6d-47ac-4ab5-a63d-dc3ce
d36d649
[26172:29132:1017/171401.451:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP
 cache.pack.google.com 127.0.0.1
[26172:29132:1017/171401.454:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP
 cache.pack.google.com 127.0.0.1
[2023-10-17 17:14:01] INFO: Testing url https://www.sitespeed.io/ iteration 1
[18564:29364:1017/171404.430:ERROR:device_event_log_impl.cc(225)] [17:14:04.430] USB: us
b_service_win.cc:415 Could not read device interface GUIDs: O sistema nÒo pode encontrar
 o arquivo especificado. (0x2)
[2023-10-17 17:14:08] INFO: Take after page complete check screenshot
[2023-10-17 17:14:09] INFO: Take cumulative layout shift screenshot
[2023-10-17 17:14:09] INFO: Take largest contentful paint screenshot
[2023-10-17 17:14:12] INFO: https://www.sitespeed.io/ 11 requests, TTFB: 204ms, firstPai
nt: 649ms, FCP: 649ms, DOMContentLoaded: 669ms, LCP: 682ms, CLS: 0.0004, TBT: 0ms, CPUBe
nchmark: 66ms, Load: 669ms
[2023-10-17 17:14:14] INFO: HTML stored in C:\Users\lucas\Workspace\performance-evaluati
on-tool\temp-sitespeed-controller\sitespeed-result\www.sitespeed.io\2023-10-17-17-14-00 
{
  errors: [],
  browsertime: [
    {
      info: [Object],
      files: [Object],
      markedAsFailure: 0,
      failureMessages: [],
      cdp: [Object],
      android: [Object],
      timestamps: [Array],
      browserScripts: [Array],
      visualMetrics: [],
      deltaToTTFB: [Array],
      cpu: [Array],
      googleWebVitals: [Array],
      extras: [Array],
      fullyLoaded: [Array],
      mainDocumentTimings: [Array],
      errors: [Array],
      renderBlocking: [],
      server: [Object],
      statistics: [Object]
    }
  ],
  har: {
    log: {
      version: '1.2',
      creator: [Object],
      pages: [Array],
      entries: [Array],
      browser: [Object]
    }
  },
  budgetResult: { working: {}, failing: {}, error: {} },
  resultUrl: '',
  pageSummaryUrl: '',
  localPath: 'C:\\Users\\lucas\\Workspace\\performance-evaluation-tool\\temp-sitespeed-co
ntroller\\sitespeed-result\\www.sitespeed.io\\2023-10-17-17-14-00'
}
THERE MORE THAN 1.5 MINUTES LATER
lucas@Lucas_Alves MINGW64 ~/Workspace/performance-evaluation-tool/temp-sitespeed-controller (main)
```

**Comment by soulgalore** [comment]
Hi @lucasvieira123 thanks for creating the issue. I think its some handlers that aren't closed correctly, that's why the process do not exit. I'll have a look the coming days + update the documentation, I think it missed out on some async/await.

**Comment by soulgalore** [comment]
Until this is fixed, I think using process exit is the way to move forward.

**Comment by lucasvieira123** [comment]
In my project, I'm trying to run sitespeed.io inside an iterator. In other words, I run sitespeed.io sequentially n times. If I use process.exit, it kills the entire execution by canceling the iterations. So this approach wouldn't work for me.

**Comment by lucasvieira123** [comment]
Do you have a deadline that you think will fix this problem?

**Comment by soulgalore** [comment]
Hi @lucasvieira123 you can try version 29.9.0, there's a fix there in Browsertime where in some cases a timer was left and never cleared. You need to update your script so it uses async/await else it will not wait on the result. You can checkout the updated example at https://www.sitespeed.io/documentation/sitespeed.io/developers/#use-sitespeedio-from-nodejs

**Comment by soulgalore** [comment]
This was fixed.
