### ISSUE TITLE
Getting daemon error while pulling or trying to integrate with sitepseedio

### ISSUE THREAD

**Issue by Heena1507** [sitespeedio/sitespeed.io#3987]
### Your question

Hi ,

I am trying to integrate sitespeed io, while pulling sitespeed io image - docker pull sitespeedio/sitespeed.io
I am getting below error - 
[1.docker.io/v2/sitespeedio/sitespeed.io/manifests/latest":](https://registry-1.docker.io/v2/sitespeedio/sitespeed.io/manifests/latest%22:) Get "[https://auth.docker.io/token?scope=repository%3Asitespeedio%2Fsitespeed.io%3Apull&service=registry.docker.io":](https://auth.docker.io/token?scope=repository%3Asitespeedio%2Fsitespeed.io%3Apull&service=registry.docker.io%22:) Forbidden

If I try to intsall using below command -
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io -b chrome

I am getting below error -

Unable to find image 'sitespeedio/sitespeed.io:29.8.0' locally
docker: Error response from daemon: Head "[https://registry-1.docker.io/v2/sitespeedio/sitespeed.io/manifests/29.8.0":](https://registry-1.docker.io/v2/sitespeedio/sitespeed.io/manifests/29.8.0%22:) Get "[https://auth.docker.io/token?
scope=repository%3Asitespeedio%2Fsitespeed.io%3Apull&service=registry.docker.io":](https://auth.docker.io/token?scope=repository%3Asitespeedio%2Fsitespeed.io%3Apull&service=registry.docker.io%22:) Forbidden.
See 'docker run --help'.

can i please get help on this? open for every suggestion

**Comment by soulgalore** [comment]
Hi @Heena1507 it should work without login to docker but it seems like [people had some strange thing happening ](https://stackoverflow.com/questions/65361083/docker-build-failed-to-fetch-oauth-token-for-openjdk). Can you try `docker login ` and the pull the container again?

**Comment by Heena1507** [comment]
Hi @soulgalore 

Thanks for your assistance, It was a connectivity issue.
