### ISSUE TITLE
Influxdb metric output has 165 duplicates of the "rsd" (cpu=longTask,longTasks=durations,statistics=cpu) metric

### ISSUE THREAD

**Issue by polarnik** [sitespeedio/sitespeed.io#3997]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://miro.com

### What are you trying to accomplish

1. Start a sitespeed test with an influxdb output config option
2. Save metrics into file
3. Parse the metric file. There is a table with metrics: https://docs.google.com/spreadsheets/d/12T6NI5Dt8i2LO7yNPpJJGgE2hmsBhkX8nVyPSp5PCPg/edit?usp=sharing
4. Try to analyse the metrics and the metrics structure

<img width="1637" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/7660287/df278287-9bda-4965-b1b1-856ec81cf651">

We can see a lot of duplicates with name "rsd". The metric file has 165 duplicates. Only one row has a non 0 value:

- summaryType=pageSummary
- origin=browsertime
- cpu=longTask,longTasks=durations,statistics=cpu
- page={someName}
- rsd, value=71.27532689772029

And the file has a lot of duplicates:

There are 7 "rsd" duplicates for the filter by:
- summaryType=pageSummary
- origin=browsertime
- statistics=visualMetrics

There are 32 "rsd" duplicates for the filter by:
- summaryType=pageSummary
- origin=browsertime
- statistics=timings,userTimings=measures
(The file has 32 user timing metrics, and additional 32 "rds"-duplicates too)

There are 6 "rsd" duplicates for the filter by:
- summaryType=pageSummary
- origin=browsertime
- statistics=googleWebVitals

etc

Will be nice to remove "rsd" duplicates.

### What browser did you use?

Chrome

### How to reproduce

```shell
Start a SiteSpeed test with options and with  sitespeedio/sitespeed.io:29.6.0-plus1 docker container:
{
  "metrics": {
    "list": true,
  }
}

Open a file metric file.
Sort the file lines.
See a file example: https://gist.github.com/polarnik/8f86a1b9c7d3bde9395abfdfa8988121
```

### Log output

```shell
https://gist.github.com/polarnik/8f86a1b9c7d3bde9395abfdfa8988121
```

**Comment by soulgalore** [comment]
Sorry for the late answer @polarnik .  I made a fix that I hope fixes it. The tagging in Influx is a hack, I've started multiple times to create a better structure so that it would work fine for influx and prometheus, I hope to get that out early next year.

**Comment by soulgalore** [comment]
I did release 31.0.1 yesterday that I think fixes the problem. Please re-open/let me know if the issue is still there.
