### ISSUE TITLE
How to get the TTFB or BackendTime for each URL request of a single page?

### ISSUE THREAD

**Issue by fernandatenorio** [sitespeedio/sitespeed.io#4003]
### Your question

Hi
I have my scripts opening pages and checking the metrics, but each page has several backend requests, so I'm wondering if there is the information of TTFB or BackendTime (assuming they are the same metric) for each backend request separately, because I need to investigate further in which route (request) is the performance issue.

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @fernandatenorio you should be able to see it in the waterfall/ HAR file:
<img width="1216" alt="Screenshot 2023-11-07 at 05 52 23" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/64edef0b-7129-4a7e-87d1-632fd75f43a6">

Best
Peter

**Comment by fernandatenorio** [comment]
Thanks for answering
So, taking a look at the picture below, could you please confirm if I'm correct on the following statements?
**1** (877ms) represents the Time To First Byte
**2** (1844ms) Represents the time_starttransfer
**3** (2721ms) represents the time_appconnect

<img width="352" alt="Screenshot 2023-11-07 at 09 51 46" src="https://github.com/sitespeedio/sitespeed.io/assets/13337748/21b23772-69b4-4f70-a62d-770d93f36123">

**Comment by fernandatenorio** [comment]
Hi @soulgalore, did you have time to take a look at this? 

Thanks in advance!

**Comment by soulgalore** [comment]
Hi, you can click on each request/response and choose timings and then you can see:
<img width="1022" alt="Screenshot 2023-11-14 at 04 39 43" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/2dc25460-672c-48cd-8283-b188f5ce913c">

And in the HAR specification you can see what they mean: 
http://www.softwareishard.com/blog/har-12-spec/#timings

**Comment by soulgalore** [comment]
Closing, please let me know if its anything else needed.
