### ISSUE TITLE
Add a button in report for download Chrome console logs

### ISSUE THREAD

**Issue by Amerousful** [sitespeedio/sitespeed.io#4006]
### Feature/improvement

Hey there! 
I found one useful option `--chrome.collectConsoleLog`. Although, there're many buttons in a report such as `Download log`, `Download Video`, `Timeline Log`, and `Download HAR`, there isn't a button for downloading collected console logs from Chrome. 
Do you mind if I try to contribute this feature? 

<img width="751" alt="image 924" src="https://github.com/sitespeedio/sitespeed.io/assets/22199881/c9f45689-b145-42a7-9c72-b8f7f84b6d44">

**Comment by Amerousful** [comment]
https://github.com/sitespeedio/sitespeed.io/pull/4007

**Comment by soulgalore** [comment]
Hi @Amerousful thank you! So the data of the console log is available in the PageXray tab, but adding a button sounds ok, thanks!

**Comment by Amerousful** [comment]
@soulgalore You're welcome!
Hm, I didn't find console log in the PageXray tab...

**Comment by Amerousful** [comment]
@soulgalore You so quickly released the new version! Thank you!

**Comment by soulgalore** [comment]
Please do!

**Comment by Amerousful** [comment]
Thanks heaps!

**Comment by Amerousful** [comment]
Here you're https://github.com/sitespeedio/sitespeed.io/pull/4012

**Comment by soulgalore** [comment]
This has been released.

**Comment by Amerousful** [comment]
I know, I've already updated to this version and am using it. Thank you!
