### ISSUE TITLE
sitespeed.io latest docker image timeout issue with javascript

### ISSUE THREAD

**Issue by dpeddaswamy** [sitespeedio/sitespeed.io#4017]
### Your question

Hi Team,
i am executing  sitespeed.io test using docker image from github actions. i have configured java script file and giving input to docker image. But when i execute the test i m getting timeout error.

Command:   docker run --rm -v $(pwd):$(pwd) -w $(pwd) <domain>sitespeedio/sitespeed.io -n 1 --spa --multi TestPlans/testscript.js -b edge --cookie TEXT="$COOKIE"  --browsertime.video false --axe.enable  --chrome.timeline --config TestPlans/PageSummaryConfig.json --outputFolder ./sitespeed-result

Log:
[2023-11-29 14:48:25] INFO: Versions OS: linux 5.19.0-41-generic nodejs: v20.9.0 sitespeed.io: 30.6.0 browsertime: 19.1.0 coach: 8.0.2
[2023-11-29 14:48:25] INFO: Axe version 4.8.2 plugin activated
[2023-11-29 14:48:25] INFO: Running tests using Edge - 1 iteration(s)
[2023-11-29 14:48:25] INFO: Using Edge is experimental at the moment and use the same configuration as for Chrome
[2023-11-29 14:48:30] INFO: Start to measure priceDateRule
[2023-11-29 14:48:31] INFO: Navigating to url https://<testdomain.com> iteration 1
[2023-11-29 14:50:42] ERROR: Failed waiting on page  to finished loading, timed out after 120000 ms Error: Running page complete check 
  return (function(waitTime) {
  const timing = window.performance.timing;
  const p = window.performance;
  const resourceTimings = p.getEntriesByType('resource');
  if (resourceTimings.length > 0) {
    const lastEntry = resourceTimings.pop();
    const stop = p.now() - lastEntry.responseEnd > waitTime;
    if (stop) {
      // empty resource timings for the next run
      p.clearResourceTimings();
      return true;
    }
  }
  else return false;

But when i save all urls in notepad file and execute the docker image , its working as expected..
Command:   docker run --rm -v $(pwd):$(pwd) -w $(pwd) <domain>/sitespeedio/sitespeed.io -n 1 --spa TestPlans/Test_URLs.txt --cookie TEXT="$COOKIE" --browsertime.video false --axe.enable --chrome.timeline --config TestPlans/PageSummaryConfig.json --outputFolder ./sitespeed-result

could you please help in resolving the issue.

**Comment by soulgalore** [comment]
Hi @dpeddaswamy can you test that the GitHub action can access the URL? You can try with curl or something like that first.

**Comment by soulgalore** [comment]
If you run it locally on your machine, does it work flawlessly? I remember when I tried it before GitHub runners had low resources cpu/memory and broke some tests for me when I tried it out. But I haven't been using it much nowadays.

**Comment by soulgalore** [comment]
Didn't get any response so closing.

**Comment by dpeddaswamy** [comment]
@soulgalore, above issue was fixed after adding Host entry in GitHub workflow yml file.

However, from Last month, i am facing again same issues with latest sitespeed.io docker image. Even after adding host entry i m getting time out error. Each url is tried 5 times. in between some times it works for first time, or at 3rd time etc..

Could you please help.

**Comment by soulgalore** [comment]
I wonder then if GitHub changed anything? I would add curl to the action and try how that works.
