### ISSUE TITLE
Connect ETIMEDOUT error while installing package

### ISSUE THREAD

**Issue by vishallanke** [sitespeedio/sitespeed.io#4018]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

24.9.0

### What are you trying to accomplish

In Gitlab our runners are running behind the proxy. Any npm package can be downloed b y setting proxy variables and it is working fine.
```
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY
```

However whne we are tryng to install sitespeed package, while installing chromedriver it throws error of timeout
`npm install sitespeed.io`

ERROR
```
npm ERR! code 1
npm ERR! path /builds/horizon/platform-tests/browser-performance/node_modules/sitespeed.io/node_modules/@sitespeed.io/chromedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Could not download Chromedriver: https://chromedriver.storage.googleapis.com/101.0.4951.15/chromedriver_linux64.zip Error: connect ETIMEDOUT 142.250.185.219:443
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:11[61](https://code.siemens.com/horizon/platform-tests/browser-performance/-/jobs/150268789#L61):16) {
npm ERR!   errno: -110,
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   syscall: 'connect',
npm ERR!   address: '142.250.185.219',
npm ERR!   port: 443
npm ERR! }
npm ERR! node:internal/process/promises:246
npm ERR!           triggerUncaughtException(err, true /* fromPromise */);
npm ERR!           ^
npm ERR! 
npm ERR! Error: connect ETIMEDOUT 142.250.185.219:443
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
npm ERR!   errno: -110,
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   syscall: 'connect',
npm ERR!   address: '142.250.185.219',
npm ERR!   port: 443
npm ERR! }
```

### What browser did you use?

Chrome

### How to reproduce

```shell
Same as above
```

**Comment by soulgalore** [comment]
Hi @vishallanke it seems the request is for Chromedriver 101, it's quite an old driver, can you update sitespeed.io so a new driver is used? Chrome has done some changes with Chromedrivers when they moved to Chrome for testing.

**Comment by vishallanke** [comment]
@soulgalore Checking this and will update you

**Comment by vishallanke** [comment]
Please check , I can see similar issue on runners running behind proxy with correct proxy variables set in Pipeline.
``
$ npm install sitespeed.io
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'chromedriver@119.0.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN deprecated wappalyzer-core@6.10.66: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /builds/horizon/platform-tests/browser-performance/node_modules/sitespeed.io/node_modules/@sitespeed.io/edgedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Could not download Edgedriver: https://msedgedriver.azureedge.net/119.0.2151.42/edgedriver_linux64.zip Error: connect ETIMEDOUT 13.107.246.60:4[43](https://code.siemens.com/horizon/platform-tests/browser-performance/-/jobs/150831069#L43)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
npm ERR!   errno: -110,
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   syscall: 'connect',
npm ERR!   address: '13.107.246.60',
npm ERR!   port: [44](https://code.siemens.com/horizon/platform-tests/browser-performance/-/jobs/150831069#L44)3
npm ERR! }
npm ERR! node:internal/process/promises:2[46](https://code.siemens.com/horizon/platform-tests/browser-performance/-/jobs/150831069#L46)
npm ERR!           triggerUncaughtException(err, true /* fromPromise */);
npm ERR!           ^
npm ERR! 
npm ERR! Error: connect ETIMEDOUT 13.107.246.60:443
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
npm ERR!   errno: -110,
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   syscall: 'connect',
npm ERR!   address: '13.107.246.[60](https://code.siemens.com/horizon/platform-tests/browser-performance/-/jobs/150831069#L60)',
npm ERR!   port: 443
npm ERR! }

```

**Comment by soulgalore** [comment]
I think this was a temporary issue for chromedriver/edgedriver storage and nothing to actually do with sitespeed.io so closing.
