### ISSUE TITLE
 SITESPEED_OPTIONS : "--browsertime.connectivity.profile 3g " doesn't seem to work on gitlab

### ISSUE THREAD

**Issue by NOuennich** [sitespeedio/sitespeed.io#4021]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://parkos.it/

### What are you trying to accomplish

I'm running sitespeed with gitlab simple configuration https://docs.gitlab.com/ee/user/project/merge_requests/browser_performance_testing.html  and I've used the option to use a specific profile which is 3g but when I check the settings I still get 'No connectivity settings' 
Am I missing something ?

### What browser did you use?

Chrome

### How to reproduce

```shell
1. configure use this gitlab.yml 

stages:
  - tests

include:
  - template: Verify/Browser-Performance.gitlab-ci.yml  

browser_performance:
  stage: tests
  URL: https://parkos.it/
  SITESPEED_OPTIONS : "--browsertime.connectivity.profile 3g "

2. run the pipeline
3. check the settings for connectivity or if the option exist in the job logs
```

**Comment by soulgalore** [comment]
Hi @NOuennich thanks for creating the issue. GitLab using Docker containers right for the CI? To get that to work the actual server needs` sudo modprobe ifb numifbs=1 ` and then the container needs to run with  `–cap-add=NET_ADMIN` to be able to change the connectivity.

There are some documentation here:
https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#throttle

**Comment by NOuennich** [comment]
I'm using the run the sitespeed.io container https://hub.docker.com/r/sitespeedio/sitespeed.io/ does it also need these additional steps ? I thought it's simply handled with the SITESPEED_OPTIONS in this case

**Comment by soulgalore** [comment]
The actual physical server at GitLab needs to run `sudo modprobe ifb numifbs=1` so you need to ask their support and then the container needs to run with `–cap-add=NET_ADMIN` to give the container rights to change the connectivity, you need to ask the GitLab support how that is setup today.

**Comment by NOuennich** [comment]
Okey, thank you for your guidance.

**Comment by soulgalore** [comment]
Closing, please let me know if you need any more info.
