### ISSUE TITLE
slack notification not working when slack.type error

### ISSUE THREAD

**Issue by amitdisha** [sitespeedio/sitespeed.io#4028]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io/

### What are you trying to accomplish

I want to enable slack notification for test run ONLY IN CASE OF ERROR where error means when --slack.limitError is violated

### What browser did you use?

Chrome

### How to reproduce

```shell
SLACK NOTIFICATION NOT WORKING
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:30.7.0 -n 1  https://www.sitespeed.io/ --slack.hookUrl https://hooks.slack.com/xxxxxx --slack.channel  performance-test-reports --slack.type error --slack.limitMetric lastVisualChange --slack.limitError 50

SLACK NOTIFICATION WORKS
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:30.7.0 -n 1  https://www.sitespeed.io/ --slack.hookUrl https://hooks.slack.com/xxxxxxx --slack.channel  performance-test-reports --slack.type all --slack.limitMetric lastVisualChange --slack.limitError 50
```

### Log output

```shell
NA
```

**Comment by amitdisha** [comment]
Also since it is straight forward way , i want to skip alerting from grafana and use this feature if this works fine.

**Comment by soulgalore** [comment]
Hi @amitdisha how do I reproduce an error so the error is sent, I didn't fully get that? Can you share so I can test? 

Thanks

**Comment by amitdisha** [comment]
Consider below example 

SLACK NOTIFICATION NOT WORKING
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:30.7.0 -n 1  https://www.sitespeed.io/ --slack.hookUrl https://hooks.slack.com/xxxxxx --slack.channel  performance-test-reports --slack.type error --slack.limitMetric lastVisualChange --slack.limitError 50

here , slack.limitError is 50 millisecond , but page takes more than 50ms(lastVisualChange) hence i consider it as error. So when i set --slack.type error in above command , i expect slack notification for the same . My usecase if to get slack notified whenever performance of page is more than --slack.limitError.

**Comment by soulgalore** [comment]
I see wee are missing documentation of what you sending. `--slack.type ` can either send the metrics for a URL, for a summary of urls (like a summary for the tested domain), errors that happend from the test (like the page is down etc) or all different types. You had configured "errors" so it will only send errors. The different limits is the configuration of the colors in the message. In your example a last visual change higher than 50 ms will create a red message in Slack. A warning will generate a yellow.

**Comment by amitdisha** [comment]
Oh, then probably I cannot use this feature as I want to send slack notifications only if lastvisualchange performance is more than limit to avoid too many notifications for each run.
