### ISSUE TITLE
LCP and FCP on sitespeed.io vary greatly from LCP and FCP on pagespeed.web.dev

### ISSUE THREAD

**Issue by jhampleman** [sitespeedio/sitespeed.io#4036]
Running speed/performance tests on sitespeed.io and pagespeed.web.dev return very different results, especially in terms of FCP and LCP.  Are there settings that I am missing to explain the difference?  sitespeed.io is a great tool, and I use it often, but I'm not sure about the results for some metrics.  See attached screens.  Thank you!
![Screenshot at Dec 20 16-47-08](https://github.com/sitespeedio/sitespeed.io/assets/48455141/86a9eee1-49c7-4bed-acc8-86ee4228cedb)

**Comment by soulgalore** [comment]
Hi @jhampleman great question, I add that to the FAQ later.

What you see there in the web dev data is the metrics from [Chrome user experience report](https://developer.chrome.com/docs/crux) meaning data that Chrome collected from users accessing that site and that "agreed" to Google to collect that data. It shows the 75 percentile, meaning 75 percent of the users (that Google collects the data from) have that metric or faster. In your example 75 % of the users have a Largest Contentful Paint faster than 3,4 seconds. Those users have different CPU speed and different network conditions than your current tests.

![webdev](https://github.com/sitespeedio/sitespeed.io/assets/540757/aacf206a-24d4-4537-8d57-ebf055d58774)

Is that data any good? Yes if you don't collect any metrics yourself using real user monitoring, this can be really useful. However its only from Chrome users that agreed that the data can be collected so it can give you a skew view of the metric (you probably have users that uses Safari/Edge/Firefox and maybe more browsers).

You can (and should) use that data to tune your sitespeed.io tests, it gives you insights so you can run your tests as the 75 percentile of your users. For example, look at your 75p TTFB and then using sitespeed.io you use network throttling to try to get the same TTFB as in the Google data. Then look at FCP/LCP are they matching? If not, you can also try to slow down the CPU (or even better if you run your test on real mobile devices). There are some documentation [here](https://www.sitespeed.io/documentation/sitespeed.io/cpu-benchmark/) on how we been doing that for testing Wikipedia.

Actually sitespeed.io have a [Chrome user experience report plugin](https://www.sitespeed.io/documentation/sitespeed.io/crux/) that you can use to collect that data direct from Google. That way you can always compare those metrics with your sitespeed.io run. 

As general advice I would think like this:
1. Do we have our own real user monitoring metrics? Use that to tune the sitespeed.io tests.
2. No we don't, so instead use the Chrome user experience data (remember that it can be skewed but probably better than not using at all).

**Comment by jhampleman** [comment]
Thank you very much!  Really appreciate the thoughtful, detailed response.
