### ISSUE TITLE
Thresholds for specific metrics (core webvitals one) 

### ISSUE THREAD

**Issue by NOuennich** [sitespeedio/sitespeed.io#4037]
Based on giltab documentation [SITESPEED_OPTIONS : ](https://docs.gitlab.com/ee/ci/testing/browser_performance_testing.html#configuring-degradation-threshold) and your documentation https://www.sitespeed.io/documentation/sitespeed.io/configure-html/ there is no configuration that will make the pipeline fail by setting specific thresholds per metric,
for example LCP needs to be between 1s - 2,5s
FID between 50 - 100ms
and CLS between 0,05 - 0,1

**Comment by soulgalore** [comment]
Hi @NOuennich a range is not supported but a hard limit, you can checkout the budget functionality in https://www.sitespeed.io/documentation/sitespeed.io/performance-budget/

**Comment by soulgalore** [comment]
Use the performance budget.
