### ISSUE TITLE
Firefox crash with gecko driver and xfce desktop to export display on vnc viewer

### ISSUE THREAD

**Issue by dr1408** [sitespeedio/sitespeed.io#4066]
### Your question

m using arm7 phone and with unrooted termux and xfce desktop to export display to vnc i use tool to enter whatsapp web in my  vncviewer but when i enter any 
conversation on firefox in the vnc firefox crashes immediately

this is the geckodriver traceback

Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=80.6358) Exiting due to channel error.
Exiting due to channel error.
[1705551185835](tel:1705551185835) geckodriver INFO Listening on 127.0.0.1:39869
[1705551195254](tel:1705551195254) mozrunner::runner INFO Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/dat ... 46607" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/data/data/com.termux/files/>
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
Read port: 39865
[1705551197478](tel:1705551197478) Marionette INFO Marionette enabled
Read port: 39865
Read port: 39865
[1705551197732](tel:1705551197732) Marionette INFO Listening on port 36577
Read port: 36577
WebDriver BiDi listening on ws://127.0.0.1:46607
[1705551198233](tel:1705551198233) RemoteAgent WARN TLS certificate errors will be ignored for this session
console.error: ({})
console.error: "Translations: SIMD not supported" (new CompileError("at offset 15: bad type", "chrome://global/content/translations/simd-detect-worker.js", 14))
DevTools listening on ws://127.0.0.1:46607/devtools/browser/a45657dd-1c54-44ff-ba84-056b9b8dd960
JavaScript warning: https://web.whatsapp.com/main.0cf917fc9b3d8f353e54.js, line 5: unreachable code after return statement
JavaScript warning: https://web.whatsapp.com/main.0cf917fc9b3d8f353e54.js, line 5: unreachable code after return statement
JavaScript error: resource://gre/modules/PromiseWorker.sys.mjs, line 102: Error: Could not get children of file(/data/data/com.termux/files/usr/tmp/rust_mozprofileSvOYg0/thumbnails) because it does not exist
Exiting due to channel error.
Exiting due to channel error.

is it problem because the tmp folder in directory that maybe cant be reachable due to rootless android and how i can change it to sdcard because i saw a comment for you about it i hope 

i know its not about your tools sir but i appreciate any help since no one helped me on gecko and selenium github

**Comment by soulgalore** [comment]
Hi @dr1408 I would report that to Mozilla if its a Firefox crash: https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla
