### ISSUE TITLE
How to configure plugins?

### ISSUE THREAD

**Issue by kanertuncel** [sitespeedio/sitespeed.io#4086]
Thanks for awesome codebase. I'm wondering if there is any chance to add configuration flags for plugins (e.g. 'coach') 
`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:33.0.0 https://sitespeed.io --plugins.coach.limit 101`

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @kanertuncel thanks for the kind words. So can you share a little more how you think or what you need, I didn't fully get it, sorry?

**Comment by kanertuncel** [comment]
Of course, I'm using sitespeed/sitespeed.io as the docker image and I'm running it using the command provided as in the docs. Something like:
```
const config = {
            "browsertime": {
                "browser": "chrome",
                "iterations": 1,
                "video": false,
                "headlesss": true,
                "screenshot": false
            },
            "plugins": {
                "remove": ["html"],
                "add": "analysisstorer"
            },
            "summary": true,
            // "slug": "",
            "summary-detail": true,
            "sustainable": {
                "enable": true,
                'pageviews': 1
            },
            "coach": {
                "limit": 101,
            },
            "crux":
            {
                "key": process.env.GOOGLE_CLOUD_API_KEY,
                "enable": true
            },
            "axe": {
                "enable": true
            },
            "crawler": {
                "depth": 1,
                "maxPages": 1
            }
        }

        let cliOptions = '';
        for (const [key, value] of Object.entries(config)) {
            if (typeof value === 'object') {
                for (const [subKey, subValue] of Object.entries(value)) {
                    cliOptions += `--${key}.${subKey} ${subValue} `;
                }
            } else {
                cliOptions += `--${key} ${value} `;
            }
        }

        return new Promise((resolve, reject) => {
            const guid = randomUUID();
            shell.exec(`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:33.0.0 ${candidate} --outputFolder sitespeed/${guid} ${cliOptions}`, (code: any, stdout: any, stderr: any) => {
                if (code !== 0) {
                    reject(new Error(`Shell command failed with code ${code}: ${stderr}`));
                    return;
                }

                resolve(guid);
            });
        });
```

But, in this case i'm confused and couldn't add more attributes for sub services. e.g. `Coach` has more flags like --limit,--details, --description flag, (https://www.sitespeed.io/documentation/coach/how-to/). I'm not sure if I can pass these parameters to docker exec command, thanks for the help.

**Comment by soulgalore** [comment]
Ok, could you use a configuration file directly that you mount to inside the container as in https://www.sitespeed.io/documentation/sitespeed.io/configuration/#configuration-as-json ? Then you don't need to recreate them as cli commands (or is it something that I'm missing?).

Then you can have section with all coach configurations:
```
coach: {
 key: value,
key2: value2
}
```

I wonder though, I don't think we expose so many configurations for the coach, like when we run it today inside sitespeed.io we just use default settings?

**Comment by kanertuncel** [comment]
Totally agree, default configuration also works great. I already tried with config.json but unfortunatelly, didn't work for me.

**Comment by soulgalore** [comment]
Yeah, but I don't think we pass on any configurations from sitespeed.io to the coach? What do you want/need to configure?

**Comment by soulgalore** [comment]
Ah ok, sorry that isn't implemented in sitespeed.io, only if you run the coach directly.

**Comment by kanertuncel** [comment]
No worries, take a bow for this awesome open source project, I hope it takes a PR soon :)  Thank you very much.
