### ISSUE TITLE
Sitespeed.io command not found 

### ISSUE THREAD

**Issue by Pashmaniwala** [sitespeedio/sitespeed.io#4098]
### Your question

I have installed latest version on Windows os V 32.2.0. It was working fine until yesterday but i am getting error as mentioned in title starting yesterday 

i am clueless why it stopped working when i am even not able execute version command 

sitespeed.io —version

**Comment by soulgalore** [comment]
Hi @Pashmaniwala we have an Github Action on Windows [where it works.](https://github.com/sitespeedio/sitespeed.io/actions/runs/8050437183/job/21986030068). We install and run it in bash there, here's the code for that: https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/windowsFull.yml

Hope that can help!

**Comment by Pashmaniwala** [comment]
If you are available i can share webex link to share my screen and explain you issue 

please let me know your availability. I work in EST timezone

**Comment by soulgalore** [comment]
Hi sorry that do not scale for me, please explain in the issue why the setup in the GitHub Action do not work for you and what kind of problem you have and follow the[ guidance in how to make a reproducible bug](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue). That way if there are someone else that have the same problem, they will find this issue and hopefully someone can help out.

Thanks!

**Comment by Pashmaniwala** [comment]
The issue is resolved by setting up path locally on windows 

npm config set prefix c:/Users/<usernamr>/AppData/Roaming/npm
