### ISSUE TITLE
How to use resultBaseURL for NodeJS+InfluxDB+Grafana setup on Windows machine [Local] to view HTML URL and Screenshot on Grafana

### ISSUE THREAD

**Issue by shrutiseth** [sitespeedio/sitespeed.io#4146]
### Your question

Hello @soulgalore,

I am configuring sitespeedio on my windows local machine using NodeJS + InfluxDB + Grafana, since docker is not allowed in my organization. 

I have been able to get the Front End metrics on the Grafana dashboard for all the tests done during the time window in a table:
<img width="956" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/45349166/f9a7d931-1333-46f6-9a19-d6cfbc106461">

I want to get the link to the Index.HTML for each of the tests along with Screenshot in the table too. Can you please guide me what should be the syntax?

I have referred - https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#annotations and https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#annotations but I am not sure of the command.

Currently I am using:
 sitespeed.io https://www.sitespeed.io/ --urlAlias Sitespeedio -n 1 --influxdb.host localhost --video --visualMetrics --viewPort 1024x768 --influxdb.annotationScreenshot --resultBaseURL localhost -v --logToFile

Output:
<img width="960" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/45349166/fef5e3c6-3298-4d38-86d6-bc437b93a8f5">

Log file shows:
<img width="836" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/45349166/05a00b16-d17d-4548-a5fa-0db44d5caedf">

My question is: What should i write in --resultBaseURL <what should be the path here?>

Thanks for your time!

**Comment by shrutiseth** [comment]
Hello @soulgalore - 
Am able to insert with following command: 
sitespeed.io https://www.sitespeed.io/ --urlAlias Sitespeedio -n 1 --influxdb.host localhost --video --visualMetrics --viewPort 1024x768 --influxdb.annotationScreenshot --resultBaseURL file:///C:/Users/shruti.s.seth/AppData/Roaming/npm/node_modules/sitespeed-result/ -v --logToFile

Am able to get correct path in events measurement of influxDB:
<img width="993" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/45349166/d8f93c11-083d-4f5a-9556-5d55e0c5b3e1">

And my index.html is accessible from this path when I copy paste below command in Chrome address bar:
file:///C:/Users/shruti.s.seth/AppData/Roaming/npm/node_modules/sitespeed-result//www.sitespeed.io/2024-04-26-22-40-01/pages/www_sitespeed_io/Sitespeedio/index.html

**However, how do I add my Device Name: P3BLAP-DY7TPP3 to access the index.html? so anyone can open it directly?**

**Comment by shrutiseth** [comment]
@zer0kool can you please guide here?

**Comment by soulgalore** [comment]
Hi @shrutiseth I would try to serve the content through a web server so you would do it the same way if you serve it locally or through a web server. If you have the server running your result base you can use your IP adress instead of file:// etc.

**Comment by shrutiseth** [comment]
Hello @soulgalore 

**I tried using http://hostname -**
![image](https://github.com/sitespeedio/sitespeed.io/assets/45349166/ea11262a-a86a-43e9-9c9e-a6ac9d19a49a)

**Using IP address:**
 sitespeed.io  https://www.sitespeed.io/ -n 1 -b chrome --influxdb.host localhost --resultBaseURL http://10.4.169.100/C/Users/sethss/AppData/Roaming/npm/node_modules/sitespeed-result/
![image](https://github.com/sitespeedio/sitespeed.io/assets/45349166/0b5af605-b6f9-4fc3-8122-9c0c9232ab26)

When I try to open this file:

![image](https://github.com/sitespeedio/sitespeed.io/assets/45349166/ea2c38ff-6855-4c08-82d4-a6db50bf0a8e)

http://awnhybristestq8/www.sitespeed.io/2024-05-03-08-42-41/index.html also gives same error.

Please guide :(

**Comment by soulgalore** [comment]
Have you setup a HTTP server that serves the content on your machine? I'm not 100% sure I understand what you want to accomplish? :) Do you want to run it locally to test everything or what's your end goal?

**Comment by shrutiseth** [comment]
Thanks. After installing Apache24 I was able to make it a file server.
