### ISSUE TITLE
Avoid screenshot capturing

### ISSUE THREAD

**Issue by sweety-18** [sitespeedio/sitespeed.io#4189]
### Your question

Hello,
I am using docker command as 
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io XXX.js --multi --viewPort 1786x708 --maxLoadTime 180000 --video=false --visualMetrics=false --visualElements=false --plugins.remove screenshot --plugins.remove har -n 1 -b chrome

It disables video capturing, but not removing screenshots taking. Could you suggest any parameter to disable taking screenshot.

[Take after page complete check screenshot
Take cumulative layout shift screenshot
Take largest contentful paint screenshot
No element attached to the entry in largest-contentful-paint]

**Comment by soulgalore** [comment]
Hi I think you can try:

`--browsertime.screenshot false --browsertime.screenshotLCP false --browsertime.screenshotLS false` but I think there's a bug for disabling LCP/LS screenshots, I'll look into that.

**Comment by sweety-18** [comment]
By trying the mentioned command, its only eliminating one screenshot, I am getting like this
Take cumulative layout shift screenshot
Take largest contentful paint screenshot
 No element attached to the entry in largest-contentful-paint

Can you please let me know how to disable these screenshots

**Comment by Perf-meghana** [comment]
Hi @soulgalore, Can you please take a look at the bug for disabling LCP/LS screenshots. It would be really helpful for me to get accurate response times, as I am very dependent on this issue. Thanks.

**Comment by sweety-18** [comment]
Hi @soulgalore, Can you please take a look at the bug for disabling LCP/LS screenshots. It would be really helpful for me to capture accurate response times. Thanks.

**Comment by soulgalore** [comment]
Let me do a fix release tomorrow that fixes it.

**Comment by sweety-18** [comment]
Sure, Thanks.

**Comment by soulgalore** [comment]
> It would be really helpful for me to capture accurate response times

Can you explain some more what you mean by accurate? The screenshots are taken after the measurements are taken so they will not affect any measurements.

**Comment by sweety-18** [comment]
Oh Okay got it. Can you please fix the bug for disabling LCP/LS screenshots.

**Comment by soulgalore** [comment]
It's coming out later today. Can you explain more why you don't need the screenshots, I haven't run into that use case before.
