### ISSUE TITLE
How to retrieve defined parameter values inside .env file while script running through Jenkins

### ISSUE THREAD

**Issue by pjayaweera** [sitespeedio/sitespeed.io#4193]
I have script named as **01_User_script.js** and have defined several inputs/parameters inside .env file as below. (Line 16, Line 22, Line 23)

<img width="626" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/147686082/ae3cf373-81ab-4ba7-9923-b3e984ef49e3">

<img width="766" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/147686082/305ae885-50f9-4a9c-872e-b4b562967739">

How i can update the Jenkins pipeline script, to command retrieve necessary input values from .env file. My current working pipeline script as below. (i have attached the pipeline script as txt file)

<img width="820" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/147686082/855645e4-2a6d-4b48-b323-5b03fda284e7">

[pipeline.txt](https://github.com/user-attachments/files/15900721/pipeline.txt)

**Comment by soulgalore** [comment]
Here's an example on how you can use .env files in NodeJS:
https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs

**Comment by pjayaweera** [comment]
@soulgalore 

Currently I'm using .env file in my script shown in t above screenshot and its working fine locally.
i.e - process.env.RPM_dashbord_URL) (line 16)
![image](https://github.com/sitespeedio/sitespeed.io/assets/147686082/c0a6602b-03a3-484e-a3fe-ab6c9e3244e8)


I wanted to know how to use values inside .env file when it comes to CI/CD environment. I'm getting following error while trying to access .env file parameters from Jenkins.

<img width="704" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/147686082/f9b745dd-cea9-487e-bdff-ab2e640af50b">

**Comment by pjayaweera** [comment]
@soulgalore any thought on this?

**Comment by soulgalore** [comment]
Can you log the URL in your script and see what it is? I usually use https://www.sitespeed.io/documentation/sitespeed.io/scripting/tutorial-18-Tips-and-tricks.html#pass-your-own-options-to-your-script instead of .env.

**Comment by pjayaweera** [comment]
![image](https://github.com/sitespeedio/sitespeed.io/assets/147686082/64c403fc-7903-4ed4-b157-8ed8e98c9c70)

<img width="419" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/147686082/060c7bda-d265-45ce-ab08-4d80092cfc40">

Found a solution by myself.

I had to change the Jenkins file as above screenshot and now this is working fine. First need to load .env file while running the pipeline script. Then only we can use variables inside .env file

**Comment by soulgalore** [comment]
Ok, great so closing.
