### ISSUE TITLE
S3 upload not working with DigitalOcean since version 34

### ISSUE THREAD

**Issue by chosroes** [sitespeedio/sitespeed.io#4194]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.google.fr

### What are you trying to accomplish

I'm trying to upload results to DigitalOcean space via S3 SDK. But since upgrading to version 34, even the last one, it doesn't work

### What browser did you use?

Chrome

### How to reproduce

```shell
Using this configuration, it works with sitespeed version 33.6, but no with 34.2.2 :
  "s3": {
    "endpoint": "fra1.digitaloceanspaces.com",
    "region": "us-east-1",
    "key": "my-key",
    "secret": "my-secret",
    "acl": "public-read",
    "bucketname": "my-bucket",
    "removeLocalResult": true,
    "options": {
      "forcePathStyle": false
    }
  }
```

### Log output

```shell
ERROR: Error uploading /my-path/2024-06-19-12-00-06/detailed.html to S3 bucket my-bucket: TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at parseUrl (/usr/src/app/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)
    at toEndpointV1 (/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:41)
    at customEndpointProvider (/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)
```

**Comment by soulgalore** [comment]
Hi @chosroes thank you for reporting. In 34 we upgraded to the [v3 of the AWS S3 plugin](https://github.com/sitespeedio/sitespeed.io/blob/main/CHANGELOG.md#3400---2024-05-29) so it must be related to that. I verified on S3 and MinIO and got reports that it works on Ceph S3. I checked https://docs.digitalocean.com/products/spaces/how-to/use-aws-sdks/ but couldn't see something. I think I got an old DO account so I can try later today. In the mean time, please check if you can find something related to [V3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/) and Digital Ocean.

**Comment by soulgalore** [comment]
@chosroes according to https://github.com/strapi/strapi/issues/18913 the endpoint need http/https can you try if that helps?

**Comment by chosroes** [comment]
@soulgalore Adding https to the endpoint solved the problem for me. Thank you
