### ISSUE TITLE
ERROR: [plugin.browsertime] Caught error from Browsertime TypeError: result[resultIndex].files.screenshot[runIndex] is not iterable     at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js

### ISSUE THREAD

**Issue by sweety-18** [sitespeedio/sitespeed.io#4202]

**Comment by soulgalore** [comment]
Hi @sweety-18 please follow the guidance in https://www.sitespeed.io/documentation/sitespeed.io/bug-report/

**Comment by sweety-18** [comment]
I was executing sitespeed scripts to capture response times. When I tried to run script with including more than one start and stop in a script file, I am getting an error. I was not getting with previous version, with updated latest version only I am getting this error.

**ERROR: Caught error from Browsertime TypeError: result[resultIndex].files.screenshot[runIndex] is not iterable
    at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:430:76)**

**Command:** 
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io XXX.js --multi --viewPort 1786x708 --maxLoadTime 180000 --video=false --visualMetrics=false --visualElements=false --browsertime.screenshot false --browsertime.screenshotLCP false --browsertime.screenshotLS false --plugins.remove screenshot --plugins.remove har -n 1 -b chrome

**Script:**

  await commands.addText.byId('XXX', 'username');
  await commands.click.byXpathAndWait("");
  await commands.addText.byId('XXX', 'password');
  await commands.measure.start('Test1');
  await commands.click.byXpathAndWait("");
  await commands.measure.stop();
  await commands.wait.byXpath("", X0000)

  await commands.measure.start('Test2');
  await commands.click.byXpathAndWait("");
  await commands.click.byXpathAndWait('');
  await commands.measure.stop();
