### ISSUE TITLE
Graphite and Grafana Integration queries

### ISSUE THREAD

**Issue by yashgarde** [sitespeedio/sitespeed.io#4238]
### Your question

I had a few questions regarding the provided Grafana dashboards for performance monitoring:
1. I noticed that the Page Metrics dashboard's metric tiles, screenshots and video tiles all only display the metrics and content from the most recent run for a certain testname (slug name). While the time series shows all historical data as well, however click on the points on the time series does not update the data on the metric tiles surrounding the time series graph. Is this something we would need to configure? Is this data available so that clicking on the points in the time series shows all the metrics for that particular test run?
2. Similar to above, I would also like to have a link out to the sitespeed results HTML page for each individual test run rather than just the most recent test run for that testname (slug name). Currently, the provided meta data field only contains a link to the most recent test run for a particular test name and I was wondering if this data is stored anywhere in Graphite or the sitespeed S3 bucket (when using Onlinetest) to be pulled?

**Comment by soulgalore** [comment]
> 1.
> 2

No. That's no way to do that today as you describe. If you enable the "Go to result" at the top, you will see vertical lines on the metrics, hover on those and you can see the screenshot/links to the result. If you do not see the lines, enable only one metric in the graph (like first visual change) and try again (there's been a bug in Grafana for a while that sometimes make the annotations not show up).
