### ISSUE TITLE
Why cannot store data to influxDB v2 ?

### ISSUE THREAD

**Issue by noviantonugroho4** [sitespeedio/sitespeed.io#4253]
### Your question

when i try store to influxdb2 with configuration at below : 

 ```
"influxdb": {
      "protocol": "https",
      "host": "influxdb2-test.io",
      "port": 8086,
      "version": 2,
      "organisation": "influxdata",
      "database": "sitespeed_pg",
      "token":"xxxxxx",
      "annotationScreenshot": true
    }
```
    
the return error : 

<img width="857" alt="Screenshot 2024-08-04 at 08 26 10" src="https://github.com/user-attachments/assets/a8cf4a3f-c310-4737-b502-e42c35159e9e">

    
    
but **when i tried to use internal docker , the result is success** . with configuration at below :
    
    "influxdb": {
      "host": "host.docker.internal",
      "version": 2,
      "organisation": "test",
      "database": "test",
      "token":"xxxxxxxx,
      "annotationScreenshot": true
    } 
   
   
   
can you tell me how to solve this case ? thank you

**Comment by soulgalore** [comment]
Hi @noviantonugroho4 so your servers name is influxdb2-test.io and you run everything on the same machine is that correct? Inside the Docker container, the local server name isn't reachable, you need to do as you did with the hack for reaching your local server: https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-host-in-your-local-network

Or what was your question? :)

**Comment by noviantonugroho4** [comment]
hi @soulgalore i'm running with difference machine ,,
which is i deploy the influxdb2 using k8s, any suggestion ?

**Comment by noviantonugroho4** [comment]
Hi @soulgalore  my case solve, the problem the port not using 8086 (as default) .. sorry and thanks for your response 🙏🏻
