### ISSUE TITLE
sitespeedio/sitespeed.io:34.9.0 Waterfall link no longer working

### ISSUE THREAD

**Issue by johnjooo** [sitespeedio/sitespeed.io#4312]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

http://jenkins

### What are you trying to accomplish

Trying to check the waterfall in the sitespeed report but it no longer works

### What browser did you use?

Chrome, Firefox, Safari Mac OS

### How to reproduce

```shell
How to reproduce issue. 

Run a sitespeed test using sitespeedio/sitespeed.io:34.9.0 in Docker
Go to the Sitespeed report

Click on Pages
if you select a URL/page you will see the summary tab, waterfall tab, metrics tab , filmstrip tab etc
when you click on the Waterfall Tab it no longer brings you to the water fall. This was working yesterday
```

### Log output

```shell
cant share log
```

**Comment by soulgalore** [comment]
Hi @johnjooo thanks for creating the issue! Hmm, I don't remember any change for that code the last releases/years. Can you open devtools and see if you get any JavaScript errors in the console? We have tests continuously running and when I tested there it seems to work: 

https://data.sitespeed.io/firstViewDocker/2024-11-06-18-41-17/pages/en_wikipedia_org/wiki/Barack_Obama/2.html

**Comment by johnjooo** [comment]
<img width="814" alt="image" src="https://github.com/user-attachments/assets/77844390-ff44-4b42-94fc-f11fd198c314">
div id="tabs"><a id="summary" href="#summary" onclick="return selectTab(this, true);">Summary</a><a id="waterfall" href="#waterfall" onclick="return selectTab(this, true);">Waterfall   </a><a id="metrics" href="#metrics" onclick="return selectTab(this, true);">Metrics</a><a id="filmstrip" href="#filmstrip" onclick="return selectTab(this, true);">Filmstrip      </a><a id="coach" href="#coach" onclick="return selectTab(this, true);">Coach</a><a id="pagexray" href="#pagexray" onclick="return selectTab(this, true);">PageXray</a><a id="thirdparty" href="#thirdparty" onclick="return selectTab(this, true);">Third party   </a></div>

**Comment by soulgalore** [comment]
That looks like the HTML and not the JavaScript console? For example, if you use Chrome you find it if you choose view and Developer:
<img width="611" alt="Screenshot 2024-11-07 at 16 29 19" src="https://github.com/user-attachments/assets/e62b9b68-dd48-4a2c-a422-049462829d6d">

**Comment by johnjooo** [comment]
everything in on the one page, none of the tabs bring you anywhere. 
<img width="814" alt="image" src="https://github.com/user-attachments/assets/54988d15-7dc7-44b1-8862-01a56dfd5ca1">

**Comment by johnjooo** [comment]
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash is all i see in console

**Comment by johnjooo** [comment]
Its all back working today Thanks
