### ISSUE TITLE
Firefox CPU Power Consumption values have incorrect units (µWh instead of Wh)

### ISSUE THREAD

**Issue by canova** [sitespeedio/sitespeed.io#4333]
I was looking into #4329 and realized that the power consumption values have incorrect units. It should be `Wh` and not `µWh`.

The same STR with #4329 can be used for testing.

For example it shows `0.0036 µWh` in a report on my machine, but it should be `0.0036 Wh` (or better yet, `3.6 mWh`).

Inside the Firefox Profiler we also have a logic to choose the best unit depending on the value:
https://github.com/firefox-devtools/profiler/blob/6306555856f9c5b1f539462f24c182b7c07d477b/src/components/tooltip/TrackPower.js#L84-L115

So this way the unit is always readable/meaningful to the user. But I don't know how easy it is to implement something similar here.

**Comment by soulgalore** [comment]
Hi @canova ooops, thanks! Let me fix that.
