### ISSUE TITLE
url couldn't be fetched. (no following redirects)

### ISSUE THREAD

**Issue by kdjonua** [sitespeedio/sitespeed.io#447]
Hi, @soulgalore again!

I noticed that the site will not be analyzed, if the server sends http 30x codes. 
For example, a site http://hh.ru. HTTP headers info here http://www.bertal.ru/index.php?a1347640/hh.ru

sitespeed.io should not follow redirects chain to 200?

**Comment by soulgalore** [comment]
Hi @kdjonua 
is this still a issue for you?

**Comment by soulgalore** [comment]
fixed in 4.0
