### ISSUE TITLE
Issue with IE 11

### ISSUE THREAD

**Issue by SunilSyal** [sitespeedio/sitespeed.io#488]
We are using sitespeed in one of our projects. It has a problem with IE 11 and does not work if the following command is executed in JavaScript:

window.performance.mark("Some String")

Error messge: 
BrowserTime failed to fetch XXXXXXXXXX, check the error log /c/Users/XXXXXXXXX/error.log
Could not collect Navigation Timing metrics for XXXXXXXXXX using ie

And in error log file:
INFO: I/O exception (java.net.SocketException) caught when processing request: Software caused connection abort: recv failed

Any workaround?

**Comment by soulgalore** [comment]
IE 11 is up and running with the new version now, please reopen if you have any problem.
