### ISSUE TITLE
Show javascript errors

### ISSUE THREAD

**Issue by giannisf19** [sitespeedio/sitespeed.io#506]

**Comment by RasPat1** [comment]
Are people still interested in this?  I'm willing to commit some time to help building this out.

**Comment by soulgalore** [comment]
hey @RasPat1  yes that would be super cool. It needs to be implemented in Browsertime, we use the [1.0 branch](https://github.com/tobli/browsertime/tree/1.0).  Check it out and see if it's something you wanna do! 

Best
Peter
