### ISSUE TITLE
Specific Graphite namespace for each url (--file and --sites)

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#517]
It would be nice if it was possible to add an extra Graphite namespace per url you specify with the --file parameter. And when using --sites (with master en subfiles).

```
http://www.jeroenvdb.be/ --graphiteNamespace homepage
http://www.jeroenvdb.be/a-nice-article/ --graphiteNamespace article
http://www.jeroenvdb.be/sports/ --graphiteNamespace section
```

```
http://www.othersiteofmine.be/ --graphiteNamespace homepage
http://www.othersiteofmine.be/another-nice-article/ --graphiteNamespace article
http://www.othersiteofmine.be/sports/ --graphiteNamespace section
```

Graphite query could then be something like:

```
homepage.summary.www.jeroenvdb.be.rule.ruleScore.max
```

And for Grafana (with templates):

```
$template.summary.www.$website.be.rule.ruleScore.max
```

Alternatively I can make a sitespeed.io command per url but then the metrics don't have the same timestamp, which is handy for comparison.

**Comment by JeroenVdb** [comment]
Little edit: the --graphiteNamespace parameter per url should be used instead of the website url in the Graphite query.

In my use case the urls I want to track (the homepage, a section and an article) have different levels: /, /<section>/ and /<section>/<article>
```
http://www.othersiteofmine.be/ --graphiteNamespace othersiteofmine.home
http://www.othersiteofmine.be/sports/ --graphiteNamespace othersiteofmine.section
http://www.othersiteofmine.be/sports/another-nice-article/ --graphiteNamespace othersiteofmine.article
```
In Graphite query this would be something like:
```
.summary.www.othersiteofmine.be.rule.ruleScore.max
.summary.www.othersiteofmine.be.sports.rule.ruleScore.max
.summary.www.othersiteofmine.be.sports.another-nice-article.rule.ruleScore.max
```
The thing about this is that I can't use a template in Grafana to select one (or all) of them because of the different "levels" (or can I?).

With the graphiteNamespace parameter the query would be this:
```
.summary.othersiteofmine.home.rule.ruleScore.max
.summary.othersiteofmine.section.rule.ruleScore.max
.summary.othersiteofmine.article.rule.ruleScore.max
```

**Comment by soulgalore** [comment]
Hi @JeroenVdb 
thanks, will have a look later next week, thinking how it can be done only using Grafana, needs to read up.
Best
Peter

**Comment by JeroenVdb** [comment]
@soulgalore I presented the use case to the Grafana users and no real solution as it seems: https://github.com/grafana/grafana/issues/1330

**Comment by soulgalore** [comment]
ok thanks :)  I'm just thinking how to do it the best way, lets sync up in a couple of days.

**Comment by soulgalore** [comment]
Haven't had time yet to think about this, pushing to next minor.

**Comment by soulgalore** [comment]
@JeroenVdb we have a much cleaner setup in 4.0, Thanks for all your input in the past 👍 

Closing too old issues. Lets start with new clean sheet for 4.0.
