### ISSUE TITLE
It's hard to see/understand if the main page(URL) has been redirected

### ISSUE THREAD

**Issue by n3o77** [sitespeedio/sitespeed.io#523]
I have the problem that on many urls I got a redirect to the startpage but all the results are still listed for the initial page which can mislead. So we need either a clear indication that the page was redirected and show the proper URL or we shouldn't display the results on that page and have a link to the redirected page.

I would prefer to have an indicator on the "pages" view that this URL was redirected. List the redirected page separately and have an extra table on the detail page with all urls which were redirected to it. But I can see problems with this solution, we need to consider query strings and header directives which could affect the result. So maybe something like a "grouping" option?

**Comment by soulgalore** [comment]
Pushing this to next minor.

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
