### ISSUE TITLE
Set crawl timeout

### ISSUE THREAD

**Issue by nickcodefresh** [sitespeedio/sitespeed.io#547]
Is is possible to change the crawl time-out? I'm using sitespeed.io to test RESTful end points, and they can be long running

`[31merror[39m: Error from the crawl:The start url: http://xyz/bca/themes?includeAll=True&forDNA=True&status=http://data.emii.com/status/published couldn't be fetched, response code Response timed out`

**Comment by nickcodefresh** [comment]
thanks, I'm just trying it out now

**Comment by soulgalore** [comment]
Hi @nickcodefresh ,
did this work out for you so I can close the issue?

**Comment by nickcodefresh** [comment]
Yep sure did
