### ISSUE TITLE
Overwrite url with parameters

### ISSUE THREAD

**Issue by measureworks** [sitespeedio/sitespeed.io#552]
Hi Peter and Tobias,

When we have for example three urls that have the same "base" url but the others have parameters the baseurl is overwritten by the ones with parameters. Therefore the (base)urls won't give results however they should still be measured and give results/json files.

Kind Regards,
Ingrid

**Comment by soulgalore** [comment]
Hi Ingrid,
yes you are perfectly right, that's a bug in the 3.x version of the naming of the files that are created, will look at it tonight and push a release.

Best
Peter
