### ISSUE TITLE
Checking YSlow rules doesn't work on Windows

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#554]
Argh, it sucks to don't have any automated tests running on Windows.
<pre>
info: Running YSlow for http://www.sitespeed.io
error: Couldn't run YSlow for http://www.sitespeed.io : {"killed":false,"code":1,"signal":null}
info: Done analyzing urls
</pre>

**Comment by soulgalore** [comment]
Getting some more useful info:
<pre>
Error: Error running YSlow: http://www.sitespeed.io ("FAIL to load undefined reason:Connection refused url:http://www.sitespeed.io/\r\n"Error: Command failed: )
Error: Could not analyze http://www.sitespeed.io ("yslow Error: Command failed: FAIL to load undefined reason:Connection refused url:http://www.sitespeed.io/\r\n")
</pre>

Running the same with slimerjs works.

**Comment by Andrew-Yourn** [comment]
i have this issue, windows 7, how do you substitute slimerjs ?

**Comment by tobli** [comment]
In the current version, pass --slimerjs as an extra argument.

**Comment by soulgalore** [comment]
the problem (at least for me) was that the proxy was burned into the Windows setup, so every access tried to use a proxy, but no proxy was setup.
