### ISSUE TITLE
PhantomJS 2 issues in Windows

### ISSUE THREAD

**Issue by thebostik** [sitespeedio/sitespeed.io#558]
Troubleshooting using PhantomJS 2.0.0 (development) in Windows (server 2012) and sitespeed.io 3.0.3. There are 2 main issues -
1) phantomjs not collecting data when use option `--phantomjsPath "path to exe"`
2) phantomjs not collecting navigation timing metrics when using option `-b phantomjs`

I logged the parameters that we try to spawn the phantomjs process with, and enabled phantomjs debug logging. [Here is the debug output](https://gist.github.com/anonymous/a625382fdfd106d54c6f)

Line 53 there is output as an error when running line 24 of yslow-3.1.8-sitespeed.js. `args = phantom.args,`

This is because [phantom.args is deprecated](http://phantomjs.org/api/phantom/property/args.html), and I guess there is no implementation in the current build of phantomjs 2 that I used (posted on the phantomjs mailing list from 12/20/14)?

Fix 1) So requiring system, and then calling system.args works. We implement this swap (system.args instead of phantom.args) in all 3 files in lib/phantomjs.

Fix 2) This has a side-effect though, as args[0] now becomes the filename. This may be Windows specific behavior? So now we need to increment all indexes into args by 1 in lib/phantomjs/collectTimings.js and lib/phantomjs/screenshot.js. Not needed in the yslow.js file since it has a more robust method for finding args.

~~Fix 3) Again, it may be Windows-specific (but I don't face issues when using sitespeed.io 3.0.3 / phantomjs 1.9.8 / chrome) is that I needed to add double-quotes around the user-agent header in defaultConfig.js. When node spawns phantom.exe, it doesn't like if the user-agent isn't quoted and will not work.~~ __Edit:__ This observation was just a symptom prior to the previous fix.

With these ~~3~~ __2__ things fixed, I am able to get yslow data and navigation timing data collected by phantomjs2.

**Comment by soulgalore** [comment]
Hi Stephen,
wow great, thanks!

1) ok, that used to work in the current 2.0 version I'm using, but lets change that then, I'll can do that tomorrow (or if you send a pull and I can test). The yslow-3.1.8-sitespeed.js is built from https://github.com/sitespeedio/yslow just fyi.

2 & 3 I need to check. Think I can have it fixed by the end of the week by the latest (I'm focusing on getting some fixes for WebPageTest finished this week that I've been trying to get finished for some time.

Best
Peter

**Comment by thebostik** [comment]
I just did one further check, and realized what I listed as number 3 above was just a symptom of 2. I reverted that change I made in defaultConfig.js and everything is still working, so strike that out.

I found this - https://github.com/ariya/phantomjs/issues/12527 - to confirm that it looks like phantom.args is gone for good.

**Comment by soulgalore** [comment]
ok cool, I will start fixing a couple of the things tonight, will update the issue then.

**Comment by soulgalore** [comment]
ah I've forgot to comment on this. did the change in YSlow but got some error logs (running YSLow directly) so I will look at that first, aim 2 do it tonight.

**Comment by soulgalore** [comment]
Hi @thebostik ,
do you have the possibility to checkout the master branch and try it out? I've done the changes now and would like to test it before I release it, would be nice to test with the phantomjs version you have.

Best
Peter

**Comment by thebostik** [comment]
Sorry I didn't see this sooner. I did update to 3.0.5 from npm yesterday and it was working without any changes on my side.

**Comment by soulgalore** [comment]
cool! thanks for pointing this out and showing the fix! hopefully phantomjs2 will be released the coming days :)
