### ISSUE TITLE
Create CSV versions of all output files

### ISSUE THREAD

**Issue by kab12** [sitespeedio/sitespeed.io#560]
Hi Peter,

I really miss having the old csv files in the new version. I used to be able to pick these up and post process the data and correlate it with data from other tools. You would make my life a lot easier if you would add this functionality (but now for all files) like it used to be.

Having output in Graphite is great for timeseries analysis but for ad-hoc analysis I still prefer my own stuff :-)

Best regards,
Peter van Gils, Key Performance

**Comment by soulgalore** [comment]
Hey Peter,
sorry for the late answer. So haven't put any time into it, but I guess it would be quite easy, the hard part is keeping it uptodate and working over time, lets see what I can do.

Best
Peter

**Comment by chrisbautista** [comment]
Hi @soulgalore, 

I think you guys are awesome! 

I would like to take this feature on. Let's discuss.

@chrisbautista

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
