### ISSUE TITLE
Yslow output for 'https://xxxxxxxx.com/#/recommended' (stdout): FAIL to load undefined

### ISSUE THREAD

**Issue by FJLopezGarcia** [sitespeedio/sitespeed.io#561]
Hello,
I am receiving the following error "error: Yslow output for 'https://xxxxxxxx.com/#/recommended' (stdout): FAIL to load undefined" running sitespeed.io for a https site:

sitespeed.io.cmd -u https://xxxxxxxxxx.com/#/recommended --screenshot --requestHeaders sitespeed-result\myheaders.txt

The myheaders.txt file contains the JSON with the ADFS cookie nedded to be authenticated (something like that)
{
"Cookie" : "s_getNewRepeat=1421340514712-New; s_vi=[CS]v1|2A5BF7B2051D39CE-6000012B2004DACF[CE]; FedAuth=77u/PD94bWwgdmVyc2lvb...................bj4="
}

Error:
info: OS: win32 6.1.7601 sitespeed:3.0.3  phantomJs:1.9.8 java:java version "1.8.0_25" browsertime:0.8.20
info: Will crawl from start point https://xxxxxxxx.com/#/recommended with crawl depth 1
info: Will analyze 1 pages
info: Running YSlow for https://xxxxxxxx.com/#/recommended
error: Yslow output for 'https://xxxxxxxx.com/#/recommended' (stdout): FAIL to load undefined

error: Error running yslow for url 'https://xxxxxxxx.com/#/recommended': { [Error: Command failed: ] killed: false, code: 1, signal: null }
info: Taking screenshot for https://xxxxxxxx.com/#/recommended
error: Phantomjs output for 'https://xxxxxxxx.com/#/recommended' (stdout): Unable to load the address!

info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file pages.html
info: Wrote file hotlist.html
info: Wrote file screenshots.html
info: Wrote file errors.html
info: Wrote file index.html
info: Wrote file rules.html
info: Wrote file detailed-site-summary.html
info: Wrote results to C:\Users\francisco.j.lopez\sitespeed-result\xxxxxxxx.com\2015-01-18-19-17-06

I have tested with other urls like http://www.google.es and it woks....
Do you know how to fix that problem??

Note: I have verified with fiddler that all the sessions requested are captured properly,

Thanks a lot!!

**Comment by FJLopezGarcia** [comment]
could be that since  'https://xxxxxxxx.com/#/recommended' is placed in DS domain (a development) the Yslow cannot access?

**Comment by soulgalore** [comment]
Hello Javi,
sorry that it took a while to answer. Hmm usually these kind of errors could be one of three things: a frontend redirect (it is not handled today), a bug in our rules or a bug i YSlow. If it is ok, could you share me the URL so I can test? My email: peter [AT] soulgalore [DOT] com

Thanks!
Peter

**Comment by FJLopezGarcia** [comment]
Hi Peter, thanks a lot for your response... unfortunately i cannot share the URL since it is an internal URL and  you need to be in the company network in order to have access... also you need a user/pw to generate the cookie and pass the adfs authentication.

**Comment by FJLopezGarcia** [comment]
Hi Peter, 
I have tested that if i run phantomjs using the YSlow for PhantomJS and passing my ADFS cooke in order to pass the authentication and I am receiving the following error message (Invalid custom headers):

C:\Users\Javi>phantomjs yslow.js -i basic -f plain https://xxxxxxxx.com/#/recommended -ch {"Cookie":"FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLT
giPz48U2VjdXJpdHlDb250ZXh0VG9rZW4gcDE6SWQ9Il8wNTZjZTgzNi03ODc3LTRiMmMtYjA1YS02YmI4NWMyMmU1ZDktODFFRjQ3MzMxMzQzMTk3MjM0REE5QkZCQkJFOUQ5RkYiIHhtbG5zOnAxPSJodHRwOi8vZG9jcy5vYXNpcy1vcGVuLm9yZy93c3MvM
jAwNC8wMS9vYXNpcy0yMDA0MDEtd3NzLXdzc2VjdXJpdHktdXRpbGl0eS0xLjAueHNkIiB4bWxucz0iaHR0cDovL2RvY3Mub2FzaXMtb3Blbi5vcmcvd3Mtc3gvd3Mtc2VjdXJlY29udmVyc2F0aW9uLzIwMDUxMiI+PElkZW50aWZpZXI+dXJuOnV1aWQ6Njkz
NjRjOWQtYmYzZC00YmI0LTg3MmItODMzMTc1YjUyZjBhPC9JZGVudGlmaWVyPjxDb29raWUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwNi8wNS9zZWN1cml0eSI+QVFBQUFOQ01uZDhCRmRFUmpIb0F3RS9DbCtzQkFBQUE0Yi9
nQVUxczQwR2NjVnRrdm5Ed2RnQUFBQUFDQUFBQUFBQURaZ0FBd0FBQUFCQUFBQUJ1MzJldUJwMERGVDYweWFyMC9SVCtBQUFBQUFTQUFBQ2dBQUFBRUFBQUFQWEFNQ0hBa0RQNjRFUmQ0Z2NyVVQ3SUF3QUF0K0NMaHFUMmFqbExuN1pKUUFYajVtQXUwMFNVdy
9qbS9ab3V3Zjk5Sk1oV094YUxXR2xXWklqVlFGQTc5TmIxKzhyWUt1Y0plSmQ5M25hMjBEcEpnb0tEOWxTa0ExOHlUQ0hIZ2dabjJQTkZDblByREU1VG4yajc1QWlMeDBqY1F5SWN4S3laNjFtWnNEaFYycU1SU3ZZUXppZ3lxMHAyMWVMeURTZW9wOXRqVzNQW
G9xcTE2K1FKUmYzcldNZytMWXZYRWlvR2JRNldUZ3E4UC8yTklkaTQkRad0FwV1NScmRzQ0dBYjlXdnFmNWpmVzhPSHAySDhXOWdXT0ppdFZnZFo2c2lhQU9rUHpOaG9vYmpLUHlOeGpsdGNHOVBGK2pKQnNrdDVjT21Q
U3hhYTVydUF1K1dNd3Y1L09zR0ZTYS94ZXptMnV4bEhpck5sbkFIVkxxeEFFZG1JYjc2OUUxR3NoQ2hiTnZJYXl4WG16ZnRhZmNLQ3BqMDFNZTR3Rk5mYjEvWEZGNjlNaHg0VTJJUFlEZVVGQlZhRGtYQ1QwRnp4ODRsVGxCYnpqS29TZkxiaURNNEVpd2VCSFJ
DYTRFbDYyZlg0b25XV1NSVGFEVGZPN1pUR1hHNzMvTUdyZDZaUzZXOFhsSzZHeGV4d3NYRXpBRHQvYTlCMzJqLzdMc2N1T0ZoOFIxaEJET1FXMDJveHJ0TXlvN0IyeE9MVjNGTkpUWlh2TTZvK2F1aGl1NzV1UmRYU3ZJNThobVM4cXJSYUJGbVU1eGRneTVxU2
1PRERHVDY2c1RaZy92Y0x3ZW5vSHpGTkhCcXhQeGIxakk5QTJGQ1BCVjZVVGlDMmFyU2h0R0thbGk5OC9nY1JnY0hZMnM0Wnl5SFgxU0NLUVlpRVJxbkNlSSsrMlhWdGttV05DRnZ2TytPenRtLzl4ZHFsalI4NWZYVXpFdFBZTDkyelRDditZN1IxNExBWmptN
HNXZjBucHkxYTJ0UDZTZjJlek0rWDJHdG9wUU5LWGROdktPNmV4UWVydUI2U3hraEFRcnY3cW9TOHA4UGd1SG5rbkJmNStRZk1oeWNDdWRuYVpkbkRtcnc5WEVPV3duT2ltYzJvTUxrdFB6czAyZVd3a2QyK3dOaTZHdEFZVmFuWnZnTEk0ZzdETlRFZnBxQ3dJ
; FedAuth1=ZSs0K2VpTVJGcGFsMk5Zcmh3dUJ6YXZSaE1Ya2Yxd0ppWFRzbGFHZkRxa2hHMDRyRjd3TXMvQzVBVkMyREZ5cXUwcnVLbUZ5QmNLOHZ2YndVeVVYVTluNDlMR2NkbjdRd29Obmx3akxqV0pTK0dGc3Q4eFR6ZW56Umc5TVd2c2FBQnBmUVRrM21o
WVFYNjQ5QkRTYU44WGQ2TW9iQzhyMW9aYTJKWkl1RkNaY2lNOXhsOTNicXlWa3kxSS9ZQlVrYkdoQjJOTjVDYmRLL05ERVNiL1FWVnJsTmZoOE44UXFINzFGd1BUOXJXQ3lwdDZPdmoxaEtRMTJPcGRCME5GdHU0V3Q1SnRXY085UFg2dGNjTzJIV2JzSXNZSmx
YanAwb1drL3BIaldmZGwza0J2cFY2elQyeDkxZ2tnalZQZUxyWTc0dktIU0JpaUw1bUNSakY0UFNlNEFuVTNWaTl5QVhXejBGRUpkcVdsTmFKbDd3Q3RLeGVHd2VQeHJLYWNZVUFBQUEreDFOODdmbFJ5MkdnNWpDaHNUR0M5STVBbFU9PC9Db29raWU+PC9TZW
N1cml0eUNvbnRleHRUb2tlbj4="}

Invalid custom headers: SyntaxError: Unable to parse JSON string
version: 3.1.8
size: 91.9K (91941 bytes)
overall score: A (93)
url: https://federation.xxxxxxxxxx.com/adfs/ls?wa=wsignin1.0&wtrealm=https%3a%2f%2fxxxxxxxxxxx.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252f&wct=2015-01-20T12%3a09%3a01Z
# of requests: 9
ruleset: ydefault
page load time: 2202

**Comment by soulgalore** [comment]
Hi Javi,
ah thanks that you tested with a plain YSlow, that's perfect. 

I've tested the same on my Mac, when I removed the line breaks within the cookie data, and then it works for me.

Best
Peter

**Comment by FJLopezGarcia** [comment]
Hi Peter, 
I have removed the line brakes and foe me is still not working

this is my cookie:
{"Cookie":"FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U2VjdXJpdHlDb250ZXh0VG9rZW4gcDE6SWQ9Il83MjRmYzQ3OC03MTgxLTRiNmEtYTI0Mi1iYWNjYmZkNzhlMDQtQkRFNENEQUJFREZDNjQyMzc5QjFFQ0RDNEJEQ0I4QTgiIHhtbG5zOnAxPSJodHRwOi8vZG9jcy5vYXNpcy1vcGVuLm9yZy93c3MvMjAwNC8wMS9vYXNpcy0yMDA0MDEtd3NzLXdzc2VjdXJpdHktdXRpbGl0eS0xLjAueHNkIiB4bWxucz0iaHR0cDovL2RvY3Mub2FzaXMtb3Blbi5vcmcvd3Mtc3gvd3Mtc2VjdXJlY29udmVyc2F0aW9uLzIwMDUxMiI+PElkZW50aWZpZXI+dXJuOnV1aWQ6MTBmZjQyM2YtNjQyMy00ZDVjLTkyMzctNjllMjk4NWFkZDE5PC9JZGVudGlmaWVyPjxDb29raWUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwNi8wNS9zZWN1cml0eSI+QVFBQUFOQ01uZDhCRmRFUmpIb0F3RS9DbCtzQkFBQUE0Yi9nQVUxczQwR2NjVnRrdm5Ed2RnQUFBQUFDQUFBQUFBQURaZ0FBd0FBQUFCQUFBQUN2Z3VaTUt2OXNHeFpCODNnZEVZaU9BQUFBQUFTQUFBQ2dBQUFBRUFBQUFFWHRQNVhoTk1FR3NzVERWMzRKYjNuSUF3QUF0ZkgrMmdWa2tNTlpLcy9VMlA4UGIxcURwOVhOSU5SQlpkVGVKSjdEQ3ZsNnBtQnZoMnpSYWkxOGxoYUFYTXhubytya3JLR1BUWHh1Z0Q5VC9NZHo3cWdKYlhua3c2SXlTNzExTXMyUlN5WjJnTjBIWVBvc1JkWjNLRXF5ckdwMGwyeTUydldWcUo1OG45R09NMWxYcWNvUGl0YlYrcitlYWRhM2t1SFJJVjdMN3BRTTNYRVlyUmg4ZVlISHBxWkRmRFp6aXVOOWN2QXc3T2pHdU9YTklORVphdGU5SzhpYXM0ck1aUXMyNWE2YVpzaWs2V0tOOVhSUkNJbXZYbllqdXJaT1h4TzhhTWdpSFpjSlFiSVVWdnl4Z3RkeUFPWFJGN2ZkanNWdTFVVmNqWnV4WitLVFJYd3VFNkJZOVEybUhXS29tMlNIVUsxS1JsSGxwd0JUZjBFTy9lYStlWHgrQzdDS0oyNTF1clZ2UnBlelg5MmQ3bm1TTkgvd2tXSUMvWDdUSTNuOUpVN1RIUFZ5ejZBK21zT1pQUWFxV3oxRVB4VERVczRvelYzeTUvVm93K3Y2OG9OdFNWc09GVUh3dytyY1p3VFZ1RTN6eks1ejNCU2psTzZLZ0wxU0tPUEZod3VIaHVWM2c4WldNYkVZSmhsWFpqeFFCK0lUSXdRd3ExckRJaWM1ZWhvRElPYVlaSTdWNFU1a3BwOFRjSHVMeFUwbWExNWtYejZxTG9WNDJ1bC9URllsUzNxNGM1WUxaRU4wNzBoUiswcE0zS3FCcC9NNm9oZm5kbWQ5SkZFdm9iY0tlVkJrTlRTaE5tNk9wZFoyVXB5SytieWpUTHBGT2Q4akd0N3FnM2MyNmFkZzFzYko3THZ4OURCb05yWVE3dGN5NGxubkRNb3NJSXJsWFo1UDhjUEtYUGdzL0l6S0xqbm56UnZOYUMxUXE3Mmd1MHlYSENpNllXZHdMK1NNYk5SeHVoN0U4K2FHbGhnZHZnSmRSOEhNK3ZFckh0UGErT2IwNklOZFFxMFphTkhYeUNLcUlmY1hGSXZnRVpnMXVGYmErQlNqUTRpakRqYll3dmJUajlzUHJFUXBTbU44djdkQ2Zqbitqb25KRVFRaUlKOW1CY040bENnWWxaNHRGQk5WVlA3UmR6SVQxMW5RNkUwNXk5R05iNWZhUDVScVJVR1FKU3N0YmRU;FedAuth1=YUFMeWU0bFZkWEVPam1MdXRyUHk3ZndRRkdRZDgvVFdLU0RsNDdMTXdsQmdzeGpUd2xWTzNmRjE1SE1qWXh0WmdRNEZEK1JFM0VGdzFua1ZZN2phRXd5OTc0ZGpsaVNoL09EQTExSDh3MWcxdElKd1BwVmR4WUpCaGxMWVRhejRUQ04rcG9yTTIxdXp2VXRwRVF0RnBBTXJobnNUcGJvN0JQTHpQUHFRQjhhMk9UUUtpSWsxZnorSU5hMkVZQTVzWVFwNllHMnBDU1BOTmJmU2hsNGFXQ0tNVDFScXQ0MXB2aWVhNVRxZXl3dnFIYUxCT2V6NTNCUUNwN01Sc0w3aW9kb3pjRlF1QzlJUHRtNmxWSkRWTDFxQWVzdkZ2SlJoMXczU1RkdHBzOFRTd0p6amFEZWxzVThBNlhuOFV3L0c2RFJxbVVtbi96RmZ0cW50WDMzeU41enFtWGpjczlzZkUyUHNUMmlUNWdVYnBGMnhKOUIwb1lqbkhLY1RLYkc4VUFBQUF0Q05kd1BuRXJZL1FHS1JpdVdNaElWQ3RjSDA9PC9Db29raWU+PC9TZWN1cml0eUNvbnRleHRUb2tlbj4="}

**Comment by soulgalore** [comment]
Hi again Javi,
and do you get an error from YSlow (like "SyntaxError: Unable to parse JSON string") or do can't you fake the login?
Best
Peter

**Comment by FJLopezGarcia** [comment]
phantomjs yslow.js -i basic -f plain https://career.ciodev.com/#/recommended -ch '{"Cookie":"FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmL
TgiPz48U2VjdXJpdHlDb250ZXh0VG9rZW4gcDE6SWQ9Il83MjRmYzQ3OC03MTgxLTRiNmEtYTI0Mi1iYWNjYmZkNzhlMDQtQkRFNENEQUJFREZDNjQyMzc5QjFFQ0RDNEJEQ0I4QTgiIHhtbG5zOnAxPSJodHRwOi8vZG9jcy5vYXNpcy1vcGVuLm9yZy93c3Mv
MjAwNC8wMS9vYXNpcy0yMDA0MDEtd3NzLXdzc2VjdXJpdHktdXRpbGl0eS0xLjAueHNkIiB4bWxucz0iaHR0cDovL2RvY3Mub2FzaXMtb3Blbi5vcmcvd3Mtc3gvd3Mtc2VjdXJlY29udmVyc2F0aW9uLzIwMDUxMiI+PElkZW50aWZpZXI+dXJuOnV1aWQ6MTB
mZjQyM2YtNjQyMy00ZDVjLTkyMzctNjllMjk4NWFkZDE5PC9JZGVudGlmaWVyPjxDb29raWUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwNi8wNS9zZWN1cml0eSI+QVFBQUFOQ01uZDhCRmRFUmpIb0F3RS9DbCtzQkFBQUE0Yi
9nQVUxczQwR2NjVnRrdm5Ed2RnQUFBQUFDQUFBQUFBQURaZ0FBd0FBQUFCQUFBQUN2Z3VaTUt2OXNHeFpCODNnZEVZaU9BQUFBQUFTQUFBQ2dBQUFBRUFBQUFFWHRQNVhoTk1FR3NzVERWMzRKYjNuSUF3QUF0ZkgrMmdWa2tNTlpLcy9VMlA4UGIxcURwOVhOS
U5SQlpkVGVKSjdEQ3ZsNnBtQnZoMnpSYWkxOGxoYUFYTXhubytya3JLR1BUWHh1Z0Q5VC9NZHo3cWdKYlhua3c2SXlTNzExTXMyUlN5WjJnTjBIWVBvc1JkWjNLRXF5ckdwMGwyeTUydldWcUo1OG45R09NMWxYcWNvUGl0YlYrcitlYWRhM2t1SFJJVjdMN3BR
TTNYRVlyUmg4ZVlISHBxWkRmRFp6aXVOOWN2QXc3T2pHdU9YTklORVphdGU5SzhpYXM0ck1aUXMyNWE2YVpzaWs2V0tOOVhSUkNJbXZYbllqdXJaT1h4TzhhTWdpSFpjSlFiSVVWdnl4Z3RkeUFPWFJGN2ZkanNWdTFVVmNqWnV4WitLVFJYd3VFNkJZOVEybUh
XS29tMlNIVUsxS1JsSGxwd0JUZjBFTy9lYStlWHgrQzdDS0oyNTF1clZ2UnBlelg5MmQ3bm1TTkgvd2tXSUMvWDdUSTNuOUpVN1RIUFZ5ejZBK21zT1pQUWFxV3oxRVB4VERVczRvelYzeTUvVm93K3Y2OG9OdFNWc09GVUh3dytyY1p3VFZ1RTN6eks1ejNCU2
psTzZLZ0wxU0tPUEZod3VIaHVWM2c4WldNYkVZSmhsWFpqeFFCK0lUSXdRd3ExckRJaWM1ZWhvRElPYVlaSTdWNFU1a3BwOFRjSHVMeFUwbWExNWtYejZxTG9WNDJ1bC9URllsUzNxNGM1WUxaRU4wNzBoUiswcE0zS3FCcC9NNm9oZm5kbWQ5SkZFdm9iY0tlV
kJrTlRTaE5tNk9wZFoyVXB5SytieWpUTHBGT2Q4akd0N3FnM2MyNmFkZzFzYko3THZ4OURCb05yWVE3dGN5NGxubkRNb3NJSXJsWFo1UDhjUEtYUGdzL0l6S0xqbm56UnZOYUMxUXE3Mmd1MHlYSENpNllXZHdMK1NNYk5SeHVoN0U4K2FHbGhnZHZnSmRSOEhN
K3ZFckh0UGErT2IwNklOZFFxMFphTkhYeUNLcUlmY1hGSXZnRVpnMXVGYmErQlNqUTRpakRqYll3dmJUajlzUHJFUXBTbU44djdkQ2Zqbitqb25KRVFRaUlKOW1CY040bENnWWxaNHRGQk5WVlA3UmR6SVQxMW5RNkUwNXk5R05iNWZhUDVScVJVR1FKU3N0YmR
U;FedAuth1=YUFMeWU0bFZkWEVPam1MdXRyUHk3ZndRRkdRZDgvVFdLU0RsNDdMTXdsQmdzeGpUd2xWTzNmRjE1SE1qWXh0WmdRNEZEK1JFM0VGdzFua1ZZN2phRXd5OTc0ZGpsaVNoL09EQTExSDh3MWcxdElKd1BwVmR4WUpCaGxMWVRhejRUQ04rcG9yTTIx
dXp2VXRwRVF0RnBBTXJobnNUcGJvN0JQTHpQUHFRQjhhMk9UUUtpSWsxZnorSU5hMkVZQTVzWVFwNllHMnBDU1BOTmJmU2hsNGFXQ0tNVDFScXQ0MXB2aWVhNVRxZXl3dnFIYUxCT2V6NTNCUUNwN01Sc0w3aW9kb3pjRlF1QzlJUHRtNmxWSkRWTDFxQWVzdkZ
2SlJoMXczU1RkdHBzOFRTd0p6amFEZWxzVThBNlhuOFV3L0c2RFJxbVVtbi96RmZ0cW50WDMzeU41enFtWGpjczlzZkUyUHNUMmlUNWdVYnBGMnhKOUIwb1lqbkhLY1RLYkc4VUFBQUF0Q05kd1BuRXJZL1FHS1JpdVdNaElWQ3RjSDA9PC9Db29raWU+PC9TZW
N1cml0eUNvbnRleHRUb2tlbj4="}'
Invalid custom headers: SyntaxError: Unable to parse JSON string
version: 3.1.8
size: 91.9K (91941 bytes)
overall score: A (93)
url: https://federation-sts-stage.com/adfs/ls?wa=wsignin1.0&wtrealm=https%3a%2f%2fcareer.ciodev.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252f&wct=2015-01-20T22%3a16%3
a01Z
# of requests: 9
ruleset: ydefault
page load time: 4015

**Comment by soulgalore** [comment]
Guess it could be a Windows issue, I can try it tomorrow. This is what I get:
<pre>
 phantomjs build/phantomjs/yslow.js -i basic -f plain http://my.url -ch '{"Cookie":"FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U2VjdXJpdHlDb250ZXh0VG9rZW4gcDE6SWQ9Il8wNTZjZTgzNi03ODc3LTRiMmMtYjA1YS02YmI4NWMyMmU1ZDktODFFRjQ3MzMxMzQzMTk3MjM0REE5QkZCQkJFOUQ5RkYiIHhtbG5zOnAxPSJodHRwOi8vZG9jcy5vYXNpcy1vcGVuLm9yZy93c3MvMjAwNC8wMS9vYXNpcy0yMDA0MDEtd3NzLXdzc2VjdXJpdHktdXRpbGl0eS0xLjAueHNkIiB4bWxucz0iaHR0cDovL2RvY3Mub2FzaXMtb3Blbi5vcmcvd3Mtc3gvd3Mtc2VjdXJlY29udmVyc2F0aW9uLzIwMDUxMiI+PElkZW50aWZpZXI+dXJuOnV1aWQ6NjkzNjRjOWQtYmYzZC00YmI0LTg3MmItODMzMTc1YjUyZjBhPC9JZGVudGlmaWVyPjxDb29raWUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwNi8wNS9zZWN1cml0eSI+QVFBQUFOQ01uZDhCRmRFUmpIb0F3RS9DbCtzQkFBQUE0Yi9nQVUxczQwR2NjVnRrdm5Ed2RnQUFBQUFDQUFBQUFBQURaZ0FBd0FBQUFCQUFBQUJ1MzJldUJwMERGVDYweWFyMC9SVCtBQUFBQUFTQUFBQ2dBQUFBRUFBQUFQWEFNQ0hBa0RQNjRFUmQ0Z2NyVVQ3SUF3QUF0K0NMaHFUMmFqbExuN1pKUUFYajVtQXUwMFNVdy9qbS9ab3V3Zjk5Sk1oV094YUxXR2xXWklqVlFGQTc5TmIxKzhyWUt1Y0plSmQ5M25hMjBEcEpnb0tEOWxTa0ExOHlUQ0hIZ2dabjJQTkZDblByREU1VG4yajc1QWlMeDBqY1F5SWN4S3laNjFtWnNEaFYycU1SU3ZZUXppZ3lxMHAyMWVMeURTZW9wOXRqVzNQWG9xcTE2K1FKUmYzcldNZytMWXZYRWlvR2JRNldUZ3E4UC8yTklkaTQkRad0FwV1NScmRzQ0dBYjlXdnFmNWpmVzhPSHAySDhXOWdXT0ppdFZnZFo2c2lhQU9rUHpOaG9vYmpLUHlOeGpsdGNHOVBGK2pKQnNrdDVjT21QU3hhYTVydUF1K1dNd3Y1L09zR0ZTYS94ZXptMnV4bEhpck5sbkFIVkxxeEFFZG1JYjc2OUUxR3NoQ2hiTnZJYXl4WG16ZnRhZmNLQ3BqMDFNZTR3Rk5mYjEvWEZGNjlNaHg0VTJJUFlEZVVGQlZhRGtYQ1QwRnp4ODRsVGxCYnpqS29TZkxiaURNNEVpd2VCSFJDYTRFbDYyZlg0b25XV1NSVGFEVGZPN1pUR1hHNzMvTUdyZDZaUzZXOFhsSzZHeGV4d3NYRXpBRHQvYTlCMzJqLzdMc2N1T0ZoOFIxaEJET1FXMDJveHJ0TXlvN0IyeE9MVjNGTkpUWlh2TTZvK2F1aGl1NzV1UmRYU3ZJNThobVM4cXJSYUJGbVU1eGRneTVxU21PRERHVDY2c1RaZy92Y0x3ZW5vSHpGTkhCcXhQeGIxakk5QTJGQ1BCVjZVVGlDMmFyU2h0R0thbGk5OC9nY1JnY0hZMnM0Wnl5SFgxU0NLUVlpRVJxbkNlSSsrMlhWdGttV05DRnZ2TytPenRtLzl4ZHFsalI4NWZYVXpFdFBZTDkyelRDditZN1IxNExBWmptNHNXZjBucHkxYTJ0UDZTZjJlek0rWDJHdG9wUU5LWGROdktPNmV4UWVydUI2U3hraEFRcnY3cW9TOHA4UGd1SG5rbkJmNStRZk1oeWNDdWRuYVpkbkRtcnc5WEVPV3duT2ltYzJvTUxrdFB6czAyZVd3a2QyK3dOaTZHdEFZVmFuWnZnTEk0ZzdETlRFZnBxQ3dJ;FedAuth1=ZSs0K2VpTVJGcGFsMk5Zcmh3dUJ6YXZSaE1Ya2Yxd0ppWFRzbGFHZkRxa2hHMDRyRjd3TXMvQzVBVkMyREZ5cXUwcnVLbUZ5QmNLOHZ2YndVeVVYVTluNDlMR2NkbjdRd29Obmx3akxqV0pTK0dGc3Q4eFR6ZW56Umc5TVd2c2FBQnBmUVRrM21oWVFYNjQ5QkRTYU44WGQ2TW9iQzhyMW9aYTJKWkl1RkNaY2lNOXhsOTNicXlWa3kxSS9ZQlVrYkdoQjJOTjVDYmRLL05ERVNiL1FWVnJsTmZoOE44UXFINzFGd1BUOXJXQ3lwdDZPdmoxaEtRMTJPcGRCME5GdHU0V3Q1SnRXY085UFg2dGNjTzJIV2JzSXNZSmxYanAwb1drL3BIaldmZGwza0J2cFY2elQyeDkxZ2tnalZQZUxyWTc0dktIU0JpaUw1bUNSakY0UFNlNEFuVTNWaTl5QVhXejBGRUpkcVdsTmFKbDd3Q3RLeGVHd2VQeHJLYWNZVUFBQUEreDFOODdmbFJ5MkdnNWpDaHNUR0M5STVBbFU9PC9Db29raWU+PC9TZWN1cml0eUNvbnRleHRUb2tlbj4="}'
version: 3.1.8
size: 135.0K (135016 bytes)
overall score: A (95)
url: http://www.sitespeed.io/
# of requests: 7
ruleset: ydefault
page load time: 650
</pre>

**Comment by FJLopezGarcia** [comment]
Thanks a lot Peter, i will wait for your further investigation :-)

**Comment by FJLopezGarcia** [comment]
Hi Peter, 
It seems that the cookie is added to the session’s header properly... the problem is that some sessions are aborted by the client or the Server (checked with fiddler),

Do you know any possible reason?

Regards
Javi

**Comment by soulgalore** [comment]
Hi @FJLopezGarcia ,
I forgot about of this, sorry. No not sure. Is this still an issue for you?

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
