### ISSUE TITLE
A link error in help command

### ISSUE THREAD

**Issue by pydubreucq** [sitespeedio/sitespeed.io#564]
Hi,
I've just seen a link error to the command help
sitespeed.io -h
   --budget <FILE>                                        A file containing the web perf budget rules. See http://www.sitespeed.io/documentation/#budget
The link should be :
http://www.sitespeed.io/documentation/#perfBudget
It is a detail of course ;)
Best Regards
Bye

**Comment by soulgalore** [comment]
Hi @pydubreucq 
ah thanks, I'll fix the link in the docs.

Best
Peter
