### ISSUE TITLE
custom columns return values 0

### ISSUE THREAD

**Issue by zoeoros** [sitespeedio/sitespeed.io#572]
Hi all,
when I use --columns <colums> option, the results for this column is 0.
Example:
$ sitespeed.io.cmd -u http://www.google.es --boxes jsPerPage --columns jsPerPage

info: [sitespeed] OS: win32 6.1.7601 sitespeed:3.0.5  phantomJs:1.9.8 java:java version "1.7.0_67" browsertime:0.8.20

Thanks a lot!

![results](https://cloud.githubusercontent.com/assets/10850065/6059790/fb915ab8-ad35-11e4-9f12-903848005f41.jpg)

**Comment by soulgalore** [comment]
Hi @zoeoros ,
yep you are perfectly right, there is something that seems wrong (and I also see that we are missing some documentation), I'll look at this asap (today).

Thanks for reporting!
Best
Peter

**Comment by soulgalore** [comment]
So the naming of the columns is a little bit complicated. I will add documentation during the day. To get the correct number of javascripts, use: 
<code>--columns yslow.assets.js</code>

I will update the documentation today and then I think we need to simplify the naming in the long run.

Thanks again!
Peter

**Comment by zoeoros** [comment]
Now, it´s works!

Thanks

**Comment by soulgalore** [comment]
fyi added a little more info in the docs:
http://www.sitespeed.io/documentation/#config-columns
