### ISSUE TITLE
The score value show the same value with or without --skipTest option

### ISSUE THREAD

**Issue by zoeoros** [sitespeedio/sitespeed.io#573]
Hi,
if you want to skip a test or rule, the result page should not show info about this test or rule, do not?

The output result web page of this command is the same:
$ sitespeed.io.cmd -u http://www.google.es --boxes jsPerPage,cssPerPage --columns yslow.assets.js,yslow.assets.css

$ sitespeed.io.cmd -u http://www.google.es --boxes jsPerPage,cssPerPage --columns yslow.assets.js,yslow.assets.css --skipTest cssnumreq

How can I do to skip rules and therefore the score value?

Thanks a lot!

**Comment by soulgalore** [comment]
Hey @zoeoros ,
ah sorry I guess the documentation is unclear. The <code>skipTest</code> is only working for JUnit/Tap/performance budgets.

If you want to skip rules you need to create your own YSlow rules files, you can checkout the current one used here: https://github.com/sitespeedio/yslow/blob/master/src/common/rulesets/ruleset_sitespeed.js

At the end of the file, you setup which rules that will be used in a ruleset. The you need to compile it for phantomjs, you can checkout the docs http://www.sitespeed.io/documentation/#addrule

Then feed sitespeed.io with the new rules as described in the docs.

Hope that helps!
Peter

**Comment by zoeoros** [comment]
ok, perfect.

Many thanks!
