### ISSUE TITLE
Error when overwrite previous results dir

### ISSUE THREAD

**Issue by mdaguete** [sitespeedio/sitespeed.io#574]
Hello,

When I try to overwrite the previous results dir the following error appears:

    { [Error: EEXIST, mkdir '/jenkins/workspace/speed/results/www.xxxxxx.com/current/data/yslow']

Version is 3.1.0

Thanks. Regards.

**Comment by soulgalore** [comment]
Hi @mdaguete ,
you run it in Jenkins right? Checked the docs we have at http://www.sitespeed.io/documentation/#jenkins and I think I've done it wrong, it's better to put the data per run in a build number dir (using $BUILD_NUMBER). I will setup Jenkins tomorrow and update the docs. Will ping this issue then.

Best
Peter

**Comment by soulgalore** [comment]
Hello again @mdaguete 
change where the result will end up. In Jenkins this is the current build dir: <code>--resultBaseDir ${WORKSPACE}/${BUILD_NUMBER}</code> 

Best
Peter

**Comment by mdaguete** [comment]
Helo @soulgalore,

Due some other issues not related to sitespeed I need to overwrite de current folder in all builds, but I can change that ....


Thanks. Regards.
