### ISSUE TITLE
Show perf budget stats

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#576]
The HTML reports should contain perf budget info (thanks @stefanjudis !).

Add an extra tab when budget is configured.

**Comment by soulgalore** [comment]
So now it's left to make the output much more readable. Lets do as @tobli suggested:

<pre>
Failed rules:
Js weight - budget 18kB
* www.foo.bar (22kB)
* www.example.com (37kB)
</pre>
or something like that.

**Comment by stefanjudis** [comment]
:+1: Great! Thanks, folks.

**Comment by soulgalore** [comment]
this is ok now, lets release it asap

**Comment by tobli** [comment]
👍
