### ISSUE TITLE
Page and assets size

### ISSUE THREAD

**Issue by zoeoros** [sitespeedio/sitespeed.io#577]
Hi all,
I would like to know how can I do to see the compressed/Gzip size of assets and total page.

Many thanks

**Comment by soulgalore** [comment]
Hi @zoeoros ,
no not today. There's a problem both for PhantomJS (#54) and SlimerJS to get correct compressed size. Using SlimerJS (<code>--headless slimerjs</code>) will get correct size but not for compressed text content though.

Best
Peter

**Comment by zoeoros** [comment]
Hi @soulgalore ,
I see that the har file generated by sitespeed.io (through BrowserMobProxy) shows correct compressed size of elements. Why not use this information to render the final report?

Many thanks

**Comment by soulgalore** [comment]
Hi @zoeoros ,
yes been thinking about it but haven't implemented anything, and I haven't checked that it is actually right. Thanks for checking!

We have an idea of making the dependency on YSlow not so tight and then it's easier to use values form other tools. I'll discuss with @tobli and see how we can do it.

Best
Peter

**Comment by soulgalore** [comment]
Hi @zoeoros ,
yep I'm pretty tired of this and will have a look next week and see if I can fix it. When you checked the values form BrowserMobProxy did you check everything or should I start just validating?

Best
Peter

**Comment by soulgalore** [comment]
released now in 3.2.1

**Comment by zoeoros** [comment]
Hi @soulgalore ,
the values from BrowserMobProxy are pretty similars from YSlow plugin for FF (Firefox).
I checked a page and the values were:
BrowserMobProxy:   15,8 Kb (js) 33,8 Kb (css) 1,0 Kb (html)
YSlow plugin for FF: 16,2 Kb(js) 34,6 Kb (css)  1,1 Kb (html)

By the way I just try last version of sitespeed (3.2.2) and I get same results from older version.
The har file generated is ok but sitespeed report show me uncompressed sizes.

Thanks a lot

**Comment by soulgalore** [comment]
hmm strange I will test again tonight, when I checked this weekend the numbers showed correctly. which site are you testing so I can test? 

best
Peter

**Comment by soulgalore** [comment]
the url:s are matched between the YSlow data and the HAR so I think there could be something that's wrong there so if I get the URLs you test I can solve it :)
