### ISSUE TITLE
Simplify testing multiple urls when testing a site

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#579]
Today it works like this (from the docs):

I create one file containing the urls for each site that I want to test. Testing amazon.com I create file named apple.txt with the URL:s I want to test:

<pre>http://www.apple.com/
http://www.apple.com/iphone/
http://www.apple.com/iphone-6/</pre>
and I compare it to Sony Mobile. I create a new text file named sony.txt with the following content:
<pre>http://www.sonymobile.com/se/
http://www.sonymobile.com/se/products/phones/
http://www.sonymobile.com/se/products/phones/xperia-z3-compact/</pre>
And then I create a master file linking in the other two files:
<pre>apple.txt
sony.txt</pre>
Run the test
Then I run it like this:
<pre>sitespeed.io --sites master.txt</pre>

We should make it easier so we only have one file containing all links. Then if we supply a crawl depth, each url will be crawled, else it will be as is. Or something like that. Ping @tobli , what do you think?

**Comment by tobli** [comment]
An alternate take on sites could be this:
Given sites a.com, b.com and c.com with selected urls listed in files a.txt, b.txt and c.txt respectively.

To crawl and compare a and b:
`$ sitespeed.io -u http://a.com -u http://b.com -d 3`
or using a list of urls:
`$ sitespeed.io -f a.txt -f b.txt`

This expands easily to multiple sites, such as:
`$ sitespeed.io -f a.txt -f b.txt -f c.txt`

This would be likely need a tweak to how site comparisons are named (likely involving --outputFolderName).

An additional use for allowing -u and -f to be repeated would be keep track of subsections of a site. E.g. the product section in foo-product-urls.txt and foo-support-urls.txt. These could be tested individually, but combined to test the whole site using something like this:
`$ sitespeed.io -f foo-product-urls.txt -f foo-support-urls.txt --concat`

With minor, and hopefully backwards compatible, we could remove the need to create a separate text file for each combination of sites.

**Comment by soulgalore** [comment]
yep sounds like a good idea. lets discuss it today, want to make this as easy as possible when running in Docker.

**Comment by JeroenVdb** [comment]
Maybe semi related: select Graphite namespace per url: https://github.com/sitespeedio/sitespeed.io/issues/517

**Comment by soulgalore** [comment]
yes, lets see how we can solve the namespace issues. yep, we have one image up and running (https://registry.hub.docker.com/u/sitespeedio/sitespeed.io-docker/) with both chrome & firefox so it is quite fat right now.

**Comment by soulgalore** [comment]
@tobli started with this today, think the easiest and cleanest is like this:
<code>$ sitespeed.io --sites a.txt --sites b.txt --sites c.txt</code>

then we keep the change to only when testing sites.

**Comment by tay1orjones** [comment]
Today I've been attempting to get this to work. I've been running the docker container with a param of `--sites prodURLS.txt`. There's 4 urls, each on a new line, within the text file. Each time I execute this with a default crawl depth of 1, it only crawls through the first url. At the end it logs `Finished with site http://www.site1.com/,http://www.site2.com/,http://www.site3.com/,http://www.site4.com/`

Not sure If I'm just missing something simple, or if maybe the docker container doesn't fully support the `--sites` config param?

**Comment by lyneld** [comment]
@tay1orjones That's strange...running the `--sites` param worked fine for me through docker. Although I only tried it with a crawl depth of 0. I'll try it with 1 and let you know if it works for me. Could it possibly have something to do with the site itself?

**Comment by tay1orjones** [comment]
@lyneld Yeah - it's definitely strange. Depth of 0 works just fine for me too - I only encounter the issue when I do a depth of 1 or greater. The first site it analyzes just fine - it just won't do the others. Probably not an issue with the sites, they're all up. I'd be interested to know if you can reproduce it.

**Comment by lyneld** [comment]
@tay1orjones I was able to reproduce it, but figured out what the problem is. I think different domains need to be in separate "site" files. Try running it with `--sites site1.txt --sites site2.txt --sites site3.txt --sites site4.txt` - in your case, it would be one URL per file. That worked for me.

**Comment by tay1orjones** [comment]
@lyneld Interesting. I'll try out the multiple txt files tomorrow. Since you were able to reproduce the issue, I think the `--sites` param isn't following what the documentation describes should happen. In the documentation on the configuration page under "Analyze sites and benchmark" it outlines that one txt file with multiple URLs on different domains should work when crawled. I'm going to confirm tomorrow if the `--sites` param behaves as described when installed via npm and ran locally. That should isolate if it's just an issue with the docker container. I might move this to it's own separate issue thread tomorrow. Multiple txt files for now it seems though. Thanks for your assistance!

**Comment by soulgalore** [comment]
Hi @tay1orjones , so I think there's some old documentation somewhere describing the old behaviour. Do you remember where? Else I will check tonight and update.

**Comment by tay1orjones** [comment]
@soulgalore Cool, Thanks! In the documentation on the configuration page under "Analyze sites and benchmark" it outlines that one txt file with multiple URLs on different domains should work when crawled. Although it appears that now the `--sites` param requires URLs to be separated into files via domains. The example text file has: "http://www.yoursite.com/path/
http://www.mycompetition.com/
http://www.mycompetition2.com/"
shown in one file.

**Comment by lyneld** [comment]
@tay1orjones did you manage to get it working with different domains in separate files?

**Comment by tay1orjones** [comment]
@lyneld Yep! Multiple files with separate domains in each file seems to be working. Thanks Again. :+1:

**Comment by lyneld** [comment]
@tay1orjones Awesome!

@soulgalore quick question - sorry, I didn't want to create a new issue for this. But in any of the pages / URL's, is there a way to replace the IP to which any particular domain resolves to? Very similar to the `setDNSName` option that wpt provides? [https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDNSName](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDNSName)

**Comment by soulgalore** [comment]
hey @lyneld 
no not today, add a new issue so we can keep track of it (it will be some changes to implement it).

Best
Peter

**Comment by lyneld** [comment]
@soulgalore thanks for the quick response! I'll go ahead and do that. thanks!

**Comment by soulgalore** [comment]
closing this now since it was released a while ago
