### ISSUE TITLE
Waterfall .png filenames incorrect

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#581]
Using Sitespeed 3.1 to fetch data from Webpagetest Private Instance (2.16) via Webpagetest API wrapper (https://github.com/marcelduran/webpagetest-api),

The .png waterfall filenames in the HTML reports generated by Sitespeed are incorrect. 

Waterfall files are saved correctly in: /data/webpagetest , but HTML reports doesn't load the images.

.png files are saved by Sitespeed like this : 

http://www.website.tld/page.html-{locationname}-{connectiontype}-waterfall.png

Sitespeed HTML report wants to load .png files like this:

http://www.website.tld/page.html-{locationname}-{browser}-{connectiontype}-waterfall.png

I tried to specify location, browser and connectiontype in custom JSON file, but filenames are still the same (with or without customization in JSON file).

**Comment by Vandrix** [comment]
This is also for Download HAR

**Comment by soulgalore** [comment]
thanks @Vandrix for the report, I'll look at this first thing tomorrow and do a fix release.

Best
Peter

**Comment by soulgalore** [comment]
hey @Vandrix ,
could you show me how you run so I can reproduce? I tested with 3.1.4 and the paths are right for me:

<code>bin/sitespeed.js -u http://www.sitespeed.io -d 0 --noYslow --wptKey MY_SECRET_KEY --wptHost www.webpagetest.org</code>

best
Peter

**Comment by Vandrix** [comment]
Hi @soulgalore , I run with:

xvfb-run --server-args="-screen 0 1920x1080x24" sitespeed.io -f <filename> -r <domain> -b chrome --viewPort 1920x1080 --screenshot --gpsiKey <key> --wptConfig <jsonfile> --wptHost <private instance> --wptKey <apikey>

JSON file:

{
  "server": "<private>",
  "location": "Local-WPTDriver",
  "browser": "chrome",
  "connectivity": "Cable",
  "timeout": "600",
  "runs": "3",
  "firstViewOnly": "true"
}

Thnx!

**Comment by soulgalore** [comment]
thanks @Vandrix , I'll try it first thing tomorrow.

Best
Peter

**Comment by soulgalore** [comment]
Hey @Vandrix ,
ah now I see, was tired yesterday. I'm using the the https://github.com/marcelduran/webpagetest-api#user-content-test-works-for-runtest-method-only method in the background and as I understand the *location* configuration contains of both browser and location. In your case, it then should be like this:

<pre>
{
"server": "private",
"location": "Local-WPTDriver:Chrome",
"connectivity": "Cable",
"timeout": "600",
"runs": "3",
"firstViewOnly": "true"
}
</pre>

Could you please test that it works for you? I'll add a check that we verify that the location is of the format of PLACE:BROWSER and will log if we have a problem.

Best
Peter

**Comment by Vandrix** [comment]
Hi @soulgalore,
Works like a charm!
Thnx!

**Comment by soulgalore** [comment]
great!
