### ISSUE TITLE
Error installing in Ubuntu 14.04.1

### ISSUE THREAD

**Issue by davidverdejologitravel** [sitespeedio/sitespeed.io#583]
OS Version:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

Nodejs installation:
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs

Sitespeed installation:
sudo npm install -g sitespeed.io

During the installation appears the following message:
npm ERR! Error: Command failed: Cloning into bare repository '/home/david/.npm/_git-remotes/git-github-com-joshuafcole-async-node-events-git-66c4fa5b'...
npm ERR! fatal: read error: Connection reset by peer

And the installation finishes with the following message:
npm ERR! Error: Command failed: Cloning into bare repository '/home/david/.npm/_git-remotes/git-github-com-joshuafcole-async-node-events-git-66c4fa5b'...
npm ERR! fatal: read error: Connection reset by peer
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "sitespeed.io"
npm ERR! cwd /home/david
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

**Comment by soulgalore** [comment]
hey @davidverdejologitravel ,
thanks for the report! I've tested on my 14.04 and it worked (having npm version 1.3.10). Does git clone work for you (just checking) or could it be a temporary Github thingy?

Best
Peter

**Comment by davidverdejologitravel** [comment]
It isn't a temporary error. I tried to reinstall from scratch two times 
and I have still received the same error.

$ node --version
v0.10.36
$ npm --version
1.4.28
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

Regards,

**Comment by davidverdejologitravel** [comment]
I have just made a downgrade to npm 1.3.10 and I still have the same error:

npm ERR! Error: Command failed: Cloning into bare repository 
'/home/david/.npm/_git-remotes/git-github-com-joshuafcole-async-node-events-git-66c4fa5b'...
npm ERR! fatal: read error: Connection reset by peer
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "sitespeed.io"
npm ERR! cwd /home/david
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.10
npm ERR! code 128

**Comment by soulgalore** [comment]
and it works just using git and clone? 

did it differ in any other way on how we do the installation for our Vagrant Ubuntu? 
https://github.com/sitespeedio/sitespeed.io-vagrant/blob/master/sitespeed-ubuntu14/setup.sh

best
Peter

**Comment by davidverdejologitravel** [comment]
Hi,

I followed this guide the first time. After that I changed the following 
block:

  # Get node and npm
   apt-get install -y nodejs npm

   # Setup node (is there a better way to do this?)
   ln -s /usr/bin/nodejs /usr/local/bin/node

For this one (to get the last nodejs version):

curl -sL https://deb.nodesource.com/setup | sudo bash -
apt-get install -y nodejs

I have just tried in a Debian 7 and I have the same error:

root@sp01:~# npm install -g sitespeed.io

 > slimerjs@0.9.2 install 
/usr/lib/node_modules/sitespeed.io/node_modules/slimerjs
 > node install.js

Downloading 
http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-linux-x86_64.tar.bz2
Saving to 
/usr/lib/node_modules/sitespeed.io/node_modules/slimerjs/slimerjs/slimerjs-0.9.2-linux-x86_64.tar.bz2
Receiving...
Received 782K...
Received 1564K...
Received 2347K...
Received 3131K...
Received 3912K...
Received 4694K...
Received 5476K...
Received 6259K...
Received 7041K...
Received 7822K...
Received 8604K...
Received 9385K...
Received 10171K...
Received 10957K...
Received 11738K...
Received 12520K...
Received 13301K...
Received 14083K...
Received 14864K...
Received 15646K...
Received 16429K...
Received 17210K...
Received 17993K...
Received 18774K...
Received 19557K...
Received 20346K...
Received 21127K...
Received 21909K...
Received 22691K...
Received 23474K...
Received 24256K...
Received 25037K...
Received 25819K...
Received 26602K...
Received 27384K...
Received 27554K total.
Extracting tar contents (via spawned process)
Copying extracted folder 
/usr/lib/node_modules/sitespeed.io/node_modules/slimerjs/slimerjs/slimerjs-0.9.2-linux-x86_64.tar.bz2-extract-1424427147362/slimerjs-0.9.2 
-> /usr/lib/node_modules/sitespeed.io/node_modules/slimerjs/lib/slimer
Writing location.js file
Done. Slimerjs binary available at 
/usr/lib/node_modules/sitespeed.io/node_modules/slimerjs/lib/slimer/slimerjs
npm ERR! git clone git://github.com/joshuafcole/async-node-events.git 
Cloning into bare repository 
'/root/.npm/_git-remotes/git-github-com-joshuafcole-async-node-events-git-66c4fa5b'...
npm ERR! git clone git://github.com/joshuafcole/async-node-events.git
npm ERR! git clone git://github.com/joshuafcole/async-node-events.git 
fatal: read error: Connection reset by peer

 > phantomjs@1.9.15 install 
/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs
 > node install.js

Downloading 
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to 
/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
   [========================================] 100% 0.0s

Received 12854K total.
Extracting tar contents (via spawned process)
Removing 
/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom
Copying extracted folder 
/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1424427333200/phantomjs-1.9.8-linux-x86_64 
-> /usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at 
/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm ERR! Error: Command failed: fatal: read error: Connection reset by peer
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" 
"sitespeed.io"
npm ERR! cwd /root
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

**Comment by davidverdejologitravel** [comment]
Hi,

I have just tried through a proxy and I receive the same error.

Regards,

**Comment by davidverdejologitravel** [comment]
Sorry, I have just finally found that we have a network block in github.

A lot of thanks for your assistance

**Comment by soulgalore** [comment]
Aha nice! So we only have that dependency (to github) so me and @tobli discussed today that we will fix it in the future. Do you need it or could you fix the block?

Best
Peter

**Comment by soulgalore** [comment]
closing this now and adding other issue later in Browsertime to get rid of the dependancy.

**Comment by davidverdejologitravel** [comment]
Hi,

The reason of the block was that our hoster's firewall blocks port 22 
and then I couldn't clone git project. I use a proxy and then everything 
is ok.

A lot of thanks for your assistance.
