### ISSUE TITLE
Not able to Perform tests on multiple browsers with -b or -browser options.

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#586]
I am performing tests withe below options 

sitespeed.io -u http://www1.macys.com/shop/product/mac-lipstick-0.1-oz?ID=106363 -d 0 -b chrome,firefox

Facing below error 

info: Starting proxy on port 2001, will wait at most 15000 ms
error: 

Any help is appreciated.

![screen shot 2015-02-19 at 1 46 45 pm](https://cloud.githubusercontent.com/assets/1479179/6276776/06bf3050-b83e-11e4-9797-c1dfd31619ed.png)

**Comment by soulgalore** [comment]
hey @badrinathvm ,
ah I need to add this in the docs. The proxy we are using needs java 1.7, so you need to upgrade from 1.6.0_65.  Sorry that isn't clear in the docs!
Best
Peter

**Comment by badrinathvm** [comment]
I am performing tests on mac , updated Java JDK &JRE versions , Worked perfectly for FireFox. But failed for Chrome. Do i need an Chrome driver for mac ? once downloaded where should i place chrome driver ?

**Comment by badrinathvm** [comment]
I downloaded chrome driver and configured the path , working as expected. Thanks a ton .

**Comment by badrinathvm** [comment]
we can close this issue. Thanks for amazing quick responses. Appreciate it

**Comment by soulgalore** [comment]
hmm, the Chromedriver should have been installed automatically though, I need to check that.

best
Peter
