### ISSUE TITLE
Unable to Perform Web Page Test with Valid API Key 

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#588]
I m using below command to test page to test web page.

sitespeed.io -u http://www1.qa16codemacys.fds.com/shop/product/mac-lipstick-0.1-oz?ID=106363 --wptHost www.webpagetest.org —wptKey   XXX -d 0 -n 1

Facing below error 

error: WebPageTest couldn't fetch info for url http://www1.qa16codemacys.fds.com/shop/product/mac-lipstick-0.1-oz?ID=106363{ statusCode: 400,
  statusText: 'An error occurred processing your request (missing API key).  If you do not have an API key assigned you can request one at http://www.webpagetest.org/getkey.php' }
error: Error running WebPageTest: { statusCode: 400,
  statusText: 'An error occurred processing your request (missing API key).  If you do not have an API key assigned you can request one at http://www.webpagetest.org/getkey.php' }

Any hep will be appreciated.

![screen shot 2015-02-20 at 11 04 40 am](https://cloud.githubusercontent.com/assets/1479179/6307416/6339b488-b8f0-11e4-9a86-0fef330a3f95.png)

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
first, treat your key as private (I've changed that part now). In your example you have —wptKey instead of --wptKey (two minus signs). 

Also seen that there was a bug introduced in your version for the default location ofthe WPT test, upgrade to v3.1.6 of sitespeed and that is fixed!

Best
Peter

**Comment by badrinathvm** [comment]
How can i update sute speed to v3.1.6 ? 

Need to install npm install sitespeed.io again to replace with latest update ?

**Comment by soulgalore** [comment]
yes!

**Comment by badrinathvm** [comment]
Updated , but facing below issue 
![screen shot 2015-02-20 at 12 47 24 pm](https://cloud.githubusercontent.com/assets/1479179/6309098/ae4e7446-b8fe-11e4-9122-988bc52952ba.png)

**Comment by badrinathvm** [comment]
With the update existing set up also got corrupted :( , Require your help , need to run lots of test.

**Comment by badrinathvm** [comment]
Peter , i identified the issue , Character   '  was not proper in 'DullesChrome' . I updated the proper quotation. Working as expected.

**Comment by badrinathvm** [comment]
Closing the issue, since it is working as expected.

**Comment by tobli** [comment]
Just a note on upgrading: if you've installed sitespeed globally (using npm -g) you can update using "npm -g update sitespeed.io". So no need to uninstall and install again (although the result is the same).
