### ISSUE TITLE
Could not fetch data for aggregator for Web Page Test Elements

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#589]
Though WebPage test was successful, it is not able to paint the web page test parameters. 

Attache screen shot.

![screen shot 2015-02-20 at 1 46 40 pm](https://cloud.githubusercontent.com/assets/1479179/6309957/f940052a-b906-11e4-8a02-1421c3b52a88.png)

Need report very badly. Help is appreciated.

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
there's bad handling if you only run the test one time, I'll do a fix later this weekend. However, you should always do more runs, to get better statistical values. So for now, configure it to run at least three (<code>-n 3</code>).

Best
Peter

**Comment by badrinathvm** [comment]
@Peter , 
Perfect , it works if i run more number of times as you suggested.  Thanks a ton , Saved my day.

**Comment by badrinathvm** [comment]
Closing the issue since it is working as expected. Please let me know once the fix is available for single run.
