### ISSUE TITLE
Lazy load screenshot page

### ISSUE THREAD

**Issue by paazmaya** [sitespeedio/sitespeed.io#591]
It might kill the browser in some cases when there are thousands of full page screenshots shown in a single page, in the report that is.

Would it make sense to add lazy loading or some other similar method?

**Comment by soulgalore** [comment]
Hey @paazmaya , yep I see your point lets see how we can make this happen.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by paazmaya** [comment]
Yes sir!
