### ISSUE TITLE
I dont know wich is the command i need.

### ISSUE THREAD

**Issue by hectortelini** [sitespeedio/sitespeed.io#593]
I need output only the average of yslow and pagespeed in json file, without HTML, for convert to csv and after to Excel file. I dont know wich is the command i need. 

I prove with many options but don't obtain the results expected.

Thanks for the help and sorry for my english ;)

**Comment by soulgalore** [comment]
Hi @hectortelini ,
yep it is not perfectly clear. Do you mean you want the Google Page Speed Insights or the browser timings (like how fast the page is in the browser)? To disable the the HTML run like this:
<code>sitespeed.io --no-html XXX</code>

To fetch browsert imings add <code>-b chrome</code> for using chrome. I'll help with the rest later :)

Best
Peter

P.S Feel free to add a PR for getting the data to CSV :)

**Comment by hectortelini** [comment]
I want only obtain the score of yslow and Google Page Speed Insights
and for obtain the data in a JSON file, which is the option?

thanks for your quick answer

**Comment by soulgalore** [comment]
Ok! So get your Google Page Speed Insights key here: https://console.developers.google.com/project and then run like this:
<code>sitespeed.io -u YOUR_URL --no-html --gpsiKey YOUR_KEY</code>

Best
Peter

**Comment by soulgalore** [comment]
Hi @hectortelini 
does it work for you? 

Best
Peter

**Comment by soulgalore** [comment]
Closing this now @hectortelini  , please reopen if don't work!

Best
Peter
