### ISSUE TITLE
Multi Threading possible ?

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#594]
Is there any way to do multi threading of these requests ? 

if i mention -n 25 current behaviour it hits the request one followed by other. Do we have provision of doing it simultaneously ?

**Comment by soulgalore** [comment]
Hello @badrinathvm 
no. They are done one by one to make each request as equal as possible (meaning empty cache and nothing else that can interrupt the metrics.

Best
Peter

**Comment by badrinathvm** [comment]
ok. Thank you.

**Comment by soulgalore** [comment]
if you test many different url:s, you can set it up to run on different machines and then send the metrics to   Graphite (depending on what and how you are measuring).
