### ISSUE TITLE
Waterfall .png filenames incorrect when changing connection profile

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#595]
Hi @soulgalore ,

Maybe this is related to issue #581 https://github.com/sitespeedio/sitespeed.io/issues/581

Waterfall images are not loading when changing WPT connection profile.

I've changed connectivity.ini in WPT to add a new profile:

[NL-Average]
label="NL Average (12/2.5 Mpbs 15ms RTT)"
bwIn=12000000
bwOut=2500000
latency=15
plr=0

I've also changed the connectivity value in custom JSON to match the new added profile in connectivity.ini from WPT:

{
  "server": "private",
  "location": "Local-WPTDriver:Chrome",
  "connectivity": "NL-Average",
  "timeout": "3600",
  "runs": "3",
  "firstViewOnly": "false"
}

The waterfall images from WebPagetest in Sitespeed HTML report are not loading because of incorrect filenames:

HTML:
domainname.tld-local-wptdriver-chrome-cable-waterfall.png

Server:
domainname.tld-local-wptdriver-chrome-nl-average-waterfall.png

sitespeed.io.log entry:

2015-02-24T19:00:45.914Z - info: [sitespeed] Running WebPageTest http://private pollResults=10, timeout=3600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Local-WPTDriver:Chrome, connectivity=NL-Average, video=true, server=private

**Comment by soulgalore** [comment]
Hi @Vandrix 
thanks for the report! Did a quick check in the handlebars code that creates the HTML and it seems it gets the connectivity from the result from WebPageTest. Could you please help me to debug, if you turn on the verbose logging <code>--verbose</code> the log will ouput the JSON returned from WPT. Check for a line looking like this:
<pre>
Got the following from WebPageTest ..
</pre>
And there you will get all the JSON from WPT. Check the connectivity do you get cable or NL-Average back?

Best
Peter

**Comment by Vandrix** [comment]
Hi @soulgalore 

JSON output from WPT in sitespeed log says:

"connectivity":"Cable","bwDown":12000,"bwUp":2500,"latency":15,"plr":0

**Comment by Vandrix** [comment]
2015-02-24T21:54:15.299Z - info: [sitespeed] Running WebPageTest http://private.tld pollResults=10, timeout=3600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Local-WPTDriver:Chrome, connectivity=NL-Average, video=true, server=private

**Comment by soulgalore** [comment]
ok cool, so the WPT reports back *Cable*. Could here be a config in WPT?

Best
Peter

**Comment by Vandrix** [comment]
I don't have 'Cable' in WPT connectivity.ini

BTW, cable is also being used in Graphite keys when I'm using connectivity=NL-Average
So also no change there.

**Comment by soulgalore** [comment]
yep, the Graphite key is also generated from the data returned from WPT.

So just to make sure I understood correctly. WPT returns:
<code>"connectivity":"Cable","bwDown":12000,"bwUp":2500,"latency":15,"plr":0</code> And bwDown and bwUp is correct as you configured, but the connectivity name is wrong?  Did the JSON from WPT mention anything about *NL-Average*? Thinking if I maybe should get the data from somewhere else?

Best
Peter

**Comment by Vandrix** [comment]
I just ran the test again to be sure.

JSON output from WPT in sitespeed log returns:

"connectivity":"Cable","bwDown":0,"bwUp":0,"latency":0,"plr":0,"completed"

My current connectivity.ini:

[NL-Average]
label="NL Average (12/2.5 Mpbs 15ms RTT)"
bwIn=12000000
bwOut=2500000
latency=15
plr=0

[DSL]
label="DSL (1.5 Mbps/384 Kbps 50ms RTT)"
bwIn=1500000
bwOut=384000
latency=50
plr=0

[FIOS]
label="FIOS (20/5 Mbps 4ms RTT)"
bwIn=20000000
bwOut=5000000
latency=4
plr=0

[Dial]
label="56K Dial-Up (49/30 Kbps 120ms RTT)"
bwIn=49000
bwOut=30000
latency=120
plr=0

[3G]
label="Mobile 3G (1.6 Mbps/768 Kbps 300ms RTT)"
bwIn=1600000
bwOut=768000
latency=300
plr=0

[Native]
label="Native Connection (No Traffic Shaping)"
bwIn=0
bwOut=0
latency=0
plr=0

---------
JSON file :

{
  "server": "private",
  "location": "Local-WPTDriver:Chrome",
  "connectivity": "NL-Average",
  "timeout": "3600",
  "runs": "3",
  "firstViewOnly": "false"
}

sitespeed log entry WPT:

2015-02-25T19:58:01.161Z - info: [sitespeed] Running WebPageTest http://private pollResults=10, timeout=3600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Local-WPTDriver:Chrome, connectivity=NL-Average, video=true, server=private

**Comment by soulgalore** [comment]
ok thanks! so I guess then, one workaround could be that use the supplied *connectivity* and not use the one returned from WPT, that would make it cleaner (and work for you). Let me check if I can do the fix tomorrow, else I know I have time on Friday.

**Comment by Vandrix** [comment]
What I'm doing now as workaround is adding the same profile in connectivity.ini with [Cable], like this:

[Cable]
label="NL Average (12/2.5 Mpbs 15ms RTT)"
bwIn=12000000
bwOut=2500000
latency=15
plr=0

And change JSON "connectivity": "NL-Average" back to "connectivity": "Cable"

Thnx!

**Comment by soulgalore** [comment]
Hi @Vandrix 
so thinking you could add an issue at https://github.com/WPO-Foundation/webpagetest and check with Pat how it can be solved in WPT, if it should return "NL-Average", then we don't have to do a workaround (cleaner on our side to always trust the WPT data).

Best
Peter

**Comment by soulgalore** [comment]
closing this, nothing 2do.
