### ISSUE TITLE
Jenkins Jobs failing with sitespeed

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#598]
Jenkins jobs are getting failed with the below error 

![screen shot 2015-02-24 at 4 19 04 pm](https://cloud.githubusercontent.com/assets/1479179/6362354/18263a30-bc41-11e4-9e2a-66419ed0df93.png)

Any help is appreciated.

**Comment by soulgalore** [comment]
Hey @badrinathvm 
ah sorry seems we need more documentation. First choose JUnit XML (I think you chosen budget right now):
http://www.sitespeed.io/documentation/jenkins-plugin-configuration.png

Then you can match the exact xml-file (if you generate many). The junit file is named <code>sitespeed.io-junit.xml</code>

Best
Peter

**Comment by soulgalore** [comment]
Closing this now @badrinathvm , please reopen if don't work!

Best
Peter
