### ISSUE TITLE
Permission Denied Exception while executing from Jenkins 

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#599]
Permission Denied exception when executing from Jenkins , i have read & write permission to the folders but still seeing denied exception.
![screen shot 2015-02-24 at 5 00 27 pm](https://cloud.githubusercontent.com/assets/1479179/6363022/1b54c238-bc48-11e4-9b60-db7b74737954.png)

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
which user in Jenkins run the job? I think that user don't have permissions to run the sitespeed executable.

Best
Peter

**Comment by badrinathvm** [comment]
there are only two user one me and admin , I have given all the privileges read & write to these folders , but still it is not picking up. Do i need to chnage any other settings ?I badly needs this to work.

**Comment by soulgalore** [comment]
Hi again @badrinathvm ,
yes but I think what's missing is execute privileges for <code>/Users/Shared/sitespeed/node_modules/sitespeed.io</code> or where you have the symlink that points it out.

Best
Peter

**Comment by badrinathvm** [comment]
Updated permissions working as expected. Thanks a ton.

**Comment by soulgalore** [comment]
perfect!
