### ISSUE TITLE
Quick Link for setting up Graphite

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#602]
Have been successful in  setting up sitespeed for Jenkins. Next step is integration to graphite. Any documentation for setting up graphite ? Any help is appreciated.

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
easiest way is to use Docker. Use this one for example: https://registry.hub.docker.com/u/hopsoft/graphite-statsd/

Make sure to map the data dir to your physical disk! We will publish a Graphite & Grafana example for sitespeed.io but still have some work 2do.

Best
Peter

**Comment by badrinathvm** [comment]
Let me install and try this , thanks for providing quickly.

**Comment by badrinathvm** [comment]
This works like awesome , now how can i configure this in Jenkins for results ?

**Comment by badrinathvm** [comment]
Attached screens hot for reference

![screen shot 2015-03-02 at 2 51 14 pm](https://cloud.githubusercontent.com/assets/1479179/6452585/957cd1c0-c0eb-11e4-8d0d-ed2207cd79de.png)

**Comment by badrinathvm** [comment]
Facing below exception 

error: Couldn't send data to Graphite:Error: getaddrinfo ENOTFOUND http://192.168.59.103:49156/ for host:http://192.168.59.103:49156/ port:2003

![screen shot 2015-03-02 at 3 25 00 pm](https://cloud.githubusercontent.com/assets/1479179/6453173/4a9a4138-c0f0-11e4-893e-0ba9a6311227.png)

**Comment by soulgalore** [comment]
Hey @badrinathvm ,
what's your config? Configure the <em>graphiteHost</em> without protocol and port like <em>192.168.59.103</em>. If yoiu run Graphite on standard port (2003) you don't need to configure it.

Then next step is to add grafana.org, then your graphs will look beautiful :)

Best
Peter

**Comment by badrinathvm** [comment]
Grafana image got installed successfully , how can i view the dashboard ?

**Comment by badrinathvm** [comment]
![screen shot 2015-03-02 at 10 31 40 pm](https://cloud.githubusercontent.com/assets/1479179/6457523/e84bd0fa-c12b-11e4-9b2d-8f3247357697.png)

How can i view the dashboard ?

**Comment by soulgalore** [comment]
you need to configure your Grafana instance to fetch the data from Graphite, check the docs on Grafana.org.  Then make sure the ports don't collide. The container you are using now seems to use both grafana & graphite, and running on port 80 on your machine.

**Comment by badrinathvm** [comment]
I configured below things in Config.js  

below is my Config.js still page doesnt gets loaded when i use "http://my.graphite.server.com:8084"

define(['settings'],
function (Settings) {
  return new Settings({

    datasources: {
      graphite: {
        type: 'graphite',
        url: "http://my.graphite.server.com:8084",
      },
      elasticsearch: {
        type: 'elasticsearch',
        //url: "/elasticsearch",
		url: "http://my.elastic.server.com:9200",
        index: 'grafana-dash',
        grafanaDB: true,
      }
    },

    // default start dashboard
    default_route: '/dashboard/db/welcome',

    // Elasticsearch index for storing dashboards
    grafana_index: "grafana-dash",

    // specify the limit for dashboard search results
    search: {
      max_results: 20
    },

    // set to false to disable unsaved changes warning
    unsaved_changes_warning: true,

    // set the default timespan for the playlist feature
    // Example: "1m", "1h"
    playlist_timespan: "1m",

    // Add your own custom pannels
    plugins: {
      panels: []
    }

  });
});


Any help is appreciated , i am almost at the end .

**Comment by soulgalore** [comment]
hello again,
in the config.js file, you need to add the url and port to graphite, to test that it is the right url, you can open  a browser and access it. Meaning change **http://my.graphite.server.com:8084** to your IP (or if you have a host setup) and the port number you use when you access graphite.
Best
Peter

**Comment by JeroenVdb** [comment]
@badrinathvm `datasources.graphite.url` should point to the Graphite web interface (like you've shown in https://github.com/sitespeedio/sitespeed.io/issues/602#issuecomment-76844758).

Then you surf to Grafana dashboard using http://my.graphite.server.com:80" (or whatever port you're using).

**Comment by badrinathvm** [comment]
Facing issue My graphite URL is  http://192.168.59.103:49156/  i have configured this in my config.js 

 datasources: {
      graphite: {
        type: 'graphite',
        url: "http://192.168.59.103:49156/",
      },
      elasticsearch: {
        type: 'elasticsearch',
        url: "/elasticsearch",
        index: 'grafana-dash',
        grafanaDB: true,
      }
    }

And my Grafana dashboard ports are 

85/tcp -> 0.0.0.0:80
8128/udp -> 0.0.0.0:8128
8129/tcp -> 0.0.0.0:8129

I navigated to "http://my.graphite.server.com:8129" it's not identfying :( Any thing in my configuration ?

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
http://my.graphite.server.com:8129 is just an example. If you run Graphite & Grafana on the same server, try your servers ip: http://192.168.59.103:8129/

Best
Peter

**Comment by badrinathvm** [comment]
No Luck , it is navigating to "https://www.googleapis.com/rpc" and getting interuptted :( Any thing i am missing ?

**Comment by soulgalore** [comment]
Hi again @badrinathvm ,
so I don't fully follow. Just so I know, what OS are you running? 

Best
Peter

**Comment by badrinathvm** [comment]
Let me explain the issue ... 

My graphite port details are : 

2003/tcp -> 0.0.0.0:49153
80/tcp -> 0.0.0.0:49154
8125/udp -> 0.0.0.0:49153


And my grafan details are 

8125/udp -> 0.0.0.0:8125
8126/tcp -> 0.0.0.0:8126
80/tcp -> 0.0.0.0:80

and Config.js datasources is 

  datasources: {
      graphite: {
        type: 'graphite',
        url:"http://192.168.59.103:8126/",
      },
      elasticsearch: {
        type: 'elasticsearch',
        url: "/elasticsearch",
        index: 'grafana-dash',
        grafanaDB: true,
      }
    }

I have configured proper ports if u notice . Still i am getting web page not found exception 

OS :  OS X v10.9.5

**Comment by soulgalore** [comment]
ok, and the ip "192.168.59.103" is the ip you get when you run <code>boot2docker ip</code>? Then you should access 192.168.59.103:80 to see grafana.

then make sure the ports don't collide (you are using 49153 on two places) and then point the graphite datasource to the IP that is normal port 80.

**Comment by badrinathvm** [comment]
Yes 192.168.59.103 is my boot2docker ip. When i enter 192.168.59.103:80 to see grafana it shows web page not found , attached screen shot below 

![screen shot 2015-03-04 at 7 56 19 pm](https://cloud.githubusercontent.com/assets/1479179/6499003/98528354-c2a8-11e4-8071-68696b373565.png)

**Comment by soulgalore** [comment]
To just test to get it up and running, stop your grafana container and test the new upcoming grafana2:
https://registry.hub.docker.com/u/grafana/grafana/

<code>docker run -i -p 3000:3000 grafana/grafana:develop</code>

It is not ready for production but it can help you just see if you can connect to graphite and see everything (you configure the graphite connection using the gui).

**Comment by badrinathvm** [comment]
Facing below exception 
![screen shot 2015-03-05 at 10 32 55 am](https://cloud.githubusercontent.com/assets/1479179/6511653/fd003074-c322-11e4-832d-abf8d26358a5.png)

**Comment by soulgalore** [comment]
I think you did not choosed the develop tag as I wrote?
<pre>docker run -i -p 3000:3000 grafana/grafana:develop</pre>

running without develop will try the tag latest but there is no latest since they avoid it until it gets properly released,

**Comment by badrinathvm** [comment]
I am able to install new image with above command and able to see graphite. 

![screen shot 2015-03-05 at 4 52 53 pm](https://cloud.githubusercontent.com/assets/1479179/6518166/0ebb79ce-c358-11e4-9021-4dbfbac8c2ec.png)

Next how can i configure Grafana ?

**Comment by soulgalore** [comment]
Think this is ok:
http://www.sitespeed.io/documentation/performance-dashboard/

closing the issue now.
