### ISSUE TITLE
Plugin for Safari and IE 

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#607]
Current Sitespeed.hdi plugin to jenkins has only chrome, firefox browsers , do we have provision for safari and IE browsers ?

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
so we are trying out support for IE & Safari, right now you need to start the selenium jar yourself, but in latest nodejs selenium it is possible to start them easier, meaning maybe we can add support later. However Safari need Safari 8 to work (only Mac right) and IE needs Windows.

Best
Peter

**Comment by soulgalore** [comment]
closing this for now.
