### ISSUE TITLE
Decrease the default Java memory size used for the crawler

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#610]
Default today is 1024 which is a really bad idea for smaller boxes. Let's make it 256 until we skip the Java crawler for simpel crawler. Lets release it in 3.2.

**Comment by tay1orjones** [comment]
@soulgalore Is there documentation on how to up the limit? Having trouble finding it and I'm getting the out of memory error when I run with a small crawl depth of 1.

**Comment by soulgalore** [comment]
Hey @tay1orjones ,
yes you can find it here (but maybe it's a little unclear):http://www.sitespeed.io/documentation/configuration/#the-options

<code>
  --memory <INTEGER>                                     How much memory the Java process will have (in mb).  [256]
</code>

so like: <code>sitespeed.io -u http://www.sitespeed.io --memory 1024
