### ISSUE TITLE
issue while installing sitespeedio

### ISSUE THREAD

**Issue by amitsingh0542** [sitespeedio/sitespeed.io#613]
I was trying to configure the sitespeed with my project. But whenever i am trying to install the package getting the issue with package. Please have a look.

![issue](https://cloud.githubusercontent.com/assets/5037180/6580495/096acb1e-c777-11e4-9295-24095832871c.jpg)

**Comment by soulgalore** [comment]
hey @amitsingh0542 ,
do you get the same error (the same file) for every try?  I've only tested it on Windows 8.1. Else try out Vagrant box.

Best
Peter

**Comment by tobli** [comment]
Also, I notice the version of npm you're using (1.4.3) is quite old. An `npm install` related problem might be cured by upgrading to a later version. The current as Im writing this is 2.7.0. For instructions on how to upgrade on Windows, see https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows.

**Comment by amitsingh0542** [comment]
hi @soulgalore,

I tried 4 to 5 times and always it get stuck here. Please let me know if any solution for this.

**Comment by amitsingh0542** [comment]
Hi @tobli,

I checked with my npm version and try to update. but it says all updated version all available in your module. Please have a look.

![issue-1](https://cloud.githubusercontent.com/assets/5037180/6590009/c8441308-c7cf-11e4-8457-919288d7a863.jpg)

**Comment by tobli** [comment]
Hi @amitsingh0542,
I was referring to the version of npm itself, i.e. the package manager that installs sitespeed.io and other modules. The npm-check-updates tool checks the version of dependencies for a given module, in your example that would be whatever modules you have listed in your d:\perf\package.json file.

You are using npm 1.4.3 (you can check by running `npm version`), the latest is 2.7.0.

**Comment by soulgalore** [comment]
Hi @amitsingh0542 ,
is this still an issue, if so, please re-open the issue.

**Comment by amitsingh0542** [comment]
Still, i have the same issue. This time i tried with Windows 7 and my npm version is 2.10.1
![speedtest](https://cloud.githubusercontent.com/assets/5037180/8142747/bea60b36-114d-11e5-9855-df09687e463d.jpg)

**Comment by cgoldberg** [comment]
install git and make it available on your path

**Comment by amitsingh0542** [comment]
![issue](https://cloud.githubusercontent.com/assets/5037180/8145005/de3ea3f4-11bb-11e5-9348-a27de916405d.png)

I configured as you said and configured the application. While running grunt i am facing the issue. Please check and let me know if am missing anything.
