### ISSUE TITLE
Provide a way to rename the DomainFolder in the output directory

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#615]
Currently , i got ./sitespeed-result/{hostname}/{DateStamp}/... for my test results folder, it would be better to have a way to change the hostname/domainname folder freely, so that user can specify the page name rather than domain name for their folder , it is hard to automated their tasks..

Recommendation:
Provide a value with "--suppressDomainFolder" which can overwrite the foldername by whatever end user want, for example:
--suppressDomainFolder MyHomePage
Sample output: 
./sitespeed-result/MyHomePage/{DateStamp}/... 

Thank you!

**Comment by soulgalore** [comment]
hey @joychester ,
so I think it's possible to do what you want right now, I think the docs needs to be cleaner. It could be cleaned up as you say (making it easier), lets see what I can do, but right now you can achieve what you want with:
<code>–resultBaseDir ./sitespeed-result/MyHomePage --suppressDomainFolder</code>

I think?

Best
Peter

**Comment by joychester** [comment]
Thanks peter for your suggestions, this will ease my work now:)

**Comment by tobli** [comment]
This seems resolved, so I'm closing this issue.
