### ISSUE TITLE
Browsertime errors when using firefox

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#618]
Since version 3.2.0 I'm getting Browsertime errors on firefox:

error: { [UnknownError: f.QueryInterface is not a function]
  code: 13,
  state: 'unknown error',
  message: 'f.QueryInterface is not a function',
  name: 'UnknownError',
  stack: 'UnknownError: f.QueryInterface is not a function\n    at new bot.Error (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)\n    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)\n    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:377:20\n    at promise.ControlFlow.runInFrame_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)\n    at promise.Callback_.goog.defineClass.notify (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)\n    at promise.Promise.notify_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)\n    at Array.forEach (native)\n    at Object.goog.array.forEach (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)\n    at promise.Promise.notifyAll_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)\n    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)' }
error: Error running browsertime: { [UnknownError: f.QueryInterface is not a function]
  code: 13,
  state: 'unknown error',
  message: 'f.QueryInterface is not a function',
  name: 'UnknownError',
  stack: 'UnknownError: f.QueryInterface is not a function\n    at new bot.Error (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)\n    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)\n    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:377:20\n    at promise.ControlFlow.runInFrame_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)\n    at promise.Callback_.goog.defineClass.notify (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)\n    at promise.Promise.notify_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)\n    at Array.forEach (native)\n    at Object.goog.array.forEach (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)\n    at promise.Promise.notifyAll_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)\n    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)' }

**Comment by soulgalore** [comment]
Hi @Vandrix can you share the URL you are using? Googling the error says that it usually is because the URL is missing protocol. We should have a check for that but maybe it is not working or it's another thing.

Best
Peter

**Comment by Vandrix** [comment]
Hi @soulgalore , you are right! Sorry for bothering. I made a mistake with URI's.

regards,
