### ISSUE TITLE
YSlow not working for specific URL

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#619]
YSlow is giving errors on specific URL:

verbose: Done processing url in yslow: private.tld
error: Yslow output for 'private.tld' (stdout): FAIL to load http://private.tld

error: Error running yslow for url 'private.tld': { [Error: Command failed: /usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /var/www/html/benchmark_private/benchmark.master/2015-03-19-12-09-20/data/yslow/private.tld-yslow.json -vp 1280x800 private.tld
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /var/www/html/benchmark_private/benchmark.master/2015-03-19-12-09-20/data/yslow/private.tld-yslow.json -vp 1280x800 private.tld' }

**Comment by Vandrix** [comment]
Additional info: info: OS: 'linux 3.13.0-46-generic', Node.js: 'v0.12.0', sitespeed.io: '3.2.0', PhantomJS: '1.9.8', java: '1.7.0_75', browsertime: '0.9.1'

**Comment by Vandrix** [comment]
Never mind. Look like some firewall issue @ our client side.

**Comment by soulgalore** [comment]
hey @Vandrix no worries, I think there's a bug when we feed URL:s from a file, we don't verify that they are valid (we do that if we feed with the U param), will fix asap.

Best
Peter
