### ISSUE TITLE
Could not fetch data for aggregator

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#620]
Hi @soulgalore ,

With the latest sitespeed version 3.2.2 I'm having some trouble again, see error messages below:
 
error: Could not fetch data for aggregator: TTFBWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: BytesWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: FirstPaintWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ImageSavingsWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ImageTotalWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: LoadTimeWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: RenderWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: RequestsWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ServerRTTWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: SpeedIndexWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: userTiming: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: VisualCompleteWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Catched an uncaught exception:TypeError: Cannot read property 'repeatView' of undefinedTypeError: Cannot read property 'repeatView' of undefined
    at /usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:184:48
    at Array.forEach (native)
    at collectWPT (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:171:28)
    at Object.exports.processPage (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:35:5)
    at /usr/local/lib/node_modules/sitespeed.io/lib/collector.js:126:7
    at Array.forEach (native)
    at Collector.collectPageData (/usr/local/lib/node_modules/sitespeed.io/lib/collector.js:125:19)
    at processAnalysisResults (/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:171:14)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:68:7
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
info: Stopping proxy

info: OS: 'linux 3.13.0-46-generic', Node.js: 'v0.12.0', sitespeed.io: '3.2.2', PhantomJS: '1.9.8', java: '1.7.0_75', browsertime: '0.9.3'

JSON file:

[
  {
    "location": "Local-WPTDriver:Chrome",
    "connectivity": "Cable",
    "timeout": "3600",
    "runs": "3",
    "firstViewOnly": "true"
  },
  {
    "location": "Local-WPTDriver:Firefox",
    "connectivity": "Cable",
    "timeout": "3600",
    "runs": "3",
    "firstViewOnly": "true"
  },
  {
    "location": "Local-WPTDriver:IE",
    "connectivity": "Cable",
    "timeout": "3600",
    "runs": "3",
    "firstViewOnly": "true"
  }
]

Any clue?

**Comment by soulgalore** [comment]
Hi @Vandrix ,
hmm, seems like something we have missed, but I tried it locally on my machine and it worked. Can you share me the URL (you got my email right :) ) and I can check what's wrong.

Best
Peter

**Comment by Vandrix** [comment]
Hi @soulgalore ,

It's fixed. I made a typo in location. Local-WPTDriver:IE -> Local-WPTDriver:IE 11
Then it all runs fine.

My fault :-(

**Comment by soulgalore** [comment]
ah cool, I didn't get around to test it.
