### ISSUE TITLE
Error when running with headless browser 

### ISSUE THREAD

**Issue by yesman82** [sitespeedio/sitespeed.io#621]
When running sitespeed.io with headless browser it produces an error while executing phantomjs. This error is preceded by a syntax error.

OS: OS X Yosemite (10.10.2), 'darwin 14.1.0', 
Node.js: 'v0.12.0', 
sitespeed.io: '3.2.2', 
PhantomJS: '1.9.8', 
java: '1.8.0_40', 
browsertime: '0.9.3'

Error occurs when executing: ```sitespeed.io -u http://www.toptarif.de -d 0 -n 1 --noYslow -b headless -v``` but also occures when using default values like ```sitespeed.io -u http://www.toptarif.de -b headless```.

Terminal log
```
admins-MacBook-Pro:sitespeedio admin$ sitespeed.io -u http://www.toptarif.de -d 0 -n 1 --noYslow -b headless -v
info: OS: 'darwin 14.1.0', Node.js: 'v0.12.0', sitespeed.io: '3.2.2', PhantomJS: '1.9.8', java: '1.8.0_40', browsertime: '0.9.3'
info: Will crawl from start point http://www.toptarif.de with crawl depth 0
info: Will analyze 1 pages
info: Fetching timing data using phantomjs for http://www.toptarif.de
error: Output for 'http://www.toptarif.de' (stdout): SyntaxError: Parse error


error: Error running headless for url 'http://www.toptarif.de': { [Error: Command failed: /usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/collectTimings.js http://www.toptarif.de /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-24-52/data/headless/www.toptarif.de-1.json /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-24-52/data/har/headless/www.toptarif.de-1.har 1280 800 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/collectTimings.js http://www.toptarif.de /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-24-52/data/headless/www.toptarif.de-1.json /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-24-52/data/har/headless/www.toptarif.de-1.har 1280 800 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36' }
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file domains.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote results to /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-24-52
info: The analyze took a minute (62 seconds)
```

Error html:
```
headless - { [Error: Command failed: /usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/collectTimings.js http://www.toptarif.de/ /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-43-09/data/headless/www.toptarif.de-1.json /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-43-09/data/har/headless/www.toptarif.de-1.har 1280 800 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 ] killed: true, code: null, signal: 'SIGTERM', cmd: '/usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/collectTimings.js http://www.toptarif.de/ /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-43-09/data/headless/www.toptarif.de-1.json /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-14-43-09/data/har/headless/www.toptarif.de-1.har 1280 800 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36' }
```

**Comment by soulgalore** [comment]
hey @yesman82 
ah think the docs isn't clear enough, you need to have phantomjs 2 to collect timings (you need to install it and pass the path to sitespeed, so that 2.0 is used). we are waiting on 2.0 to be availible on all platforms before we ship it with sitespeed.io.

best
Peter

**Comment by yesman82** [comment]
Thanks for your fast response. 
* I repacked the phantomjs binary with UPX  - unfortunately didn't work.
* Using the pre-compiled phantomjs version from eugene1g (found here: https://github.com/eugene1g/phantomjs/releases) also didn't work out. 

Both resulted in the same error as shown before :-1:
Just the syntax error is gone :+1:

```
admins-MacBook-Pro:sitespeedio admin$ sitespeed.io -u http://www.toptarif.de -d 0 -n 1 --noYslow -b headless --phantomjsPath /usr/local/bin/phantomjs 
info: OS: 'darwin 14.1.0', Node.js: 'v0.12.0', sitespeed.io: '3.2.2', PhantomJS: '2.0.0', java: '1.8.0_40', browsertime: '0.9.3'
info: Will crawl from start point http://www.toptarif.de with crawl depth 0
info: Will analyze 1 pages
info: Fetching timing data using phantomjs for http://www.toptarif.de
error: Error running headless for url 'http://www.toptarif.de': { [Error: Command failed: /usr/local/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/collectTimings.js http://www.toptarif.de /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-16-03-44/data/headless/www.toptarif.de-1.json /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-16-03-44/data/har/headless/www.toptarif.de-1.har 1280 800 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/local/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/local/lib/node_modules/sitespeed.io/lib/headless/scripts/collectTimings.js http://www.toptarif.de /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-16-03-44/data/headless/www.toptarif.de-1.json /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-16-03-44/data/har/headless/www.toptarif.de-1.har 1280 800 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36' }
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file domains.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote results to /Users/admin/Desktop/sitespeedio/sitespeed-result/www.toptarif.de/2015-03-26-16-03-44
info: The analyze took a minute (62 seconds)
```

I have not tried compiling the source code myself yet.

**Comment by soulgalore** [comment]
Hi again @yesman82 ,
yes you are perfectly, I've broken the function a couple of days ago. I will do a fix release later tonight. 

Did a quick test but the  http://www.toptarif.de still didn't work so I need to check what's wrong.

Thanks for reporting!
Best
Peter

**Comment by soulgalore** [comment]
Hi again @yesman82 , 
I've released v3.2.3 where it works, thanks again for reporting.

**Comment by yesman82** [comment]
Thank you @soulgalore for fixing this issue. I can confirm that it works now with OS X and the pre-compiled phantomjs version from eugene1g and will probably work on other OSs too.

**Comment by sampun** [comment]
Hi,
Am using sitespeed.io version 3.11.5 but still getting the same issue, Will you please help in closing this issue.
It works fine for some url only. But most of the time we got below issue.

sitespeed.io -u http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html -b headless -d 0  -r /data/tmp
info: OS: 'linux 3.10.0-229.14.1.el7.x86_64', Node.js: 'v0.10.42', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_91', browsertime: '0.12.2'
info: Will analyze 1 page
info: Running YSlow for http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html [phantomjs]
info: Fetching timing data using phantomjs for http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html
error: Error running headless for url 'http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html': { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }
info: Fetching timing data using phantomjs for http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html
error: Error running headless for url 'http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html': { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }
info: Fetching timing data using phantomjs for http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html
error: Error running headless for url 'http://www.webupd8.org/2016/03/mailnag-email-notifier-12-released-with.html': { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }
info: Done analyzing urls
info: Wrote file errors.html
info: Wrote file domains.html
info: Wrote file assets.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote file www_webupd8_org-2016-03-mailnag-email-notifier-12-released-with.html.html
info: Wrote results to /data/tmp/www.webupd8.org/2016-05-03-15-46-20
info: The analyze took 4 minutes (232 seconds)
