### ISSUE TITLE
[Question] Set cookie before test

### ISSUE THREAD

**Issue by JakeChampion** [sitespeedio/sitespeed.io#622]
Hi, I was wondering if it is possible to set a cookie before running a test? I've been able to do it using webpagetest directly and through the nodejs webpagetest module but not through sitespeed.

If this isn't a feature currently in the project, would it be a feature that you would consider having in the future?

**Comment by soulgalore** [comment]
Hi @JakeChampion ,
do you want to set the just when you're using WPT or for all things? What I've seen people do (for example to fake a logged in user), is first login the user using the browser, take the session info and add it as a request parameter <pre>--requestHeaders</pre>. That will work for YSlow and collecting timings using the browsers, however it is not populated to WPT. There's a good way to do it add them like proposed in https://github.com/sitespeedio/sitespeed.io/issues/568 but I haven't had time to do it, I think it will not happen in May, probably after that. I'm focusing on getting the online version working first, that's my nr 1 prio. But if you have time to do a PR, I can try it out?

Best
Peter

**Comment by soulgalore** [comment]
Closing this now, since we support scripting for WPT now and will support script in #688
