### ISSUE TITLE
[Feature Request] Passing script to WPT

### ISSUE THREAD

**Issue by JakeChampion** [sitespeedio/sitespeed.io#623]
WPT can accept either a url or a [script](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting), would it be possible to have sitespeed take and pass a script to WPT? I'm not sure how this would work with other testing agents such as yslow, headless browsers etc.

Being able to preconfigure a browser for a test, such as setting cookies is what I'm currently using the scripting feature for however, the preconfiguration for a test could also be accessing another page first and then the page you want to test second in order to test shared css and js caching for example.

**Comment by soulgalore** [comment]
Hi again @JakeChampion,
yep it would be possible since implemented in https://github.com/marcelduran/webpagetest-api, just not sure how to make it work for the rest as you said. One way maybe could be that you could pass the scrip and sitespeed.io adds the URL as the last point of the script, so that all pages tested will use the passed script? The the script is only valid for WPT but maybe that is good, if you sitespeed for collecting WPT metrics and sending them to Graphite.

Lets discuss here how we can do it, I think would cool to have the WPT script functionality. Ping @tobli

Best
Peter

**Comment by Verkurkie** [comment]
I second the desire (or 'need' in our case) for scripting capabilities. We are seriously looking at incorporating sitespeed.io into our CI pipelines but can't do it without scripting. The majority of our sites/URLs use our own SSO auth. This is not basic auth and can't simply be set through a cookie or anything like that. We have to run through SSO (typical two edit boxes and one click) before we can get to our target URLs ... it would be awesome if we could have a generic 'auth' script that can be used by all the tools sitespeed can kick off (browsertime, phantomjs/yslow, WPT, gpsi). Not easy I suppose, but it would be very awesome!

**Comment by Vandrix** [comment]
+1

**Comment by cgoldberg** [comment]
I faced a similar situation with an app I was using with sitepseed.io.  All the pages I needed to load were behind login/authentication.

So as workaround/hack, I came up with this:  https://github.com/edx/edx-sitespeed

It only works for this specific application, but you can take the same concept and use it for any site:
https://github.com/edx/edx-sitespeed/blob/master/edx-sitespeed.py

I call it "shnerp the cookie"..  I use an http library to login to the app and write out the session cookie to a json file... and then pass it to sitespeed.io via the --request-headers command line arg, and voila, I am authenticated.

**Comment by soulgalore** [comment]
@cgoldberg thanks for sharing your fix! 

For running WPT, well I don't have a good pattern right now for solve it, but it's solvable. Right now I'm focusing on getting the online version of sitespeed up and running, then I want to add a HAR viewer and after that maybe we can fix this for WPT, lets see, don't want to promise it :) 

Getting a fix for sitespeed.io (except for doing like @cgoldberg did) will probably be doable in september/early october. I think that's when the next "big" release will be and what we need to do then is to be able to run the rule system in a browser, meaning dropping the current YSlow version and instead inplement a new rule engine that can run in all major browser and will support and work on both HTTP2 and HTTP1. And when we have that in place, it will be easier to support scripting for login or doing other cool stuff.

@Verkurkie the solution Corey will only work for the YSlow/sitespeed.io rules and Browsertime, not for GPSI and WebPageTest. Is the cookie you use for your SSO bound to the exact browser or something like that, it will not work either. So ... what I wanted to say: we are always open for PR :) Or if you have an idea of how we can add something that could partly fix it so we don't need to wait till late this year, thats also good, maybe we could try do something together.

**Comment by soulgalore** [comment]
so I thought about this last night and opening up for running the WPT script "language" wouldn't be so much work plus I think it would help a lot of people. I will start working on it this weekend, and ping this thread when I have a branch ready, would be great if someone could help me testing it. I'll update the thread with info of the implementation so you guys can give feedback.

**Comment by Vandrix** [comment]
Very nice :-) I really need to setCookies :-) :-)

**Comment by soulgalore** [comment]
I will fix a small addon following @cgoldberg example later for sitespeed.io later. So for WPT, I guess something like this will do (just following one of Pats examples):
<pre>
logData	0
// bring up the login screen
navigate	http://webmail.aol.com
// log in
setValue	name=loginId	someuser@aol.com
setValue	name=password	somepassword
submitForm	name=AOLLoginForm
logData	1
navigate {{{URL}}}
</pre>

Meaning you will pass a script and for each run the {{{URL}}} will be replaced. That will do it right?

**Comment by lyneld** [comment]
@soulgalore that should do it. I'll be happy to help test it out.

**Comment by soulgalore** [comment]
@lyneld great! it's in master now, so check-out and you can run it.  https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting.  Every occurrence of {{{URL}}} in your script will be replaced with the URL that is actually going to be tested. And you have it as a plain text (utf-8) and feed it with <code>--wptScript filename</code>

**Comment by soulgalore** [comment]
releasing it in a couple of mintes ....

**Comment by akashk92** [comment]
@cgoldberg 
I am getting following response:
`Traceback (most recent call last):
  File "edx-sitespeed.py", line 80, in <module>
    args.email, args.password, args.base_url, auth_user=args.auth_user, auth_pass=args.auth_pass)
  File "edx-sitespeed.py", line 42, in login
    csrf = r.cookies['csrftoken']
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 327, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 398, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

if its ok, then where do I does it create cookie.json file?

**Comment by cgoldberg** [comment]
> if its ok, then where do I does it create cookie.json file?

It raised an exception, so it did not create the file.

I have no idea what the contents of your script are or what the site you are running it against uses for cookies... so I can't help you at all.  good luck.

**Comment by akashk92** [comment]
@cgoldberg 
I am using following script
`https://github.com/edx/edx-sitespeed`

and running site on local
