### ISSUE TITLE
Test Pages having '&' in the URL

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#624]
How can i test the urls which is having '&' and ',' in the url  just like below ? Do we need to escape characters or some thing like that ?

http://www.exmp.com/shop/product/chanel-ID=1927746&test=312,362

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
if you feed the URL from the command line on Linux, use ": 
<code>sitespeed.io -u "http://www.exmp.com/shop/product/chanel-ID=1927746&test=312,362"</code>

If you feed from a file, it should just work.

**Comment by badrinathvm** [comment]
How to accomplish the same in windows cmd.exe ?

I am using commands in "Execute Shell" Section in jenkins as shown in the below attachment , every time i face below error 

Jenkins screens hot 

![screen shot 2015-03-27 at 12 41 19 pm](https://cloud.githubusercontent.com/assets/1479179/6875734/75a922b2-d47e-11e4-8d6f-f9ccabb52ee0.png)

![screen shot 2015-03-27 at 12 40 46 pm](https://cloud.githubusercontent.com/assets/1479179/6875726/6355cbf6-d47e-11e4-8de5-e25e5f7477fe.png)

**Comment by soulgalore** [comment]
I think it look likes the URL is ok right, but you get a 401 response for the server. Does your server running Jenkins have access to that URL?

Best
Peter

**Comment by badrinathvm** [comment]
Yes URL is correct, i am passing the urls in "Execute Shell" section of Jenkins.

**Comment by badrinathvm** [comment]
![screen shot 2015-03-27 at 2 05 16 pm](https://cloud.githubusercontent.com/assets/1479179/6877007/3226b71e-d48a-11e4-95b6-f52f26695da4.png)

**Comment by tobli** [comment]
@badrinathvm - in the screen shot above you are not putting quotes around the url, as @soulgalore shows in an earlier comment. Please do that.

**Comment by badrinathvm** [comment]
Works with code , Thanks a ton, Closing the issue
