### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE while running Google Page Speed in Jenkins

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#626]
How can i resolve the issue of  "UNABLE_TO_VERIFY_LEAF_SIGNATURE' while jobs are running in jenkins ?

tried below options 

npm config set strict-ssl false 

changed to new Google api key , but still it dint work.. Any help will be appreciated.

Attached screen shot 

![screen shot 2015-03-28 at 7 22 10 pm](https://cloud.githubusercontent.com/assets/1479179/6883860/ec5033ae-d57f-11e4-8467-fe27d96b5061.png)

**Comment by soulgalore** [comment]
So you run against a URL that is accessible from the outside world right? GSPI runs as a service and need to be able to access it,

**Comment by soulgalore** [comment]
Hey @badrinathvm ,
did you get this to work? If you have problem, please re-open!
