### ISSUE TITLE
ECONNREFUSED connect ECONNREFUSED when trying to execute on Safari browser.

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#627]
Facing ECONNREFUSED connect ECONNREFUSED when trying to execute on Safari browser.

I have installed safari browser extension as mentioned int he documentation. below are the logs

error: ECONNREFUSED connect ECONNREFUSED
error: Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:30:31
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/browsertime.js:164:14
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:54:5
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:151:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:615:34
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:69:16
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:151:21
info: Stopping proxy

**Comment by badrinathvm** [comment]
![screen shot 2015-03-29 at 1 02 41 am](https://cloud.githubusercontent.com/assets/1479179/6884616/5b09c046-d5b0-11e4-8105-265720d27635.png)

**Comment by badrinathvm** [comment]
![screen shot 2015-03-29 at 1 34 22 am](https://cloud.githubusercontent.com/assets/1479179/6884717/9e05bd98-d5b3-11e4-9ab8-681fde063b34.png)

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
it seems like the URL is not accessable from the computer where you run sitespeed.io? I'll check that we handle the error in a better way later, but for you to get it to work, make sure you have access (and run Safari 8).

Best
Peter

**Comment by badrinathvm** [comment]
I am having Safari 8.0.3 , the request are failing even for google.com  :( below are screens hots , Do i need to update sitespeed.io ?

![screen shot 2015-03-29 at 10 53 33 am](https://cloud.githubusercontent.com/assets/1479179/6886867/b9f03008-d601-11e4-90d8-5afa927df7c3.png)

**Comment by soulgalore** [comment]
No the version is fine. Have you installed the SafariDriver extension - SafariDriver.safariextz (more info here) 

http://www.sitespeed.io/documentation/browsers/#safari

best
Peter

**Comment by badrinathvm** [comment]
Yes i have installed.  I have site speed 3.1.5 , do i need to update that ?
![screen shot 2015-03-29 at 1 49 24 pm](https://cloud.githubusercontent.com/assets/1479179/6887632/4cff4088-d61a-11e4-843f-59f37a7d74cd.png)
 the extension as mentioned in the documentation.

**Comment by soulgalore** [comment]
yes sorry, you need at least 3.2 so if you can upgrade that will do it. the older versions need you to run the selenium jar yourself, but with 3.2 or later it will work out of the box.

**Comment by badrinathvm** [comment]
Let me install version 3.2 now and try it ..

**Comment by badrinathvm** [comment]
How can i update to 3.2 ?  just by executing below command rt ? 
npm install sitespeed.io

**Comment by soulgalore** [comment]
Hi again,
you need to add the g to install it globally:
<pre>npm install sitespeed.io -g </pre>

**Comment by badrinathvm** [comment]
Perfect it works like awesome. Thanks a ton.. !
