### ISSUE TITLE
Safari browser plugin for site speed jenkins plugin.

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#628]
Do we have option in drop down for Safari browser for jenkins plugin ?
![screen shot 2015-03-29 at 2 42 47 pm](https://cloud.githubusercontent.com/assets/1479179/6887889/c226101a-d621-11e4-9d16-16090d4bb4fd.png)

**Comment by soulgalore** [comment]
no not right now, I need to add that.

**Comment by badrinathvm** [comment]
Any time sooner can be available ?

**Comment by badrinathvm** [comment]
Will be helpful if it is available or let us know the steps to accomplish this ..!

**Comment by soulgalore** [comment]
hey again,
run git pull on the the jenkins project, rebuild and add it to jenkins and it should be there now. please let me know if it worked out for you.

best
peter

**Comment by badrinathvm** [comment]
Executed maven on jenkins git hub project , Now able to see the Safari browser in drop down.
![screen shot 2015-03-30 at 11 12 23 am](https://cloud.githubusercontent.com/assets/1479179/6903222/b2b58dd4-d6cd-11e4-8b0e-e8562ad7620c.png)

**Comment by badrinathvm** [comment]
Closing the issue
