### ISSUE TITLE
HTTPS authentification ?

### ISSUE THREAD

**Issue by Johaann** [sitespeedio/sitespeed.io#629]
Hello,

I use Sitespeed.io and it is very useful.

I would like to know if is it possible to do a HTTPS authentication with the tool ? In fact, i can check only the login page of my website... 
Have you got any ideas to monitor the pages behind a HTTPS authentication ?

Best regards,

**Comment by soulgalore** [comment]
Hi @Johaann ,
great that you like sitespeed.io :)

Ok, so I know people add one step themselves when running sitespeed to login to sites (there's no built in support today but it would be cool to have it). You need to create a script that logins to your site, takes the session cookie and add it as a request header using <code>--requestHeaders</code>. 

I can try to help you if you have problem, drop me an email peter [at] soulgalore [dot] com.

Best
Peter

**Comment by Johaann** [comment]
Ok, i will try that. Thanks for you quick answer :)

Best regards,
Johann

**Comment by cgoldberg** [comment]
> You need to create a script that logins to your site,
> takes the session cookie and add it as a request 
> header using --requestHeaders. 

can you show example syntax for this?
say for example I already have a valid session cookie for domain: foo.com , named "sessionid" with a value of "ec831015d39603e92c4530613c2812d3".  I want to pass it in the request header to a single page test that hits foo.com...

what exactly would I pass in for --requestHeaders?

any help is appreciated.

regards.
-Corey

**Comment by soulgalore** [comment]
Hi @cgoldberg ,
ah sorry that it's unclear, I will do a step by step guide tomorrow asap.
Best
Peter

**Comment by cgoldberg** [comment]
@soulgalore thanks!
that would be awesome.

btw, are your docs in git?
tag me on a doc PR if you want me to have a look.

**Comment by soulgalore** [comment]
yes they are here: 
https://github.com/sitespeedio/doc.sitespeed.io
see if I find the time tonight. Can try to do a simple explanation now:

Depending how your site is generating the cookie (like do you have a unique identifier someway tied to the cookie) this can work:
Login using chrome, and check dev tools to see the cookie set by your site. Then create a file (cookie.json) that looks something like:
<pre>
{
"Cookie":"PASTE_IN_ALL_COOKIE_VALUES_HERE_AND_ADD_\backslash_IF_YOU_HAVE_QUTATION:MARKS"
}
</pre>
Then run: <code>sitespeed.io -u http://www.example.com --requestHeaders cookie.json</code>

Yep, think it is something like that.

**Comment by cgoldberg** [comment]
great.. I'll give it a try today!

**Comment by cgoldberg** [comment]
got it working.  Many thanks.

**Comment by soulgalore** [comment]
closing this now and reference to the coming scripting #688

**Comment by jeffersd** [comment]
Hello, I'd like additional clarification on the syntax of the json file. If there are multiple cookies, do you put all the values together in one string? If so, does order matter, do you separate them somehow? Or do you list every cookie in the json file by name and value? Additionally, what about cookies that are specific to the session?

**Comment by soulgalore** [comment]
hello @jeffersd ,
all in one. I think it's easiest to just check how the cookies are delivered for the site you want to test. Using Chrome, open Developer Tools and turn on the network recording and access the URL. Then check the headers and you will see the Cookie headers, copy and paste that.

About specific to the session: It depends. If it's just a session cookie and not specific to bound to your browser version, then it will work fine to just include it and run with sitespeed.io. 

Best
Peter

**Comment by jeffersd** [comment]
I got it to work. Thank you very much.

**Comment by shazz2103** [comment]
Hey @soulgalore 
Is that the right syntax of cookie.json file?
{
"Cookie": "anonymousUserId = d09afacf1dbcf55179ad;JSESSIONID=19vgvnduw248gq0itb0sbkbmi"
}
 
i am getting "not a valid json header string" error when i use that in --requestHeaders

**Comment by soulgalore** [comment]
Hey @shazz2103 
sorry for not getting back sooner. Tested locally and it works for me, I run it:
<pre>--requestHeaders cookie.json -u http://www.sitespeed.io -b chrome -n 1 -d 0</pre>

Do you feed with a file or just the JSON?
Best
Peter
