### ISSUE TITLE
Cannot read property 'forEach' of undefinedTypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#630]
Facing error as mentioned in below screenshot , Any pointers will help

![screen shot 2015-03-30 at 11 46 15 am](https://cloud.githubusercontent.com/assets/1479179/6903934/54387096-d6d2-11e4-9866-bd36bf62e282.png)

**Comment by badrinathvm** [comment]
Works when i run from command Line , but fails when executed via plugin from jenkins

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
to help out I need to have info on how you run and exact version so I can try to reproduce.

Best
Peter

**Comment by badrinathvm** [comment]
This issue is happening after me replacing old sitespeed.io jenkins plugin with new one.

**Comment by badrinathvm** [comment]
More details : 

Version :  sitespeed.io: '3.2.3'  

SiteSpeed : 1.0 - beta8

I suspect latest version of site speed is not compatible with Jenkins plugin.

**Comment by badrinathvm** [comment]
I found out the issue , it is happening when i set custom "budget.json"

try running below command

sitespeed.io -u http://www.sitespeed.io --budget budget.json -b chrome -n 3 -d 0

below is the error 

![screen shot 2015-03-31 at 3 03 47 pm](https://cloud.githubusercontent.com/assets/1479179/6930322/0e57f7f0-d7b7-11e4-8c25-55a70c34e3e0.png)

**Comment by badrinathvm** [comment]
Failing when we use --budget in command.

**Comment by soulgalore** [comment]
yes could you please supply the budget.json file and I can have a look to see if it is wrong in the config or a bug :)

**Comment by badrinathvm** [comment]
sure , below are the contents of the budget.json 

{
"timings": 
   { "speedIndex": 10000 }
}



![screen shot 2015-04-01 at 8 01 06 am](https://cloud.githubusercontent.com/assets/1479179/6943794/26e139ec-d845-11e4-9eaf-1a133485ac14.png)
![screen shot 2015-04-01 at 8 01 06 am](https://cloud.githubusercontent.com/assets/1479179/6943802/32b10180-d845-11e4-9930-0117aa652a48.png)

**Comment by soulgalore** [comment]
yes looks like a bug, give me a couple of minutes

**Comment by badrinathvm** [comment]
Sure .. I would be very happy for solution.

**Comment by soulgalore** [comment]
hi @badrinathvm 
I've released 3.2.4 now where this is fixed, thanks for reporting!

best
peter
