### ISSUE TITLE
How to Change default Location when scheduling for FireFox and and Safari browsers with Web Page Test

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#631]
Here is the scenario,  

default location set is Dulles:Chrome, works fine if i run below command 

sitespeed.io -u "http://www1.macys.com/shop/product/mac-eye-shadow-0.05-oz?ID=106344" --wptHost www.webpagetest.org --wptKey XXXX -d 0 -n 10  -b firefox

It should be set to Dulles:FireFox

below are logs screen shot

![screen shot 2015-03-30 at 3 21 02 pm](https://cloud.githubusercontent.com/assets/1479179/6908178/482031d6-d6f0-11e4-8bb1-463445d7c143.png)

**Comment by badrinathvm** [comment]
How can i specify for the webpage test also to pick up "firefox" browser instead of Dulles:Chrome every time from command ?

**Comment by soulgalore** [comment]
checkout http://www.sitespeed.io/documentation/webpagetest/#configuration and use the <code>--wptConfig</code> and feed a JSON with your configuration.

**Comment by badrinathvm** [comment]
I tried with below command it is getting failed

sitespeed.io -u XXX -d 0 -n 3 -b firefox --gpsiKey XXXX --wptHost www.webpagetest.org --wptKey  XXXX --wptConfig {"location":"Dulles:Firefox"}

how should i pass --wptConfig details ??

**Comment by soulgalore** [comment]
Hi @badrinathvm 
it needs be a file like this: <code>--wptConfig yourFile.json</code>

Best
Peter

**Comment by badrinathvm** [comment]
Thank you , do i need to provide the path of the file ? just like below 

--wptConfig /Users/XXXX/.jenkins/jobs/Firefox_Job/workspace/webpage.json

or wat location should i place it if i dont need to provide path ?

**Comment by soulgalore** [comment]
yep a absolute path will do, did it work out for you?

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
