### ISSUE TITLE
npm install sitespeed.io will install v3.2.4 but with different content

### ISSUE THREAD

**Issue by yesman82** [sitespeedio/sitespeed.io#633]
When doing ```npm install sitespeed.io``` it will install the correct version of sitespeed.io (v3.2.4 according to package.json) but somehow with a different content.

I recognized because the postResult.json in the postTasks directory ruined my result.json. But GitHub it doesn't exist anymore.

When I take the content from ```node_modules\sitespeed.io``` and put it into the original sitespeed.io git repo there is a non-noteworthy diff in the package.json and the postResult.js is new to the git system.

I also tried cleaning my npm cache with no success.

There might have gone something wrong when registering with the npm system.

**Comment by soulgalore** [comment]
thanks for reporting, there was some code that slipped into 3.2.4 that shouldn't. Published 3.2.5 that works now.

Thanks again!
Peter
