### ISSUE TITLE
Installing older version of sitespeed.io

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#634]
When i try to execute it is installing older version of sitespeed.io  , command used is 

npm install  sitespeed.io -g 

Any other command needs to be executed to pick up the latest version ?

**Comment by badrinathvm** [comment]
![screen shot 2015-04-02 at 11 16 03 am](https://cloud.githubusercontent.com/assets/1479179/6970318/84afa3bc-d929-11e4-8100-b07e077157a7.png)

Please help , i had proper working version , it is not downloading the latest version

**Comment by soulgalore** [comment]
hmm you are doing it right: <pre>npm install sitespeed.io -g</pre>
What happens if you run: <pre>npm view sitespeed.io version</pre>

**Comment by tobli** [comment]
Also, please check your PATH variable, to see what version is actually run. "which sitespeed.io" can be used as well.

**Comment by badrinathvm** [comment]
I verified  npm view sitespeed.io version , it shows latest version , but when i excute command it shows 3.1.6  :(
![screen shot 2015-04-02 at 11 34 59 am](https://cloud.githubusercontent.com/assets/1479179/6970727/44c58458-d92c-11e4-83cf-33b85b678d31.png)

**Comment by soulgalore** [comment]
and did you try what @tobli wrote <pre>which sitespeed.io</pre>?

**Comment by badrinathvm** [comment]
@tobli solution worked. Thanks a ton. Closing the ticket
