### ISSUE TITLE
Splitting URLs from file to array not working (Windows)

### ISSUE THREAD

**Issue by yesman82** [sitespeedio/sitespeed.io#640]
**Problem/Reproduction:**
OS: Windows 7
I have a url.txt (created using sublime text 3 build 3083) containing several URLs

```
http://www.toptarif.de/
http://versicherung.toptarif.de/private-krankenversicherung/
http://www.toptarif.de/stromvergleich/
http://www.tarife.de/
```

When running sitespeed.io the following error occurs.
`node bin\sitespeed.js -f urls.txt -d 0 -n 1`

```
http://www.toptarif.de
http://versicherung.toptarif.de/private-krankenversicherung
http://www.toptarif.de/stromvergleich
http://www.tarife.de is not a valid url (you need to include the protocol)
Fix the URL(s) before you continue
```

**Reason**:
Method `getFileAsArray()` in `lib/util/fileHelpers.js` uses `require('os').EOL` to `String.prototype.split()` the file content into an array of URLs. This works great on output files but unfortunately does not work on input files. 
My file returns this string: `http://www.toptarif.de/\nhttp://versicherung.toptarif.de/private-krankenversicherung/\nhttp://www.toptarif.de/stromvergleich/\nhttp://www.tarife.de/`,
And require('os').EOL returns this: `\r\n`
My URL string doesn't contain this line separator :(

OS: 'win32 6.1.7601', Node.js: 'v0.12.0', sitespeed.io: '3.2.7'

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
