### ISSUE TITLE
Not all domains is sent to Graphite

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#643]
https://twitter.com/JrnVdb/status/587571201586946049/photo/1

ping @JeroenVdb

**Comment by JeroenVdb** [comment]
I've updated to 3.2.9 and still only 10 domains are send to Graphite hen I check with --verbose setting on.

Part of the output: http://pastebin.com/2CiBK1mD

**Comment by soulgalore** [comment]
thanks, yep then there's something else I'll continue to look.

**Comment by soulgalore** [comment]
yes, coding in the middle of the night didn't work out very well for me :)  ok, I've released 3.2.10, there was a bug where we limited the number of domains when generating the hotlist. Did a quick fix for this for now and will do something cleaner later.

**Comment by JeroenVdb** [comment]
Works now! Thanks!

![3rd party dashboard example](http://i.imgur.com/lhcXQPc.jpg?1)

**Comment by soulgalore** [comment]
ah lovely! do you have a nice way to draw the metrics difference between 1st/3rd?

**Comment by JeroenVdb** [comment]
This is currently my dashboard for 3rd party analysis. You can see how 3rd party dominance has grown since more as one domain is passed to Graphite :+1: 

![3rd party dashboard](https://drive.google.com/uc?export=view&id=0B7dLgckbARouVkNNdmZ6dThLSDA)

Screenshot url: https://docs.google.com/file/d/0B7dLgckbARouVkNNdmZ6dThLSDA/edit

**Comment by soulgalore** [comment]
looks lovely :) will and something similiar to the example dashboard this week and give you cred. thanks for sharing!

**Comment by soulgalore** [comment]
closing this. fyi: will rework the sizes before the release, lets see if we can make something that are more correct than is it the master.
