### ISSUE TITLE
More data about domains for 3rd party analysis

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#644]
Sitespeed.io provides (summary) timings and # of requests for each domain used on your website. I used this data to plot the difference between 1st party and 3rd party domain timings.

Example:
![3rd party dashboard example](http://i.imgur.com/lhcXQPc.jpg?1)

It would be nice if we had more data per domain like totalWeight, imageWeight, cssWeight, jsWeight, etc. so we can have more insight in 3rd party.

**Comment by soulgalore** [comment]
ah good idea @JeroenVdb ! I'll see if I can do something tonight or tomorrow.  Total size is easy, per type is some more work.

Best
Peter

**Comment by JeroenVdb** [comment]
Total size would be a nice begin!
I would like te calculate the (percentage) difference between content loaded from 1st and 3rd party domains.

Maybe we can think about passing first party urls to sitespeed.io (--firstparty jeroenvdb.be, jeroenvdb-img.be) and add these to the Graphite target url.
```
sitespeed.io.domains.firstparty.timings.*.median
sitespeed.io.domains.*.timings.*.median
```
But this may be overkill because you can filter them out when using exclude in Grafana.

**Comment by soulgalore** [comment]
yes lets see, I will push a release tomorrow with size and content type size per domain and start with the Grafana dashboard.
