### ISSUE TITLE
Not reading set location from budget file for Safari browser when executed with --wtpConfig 

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#647]
Hi , 

I have below Jenkins Job for Safari browser and below is my command for Execute Shell 

sitespeed.io -u ${URL} -d 0 -n 10 -b safari --wptHost www.webpagetest.org --wptKey XXXXX --gpsiKey XXXXX  --wtpConfig  /<location>/Safari.json

While executing web page test it is picking up location: Dulles:Chrome though i had set to Dulles:safari in Safari.json . 

Any other configuration change do i need to make ?

Below are screen shots 

![screen shot 2015-04-19 at 7 21 03 pm](https://cloud.githubusercontent.com/assets/1479179/7222738/03a9ccae-e6c9-11e4-9261-0c3e6fef664f.png)

![screen shot 2015-04-19 at 7 21 28 pm](https://cloud.githubusercontent.com/assets/1479179/7222748/2173945e-e6c9-11e4-87eb-4c1c5da759cd.png)

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
try having an absolute path to the Safari.json file, it seems now that it is not picked up.

Best
Peter

**Comment by soulgalore** [comment]
Hi @badrinathvm 
closing this now, please let me know if this is still an issue.
