### ISSUE TITLE
An issue appeared ran sitespeed.io with browsertime==0.9.4 but it's ok used browsertime==0.9.3

### ISSUE THREAD

**Issue by jubel-han** [sitespeedio/sitespeed.io#648]
sitespeed.io -f URLS
[32minfo[39m: OS: 'linux 3.19.1-x86_64-linode53', Node.js: 'v0.10.33', sitespeed.io: '3.2.7', PhantomJS: '1.9.8', java: '1.7.0_75', browsertime: '0.9.4'
[32minfo[39m: Will analyze 1 pages
...
[31merror[39m: The YSlow file was not created: /var/lib/jenkins/jobs/web-performance/workspace/285/URLS/2015-04-17-10-55-42/data/yslow/www.xxxx.com-xxxx-xx--yslow.json
[31merror[39m: Error running yslow for url 'http://www.xxxx.com/xxx/xxx/': { [Error: ENOENT, open '/var/lib/jenkins/jobs/web-performance/workspace/285/URLS/2015-04-17-10-55-42/data/yslow/www.xxxx.com-xxxx-xxxx--yslow.json']
  `errno: 34`,
  `code: 'ENOENT'`,

**Comment by soulgalore** [comment]
Hi @jubel-han ,
I don't think browsertime is the issue the error comes from running YSlow.  If you can upgrade to the latest sitespeed.io that would be great and then test again.

Best
Peter

**Comment by jubel-han** [comment]
@soulgalore  Thanks a lot, as you said, This issue has gone after upgrade sitespeed.io to latest version(3.3.3).

**Comment by soulgalore** [comment]
perfect
