### ISSUE TITLE
An issue appeared when I ran sitespeed.io with argument  of use custom yslow script. `-y yslow.js`

### ISSUE THREAD

**Issue by jubel-han** [sitespeedio/sitespeed.io#649]
jenkins@ci:/tmp$ pwd
/tmp
jenkins@ci:/tmp$ ls -l /tmp/site_speed/yslow.js 
-rwxr-xr-x 1 jenkins jenkins 418697 Apr 20 11:51 /tmp/site_speed/yslow.js
jenkins@ci:/tmp$ sitespeed.io -u http://www.sitespeed.io/ -y /tmp/site_speed/yslow.js 
info: OS: 'linux 3.19.1-x86_64-linode53', Node.js: 'v0.10.33', sitespeed.io: '3.2.10', PhantomJS: '1.9.8', java: '1.7.0_75', browsertime: '0.9.3'
info: Will crawl from start point http://www.sitespeed.io/ with crawl depth 1
info: Will analyze 14 pages
info: Running YSlow for http://www.sitespeed.io/ [phantomjs]
info: Running YSlow for http://www.sitespeed.io/documentation/graphs/ [phantomjs]
info: Running YSlow for http://www.sitespeed.io [phantomjs]
info: Running YSlow for http://www.sitespeed.io/logo/ [phantomjs]
info: Running YSlow for http://www.sitespeed.io/faq/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/documentation/graphs/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/graphs/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/release-notes/3.2/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/aboutus/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/example/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/faq/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/faq/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/documentation/performance-budget/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/logo/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/logo/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/documentation/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/release-notes/3.2/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/release-notes/3.2/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/documentation/rules-and-best-practices/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/aboutus/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/aboutus/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/documentation/installation/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/example/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/example/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/documentation/browsers/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/documentation/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Running YSlow for http://www.sitespeed.io/documentation/result/ [phantomjs]
error: Yslow output for 'http://www.sitespeed.io/documentation/performance-budget/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/performance-budget/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
error: Yslow output for 'http://www.sitespeed.io/documentation/rules-and-best-practices/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/rules-and-best-practices/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
error: Yslow output for 'http://www.sitespeed.io/documentation/installation/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/installation/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
error: Yslow output for 'http://www.sitespeed.io/documentation/browsers/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/browsers/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
error: Yslow output for 'http://www.sitespeed.io/documentation/result/' (stderr): Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'

error: Error running yslow for url 'http://www.sitespeed.io/documentation/result/': { [Error: Command failed: Can't open '/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js'
] killed: false, code: 255, signal: null }
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote results to /tmp/sitespeed-result/www.sitespeed.io/2015-04-20-11-59-15
info: The analyze took a few seconds (2 seconds)

**Comment by jubel-han** [comment]
Seems the It looks a wrong directory for `yslow.js` in `/usr/lib/node_modules/sitespeed.io/lib/tmp/site_speed/yslow.js` instead of `/tmp/site_speed/yslow.js

**Comment by tobli** [comment]
This should be fixed in the next upcoming Sitespeed release. Thanks for reporting!
