### ISSUE TITLE
Send size per asset to Graphite

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#650]
> why are the domain.requests/size/... only added to the summary? Wouldn't it be useful to also add them per page? Working with Grafana (or something alike) you actually would not need summary because you can do the calculations yourself if you'd like.
> @JeroenVdb 

yep I agree, lets change that.

**Comment by JeroenVdb** [comment]
To be clear: domains.timings.*, domains.size.* and domains.requests.* can now also be collected per-page by using:

<namespace>.<pageUrl>.requests.<assetUrl>.timings.{blocked, dns, ..., total}
<namespace>.<pageUrl>.requests.<assetUrl>.type.<assetType>.size
<namespace>.<pageUrl>.requests.*

Very nice!

**Comment by soulgalore** [comment]
yep exactly, thanks! need to have some time to test that I nailed everything, hopefully I will release it tomorrow.

**Comment by soulgalore** [comment]
well it happend today :)
