### ISSUE TITLE
Graphite key contains duplicate dots

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#654]
Hi @soulgalore 

I've upgraded sitespeed to 3.4.0 but now having some problems with the new Graphite structure:
protocol.hostname.pathname

There are duplicate dots in some graphite keys and because of that I can't find the data in Graphite to build a query with.

For example:

http.www.domainname.com..en.subpage.requests.

It's only with .http metrics (not .summary).

Thnx for checking!

**Comment by soulgalore** [comment]
ah thanks, I thought I fixed that before the release but I must have missed at least one place. can you please share the exact URL and the key(s) that went wrong and I will do a fix release asap, you got my email right.
Best
Peter

**Comment by soulgalore** [comment]
Did a quick fix with 3.4.1 but if you could please send me the exact problem I will fix it nicer tonight! 

Best
Peter

**Comment by soulgalore** [comment]
this is fixed
