### ISSUE TITLE
Any way to measure the time taken for java script file?

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#655]
Hi , 

Test URL which i am testing has around 51 javascript files, is there any way that we can get time taken for loading each js file in report ?

I see the list of js files in assest.html.

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
not displayed in the HTML, but you get a HAR file for each run that you can view in http://rafacesar.github.io/simplehar/ or if you send the metrics to Graphite, then the timings for each request is stored.

Best
Peter

**Comment by badrinathvm** [comment]
Is har generated by sitespeed ?i am not able to find that in results.

**Comment by soulgalore** [comment]
yep, as long as you test it with a browser <pre>-b chrome<pre>. you can find the HAR-file(s) in the generated data directory.

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
closing this one now, let me know if there's something thats unclear.
