### ISSUE TITLE
default browser results shows decompressed sizes instead of gzipcompressed sizes

### ISSUE THREAD

**Issue by jordo1138** [sitespeedio/sitespeed.io#658]
When using "sitespeed.io -u http://www.newegg.com -d 0" and the default browser the 'resources without gzip' is correct but the page/object sizes are all decompressed sizes
![decompressed](https://cloud.githubusercontent.com/assets/8525512/7326545/ef50755e-ea7a-11e4-9199-b3f545c02ba5.jpg)

"sitespeed.io -u http://www.newegg.com -d -b firefox" displays the gzip compressed sizes
![compressed](https://cloud.githubusercontent.com/assets/8525512/7326550/fa9b23c8-ea7a-11e4-979d-6d246b502d4a.jpg)

**Comment by soulgalore** [comment]
ah sorry I see, I didn't get the default browser part. ok so the problem is that if you don't specify a browser, we use phantomjs. So to get it right you need to add <pre>-b chrome</b> or <pre>-b firefox</pre> becasue phantomjs has a defect that it can't fetch the right size.

best
Peter

**Comment by jordo1138** [comment]
Got it thanks!
