### ISSUE TITLE
I Can't install SiteSpeed.io "NPM ERR! code 128"

### ISSUE THREAD

**Issue by darkterra** [sitespeedio/sitespeed.io#659]
Hello everyone , I need to install SiteSpeed.io for work , but I installation errors .
In the past I have used SiteSpeed.io, but I do not remember to have had the following errors :

>npm ERR! Windows_NT 6.1.7601
>npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "sitespeed.io"
>npm ERR! node v0.12.2
>npm ERR! npm  v2.7.4
>npm ERR! code 128

>npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\jeremy\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:joshuafcole/async-node-events.git C:\Users\jeremy\AppData\Roaming\npm-cache\_git-remotes\git-github-com-joshuafcole-async-node-events-git-cb099772
>npm ERR! Cloning into bare repository 'C:\Users\jeremy\AppData\Roaming\npm-cache\_git-remotes\git-github-com-joshuafcole-async-node-events-git-cb099772'...
>npm ERR! ssh: connect to host github.com port 22: Bad file number
>npm ERR! fatal: Could not read from remote repository.
>npm ERR!
>npm ERR! Please make sure you have the correct access rights
>npm ERR! and the repository exists.
>npm ERR!
>npm ERR!
>npm ERR! If you need help, you may report this error at:
>npm ERR!     <https://github.com/npm/npm/issues>

>npm ERR! Please include the following file with any support request:
>npm ERR!     C:\Users\jeremy\npm-debug.log

If necessary, I have the file "C:\Users\jeremy\npm-debug.log", but I do not know where to store it on GitHub.

**Comment by soulgalore** [comment]
hey @darkterra ,
hmm do you have git installed on your computer? we have a dependency today (that we soon will fix), that you need to have git.
Best

**Comment by soulgalore** [comment]
Else I would check if there's a newer version of npm, don't have the version numbers in my head right now. Test install git (if missing) and upgrade npm.

Best
Peter

**Comment by darkterra** [comment]
Thank you for your quick response Peter Soulgalore !

Yes, sorry I forgot to mention but, I intalled Git, rather" GitHub for Windows" .
So, I add to the env var "Path" :
>C:\Users\jeremy\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin

So, I try to git (to see if himself could clone the repo) :
>git -c core.longpaths=true clone --template=C:\Users\jeremy\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:joshuafcole/async-node-events.git C:\Users\jeremy\AppData\Roaming\npm-cache_git-remotes\git-github-com-joshuafcole-async-node-events-git-cb099772

My npm version is : "2.7.4"

I'll try again after MAJ npm.
 
Wants you view the npm-debug files?

DarkTerra

**Comment by darkterra** [comment]
Hello,
Last night I tried on my home PC, (MAJ NPM to 2.8.4) and here are the mistakes I had (no npm -debug file) :

>C:\Users\Jérémy>npm install -g sitespeed.io
/

> slimerjs@0.9.2 install C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\slimerjs
> node install.js

>Download already available at C:\Users\JRMY~1\AppData\Local\Temp\slimerjs\slimerjs-0.9.2-win32.zip
Extracting zip contents
Copying extracted folder C:\Users\JRMY~1\AppData\Local\Temp\slimerjs\slimerjs-0.9.2-win32.zip-extract-1430288714590\slimerjs-0.9.2 -> C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\slimerjs\lib\slimerWriting location.js file
Done. Slimerjs binary available at C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\slimerjs\lib\slimer\slimerjs.bat

> phantomjs@1.9.15 install C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\phantomjs
> node install.js

>Download already available at C:\Users\JRMY~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\JRMY~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1430288718794\phantomjs-1.9.8-windows -> C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\phantomjs\lib\phantom\phantomjs.exe
npm WARN deprecated jws@0.0.2: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated tap-consumer@0.0.1: This module is not supported. Please use 'tap' instead.
npm WARN installMany tap-consumer was bundled with tap@0.3.3, but bundled package wasn't found in unpacked tree
npm WARN deprecated tap-results@0.0.2: This module is not supported. Please use 'tap' instead.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1183:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:485:12)
npm WARN addRemoteGit  git+https://github.com/joshuafcole/async-node-events.git# d32411f1f4 resetting remote C:\Users\Jérémy\AppData\Roaming\npm-cache\_git-remotes\https-github-com-joshuafcole-async-node-events-git-2b5617ae because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
|
> utf-8-validate@1.0.1 install C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


>C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Jérémy\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Jérémy\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Users\Jérémy\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Jérémy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> bufferutil@1.0.1 install C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


>C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Jérémy\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Jérémy\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Users\Jérémy\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Jérémy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
npm WARN optional dep failed, continuing bufferutil@1.0.1
C:\Users\Jérémy\AppData\Roaming\npm\sitespeed.io -> C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io\bin\sitespeed.jssitespeed.io@3.5.0 C:\Users\Jérémy\AppData\Roaming\npm\node_modules\sitespeed.io

├── whereis@0.4.0
├── valid-url@1.0.9
├── fast-stats@0.0.2
├── async@0.9.0
├── cross-spawn@0.2.6 (lru-cache@2.6.2)
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
├── winston@0.9.0 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, p
kginfo@0.3.0, colors@1.0.3)
├── tape@3.5.0 (inherits@2.0.1, defined@0.0.0, resumer@0.0.0, deep-equal@0.2.2,
through@2.3.7, object-inspect@0.4.0, glob@3.2.11)
├── fs-extra@0.16.3 (jsonfile@2.0.0, graceful-fs@3.0.6, rimraf@2.3.2)
├── request@2.55.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0,
forever-agent@0.6.1, stringstream@0.0.4, form-data@0.2.0, oauth-sign@0.6.0, tunn
el-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7
, mime-types@2.0.10, http-signature@0.10.1, bl@0.9.4, tough-cookie@1.1.0, hawk@2
.3.1, har-validator@1.6.1)
├── moment@2.9.0
├── html-minifier@0.7.0 (relateurl@0.2.6, change-case@2.2.0, cli@0.6.6, clean-cs
s@3.0.10, uglify-js@2.4.20)
├── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)
├── slimerjs@0.9.2 (which@1.0.9, rimraf@2.2.8, kew@0.1.7, ncp@0.4.2, mkdirp@0.3.
5, adm-zip@0.2.1, npmconf@0.0.24)
├── xmlbuilder@2.6.1 (lodash@3.3.1)
├── phantomjs@1.9.15 (which@1.0.9, progress@1.1.8, kew@0.4.0, request-progress@0
.3.1, adm-zip@0.4.4, npmconf@2.0.9, request@2.42.0)
├── webpagetest@0.2.5 (commander@2.3.0, entities@1.1.1, csv@0.4.2, xml2js@0.4.8,
 mocha@1.21.5)
├── gpagespeed@1.0.0 (minimist@1.1.1, googleapis@1.1.5)
└── browsertime@0.9.4 (browsermob-proxy-api@0.1.4, getport@0.1.0, minimist@1.1.1
, async-node-events@0.0.6, selenium-webdriver@2.45.1)


I thought I understood from the above errors that there is a dependence on " Python" ?
>gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.

DarkTerra

**Comment by darkterra** [comment]
Ok, sorry if I Flood, but I wanted to share my progress.

After initially installed the latest version of Python (3.4.3) for windows, added to the "Path" var and relaunched the command "npm install sitespeed.io -g", I get an error message said that the version of "Python" is not compatible and that a version> = 2.5.0 && <3.0.0.

So I downloaded the version 2.7.x yet revived the command "npm install sitespeed.io -g".
Here is the result:
![capture-intall-sitespeed io-3](https://cloud.githubusercontent.com/assets/7060696/7402448/34758778-eecc-11e4-9eab-27f3ce9f628b.PNG)

If I understand correctly, it is impossible to load the Visual C ++ Component "VCBuild.exe"

DarkTerra

**Comment by cgoldberg** [comment]
@darkterra do you have MS VisualStudio installed?

this thread may be of some help: http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012

**Comment by darkterra** [comment]
Hello @cgoldberg  , thank you for your answer , I suddenly retry the complete installation on my computer Proffessional (which Visual Studio installed). And this time , with all the prerequisites, I successful to go through the installation.

I do not want "type on the fingers" (French expression, I do not know how to translate it into English) dévellopeur of this great tool, but it is not normal for an NPM module to encounter this kind of difficulty.

However , now that SiteSpeed.io is installed, it can not find the website of my company intranet :
![capture-intall-sitespeed io-4](https://cloud.githubusercontent.com/assets/7060696/7414295/09fdd5dc-ef52-11e4-8de1-52ce3bc88eca.PNG)

**Comment by cgoldberg** [comment]
>  it is not normal for an NPM module to encounter this kind of difficulty.

It's a breeze to install on Linux.  I'd blame Windows for your troubles.

**Comment by darkterra** [comment]
Hi @cgoldberg ,

It is true that the first time I used SiteSpeed.io (there are several months) I installed it on a Linux computer . And I understand that on Windows it works less well, or more difficult to install. But I've already installed several modules NPM on Windows without having one difficulty or installation or use.

Attention no way I attack or denigrate the hard work that is done on this beautiful module I just said it's a shame that the installation is not easy .

If anyone knows why I can contact with my browser (Chrome) the intranet , but not with SiteSpeed.io (immage in my previous méssage) ?
