### ISSUE TITLE
Question : Recommended storage-schema for Graphite/Carbon conf

### ISSUE THREAD

**Issue by darraghgrace** [sitespeedio/sitespeed.io#660]
Hi,
I've been experimenting on the best settings for sending wpt timings from sitespeed.io to Graphite/Graphana. I was wondering if you guys had suggested storage-schemas for Graphite assuming I will be running tests against 5 sites maybe every 3/4 hours? (using wpt metrics)
Cool tool btw, very much appreciated!

**Comment by soulgalore** [comment]
Hi @darraghgrace ,
have you had a look at:
https://github.com/sitespeedio/docker-graphite-statsd/blob/master/conf/graphite/storage-schemas.conf
https://github.com/sitespeedio/docker-graphite-statsd/blob/master/conf/graphite/storage-aggregation.conf

I think you could set a high (hours) on your retentions and then make sure that the aggregation with a  xFileFactor 0.0 for the metrics, something like:
<pre>
[default_average]
pattern = .*
xFilesFactor = 0.0
aggregationMethod = average
</pre>
I think that should be ok (just on the top of my head), else I always look into the Graphite docs when setting it up :)

Or have you seen any problem or any specific that don't work?

Best
Peter

**Comment by darraghgrace** [comment]
Thanks @soulgalore . Have it running nicely now. Saw the new documentation on setting up the Graphs from a few days ago which are really helpful.
