### ISSUE TITLE
SiteSpeed.io does not work (Window)

### ISSUE THREAD

**Issue by darkterra** [sitespeedio/sitespeed.io#661]
Hello everyone, After Having had problems with Windows Setup on (#659), it can not find the website of my company intranet :
![capture-intall-sitespeed io-4](https://cloud.githubusercontent.com/assets/7060696/7414736/db4b8434-ef54-11e4-9981-a476df7180bc.PNG)

I also try a site a bit more experienced ^^ :
![capture-intall-sitespeed io-5](https://cloud.githubusercontent.com/assets/7060696/7457266/7591784e-f28b-11e4-8cab-3c8af65d4696.PNG)

And other options :
![capture-intall-sitespeed io-6](https://cloud.githubusercontent.com/assets/7060696/7457287/9d77b26a-f28b-11e4-9121-9a21be8b6296.PNG)
![capture-intall-sitespeed io-7](https://cloud.githubusercontent.com/assets/7060696/7457294/b1b2f91a-f28b-11e4-9956-536194c684cf.PNG)

But I still can not operate SiteSpeed.io , I missed something?

**Comment by tobli** [comment]
Hi!
I'm guessing you have a corporate firewall that you need to authenticate to. Http error 401 means Unauthorized. Also the inability to access external urls such as Google could very well be indicating the same thing. Do you have any proxy server set up in your web browser? If so you'll need to tell sitespeed.io to use the same proxy, via the -p option.

**Comment by darkterra** [comment]
Hi @tobli, you is right, there is a good corporate proxy, so if you look at the last picture of my first message, there is the "--proxy" which according to the doc is the same something that the option "-p"

**Comment by soulgalore** [comment]
Hi @darkterra ,
sorry for answering so late, have you tried configure the proxy like:
http://USERNAME:PASSWORD@PROXYIP:PROXYPORT

Best
Peter

**Comment by darkterra** [comment]
Hi @soulgalore,

For obvious safety reasons, I am forced to hide some part of the command line , but yes I did several test on the images above and show what you offer me @soulgalore. Juse in case , I made a test again :
![capture-intall-sitespeed io-11](https://cloud.githubusercontent.com/assets/7060696/7513164/5538bae8-f4b2-11e4-8085-fdf368e58062.PNG)

**Comment by darkterra** [comment]
An idea ?

**Comment by tobli** [comment]
Hi!
Seems like a bug in the handling of proxy authentication. We'll need to investigate this one closer.

**Comment by Jxck** [comment]
+1

**Comment by hansdekker** [comment]
+1

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
