### ISSUE TITLE
Query - Data sent to Graphite

### ISSUE THREAD

**Issue by darraghgrace** [sitespeedio/sitespeed.io#664]
Hi, 

I have a query about what data gets sent to Graphite. I am running sitespeed against 4 urls using following command
sitespeed.io.cmd -f urls.txt --screenshot --wptHost xx.xxx.xxx.xxx --wptKey xxx --wptConfig webpagetest_amazon.json -d 0 --noYslow --budget Budget.json --graphiteHost xxxxxxxx --graphitePort xxxx --graphiteNamespace xxxxx --resultBaseDir %WORKSPACE%\%BUILD_NUMBER% --junit>junit.xml

For the time being I am only interested in getting metrics from WebPageTest. Hence --noYslow.

Of the 4 urls, 3 begin with same domain, the 4th is a different domain name i.e. 
www.domain.com/X
www.domain.com/Y
www.domain.com/Z
www.anotherdomain.com

When I look at the data added to Graphite I also get a Summary node for - www.domain.com
![image](https://cloud.githubusercontent.com/assets/2386816/7536201/aebb3af4-f585-11e4-8ab8-b81f3cb8820f.png)

I was wondering what this summary information represents? Is it an aggregrated summary of all the metrics for 3 of the urls, www.domain.com/X,Y,Z . Is it an aggregrated summary of the 3 urls of same domain plus the www.anotherdomain.com?
Final question, is the summary information coming from WebPageTest?

Once again, thank for for the great work, we are getting some really nice graphs from sitespeed!

**Comment by soulgalore** [comment]
Hi Darragh,
ok, I will try to explain. So the implementation right now is really stupid and not any smart logic. If you feed it with a file using <code>-f</code> it will use the first domain from the first URL and summarise every data under that, so in your example, it will be wrong.

So what can we do? Well, if you split the url:s to two files, one containing all urls for one domain and the other the last url and feed it with the site parameter, something like <code>--sites url.txt --sites url2.txt</code> then you will have two summaries in graphite, one for each domain.

yes, if you run without the -no-yslow the data is generated from WPT (but you will miss out on some data right now, that could be done cleaner).

thanks for the kind words :)

Best
Peter

**Comment by darraghgrace** [comment]
Hi Peter,

Thanks as always for the quick reply. 
I want to treat each of the 4 urls as a kind of 'separate' domain. So for the 3 pages under the same domain, I don't want a summary of all 3, i would like a summary for each individually. 
Instead of getting a summary for www.domain.com
I want to get a summary for 
www.domain.com/X
and for 
www.domain.com/Y
etc. 
So I guess I would need create separate jobs and send them to 4 different Graphite namespaces?

Best Regards
Darragh

**Comment by soulgalore** [comment]
yes exactly, that is the only way do it today.
best
Peter

**Comment by darraghgrace** [comment]
thanks Peter!
