### ISSUE TITLE
Add check for X-Cache header in CDN check 

### ISSUE THREAD

**Issue by atiro** [sitespeedio/sitespeed.io#666]
Our CDN is using a X-Cache header (X-Cache: HIT from [CDNname]) which we would like to use to test if a request was served by a CDN. It's not one of the headers yslow is checking though, perhaps it could be added ?

**Comment by soulgalore** [comment]
Hi @atiro ,
sorry for the late answer. You can write your own rules (http://www.sitespeed.io/documentation/developers/#add-your-own-rules) and run it, then you can add your custom test(s). 

I can help you in the right direction if the docs don't give you the full picture.

Best
Peter

**Comment by atiro** [comment]
Hi Peter,

Many thanks, will dig into that (I was being lazy and using the docker version). Surprised me that yslow rules don't already look for X-Cache though as it's a fairly common CDN header.

regards,

Richard

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
