### ISSUE TITLE
Proxy with Authentication doesn't work

### ISSUE THREAD

**Issue by Jxck** [sitespeedio/sitespeed.io#667]
Hi

I'm using sitespeed.io behind proxy.
it works with no auth proxy, but not work in proxy with user/pass like this.
`user:pass@proxy.com:8080`

it seems that code here ignores user/pass from arguments isn't it ?
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/crawler/crawler.js#L37

any suggestion for work around or fixing are helpful.

thanks

**Comment by darkterra** [comment]
Hey @Jxck,

I have the same problem, see the issue #661 ^^.

**Comment by soulgalore** [comment]
Hi @Jxck & @darkterra ,
yep and the code in the crawler doesn't handle login/pw. @tobli did a quick check and we need to update the httpclient version we use in the crawler, but I need to test to be able to fix it. Got a lot on my 2do for the coming weeks but will try to squeeze it in. If we do a fix, can you test from the repository, so you can verify before we do a release, that would help us!

Best
Peter

**Comment by darkterra** [comment]
Hi @soulgalore & @tobli Thank you for taking time to fix the problem Auth.

With pleasure I test version when you will Update the repository.
So I close my issue ? Because it has not quite the right name, and above all it is duplicate thereof.
Last little thing, Auth Kerberos/NTLM are or will be possible?

**Comment by hansdekker** [comment]
Any update on this?

**Comment by soulgalore** [comment]
@hansdekker no sorry, I've totally missed this, sorry. I'm very happy to accept PR for this :=)

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by mrtypn** [comment]
By using several tricks i have successfully made all major authentication works (Basic , NTLM, Certificate and Negotiate) , I have done this for Chrome only.
1) For NTLM, Basic : we need to write a small browser extension , listen to authentication and and provide the password, to load the extension we use the command option: --browser.args "load-extension=/path_to_your_ext"
2) for Certificate
- we need to load certificate using cerutil and pk12util command to load certificate
3) for kerberos 
 - we need to install krb5-user package
 - when we launch the docker we need to run: echo password | kinit username 
for certificate and kerberos to work, we need to modify the chrome policy 
the chrome policy is located in /etc/opt/chrome/policies/managed/policy.json
