### ISSUE TITLE
Speedgun.io down?

### ISSUE THREAD

**Issue by dandv** [sitespeedio/sitespeed.io#668]
http://www.sitespeed.io/ links in the footer to speedgun.io, which at the moment [is down](http://isup.me/speedgun.io).

**Comment by soulgalore** [comment]
cool, I've tweeted @wesleyhales who runs it.

**Comment by wesleyhales** [comment]
Thanks! I've created an issue to track this https://github.com/wesleyhales/speedgun/issues/31
