### ISSUE TITLE
HTML reports: Timings not generated on Pages table 

### ISSUE THREAD

**Issue by bbenichou** [sitespeedio/sitespeed.io#669]
Hi,

First things first thanks for your great work, sitespeed.io is so helpful!
I'm using sitespeed.io with a webpagetest API key on Windows via cmd.exe to produce HTML reports.

OS: Windows 7
url analysed: http://www.bakerross.co.uk
Description:  I try to configure the columns on the pages page to get some timings values on one table.
Basically I use the following command line to get the values: 

sitespeed.io.cmd -u http://www.bakerross.co.uk -d 0 --columns timings.pageDownloadTime.median,timings.domContentLoadedTime.median,timings.pageLoadTime.median,timings.firstPaint.median,timings.TTFB.median,timings.Render.median  --wptHost www.webpagetest.org --wptKey MYAPIKEY

I don't get any no errors at the execution, but the values are always 0 on the pages page
![emptyvaluesonpages](https://cloud.githubusercontent.com/assets/12528382/7725634/5059f0e0-fef4-11e4-8b8a-883bdfe3f95e.jpg)
Even though on the detailed summary the same values are not 0: 
![valuesokondetailedsummary](https://cloud.githubusercontent.com/assets/12528382/7725716/24204e74-fef5-11e4-9587-b329ae90df9e.jpg)

Any idea what could be the cause?

Also how can I get the first view and the repeat view for each timings on the pages page ?

Thanks,
Ben

**Comment by soulgalore** [comment]
Hi Ben,
thanks for the kind words :)

The configuration for the columns is messy right now, sorry for that. First, we pick up the following metrics for WPT:  <code>'SpeedIndex', 'firstPaint', 'render', 'TTFB', 'visualComplete', 'domContentLoadedEventEnd', 'loadTime'</code>
so these can be displayed. 

But the keys from WPT is created like this (the keys that you use when you configure the columns): wpt[location][browser][connectivity][view][timing]. Ehh, let me add some documentation tomorrow about it, it is so complicated that I need to test it :(

Let me get back tomorrow night when I've tested it.

Best
Peter

**Comment by bbenichou** [comment]
Hi Peter,

Thanks for the feedback.

I would be happy to help if you need me to run some tests.

Best,
Ben

**Comment by soulgalore** [comment]
Hi Ben,
ok, tested now, you can get the data but the column names will be quite long and mess up the page, I'll add an issue for that. 

It works as I wrote, so when configuring columns the exact name from the WPT API is used:
'SpeedIndex', 'firstPaint', 'render', 'TTFB', 'visualComplete', 'domContentLoadedEventEnd', 'loadTime' (SpeedIndex, not speedIndex etc).

So if you want to show firstView and repeatView speedIndex (it's taken from the median run) you add it like this:
<pre>--columns wpt.dulles.chrome.cable.firstView.SpeedIndex,wpt.dulles.chrome.cable.repeatView.SpeedIndex </pre>

Following the pattern of wpt[location][browser][connectivity][view][timing].

I'll see when I can find the time to make the whole column concept cleaner :)

Best
Peter

**Comment by bbenichou** [comment]
Hi Peter,

Just tried following the pattern you gave and it's working fine!
The column are not too messed-up so it's doing the job pretty well for me.

Thanks a lot
Ben
