### ISSUE TITLE
Summary data not being created

### ISSUE THREAD

**Issue by danielsonjh** [sitespeedio/sitespeed.io#670]
Hi, I'm running Graphite in Docker with this command:
sudo docker run -d --name graphite -p 8080:80 -p 2003:2003 --restart="always" -v /data/graphite/storage/whisper:/opt/graphite/storage/whisper -v /etc/.htpasswd:/etc/nginx/.htpasswd sitespeedio/graphite

And when I run sitespeed.io with the command:
sudo docker run --privileged --rm sitespeedio/sitespeed.io sitespeed.io -u http://www.example.com -b firefox  --connection cable --graphiteHost 172.17.42.1 --seleniumServer http://127.0.0.1:4444/wd/hub

Graphite receives the data and it shows up in the 'summary' folder as well as the 'http' folder for example.com
But afterwards, when I tested with other sites the data only shows up in 'http/https' and not 'summary'.
I've tried removing the summary folder and running the commands again, and only the command with www.example.com recreates it.

Any ideas on how to resolve this issue?

Here's a screenshot to clarify what I mean with the folders:
![screenshot_052015_065532_pm](https://cloud.githubusercontent.com/assets/4494875/7737468/cb75c902-ff21-11e4-86a6-85f523c780b6.jpg)

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @danielsonjh ,
yes I think I know the problem. When you configure graphite you can choose how many "new" metrics that can be created at a time, it is a way of making sure that the server is not overloaded with work. Check out: 
http://www.sitespeed.io/faq/#i-dont-get-all-values-in-graphite

I've turned that down on the Graphite/docker version to get the dashboard site more stable. Easiest is to take a copy of the carbon.conf, change so you have <code>MAX_CREATES_PER_MINUTE = inf</code> and feed the carbon.conf to your container when you start it, something like this:
<pre>
-v /my/path/carbon.conf:/opt/graphite/conf/carbon.conf \
</pre>

I can change the default values and rebuild the container later this week.

Hope this helps
Best
Peter

**Comment by danielsonjh** [comment]
That solved the issue, thanks!
