### ISSUE TITLE
Add more connection types

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#672]
I really like what WPT is doing, would be cool to have mobile2g and edge at least.

**Comment by Vandrix** [comment]
Custom connection profile would be cool :-)

**Comment by soulgalore** [comment]
that is possible today by the btConfig parameter, I can show you late tonight or tomorrow :)

**Comment by Vandrix** [comment]
Show me! Think I missed it in de docs ;-)
Thnx.

**Comment by soulgalore** [comment]
Hey @Vandrix ,
I'll add it to the docs tomorrow, here's a sneak preview: You can make sitespeed.io configure whatever configuration you want by using the flag <code>--btConfig</code> pointing to a JSON file. For browsertime you have the following possible config: https://github.com/tobli/browsertime/blob/master/lib/cli.js

So for setting your own connection profile, create the file like this:
<pre>
{
 "connectionRaw" : {
    "downstreamKbps": $X,
    "upstreamKbps": $Y,
     "latency": $Z
  }
}
</pre>

Best
Peter

**Comment by Vandrix** [comment]
Hey @soulgalore,

Thnx! Very clear now.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
