### ISSUE TITLE
Not seeing many metrics in Graphite

### ISSUE THREAD

**Issue by lyneld** [sitespeedio/sitespeed.io#674]
It seems to work perfectly, except that I don't get too many metrics in Graphite. Which means Grafana doesn't have a lot of data to show either. I figure MAX_CREATES_PER_MINUTE = inf is the setting I'm looking for, but how to do I make this change if I'm using the docker containers?

Also, could it be another reason for me missing a lot of the timing metrics?

Appreciate any help I can get...Thanks!

**Comment by soulgalore** [comment]
Hi @lyneld ,
yep that's the one. You can feed the container with your own config file, check out the readme here: 
https://github.com/sitespeedio/docker-graphite-statsd

I will change the max create to inf as default in the docker container. Will rebuild the container now and it will be fixed in a couple of minutes, just pull the new version.

Best
Peter

**Comment by soulgalore** [comment]
You can check the status here, it will be the latest tag that will be updated:
https://registry.hub.docker.com/u/sitespeedio/graphite/builds_history/159892/

**Comment by lyneld** [comment]
@soulgalore You guys are amazing! Thank you for the super quick response. I'll try this out right away :)

**Comment by lyneld** [comment]
This works perfectly, thank you!

I have another quick question. Running sitespeed on multiple sites (2 sites, 3 links each), I got a script timeout on the first URL of the second sites list - the first one completed fine. What could the problem be? Or how can I increase the timeout? I don't believe this would be the crawler dependencies setting (i have the switch -d 0 enabled), but it may be the proxy on port 2001 currently set to 15000ms as mentioned in the logs. Below is the log snippet:

error: { code: 28,
  state: 'script timeout',
  message: 'Timed out waiting for page load.

**Comment by soulgalore** [comment]
Hi @lyneld 
ok, right now the browser timeout time is hardcoded to 60 seconds. If you load the page in your browser do you see that all Navigation Timing events happens? 

Best
Peter

**Comment by lyneld** [comment]
Hi @soulgalore 

Strange. It completes in 16sec on my browser and about 10sec on Webpage Test. Let me run it once more, it could just be a glitch with EC2?

Lynel

**Comment by soulgalore** [comment]
Hi @lyneld ,
does it happen all the time or just sometimes? Does it work on you run it on your laptop?

Best
Peter

**Comment by lyneld** [comment]
Hi @soulgalore 
It works perfectly now. Probably just a glitch - I kept it on a cron every 30min for the last day and it worked without any issues. Thanks for your help!
Lynel
