### ISSUE TITLE
Option to replace DNS hostname during lookup

### ISSUE THREAD

**Issue by lyneld** [sitespeedio/sitespeed.io#677]
Hi!

I was hoping to have an option to override the IP address (or host) returned through DNS resolution, forcing the request to go to a fixed IP. Would be great in testing CDN's and such.

Currently, WPT supports this using the following `setDns` option:
[https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDns](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDns)

Another option for this implementation is the `setDNSName` setting, which does pretty much the same thing, except it overrides the hostname altogether - the lookup is done on a different (substituted) host.

[https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDNSName](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setDNSName)

Is there a workaround for such a test right now?

Thanks!

Best
Lynel

**Comment by soulgalore** [comment]
This issue belongs in Browsertime: https://github.com/sitespeedio/browsertime/issues/84

It should be doable in your Docker container, taking PRs for the docs on how to do that :)
