### ISSUE TITLE
WPT graphite keys changed/moved in version 3.6?

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#681]
Hi @soulgalore 

I've updated Sitespeed from 3.5 to 3.6 today and it looks like that the (WPT) graphite keys are changed.
I used to fetched all WPT graphite keys in Grafana from:

namespace.[URI].WPT

They moved to summary:

namespace.summary.[domain].timing
namespace.summary.[domain].pagemetric

Is this correct? I'll need to update all my graphs now, or combine graph with old and new keys to see all data from for example previous 30 days.

**Comment by Vandrix** [comment]
I also miss Graphite WPT key "bytesInDoc" now.. It's in verbose JSON result from Webpagetest, but no graphitekey is sent with "bytesInDoc"

**Comment by soulgalore** [comment]
hmm no they haven't moved between the releases, let me check tonight. only Graphite change *should* be the handling of pipes and other characters in the generation of keys. Between 3.4 and 3.5 there was some shifting of key names but not now. Let me get back to you tonight.

bytesindoc should be there also, strange.

Best
Peter

**Comment by soulgalore** [comment]
ok so did quick check: I still have all the WPT keys on the same place as you explain: **namespace.[URI].wpt.* for 3.6?

about the bytesindoc, yep there's a bug when sending the WPT values, it's not specific for bytesindoc though, let me fix that in 3.6.1 asap.

**Comment by Vandrix** [comment]
Fix confirmed :-)

**Comment by soulgalore** [comment]
great, thanks for reporting. sorry about the bug.
