### ISSUE TITLE
After update to 3.6.1 getting errors 

### ISSUE THREAD

**Issue by darraghgrace** [sitespeedio/sitespeed.io#683]
I was using an older version of sitespeed, 3.5.0 I think. Updated to 3.6.1 and cannot run sitespeed anymore. The update seemed to go well with no errors
Windows 7 Pro machine 
npm - 2.11.1
node - v0.10.33

I tried uninstalling via npm and installing again but no luck

Screenshot of issue below. 
Any suggestions would be much appreciated.
![screen shot 2015-06-09 at 20 30 29](https://cloud.githubusercontent.com/assets/2386816/8068632/09e6631a-0eed-11e5-8636-28af1d8885f8.png)

**Comment by darraghgrace** [comment]
I suspect it is because C:\Program Files\nodejs\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\_base.js cannot handle windows paths
var CLOSURE_BASE_FILE_PATH = (function() {
  var relativePath = isDevMode() ?
      '../../../third_party/closure/goog/base.js' :
      './lib/goog/base.js';
  return path.join(__dirname, relativePath);
})();

it is looking for base.js in the folder sitespeed.io.cmd is run from, i.e. in my case even though i have sitespeed installed globally it is looking for these folders relative to my jenkins workspace

**Comment by soulgalore** [comment]
hey @darraghgrace ,
hmm thats no good. Kind of a limbo: the new version of selenium is needed to run Firefox 38 (that's been out for a while). Seems like they did a [logging change](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md) Could you post an issue on the Selenium NodeJS  issue tracker? 

Also, I haven't really used Windows in the last 15 years so would love if you or someone else could help us setup ci.appveyor.com that would be great! I can give you (or someone else) the rights you need. Really missing automatically test the windows version.

Best
Peter

**Comment by darraghgrace** [comment]
Hi Peter, 
Sure, I will log that to selenium today. 
And i'd be happy to look into setting up ci.appveyor.com for sitespeed.io. Hopefully i'll have some time later this week.
Thanks
Darragh

**Comment by soulgalore** [comment]
Thanks Darragh,
perfect, I'll setup permissions so you have all access. Think I'm gonna need your email address (not sure if I have it), drop me an email : peter [AT] soulgalore [dot] com

Thanks
Peter

**Comment by darraghgrace** [comment]
Hi Peter
This issue is already logged to selenium - https://github.com/SeleniumHQ/selenium/issues/642

I need to use the --wptScript functionality but i think this is only available in the new release 3.6.1, is that correct?

Thanks
Darragh

**Comment by soulgalore** [comment]
Hi Darragh,
yep sorry it's only in the latest. Hope the selenium boys and girls can do a quick fix release :(

Best
Peter

**Comment by darraghgrace** [comment]
I rebuilt sitespeed 3.6.1 with browsertime 0.9.5 and works great!
Cheers
Darragh

**Comment by soulgalore** [comment]
creative, perfect :)

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
