### ISSUE TITLE
No url can be fetched

### ISSUE THREAD

**Issue by bbenichou** [sitespeedio/sitespeed.io#684]
Hi,

I'm trying to run sitespeed.io on UBUNTU 14.04 using the docker image.

The command I pass is the following:

sudo docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.bakerross.co.uk -d 0 --noYslow --wptHost www.webpagetest.org --wptKey MY_WPT_KEY -r /tmp/ --graphiteHost 10.67.101.6 --graphitePort 2003 --graphiteNamespace bakerross --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

On sitespeed-run.txt I always get the following error:

Wed Jun 10 10:30:01 UTC 2015
ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf)
Google Chrome 43.0.2357.81
Mozilla Firefox 38.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.16.0-38-generic', Node.js: 'v0.10.25', sitespeed.io: '3.6.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.9.7'
info: Will crawl from start point http://www.bakerross.co.uk with crawl depth 0
error: Error from the crawl: java.net.UnknownHostException: www.bakerross.co.uk
error: Error from the crawl:

error: Error from the crawl: The start url: http://www.bakerross.co.uk couldn't be fetched, response code Unknown error

info: Didn't get any URLs
error:  Error: No URLs to analyze
    at Object.module.exports.fineTuneUrls (/usr/local/lib/node_modules/sitespeed.io/lib/util/util.js:329:18)
    at async.waterfall.callback.budget (/usr/local/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:51:12)
    at fn (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

I have checked the existing ticket https://github.com/sitespeedio/sitespeed.io/issues/472 so I have set my JAVA_HOME path but I still get the same error.

FYI my path is:
/usr/lib/jvm/java-1.7.0-openjdk-amd64

It would be great if you can help me with this.

cheers,
Ben

**Comment by soulgalore** [comment]
Hi @bbenichou 
do you run it locally on your Mac? Sometimes Docker on Mac as kind unexpected behaviour, for example if you switch networks. Then <code>boot2docker down</code> followed by a <code>boot2docker up</code> will do it. 

Else if you run it on a standalone server, can you reach www.bakerross.co.uk from it?

Best
Peter

**Comment by bbenichou** [comment]
HI @soulgalore,

Nope. Basically from a standalone Linux Ubuntu 14.04 server - freshly installed - I run sitespeed through Docker. I use the following command:

sudo docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.bakerross.co.uk -d 0 --noYslow --wptHost www.webpagetest.org --wptKey MY_WPT_KEY -r /tmp/ --graphiteHost 10.67.101.6 --graphitePort 2003 --graphiteNamespace bakerross --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

And from this server I can ping www.bakerross.co.uk without any problem.

Best,
Ben

**Comment by soulgalore** [comment]
Hi Ben,
hmm ok, strange. Can you test to sidestep the crawler and feed sitespeed.io with a list of URL:s using <code>--file</code> instead?

Best
Peter

**Comment by bbenichou** [comment]
Hi Peter,

It's slightly better. 

The url.txt is taken into account so the test start but I get another error now:

info: OS: 'linux 3.16.0-38-generic', Node.js: 'v0.10.25', sitespeed.io: '3.6.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.9.7'
info: Will analyze 1 pages
info: Running WebPageTest http://www.bakerross.co.uk pollResults=10, timeout=600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Dulles:Chrome, connectivity=Cable, video=true
error: WebPageTest couldn't fetch info for url http://www.bakerross.co.uk{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
error: Error running WebPageTest: { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }

TypeError: Cannot read property 'response' of undefined

Any idea?

Best,
Ben

**Comment by bbenichou** [comment]
Hi @soulgalore,

I made 2 new tests:

> 1 without Webpagetest and with Yslow: 

The analyse goes to the end but I have the following Yslow error:
error: Yslow output for 'http://www.bakerross.co.uk' (stdout): FAIL to load http://www.bakerross.co.uk
error: Error running yslow for url 'http://www.bakerross.co.uk': { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }

> 1 without Webpagetest  and without Yslow: 

The analyse goes to the end but takes 0 second to be completed.
info: The analyze took a few seconds (0 seconds)


Hope it helps,

Best,
Ben

**Comment by soulgalore** [comment]
Hi again Ben,
ok, so the first error I would say it can't reach WebPageTest either, and the second one is that it times out (the tests takes too long time).  Are you behind a firewall? You could ping the address, does it work if you curl/wget it?

Best
Peter

**Comment by bbenichou** [comment]
Hi Peter,

We are behind a firewall but I can ping, curl and wget www.bakerross.co.uk or www.webpagetest.org.

I've double check my JAVA config and for my user and root:
the JAVA_HOME is: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java

**Comment by akashnimare** [comment]
@bbenichou I tested the same command It's working
> sudo docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.bakerross.co.uk -d 0 --noYslow --wptHost www.webpagetest.org --wptKey MY_WPT_KEY -r /tmp/ --graphiteHost 10.67.101.6 --graphitePort 2003 --graphiteNamespace bakerross --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1

I am using  sitespeed.io - 3.5.0 , browsertime - 0.9.4

**Comment by bbenichou** [comment]
Hi @akashnimare, @soulgalore,

I can ping, curl and wget www.bakerross.co.uk and www.webpagetest.org so I really don't think it's a network issue.

The only time somebody has encountered the same problem was in the ticket https://github.com/sitespeedio/sitespeed.io/issues/472.

It has been solved by setting the $JAVA_HOME. 

I did it by adding the line "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java" in "/etc/environment" 

since then when I do "echo $JAVA_HOME" I got "/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java"

Are you sure there isn't anything wrong with that?

Thanks,
Ben

**Comment by bbenichou** [comment]
Hi @soulgalore, @akashnimare, 

My apologies...I've double checked with my IT team and it appears that only outbound traffic was allowed. Which explain why the ping/curl/wget were working...

This has been fixed and everything is working fine now, I've got my first graph!!

A big thanks for your amazing tool and the time you took to help me.

Ben

**Comment by akashnimare** [comment]
Cheers man :)

**Comment by soulgalore** [comment]
@bbenichou ah that's perfect :) Thanks for the kind words!
