### ISSUE TITLE
Screenshot is capturing whole page not viewport only

### ISSUE THREAD

**Issue by Vandrix** [sitespeedio/sitespeed.io#685]
Hi @soulgalore 
What I recently noticed is that Sitespeed is taking screenshots of the whole page, not (default) viewport.
So with the screenshots for (default) viewport 1280x800 it's also capturing everything below the fold, until the end of the page.
Is this a bug?

**Comment by soulgalore** [comment]
Hi @Vandrix 
think I actually made it configurable but could be that it isn't actually exposed, I'll check tonight and get back.

**Comment by soulgalore** [comment]
ok, had a look. It's configurable in the js-file that actually takes the screenshots, but not from sitespeed. I'll add that in a coming release. When I have used it now, I screened that the pages are looking ok, but it would of course be valuable to have screenshots of the "right" height.

**Comment by Vandrix** [comment]
Yup. Thnx!

**Comment by soulgalore** [comment]
fixed in 4.0
