### ISSUE TITLE
Add Slack integration

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#692]
In run.sitespeed.io we have integrated Slack using Winston, so when we get an error in the log, we send it to Slack. That would be very useful to also have directly in sitespeed (so you super easy can get errors from your runs into slack, extremely useful for the dashboard). 

However: the configuration starts to be kind of messed up (it's so much info). @tobli has started using yargs for the next version of Browsertime and there you can have configuration parameters on different levels like slack.channel, slack.domain etc. That's something we need in sitespeed, so lets implement it in 4.0.

**Comment by soulgalore** [comment]
or lets add it in the coming release, it is sooo useful :)

**Comment by mackelito** [comment]
It would be interesting to see your setup! :)
Are you using dockers? All installed on the same server/instance? etc etc.. :)

**Comment by soulgalore** [comment]
Hey @mackelito , I wrote a little about it here:
https://www.peterhedenskog.com/blog/2015/07/learnings-deploying-sitespeed.io-online-using-docker/

Yes, everything is Docker. One instance run the server (https://hub.docker.com/r/soulgalore/run.sitespeed.io-server/), the receiver https://hub.docker.com/r/soulgalore/run.sitespeed.io-receiver/, a nginx container, a mysql container, and a redis container, 

Then the worker (https://hub.docker.com/r/soulgalore/run.sitespeed.io-worker/) are on one instance per runner. So for example if you want to have to workers in SF, they need to be on two different instances.

Best
Peter

**Comment by soulgalore** [comment]
fixed in 4.0
