### ISSUE TITLE
Cookie Authentication not working

### ISSUE THREAD

**Issue by ipao9** [sitespeedio/sitespeed.io#695]
Hello again,

I'm using "--requestHeaders cookies.json" in an attempt to crawl a route on a site that requires authentication, with my cookies.json file looking something like 
{
  "somekey":"afdsfgf",
  "somekey2":"bfdvsdq",
  "somekey3":"qwiori"
} 
and saved/located in my main project directory.

There are no issues with output, so no error messages. However, when I use "-b chrome", I see the chrome window pop up and instead of using my cookies to get to the requested page, it goes to the sign in page and just logs the load time of that. Same happens for mozilla and headless.

The command I type in Mac terminal is:
sitespeed.io -u http://xxxxxx.xxx/need/auth -b chrome --requestHeaders cookies.json --phantomjsPath /usr/local/bin/phantomjs

Any help is appreciated!

**Comment by soulgalore** [comment]
Hey @ipao9 
is the cookies tied to one browser or one login on your site? I mean can you do the same thing manually and it works?

You can have a look have edx solved it to automate the login: https://github.com/edx/edx-sitespeed

Best
Peter

**Comment by ipao9** [comment]
Thanks, Peter.

Cookies are tied to the browser. I can go to the site in and out just fine manually. Thanks for the resource, I'll take a look at it immediately.

**Comment by ipao9** [comment]
Unfortunately, the edx tool is not working for me.

command line:
python edx-sitespeed.py ishap@gmail.com 12345 https://wordpress.com/wp-login.php

error:
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "edx-sitespeed.py", line 44, in <module>
    session_key, session_id = login(args.email, args.password, args.base_url)
  File "edx-sitespeed.py", line 12, in login
    csrf = r.cookies['csrftoken']
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 283, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 341, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by soulgalore** [comment]
oh, I meant it as an example, you need to adjust it to your site etc.

**Comment by ipao9** [comment]
Ah, I see. Well, I was not able to get it to work :(

Other than cookies, I tried the --basicAuth supplying a username and password. That did not work either. Is basicAuth supposed to autofill the forms?

Thanks!

**Comment by ipao9** [comment]
Hi Peter,

Assuming the basicAuth does not work, I am returning to the edx plugin. If I had username:test, password:123, and the site as https://wordpress.com/wp-login.php, what parts of the edx-sitespeed.py need to be modified? I keep getting errors that don't give me context to debug.

Traceback (most recent call last):
  File "edx-sitespeed.py", line 44, in <module>
    session_key, session_id = login(args.email, args.password, args.base_url)
  File "edx-sitespeed.py", line 19, in login
    raise RuntimeError('failed login')
RuntimeError: failed login

**Comment by ipao9** [comment]
Authentication works now. The solution was to copy ALL the headers, not just the cookie key and value into the json file.

**Comment by VladimirCacicArapovic** [comment]
Hi please can u show example please.
