### ISSUE TITLE
how to pause page after render

### ISSUE THREAD

**Issue by ipao9** [sitespeedio/sitespeed.io#696]
Before the web page even completely loads, YSlow terminates the instance halfway. Is there a way to make YSlow close the instance after everything is loaded?

**Comment by soulgalore** [comment]
Using PhantomJS 1.9 it waits for pageLoad, if you use 2.0 you can define when to end yourself (it will affect both YSLow and the browser):
http://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test

**Comment by ipao9** [comment]
Using 1.9 will not allow time collecting, though. For 2.0, I defined the script as
'return window.document.readyState === "complete"', but it did not work. I want the entire page to load including all assets before terminating. Any ideas?

**Comment by soulgalore** [comment]
Do you ajax load the assets? Add a User Timing when you are finished and wait for that or another event/value. Or increase the extra time after loadEventEnd.

**Comment by ipao9** [comment]
The assets are ajax loaded. 

I'm sorry, but I couldn't really understand the advice. I tried several things, which didn't work, like 
return window.performance.timing.loadEventEnd > 0 && setTimeout(function(){return true}, 5000);
and
return window.performance.measure("now", "mark_fully_loaded");

I'd appreciate if you could elaborate more. Thanks!

**Comment by ipao9** [comment]
return Date.now() - window.performance.timing.loadEventEnd > X

Thanks!

**Comment by soulgalore** [comment]
yep, the definition is here:
https://github.com/sitespeedio/sitespeed.io/blob/52ec32a240405ac283d42382942e6b2c861d113a/conf/defaultConfig.js#L18

**Comment by ipao9** [comment]
Thanks for the reference to the doc!
