### ISSUE TITLE
Unable to load page after working cookie authentication

### ISSUE THREAD

**Issue by ipao9** [sitespeedio/sitespeed.io#698]
Not sure if others get this problem, but "--requestHeaders cookie.json" sends these cookies to the server. However, when YSlow spins up a new Chrome instance, the page only half loads yet clearly gets past the login page. Furthermore, the cookie values are different than the values I sent through the cookie.json file in this spun-up instance, and some key:value pairs are even missing. 

Also, when YSlow spins up a new Chrome instance, is it normal to not be able to open a new tab and go to google.com?

**Comment by soulgalore** [comment]
Hey @ipao9 ,
I'm not fully following. So this is the flow:
http://www.sitespeed.io/documentation/developers/the-sitespeed.io-universe.png

The headers will be added but all different tools will also add their own headers. Are there anyway I can reproduce?

Best
Peter

**Comment by ipao9** [comment]
After further investigation, I think Selenium may have trouble spinning up instances and loading images and assets, etc. Try this url: http://www.google.com/shopping?hl=en&tab=wf&ei=noKpVd-gMMbX-QHA_KPADg&ved=0CAwQqS4oDA

sitespeed.io -u http://google.com -b firefox  --phantomjsPath /usr/local/bin/phantomjs --waitScript 'return Date.now() - window.performance.timing.loadEventEnd > 40000'

**Comment by ipao9** [comment]
I don't think the issue has anything to do with cookie authentication.

**Comment by ipao9** [comment]
It seems like a recurring issue with many sites now. I am unable to access an url that requires authentication using --requestHeaders cookie.json. Currently, I sign in to that url somewhere else, copy all the key value pairs in the cookie storage, and put in the cookie.json file. Then I execute the command above that I c/p, and the spun-up url from Selenium only half loads.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
