### ISSUE TITLE
Reports are not showing size for practically any asset

### ISSUE THREAD

**Issue by falkoner** [sitespeedio/sitespeed.io#699]
v 3.6.3

Page view / Page summary and related section show "0" as size for practically all assets. I can see size now for several web fonts only out of 70 requests. 

Please let me know if any additional info required to help fix this issue.

**Comment by soulgalore** [comment]
Hey @falkoner 
thanks for reporting! Yes could you please share the URL (if you wanna keep it a secret you can email me peter [at] soulgalore [dot] com) so I can reproduce. Exactly how you run would be great! What OS are you using and do you also collect timings using the browser? The reason I ask is that if you use the browser we get the size from the proxy = we can get correct size for compressed assets.

All the best
Peter

**Comment by falkoner** [comment]
Hi @soulgalore Thanks for quick response. 

I've got a little confused here - I just can't reproduce this issue today of various sites, getting valid asset sizes. The way I was running it yesterday (the same environments - latests Chrome, latest Mac OS, same network in same office) was as follows:

```
sitespeed.io \
  -u https://www.yahoo.com \
  -d 0 \
  -b chrome \
  --screenshot \
  --name "New Marketing site" \
  --resultBaseDir ./test_results/ \
```

From your experience, what might have caused such discrepancies? I have reports saved to prove my words.

**Comment by soulgalore** [comment]
ok, no I don't know, but if you could send med the logs from the run when it failed, that would be great, then I can have a look and see if I can see something.

Best
Peter

**Comment by falkoner** [comment]
Thanks Peter, I'll send you the reports that I have to show case the problem.

**Comment by soulgalore** [comment]
perfect thanks! :)

**Comment by soulgalore** [comment]
I've checked your examples, yep something is wrong :) Only thing in the logs is some errors in the browsermobproxy but the HAR looks ok from BMP. I need to check the code and see if there's where this can happen. All different collectors (phantomjs, the browser and WPT) get the size. What we do today is that since the size is incorrect if the repsonse is compressed from Phantomsjs, we replace the sized there using the HAR files either from Browsertime or WebPageTest and there must be somewhere there we have the problem. 

Sorry for writing it down but it's a good way for me to remember :)

Will continue to look.

**Comment by falkoner** [comment]
Awesome, thanks @soulgalore for quick investigation. Let me know if I can help in any way.

**Comment by soulgalore** [comment]
Hey @falkoner ,
fyi: I'm travelling the coming days and will not be able to do anything. Did a quick look and couldn't see why this happen (but really good that you sent me the raw data). How often does this happen do you know?

Best
Peter

**Comment by falkoner** [comment]
Thanks, @soulgalore. Pretty often, most of the times I would say. Just ran this again and got the same 0 size results for most of the assets. Same version, same web site.

**Comment by soulgalore** [comment]
ok cool, I'll try and reproduce in a couple of days when I got a decent internet connection.

Best
Peter

**Comment by falkoner** [comment]
Hi @soulgalore, any luck there? You release *.2 more versions since than, so I guess, I should update my version too to keep this issue up to day. So just wondering if you had any ideas about this issue since then.

**Comment by soulgalore** [comment]
Hi @falkoner , thanks for pinging me, sorry I had forget, I'll try first thing tonight. I havenät made any changes that could fix this. I checked the code but couldn't see any obvios error in it, so lets see if I can reproduce

Best
Peter

**Comment by soulgalore** [comment]
Hello @falkoner ,
good news is that I can reproduce it. It happens when we collect data from WPT. I'll pushed a temporary fix that gets the data from Browsertime (if it's exists) and then skip WPT, but I'll see if I can fix the main issue. Then I'll can do a release this weekend.

Best
Peter

**Comment by falkoner** [comment]
Thanks @soulgalore
