### ISSUE TITLE
custom scripting

### ISSUE THREAD

**Issue by ipao9** [sitespeedio/sitespeed.io#700]
I'm trying to run a custom script that allows me to auto fill the username and password of the site that is being spun up. However, the script isn't being run?

custom/custom.js:
window.document.getElementById("login-field").value = 'biker@elementum.com';
window.document.getElementById("password-field").value= 'amsterdam';
window.document.getElementsByName("log-form")[0].submit();

The site is spun and just stays there. Ideas?

**Comment by soulgalore** [comment]
ok, think the docs are unclear, the custom scripts can be used to collect metrics and not doing a log in. Like it works right now is that when the loadEventEnds for the URL happens, we run the scripts, and then close the browser and empty the cache (where possible) and then test the URL again. We want to support custom scripts in a way you describe but that will not happen before 4.0.
