### ISSUE TITLE
sitespeed.io on windows - no url fetched

### ISSUE THREAD

**Issue by qa2015** [sitespeedio/sitespeed.io#709]
pls assist getting the following exception:

on windows 7 32 bit pc
all prerequisite install - sitespeed.io-1.8. phantomjs 2.0, nodejs and git

$ sitespeed.io -u http://www.google.com/
Will crawl from start point http://www.google.com/ with User-Agent Mozilla/6.0 a
nd viewport 1280x800 with crawl depth 1 using ruleset sitespeed.io-1.8 ... this
can take a while
./sitespeed.io: line 265: C:\Program: is a directory
No url:s were fetched

**Comment by soulgalore** [comment]
Hey @qa2015 
did you install the latest version of sitespeed, or what's sitespeed.io-1.8? 

You need to have nodejs, git and Java. That should do it.
<pre>
 npm install -g sitespeed.io
sitespeed.io.cmd -h
</pre>

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
