### ISSUE TITLE
Need help in passing input parameters

### ISSUE THREAD

**Issue by vigneshshanmugam** [sitespeedio/sitespeed.io#710]
Checked the docs, But couldnt able to figure out this.

I have a page which requires authentication to login , 

Example
```
 https://www.example.com/login
```

this page has the username, password and login fields. On submitting it will list the actual page with images etc.  How do i test this page?. 

I tried this 
```
sitespeed.io -u  https://www.example.com/login --basicAuth username:pass --noYslow -b chrome
```

But it didnt work. Can you help?

**Comment by soulgalore** [comment]
Hey @vigneshshanmugam ,
ok, so one of the largest drawbacks right now is that there is no built in support for handling login (the thing you tested is only for basic auth (https://en.wikipedia.org/wiki/Basic_access_authentication)). 

You can probably solve it right now with a hack, passing request headers with the cookie information for a logged in user. You can check out [here](https://github.com/edx/edx-sitespeed) how edx solved it.

In the coming 4.0 we will aim to solve it, but either me nor @tobli has started with it yet, so I don't know when it will be finished.

Best
Peter

**Comment by vigneshshanmugam** [comment]
Alright then, I can close the issue if you are tracking this as part of upcoming features

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
