### ISSUE TITLE
i have a webpagetest server 

### ISSUE THREAD

**Issue by norlover** [sitespeedio/sitespeed.io#711]
Before I use 
webpagetest test www.163.com -s xxx --location paris-wptdriver

webpagetest -s xxx status 150106_WP_6
webpagetest -s xxx results 150106_WP_6

Now I installed sitespeed 

how working ?  sitespeed  and webpagetest? 

i can find any key in my wptserver(xxx)

please give me an Examples wptConfig.json ,  thank you !

**Comment by soulgalore** [comment]
Hi @norlover 
Don't have my computer but will try to help. You configure your key when you setup your webpagetest instance (in the .ini file). If you don't have a key, you don't need to supply it. 

Have you checked the docs at http://www.sitespeed.io the specific webpagetest docs? There's one example there with config.

Best
Peter

**Comment by norlover** [comment]
i use 

{
"location": "paris-wptdriver:Chrome",
"connectivity": "Cable",
"timeout": "600",
"runs": "1",
"firstViewOnly": "true"
}

and 

 sitespeed.io -u http://www.qq.com --storeJson --noYslow ----wptHost 111.161.65.44 --wptConfig /root/wpt.json 


Task has still not issued into server (111.161.65.44)

**Comment by norlover** [comment]
Has tested well, it should be the environment .
