### ISSUE TITLE
Connection reset error for webpagetest when running behind proxy

### ISSUE THREAD

**Issue by ramanathanMuthuraman** [sitespeedio/sitespeed.io#712]
![sitespeederror](https://cloud.githubusercontent.com/assets/5201881/8905309/cd0adbc2-3482-11e5-80aa-626d1a55e03a.PNG)
Even after adding the proxy config, I am unable to get the webpagetest results due to connection reset error whereas I am able to get the yslow and gpsi results. For webpagetest I use the www.webpagetest.org as host with the provided API key.Also I use ngrok to expose localhost. Do let me know, if you need any more info.
![sitespeed](https://cloud.githubusercontent.com/assets/5201881/8905254/50ed7900-3482-11e5-9b71-57c1e3309eec.PNG)

**Comment by soulgalore** [comment]
Hi @ramanathanMuthuraman 
hmm could you check the nodejs api for webpagetest and see there how yiu use it with a proxy? else try localky that you can reach the webpagetest server through your proxy, does it work?

Best
Peter

**Comment by ramanathanMuthuraman** [comment]
Unfortunately webpagetest proxy option is only for creating private instance of wpt server and not anything related to firewall. 

From the [documentation] (https://www.npmjs.com/package/webpagetest)
<pre><code>$ webpagetest listen 8080 --server wpt.foo.com</code></pre>

wpt.foo.com is overriding the default www.webpagetest.org server but can still be overridden with server option

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
