### ISSUE TITLE
Collecting more data from WPT to Graphite

### ISSUE THREAD

**Issue by jeremy-green** [sitespeedio/sitespeed.io#714]
Hi, I was wondering if it was possible to collect even more data from WPT.  In the docs, there's a mention of adding a new collector but no documentation.  Going through the source, I found: https://github.com/sitespeedio/sitespeed.io/blob/master/lib/cli.js#L329.

I ended up copying https://github.com/sitespeedio/sitespeed.io/blob/master/lib/collectors/pages.js to a new file:

```
'use strict';

// path in docker container
var util = require('/usr/local/lib/node_modules/sitespeed.io/lib/util/util');
var pages = [];

exports.processPage = function(pageData) {
  var p = {};

  if (pageData.webpagetest) {
    collectWPT(pageData, p);
  }

  p.url = util.getURLFromPageData(pageData);

  if (p.url !== 'undefined') {
    pages.push(p);
  }
};

exports.generateResults = function() {
  return {
    id: 'wptCustom',
    list: pages
  };
};

exports.clear = function() {
  pages = [];
};

function collectWPT(pageData, p) {
  p.wpt = {};

  var views = ['firstView'];
  var scores = [
    'score_cache',
    'score_cdn',
    'score_cookies',
    'score_keep-alive',
    'score_minify',
    'score_combine',
    'score_compress',
    'score_etags'
  ];
  var timings = [
    'domContentLoadedEventStart',
    'loadEventStart',
    'loadEventEnd',
    'titleTime',
    'server_rtt'
  ];

  pageData.webpagetest.wpt.forEach(function(browserAndLocation) {

    var connectivity = browserAndLocation.response.data.connectivity.toLowerCase();
    var locationAndBrowser = browserAndLocation.response.data.location.split(':');
    var location = locationAndBrowser[0].toLowerCase();
    var browser = locationAndBrowser[1].toLowerCase();

    p.wpt[location] = p.wpt[location] || {};
    p.wpt[location][browser] = p.wpt[location][browser] || {};
    p.wpt[location][browser][connectivity] = p.wpt[location][browser][connectivity] || {};

    if (browserAndLocation.response.data.median.repeatView) {
      views.push('repeatView');
    }

    views.forEach(function(view) {
      p.wpt[location][browser][connectivity][view] = {};
      scores.forEach(function(score) {
        p.wpt[location][browser][connectivity][view][score] = {
          'v': browserAndLocation.response.data.median[view][score],
          'unit': ''
        };
      });
      timings.forEach(function(timing) {
        p.wpt[location][browser][connectivity][view][timing] = {
          'v': browserAndLocation.response.data.median[view][timing],
          'unit': 'milliseconds'
        };
      });

    });

  });

}
```

I was able to search the results.json file that I generated locally and saw the `wptCustom` values.  However, when I ran it through Docker, the values weren't set to Graphite.

Currently, we're running Docker from Jenkins using this command:
```
# remove old results directory
sudo rm -rf $WORKSPACE/sitespeed-result/urls.txt/results

# create a custom script the returns some jenkins info.
echo "return ${BUILD_NUMBER};" > $WORKSPACE/scripts/buildNumber.js

docker run \
--privileged \
--rm \
-v $WORKSPACE:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io \
--file urls.txt \
--name "Jenkins ${BUILD_DISPLAY_NAME}" \
-d 0 \
-b firefox \
-n 3 \
--collectors collectors \
--connection cable \
--graphiteHost <host> \
--gpsiKey <key> \
--customScripts scripts \
--wptHost <host> \
--wptKey <key> \
--wptConfig wptConfig.json \
--outputFolderName results \
--noColor
```

Any ideas?  Or maybe I'm just looking in the wrong place?

Sitespeed.io and Grafana are awesome by the way!

**Comment by soulgalore** [comment]
Hi @jeremy-green ,
thanks for the kind words :)

Hmm, yes so I think the easiest (and best) way is that I rewrite that part so every metric from WPT is atomatically picked up and added to the json and sent to Graphite? It should be quite straight forward, but I need/want to fix https://github.com/sitespeedio/sitespeed.io/issues/708 and https://github.com/sitespeedio/sitespeed.io/issues/713 first, because they will change the internal structure a little. I could probably start this weekend with the implementation.

About the current implementation: fetching data to the summary for WPT is straightforward (you create your own aggregator in lib/aggregators/webpagetest but for getting it for each page, you need to do it the way you do. But let me change that so it's easier and you don't need to do your own.

Best
Peter

**Comment by soulgalore** [comment]
Hey Jeremy,
started looking at this now, the generic solution is possible but need to add mapping describing the data (type and description text) so it will take some time. What metrics are you most intrested in, is the score or titleTime? Maybe I can do quick fix for some of the ones you need and then later do a better more generic solution.

Best
Peter

**Comment by jeremy-green** [comment]
Hi Peter, sorry for the late response -- a month late :unamused:.  As it is right now, I think we're pretty happy with all the data that's being collected so a quick fix is appreciated but not necessary.  I was more digging into what's possible with sitespeed.io than what's required.  I think this can be closed and I'll continue to watch releases and see what new features come out that I can find.  Thanks!!
Jeremy

**Comment by beenanner** [comment]
I'm interested in collecting domain level metrics from WPT fully loaded as currently only resources loaded up to the onload event are captured. Of course this will generate a ton of metrics so it may be worth having this configurable(off by default).

**Comment by soulgalore** [comment]
so I think in the coming version we can have two different ways of pickup metrics: hadn picked speed index/fullyLoaded, assets sizes etc and then get them all. Lets aim for that, but I haven't started with the WPT implementation of 4.0 yet, need to fix some other things first so it all will be cleaner. Will ping this thread when it's there so you ca try.

**Comment by beenanner** [comment]
Thanks @soulgalore! Let me know if I can assistance in any way I'd be happy to help when I can and if it doesn't step on any other toes working on 4.0.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
