### ISSUE TITLE
inline support for requestHeader config

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/sitespeed.io#715]
Right now --requestHeaders config needs a FILE to set value:
--requestHeaders FILE
For example:
sitespeed.io -u http://www.example.com --requestHeaders cookie.json

I'd like to set the value as inline like this:
sitespeed.io -u http://www.example.com --requestHeaders "{'Cookie':'12345'}"

This should be fairly simple improvement by checking the value whether it has .json at the end or a valid json string etc...

**Comment by pranavparikh** [comment]
:+1:

**Comment by soulgalore** [comment]
Hi @tufandevrim ,
yep good idea! Don't have so much time at the moment, if you could submit a PR that would be great! 

Best
Peter
