### ISSUE TITLE
Configure Browsers

### ISSUE THREAD

**Issue by chrisbautista** [sitespeedio/sitespeed.io#721]
Hi 

Awesome job you're doing! Would like to contribute. 

I have a specific need to modify how the browsers(Phantomjs, chrome , etc. ) handle certain features like CORS and more granular control on requests vs proxy settings.

**Comment by soulgalore** [comment]
Hi @chrisbautista 
thanks for the kind words!

Yes that would be great. We run browsers using Selenium from https://github.com/tobli/browsertime. We are building a new version to be relesed, but if you do some changes we can patch (if it isn't too big of change hehe, we will soon(?) publish the branch with the changes but wanted to test and add some more functionality). However: phantomjs runs through a script in sitespeed.io, becasue the current selenium version is missing some important configuration features.

Could you explain a little more what you wanna do and I can help in the right direction. Either in this issue or drop me an email: peter [AT] soulgalore [dot] com

All the best
Peter

**Comment by chrisbautista** [comment]
Hi @soulgalore 

I would like to be able to pass browser specific parameters e.g.  "--web-security=false" or "load-images=false"  to phantomjs etc.  I had the misfortune of testing an internal site which gets it's data from a different domain. Sitespeed gets the incomplete site but not my actual pages because of the data missing. 

Any hints?

Chris

**Comment by soulgalore** [comment]
Hello @chrisbautista ,
hmm not really sure how you mean? Data = all the requests - should be able to be fetched, as long as the server where you run sitespeed.io can access it.

Best
Peter

**Comment by chrisbautista** [comment]
Hi @soulgalore 

I can open the test site via Chrome with web-security turn off. The website I'm testing was made to work on the same domain but the lab setup still uses the remote domain for data.  So I'm running to cross domain errors. As part of CI, I can't modify the code to fix this. Since I trust the domain I should be able to just ignore it.  PhantomJS has a similar switch on the command line to disable cross domain checking.

http://phantomjs.org/api/command-line.html

Suggestion is to add a parameter that passes e.g.  --browser-args="--web-security=false " 
or  quiet nicely --browser-args="--config=/path/to/json" 

Warm regards

Chris

**Comment by soulgalore** [comment]
Hi Chris,
yep making it possible to send arbitrary browser configs sounds good! Pinging @tobli about this also so we can discuss how to also get it into Browsertime.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
