### ISSUE TITLE
User browser's cache after first run

### ISSUE THREAD

**Issue by floreo** [sitespeedio/sitespeed.io#726]
Hi,

I've noticed once you set the flag -n for several run at more than 2 that it doesn't use the browser's cache.Yes I did saw that [thread](https://github.com/sitespeedio/sitespeed.io/issues/443). So if I get it right, it runs Selenium to control the browser and for now it starts two times the browser without keeping its cache if you set -n to 2. Would you consider adding a flag to activate keeping the cache when -n > 2 ? I don't know if it's possible yet, though I found [this](http://stackoverflow.com/questions/6787095/how-to-stop-selenium-from-creating-temporary-firefox-profiles-using-web-driver) interesting. Perhaps there is a way to do it with Chrome too. So my idea would be if you want cache for several run simply to have a flag to set it like so:

    sitespeed.io -u http://example.com -b firefox -n 2 --cache

Why this feature ? Because it would be really great to see if the caching rules you've set are really working (mod_expires, etc ...).
Thanks already for the good work, it's quite an amazing tool and I hope you can have a look at my request.

**Comment by soulgalore** [comment]
Hi @floreo 
thanks for the kind words :)

Yes, that is one thing we aim to fix for 4.0 (but that release is quit far away). First we will release  a new version of Browsertime (1.0), @tobli has done much work there but there are still some things 2do before the release. 

We are more thinking of defining a couple of pages you will visit and not emptying the caches between them but I think doing it for the same page will have the same functionality so it will not be a problem.

However, we have quit much work before we are there.

Best
Peter

**Comment by floreo** [comment]
Hi @soulgalore 

thanks for your fast answer !
Yes your way would be quite more flexible, though I'm afraid about how it would look like if you want to call several time the same page with the cache. If you have to write down several times the same URL in the configuration (as if it was several URLs) it would be a bit "ugly". I guess I'm getting a bit ahead of myself.
Well I'm looking forward for 4.0 !
Courage, keep up the good work :)

**Comment by soulgalore** [comment]
Hey @floreo ,
yep I think your solution with a flag is nice,  lets aim for adding that. Need to think about the rule score though, have started testing out new structure for the rules or kind of a new page setup, will push it to Github next week.

Best
Peter

**Comment by floreo** [comment]
Awesome @soulgalore, thanks !
About the rule score I'd suggest adding the result on the same page, simply because it's not so practical to have to switch pages to compare if you see what I mean. I'd suggest adding it on the same page, perhaps having two rows. First run above and under the cached call, this way you could see the difference and wether the caching really is OK. Though, maybe it would ruin the readability, too much information? Last "problem", if you make more than 2 runs, how would you show it on the page? I just thought maybe if you set -n to 5 then you do 5 calls without cache and 5 calls with cache, so you can do some average and only show the average of both in the results. This way you keep only 2 results in the page, average calls not cached compared to average calls with cache. Dunno if I'm so clear here :'D
Thanks for having a look at that I'll be around to test it out if you need :)

**Comment by soulgalore** [comment]
Hehe :) I'll ping this thread when I start implement this and then take it up for discussion. It looks like it will take a month or two though before I start.

**Comment by jzoldak** [comment]
@soulgalore Re "defining a couple of pages you will visit" - although I have yet to use it myself, it looks like webpagetest has a [scripting mechanism](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting). Might be good to look at that for ideas, even if to just start by implementing something like their "logData" and "navigate" commands. As a user, those are the ones I'd start with. FWIW.

**Comment by soulgalore** [comment]
jepp it is something like that but with a little twist :) Scripting what to test is cool, what will be extra nice is that we can collect data from multiple pages kind of out of the box. lets see when we have done some more coding :)

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
