### ISSUE TITLE
Enable configuration option for specifying cookie values

### ISSUE THREAD

**Issue by jzoldak** [sitespeedio/sitespeed.io#730]
I've been passing logged-in session information for my web application via the --requestHeaders command line option. Example header is something like this:
```{"X-CSRFToken": "foo", "Cookie": "sessionid=bar; csrftoken=foo"}```

This works fine for the initial page load with the correct, logged-in user. However there are pages in my application that access an external API via an ajax callback from a Backbone.js model. For those subrequests, the API server is responding with 401 unauthorized.

I can reproduce this issue directly in phantomjs with code like this, run with the command ```/usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs test.js```:
```
var webPage = require('webpage');
var page = webPage.create();

page.customHeaders = {
  "Cookie": "sessionid=bar"
};

page.open('<my_url>', function() {
  phantom.exit();
});
```

If instead I set the cookies directly the callbacks work fine. E.g.:
```
var webPage = require('webpage');
var page = webPage.create();

phantom.addCookie({
  'name'     : 'sessionid',
  'value'    : 'bar',
  'domain'   : '<my domain>',
  'path'     : '/',
  'httponly' : true,
  'secure'   : false,
  'expires'  : (new Date()).getTime() + (1000 * 60 * 60)   /* <-- expires in 1 hour */
});

page.open('<my_url>', function() {
  phantom.exit();
});
```

@soulgalore I was intending on adding a --cookies option to the CLI and wiring it through to the headless scripts. Wanted to get your feedback first to make sure it's something you agree with.

Implementation thoughts:
* Not supported for WPT & GPSI.
* Will work similar to requestHeaders where you can pass in a filename or JSON
* Reference: [PhantomJS addCookie method](http://phantomjs.org/api/webpage/method/add-cookie.html)

**Comment by soulgalore** [comment]
it needs to work with Browsertime also. I'll add @tobli to the mix :)

First just FYI the plan: @tobli is working on a new slicker version of Browsertime and when we have that, we have the ability to improve sitespeed and do much cooler things and that will be 4.0 (like support for actual login). My first plan was that it would be release October by now I think a more realistic date is December.

What did I want to say with that? Hehe, a cookie thing will be cool as long as it works with Browsertime and it will probably be dropped in 4.0 to a more generic solution. Ok?

**Comment by jzoldak** [comment]
Cool, I'll take a peek at the existing browsertime integration code to gauge how easy/difficult it would be.
Very psyched for the 4.0 features, and I am totally all for refactoring out the cookie business for something better!

**Comment by jzoldak** [comment]
OK I looked into wiring this through browsertime, and it seems that this would not be easy - the  browsermobproxy code is the limiting factor here.
I was also able to figure out a way to work around my original problem, by configuring my application under test to save session cookies on every request. This should hold me over for the time being.
