### ISSUE TITLE
Graphite doesn't seem to receive metrics

### ISSUE THREAD

**Issue by thibthib** [sitespeedio/sitespeed.io#732]
Hi,

I'm trying to send the sitespeed data to Graphite, but no metrics are displayed in the graphite interface.

I'm using the docker images. I started the graphite one with
```bash
docker run -d
--name graphite
-p 8080:80
-p 2003:2003
--restart="always"
-v /data/graphite/storage/whisper:/opt/graphite/storage/whisper
-v /Users/Thibaut/.htpasswd:/etc/nginx/.htpasswd
sitespeedio/graphite
```

and then I run
```bash
docker run
--privileged --rm
-v /data/sitespeed.io:/sitespeed.io
sitespeedio/sitespeed.io
sitespeed.io
-u http://mywebsite.com
-d 0 -b chrome -r /tmp/
--graphiteHost myGraphiteIP
--seleniumServer http://127.0.0.1:4444/wd/hub
2>&1
```
to feed graphite with some metrics. I seems to send the data to graphite, as it print `info: Sending data to Graphite host:192.168.99.100 port:2003`, but then in the Graphite interface, I have no metrics :

![capture d ecran 2015-08-24 11 14 47](https://cloud.githubusercontent.com/assets/1030644/9436678/63ce7436-4a51-11e5-96bb-b2b08b3b5c9e.png)

Am I doing something wrong, or is there something broken ?

**Comment by soulgalore** [comment]
Hi @thibthib ,
hmm, lets see. Are you the ip you are using as myGraphiteIP is the ip of the server not the Docker container?  Meaning the same as you surf to when you access the graphite admin?

Best
Peter

**Comment by thibthib** [comment]
Yup, it's the same IP as in the URL of the graphite admin. But it seems it's also the container's IP.

**Comment by soulgalore** [comment]
Ok what OS are you running on?

**Comment by thibthib** [comment]
I'm on the OS X beta 10.11 (15A262e).

**Comment by soulgalore** [comment]
ok thanks I'll look into it tonight.

**Comment by soulgalore** [comment]
ok, so I tested now.  I used the (new) Docker quickstart terminal.
<pre>
docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com
</pre>
First starting Graphite with no mapping of the volumes just to make it easy.
<pre>
docker run -d   --name graphite   -p 8080:80   -p 2003:2003   sitespeedio/graphite
</pre>

And then collect some data:
<pre>
docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.sitespeed.io -b firefox -n 5 --connection cable -r /tmp/ --graphiteHost 192.168.99.100 --seleniumServer http://127.0.0.1:4444/wd/hub -d 0
</pre>

And I got some metrics in Graphite. Can you check if it works for you?

Best
Peter

**Comment by thibthib** [comment]
Oh, I got some metrics too. I just ran the issue down, it was a permission fail on the graphite `graphite/storage/whisper` folder. Thanks a lot.

**Comment by soulgalore** [comment]
great!
