### ISSUE TITLE
not all values are sent to graphite

### ISSUE THREAD

**Issue by rafalSuntimes** [sitespeedio/sitespeed.io#733]
I run this command

    sitespeed.io --graphiteHost localhost --graphiteNamespace chicago -f URLs.txt -b firefox --seleniumServer http://10.2.200.147:4444/wd/hub --verbose

, and I get beautiful results that I can view from the html pages created, such as:

![screen shot 2015-08-25 at 10 16 22 am](https://cloud.githubusercontent.com/assets/12926563/9480226/906c15e2-4b47-11e5-8596-acfa2ea90af6.png)
 
However, most of these statistics never make it to my Graphite instance. 

For example, --verbose flag shows these timings values:

![screen shot 2015-08-25 at 4 42 38 pm](https://cloud.githubusercontent.com/assets/12926563/9480386/5a1d988e-4b48-11e5-9ff2-540da7ac8a37.png)

, and this is what Graphite gets/displays:

![screen shot 2015-08-25 at 4 44 34 pm](https://cloud.githubusercontent.com/assets/12926563/9480427/9bd13eca-4b48-11e5-9f1c-b0541aa8da05.png)

It does not even have the summary directory. Am I doing something wrong? 

This is my "/etc/carbon/storage-schemas.conf" if it matters.

    [carbon]
    pattern = ^carbon\.
    retentions = 60:90d

    [chicago]
    pattern = ^chicago\.
    retentions = 30s:1d

    [default_1min_for_1day]
    pattern = .*
    retentions = 60s:1d

My OS: 'linux 3.13.0-62-generic', Node.js: 'v0.12.7', sitespeed.io: '3.9.0', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.10.2'

**Comment by soulgalore** [comment]
Hey @rafalSuntimes ,
do you run your own Graphite instance? We push a lot of metrics at once and by default only a limited number are created, checkout https://www.sitespeed.io/faq/#i-dont-get-all-values-in-graphite

Can help you more later.
Best
Peter

**Comment by rafalSuntimes** [comment]
Yes, I run my own instance. I installed it alongside Grafana and sitespeed.io on my Ubuntu box.

I can't believe I missed that FAQ question.. Works perfectly now. Thanks, @soulgalore !

**Comment by soulgalore** [comment]
ah good. @rafalSuntimes if you have any ideas of how we can make the graphite info more obvoius that would be great.

**Comment by rafalSuntimes** [comment]
@soulgalore 

I saw that there is not much information on the Documentation/Graphs page when it comes to combining Sitespeed.io, Graphite and Grafana. It says however that "soonish" a video would be made about creating graphs in Grafana. Is that something that is currently being worked on?

Since I already went through learning how to set up a provisioned vagrant (bonus points) VM box with Graphite, Grafana and sitespeed.io on it, maybe I could help out? I saw you guys offer a vagrant box with sitespeed.io and browsers, but I think they do not include the other two pieces? As of right now, I have a fully working Graphite-Grafana-sitespeed.io setup.

**Comment by soulgalore** [comment]
yes so switched using the docker containers instead https://hub.docker.com/u/sitespeedio/dashboard/ . Think that is nice because each tool runs in their own container and it gets a nice separation + it's good if you already use Grafana or Graphite.

**Comment by rafalSuntimes** [comment]
I understand. Thanks.
