### ISSUE TITLE
sitespeed.io doesn't honour the --btConfig parameter in all cases 

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#735]
We got reports that this isn't working
<pre>sitespeed.io -v -u http://www.url.com/ -d 0 -n 1 -b firefox --btConfig btconf.json</pre>

I did a quick test yesterday, then I saw that if you donät inclide the browser, we will not execute the btconfig (and that maybe is quite ok). Lets dig into this and see.

**Comment by m0nkey** [comment]
Thank you. Specifically the use case I have is wanting to pass --useProxy false to browsertime via --btConfig.  Ideally we could use mobproxy via external --seleniumServer (no HAR generated in the described use case) but in alas in my case the test to external Selenium grid times out because mobproxy isn't available locally.

**Comment by soulgalore** [comment]
yep, I'm able to reproduce, give me a couple of minutes ...

**Comment by soulgalore** [comment]
ok, so there's some hardcoded things I've missed when I implemented it the first time, the proxy is pretty hard-wired into sitespeed.io, think I will not be able to fix it tonight but I have quiet much time Saturday/Sunday when I travelling so hopefully there's a fix release Sunday night. Also ping @tobli if you have some time, else I fix it this weekend.

**Comment by m0nkey** [comment]
Thanks @soulgalore and @tobli

**Comment by chrisbautista** [comment]
Thanks for pointing me here @soulgalore .  I will follow this fix as well.  I would like to help if you need to test this in windows. 

Warm regards

Chris

**Comment by cgatian** [comment]
Im also running into this issue. When I include a browser to run against the error is displayed.  My command line is pretty simplistic.  Is there a configuration setting I can set to bypass reading the btConfig? 

![image](https://cloud.githubusercontent.com/assets/1752170/9619128/ca673bd0-50da-11e5-9d0b-dea0c0016869.png)

**Comment by m0nkey** [comment]
@soulgalore  and @tobli  just checking in to see if there's anything I can offer in support of a fix, thanks for looking at this one.

**Comment by tobli** [comment]
Hi @m0nkey,
We're testing out a patch for the issue when running without generating a HAR file. We'll merge and release a new version this week. Thanks for waiting. =)
/Tobias

**Comment by m0nkey** [comment]
Awesome thank you both!
On September 14, 2015 at 12:24:11 PM, Tobias Lidskog (notifications@github.com) wrote:

Hi @m0nkey,
We're testing out a patch for the issue when running without generating a HAR file. We'll merge and release a new version this week. Thanks for waiting. =)
/Tobias

**Comment by soulgalore** [comment]
@tobli maybe we could just release this, I thought I should bundle a couple of more fixes but don't see any problem making a couple of small ones?

**Comment by tobli** [comment]
I'm all for it, won't have time tonight however.

**Comment by soulgalore** [comment]
I've pushed the release a couple of minutes ago. Hope it work now for you @m0nkey !

**Comment by m0nkey** [comment]
Thanks, I’ll give this a shot later tonight!

**Comment by chrisbautista** [comment]
Awesome guys! Will test this feature too.
