### ISSUE TITLE
custom post tasks not working

### ISSUE THREAD

**Issue by rafaltruszkowski** [sitespeedio/sitespeed.io#738]
I am trying to include an additional statistics in my Graphite, but I am not sure how to create a custom post task. I thought I could just do this:

    exports.task = function(result, config, cb) {
      console.log('yep this is my task running!')
      var totalWaitTime = 0
      var domains = result.domains

      for(var i=0;i<domains.length;i++){
            var domain = domains[i];
            //console.log(domain.wait.stats.sum)
            totalWaitTime += domain.total.stats.sum
        }
      console.log('total wait time: ' + totalWaitTime)

      result.pages[0].timings.frontEndTime.max.v = 9000

      console.log(result.pages[0].timings.frontEndTime.max.v)

      cb();
    };

While 9000 is printed to terminal, it is not stored in Graphite. Instead, the original value is used. Am I doing it wrong? Can I even update the result object at this stage?

**Comment by soulgalore** [comment]
ah I see, this is cool, I haven't been thinking of using it like this. So the post tasks are running in parallel right now, both the internal post task sitespeed.io uses and the ones you create yourself, and that is a problem so the data could have already been sent to graphite before you change it.

I never thought of the idea that you would actually add things (metrics) yourself, that is cool idea. one way to fix it could be to run the the external post tasks first and then the internal post tasks, but best case would be to able to choose. let me think a little on how we should fix this.

**Comment by rafalSuntimes** [comment]
Thanks! I tried looking into the code, but I could not figure it out..

**Comment by rafalSuntimes** [comment]
I found the files that deal with all that. I will try to modify it in a reasonable way. If I am successful, I will make a PR.

**Comment by soulgalore** [comment]
cool, I don't have so much time right focusing on 4.0 I think we should create a issue for this making it possible to run post tasks before and after the rest of the tasks.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
