### ISSUE TITLE
Cannot set property of "name" of undefined

### ISSUE THREAD

**Issue by cgatian** [sitespeedio/sitespeed.io#739]
Im trying to run sitespeed.io on window server 2012. When I run with a browser enabled, browsetime looks like it trips up on a property within the HAR file.  I'm thinking there might be a permission or dependency missing in how the HAR file is returned.  I tried going to previous versions as well.  Any thoughts?  
I saw this same error was posted in another issue #735 but I think something else is going on.

Site Speed 3.9.0
![image](https://cloud.githubusercontent.com/assets/1752170/9619128/ca673bd0-50da-11e5-9d0b-dea0c0016869.png)

Site Speed 3.7.0
![image](https://cloud.githubusercontent.com/assets/1752170/9666702/a207b00e-5245-11e5-9d9a-f7ff133c3349.png)

Site Speed 3.6.3
![image](https://cloud.githubusercontent.com/assets/1752170/9666547/c4bf2100-5244-11e5-8776-7fba66c57c4f.png)

**Comment by cgatian** [comment]
Interesting, switching to Chrome as the browser did not cause these issues. In retrospect, I should've tried this sooner...

FireFox version I am using is 38.2.1 ESR

**Comment by tobli** [comment]
Hi @cgatian,
Thanks for the report. For some reason the HAR files generated when running Firefox don't contain the expected data about the browser used. I'm not sure why that is, but I'm putting some additional safety checks in Browsertime to get around this. I'll update this issue once a fix is available.

As for the second issue, could you please open a separate issue for that, and add whatever details you can. Is this repeatable 100%? We've not seen this on Linux or Mac, so it could be a Windows specific issue.

**Comment by cgatian** [comment]
I'm surprised no one else has seen this.  It works fine on Windows 7 Firefox 31.4.  I'll report back with any additional findings.

@tobli  Could you point me in the direction of a wiki outlining how to build and debug sitespeed.io locally?  I wouldn't mind taking a more closer look.

**Comment by soulgalore** [comment]
Hi @cgatian ,
sorry for not responding earlier.  If you can add the har and the JSON from Browsertime in a gist and I can have a look, else compare those two files with the working version you had, then you can probably see what fields are missing or something is strange. That would be great!
Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
