### ISSUE TITLE
How to collect custom metric asynchronously

### ISSUE THREAD

**Issue by yurychika** [sitespeedio/sitespeed.io#740]
The sitespeed.io is fantastic. It really help to enhance our app.

Currently, we have some time metrics to collect after user do some actions, but those actions will trigger some ajax call and make it asynchronously. 

I've taken a look at the sample custom metrics script, and all of them are getting metrics synchronously. I wonder if I can get some metrics asynchronously and send it back to Graphite.

Thanks for the great effort.

**Comment by soulgalore** [comment]
Hi @yurychika ,
thanks for the kind words! What you need to do is change when the browser stops collect metrics. You can define your own javascript that will define when to end. Checkout this: https://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test

It is a little short, maybe it will get you started, test it and if you need help ping the thread I will help out!

Best
Peter

**Comment by yurychika** [comment]
Hi @soulgalore 

Thanks for the quick response.

I read the doc you provided and it's interesting.  It's good to control when to stop the test, but I still don't get it very well about how  to send out my custom *metrics*. According to https://www.sitespeed.io/documentation/browsers/#custom-metrics, I should have some script to return a simple value of JS(Number or String, etc). But in my case that I will need to do some ajax call and then get a custom timing, I can't return a simple JS value like that directly.  Maybe what I can return is a *Promise* but I am not sure if the *sitespeed.io* supports that. Correct me if I understand the process incorrectly.

Let me explain more about my *case* here:
I've got some JS script written in *CasperJS*(a headless testing tool based on *PhantomJS*). I use those scripts to simulate real user actions on our app and collect timing spent. 
I would like to send the metrics back to graphite if possbile, and also I would like to set a performance budget on that. After reading https://www.sitespeed.io/documentation/developers/#add-your-own-post-tasks, I thought if I should rely on that to implement my case.

Any comments would be really grateful.

Thanks,
Qi

**Comment by soulgalore** [comment]
Hi @yurychika ,
aha ok, I think I misunderstood. If you do some ajax calls on you page as standard behaviour, then you can wait until you get the response, collect the data and end the test. There's no support for custom fetching of data from other sources. Think you need to add your own hook to send these metrics to Graphite.

Best
Peter

**Comment by yurychika** [comment]
Hi @soulgalore 

Is there any guide about how to write my own hook to send metrics to Graphite? I think we already set up a graphite server.

After thinking about my cases, I think it may not be a good idea to put our scripts inside sitespeed.io since they tend to focus on different things.

thanks,
Qi

**Comment by yurychika** [comment]
Since I am using casperJS. Although it uses PhantomJS, but I found it hard to get the phantomJS session inside sitespeed.io and send it to casperJS to use.

Actually, CasperJS itself doesn't accept other PhantomJs session, and it has to create one on its own.

**Comment by soulgalore** [comment]
Hey @yurychika 
sorry for the late replay. yep keep it outside. If node/javascript is your thing then you can have a look at https://github.com/sitespeedio/sitespeed.io/blob/master/lib/graphite/graphiteSender.js that the code that sends the data to Graphite.

Best
Peter

**Comment by yurychika** [comment]
Hi  @pelmered ,

Thanks for the update and i will give it a try.

thanks,
Qi
