### ISSUE TITLE
GC overhead limit reached

### ISSUE THREAD

**Issue by RasPat1** [sitespeedio/sitespeed.io#741]
```
% sitespeed.io -b firefox --url 'http://www.shoptiques.com' -d 4
info: OS: 'darwin 14.4.0', Node.js: 'v0.12.6', sitespeed.io: '3.9.0', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.10.2'
info: Will crawl from start point http://www.shoptiques.com with crawl depth 4
error: Error from the crawl: Exception in thread "main"
error: Error from the crawl: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Crawl works with no default depth of 1
Machine:
```
Darwin MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

No data/error.log file was generated

CPU usage of java spiked to use 700% (8 cores)
Memory ramped up from 0->~160->~320MBs approximately and increased slowly after 320.
Network showed no serious packet data in or out. sent 28kb, in 1.6mb
Takes about ~1.5 minutes to hit GC Overhead limit
Doesn't exit after error shown

**Comment by RasPat1** [comment]
Occasionally it will go a bit and the spit out 
```
% sitespeed.io -b firefox --url 'http://www.shoptiques.com' -d 4
info: OS: 'darwin 14.4.0', Node.js: 'v0.12.6', sitespeed.io: '3.9.0', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.10.2'
info: Will crawl from start point http://www.shoptiques.com with crawl depth 4
error: Error from the crawl: Sep 11, 2015 12:11:37 PM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: I/O exception (java.net.SocketException) caught when processing request: Connection reset

error: Error from the crawl: Sep 11, 2015 12:12:13 PM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: Retrying request

error: Error from the crawl: Sep 11, 2015 12:12:15 PM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: I/O exception (java.net.SocketException) caught when processing request: Broken pipe

error: Error from the crawl: Sep 11, 2015 12:12:16 PM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: Retrying request

error: Error from the crawl: Exception in thread "main"
error: Error from the crawl: java.lang.OutOfMemoryError: Java heap space
```
System specs: 
https://www.dropbox.com/s/9zil7nnsmmlqsyf/Screenshot%202015-09-11%2012.26.25.png?dl=0
After hitting GC limit:
https://www.dropbox.com/s/sb1kipay8mozpu1/Screenshot%202015-09-11%2012.26.48.png?dl=0

**Comment by soulgalore** [comment]
Hey @RasPat1 ,
thanks for the report. The current crawler runs in Java and uses quite much memory. You can increase the available memory for the Java process by using the parameter --memory . Default is 256, you can try for example:
--memory 1024

Please let me know if it works better.

Best
Peter

**Comment by soulgalore** [comment]
Hey @RasPat1 did this work out for you?
Best
Peter

**Comment by RasPat1** [comment]
@soulgalore,

It worked to avoid the GC errors, but still an unsuccessful run.  I'm going to close this issue and, if necessary, open another after investigating the errors from the expanded memory run.

Thanks for the speedy response and follow up!

Onwards,
Ras
