### ISSUE TITLE
Har file naming convention in Har/

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#742]
Current the Har file naming convention is: {host}-{Path1}-{Path2}--0.html;  however, the host name is usually has dot within it, so it is not convenient to automated to read those files.
for example, current har HTML file sample: 
www.myhost.com-abc-123--0.html

Suggestion: can we replace the dot within host name to '_'
sample:
www_myhost_com-abc-123--0.html

Thanks!
Cheng Chi (@joychester)

**Comment by soulgalore** [comment]
Hej @joychester ,
yes you are right. Think though it uses the same namings all over the board, need to check (meaning for generating HTML etc).

Let me try it out, could probably do it tomorrow Tuesday. There's also a bug with HAR namings for WPT: https://github.com/sitespeedio/sitespeed.io/issues/729 want to fix that also. 

Best
Peter

**Comment by joychester** [comment]
Thanks! :+1:

**Comment by soulgalore** [comment]
ooops this took longer time than I thought, will ping this thread when I start.

**Comment by joychester** [comment]
i can wait, take your time, peter :)

**Comment by joychester** [comment]
BTW, the 3.9.1 release seems no docker image available, please double check.

**Comment by soulgalore** [comment]
hey you are right, thanks for telling me, I'm pretty sure I built and tagged them, but will do again.

**Comment by soulgalore** [comment]
building right now. We build the images at the Docker hub and that's cool but one annoying feature is that  the webhook (that tells Slack that the build is ready) is only fired on success, so if it fails I will not know.

**Comment by soulgalore** [comment]
now we have a tagged and the latest updated.

**Comment by joychester** [comment]
awesome, works now!

**Comment by joychester** [comment]
hey Peter,did you have bandwidth to work on this? :)

**Comment by soulgalore** [comment]
Hey @joychester no, but I can do it tomorrow. Need to think though if it can affect others, let me test a little.

**Comment by joychester** [comment]
Sure Peter, I can wait.

**Comment by soulgalore** [comment]
Hey @joychester ,
ok, hehe so, started looking at this, can you drop me an email (peter [at] solgalore [dot] com)  explaining what you need to do and I'll fix it, didn't fully follow how you want to automate the read of the file?

Best
Peter

**Comment by joychester** [comment]
Hi, peter, i got following error when sending the email..will send you the linkdedin message instead.
Delivery to the following recipient failed permanently:

     peter@solgalore.com

Technical details of permanent failure:
DNS Error: Address resolution of solgalore.com. failed: Domain name not found

**Comment by soulgalore** [comment]
Hey @joychester ,
I've pushed this to master now, is it possible for you to test that it works as you want before I do the release?

Best
Peter

**Comment by joychester** [comment]
Hi, Peter,

Great to hear that you fix this!

Currently I am using the Docker images on our cloud machine to do my
tests.. so can you help to make a temp docker images  to this snapshots so
that i can use this for test?

Thanks!
Cheng Chi

**Comment by soulgalore** [comment]
Hey Cheng,
yes download the canary tag: <pre>docker pull sitespeedio/sitespeed.io:canary</pre>
Best
Peter

**Comment by joychester** [comment]
Hi, Peter,

just run some tests against Canary build, seems the result is the same
under Har dir:

[cchi@slcd000ldr004 firefox]$ pwd
/nas/home/cchi/sitespeed/sitespeed-result/UN_ArtistPage/2015-10-14-04-39-24/har/firefox
[cchi@slcd000ldr004 firefox]$ ls
www.stubhub.com-performer-136034-0.html
www.stubhub.com-performer-136034-1.html
www.stubhub.com-performer-136034-2.html
www.stubhub.com-performer-136034-3.html
www.stubhub.com-performer-136034-4.html
www.stubhub.com-performer-136034-5.html
www.stubhub.com-performer-136034-6.html
www.stubhub.com-performer-136034-7.html
www.stubhub.com-performer-136034-8.html

There is still Hostname with '.' in the filename. Could you double check?

PS: here is my cmd to run the tests, i am using firefox to run against:

sudo /usr/bin/docker run --privileged --rm -v "/nas/home/cchi/sitespeed":/
sitespeed.io sitespeedio/sitespeed.io:canary sitespeed.io -u
http://www.stubhub.com/ -b firefox -n 9 -r ./sitespeed-result/UN_HomePage
--suppressDomainFolder

Thanks!
Cheng Chi

**Comment by soulgalore** [comment]
ooops I missed to change the docker file, will fix it later today!

**Comment by joychester** [comment]
I see, Then my test is valid :) How is the velocity Conf? a lot of Fun?

**Comment by soulgalore** [comment]
I've released 3.11.0 with the change.

**Comment by joychester** [comment]
Verified, it is fixed! Thanks Peter!

**Comment by soulgalore** [comment]
perfect!
