### ISSUE TITLE
About 4gLTE and --connectionRaw

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#747]
Why are we suppressing the FLAG for connectionRaw - its very useful... e.g. Native, 3g, 3gfastmobile, and cable - are not good enought... we need to be able to test 4glte - better to allow connectionRaw...

Since most of US carriers and customers are on 4glte

**Comment by soulgalore** [comment]
Hey @softwareklinic ,
you can send whatever config you want to Browsertime using  **--btConfig** and a JSON file with names as the key and value, yep the value that you want to send. Try that and see if it works.

Best
Peter

**Comment by softwareklinic** [comment]
Thank you very much – I will certainly check it out.

**Comment by softwareklinic** [comment]
--connectionRaw {downstreamKbps: $X, upstreamKbps: $Y, latency: $Z}
I'm interested in sending this + the --userAgent --- do we have any examples of user agent values... or should I just copy paste from what the browser header shows for the userAgent.... 

Also, since there are 3 values for ConnectionRaw - how do i construct the JSON?

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by soulgalore** [comment]
This is now in the docs and you can skip the JSON!
