### ISSUE TITLE
Question about Event/Annotations

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#748]
Can the annotations be created for past events?

curl -u LOGIN:PASSWORD -X POST "http://HOSTNAME:8080/events/" -d '{"what": "Deploy", "tags": "production deploy example", "data": "deploy of master branch, version 1.0.0"}'

**Comment by soulgalore** [comment]
Hey @softwareklinic 
yep it seems to be doable (haven't tested myself), checkout the *when* section here:
https://docs.hostedgraphite.com/advanced/annotations-and-events.html#create-a-single-event

Best
Peter

**Comment by soulgalore** [comment]
Please re-open if you didn't get it to work.
