### ISSUE TITLE
Having some troubles with graphite and sitespeed.io

### ISSUE THREAD

**Issue by m-frachet** [sitespeedio/sitespeed.io#749]
Hi,

I m actually getting an error when trying to use sitespeed.io with graphite.

Here's the related post : http://stackoverflow.com/questions/32694920/sitespeed-io-and-graphite

Thanks for your help

**Comment by softwareklinic** [comment]
I just responded to your post... on stackoverflow..

**Comment by soulgalore** [comment]
thanks @softwareklinic . Yep, so you actually need to configure the port individually. 

<pre>
 --graphiteHost <HOST> -  The Graphite host.
 --graphitePort <INTEGER>  - The Graphite port.  [2003]
</pre>

Best
Peter

**Comment by soulgalore** [comment]
Closing this, please re-open if it didn't work out for you.
