### ISSUE TITLE
Continuous flow of pages - peformance test

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#750]
I want to do a page performance for a continuous set of pages - e.g. customer going to the Home page, visiting a product learn page, then adding to cart, providing their address... etc...

How do I capture the page performance for such scenarios...

**Comment by soulgalore** [comment]
There's no good way to do it with sitespeed.io today, we are aiming for something like that in 4.0. I would use WebPageTest.org and use the scripting facility. What's missing there is a good way to capture measurements for the full flow like total page weight, total requests (at least that I know of) but you can measure each and every step individually): https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting

Best
Peter

**Comment by soulgalore** [comment]
closing this and hope it will be availible in 4.0 :)
