### ISSUE TITLE
Question about Authenticated pages

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#756]
Our website has multi-step authentication - where it seeks for the username on PAGE 1 -- takes the customers for secret question on PAGE 2 - and then asks for password on PAGE 3 -- how can we measure performance of these types of pages/site.. using sitespeed.io?

**Comment by soulgalore** [comment]
Hey @softwareklinic I would use the same as I described here: https://github.com/sitespeedio/sitespeed.io/issues/750 

Setup a webpagetest instance and use the script language to pick up the data needed.

Best
Peter
