### ISSUE TITLE
Command from documentation not working for WPT

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#758]
https://www.sitespeed.io/documentation/webpagetest/

sitespeed.io --wptScript wptScript.txt --wptHost my.wpt.host.com

this command gives an error saying you need to use -u or -f or -configFile

**Comment by soulgalore** [comment]
Hey @softwareklinic 
good, I've updated the docs, you always need to feed what URL or file containing URLs to sitespeed.io, else it will not know what to test!

best
Peter
