### ISSUE TITLE
Need more explanation

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#759]
While creating wptScript.txt - as directed below--- what is the meaning of {{{URL}}}

logData    0

// put any urls you want to navigate
navigate    www.aol.com
navigate    news.aol.com

logData    1

// this step will get recorded
navigate    news.aol.com/world

Then change your URL you want test (probably the last one) to } and then all occurrences of {{{URL}}} will then be replaced with the current URL that should be tested. Then run sitespeed (and add the parameters as you usually do):
sitespeed.io --wptScript wptScript.txt --wptHost my.wpt.host.com -u http://example.org

**Comment by soulgalore** [comment]
Hey @softwareklinic , the {{{URL}}} is a placeholder that will be changed to the real URL that you wnat to test. Say that you crawl with sitespeed, collect 100 URL:s and then want to test them with WebPageTest and a script, write the script and where you want to test that specific URL, add the placeholder and it will be changed in run time.

Best
Peter

**Comment by softwareklinic** [comment]
So, if I provide –f <filename> with 100 urls….

Now in wptScript.txt should it look like below

logData 0

navigate {{{URL}}}

would this add all those 100 URLs and pass to Webpagetest…

Keyur

**Comment by soulgalore** [comment]
yes, but it will not collect the metrics because of the logdata 0. You can check exactly what you can do in the webpagetest docs:
https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting
