### ISSUE TITLE
WebPageTest scores not showing in Graphite

### ISSUE THREAD

**Issue by mtwalsh** [sitespeedio/sitespeed.io#760]
Hi,

It's quite possible I'm just not looking in the right place, but I can't seem to find the scores from WebPageTest in Graphite e.g.

* score_cache
* score_cdn
* score_cookies
* score_keep-alive
* score_minify
* score_combine
* score_compress
* score_etags

I want to use these scores to generate similar optimisation grades (A to F) as the WebPageTest results page.

I'm not passing through a custom `wptConfig.json` and I coudn't see anything in the [list of options](https://github.com/marcelduran/webpagetest-api#test-works-for-runtest-method-only) that I might be lacking.

Thanks.

**Comment by soulgalore** [comment]
Hey @mtwalsh !
with the current version we only pick up a couple of key metrics like speedindex and render, the values we cannot do in sitespeed.io ourselves right now. There's an issue about picking up more values but I havent given it any love.
Best
Peter

**Comment by mtwalsh** [comment]
Ah, that explains it!  Thanks for your reply.  Would be great to be able to capture the WPT scores.

**Comment by soulgalore** [comment]
yes I agree (at least for some of them). Lets see if we can make it happen in 4.0.

**Comment by mtwalsh** [comment]
Thanks, that would be great.  Although, now I have a better grasp of the sitespeed.io rules having the scores from WPT seems less important in my mind.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
