### ISSUE TITLE
Yslow analysis failed by adding --waitscript 

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#761]
by adding --waitscript , it will stop the Yslow running properly:

[cchi@slcd000ldr004 sitespeed]$ sudo /usr/bin/docker run --privileged --rm -v "/nas/home/cchi/sitespeed":/sitespeed.io sitespeedio/sitespeed.io:3.11.0 sitespeed.io -u http://www.stubhub.com/ -b firefox -n 6 -r ./sitespeed-result/UN_HomePage_WaitScript --suppressDomainFolder --waitScript 'return window.document.getElementsByClassName("event-title").length > 0'
Fri Oct 16 07:14:16 UTC 2015
ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf)
Google Chrome 45.0.2454.101
Mozilla Firefox 41.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 2.6.32-431.el6.x86_64', Node.js: 'v0.10.25', sitespeed.io: '3.11.0', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.11.0'
info: Will crawl from start point http://www.stubhub.com/ with crawl depth 1
info: Will analyze 1 page
**info: Running YSlow for http://www.stubhub.com/ [phantomjs]**
**error: Error running yslow for url 'http://www.stubhub.com/': { [Error: Command failed: ] killed: false, code: 1, signal: null }**
Starting proxy on port 2001, will wait at most 15000 ms

After removing the --waitscript, the tests runs correctly.

**Comment by soulgalore** [comment]
Hey @joychester , did you config to run phantomjs 2? could be that the doc is missing that, you need phantom2 for it to work. is there an example in the docker readme, not sure will check when im home.
best
peter

**Comment by joychester** [comment]
Hi, Peter, 
right, seems the installed version is PhantomJS: '1.9.8'..
how can i switch to  PhantomJS 2.0  or do i need to install my own Phantomjs? Any document references?

**Comment by soulgalore** [comment]
Hey Cheng, 
it's bundled in the container, just add <pre>--phantomjsPath /usr/local/phantomjs/bin/phantomjs</pre> and you have 2.0 (I'll add it to the docker page, now it's only on the perfromance dashboard, that's hard to find!).

**Comment by joychester** [comment]
Sure, please let me know once you add to the docker page :)

**Comment by joychester** [comment]
verify the --phantomjsPath /usr/local/phantomjs/bin/phantomjs works in my docker image. Thanks! :+1:
