### ISSUE TITLE
[New Feature] Resource Timing API support

### ISSUE THREAD

**Issue by joychester** [sitespeedio/sitespeed.io#762]
Hi, Peter, 

As Phantomjs is not support Resource Timing API currently(https://bugs.webkit.org/show_bug.cgi?id=61138), adding Resource Timing API support is critical for SPA performance measurement.

Nightmare API sounds a good option, as it switch from Phantomjs to Extron, which supports resource timing API after my testing. so this should an option to integrate electron in the future:
https://github.com/segmentio/nightmare/issues/200

Thanks!
Cheng Chi

**Comment by soulgalore** [comment]
Hi @joychester ,
so how do you wanna use it? We pick up the resource timing metrics today for the browsers that support in Browsertime but we dont do anything with it using sitespeed.io but I think the raw data is stored in the browsertime json file.
Best
Peter

**Comment by joychester** [comment]
Hey, Peter, 
One possible way is to integrate the nightmare API into sitespeed.io to get some perf metrics data.
we can discuss further to see if this really matters to most of users of sitespeed.io

Thanks!
Cheng Chi

**Comment by joychester** [comment]
Hi, Peter, 

revisit this ticket, are you getting a chance to look at the nightmare API as it has been released nightmare 2.0 a few month back, relative stable release currently. sounds good to write page testing(they use promise to do test automation) and decent API they expose. Are you consider to integrate this together with your 4.0 open source release. This should be a complementary for page tests.

**Comment by soulgalore** [comment]
Hi Cheng,
no I haven't looked at it. In the coming 4.0 Browsertime will have support to run Selenium scripts (for login etc) and for the first release we plan only to use Chrome/Firefox, but later maybe we can add more.

I didn't fully understood what extra you need? Lets check and see if we can fix it.

Best
Peter

**Comment by joychester** [comment]
Hi, Peter, 
This is just a new feature coming into my mind when i first saw the idea of nightmare v2 coming out(nightmare v1 is using phantomjs too, too many call backs i need to write to test a complex scenario), I just feel to write nightmare v2 test is more elegant so integrating with sitespeed.io would be a good complementary for page(especially multiple steps) tests. (my personal feeling, but your insights with this)

It is basically doing the same as Selenium Webdriver tests actually, but in a headless way using Electron(http://electron.atom.io/), so concurrent page tests using nightmare API should be consuming less HW resources. So that's why i also wrote a project called "Smurfs" to do concurrent page tests by nightmare v2 API: https://github.com/joychester/Smurfs_v2

This also can easily expose the navigation/resource/user timing API, so i would suggest to check it out once you have time  :)

**Comment by soulgalore** [comment]
Cool, I'll test Smurfs later when I have the time :)

The aim with 4.0 is first support "real" browsers even though that electon is cool.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
