### ISSUE TITLE
Error when running sitespeed.io with firefox

### ISSUE THREAD

**Issue by Tissa1** [sitespeedio/sitespeed.io#763]
I have always this error when running sitespeed with firefox 

Fetching http://www.cybercom.com (1 of 3)
[Error: Timed out waiting for the WebDriver server at http://******/hub]
error: Error running browsertime: [Error: Timed out waiting for the WebDriver server at http://*****/hub]
info: Running browsertime for firefox http://www.cybercom.com/sv/
.
.
.
.

Stopping proxy
error: Could not generate HAR for http://www.cybercom.com/Legal-notice/Cookies/ { [Error: ENOENT, no such file or directory '/home/aa/sitespeed-result/www.cybercom.com/2015-10-19-10-32-36/data/har/firefox/www.cybercom.com-Legal-notice-Cookies-.har']
  errno: 34,
  code: 'ENOENT',
  path: '/home/aa/sitespeed-result/www.cybercom.com/2015-10-19-10-32-36/data/har/firefox/www.cybercom.com-Legal-notice-Cookies-.har',
  syscall: 'open' }

How could I solve it ?

**Comment by soulgalore** [comment]
Hey @Tissa1 
looks like the Firefox version and the Selenium version is out of sync. Which version of Firefox & sitespeed.io and what OS are you using?

Best
Peter

**Comment by Tissa1** [comment]
*Mozilla Firefox 41.0.2
*Ubuntu 14.04.3 LTS
*sitespeed.io version 3.10.0

**Comment by pydubreucq** [comment]
Hi,
Do you run xvfb ?
Bye

**Comment by Tissa1** [comment]
Hi, 
yes i have runnnig it with this commande   : Xvfb :0 -ac -screen 0 1024x768x24 &

**Comment by soulgalore** [comment]
Hi @Tissa1 ,
can you show me exactly how you run it? tested with the Docker image that match those versions and it worked:
<pre>
docker pull sitespeedio/sitespeed.io-firefox
docker run --privileged --rm sitespeedio/sitespeed.io-firefox sitespeed.io -u http://www.sitespeed.io -b firefox
</pre>
Best
Peter

**Comment by Tissa1** [comment]
i have tested the example in the web site sitespeed.io https://www.sitespeed.io/documentation/graphs/
$ sitespeed.io -u http://www.cybercom.com --graphiteHost localhost -m 5 --graphiteNamespace cybercom -b firefox -n 11

**Comment by Tissa1** [comment]
When I execute this commande , i have Error downloading dependent layers on Docker install

*Pulling repository sitespeedio/sitespeed.io-firefox
29aa4782c029: Error pulling image (3.7.1) from sitespeedio/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/lib/x86_64-linux-gnu/libcgmanager.so.0.0.0: no space left on device cgmanager.so.0.0.0: no space left on device ite /var/lib/docker/aufs/diff/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/lib/x86_64-linux-gnu/libcgmanc564df0a2c42: Error pulling image (3.9.1) from sitespeedio/sitespeed.io-firefox, lchown /var/lib/docker/aufs/diff/d3a1f33e8a5a513092f01bb7eb1c2abf4d711e5105390a3fe1ae2248cfde1391/bin/bash: no such file or directory fde1391/bin/bash: no such file or directory speedio/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/d3a1f33e8a5a513092f01bb7eb1c2abf4d711e5105390a3fe1ae2248cfde1391/bin/echo: no space left on de26b4155f828: Error pulling image (3.6.0) from sitespeedio/sitespeed.io-firefox, lchown /var/lib/docker/aufs/diff/e118faab2e16f9d858fcec0d86c9148e9b0fa021697239745f3253f367941dcc/bin/bash: no such file or directory 7941dcc/bin/bash: no such file or directory peedio/sitespeed.io-firefox, lchown /var/lib/docker/aufs/diff/e118faab2e16f9d858fcec0d86c9148e9b0fa021697239745f3253f367941dcc/bin/run-parts: no such file or directory cc/bin/run-parts: no such file or directory o/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/f3c84ac3a0533f691c9fea4cc2ceaaf43baec22bf8d6a479e069f6d814be9b86/bin/less: no space left on device 814be9b86/bin/less: no space left on device tespeedio/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/6071b4945dcf0886af97cc4782a189cef303fcc43a3d9813aa9fef86e1f7a318/lib/udev/hwdb.d/20-pci-vendor02cd6abba1b6: Error pulling image (latest) from sitespeedio/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/d3a1f33e8a5a513092f01bb7eb1c2abf4d711e5105390a3fe1ae2248cfde1391/lib/udev/hwdb.bin: no space edca0424729b: Error pulling image (3.9.0) from sitespeedio/sitespeed.io-firefox, lchown /var/lib/docker/aufs/diff/d3a1f33e8a5a513092f01bb7eb1c2abf4d711e5105390a3fe1ae2248cfde1391/bin/ip: no such file or dire21981614ccde: Error pulling image (3.7.0) from sitespeedio/sitespeed.io-firefox, mkdir /var/lib/docker/aufs/diff/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/etc/initramfs-tools/scripts/nfs-premount: no space left on device ripts/nfs-premount: no space left on device  lchown /var/lib/docker/aufs/diff/d3a1f33e8a5a513092f01bb7eb1c2abf4d711e5105390a3fe1ae2248cfde1391/bin/cat: no such file or directory cfde1391/bin/cat: no such file or directory peedio/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/e118faab2e16f9d858fcec0d86c9148e9b0fa021697239745f3253f367941dcc/lib/udev/hwdb.d/20-pci-vendorf942954e207c: Error pulling image (3.8.0) from sitespeedio/sitespeed.io-firefox, write /var/lib/docker/aufs/diff/6071b4945dcf0886af97cc4782a189cef303fcc43a3d9813aa9fef86e1f7a318/lib/x86_64-linux-gnu/libblkid.so.1.1.0: no space left on device /libblkid.so.1.1.0: no space left on device
6071b4945dcf: Error downloading dependent layers
e118faab2e16: Error downloading dependent layers
511136ea3c5a: Download complete
f3c84ac3a053: Error downloading dependent layers
83e4dde6b9cf: Error downloading dependent layers
2015/10/19 13:33:57 Could not find repository on any of the indexed registries.*
