### ISSUE TITLE
-wptConfig issue

### ISSUE THREAD

**Issue by Quualudes** [sitespeedio/sitespeed.io#764]
Hi,
Im having an issue when trying to feed a JSON file into -wptConfig

I get the error...

$ sitespeed.io -f wpt_scripts/myurls.txt -n 1 -d 0 --wptHost www.webpagetest.org --wptKey MyPrivateAPIKey -wptConfig wpt_scripts/MyJASONfile.json
--threads: You must specify an integer of how many processes/threads that will analyze your page>

If I try and run the same commands and parameters without appending -wptConfig directory/MyJASONfile.json to the end everything runs well.  

The contents of MyJASONfile.json is as follows....

[
  {
    "location": "ec2-us-east-1:Chrome",
  },
  {
    "location": "ec2-us-west-1:Chrome",
  }
]

If I try and specify a number of --threads I still get the same error.  Any help would be appreciated. Thanks.

**Comment by Quualudes** [comment]
Thanks for getting back to me so quick…tried your suggestion and no change.

**Comment by soulgalore** [comment]
Hi @Quualudes ,
in you example you have only one minus sign <pre>-wptConfig</pre> it should be two for a parameter name like <pre>--wptConfig</pre> Is that copy/paste error? If so, add exact how you run it and I can have a look!
Best
Peter

**Comment by Quualudes** [comment]
Hi Peter,
Thanks so much for chiming in here...Yes I was was using -wptConfig instead of --wptconfig thanks for catching that.  I am now getting a different error though, below is the readout from terminal:

$ sitespeed.io -f wpt_scripts/myurls.txt -n 1 -d 0 --wptHost www.webpagetest.org --wptKey MyPrivateAPIKey --wptConfig wpt_scripts/MyJSONfile.json 
undefined:7
  },
  ^
SyntaxError: Unexpected token }
    at Object.parse (native)
    at Object.module.exports.getFileAsJSON (/usr/local/lib/node_modules/sitespeed.io/lib/util/fileHelpers.js:22:17)
    at Object.nomnom.help.options.wptConfig.transform (/usr/local/lib/node_modules/sitespeed.io/lib/cli.js:392:22)
    at Object.ArgParser.setOption (/usr/local/lib/node_modules/sitespeed.io/node_modules/nomnom/nomnom.js:463:21)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/nomnom/nomnom.js:261:20
    at Array.reduce (native)
    at Object.ArgParser.parse (/usr/local/lib/node_modules/sitespeed.io/node_modules/nomnom/nomnom.js:223:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/sitespeed.io/lib/cli.js:480:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Thanks!

**Comment by soulgalore** [comment]
Hi again,
I think it's the trailing commas <pre>"location": "ec2-us-east-1:Chrome",</pre> , you have some examples for the config file here if you scroll down https://www.sitespeed.io/documentation/webpagetest/#configuration

Best
Peter

**Comment by Quualudes** [comment]
Thanks!

Thats exactly what the problem was, that fixed the issue.

On a separate issue I’m trying to test another site and it’s returning a number of errors.   Any ideas why?  Everything worked well for the first site I tried.

$ sitespeed.io -f wpt_scripts/myurls.txt -n 1 -d 0 --wptHost www.webpagetest.org --wptKey MyPrivateAPIKey --wptConfig wpt_scripts/MyJSONfile.json
info: OS: 'darwin 14.5.0', Node.js: 'v0.12.1', sitespeed.io: '3.11.0', PhantomJS: '1.9.8', java: '1.6.0_65', browsertime: '0.11.0'
info: Will analyze 1 page
info: Running YSlow for http://www.cain-biologics.com [phantomjs]
info: Running WebPageTest http://www.cain-biologics.com pollResults=10, timeout=10000, firstViewOnly=false, runs=1, private=true, aftRenderingTime=true, location=ec2-us-east-1:Chrome, connectivity=Cable, video=true
info: Running WebPageTest http://www.cain-biologics.com pollResults=10, timeout=10000, firstViewOnly=false, runs=1, private=true, aftRenderingTime=true, location=ec2-us-west-1:Chrome, connectivity=Cable, video=true
error: Could not fetch data for aggregator: TTFBWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: BytesWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: FirstPaintWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ImageSavingsWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ImageTotalWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: LoadTimeWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: RenderWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: RequestsWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ServerRTTWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: SpeedIndexWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: userTiming: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: VisualCompleteWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:210
    if (browserAndLocation.response.data.median.repeatView) {
                                               ^
TypeError: Cannot read property 'repeatView' of undefined
    at /usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:210:48
    at Array.forEach (native)
    at collectWPT (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:197:28)
    at Object.exports.processPage (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:58:5)
    at /usr/local/lib/node_modules/sitespeed.io/lib/collector.js:126:7
    at Array.forEach (native)
    at Collector.collectPageData (/usr/local/lib/node_modules/sitespeed.io/lib/collector.js:125:19)
    at processAnalysisResults (/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:185:14)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:68:7
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:46:16

**Comment by soulgalore** [comment]
hello again, hmm seems that we got an error from WPT but no error object. if you add --verbose to the run, all the json from wpt is logged, then we can see whats wrong. 
Best
Peter

**Comment by Quualudes** [comment]
Hi Peter,

Thanks for the tip.  Attached below is the output of the run with --verbose included...


$ sitespeed.io -f wpt_scripts/myurls.txt -n 1 -d 0 --wptHost www.webpagetest.org --wptKey MyPrivateAPIKey --wptConfig wpt_scripts/MyJSONfile.json --verbose
info: OS: 'darwin 14.5.0', Node.js: 'v0.12.1', sitespeed.io: '3.11.0', PhantomJS: '1.9.8', java: '1.6.0_65', browsertime: '0.11.0'
info: Will analyze 1 page
info: Running YSlow for http://www.cain-biologics.com [phantomjs]
verbose: Done processing url in yslow: http://www.cain-biologics.com
info: Running WebPageTest http://www.cain-biologics.com pollResults=10, timeout=10000, firstViewOnly=false, runs=1, private=true, aftRenderingTime=true, location=ec2-us-east-1:Chrome, connectivity=Cable, video=true
info: Running WebPageTest http://www.cain-biologics.com pollResults=10, timeout=10000, firstViewOnly=false, runs=1, private=true, aftRenderingTime=true, location=ec2-us-west-1:Chrome, connectivity=Cable, video=true
verbose: Got the following from WebPageTest:{"response":{"statusCode":200,"statusText":"Ok","data":{"testId":"151024_26_243476cc9e260caf6ef671e8a78fd4e9","summary":"http://www.webpagetest.org/result/151024_26_243476cc9e260caf6ef671e8a78fd4e9/","testUrl":"http://www.cain-biologics.com","location":"ec2-us-east-1:Chrome","from":"Virginia USA - EC2  - <b>Chrome</b> - <b>Cable</b>","connectivity":"Cable","bwDown":5000,"bwUp":1000,"latency":28,"plr":0,"mobile":0,"completed":"Sat, 24 Oct 2015 08:46:26 +0000","tester":"i-68f6b5d7","testerDNS":"172.31.0.2","successfulFVRuns":0,"average":{},"standardDeviation":{}}}}
verbose: Got the following from WebPageTest:{"response":{"statusCode":200,"statusText":"Ok","data":{"testId":"151024_6M_73e2d6fd895611a7159e9aeed9143f56","summary":"http://www.webpagetest.org/result/151024_6M_73e2d6fd895611a7159e9aeed9143f56/","testUrl":"http://www.cain-biologics.com","location":"ec2-us-west-1:Chrome","from":"California USA - EC2 - <b>Chrome</b> - <b>Cable</b>","connectivity":"Cable","bwDown":5000,"bwUp":1000,"latency":28,"plr":0,"mobile":0,"completed":"Sat, 24 Oct 2015 08:46:30 +0000","tester":"i-6f6c60ad","testerDNS":"172.31.0.2","successfulFVRuns":0,"average":{},"standardDeviation":{}}}}
error: Could not fetch data for aggregator: TTFBWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: BytesWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: FirstPaintWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ImageSavingsWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ImageTotalWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: LoadTimeWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: RenderWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: RequestsWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: ServerRTTWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: SpeedIndexWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: userTiming: err: [TypeError: Cannot read property 'firstView' of undefined]
error: Could not fetch data for aggregator: VisualCompleteWPT: err: [TypeError: Cannot read property 'firstView' of undefined]
/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:210
    if (browserAndLocation.response.data.median.repeatView) {
                                               ^
TypeError: Cannot read property 'repeatView' of undefined
    at /usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:210:48
    at Array.forEach (native)
    at collectWPT (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:197:28)
    at Object.exports.processPage (/usr/local/lib/node_modules/sitespeed.io/lib/collectors/pages.js:58:5)
    at /usr/local/lib/node_modules/sitespeed.io/lib/collector.js:126:7
    at Array.forEach (native)
    at Collector.collectPageData (/usr/local/lib/node_modules/sitespeed.io/lib/collector.js:125:19)
    at processAnalysisResults (/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:185:14)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:68:7
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:46:16

Thanks!

**Comment by daustin2011** [comment]
This happens when wpt returns an empty element for the run (average, median, etc are all empty). WPT has failed to run the test and the json is incomplete like so: 

verbose: Got the following from WebPageTest:{"response":{"statusCode":200,"statusText":"Ok","data":{"testId":"someID","summary":"someURL","testUrl":"someURL","location":"someLoc</b>","connectivity":"Cable","bwDown":5000,"bwUp":1000,"latency":28,"plr":0,"mobile":0,"completed":"Mon, 07 Dec 2015 17:58:31 +0000","tester":"foo","testerDNS":"foo","successfulFVRuns":0,"average":{},"standardDeviation":{}}}}

if successfulFVRuns is 0, this error will occur. This error happens inconsistently, and seems to be related to the timeout for certain pages. It does not occur in every case for the same URL, but if the error occurs of course nothing is written to graphite. 

The well-known "Catched an uncaught exception:TypeError: Cannot read property" bug also results from this wpt error.

The webpagetest record will show:
The testing completed but failed.
Skipped repeat view, first view failed: Test run failed with result code -1

**Comment by soulgalore** [comment]
Yep so if I remember correctly we check for the error object in the WebPageTest API but sometimes the error is only reported as an error code and I missed that when I implemented it. Lets fix that in the coming version.

**Comment by hinok** [comment]
In documentation here https://www.sitespeed.io/documentation/webpagetest/

```
The default location will be overidden and the connectivity will be set to 3G. Feed it with: –wptConfig yourFile.json
```

should be probably

```
The default location will be overidden and the connectivity will be set to 3G. Feed it with: --wptConfig yourFile.json
```

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
