### ISSUE TITLE
Windows 10 :: Error while installing sitespeed.io using command "npm install sitespeed.io -g"

### ISSUE THREAD

**Issue by pranatikumari** [sitespeedio/sitespeed.io#765]
![error_sitespped](https://cloud.githubusercontent.com/assets/12223278/10704758/c1bcbdbc-79f6-11e5-8929-d8bbf7efe9ee.png)

**Comment by lippea** [comment]
The error shows cannot find python

**Comment by beenanner** [comment]
@pranatikumari make sure you have python installed correctly as @lippea noted. You can check by running "python --version" from the command line.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
