### ISSUE TITLE
Docker sitespeed.io can't write in symlinked resultBaseDir

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/sitespeed.io#766]
Hi,

Following docker sitespeed.io hangs when we have resultBaseDir as symlink. In following command "sitespeedio" directory in "public" directory is a symlink:

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:3.8.1 sitespeed.io -u "https://www.yahoo.com/" -r "public/sitespeedio" --outputFolderName "SSIO_12345" --suppressDomainFolder -d 0 -b firefox -n 5 --screenshot --seleniumServer http://127.0.0.1:4444/wd/hub

Do you have any idea? It does work fine when I run sitespeed.io command without docker.

**Comment by soulgalore** [comment]
Hey @tufandevrim , do you run on Linux or Mac OS X? Using Mac you can only map files that are wihin the users home dir.

Else could be that symlinks outside doesn't work inside Docker. But you should be a able to fix that by just mounting another volume right? Or change the first one "$(pwd)":/sitespeed.io?

Best
Peter

**Comment by tufandevrim** [comment]
Hey Peter,

I test my changes on Mac OS X first. My project is in my home directory. As I mentioned running the same command without docker works fine:
sitespeed.io -u "https://www.yahoo.com/" -r "public/sitespeedio" --outputFolderName "SSIO_12345" --suppressDomainFolder -d 0 --screenshot

The point is here that we want to keep the sitespeed.io results outside of our project home directory, so when we remove our app via "npm uninstall", we dont want previous test results wiped out. Our app is simple node/express app which runs the docker under the hood. 

I think this is docker related issue and dont know how to fix this. Our production is RHEL7 btw.

**Comment by soulgalore** [comment]
Hey @tufandevrim 
ok cool, so I think on OS X it will not work (if you symlink outside of your home dir).

But then could you just mount the dir that you want to use? Googled problems with symlinks and Docker and I think that should be the solution. Like <pre>-v /path/to/where/you/want/your/data:/sitespeed.io</pre> or could be that I not follow exactly :)

Best
Peter

**Comment by tufandevrim** [comment]
@soulgalore oh I see. I have already 
'-v "$(pwd)":/sitespeed.io'
which print my app path. So I need to run docker.
Thanks for the tip
