### ISSUE TITLE
Make phantomjs and slimerjs optional

### ISSUE THREAD

**Issue by anselmbradford** [sitespeedio/sitespeed.io#767]
Phantomjs + slimerjs together are about a 130MB download. I work on a project that uses sitespeed.io but we're using chromedriver for our other testing so would like to use chromedriver with sitespeed.io too. Is there a way the project could be architected that wouldn't require phantomjs and slimerjs be downloaded? Thanks for any ideas!

**Comment by tobli** [comment]
Hi, thanks for the feedback! Peter and myself are right now discussing how to architect Sitespeed 4, in order to improve in a number of areas. Greater modularity is one area we're looking at. I hope we'll have something to suit your needs.
/Tobias

**Comment by soulgalore** [comment]
Hey @anselmbradford ,
yes as Tobias says 4.0 will be better but it is at least a couple of months away before we can release the first beta. But you could probably start using parts of it earlier depending on what you do/need.

What exactly do you need right now? Do you want the rules or do you need the timings? The rules are currently tied to phantom/slimer but if you need timinings you could use https://github.com/tobli/browsertime (and run Chrome). 

Best
Peter

**Comment by soulgalore** [comment]
We removed them for 4.0.
