### ISSUE TITLE
Issue Installing Sitespeed with SlimerJS

### ISSUE THREAD

**Issue by mjbyrnes4664** [sitespeedio/sitespeed.io#769]
I am unable to install sitespeed.io on my Mac with OS X 10.11 with this error.  I have tried many ways of getting slimerjs installed but still see this issue.  Issue is also seen on a Mac with OS X 10.5.5

> slimerjs@0.9.2 install /usr/local/lib/node_modules/sitespeed.io/node_modules/slimerjs
> node install.js

Downloading http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2
Saving to /usr/local/lib/node_modules/sitespeed.io/node_modules/slimerjs/slimerjs/slimerjs-0.9.2-mac.tar.bz2
Receiving...
Error requesting archive.
Status: 403
Request options: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "download.slimerjs.org",
  "port": null,
  "hostname": "download.slimerjs.org",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2",
  "path": "/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2",
  "href": "http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2"
}
Response headers: {
  "cache-control": "no-cache",
  "pragma": "no-cache",
  "content-type": "text/html; charset=utf-8",
  "connection": "close",
  "content-length": "1599"
}
Make sure your network and proxy settings are correct.
...
...
...
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "sitespeed.io"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! slimerjs@0.9.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slimerjs@0.9.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the slimerjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls slimerjs
npm ERR! There is likely additional logging output above.

**Comment by tdmoneybanks** [comment]
+1 @soulgalore this is the same issue i am having btw.

**Comment by dmillerme7** [comment]
Have you tried running npm install with sudo?
sudo npm install -g sitespeed.io

**Comment by 0xR** [comment]
The slimerjs download server is having some trouble under load from aws. Read more here: https://groups.google.com/forum/#!topic/slimerjs/nIi0ZqSNzBs

**Comment by soulgalore** [comment]
Hey @0xR 
I'll push the release with the fix tonight. A couple of things:
* After the summer we will push 4.0 get in touch if you need help with upgrading, the new version will be less resource intensive and maybe can save you money (+test on http2 and all the other new good things).
* I think running Docker and keeping your own Docker hub would be better for your use case. For 4.0 I can add some docs on different scenarios so it's easier to understand the dependencies.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
