### ISSUE TITLE
Custom metric without using WebPageTest

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#771]
Wondering whether sitespeed.io can measure custom metric without using WebPageTest. Since the user timings can be collected User Timing API via browser, is there a way we can get the numbers on dashboard without WPT?   I see the documentation of https://www.sitespeed.io/documentation/webpagetest/#custom-metrics, but is is under the webpagetest, hence the question.  

Thanks
Abha

**Comment by soulgalore** [comment]
Hey Abha,
yes you can. There are two different ways of doing custom metrics in sitespeed.io:

* User Timings API. If you add user timings on your page, they will automatically be picked up by sitespeed.io as in http://dashboard.sitespeed.io/dashboard/db/user-timing-and-custom-metrics (that is without webpagetest. All user timings thats created on your page will be under *.timings as a Graphite key. For the HTML output, I don't have in my head now if you need to configure something to see it. If you need it, let me know and I'll look.

* Custom Metrics is a javascript snippet that will be executed in the browser (check out https://www.sitespeed.io/documentation/browsers/#custom-metrics) Then you can run your own code in your browser and pick up what you want, that will also automatically be sent to Graphite.

Best
Peter

**Comment by geekdave** [comment]
Thanks Peter! We have two use cases for tracking user timings. 

1) Graphing results over time as your dashboard example represents perfectly
2) Failing a build with the grunt-sitespeed plugin if a user timing is greater than a configured budget value

Is there a way to accomplish the second use case currently?

Thanks!

**Comment by soulgalore** [comment]
Hey @geekdave ,
yes that should work (haven't used it in a while. You can look at: 
https://www.sitespeed.io/documentation/performance-budget/#testing-user-timings

There's an example for the budget with user timing and then you can use it within the grunt plugin (don't have it in my head how to set it up correctly).

Just let me know if you need more help.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
