### ISSUE TITLE
DNS Lookup Time always 0

### ISSUE THREAD

**Issue by une6** [sitespeedio/sitespeed.io#772]
Hi guys,

I noticed that the timings.domainLookUpTime is always 0, and as such since it was following the formula:

domainLookupEnd - domainLookupStart

i checked and both the End and Start have the same value. is this normal or an issue?

thanks in advance

**Comment by soulgalore** [comment]
Hi @une6 
what browser and what OS are you using? I've seen the same thing and I think the problem is that we can't empty the DNS cache in a good way today using Selenium (@tobli do you know)? We are looking into other solutions for 4.0, lets see the coming months :)

Best
Peter

**Comment by une6** [comment]
Hiya,

We're using CentOS 7.1 and firefox. thanks and i hope it works out well.

Best regards

**Comment by bt-wbertl** [comment]
Hi,

I have the same problem. I'm using Debian 8.2 and Firefox.

Thanks.

Best
Wolfgang

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
