### ISSUE TITLE
Anyway to include BasicAuth in website lists?

### ISSUE THREAD

**Issue by insightevancrouch** [sitespeedio/sitespeed.io#774]
Hi. When running regular tests on a whole bunch of sites stored in a .txt using the --sites flag, is there any way to specify username/password combos per site (if applicable)?

Thanks

**Comment by soulgalore** [comment]
no not today, only the same basic auth for all site. lets keep this issue open and lets make it a request for 4.0.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
