### ISSUE TITLE
Real User Monitoring support

### ISSUE THREAD

**Issue by une6** [sitespeedio/sitespeed.io#776]
Hi, 

Currently we really really like the numbers and how things are in the grafana and sitespeed, this is via a Synthetic monitoring point of view setup. It's really great and the numbers shown are really what we need. And right now, we're just wondering if sitespeed also has support for Real User Monitoring perspective wherein we can inject a sitespeed javascript file into our page, and let it send all the similar metrics into sitespeed, and then grab the numbers into grafana. Or something similar. Forgive me if i might have just missed this from the documents, But i'd love to hear from you guys about this :)

thanks.

**Comment by soulgalore** [comment]
Hi @une6 ,
thanks for the kind words, great that you like what we do :)

There's no RUM built in today. If you use Google Analytics, you can take that data and insert it into Graphite with https://hub.docker.com/r/sitespeedio/gatographite/

However better is to use [Boomerang](https://github.com/lognormal/boomerang) it's open source and the best RUM solution out there. And then use Boomcatch and get the data to Graphite using statds. @tollmanz has done a good writeup https://www.tollmanz.com/rum-monitoring-boomerang-boomcatch-datadog/

Best
Peter

**Comment by une6** [comment]
excellent info soulgalore, thanks i'll definitely check those out.

cheers

**Comment by dmillerme7** [comment]
@soulgalore Boomerang is great stuff, thanks for the tip.
Go sitespeed.io!
Looking forward to v4

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
