### ISSUE TITLE
is there any way to send metrics to StatsD?

### ISSUE THREAD

**Issue by ewe-biwu** [sitespeedio/sitespeed.io#777]
Hi,

Our team wants to use SiteSpeed.IO to run some web tests, and build dashboard in Grafana for page performance analysis.  From sitespeed.io documentation, https://www.sitespeed.io/documentation/performance-dashboard/#graphite, it seems like data will be directly sent to Graphite, but our team currently mainly support this flow: data from application -> statsD -> Graphite-> grafana, and it might not work if data directly goes to Graphite.  i'm  wondering, if there is any way SiteSpeed.IO can send data to StatsD and then from our end to pump data to Graphite?

Thanks!
Bingbing

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by scabenga** [comment]
@soulgalore, just checking if this was ever resolved.  I have the same setup as @ewe-biwu describes above, however when sending the metrics to statsd, nothing shows in Graphite.

From what i can tell is that the syntax for statsd is slightly different.

Graphite:
`echo "metric_name metric_value `date +%s` | nc -q0 127.0.0.1 2003`

StatsD
`echo "metric_name:metric_value|type_specification" | nc -u -w0 127.0.0.1 8125`

**Comment by soulgalore** [comment]
@scabenga no it will not, it is as you said. If we want StatsD to work we need PR that makes it configurable.
