### ISSUE TITLE
Is number of times (-n --no) param ignored?

### ISSUE THREAD

**Issue by twirls** [sitespeedio/sitespeed.io#779]
I'm having troubles running sitespeed multiple times for url

I have tried to run it like this (or take urls from text file):
sitespeed.io.cmd -u http://mypage.url --no 1 -p http://127.0.0.1:8888 -d 0 -m 1 -v

However I still see 3 request to mypage.url in fiddler

Is there something I'm missing?

**Comment by soulgalore** [comment]
Hey @twirls ,
thanks the report. In the current version, the number of times is how many times we will use a browser to fetch navigation timing data. What you are seeing now is PhantomJS Yslow and the crawler that access the url. In the coming 4.0 we'll have different structure but it looks like this:
* 1 request from the crawler (if you choose to crawl)
* x request from PhantomJS YSlow to check the rules
* -n requests for the browser to fetch the timings (if you configure to run a browser).


Best
Peter

**Comment by twirls** [comment]
Thanks for reply @soulgalore!

So, if I understand you correctly, currently, in order to test all my urls x times, do I have to call sitespeed x times?

Kind Regards,
Evgeny

**Comment by soulgalore** [comment]
No, sorry I was unclear. If you want to fetch timings 7 times (and use the median of the runs) use:
<pre>-n 7 -b firefox</pre>

you need to configure the browser + number of runs.

Best
Peter

**Comment by twirls** [comment]
Ok. Thanks!

Kind Regards,
Evgeny
