### ISSUE TITLE
Binary "sitespeed.io" not found after installation

### ISSUE THREAD

**Issue by jamesmortensen** [sitespeedio/sitespeed.io#782]
I have been trying to install sitespeed.io on Ubuntu 14.04 unsuccessfully.  I used the following command:

```
$ sudo npm install --unsafe-perm -g sitespeed.io
```

While the installation appears to be successful, the sitespeed.io binary cannot be found.  I've also tried cloning the GitHub project, and same thing, there appears to be no sitespeed.io binary.  Can someone please provide more clarification on how to install sitespeed.io and whether or not this is an issue in the package itself.  Thank you.

I've also attached the installation logs. Please let me know if there are any other missing details or troubleshooting steps I can provide.  I am happy to help. 

[sitespeed-install-log.txt](https://github.com/sitespeedio/sitespeed.io/files/48224/sitespeed-install-log.txt)

**Comment by soulgalore** [comment]
Hey @jamesmortensen ,
thatnks for the report. 

How do you run it? I think the installtion works but could it be that it isn't in the users path where you try to run it? Can you check your path and <pre>which sitespeed.io</pre>?

Best
Peter

**Comment by jamesmortensen** [comment]
Hey Peter, thanks for the quick reply.  Good point to check the PATH. It didn't get installed where I thought it was, but I found it by doing a grep search:

```
jem@x.x.x.x:~$ which sitespeed.io
jem@x.x.x.x:~$ 
```

"which" doesn't find the location of the binary.

```
jem@x.x.x.x:~$  locate sitespeed.io|grep "sitespeed.io$"
/home/jem/.npm/simplehar.sitespeed.io
/home/jem/.npm/sitespeed.io
/home/jem/.npm/registry.npmjs.org/simplehar.sitespeed.io
/home/jem/.npm/registry.npmjs.org/sitespeed.io
/opt/jenkins-addons/sitespeed.io
/opt/local/node-v4.2.2-linux-x64/bin/sitespeed.io
/opt/local/node-v4.2.2-linux-x64/lib/node_modules/sitespeed.io
/opt/local/node-v4.2.2-linux-x64/lib/node_modules/sitespeed.io/node_modules/simplehar.sitespeed.io
/opt/local/node-v4.2.2-linux-x64/lib/node_modules/sitespeed.io/node_modules/.bin/simplehar.sitespeed.io
/usr/local/lib/node_modules/sitespeed.io
jem@x.x.x.x:~$ 
```

I did find the binary here:  /opt/local/node-v4.2.2-linux-x64/bin/sitespeed.io

My guess is that since apt-get installs an ancient, dusty version of Node.js, and I intalled manually, that the bin folder simply isn't in my PATH by default.  Editing my bash_profile with the following solves the issue:

```
export PATH=$PATH:/opt/local/node-v4.2.2-linux-x64/bin
```

Thanks for the tip!
James
