### ISSUE TITLE
Gathering sitespeed summary data for multiple sites

### ISSUE THREAD

**Issue by ziki88** [sitespeedio/sitespeed.io#786]
So far I'm loving the dashboard and what it can offer for me. I ran into an issue when comparing multiple sites. I went to run the docker command and the only way to collect a summary for each site was to pass the URL in a txt file using the --sites flag. Is this the correct way to execute the command, or am I doing something wrong? 

docker run --privileged --rm ... sitespeedio/sitespeed.io sitespeed.io --sites urls1.txt --sites urls2.txt --sites urls3.txt --sites urls4.txt --sites urls5.txt ...

**Comment by soulgalore** [comment]
Hello @ziki88
great :) yes it is if you don't do it manually in Grafana. By using the sites flag we also calculate summaries inside sitespeed.io, maybe we can do that simpler in the coming version.

I guess you could do it with just one file and then with Graphite/Grafana group/calculate values per domain but I don't have an example dashboard for that.

Best
Peter

**Comment by softwareklinic** [comment]
is the --sites or --f still valid???? with 4.0

**Comment by soulgalore** [comment]
@softwareklinic we haven't implemented --sites yet. You can see what works for the current alpha with --help.

**Comment by softwareklinic** [comment]
I.tried with just a text file with.list of urls that.worked

Sent from my iPhone

On Jun 30, 2016, at 6:37 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> we haven't implemented --sites yet. You can see what works for the current alpha with --help.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
