### ISSUE TITLE
Sitespeedio throws the following warning/error " killed: true,   code: null,   signal: 'SIGTERM' "

### ISSUE THREAD

**Issue by qa2015** [sitespeedio/sitespeed.io#788]
getting the following error, it was working fine all this while (the last time i perform sitespeedio test with the same command was back in 27th August 2015). Seems like something broken, pls assist.
the script executed on win 7 64-bit machine. I had tried with with ssl any and ignore ssl true too and it's the same

Pls take note the script executed is as below, but do check the log which outline the following "--ssl-protocol=any --ignore-ssl-errors=yes"

Log snippets
----------------

C:\Program Files\Jenkins\jobs\MyEG Sdn Bhd Website - Performance Optimization Test\workspace>C:\Users\Admin\AppData\Roaming\npm\sitespeed.io.cmd -u http://dev5.myeg.com.my/myegphp5/index.php -d 1 
info: OS: 'win32 6.1.7601', Node.js: 'v4.2.2', sitespeed.io: '3.11.1', PhantomJS: '2.0.0', java: '1.7.0_67', browsertime: '0.12.0'
info: Will crawl from start point http://dev5.myeg.com.my/myegphp5/index.php with crawl depth 1
info: Will analyze 33 pages
info: Running YSlow for http://dev5.myeg.com.my/myegphp5/index.php [phantomjs]
info: Running YSlow for http://dev5.myeg.com.my/myegphp5/index.php?p=location_site [phantomjs]
info: Running YSlow for http://dev5.myeg.com.my/myegphp5/index.php?p=rt_RTD_summons [phantomjs]
info: Running YSlow for http://dev5.myeg.com.my/myegphp5/index.php?p=insolvency_bankrupt [phantomjs]
info: Running YSlow for http://dev5.myeg.com.my/myegphp5/index.php?p=ppz_income [phantomjs]
error: Error running yslow for url 'http://dev5.myeg.com.my/myegphp5/index.php': { [Error: Command failed: C:\Users\Admin\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\phantomjs\lib\phantom\phantomjs.exe --ssl-protocol=any --ignore-ssl-errors=yes C:\Users\Admin\AppData\Roaming\npm\node_modules\sitespeed.io\lib\headless\scripts\yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file C:\Program Files\Jenkins\jobs\MyEG Sdn Bhd Website - Performance Optimization Test\workspace\sitespeed-result\dev5.myeg.com.my\2015-12-08-16-41-31\data\yslow\dev5_myeg_com_my-myegphp5-index.php-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://dev5.myeg.com.my/myegphp5/index.php
]
  killed: true,
  code: null,
  signal: 'SIGTERM',

**Comment by soulgalore** [comment]
Hey @qa2015 ,
what happens is that the script in PhantomJS times out (that's why the killed: true log).

When you access that URL in your browser do all the timing events (like loadEventEnd) happen? Does the page wait on something special?

Best
Peter

**Comment by qa2015** [comment]
hey soulgalore..thnx for hint.."Does the page wait on something special?"

i found the website waiting for a javascript for an analytic tool which only define for PROD not on in the dev site. commenting out the javascript, enable sitespeed.io executed command and return proper result. Thanks, cheers !!!

**Comment by qa2015** [comment]
Hello Peter,
How can I scan login based app..I tried with basicAuth but only pages
without login appeared in result..

**Comment by soulgalore** [comment]
Hey @qa2015 ,
to login with the current sitespeed version, you need to do that outside and then pass the cookie using request header. In the next version we will support login. You can also use WebPageTest to test login pages, they have their own scrip language todo a login.

Best
Peter

**Comment by qa2015** [comment]
hello peter,
how shall i set cookies using request header?

**Comment by qa2015** [comment]
if using --basicAuth..then command would be (given that username is abc and
password is 123456) --basicAuth abc:123456

**Comment by qa2015** [comment]
Request header means the sessionid of the website?

**Comment by soulgalore** [comment]
Hello @qa2015 ,
yep. Here you can check out how you one user solved it: https://github.com/edx/edx-sitespeed 

But we plan to release login/scripting soon :)

Best
Peter
