### ISSUE TITLE
Bootstrap layout could be done more efficiently in the summary page

### ISSUE THREAD

**Issue by teomaragakis** [sitespeedio/sitespeed.io#789]
Instead of creating a .row element for every three info boxes, there should be one to include them all, an their classes should be different to make layouts better in tablet and wide screen resolutions. I could do a push request if interested.

**Comment by soulgalore** [comment]
Hey @teomaragakis ,
thanks for the report. We are focusing on 4.0 right now and try to minimize the fixes on the current version. However  I would love to have your input the HTML on the new version, when we have a branch ready. If it's ok for you it would be great if I can ping you and you can have a look? Will take a month or so before we have it up and running though.

Best
Peter

**Comment by teomaragakis** [comment]
Hi @soulgalore! Absolutely! Don't forget me, huh? :)

**Comment by soulgalore** [comment]
@teomaragakis promise I won't :)

**Comment by soulgalore** [comment]
ping @teomaragakis we have started with the HTML/CSS for 4.0 now, do you have time to help out? We've dropped bootstrap though :)

**Comment by dmillerme7** [comment]
Hi @soulgalore I'm familiar with bootstrap but if you need a set of eyes I can help out some.

**Comment by soulgalore** [comment]
Hey @dmillerme7 yes please :) 
 
I've started created issues what I know needs to be done (tagged with design), check them out or try 4.0 by checking out the branch, then run npm install and <code>bin/sitespeed.js https://www.sitespeed.io -n 1</code> to get some result pages.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by teomaragakis** [comment]
Boy, was I slow on that ping. Sorry. :(

**Comment by soulgalore** [comment]
@teomaragakis we have lot others thing to do if you have some free time and wanna improve the front end code :)
