### ISSUE TITLE
Unable to connect to Graphite container from another container on the same node

### ISSUE THREAD

**Issue by jurajseffer** [sitespeedio/sitespeed.io#790]
I started `sitespeedio/graphite` container as well as `grafana/grafana:2.5.0` on the same AWS node. Grafana container was linked to graphite container and was unable to connect to Graphite web service on exposed port `8080`. It replied with connection refused. When port is mapped to localhost on the AWS node itself, connecting to localhost:8080 works. This problem seems to be caused by the fact that graphite web is bound to localhost in the startup script https://github.com/sitespeedio/docker-graphite-statsd/blob/master/daemons/graphite.sh#L3

Can the host be changed from `host=127.0.0.1` to `host=0.0.0.0`?

**Comment by soulgalore** [comment]
Hey @jurajseffer 
thanks for the report. Yes, I need to test that. You can ovveride that file at startup, can you try that? Doing like this:
<pre>  -v /path/to/graphite.sh:/opt/graphite/daemons/graphite.sh</pre>

Best
Peter

**Comment by jurajseffer** [comment]
Thanks @soulgalore, I forked, modified the file and built an image, haven't tried mounting on top. The result with `0.0.0.0.` was that 6 processes with `usr/bin/python /opt/graphite/webapp/graphite/manage.py runfcgi daemonize=false host=0.0.0.0 port=8080` were started and when connecting on port `8080` to it, it accepts the connection but hangs forever. Grafana reports "Testing..." when adding Graphite as source, something isn't right.

**Comment by jurajseffer** [comment]
It seems this is not a problem for my use case after all as I should be connecting to graphite web via nginx on port `80`, not `8080` directly. It's still a problem for someone who wants to connect to that python service.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
