### ISSUE TITLE
when running sitespeed.io through a proxy the screenshot is not taken properly

### ISSUE THREAD

**Issue by daehin** [sitespeedio/sitespeed.io#791]
I am testing a proxy server for ad blocking. when i run sitespeed.io with the -p option it runs properly through the trasparent proxy but the screenshot is not done with this option enabled ( there is no ad blocking, that is shown in the page assets, neither the widget we inject in the HTML code ).

**Comment by soulgalore** [comment]
HI @daehin 
thanks for reporting! Do you have time to look into this yourself? Trying to finish off the new version (4.0) the coming months and will try to focus on this. The screenshot is done today using phantomjs in a specific script, could be that it misses the proxy option.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
