### ISSUE TITLE
webfonts not being reported

### ISSUE THREAD

**Issue by lbod** [sitespeedio/sitespeed.io#792]
I see a couple of previous issues with this e.g. #699 but not sure if these are relevant.

Running PhantomJS we noticed that the reports were showing 0 fonts per page, which isn't correct. I saw there were reported bugs for PhantomJS that it wouldn't load fonts using font-face.
So I ran sitespeed with both Firefox and Chrome browsers and still got the same results, 0 fonts.

I haven't debugged anything yet but is this a known issue?

**Comment by soulgalore** [comment]
Hey @lbod ,
thanks for reporting. In the current version we base the the numbers from PhantomJS, we don't use the request from Chrome/Firefox ... but we got 4.0 on the way where we base everything on Chrome/FF. Don't have a release date yet but th ecode for identifying will soon be released so you can help us test it out if you can. 

Best
Peter

**Comment by lbod** [comment]
Hi @soulgalore and thanks.
Yes happy to test. I presume it's the downstream issue reported in PhantomJS which is the cause? And that sitespeed has never reported web fonts then?

I had a debug round the app, it's a pretty large codebase! But i'd be happy to try and fix any bugs if needed

**Comment by soulgalore** [comment]
Great. Yep it's in phantomjs/YSlow. The code for that in the new version will be small and much easier to debug.

Best
Peter

**Comment by soulgalore** [comment]
should work in 4.0

**Comment by lbod** [comment]
Thanks so much for all the updates with 4 but it seems like this should be reopened.

I ran a crawl expecting woff being reported and they aren't using the docker image and a firefox run. I ran it from another machine so will update with the docker command and output tomorrow.

**Comment by soulgalore** [comment]
Hey @lbod we could have missed that. The matching for what's a font happens in PageXray: https://github.com/sitespeedio/pagexray/blob/master/lib/util.js#L6 

Please feel free to send a PR that fixes it or the URL you test, so it's easy to reproduce!

**Comment by lbod** [comment]
Will do, sorry I've been a bit lax and I'd rather send a pr but I'm switching between work and home.
So I'll need to debug and do it properly, I'll have a look for tests too.

**Comment by soulgalore** [comment]
@lbod do you have time to just give me the mime type you are using for woff so I can run it trough our tests?

**Comment by lbod** [comment]
@soulgalore I was running the tests at this very moment when I realised we're serving them (woff) as text/plain so it's obviously a server misconfiguration. There wasn't even any warnings in the browser console but still being served correctly.

Sorry again but I think this is fine to close. 

However thinking this through, the mime type is the right way to determine the content but at the same time, browsers can and do guess content types from file extensions, actual content etc. Does more work need to be done to accommodate this or is it better to stick to the actual W3C specs ?

**Comment by soulgalore** [comment]
ah cool. I think it can be ok for now, I need to spend some time to look into how it actually works.

**Comment by beenanner** [comment]
@soulgalore / @lbod this would be a good rule to add to https://github.com/sitespeedio/coach to let the user know they have incorrectly configured content-types. Possible comparing file extension to content-type. @lbod feel free to file a ticket over there or if you would like a PR. :-)

**Comment by lbod** [comment]
@beenanner ok cool, i'll give it a go. I've had a think about it already using the official iana spec, I'll have a play first and look to submit a pr, then raise a ticket over at the coach.
