### ISSUE TITLE
Selenium web-driver timeouts

### ISSUE THREAD

**Issue by jurajseffer** [sitespeedio/sitespeed.io#793]
Is there anything that can be done to address timeouts during page loading? The page may appear largely OK to the user but some of the assets may be blocked. Is there a way to still get the timings within the results?

I tried using `--waitScript 'if (window.performance && window.performance.timing){ return ((window.performance.timing.requestStart > 0) && ((new Date).getTime() - window.performance.timing.requestStart > 10000 ));} else { return true;}'` but no luck.

```
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 46.0.2490.71 
Mozilla Firefox 41.0.2
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.16.0-4-amd64', Node.js: 'v4.2.1', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.12.0'
info: Will analyze 1 page
info: Running YSlow for https://url [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for https://url firefox
info: Running browsertime for firefox https://url
Fetching https://url (1 of 10)
{ [TimeoutError: Timed out waiting for page load.]
  code: 21,
  state: 'timeout',
  message: 'Timed out waiting for page load.',
  name: 'TimeoutError',
  stack: 'TimeoutError: Timed out waiting for page load.\n    at new bot.Error (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20\n    at promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)\n    at goog.defineClass.notify (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)\n    at promise.Promise.notify_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)\n    at goog.async.run.processWorkQueue (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)\n    at process._tickCallback (node.js:366:9)' }
error: Error running browsertime: { [TimeoutError: Timed out waiting for page load.]
```

**Comment by soulgalore** [comment]
Hey @jurajseffer 
so it's Selenium that times out? Think that is hardcoded right now to 2 minutes. If you load the URL in your browser then your should be able to trim the waitscript to check that it works. If you can get it to work there it "should" work running in browsertime.

Best
Peter

**Comment by jurajseffer** [comment]
Hi, I think it's Selenium. I'll give it a try.

**Comment by cgoldberg** [comment]
@soulgalore, yup pageLoadTimeout is a constant 2 mins set in browsertime and passed to selenium webdriver:
https://github.com/tobli/browsertime/blob/master/lib/browsertime.js#L88

```javascript
pageLoadTimeout = 120000;
```
```javascript
driver.manage().timeouts().pageLoadTimeout(pageLoadTimeout);
```

(I think the selenium default is 5 mins)

----

@jurajseffer but what does "some of the assets may be blocked" mean?  Are you running in a test environment that can't access certain assets?  If so, you might look at black-holing the blocked assets so you get smoother pageloads.  In fact, browsertime recently added support for request blocking using BrowsermobProxy:  https://github.com/tobli/browsertime/issues/98

the black hole proxy pattern is useful functional/acceptance testing to reduce automation flakiness... but it also changes your measurements from what a real user would experience, so any performance assessments you make are likely not representative or accurate at that point :)

Interesting stuff none-the-less...
for more info, see:
 * http://www.schooner.com/~loverso/no-ads/#blackhole
 * https://engineering.groupon.com/2013/misc/black-hole-proxy-for-selenium-testing/

**Comment by jurajseffer** [comment]
@cgoldberg "some of the assets may be blocked" means that the site and sitespeed.io runs in China where many things such as tracking/social are blocked. I suspect that the site works OK for the user as they're loaded async etc. but if browsertime/selenium has to wait for all assets to finish loading, I will never get the results. Finding which assets exactly are timing out is quite difficult as they're often dynamic.

Ideally, I'd like to get a report from sitespeed for what was loaded until a custom set timeout occurs. In other words, I'd be fine with sitespeed reporting it took for example 200ms for backend, 1s to start painting etc with the full page render being equal to my custom set timeout.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
