### ISSUE TITLE
About 4.0 and possible enhancements

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#794]
One of the key enhancements that would make this tools extremely powerful is for authenticated users... E.g. these days the websites use all type of complex authentication mechanisms to be able to make it as difficult for hackers to get into the site....

Is there any plan to configure site speed for authenticated users flows...

Also, one important thing is to define flows... e.g. i might have about 20 pages from start - 2- finish... but i want to give logical names to the steps involved...e.g. Step 1- provided address information
step 2 - added products to cart
step 3- provided payment information
step 4 - submitted order

then i want to be able track how the pages under each flow are performing... anonymous or authenticated.. both...

**Comment by soulgalore** [comment]
Hey @softwareklinic 
we will support login/authenticated in 4.0 and probably even do in next 3.x. You will use selenium code to do your own login (or whatever you want todo). About naming for steps, not sure what's the best solution, lets sync later on that.

Best
Peter

**Comment by softwareklinic** [comment]
Sure sounds great.



Regards,
Keyur

On Dec 23, 2015, at 1:16 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic>
we will support login/authenticated in 4.0 and probably even do in next 3.x. You will use selenium code to do your own login (or whatever you want todo). About naming for steps, not sure what's the best solution, lets sync later on that.

Best
Peter

**Comment by softwareklinic** [comment]
Is the authentication support added in 3.x>

**Comment by soulgalore** [comment]
No it will not. We thought it would be but then we saw that it would take so long time to implement. But soon you can start testing in 4.0.
