### ISSUE TITLE
Errors when running docker container with drone

### ISSUE THREAD

**Issue by geekdave** [sitespeedio/sitespeed.io#795]
Trying out [drone](http://drone.io) as a Jenkins alternative, which has first-class docker support.  

But when running sitespeed, it seems to bomb-out on the Selenium part, probably due to some docker networking weirdness.

I realize this is more of a "learn docker networking" question, but just wondering if you had tried out drone, and if you had any quick ideas about this:

Here is my drone yml file:

```
$ cat .drone.yml 
build:
  image: sitespeedio/sitespeed.io
  commands:
    - sitespeed.io -u http://sitespeed.io -b firefox -d 0
```

Logs below.  The relevant part seems to be `Error: Timed out waiting for the WebDriver server at http://127.0.0.1:53040/hub`

```
[info] Pulling image plugins/drone-git:latest
$ git init
Initialized empty Git repository in /drone/src/build/FEOps/drone-sitespeed-test/.git/
$ git remote add origin https://build/FEOps/drone-sitespeed-test.git
$ git fetch --no-tags --depth=50 origin +refs/heads/master:
From https://build/FEOps/drone-sitespeed-test
* branch            master     -> FETCH_HEAD
* [new branch]      master     -> origin/master
$ git reset --hard -q 81b202bf983ca1188a5896624f319105545bbae5
$ sitespeed.io -u http://sitespeed.io -b firefox -d 0
info: OS: 'linux 4.1.12-boot2docker', Node.js: 'v4.2.2', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_85', browsertime: '0.12.0'
info: Will analyze 1 page
info: Running YSlow for http://sitespeed.io [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for http://sitespeed.io firefox
info: Running browsertime for firefox http://sitespeed.io
Fetching http://sitespeed.io (1 of 3)
[Error: Timed out waiting for the WebDriver server at http://127.0.0.1:53040/hub]
error: Error running browsertime: [Error: Timed out waiting for the WebDriver server at http://127.0.0.1:53040/hub]
Stopping proxy
error: Could not generate HAR for http://sitespeed.io { [Error: ENOENT: no such file or directory, open '/drone/src/build/FEOps/drone-sitespeed-test/sitespeed-result/sitespeed.io/2016-01-01-00-13-18/data/har/firefox/sitespeed_io.har']
 errno: -2,
 code: 'ENOENT',
 syscall: 'open',
 path: '/drone/src/build/FEOps/drone-sitespeed-test/sitespeed-result/sitespeed.io/2016-01-01-00-13-18/data/har/firefox/sitespeed_io.har' }
info: Done analyzing urls
info: Wrote file assets.html
info: Wrote file domains.html
info: Wrote file errors.html
info: Wrote file hotlist.html
info: Wrote file pages.html
info: Wrote file rules.html
info: Wrote file index.html
info: Wrote file detailed-site-summary.html
info: Wrote file sitespeed_io.html
info: Wrote results to /drone/src/build/FEOps/drone-sitespeed-test/sitespeed-result/sitespeed.io/2016-01-01-00-13-18
info: The analyze took a minute (54 seconds)
expand_more
```

**Comment by soulgalore** [comment]
Hi @geekdave ,
no I haven't tried out drone.io, let me try when I'm back from the holidays in a couple of days.

You get that problem if XVFB isn't running, that should happen automatically and also the versions of Firefox & Chrome should be logged when you start the Docker container but I don't see that in your output?

Best
Peter

**Comment by bradrydzewski** [comment]
my guess is that the sitespeed Dockerfile uses a default entrypoint or command that starts selenium and xvfb. When using an image as a [build container](http://readme.drone.io/usage/build_test/), instead of a [compose container](http://readme.drone.io/usage/services/), drone will override the entrypoint and commands to run your build script.

again, this is just a guess, but in this case you may need to manually invoke whatever entrypoint script that the sitespeed container is invoking in your build script

**Comment by geekdave** [comment]
@soulgalore - The suggestion from @bradrydzewski (creator of drone!) indeed fixed the issue.  When drone starts the docker image, the `ENTRYPOINT` [defined here](https://github.com/sitespeedio/sitespeed.io-docker/blob/master/browsers/all/Dockerfile#L13) does not get executed, so I have to do it manually, ala:

```
build:
  image: sitespeedio/sitespeed.io
  commands:
    - /home/root/scripts/start.sh sitespeed.io -u http://sitespeed.io -b firefox -d 0
```

Closing as this works using the above commands.  Thanks everybody for talking it through!

**Comment by soulgalore** [comment]
cool :)
