### ISSUE TITLE
sitespeed failing for mobile URL's

### ISSUE THREAD

**Issue by sunil-jhamnani** [sitespeedio/sitespeed.io#796]
Hi,

I am running sitespeed using docker and this is the command I am using for one of the mobile URL:
docker run --privileged --rm -v /Users/sunil.jhamnani/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://m.bloomingdales.com/ --userAgent iphone -b chrome -n 3 -d 1 -m 1  --connection cable -r /tmp/ --graphiteHost 192.168.99.100 --seleniumServer http://127.0.0.1:4444/wd/hub

This the docker configuration I am using: 
OS: 'linux 4.1.13-boot2docker', Node.js: 'v4.2.2', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_85', browsertime: '0.12.0'

And I am getting this error:
Error running yslow for url 'http://m.bloomingdales.com': { [Error: Command failed: /usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua iphone --file /tmp/urls.txt/2016-01-06-08-03-45/data/yslow/m_bloomingdales_com-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://m.bloomingdales.com
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua iphone --file /tmp/urls.txt/2016-01-06-08-03-45/data/yslow/m_bloomingdales_com-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://m.bloomingdales.com' }
Starting proxy on port 2001, will wait at most 15000 ms 

If I run any desktop URL then everything goes well. 
Please help

**Comment by soulgalore** [comment]
Hi @sunil-jhamnani ,
thanks for the report.

Hmm, PhantomJS fails. One thing you can test is to use PhantomJS 2.0. You can do that by adding <code>--phantomjsPath /usr/local/phantomjs/bin/phantomjs</code> to your oneliner.

Best
Peter

**Comment by beenanner** [comment]
@soulgalore and @sunil-jhamnani I tried reproducing the error to see if I could help, but it seems to work for me out of the box. 

See: http://pastebin.com/4MSH9MgY

**Comment by beenanner** [comment]
Here it is with PhantomJS 2.0 which also passed successfully.

See: http://pastebin.com/FE5HbsHV

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
