### ISSUE TITLE
spaces in metric names from WPT

### ISSUE THREAD

**Issue by daustin2011** [sitespeedio/sitespeed.io#798]
Hi - I have been trying to get data from IE11 tests into graphite via sitespeed.io and WPT. Unfortunately, a space is inserted into the metric label that confuses graphite.

Here is an example from sitespeed output:
sitespeed.summary.my.testedwebsiteurl.com.timing.wpt.ap-southeast-2_ie11.cable.ie 11.repeatView.visualComplete.sum 4400 1452281671

Notice the space in "ie 11". Graphite cannot store data with spaces in the metric name, so this data is never stored.

This is a problem caused by WPT originally, here is the relevant JSON returned to sitespeed.io:
"location":"ap-southeast-2_IE11:IE 11","from":"Asia Pacific (Sydney) - <b>IE 11</b> - <b>Cable</b>"

How can we tell graphite to substitute a "_" in metric names when it encounters whitespace in a metric name?

Thanks!

R,
D-

**Comment by soulgalore** [comment]
Hi @daustin2011 and thanks for the report. I think I've missed the substition for that (spaces in the browser name), let me do a fix this weekend. I'll ping the issue when it's fixed.
 
Best
Peter

**Comment by daustin2011** [comment]
Thanks Peter!
R,
D-

**Comment by soulgalore** [comment]
Het @danielsamuels ,
fixed it this weekend but haven't had time to do the release, but now it is there: v3.11.2

It's updated in npm, the Docker containers will be finished later today.

Best
Peter

**Comment by danielsamuels** [comment]
Sorry, what's this about? Not sure if I've been tagged by mistake.

**Comment by soulgalore** [comment]
oops sorry @danielsamuels , that should have been @daustin2011

**Comment by danielsamuels** [comment]
No worries, just wanted to be sure!
