### ISSUE TITLE
YSlow not working for specific URL

### ISSUE THREAD

**Issue by web24365** [sitespeedio/sitespeed.io#801]
YSlow is giving errors on specific URL:

# docker run --privileged --rm -v /opt/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.cherrykoko.com --phantomjsPath /usr/local/phantomjs/bin/phantomjs  -r /tmp/ --graphiteHost 172.17.0.2 --seleniumServer http://127.0.0.1:4444/wd/hub
Wed Jan 13 07:15:17 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 46.0.2490.80 
Mozilla Firefox 42.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.13.0-49-generic', Node.js: 'v4.2.2', sitespeed.io: '3.11.1', PhantomJS: '2.0.0', java: '1.7.0_85', browsertime: '0.12.0'
info: Will crawl from start point http://www.cherrykoko.com with crawl depth 1
info: Will analyze 153 pages
info: Running YSlow for http://www.cherrykoko.com [phantomjs]
info: Running YSlow for http://www.cherrykoko.com/shop/shopdetail.html?branduid=28117&xcode=083&mcode=001&scode=&type=Y&sort=order&cur_code=083&GfDT=bW53UFw= [phantomjs]
info: Running YSlow for http://www.cherrykoko.com/shop/shopdetail.html?branduid=27460&xcode=001&mcode=002&scode=001&special=2&GfDT=amx3UlQ= [phantomjs]
info: Running YSlow for http://www.cherrykoko.com/shop/shopdetail.html?branduid=28049&xcode=001&mcode=003&scode=001&special=1&GfDT=bml3U1g= [phantomjs]
info: Running YSlow for http://www.cherrykoko.com/shop/shopdetail.html?branduid=28036&xcode=001&mcode=002&scode=001&special=1&GfDT=bm5+W19G [phantomjs]
error: Yslow output for 'http://www.cherrykoko.com/shop/shopdetail.html?branduid=28117&xcode=083&mcode=001&scode=&type=Y&sort=order&cur_code=083&GfDT=bW53UFw=' (stdout): FAIL to load http://www.cherrykoko.com/shop/shopdetail.html?branduid=28117&xcode=083&mcode=001&scode=&type=Y&sort=order&cur_code=083&GfDT=bW53UFw=

  /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js:306

error: Error running yslow for url 'http://www.cherrykoko.com/shop/shopdetail.html?branduid=28117&xcode=083&mcode=001&scode=&type=Y&sort=order&cur_code=083&GfDT=bW53UFw=': { [Error: Command failed: /usr/local/phantomjs/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /tmp/www.cherrykoko.com/2016-01-13-07-15-24/data/yslow/www_cherrykoko_com-shop-shopdetail.htmld9c04-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://www.cherrykoko.com/shop/shopdetail.html?branduid=28117&xcode=083&mcode=001&scode=&type=Y&sort=order&cur_code=083&GfDT=bW53UFw=
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/local/phantomjs/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /tmp/www.cherrykoko.com/2016-01-13-07-15-24/data/yslow/www_cherrykoko_com-shop-shopdetail.htmld9c04-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://www.cherrykoko.com/shop/shopdetail.html?branduid=28117&xcode=083&mcode=001&scode=&type=Y&sort=order&cur_code=083&GfDT=bW53UFw=' }
info: Running YSlow for http://www.cherrykoko.com/shop/shopdetail.html?branduid=27877&gf_ref=Yz0yb0VROWo= [phantomjs]
error: Yslow output for 'http://www.cherrykoko.com' (stdout): FAIL to load http://www.cherrykoko.com

  /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js:306

**Comment by soulgalore** [comment]
Hi @web24365 and thanks for the report. We have a known problem with Yslow PhantomJS version that it deosn't handle frontend redirect, could it be that (I did it check). If that's not the problem, try use PhantomJS 2.0, it's inlcuded in the container, just add <code>--phantomjsPath /usr/local/phantomjs/bin/phantomjs</code> to your run. Hope that helps!

Best
Peter

**Comment by web24365** [comment]
Do you have any other solution? I've seen many web sites using frontend redirect.

Best regards

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
