### ISSUE TITLE
Custom metrics not consistently sent to graphite

### ISSUE THREAD

**Issue by frankzzz** [sitespeedio/sitespeed.io#802]
I have configured a scripts folder with two scripts that fetch custom metrics. I have a cron set to fire up the sitespeed.io docker container every five minutes and hit a list of 5 url's (each url 5 times)....sometimes I see the custom metric data get sent to graphite, sometime not, its very inconsistent.

I'm verifying this by tcpdumping the interface and filtering for the custom metric i'm sending.

**Comment by soulgalore** [comment]
Hi Frank, thanks for the report. So do you see that it is actually not sent or that it isn't there in Graphite? When I get these kind of problems, I use the <code>--verbose</code> flag to sitespeed.io. It will log quite much and one of the things is all the keys and values sent to Graphite. There you can see if the metrics are there and the keys are right (like are there spaces or something else that messes up the keys). 

If the metrics actually are sent, it could be that we send to many metrics to Graphite, see https://www.sitespeed.io/faq/#i-dont-get-all-values-in-graphite
It isn't perfect in the current version we send too many values per default, it would be better to just send a important few and than make it configurable to send more, this will change in the coming version.

Please get back if you are able to backtrack where it's wrong and I'll help out.

Best
Peter

**Comment by frankzzz** [comment]
My graphite box is already set up with the MAX_CREATES_PER_MINUTE=inf .

I ran sitespeed with the verbose flag as you suggested and I can confirm that of the 7 url's I am analyzing on each run, I am only getting custom metrics sent to graphite for a random selection of 2 or 3 url's (of the total 7).

**Comment by soulgalore** [comment]
@frankzzz could you share the verbose log in a gist with some explanations or send it to me via email: peter AT soulgalore DOT com 

easier then to check, see if I can understand what's happening.

**Comment by frankzzz** [comment]
@soulgalore thanks, I just sent you a pastebin link

**Comment by soulgalore** [comment]
@frankzzz thanks, have had a busy week but will look at it tomorrow.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
