### ISSUE TITLE
Require phantomjs/slimer lazily

### ISSUE THREAD

**Issue by keithamus** [sitespeedio/sitespeed.io#805]
Firstly, thanks for the awesome project. It works amazingly and I really appreciate all the work you have all put into this.

I'm trying to use sitespeed.io with [Alpine Linux](http://www.alpinelinux.org/) in a Docker container ([this one](https://github.com/gliderlabs/docker-alpine)). 

The problem I'm running into, is if I run sitespeed, I get the following error:

```bash
bash-4.3# ./node_modules/.bin/sitespeed.io -u http://google.com
error: Error getting versions: { [Error: spawn /code/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /code/node_modules/phantomjs/lib/phantom/bin/phantomjs',
  path: '/code/node_modules/phantomjs/lib/phantom/bin/phantomjs',
  spawnargs: [ '--version' ],
  cmd: '/code/node_modules/phantomjs/lib/phantom/bin/phantomjs --version' }
error:  Error: spawn /code/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

That file exists, but the phantomjs binary dynamically links to libraries that don't exist on Alpine (as is my understanding). So, I thought I'd try slimer instead!

```bash
bash-4.3# ./node_modules/.bin/sitespeed.io -u http://google.com --headless slimer
error: Error getting versions: { [Error: spawn /code/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /code/node_modules/phantomjs/lib/phantom/bin/phantomjs',
  path: '/code/node_modules/phantomjs/lib/phantom/bin/phantomjs',
  spawnargs: [ '--version' ],
  cmd: '/code/node_modules/phantomjs/lib/phantom/bin/phantomjs --version' }
error:  Error: spawn /code/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

As far as I can see, this is because everywhere that phantomjs is required - it is required at the top of the file (e.g. [here](https://github.com/sitespeedio/sitespeed.io/blob/d49a94d49ca22f5964c28bece25d72d8ebc6143a/lib/analyze/yslow.js#L11-L12)), meaning I _always_ have to have it installed and working to even use sitespeed.

If these requires became lazy, I'm quite sure it'd fix my problem. I'm happy to investigate further - and even make a PR, but I wanted to make sure it was something you'd accept as a potential change before doing so.

**Comment by soulgalore** [comment]
Hi @keithamus and thanks for the kind words :)

Would be really cool to make it work on Alpine, thinking if it is worth to spend time now though? The background: We are working on the 4.0, we aim to do the "real" release in June, but hopefully a first alpha in March. We got the new structure up and running (soon public we hope) and need to do all the gluing and making it work. The new version will not use Phantom at all, we will only focus on Firefox/Chrome, because webkit in Phantom is getting older and older and diverting more from a real browser (however I really love PhantomJS!). 

Would be really cool if you can help out building the new sitespeed.io on Alpine? 

Best
Peter

**Comment by keithamus** [comment]
@soulgalore - that sounds awesome and I'd definitely like to help with that. Cards on the table: this is a project for work, and it has to be done by the end of the sprint. I could switch to using a full Debian Docker image and get it working, but our infrastructure is built around Alpine containers (for many reasons) and so I already have it (mostly) put together on Alpine. I've made the changes I need locally and it seems to work well. I guess what I'm trying to say is - if I could be so bold as to make the PR for this just to get my work done, that'd be swell.

**Comment by tobli** [comment]
Looks good! We'll merge later.

**Comment by soulgalore** [comment]
Yep lets sync and merge this tomorrow or Sunday. thanks @keithamus !
