### ISSUE TITLE
Error while using browser as chrome on a RHEL server

### ISSUE THREAD

**Issue by sunil-jhamnani** [sitespeedio/sitespeed.io#807]
I am running the normal docker command as: 
docker run --privileged --rm -v /data/sitespeed/iofiles:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -m 1 -u http://www.macys.com -b chrome -d 0 -n 1 --connection cable --phantomjsPath /usr/local/phantomjs/bin/phantomjs --seleniumServer http://127.0.0.1:4444/wd/hub

I have the setup on a RHEL server and I am getting this error when using chrome as a browser:

{ [UnknownError: chrome not reachable
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.13 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: '12537a898971', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.el7.x86_64', java.version: '1.7.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver]
  code: 13,
  state: 'unknown error',
  message: 'chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 60.13 seconds\nBuild info: version: \'2.48.2\', revision: \'41bccdd\', time: \'2015-10-09 19:59:12\'\nSystem info: host: \'12537a898971\', ip: \'172.17.0.4\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'3.10.0-327.el7.x86_64\', java.version: \'1.7.0_91\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver',

Everything works well while using the firefox as browser. Please help

**Comment by sunil-jhamnani** [comment]
Hi @soulgalore 

Please provide you suggestions for this issue also.

**Comment by soulgalore** [comment]
Hey @sunil-jhamnani 
checkout the solution in this thread: https://github.com/sitespeedio/sitespeed.io-docker/issues/5 

Setting no sandbox will hopefully fix the problem. Maybe we can make it default in coming versions.
Best
Peter

**Comment by sunil-jhamnani** [comment]
Thank a ton @soulgalore 
It worked like a magic for me.
