### ISSUE TITLE
Export to CSV for https://run.sitespeed.io/

### ISSUE THREAD

**Issue by TrevorJTClarke** [sitespeedio/sitespeed.io#810]
I would LOVE to see CSV export available, and have created a super fast solution to extract the current results:

[sitespeed.io to CSV](https://gist.github.com/TrevorJTClarke/2c126e193cbc218c6007)

If I had time, I would add to the site.
thanks!

**Comment by soulgalore** [comment]
Hey @TrevorJTClarke ,
cool :) I'll put it in low prio right now (will only work on 4.0 things the coming months) but if you later on have the time to do a PR, you can find the code that generates the result page here: https://github.com/sitespeedio/run.sitespeed.io/tree/master/worker 

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
