### ISSUE TITLE
Error: Forbidden for WebPageTest

### ISSUE THREAD

**Issue by sunil-jhamnani** [sitespeedio/sitespeed.io#814]
Tried running this command to get the WebPageTest data in sitespeed:

docker run --privileged --rm -v /Users/yc03764/sitespeed/iofiles:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -m 1 --sites urls/desktop/mcom.txt --wptHost www.webpagetest.org --wptKey XXXX -b firefox -d 0 -n 3 --connection cable --phantomjsPath /usr/local/phantomjs/bin/phantomjs --seleniumServer http://127.0.0.1:4444/wd/hub 

The yslow and browsertime works fine but it gives a Forbidden error for WebPageTest. This is the error:

info: Running WebPageTest http://www.abc.com/ pollResults=10, timeout=600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Dulles:Firefox, connectivity=Cable, video=true
error: WebPageTest couldn't fetch info for url http://www.abc.com/{ [WPTAPIError: Forbidden] name: 'WPTAPIError', code: 403, message: 'Forbidden' }
error: Error running WebPageTest: { [WPTAPIError: Forbidden] name: 'WPTAPIError', code: 403, message: 'Forbidden' }

I checked in the WebPageTest code and found that this error code with Forbidden message will come when not authenticating as an admin. but have no idea about this.

Please help me to resolve this issue

**Comment by soulgalore** [comment]
hey @sunil-jhamnani 
and you are really sure that the key is right? check by running with a crazy key and check if you get the same message.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
