### ISSUE TITLE
Support for Kairos DB in sitespeed?

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#815]
Hi,
Is there any roadmap/plan/discussions for supporting kairos db for saving the time series data in addition to Graphite for sitespeed?

Abha

**Comment by soulgalore** [comment]
Hey @abhagupta , in the current version you could build it yourself using a postTask (https://www.sitespeed.io/documentation/developers/#add-your-own-post-tasks), there you have access to all the metrics that sitspeed.io collected and can store it wherever you want. 

However, I would wait for 4.0 or at least for the alpha that we hope we can show in March, then it will be easier to build your own plugins + you can share them with other users. 

Best
Peter

**Comment by abhagupta** [comment]
Thank you @soulgalore . using the above feature, I could easily store data in Mongodb and Kairosdb.  I will close the issue
