### ISSUE TITLE
How to increase the timeout time

### ISSUE THREAD

**Issue by sunil-jhamnani** [sitespeedio/sitespeed.io#816]
Hi @soulgalore 

I got this error:
"Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called."

I had a look on the issues similar to this and found that the issue is related to timeout time which can be set by using the --btConfig but didn't found how to do it. Please let me know if increasing the timeout can resolve this issue or there is any other way around.

Thanks in advance.

**Comment by sunil-jhamnani** [comment]
Hi all,
Please give you comment on this. I am stuck some where in the  middle ho installation

**Comment by tobli** [comment]
Hi Sunil,
We can't tell what's wrong, or what can fix it, without more information. The "Callback was already called" error does occur from time to time with the current version of Browsertime. A new version which improves on stability among other things is under development.

Regarding timeouts some values are hard coded in Browsertime in the current version. If you check out the source from GitHub you can update the timeout values, build a custom version and see if that helps.

**Comment by sunil-jhamnani** [comment]
Thansk @tobli for the suggestions. Also I am attaching the complete stack trace of the error below:

**error: Error running yslow for url 'http://www.intimecrm.com/': { [Error: Command failed: /usr/lib/node_modules/sitespeed.io/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /tmp/sites/2016-02-01-11-49-13/www.intimecrm.com/data/yslow/www_intimecrm_com-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://www.intimecrm.com/
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /tmp/sites/2016-02-01-11-49-13/www.intimecrm.com/data/yslow/www_intimecrm_com-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://www.intimecrm.com/' }
error: Error running yslow for url 'http://www.intimecrm.com/': { [Error: Command failed: /usr/lib/node_modules/sitespeed.io/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /tmp/sites/2016-02-01-11-50-25/www.intimecrm.com/data/yslow/www_intimecrm_com-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://www.intimecrm.com/
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/usr/lib/node_modules/sitespeed.io/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=yes /usr/lib/node_modules/sitespeed.io/lib/headless/scripts/yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file /tmp/sites/2016-02-01-11-50-25/www.intimecrm.com/data/yslow/www_intimecrm_com-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://www.intimecrm.com/' }
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
**
Let me know if it helps or I can help in any other way to contribute to this.
