### ISSUE TITLE
sitespeed hanging 

### ISSUE THREAD

**Issue by sunil-jhamnani** [sitespeedio/sitespeed.io#817]
Hi,

Its again something strange i am facing. I am running the latest version of sitespeed but the docker container gets hang after running the sitespeed command 4-5 times. The docker container is not stopping using the docker stop command and also not responding on docker kill command. The only option is to reboot the ubuntu machine This the error I got:

Wed Feb  3 10:00:02 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 48.0.2564.82 
Mozilla Firefox 44.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
error: Error getting versions: { [Error: Command failed: /bin/sh -c java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/bin/sh -c java -version' }
error:  Error: Command failed: /bin/sh -c java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

Please help

**Comment by soulgalore** [comment]
Hey @sunil-jhamnani 
can you show me how you start the container? Do you follow the instructions [here](https://hub.docker.com/r/sitespeedio/sitespeed.io/)?

Best
Peter

**Comment by sunil-jhamnani** [comment]
Hi @soulgalore 

I was earlier working on the version 3.11.3 and it working fine so tried with the same version again but got the same issue on the Ubuntu machine. I think may be the issue is with the ubuntu machine itself not with sitespeed so I am trying to find the resolution of that.

Closing the ticket for now. Thanks for you response.
