### ISSUE TITLE
Sitespeed.io metric for number images are less than what Chrome or WebPageTest provides

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#818]
This is more of a clarification question rather than an issue.  I am noticing that metrics for Number of Images per page for my tests are coming out to be almost half (31) of what Chrome or WebpageTest provides (~70).  I ran Yslow manually on my site and I saw the same number which sitespeed is spitting out. That makes sense, but why so much difference?  eg. www.walmart.com

**Comment by soulgalore** [comment]
Hey @abhagupta 
I can check later, but that's one thing why we are changing to only use real browsers in 4.0.

Did you see what the difference is, any image type that YSlow don't pick up? One thing could be that you load the images after the onLoad event, then you need to configure when to end the test. If you using PhantomJS2 you can do that by https://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test

I'll get back tonight or tomorrow when I checked.

Best
Peter

**Comment by abhagupta** [comment]
Thanks @soulgalore  for quick reply. I think you may be right about loading the images after onLoad event. I am looking into this as well. Few other things I noted, if I just run the test on Chrome and no YSlow,  I do not get the metrics for Number of Requests or Number of Img Requests. I set up the budgets for requests and they were ignored when just chrome was used.  I understand that the rules need to be set to specify what needs to be measured. Is number of requests for just chrome one of the rules that I will have to set?
