### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by VladimirCacicArapovic** [sitespeedio/sitespeed.io#819]
Hi just want to check how to test page after login page with sitespeed.io.
So i have user and pass and then button click and then wait and then test speed.

Thanks

**Comment by soulgalore** [comment]
Hey @VladimirCacicArapovic !
Today there's no automated way to do it in sitespeed.io. Some users has solved it by login the user with another tool and used the login-cookie and pass that when running sitespeed.io. In 4.0 (released this summer) we will have support for running selenium scripts, so you can login the user.

You can use WebPageTest.org and https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting to login the user and measure using that tool, either standalone or drive it using sitespeed.io.

Best
Peter

**Comment by VladimirCacicArapovic** [comment]
Hi, thanks for fast reply,
just maybe we can help others with the same problem.
I made login script with casperjs
but i don't know how i can start sitespeed.io script after.

Thanks

casper.start(startUrl, function() {
    this.evaluate(function() {
        document.querySelector('input#logonpassfield').value = 'password';
        document.querySelector('input#logonuidfield').value = 'user';
        document.querySelector('input#button').click();
    });
    start sitespeedio here
});

**Comment by VladimirCacicArapovic** [comment]
Hi i have good news.. I am trying with cookie.Please can u check if cookie is in good format.

I was trying to find any solution (sample cookie), but with no luck ..

`[{"domain":".test.net","expires":"Sun, 14 Feb 2016 03:23:09 GMT","expiry":1455420189,"httponly":false,"name":"_gat","path":"/","secure":false,"value":"1"},{"domain":".test.net","expires":"Tue, 13 Feb 2018 03:13:09 GMT","expiry":1518491589,"httponly":false,"name":"_ga","path":"/","secure":false,"value":"4224234234"},{"domain":"test.net","httponly":false,"name":"PortalNew","path":"/","secure":false,"value":"portal"}, {"domain":"test.net","httponly":false,"name":"SESSIONID","path":"/","secure":false,"value":"test"}, {"domain":"test.net","httponly":false,"name":"USER.PRIVATE_","path":"/irasj","secure":false,"value":"z"},{"domain":"test.net","httponly":false,"name":"brand2","path":"/irasj","secure":false,"value":"Test"},{"domain":"test.net","httponly":false,"name":"USER.PRIVATE_DATASOURCE","path":"/irasj/","secure":false,"value":"en_GB"}]`

Thanks
Vladimir

**Comment by soulgalore** [comment]
Hello @VladimirCacicArapovic 
did this work out for you?

Best
Peter

**Comment by VladimirCacicArapovic** [comment]
No, I end up changing \lib\headless\scripts\yslow-3.1.8-sitespeed.js and adding login after page.open, for now..i have to implement betters solution :)

**Comment by RichardBray** [comment]
I have a similar issue. I've written a selenium script to login to my site, but it runs on a different server from the sitespeed.io stuff.

Here is my selenium script;

```
var webdriver = require('selenium-webdriver');

var By = webdriver.By;

function createDriver() {
  var driver = new webdriver.Builder()
    .usingServer('http://localhost:4444/wd/hub')
    .withCapabilities(webdriver.Capabilities.chrome())
    .build();

  driver.manage().timeouts().setScriptTimeout(10000);
  return driver;
}

var driver = createDriver();

driver.get('http:[server]');
driver.findElement(By.id('email')).sendKeys('user');
driver.findElement(By.id('password')).sendKeys('pass');
driver.findElement(By.className('mdl-button')).click();
```

and here is what I type in the terminal after that

`sitespeed.io -u http://[server] --seleniumServer http://127.0.0.1:4444/wd/hub -b chromez

**Comment by VladimirCacicArapovic** [comment]
Thanks

**Comment by soulgalore** [comment]
Hey @RichardBray 
it will work when we release 4.0 but that will not be until June so there is some time until it happens, sorry. What's good is that it will work as you done already, check out the example here: 
https://github.com/tobli/browsertime/blob/1.0/test/preposttasks/preLoginExample.js

Follow that pattern and it will work.

For now you need to hack and send the cookie as a request headers.
Best
Peter

**Comment by StephaneColson** [comment]
HI, I'm trying with version 4.0.0-beta.1 and this script for login:
```
'use strict';
var webdriver = require('selenium-webdriver');

module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('http://ip')
        .then(() => {
          var login = driver.wait(webdriver.until.elementLocated(webdriver.By.id('username')), 3000);
          login.sendKeys('user');

          var password = driver.wait(webdriver.until.elementLocated(webdriver.By.id('password')), 3000);
          password.sendKeys('password');

           driver.findElement(webdriver.By.xpath('/html/body/div/div/div[2]/div[1]/form/fieldset/button')).click();
	       });
      })
    }
};
```
I execute this 

> $ bin/sitespeed.js -b chrome --preScript login.js http://ip

and the error returned is the following
```
[2016-09-07 11:33:06] Versions OS: linux 3.16.0-4-amd64 nodejs: v4.2.6 sitespeed.io: 4.0.0-beta.1 browsertime: 1.0.0-beta.3 coach: 0.25.0
[2016-09-07 11:33:07] Starting chrome for analysing http://ip/ 3 time(s)
[2016-09-07 11:33:07] Testing url http://ip/ run 1
[2016-09-07 11:33:11] TypeError: login.sendKeys is not a function
    at /home/scolson/dev/sitespeed.io/login.js:10:17
    at ManagedPromise.invokeCallback_ (/home/scolson/dev/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:1315:14)
    at TaskQueue.execute_ (/home/scolson/dev/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2736:14)
    at TaskQueue.executeNext_ (/home/scolson/dev/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2719:21)
    at /home/scolson/dev/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2595:27
    at /home/scolson/dev/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:368:9)
[2016-09-07 11:33:11] Render HTML for 1 page(s) 
[2016-09-07 11:33:11] Error TypeError: Cannot read property 'score' of undefined
    at module.exports (/home/scolson/dev/sitespeed.io/lib/plugins/html/setup/summaryBoxes.js:60:35)
    at HTMLBuilder.renderHTML (/home/scolson/dev/sitespeed.io/lib/plugins/html/htmlBuilder.js:88:189)
    at Object.close (/home/scolson/dev/sitespeed.io/lib/plugins/html/index.js:88:29)
    at /home/scolson/dev/sitespeed.io/lib/sitespeed.js:35:49
...

```
Why do I have a `TypeError: login.sendKeys is not a function  ` ?

**Comment by soulgalore** [comment]
Hey @StephaneColson 
one thing I saw you shouldn't require('selenium-webdriver') (sorry we need to get the docs out). Checkout https://github.com/sitespeedio/browsertime/blob/master/test/prepostscripts/preLoginExample.js where you can get the  selenium-webdriver from the context (to make sure we use the right one and Node finds it):
<pre>
// we fetch the selenium webdriver from context
var webdriver = context.webdriver;
</pre>

Lets see if that will help.

Best
Peter

**Comment by StephaneColson** [comment]
Thanls @soulgalore for the quick answer, I'll try this in a few....

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
