### ISSUE TITLE
Not able to install sitespeedio 

### ISSUE THREAD

**Issue by jpala** [sitespeedio/sitespeed.io#820]
Hi, 

slimerjs dependency is causing installation failure of sitespeed.io. Following is the stack.
Downloading http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2
Saving to /var/folders/rj/063w5wnd3vv0wq9rgk_zzdk5240rgh/T/slimerjs/slimerjs-0.9.2-mac.tar.bz2
Receiving...
Error requesting archive.
Status: 403
Request options: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "download.slimerjs.org",
  "port": null,
  "hostname": "download.slimerjs.org",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2",
  "path": "/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2",
  "href": "http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2"
}
Response headers: {
  "cache-control": "no-cache",
  "pragma": "no-cache",
  "content-type": "text/html; charset=utf-8",
  "connection": "close",
  "content-length": "1310"
}
Make sure your network and proxy settings are correct.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "sitespeed.io"
npm ERR! node v5.4.0
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! slimerjs@0.9.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slimerjs@0.9.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the slimerjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls slimerjs
npm ERR! There is likely additional logging output above.

**Comment by tobli** [comment]
Hi @jpala,
As the error message says: "This is most likely a problem with the slimerjs package". I just tried a fresh installation on mac, without seeing any of the same problems. So maybe a temporary glitch on the slimerjs site.
