### ISSUE TITLE
Question: parallel run of browsertime

### ISSUE THREAD

**Issue by azimut** [sitespeedio/sitespeed.io#822]
When I run sitespeed I see that the lines like this:
```
info: Running browsertime for chrome
```
Run sequencially. This doesn't work especially well on my case because I use Selenium Grid to schedule the jobs elsewhere. If Sitespeed could send more than one job/browsertime at the time I could do a better use of Selenium and improve the overall speed.

There is any option to do this on sitespeed?

**Comment by soulgalore** [comment]
Hey @azimut 
no not in the current version. You could do it yourself if you hack the code, check out https://github.com/sitespeedio/sitespeed.io/blob/master/lib/analyze/browsertime.js#L84 
there is where we set the limit of just running 1 at a time.

Please let us know how it works out :)

Best
Peter
