### ISSUE TITLE
Browsertime times out, gives error from server: 455

### ISSUE THREAD

**Issue by sandinmyjoints** [sitespeedio/sitespeed.io#823]
On Ubuntu 14.04, with sitespeed.io installed via npm -g:

```
[Error: Timed out waiting for the WebDriver server at http://127.0.0.1:54732/hub]
error: Error running browsertime: [Error: Timed out waiting for the WebDriver server at http://127.0.0.1:54732/hub]
info: Running browsertime for firefox http://www.spanishdict.com/
error: Error running browsertime: [Error: Error from server: 455]
```

The command I am using to launch it is:

```
sitespeed.io \
    --profile desktop \
    -b firefox \
    -d 0 \
    -n 5 \
    -f urls/unified.txt \
    --wptHost www.webpagetest.org \
    --wptConfig wpt-public.json \
    --wptKey "$WPT_API_KEY_PUBLIC"
```

urls/unified.txt has a list of 6 urls to test.

Any ideas?

**Comment by azimut** [comment]
I believe that is not finding the selenium server instance on 127.0.0.1:54732/hub. See `--help` at `https://www.sitespeed.io/documentation/configuration/`. Selenium is bundled on the docker image.

**Comment by soulgalore** [comment]
Hi @sandinmyjoints 
thanks for the error report. I've seen this before, sometimes Selenium somehow, someway gets out of sync and try to access the selenium server on the wrong time? Or do you see that it happens every time? I think I mostly seen this using Firefox with the NodeJS version of Selenium (that's the one that is bundled with sitespeed.io).

You could try running your own Selenium server (in Java) as we do in the Docker container: 
https://github.com/sitespeedio/sitespeed.io-docker/tree/master/all

Checkout the Docker file and the scripts/start.sh script. Or you can run the Docker container directly.

Best
Peter

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
