### ISSUE TITLE
HTML page being overwritten

### ISSUE THREAD

**Issue by mNantern** [sitespeedio/sitespeed.io#824]
Hi !

I tried to use sitespeed with multiple URL:

```
https://www.dev.test.io/dashboard/#/
https://www.dev.test.io/dashboard/#/peripherals
https://www.dev.test.io/dashboard/#/history
```

Everything went fine except in the output folder where I have only 1 html in the folder pages: `s-www_dev_test_io-dashboard-.html`.

It looks like the '#' is being ignored when calculating the filename

**Comment by soulgalore** [comment]
Hey @mNantern ,
yes your are right, we don't support Hash-Bang. So is it a site that you built or a product? Best practice nowadays is to not show different content depending on # I think.

Best
Peter

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.

**Comment by danut-iosif** [comment]
Hello, mate. 

On latest version of SiteSpeed.io from the Docker-compose.yml, this issue is still manifesting.

Thank you!
