### ISSUE TITLE
issue installing slimer fails sitespeed install

### ISSUE THREAD

**Issue by tdmoneybanks** [sitespeedio/sitespeed.io#825]
I am running npm install -g sitespeed.io and getting the following error. It looks like its because the download url  for slimer does not work. I downloaded slimer using npm and that worked fine but it still is getting this error. 
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
 
> slimerjs@0.9.2 install /usr/local/lib/node_modules/sitespeed.io/node_modules/slimerjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2
Saving to /usr/local/lib/node_modules/sitespeed.io/node_modules/slimerjs/slimerjs/slimerjs-0.9.2-mac.tar.bz2
Receiving...
Error requesting archive.
Status: 302
Request options: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "download.slimerjs.org",
  "port": null,
  "hostname": "download.slimerjs.org",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2",
  "path": "/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2",
  "href": "http://download.slimerjs.org/releases/0.9.2/slimerjs-0.9.2-mac.tar.bz2"
}
Response headers: {
  "location": "http://msbc81/?cfru=aHR0cDovL2Rvd25sb2FkLnNsaW1lcmpzLm9yZy9yZWxlYXNlcy8wLjkuMi9zbGltZXJqcy0wLjkuMi1tYWMudGFyLmJ6Mg==",
  "cache-control": "no-cache",
  "pragma": "no-cache",
  "content-type": "text/html; charset=utf-8",
  "connection": "close",
  "content-length": "622"
}
Make sure your network and proxy settings are correct.
-
> phantomjs-prebuilt@2.1.3 install /usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip
Saving to /usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs-prebuilt/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
-
Error requesting archive.
Status: 429
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/2.14.12 node/v4.3.0 darwin x64"
  },
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie",
  "cache-control": "max-age=900",
  "content-type": "text/plain",
  "strict-transport-security": "max-age=31536000",
  "date": "Tue, 16 Feb 2016 19:35:50 GMT",
  "x-served-by": "app-104",
  "expires": "Tue, 16 Feb 2016 19:35:50 GMT",
  "content-language": "en",
  "etag": "\"62dcd5481fd29816ecc5ae00be2da0b0\"",
  "x-static-version": "3b9e7b99f146",
  "x-render-time": "0.0133938789368",
  "connection": "close",
  "x-request-count": "418",
  "x-frame-options": "SAMEORIGIN",
  "last-modified": "Tue, 16 Feb 2016 19:35:50 GMT",
  "x-version": "3b9e7b99f146",
  "content-length": "46"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
-
> bufferutil@1.2.1 install /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "sitespeed.io"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! slimerjs@0.9.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slimerjs@0.9.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the slimerjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls slimerjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tdunkel/code_files/site_speed_test/npm-debug.log

Is there anyway to tell sitespeed.io to not download slimer and use the version i already installed?
Thanks!

**Comment by soulgalore** [comment]
Hey @tdmoneybanks 
thanks for reporting! 

Can you please try again? I think there has been some problem for slimer today. Else if you can try the docker image. We are working on the coming 4.0 and then we will skip slimer.

Best
Peter

**Comment by tdmoneybanks** [comment]
@soulgalore Hi thanks for responding so quick! I just tried again and got the same error. it appears there is a problem with the way slimer is getting installed. maybe try a different download url?

**Comment by soulgalore** [comment]
Yes, so you can try this out (we use that package):
https://www.npmjs.com/package/slimerjs#downloading-from-a-custom-url

We are running a older version though, so I'm not 100% sure that the URL bypass was done at that time, else let me check if we can upgrade to latest.

Best
Peter

**Comment by tdmoneybanks** [comment]
Ok yea i'll set the flag. do you happen to know another url besides the releases one that would have the slimerjs binary? The one I passed in seems to be the same one that the install is trying to access (and failing).

**Comment by tdmoneybanks** [comment]
Hey @soulgalore, any updates on if you can upgrade the dependency? Thanks again!

**Comment by soulgalore** [comment]
Hey @tdmoneybanks no I don't. Can you access the download location in your browser (https://download.slimerjs.org/releases/0.9.2/)?

**Comment by tdmoneybanks** [comment]
hey @soulgalore I'm guessing it was a problem with the intranet at work because i did the install at home and it worked fine. So sorry to have wasted your time with this problem and thanks so much for the help!
