### ISSUE TITLE
Chrome/37.0.2062.120 on run.sitespeed.io

### ISSUE THREAD

**Issue by JosefJezek** [sitespeedio/sitespeed.io#826]
After choice Chrome 48 I get result for Chrome/37.0.2062.120...

```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 Viewport: 1280x800
```

Result with Chrome/37.0.2062.120
https://results.sitespeed.io/6ba4-2016/1/21/96a731d4-45fe-4230-958f-255011dd14a3/index2.html

**Comment by soulgalore** [comment]
Hey @JosefJezek 
thanks for the report! Yep, 48 is used but the default user-agent is 37, let us fix it to the next release.

Best
Peter

**Comment by JosefJezek** [comment]
Chrome is not 48, because Web Components are not present.

**Comment by soulgalore** [comment]
Hmm strange because I think we are using the latest Docker container, would it be possible for you to verify testing out https://hub.docker.com/r/sitespeedio/sitespeed.io/ ? Latest should be based on Chrome 48 and FF 44. Else what location are you using, then I can check the logs.

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
