### ISSUE TITLE
TypeError: Bad argument

### ISSUE THREAD

**Issue by djfredc** [sitespeedio/sitespeed.io#827]
Hi

when i Run this command i have an error

# sitespeed.io -u http://google.com
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:367:9)
    at Object.exports.execFile (child_process.js:139:15)
    at async.parallel.childProcess.exec.timeout (/usr/lib/node_modules/sitespeed.io/lib/util/util.js:374:26)
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:233:13)
    at _parallel (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:731:9)
    at Object.module.exports.logVersions (/usr/lib/node_modules/sitespeed.io/lib/util/util.js:366:13)

**Comment by beenanner** [comment]
@djfredc what version of node are you running? 

➜  ~ node -v
v4.3.1
➜  ~ npm -v
2.14.12

**Comment by djfredc** [comment]
Hi,

the version of node is:

~ node -v
v5.7.0

~  npm -v
3.6.0

**Comment by beenanner** [comment]
Hmm just upgraded and it's working for me. What's your OS?

➜  ~ sitespeed.io -u http://google.com
info: OS: 'darwin 15.2.0', Node.js: 'v5.7.0', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.8.0_66', browsertime: '0.12.2'
info: Will crawl from start point http://google.com with crawl depth 1
error: Failed to download https://www.google.com/calendar?tab=wc
info: Will analyze 17 pages
info: Running YSlow for http://google.com [phantomjs]
info: Running YSlow for https://www.google.com/contacts/?hl=en&tab=wC [phantomjs]
info: Running YSlow for https://www.google.com/intl/en/about.html?fg=1 [phantomjs]

**Comment by djfredc** [comment]
My OS is debian 8

phantomjs --version
2.1.1                   

~# java -version
java version "1.7.0_95" 
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by beenanner** [comment]
Tested on my Ubuntu machine and everything is still working as expected. Have you tried reinstalling  sitespeed.io?

➜  ~ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)


➜  ~ sitespeed.io -u http://google.com
info: OS: 'linux 3.19.0-51-generic', Node.js: 'v5.7.0', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'
info: Will crawl from start point http://google.com with crawl depth 1
error: Failed to download https://www.google.com/calendar?tab=wc
info: Will analyze 17 pages
info: Running YSlow for http://google.com [phantomjs]
info: Running YSlow for https://www.google.com/imghp?hl=en&tab=wi&ei=qqDXVqv2DMiueJChnfgG&ved=0EKouCBkoAQ [phantomjs]
info: Running YSlow for https://www.google.com/advanced_search?hl=en&fg=1 [phantomjs]
...

**Comment by beenanner** [comment]
@djfredc my best guess is one of the dependent packages failed to install while you were installing sitespeed.io.

**Comment by djfredc** [comment]
I have reinstall twice

**Comment by tobli** [comment]
Is this running the latest version of sitespeed.io? As of 3.11.4 we're bundling PhantomJS 2.1.1 inside the sitespeed.io package. The error comes from executing that binary to get the version. We haven't received any reports of it not working on Debian 8, but I haven't tested it myself.

Could you please run the following command? (this is assuming you've installed sitespeed.io globally with npm install -g)

> $(npm -g root)/sitespeed.io/node_modules/phantomjs-prebuilt/bin/phantomjs --version

If you have PhantomJS installed on your system it's still going to run the bundled one, unless you explicitly specify --phantomjsPath. If there's an issue with the bundled one, you might be able to work around it by specifying the binary you have installed outside of sitespeed.io.

**Comment by djfredc** [comment]
npm -g /sitespeed.io/node_modules/phantomjs-prebuilt/bin/phantomjs --version
3.6.0

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
