### ISSUE TITLE
Difference in http metric vs pagemetric

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#828]
I see in Graphite that there are three sections of metric collection.  `http`, `meta` and `summary` .   While I understand `summary`, I do not get `http`.  Specifically, there is a `jsWeight` metric which falls into `http` as well as `summary>site>pagemetric>jsWeight`, which sometimes gives a different value. Is there a difference in how these are calculated, if yes, which should be considered to measure user perceived metric?

**Comment by soulgalore** [comment]
Hey @abhagupta , sorry for the late answer, been working with the new version and neglecting issues, sorry again:
* summary holds metrics for the whole run. If you test 100 URLs you will find median metrics here for all the runs.
* http holds info on per URL bases, so you can keep track of metrics per URL.

I think you should focus on the  user timing metrics per URL.  I try to focus on couple of URLs (http://calendar.perfplanet.com/2015/measuring-performance-in-practice/), the "most" important one. Then I usually use the summary for more to have a better feeling of how the whole site are doing. 

Best
Peter

**Comment by abhagupta** [comment]
Thanks @soulgalore for reply. No problem. We appreciate you working on the new version.   

So if I understand it correctly,  by 100 URLs , you mean, if we test  100 different urls which could be passed in to sitespeed.io via `--file` or `--sites`, then we should look into `summary`. 

In my case, I am using just  1 url by passing in `-u` option. In this case, `http` and `summary` would be same ..correct?

**Comment by soulgalore** [comment]
yes!
