### ISSUE TITLE
Problems running Webpagetest on AWS

### ISSUE THREAD

**Issue by pmartens** [sitespeedio/sitespeed.io#830]
Hi Peter,

I have read your article on https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance/ about running webpagetests on an AWS. I have been following your instructions on this site but I do not get it to work with sitespeed.io.

- I'm using the eu-central-1: ami-22cefd3f AMI on AWS

- On the AMI I have set the following user data:

```
ec2_key=<My` private ec2 key>
ec2_secret=<My private ec2 secret>
api_key=< a self-generated key>
headless=0
iq=80
pngss=1
EC2.ue-central-1.min=1
EC2.ue-central-1.max=5
```

- The sitespeed command looks like this:
`sitespeed.io -u '<website>' -n 1 -d 0 -v --wptHost www.webpagetest.org --wptKey < a self-generated key> --wptConfig ~/sitespeed.json --graphiteHost x.x.x.x  -r ~/sitespeed-result`

- The sitespeed.json file looks like this:
```
[
  {
    "pollResults": 1,
    "timeout": 600,
    "runs": 1,
    "private": true,
    "aftRenderingTime": true,
    "video": false,
    "location": "ec2-eu-central-1:Chrome",
    "connectivity": "Cable"
  },
  {
    "pollResults": 1,
    "timeout": 600,
    "runs": 1,
    "private": true,
    "aftRenderingTime": true,
    "video": false,
    "location": "ec2-eu-central-1:Firefox",
    "connectivity": "Cable"
  }
]
```

When I run this sitespeed command, I get the errror message: 
`error: Error running WebPageTest: { statusCode: 400, statusText: 'Invalid API Key' }`

Which API key I must use to get it working? When I uses the API key sponsored by Akamai, it works for 200 requests. But we do a lot more.....

Please can you help me?

**Comment by soulgalore** [comment]
Hey @pmartens ,
the key is for protecting the instance so only you can use it from the API.

Right now you are accessing the public instance of wpt (wptHost parameter):
<pre>sitespeed.io -u '<website>' -n 1 -d 0 -v --wptHost www.webpagetest.org --wptKey < a self-generated key> --wptConfig ~/sitespeed.json --graphiteHost x.x.x.x -r ~/sitespeed-result</pre>

Change the wptHost to the domain of your machine (you can see that in the settings in the AWS admin). Then it will hopefully work :)

Best
Peter

**Comment by pmartens** [comment]
Thanks for your fast reply!

Also this I have already tested and get the following error messsage:
```
error: WebPageTest couldn't fetch info for url http://website { statusCode: 400,
  statusText: 'Invalid Location, please try submitting your test request again.' }
```
In the json file I've tried multiple locations like `"location": "ec2-eu-central-1:Firefox"`.

For measurements is sitespeed.io a great tool!

**Comment by soulgalore** [comment]
Thanks for the kind words :)

You can check the available locations by going to the URL of your WebPageTest instance and then add /getLocations.php, so for the public instance you can access http://www.webpagetest.org/getLocations.php to see them.

**Comment by pmartens** [comment]
I have already founded this page and tried more then one location. Not one worked for me.. I just tried the following json for the test:

```
[
  {
    "pollResults": 1,
    "timeout": 600,
    "runs": 1,
    "private": true,
    "aftRenderingTime": true,
    "video": false,
    "location": "ec2-eu-west-1:Chrome",    
    "connectivity": "Cable"
  },
  {
    "pollResults": 1,
    "timeout": 600,
    "runs": 1,
    "private": true,
    "aftRenderingTime": true,
    "video": false,
    "location": "ec2-eu-west-1:Chrome",
    "connectivity": "Cable"
  }
]
```
With the same error message....

**Comment by pmartens** [comment]
The verbose message gives the following info:
`verbose: Got the following from WebPageTest:undefined`

Tested json file:
```
[
  {
    "pollResults": 1,
    "timeout": 600,
    "runs": 1,
    "private": true,
    "aftRenderingTime": true,
    "video": false,
    "location": "Dulles:Chrome",
    "connectivity": "Cable"
  },
  {
    "pollResults": 1,
    "timeout": 600,
    "runs": 1,
    "private": true,
    "aftRenderingTime": true,
    "video": false,
    "location": "Dulles:firefox",
    "connectivity": "Cable"
  }
]
```

**Comment by soulgalore** [comment]
So I think are not accessing your own instance location list? <pre>ec2-eu-west-1:Chrome</pre> is from WebPageTest.org. When I check on a Amazon instance, the name is <pre>eu-west-1:Chrome</pre>.

**Comment by pmartens** [comment]
This was the solution!! Thank you very much for your help. We greatly appreciate..

**Comment by soulgalore** [comment]
Great! If you will use WebPageTest on AWS I've done a full write up how we set it up for Wikipedia: https://wikitech.wikimedia.org/wiki/WebPageTest

**Comment by namnn96** [comment]
Hi @soulgalore ,

Really appreciate what you've done. I just got a bug, when running sitespeed.io I keep getting this error no matter what location i entered. I followed your instruction by getting locations based on instance, but that did not work neither. I am quire hopeless now. Here is the error:

Running WebPageTest **** pollResults=10, timeout=600, firstViewOnly=false, runs=n, private=true, aftRenderingTime=true, location=us-east-1:Firefox, connectivity=Cable, video=true
error: WebPageTest couldn't fetch info for url **** { statusCode: 400,
  statusText: 'Invalid Location, please try submitting your test request again.' }
error: Error running WebPageTest: { statusCode: 400,
  statusText: 'Invalid Location, please try submitting your test request again.' }


Thank you in advance

**Comment by soulgalore** [comment]
Hey @namnn96 
if you run on the public instance of WPT and have an API key, these locations should work:
http://www.webpagetest.org/getLocations.php

If it doesn't work, can you show me your config file when you run?

Best
Peter

**Comment by namnn96** [comment]
Hi @soulgalore, 

I did not run it on the public instance. I created my own wpt server with aws ec2 following this tutorial https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance/

Below is the config file i use for wpt
{
  "pollResults": 10,
  "timeout": 600,
  "firstViewOnly": false,
  "runs": "n",
  "private": true,
  "aftRenderingTime": true,
  "location": "us-east-1:Firefox",
  "video": true
}

Thank you

**Comment by soulgalore** [comment]
Ok, if you switch to the public instance does it work there? Wonder if there's problem with the instance or sitespeed that sends wrong values.

**Comment by namnn96** [comment]
Sorry for this late reply.

It kind of works on wpt public server. However, it only generates data in
har folder.
When I tried to display it on grafana, all metrics under wpt are N/A, which
quite confuses me.

Below is my instance
[image: Inline image 1]

Best regards,
Nam

**Comment by namnn96** [comment]
I had 2 instances, one in us-west oregon and one in sydney, both of them do
not work.
When i check the <public dns>/getLocations.php, there are no idle testers.

Is that the reason for failure?

Best regards,

**Comment by namnn96** [comment]
And this is the us-west instance. I terminated the sydney instance.

[image: Inline image 1]

**Comment by soulgalore** [comment]
Hey @namnn96 
to test your instance, change so you have a GUI (so you can submit test using the HTML page):
headless=0

To see if that works. If it works, then something is wrong on the sitespeed.io side :)

Best
Peter

**Comment by namnn96** [comment]
Hi Peter,

I actually set the headless = 0 when i created the instance as you
mentioned in Step 6
https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance/

As I mentioned, it kind of works for public instances, though the data
generated is not all sent to graphite. I don't think there is some problem
with sitespeed, cause it runs find with the public server and also
generates data i expected

Please help me out of this, thank you.

**Comment by sampun** [comment]
Same issue is being faced by me. Please help.
Also can you please share any sample location.ini which we should need to create on private instance of WPT.
