### ISSUE TITLE
Implement HTML & design 

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#832]
The work on 4.0 is coming along fine. We have the [branch](https://github.com/sitespeedio/sitespeed.io/tree/4.0) up and running, but we don't have any good looking HTML yet. We switched from Handlebars to [Jade](http://jade-lang.com/) to create the HTML output. The templates are not finished but we at least put out most of the metrics that we want.

In the sitespeed.io 3.0 we used Bootstrap for the HTML pages. Would be cool to though to skip Bootstrap for the new version.

Also want to include graphs in the new version. Lets look at https://gionkunz.github.io/chartist-js/ and http://www.chartjs.org/. Let see which would work out best for us.

**Comment by softwareklinic** [comment]
Are we planning to include FLOW-based testing e.g. start from page1---> page 2 ---> page 5 ---> page 6 .... and also the selenium type signed-en flows --- e..g. i can record my flow using selenium builder.... and pass JSON to selenium server to test the flow  and site speed capture the performance metrics... let me know how are we planning to cover this...
