### ISSUE TITLE
error: Yslow output for 'http://xxx' (stdout): FAIL to load ht tp://www.xxx

### ISSUE THREAD

**Issue by MargotElMadi** [sitespeedio/sitespeed.io#833]
Hi, 
I have got the error and i don't understand why... 
My others URL are ok...
If you need my URL i can tell you.
Sorry for my english... 

error: Yslow output for 'xxx' (stdout): FAIL to load http://xxx

  phantomjs://code/yslow-3.1.8-sitespeed.js:306

error: Error running yslow for url 'http://xxx': { [Error: Command failed: C:\xxx\node_modules\sitespeed.io\node_modules\phantomjs-prebuil
t\lib\phantom\bin\phantomjs.exe --ssl-protocol=any --ignore-ssl-errors=yes C:\xxxi\node_modules\sitespeed.io\lib\headless\scripts\yslow-3.1.8-sitespeed.js -d -r sitespeed.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 --file C:\xxx\sitespeed-result\www.leroymerlin.fr\2016-03-14-16-38-
36\data\yslow\xxx-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new D
ate).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return true;} http://xxx]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: 'C:\\xxxi\\node_modules\\sitespeed.io\\node_modules\\phantomjs-pre
built\\lib\\phantom\\bin\\phantomjs.exe --ssl-protocol=any --ignore-ssl-errors=yes C:\\xxx\\node_modules\\sitespeed.io\\lib\\headless\\scripts\\yslow-3.1.8-sitespeed.js -d -r sitespee
d.io-desktop --ua Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
37.0.2062.120 Safari/537.36 --file C:\\xxx\\sitespeed-result\\www.xxx\\data\\yslow\\www_xxx-yslow.json -vp 1280x800 --waitScript  if (window.performance && window.performance.timing){ return ((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 ));} else { return
 true;} http://xxx' }

**Comment by soulgalore** [comment]
Hey @MargotElMadi thanks for the report. It's hard to say without the URL, but one known bug with the current YSlow/PhantomJS setup is that it can't handle frontend-redirects, could that be the problem? 

Else if you can email me the URL I can have a look: peter [AT] soulgalore [dot] com

When I debug I first try the URL standalone in default YSlow (to check if it's a bug in YSlow), If that works, I try the specific sitespeed.io ruleset, to see if it could be one of our rules that are the problem.

Best
Peter

**Comment by Jinghua-ZHU** [comment]
Hi @soulgalore 
Thanks for you clarifying this issue.

I also encounter similar issue and my app works based on reverse proxy. So, regarding your comment _"but one known bug with the current YSlow/PhantomJS setup is that it can't handle frontend-redirects"_,
could you please share me with more detailed info?

Thanks a lot.

Cheers,
Jinghua

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
