### ISSUE TITLE
How to test auth enabled pages

### ISSUE THREAD

**Issue by guptaanoop2005** [sitespeedio/sitespeed.io#839]
Hi,
I am working on an application which uses JWT based token for login and session management. How can I implement sitespeed for page which comes after login?
I am using Gulp for build.

**Comment by soulgalore** [comment]
Hey @guptaanoop2005 ,
there's no super clean way to do it in the current version (but will come in 4.0 this summer). You can check [this thread](https://github.com/sitespeedio/sitespeed.io/issues/819) where there's more info about what you can do.
Best
Peter

**Comment by guptaanoop2005** [comment]
thanks @soulgalore . Waiting for 4.0 however let me look at the thread you provided.

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
