### ISSUE TITLE
Wrong colours on result tables for the coach

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#871]
The coach has the ability to show more details in the tables by hiding/showing extra rows. But today the give each row different colors depending if it is even or odd (in the css). We should change that for just coaches tables.

Before you click show/hide (the two first rows are white, that's wrong they should alternate):
<img width="987" alt="screen shot 2016-04-14 at 00 33 18" src="https://cloud.githubusercontent.com/assets/540757/14511606/d9a60626-01d8-11e6-9505-f4f6760a7a0a.png">

Clicking on show, shows the detail row. Maybe that row should have a completely different color?
<img width="1012" alt="screen shot 2016-04-14 at 00 33 27" src="https://cloud.githubusercontent.com/assets/540757/14511619/f44a8e8e-01d8-11e6-9a1b-d82add090db6.png">

**Comment by dmillerme7** [comment]
The first highlighted row is being hidden so you can't see that it probably is highlighted already.
Are you using JS or CSS for alternate row highlighting?

**Comment by soulgalore** [comment]
Yes. Now it's a simple CSS rule. Adding classes per row would do it, should be doable from the Jade template. Or do you have any other idea, love more input :)
