### ISSUE TITLE
Design quick links

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#872]
There's a lot that can be done to make the quick links (linking inside the page) more beautiul :)

<img width="836" alt="screen shot 2016-04-14 at 00 37 56" src="https://cloud.githubusercontent.com/assets/540757/14511641/353f038e-01d9-11e6-98a9-2ac888a4fe5d.png">

**Comment by dmillerme7** [comment]
Hi, what's your idea of more beautiful? Looking for some specific CSS treatment here?

**Comment by soulgalore** [comment]
Well the current version is just ugly :) I think a standarized way to just show links within the same page would be cool, highlighting them in some way. Do you have any idea?

**Comment by beenanner** [comment]
I wonder if we could do something like a floating hamburger menu in the top right? They seem fairly standard these days. What do you guy's think @soulgalore / @tobli / @dmillerme7?

**Comment by soulgalore** [comment]
@beenanner good idea, lets try that, do you wanna or should I?

**Comment by beenanner** [comment]
@soulgalore I can give it a shot later tonight or tomorrow, but feel free to give it a shot if you have time today. I was thinking a pure CSS option would be nice. Here is one example I found.

https://www.sitepoint.com/pure-css-off-screen-navigation-menu/

**Comment by soulgalore** [comment]
looks cool! Try it when you have time :)

**Comment by beenanner** [comment]
@soulgalore / @dmillerme7  feel free to checkout the hamburger-quick-links branch. I think it could use some more tweaking from someone that does CSS on a daily basis. ;-)

Desktop version
![desktop](https://cloud.githubusercontent.com/assets/723985/16718612/9f852ed4-46ef-11e6-9ba6-1c47ee47ca44.png)

Mobile closed
![mobile](https://cloud.githubusercontent.com/assets/723985/16718617/a989fcd4-46ef-11e6-8d9a-0c5b79c46cbd.png)

Mobile open
![mobile open](https://cloud.githubusercontent.com/assets/723985/16718620/af26339c-46ef-11e6-93d1-8a9cba777ebe.png)

**Comment by soulgalore** [comment]
cool, maybe matt can help out. I'll test it tonight. Not 100% sure, seems a little confusing with the two menus on the same level?

**Comment by soulgalore** [comment]
Been thinking maybe we should use tabs for content something like https://codepen.io/fusco/pen/Wvzjrm

**Comment by beenanner** [comment]
@soulgalore That's a good idea too maybe I can throw together another branch with the tabs idea.

**Comment by soulgalore** [comment]
I don't mind if we use JS for the tabs or make it as easy at possible. I can have a go with it if you want @beenanner ?

**Comment by beenanner** [comment]
Sure @soulgalore! I haven't been able to spend much time on this due to work related tasks. Let me know if you need me to test anything.

**Comment by soulgalore** [comment]
@beenanner cool, I'll give it a try on Sunday.

**Comment by soulgalore** [comment]
@beenanner check out the new branch css-tabs.

<img width="997" alt="screen shot 2016-07-23 at 23 10 25" src="https://cloud.githubusercontent.com/assets/540757/17080335/6d6ed166-512b-11e6-99bd-1606247836cb.png">

I think we should add each logo in front of each tab and then rename the text to better explain what kind of data we collects? Also find a better way to display that we show data from run number 1. Feel free to play around with it if you have time :)

**Comment by beenanner** [comment]
@soulgalore had some time to look at it. I like it! If we add logos will those carry over to the mobile view. I noticed we are limited on space there and just display the letter. Would the logos replace the letters, maybe we can show the full text for the active tab. To better explain the data we collect for each tab we could give a short description at the top of each tab explaining what is within that specific tab? Maybe a note above the tabs is needed to express that all metrics within the tabs are from the first run. I agree I don't think the (1) will be very initiative to new users that they are looking at only run 1 stats. That could also be a good opportunity to call out the links to each individual run as well.

**Comment by beenanner** [comment]
Also the waterfall captured in the browsertime when the option is enabled allows you see more than just the first run in the page summary so that may need an extra call out as well or we could move that to it's own tab?

**Comment by soulgalore** [comment]
@beenanner added the logos but need some fine tuning, will continue with the other things probably tomorrow. If you feel like polish up the design/HTML ... go ahead 💃

**Comment by soulgalore** [comment]
@beenanner I've added some short description and the logos. Let me know if you feel it looks ok (it's both on page level and on each individual run). After we merged I can clean up the pug code so more of it is re-used (but I want to do that in another step). And also want to add more links for metrics to the help page (and add some overall summary text to the help page, think that will make it even better).

**Comment by beenanner** [comment]
@soulgalore let me look again tonight but first pass it seems good enough to merge.

**Comment by beenanner** [comment]
@soulgalore looks good enough to merge to me. I did a minor padding tweak to allow all the tabs to fit on a single line for tablet and mobile. I'm sure we will have a few more tweaks before we release. :-)

**Comment by soulgalore** [comment]
I moved what's left to #1087
