### ISSUE TITLE
Domains result needs some love

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#873]
We are missing stats like: Total time per domain and number of requests per domain. We should also sort the table by number of requests and have a limit of X (200) number of domains.

<img width="984" alt="screen shot 2016-04-14 at 00 46 01" src="https://cloud.githubusercontent.com/assets/540757/14511820/89f0c420-01da-11e6-86e1-4ce06267a172.png">

**Comment by soulgalore** [comment]
We need to sort them of number of requests and set a max limit (200) of rows to show.

**Comment by tobli** [comment]
Limited to 200 and made sortable in b1c79af0be291fc0e6b1b56a31a40b871787e26e.
Will leave this open a little longer until we've tested it a bit longer.

**Comment by soulgalore** [comment]
Looks good. What do you think about showing max values instead of median? Thinking we want to find domains that have slow assets, maybe then catch the max one?

**Comment by tobli** [comment]
Yeah, showing max might be a good thing. In general we need more explanations of what's shown on all pages. It can be quite confusing since the numbers in each column are median or max for that value only. The "Total time" column will not add up to the sum of all columns before it.

**Comment by soulgalore** [comment]
Yes you are right. Also got feedback this week that it is overall is hard to understand, we need to see if we can both add good explanations and then I'm liking the idea of small videos.

**Comment by beenanner** [comment]
Adding tooltips might be good for these so when hovered over they can give a short explanation.

**Comment by tobli** [comment]
Yep. However we need to consider mobile as well, where hovering isn't a thing.

**Comment by soulgalore** [comment]
I want us to be able to see all data/metrics on a phone however I think it's ok to add some sugar for desktop like hovering etc. Think it will be hard to see everything on a small device.

**Comment by beenanner** [comment]
I think there are a few css3 tooltips that use taps to work on mobile devices. The UX will be a challenge on mobile with all the data that is collected.  I'll look around to see what I can find.

**Comment by tobli** [comment]
Sounds great @beeanner

**Comment by soulgalore** [comment]
Nice, this will not stop alpha1 so I'm moving it.

**Comment by soulgalore** [comment]
@tobli had a sweet idea: use max in all fields, except in total where we also show min/max (and sort on max).

**Comment by soulgalore** [comment]
This is not crucial for 4.0 let move this to a later release.

**Comment by soulgalore** [comment]
We can live with the way it is now.
