### ISSUE TITLE
Some metics missing when running on Jenkins box

### ISSUE THREAD

**Issue by tdmoneybanks** [sitespeedio/sitespeed.io#878]
Some of the metics like domContentLoaded are not produced when the tool is run on jenkins box. Is this normal?

**Comment by soulgalore** [comment]
Hey @tdmoneybanks 
thanks for the report, no that should not be the case. Whats the configuration, what browserdo you use? Do you have any logs?

Best
Peter

**Comment by tdmoneybanks** [comment]
Hi @soulgalore here is the command that is being run on the Jenkins box. 
/usr/local/sitespeed.io/bin/sitespeed.io -f beta_urls.txt -d 0 -n 10 --graphiteHost //hostName --graphiteNamespace //namespace --graphitePort 2003

The namespace and hostName are actual values in the command. The file is cloned from a git repo and then the command is run. We get some metics out but some other ones are missing.

**Comment by soulgalore** [comment]
Hi again, you are missing the config for the browser sp you will not get any timing metrics. -b chrome or -b firefox. You also need xvfb if you dont have that already. After that you will hopefully get what you want :)

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
