### ISSUE TITLE
requestsWithoutGzip missing in graphite

### ISSUE THREAD

**Issue by pborreli** [sitespeedio/sitespeed.io#879]
I have requestsWithoutExpire but requestsWithoutGzip is not exported to graphite

OS: 'linux 3.16.0-4-amd64', Node.js: 'v4.3.2', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'

**Comment by soulgalore** [comment]
Hey @pborreli could it be that you miss more metrics? Graphite has a configuration for how many new metrics that will be created per minute: https://www.sitespeed.io/faq/#i-dont-get-all-values-in-graphite

Today we send so many metrics by default (will be changed in the new version).

Best
Peter

**Comment by pborreli** [comment]
thanks for your answer, I'm using the full docker stack of yours (i should have told you earlier sorry)

**Comment by pborreli** [comment]
I followed the procedure here : https://www.sitespeed.io/documentation/performance-dashboard/

**Comment by soulgalore** [comment]
yes and is that the only metrics you don't get? Theres a couple of ways of debug this: 
* You can turn on verbose logging with <code>--verbose</code> and then all keys and values that are sent to Graphite is logged.
* You can check the log in the Graphite container that you receive the value (I don't have it in my head right now though).

I'm still thinking there could be a problem with too many keys, if you continue to run the tests, I hope it will turn up.

**Comment by OffByNone** [comment]
I think his issue is that sitespeed doesn't send all of the metrics on a per page level, only on a per site.

requestsWithoutExpires gets sent for both, but requestsWithoutGzip and jsSyncInHead only seem to be showing up for me under the summary and not for individual pages.

**Comment by soulgalore** [comment]
ok, hmm. we shouldn't single them out. to make sure they are not sent, you ca turn on verbose logging <code>--verbose</code> to see if the metrics leaves sitespeed.io or just fail to get into Graphite.

**Comment by OffByNone** [comment]
Just checked with verbose and they are indeed not sent to graphite.
Looks like the `requestsWithoutGzip` and `jsSyncInHead` are only under `sitespeed.io.summary.[domain].com.pagemetric`

I also see that `browserScaledImages` and `spofPerPage` have the number of scaled images and spofs only under `sitespeed.io.summary.[domain].com.rule`

Whereas for a specific page I don't see anything for `browserScaledImages`, and for `spofPerPage` I only see the yslow score not the actual number.

**Comment by soulgalore** [comment]
ok thanks @OffByNone lets see how we can make this smarter in 4.0 so it's more understandable what kind of metrics are sent when and where.

**Comment by OffByNone** [comment]
In order to tally them for the summary it must be collecting them at the page level.

Is it worth it for me to track down where they need to be added in 3.x or is that part changing for 4.0?

**Comment by soulgalore** [comment]
No you don't need to do that, everything is completely rewritten for 4.0. But if you have time to test and give input on the first alpha release (hopefully coming later next week) that would be great :)

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
