### ISSUE TITLE
Implement Web Performance budget

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#890]
We haven't done anything here yet. Lets discuss what we need, minimal we should have TAP/JUnit XML support + be able to break builds if we don't meet the criteria.

There's a lot to be done here about configuration,  setup etc. We should also sync with the Grunt/Gulp plugins so it works.

**Comment by matthojo** [comment]
What is needed to pick up this issue? I recently built https://github.com/perflint/budgie and I'm wondering if I could take a similar approach and / or use budgie in some way.

**Comment by tobli** [comment]
Hi @matthojo,
Perflint looks awesome! If nothing else I see a potential for sharing the format for specifying budgets, and associated tooling. Sitespeed.io 4 is still under heavy development, we haven't gotten around to budgets yet. However there are some high level thoughts, and we hope to start work soon.

If you're interested we could have a hangout to exchange ideas. DM myself (tobiaslidskog) or Peter (soulislove) on Twitter and we'll take it from there.

**Comment by soulgalore** [comment]
Lets move this to next alpa, so we can push alpa.2

**Comment by matthojo** [comment]
Sounds good. Let me know when you're both free and we'll have a hangout :)

**Comment by soulgalore** [comment]
@matthojo Tobias and me synced last week, haven't had time to write notes in the issue though. Lets see when you and he has time (I have hard time to find a time talk this week).Lets see how can make it happen.  

I also like budgie :)

**Comment by matthojo** [comment]
:) Thanks. No problem, I _should_ be free most evenings.

**Comment by soulgalore** [comment]
We will use the outcome of https://github.com/matthojo/web-performance-configuration/

**Comment by soulgalore** [comment]
Status update: https://github.com/sitespeedio/sitespeed.io/pull/1227 gives us the same thing as we have in 3.x: max/min values for metrics. Let push that for now and then add functionality to check against the latest run. And then conform with budgie etc.

**Comment by soulgalore** [comment]
Lets close this and open a new one for the rest of the work.
