### ISSUE TITLE
Load your own plugins (was postTask)

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#891]
In 3.x you could run your own postTask where you could get any metrics you want from sitespeed.io and do whatever you want with it. 

In the new version that would be a plugin.

**Comment by tobli** [comment]
Loading of external plugins is still missing. Probably some of the plugins currently in the source tree should be converted to external plugins and can also serve as examples. Slack and yslow comes to mind.

Packaging as npm modules would be handy (minimum package.json + 1 js-file). No need to publish to npm of course.

**Comment by soulgalore** [comment]
Added support for disabling and listing plugins. Lets add this soon.
