### ISSUE TITLE
Create Grafana-ready made templates/dashboards

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#892]
With the new Graphite structure we aim to make it possible to use the same dashboards for different projects, so it's super easy to get everything up and running.

**Comment by beenanner** [comment]
I was talking with the Grafana peeps the other day and it would be cool to create a sitespeed.io app that interfaces with the new Grafana 3.0. They even offered to host the app plugin if one was created. :-)

https://github.com/grafana/example-app

**Comment by soulgalore** [comment]
Hey Jonathan,
yes so I wonder what it would be like, what extra things we can do with the plugin? Thinking linking back and forth for a specific run and result pages would be wonderful, so you easy can check the waterfall for a specific. Do you have other ideas of what we should do?

**Comment by beenanner** [comment]
I haven't dug too far into the implemenation details yet, but I think it mostly just give the user a centralized place to manage the configuration and import dashboards that are pre-packaged. The configuration tab could also be setup to allow the user to configure their privately hosted graphite/influxDB/etc data source. 

![screen shot 2016-04-20 at 10 17 07 am](https://cloud.githubusercontent.com/assets/723985/14677775/12fcf71a-06e1-11e6-8db7-fc5a682d5ab9.png)

Here is the WorldPing App which allows users to selectively choose from a list of predefined dashboards available. I know that grafana has links available now in annotations which could allow implement in the available dashboards which are shipped with the app.

![screen shot 2016-04-20 at 10 14 11 am](https://cloud.githubusercontent.com/assets/723985/14677701/a9fc9a9a-06e0-11e6-83e9-88f9aba9218c.png)

**Comment by soulgalore** [comment]
Yes cool, let see if we can buy @bergquist lunch someday and discuss what we can do :)

**Comment by bergquist** [comment]
Lunch? go outside? I can do that! :)

**Comment by soulgalore** [comment]
@bergquist you got mail :)

**Comment by OffByNone** [comment]
I actually made some dashboards that are totally dynamic in what pages they let you view.  

As long as someone has the standard graphite structure the dashboards should "just work" for whatever they have.

If you want I can shoot them your way.

They are for the 3.x release of sitespeed.io though, and I am not sure what changes you have made to the graphite structure.

**Comment by soulgalore** [comment]
@OffByNone yes cool. so we are changing the structure a little with the keys to make the structure the same as default. however that part isn't completely finished yet but will be before we release alpha1.

**Comment by beenanner** [comment]
@OffByNone feel free to share they would be great to use for testing against 4.0 and would help with writing migration documentation as well. Thanks!

**Comment by OffByNone** [comment]
I have three dashboards: summary of a site, single page, and comparison of pages.

I did hardcode the environment variable as there is some left over test data in my instance that would populate it with a lot of noise if I tried to query it.

I also turned on `graphiteUseQueryParameters`.  I don't think the dashboards will work with it off as it adds an _ to the end of the url path.

To fix this do a find and replace on `_[[page]]_` and `_[[pages]]_` to be `_[[page]]` and `_[[pages]]` respectively.

[Sitespeed.io Dashboards.zip](https://github.com/sitespeedio/sitespeed.io/files/253511/Sitespeed.io.Dashboards.zip)

**Comment by softwareklinic** [comment]
I've created templated dashboards for the sitespeed 3.x and those are cool... working well for our purpose... planning to create templates for 4.x once structure is final... for graphite

**Comment by softwareklinic** [comment]
To be able to see the List of runs for a specific window from Grafana and then open a specific run summary would be really awesome... also point and click a particular run on chart would be amazing.,,.

**Comment by soulgalore** [comment]
@softwareklinic yes that would be cool, I guess we need to build a plugin for that. We want to make it possible to link between runs in Grafana back to sitespeed (so you can click on a specific run and then see the full HTML result), hard to see it make 4.0, probably more 4.1 though.

**Comment by softwareklinic** [comment]
I've demonstrated this to developer forum with 500+ dev and ops team members and they are really excited to see 4.0 coming along.... also, one of the most common ask was link back specific run and show html summary for the same... also, if thats the case - then the html summary should be kind of light-weight --- currently it stores GBs worth of data for just a few hours of run for about 50 urls run every hour...

**Comment by soulgalore** [comment]
yes [that](https://github.com/sitespeedio/sitespeed.io/issues/893) will be cool. About limited HTML, I think the HTML need to be the same but you can turn off storing of all the extra data (JSON) that is big, and we could also zip the results.

**Comment by soulgalore** [comment]
We should have this when we release 4.0 because it's awesome.

**Comment by alex-mcd** [comment]
Hey, I'm trying to set up grafana but am really struggling on the query front. Can you release the json grafana allows you to export. In particular I'm most interested in the single page metrics displayed on [this currently 404 site](https://dashboard.sitespeed.io/dashboard/db/metrics-for-one-page-american-airlines-home-page)

**Comment by soulgalore** [comment]
Hey @alex-mcd , hmm I didn't the warning that the site was, fixed now. You have the example JSONs downloadable from www.sitespeed.io, here's the direct link: https://www.sitespeed.io/documentation/performance-dashboard/dashboards.zip

This is for sitespeed.io 3.x, we changed the structure to be more generic for 4.0 so dashboards more easily can be re-used between users.

**Comment by softwareklinic** [comment]
Alex - I will see if I can share my 4.0 dashboard zip --- after stripping if any proprietary data/info...

**Comment by alex-mcd** [comment]
Thanks, I can't believe I missed that link. No urgency on 4.0

**Comment by soulgalore** [comment]
I just pushed a first version to master today, lets iterate before 4.0.

**Comment by soulgalore** [comment]
Want to iterate those one more time when we get the "final" 1.0 version of PageXray and add some more cool stuff for WebPageTest.

**Comment by soulgalore** [comment]
they are ok for now.
