### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#894]
We need to verify that this is the structure of the result folders that we want. This is important for #893

**Comment by beenanner** [comment]
I like the idea of having the host as a folder for easy grouping and then date(yyyy-mm-dd) as another folder. I'm not sure which would be best at the top level but probably date to limit the items that are written to a directory over a long period of time and would help out on the server implementation of reading certain large directories. I wonder if it would be worth having a 3rd directory of the URL being tested as well. Then maybe file name is time of run on that date for that particular page?

**Comment by soulgalore** [comment]
Lets add domain on top, the only thing is that we don't have a clean version solution if we run multiple domains in a file (or feed with multiple), either use the first all call it by the file name or specific hardcoded name?

yyyy-mm-dd is good, today we have time also, but we could have that a path under to make it cleaner.

<pre>
my.domain/yyyy-mm-dd/HH-mm-ss/
</pre>

We have specific paths/directories for the URLs in 4.0, not exactly as you suggested, so either put it there or have one folder more on top (the exact time).

**Comment by soulgalore** [comment]
Tested with my.domain/yyyy-mm-dd/HH-mm-ss/ but got a feeling that it is too deep, lets see.

**Comment by soulgalore** [comment]
Lets keep it <code>my.domain/yyyy-mm-dd-HH-mm-ss/</code> and <code>filename_ext/yyyy-mm-dd-HH-mm-ss/</code> for now.
