### ISSUE TITLE
Throttle the connection

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#895]
In 3.X we use BrowserMobProxy to throttle the connection and we need something new. 

For Chrome maybe we could use the Network Connectivity Emulation in the Chrome debugger. We cannot use it from Selenium though (since there's a limit of one debugger a time) but maybe we could use it directly in the Chromedriver?

A universal solution would be cool. What should we use and can you help us build it it?https://github.com/phuedx/micro-device-lab could be a good start if we re-package it (uses TC). We could use that in our Docker containers.

Other ways we can do it?

**Comment by soulgalore** [comment]
ping @phuedx :)

**Comment by cgoldberg** [comment]
some thoughts...

Bandwidth throttling would be a cool feature, but a general solution will be tough.

I know of 2 basic methods to do traffic shaping:

  * route requests through a local http proxy that implements a token bucket to throttle (a la BrowserMob)
  * inject network delay into your OS's packet scheduler (not cross-platform)

For the first method, I don't know of other good open source bandwidth managment tools that work via proxy.

For the second... tweaking your OS's packet scheduler is definitely feasible, but it is platform-specific, so might not be a good fit for sitespeed.io.  I'm only familiar with controlling this on Linux, and am not even sure Mac/Windows expose something similar.  For the Linux kernel, the facilities to do this exist in NetEm (Network Emulation).  If you wanted a Linux-only solution, you could build on top of `tc` (Traffic Control).  `tc` is a command-line tool used to control network emulation properties in NetEm.  Another option would be integrate with ATC (Augmented Traffic Control), an open source tool from Facebook.  However, ATC is also Linux-only (it uses `tc` internally)

hth

* http://facebook.github.io/augmented-traffic-control/

**Comment by soulgalore** [comment]
Hey @cgoldberg thanks for the input! In 3.X we used https://github.com/lightbody/browsermob-proxy for proxy but we want to get away from that. For Linux/Docker we will hope to use a modified version of https://github.com/phuedx/micro-device-lab  (that is practical the same as the Facebook version).  We also been talking about to use Chrome dev tools when we use Chrome but we use Selenium so there's some hacking needed.

**Comment by phuedx** [comment]
@soulgalore:

> that is practical the same as the Facebook version

My micro-device-lab (µDL) project ended up being a wrapper around `tc`, much like facebook/augmented-traffic-control (ATC), but I built it specifically for *my* Raspberry Pi running Raspbian and consequently it's less flexible. Both µDL and ATC use a client-server architecture, with the former using REST as a transport and the latter using Thrift – N.B. that [Thrift can generate Node.js bindings](https://github.com/apache/thrift/tree/trunk/lib/nodejs).

If I were to recommend a wrapper around `tc`, then, given the state of the µDL and ATC projects, then I'd recommend the latter. However, you're not looking for a wrapper around `tc`.

@cgoldberg has already mentioned that on Linux we use `tc`. On FreeBSD we use [`ipfw`](https://en.wikipedia.org/wiki/Ipfirewall). On Mac we use [`pf`](https://en.wikipedia.org/wiki/PF_(firewall)). I'm not sure that there's a comparable tool for Windows.

You're looking for a wrapper around `tc`, `ipfw`, and `pf`.

**Comment by soulgalore** [comment]
@phuedx thanks for clarifying. As a first step, we will need a wrapper for tc, that's prio 1 and then we can see later what we can do for the rest.

**Comment by soulgalore** [comment]
but if we can have it all, that wouldl be nice. https://github.com/tylertreat/comcast looks kind of cool.

**Comment by soulgalore** [comment]
We will use https://github.com/sitespeedio/sltc for now.

**Comment by beenanner** [comment]
Linking this here for reference, hopefully in the future we will have native support that we can leverage. https://github.com/docker/docker/issues/4763

**Comment by beenanner** [comment]
Another option for our docker container is to build our own bridge that we can apply rules upon. 

https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/
