### ISSUE TITLE
Setup correct keys for Graphite

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#901]
We haven't given the key structure any love for Graphite. They should be named after each plugin (browsertime for timing metrics, coach for .. coach and pagexray for xray metrics).

We also need to configure good default keys so we don't overload graphite with metrics as we do in 3.0. 

Also add docs for the keys we will have by default.

**Comment by beenanner** [comment]
@soulgalore I can try to work on this issue. What are your thoughts on "configure good default keys"? I can add a doc folder to 4.0 so we can document as things are cleaned up.

**Comment by soulgalore** [comment]
@beenanner yes that would be great!

>"configure good default keys"?
Sorry that was really unclear. I want us to choose just a couple of metrics that we send by default, just so we don't overload Graphite. I was thinking of rumSpeedIndex, fullyLoaded, coach speed score, number of requests per asset type and size, speedIndex (when we have it, don't know if you tried out the Docker image yet + any ideas are welcomed. Are there some metrics that you think should be there by default?

**Comment by soulgalore** [comment]
A couple of things:
<code>namespace.pageSummary.www_sitespeed_io._browsertime.statistics.timings</code> here we probably should get rid of .statistics.

<code>namespace.summary.domains</code> we do not send domain specific data per page, maybe we should do that to have the same for both summary & pageSummary.

One thing that I've missed: We don't have a solution if you want to test multiple sites within the same run. For example, I want to test two sites, but do that within the same run and namespace. The pageSummary will be fine but the summary will be for both sites. I kind of like the idea of be able to do that within the same run. In the old version you could do that in a hacky way by having one text files per site.

**Comment by soulgalore** [comment]
Ah and in the old version we also had: 
<code>namespace.summary.www_sitespeed_io</code> but it's kind of hard coded to the first URL you test on that run (if I remember correctly).

**Comment by soulgalore** [comment]
With the fix for contentTypes (thanks @beenanner for spotting that) I think we are pretty good. But hey, lets all go through them again before we release alpha1.

**Comment by soulgalore** [comment]
Nooo, it is not ok. We should fix so that summary (sitespeed_io.summary.www_expressen_se.Y) also includes origin of metrics (browsertime, pagexray, coach) so we have the exact same structure as PageXray.

**Comment by soulgalore** [comment]
It's late ... forget that comment, it works fine as it is.
