### ISSUE TITLE
Connect grafana <-> graphite

### ISSUE THREAD

**Issue by alex-moreno** [sitespeedio/sitespeed.io#904]
Hi,

I've been following a couple of instrauctions/howtos, but the actual connection between Grafana and Graphite does not seem clear. I have both containers up and running, I am able to connect to them via web, but when I try to add a new source in Grafana, I can only get errors. Is there a proxy running by default in one of the containers? Graphite does not seem to be running with CORS enabled.

Thanks in advance.

**Comment by soulgalore** [comment]
Hey @alex-moreno do you run the sitespeed.io containers? Could it be that the Graphite is behind Basic Auth? Do you have any logs, that would make it easier to check.

Best
Peter

**Comment by alex-moreno** [comment]
Hi Peter,

seems the problem is in Grafana, not Graphite. I tried the new version of
Grafana and that worked fine:

sudo docker run -d -p  3000:3000 --name grafana grafana/grafana:3.0.0-beta5

**Comment by soulgalore** [comment]
cool I'll close the issue.
