### ISSUE TITLE
Improve test setup for graphite/influxdb/grafana

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#908]
I'm going to look into setting up a docker-compose file for running these 3 services it seems on my linux machine they aren't able to talk to one another without additional work. It would be nice to just run `cd tools;docker-compose up` for development.

**Comment by soulgalore** [comment]
yes sounds good :)

**Comment by tobli** [comment]
Fixed now, thanks @beenanner!
