### ISSUE TITLE
Regarding couple questions

### ISSUE THREAD

**Issue by maximillean** [sitespeedio/sitespeed.io#909]
I set multiple urls but under grapite i can not see them as seperated timings. Timings seems like the total timigs of all urls. Can i run it with -f urls.txt and see them with seperated timings and metrics otherwise i have to run it with -u and each url with different tabname under graphite since this works with cron i have to use seperate time range for each url then it is a problem. 

Second question is can i only fetch certain metrics rather than a group to graphite like i want to fetch 10 metrics to graphite and nothing else. so it only shows those 10 metrics for each url in graphite. 

Lastly can i also send post requests? so can get the timings for post requests to like submit a form in page. 

Thanks
I apologize could not find an irc address or email to ask questions so i asked from issue line.

**Comment by soulgalore** [comment]
Hey @maximillean 
it works perfect to ask in an issue :)

It should always be possible to see timings for each specific URL. You should find them:
NAMESPACE.http.DOMAIN.PATH.timings.* can you find them?

<code>-f urls.txt</code> works fine and the summary will be for all the URLs in that file, there is no magic there. If you are testing multiple sites, you can follow this example: https://www.sitespeed.io/documentation/use-cases/#setup-the-files

There's some things you can configure to choose metrics but its not finegrained. It's better in the coming 4.0 but you can at least turn off some now:
https://www.sitespeed.io/documentation/performance-dashboard/#configure-sitespeedio-what-metrics-to-send

Best
Peter

**Comment by maximillean** [comment]
Thanks
