### ISSUE TITLE
3rd party vs 1st party for sitespeed 4.0

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#915]
For sitespeed 4.0 it would be a nice feature to be able to configure what requests are considered 1st party vs everything else which would be third party so we could present statistics around those configurations. Possible have some sort of domain whitelist or JSON file for naming a group of domains would be nice.

**Comment by soulgalore** [comment]
Yep I agree. One fat regular expression? Easiest way should be to specify what's 1st party right and then treat the rest as third party. 

What kind of metrics do you want to see? requests & size. Timings?

**Comment by beenanner** [comment]
Yeah it would be nice to possible pre-calculate these request counts, size total, etc. before sending them over to a time-series db for storage so that they wouldn't have to be calculated on the fly as is currently done in 3.x

**Comment by tobli** [comment]
Request count per domain is in by default now (total for all pages).

**Comment by soulgalore** [comment]
Only missing now is the summary in https://github.com/sitespeedio/sitespeed.io/blob/4.0/lib/plugins/coach/pagexrayAggregator.js

**Comment by soulgalore** [comment]
@beenanner you can try it out now and see if it works as you want. You need to supply a regex that categorize a URL as a firstParty, all other URLs will be third.

**Comment by beenanner** [comment]
@soulgalore look good everything seems to be working as expected. Great addition!

**Comment by beenanner** [comment]
Everything looks good to me closing this out. Thanks guys!

**Comment by soulgalore** [comment]
I will just add something in the front end  HTML.

**Comment by guifreitag** [comment]
Is there a way to provide first party regex when using url's in a separate file?

**Comment by soulgalore** [comment]
Hi @guifreitag yep that should just work out of the box? `sitespeed.io myFile.txt --firstParty ".*sitespeed.*"` but the regex is the same for all URLs.

Best
Peter
