### ISSUE TITLE
Screenshots are taken with Phantom instead of preferred headless choice

### ISSUE THREAD

**Issue by OffByNone** [sitespeedio/sitespeed.io#916]
Hello good sirs!

Phantom has a bug where it does not correctly render our pages.  I like the screenshot functionality but, it is taken with phantom even if I set the headless switch to slimer.

It would be nice if the screenshot param would work with the headless param if it is set.

**Comment by soulgalore** [comment]
Hey @OffByNone ,
lets wait for 4.0 and you can try it out, there we take screenshots using Chrome/Firefox.

Best
Peter

**Comment by OffByNone** [comment]
Thanks for the quick reply!

100% with you, as I would much rather take the screenshot in the actual browser.

4.0 looks pretty awesome.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
