### ISSUE TITLE
Scripts loaded via Lab.js reported incorrectly as blocking

### ISSUE THREAD

**Issue by colinmollenhour** [sitespeedio/sitespeed.io#92]
First of all, awesome tool!

I use [Lab.js](http://labjs.com) for loading my third-party scripts. I use `$LAB.queueScript()` and use an onload event which runs the queue a half-second _after_ onload. However, Sitespeed.io is reporting scripts loaded with this method as blocking/synchronous. Google PageSpeed on Chrome and Firefox and YSlow on Firefox all report these scripts as non-blocking. Put differently, on YSlow/Firefox I get an A for "Put Javascript at bottom" but in Sitespeed.io I get a 37 for "Load third party javascript asynchronously" and it lists Google+, Facebook and Twitter which are all loaded via `$LAB.queueScript()` as offending scripts.

I think the issue is that Lab.js may be inserting script elements into the head element and Sitespeed.io is therefore counting these as blocking scripts, but since they are loaded _after_ onload it seems to me that they should not be considered as offenders by the "Load third party javascript asynchronously" rule.

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
