### ISSUE TITLE
Send number of errors to graphite

### ISSUE THREAD

**Issue by OffByNone** [sitespeedio/sitespeed.io#922]
Right now Sitespeed keeps track of if there were any errors on the pages it loaded.  It would be nice if this could be sent to graphite so we can see this over time.

**Comment by soulgalore** [comment]
Hey @OffByNone yes, so what kind of error do you mean?
Best
Peter

**Comment by OffByNone** [comment]
Just a count of whatever shows up on the errors page in the report

**Comment by soulgalore** [comment]
So in 4.0 we haven't implemented any errors/fails yet for individual pages, but lets add that.

**Comment by OffByNone** [comment]
Thanks!

**Comment by soulgalore** [comment]
I think this better implemented by a log watcher as described in https://www.sitespeed.io/releasing-with-confidence/
