### ISSUE TITLE
Send HTTP Status code info to Graphite

### ISSUE THREAD

**Issue by OffByNone** [sitespeedio/sitespeed.io#923]
I could be wrong, but I don't believe sitespeed currently sends HTTP status codes to graphite.  It would be nice to be able to see how many of each I am getting in relation to each other and over time.

**Comment by soulgalore** [comment]
Yes, so in 4.0 we send (or you can configure to send) response codes for each asset on a page. Like X 200s and Y 301.

**Comment by OffByNone** [comment]
Nice.  Let me know when it is ready to test

**Comment by soulgalore** [comment]
Lets fix this tonight.

**Comment by soulgalore** [comment]
Think this is ok for now.
