### ISSUE TITLE
Error: No URLs to analyze

### ISSUE THREAD

**Issue by TarunGoel** [sitespeedio/sitespeed.io#936]
Hi Team,

Firstly thanks for putting together such a great tool and with the ease of using it through docker.

Need help with an error while analyzing some URLs. Please note I am operating behind proxy server and using following command to initiate analysis.

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io \
	-f mobile_url.txt \
	-d 0 \
	-b chrome \
	--seleniumServer http://127.0.0.1:4444/wd/hub \
	--gpsiKey <my API Key> \
	-v \
	-n 2 \
	--screenshot \
	--profile mobile \
	--graphiteHost 192.168.92.130
	--proxy http://proxy host IP:8080

This command gives me following error:
info: OS: 'linux 4.4.0-21-generic', Node.js: 'v4.3.2', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'
error: Couldn't fetch <URL> Error: getaddrinfo ENOTFOUND <Hostname>
error: Failed to download 0
info: Didn't get any URLs
error:  Error: No URLs to analyze
    at Object.module.exports.fineTuneUrls (/usr/lib/node_modules/sitespeed.io/lib/util/util.js:354:18)
    at /usr/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:52:12
    at fn (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:706:43
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:1209:30
    at Request._callback (/usr/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:134:7)
    at self.callback (/usr/lib/node_modules/sitespeed.io/node_modules/request/request.js:199:22)

But the same command work fine as I connect to direct internet (just by removing --proxy).

Please help in identifying what is an issue here.

**Comment by soulgalore** [comment]
Hi @TarunGoel and thanks for the kind words.

The proxy functionality hasn't got so much love lately. Could it be that the proxy isn't visible for the Docker container? Can you turn on verbose logging and see if you get more info?

Best
Peter

**Comment by TarunGoel** [comment]
Seems you are right, this issue may be related proxy isn't visible to Docker container itself. Will try to work on this once I will be testing again in proxy enabled environment.

**Comment by TarunGoel** [comment]
@soulgalore this is resolved. It was an issue issue with docker container visibility to proxy configuration.

Following can be useful in setting up docker container - https://docs.docker.com/engine/admin/systemd/
