### ISSUE TITLE
Issue: while parsing results from gpsi (TypeError: Cannot read property 'length' of undefined at Object.module.exports.gpsiReplacers

### ISSUE THREAD

**Issue by TarunGoel** [sitespeedio/sitespeed.io#937]
Hi,

Working on to execute some URL's through YSLOW, GSPI, and WPT

Used Command -
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io \
	-f mobile_url.txt \
	-d 0 \
	--gpsiKey <GPSI Key> \
	-v \
	-n 2 \
	--screenshot \
	--profile mobile \
	--graphiteHost 192.168.92.130 \
	--viewPort 400x300 \
	--name "Test Name" \
	--wptHost www.webpagetest.org \
	--wptKey <WPT Key>

Error : 
![image](https://cloud.githubusercontent.com/assets/8359602/15315804/6c488f8a-1c37-11e6-8bf5-ca35fb57c522.png)

Please help if I am doing something wrong here.

**Comment by soulgalore** [comment]
Hi @TarunGoel 
hmm strange. You supply a GPSI-key right? I'll have a look later this week.

Best
Peter

**Comment by TarunGoel** [comment]
Thanks @soulgalore for taking this up.
Yes I am supplying GPSI-key. I verified this again today and same error. However in results folder GPSI data is getting accumulated in form of JSON response.

But the report generation is getting failed for overall process. Please let me know if any further information is required to replicate this @ ur end.

**Comment by jobetdelima** [comment]
Hi @TarunGoel and @soulgalore, I'm running into the same error doing the same thing. Might even be simpler as my command just looks like "sitespeedio.io -u my_site_url --gpsiKey my_key.

I was hoping you've made progress on this issue and would be able to share what you've done.

Thanks

**Comment by soulgalore** [comment]
Hey @jobetdelima do you run the latest alpha or from master? Did a fix in #1110 that isn't in the alpha. Is there any documentation for the JSON returned by GPSI? The thing with #1110 was that one rule was missing a summary.

Best
Peter

**Comment by jobetdelima** [comment]
Hi @soulgalore,

I'm running whatever version I got when I did "npm install -g sitespeed.io" yesterday. 

If you could let me know how to try a different version that has your fix, I would be happy to be try it.

Thanks!

**Comment by soulgalore** [comment]
fixed
