### ISSUE TITLE
Remove hardcoded list of assets from sitespeed 4.0 contentType pagexrayAggregator.js

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#942]
Looks like we have a hardcoded list here: https://github.com/sitespeedio/sitespeed.io/blob/4.0/lib/plugins/coach/pagexrayAggregator.js#L7

We probably want to remove that  so we can have all the other content type goodness that Pagexray can provide and any new ones that could be added in the future.
https://github.com/sitespeedio/pagexray/blob/master/lib/util.js#L4 

Also I wonder if we should let those exist under the contentTypes key so the individual content types are separate from the higher level metrics (i.e. total requests, first party, third party, etc).

**Comment by soulgalore** [comment]
Yes, so I wonder what I was thinking when I did this, lets get all the keys as you said. And also put them other contentTypes, that will be much cleaner, good idea!

**Comment by soulgalore** [comment]
@beenanner I'll fix this tonight + add so we send response codes also by default, that's kind of neat to have.
