### ISSUE TITLE
Upgrade from 3.x to 4.0 instructions

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#945]
We need to have instructions how to upgrade from 3.x to 4.0.

**Comment by beenanner** [comment]
A table with 3.x to 4.0 mappings would be nice to put in the docs. We can flag if something has been deprecated/add/etc as well. I'll try to work on that tomorrow night.

**Comment by soulgalore** [comment]
Sounds great! I talked to a couple of companies and for the changes in keys in Graphite, it doesn't matter, they will just setup a new instance. But explaining that the key structure has changed, that is good!
