### ISSUE TITLE
Docker images and WPT

### ISSUE THREAD

**Issue by bartekl** [sitespeedio/sitespeed.io#951]
Hi,

I'm using various docker images (3.6.0, 3.9.1, 3.10.0, 3.11.0, 3.11.5) and none of them seem to support --wptKey option correctly. Every time I try to run a test I get:

`root@sitespeed:~# docker run --privileged --rm -v /data/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -f url.list -r /tmp/ --graphiteHost 162.243.232.215 --seleniumServer http://127.0.0.1:4444/wd/hub --wptHost www.webpagetest.org -–wptKey 'KEY' -v
Tue May 24 02:07:30 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 49.0.2623.75
Mozilla Firefox 45.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.13.0-85-generic', Node.js: 'v4.3.2', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.7.0_95', browsertime: '0.12.2'
info: Will analyze 3 pages
info: Running YSlow for http://www.hiddensite.com [phantomjs]
info: Running YSlow for http://www.hiddensite.com/c/Cameras [phantomjs]
info: Running YSlow for http://www.hiddensite.com/ADICA1DXM2KPFC.html [phantomjs]
verbose: Done processing url in yslow: http://www.hiddensite.com
verbose: Done processing url in yslow: http://www.hiddensite.com/c/Close
verbose: Done processing url in yslow: http://www.hiddensite.com/ADICA1DXM2KPFC.html
info: Running WebPageTest http://www.hiddensite.com pollResults=10, timeout=600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Dulles:Chrome, connectivity=Cable, video=true
info: Running WebPageTest http://www.hiddensite.com/c/Cameras pollResults=10, timeout=600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Dulles:Chrome, connectivity=Cable, video=true
info: Running WebPageTest http://www.hiddensite.com/ADICA1DXM2KPFC.html pollResults=10, timeout=600, firstViewOnly=false, runs=3, private=true, aftRenderingTime=true, location=Dulles:Chrome, connectivity=Cable, video=true
verbose: Got the following from WebPageTest:undefined
error: WebPageTest couldn't fetch info for url http://www.hiddensite.com{ statusCode: 400,
  statusText: 'An error occurred processing your request (missing API key).  If you do not have an API key assigned you can request one at http://www.webpagetest.org/getkey.php' }
error: Error running WebPageTest: { statusCode: 400,
  statusText: 'An error occurred processing your request (missing API key).  If you do not have an API key assigned you can request one at http://www.webpagetest.org/getkey.php' }
verbose: Got the following from WebPageTest:undefined
error: WebPageTest couldn't fetch info for url http://www.hiddensite.com/ADICA1DXM2KPFC.html{ statusCode: 400,
  statusText: 'An error occurred processing your request (missing API key).  If you do not have an API key assigned you can request one at http://www.webpagetest.org/getkey.php' }
`

This only works when I pass the key in the using --wptConfig option having config like this:
{
  "key": "KEY",
}

Haven't checked not dockerized sitespeed, but I can see there were similar issues (i.e. https://github.com/sitespeedio/sitespeed.io/issues/588)

**Comment by soulgalore** [comment]
Hey @bartekl pretty sure it works because we have it up and running with Docker for https://dashboard.sitespeed.io/dashboard/db/using-webpagetest 

It seems to be the cli options, it's not standard dashes before the wptKey in your example try it again with <pre>--wptKey</pre> 

Could it be that it's wrong somewhere in the docs + copy/paste?

Best
Peter

**Comment by bartekl** [comment]
Hey @soulgalore , Sorry for late reply, forgot to get back to you. It seems you were right and it must have been copy paste issue, but I cannot  tell you which site exacltly contains incorrect characters (it could be also that I got it from other place than official documentation, like an issue report).
Thanks for your help.
