### ISSUE TITLE
CloudFlare domain lookups end up in SSL error

### ISSUE THREAD

**Issue by frdmn** [sitespeedio/sitespeed.io#953]
error: Error from the crawl: javax.net.ssl.SSLException: Received fatal alert: internal_error

When trying to crawl to `https://frd.mn` or `https://blog.frd.mn`.

Mac OS X 10.11.4

**Comment by soulgalore** [comment]
Hi @frdmn 
ah ok, so in the old (well current) we use Java crawler and I guess there different configs you can do for the SSL, I don't have it in my head. The good news in 4.0 (we got an early alpha out) we skipped Java so I think it will work smooth there. However the alpha(!) is not ready for production, hopefully the beta will be there in June.

Best
Peter

**Comment by frdmn** [comment]
Alright! Thanks for the quick response, Peter!

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
