### ISSUE TITLE
Pages tab: HAR waterfall graph will overwrite previous page results when URL has a # sign 

### ISSUE THREAD

**Issue by afong** [sitespeedio/sitespeed.io#958]
Run sitespeed with multiple URLs with a "#" sign in them, such as:
https://www.sigfig.com/site/#/tour
https://www.sigfig.com/site/#/pricing

Result:
When the results are written, it will overwrite the earlier page results, because it gives them the same name:
info: Wrote file s-www_sigfig_com-site-.html
info: Wrote file s-www_sigfig_com-site-.html

Expected:
It should give each result a unique name, even when the URL has a # sign in it.

**Comment by soulgalore** [comment]
Hey @afong 
thanks for reporting!  This has been up before but I didn't find the issue. 

We have decided to treat # as the same page as it should be only help the browser which content that browser should scroll to. I know there's been ajax solutions to load different content but today there's fix for that to use pushState to change the URL it's supported for almost every  browser: http://caniuse.com/#search=pushstate. 

Best
Peter

**Comment by lyio** [comment]
I think @afong is testing an SPA and wants to test different routes within that application. So it is actually not the same page.

**Comment by soulgalore** [comment]
yep but I think the SPA should change the URL :) 

I think measuring SPA should be done with the coming 4.0, then you can access a page first and then measure the page you want to hit + you probably want to add your own userTimings and configure when to end the test. Lets see if we can do some docs on that.

**Comment by danut-iosif** [comment]
I'm being hit by the same issue, as the test URLs that I've tried all feature a /#/ in the middle.

@soulgalore, what would a status be on this? Any way for me to monkey-patch this?

Thank you!

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
