### ISSUE TITLE
Custom scripts not run

### ISSUE THREAD

**Issue by lyio** [sitespeedio/sitespeed.io#959]
I am executing `sitespeed.io -f sitespeed/sites.txt --budget timings.json --custom-scripts sitespeed\script\ -b chrome` 

where `sitespeed\script\` contains a single file `loginLoaded.js` with the contents: 

```javascript
var p = window.performance;
var l = p.getEntriesByName("untilLoginLoaded")[0];

return l.duration;
```

This is with  `info: OS: 'win32 10.0.10586', Node.js: 'v6.0.0', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.8.0_91', browsertime: '0.12.2'`

From what I understood, I should find *loginLoaded* somewhere in the details page.

Replacing the contents with the example code from the documention also has no effect.

Is there a way to make sure that custom scripts are run? What am I missing?

**Comment by soulgalore** [comment]
Hey @lyio 
hmm at first glance it looks ok, could it be that we don't show it on details and only send that to Graphite? I'll check the code, been focusing on 4.0 and forgot how everything works in 3.x :/

Best
Peter

**Comment by lyio** [comment]
@soulgalore is there a way to get at these values without setting up Graphite/Grafana? I don't really know my way around this codebase, maybe you could point me at an entry point for the custom scripts.

**Comment by soulgalore** [comment]
I think it could be that I've missed outputting this in the HTML, I haven't looked, sorry, been focusing on 4.0. I can show you tonight, I'll update the issue.

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
