### ISSUE TITLE
Error : WebPageTest couldn't get HAR ({})

### ISSUE THREAD

**Issue by SanjeebJena** [sitespeedio/sitespeed.io#975]
While running WPT from sitespeed.io
sitespeed.io.cmd -u value -p  value -m 1 --profile mobile --noYslow --wptConfig value.json --wptHost http://localhost:value/ --html --storeJson

WebPageTest is running successfully and results are getting generated at its resultsdirectory, 
but from sitespeed.io, it's getting error out.
Error : 
WebPageTest couldn't get HAR ({})
[31merror[39m: Error running WebPageTest: [SyntaxError: Unexpected end of input]
.....\Roaming\npm\node_modules\sitespeed.io\lib\util\util.js:281
        return _**pageData.webpagetest.wpt[0**_].response.data.testUrl;
                                          ^

TypeError: Cannot read property 'response' of undefined

I think the proxy is not the cause here, What else can it be ?

**Comment by soulgalore** [comment]
Hey @SanjeebJena which version are you using (3.x or 4.alpha)? Can you give me the exact configuration you are using so I can test? You can drop me an email peter [AT] soulgalore [dot] com.

Thanks!

**Comment by SanjeebJena** [comment]
Hi @soulgalore  This is the config I'm using   
'win32 6.1.7601', Node.js: 'v6.2.1', sitespeed.io: '3.11.5', PhantomJS: '2.1.1', java: '1.8.0_45', browsertime: '0.12.2'

with WPT private instance

This is the exact error I'm getting..

[31merror[39m: WebPageTest couldn't get HAR ({})
[31merror[39m: Error running WebPageTest: SyntaxError: **Unexpected end of JSON input**
    at Object.parse (native)
    at WebPageTest.apiCallback (C:\sitespeed\node_modules\sitespeed.io\node_modules\webpagetest\lib\**webpagetest.js**:192:27)
    at IncomingMessage.onEnd (C:\sitespeed\node_modules\sitespeed.io\node_modules\webpagetest\lib\webpagetest.js:123:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
C:\sitespeed\node_modules\sitespeed.io\lib\util\util.js:281
        return pageData.webpagetest.wpt[0].response.data.testUrl;

TypeError: Cannot read property **'response'** of undefined

----------------------------------------------------------
In webpagetest.js , the line that gets error out 

_else if (info.type === 'application/json') {
              data = JSON.parse(data);_

Does it need to add other MIME for JSON parsing, now for major webpages , JSON-LD being used.
Is there something to be done here ?

I sent you an mail on the above issue.

Thanks

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
