### ISSUE TITLE
Missing data in alpha v2 output

### ISSUE THREAD

**Issue by rschoessler** [sitespeedio/sitespeed.io#986]
When using the alpha2 version, I am seeing that the results HTML are missing the following:

- Coach data (no coach.summary.json file is created)
- Overall score (Summary page)
- Performance score (Summary page)
- Accessibillity score (Summary page)
- Best Practice score (Summary page)

Command used:
>node bin\sitespeed.js http://www.myurl.com

Is this expected behavior for this version?

Thanks...

**Comment by soulgalore** [comment]
Yes that's wrong, I fixed it in master earlier today but want to see if we are able to upgrade FF before we do a new release, lets see tonight.

**Comment by rschoessler** [comment]
OK, thanks @soulgalore !

**Comment by soulgalore** [comment]
I've pushed alpha.3.

**Comment by rschoessler** [comment]
Thanks again @soulgalore .  Updated and looks good this morning.
